### ISSUE TITLE
About setvars.sh setup

### ISSUE THREAD

**Issue by aiopeniot** [openvinotoolkit/openvino#10]
If the user doesn't install OpenVINO，how to set up the vars?

<INSTALL_DIR>/deployment_tools/inference_engine/bin/intel64/Release folder):
source ../../setvars.sh

Regards

**Comment by shubha-ramani** [comment]
Hello aiopeniot. setvars.sh sets environment variables with dependencies such as the correct version of Python, OpenCV, Inference Engine, OpenVX, etc...It's better that you install OpenVINO first. For instance, how would you get Inference Engine if you don't install OpenVino ? I suppose it should be possible to point to your own installation of Python and OpenCV (relative to INTEL_CVSDK_DIR) and hack the script to reflect your paths but I haven't tried this before.  Can you kindly describe why you want to do this ?

**Comment by AnastasiaKazantaeva** [comment]
Close this issue as no response. Please, create a new one or reopen this issue if the question is still actual
