### ISSUE TITLE
FakeQuantize layer, from IR to IE

### ISSUE THREAD

**Issue by piti-diablotin** [openvinotoolkit/openvino#10028]
##### System information (version)
- OpenVINO => 2021.4
- Operating System / Platform => docker openvino_data_dev
- Problem classification: Quantization

##### Detailed description
I'm currently trying to implement a new algorithm to quantize an IR model. I'm working in the `pot.py` utility tool.
I created a new quantization algorithm which is found and launched correctly.
I got an IR in the xml format which seems very fine. 

The problem is that the inference is done in float32 and not int8 despite the addition of `FakeQuantize` layers (checked with DLWorkbench runtine precision).

The [diff.tar.gz](https://github.com/openvinotoolkit/openvino/files/7971627/diff.tar.gz) archive contains 2 xml files of IR models. It seems to me that they are very similar in architecture, the `offset` attribute for `Const` layers are different but `size` are the same and the graphs contain the same layers.

The `DefaultQuantization` xml IR is correctly inferred in int8 and has a good performance increase (2 times more FPS) however the EdQuant (my implementation) has not. It is as slow as with float32 model or even worse sometimes due to FQ overhead.

Currently my implementation does not do anything, it fills the parameters of the `FakeQuantize` layers with positive random numbers around 0 for *low* input/output and around 250 for *high* input/output with 256 levels. I plan to correctly set the bounds later on when I get a model that runs in int8, but maybe that's a bad idea ? How FQ layer bounds affect the IE to infer in low precision int8 ?

I'm looking for any help on the requirements for the IE to indeed infer with low precision int8 numbers. All my tests are performed on CPU only (target device) and tested on i7-1185G7 and Xeon Gold 6258 both with AVX-512 AVX-512VNNI and DLBoost

Thanks for any help you can provide !

**Comment by ilyachur** [comment]
I don't see any big difference between these IRs. @eshoguli @dmitry-gorokhov maybe could you advise.

**Comment by piti-diablotin** [comment]
Thanks for your reply.

The only difference I have in mind  is the `.bin` file. Do `Const` values matter for low precision inference triggering ?

**Comment by jgespino** [comment]
Hi @piti-diablotin Apologies for the delay from our side, I am reaching out to my peers for additional assistance.

Ref. 80668

**Comment by jgespino** [comment]
@piti-diablotin Would you mind sharing the quantized IR model (both .xml and .bin files)?

**Comment by piti-diablotin** [comment]
Hi, Sorry I'm no longer working on this topic. I don't have the files anymore. Sorry.

**Comment by jgespino** [comment]
@piti-diablotin I understand and appreciate your response. Feel free to start a new discussion if you need any help in the future.
