### ISSUE TITLE
Can openvino transform tf model to IR with NHWC format?

### ISSUE THREAD

**Issue by panshaohua** [openvinotoolkit/openvino#1022]
I found some layer reorder from NCHW to NHWC when openvino inference optimizing INT8 model. So I want transform tf-model or onnx-model to NHWC format IR.

**Comment by maxlytkin** [comment]
Hi @panshaohua 
For TensorFlow model conversion you can take a look at Model Optimizer parameter "--disable_nhwc_to_nchw" that disables default translation from NHWC to NCHW.
As per https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html#tensorflow_specific_conversion_params

Hope this helps.
Best regards, Max.

**Comment by avitial** [comment]
Closing this issue, I hope previous response was sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
