### ISSUE TITLE
[Bug] Openvino Link Failed (With TorchScript)

### ISSUE THREAD

**Issue by cxz1418** [openvinotoolkit/openvino#10289]
##### System information (version)

- OpenVINO => 2021.3
- Operating System / Platform => ubuntu 20.4
- Compiler => CMake
- Problem classification: Lib Compile
- Framework: torchscript(1.6, 1.10) + openvino

##### Detailed description
**Hello~, I try to use Torchscript and Openvino at the same time, but if I load both libs at the same time, I get an error message like this (undefined reference)**
![image](https://user-images.githubusercontent.com/11434363/153548994-296c385e-8ec0-4e58-b998-17cc3ee526e8.png)

![image](https://user-images.githubusercontent.com/11434363/153548927-e1f53db8-b782-49ae-954b-7f9be408e1d3.png)

**When linking only Openvino single, it works well as follows.**
![image](https://user-images.githubusercontent.com/11434363/153549174-21aaa637-ed21-41ba-a767-5e50395d58d6.png)

![image](https://user-images.githubusercontent.com/11434363/153549111-b56db958-764e-484f-bc71-cccdd19d6386.png)

What am I missing?

**Comment by dkurt** [comment]
Hi! Can you try the following approach?
```cmake
find_package(InferenceEngine REQUIRED)
find_package(ngraph REQUIRED)

target_link_libraries(CMake_test PRIVATE IE::inference_engine ${NGRAPH_LIBRARIES}
```

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
