### ISSUE TITLE
Wrong path to ngraph in setupvars.{sh.bat}

### ISSUE THREAD

**Issue by g3n35i5** [openvinotoolkit/openvino#1029]
I think

https://github.com/openvinotoolkit/openvino/blob/2fe9b1523058e282ad374db7dc1b3538c7d2dd27/scripts/setupvars/setupvars.sh#L67-L69

should be

```bash
if [ -e $INSTALLDIR/ngraph ]; then
    export LD_LIBRARY_PATH=$INSTALLDIR/lib:$LD_LIBRARY_PATH
    export ngraph_DIR=$INSTALLDIR/cmake
fi
```

since the ngraph module has been moved to the project root. Maybe one should also think about replacing the `setupvars.sh` script with a proper cmake structure.

**Comment by ilya-lavrenov** [comment]
CC @tomdol @artanokhov

**Comment by artanokhov** [comment]
This is not an issue in setupvars script, because we have different layout for 'make install' artifacts and product layout. So I think right way to fix it - align these layouts.

**Comment by tomdol** [comment]
I thought ngraph's component prefix should always (and by default) be set to `deployment_tools/ngraph`. This is the layout UEP in ONNXRuntime depends on. I'm not sure what the layout should be but in case this is a subject to change, please notify the UEP team.

**Comment by ilya-lavrenov** [comment]
> I thought ngraph's component prefix should always (and by default) be set to deployment_tools/ngraph

See https://github.com/openvinotoolkit/openvino/blob/master/CMakeLists.txt#L108. When artifacts are installed via `make install`, this prefix is still ignored.. @azhogov @asuhov  what prevents us from uncommenting this line?

**Comment by artanokhov** [comment]
Not actual anymore after we aligned 'make install' and product public layout.

Please check it out with latest product state :)
