### ISSUE TITLE
inference engine R5 compilation failure with Intel C++ compiler 19 on Windows

### ISSUE THREAD

**Issue by burialpine** [openvinotoolkit/openvino#103]
OS: Windows 10
SW: Visual studio 2015 + Intel C++ compiler 19.0 Update 2

Steps:
1, Download R5 release source code as zip file and unzip
2, Download ade as zip file and unzip to thirdparty/ade
3, mkdir build and cd build
4, cmake -G "Visual Studio 14 2015 Win64" -T "Intel C++ Compiler 19.0" -DCMAKE_BUILD_TYPE=Release -DICCLIB="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\compiler\lib" -DTHREADING=TBB ..

cmake is successful
5, Open the generated sln in Visual Studio, choose x64 and release, then build
build failed with below message

Error: reinterpret_cast cannot cast away const or other type qualifiers	fluid	<dldt_root>\inference-engine\thirdparty\fluid\modules\gapi\include\opencv2\gapi\util\variant.hpp	343

**Comment by shubha-ramani** [comment]
Dear burialpine, can you kindly try one thing for me ?
Can you first execute eployment_tools\inference_engine\samples\create_msvc2017_solution.bat

Doing so will create a VS *.sln file in 
C:\Users\johndoe\Documents\Intel\OpenVINO\inference_engine_samples_2017

Pull up that *.sln file and rebuild. 

Please post your progress here.

Thanks for using OpenVino !

Shubha

**Comment by burialpine** [comment]
Dear Shubha
I am not compiling OpenVINO samples. I am trying to compile inference engine runtime and plugin libraries.

**Comment by shubha-ramani** [comment]
got it burialpine. Are you following a README for this ? If so, can you point me to which one you're following ?

**Comment by burialpine** [comment]
I am referring to 
https://github.com/opencv/dldt/blob/2018/inference-engine/README.md
Section "Build on Windows* Systems"

As for my detailed steps, i have described in my original question.

**Comment by shubha-ramani** [comment]
Dear burialpine: 

I am attempting to reproduce your issue now. I'm using VS 2017 however, hopefully it doesn't make a difference.  OpenVino validation occurs primarily on VS 2017 so it's recommended that customers use VS 2017 also (Community Edition is free so why not ?)

I could not reproduce your particular issue. Here is what I found, however.  The  Inference Engine run-time build process relies on **wget**.  If you don't have the wget executable and its dependencies in your Windows PATH, then the build process will fail with some cmake downloading error. wget Windows has some DLL dependencies also. You can download all the wget stuff you need from this website :
[http://gnuwin32.sourceforge.net/packages/wget.htm](http://gnuwin32.sourceforge.net/packages/wget.htm)

The exact command-line I used is similar to yours, except of course I used VS 2017:

> cmake -G "Visual Studio 15 2017 Win64" -T "Intel C++ Compiler 19.0" -DCMAKE_BUILD_TYPE=Release -DICCLIB="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\compiler\lib" -DTHREADING=TBB ..
> 
Also there is no need for this step:
2, Download ade as zip file and unzip to thirdparty/ade

I checked and thirdparty/ade is already downloaded by default:
C:\Intel\dldt\inference-engine\thirdparty\ade

Hope this helps you ! And thank you for using OpenVino !

Shubha

**Comment by burialpine** [comment]
Dear Shubha
Thanks for the info.
Are you also using R5 release?

**Comment by shubha-ramani** [comment]
Dear burialpine:
I always clone the git repo and do a "git pull" about once a week. This means I get the latest and greatest stuff. I know that i'm on R5 because I see this "git log" tag:

> commit 30594bb3099b7874f372074e6c0cc82748344435 (tag: 2018_R5)

Hope it helps. Thanks for using OpenVino !

Shubha

**Comment by burialpine** [comment]
hi, Shubha
I believe it has something to do how compiler handling reinterpret_cast
The bold line is what caused the error
```
    template<typename T, typename... Types>
    const T& get(const util::variant<Types...> &v)
    {
        const constexpr std::size_t t_index =
            util::type_list_index<T, Types...>::value;

        if (v.index() == t_index)
            **return reinterpret_cast<const T&>(v.memory);**
        else
            throw_error(bad_variant_access());
    }
```
It is in file
inference-engine\thirdparty\fluid\modules\gapi\include\opencv2\gapi\util\variant.hpp

I worked around by pointing fluid project to use VC compiler, others still using Intel compiler.
I  am not sure why this didn't happen on your side, maybe because you already have fluid.lib built?

**Comment by shubha-ramani** [comment]
Dearest burialpine,

No special build is going on here. I cloned the git repo from scratch to reproduce your issue. I use the same git repo out here that everyone else does.

My guess is that you missed a step in the README which you yourself pointed me to. For instance, did you do these steps ?

> cd dldt/inference-engine
git submodule init
git submodule update --recursive
> 

The other possibility (as I aforementioned) is that somehow your cmake process got messed up - perhaps because the downloading over the Internet didn't succeed ? 

Thanks for using Open Source OpenVIno !

Shubha

**Comment by alalek** [comment]
@burialpine Can try workaround similar to this: https://github.com/opencv/opencv/pull/14144 (the same file, but different repository) ?

**Comment by burialpine** [comment]
@alalek Thanks, this solves my problem.

**Comment by ilyachur** [comment]
@burialpine can I ask you try to use the last OpenVINO master?
I hope the issue should be resolved.

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
