### ISSUE TITLE
[ERROR] ... Cannot find reader for model format: xml and read the model... Please check that reader library exists in your PATH

### ISSUE THREAD

**Issue by jhonrputra** [openvinotoolkit/openvino#10337]
##### System information (version)
- OpenVINO => 2021.4
- Operating System / Platform => MacOS Catalina
- Problem classification: Model Inference

Hi,

I've downloaded Openvino Installer (offline) and successfully installed on my MacOS. I've also followed additional instructions. But when i run my script (python), i got this error:

RuntimeError: Unknown model format! Cannot find reader for model format: xml and read the model: 
.../face-detection-retail-0004.xml. Please check that reader library exists in your PATH.

I tried to find any solutions that related to this error and found that probably this is related with inference_engine.so. I tried to look up the file in /opt/intel/openvino_2021/inference_engine/lib/intel64 folder and found this file didn't exist.

My question is: Is it normal that inference_engine.so doesn't exist considering that i've installed Openvino using OpenVino Installer (offline)?

/opt/intel/openvino_2021/inference_engine/lib/intel64 :
libAutoPlugin.so				libinference_engine_ir_reader.so		libinference_engine_transformationsd.dylib
libAutoPlugind.so				libinference_engine_ir_readerd.so		libinference_engined.dylib
libHeteroPlugin.so				libinference_engine_legacy.dylib		libmyriadPlugin.so
libHeteroPlugind.so				libinference_engine_legacyd.dylib		libmyriadPlugind.so
libMKLDNNPlugin.so				libinference_engine_lp_transformations.dylib	myriad_compile
libMKLDNNPlugind.so				libinference_engine_lp_transformationsd.dylib	myriad_perfcheck
libMultiDevicePlugin.so				libinference_engine_onnx_reader.so		pcie-ma2x8x.mvcmd
libMultiDevicePlugind.so			libinference_engine_onnx_readerd.so		plugins.xml
libinference_engine.dylib			libinference_engine_preproc.so			usb-ma2x8x.mvcmd
libinference_engine_c_api.dylib			libinference_engine_preprocd.so
libinference_engine_c_apid.dylib		libinference_engine_transformations.dylib

Thank you.

Regards,
Jhon R Putra

**Comment by brmarkus** [comment]
Have you followed "https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_macos.html" to install OpenVINO?
Your machine is Intel-based?
Do you have a chance to try the latest version, 2021.4.2?
Have you called "source /opt/intel/openvino_2021/bin/setupvars.sh" to let certain ENV variables be set?
Don't forget to call "sudo ./install_prerequisites.sh" as well.

**Comment by jhonrputra** [comment]
Hi,

I tried several time reinstalling OpenVino few days ago and finally it's working great now.

My steps:
1. Uninstall OpenVino.
2. Reinstall Phyton.
3. Install OpenVino and follow additional steps.
4. Execute my code and still got error.
5. Download updated models using model downloader.
6. Replace the models with updated models.
7. Code run perfectly.

The error message "Please check that reader library exists in your PATH." is pointing to missing library problem. But then i tried to think differently... Is it possible that caused by incompatible models? So I tried to replace the models and everything run flawlessly.

I hope this can help anyone that probably is experiencing same problem. 

Thank you for all supports.

Regards,
Jhon R Putra

**Comment by dgorissen** [comment]
Dupe of https://github.com/openvinotoolkit/openvino/issues/3325

To help future googlers. I got bitten by this when using a model from the 2022.1.0 branch alongside a 2021.4 openvino installation. Using the 2021.4.2 tag of open model zoo fixed things.

**Comment by muhammad-faizan-122** [comment]
Hi, when I load .xml model, facing the following issue.
**RuntimeError: Check 'false' failed at frontends/common/src/frontend.cpp:54: Converting input model**
code: 
```
from openvino.runtime import Core

ie = Core()
model = ie.read_model("model/best.xml")
compiled_model = ie.compile_model(model, "CPU")


input_layer_ir = compiled_model.input(0)
output_layer_ir = compiled_model.output("boxes")

```
can anyone please help me to resolve this issue?

**Comment by brmarkus** [comment]
Can you create a new Github issue for your problem, please?
Don't forget to provide details about your environment (HW and SW), like which OS-version, which Python version, which and how OpenVINO was installed, which version of YoloV5 (from which repo), how you exported it.

**Comment by yangchengxin** [comment]
> Hi, I exported openvino model from yolov5, when try to load .xml file, facing the following issue. **RuntimeError: Check 'false' failed at frontends/common/src/frontend.cpp:54: Converting input model** code:
> 
> ```
> from openvino.runtime import Core
> 
> ie = Core()
> model = ie.read_model("model/best.xml")
> compiled_model = ie.compile_model(model, "CPU")
> 
> 
> input_layer_ir = compiled_model.input(0)
> output_layer_ir = compiled_model.output("boxes")
> ```
> 
> can anyone please help me to resolve this issue?

i have the same problem as you now， have you solved this problem？please help me， thank you very much！

**Comment by jinwater88** [comment]
Exception from src/inference/src/cpp/core.cpp:95:
Exception from src/inference/src/model_reader.cpp:155:
Unable to read the model: whisper-base/openvino_tokenizer.xml Please check that model format: xml is supported and the model is correct. Available frontends: 

The compiled cpp can run perfectly on machine A, but it reports an error on machine B. Who can solve this problem? Thank you.
