### ISSUE TITLE
[Bug] InferenceEngine::details::cloneNetwork requires ngraph-based `network` object to clone

### ISSUE THREAD

**Issue by smistad** [openvinotoolkit/openvino#10344]
##### System information (version)
- OpenVINO => 2021.4.2
- Operating System / Platform => Ubuntu 18.04
- Compiler => GCC 7.5
- Problem classification: Inference
- Framework: TensorFlow (if applicable)
- Model name: Custom model

##### Detailed description

I build OpenVINO myself as part of https://github.com/smistad/FAST.

The exact same model and code works on Windows 10 and macOS 10.13.
But on Ubuntu 18.04 using CPU I get the follow error in LoadNetwork() (https://github.com/smistad/FAST/blob/master/source/FAST/Algorithms/NeuralNetwork/InferenceEngines/OpenVINOEngine.cpp#L189):

```
InferenceEngine::details::cloneNetwork requires ngraph-based `network` object to clone
```

##### Steps to reproduce

Build OpenVINO on ubuntu 18.04, read network using ReadNetwork, then use LoadNetwork on the read network. (https://github.com/smistad/FAST/blob/master/source/FAST/Algorithms/NeuralNetwork/InferenceEngines/OpenVINOEngine.cpp#L189)

**Comment by jgespino** [comment]
Hi @smistad 

I'm not familiar with FAST and how OpenVINO is integrated. Could you share your model (.pb/saved_model format and IR files) for me to reproduce the issue on OpenVINO. Feel free to share the models privately (email on my profile).

Regards,
Jesus

**Comment by ilyachur** [comment]
Hi @smistad,

Looks strange that you faced with the issue that CNNNetwork doesn't have nGraph function. As I see you are using IR v10, but IR v10 always contains nGraph.
Do you use CPU device and the same IR for all platforms?
Also could you check that here: https://github.com/smistad/FAST/blob/master/source/FAST/Algorithms/NeuralNetwork/InferenceEngines/OpenVINOEngine.cpp#L71 you have nGraph function?

**Comment by smistad** [comment]
I am running on an old CPU (Intel® Core™ i5-4460 CPU) could that be the reason?

**Comment by jgespino** [comment]
Hi @smistad 

It's possible as OpenVINO supports 6th to 12th generation Intel® Core™ processors ([system requirements](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html)). Could you test on a newer system? If you can share step-by-step instructions, I can see if the issue is present my 11th gen system.

Regards,
Jesus

**Comment by ilyachur** [comment]
It is very strange that IR v10 doesn't have function... I don't see issues in your code, could you try to use another IR?

**Comment by smistad** [comment]
Hi again

I tried running on an i7-10750H CPU on Ubuntu 20.04 and it worked. 
If this error is actually due to the old CPU i tried on, maybe the error message could be improved.

**Comment by jgespino** [comment]
Hi @smistad 

Thanks for the update, glad it's now working for you. I have created an internal ticket with the development with your feedback.

Regards,
Jesus

Ref. 81202
