### ISSUE TITLE
[Bug]Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 1).

### ISSUE THREAD

**Issue by SiChuanJay** [openvinotoolkit/openvino#10420]
##### System information (version)

hello, The ONNX model I used had five inputs and was successfully converted to the OpenVino model, but ran with an error.
![图片](https://user-images.githubusercontent.com/52130681/154217009-311c0672-85aa-4dba-b001-7b888682da0b.png)
When I change the model to an input and convert it to openvino format it is successful. I compared the structure of the two models and found that at cancat293, the input and output of the two models are the same, so why does the above problem occur?
![图片](https://user-images.githubusercontent.com/52130681/154217637-4f7be445-7456-4b9e-aaa5-5dc39a8b93c4.png)
![图片](https://user-images.githubusercontent.com/52130681/154217812-d25dc1b5-59cd-4ced-80a0-1f8821e52c41.png)

I need to solve the above problem because I found that it works better when the model has 5 inputs than when the model has only one input, hope you can help me.

**Comment by SiChuanJay** [comment]
pth: https://github.com/PeterL1n/RobustVideoMatting/releases/download/v1.0.0/rvm_mobilenetv3.pth
onnx: https://github.com/PeterL1n/RobustVideoMatting/releases/download/v1.0.0/rvm_mobilenetv3_fp32.onnx  
onnx-code: https://github.com/PeterL1n/RobustVideoMatting/tree/onnx

Thanks for your help!

**Comment by zulkifli-halim** [comment]
Hello @SiChuanJay. Please share with us the Model Optimizer command and input shapes for all 5 inputs you used to convert the model.

**Comment by SiChuanJay** [comment]
hello @zulkifli-halim thanks for your help.
![图片](https://user-images.githubusercontent.com/52130681/154399885-a67dfa02-a730-4508-97bd-1ed6e6365f45.png)

**Comment by ThreeBoxWithCode** [comment]
Hello @SiChuanJay  Have you ever run into problems like "Other Inputs are needed for Output computation" 
(The #27 question: https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=27#question-27)

**Comment by zulkifli-halim** [comment]
Hello @SiChuanJay. We are unable to run the model with benchmark_app. Please share with us the Python code you used to run the model.

**Comment by SiChuanJay** [comment]
@ThreeBoxWithCode @zulkifli-halim thank you, I have solved the problem.

**Comment by zulkifli-halim** [comment]
Closing issue.

**Comment by smohammad-de** [comment]
Hi @SiChuanJay  I'm facing the same issue. pls let me know how you solved this issue. thanks!
