### ISSUE TITLE
Error build with VS - The solution file has two projects named "docs"

### ISSUE THREAD

**Issue by Bleach665** [openvinotoolkit/openvino#1045]
Win 10, SV 2017, CMake 3.18. Bug reproduced on OpenVINO rev 3417004e6d07a58ac222d5aba7bc45ac34676d32 and ae9e0510f008220a297130c45e30bfc7fcf27b04.

Error building OpenVINO using `msbuild`:
````
0>E:\Lib_prebuild\OpenVino\prebuild\OpenVINO.sln : Solution file error MSB5004: The solution file has two projects
        named "docs".

Build FAILED.
````

**Comment by ilya-lavrenov** [comment]
@Bleach665 do you know which projects contains such targets?

**Comment by Bleach665** [comment]
@ilya-lavrenov No, I didnt investigate this, just removed 'docs' project from VS solution to make success build.

**Comment by jgespino** [comment]
@Bleach665 

I did not see this issue when building from master yesterday (commit d9927a9f357254d05788920da5c0285d67aa7f26). Feel free to re-open the issue if you run into this issue again.

Regards,
Jesus
