### ISSUE TITLE
Error build with VS - libprotobuf.lib link error 

### ISSUE THREAD

**Issue by Bleach665** [openvinotoolkit/openvino#1046]
Win 10, SV 2017, CMake 3.18, OpenVINO rev ae9e0510f008220a297130c45e30bfc7fcf27b04.

Error building OpenVINO using `msbuild OpenVINO.sln /m /p:configuration=debug`:
````
"E:\Lib_prebuild\OpenVino\prebuild\OpenVINO.sln" (default target) (1) ->
       "E:\Lib_prebuild\OpenVino\prebuild\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
       "E:\Lib_prebuild\OpenVino\prebuild\ngraph\src\ngraph\frontend\onnx_import\onnx_importer.vcxproj.metaproj" (defau
       lt target) (58) ->
       "E:\Lib_prebuild\OpenVino\prebuild\ngraph\src\ngraph\frontend\onnx_import\onnx_importer.vcxproj" (default target
       ) (107) ->
       (Link target) ->
         LINK : fatal error LNK1104: cannot open file '..\..\..\..\protobuf\lib\libprotobuf.lib' [E:\Lib_prebuild\OpenV
       ino\prebuild\ngraph\src\ngraph\frontend\onnx_import\onnx_importer.vcxproj]
````

I think this is because in debug mode linked lib filename (`..\..\..\..\protobuf\lib\libprotobuf.lib`) must be with the `d` suffix.
File `libprotobufd.lib` exist on build folder.

**Comment by Bleach665** [comment]
Also `install.vcxproj` copied debug and release bin files to one dir `OpenVino install dir\deployment_tools\inference_engine\bin\intel64\Release`. Same with lib, debug and release lib copied to one folder `OpenVino install dir\build_x64\deployment_tools\inference_engine\lib\intel64\Release`.

**Comment by Bleach665** [comment]
Also something wrong with output CMake configuration `OpenVino_install_dir\deployment_tools\inference_engine\share`. Although perhaps the problem is on the side of OpenCV. 
In OpenCV CMake GUI i set `InferenceEngine_DIR` to `OpenVino_install_dir\deployment_tools\inference_engine\share`. After configuring IE Release library (IE_C_API_RELEASE_LIBRARY, IE_LEGACY_RELEASE_LIBRARY, IE_RELEASE_LIBRARY) were set to the correct value like `OpenVino_install_dir/deployment_tools/inference_engine/lib/intel64/Release/inference_engine.lib`, but IE Debug library entry (IE_C_API_DEBUG_LIBRARY, IE_LEGACY_DEBUG_LIBRARY, IE_DEBUG_LIBRARY) remained `...-NOTFOUND`.

**Comment by Bleach665** [comment]
3. `install.vcxproj` dont copy this
````
format_readerd.dll
inference_engine_ir_readerd.dll
inference_engine_onnx_readerd.dll
interpreter_backendd.dll
ngraph_backendd.dll
ngraphd.dll
onnx_importerd.dll
opencv_c_wraperd.dll
template_extensiond.dll
````
files to `CMAKE_INSTALL_PREFIX` dir. 
Is that how it should be? In my opinion, they should be copied there.

**Comment by ilya-lavrenov** [comment]
@tomdol

**Comment by tomdol** [comment]
This should be fixed in https://github.com/openvinotoolkit/openvino/pull/687

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issue was solved. Closing it. Feel free to reopen it or create a new one.
