### ISSUE TITLE
ubuntu 18.04 int8 GPU is slow then float32 GPU and int8 CPU

### ISSUE THREAD

**Issue by tangtang666** [openvinotoolkit/openvino#10464]
##### System information (version)

- OpenVINO => 2020.4
- Operating System / Platform => Ubuntu 18.04
- Compiler => cmake
- Problem classification: Model Conversion
- Framework: onnx (if applicable)
- Model name: YoloV5 (if applicable)

I have test in GPU UHD630 and GPU UHD600,the int8 gpu model is slow then float32 gpu and int8 cpu.

```
./benchmark_app -m yolov5m_v4_int8_cpu.xml -nireq 1 -nstreams 1 -b 1 -d GPU
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine: 
        IE version ......... 2021.4.2
        Build ........... 2021.4.2-3974-e2a469a3450-releases/2021/4
[ INFO ] Device info: 
        GPU
        clDNNPlugin version ......... 2021.4.2
        Build ........... 2021.4.2-3974-e2a469a3450-releases/2021/4

[Step 3/11] Setting device configuration
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 26.84 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size was changed to: 1
[Step 6/11] Configuring input of the model
Network inputs:
    images : U8 / NCHW
Network outputs:
    530 : FP32 / NCDHW
    544 : FP32 / NCDHW
    output : FP32 / NCDHW
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 19035.07 ms
[Step 8/11] Setting optimal runtime parameters
[Step 9/11] Creating infer requests and filling input blobs with images
[ INFO ] Network input 'images' precision U8, dimensions (NCHW): 1 3 640 640 
[ WARNING ] No input files were given: all inputs will be filled with random values!
[ INFO ] Infer Request 0 filling
[ INFO ] Fill input 'images' with random values (image is expected)
[Step 10/11] Measuring performance (Start inference asynchronously, 1 inference requests using 1 streams for GPU, limits: 60000 ms duration)
[ INFO ] First inference took 203.04 ms

[Step 11/11] Dumping statistics report
Count:      302 iterations
Duration:   60307.60 ms
Latency:    199.39 ms
Throughput: 5.01 FPS

```

```
./benchmark_app -m yolov5m_v4_int8_cpu.xml -nireq 1 -nstreams 1 -b 1 -d CPU
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine: 
        IE version ......... 2021.4.2
        Build ........... 2021.4.2-3974-e2a469a3450-releases/2021/4
[ INFO ] Device info: 
        CPU
        MKLDNNPlugin version ......... 2021.4.2
        Build ........... 2021.4.2-3974-e2a469a3450-releases/2021/4

[Step 3/11] Setting device configuration
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 38.94 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size was changed to: 1
[Step 6/11] Configuring input of the model
Network inputs:
    images : U8 / NCHW
Network outputs:
    530 : FP32 / NCDHW
    544 : FP32 / NCDHW
    output : FP32 / NCDHW
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 229.79 ms
[Step 8/11] Setting optimal runtime parameters
[Step 9/11] Creating infer requests and filling input blobs with images
[ INFO ] Network input 'images' precision U8, dimensions (NCHW): 1 3 640 640 
[ WARNING ] No input files were given: all inputs will be filled with random values!
[ INFO ] Infer Request 0 filling
[ INFO ] Fill input 'images' with random values (image is expected)
[Step 10/11] Measuring performance (Start inference asynchronously, 1 inference requests using 1 streams for CPU, limits: 60000 ms duration)
[ INFO ] First inference took 88.03 ms

[Step 11/11] Dumping statistics report
Count:      732 iterations
Duration:   60096.76 ms
Latency:    81.40 ms
Throughput: 12.18 FPS

```

**Comment by Iffa-Meah** [comment]
@tangtang666 ,

first and foremost, please provide these: 

1. The source of your YOLOv5 model? Did you get it from the [Ultralytic GitHub](https://github.com/ultralytics/yolov5)?
2. Your conversion & optimization commands
3. Model files

**Comment by tangtang666** [comment]
> @tangtang666 ,
> 
> first and foremost, please provide these:
> 
> 1. The source of your YOLOv5 model? Did you get it from the [Ultralytic GitHub](https://github.com/ultralytics/yolov5)?
> 2. Your conversion & optimization commands
> 3. Model files
Thanks.
1. Yeah,I get it from Ultralytic GitHub,but i checkout to V4.0 tag,and use model from https://api.github.com/repos/ultralytics/yolov5/releases/tags/v4.0.
2. I ues the mo_onnx.py conver model,then use pot to optimization int8 model(pot -c yolov5m_v4_int8_simple_mode_cpu.json).
3. [file google link](https://drive.google.com/file/d/1-sJSEfKIMZcGrP0-GjHQZoJJeptAZx_k/view?usp=sharing)
├── yolov5m.bin
├── yolov5m.mapping
├── yolov5m.onnx
├── yolov5m.pt
├── yolov5m_v4_int8_cpu.bin
├── yolov5m_v4_int8_cpu.mapping
├── yolov5m_v4_int8_cpu.xml
├── yolov5m_v4_int8_simple_mode_cpu.json
└── yolov5m.xml

[](url)

**Comment by Iffa-Meah** [comment]
@tangtang666 ,

I had requested access to your file. You need to approve it first.

![image](https://user-images.githubusercontent.com/79643476/154648823-0d3c6b69-b782-4968-b277-5c7ba88d3d98.png)

**Comment by tangtang666** [comment]
Sorry, you can access now. I changed my permission.

**Comment by tangtang666** [comment]
> @tangtang666 ,
> 
> I had requested access to your file. You need to approve it first.
> 
> ![image](https://user-images.githubusercontent.com/79643476/154648823-0d3c6b69-b782-4968-b277-5c7ba88d3d98.png)

Sorry, you can access now. I changed my permission.

**Comment by vladimir-paramuzov** [comment]
@tangtang666 UHD630 and UHD600 graphics don't have HW acceleration for int8 execution (dp4a instruction), thus the quantized model is actually executed in original FP precision (i.e. if you take FP32 IR for quantization, then FP32 will be used by the plugin for such case). And since the quantized model has additional operations (FakeQuantize) comparing to original floating point model, the performance may be a bit slower.

**Comment by tangtang666** [comment]
> 

Thanks,Now i know it,I need to use more than 11 generations of CPU if i want to use int8 gpu model。
