### ISSUE TITLE
Unable to run converted ssd_mobilenet_v2_coco

### ISSUE THREAD

**Issue by nikogamulin** [openvinotoolkit/openvino#105]
After downloading the ssd_mobilenet_v2_coco from Tensorflow detection model zoo,

I ran the following command to convert the model: 
`python3 mo_tf.py --input_model ~/ssd_mobilenet_v2_coco/frozen_inference_graph.pb --tensorflow_use_custom_operations_config extensions/front/tf/ssd_v2_support.json --tensorflow_object_detection_api_pipeline_config ~/ssd_mobilenet_v2_coco/pipeline.config --data_type FP16`

and got the following result:
```
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/niko/ssd_mobilenet_v2_coco/frozen_inference_graph.pb
	- Path for generated IR: 	/home/niko/intel/computer_vision_sdk_2018.5.455/deployment_tools/model_optimizer/.
	- IR output name: 	frozen_inference_graph
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP16
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Offload unsupported operations: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	/home/niko/ssd_mobilenet_v2_coco/pipeline.config
	- Operations to offload: 	None
	- Patterns to offload: 	None
	- Use the config file: 	/home/niko/intel/computer_vision_sdk_2018.5.455/deployment_tools/model_optimizer/extensions/front/tf/ssd_v2_support.json
Model Optimizer version: 	1.5.12.49d067a0
The Preprocessor block has been removed. Only nodes performing mean value subtraction and scaling (if applicable) are kept.

[ SUCCESS ] Generated IR model.
[ SUCCESS ] XML file: /home/niko/intel/computer_vision_sdk_2018.5.455/deployment_tools/model_optimizer/./frozen_inference_graph.xml
[ SUCCESS ] BIN file: /home/niko/intel/computer_vision_sdk_2018.5.455/deployment_tools/model_optimizer/./frozen_inference_graph.bin
[ SUCCESS ] Total execution time: 165.68 seconds.
```

Upon implementing the model in the code, however, it didin't detect any object at all.

The part of the code for object detection is the following:

```
from openvino.inference_engine import IENetwork, IEPlugin

# Load the model

# Specify target device
plugin = IEPlugin(device='MYRIAD')

logger.info("Reading IR...")
net = IENetwork.from_ir(model='models/mobilenet-ssd/FP16/ssd_mobilenet_v2_coco.xml',
                        weights='models/mobilenet-ssd/FP16/ssd_mobilenet_v2_coco.bin')

input_blob = next(iter(net.inputs))
out_blob = next(iter(net.outputs))
logger.info("Loading IR to the plugin...")
exec_net = plugin.load(network=net, num_requests=2)
# Read and pre-process input image
net_n, net_c, net_h, net_w = net.inputs[input_blob].shape
logger.info(
    "net.inpute.shape(n, c, h, w):{}".format(net.inputs[input_blob].shape))
del net

def predict(frame, exec_net, w, h, input_blob, out_blob, cur_request_id, next_request_id, log=None):
    predictions = []
    try:
        inf_start = timer()
        # Prepare input blob and perform an inference
        blob = preprocess_image(frame, w, h)
        exec_net.start_async(
            request_id=next_request_id, inputs={input_blob: blob})
        if exec_net.requests[cur_request_id].wait(-1) == 0:
            inf_end = timer()
            det_time = inf_end - inf_start

            # Parse detection results of the current request
            out = exec_net.requests[cur_request_id].outputs[out_blob]
            out = out.flatten()

            for box_index in range(100):
                if out[box_index + 1] == 0.0:
                    break
                base_index = box_index * 7
                if (not np.isfinite(out[base_index]) or
                        not np.isfinite(out[base_index + 1]) or
                        not np.isfinite(out[base_index + 2]) or
                        not np.isfinite(out[base_index + 3]) or
                        not np.isfinite(out[base_index + 4]) or
                        not np.isfinite(out[base_index + 5]) or
                        not np.isfinite(out[base_index + 6])):
                    continue

                object_info_overlay = out[base_index:base_index + 7]

                base_index = 0
                class_id = int(object_info_overlay[base_index + 1])
                if class_id == 0:
                    continue
                conf = object_info_overlay[base_index + 2]

                box_left = object_info_overlay[base_index + 3]
                box_top = object_info_overlay[base_index + 4]
                box_right = object_info_overlay[base_index + 5]
                box_bottom = object_info_overlay[base_index + 6]

                prediction_to_append = [class_id, conf, ((box_left, box_top), (box_right, box_bottom))]
                predictions.append(prediction_to_append)
    except:
        log.error('An arror occurred while trying to make predictions:', sys.exc_info()[0])

    return predictions
```

**Comment by shubha-ramani** [comment]
Dearest nikogamulin, 
can you first try one of OpenVino's object detection samples ?  For instance under here : 
[https://github.com/opencv/dldt/tree/2018/inference-engine/samples](https://github.com/opencv/dldt/tree/2018/inference-engine/samples)
For instance, 
[object_detection_sample_ssd](https://github.com/opencv/dldt/tree/2018/inference-engine/samples/object_detection_sample_ssd) would be a good start.

Thanks for using OpenVino,

Shubha

**Comment by nikogamulin** [comment]
Hi Shubha,

Thank you for quick response. I have successfully implemented various pretrained samples. This, for isntance, is the one, that is working as expected: https://github.com/nikogamulin/openvino-realtime-vehicle-detection/blob/master/realtime_objectdetection.py

**Comment by shubha-ramani** [comment]
Dear nikogamulin:
First I need to ask, does your code work on ssd_mobilenet_v2_coco without using OpenVino Model Optimizer IR and without using OpenVino Inference Engine logic ? Did you re-write your prediction code  logic in Tensorflow for instance, and does that work  ?  If the exact prediction logic works fine in Tensorflow but not in OpenVino then we have proof that this could be an OpenVino issue.

**Comment by nikogamulin** [comment]
Hi Shubha,

According to tensorboard Precision and Recall charts and image evaluation, I believe the model should work. One thing that I am not sure at this point, as I was unable to export the graph to IR using meta graph is whether the model has been frozen incorrectly with TensorFlow Object Detection API, or the frozen graph has been converted to IR incorrectly.
I pasted the exported log [here](https://software.intel.com/en-us/forums/computer-vision/topic/806596#comment-1936121).

To test the model, I used the [exact same code as in this project](https://github.com/nikogamulin/counting-cars), the only thing I changed is the [model IR files in line 166 in this script](https://github.com/nikogamulin/counting-cars/blob/master/realtime_objectdetection_and_tracking.py) For that project, I converted MobileNet SSD (not sure if v1 or v2) caffe model to IR and everything worked as expected.

![Selection_042](https://user-images.githubusercontent.com/1803701/54877614-3add9c00-4e21-11e9-84ca-1b711cd80bc5.jpg)

![Selection_043](https://user-images.githubusercontent.com/1803701/54877618-45983100-4e21-11e9-8af6-79dddda2158c.jpg)

**Comment by shubha-ramani** [comment]
Dearest nikogamulin, 

Let's start with a simple task first. Please try and run your generated IR against the following OpenVino sample:
[https://github.com/opencv/dldt/tree/2018/inference-engine/samples/object_detection_sample_ssd](https://github.com/opencv/dldt/tree/2018/inference-engine/samples/object_detection_sample_ssd)

Are objects detected correctly ?

Please report your findings here.

Unfortunately I don't have the bandwidth to debug your code. But we can start by seeing whether OpenVino samples work on your IR model.

Thanks,

Shubha

**Comment by nikogamulin** [comment]
Hi Shubha,

I ran the prediction model for the above picture of baseball player and got the following result:

~/intel/computer_vision_sdk_2018.5.455/inference_engine/samples/build/intel64/Release$ ./object_detection_sample_ssd -i /home/niko/Pictures/baseball-player.jpg -m ~/workspace/counting-cars-with-backend-conn/models/mobilenet-ssd/FP16/frozen_inference_graph.xml -d MYRIAD
[ INFO ] InferenceEngine: 
	API version ............ 1.4
	Build .................. 19154
Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     /home/niko/Pictures/baseball-player.jpg
[ INFO ] Loading plugin

	API version ............ 1.5
	Build .................. 19154
	Description ....... myriadPlugin
[ INFO ] Loading network files:
	/home/niko/workspace/counting-cars-with-backend-conn/models/mobilenet-ssd/FP16/frozen_inference_graph.xml
	/home/niko/workspace/counting-cars-with-backend-conn/models/mobilenet-ssd/FP16/frozen_inference_graph.bin
[ INFO ] Preparing input blobs
[ INFO ] Batch size is 1
[ INFO ] Preparing output blobs
[ INFO ] Loading model to the plugin
[ WARNING ] Image is resized from (480, 640) to (300, 300)
[ INFO ] Batch size is 1
[ INFO ] Start inference (1 iterations)
[ INFO ] Processing output blobs
[0,1] element, prob = 0.95166    (151.172,80.7812)-(467.578,640) batch id : 0 WILL BE PRINTED!
[ INFO ] Image out_0.bmp created!

total inference time: 74.3983
Average running time of one iteration: 74.3983 ms

Throughput: 13.4412 FPS

[ INFO ] Execution successful

I guess the model has been converted to IR correctly as the result is similar to the above original TensorFlow model.

Thank you very much for help!

**Comment by shubha-ramani** [comment]
Dearest nikogamulin,

Fantastic to hear ! It's always a good idea to start with the OpenVino samples first and see if your IR converted models work with those.

Thanks for using OpenVino !

Shubha

**Comment by ilyachur** [comment]
Hi @nikogamulin,

Can we close the ticket? Was the original problem resolved?

**Comment by AnastasiaKazantaeva** [comment]
As problem doesn't exist any more, I am closing this issue. You may reopen it or create a new one
