### ISSUE TITLE
Is there any mark or other variable can be used to infer request?

### ISSUE THREAD

**Issue by SummerZ2020** [openvinotoolkit/openvino#10501]
##### System information (version)

- OpenVINO => 2021.4.582
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: inference async

##### Detailed description
I am doing the inference with several patches. Currently the infer request number is 5, for the high performance, I chose the async inference in my implementation.  The problem I encountered now is that how to know the patch id of the current completed request.  Any help would be appreciated.

**Comment by SummerZ2020** [comment]
> With a short Python code-snippet you can see that when creating an async infer-request you get an inference-ID back, as a kind of cookie or identifier:
> 
> ```
> for idx in range(10):
>     infID[idx] = ie.asyncInfer( myInput )
> ```
> 
> You register a callback-method:
> 
> ```
> ie.setCallback( myCallback )
> ```
> 
> Your callback signature then looks like this:
> 
> ```
> def callback( infer_id, output ):
> ```
> 
> So, within the callback you know the inferenceID the result/output belongs to.

Thanks a lot. Your solution is perfect and straightaway. And I also found an example from here [https://docs.openvino.ai/latest/omz_demos_object_detection_demo_cpp.html?highlight=object%20detection](url)

**Comment by brmarkus** [comment]
Have you got it working (with C/C++ as you mentioned "Compiler => Visual Studio 2019")?
Anything left to clarify?
Feel free to close this issue if no further questions.
