### ISSUE TITLE
[Bug] Broken link OpenVINO Runtime

### ISSUE THREAD

**Issue by js333031** [openvinotoolkit/openvino#10540]
##### System information (version)
The link below is broken
[OpenVINO™ Runtime](https://docs.openvino.ai/latest/openvino_docs_OV_Runtime_User_Guide.html)

**Comment by andrew-zaytsev** [comment]
@js333031 could you please indicate the page you have found this link on?

**Comment by js333031** [comment]
[From https://github.com/openvinotoolkit/openvino, scroll down to ](https://github.com/openvinotoolkit/openvino#repository-components)  --> OpenVINO Runtime is broken

**Comment by jgespino** [comment]
@js333031 Thanks for reporting, we are working on updating the documentation and the page you shared has the updated URLs. Once the documentation goes live, the links will work as expected.

For now, you can find the OpenVINO Runtime User Guide from the nightly built:
https://docs.openvino.ai/nightly/openvino_docs_OV_Runtime_User_Guide.html

@andrew-zaytsev FYI

Regards,
Jesus

**Comment by ilya-lavrenov** [comment]
Hi,

[openvino_docs_OV_Runtime_User_Guide.html](https://docs.openvino.ai/nightly/openvino_docs_OV_Runtime_User_Guide.html) page is available only in nightly documentation (future 2022.1 documentation) while latest (2021.4 branch) has a document with a different name https://docs.openvino.ai/latest/openvino_docs_IE_DG_Deep_Learning_Inference_Engine_DevGuide.html
