### ISSUE TITLE
Not able install openvino for arm64 architecture

### ISSUE THREAD

**Issue by Ajith61** [openvinotoolkit/openvino#10661]
I installed debian buster 10 in ROCKPI  which is aarch64 architecture. I followed this blog https://www.intel.com/content/www/us/en/developer/articles/technical/arm64-sbc-and-ncs2.html. But after this git clone https://github.com/openvinotoolkit/openvino.git command I could not see inference-engine directory. So after this issue  I could not continue the installation. I attached the image for reference
![Capture](https://user-images.githubusercontent.com/100111342/155693968-17521361-dce9-4219-9954-e50e4aeeec72.PNG)

**Comment by jgespino** [comment]
Hi @Ajith61

The article needs to be updated, I will provide the feedback to the appropriate team. In the meantime, please follow the build instructions here: https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux

You can run the `git submodule update --init --recursive` command at the `openvino `directory and build openvino using the following cmake command from the article you linked.

```
cd ~/openvino
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_MKL_DNN=OFF \
    -DENABLE_CLDNN=ON \
    -DENABLE_GNA=OFF \
    -DENABLE_SSE42=OFF \
    -DTHREADING=SEQ \
    -DENABLE_SAMPLES=ON \
    ..
make -j4
```

Regards,
Jesus

**Comment by dkurt** [comment]
@Ajith61, instead of master branch, you can try build 2021.4 release branch. The layout of folders has been changed:

```
git clone -b releases/2021/4 https://github.com/openvinotoolkit/openvino
```

**Comment by dkurt** [comment]
> Does openvino support debian 10 buster on rockpi device with arm64 architecture?

Yes, it's supported configuration. You can run on MYRIAD from aarch64 host or on ARM CPU using MKLDNN plugin (default CPU plugin in OpenVINO) or with ARM plugin: https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin (add `-DIE_EXTRA_MODULES` option).

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.

**Comment by dukezuoHZ** [comment]
hi,I can't find  MKLDNN plugin on arm64 platofrm when I native build  it. I check the  plugin.xml,no found  plugin for CPU.
    <plugins>
        <plugin name="AUTO" location="libAutoPlugin.so">
        </plugin>
        <plugin name="HETERO" location="libHeteroPlugin.so">
        </plugin>
        <plugin name="MULTI" location="libMultiDevicePlugin.so">
        </plugin>
        <plugin name="MYRIAD" location="libmyriadPlugin.so">
        </plugin>
    </plugins>
~~~~~~~~~~~~~~~~~~~~~~~~
I enable the build optin in features.cmake,It will report much error when build.
ie_dependent_option (ENABLE_MKL_DNN "MKL-DNN plugin for inference engine" ON "X86_64" ON)
so how can you built it for ARM64 CPU?

**Comment by jgespino** [comment]
@dukezuoHZ clDNN is used to infer on Intel Processor Graphics. You need to look for the CPU plugin. Please take a look at the [CMake options for custom compilation](https://github.com/openvinotoolkit/openvino/wiki/CMakeOptionsForCustomCompilation) and [Build OpenVINO Inference Engine](https://github.com/openvinotoolkit/openvino/wiki/BuildingCode).

Please start a new issue if you run into any problems and provide your cmake command and environment details.
