### ISSUE TITLE
The IA-32 architecture host installation is no longer supported. The product cannot be installed on this system. Please refer to product documentation for more information.  Quitting!

### ISSUE THREAD

**Issue by Ajith61** [openvinotoolkit/openvino#10664]
The IA-32 architecture host installation is no longer supported.
The product cannot be installed on this system.
Please refer to product documentation for more information.

Quitting!

**Comment by zulkifli-halim** [comment]
Hello @Ajith61. Please provide us with more information on the issue such as OpenVINO version, platform, system, etc.

**Comment by ilya-lavrenov** [comment]
Hi @Ajith61 
You can build OpenVINO for IA32 from sources https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux#additional-build-options using IA32 toolchain file.

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to reopen the issue if further assistance is needed.
