### ISSUE TITLE
[Bug]The effect of OpenVino inference becomes worse

### ISSUE THREAD

**Issue by SiChuanJay** [openvinotoolkit/openvino#10681]
##### System information (version)

Hello, when I  used openvino for inference, the results were a little worse than onnxruntime. Is there any loss of accuracy when onnx model is transferred to openvino format?

onnx
![图片](https://user-images.githubusercontent.com/52130681/155913626-3af2f073-1d2e-490f-b02c-25f9e66efb8c.png)

openvino
![图片](https://user-images.githubusercontent.com/52130681/155913672-686d3c07-d279-495c-a9d7-0a5cdcfe0dfe.png)

In addition, when I use gpu to accelerate OpenVino, the GPU starts very slowly, is there a good way to solve this problem? Thanks for your help

Best regards

**Comment by zulkifli-halim** [comment]
Hello @SiChuanJay, Please provide us with these details:
1. ONNX model
2. Sample code to reproduce
3. Model Optimizer command used
4. OpenVINO version 
5. GPU Model and Driver Version
6. Operating System

This [article ](https://www.intel.com/content/www/us/en/support/articles/000057525/software/development-software.html) shows how to improve the model load time on GPU.

**Comment by brmarkus** [comment]
What do you mean with "when I use gpu to accelerate OpenVino, the GPU starts very slowly"? Do you mean a high, initial delay/latency when starting?
That could be caused by OpenVINO to compile OpenCL-kernels used when doing inference on the GPU (in the ExecutionUnits).
Either follow the link "https://www.intel.com/content/www/us/en/support/articles/000057525/software/development-software.html" mentioned by @zulkifli-halim .
Or create an ENV variable "cl_cache_dir" pointing to an existing and writable directory, like:

$> mkdir /tmp/ocl
$> export cl_cache_dir=/tmp/ocl

**Comment by SiChuanJay** [comment]
@zulkifli-halim 
1.the onnx model  is from [RVM](https://github.com/PeterL1n/RobustVideoMatting/blob/master/documentation/inference.md#onnx) 
2.the sample code is as follows

model_xml='automatic_5_resetri.xml'
model_bin='automatic_5_resetri.bin'
ie=IECore()
net=ie.read_network(model=model_xml,weights=model_bin)
exec_net=ie.load_network(network=net, device_name='CPU')
rec1=np.zeros([1,16,45,80], dtype=np.float32)
rec2=np.zeros([1,20,23,40], dtype=np.float32)
rec3=np.zeros([1,40,12,20], dtype=np.float32)
rec4=np.zeros([1,64,6,10], dtype=np.float32)
cap=cv2.VideoCapture('indoorDemo.avi')
while True:
    ret, src=cap.read()
    if ret:
        cv2.imshow('src',src)
        src=cv2.resize(src, (320,180))
        src=np.transpose(src,(2,0,1)).astype(np.float32)
        src=np.expand_dims(src, 0)/255.0
        out=exec_net.infer(inputs={'src':src, '1':rec1,'2':rec2,'3':rec3, '4':rec4})
        pha=out['pha']
        rec1=out['r1o']
        rec2=out['r2o']
        rec3=out['r3o']
        rec4=out['r4o']
        pha = (pha * 255).astype(np.uint8)
        pha = np.squeeze(pha, 0)
        pha = np.transpose(pha, [1, 2, 0])
        cv2.imshow("pha", pha)
        key=cv2.waitKey(1)
        if key==ord('q'):
            break
    else:
        break

3. the command: 
python mo_onnx.py --input_model C:\Users\HuangZhe\Desktop\automatic_5_resetri.onnx --output_dir C:\Users\HuangZhe\Desktop --input "src[1 3 180 320],1[1 16 45 80],2[1 20 23 40],3[1 40 12 20],4[1 64 6 10]"

4. the version of openvino is openvino_2021.4.752
5.  
![图片](https://user-images.githubusercontent.com/52130681/156273914-0636705a-fd13-4dc0-a834-a06f91b5154c.png)
6. the Operating System is windows

Thanks for your help

**Comment by SiChuanJay** [comment]
@zulkifli-halim I have another question.  Compiling OpenVino into ONNXRuntime, can onnxruntime inference framework achieve the same speed as OpenVino? I tried following the information provided by ONNXRuntime, but nothing accelerated.

**Comment by zulkifli-halim** [comment]
Hi @SiChuanJay, Please share the exact ONNX model you used. RVM repo inputs are  [src, r1i, r2i, r3i, r4i, downsample_ratio] but you are using src[1 3 180 320],1[1 16 45 80],2[1 20 23 40],3[1 40 12 20],4[1 64 6 10] which is different.  

Based on your code, you are loading to CPU not GPU.

**Comment by SiChuanJay** [comment]
hello, @zulkifli-halim, thanks for your help.
[onnx.zip](https://github.com/openvinotoolkit/openvino/files/8173763/onnx.zip)

**Comment by jgespino** [comment]
Hi @SiChuanJay 

I am testing your model on the OpenVINO toolkit 2022.1 pre-release package, currently converting your code to use the new API to see if there are improvements. However, it seems the inference results vary with different lighting conditions. Could you share the code used to test with ONNX framework or your input video?

Regards,
Jesus

**Comment by SiChuanJay** [comment]
Hi @jgespino 
Could you share the test results of this video? Thank you 
[video.zip](https://github.com/openvinotoolkit/openvino/files/8241043/video.zip)

**Comment by jgespino** [comment]
Hi @SiChuanJay The inference results are the same on the latest release 2022.1, see attached video. Would you mind sharing your onnxruntime inference code?
[video.zip](https://github.com/openvinotoolkit/openvino/files/8421265/video.zip)

**Comment by SiChuanJay** [comment]
Hello @jgespino , I have solved the problem. It is mainly caused by inconsistencies in the color channel of my input image, thanks for your helo.

**Comment by SiChuanJay** [comment]
Hello @jgespino , I have solved the problem. It is mainly caused by inconsistencies in the color channel of my input image, thanks for your help.
