### ISSUE TITLE
Local variable new_attrs referenced before assgiment

### ISSUE THREAD

**Issue by zraurum** [openvinotoolkit/openvino#107]
https://github.com/opencv/dldt/blob/669bee86e580cbbc8ef40b440ab195ba2cbf5142/model-optimizer/mo/front/extractor.py#L607

When an error occurs in the extractor function due to the fact that the variable new_attrs is not defined, it is difficult to understand what kind of error it is.

**Comment by shubha-ramani** [comment]
Dearest zraurum:
Here is the code snippet. It seems that a friendly message is printed when an exception happens. Can you be more specific about what you mean ? 

Thanks for using OpenVino !

Shubha

  # the 'OpOutput' operation is a virtual operation that is added after the output nodes
        if 'op' in attrs and attrs['op'] == 'OpOutput':
            supported, new_attrs = True, {'in_attrs': list(), 'out_attrs': list()}
        else:
            try:
                supported, new_attrs = extractor(Node(graph, node))
            except Exception as e:
                log.warning('Node attributes: {}'.format(graph.node[node]))
                raise Error(
                    'Unexpected exception happened during extracting attributes for node {}.' +
                    '\nOriginal exception message: {}',
                    new_attrs['name'] if 'name' in new_attrs else '<UNKNOWN>',

**Comment by zraurum** [comment]
My description of this error on the Intel forum: https://software.intel.com/en-us/forums/computer-vision/topic/803919

**Comment by shubha-ramani** [comment]
Dear zraurum ,
thanks for the IDZ link. Definitely that seems like a real MO bug. I have sent you a PM to enable sending me your onnx model so that I can reproduce it and file a bug ticket.

Thanks for using OpenVIno !

Shubha

**Comment by eugenio-guarino** [comment]
Is there any known fix for this bug?

**Comment by lazarevevgeny** [comment]
This issue has been fixed already. Please, check the master branch.
