### ISSUE TITLE
Get lower qps for INT8 model(Calibration Tool)

### ISSUE THREAD

**Issue by chong-lee** [openvinotoolkit/openvino#108]
I calibrate a IR model(inception-v3) from FP32 to INT8, following the sample of calibration_tool. But only get qps of 6, compare to 45 before calibration. Is there any thing wrong?
the calibration_tool command line like this:
`./calibration_tool -t C -m output.xml -lbl labels.txt -i dataset/ -ppType "Resize"`

**Comment by mmx110** [comment]
Also ask!

**Comment by chong-lee** [comment]
I found one reason may cause this situation. I calibrate IR model use openvino-4.0.1, test it use openvino-4.0.0, and get result mentioned as above. Then I try to test it use openvino-4.0.1, get qps of 46. It seems ok, although not as fast as expected.

**Comment by shubha-ramani** [comment]
Dear @chong-lee,  
It seems like you were using two different versions for the calibration and testing steps. Once you used 4.01 for testing AND calibration, everything worked properly. This is what I understand from above. I encourage you to download the latest 2019 R1 release. Many improvements, fixes and new features are in the new release !

Thanks for using OpenVino,

Shubha

**Comment by AnastasiaKazantaeva** [comment]
As no response, it seems everything's working. Closing this issue. You may reopen it or create a new one
