### ISSUE TITLE
[Bug] infer request error when InferRequest variable is a private member in class.

### ISSUE THREAD

**Issue by TallyH0** [openvinotoolkit/openvino#10830]
##### System information (version)

- OpenVINO => 2021.4.752
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2019
- Problem classification : Inference
- Framework : onnx 

##### Detailed description
When inferRequest is used within the scope where OpenVino engine is declared, the variable produces no error. However, when it is called in another
function within the same class, an error is produced. I would like to know whether this is a known issue or a simple misusage of the variable.
see the annotations at line 68, 88.
my codes are attached below.
[OpenVINO_2021.4_infer_test.txt](https://github.com/openvinotoolkit/openvino/files/8204249/OpenVINO_2021.4_infer_test.txt)

**Comment by ilya-lavrenov** [comment]
@apankratovantonp could you please take a look?

**Comment by apankratovantonp** [comment]
@TallyH0 Could you please provide more details about the error? Is it exception or may by segmentation fault? If it is exception could you provide the error message?

**Comment by zulkifli-halim** [comment]
Hi @TallyH0. You cannot use the infer request outside an ExecutableNetwork. 

Only `infer_request.Wait` (InferenceEngine::InferRequest::WaitMode::RESULT_READY and InferenceEngine::InferRequest::WaitMode::STATUS_ONLY) can be called from different threads. 

For more information, please refer to [Step 6: Start Inference.
](https://docs.openvino.ai/2021.4/openvino_docs_IE_DG_Integrate_with_customer_application_new_API.html#step-6-start-inference)

**Comment by TallyH0** [comment]
> @TallyH0 Could you please provide more details about the error? Is it exception or may by segmentation fault? If it is exception could you provide the error message?

Thank you for your reply. It is just segmentation fault.

**Comment by TallyH0** [comment]
> Hi @TallyH0. You cannot use the infer request outside an ExecutableNetwork.
> 
> Only `infer_request.Wait` (InferenceEngine::InferRequest::WaitMode::RESULT_READY and InferenceEngine::InferRequest::WaitMode::STATUS_ONLY) can be called from different threads.
> 
> For more information, please refer to [Step 6: Start Inference. ](https://docs.openvino.ai/2021.4/openvino_docs_IE_DG_Integrate_with_customer_application_new_API.html#step-6-start-inference)

Thank you for your reply. 
I understand. It seems that using InferRequest outside the scope was possible in previous OpenVINO versions (I checked openvino 2020.4 version). Is this feature no longer available?

**Comment by apankratovantonp** [comment]
@TallyH0 When you created memory buffer for weights you pass it into `InferenceEngine::Core::ReadNetwork` using **non owning** `InferenceEngine::Blob::Ptr`
```c++
		vector<uint8_t> binBuffer = vector<uint8_t>(istreambuf_iterator<uint8_t>(binStream), istreambuf_iterator<uint8_t>());

		m_Network = ie.ReadNetwork(xmlBuffer, 
			make_shared_blob<uint8_t>({ Precision::U8, {binBuffer.size()}, C }, binBuffer.data()));
```
So when the code goes out of the `Init()` function scope `binBuffer` is destroyed and the shared buffer with weights points to deleted memory in `Process()` function scope.

**Comment by TallyH0** [comment]
> @TallyH0 When you created memory buffer for weights you pass it into `InferenceEngine::Core::ReadNetwork` using **non owning** `InferenceEngine::Blob::Ptr`
> 
> ```c++
> 		vector<uint8_t> binBuffer = vector<uint8_t>(istreambuf_iterator<uint8_t>(binStream), istreambuf_iterator<uint8_t>());
> 
> 		m_Network = ie.ReadNetwork(xmlBuffer, 
> 			make_shared_blob<uint8_t>({ Precision::U8, {binBuffer.size()}, C }, binBuffer.data()));
> ```
> 
> So when the code goes out of the `Init()` function scope `binBuffer` is destroyed and the shared buffer with weights points to deleted memory in `Process()` function scope.

@apankratovantonp 
now I declared binBuffer as a member. It works well.
Thank you!
