### ISSUE TITLE
Int8 inference takes longer than float32 inference with batch_size>1

### ISSUE THREAD

**Issue by hsj307** [openvinotoolkit/openvino#1085]
Hi,
Thanks for sharing this great platform!

i run the int8  model with different batch_size(1,32). but int8 inference takes longer than float32 inference with batch_size=32.

topology;age_gender
target device;CPU
[ INFO ] InferenceEngine:
         API version............. 2.1.2020.3.0-3467-15f2c61a-releases/2020/3
[ INFO ] Device info
         CPU
         MKLDNNPlugin............ version 2.1
         Build................... 2020.3.0-3467-15f2c61a-releases/2020/3
[ INFO ] Network input 'data' precision U8, dimensions (NCHW): 32 3 62 62

batch_size=1
float32
Count:      51991 iterations
Duration:   60000.38 ms
Latency:    0.97 ms
Throughput: 1029.65 FPS
int 8 
Count:      90758 iterations
Duration:   60000.04 ms
Latency:    0.49 ms
Throughput: 2036.40 FPS

batc_size=32
float32
Count:      2933 iterations
Duration:   60017.89 ms
Latency:    18.48 ms
Throughput: 1731.29 FPS
int8 
Count:      2368 iterations
Duration:   60021.69 ms
Latency:    23.85 ms
Throughput: 1341.98 FPS

system: Linux version 4.4.0-184-generic (buildd@lgw01-amd64-060) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) )
CPU: Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8

**Comment by ilya-lavrenov** [comment]
@eshoguli @dmitry-gorokhov could you please help?

**Comment by dmitry-gorokhov** [comment]
Hi @hsj307,
Any chance you can share the model? It will allow us to analyze the issue.

**Comment by xizi** [comment]
I meet the same problem using mobilenetv2 network.

**Comment by jgespino** [comment]
Closing, please feel free to re-open and attach model if additional assistance is needed.
