### ISSUE TITLE
Redundant check for is_remote

### ISSUE THREAD

**Issue by ngaloppo** [openvinotoolkit/openvino#10888]
This looks like a bug. There is no need to check for `is_remote` inside `!is_remote` else clause. 

https://github.com/openvinotoolkit/openvino/blob/4e0a740eb3ee31062ba0df88fcf438564f67edb7/src/plugins/intel_gpu/src/plugin/infer_request.cpp#L326

**Comment by jgespino** [comment]
Hi @ngaloppo 

This may be needed as `is_remote` is set to true in two occasions within the else statement. 

https://github.com/openvinotoolkit/openvino/blob/4e0a740eb3ee31062ba0df88fcf438564f67edb7/src/plugins/intel_gpu/src/plugin/infer_request.cpp#L311

https://github.com/openvinotoolkit/openvino/blob/4e0a740eb3ee31062ba0df88fcf438564f67edb7/src/plugins/intel_gpu/src/plugin/infer_request.cpp#L321

@vladimir-paramuzov @sshlyapn Could you confirm if [is_remote](https://github.com/openvinotoolkit/openvino/blob/4e0a740eb3ee31062ba0df88fcf438564f67edb7/src/plugins/intel_gpu/src/plugin/infer_request.cpp#L326) is purposely checked or if this is a bug?

Regards,
Jesus

**Comment by ngaloppo** [comment]
OK, nevermind! I did not realize that `is_remote` is mutable within the else statement. Closing, apologies for the spam!
