### ISSUE TITLE
Creating a USMTensor from user-provided pointer tries to allocate regardless

### ISSUE THREAD

**Issue by ngaloppo** [openvinotoolkit/openvino#10890]
I am currently running into an issue running into an failed assertion here: 

https://github.com/openvinotoolkit/openvino/blob/4e0a740eb3ee31062ba0df88fcf438564f67edb7/src/plugins/intel_gpu/src/plugin/remote_context.cpp#L121

The stack is as follows:

- Application calls `auto remote_tensor = gpu_context.create_tensor(type, shape, usm_ptr)`
- `ClContext::create_tensor()` calls base class `RemoteContext::create_tensor()`, which calls plugin's `CreateBlob()`, immediately followed by `blob->allocate()` ([here](https://github.com/openvinotoolkit/openvino/blob/4e0a740eb3ee31062ba0df88fcf438564f67edb7/src/inference/src/cpp/ie_remote_context.cpp#L69)).

This then causes the `m_memObj == null_ptr` assertion (since it was already set by `CreateBlob()` when the USM pointer was provided by the application. 

Why does `RemoteContext::create_tensor()` call `allocate()` unconditionally? That doesn't seem right with the RemoteContext::create_tensor() -> USMTensor semantics.

**Comment by vladimir-paramuzov** [comment]
`allocate()` doesn't mean that a memory buffer is actually allocated when memory sharing is used. In case of mem sharing it just creates `cldnn::memory` handle which wraps user handle (https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/src/plugin/remote_context.cpp#L145). Do you have a code snippet which causes assertion fail? I've tried to run [functional tests](https://github.com/openvinotoolkit/openvino/blob/master/src/tests/functional/plugin/gpu/remote_blob_tests/gpu_remote_tensor_tests.cpp) in debug mode and none of them failed.

**Comment by ngaloppo** [comment]
Thanks, developing a code snippet allowed me to pin-point the issue. It turns out that this only happens when repeatedly calling `ClContext::create_tensor()` with the same underlying USM memory. Whether this is a bug is debatable, since what I'm doing is perhaps not the right way to use the API? Regardless, we probably should either document this, or somehow prevent the user to apply the pattern I used. See below for "typical" code: 

```cpp
#include <CL/sycl.hpp>
#include <CL/sycl/backend/opencl.hpp>

#include <openvino/openvino.hpp>
#include <openvino/opsets/opset8.hpp>
#include <openvino/runtime/intel_gpu/ocl/ocl.hpp>

inline std::shared_ptr<ov::Model> makeSimpleReluFunction(std::vector<size_t> input_shape = {1, 3, 20, 20},
                                                         const ov::element::Type & element_type = ov::element::f32)
{
    using namespace ov::opset8;
    auto data = std::make_shared<Parameter>(element_type, ov::Shape(input_shape));
    data->set_friendly_name("data");
    data->output(0).set_names({"data_t"});
    auto relu = std::make_shared<Relu>(data);
    relu->set_friendly_name("relu");
    relu->output(0).set_names({"relu_t"});

    auto result = std::make_shared<Result>(relu);
    result->set_friendly_name("result");

    return std::make_shared<ov::Model>(ov::ResultVector{result}, ov::ParameterVector{data}, "simple_relu");
}

int main()
{
    try {
        std::vector<size_t> input_shape = {1, 3, 20, 20};

        // Create SYCL queue and device shared memory
        auto queue = sycl::queue(sycl::gpu_selector());
        size_t blob_size = input_shape[0] * input_shape[1] * input_shape[2] * input_shape[3];
        float * usm_ptr = sycl::malloc_shared<float>(blob_size, queue);

        ov::Core core;
        auto cl_queue = sycl::get_native<sycl::backend::opencl>(queue);
        auto remote_context = ov::intel_gpu::ocl::ClContext(core, cl_queue);

        // Create a function/model
        auto f = makeSimpleReluFunction(input_shape);
        std::cout << f->input().get_shape() << std::endl;
        ov::CompiledModel model = core.compile_model(f, remote_context);

        auto infer_request = model.create_infer_request();

        for (int i = 0; i < 3; ++i) {
            auto input = model.input();
            auto cl_context = model.get_context().as<ov::intel_gpu::ocl::ClContext>();
            ov::RemoteTensor input_tensor = cl_context.create_tensor(
                    input.get_element_type(), input.get_shape(), usm_ptr);
            infer_request.set_tensor(input.get_any_name(), input_tensor);

            infer_request.start_async();
            infer_request.wait();
        }

        sycl::free(usm_ptr, queue);

    } catch (std::runtime_error & e) {
        std::cout << e.what() << std::endl;
        return 1;
    }

    return 0;
}
```

**Comment by ilya-lavrenov** [comment]
> Whether this is a bug is debatable

I think the code is valid. @vladimir-paramuzov @p-durandin we need to fix this.

**Comment by mletavin** [comment]
The PR containing the fix is https://github.com/openvinotoolkit/openvino/pull/11304
