### ISSUE TITLE
inference engine should system pugixml if available

### ISSUE THREAD

**Issue by tripzero** [openvinotoolkit/openvino#109]
https://github.com/opencv/dldt/blob/2018/inference-engine/thirdparty/CMakeLists.txt#L10

**Comment by shubha-ramani** [comment]
Dear tripzero, I don't understand your comment. Can you kindly clarify it ?

Thanks,

Shubha

**Comment by alalek** [comment]
- [x] buld/install
- [x] feature

Prefer using of system library (for example, installed via `apt-get` with "-dev" packages) instead of bundled 3rdparty code.

**Comment by tripzero** [comment]
alalek is correct.

**Comment by tripzero** [comment]
Any update on this?  I had to disable the "add_subdir(pugixml)" line in inference-engine/thirdparty/CMakeLists.txt to avoid getting multiple cmake files that reference/depend on different versions of pugixml.  The InferenceEngine-*Debug.cmake referenced 1.0.7 while the system had a newer version installed.  The result was I couldn't build opencv with the InferenceEngine backend because pugixml 1.0.7 didn't exist on the system.

find_package is your friend.

**Comment by ilyachur** [comment]
We have a PR: https://github.com/openvinotoolkit/openvino/pull/2502

This PR allows to use system pugixml.
