### ISSUE TITLE
RPi 4 32/64bit malloc(): unsorted double linked list corrupted

### ISSUE THREAD

**Issue by Mateusz5116** [openvinotoolkit/openvino#10926]
##### System information (version)

- OpenVINO => 2021.4.2
- Operating System / Platform => Raspbian 32 bit (Bullseye/Buster) / Raspbian 64 bit (Bullseye) / Ubuntu 21.10 / Raspberry Pi 4 
- Compilers => gcc 9.1.0 - gcc 10.1.0 - gcc 10.2
- Problem: malloc() Unsorted unsorted double linked list corrupted issue. I investigated the solutions but not works for me and i got this issue since run the software.

##### Detailed description
I working on a software which open a model .xml files. It's a classification model for the analysis and it's a small one ~12MB. Software compile is work without any issues. After i execute the compiled software in the source code the ReadNetwork function the network loaded successfully, and when the software try to load the network with LoadNetwork function in the selected device (CPU) after cause the problem. The compile is successfull and when i'm executing the software and then this LoadNetwork part reached i got this error message:  
malloc(): unsorted double linked list corrupted
After this aborting the executable.
For the compile i used the latest l_openvino_toolkit_runtime_raspbian_p_2021.4.752.tgz package.
I add in to the Cmake file the proposed based on the examples: 
add_compile_options(-march=armv7-a)

After i use the uname -m result is : armv7l

I tried to solve the problem based on this issues:
[1852](https://github.com/openvinotoolkit/open_model_zoo/issues/1852)

I tried it in the 64bit Raspbian OS too but after that with the same toolkit runtime package to compile the software. After with this construction when i compile the software i got that message: it missing the inference_engine and other files or not found the type.
In the Raspberry pi with Ubuntu 21.10 cause the same issue.

The latest package not support the aarch64 or 64bit Raspberry pi processors?

The software works perfectly in my computer in a Linux system without any problem.

Can you gave me any advise or hints what can cause this?

**Comment by alalek** [comment]
> l_openvino_toolkit_runtime_raspbian_p_2021.4.752.tgz

>  selected device (CPU)

BTW, there is no support for ARM CPU inference device in RPi package. It is targeted for Myriad sticks (NCS2).


---

> Raspberry Pi 4

Not validated, see documentation:

https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_raspbian.html

---

CPU plugin for ARM H/W could be built separately (with RPi 4 support). You may want to take a look on this module (use 2021.4 branch): https://github.com/openvinotoolkit/openvino_contrib/tree/2021.4/modules/arm_plugin

(you could try 2021.4 or wait for 2022.1 release)

**Comment by jgespino** [comment]
@Mateusz5116 You can build OpenVINO and include the Arm Plugin from the [openvino_contrib ](https://github.com/openvinotoolkit/openvino_contrib)repository. I also provided some steps on a [previous discussion](https://github.com/openvinotoolkit/openvino/issues/10776#issuecomment-1059616600), please give it a try and let me know if you have any issues.

**Comment by jgespino** [comment]
@Mateusz5116 Correct, the runtime package you download is not built for aarch64 which is why you need to built from source. What is the cmake command you used to build OpenVINO on your aarch64 system? When you have a successful built are you using OpenVINO with Python or C/C++. What is the exact error you are seeing?

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
