### ISSUE TITLE
Model Optimizer errors when trying to optimize official Tensorflow implementation of Resnet model

### ISSUE THREAD

**Issue by stefan-andritoiu** [openvinotoolkit/openvino#11]
TF Model repo used: https://github.com/tensorflow/models/tree/master/official/resnet
**Observation:** The implementation uses the Estimator framework. A saved_model of the inference graph is exported. 

**Trying to optimize a saved model:** 
Model Optimizer command used: 
python3 /opt/intel/computer_vision_sdk/deployment_tools/model_optimizer/mo_tf.py --saved_model_dir <model_dir>

**Error:**
Model Optimizer version:     1.2.185.5335e231
[ ERROR ]  Cannot infer shapes or values for node "images".
[ ERROR ]  'bytes' object has no attribute 'shape'
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function tf_native_tf_node_infer at 0x7fddbbbba488>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Stopped shape/value propagation at "images" node.
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #38.

**Cause (in TF Python model implementation):**
...
#Generate a summary node for the images
tf.summary.image('images', features, max_outputs=6)
...
 
**FIX:** After removing the above tf.summary.image statement, the same command was used and the following asserts were triggered:

**1st one:** /opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/ops/op.py:173

_assert all(old_shape is None for old_shape in old_data_shape) or all([np.array_equal(old_data_shape[id], data_node.shape) for id, data_node in enumerate(data_nodes)])_
Commented it, then the 2nd assert followed: 

**2nd one:** /opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/middle/passes/fusing/fuse_linear_seq.py:81

_assert (np.array_equal(fnodes[0].in_node(get_tensor_id(fnodes[0])).shape, fnodes[-1].out_node().shape))_

Commented the assert and then the process finished with a 
_[SUCCESS] Generated IR model_
And the generated .bin is NOT empty, as has happened with some errors. 
But the inference engine fails while loading the network (Error: Segmentation Fault).

**Comment by shubha-ramani** [comment]
stefan can you kindly tell me which exact resnet model you used ? I assume it's one of the pre-trained ones ?
Thanks,

Shubha

**Comment by lazarevevgeny** [comment]
@stefan-andritoiu The conversion error is caused by the operation of type "ImageSummary" which is called "images" in the TensorBoard (refer to the attached image). This output is not needed during inference phase, so should be removed. There are 2 meaningful outputs in this topology: "ArgMax" and "softmax_tensor" (marked with green in the attached image). The first one produces top1 for each element in the batch, while the second one produces 1000 probabilities for each element in the batch.

In order to convert the model just add command line parameter to the Model Optimizer: "--output" and either "ArgMax" or "softmax_tensor". You may also need to specify "--reverse_input_channels" depending on the order of channels used for model training (RGB or BGR) and how you feed the input images to the Inference Engine (by default InferenceEngine sample load images with the BGR channels order).

![resnet_topology](https://user-images.githubusercontent.com/30651952/48485478-0a11a880-e82a-11e8-895d-4242520e52e8.PNG)

**Comment by lazarevevgeny** [comment]
@stefan-andritoiu were you able to convert the model? If so then please, close the ticket.

**Comment by lazarevevgeny** [comment]
@stefan-andritoiu any feedback?

**Comment by anishagartia** [comment]
@lazarevevgeny I followed your steps and got the below error:

[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  After re-inference of Add2_ node, old and new shapes do not match. Old shapes: [array([ 1, 64, 56, 56])], new shapes: [array([ 1, 64, 56, -1])].

**Comment by mpjlu** [comment]
@anishagartia , I comment out these codes, and fix your error. I got the same error.     
In model-optimizer/mo/front/common/partial_infer/eltwise.py

 ugly but clear solution
    output_shape = extended_shapes[0]
    '''
    print("eltwise_infer output_shape:" + str(output_shape))
    for si in range(1, len(extended_shapes)):
        for ei in range(max_dims):
            mind = min(output_shape[ei], extended_shapes[si][ei])
            maxd = max(output_shape[ei], extended_shapes[si][ei])
            if mind == -1:
                output_shape[ei] = -1
            elif mind == 1:
                output_shape[ei] = maxd
            elif mind != maxd:
                output_shape[ei] = -1


Anyone can give a final solution?

**Comment by lazarevevgeny** [comment]
@mpjlu is this issue still actual? I do not see the models repo mentioned above anymore.

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
