### ISSUE TITLE
Failed to load IR converted from tf model

### ISSUE THREAD

**Issue by remarkableJ** [openvinotoolkit/openvino#1100]
Sir, I had a problem about Inference Engine recently.
Something went wrong until I added the network layers shown in Figure 1. It is worked to convert tf model to IR, but failed to load the IR shown in Figure 2. 
Please help me to figure it out.
![1](https://user-images.githubusercontent.com/45261220/85485363-29260e00-b5fb-11ea-870a-45998b3b55a3.jpg)
![2](https://user-images.githubusercontent.com/45261220/85485443-54a8f880-b5fb-11ea-8c0d-59cdfedf9d62.jpg)

**Comment by ilyachur** [comment]
Hi @remarkableJ,

Could you provide more information? Could you print the message which Inference Engine throws? 

I didn't see Inference Engine error in this issue and cannot help you.

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
