### ISSUE TITLE
RPi 4B build openvino  failed

### ISSUE THREAD

**Issue by xiuxiusen** [openvinotoolkit/openvino#11017]
##### System information (version)
<!-- Example
- OpenVINO => 2020.4
- Operating System / Platform => Ubuntu mate 20.04-arnhf+raspi
- Compilers=>gcc 9.4.0

##### Detailed description
I read the doc,and find there is no method to intall openvino no a RPi with ubuntu mate.I try to use this https://docs.openvino.ai/cn/latest/openvino_docs_install_guides_installing_openvino_linux.html mathod,but failed.

**Comment by andrei-kochin** [comment]
@xiuxiusen could you please provide more information on the issue? Failed log, system information and so on.

Thank you in advance!

**Comment by xiuxiusen** [comment]
I read the doc,and find there is no method to intall openvino no a RPi with ubuntu mate.I try to use this https://docs.openvino.ai/cn/latest/openvino_docs_install_guides_installing_openvino_linux.html mathod,but failed.
ERROR:.
/install.sh: 60: [: -lt: unexpected operator
./install.sh: 63: [: -eq: unexpected operator
The IA-32 architecture host installation is no longer supported.
The product cannot be installed on this system.
Please refer to product documentation for more information.

**Comment by brmarkus** [comment]
Can you provide more information about your environment, please? You are using which version of Ubuntu?
Which version of OpenVINO are you trying to install?
You want to install a pre-built version, or building from source?

Does it have to be Ubuntu?

Can you use "https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_raspbian.html" successfully?

**Comment by xiuxiusen** [comment]
@brmarkus I'm sorry to forget write it.I'm using ubuntu mate 20.04 in a RPi 4B.And I want to use openvino 20.04.I used it "https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_raspbian.html"before.But when i run an open_model_zoo/demos,I run the order ./build_demos.sh,the error was that:
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Some of mandatory Inference Engine components are not found.  Please
  consult InferenceEgnineConfig.cmake module's help page.  (missing:
  IE_RELEASE_LIBRARY IE_LEGACY_RELEASE_LIBRARY IE_C_API_RELEASE_LIBRARY)
  (Required is at least version "2.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /home/xiuxiusen/Downloads/inference_engine_vpu_arm/deployment_tools/inference_engine/share/InferenceEngineConfig.cmake:100 (find_package_handle_standard_args)
  common/CMakeLists.txt:5 (find_package)


CMake Error at common/CMakeLists.txt:5 (find_package):
  Found package configuration file:

    /home/xiuxiusen/Downloads/inference_engine_vpu_arm/deployment_tools/inference_engine/share/InferenceEngineConfig.cmake

  but it set InferenceEngine_FOUND to FALSE so package "InferenceEngine" is
  considered to be NOT FOUND.


-- Configuring incomplete, errors occurred!
See also "/home/xiuxiusen/omz_demos_build/CMakeFiles/CMakeOutput.log".
Error on or near line 84; exiting with status 1
So I think the "https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_raspbian.html" is not used for ubuntu mate 20.04.

**Comment by xiuxiusen** [comment]
I make some cahnges to this link "https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_raspbian.html" .I replace the package with I_openvino__toolkit_runtime_ubuntu20_p_2021.4.But when I build_demos.sh,some error happened.
CMake Warning at /home/xiuxiusen/Downloads/inference_engine_vpu_arm/deployment_tools/inference_engine/share/InferenceEngineConfig-version.cmake:17 (message):
  Inference Engine versioning has changed.  Use 2021.4.0 instead of 2.0
Call Stack (most recent call first):
  CMakeLists.txt:221 (find_package)


CMake Error at CMakeLists.txt:180 (find_package):
  By not providing "Finddlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "dlib", but
  CMake did not find one.

  Could not find a package configuration file provided by "dlib" with any of
  the following names:

    dlibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "dlib" to CMAKE_PREFIX_PATH or set
  "dlib_DIR" to a directory containing one of the above files.  If "dlib"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  human_pose_estimation_demo/CMakeLists.txt:14 (ie_add_sample)


-- Configuring incomplete, errors occurred!
Then I pip3 install dlib,but it makes no sense.It confuses me.I don't know what went wrong.

**Comment by jgespino** [comment]
Hi @xiuxiusen 

Are you trying to run inference on CPU or MYRIAD? If you are trying to run inference on CPU, you will need to build the AMR Plugin from the OpenVINO contrib and OpenVINO from source. Please take a look at my response on this [issue ](https://github.com/openvinotoolkit/openvino/issues/10776#issuecomment-1059616600)for steps to build.

Regards,
Jesus

**Comment by xiuxiusen** [comment]
@jgespino Thank you very much.l will have a try.

**Comment by xiuxiusen** [comment]
@jgespino Thank you very much.I have successfully installed openvino on my RPi.But when I run the open_model_zoo,some errors happened.
My code is:./build_demos.sh.
By not providing "Finddlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "dlib", but
  CMake did not find one.

  Could not find a package configuration file provided by "dlib" with any of
  the following names:

    dlibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "dlib" to CMAKE_PREFIX_PATH or set
  "dlib_DIR" to a directory containing one of the above files.  If "dlib"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  human_pose_estimation_demo/CMakeLists.txt:14 (ie_add_sample)


-- Configuring incomplete, errors occurred!
It confused me.I appoligize in andvance if i made something wrong.

**Comment by xiuxiusen** [comment]
@jgespino Thank you very much.I have successfully installed openvino

**Comment by jgespino** [comment]
@xiuxiusen Glad you were able to install successfully!
