### ISSUE TITLE
Support for Raspberry aarch64, Debian GNU/Linux 11 (bullseye)

### ISSUE THREAD

**Issue by vollebreggie** [openvinotoolkit/openvino#11059]
Hello,

I'm trying to run an speech to text model on the intel neural stick 2 with a Raspberry pi 4, aarch64, Debian GNU/Linux 11 (bullseye) and python version 3.9.

I tried to build the releases/2022/1 following this [BuildingForRaspbianStretchOS](https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS) wiki. Everything build correctly.  However, when I open a python script and try to import openvino, it says "module not found.".

Is there any documentation for building and installing openvino on the Raspberry Bullseye with aarch64?

**Comment by jgespino** [comment]
Hi @vollebreggie 

Could you share the cmake command you used to build OpenVINO? We don't have a guide to build specific for aarch64 but the guide you followed should work. I am in the process of building OpenVINO on Raspberry Pi 4 with Bullseye aarch64. I will update this issue once it's complete. 

Regards,
Jesus

**Comment by vollebreggie** [comment]
Hello @jgespino ,

Thank you for responding to my issue. I used `cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=SEQ .. && make` without additional build options. I'm starting to assume it has something to do with not adding the additional python build options.

I just finished building a Ubuntu* 20.04 (64-bit) on my raspberry and followed the [Linux wiki](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux). When I run

> openvino/bin/aarch64/Releases/hello_query_device

 It works perfectly. But when I try to run 

> samples/python/hello_query_device.py

I get 'openvino module not found'.


`pip install openvino==2022.1.0.dev20220316` is not a supported wheel on the raspberry, but I'm assuming that is correct and I have to manually build it.

**Comment by jgespino** [comment]
Hi @vollebreggie 

Correct, for aarch64 you have to build from source. 

By default, Python is turned off. You will have to enable it with `-DENABLE_PYTHON=ON` and specify the bin, include and lib directories. Here is the cmake command I used to start the build.

```
cmake -DCMAKE_BUILD_TYPE=Release \
-DTHREADING=SEQ \
-DENABLE_PYTHON=ON \
-DPYTHON_EXECUTABLE=/usr/bin/python3.9 \
-DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.9.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.9 \
-DCMAKE_INSTALL_PREFIX=/opt/intel/openvino_2022 \
..
```

Regards,
Jesus

**Comment by vollebreggie** [comment]
Regarding the conversion of my model. I was successful on converting a dynamic hubert model to IR on a windows machine.

**Comment by vollebreggie** [comment]
The build succeeded and I can now also build hello_query_device.py. Thank you very much!

**Comment by jgespino** [comment]
Awesome, glad it worked for you. Please let me know if you have additional questions.

**Comment by vollebreggie** [comment]
I have one final question.

`python3 hello_query_device.py` only works if I have run the setupvars.sh.
I tried to use `export PYTHONPATH=$PYTHONPATH:/~/openvino/bin/intel64/Release/lib/python_api/python3.6/`, but that didn't work. What is the proper way to set the api a default path?

**Comment by jgespino** [comment]
@vollebreggie I would stick to the setupvars.sh to ensure all paths are set correctly. If you just want to setup the `PYTHONPATH` use the following command.

`export PYTHONPATH=$PYTHONPATH:/home/pi/openvino/bin/aarch64/Release/lib/python_api/python3.9/`

Couple of things to note as your path may be different.

- Built openvino in my home directory `/home/pi/openvino`
- Built was for `aarch64 `(your command is for `intel64` platform)
- Built openvino for Python3.9, ensure your path matches your python version

**Comment by vollebreggie** [comment]
A I copied the wrong link.

My built openvino is in my `/opt/intel/` directory. so I used 
`export PYTHONPATH=$PYTHONPATH:/opt/intel/openvino/bin/aarch64/Release/lib/python_api/python3.9/` and `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/openvino/bin/aarch64/Release/lib
`

Rightnow I have to run the commands below everytime I want to use the openvino in the terminal.
```
$ source /opt/intel/openvino_2022/setupvars.sh
$ /opt/intel/openvino_2022/install_dependencies/install_NCS_udev_rules.sh
```
It doesn't work when I try to run it in my visual code editor. Is this the way it works? Or did I somehow screw up the cmake commands?

**Comment by vollebreggie** [comment]
I stand corrected. I ran the commands below in the proper project directory and it works.

```
$ source /opt/intel/openvino_2022/setupvars.sh
$ /opt/intel/openvino_2022/install_dependencies/install_NCS_udev_rules.sh
```

**Comment by jgespino** [comment]
@vollebreggie The trick is to source `setupvars.sh` and launch code from the same terminal.

```
$ source /opt/intel/openvino_2022/setupvars.sh
$ code
```

Also, you should only need to run `install_NCS_udev_rules.sh` once.

**Comment by jgespino** [comment]
@vollebreggie Closing as you are up and running with openvino on Bullseye. Feel free to start a new issue if you need any help.

**Comment by vollebreggie** [comment]
I got it working!

I do have a follow-up question. I have a `facebook/hubert-large-ls960-ft` model. I've converted it to an onnx model and converted the onnx model to an IR model.

I've run this model and script on my windows machine and it works perfectly. However, when I run it on my raspberry I get the following error: `RuntimeError: Cannot get length of dynamic dimension`.

The code I use:
```
from openvino.runtime import Core
from transformers import Wav2Vec2Processor
import librosa
import torch #1.10.1
import openvino.runtime as ov
import numpy as np #1.21.0

print(torch.__version__)
print(np.__version__) 
print(np.__path__)

core = Core()

processor = Wav2Vec2Processor.from_pretrained("facebook/hubert-large-ls960-ft")
input_audio, _ = librosa.load("sound.wav", sr=16000)
input_values = processor(input_audio, return_tensors="pt", sampling_rate=16000).input_values

available_devices = core.available_devices
print(available_devices)
compiled_model = core.compile_model("hubert/hubert.onnx", "MYRIAD")
infer_request = compiled_model.create_infer_request()

input_tensor = ov.Tensor(array=input_values.numpy(), shared_memory=True)
infer_request.set_input_tensor(input_tensor)

infer_request.infer()
output = infer_request.get_output_tensor()
output_buffer = output.data
predicted_ids = torch.argmax(torch.Tensor(output_buffer), dim=-1)
transcription = processor.decode(predicted_ids[0]).lower()

print(f"transcription: {transcription}")
```

it crashes on this line:
`compiled_model = core.compile_model("hubert/hubert.onnx", "MYRIAD")`


The stacktrace:
`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/pi/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/pi/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/Desktop/raspberry/voice-to-text/test.py", line 21, in <module>
    compiled_model = core.compile_model("hubert/hubert.xml", "MYRIAD")
  File "/opt/intel/openvino/python/python3.9/openvino/runtime/ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Cannot get length of dynamic dimension`
