### ISSUE TITLE
[Bug]different input size caused huge difference of resluts

### ISSUE THREAD

**Issue by Asthestarsfalll** [openvinotoolkit/openvino#11058]
##### System information (version)

- OpenVINO => 2021.4
- Operating System / Platform => Windows 11 64 Bit
- Compiler => Visual Studio 2022
- Model name: RVM

I used diferent input size 1080 *1920 and 540 * 960 to export onnx model, then I converted them to openvion model.
Inferenced with same data,  the small input size got the terrible results like this:
![2T@77LD4R_~J}@UAQ{(4HDY](https://user-images.githubusercontent.com/72954905/159115377-6426ba96-3a88-410b-9fc5-c4a89cbaf13d.png)
The results of large input size model are normal:
![0GT}NJC3GM7L7C%04OH %(0](https://user-images.githubusercontent.com/72954905/159115396-a31c7745-caee-48da-8f7a-5d7beff31d53.png)

What's wrong with my models?
I used the same way to export onnx model, only modify the input shape.
And I used `python mo_onnx.py --input_model D:\xxx\model.onnx --output_dir D:\xxx\` to convert model.

So how to solve this problem? Thanks in advance for your help.

**Comment by andrei-kochin** [comment]
Hello @Asthestarsfalll, thanks for reaching us! 

Could you please let me know if it is possible to share the ONNX model with some random weights?

Also would be very valuable trying to convert the model on the upcoming release 2022.1 with ONNX Frontend under the hood of Model Optimizer. Is it possible for you to build from source on the 'master' track and try the inference one more time?

Best regards,
Andrei

**Comment by Asthestarsfalll** [comment]
Hi @andrei-kochin  Thank you for your reply.

The two onnx model I exported are below:
https://drive.google.com/drive/folders/108y2jk8W4MTZ589oUv8AmW3w_8Tg-kNE?usp=sharing
I will try to build from source on the master later.

**Comment by Asthestarsfalll** [comment]
@mateusztabaka  
1. The result of ONNXRuntime is normal.
    ![image](https://user-images.githubusercontent.com/72954905/159673578-b39b93e4-23e1-4f7c-ba55-15cd9705d389.png)
2. I use `torch.onnx.export`，and fix the input shape to (1, 3, 540, 960).

**Comment by Asthestarsfalll** [comment]
I use the openvino_2021.2.185, the results don't imporve.
![image](https://user-images.githubusercontent.com/72954905/159679485-b5337078-293d-43f9-9d79-03cd45628271.png)

**Comment by mandrono** [comment]
Hi, @Asthestarsfalll. What device did you use for inference?

**Comment by Asthestarsfalll** [comment]
hi, @mandrono 
Intel i5-10210U CPU

**Comment by mandrono** [comment]
@Asthestarsfalll May I ask you to check results on any other device? GPU maybe?

**Comment by Asthestarsfalll** [comment]
> May I ask you to check results on any other device? GPU maybe?
Not yet, I have checked results on cpu with pytorch model, onnx model and openvino(with input shape [1080, 1920]).Only the openvino model with input shape [540, 960] does't work.
I will test on other device latter!

**Comment by Asthestarsfalll** [comment]
Thank you very much for your help! 
I am also very sorry for disturbing you!
I test on other device, and the results are normal.
So I reinstall the openvino and openvino-dev with pip . The converted openvino model works well !

**Comment by mandrono** [comment]
@Asthestarsfalll sorry for delay in response.
Could you clarify some moments please?

> I test on other device, and the results are normal.
On which device have you tested? GPU?

> The converted openvino model works well !
After reinstallation model works well on CPU?

**Comment by Asthestarsfalll** [comment]
@mandrono 
Hi.
I just install openvino in other computer and convert the onnx model.
The converted model works well on CPU, so I test it on origin computer.
However, the results don't improve.So I reinstall again, and it works.
Maybe the previous way of installing are wrong.

But now I encountered another problem:
I want to use c++ to deploy the above model540, but it comes Unhandled exception at 0x00007FF84E6B478C (in openvinotest.exe): Microsoft C++ exception: InferenceEngine::GeneralError at memory location 0x000000D6F12FE8A0.
![image](https://user-images.githubusercontent.com/72954905/161948885-f6f5df91-0929-4e92-8391-0d8c17da00cd.png)
However, when I use model1080.xml and bin, it can inference successfully.

**Comment by jgespino** [comment]
@Asthestarsfalll Apologies for the delay, not sure if you have figured out the new error. If you haven't could you please start a new issue and provide necessary steps and files to reproduce?
