### ISSUE TITLE
How to copy blob?

### ISSUE THREAD

**Issue by SummerZ2020** [openvinotoolkit/openvino#11098]
I found there is a function named [blob_copy](https://docs.openvino.ai/latest/groupie_dev_api_memory.html?highlight=blob_copy) which can copy blob from source to dest. But I cannot find it in version 2021.4.582. 
where can I find it?
 Or if there is the other function can be used to copy blob. Any help would be appreciated. Thanks a lot.

**Comment by jgespino** [comment]
Hi @SummerZ2020 

`blob_copy` should be available on OpenVINO 2021.4, see [api reference](https://docs.openvino.ai/2021.4/groupie_dev_api_memory.html) for 2021.4.

Could you confirm you are using OpenVINO 2021.4?

Regards,
Jesus

**Comment by ilya-lavrenov** [comment]
Hi, 

This function is available on for OpenVINO plugin developers. It's not a part of public API, so go cannot find it in Inference Engine headers.

Use memcpy to copy blob content.

Thanks, 
Ilya

**Comment by SummerZ2020** [comment]
> Hi,
> 
> This function is available on for OpenVINO plugin developers. It's not a part of public API, so go cannot find it in Inference Engine headers.
> 
> Use memcpy to copy blob content.
> 
> Thanks, Ilya

Thanks a lot
