### ISSUE TITLE
what is the fixed order of TensorDesc dims?

### ISSUE THREAD

**Issue by SummerZ2020** [openvinotoolkit/openvino#11103]
In the demo code common.hpp, the getTensorHeight function is defined as below:
`inline std::size_t getTensorHeight(const InferenceEngine::TensorDesc& desc) {

    const auto& layout = desc.getLayout();
    const auto& dims = desc.getDims();
    const auto& size = dims.size();

    if ((size >= 2) &&
        (layout == InferenceEngine::Layout::NCHW  ||
         layout == InferenceEngine::Layout::NHWC  ||
         layout == InferenceEngine::Layout::NCDHW ||
         layout == InferenceEngine::Layout::NDHWC ||
         layout == InferenceEngine::Layout::OIHW  ||
         layout == InferenceEngine::Layout::CHW   ||
         layout == InferenceEngine::Layout::HW)) {
        // Regardless of layout, dimensions are stored in fixed order
        return dims.at(size - 2);
    } else {
        throw std::runtime_error("Tensor does not have height dimension");
    }
    return 0;
}`

what is the fixed orderof the tensorDesc dims? 
According to the other function getTensorWidth , getTensorChannels and so on, the fixed order should be NCHDW, no matter the layout is NCDHW or NDHWC. Is it right？
where can I find the description in the intel website. Any help would be appreciated. Thanks.

**Comment by ilya-lavrenov** [comment]
Hi, 

Yes, you are right. Regardless of actual data layout in the blob, the order of dimensions in shapes is always the same. So for NCHW and NHWC we always have NCHW order of dimensions in shape e.g. 1 3 224 224, so H is always pre-last element in the array of dimensions representing a shape. 

Thanks, 
Ilya.

**Comment by SummerZ2020** [comment]
> Hi,
> 
> Yes, you are right. Regardless of actual data layout in the blob, the order of dimensions in shapes is always the same. So for NCHW and NHWC we always have NCHW order of dimensions in shape e.g. 1 3 224 224, so H is always pre-last element in the array of dimensions representing a shape.
> 
> Thanks, Ilya.

Thanks a lot.
