### ISSUE TITLE
Result gives all zeroes

### ISSUE THREAD

**Issue by krishyadav007** [openvinotoolkit/openvino#11121]
On running whichever model of OpenVINO zoo the output gives 0 in predictions.

The code for a sample model can be found here: https://colab.research.google.com/drive/1mH2SoOqlwcoJ05Qa4KhZWeVpfmRvWL_t?usp=sharing.

Re-running the notebook should allow reproducing the bug.

**Comment by vladimir-dudnik** [comment]
@krishyadav007 is there any specific reason for you to use OMZ model from OpenVINO 2021.3 release with OpenVINO 2022.1 runtime? Also, why do you load models by their direct links? Is not it possible to install openvino-dev PyPi package and use omz_downloader tool for that?

**Comment by vladimir-dudnik** [comment]
@krishyadav007 did this notebook work with previous version of OpenVINO or this is your first attempt to try OpenVINO inference? If second is true, I would recommend you to review OpenVINO [notebooks](https://github.com/openvinotoolkit/openvino_notebooks) as a sample of how to use OpenVINO in notebooks.

**Comment by eaidova** [comment]
@krishyadav007 I believe problem in these lines:
```
tran = transforms.ToTensor()  # Convert the numpy array or PIL.Image read image to (C, H, W) Tensor format and /255 normalize to [0, 1.0]
img_tensor = tran(resized)
img_tensor = img_tensor.unsqueeze_(0)
```

First of all, openvino expects np.array object as input, not torch.Tensor. Secondly, all OMZ pretrained models expects input data in [0, 255] range instead [0, 1].

Probably these lines should be replaced by:
```
img_tensor = np.expand_dims(np.transpose(resized, (2, 0, 1), 0)
```

**Comment by krishyadav007** [comment]
Ok sure, I will test the updated nbs and tell.

Is there an example on Colab?

**Comment by eaidova** [comment]
@krishyadav007 any updates from your side?

**Comment by krishyadav007** [comment]
Thank you, it was extremely helpful
