### ISSUE TITLE
[QUESTION] How can I use POT's accuracy aware quantization on similarity based models?

### ISSUE THREAD

**Issue by ZiyueWangUoB** [openvinotoolkit/openvino#11154]
Hi, I have a model where the output layer is a feature vector for similarity comparisons. I'm unsure how I can use the POT as there aren't any labels?

**Comment by AlexKoff88** [comment]
Hi @ZiyueWangUoB, 

You can work around this by creating (dumping) a subset of reference feature vectors that you will use in your `Metric`. During the per-sample metric update, you will use these reference vectors as an annotation. This should help to control the accuracy during the quantization process. 
Here is an example of accuracy-aware quantization with POT API: https://github.com/openvinotoolkit/openvino/tree/master/tools/pot/openvino/tools/pot/api/samples/object_detection

**Comment by ZiyueWangUoB** [comment]
@AlexKoff88 I see, so I would need to write my custom metric with a bunch of reference feature vectors (which are from my fp32 model) as "labels". Thanks!
