### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'mo' for the latest version 2022.1

### ISSUE THREAD

**Issue by NaNAGISaSA** [openvinotoolkit/openvino#11150]
##### System information (version)

- OpenVINO => 2022.1
- Operating System / Platform => Ubuntu 20.04
- Problem classification => Python pip package

##### Detailed description
For the latest version 2022.1, we can not find the module `mo`.

##### Steps to reproduce
```bash
virtualenv -p python3.7 --no-download $PWD/delete
source delete/bin/activate
python3 -m pip install --upgrade pip setuptools
python3 -m pip install openvino-dev
python3 -c "from mo.mo.utils.version import get_version; print(get_version())"
```
You will get:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mo'
```
For the last version:
```bash
virtualenv -p python3.7 --no-download $PWD/delete2
source delete2/bin/activate
python3 -m pip install --upgrade pip setuptools
python3 -m pip install openvino-dev==2021.4.2
python3 -c "from mo.mo.utils.version import get_version; print(get_version())"
```
You will get `2021.4.2-3976-0943ed67223-refs/pull/539/head`, `mo` module can be imported correctly.

**Comment by dkurt** [comment]
Please use changed import:
```
python3 -c "from openvino.tools.mo.utils.version import get_version; print(get_version())"
```

**Comment by NaNAGISaSA** [comment]
It works! Thank you!

**Comment by muhammadilahee-a3** [comment]
I get the following- ModuleNotFoundError: No module named 'openvino.tools.mo'

**Comment by danielbdr** [comment]
> I get the following- ModuleNotFoundError: No module named 'openvino.tools.mo'

same here! 
I have currently pip installed the modules below
```
openvino==2024.0.0
openvino-telemetry==2023.2.1
```
