### ISSUE TITLE
mask r cnn unsupported layer type NCS2

### ISSUE THREAD

**Issue by GotG** [openvinotoolkit/openvino#1117]
hello
when running text spotting python demo on Myriad (NCS2):

RuntimeError: Failed to compile layer "758": unsupported layer type "ExperimentalDetectronTopKROIs"

any suggestions to make this work?
thanks

**Comment by ilya-lavrenov** [comment]
CC @gladilov-gleb

**Comment by avitial** [comment]
@GotG I am able to see the same runtime error, looks like "758" layer is coming from _text-spotting-0002-detector_ model. Based on other text-detection models (_text-detection-0003_ and _text-detection-0004_) in OMZ repo [here](https://github.com/opencv/open_model_zoo/tree/master/demos) it looks like this model is not supported by Myriad plugin, therefore text-spotting demo will not work with NCS2. However let me check if this information is accurate, I will provide update soon.

**Comment by GotG** [comment]
The text-detection-0003 and text-detection-0004 work on NCS2.
What I would like to know is whether I can manually add support for this layer via an extension.

**Comment by avitial** [comment]
@GotG just wanted to confirm that indeed the text spotting demo is not supported by Myriad plugin. If you you would like to pursue and manually add support for this layer in text-spotting-0002-detector model, you can try following this document: [How to Implement Custom Layers for VPU (Intel® Neural Compute Stick 2)](https://docs.openvinotoolkit.org/2020.3/_docs_IE_DG_Extensibility_DG_VPU_Kernel.html).

**Comment by GotG** [comment]
Thank you
