### ISSUE TITLE
RuntimeError: Cannot get length of dynamic dimension

### ISSUE THREAD

**Issue by vollebreggie** [openvinotoolkit/openvino#11213]
##### System information (version)

- OpenVINO => 2022.1
- Operating System / Platform => Raspberry aarch64
- Compiler => python3.9
- Problem classification: Compile model

Hey guys, 
I'm trying to build a speech-to-text model. I have a `facebook/hubert-large-ls960-ft` model. I've converted it to an onnx model and converted the onnx model to an IR model.

I've run this model and script on my windows machine and it works perfectly. However, when I run it on my raspberry I get the following error: `RuntimeError: Cannot get length of dynamic dimension`.

The code I use:
```
from openvino.runtime import Core
from transformers import Wav2Vec2Processor
import librosa
import torch #1.10.1
import openvino.runtime as ov
import numpy as np #1.21.0

print(torch.__version__)
print(np.__version__) 
print(np.__path__)

core = Core()

processor = Wav2Vec2Processor.from_pretrained("facebook/hubert-large-ls960-ft")
input_audio, _ = librosa.load("sound.wav", sr=16000)
input_values = processor(input_audio, return_tensors="pt", sampling_rate=16000).input_values

available_devices = core.available_devices
print(available_devices)
compiled_model = core.compile_model("hubert/hubert.xml", "MYRIAD")
infer_request = compiled_model.create_infer_request()

input_tensor = ov.Tensor(array=input_values.numpy(), shared_memory=True)
infer_request.set_input_tensor(input_tensor)

infer_request.infer()
output = infer_request.get_output_tensor()
output_buffer = output.data
predicted_ids = torch.argmax(torch.Tensor(output_buffer), dim=-1)
transcription = processor.decode(predicted_ids[0]).lower()

print(f"transcription: {transcription}")
```

it crashes on this line:
`compiled_model = core.compile_model("hubert/hubert.xml", "MYRIAD")`

The stacktrace:
`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/pi/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/pi/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/Desktop/raspberry/voice-to-text/test.py", line 21, in <module>
    compiled_model = core.compile_model("hubert/hubert.xml", "MYRIAD")
  File "/opt/intel/openvino/python/python3.9/openvino/runtime/ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Cannot get length of dynamic dimension`

**Comment by jgespino** [comment]
@vollebreggie Thanks for starting a new issue. 

Dynamic shapes are only supported on CPU Plugin. When you say the code runs fine on you windows machine, are you running it on MYRIAD or CPU?

**Comment by vollebreggie** [comment]
I'm running it on CPU

**Comment by ilya-lavrenov** [comment]
Hi @vollebreggie 

[Dynamic shapes feature](https://docs.openvino.ai/nightly/openvino_docs_OV_UG_DynamicShapes.html) is supported by Intel [CPU device only](https://docs.openvino.ai/nightly/openvino_docs_OV_UG_supported_plugins_CPU.html) which cannot be run on ARM platform.

Thanks,
Ilya.

**Comment by vollebreggie** [comment]
That's unfortunate. 

Do you guys have any suggestions on what models I should use instead or what kind of hardware setup I might need to buy to support dynamic models? Because my current understanding is, that most speech to text models use dynammic shapes.

**Comment by vollebreggie** [comment]
Unfortunatly the raspberry cannot handle the size of the model. I was hoping I could support it with a cpu stick.

**Comment by dkurt** [comment]
@vollebreggie, you can consider using a fixed input length padding by zeros. At least this is what I've tried during quantized model training: https://github.com/openvinotoolkit/openvino_contrib/blob/master/modules/optimum/examples/audio_classification_wav2vec2.md.

**Comment by vollebreggie** [comment]
@dkurt, thanks a lot for looking at my issue. My understanding of transformers and how to change the input length isn't good. Is there any documentation you can point me to, that helps me understand how I can implement a fixed input length

**Comment by yury-gorbachev** [comment]
Hey @vollebreggie , you might want to check this document as well...
https://docs.openvino.ai/latest/openvino_docs_OV_UG_NoDynamicShapes.html
Curious if this helps or makes any better?

**Comment by dkurt** [comment]
@vollebreggie, according to Hubert docs, you can just pad `input_values` with zeros.
```
`attention_mask` should only be passed if the corresponding processor has `config.return_attention_mask ==
True`. For all models whose processor has `config.return_attention_mask == False`, such as
[hubert-base](https://huggingface.co/facebook/hubert-base-ls960), `attention_mask` should **not** be passed
to avoid degraded performance when doing batched inference. For such models `input_values` should simply be
padded with 0 and passed without `attention_mask`. Be aware that these models also yield slightly different
results depending on whether `input_values` is padded or not.
```
source: https://github.com/huggingface/transformers/blob/088c1880b7bfd47777778d0d0fcc20e921bcf21e/src/transformers/models/hubert/modeling_hubert.py#L918-L923

Here is an example with just zero padding:

<details>
<summary>example.py</summary>

```python
import io
import warnings
import numpy as np
import torch
from transformers import Wav2Vec2Processor, HubertForCTC
from datasets import load_dataset
import soundfile as sf
from openvino.runtime import Core

warnings.filterwarnings("ignore")

processor = Wav2Vec2Processor.from_pretrained("facebook/hubert-large-ls960-ft")
model = HubertForCTC.from_pretrained("facebook/hubert-large-ls960-ft")

def map_to_array(batch):
    speech, _ = sf.read(batch["file"])
    batch["speech"] = speech
    return batch

ds = load_dataset("patrickvonplaten/librispeech_asr_dummy", "clean", split="validation")
ds = ds.map(map_to_array)

input_values = processor(ds["speech"][0], return_tensors="pt").input_values  # Batch size 1

# Run reference model
logits = model(input_values).logits
predicted_ids = torch.argmax(logits, dim=-1)
transcription = processor.decode(predicted_ids[0])

print(f"PyTorch output: {transcription}")

# Convert model to ONNX
max_input_length = 100000
dummy_input_values = torch.zeros([1, max_input_length], dtype=torch.float32)
buf = io.BytesIO()
torch.onnx.export(
    model,
    (dummy_input_values),
    buf,
    input_names=["input_values"],
    output_names=["logits"],
    opset_version=11,
)

# Load ONNX model with OpenVINO
core = Core()
model = core.read_model(buf.getvalue(), b"")
model = core.compile_model(model, "CPU")
req = model.create_infer_request()

# Pad input_values
input_values = np.pad(input_values, ((0, 0), (0, max_input_length - input_values.shape[1])))

# Run OpenVINO
out = req.infer({"input_values": input_values})

logits = next(iter(out.values()))
predicted_ids = torch.argmax(torch.tensor(logits), dim=-1)
transcription = processor.decode(predicted_ids[0])

print(f"OpenVINO output: {transcription}")
```

</details>

```
PyTorch output: MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL
OpenVINO output: MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL
```

`model = core.read_model(buf.getvalue(), b"")` can be replaced to IR reading `model = core.read_model("model.xml")`

**Comment by dkurt** [comment]
Also, if it might be interesting for you, there is an [extension](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/optimum) API which hides all OpenVINO logic inside (please wait for https://github.com/openvinotoolkit/openvino_contrib/pull/355 or modify manually):

```
pip install git+https://github.com/openvinotoolkit/openvino_contrib.git#subdirectory=modules/optimum
```

```python
import torch
from transformers import Wav2Vec2Processor, HubertForCTC
from datasets import load_dataset
import soundfile as sf
from optimum.intel.openvino import OVAutoModel

processor = Wav2Vec2Processor.from_pretrained("facebook/hubert-large-ls960-ft")

OVAutoModel._pt_auto_model = HubertForCTC  # TODO: this is a workaround and will be fixed in future release
model = OVAutoModel.from_pretrained("facebook/hubert-large-ls960-ft", from_pt=True)
model.use_dynamic_shapes = False
model.max_length = 100000

def map_to_array(batch):
    speech, _ = sf.read(batch["file"])
    batch["speech"] = speech
    return batch

ds = load_dataset("patrickvonplaten/librispeech_asr_dummy", "clean", split="validation")
ds = ds.map(map_to_array)

input_values = processor(ds["speech"][0], return_tensors="pt").input_values  # Batch size 1

logits = model(input_values).logits
predicted_ids = torch.argmax(logits, dim=-1)
transcription = processor.decode(predicted_ids[0])

print(f"Optimum output: {transcription}")
```

**Comment by dkurt** [comment]
Unfortunately, MYRIAD cannot fit `facebook/hubert-large-ls960-ft` because it's FP16 weights take about 600MB. Is there less size finetuned models?

**Comment by vollebreggie** [comment]
Hey @dkurt, 
I haven't time yet to go through the documentatie. It will problably be tomorrow evening. 

The distilbert model will problably suffice. Thanks again for looking at my issue!

**Comment by vollebreggie** [comment]
I tried a distilled model `OthmaneJ/distil-wav2vec2` from the wav2vec2 model. This model is 45% smaller, but it was still unable to run on the raspberry.

**Comment by vollebreggie** [comment]
Other models like `facebook/wav2vec2-base-960h` also don't run. I'm afraid my hardware is just not strong enough. @dkurt Do you have any recommendations for single board computers that might support these models?

**Comment by vollebreggie** [comment]
The solution @dkurt provided did solve the dynamic shape problem. I'll close this issue
