### ISSUE TITLE
[Feature request] Convert Model IR to FP16 from Python

### ISSUE THREAD

**Issue by dkurt** [openvinotoolkit/openvino#11256]
There is a method in C++ which allows convert OpenVINO Model from FP32 to FP16: `ConvertFP32ToFP16`. Is there a Python alternative which can help with model serialization in FP16 in runtime? I.e. we need this option when load ONNX model from buffer and wanted save in IR by the following code:
```python
import openvino.runtime.passes as passes

pass_manager = passes.Manager()
pass_manager.register_pass("Serialize", xml_path, xml_path.replace(".xml", ".bin"))
pass_manager.run_passes(model)
```

**Comment by ilya-lavrenov** [comment]
@dkurt is it possible to such conversion via `openvino.tools.mo` API? Do you think extending MO Python API is more proper way instead of exposing some transformations?

**Comment by dkurt** [comment]
I think that should be available without MO API. In C++ there is an nGraph pass which is not exported to Python API.

**Comment by GlebKazantaev** [comment]
@dkurt transformation python API is currently limited in OV and full support will be available only in 22.2.
For your particular use case I can suggest only one approach, but please consider that this is our private python API which can be changed during releases.
```py
from openvino.offline_transformations import compress_model_transformation
compress_model_transformation(model)
```

**Comment by slyalin** [comment]
@dkurt, I believe you need to call `compress_model_transformation` instead `ConvertFP32ToFP16`. @GlebKazantaev will provide more details.
But anyway such functionality is going to be available in `mo.convert` eventually as one of the arguments. This is going to be a dedicated user-side API.

**Comment by dkurt** [comment]
Many thanks! Closing that issue
