### ISSUE TITLE
How to convert the output tensor from FP16 to FP32 w/ ov 2.0  C++ API

### ISSUE THREAD

**Issue by JohnLeFeng** [openvinotoolkit/openvino#11268]
Hi There, 

Sorry for asking a question by filing an issue by **BUG** label (Really sorry about that), currently, I met a problem during converting the output tensor from FP16 to FP32 in OV 2.0 C++ API.
As the inputted model is a compiled model which is for VPU, I cannot do any changes to this model. Therefore, I am trying to convert the type in runtime during the process of the output, however, I still cannot find a method to handle this. Could you share with me any function or sample code that can achieve this?

Example: This one is for get the float32 precision data, however, the data is FP16. Therefore, it will meet an error.
```cpp
const float*  outData = tensor.data<float>();
```

 Does it has any function or method that can convert the FP16 to FP32 before that line?

Thanks,
John

**Comment by ilya-lavrenov** [comment]
Hi @JohnLeFeng 

If you have `f16` data stored in tensor, you need to access it as `f16`:

```c++
auto data = t.data<ov::float16>();
```
So, you need to convert this data manually to `FP32` once you get it from tensor.
If you are able to affect model compilation process, use [Optimize Preprocessing](https://docs.openvino.ai/latest/openvino_docs_OV_Runtime_UG_Preprocessing_Overview.html) guide - you can specify desired precisions and data layouts for input and outputs tensors before compilation.

Thanks,
Ilya.
