### ISSUE TITLE
Pyinstaller issue with Openvino 2022.1

### ISSUE THREAD

**Issue by JackTCLi** [openvinotoolkit/openvino#11293]
##### System information (version)

- OpenVINO=> 2022.1
- Operating System / Platform => Winodws 64 Bit
- Virtual environment => Anaconda 4.9.2
- Python => 3.8.12
- Installation => From PyPI (pip install openvino)
- Problem classification => Openvino Inference Engine
- Model name: Mobilenetv3 (From Torchvision)
- Pyinstaller => 4.10

##### Detailed description

I use the latest openvino runtime (API 2.0) to implement the inference pipeline, and it goes well, I can run the inference without any errors.
The code I use (partial):
![inference_engine_error2](https://user-images.githubusercontent.com/87409782/160550635-0021b89a-1a33-4eaa-8d47-c411d3a0a1e0.JPG)

Then I create an EXE file from python scripts using Pyinstaller, It's finished successfully, but the following error occurs while executing the EXE file.
![inference_engine_error](https://user-images.githubusercontent.com/87409782/160549167-1e489024-e032-4409-bef3-a8cbf3c0afca.JPG)

The .spec file that I used:

```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['../openvino_ie_controller.py'],
             pathex=['D:\\ProgramData\\Anaconda3\\envs\\openvino_ie\\Lib\\site-packages\\openvino',
                     'D:\\ProgramData\\Anaconda3\\envs\\openvino_ie\\Lib\\site-packages\\openvino\\libs'],
             binaries=[],
             datas=[('D:\\ProgramData\\Anaconda3\\envs\\openvino_ie\\Lib\\site-packages\\openvino\\libs\\plugins.xml', '.'),
                    ('D:\\ProgramData\\Anaconda3\\envs\\openvino_ie\\Lib\\site-packages\\openvino\\inference_engine\\constants.cp38-win_amd64.pyd','openvino\\inference_engine')],
             hiddenimports=['openvino', 'openvino.frontend.onnx', 'ngraph'],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='Openvino_IE',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None ) 
```
##### Steps to reproduce

1. Train the Mobilenetv3 model with PyTorch.
2. Using torch.onnx to export the model into ONNX format.
3. Using OpenVINO Model Optimizer to convert the model to IR format.
4. Using Pyinstaller to bundle python scripts and all its dependencies into an executable file.

Thanks,
Jack

**Comment by ilya-lavrenov** [comment]
Hi @JackTCLi 

I am not familiar with `.spec` file syntax to create PyInstallers, but looks like that such installer does not contain all the necessary libraries needed to read the model and perform inference. See [local distribution](https://docs.openvino.ai/latest/openvino_docs_deploy_local_distribution.html#reading-models) guide to understand what libraries are needed for your case. Based on the error message you provided I suppose you use OpenVINO IR file to store your model and in this case you need to put `openvino_ir_frontend` to the PyInstaller, but OpenVINO reports that only ONNX files can be read (so, you have put only `openvino_onnx_frontend`).

Thanks,
Ilya.

**Comment by JackTCLi** [comment]
Hi @ilya-lavrenov 

After bundling `openvino_ir_frontend.dll` and `openvino_intel_cpu_plugin.dll` into the EXE file, it works!

Thank you for your help,
Jack

**Comment by vishal-opt** [comment]
Hi @JackTCLi 

i also facing the same problem. How you bundle openvino_ir_frontend.dll and openvino_intel_cpu_plugin.dll when creating exe file ?

**Comment by vissha** [comment]
Hi @JackTCLi

i also facing the same problem. How you bundle openvino_ir_frontend.dll and openvino_intel_cpu_plugin.dll when creating exe file ?

**Comment by JackTCLi** [comment]
Hi @vissha,
You can add these files by using --add-data command option, or by adding them as a list to the spec file.

**Comment by pjvanbeek** [comment]
Thank you. I had a very similar problem trying to read an openvino IR model file, and this solved it.  On Windows, with a Python virtual environment. 

I am using auto-py-to-exe (a GUI wrapper around pyinstaller).  In the auto-py-to-exe GUI, there is an "--add-binary" option under the Advanced menu.  Adding the above two openvino dlls solved the issue for me.  The two dlls were bundled/copied into the output directory.

**Comment by Asilbek0444** [comment]
How to find openvino_ir_frontend.dll ? I'm working in linux, how to solve problem ?

**Comment by Asilbek0444** [comment]
@JackTCLi
