### ISSUE TITLE
inference with open_models/demos/

### ISSUE THREAD

**Issue by xinyuegtxy** [openvinotoolkit/openvino#113]
cd open_models
./demos/build/intel64/Release/security_barrier_camera_demo \
> -i wcar.jpeg \
> -m model_downloader/Transportation/object_detection/vehicle/mobilenet-reduced-ssd/dldt/vehicle-detection-adas-0002.xml \
> -m_va model_downloader/Security/object_attributes/vehicle/resnet10_update_1/dldt/vehicle-attributes-recognition-barrier-0039.xml \
> -m_lpr model_downloader/Security/optical_character_recognition/license_plate/dldt/license-plate-recognition-barrier-0001.xml \
> -d GPU
[ INFO ] InferenceEngine: 
	API version ............ 1.4
	Build .................. custom_2018_669bee86e580cbbc8ef40b440ab195ba2cbf5142
[ INFO ] Parsing input parameters
[ INFO ] Capturing video streams from the video files or loading images
[ INFO ] Files were added: 1
[ INFO ]     wcar.jpeg
[ INFO ] Number of input image files: 1
[ INFO ] Number of input video files: 0
[ INFO ] Number of input channels:    1
[ INFO ] Loading plugin GPU

	API version ............ 1.5
	Build .................. custom_2018_669bee86e580cbbc8ef40b440ab195ba2cbf5142
	Description ....... clDNNPlugin
[ INFO ] Loading plugin CPU

	API version ............ 1.5
	Build .................. custom_2018_669bee86e580cbbc8ef40b440ab195ba2cbf5142
	Description ....... MKLDNNPlugin
[ INFO ] Loading network files for VehicleDetection
[ ERROR ] Error reading network: cannot parse future versions: 5

**Comment by xinyuegtxy** [comment]
@BelBES @asuhov @dkurt @RachelRen05 @

**Comment by shubha-ramani** [comment]
Dear @xinyuegtxy in Windows there is a file under <OpenVino_Installation_Dir>/bin/setupvars.bat. In Linux there's setupvars.sh in a similar path. Make sure that the shell from which you run the samples has had that setupvars.bat[sh] executed.

Thanks,

Shubha

**Comment by alalek** [comment]
@xinyuegtxy

> cannot parse future versions: 5

You need to wait for the next release of `dldt`.
Or try models from `2018` branch of `open_model_zoo`

**Comment by RachelRen05** [comment]
@xinyuegtxy  I have encountered the same problem.

This issue is caused by the conflict of the version of OpenVINO, which is why there are two inference version in you log.
```
[ INFO ] InferenceEngine:
API version ............ 1.4
```
and
`API version ............ 1.5`

Please ensure that only a specific OpenVINO version exists in the current environment.

**Comment by xinyuegtxy** [comment]
> @xinyuegtxy
> 
> > cannot parse future versions: 5
> 
> You need to wait for the next release of `dldt`.
> Or try models from `2018` branch of `open_model_zoo`

I tried it, 2018 branch didn't work, it's also version 5

**Comment by xinyuegtxy** [comment]
> @xinyuegtxy
> 
> > cannot parse future versions: 5
> 
> You need to wait for the next release of `dldt`.
> Or try models from `2018` branch of `open_model_zoo`

It means I can only use dldt4 and open_model_zoo with v4??

**Comment by vmatveic** [comment]
Hi,
Yes, dldt version from the 2018/R5 branch can only handle models with max version 4. So, if you are using latest open-model-zoo version then you need to wait updated dldt release published officially (it's not completely open sourced yet while open-model-zoo is already developed on master). Thanks

**Comment by TheLostIn** [comment]
I updated openvino from R1 to R3,it helped.

**Comment by ilyachur** [comment]
Hi,

Looks like the ticket is out of date. I will close it. 
The current IR version is v 10.
Feel free to reopen it if it is still actual.
