### ISSUE TITLE
RuntimeError: Reduce node with name '493' has not found jit_uni_reduce_post_kernel_f32

### ISSUE THREAD

**Issue by mistoFENG** [openvinotoolkit/openvino#11328]
OpenVINO=> 2022.1

converte the resnet50-pytorch model to onnx

```jsx
model = torchvision.models.resnet50(pretrained=True).eval() 
dummy_input = torch.randn(1, 3, 224, 224)
torch.onnx.export(model,  (dummy_input,), 'resnet50.onnx')
```
convert onnx to xml

`mo --input_model resnet50.onnx --output_dir output/ `

Using the following script, getting an error
```jsx
from openvino.runtime import Core

ie = Core()
model_path="/model/output/resnet50.xml"
ie_loaded = ie.read_model(model=model_path)
model = ie.compile_model(model=ie_loaded, device_name="CPU")

input_layer = next(iter(model.inputs))
print("inputs: ", input_layer)
```
```jsx
raceback (most recent call last):
  File "test_openvino.py", line 9, in <module>
    model = ie.compile_model(model=ie_loaded, device_name="CPU")
  File "/usr/local/lib/python3.8/dist-packages/openvino/runtime/ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Reduce node with name '493' has not found jit_uni_reduce_post_kernel_f32.
```
Looking forward to your answer!!!  in addition, testing the VGG model will not report this error

**Comment by dmitry-gorokhov** [comment]
@mistoFENG Could you please provide HW configuration details on which the issue is reproducible?

**Comment by mistoFENG** [comment]
> @mistoFENG Could you please provide HW configuration details on which the issue is reproducible?

The error appeared in centos8.3, But I just tested it on ubuntu20.04 and no errors were reported. Maybe the interface is affected by the system?

**Comment by dmitry-gorokhov** [comment]
@mistoFENG Thanks, Could you please also share your CPU spec (like "lscpu" log) for both centos and ubuntu machines?

**Comment by dmitry-gorokhov** [comment]
@mistoFENG  Seems like your are using VM with maximum available ISA equals SSE2 (most likely default KVM behavior to support heterogeneity). Minimum supported ISA for OpenVINO CPU is SSE42: https://docs.openvino.ai/latest/openvino_docs_OV_UG_Working_with_devices.html. So my recommendation is to change your VM properties. 
On the other hand we are still trying to keep OV execution functional on older (w/o SSE42) CPUs as well. The issue your faced definitely breaks this intention so I would prefer to have this fixed. @xuchen-intel May I ask you to take a look?

**Comment by mistoFENG** [comment]
> 



> @mistoFENG Seems like your are using VM with maximum available ISA equals SSE2 (most likely default KVM behavior to support heterogeneity). Minimum supported ISA for OpenVINO CPU is SSE42: https://docs.openvino.ai/latest/openvino_docs_OV_UG_Working_with_devices.html. So my recommendation is to change your VM properties. On the other hand we are still trying to keep OV execution functional on older (w/o SSE42) CPUs as well. The issue your faced definitely breaks this intention so I would prefer to have this fixed. @xuchen-intel May I ask you to take a look?

OK, @dmitry-gorokhov , thanks for your answer, I can use it on a higher instruction set
