### ISSUE TITLE
OpenVINO downloading pages ERROR

### ISSUE THREAD

**Issue by gusye1234** [openvinotoolkit/openvino#11375]
I tried to download a released version of OpenVINO. But the download link on the official website of OpenVINO is failing.
The [latest version](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_linux.html) of the website and the [2021.4](https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_linux.html) version both offered a [failing page](https://software.intel.com/en-us/openvino-toolkit/choose-download) for downloading and then redirected me to a [Oops website](https://www.intel.com/content/www/us/en/404.html?ref=https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit-download.html).

I'm trying to share my currently-using OpenVINO version with others, and I'm curious is there anywhere else I can download OpenVINO?

**Comment by ilya-lavrenov** [comment]
@xu-yuan1 could you please have a look?

**Comment by xu-yuan1** [comment]
> @xu-yuan1 could you please have a look?

This link: https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html is referenced in documentation and is working. I think the real issue is about why is that link not working and should report this issue to the website team (marketing maybe?).

**Comment by gusye1234** [comment]
> > @xu-yuan1 could you please have a look?
> 
> This link: https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html is referenced in documentation and is working. I think the real issue is about why that link is not working for this user and we should report this issue to the website team (marketing maybe?).

Oh, shot...
This page works for me too now. But this page's UI style changed a lot from what I remembered. 
I think this issue can be closed now. Thanks
