### ISSUE TITLE
device_name changed gpu error[Bug]

### ISSUE THREAD

**Issue by Deep-learning999** [openvinotoolkit/openvino#11382]
![Uploading Screenshot_20220331_225553.jpg…]()

##### System information (version)
<!-- Example
- OpenVINO => 2022.1
- Operating System / Platform => Ubuntu18.04
- Problem classification: Model Conversion
- Framework: pytorch (if applicable)

**Comment by ilya-lavrenov** [comment]
@Deep-learning999 could you please re-upload the picture?
