### ISSUE TITLE
Error when reading custom trained model 

### ISSUE THREAD

**Issue by vyang2968** [openvinotoolkit/openvino#11417]
I have trained a custom SSD_MobileNet V2 FPNLite 320x320 model and I was successfully able to export it using the Model Optimizer.  I am trying to get the Inference Engine on Raspberry Pi 4 with Neural Compute Stick to read my exported model through the code
```
from openvino.inference_engine import IECore
xml = 'ssd_mobnet_openvino/saved_model.xml'
bin = 'ssd_mobnet_openvino/saved_model.bin'
ie = IECore()
network = ie.read_network(xml, bin)
```
which throws error
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    network = ie.read_network(xml, bin)
  File "ie_api.pyx", line 357, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 400, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Unknown model format! Cannot find reader for model format: xml and read the model: ssd_mobnet_openvino/saved_model.xml. Please check that reader library exists in your PATH.
```
I will be more than happy to provide any files or any other information. 
Thanks in advance.

**Comment by Killerkiwi2005** [comment]
Getting the same issue I think the mo is creating a newer xml version then the precompiled openvino version supports..

**Comment by ilyachur** [comment]
@vyang2968 Could you share IR file?

**Comment by vyang2968** [comment]
Export from Model Optimizer:
[ssd_mobnet_openvino.zip](https://github.com/openvinotoolkit/openvino/files/8406783/ssd_mobnet_openvino.zip)

**Comment by brmarkus** [comment]
From "saved_model.xml" in your ZIP-file it looks like the model is in IR version "11":
    <?xml version="1.0" ?>
    <net name="saved_model" version="11">
        	<layers>
Do you run the Model-Optimizer from the same OpenVINO installer (on the same machine) as you actually want to run your application?
It looks like you used a Model-Optimizer from a newer version of OpenVINO (supporting IR version v11) than you run your application (on your Raspberry Pi 4) with.

**Comment by vyang2968** [comment]
Taking into consideration what @Killerkiwi2005 said, OpenVINO on my Raspberry Pi 4 with 32-bit Buster OS is in OpenVINO 2021.4.752 as that is the latest version I could find for it. However, I converted my SSD MobileNet model with OpenVINO 2022.1, the latest version. The differences in version may be a problem. 

I attempted to take a shot at this by downgrading to OpenVINO 2021.4.2 and converting my Tensorflow model in the same way I did with OpenVINO 2022.1, but I was presented with the error `[ FRAMEWORK ERROR ]  Cannot load input model: SavedModel format load failure: Unknown SavedObject type: None`

**Comment by vyang2968** [comment]
\

> From "saved_model.xml" in your ZIP-file it looks like the model is in IR version "11":
> 
> > < net name="saved_model" version="11" >
> 
> Do you run the Model-Optimizer from the same OpenVINO installer (on the same machine) as you actually want to run your application? It looks like you used a Model-Optimizer from a newer version of OpenVINO (supporting IR version v11) than you run your application (on your Raspberry Pi 4) with.

I used Model Optimizer on Colab with `pip install openvino-dev[tensorflow2]` which uses OpenVINO 2022.1. I don't believe I can use Model Optimizer on Raspberry Pi because it doesn't come in the installation.

**Comment by ilyachur** [comment]
@vyang2968 2021.4 release of OpenVINO doesn't support IR v11.
You use v11 IR, to load it please use OpenVINO 2022.1

**Comment by vyang2968** [comment]
> @vyang2968 2021.4 release of OpenVINO doesn't support IR v11. You use v11 IR, to load it please use OpenVINO 2022.1

How can I use Model Optimizer to export my Tensorflow model so that it will work for Raspberry Pi 4 OpenVINO 2021.4.2?

**Comment by ilyachur** [comment]
> > @vyang2968 2021.4 release of OpenVINO doesn't support IR v11. You use v11 IR, to load it please use OpenVINO 2022.1
> 
> How can I use Model Optimizer to export my Tensorflow model so that it will work for Raspberry Pi 4 OpenVINO 2021.4.2?

@vyang2968 Please use MO from the OpenVINO 2021.4 distribution.

**Comment by vyang2968** [comment]
Thank you all for your responses. They were of great help to me. I got it all figured out and I was able to convert my model successfully. The issue I described previously with the model from the Tensorflow Model Zoo converting and my custom model not converting seems to be a one-time occurrence. I retrained my model and I was able to convert it successfully.  I use the command `mo --saved_model_dir /content/TFODCourse/Tensorflow/workspace/models/ssd_mobnet/export/saved_model --reverse_input_channels --input_shape=[1,320,320,3] --transformations_config /content/ssd_support_api_v2.4.json --tensorflow_object_detection_api_pipeline_config /content/TFODCourse/Tensorflow/workspace/models/ssd_mobnet/export/pipeline.config --data_type FP16`. I am now able to inference on my Raspberry Pi 4 with Neural Compute Stick 2. Again, thank you guys.
