### ISSUE TITLE
[Bug] benchmark_app warning while trying to use video as input

### ISSUE THREAD

**Issue by js333031** [openvinotoolkit/openvino#11484]
[This link](https://www.intel.com/content/www/us/en/develop/documentation/edge-insights-amr-2022-1-doc/top/tutorials/tutorials-amr/run-openvino-benchmarking-tool.html) and my own attempt at running benchmark_app with input video shows following warning:

`[ WARNING ] No supported image inputs found! Please check your file extensions: bmp, dib, jpeg, jpg, jpe, jp2, png, pbm, pgm, ppm, sr, ras, tiff, tif`

I'm trying [this video](https://mirror.clarkson.edu/blender/demo/movies/BBB/bbb_sunflower_1080p_30fps_normal.mp4) as the input file to benchmark app

**Comment by jgespino** [comment]
@js333031 Edge Insights for AMR package includes OpenVINO 2021.4 release. Looking at the benchmark_app from 2021.4 branch, the sample application only supports image and binary file. You can confirm by running` benchmark_app -h`.

https://github.com/openvinotoolkit/openvino/tree/2021.4/tools/benchmark

` -i "<path>"                 Optional. Path to a folder with images and/or binaries or to specific image or binary file. `

I will submit a ticket to the appropriate team to update the Edge Insights for AMR documentation.

**Comment by js333031** [comment]
The benchmark_app in this case is the C++ app, not Python. In any case, was the AMR package using a modified benchmark_app. If you look at the AMR benchmark link provided in original issue submission, the input of the app specified a video whereas the execution of the app ended up using random input data due to video input not supported.  So this issue needs to be brought up to the AMR team.

**Comment by jgespino** [comment]
@js333031 I meant to link to the cpp sample, my last response applies to the C++ sample as well.

https://github.com/openvinotoolkit/openvino/tree/2021.4/inference-engine/samples/benchmark_app
`-i "<path>"                 Optional. Path to a folder with images and/or binaries or to specific image or binary file.`

I have provided your feedback to the development team for consideration.

Ref. 83961
