### ISSUE TITLE
Disable AVX512F Failed

### ISSUE THREAD

**Issue by mistoFENG** [openvinotoolkit/openvino#11487]
- openvino version : 2022.1
- CPU : Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz  
- Operating System : ubuntu20.04

Hi, I want to  disable AVX512 in the CPU, try to build  Open Source OpenVINO, the command is as follows:
```jsx
cmake   -DCMAKE_BUILD_TYPE=Release -DENABLE_AVX512F=OFF -DENABLE_INTEL_GPU=OFF -DENABLE_INTEL_GNA=OFF \
-DENABLE_INTEL_MYRIAD=OFF -ENABLE_INTEL_MYRIAD_COMMON=OFF -DENABLE_PYTHON=ON \
-DPYTHON_EXECUTABLE=`which python3.8` -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.8.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.8 ..
```
after  the build is successful, I test benchmark of resnet50:
`/openvino/bin/intel64/Release/benchmark_app -m openvino/fp32/resnet50_v1.xml -b 1 -d CPU -pc`
the following is a part of results:
```jsx
Convolution_2571              EXECUTED       layerType: Convolution        realTime: 288       cpu: 288             execType: jit_avx512_1x1_FP32
485                           NOT_RUN        layerType: Relu               realTime: 0         cpu: 0               execType: undef
Convolution_2620              EXECUTED       layerType: Convolution        realTime: 609       cpu: 609             execType: jit_avx512_FP32
488                           NOT_RUN        layerType: Relu               realTime: 0         cpu: 0               execType: undef
Convolution_2669              EXECUTED       layerType: Convolution        realTime: 277       cpu: 277             execType: jit_avx512_1x1_FP32
```
why is the exectype still avx512, looking forward for your help! thx!

**Comment by jgespino** [comment]
@mistoFENG I built openvino from source without avx512 optimizations and can see the execType: jit_avx512_FP32 when running benchmark_app. According to the documentation, **"Affects only Inference Engine common part and preprocessing plugin, does not affect the mkldnn library"**. 

Let me investigate further and get back to you.

**Comment by jgespino** [comment]
@mistoFENG Apologies for the delay, I've confirmed with my peers that turning off `-DENABLE_AVX512F` only disables the optimizations. The OpenVINO CPU Plugin is leveraging oneDNN implementation which use Xbyak, a JIT assembly template library to generate kernels and it may not be possible to turn it off.

In this case, oneDNN will use avx512 opsets to accelerate the layer execution in runtime.
