### ISSUE TITLE
Build open_model_zoo demos falied

### ISSUE THREAD

**Issue by xiuxiusen** [openvinotoolkit/openvino#11481]
- OpenVINO => 2021.4
- Operating System / Platform => Ubuntu-mate 20.04
- Compiler => gcc
When I use openvino in my rpi 4b ,I tried to build demos with open_model_zoo,but somehow it made some mistakes.The error information is like this.
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:26:43: error: ‘dlib’ has not been declared
   26 | extern std::string eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                           ^~~~
In file included from /home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:31:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp: At global scope:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp:26:35: error: ‘dlib’ has not been declared
   26 | extern int eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                   ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:26:65: error: expected ‘,’ or ‘...’ before ‘pos_model’
   26 | extern std::string eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                                                 ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp:26:57: error: expected ‘,’ or ‘...’ before ‘pos_model’
   26 | extern int eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                                         ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:27:8: error: ‘dlib’ does not name a type
   27 | extern dlib::shape_predictor loadModel();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp:27:8: error: ‘dlib’ does not name a type
   27 | extern dlib::shape_predictor loadModel();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:28:8: error: ‘dlib’ does not name a type
   28 | extern dlib::frontal_face_detector loadDetector();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp:28:8: error: ‘dlib’ does not name a type
   28 | extern dlib::frontal_face_detector loadDetector();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp: In function ‘int main(int, char**)’:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:389:2: error: ‘dlib’ has not been declared
  389 |  dlib::shape_predictor pos_model = loadModel();
      |  ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:390:2: error: ‘dlib’ has not been declared
  390 |  dlib::frontal_face_detector detector = loadDetector();
      |  ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/main.cpp: In function ‘int main(int, char**)’:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/main.cpp:255:2: error: ‘dlib’ has not been declared
  255 |  dlib::shape_predictor pos_model = loadModel();
      |  ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/main.cpp:256:2: error: ‘dlib’ has not been declared
  256 |  dlib::frontal_face_detector detector = loadDetector();
      |  ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:599:25: error: ‘pos_model’ was not declared in this scope
  599 |    eye_func(curr_frame, pos_model, detector);
      |                         ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:599:36: error: ‘detector’ was not declared in this scope; did you mean ‘detection’?
  599 |    eye_func(curr_frame, pos_model, detector);
      |                                    ^~~~~~~~
      |                                    detection

I have tied to install dlib in my system from this link.But it made no sense.
https://stackoverflow.com/questions/50545025/how-can-i-add-dlib-in-cmake-with-findpackage

**Comment by xiuxiusen** [comment]
- OpenVINO => 2021.4
- Operating System / Platform => Ubuntu-mate 20.04
- Compiler => gcc
When I use openvino in my rpi 4b ,I tried to build demos with open_model_zoo,but somehow it made some mistakes.The error information was followed.
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:26:43: error: ‘dlib’ has not been declared
   26 | extern std::string eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                           ^~~~
In file included from /home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:31:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp: At global scope:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp:26:35: error: ‘dlib’ has not been declared
   26 | extern int eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                   ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:26:65: error: expected ‘,’ or ‘...’ before ‘pos_model’
   26 | extern std::string eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                                                 ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp:26:57: error: expected ‘,’ or ‘...’ before ‘pos_model’
   26 | extern int eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                                         ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:27:8: error: ‘dlib’ does not name a type
   27 | extern dlib::shape_predictor loadModel();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp:27:8: error: ‘dlib’ does not name a type
   27 | extern dlib::shape_predictor loadModel();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:28:8: error: ‘dlib’ does not name a type
   28 | extern dlib::frontal_face_detector loadDetector();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/include/dlib_face.hpp:28:8: error: ‘dlib’ does not name a type
   28 | extern dlib::frontal_face_detector loadDetector();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp: In function ‘int main(int, char**)’:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:389:2: error: ‘dlib’ has not been declared
  389 |  dlib::shape_predictor pos_model = loadModel();
      |  ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:390:2: error: ‘dlib’ has not been declared
  390 |  dlib::frontal_face_detector detector = loadDetector();
      |  ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/main.cpp: In function ‘int main(int, char**)’:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/main.cpp:255:2: error: ‘dlib’ has not been declared
  255 |  dlib::shape_predictor pos_model = loadModel();
      |  ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/main.cpp:256:2: error: ‘dlib’ has not been declared
  256 |  dlib::frontal_face_detector detector = loadDetector();
      |  ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:599:25: error: ‘pos_model’ was not declared in this scope
  599 |    eye_func(curr_frame, pos_model, detector);
      |                         ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo_meng/main.cpp:599:36: error: ‘detector’ was not declared in this scope; did you mean ‘detection’?
  599 |    eye_func(curr_frame, pos_model, detector);
      |                                    ^~~~~~~~
      |                                    detection
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/main.cpp:528:47: error: ‘pos_model’ was not declared in this scope
  528 |    std::string face_data=eye_func(curr_frame, pos_model, detector);
      |                                               ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/main.cpp:528:58: error: ‘detector’ was not declared in this scope; did you mean ‘detection’?
  528 |    std::string face_data=eye_func(curr_frame, pos_model, detector);
      |                                                          ^~~~~~~~
      |                                                          detection
make[2]: *** [human_pose_estimation_demo_meng/CMakeFiles/human_pose_estimation_demo_meng.dir/build.make:63: human_pose_estimation_demo_meng/CMakeFiles/human_pose_estimation_demo_meng.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:319: human_pose_estimation_demo_meng/CMakeFiles/human_pose_estimation_demo_meng.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [human_pose_estimation_demo/CMakeFiles/human_pose_estimation_demo.dir/build.make:63: human_pose_estimation_demo/CMakeFiles/human_pose_estimation_demo.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 57%] Building CXX object human_pose_estimation_demo/CMakeFiles/human_pose_estimation_demo.dir/src/dlib_face.cpp.o
In file included from /home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:5:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:26:43: error: ‘dlib’ has not been declared
   26 | extern std::string eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                           ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:26:65: error: expected ‘,’ or ‘...’ before ‘pos_model’
   26 | extern std::string eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector);
      |                                                                 ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:27:8: error: ‘dlib’ does not name a type
   27 | extern dlib::shape_predictor loadModel();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/include/dlib_face.hpp:28:8: error: ‘dlib’ does not name a type
   28 | extern dlib::frontal_face_detector loadDetector();
      |        ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:8:17: error: ‘dlib’ is not a namespace-name
    8 | using namespace dlib;
      |                 ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:19:1: error: ‘dlib’ does not name a type
   19 | dlib::shape_predictor loadModel()
      | ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:29:1: error: ‘dlib’ does not name a type
   29 | dlib::frontal_face_detector loadDetector()
      | ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:35:36: error: ‘dlib’ has not been declared
   35 | std::string eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector)
      |                                    ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:35:58: error: expected ‘,’ or ‘...’ before ‘pos_model’
   35 | std::string eye_func(cv::Mat temp, dlib::shape_predictor pos_model, dlib::frontal_face_detector detector)
      |                                                          ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp: In function ‘std::string eye_func(cv::Mat, int)’:
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:69:5: error: ‘array2d’ was not declared in this scope
   69 |     array2d<dlib::bgr_pixel> cimg;
      |     ^~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:69:13: error: ‘dlib’ has not been declared
   69 |     array2d<dlib::bgr_pixel> cimg;
      |             ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:69:30: error: ‘cimg’ was not declared in this scope
   69 |     array2d<dlib::bgr_pixel> cimg;
      |                              ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:70:24: error: ‘cv_image’ was not declared in this scope
   70 |     assign_image(cimg, cv_image<uchar>(gray));
      |                        ^~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:70:38: error: expected primary-expression before ‘>’ token
   70 |     assign_image(cimg, cv_image<uchar>(gray));
      |                                      ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:70:5: error: ‘assign_image’ was not declared in this scope
   70 |     assign_image(cimg, cv_image<uchar>(gray));
      |     ^~~~~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:72:17: error: ‘dlib’ was not declared in this scope
   72 |     std::vector<dlib::rectangle> faces = detector(cimg);
      |                 ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:72:32: error: template argument 1 is invalid
   72 |     std::vector<dlib::rectangle> faces = detector(cimg);
      |                                ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:72:32: error: template argument 2 is invalid
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:72:42: error: ‘detector’ was not declared in this scope
   72 |     std::vector<dlib::rectangle> faces = detector(cimg);
      |                                          ^~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:74:17: error: ‘full_object_detection’ was not declared in this scope
   74 |     std::vector<full_object_detection> shapes;
      |                 ^~~~~~~~~~~~~~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:74:38: error: template argument 1 is invalid
   74 |     std::vector<full_object_detection> shapes;
      |                                      ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:74:38: error: template argument 2 is invalid
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:75:28: error: request for member ‘size’ in ‘faces’, which is of non-class type ‘int’
   75 |     int faceNumber = faces.size(); //获取容器中向量的个数即人脸的个数
      |                            ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:78:16: error: request for member ‘push_back’ in ‘shapes’, which is of non-class type ‘int’
   78 |         shapes.push_back(pos_model(cimg, faces[i]));
      |                ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:78:49: error: invalid types ‘int[int]’ for array subscript
   78 |         shapes.push_back(pos_model(cimg, faces[i]));
      |                                                 ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:78:26: error: ‘pos_model’ was not declared in this scope
   78 |         shapes.push_back(pos_model(cimg, faces[i]));
      |                          ^~~~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:82:17: error: request for member ‘empty’ in ‘shapes’, which is of non-class type ‘int’
   82 |     if (!shapes.empty())
      |                 ^~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:85:33: error: request for member ‘size’ in ‘shapes’, which is of non-class type ‘int’
   85 |         int faceNumber = shapes.size();
      |                                 ^~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:91:50: error: invalid types ‘int[int]’ for array subscript
   91 |                 cv::circle(temp, cvPoint(shapes[j].part(i).x(), shapes[j].part(i).y()), 2, cv::Scalar(0, 0, 255), -1); //参数说明 图像 圆心 线条宽度 颜色 线的类型
      |                                                  ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:91:73: error: invalid types ‘int[int]’ for array subscript
   91 |                 cv::circle(temp, cvPoint(shapes[j].part(i).x(), shapes[j].part(i).y()), 2, cv::Scalar(0, 0, 255), -1); //参数说明 图像 圆心 线条宽度 颜色 线的类型
      |                                                                         ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:91:34: error: ‘cvPoint’ was not declared in this scope
   91 |                 cv::circle(temp, cvPoint(shapes[j].part(i).x(), shapes[j].part(i).y()), 2, cv::Scalar(0, 0, 255), -1); //参数说明 图像 圆心 线条宽度 颜色 线的类型
      |                                  ^~~~~~~
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:99:28: error: invalid types ‘int[int]’ for array subscript
   99 |         int x_36 = shapes[0].part(36).x();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:104:28: error: invalid types ‘int[int]’ for array subscript
  104 |         int y_37 = shapes[0].part(37).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:108:28: error: invalid types ‘int[int]’ for array subscript
  108 |         int y_38 = shapes[0].part(38).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:111:28: error: invalid types ‘int[int]’ for array subscript
  111 |         int x_39 = shapes[0].part(39).x();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:116:28: error: invalid types ‘int[int]’ for array subscript
  116 |         int y_40 = shapes[0].part(40).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:120:28: error: invalid types ‘int[int]’ for array subscript
  120 |         int y_41 = shapes[0].part(41).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:165:28: error: invalid types ‘int[int]’ for array subscript
  165 |         int x_42 = shapes[0].part(42).x();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:169:28: error: invalid types ‘int[int]’ for array subscript
  169 |         int y_43 = shapes[0].part(43).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:172:28: error: invalid types ‘int[int]’ for array subscript
  172 |         int y_44 = shapes[0].part(44).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:174:28: error: invalid types ‘int[int]’ for array subscript
  174 |         int x_45 = shapes[0].part(45).x();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:178:28: error: invalid types ‘int[int]’ for array subscript
  178 |         int y_46 = shapes[0].part(46).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:182:28: error: invalid types ‘int[int]’ for array subscript
  182 |         int y_47 = shapes[0].part(47).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:211:28: error: invalid types ‘int[int]’ for array subscript
  211 |         int x_48 = shapes[0].part(48).x();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:212:28: error: invalid types ‘int[int]’ for array subscript
  212 |         int x_54 = shapes[0].part(54).x();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:217:28: error: invalid types ‘int[int]’ for array subscript
  217 |         int y_61 = shapes[0].part(61).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:218:28: error: invalid types ‘int[int]’ for array subscript
  218 |         int y_67 = shapes[0].part(67).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:223:28: error: invalid types ‘int[int]’ for array subscript
  223 |         int y_63 = shapes[0].part(63).y();
      |                            ^
/home/xiuxiusen/intel/open_model_zoo/demos/human_pose_estimation_demo/src/dlib_face.cpp:224:28: error: invalid types ‘int[int]’ for array subscript
  224 |         int y_65 = shapes[0].part(65).y();
I have tied to install dlib in my system from this link.But it made no sense.
https://stackoverflow.com/questions/50545025/how-can-i-add-dlib-in-cmake-with-findpackage

**Comment by zulkifli-halim** [comment]
Hello @xiuxiusen. You can install dlib by using this command:

`pip3 install dlib `

To build Open Model Zoo demos, you can refer to [Build the Demo Applications on Linux](https://docs.openvino.ai/2021.4/omz_demos.html#build-the-demo-applications-on-linux).

**Comment by xiuxiusen** [comment]
@zulkifli-halim The command doesn't work.I met some error when I run the command.
ERROR:Could not find a version that satisfied the requirement dlib(from versinos: none)
ERROR: No matching distribution found for dlib

**Comment by zulkifli-halim** [comment]
@xiuxiusen try to run these commands before installing dlib:
```
python3 -m pip install --upgrade pip 
pip3 install -U pip 
pip3 install cmake
```
 
Then rerun the command to install dlib:
` pip3 install dlib`

**Comment by xiuxiusen** [comment]
I have solved the question through reinstalling openvino.And I have successfully build open_model_zoo..And the directory omz_demos_build occurs.
I use the intel realsense D435i and NCS2.
I follwoed this link https://docs.openvino.ai/latest/omz_demos_human_pose_estimation_demo_cpp.html. Then I open ~/omz_demos_build/aarch64/Release in the Terminal.
I run the commend ./human_pose_estimation_demo -i /dev/video -m ~/intel/human-pose-estimation-0001/FP16/human-pose-estimation-0001.xml -d MYRIAD
And it says connect:Connection refused.
Does anyone meet the same question?
Thanks for any help what so ever! More than happy to provide further info if required.

**Comment by brmarkus** [comment]
Can you narrow the problem down further, please? Which "connection" gets refused? Can you share log-files or console-output?

Is it related to NCS2 (e.g. missing to install udev-rules for the MyriadX NCS2)?
Is it related to the RealSense device - e.g. will it work with a local video-file or a "standard Logitec USB-webcam"?

**Comment by xiuxiusen** [comment]
I met some errors when i run the code "make -j 4"
/home/xiuxiusen/openvino/inference-engine/thirdparty/ade/sources/ade/source/execution_engine.cpp: In member function ‘std::unique_ptr<ade::Executable> ade::ExecutionEngine::createExecutable(const ade::Graph&)’:
/home/xiuxiusen/openvino/inference-engine/thirdparty/ade/sources/ade/source/execution_engine.cpp:141:21: error: redundant move in return statement [-Werror=redundant-move]
  141 |     return std::move(ret);
      |            ~~~~~~~~~^~~~~
/home/xiuxiusen/openvino/inference-engine/thirdparty/ade/sources/ade/source/execution_engine.cpp:141:21: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
make[2]: *** [inference-engine/thirdparty/ade/sources/ade/CMakeFiles/ade.dir/build.make:132: inference-engine/thirdparty/ade/sources/ade/CMakeFiles/ade.dir/source/execution_engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2858: inference-engine/thirdparty/ade/sources/ade/CMakeFiles/ade.dir/all] Error

**Comment by brmarkus** [comment]
You might revert back to your previous state where you wrote "solved the question through reinstalling openvino.And I have successfully build open_model_zoo" - using Open-Model-Zoo also in version "2021.3"?
And then focus on the connection-refused problem.

**Comment by zulkifli-halim** [comment]
Closing, please re-open if additional assistance is needed.
