### ISSUE TITLE
import/export model for GPU

### ISSUE THREAD

**Issue by ZachL1** [openvinotoolkit/openvino#11489]
I noticed that CPU and GNA devices support import/export model, while GPU plugin implementation supports only compiled kernels caching.

Compiling the model is very slow when using GPU devices. I got the model cache blob by compiling the model on my own computer using the GPU, and after that the second time I ran the program it was much faster. I would like to use this cache on my friend's computer, who has the exact same CPU and GPU as me. However, not as I thought, the program compiled the model again after porting to the new computer, even though the GPU model was exactly the same.

Is this because the kernel level cache is not portable? Is it possible for me to use the cache blob generated by computer A on computer B to speed up the first inference latency? (GPU)
Or, are you already working on GPU support for the import/export model? I desperately need to use it!

**Comment by zulkifli-halim** [comment]
Hi @ZachL1. The GPU plugin does not have the EXPORT_IMPORT capability and does not support model caching yet.

For the kernel cache portability, I’m checking this with the development team for clarification and will get back to you at the earliest.

**Comment by ZachL1** [comment]
@zulkifli-halim thanks!

Just in case you forgot about this, I took the liberty to ask if there was any progress.

**Comment by zulkifli-halim** [comment]
@ZachL1. Apologies for the delayed response.

We used benchmark_app to test a model and created _cl_cache_ directory, then copy the directory to another system with similar specs, and the model loaded fast again using the _cl_cache_ directory. Note we copied the cl_cache directory to another system and didn't recompile the model.

You can refer to this [article ](https://www.intel.com/content/www/us/en/support/articles/000057525/software/development-software.html) to improve the model load time on GPU.

Or create an ENV variable "_cl_cache_dir_" pointing to an existing and writable directory, like:

```
$> mkdir /tmp/ocl
$> export cl_cache_dir=/tmp/oc
```

Is this something that you have tried?

**Comment by zulkifli-halim** [comment]
Closing, please re-open if additional assistance is needed.
