### ISSUE TITLE
Using OpenVINO in Win32 programs

### ISSUE THREAD

**Issue by ZachL1** [openvinotoolkit/openvino#11491]
I need to build a Win32 dll, using OpenCV and OpenVINO. It seems to be possible to build 32-bit OpenCV from source, but I didn't find anything for OpenVINO. How can I use OpenVINO in my Win32 program?

I noticed #216:
>The OpenVino team has not built 32-bit for more than two years and doing so is not a priority at this time.

Is it possible for me to build 32-bit OpenVINO? I mean, build exactly as the [tutorial steps](https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows), but for Microsoft* Visual Studio 2019 Win32 architecture:
```
cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release ..
```
Or do I need to modify the source code to make it work?

**Comment by jgespino** [comment]
@ZachL1 Building OpenVINO from source is only validated on Microsoft* Windows* 10 (64-bit) with Visual Studio 2019. You may be able to compile OV but some features may not be available or work properly. Unfortunately, I don't have access to a 32-bit system to test.

I see there are a couple of commits around win32 on this repository: https://github.com/openvinotoolkit/openvino/search?q=win32&type=commits

**Comment by tomdol** [comment]
@ZachL1 could you try compiling with warnings disabled? https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-170

Try using `/w` or `/w0` in your first `cmake` call which should overwrite the warnings globally for the whole project.

**Comment by ZachL1** [comment]
@tomdol I don't think this might make me compile successfully.

I get 11 errors, the first and last two seem to be caused by warnings, and disabling warnings might avoid all three.

However there are a bunch of `error C3861: '_mm_insert_epi64': identifier not found`, which I think is probably unavoidable.

**Comment by tomdol** [comment]
I've looked around and it seems that officially only the 64-bit version of Windows is supported https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes.html

On the other hand the code which causes errors during your compilation should be switched off on a 32-bit system https://github.com/openvinotoolkit/openvino/blob/master/src/common/preprocessing/cpu_x86_sse42/ie_preprocess_gapi_kernels_sse42.cpp#L100-L122. 
I haven't tried cross compiling myself but perhaps the `-A` flag passed to cmake is not enough. Can you experiment with `--toolchain` for example?

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.

**Comment by yinghuang** [comment]
Hi, I just compile ov static library for windows10-32bit successfully, but it can't work properly.
When I compile model `core.compile_model(model_, device_name_)`
it says `failed to initialize model: Device with "CPU" name is not registered in the OpenVINO Runtime`

The source version I use is `openvino_4f1ad3bf`.
Then built-cmd I use is
```
cmake -G "Visual Studio 16 2019" -A Win32 ^
-DCMAKE_SYSTEM_NAME=Windows ^
-DCMAKE_BUILD_TYPE=Release ^
-DBUILD_SHARED_LIBS=OFF ^
-DTHREADING=TBB_AUTO ^
-DENABLE_PYTHON=OFF ^
-DENABLE_TESTS=OFF ^
-DENABLE_INTEL_MYRIAD_COMMON=OFF ^
-DENABLE_INTEL_GPU=OFF ^
-DENABLE_INTEL_GNA=OFF ^
-DENABLE_TEMPLATE=OFF ^
-DENABLE_HETERO=OFF ^
-DENABLE_MULTI=OFF ^
-DENABLE_AUTO=OFF ^
-DENABLE_AUTO_BATCH=OFF ^
-DENABLE_OV_ONNX_FRONTEND=OFF ^
-DENABLE_OV_PADDLE_FRONTEND=OFF ^
-DENABLE_OV_TF_FRONTEND=OFF ^
-DENABLE_IR_V7_READER=OFF ^
-DENABLE_GAPI_PREPROCESSING=OFF ^
-DENABLE_INTEL_CPU=ON ^
-DENABLE_OV_IR_FRONTEND=ON ^
-B%BUILD_DIR% ^
-H%CMAKE_DIR%
```
Hope more progress could be made!

**Comment by ilya-lavrenov** [comment]
Hi @yinghuang 
Why do you need 32bits?
CPU plugin is not available for 32 bits

**Comment by yinghuang** [comment]
> Hi @yinghuang Why do you need 32bits? CPU plugin is not available for 32 bits

OK.  For some reason, we have to deploy AI apps on 32bits machiens.

**Comment by weizhao-11** [comment]
Hello, have you finally implemented the deployment of OpenVino on Windows 32？yes or no

**Comment by ilya-lavrenov** [comment]
no

**Comment by 1610101442** [comment]
> > Hi @yinghuang Why do you need 32bits? CPU plugin is not available for 32 bits
> 
> OK. For some reason, we have to deploy AI apps on 32bits machiens.

**Excuse me, may I ask if you have completed the Windows 32-bit openvino**
