### ISSUE TITLE
Install OpenVINO on Cortex-A53 (aarch64)

### ISSUE THREAD

**Issue by vleonn** [openvinotoolkit/openvino#11500]
Hello, I would like to install OpenVINO on the ARM processor of Xilinx US+ MPSoC FPGA.

From what I have seen, there is no ready-to-use docker or installation instructions specifically for aarch64.
The installer option does not work, while building it from source (Linux instructions) stacks at ~45%.

Therefore, I would like to ask for any suggestions/solutions or any comments on this.

Setup:
- ARM Cortex-A53 (on Xilinx US+ MPSoC)
- aarch64
- Linux 5.4.0-1015-xilinx-zynqmp # 18-Ubuntu SMP (Ubuntu 20.04.2 LTS)  

Thank you in advance.

**Comment by Iffa-Meah** [comment]
@vleonn ,

As of now, there are 3 options to install OpenVINO:
1. [Install OpenVINO runtime](https://docs.openvino.ai/latest/openvino_docs_install_guides_install_runtime.html)
2. [Build from source (GitHub)](https://github.com/openvinotoolkit/openvino/wiki/BuildingCode)
3. [Install OpenVINO Development Tools (from PyPI)](https://docs.openvino.ai/latest/openvino_docs_install_guides_install_dev_tools.html)

From what you've said above, it seems that options 1 and 2 are not applicable. You may try option 3 as a workaround.

Please note that only ARM64 (**Raspberry Pi**) is officially supported. You may refer [here](https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html).

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
