### ISSUE TITLE
[MO] onnx if operand is not supported

### ISSUE THREAD

**Issue by AIHHU** [openvinotoolkit/openvino#11509]
##### Detailed description
ONNX if operand is not supported as in the picture. Are there any solutions to this problem?
![O$8W9D}YXT) 87}0% $MEOV](https://user-images.githubusercontent.com/66868438/163095054-96b2f531-2cb1-47fd-8935-ac7218823fd6.png)

**Comment by mateusztabaka** [comment]
Hi, can you update to 2022.1? If operator is supported in that release.
