### ISSUE TITLE
[Bug] Tensorflow Dynamic Shapes not support in mo?

### ISSUE THREAD

**Issue by GuoGuiRong** [openvinotoolkit/openvino#11504]
##### System information (version)
OpenVINO => 2021.4.1
use 
```
mo --saved_model_dir "/root/open_model_zoo_models/custom/origin_model" --data_type FP16 --input dense_input,seq_50_input,sparse_ids_input,sparse_wgt_input --input_shape [1..100,587],[1..100,6,50],[1..100,53],[1..100,53] --output_dir "/root/open_model_zoo_models/custom/fp16"
```
then return: 
 ERROR ]  Input shape "[1..100,587],[1..100,6,50],[1..100,53],[1..100,53]" cannot be parsed. 

I refer the doc: https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model.html

**Comment by brmarkus** [comment]
Your referenced link to the documentation refers to the latest version, which currently is 2021.1 - supporting dynamic shapes.

You are using OpenVINO v2021.4.1?
Then this is the corresponding documentation:
https://docs.openvino.ai/2021.4/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model.html
(not supporting dynamic shapes)

**Comment by GuoGuiRong** [comment]
thank you, so I need update my openvion to 2022.1. Then Dynamic Shapes will be supported.

**Comment by jgespino** [comment]
@GuoGuiRong OpenVINO is no longer supported on CentOS starting with 2022.1 release. This is mentioned in the release notes for 2021.4.

> Intel Distribution of OpenVINO toolkit will continue support for Red Hat* Enterprise Linux* (RHEL*) 8 and will drop support for CentOS in new releases starting 2022.1 (Q1’22).
