### ISSUE TITLE
  I want to integrate openvino into ffmpeg. Where are the latest header files and library files? 

### ISSUE THREAD

**Issue by cvDFT** [openvinotoolkit/openvino#11502]
I want to integrate openvino into ffmpeg. Where are the latest header files and library files? Failed to specify the openino path

root@xh-ROG-Zephyrus-M16-GU603HM-GU603HM:/home/xh/ffmpeg/build# ../configure --enable-libopenvino --extra-cflags=-I/home/xh/intel/openvino_2022.1.0.643/runtime/include --extra-ldflags=-L/home/xh/intel/openvino_2022.1.0.643/runtime/lib/intel64
ERROR: libopenvino not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by jgespino** [comment]
@cvDFT Did you build OpenVINO from source? According to this commit (https://github.com/FFmpeg/FFmpeg/commit/87cb24a1ca4a76e5a5a9969e3058a94d952e1b37) you need to build OpenVINO from source with C library enabled for GPU (`-DENABLE_CLDNN=ON`).

Built instructions can be found [here](https://github.com/openvinotoolkit/openvino/wiki/BuildingCode).

**Comment by cvDFT** [comment]
Thank you for your reply. I want to know how to deal with runtime libraries if I want to integrate openvino into my client?

**Comment by jgespino** [comment]
@cvDFT I successfully built FFmpeg using OpenVINO 2021.4.2 but same steps failed for OpenVINO 2022.1. I am reaching out to my peers for additional guidance. I will let you know what I find out.

OpenVINO 2021.4.2:
```
source /opt/intel/openvino_2021.4.752/bin/setupvars.sh 
cd Downloads/FFmpeg/build/
../configure --enable-libopenvino --extra-cflags='-I /opt/intel/openvino_2021/deployment_tools/inference_engine/include' --extra-ldflags='-L /opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64'
make
./ffmpeg --help
```

OpenVINO 2022.1:
```
source /opt/intel/openvino_2022/setupvars.sh
cd Downloads/FFmpeg/build/
../configure --enable-libopenvino --extra-cflags='-I /opt/intel/openvino_2022/runtime/include/ie' --extra-ldflags='-L /opt/intel/openvino_2022/runtime/lib/intel64'

ERROR: libopenvino not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

```

**Comment by cvDFT** [comment]
> @cvDFT I successfully built FFmpeg using OpenVINO 2021.4.2 but same steps failed for OpenVINO 2022.1. I am reaching out to my peers for additional guidance. I will let you know what I find out.
> 
> OpenVINO 2021.4.2:
> 
> ```
> source /opt/intel/openvino_2021.4.752/bin/setupvars.sh 
> cd Downloads/FFmpeg/build/
> ../configure --enable-libopenvino --extra-cflags='-I /opt/intel/openvino_2021/deployment_tools/inference_engine/include' --extra-ldflags='-L /opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64'
> make
> ./ffmpeg --help
> ```
> 
> OpenVINO 2022.1:
> 
> ```
> source /opt/intel/openvino_2022/setupvars.sh
> cd Downloads/FFmpeg/build/
> ../configure --enable-libopenvino --extra-cflags='-I /opt/intel/openvino_2022/runtime/include/ie' --extra-ldflags='-L /opt/intel/openvino_2022/runtime/lib/intel64'
> 
> ERROR: libopenvino not found
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.
> ```

It seems that ffmpeg only supports DNN now. Is that right？

**Comment by jgespino** [comment]
@cvDFT OpenVINO 2022.1 had some major changes, Use the steps below to build FFmpeg for 2022.1 release.

Modify configure file: https://github.com/FFmpeg/FFmpeg/blob/master/configure#L6580
From:
`enabled libopenvino       && require libopenvino c_api/ie_c_api.h ie_c_api_version -linference_engine_c_api`
To:
`enabled libopenvino       && require libopenvino c_api/ie_c_api.h ie_c_api_version -lopenvino_c`

`../configure --enable-libopenvino --extra-cflags=-I /opt/intel/openvino_2022/runtime/include/ie/ --extra-ldflags=-L /opt/intel/openvino_2022/runtime/lib/intel64/ --extra-ldflags=-L /opt/intel/openvino_2022/runtime/3rdparty/tbb/lib/`
