### ISSUE TITLE
[MO]RuntimeError: While validating ONNX node '<Node(Slice): Slice_424>': bad_weak_ptr

### ISSUE THREAD

**Issue by mrhe13** [openvinotoolkit/openvino#11517]
##### Detailed description
I'm try to convert my onnx file to IR files.The Input shape:[1,2,-1,161],so the third dimension is changeable.However i met this:
![bug](https://user-images.githubusercontent.com/79364519/163323973-2b165722-5329-4d9e-a02a-62e7996b0c3f.png)

Why this happen?Thanks!!

**Comment by mbencer** [comment]
Hi @mrhe13!
Could you provide the model which causes such a problem?
If your model is protected, could you please at least provide fragment of the model which constains this problematic Slice operator (more details about cutting onnx models you find in https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#extracting-sub-model-with-inputs-outputs-tensor-names)

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.

**Comment by luvwinnie** [comment]
I'm facing the same error which shows on Slice node when validating the model.
The model I'm trying to export is a shape with (batch,n_steps,512) --> (-1,-1,512) , the below is the partial of my model.
Does anyone solved this?
![Screen Shot 2022-05-23 at 16 05 23](https://user-images.githubusercontent.com/13714992/169762907-0f7e9a6d-6af9-4b3a-bacd-4f9688def99e.png)


Errors
```
Advanced parameters:
	- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: 	False
	- Force the usage of new Frontend of Model Optimizer for model conversion into IR: 	False
OpenVINO runtime found in: 	/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino
OpenVINO runtime version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  While validating ONNX node '<Node(Slice): Slice_26>':
bad_weak_ptr
[ ERROR ]  Traceback (most recent call last):
  File "/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 394, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
  File "/misc/home/usr16/cheesiang_leow/venv_hanamaruki/lib/python3.8/site-packages/openvino/tools/mo/moc_frontend/pipeline.py", line 147, in moc_pipeline
    ngraph_function = moc_front_end.convert(input_model)
RuntimeError: While validating ONNX node '<Node(Slice): Slice_26>':
bad_weak_ptr

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```

**Comment by jgespino** [comment]
@luvwinnie Would it be possible for you to share your model? If so, please start a new issue and we can take a look.
