### ISSUE TITLE
[Bug] DynamicToStaticShape transformation for onnx::Slice of type StridedSlice ver. 1 expects DynamicShapeResolver ver. 0 as input with index 0

### ISSUE THREAD

**Issue by friend045** [openvinotoolkit/openvino#11510]
##### System information (version)
- OpenVINO => 2022.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: Model Conversion
- Framework: Pytorch -> Onnx -> **OpenVino -> Blob** 

##### Detailed description

compile_tool -m model.xml -ip U8 -d MYRIAD -VPU_NUMBER_OF_SHAVES 5 -VPU_NUMBER_OF_CMX_SLICES 5

What is happened?
![image](https://user-images.githubusercontent.com/19499221/163118897-e143ef6f-e100-4fbd-a5dd-f236b1ceb27e.png)

**Comment by jgespino** [comment]
@friend045 Please share ONNX model and model optimizer command used to convert to IR.

**Comment by friend045** [comment]
Sorry, I can't provide the Onnx model, because this is the company's project, the instruction of Onnx convert to IR is as follows.
![image](https://user-images.githubusercontent.com/19499221/163294846-38686eea-eec6-47b3-97ba-a6e0bf16026e.png)


I think the cause of the error should be caused by the ROI.
 roi = img[:,:,ymin:ymax, xmin:xmax]

**Comment by Iffa-Meah** [comment]
@friend045 ,
Fyi starting from the 2020.4 release, [OpenVINO™ supports reading native ONNX models](https://docs.openvino.ai/2021.1/openvino_docs_IE_DG_ONNX_Support.html).
However, OpenVINO doesn't provide a mechanism to specify pre-processing for the ONNX format.

Since you can't share the model files, have you verified your native ONNX model with the [OpenVINO Benchmark Python Tool](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html)?.

It should be able to infer if your model's topology is supported/compatible with OpenVINO.

**Comment by friend045** [comment]
it looks good

![image](https://user-images.githubusercontent.com/19499221/163305340-7c2bade2-7757-4abf-8bdf-b00f8e0ebbdd.png)

**Comment by Iffa-Meah** [comment]
Looking at that result, you should be good to run the compile tool with that model.

Try to run the cmd as admin and run the command (don't forget to run the setupvars beforehand): 
compile_tool.exe -ip U8 -d MYRIAD -VPU_NUMBER_OF_SHAVES 5 -VPU_NUMBER_OF_CMX_SLICES 5 -m <path_to_onnx> 

OR to produce blob file: 
compile_tool.exe -ip U8 -d MYRIAD -VPU_NUMBER_OF_SHAVES 5 -VPU_NUMBER_OF_CMX_SLICES 5 -m <path_to_onnx> -o <path_to_output_dir>\<name>.blob

**Comment by friend045** [comment]
> 查看該結果，您應該很好地使用該模型運行編譯工具。
> 
> 嘗試以管理員身份運行 cmd 並運行命令（不要忘記預先運行 setupvars）： compile_tool.exe -ip U8 -d MYRIAD -VPU_NUMBER_OF_SHAVES 5 -VPU_NUMBER_OF_CMX_SLICES 5 -m <path_to_onnx>
> 
> 或生成 blob 文件： compile_tool.exe -ip U8 -d MYRIAD -VPU_NUMBER_OF_SHAVES 5 -VPU_NUMBER_OF_CMX_SLICES 5 -m <path_to_onnx> -o <path_to_output_dir><name>.blob

![image](https://user-images.githubusercontent.com/19499221/163314382-91d93d85-6cb7-4c47-975b-7938b461872c.png)

**Comment by friend045** [comment]
The same problem
![image](https://user-images.githubusercontent.com/19499221/163317512-100ceba5-7b17-4566-b8b8-525cb5681ff8.png)

**Comment by friend045** [comment]
The same problem..
![image](https://user-images.githubusercontent.com/19499221/163317556-1558d75b-cf7c-40f8-88cb-81fc776fabd1.png)

**Comment by Iffa-Meah** [comment]
Does the same thing happen if you use these commands:

1. compile_tool.exe -d MYRIAD  -m <path_to_onnx> -o xxx.blob
2. compile_tool.exe -ip U8 -d MYRIAD  -m <path_to_onnx> -o xxx.blob

**Comment by friend045** [comment]
> 3\. compile_tool.exe -d MYRIAD -VPU_NUMBER_OF_SHAVES 5 -VPU_NUMBER_OF_CMX_SLICES 5 -m <path_to_onnx> -o xxx.blob

Yes, they are the same error.

**Comment by Iffa-Meah** [comment]
There's a known issue regarding this Dynamic Shape Resolver previously in this particular OpenVINO version (2021.1). 
Whenever the model contains a dynamic network, the DynamicShapeResolver will be automatically pushed, especially with the presence of ConvertMinimum.
It would attempt to utilize the Minimum transform even if it's actually not being used.

In 2021.2, this plugin had been disabled, and therefore this DynamicShapeResolver won't act as in 2021.1.

It is recommended for you to upgrade to OV version 2021.2 and see whether this solves your issue too.

**Comment by friend045** [comment]
Sorry, the information filled in earlier is wrong, my OpenVino is currently using 2022.1 Ver. .

**Comment by friend045** [comment]
Is there any other way to find the cause of the error? I can convert to .xml and .bin but not .blob .

**Comment by jgespino** [comment]
@friend045 Since you are unable to share the model, could you please check the following?

1. Which VPU device are you using? Are you able to run benchmark_app with your model on the VPU device (MYRIAD or HDDL)?
2. Are all the layers/ops [supported](https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html) by VPU device?
3. Are you able to provide a piece of the model that reproduces the issue?
4. Does your model contain dynamic shapes? Currently dynamic shapes are only supported on CPU device.

**Comment by friend045** [comment]
Sample Model：[https://drive.google.com/drive/folders/1ze7vYnc_Z6Xtwxi2wWYrdhViJ4xh61mP?usp=sharing](https://drive.google.com/drive/folders/1ze7vYnc_Z6Xtwxi2wWYrdhViJ4xh61mP?usp=sharing)

1.  [OpenCV AI Kit: OAK—D ](https://store.opencv.ai/products/oak-d)
2.  I think it's gonna work
3. After discussing with the supervisor, we can provide a piece of the model that reproduces the issue
4.  Likely to be

  
Thanks.

**Comment by friend045** [comment]
> @friend045感謝提供模型！我能夠在 2022.1 版本上使用 cpp benchmark_app 重現該問題。
> 
> 我認為問題在於 imgDepth 輸入後的 Slice 操作。您能否嘗試指定此操作的開始和結束？目前只指定了軸和步。我相信如果開始、結束、步驟或軸中的至少一個不是恆定的，模型優化器將設置動態尺寸。由於 MYRIAD 不支持動態形狀，它將無法加載模型。
> 
> ![圖片](https://user-images.githubusercontent.com/18014973/164062753-d5c1676e-82bc-41ca-97d2-c17d1027de15.png)



So I can't crop a face on MYRIAD with top(x,y) bottom(x,y) in my model? Are there other methods?

**Comment by jgespino** [comment]
@friend045 I am not familiar with what these operations are doing. However, I suspect this input is being set to dynamic which are not supported by myriad. If you could please help me confirm this is the case. If setting the starts and ends still reproduce the error I can open a bug with the development team to further investigate.
