### ISSUE TITLE
After changing the model from fp32 to fp16, the reasoning is abnormal

### ISSUE THREAD

**Issue by cvDFT** [openvinotoolkit/openvino#11523]
![image](https://user-images.githubusercontent.com/94675255/163379829-fb881737-cabe-4e2b-beff-9792123d4a5f.png)
![image](https://user-images.githubusercontent.com/94675255/163379883-8b5f0b8c-7f4f-4c93-b835-35ad47c08204.png)

**Comment by brmarkus** [comment]
Can you try to rephrase your problem statement, please?

You don't get an error from model-optimizer, right?

Your error is caused by `cv2.resize(pha, (W, H)))`, right?
So, the passed data seem to be wrong... wrong type, wrong structure...

**Comment by cvDFT** [comment]
@brmarkus yes，thank you
