### ISSUE TITLE
After changing the model from fp32 to fp16, opencv is abnormal

### ISSUE THREAD

**Issue by cvDFT** [openvinotoolkit/openvino#11528]
![image](https://user-images.githubusercontent.com/94675255/163659555-cfc55ab7-acb6-4b39-9f0d-9c71ab6b7dcb.png)
There will be problems with the resize function of OpenCV. Is there a solution？

**Comment by brmarkus** [comment]
Can you share more of the code and describe your model, please?
It might be missing error-handling in the code prior to trying to call "cv2.resize()".
Can you check the data-type and content of `frame_np`, please? You might check with just displaying the content using something like `cv2.imshow( 'test image', frame_np )`.

**Comment by brmarkus** [comment]
Any new insights from your other issue "https://github.com/openvinotoolkit/openvino/issues/11523"?

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
