### ISSUE TITLE
[Question] Unsupported Layer Type "FakeQuantize"

### ISSUE THREAD

**Issue by vyang2968** [openvinotoolkit/openvino#11529]
I am trying to inference using a Raspberry Pi 4 and NCS2 using a custom-trained SSD MobileNet V2 FPN Lite 320x320 model from Tensorflow. I have successfully converted the SSD model to IR format using the Model Optimizer and am now looking to improve the model even further. As of right now, my model is inferencing at around 7-8 fps max. I know the NCS2 is capable of more because I ran a face detection model from Intel's Open Model Zoo and it was running at around 20-25 fps, near the FPS limit of my webcam. I looked to the Post-Training Optimization Tool to achieve this. In Colab, I ran the command `!pot -c /content/optimization_config.json` where `optimization_config.json` contains the following 
```
{
    "model": {
        "model_name": "openvino", 
        "model": "/content/drive/MyDrive/final_openvino/saved_model.xml",
        "weights": "/content/drive/MyDrive/final_openvino/saved_model.bin" 
    },


    "engine": {
        "type": "simplified",
        "layout": "NCHW",   
        "data_source": "/content/dataset"
    },


    "compression": {
        "target_device": "MYRIAD", 
        "algorithms": [
            {
                "name": "DefaultQuantization", 
                "params": {
                    "preset": "performance", 

                    "stat_subset_size": 300  
                }
            }
        ]
    }
}
```
When I ran this, it said the model was finished quantizing because it outputted a new XML and BIN file. However, there was a lot of errors such as `[ ERROR ] Changing Const node '157315758584' data type from float32 to float16 for Elementwise operation
[ WARNING ]  Changing Const node '157315758584' data type from float32 to float16 for Elementwise operation`. However, I just went with it and sent this model to the Inference Engine. When I ran my object detection file, it came up with this error 
```
Traceback (most recent call last):
  File "vid_detect.py", line 165, in <module>
    main()
  File "vid_detect.py", line 43, in main
    exec_network = core.load_network(network=network, device_name='MYRIAD')
  File "ie_api.pyx", line 403, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 442, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: [ GENERAL_ERROR ]
/home/jenkins/agent/workspace/private-ci/ie/build-linux-debian_9_arm/b/repos/openvino/inference-engine/src/vpu/graph_transformer/src/frontend/frontend.cpp:441 Failed to compile layer "StatefulPartitionedCall/ssd_mobile_net_v2_fpn_keras_feature_extractor/model/Conv1/Conv2D/fq_input_0": unsupported layer type "FakeQuantize"
```

I'm not sure how to resolve this issue, so any help would be greatly appreciated. I am happy to provide any additional information. Thanks in advance. 

I used OpenVINO 2021.4.2 for everything, including Colab.

**Comment by brmarkus** [comment]
You went through the process of "INT8 quantization" successfully, seems like.
However, those INT8 quantized models (and such fake-quantization) layer types are not supported with MyriadX/NCS2 to my knowledge.

For comparison, do you want to try the model `ssdlite_mobilenet_v2` from OpenModelZoo and check the framerate?

**Comment by vyang2968** [comment]
> You went through the process of "INT8 quantization" successfully, seems like. However, those INT8 quantized models (and such fake-quantization) layer types are not supported with MyriadX/NCS2 to my knowledge.
> 
> For comparison, do you want to try the model `ssdlite_mobilenet_v2` from OpenModelZoo and check the framerate?

I ran the ssdlite_mobilenet_v2 from OpenModelZoo and received a framerate of around 7 fps as well. I'm not sure if this is normal or not. The whole point of me attempting to use the Post Training Optimization Tool is to make my inferencing faster. Is there anyway else I can make inference faster if the POT does not work?

**Comment by vyang2968** [comment]
I'm going to close this issue because the problem has been solved and will open an new issue about speeding up models for NCS2. Thank you!
