### ISSUE TITLE
How to quickly preview for others?

### ISSUE THREAD

**Issue by cvDFT** [openvinotoolkit/openvino#11522]
I wrote a demo in Python using openvino runtime. How can I quickly package it into an executable program and share it with others to demonstrate the effect

**Comment by brmarkus** [comment]
Depending on which version of OpenVINO you are using (latest 2021.1 or older like 2021.4.2), you can check the _OpenVINO Deployment Manager_:
https://docs.openvino.ai/latest/openvino_docs_install_guides_deployment_manager_tool.html

**Comment by cvDFT** [comment]
> 根据您使用的OpenVINO版本（最新的2021.1或更早版本，如2021.4.2），您可以检查_OpenVINO部署管理器_：https://docs.openvino.ai/latest/openvino_docs_install_guides_deployment_manager_tool.html

I know this method, but it doesn't seem to be a simple demonstration method

**Comment by cvDFT** [comment]
> Depending on which version of OpenVINO you are using (latest 2021.1 or older like 2021.4.2), you can check the _OpenVINO Deployment Manager_: https://docs.openvino.ai/latest/openvino_docs_install_guides_deployment_manager_tool.html

I know this method, but it doesn't seem to be a simple demonstration method

**Comment by brmarkus** [comment]
You application is a Python application and you installed OpenVINO and its dependencies via `pip`?
Have you created a Python virtual environment?

Then you might just get the installed packages of the virtual environment via `pip3 freeze > myrequirements.txt`.

Then you can inform others about to install those requirements in a virtual environment via `pip install -U -r myrequirements.txt` as well (you might tell them how to create a virtual environment). 

And you package your source-code and model-files, config files, etc. via a simple ZIP-archive.

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
