### ISSUE TITLE
Apple silicon (M1) prebuilt openvino with arm plugin wheels released on PyPI

### ISSUE THREAD

**Issue by cansik** [openvinotoolkit/openvino#11554]
I have created an [automated script](https://github.com/cansik/openvino-arm) to build openvino for Apple silicon (M1) Mac (BigSur `11` and Monterey `12`). The build uses the [openvino-contrib arm plugin](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin) to allow networks to be run on arm64 Macs. The release is meant for developers to have an easy way to tryout native openvino on Mac M1. There are still some know issues which is why I would not recommend to use it for production (at the end of this issue).

The prebuilt binaries are hosted on [PyPI](https://pypi.org/project/openvino-arm/) which makes the installation as simple as possible:

```
pip install openvino-arm
```

If you want to include openvino in a `requirements.txt`, I would suggest the following two lines to either install the default version or the Apple silicon version:

```
openvino>=2022.1.0; platform_system != "Darwin" and platform.machine != 'arm64'
openvino-arm>=2022.1.0; platform_system == "Darwin" and platform.machine == 'arm64'
```

I look forward to feedback and suggestions from the community.
Hopefully the official openvino wheels will be updated soon to support Apple silicon.

### Know Issues
- It seems that at the moment only `FP32` is supported and performance is not as good as on Intel machines.
- At the moment the build includes opencv3 binaries as well, which can lead to a version conflict warnings between the package opencv dylibs and the opencv-python installation.
- There is still an issue with building older numpy versions on M1. Because of that the package loosens the numpy requirement to be just `>=1.16.6` as mentioned in #11532. For example [numpy 1.22.3](https://pypi.org/project/numpy/1.22.3/) works fine with deprecation warnings.

**Comment by NekiKulLik** [comment]
Hmm when I try to `import openvino.runtime` with openvino-arm on M1 Mac I seem to get:
```
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/openvino/pyopenvino.cpython-39-darwin.so, 2): Library not loaded: @rpath/libopenvino.dylib
```
Have you maybe noticed this issue @cansik ?

**Comment by cansik** [comment]
@NekiKulLik Yes I experience the same error, thanks for the hint. It is because openvino links the libs with `@rpath` and I have to "manually" change them with the `install_name_tool ` ([build-macos.sh#L138-L139](https://github.com/cansik/openvino-arm/blob/main/build-macos.sh#L138-L139)). To `import openvino` the current changes were enough, but I never used the `openvino.runtime`. I am going to add support for that soon.

**Comment by NekiKulLik** [comment]
@cansik Solves the problem, thanks for the response!
I'm running into a different issue though, when I try to call [compile_model](https://docs.openvino.ai/latest/api/ie_python_api/_autosummary/openvino.runtime.compile_model.html) function from that module.
It throws:
```
Cannot load library '/Users/nekikullik/Code/project/venv/lib/python3.9/site-packages/openvino/libs/libopenvino_arm_cpu_plugin.so: dlopen(/Users/nekikullik/Code/project/venv/lib/python3.9/site-packages/openvino/libs/libopenvino_arm_cpu_plugin.so, 2): Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/nekikullik/Code/project/venv/lib/python3.9/site-packages/openvino/libs/libopenvino_arm_cpu_plugin.so
  Expected in: /usr/lib/libc++.1.dylib
```
Could be that I have version mismatch there, I'll investigate a bit more.

**Comment by cansik** [comment]
Ok, I've released the new build to pypi. If you could provide me a small code example, I can investigate further. Would that be possible?

**Comment by NekiKulLik** [comment]
@cansik Sure, the code is quite small:

```
from openvino.runtime import Core

if __name__ == '__main__':
    core = Core()
    model_definition = core.read_model(model='./mobilenet-ssd.xml', weights='./mobilenet-ssd.bin')
    model = core.compile_model(model_definition, "CPU")
```
Where mobilenet-ssd is downloaded using [Openvino Model downloader](https://docs.openvino.ai/latest/omz_tools_downloader.html) though I'm facing that same issue with any model, not just Mobilenet. It breaks on `compile_model` line.

**Comment by cansik** [comment]
@NekiKulLik Thanks for the test script, I could run it and it seems to work here. My guess is that it has to do with the MacOS version. I was not aware that there is a dependency to the system it is built on because I have set the `CMAKE_OSX_DEPLOYMENT_TARGET=11` which should work on **BigSur** too. Are you running the script on **BigSur** or **Monterey**?

**Comment by NekiKulLik** [comment]
@cansik Ah. As of now I'm on Big Sur 11.2.2

**Comment by cansik** [comment]
What I could try to do is to build it on MacOS 11 with github actions, but because the machines are not ARM64 but Intel I am not sure if it will work. Otherwise you could of course build the wheels for now for your own system with the [shell script](https://github.com/cansik/openvino-arm). Just clone the repo and run `build-macos.sh`.

**Comment by NekiKulLik** [comment]
That is okay, I have an option to either build it or just upgrade the system. Thanks for all the help! @cansik

**Comment by cesarhcq** [comment]
Hello guys! Any update about OpenVINO on MACOS M1?

**Comment by ilya-lavrenov** [comment]
Hi @cansik 

I see you have several patches in your repository. Could you please send them to the main OpenVINO repository?
We want to adopt the great work you've done and thinking about publishing of official `openvino` pip package for M1/M2. 

I also see that you are fixing RPATH for libraries here https://github.com/cansik/openvino-arm/blob/main/build-macos.sh#L133-L155 why is it needed? I suppose we already have such code https://github.com/cansik/openvino-arm/blob/main/build-macos.sh#L133-L155

Thanks,
Ilya.

**Comment by cansik** [comment]
@ilya-lavrenov Yes, I will create a PR for the arm64 support. As far as I can see the relaxing of the numpy dependency (#11532) has already been covered here https://github.com/openvinotoolkit/openvino/pull/12191?

Regarding the RPATH issue, when I was testing the build, it did not work. That's why I've implemented my [own resolver](https://github.com/cansik/openvino-arm/blob/main/rpath-resolver.py) for the rpaths. if you could send me the link to the code you already have, I will try it again. But I guess you will have to adapt the script to use on your internal CI system anyways, right?

**Comment by ilya-lavrenov** [comment]
@cansik 

> has already been covered here https://github.com/openvinotoolkit/openvino/pull/12191?

Right, I hope so.

>  if you could send me the link to the code you already have, I will try it again.

Sorry, pasted the wrong link in the original message, updated. Here is a code https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/wheel/setup.py#L336-L362

> But I guess you will have to adapt the script to use on your internal CI system anyways

I suppose we don't have any internal CIs for wheels building, it's fully open sourced and available for everybody.

My end goal is to have `openvino` runtime package build available via `cmake -DIE_EXTRA_MODULES=<path to contrib> <openvino repo> && cmake --build <build dir> --target ie_wheel -j8` without any changes from users. So, it would be very helpful to have your changes and we will fix the remaining things if needed. Thanks!

**Comment by ilyachur** [comment]
@cansik @ilya-lavrenov 

Created PR https://github.com/openvinotoolkit/openvino_contrib/pull/399 for ARM plugin where bump the version of ARM Compute library.
This change allows to build ARM plugin for M1 without the patch.

**Comment by cansik** [comment]
@ilyachur Thanks for creating the PR which adds the fixes in the ComputeLibrary. With your PR branch and the head version of openvinotoolkit I was able to build the wheels successfully on MacOS M1 without any additional patches (here the script: https://github.com/cansik/openvino-arm/blob/build-latest/build-latest.sh) and the following commands:

```bash
cmake -DIE_EXTRA_MODULES="$root_dir/$openvino_contrib_dir/modules/arm_plugin" -DTHREADING=SEQ -DENABLE_PYTHON=ON -DENABLE_WHEEL=ON -DPYTHON_EXECUTABLE="$python_executable" -DPYTHON_LIBRARY="$python_lib" "$root_dir/$openvino_dir"
cmake --build . --target ie_wheel -j8
```

I guess it would be possible to skip the python executable and library paths, I just provide them to be able to use virtual-envs.

@ilya-lavrenov TBB is not supported on MacOS M1, so we may have to disable it directly in the `ie_wheel` target (using `-DTHREADING=SEQ`).

Here is the wheel prebuilt on Mac M1 for python `3.9`: [openvino_arm-2022.3.0-000-py3-none-macosx_12_0_arm64.whl.zip](https://github.com/openvinotoolkit/openvino/files/9349339/openvino_arm-2022.3.0-000-py3-none-macosx_12_0_arm64.whl.zip)

**Comment by raymondlo84** [comment]
Do you have the openvino-dev prebuilt too?

**Comment by ilyachur** [comment]
Hi @raymondlo84  no we don't provide pre-build openvino-dev

**Comment by ilya-lavrenov** [comment]
Published official openvino and openvino-dev packages for Apple Silicon on PyPi 
https://pypi.org/project/openvino/2022.3.0/

**Comment by massimag** [comment]
hello, if I type pip3 install openvino in my Macbook M1 terminal
I get
ERROR: Could not find a version that satisfies the requirement openvino (from versions: none)
ERROR: No matching distribution found for openvino

any help?

**Comment by cansik** [comment]
@massimag Please provide your pip and python version, otherwise it's difficult to help.
