### ISSUE TITLE
[Bug]  When performing AI inference, the GPU does not respond and keeps failing to return inference results.

### ISSUE THREAD

**Issue by karonluo** [openvinotoolkit/openvino#11562]
##### System information (version)

- OpenVINO => 2021.4
- Operating System / Platform => Ubuntu 20.04
- Compiler => g++ 7.5.0
- Problem classification: Model Conversion
- Framework: Pytorch
- Model name: YoloV5L deepsort onnx mtcnn 

##### Detailed description

When performing AI inference, the GPU does not respond and keeps failing to return inference results. Using the intel_gpu_top tool, I found that the GPU Render/3D/0 is 0%, Video/0 is 20%, VideoEnhance/0 is 20%, and under normal inference conditions, Render/3D/0 is 70% to 90%.
Note: This problem is likely to occur with continuous high stress reasoning.

**Comment by brmarkus** [comment]
Can you describe your environment first, please?
Which SOC (CPU+GPU) are you using?
(checking with `lscpu` and `lspci | grep VGA`)

Which model exactly are you using? Can you maybe share it for reproduction?
Have you converted it with "model-optimizer", if yes, how, can you share the used command-line, please?

Which code, which application are you using? Can you provide more details, or share the code?
Can you run e.g. `benchmark_app` (C++ or python version), just for consistency-check of your environment?

Have you installed the NEO-OpenCL-package as described under "https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_linux.html#step-5-optional-configure-inference-on-non-cpu-devices"?

For doing GPU-inference, OpenVINO need to create and compile OpenCL kernels first. This can take from some seconds up to a minute when starting the application for the first time.

You might benefit from an OpenCL-cache:

$> mkdir /tmp/ocl/
$> export cl_cache_dir=/tmp/ocl

And then start your application; you should see a high CPU-load while the OpenCL kernels get compiled and the folder `/tmp/ocl/` will fill up.

**Comment by karonluo** [comment]
Information:
OpenVINO Version: 2021.4.582
CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz 
GPU:  VGA compatible controller: Intel Corporation Device 9a49 (rev 01)
OpenCL Cache:  /opt/intel/cl_cache
Model include: Yolov5L, MTCNN, Deepsort

--------------------------------------------

Develop applications using C++ for vehicle detection, tracking and detection of identifying license plates.

Using OpenCV to pull camera frame (VideoCapture) and perform long continuous inference on the GPU can easily cause the GPU to stop outputting inference results, but the program used for inference does not terminate abnormally.

**Comment by karonluo** [comment]
The following images are normal:

![image](https://user-images.githubusercontent.com/19998353/165901063-076a429a-33a5-43bd-a1c0-b1b7deba635e.png)

![image](https://user-images.githubusercontent.com/19998353/165901168-da5582e8-e0a2-4c1f-a154-9a01b5d8ff71.png)

------

The main thread starts a thread for inference, which calls OpenVINO for inference and post-processing. The main thread gets the final output of this inference thread and then puts a new image into the inference thread.
The problem is that the thread for inference and post-processing does not return the result after sending the image to OpenVINO for inference, and the main thread cannot get the final output from the inference thread, so the whole program is stuck on the main thread pulling and decoding the video frames instead of submitting the new image to the inference thread for inference.

-------

Data Flow Diagram:

![image](https://user-images.githubusercontent.com/19998353/165905698-1b94fb4c-01d3-496f-9d03-14425fedb904.png)

**Comment by brmarkus** [comment]
So in case your application seems stuck - you still see CPU-load and GPU-load, i.e. it's still busy doing something? Or in this case there is no CPU-, no GPU-load?

Does your application supports logging and you can find out which call seems to not return? Which is the last call you are waiting for to complete and continue returning the result?
Are you sure it's not a dead-lock or an endless loop (maybe an API returns an error and you try again, and again)?

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
