### ISSUE TITLE
/opt/intel/openvino_2022/setupvars.sh  can't be source in macOS 12

### ISSUE THREAD

**Issue by Dracanrage** [openvinotoolkit/openvino#11579]
Hello,

I had installed openvino 2022.1 in my Intel Mac, but it can't be source, shows python version error, but actually I had installed the true version, it seems like a shell mistake. 
Here is the screenshot:
First I edit the sh to figure out where is wrong:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/30333935/165196462-c87aa3c0-e2c6-4144-8f7a-173b1528826a.png">
This is the output:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/30333935/165196493-2306dae7-1aae-448b-872a-b885b15e8567.png">
Seems like it didn't take the version string as an array.

**Comment by Dracanrage** [comment]
I had find the solution:
Just remove the () outsides the '${python_version//./ }'

**Comment by Dracanrage** [comment]
When modified like this, it works now:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/30333935/165197619-42f74776-3c0b-454d-b772-03b715fd8723.png">

**Comment by jgespino** [comment]
@Dracanrage Glad you figured it out! Please note that OpenVINO has only been validated with Mac OS 10.15 as mentioned in the [system requirements](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_macos.html#system-requirements). 

The latest 2022.1 installer will allow OpenVINO to be installed on newer Mac OS version but displays the following warning. 

![image](https://user-images.githubusercontent.com/18014973/165353524-3dd68903-d9fc-4706-83b6-a7a5d3c45491.png)

**Comment by artkuli** [comment]
@Dracanrage Thank you for reporting.
I guess that issue is related to the default shell on Mac (`zsh`). 
I see that splitting string variable to array works differently on `zsh` than in `bash`. Also `zsh` starts indexing arrays from `1` instead of `0`. 
I made small changes which should figure out the issue REPORTED BY @Dracanrage, PR: #11614
