### ISSUE TITLE
[Bug] compile a simple test program armv7-a

### ISSUE THREAD

**Issue by jafar0892** [openvinotoolkit/openvino#11582]
Hi everyone, could anyone help me with this problem? 

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=armv7-a" /opt/intel/openvino/deployment_tools/inference_engine/samples/cpp
-- The CXX compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - broken
CMake Error at /usr/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pato/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake cmTC_d4139/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_d4139.dir/build.make CMakeFiles/cmTC_d4139.dir/build
    gmake[1]: Entering directory '/home/pato/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_d4139.dir/testCXXCompiler.cxx.o
    /usr/bin/c++   -march=armv7-a  -o CMakeFiles/cmTC_d4139.dir/testCXXCompiler.cxx.o -c /home/pato/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    cc1plus: error: unknown value 'armv7-a' for '-march'
    cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a native; did you mean 'armv8-a'?
    gmake[1]: *** [CMakeFiles/cmTC_d4139.dir/build.make:85: CMakeFiles/cmTC_d4139.dir/testCXXCompiler.cxx.o] Error 1
    gmake[1]: Leaving directory '/home/pato/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:140: cmTC_d4139/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)

-- Configuring incomplete, errors occurred!
See also "/home/pato/build/CMakeFiles/CMakeOutput.log".
See also "/home/pato/build/CMakeFiles/CMakeError.log".

**Comment by Iffa-Meah** [comment]
@jafar0892, 

Could you verify/provide these infos:
1. Are you using **Raspberry Pi with ARM ARMv7-A CPU architecture** running Raspbian OS?. From the error, the error prompt armv8-a instead v7. You need to verify whether your Pi is v7 or v8. ([Note that officially supported is v7](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_raspbian.html?))
2. Did you install from the OpenVINO Runtime installer or did you [build from source](https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS#native-compilation)?
3. It seems that you saved and build your custom code in the location: /opt/intel/openvino/deployment_tools/inference_engine/samples/cpp

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by jafar0892** [comment]
@Iffa-Meah
i apologize for late answer, beacuse i was quite busy with exam!!! Ja, i am using raspberry pi with ARMv7 and runtime has been installed from openvino site. 
I tried to run an example code from openvino but i got just error after error.
