### ISSUE TITLE
setupvars.sh [Bug]

### ISSUE THREAD

**Issue by jxust01** [openvinotoolkit/openvino#11587]
##### System information (version)
- OpenVINO => 2022.1
- Operating System / Platform => ubuntu16.04

##### Detailed description
[setupvars.sh] WARNING: Can not find OpenVINO Python binaries by path /opt/intel/openvino_2022/python 
[setupvars.sh] WARNING: OpenVINO Python environment does not set properly

>>> from openvino.runtime import Core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openvino.runtime'

##### Steps to reproduce
   ./opt/intel/openvino_2022/setupvars.sh

**Comment by jgespino** [comment]
@jxust01 OpenVINO 2022.1 is not supported in Ubuntu 16.04. Please take a look at the [system requirements](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html) page. 

> **Compatible Operating Systems**
> 
> - Ubuntu* 18.04 LTS (64 bit)
> - Ubuntu 20.04 LTS (64 bit)
> - Windows® 10 (64 bit)
> - Windows* 11 (recommended for 12th generation Intel Core processors)
> - Red Hat* Enterprise Linux* 8 (64 bit)
> - macOS* 10.15 (64 bit)
