### ISSUE TITLE
[Bug] Build demos that developed inside ubuntu-docker not working on windows 

### ISSUE THREAD

**Issue by AyaNasser96** [openvinotoolkit/openvino#11583]
I am working on 2 environments now, one that I developed on which is ubuntu 20.04 using this openvino docker:
docker [link](https://hub.docker.com/r/openvino/ubuntu20_dev) docker pull openvino/ubuntu20_dev

and the other one is on windows to test if my demo is working with cross-platform:
I installed the openvino installer on the system then the development tool and I tried the open_model_zoo demos and it worked great.

but my demo that I developed and tested on ubuntu not working on windows, it gives me the following error, 

![image](https://user-images.githubusercontent.com/98317981/165328734-eaf25c48-f10f-4bc2-ac25-be5fd9d3ee3a.png)

`C:\Program Files (x86)\Intel\openvino_2022.1.0.643\runtime\include\ngraph/op/region_yolo.hpp(13,19): error C2874: using-declaration causes a multiple declaration of 'ngraph::op::v0::RegionYolo' [D:\work\openvino-related-work\make_class_
task\github_repo2\IE\build_win\common\cpp\models\models.vcxproj]
D:\work\openvino-related-work\make_class_task\github_repo2\IE\common\cpp\models\include\models/detection_model_yolo.h(23): message : see declaration of 'ngraph::op::v0::RegionYolo' [D:\work\openvino-related-work\make_class_task\github_r
epo2\IE\build_win\common\cpp\models\models.vcxproj]
D:\work\openvino-related-work\make_class_task\github_repo2\IE\common\cpp\models\src\detection_model_yolo.cpp(115,24): error C2027: use of undefined type 'ngraph::op::v0::RegionYolo' [D:\work\openvino-related-work\make_class_task\github_
repo2\IE\build_win\common\cpp\models\models.vcxproj]
D:\work\openvino-related-work\make_class_task\github_repo2\IE\common\cpp\models\include\models/detection_model_yolo.h(23): message : see declaration of 'ngraph::op::v0::RegionYolo' [D:\work\openvino-related-work\make_class_task\github_r
epo2\IE\build_win\common\cpp\models\models.vcxproj]
D:\work\openvino-related-work\make_class_task\github_repo2\IE\common\cpp\models\src\detection_model_yolo.cpp(115,38): error C2039: 'get_mask': is not a member of 'std::shared_ptr<ngraph::op::v0::RegionYolo>' [D:\work\openvino-related-wo
rk\make_class_task\github_repo2\IE\build_win\common\cpp\models\models.vcxproj]
D:\work\openvino-related-work\make_class_task\github_repo2\IE\common\cpp\models\include\models/detection_model_yolo.h(40): message : see declaration of 'std::shared_ptr<ngraph::op::v0::RegionYolo>' [D:\work\openvino-related-work\make_cl
ass_task\github_repo2\IE\build_win\common\cpp\models\models.vcxproj]
D:\work\openvino-related-work\make_class_task\github_repo2\IE\common\cpp\models\src\detection_model_yolo.cpp(307,24): error C2027: use of undefined type 'ngraph::op::v0::RegionYolo' [D:\work\openvino-related-work\make_class_task\github_
repo2\IE\build_win\common\cpp\models\models.vcxproj]
D:\work\openvino-related-work\make_class_task\github_r`

I found a huge difference between the open_model_zoo demos provided inside the docker image and with the demos inside the github that's I used inside windows env, 

I am sure that the big difference inside the cmake files and the object_detection_yolo script that cause those differences, 

My question is, How to re-run my demo (that I've develop on openvino ubuntu docker on windows env)?

I'll put some snippest here for the difference between the openvino demos provided inside the ubuntu docker and what inside the windows

cmake difference: 

ubuntu:

![image](https://user-images.githubusercontent.com/98317981/165330139-e96e1f1d-65e6-4a6f-ac8c-1c956ee03d8c.png)

windows:

![image](https://user-images.githubusercontent.com/98317981/165329235-708b5ace-b904-4b67-9a8d-8d7032652133.png)

**Comment by zulkifli-halim** [comment]
Hi @AyaNasser96. The Docker image you pulled is OpenVINO 2021, and the one you installed in Windows is OpenVINO 2022.1.
You can see the difference between the CMAKE file of these two versions here:
[2021.4/demos/CMakeLists.txt ](https://github.com/openvinotoolkit/open_model_zoo/blob/2021.4.2/demos/CMakeLists.txt)
[2022.1/demos/CMakeLists.txt](https://github.com/openvinotoolkit/open_model_zoo/blob/2022.1.0/demos/CMakeLists.txt)

You can refer to the [release notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes.html) of OpenVINO 2022 for new features and updates. 

Since you are using OpenVINO 2021 in Ubuntu 20.04, I suggest you install the same version of OpenVINO in Windows as well.

**Comment by zulkifli-halim** [comment]
Closing, please re-open if additional assistance is needed.

**Comment by AyaNasser96** [comment]
@zulkifli-halim  Thank you, the last question is 
My version on linux is equal to **2021.4.752** is this equal to 2021.4.2 at windows or there are some difference ??

**Comment by AyaNasser96** [comment]
@zulkifli-halim  Thank you ^^
