### ISSUE TITLE
[Bug] ov2022.1 runtime windows10 offline installer not work under vmware

### ISSUE THREAD

**Issue by yantaozhao** [openvinotoolkit/openvino#11596]
##### System information (version)

- OpenVINO=> 2022.1
- Operating System / Platform => windows 10
- Compiler => visual studio 2022
- Problem classification => Installing issue

##### Detailed description

Under vmware workstation, OpenVINO 2022.1 runtime windows10 offline installer shows blank screen rather than anything when launch the installation, stuck in the first step.

##### Steps to reproduce
Install windows10 inside VMWare workstation, then install OpenViNO 2022.1 in offline style.

**Comment by Iffa-Meah** [comment]
@yantaozhao , before proceeding further, hope you had noticed that up till this moment, OpenVINO requires specifically [Microsoft Visual Studio 2019 with MSBuild](http://visualstudio.microsoft.com/downloads/) to operate.
Other version might works but issues are expected.
You may refer [here](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_windows.html#doxid-openvino-docs-install-guides-installing-openvino-windows) for further info.

**Comment by yantaozhao** [comment]
glad to here that.
but it seems that the problem has nothing to do with IDE.

It's just an installation issue using Intel official built offline installer. maybe something is wrong inside the openvino2022.1 installer.

**Comment by Iffa-Meah** [comment]
@yantaozhao ,

this is using VS 2019 with OpenVINO 2022 offline installer. Make sure you had fulfilled the **pre-requisites** before running the installer and ensure you had assigned enough memory to the VM.


<img width="960" alt="2022RuntimeInstaller" src="https://user-images.githubusercontent.com/79643476/166175551-b548f6e9-7d27-47e1-a944-11b3bc633ea0.png">

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
