### ISSUE TITLE
[Error] google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.SavedModel'

### ISSUE THREAD

**Issue by RogerMor** [openvinotoolkit/openvino#11594]
##### System information (version)

- OpenVINO => 2022.1
- Operating System / Platform => Intel Dev Cloud notebooks: https://notebooks.edge.devcloud.intel.com/
- Intel Dev Cloud edge notebooks launcher => OPENVINO 2022.1 + tensorflow 2.4
- Problem classification: Model Conversion
- Framework: TensorFlow (Tensorflow Lite Model Maker)
- Model name: efficientdet_lite2 

##### Detailed description
Error when converting the model efficeintdet-2 from tflite to OPENVINO using mo --saved_model_dir "saved_model_path"

Obtained Error: 

[ FRAMEWORK ERROR ]  Cannot load input model: Cannot parse file b'/home/u150887/Reference-samples/iot-devcloud/openvino-dev-latest/developer-samples/python/object-detection-python/saved_odel2/saved_model.pb': Error parsing message with type 'tensorflow.SavedModel'.
[ 2022-04-27 06:02:58,769 ] [ DEBUG ] [ main:554 ]  Traceback (most recent call last):
  File "/data/venv/openvino_2022.1.0.643-tensorflow_2.4/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 99, in parse_saved_model
    saved_model.ParseFromString(file_content)
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.SavedModel'

##### Steps to reproduce

   Train a efficeintdet-2 with model maker e.g. https://colab.research.google.com/github/googlecodelabs/odml-pathways/blob/main/object-detection/codelab2/python/Train_a_salad_detector_with_TFLite_Model_Maker.ipynb

Then export using: model.export(export_dir='path', export_format= [ExportFormat.SAVED_MODEL])

And finally "optimize"/convert the model for openvino using:

$mo --saved_model_dir saved_model_path --log_level=DEBUG

Obtaining as a result:

[ FRAMEWORK ERROR ]  Cannot load input model: Cannot parse file b'/home/u150887/Reference-samples/iot-devcloud/openvino-dev-latest/developer-samples/python/object-detection-python/saved_odel2/saved_model.pb': Error parsing message with type 'tensorflow.SavedModel'.
[ 2022-04-27 06:02:58,769 ] [ DEBUG ] [ main:554 ]  Traceback (most recent call last):
  File "/data/venv/openvino_2022.1.0.643-tensorflow_2.4/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 99, in parse_saved_model
    saved_model.ParseFromString(file_content)
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.SavedModel'

and the full log see attached resp.log:

[resp.log](https://github.com/openvinotoolkit/openvino/files/8572448/resp.log)

I have also tried to use:

!mo --input_model model_path/saved_model.pb --log_level=DEBUG

[ FRAMEWORK ERROR ]  Cannot load input model: TensorFlow cannot read the model file: "/home/u150887/Reference-samples/iot-devcloud/openvino-dev-latest/developer-samples/python/object-detection-python/saved_odel2/saved_model.pb" is incorrect TensorFlow model file.

**Comment by jgespino** [comment]
@RogerMor Please double check the saved_model directory and ensure all files are there. I was able to export the model in saved_model format with the following structure but run into additional issues with the model optimizer. Currently, tflite model are not supported.

![image](https://user-images.githubusercontent.com/18014973/165595537-40da173d-f073-46db-ad47-8c03fecf5798.png)
```
[ WARNING ]  The model contains input(s) with partially defined shapes: name="images" shape="[-1, -1, -1, 3]". Starting from the 2022.1 release the Model Optimizer can generate an IR with partially defined input shapes ("-1" dimension in the TensorFlow model or dimension with string value in the ONNX model). Some of the OpenVINO plugins require model input shapes to be static, so you should call "reshape" method in the Inference Engine and specify static input shapes. For optimal performance, it is still recommended to update input shapes with fixed ones using "--input" or "--input_shape" command-line parameters.
[ ERROR ]  Cannot infer shapes or values for node "StatefulPartitionedCall/loop_body/resize/ResizeBilinear/pfor/TensorArrayV2".
[ ERROR ]  Input 1 of node StatefulPartitionedCall/loop_body/resize/ResizeBilinear/pfor/TensorArrayV2 was passed double from StatefulPartitionedCall/loop_body/resize/ResizeBilinear/pfor/strided_slice_port_0_ie_placeholder:0 incompatible with expected int32.
[ ERROR ]
[ ERROR ]  It can happen due to bug in custom shape infer function <function tf_native_tf_node_infer at 0x0000011796041510>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'openvino.tools.mo.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "StatefulPartitionedCall/loop_body/resize/ResizeBilinear/pfor/TensorArrayV2" node.
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)
```

For Object Detection models, we need to use a [transformations_config](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html?highlight=object%20detection%20model) file. We have some available for [EfficientDet ](https://docs.openvino.ai/latest/omz_models_model_efficientdet_d0_tf.html)models but not the lite versions.

Regards,
Jesus

**Comment by RogerMor** [comment]
> @RogerMor Please double check the saved_model directory and ensure all files are there. I was able to export the model in saved_model format with the following structure but run into additional issues with the model optimizer. Currently, tflite model are not supported.
> 
> ![image](https://user-images.githubusercontent.com/18014973/165595537-40da173d-f073-46db-ad47-8c03fecf5798.png)
> 
> ```
> [ WARNING ]  The model contains input(s) with partially defined shapes: name="images" shape="[-1, -1, -1, 3]". Starting from the 2022.1 release the Model Optimizer can generate an IR with partially defined input shapes ("-1" dimension in the TensorFlow model or dimension with string value in the ONNX model). Some of the OpenVINO plugins require model input shapes to be static, so you should call "reshape" method in the Inference Engine and specify static input shapes. For optimal performance, it is still recommended to update input shapes with fixed ones using "--input" or "--input_shape" command-line parameters.
> [ ERROR ]  Cannot infer shapes or values for node "StatefulPartitionedCall/loop_body/resize/ResizeBilinear/pfor/TensorArrayV2".
> [ ERROR ]  Input 1 of node StatefulPartitionedCall/loop_body/resize/ResizeBilinear/pfor/TensorArrayV2 was passed double from StatefulPartitionedCall/loop_body/resize/ResizeBilinear/pfor/strided_slice_port_0_ie_placeholder:0 incompatible with expected int32.
> [ ERROR ]
> [ ERROR ]  It can happen due to bug in custom shape infer function <function tf_native_tf_node_infer at 0x0000011796041510>.
> [ ERROR ]  Or because the node inputs have incorrect values/shapes.
> [ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
> [ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
> [ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'openvino.tools.mo.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "StatefulPartitionedCall/loop_body/resize/ResizeBilinear/pfor/TensorArrayV2" node.
>  For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)
> ```
> 
> For Object Detection models, we need to use a [transformations_config](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html?highlight=object%20detection%20model) file. We have some available for [EfficientDet ](https://docs.openvino.ai/latest/omz_models_model_efficientdet_d0_tf.html)models but not the lite versions.
> 
> Regards, Jesus

Thanks Jesus,

Yes I have the same file distribution than you in the saved_model folder.

Just to let it reported: When I run the "optimization" in my own laptop I get the same error as you:

[log2.txt](https://github.com/openvinotoolkit/openvino/files/8579924/log2.txt)

However, when I run it in the jupyter lab of the Intel Cloud dev notebooks I get the error reported above.


As you pointed out I understand that the conlcusion is that currently tflite models are not supported.

Thanks a lot!

Regards,
Roger.
