### ISSUE TITLE
 "Attempting to use uninitialized value adam_vars/beta1_power" when converting deeplab resnet_v1_101 to IR

### ISSUE THREAD

**Issue by violet17** [openvinotoolkit/openvino#116]
OS : unbuntu 16.04
openvino version: openvino 2019R1
python version for training deeplab: python 2.7
TF version for training deeplab: 1.12.0

command for converting:
`python3 mo.py  --input_meta_graph model_resnet_101_16s.ckpt.meta`
 

log:
```
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	None
	- Path for generated IR: 	/home/crystal/projects/deeplab/log_resnet_101_16s/.
	- IR output name: 	model_resnet_101_16s.ckpt
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Operations to offload: 	None
	- Patterns to offload: 	None
	- Use the config file: 	None
Model Optimizer version: 	2019.1.0-341-gc9b66a2
[ FRAMEWORK ERROR ]  Cannot load input model: Attempting to use uninitialized value adam_vars/beta1_power
	 [[Node: _retval_adam_vars/beta1_power_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](adam_vars/beta1_power)]]

```

**Comment by shubha-ramani** [comment]
Dear @violet17 
It looks like deeplab is not one of OpenVino's supported and tested Tensorflow topologies according to [this list](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html) 
but someone in the community has made DeepLab work with OpenVino:
[https://github.com/feng1sun/Deeplab-OpenVINO](https://github.com/feng1sun/Deeplab-OpenVINO)
He is using an entirely different MO command than you.

Thanks and I hope it helps,

Shubha

**Comment by violet17** [comment]
@shubha-ramani Thank you very much!

**Comment by lazarevevgeny** [comment]
@violet17 when you provide a meta-graph as input you must specify output node names to cut-off the part of the model related to training. As you can see from the log the MO failed to convert operations related to training.

Have you managed to solve that issue already?

**Comment by AnastasiaKazantaeva** [comment]
As problem doesn't exist any more, I am closing this issue. You may reopen it or create a new one
