### ISSUE TITLE
imread() failed with some images of LFW test set

### ISSUE THREAD

**Issue by bianxg** [openvinotoolkit/openvino#1163]
I use openvino to do LFW test.  most images can be read using imread(), but some failed.(all images are from LFW test set)

Read picture share/lfw/Abdel_Madi_Shabneh/Abdel_Madi_Shabneh_0001.jpg failed!
Read picture share/lfw/Abdul_Rahman/Abdul_Rahman_0001.jpg failed!

code:
Mat img = imread(image_name);
if(!img.data) return -1;

version：
OpenCV version : 4.3.0-openvino-2020.3.0
Major version : 4
Minor version : 3
Subminor version : 0

OS:
CentOS 7

**Comment by brmarkus** [comment]
Can you help providing details about what this LFW test set is, maybe provide references where to get the two mentioned pictures?
I have OpenVINO "2020.3.194" installed under Ubuntu - natively as well as within a container and could look into the JPG file, maybe it is an exotic JPG encoding (like Turbo-JPEG-2000).
Have you installed OpenVINO natively under CentOS7 and/or within a (Docker) container?

**Comment by brmarkus** [comment]
Is it this, `http://vis-www.cs.umass.edu/lfw/images/Abdel_Madi_Shabneh/Abdel_Madi_Shabneh_0001.jpg`?
And this, `http://vis-www.cs.umass.edu/lfw/images/Abdul_Rahman/Abdul_Rahman_0001.jpg`?

Have you checked you have the files locally, so it exists, non-zero file-size, proper access rights?

**Comment by bianxg** [comment]
http://vis-www.cs.umass.edu/lfw/lfw.tgz
I install OpenVINO natively under CentOS 7.
I use files locally. Most files in the directory are ok. But some files are not ok using imread(). however, they all can be seen ok using any image tools.

**Comment by brmarkus** [comment]
Ok, I don't have CentOS7 but Ubuntu... and just copied an existing sample from OpenModelZoo, emptied the main.cpp and just load the pictures and display them... I can open and display the images successfully...
![image](https://user-images.githubusercontent.com/29976962/86145350-204fa380-baf7-11ea-8713-cc7fbccbe890.png)
(I used `cv::IMREAD_COLOR`, but I also tested without it)
(I have the same OpenCV version like you, as it is part of the OpenVINO installation; cmake outputs `-- Found OpenCV: /opt/intel/openvino_2020.3.194/opencv (found version "4.3.0") found components:  core imgproc` in my case when I use a small C++ sample)

**Comment by bianxg** [comment]
Thanks. It's my fault. Some pictures file path is not right. 

https://github.com/terryshyan/libovface

**Comment by brmarkus** [comment]
Sounds promising, so everything working now?
Would you mind to close the issue then?

**Comment by bianxg** [comment]
Please close the issue. Everything working now.

**Comment by brmarkus** [comment]
Nice project, `libovface`, by the way.

**Comment by brmarkus** [comment]
Only you or an admin can close the issue, I think.
