### ISSUE TITLE
[Bug] openvino opencv installation instructions for Linux are confusing

### ISSUE THREAD

**Issue by nyck33** [openvinotoolkit/openvino#11634]
##### System information (version)

- OpenVINO => 2022.1
- Operating System / Platform => Windows 64 Bit (WSL2 Linux Subsystem)
- Compiler => Visual Studio 2022
- Problem classification: documentation error

##### Detailed description
Here: https://docs.openvino.ai/nightly/openvino_docs_install_guides_installing_openvino_linux.html#install-external-dependencies

it says:
```
OpenCV is necessary to run demos from Open Model Zoo (OMZ). Some OpenVINO samples can also extend their capabilities when compiled with OpenCV as a dependency. The Intel® Distribution of OpenVINO™ provides a script to install OpenCV: <INSTALL_DIR>/extras/scripts/download_opencv.sh.

Note

Make sure you have 2 prerequisites installed: curl and tar.

Depending on how you have installed the Intel® Distribution of OpenVINO™, the script should be run either as root or regular user. After the execution of the script, you will find OpenCV extracted to <INSTALL_DIR>/extras/opencv.
```
but here:  https://docs.openvino.ai/nightly/openvino_docs_install_guides_installing_openvino_apt.html

it says:
```
To Install the Latest Version of OpenCV

Run the following command:

sudo apt install openvino-opencv

To Install a Specific Version of OpenCV

Run the following command:

sudo apt install openvino-opencv-<VERSION>.<UPDATE>.<PATCH>
```
Please clarify.  I am installing on Ubuntu and WSL2 subsystem.

**Comment by jgespino** [comment]
@nyck33 Thanks for reaching out, both installation methods will install openvino-opencv version 2022.1.0.

If you are using the offline/online installer, you can verify by looking at the download_opencv.sh script:
`VER="opencv/release_2022.1/20220311_0602-4.5.5_090`

If you are installing using the APT repository, you can verify by running:
```
$ apt list -a openvino-opencv
openvino-opencv/focal 2022.1.0-643 amd64
```

I would recommend installing OpenCV using the documentation from the same installation method.
