### ISSUE TITLE
[Bug] ReverseSequence Doesn't support op with dynamic shapes

### ISSUE THREAD

**Issue by a3213105** [openvinotoolkit/openvino#11648]
I have an OCR model using ReverseSequence need dynamic shapes, but OV is not supported. Can i write a support patch and push it to main stream?

**Comment by jgespino** [comment]
@a3213105 Yes you can! I see you have already created the pull request and is pending a review by one of the maintainers.

**Comment by mateusztabaka** [comment]
There is also work ongoing here https://github.com/openvinotoolkit/openvino/pull/11644 to add the dynamic shapes support to ReverseSequence.

**Comment by a3213105** [comment]
> There is also work ongoing here #11644 to add the dynamic shapes support to ReverseSequence.

It's great that someone try to fix my issue. I will wait if his commit can make my model run, then I will close this ticket. thanks for your mention @mateusztabaka
