### ISSUE TITLE
ov::DiscreteTypeInfo::version’ is deprecated: This member was deprecated. Please use version_id instead. 

### ISSUE THREAD

**Issue by intjun** [openvinotoolkit/openvino#11646]
编译的时候出现：
ov::DiscreteTypeInfo::version’ is deprecated: This member was deprecated. Please use version_id instead.

**Comment by Iffa-Meah** [comment]
@intjun could you provide:
1. command that you use which cause the error
2. script/code (did you use official OpenVINO sample or custom made?)
3. which OpenVINO version are you using?

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
