### ISSUE TITLE
Check 'element::Type::merge(element_type, element_type, node->get_input_element_type(i))' failed at core/src/op/util/elementwise_args.cpp:20: While validating node 'v1::Equal 438 (436[0]:boolean{?,1,?,?}, Constant_91604[0]:u8{1,1,1,1}) -> ()' with friendly_name '438': Argument element types are inconsistent.[Bug]

### ISSUE THREAD

**Issue by Duum** [openvinotoolkit/openvino#11666]
Check 'element::Type::merge(element_type, element_type, node->get_input_element_type(i))' failed at core/src/op/util/elementwise_args.cpp:20:
While validating node 'v1::Equal 438 (436[0]:boolean{?,1,?,?}, Constant_91604[0]:u8{1,1,1,1}) -> ()' with friendly_name '438':
Argument element types are inconsistent.

**Comment by Iffa-Meah** [comment]
@Duum could you provide:

1. your commands 
2. script/code (did you use official OpenVINO sample or custom code?)
3. which OpenVINO version 
4. your model and its topology

**Comment by Duum** [comment]
https://github.com/Mashiro009/wenet-online-decoder-onnx
in this readme , it has a link of baidu wangpan, and it has three onnx ，when I try encoder, and build model failed.

**Comment by Duum** [comment]
I has no idea how to add big file in this readme ,if you can't find ,I can send the onnx model by email

**Comment by tomdol** [comment]
@Duum your model contains an `Equal` operation which takes a boolean and uint8 inputs. Both data types have to be the same in order to be imported to OV https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/comparison/Equal_1.md

Can you please check your model and adjust it? You should either align both inputs or insert a `Cast` operator before one of the operator's inputs.

**Comment by Duum** [comment]
buy why onnx runtime is work fine? we don't compatibility with onnx？

**Comment by tomdol** [comment]
ONNXRuntime is a different framework which implements the ONNX standard. In fact the ONNX standard also requires that the inputs to the `Equal` operator use the same data type https://github.com/onnx/onnx/blob/main/docs/Operators.md#inputs-31. Perhaps in ONNXRT the requirements are more relaxed.

BTW, can you check your model with this python code?

`import onnx`
`model = onnx.load("path/to/your/model.onnx")`
`onnx.checker.check_model(model, full_check=True)`

**Comment by Duum** [comment]
thank you ， I'll try it

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
