### ISSUE TITLE
Fail to Convert ONNX Model to OpenVINO IR

### ISSUE THREAD

**Issue by shliar** [openvinotoolkit/openvino#11676]
##### System information (version)
- OpenVINO => 2022.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2021
- Problem classification: Model Conversion
- Framework: onnx
- Model name: yolo

##### Detailed description
I'm using the Mo tool to complete the conversion from onnx format model to IR format model, but I encountered some errors, resulting in the conversion failure,the log is as follows.How can I solve these mistakes？

Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      D:\Games\sqayolo\work\output\yolov3_darknetsqa\inference_model\new\inference_model\model.onnx
        - Path for generated IR:        D:\Games\sqayolo\work\output\yolov3_darknetsqa\inference_model\new\inference_model\ir
        - IR output name:       model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         Not specified, inherited from the model
        - Source layout:        Not specified
        - Target layout:        Not specified
        - Layout:       Not specified
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - User transformations:         Not specified
        - Reverse input channels:       False
        - Enable IR generation for fixed input shape:   False
        - Use the transformations config file:  None
Advanced parameters:
        - Force the usage of legacy Frontend of Model Optimizer for model conversion into IR:   False
        - Force the usage of new Frontend of Model Optimizer for model conversion into IR:      False
OpenVINO runtime found in:      c:\users\18431\appdata\local\programs\python\python38\lib\site-packages\openvino
OpenVINO runtime version:       2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version:        2022.1.0-7019-cdb9bec7210-releases/2022/1
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  While validating ONNX node '<Node(Resize): p2o.Resize.0>':
Check 'sizes_et == element::i32 || sizes_et == element::i64 || sizes_et == element::u32 || sizes_et == element::u64' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\core\src\op\interpolate.cpp:212:
While validating node 'v4::Interpolate Interpolate_696 (leaky_relu_58.tmp_0[0]:f32{1,256,40,40}, NullNode_689[0]:dynamic..., Add_695[0]:f32...) -> (dynamic...)' with friendly_name 'Interpolate_696':
Sizes element type must be i32, i64, u32 or u64

[ ERROR ]  Traceback (most recent call last):
  File "C:\Users\18431\AppData\Local\Programs\Python\Python38\Lib\site-packages\openvino\tools\mo\main.py", line 533, in main
    ret_code = driver(argv)
  File "C:\Users\18431\AppData\Local\Programs\Python\Python38\Lib\site-packages\openvino\tools\mo\main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "C:\Users\18431\AppData\Local\Programs\Python\Python38\Lib\site-packages\openvino\tools\mo\main.py", line 394, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
  File "c:\users\18431\appdata\local\programs\python\python38\lib\site-packages\openvino\tools\mo\moc_frontend\pipeline.py", line 147, in moc_pipeline
    ngraph_function = moc_front_end.convert(input_model)
RuntimeError: While validating ONNX node '<Node(Resize): p2o.Resize.0>':
Check 'sizes_et == element::i32 || sizes_et == element::i64 || sizes_et == element::u32 || sizes_et == element::u64' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\core\src\op\interpolate.cpp:212:
While validating node 'v4::Interpolate Interpolate_696 (leaky_relu_58.tmp_0[0]:f32{1,256,40,40}, NullNode_689[0]:dynamic..., Add_695[0]:f32...) -> (dynamic...)' with friendly_name 'Interpolate_696':
Sizes element type must be i32, i64, u32 or u64

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by Iffa-Meah** [comment]
@shliar could you share your model? and where's the source of this model? (eg: [Ultralytic](https://github.com/ultralytics/yolov5))

**Comment by Iffa-Meah** [comment]
@shliar based on the model you emailed me, I did a quick test and found that your model is not supported to be run on OpenVINO.

<img width="660" alt="benchmark" src="https://user-images.githubusercontent.com/79643476/168250897-ccb90c90-dd4c-4740-a5a8-2b57b35e2710.png">

Is this a custom model that you created or is it sourced from somewhere?

These are readily available ONNX models and officially supported by OpenVINO:
[ONNX Faster RCNN](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_onnx_specific_Convert_Faster_RCNN.html?highlight=onnx)
[ONNX Mask RCNN](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_onnx_specific_Convert_Mask_RCNN.html?highlight=onnx)

**Comment by shliar** [comment]
Hi:
&nbsp; &nbsp;&nbsp;This is my own training model,the model file is in the attachment,please unzip it .In /best_model is the model created by paddle frame,in /inference_model/new/inference_model are the inference_model and&nbsp; onnx model,thanks~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openvinotoolkit/openvino"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月13日(星期五) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openvinotoolkit/openvino] Fail to Convert ONNX Model to OpenVINO IR (Issue #11676)





 
@shliar based on the model you emailed me, I did a quick test and found that your model is not supported to be run on OpenVINO.
 

 
Is this a custom model that you created or is it sourced from somewhere?
 
These are readily available ONNX models and officially supported by OpenVINO:
 ONNX Faster RCNN
 ONNX Mask RCNN

**Comment by shliar** [comment]
> 

Hi Iffa-Meah
    you can find my model file in https://github.com/shliar/onnx-model-Colourful-mosaic-detection.git

**Comment by tomdol** [comment]
@shliar your model contains a Resize node named `p2o.Resize.0`. This node takes an optional input called `sizes` and in your model it seems to be connected to something with undefined data type:
![image](https://user-images.githubusercontent.com/22572387/168269179-289b7f87-2ceb-458c-8c6d-ea52465e59b2.png)
If you're trying to resize the output of LeakyRelu using scales you should not connect anything to the last input of Resize (only one of those inputs should be provided to this op).

**Comment by tomdol** [comment]
I've checked again and it turns out my original assumption was wrong. Resize operator handling had a bug and here's a bugfix https://github.com/openvinotoolkit/openvino/pull/11692

**Comment by shliar** [comment]
> 

Thanks! I'll get the latest version and try again later

**Comment by Iffa-Meah** [comment]
@shliar 
Note that starting from the 2020.4 release, OpenVINO™ supports reading native ONNX models. 
You should be able to run the model using OpenVINO Benchmark App without any conversion to see compatibility.

I tested the model you shared through email 

<img width="554" alt="benchmarkapp" src="https://user-images.githubusercontent.com/79643476/168504942-048417e6-ead3-49cc-ab57-395776c3c1c5.png">

The result of this Benchmark Application does not throws error regading unsupported model or format but instead, it is related to the input shape. 

Try to run the native onnx model using the Benchmark App and see whether it works. If it does works, then it means the model is supoorted and you need to provide the [correct input shapes or other required values during conversion](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model.html) into IR.
