### ISSUE TITLE
issue with dlls in 2019 R1

### ISSUE THREAD

**Issue by wojsla** [openvinotoolkit/openvino#117]
Hi guys,
Just upgraded my application from OpenVINO 2018 R5.01 to 2019 R1 and found couple of issues with dlls:
- debug build of cpu plugin needs Intel Threading Building Blocks dlls with names "tbb_debug.dll" as well as "tbb.dll" - if it is missing either it crashes (same for tbbmalloc). Myriad plugin works ok with just "tbb_debug.dll", release build works ok with "tbb.dll" for both cpu and Myriad.
- cpu plugin seems to need "mkl_tiny_omp.dll", "mkl_tiny_seq.dll" as well as "mkl_tiny_tbb.dll" none of which are in "openvino_2019.1.087\inference_engine\bin\intel64\Release". After copying these dlls from "openvino_2019.1.087\inference_engine\bin\intel64\Debug" it works ok.

**Comment by shubha-ramani** [comment]
Dear @wojsla I have also reproduced this issue. Thanks for pointing it out ! I will file a bug on this issue.

Thanks,

Shubha

**Comment by shubha-ramani** [comment]
Dear @wojsla 

I misspoke earlier.  I actually couldn't reproduce your issue. Could you give details of how you reproduced it ? I mean, how did you find that these DLLs were in the wrong place ?

Thanks !

Shubha

**Comment by mrsabhar** [comment]
@shubha-ramani  @wojsla  is correct on #2. Mkl tiny dlls are missing from release folder in R1.

**Comment by shubha-ramani** [comment]
@mrsabhar Indeed  I have heard this is the case (re : mkl tiny dlls). I'm reproducing it today and filing a bug. 

Thanks,

Shubha

**Comment by wojsla** [comment]
@shubha-ramani no I haven't set up any paths as we distribute all dll's with the application so I was checking if new version requires any additional dll's. Even after copying all from "openvino_2019.1.087\deployment_tools\inference_engine\bin\intel64\Debug" I was still getting missing dll exceptions when using cpu plugin in debug build. In release build I was missing "mkl_tiny" dlls.

**Comment by jbrownkramer** [comment]
openvino_2020.1.033\deployment_tools\inference_engine\bin\intel64\Debug does not contain tbb.dll or tbb_debug.dll.  It's blocking me from running a standalone model.

**Comment by jbrownkramer** [comment]
I see that it is an externals folder.

**Comment by ilyachur** [comment]
@wojsla Can you try to use the last OpenVINO package?
@jbrownkramer @wojsla Please use setup_vars in order to set the right environment. I think it should help to solve problems with tbb libraries.

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
