### ISSUE TITLE
[Bug] Python AsyncInferQueue maybe has memory leak?

### ISSUE THREAD

**Issue by a3213105** [openvinotoolkit/openvino#11727]
Currently I'm writing asynchronous inference code using OpenVINO Python API, I found that when running the code below, the memory usage increases until the instance runs out of system memory, and then gets killed.

So I would like to ask, does OpenVINO have an operation to release memory? Or other way to work around this issue？

I have an object named ov_ops and it has a function run_async_batch which I call when there is an inference request.
"infer_queue" is a local variable, I think it will be freed when the function returns. And "self.exec_net" is a member variable of the object ov_ops, which has the same life cycle as ov_ops. The return value "res" is a list, I will call the res.clear() to clear it after using it outside the function.

now, when i call run_async_batch  for about 30 times and each call the norm_img_batch_list has 40 items. The system memory(16GB) will be exhausted.

##### my code：

    def run_async_batch(self, norm_img_batch_list) :
        nsize = len(norm_img_batch_list)
        infer_queue = AsyncInferQueue(self.exec_net, nsize)
        for i, input_tensor in enumerate(norm_img_batch_list):
            infer_queue.start_async({0: input_tensor}) 
        infer_queue.wait_all()
        res=[]
        for i in range(nsize) :
            res.append(infer_queue[i].get_output_tensor().data)
        return res

**Comment by a3213105** [comment]
I use memory_profiler to debug the code and it shows that AsyncInferQueue causes a memory leak

Filename: /root/sgui/e2e/ov_operator_async.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
   168 13812.582 MiB 9074.680 MiB          17       @profile
   169                                                                     def run_async_batch(self, norm_img_batch_list) :
   170 13812.582 MiB    0.000 MiB          17               nsize = len(norm_img_batch_list)
   171 13812.582 MiB    0.000 MiB          17               infer_queue = AsyncInferQueue(self.exec_net, nsize)
   172 13812.582 MiB    2.059 MiB         595              for i, input_tensor in enumerate(norm_img_batch_list):
   173 13812.582 MiB   16.297 MiB         578                 infer_queue.start_async({0: input_tensor})
   174 13990.473 MiB 4897.438 MiB          17            infer_queue.wait_all()
   175 13990.473 MiB    0.000 MiB          17               res=[]
   176 13990.473 MiB    0.000 MiB         595              for i in range(nsize) :
   177 13990.473 MiB    0.000 MiB         578                  res.append(infer_queue[i].get_output_tensor().data)
   178 13990.473 MiB    0.000 MiB          17               return [] #res

**Comment by a3213105** [comment]
Filename: /root/sgui/e2e/ov_operator_async.py

Line #    Mem usage    Increment  Occurrences   Line Contents
\=============================================================

   169 13812.582 MiB 9074.680 MiB          17       @profile def run_async_batch(self, norm_img_batch_list) :
   170 13812.582 MiB    0.000 MiB          17           nsize = len(norm_img_batch_list)
   171 13812.582 MiB    0.000 MiB          17           infer_queue = AsyncInferQueue(self.exec_net, nsize)
   172 13812.582 MiB    2.059 MiB         595           for i, input_tensor in enumerate(norm_img_batch_list):
   173 13812.582 MiB   16.297 MiB         578               infer_queue.start_async({0: input_tensor})
   174 13990.473 MiB 4897.438 MiB          17           infer_queue.wait_all()
   175 13990.473 MiB    0.000 MiB          17           res=[]
   176 13990.473 MiB    0.000 MiB         595           for i in range(nsize) :
   177 13990.473 MiB    0.000 MiB         578               res.append(infer_queue[i].get_output_tensor().data)
   178 13990.473 MiB    0.000 MiB          17           return [] #res

**Comment by a3213105** [comment]
The input shape is dynamic, could this be the cause of the memory leak?

**Comment by riverlijunjie** [comment]
If you run dynamic shape inference, it does hold max memory size that have ever allocated to fit the max shape consumption, even if new input tensor become smaller the previous max memory will not be releases, but only to be reused.
We have a PR to fix this issue, maybe you can try it - https://github.com/openvinotoolkit/openvino/pull/11667

**Comment by a3213105** [comment]
Thanks @riverlijunjie, I will try it.
But I think it may not be the reason in my case.
I re-run it 30 times with the same image and the memory is still increasing. As you mentioned, in the first loop, OV will allocate all needed memory, and for other loops, it will reuse this memory without causing memory growth, because they are the same inference request. Is my understanding correct?

**Comment by riverlijunjie** [comment]
yes, If the input tensor shape is not changed any more, the memory size should not increase any more.

In your sample, each run_async_batch will create 40 inferReqs in infer_queue, there will consume huge memory and low performance, why not create 4~8 inferReqs and reuse them?

**Comment by a3213105** [comment]
my case is an OCR workload, the input is the same image, and it has about 40 text lines, so there are 40 inferReqs. And my test is re-run the same image inference to simulate real world.

For each inference, I have printed current memory usage, and you can see it is increasing, and then it will be killed by system.

### Cur Memory: 10.763656616210938
### Cur Memory: 11.076732635498047
### Cur Memory: 11.2989501953125
### Cur Memory: 11.468605041503906
### Cur Memory: 11.698539733886719
### Cur Memory: 11.85184097290039
### Cur Memory: 12.094711303710938
### Cur Memory: 12.26071548461914
### Cur Memory: 12.426036834716797
### Cur Memory: 12.591197967529297
### Cur Memory: 12.747425079345703
### Cur Memory: 13.007747650146484
### Cur Memory: 13.173694610595703
### Cur Memory: 13.331607818603516
### Cur Memory: 13.464851379394531
### Cur Memory: 13.626884460449219
### Cur Memory: 13.80898666381836
### Cur Memory: 13.978931427001953
### Cur Memory: 14.13070297241211
### Cur Memory: 14.309261322021484
### Cur Memory: 14.482795715332031
### Cur Memory: 14.647335052490234
### Cur Memory: 14.820354461669922
### Cur Memory: 14.983699798583984
### Cur Memory: 15.152637481689453
### Cur Memory: 15.339344024658203
### Cur Memory: 15.509037017822266
### Cur Memory: 15.667594909667969
### Cur Memory: 15.841316223144531
### Cur Memory: 16.004409790039062
### Cur Memory: 16.191204071044922
### Cur Memory: 16.351940155029297
### Cur Memory: 16.500755310058594
### Cur Memory: 16.76296615600586
### Cur Memory: 16.934917449951172
### Cur Memory: 17.093223571777344
### Cur Memory: 17.2596435546875
### Cur Memory: 17.440780639648438
### Cur Memory: 17.611228942871094
### Cur Memory: 17.778907775878906
### Cur Memory: 17.926528930664062
### Cur Memory: 18.099864959716797
### Cur Memory: 18.267173767089844
### Cur Memory: 18.442459106445312
### Cur Memory: 18.60655975341797
### Cur Memory: 18.78839111328125
### Cur Memory: 18.96493911743164
### Cur Memory: 19.136898040771484
### Cur Memory: 19.300491333007812
### Cur Memory: 19.480060577392578
### Cur Memory: 19.651012420654297
### Cur Memory: 19.82281494140625
### Cur Memory: 19.992507934570312
### Cur Memory: 20.167625427246094
### Cur Memory: 20.335556030273438
### Cur Memory: 20.475692749023438
### Cur Memory: 20.65802764892578
### Cur Memory: 20.837596893310547
### Cur Memory: 21.01333999633789
### Cur Memory: 21.153709411621094
### Cur Memory: 21.341449737548828
### Cur Memory: 21.49164581298828
### Cur Memory: 21.669261932373047
### Cur Memory: 21.840652465820312
### Cur Memory: 22.00324249267578
### Cur Memory: 22.175968170166016
### Cur Memory: 22.344982147216797
### Cur Memory: 22.525493621826172
### Cur Memory: 22.699970245361328
### Cur Memory: 22.85778045654297
### Cur Memory: 23.018104553222656
### Cur Memory: 23.201065063476562
### Cur Memory: 23.356735229492188
### Cur Memory: 23.542903900146484
### Cur Memory: 23.69939422607422
### Cur Memory: 23.873924255371094
### Cur Memory: 24.04663848876953
### Cur Memory: 24.218597412109375
### Cur Memory: 24.38481903076172
### Cur Memory: 24.55545425415039
### Cur Memory: 24.725902557373047
### Cur Memory: 24.88748550415039
### Cur Memory: 25.063274383544922
### Cur Memory: 25.240829467773438
### Cur Memory: 25.416061401367188
### Cur Memory: 25.586509704589844
### Cur Memory: 25.735698699951172
### Cur Memory: 25.922119140625
### Cur Memory: 26.074329376220703
### Cur Memory: 26.2564697265625
### Cur Memory: 26.43503189086914
### Cur Memory: 26.60623550415039
### Cur Memory: 26.74831771850586
### Cur Memory: 26.934803009033203
### Cur Memory: 27.10726547241211
### Cur Memory: 27.272052764892578
### Cur Memory: 27.431873321533203
### Cur Memory: 27.605648040771484
### Cur Memory: 27.76949691772461
### Cur Memory: 27.950069427490234
### Cur Memory: 28.101329803466797
### Cur Memory: 28.282211303710938
### Cur Memory: 28.425861358642578
### Cur Memory: 28.603160858154297
### Cur Memory: 28.774673461914062
### Cur Memory: 28.944869995117188
### Cur Memory: 29.104248046875
### Cur Memory: 29.27035140991211
### Cur Memory: 29.447906494140625
### Cur Memory: 29.618606567382812
### Cur Memory: 29.770313262939453
### Cur Memory: 29.937602996826172
### Cur Memory: 30.111007690429688
### Cur Memory: 30.302467346191406
### Cur Memory: 30.466537475585938
### Cur Memory: 30.614158630371094
### Cur Memory: 30.79991912841797
### Cur Memory: 30.943531036376953
### Cur Memory: 31.121082305908203
### Cur Memory: 31.279052734375
### Cur Memory: 31.469558715820312
### Cur Memory: 31.63497543334961
### Cur Memory: 31.781841278076172
### Cur Memory: 31.958953857421875
### Cur Memory: 32.13437271118164
### Cur Memory: 32.31444549560547
### Cur Memory: 32.48413848876953
### Cur Memory: 32.65534210205078
### Cur Memory: 32.823020935058594
### Cur Memory: 32.98717498779297
### Cur Memory: 33.140777587890625
### Cur Memory: 33.31681823730469
### Cur Memory: 33.49563217163086
### Cur Memory: 33.660037994384766
### Cur Memory: 33.8204231262207
### Cur Memory: 33.984458923339844
### Cur Memory: 34.15747833251953
### Cur Memory: 34.32878875732422
### Cur Memory: 34.4832649230957
### Cur Memory: 34.65066909790039
### Cur Memory: 34.834449768066406
### Cur Memory: 35.007789611816406
### Cur Memory: 35.18201446533203
### Cur Memory: 35.33170700073242
### Cur Memory: 35.5054817199707
### Cur Memory: 35.6683235168457
### Cur Memory: 35.84442901611328
### Cur Memory: 36.01581954956055
### Cur Memory: 36.181800842285156
### Cur Memory: 36.3638801574707
### Cur Memory: 36.53634262084961
### Cur Memory: 36.69817352294922
### Cur Memory: 36.872901916503906
### Cur Memory: 37.02587127685547
### Cur Memory: 37.1977653503418
### Cur Memory: 37.36821365356445
### Cur Memory: 37.52778244018555
### Cur Memory: 37.71363067626953
### Cur Memory: 37.877281188964844
### Cur Memory: 38.02075958251953
### Cur Memory: 38.20032501220703
### Cur Memory: 38.384986877441406
### Cur Memory: 38.55467987060547
### Cur Memory: 38.72235870361328
### Cur Memory: 38.89079284667969
### Cur Memory: 39.059226989746094
### Cur Memory: 39.2276611328125
### Cur Memory: 39.3968505859375
### Cur Memory: 39.54462814331055
### Cur Memory: 39.72419738769531
### Cur Memory: 39.896156311035156
### Cur Memory: 40.048805236816406
### Cur Memory: 40.21849822998047
### Cur Memory: 40.40189743041992
### Cur Memory: 40.545230865478516
### Cur Memory: 40.72202682495117
### Cur Memory: 40.87765121459961
### Cur Memory: 41.06684112548828
### Cur Memory: 41.2198600769043
### Cur Memory: 41.39413833618164
### Cur Memory: 41.55204772949219
### Cur Memory: 41.744537353515625
### Cur Memory: 41.90298843383789
### Cur Memory: 42.06759262084961
### Cur Memory: 42.25407791137695
### Cur Memory: 42.42628860473633
### Cur Memory: 42.580196380615234
### Cur Memory: 42.76906967163086
### Cur Memory: 42.93825912475586
### Cur Memory: 43.09028244018555
### Cur Memory: 43.280731201171875
### Cur Memory: 43.436214447021484
### Cur Memory: 43.60955047607422
### Cur Memory: 43.77037811279297
### Cur Memory: 43.9560432434082
### Cur Memory: 44.125484466552734
### Cur Memory: 44.28511428833008
### Cur Memory: 44.45964050292969
### Cur Memory: 44.6331901550293
### Cur Memory: 44.7828254699707
### Cur Memory: 44.96113204956055
### Cur Memory: 45.138938903808594
### Cur Memory: 45.30989074707031
### Cur Memory: 45.46160888671875
### Cur Memory: 45.63079833984375
### Cur Memory: 45.799285888671875
### Cur Memory: 45.97074890136719
### Cur Memory: 46.12119674682617
### Cur Memory: 46.312652587890625
### Cur Memory: 46.466121673583984
### Cur Memory: 46.63656997680664
### Cur Memory: 46.80601119995117
### Cur Memory: 46.9762077331543
### Cur Memory: 47.153236389160156
### Cur Memory: 47.32487869262695
### Cur Memory: 47.499534606933594
### Cur Memory: 47.6719970703125
### Cur Memory: 47.823822021484375
### Cur Memory: 47.99093246459961
### Cur Memory: 48.161380767822266
### Cur Memory: 48.323970794677734
### Cur Memory: 48.49265670776367
### Cur Memory: 48.67631530761719
### Cur Memory: 48.84695053100586
### Cur Memory: 49.01004409790039
### Cur Memory: 49.18935775756836
### Cur Memory: 49.347164154052734
### Cur Memory: 49.530311584472656
### Cur Memory: 49.70201873779297
Killed

**Comment by a3213105** [comment]
Actually, I tracked memory malloc/free in plugins/intel_cpu/src/cpu_memory.cpp and they are all paired. Also in plugins/intel_cpu/src/infer_request.cpp, there are no memory leak, so I think the problem maybe in python API

**Comment by riverlijunjie** [comment]
In each run_async_batch loop, it will re-create 40 inferReqs, maybe the inferReqs created in last loop still exist in current loop?
So can you one-time create 40 inferReqs and reuse them in next loop?
I'm not sure whether the problem comes from inferReqs not destruction, could you have a try?

**Comment by a3213105** [comment]
class TextRecognizerResult :
    def __init__(self) :
         self.result = {}

    def completion_callback(self, infer_request: InferRequest, index: int) :
        predictions = next(iter(infer_request.results.values()))
        self.result[index] = predictions


class TextRecognizer():
    def __init__(self, model, core =None):
        if core is None :
            self.core = Core()
        else :
            self.core = core
        self.model = self.core.read_model(model=model)
        
    def setup_model(self, stream_num, shape) :
        if shape is not None :
            self.model.reshape({self.input_name: shape})
        config = self.prepare_for_cpu(stream_num)
        self.exec_net = self.core.compile_model(self.model, 'CPU', config)
        self.num_requests = self.exec_net.get_property("OPTIMAL_NUMBER_OF_INFER_REQUESTS")
        self.infer_queue = AsyncInferQueue(self.exec_net, self.num_requests)   
        self.ocr_res = TextRecognizerResult()
        self.infer_queue.set_callback(self.ocr_res.completion_callback)

 def run_async_batch(self, norm_img_batch_list) :
        for i, input_tensor in enumerate(norm_img_batch_list):
            self.infer_queue.start_async({0: input_tensor}, userdata=i)

        self.infer_queue.wait_all()
        res = []
        for i in range(len(batch_list)) :
            res.append(self.ocr_res.result[i])
        return res

**Comment by jiwaszki** [comment]
Hi @a3213105,

I managed to fix/adjust your snippet and pass fake data inside of it. I was wondering how it is possible that number of call to `start_async` in your loop does not match number of calls to iterator itself.

Your numbers:
![image](https://user-images.githubusercontent.com/65762745/170714293-c2feb322-9652-4f51-927c-4499fc9a8437.png)

My report:
![image](https://user-images.githubusercontent.com/65762745/170714613-2d3c4cf7-7e25-443f-a145-e26e7f0a5b70.png)

I used the same profiler as you, 100000 fake inputs, 12 IR in pool of Queue, simple handcrafted model (note: it was tested at my local master build -- if this makes a difference).

Let's also focus on `wait_all()` call... For some reason this is actually a big surprise for me here. I have created `AsyncInferQueue` and never encountered behavior like this. Could you provide actual reproducer with model and data?

Here is a snippet I ran:
```python
import numpy as np
import openvino.runtime as ov
from memory_profiler import profile

class TextRecognizerResult :
    def __init__(self):
        self.result = {}

    def completion_callback(self, infer_request: ov.InferRequest, index: int):
        predictions = next(iter(infer_request.results.values()))
        self.result[index] = predictions


class TextRecognizer():
    def __init__(self, model=None, core=None):
        if core is None:
            self.core = ov.Core()
        else:
            self.core = core
        param = ov.opset9.parameter(ov.Shape([2, 10]), dtype=np.float32)
        model = ov.Model(ov.opset9.relu(param), [param])
    
        self.model = model

    @profile
    def setup_model(self):
        self.exec_net = self.core.compile_model(self.model, 'CPU')
        # AsyncInferQueue will automatically run this if you don't specify jobs
        # self.num_requests = self.exec_net.get_property("OPTIMAL_NUMBER_OF_INFER_REQUESTS")
        self.infer_queue = ov.AsyncInferQueue(self.exec_net, jobs=12)
        self.ocr_res = TextRecognizerResult()
        self.infer_queue.set_callback(self.ocr_res.completion_callback)

    @profile
    def run_async_batch(self, norm_img_batch_list):
        for i, input_tensor in enumerate(norm_img_batch_list):
            self.infer_queue.start_async({0: input_tensor}, userdata=i)

        self.infer_queue.wait_all()
        res = []
        for i in range(len(norm_img_batch_list)) :
            res.append(self.ocr_res.result[i])
        self.ocr_res.result.clear()
        return res

data_shape = [100000, 2, 10]
fake_data = np.random.rand(*data_shape) - 0.5
results_ref = np.maximum(fake_data, 0)

my_infer_engine = TextRecognizer()
my_infer_engine.setup_model()
results_ov = my_infer_engine.run_async_batch(fake_data)

assert np.allclose(results_ov, results_ref)
```

**Comment by a3213105** [comment]
I have confirmed that these is not a memory leak. The memory increasing caused by cache. (openvino/src/plugins/intel_cpu/src/cache/)
If I set config['CPU_RUNTIME_CACHE_CAPACITY'] = '0' the memory increase goes away :)
But now the question is, why the cache doesn't cache the primitive, or caches it but doesn't find it when it needs to be reused.
I repeat the same 40 inferences, although the 40 inputs have different shapes, I think when I repeat them, the 40 different shapes of primitives should have been cached,
I will continue to investigate this issue.

**Comment by a3213105** [comment]
hi @jiwaszki   595 = 578+17 as yours is 100001=100000+1.
i have run run_async_batch for many times. 
your input is the same shape, but mine is not.
as i mentioned in last reply. the cache caused the memory increasing.
thanks for your time to investigate my issue :)

**Comment by jiwaszki** [comment]
> hi @jiwaszki 595 = 578+17 as yours is 100001=100000+1. i have run run_async_batch for 17 times.

Oh... my bad! I forgot to include the fact that it was run 17 times.

> as i mentioned in last reply. the cache caused the memory increasing.

Glad to see a progress with the investigation! @riverlijunjie let's raise that topic as soon as possible.

**Comment by a3213105** [comment]
@jiwaszki @riverlijunjie 
I reviewed the code, I think the cache is not actually invalid. I use 8 streams, and each stream will have its own set of caches, but different shapes are randomly matched to the streams when called, so all 40 different shapes need to be cached 8 copies to 8 different cache pools , this amount may have exceeded my 16GB dram, I also tested on a 64GB dram machine and the dram was also exhausted.

So I think we should change the cache strategy, such as no cache for dynamic shape. Or set the memory max limit of the cache pool during configuration to avoid memory exhaustion.

The description of the configuration file also needs to be optimized. The current configuration option is the number of items in cache, and ordinary users cannot associate the number with the final amount of memory.

**Comment by a3213105** [comment]
Thanks for your help, @riverlijunjie @jiwaszki . 
I will close this issue first. I will check the cache problem later, if there is a real problem with the cache strategy, I will raise another issue

**Comment by xipingyan** [comment]
hi @a3213105 , I also try your code, I found only OCR network exist the problem, the detection network is OK. 
So please also pay attention the difference of the both networks in your next verifiction.

**Comment by a3213105** [comment]
@xipingyan ,  yes, i think it because my input image is the same, so detection network did not change the shape. And i will test more different shape to confirm this.
