### ISSUE TITLE
not possible to configure Neural Computer Styck with OpenVINO: 2022.1 (Pypi)

### ISSUE THREAD

**Issue by fenaux** [openvinotoolkit/openvino#11722]
##### System information (version)
 Ubuntu 20.04.4 LTS
-Pip version: 22.1
OpenVINO source: /home/fenaux/openvino_env/lib/python3.9/site-packages/openvino
OpenVINO IE version: 2022.1.0-7019-cdb9bec7210-releases/2022/1
OpenVINO environment activated: OK
Jupyter kernel installed for openvino_env: NOT OK
Python version: 3.9 OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: OK

Problem :
To configure Neural computer stick 
https://docs.openvino.ai/latest/openvino_docs_install_guides_configurations_for_ncs2.html
I do not have any install_dependencies directory
nor install_NCS_udev_rules.sh script.

Should I follow #11476 ?
if yes the command line should be performed in the same <INSTALL_DIR> ?

thanks for your help

**Comment by fenaux** [comment]
I discover the problem with
https://github.com/openvinotoolkit/openvino_notebooks/issues/556

**Comment by jgespino** [comment]
@fenaux The Myriad Plugin is not part of the pip package. You must install OpenVINO using the [Offline/Online installer](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html) and run the scripts mentioned in the [additional instructions](https://docs.openvino.ai/latest/openvino_docs_install_guides_configurations_for_ncs2.html) for NCS 2.

**Comment by fenaux** [comment]
thanks
I follow instruction here https://docs.openvino.ai/nightly/openvino_docs_install_guides_installing_openvino_linux.html
step 1.5 fails with this message
"system requirements not met
Not enough permissions
Directory /home/fenaux/intel requires write permissions"

here is the result of ls -l
drwxr-xr-x  2 root   root    4096 oct.   2  2019 intel


I try with 
chmod g+w intel
but I got permission denied !

**Comment by jgespino** [comment]
@fenaux Probably some configuration issue on your sytem as you shouldn't see any permission issues in your home directory. When running the sh script from the offline installer, the intel directory was automatically created in my home directory with the following permissions. Please try modifying your intel directory permissions using `chmod 775 intel`. If that does not work, try running the installation script using sudo this will install openvino in `/opt/intel/openvino/2022`

![image](https://user-images.githubusercontent.com/18014973/169580674-0e741f3d-cdf5-4ea7-afcf-22ee500f6e8c.png)

**Comment by fenaux** [comment]
Thanks but I am a bit lost...

I think this "intel" directory was created during a first installation of openvino in 2019. This directory is the only one with these permissions. So I think it was created with this permissions by the installation.
- Files where installed in openvino_training_extensions-develop
- so now I have a second directory openvino_env with 2021 version as describe in https://pypi.org/project/openvino/
- as chmod 775 intel does not work I should run the installation with sudo and get an openvino in a third directory.

Is there a way to clean something  ?

**Comment by jgespino** [comment]
@fenaux That does sound messy, I would recommend uninstalling all previous installations of OpenVINO and remove any files of built samples or downloaded IR models to avoid any conflicts going forward. 

> Files where installed in openvino_training_extensions-develop

Are you referring to this repository? This repository is separate from OpenVINO installation.

> so now I have a second directory openvino_env with 2021 version as describe in https://pypi.org/project/openvino/

If you want to remove the pip installation, just remove the openvino_env directory. 

An alternative would be to start with a clean Ubuntu 20.04 install on your system.

**Comment by fenaux** [comment]
Thanks

I manage to change to change intel directory permission
drwxrwxr-x  2 root   root    4096 oct.   2  2019 intel
with sudo chmod 775 intel 

then  removed openvino_training_extensions-develop

I am now ready to delete he openvino_env directory and perform the installation as describe
here https://docs.openvino.ai/nightly/openvino_docs_install_guides_installing_openvino_linux.html

Sorry but I have one more question before doing that : as to perform Pypi installation it was needed to create a virtual environment, should I perform the new  installation in my default environment or create a dedicated environment ?

**Comment by jgespino** [comment]
@fenaux The installer will install OpenVINO on your default environment. We recommend creating a virtual environment when using the Pypi installation method. In this case, just install it to your default environment.

**Comment by fenaux** [comment]
Thanks @jgespino ,

Installation worked pretty well note that chmod was not enough I nedded chown from root to fenaux to run the installation
Once installation completed, I could run the model with 
compiled_model = ie_core.compile_model(model=model, device_name="CPU")

then I moved to NCS intallation ran the install_NCS_udev_rules.sh script and restarted my machine.
Then with the command
compiled_model = ie_core.compile_model(model=model, device_name="MYRIAD")
I got
 File "/home/fenaux/stick/contact/test_ext.py", line 36, in <module>
    compiled_model = ie_core.compile_model(model=model, device_name="MYRIAD")
  File "/home/fenaux/intel/openvino_2022/python/python3.9/openvino/runtime/ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Failed to allocate graph: MYRIAD device is not opened.

the device is there indeed :(.

**Comment by fenaux** [comment]
Sure
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 04ca:7054 Lite-On Technology Corp. HP HD Camera
Bus 001 Device 005: ID 8087:0a2b Intel Corp. 
Bus 001 Device 048: ID 1a7c:0191 Evoluent VerticalMouse 4
Bus 001 Device 011: ID 413c:2010 Dell Computer Corp. Keyboard
Bus 001 Device 010: ID 413c:1003 Dell Computer Corp. Keyboard Hub
Bus 001 Device 012: ID 03e7:2150 Intel Myriad VPU [Movidius Neural Compute Stick]
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by jgespino** [comment]
@fenaux Thanks! Looks like you are using the original Intel Movidius Neural Compute Stick with Intel Myriad 2 VPU which has been discontinued and is no longer supported by OpenVINO. If you want to continue using OpenVINO with the Intel Neural Compute Stick please install OpenVINO 2020.3 LTS release.

Additional information can be found in the OpenVINO 2020 [release notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes-2020.html).

**Comment by jgespino** [comment]
@fenaux OpenVINO 2020.3 LTS release does not support Ubuntu 20.04, during the installation you should have seen the following page. You will need to use of of the supported OS. With OpenVINO 2020.3 LTS release, we only had one installation package, it was not split into runtime or devtools at the time.

![image](https://user-images.githubusercontent.com/18014973/170306292-32d173f8-0d33-4a94-97ab-cc9e43e165f8.png)

**Comment by fenaux** [comment]
@jgespino 

Thanks a lot for all your support. I really do appreciate. But I will not go this way. :(
I do not know if other packages installed on my computer are available with Ubuntu 18.04 and in addition I wish to run yolov5 that needs Python >= 3.7

I have two last remarks (or questions)
I was surprised by, by the fact I got and old version of Neural Compute Stick. I bought it 2 weeks ago ! Can you tell me what is the name of the product I should look for ? And if it will be deprecated soon ;) ? 

I translated Yolov5x following this procedure https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/102-pytorch-onnx-to-openvino
with original Pytorch model mean inference time 1.35 s / image
with openVino optimized model inference time is 1.63 s /image
(CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz)

**Comment by jgespino** [comment]
@fenaux OpenVINO supports the Intel Neural Compute Stick 2 and Intel Vision Accelerator Designs with Intel Myriad X VPU:
https://www.intel.com/content/www/us/en/developer/topic-technology/edge-5g/hardware/vision-accelerator-movidius-vpu.html

> And if it will be deprecated soon ;), I saw on a site selling it that it's an end of life product" ?

I am checking with the product manager on this and will provide an update once I have more information.
