### ISSUE TITLE
[Bug][Test] ConvertColorI420 SetUp issue (?)

### ISSUE THREAD

**Issue by AndreiLupas** [openvinotoolkit/openvino#11736]
ConvertColorI420LayerTest::SetUp() instantiates **::NV12toRGB** op but should be the **::I420toRGB** instead ?
https://github.com/openvinotoolkit/openvino/blob/master/src/tests/functional/shared_test_classes/src/single_layer/convert_color_i420.cpp#L38

**Comment by jgespino** [comment]
@AndreiLupas I opened an internal ticket for the development to take a look. 

Ref. 85603

**Comment by ilya-lavrenov** [comment]
@AndreiLupas you are right, could you please create a PR fixing this?

**Comment by avitial** [comment]
@AndreiLupas as suggested by Ilya, you can create PR from your own fork. Refer to for more info [https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md).
