### ISSUE TITLE
[unsolved] How can I specify a single threaded runner in OpenVINO runtime API2.0

### ISSUE THREAD

**Issue by Aed-p** [openvinotoolkit/openvino#11740]
My openvino version is 2022.1, Now, I want to run the inference program on an E5 2680 CPU, How to specify a single thread to run the inference program?

**Comment by brmarkus** [comment]
The CPU plugin of the InferenceEngine has config-options like `CPU_THREADS_NUM` (max. number of threads to use, INTEGER; max. number is the number of physical cores with ignoring potential HyperThreading) and `CPU_BIND_THREAD` (bind the thread(s) to a specific CPU-(NUMA)-core).

See the config-keys here: https://docs.openvino.ai/2022.1/namespaceInferenceEngine_1_1PluginConfigParams.html

See additional hints here: https://docs.openvino.ai/latest/ovms_docs_performance_tuning.html?highlight=cpu_threads_num#scalability

**Comment by Aed-p** [comment]
thank you very much

**Comment by riverlijunjie** [comment]
@Aed-p could you please close this tickets if it has been addressed?

**Comment by ashray21** [comment]
@Aed-p 
If you are able to run openvino inference on single thread can you please guide me how I can do that.
