### ISSUE TITLE
Error on Onnx to Openvino IR Conversion

### ISSUE THREAD

**Issue by justin-larking-pk** [openvinotoolkit/openvino#11786]
##### System information 
- OpenVINO => 2022.1.0
- Operating System / Platform => Ubuntu 20.04 64 Bit
- Environment Pip and conda (does this for both)
- Problem classification: Model Conversion
- Framework: Pytorch -> Onnx -> Openvino
- Model name: Mobilenetv3

##### Detailed description
When converting from an onnx model exported from pytorch, the conversion fails.
Outputs:

[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  While validating ONNX node '<Node(Conv): Conv_0>':
Check 'input_shape[1].compatible(filters_shape[1])' failed at core/shape_inference/include/convolution_shape_inference.hpp:265:
While validating node 'v1::Convolution Convolution_109 (input.1[0]:f32{1,256,128,3}, 421[0]:f32{16,3,3,3}) -> (dynamic...)' with friendly_name 'Convolution_109':
Data batch channel count (256) does not match filter input channel count (3).

Offending file:
[mbnetv3_embeddings.zip](https://github.com/openvinotoolkit/openvino/files/8828233/mbnetv3_embeddings.zip)

**Comment by Iffa-Meah** [comment]
@justin-larking-pk I manage to convert your model into IR (static and dynamic shape) and also able to infer them including the native ONNX format.

ONNX benchmark_app (inference)
command: benchmark_app -m mbnetv3_embeddings.onnx

<img width="501" alt="benchmarkonnx" src="https://user-images.githubusercontent.com/79643476/171791828-5edb92bf-2f78-4476-9eb3-30024dc0da25.png">

Convert ONNX into IR static shape (default FP32)
command as attachment

<img width="704" alt="IRstatic" src="https://user-images.githubusercontent.com/79643476/171792134-0da34c2a-3e23-430f-a75a-e02e1bd00e8a.png">

IR Static benchmark_app (inference)
command: benchmark_app -m mbnetv3_embeddings.xml

<img width="696" alt="IRstaticBenchmark" src="https://user-images.githubusercontent.com/79643476/171792239-a5d076f6-40ae-4789-b14f-9be4f5f4c8d9.png">

Convert ONNX into IR dynamic shape (default FP32)
command as attachment

<img width="693" alt="IRdynamic" src="https://user-images.githubusercontent.com/79643476/171792349-7d4d8665-e522-474f-bec5-9431deb8b196.png">

IR Static benchmark_app (inference)
commands: benchmark_app -m mbnetv3_embeddings.xml -data_shape [1,3,256,100]
                   benchmark_app -m mbnetv3_embeddings.xml -data_shape [2,3,256,100]
                   benchmark_app -m mbnetv3_embeddings.xml -data_shape [3,3,256,100]

<img width="692" alt="IRdynamicbenchmark_datashape" src="https://user-images.githubusercontent.com/79643476/171792599-df2e8ab4-ea77-453a-9a1d-925c5cc71df0.png">

OR

IR Static benchmark_app (inference)
commands: benchmark_app -m mbnetv3_embeddings.xml -shape [1,3,256,100]
                   benchmark_app -m mbnetv3_embeddings.xml -shape [2,3,256,100]
                   benchmark_app -m mbnetv3_embeddings.xml -shape [3,3,256,100]

<img width="697" alt="IRdynamicbenchmark_shape" src="https://user-images.githubusercontent.com/79643476/171792683-703b5c02-4cb1-4e87-9157-a0d2619411d1.png">

**Comment by justin-larking-pk** [comment]
Ah so the issue was an incorrectly defined input shape? As I was parsing [1,256,128,3], as it showed here:
https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model.html#doxid-openvino-docs-m-o-d-g-prepare-model-convert-model-converting-model

but in future when converting a model it should be defined [batch_size, channels, heigt, width], if thats how its defined where the model was created?

**Comment by Iffa-Meah** [comment]
@justin-larking-pk, the input shapes for Tensorflow and ONNX are different (there are different model types in that documentation). The Tensorflow often requires to be reversed, depending on how the model was handled/processed.

The input shape I used in the conversion above is what I can see from your original model itself. You may look at the inference of your native ONNX model (the 1st image).

**Comment by zulkifli-halim** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
