### ISSUE TITLE
Use cldnn from system if available.

### ISSUE THREAD

**Issue by tripzero** [openvinotoolkit/openvino#118]
Right now you cannot compile the GPU device plugin without ENABLE_CLDNN and ENABLE_CLDNN automatically tries to build CLDNN from thirdparty.  CLDNN plugin should try to use CLDNN installed separately on system before using thirdparty/cldnn.

**Comment by ilya-lavrenov** [comment]
Why do you think so?
CLDNN which is a part of DLDT source tree is more fresh and optimised.

**Comment by tripzero** [comment]
What if another project uses cldnn?  Now you have two versions installed for no reason.  If there are non-upstream optimizations to cldnn, they should be made part of the upstream otherwise other projects will not benefit.  Likewise, fixes that happen upstream will not be automatically pulled into dldt's fork without extra efforts.

Another project that does this is ngraph.  If you have dldt and ngraph on same system, you have two different trees of cldnn and two different installs.  This will cause problems during link/runtime.

**Comment by vladimir-paramuzov** [comment]
CLDNN is not supported anymore as a standalone project. So the issue seems to be not relevant anymore.
