### ISSUE TITLE
pip install openvino-dev[pytorch] fails at fast-ctc-decode requirement

### ISSUE THREAD

**Issue by mjohannessen** [openvinotoolkit/openvino#11801]
I'm attempting to install OpenVINO dev tools on a Raspberry Pi 4b, with failure at a requirement for fast-ctc-decode, which does not have an appropriate version.  Here are the details:

Hardware: Raspberry Pi 4b

OS:

$ lsb_release -a >
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

Python:

$ python -V > Python 3.8.13
$ python -m pip install --upgrade pip
Requirement already satisfied: pip in ./.pyenv/versions/3.8.13/lib/python3.8/site-packages (22.1.2)
$ pip3 install numpy
Requirement already satisfied: numpy in ./.pyenv/versions/3.8.13/lib/python3.8/site-packages (1.22.4)

Run installation command:

$ pip3 install openvino-dev[pytorch]==2022.1.0
Collecting openvino-dev[pytorch]==2022.1.0
  Using cached openvino_dev-2022.1.0-7019-py3-none-any.whl (5.8 MB)
Collecting defusedxml>=0.7.1
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting numpy<=1.21,>=1.16.6
  Using cached numpy-1.21.0-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.0 MB)
Collecting py-cpuinfo>=7.0.0
  Using cached py-cpuinfo-8.0.0.tar.gz (99 kB)
  Preparing metadata (setup.py) ... done
Collecting parasail>=1.2.4
  Using cached parasail-1.2.4.tar.gz (77 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-image>=0.17.2
  Using cached scikit_image-0.19.2-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.5 MB)
Collecting lmdb>=1.2.1
  Using cached lmdb-1.3.0-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (298 kB)
Collecting sentencepiece>=0.1.95
  Using cached sentencepiece-0.1.96-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.2 MB)
Collecting numpy<=1.21,>=1.16.6
  Using cached numpy-1.19.5-cp38-cp38-manylinux2014_aarch64.whl (12.4 MB)
Collecting rawpy>=0.16.0
  Using cached rawpy-0.17.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.9 MB)
Collecting transformers>=4.5
  Using cached transformers-4.19.2-py3-none-any.whl (4.2 MB)
Collecting tqdm>=4.54.1
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
ERROR: Could not find a version that satisfies the requirement fast-ctc-decode>=0.2.5 (from openvino-dev[pytorch]) (from versions: none)
ERROR: No matching distribution found for fast-ctc-decode>=0.2.5

Attempt to install fast-ctc-decode:

$ pip3 install fast-ctc-decode
ERROR: Could not find a version that satisfies the requirement fast-ctc-decode (from versions: none)
ERROR: No matching distribution found for fast-ctc-decode

**Comment by Iffa-Meah** [comment]
@mjohannessen , 

currently, the OpenVINO was [officially supported & validated on these OS only](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux):

Ubuntu* 18.04 (64-bit) with default GCC* 7.5.0
Ubuntu* 20.04 (64-bit) with default GCC* 9.3.0
Red Hat* Enterprise Linux* 8.2 (64-bit) with default GCC* 8.5.0
[Raspbian Stretch OS](https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS)

It is recommended to revert to Ubuntu 20.04 instead of 22.04 in order to use it with OpenVINO.

**Comment by mjohannessen** [comment]
Conversion done with same error:

$ python -V
Python 3.8.10

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

$ pip instsll numpy

$ pip install openvino-dev[pytorch]==2022.1.0
Defaulting to user installation because normal site-packages is not writeable
Collecting openvino-dev[pytorch]==2022.1.0
  Using cached openvino_dev-2022.1.0-7019-py3-none-any.whl (5.8 MB)
Collecting pyyaml>=5.4.1
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (721 kB)
Collecting py-cpuinfo>=7.0.0
  Using cached py-cpuinfo-8.0.0.tar.gz (99 kB)
  Preparing metadata (setup.py) ... done
Collecting nibabel>=3.2.1
  Using cached nibabel-3.2.2-py3-none-any.whl (3.3 MB)
Collecting numpy<1.20,>=1.16.6
  Using cached numpy-1.19.5-cp38-cp38-manylinux2014_aarch64.whl (12.4 MB)
ERROR: Could not find a version that satisfies the requirement fast-ctc-decode>=0.2.5 (from openvino-dev[pytorch]) (from versions: none)
ERROR: No matching distribution found for fast-ctc-decode>=0.2.5

$ pip install fast-ctc-decode
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement fast-ctc-decode (from versions: none)
ERROR: No matching distribution found for fast-ctc-decode

**Comment by Iffa-Meah** [comment]
I used the Ubuntu 20.04 which obtained from the official Raspberry Pi imager.

<img width="339" alt="piImager" src="https://user-images.githubusercontent.com/79643476/172746971-8873ede7-327e-4b8f-8c32-4945d40a650e.png">

I specified Tensorflow2 and ONNX to check the installation of the combination of Armv7 with Ubuntu (This usually works with my Ubuntu OS with i7 processor)
![piUbuntuOV](https://user-images.githubusercontent.com/79643476/172747155-591ffb0c-35b7-4dd3-a324-d84632ddf652.png)
 

Generally, the OpenVINO is validated on [Raspberry Pi (armv7) with Raspbian OS
](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_raspbian.html#doxid-openvino-docs-install-guides-installing-openvino-raspbian)

Other OS combination with the armv7 (Raspberry Pi) may or may not works.
You could try to use the [build from source option](https://github.com/openvinotoolkit/openvino/wiki/BuildingCode) **as a workaround**.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by nserrino** [comment]
When will 22.04 be supported?

**Comment by trinhgiahuy** [comment]
Hello, 

I installed OpenVINO-dev for Ubuntu 20.04 server obtained from the official Raspberry Pi imager as well but encounter same error. How can I solve it.

![image](https://user-images.githubusercontent.com/65078173/196354482-cbbd444c-f918-42d2-8b44-f6e0c11f9368.png)
