### ISSUE TITLE
[Bug] load model crash with intel GPU

### ISSUE THREAD

**Issue by wang7393** [openvinotoolkit/openvino#11830]
##### System information (version)
- OpenVINO => 2021.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
- Problem classification: Model load with intel gpu
- Framework: onnx
- Model name: [deep-hough-transform](https://github.com/Hanqer/deep-hough-transform)

##### Detailed description

load with cpu, success
but load with gpu, crash.
The main reason for the crash  is the optimization of the following structure:
![image](https://user-images.githubusercontent.com/29936604/172569161-1f14fd48-bee5-4436-bf93-43159544349f.png)

It will go to the code（prepare_primitive_fusing.cpp：1002）:
`if (recalc_processing_order)`
`p.get_processing_order().calc_processing_order(p);`

and crashed at this code(nodes_ordering.cpp: 20):
` calc_processing_order_visit(user);`

how to solve it?

**Comment by Iffa-Meah** [comment]
@wang7393 could you share your ONNX model files?

**Comment by wang7393** [comment]
hi, I have modified the model like this, it can be loaded successful wit gpu.
![image](https://user-images.githubusercontent.com/29936604/172831445-add82566-e18c-4fc5-9eb7-7752a0c9c5b0.png)
And, I have  regenerated two models :
[model.zip](https://github.com/openvinotoolkit/openvino/files/8869692/model.zip)
the first.onnx can load successful with gpu, but the second.onnx can not.
Maybe the optimization needs to be further optimized.

**Comment by Iffa-Meah** [comment]
@wang7393 I managed to run both of them using OpenVINO Benchmark Python Tool (OV version 2022.1)

First model
<img width="702" alt="first" src="https://user-images.githubusercontent.com/79643476/172990380-51cea658-38ca-497f-8bbb-5200968c781b.png">

Second model
<img width="804" alt="second" src="https://user-images.githubusercontent.com/79643476/172990426-02c0092a-9de2-4024-9e06-40ac22b94e5a.png">

Try to use the official OpenVINO sample and apply it to your custom code (if you are trying to create your own inferencing code)

**Comment by wang7393** [comment]
> @wang7393 I managed to run both of them using OpenVINO Benchmark Python Tool (OV version 2022.1)
> 
> First model <img alt="first" width="702" src="https://user-images.githubusercontent.com/79643476/172990380-51cea658-38ca-497f-8bbb-5200968c781b.png">
> 
> Second model <img alt="second" width="804" src="https://user-images.githubusercontent.com/79643476/172990426-02c0092a-9de2-4024-9e06-40ac22b94e5a.png">
> 
> Try to use the official OpenVINO sample and apply it to your custom code (if you are trying to create your own inferencing code)
