### ISSUE TITLE
[Bug]Elementwise operation 'Mul_1444' has inputs of different data types: 'float16' and 'float32' that cannot be aligned

### ISSUE THREAD

**Issue by wang7393** [openvinotoolkit/openvino#11847]
##### System information (version)
- OpenVINO => 2021.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: Model Conversion
- Framework: onnx

##### Detailed description
As the title, the following structure to fp16 report the error:
![image](https://user-images.githubusercontent.com/29936604/172979125-9efdbf5e-800a-4c8d-a914-35272577e799.png)
the sin or cos's output is float32, and the ReduceSum's output is float fp16, how to solve this problem when convert to fp16 model?

**Comment by zulkifli-halim** [comment]
Hello @wang7393, please share with us your ONNX model and MO command used to convert the model.

**Comment by zulkifli-halim** [comment]
Closing, please re-open if additional assistance is needed.
