### ISSUE TITLE
DLL load failed while importing ie_api

### ISSUE THREAD

**Issue by jyr12121** [openvinotoolkit/openvino#11856]
##### System information (version)

- OpenVINO= 2022.1
- Operating System / Platform => Windows 64 Bit
- Problem classification => :grey_question:
- Problem classification: Model Conversion
- Framework: onnx 
- Model name: yolov5

##### Detailed description
The following errors occurred in the process of inferring and predicting the IR model
you can find the python file from https://github.com/violet17/yolov5_demo.git
this python file can not work on my computer which CPU is  i5-8250U,but it works on i5-10210y
![error](https://user-images.githubusercontent.com/75134085/173028034-f0b11e2a-5c50-4b94-b58f-a5e8e6079b1c.png)

**Comment by zulkifli-halim** [comment]
Hello @jyr12121, have you tried rerunning the _setupvars.bat_?
