### ISSUE TITLE
compile_tool GENERAL_ERROR

### ISSUE THREAD

**Issue by ynjiun** [openvinotoolkit/openvino#11860]
Hi,

I tried to compile my IR (.xml and .bin) into a VPU blob as below:

```
/opt/intel/openvino_2022/tools/compile_tool/compile_tool \
    -m ./eth3d.xml \
    -d MYRIAD \
    -ip FP16 \
    -VPU_NUMBER_OF_SHAVES 8 \
    -VPU_NUMBER_OF_CMX_SLICES 8 \
    -op FP16 
```

and encounter following error message:

```
OpenVINO Runtime version ......... 2022.1.0
Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
Network inputs:
    input : f16 / [...]
Network outputs:
    reference_output_disparity:0 : f16 / [...]
[ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/frontend/frontend.cpp:592 Failed to compile layer "level0/shared/prop0/WarpImageWithHypotheses/get_warp1d_coordinates_from_tile_hypotheses/get_warp_disparity": [ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/model/model.cpp:198 duplicateData error: while duplicating level0/shared/prop0/WarpImageWithHypotheses/get_warp1d_coordinates_from_tile_hypotheses/get_warp_disparity@weights Const data got different desc and content byte sizes (24 and 96 respectively)
```

attached below please find the eth3d.xml and eth3d.bin in a eth3d.zip for your duplication.

[eth3d.zip](https://github.com/openvinotoolkit/openvino/files/8884878/eth3d.zip)

Be aware that this eth3d IR was converted from a tensorflow model with NHWC input format. I am not sure whether this might upset the compile_tool or not. Is there a way to --disable_nhwc_to_nchw for comple_tool just like mo does?

Please advise how to fix the above error. Thanks a lot.

**Comment by zulkifli-halim** [comment]
Hello @ynjiun, we received the same error when compiling the model using MYRIAD. 
```
pse@gcsaisw-up2e3950-l:/opt/intel/openvino_2022.1.0.643/tools/compile_tool$ ./compile_tool -m /home/pse/Downloads/eth3d/eth3d.xml -d MYRIAD -ip FP16 -VPU_NUMBER_OF_SHAVES 8 -VPU_NUMBER_OF_CMX_SLICES 8 -op FP16
OpenVINO Runtime version ......... 2022.1.0
Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
Network inputs:
    input : f16 / [...]
Network outputs:
    reference_output_disparity:0 : f16 / [...]
[ GENERAL_ERROR ]
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu18/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/frontend/frontend.cpp:592 Failed to compile layer "level0/shared/prop0/WarpImageWithHypotheses/get_warp1d_coordinates_from_tile_hypotheses/get_warp_disparity": [ GENERAL_ERROR ]
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu18/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/model/model.cpp:201 duplicateData error: while duplicating level0/shared/prop0/WarpImageWithHypotheses/get_warp1d_coordinates_from_tile_hypotheses/get_warp_disparity@weights Const data got different desc and content byte sizes (24 and 96 respectively)
```
We've also tested your model using [benchmark_app ](https://docs.openvino.ai/2022.1/openvino_inference_engine_tools_benchmark_tool_README.html)with CPU and MYRIAD as the target devices. We obtained expected results for CPU, but for MYRIAD it gives the same error as in compile tool.

For further investigation, please share with us your TensorFlow model in .pb format and the MO command used to convert the model.

**Comment by ynjiun** [comment]
Hi @zulkifli-halim 

Attached please find the tensorflow model eth3d.pb zipped in eth3dpb.zip below:
[eth3dpb.zip](https://github.com/openvinotoolkit/openvino/files/8901831/eth3dpb.zip)

The command I use to convert this model to IR as following:

```
mo --input_model ../models/eth3d.pb --input_shape [1,480,640,2] --disable_nhwc_t
o_nchw --data_type=FP16
```

Thank you very much for your help.

**Comment by zulkifli-halim** [comment]
Hi @ynjiun. The error message is for op: Conv3DBackpropInputV2 which is a 3D convolution layer. Myriad does not support 3D convolution operations.

**Comment by zulkifli-halim** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
