### ISSUE TITLE
"RuntimeError: Cannot get dims for non static shape" while inferencing openvino

### ISSUE THREAD

**Issue by korotaS** [openvinotoolkit/openvino#11918]
Hello!
I have a strange issue while inferencing openvino (version 2022.1.0). There is a simple class:
```python
import openvino.runtime as ov
import numpy as np

class OpenVinoEngine():
    def __init__(self, model_fpath, num_workers):
        core = ov.Core()
        raw_model = core.read_model(model_fpath, "AUTO")
        self.model = core.compile_model(raw_model, "CPU", config={"INFERENCE_NUM_THREADS": str(num_workers)})
        self.infer_request = self.model.create_infer_request()  # line 1

    def process(self, batch):
        # self.infer_request = self.model.create_infer_request()  # line 2
        self.infer_request.infer([batch])
        output = [out.data[:] for out in self.infer_request.output_tensors]
        if len(output) > 1:
            return output
        return output[0]

eng = OpenVinoEngine('model.onnx', 8)
out = eng.process(np.random.rand(1, 3, 32, 256))
```

The engine is working when passing my model with dynamic input shape `{?,3,?,?}` ([model.onnx.zip](https://github.com/openvinotoolkit/openvino/files/8929111/model.onnx.zip)) and other models too. But there is a huge memory leak - my full pipeline (which has a couple of these engines with different models), which took about 3GB with `onnxruntime` inference, suddenly after 10 requests takes up to 5-6GB and keeps increasing. 
So I try to comment line 1 and uncomment line 2, but there is an error on the very first request:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_2333043/2507853659.py in <module>
----> 1 out = eng.process(np.random.rand(1, 3, 32, 256))

/tmp/ipykernel_2333043/1809003609.py in process(self, batch)
      9 
     10     def process(self, batch):
---> 11         self.infer_request = self.model.create_infer_request()
     12         self.infer_request.infer([batch])
     13         output_tensors = [out.data[:] for out in self.infer_request.output_tensors]

~/env/lib/python3.8/site-packages/openvino/runtime/ie_api.py in create_infer_request(self)
    157         :rtype: openvino.runtime.InferRequest
    158         """
--> 159         return InferRequest(super().create_infer_request())
    160 
    161     def infer_new_request(self, inputs: Union[dict, list] = None) -> dict:

RuntimeError: Cannot get dims for non static shape
```
The error says that something is wrong with dynamic shape but in case with line 1 it works perfectly with the same model.
Maybe someone has faced similar problems? Also maybe there is a simpler way to deal with this memory issue? 
Any clues would be highly appreciated.

**Comment by Iffa-Meah** [comment]
@korotaS 

Starting from the 2020.4 release, OpenVINO™ supports reading native ONNX models, therefore, the model should be able to infer without conversion, if it is supported.

I tested your model using OpenVINO Benchmark App. The model seems to be dynamic as you mentioned but it requires data shape. May I know what data shape you use for this?
Usually, the native ONNX & dynamic model would run without asking for data shape (which only occurs for static model).

<img width="750" alt="modelonnx" src="https://user-images.githubusercontent.com/79643476/174545765-fb1dcd82-0ad7-47f6-ba8c-9b9dc8d4561b.png">

**Comment by korotaS** [comment]
@Iffa-Meah 
Thank you for the reply. 
I exported the model with the shape (1, 3, 32, 256) and it is used with variable batch size and variable image width (first and last dimensions).

**Comment by Iffa-Meah** [comment]
@korotaS 

I used that shape but still does not work.

<img width="750" alt="model Shape" src="https://user-images.githubusercontent.com/79643476/174548349-dceb7827-8abe-427c-adc0-517a2c6a7756.png">

I noticed that the native ONNX has NCHW: ?3??

Usually, a working native ONNX would have some shape defined such as NCHW: 1,3,256,128.
You may refer [here](https://user-images.githubusercontent.com/79643476/171791828-5edb92bf-2f78-4476-9eb3-30024dc0da25.png).

The conversion to Dynamic IR should look like [this](https://user-images.githubusercontent.com/79643476/171792349-7d4d8665-e522-474f-bec5-9431deb8b196.png) and the successful Dynamic IR inference shoud be like [this](https://user-images.githubusercontent.com/79643476/171792599-df2e8ab4-ea77-453a-9a1d-925c5cc71df0.png).

**Comment by korotaS** [comment]
@Iffa-Meah 
I will now try to convert to IR my model via MO, as you mentioned, with dynamic shapes and check its performance. 
But shouldn't the native ONNX work successfully with dynamic shapes while inferencing in OpenVino?

**Comment by Iffa-Meah** [comment]
@korotaS yeah it should, that's why I get back to you with previous questions.
If the inferencing after conversion also didn't work, then it's probably related to the native ONNX model's shape (NCHW: ?3??) which contains 3 unknown values.

**Comment by korotaS** [comment]
@Iffa-Meah 
Okay, thanks. And the memory issues also may come from these dynamic shapes?

**Comment by Iffa-Meah** [comment]
@korotaS it could be. Try to use your model with the Benchmark App as I did above and see whether there's any memory leak.
However, bear in mind that this application collects every latency value and calculates the median value of latency and hence is not quite suitable for stress testing.

**Comment by korotaS** [comment]
Interesting, but if I make `core` and `raw_model` object attributes (add `self.` to them), the `RuntimeError: Cannot get dims for non static shape` error disappears when I uncomment line 2:

```python
class OpenVinoEngine():
    def __init__(self, model_fpath, num_workers):
        self.core = ov.Core()
        self.raw_model = self.core.read_model(model_fpath, "AUTO")
        self.model = self.core.compile_model(self.raw_model, "CPU", config={"INFERENCE_NUM_THREADS": str(num_workers)})
        # self.infer_request = self.model.create_infer_request()  # line 1

    def process(self, batch):
        self.infer_request = self.model.create_infer_request()  # line 2
        self.infer_request.infer([batch])
        output = [out.data[:] for out in self.infer_request.output_tensors]
        if len(output) > 1:
            return output
        return output[0]
```

**Comment by Iffa-Meah** [comment]
@korotaS hmm.. we'll further investigate this.

**Comment by korotaS** [comment]
@Iffa-Meah but the memory issue still stays the same.
I converted my model to IR (not the one I provided, but the other one, which is similar but has much bigger input/output shapes up to 2048) with shapes (1, 3, 1..2048, 1..2048), but there is still a leak. 
If i recompile my model every time in `process` method like this:
```python
self.raw_model.reshape(list(batch.shape))
self.model = self.core.compile_model(self.raw_model, "CPU", config={"INFERENCE_NUM_THREADS": "8"})
```
the memory is OK.

**Comment by korotaS** [comment]
@Iffa-Meah 
The shape of ONNX model is ?3?? because I export it like this, specifying dynamic axes:
```python
torch.onnx.export(
            model,
            x,
            path,
            export_params=True,
            opset_version=12,
            do_constant_folding=True,
            input_names=['input'],
            output_names=['output'],
            dynamic_axes={
                'input': {0: 'batch_size', 2: 'width', 3: 'height'},
                'output': {0: 'batch_size', 2: 'width', 3: 'height'}
            }
        )
```

**Comment by korotaS** [comment]
I tried to re-export the model without `dynamic_axes`, then convert it to IR with shape ranges, but nothing has changed in terms of memory...

**Comment by korotaS** [comment]
I've decided to make a separate issue for memory leak  (#11939), so in this one we can continue to discuss `RuntimeError: Cannot get dims for non static shape` error.

**Comment by jgespino** [comment]
@korotaS Since you have your code working after adding self to core = ov.Core(), are you okay closing this issue and investigating the memory leak in your other issue?

**Comment by korotaS** [comment]
@jgespino I am glad that my code is working and I'm okay with closing this issue, but is it an expected behavior? Or maybe I was using OV somehow wrong

**Comment by jane-intel** [comment]
@korotaS, `Core` object is essential to keep till the end of the program. You could save it in your `OpenVinoEngine` object like so

![image](https://user-images.githubusercontent.com/55839243/179497692-8f851cca-0ae1-49b1-8e71-a8f82d9f373d.png)

I would like to note that this is more of a workaround, OpenVINO engineering team is working on fixing it.
