### ISSUE TITLE
Cannot convert custom TF model to IR

### ISSUE THREAD

**Issue by onurbarut** [openvinotoolkit/openvino#11917]
##### System information (version)

- Environment => Intel AI Analytics Toolkit TensorFlow environment (intel optimized TF2.8 is uninstalled and TF2.5 is installed, the same error persists)
- OpenVINO => 2021.1.0 (dev)
- Operating System / Platform =>Ubuntu 20.04
- Problem classification: Model Conversion
- Framework: TensorFlow
- Model name: Custom

command: `$ mo --input_model frozen_model/simple_frozen_graph.pb --framework tf --input_shape [-1,50,2,1]`
Highlights of the error is given below:

> [ ERROR ]  -------------------------------------------------
> [ ERROR ]  ----------------- INTERNAL ERROR ----------------
> [ ERROR ]  Unexpected exception happened.
> [ ERROR ]  Please contact Model Optimizer developers and forward the following information:
> [ ERROR ]  Exception occurred during running replacer "fusing (<class 'openvino.tools.mo.middle.fusings.Fusing'>)": 'numpy.float32' object cannot be interpreted as an integer
> [ ERROR ]  Traceback (most recent call last):
> ...

detailed log file is attached:
[openvino-error.txt](https://github.com/openvinotoolkit/openvino/files/8927853/openvino-error.txt)

Model to be converted is attached:
[simple_frozen_graph.zip](https://github.com/openvinotoolkit/openvino/files/8927941/simple_frozen_graph.zip)

Installed packages:
[requirements.txt](https://github.com/openvinotoolkit/openvino/files/8927959/requirements.txt)

Thanks for your help!

**Comment by zulkifli-halim** [comment]
Sorry for the delayed response. I managed to convert your model to IR.  

```
[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: C:\Users\GitHub\11917\simple_frozen_graph.xml
[ SUCCESS ] BIN file: C:\Users\GitHub\11917\simple_frozen_graph.bin
[ SUCCESS ] Total execution time: 45.72 seconds.
```


Your model is actually a TensorFlow 1. To convert your model, you need to install TensorFlow 1.15.5. 

In Ubuntu 20, the default Python version is 3.8, where TF1.x is not supported here. Hence, you'll need to downgrade the Python version to 3.6 or 3.7.

For openvino-dev 2022.1.0, the support of the Model Optimizer tool in TensorFlow 1.x environment is deprecated. My suggestion for you is to install [openvino-dev 2021.4.2](https://pypi.org/project/openvino-dev/2021.4.2/) since this is the latest version that supports TensorFlow 1. 

Lastly, please use --input_shape with positive integers to override model input shapes. This is the MO command I used to convert the model:
`mo --input_model simple_frozen_graph.pb --framework tf --input_shape [1,50,2,1]`

**Comment by onurbarut** [comment]
Hi Zuklifli, I don't want to downgrade to older versions since my model was frozen with TFv1 although I trained it using TF2-keras API (I also have the trained keras model). Is there any other way I can convert my keras model (TF2) model to graph? I just tried to convert my keras saved model to tf.saved_model and used it as input_model to mo but it didn't like it. It said this model is not a graph:

> The file should contain one of the following TensorFlow graphs:
> 1. frozen graph in text or binary format
> 2. inference graph for freezing with checkpoint (--input_checkpoint) in text or binary format
> 3. meta graph

Do you know how I can convert my model to frozen graph (tf2 so that latest openvino version that I currently have will work)? My search on the web shows frozen graphs are deprecated in TF2...

**Comment by onurbarut** [comment]
Different problem, but under the same topic, so I continue from here:

I've managed to convert my keras model to frozen graph (also I noticed I can use tf.saved_model as input). After executing:
`$ mo --input_model frozen_models/my_frozen_graph.pb --framework tf --input_shape [1,50,2,1]
`or
`$ mo --saved_model_dir saved_models/my_saved_model --framework tf --input_shape [1,50,2,1]
`
I got the same exact error shown below:

> Model Optimizer arguments:
> Common parameters:
>         - Path to the Input Model:      None
>         - Path for generated IR:        /home/onur/test-tuned-R1DIT_8-class-AppID_RAW-2x50/.
>         - IR output name:       saved_model
>         - Log level:    ERROR
>         - Batch:        Not specified, inherited from the model
>         - Input layers:         Not specified, inherited from the model
>         - Output layers:        Not specified, inherited from the model
>         - Input shapes:         [1,50,2,1]
>         - Source layout:        Not specified
>         - Target layout:        Not specified
>         - Layout:       Not specified
>         - Mean values:  Not specified
>         - Scale values:         Not specified
>         - Scale factor:         Not specified
>         - Precision of IR:      FP32
>         - Enable fusing:        True
>         - User transformations:         Not specified
>         - Reverse input channels:       False
>         - Enable IR generation for fixed input shape:   False
>         - Use the transformations config file:  None
> Advanced parameters:
>         - Force the usage of legacy Frontend of Model Optimizer for model conversion into IR:   False
>         - Force the usage of new Frontend of Model Optimizer for model conversion into IR:      False
> TensorFlow specific parameters:
>         - Input model in text protobuf format:  False
>         - Path to model dump for TensorBoard:   None
>         - List of shared libraries with TensorFlow custom layers implementation:        None
>         - Update the configuration file with input/output node names:   None
>         - Use configuration file used to generate the model with Object Detection API:  None
>         - Use the config file:  None
> OpenVINO runtime found in:      /home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino
> OpenVINO runtime version:       2022.1.0-7019-cdb9bec7210-releases/2022/1
> Model Optimizer version:        2022.1.0-7019-cdb9bec7210-releases/2022/1
> [ ERROR ]  Check 'input_shape[1].compatible(filters_shape[1])' failed at core/shape_inference/include/convolution_shape_inference.hpp:265:
> While validating node 'v1::Convolution Convolution_4 (input_1[0]:f32{1,50,2,1}, StatefulPartitionedCall/model/feature_and_position_embedding2d/conv2d/Conv2D/ReadVariableOp[0]:f32{3,3,1,8}) -> ()' with friendly_name 'Convolution_4':
> Data batch channel count (50) does not match filter input channel count (3).
> 
> [ ERROR ]  offline transformations step has failed.

My model input shape is [B,D1,D2,1] where B is batch size, D1 is dimension1 (50), D2 is dimension2 (2), 1 is just additional axis.

Model summary of keras is as:

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 50, 2, 1)]        0         
_________________________________________________________________
feature_and_position_embeddi (None, 50, 2, 8)          80        
_________________________________________________________________
residual_transformer (Residu (None, 50, 2, 8)          4576      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 50, 2, 8)          0         
_________________________________________________________________
flatten (Flatten)            (None, 800)               0         
_________________________________________________________________
dense_16 (Dense)             (None, 8)                 6408      
=================================================================
Total params: 11,064
Trainable params: 11,064
Non-trainable params: 0



When I do not specify the batch size (i.e input_shape [?,50,2,1]) I got this error below:



`(openvino) onur@inspur-r6-4:~/test-tuned-R1DIT_8-class-AppID_RAW-2x50$ mo --saved_model_dir saved_model/r1dit_saved_model/ --framework tf --input_shape [?,50,2,1]
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      None
        - Path for generated IR:        /home/onur/test-tuned-R1DIT_8-class-AppID_RAW-2x50/.
        - IR output name:       saved_model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [?,50,2,1]
        - Source layout:        Not specified
        - Target layout:        Not specified
        - Layout:       Not specified
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - User transformations:         Not specified
        - Reverse input channels:       False
        - Enable IR generation for fixed input shape:   False
        - Use the transformations config file:  None
Advanced parameters:
        - Force the usage of legacy Frontend of Model Optimizer for model conversion into IR:   False
        - Force the usage of new Frontend of Model Optimizer for model conversion into IR:      False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
OpenVINO runtime found in:      /home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino
OpenVINO runtime version:       2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version:        2022.1.0-7019-cdb9bec7210-releases/2022/1
[ WARNING ]  The model contains input(s) with partially defined shapes: name="input_1" shape="[-1, 50, 2, 1]". Starting from the 2022.1 release the Model Optimizer can generate an IR with partially defined input shapes ("-1" dimension in the TensorFlow model or dimension with string value in the ONNX model). Some of the OpenVINO plugins require model input shapes to be static, so you should call "reshape" method in the Inference Engine and specify static input shapes. For optimal performance, it is still recommended to update input shapes with fixed ones using "--input" or "--input_shape" command-line parameters.
/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/front/common/partial_infer/utils.py:199: UserWarning: Warning: converting a masked element to nan.
  x = np.array(value, dtype=dtype)
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "fusing (<class 'openvino.tools.mo.middle.fusings.Fusing'>)": 'numpy.float32' object cannot be interpreted as an integer
[ ERROR ]  Traceback (most recent call last):
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/utils/class_registration.py", line 276, in apply_transform
    replacer.find_and_replace_pattern(graph)
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/middle/fusings.py", line 77, in find_and_replace_pattern
    for_graph_and_each_sub_graph_recursively(graph, fuse_linear_ops)
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/middle/pattern_match.py", line 46, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/middle/passes/fusing/fuse_linear_ops.py", line 167, in fuse_linear_ops
    is_fused = _fuse_mul(graph, node, fuse_nodes)
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/middle/passes/fusing/fuse_linear_ops.py", line 77, in _fuse_mul
    value = np.full(shape, value.item(), dtype=value.dtype)
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/numpy/core/numeric.py", line 314, in full
    a = empty(shape, dtype, order)
TypeError: 'numpy.float32' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/onur/intel/oneapi/intelpython/python3.9/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/home/onur/intel/oneapi/intelpython/python3.9/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/home/onur/intel/oneapi/intelpython/python3.9/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 407, in prepare_ir
    graph = unified_pipeline(argv)
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/pipeline/unified.py", line 13, in unified_pipeline
    class_registration.apply_replacements(graph, [
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/utils/class_registration.py", line 328, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/utils/class_registration.py", line 314, in apply_replacements_list
    apply_transform(
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/utils/logger.py", line 112, in wrapper
    function(*args, **kwargs)
  File "/home/onur/intel/oneapi/intelpython/latest/envs/openvino/lib/python3.9/site-packages/openvino/tools/mo/utils/class_registration.py", line 302, in apply_transform
    raise Exception('Exception occurred during running replacer "{} ({})": {}'.format(
Exception: Exception occurred during running replacer "fusing (<class 'openvino.tools.mo.middle.fusings.Fusing'>)": 'numpy.float32' object cannot be interpreted as an integer

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------`



I could use some help why these errors occurs and how to solve. Thanks!

**Comment by zulkifli-halim** [comment]
@onurbarut. The latest test error is similar to the error you get when converting the model to IR using TF2.5.  Another way is to use pip install openvino-dev[tensorflow]==2022.1.0 to install openvino-dev with TF1.x. However, the model fails to convert and the MO states that TF 1.x is deprecated and it is highly recommended for you to use TensorFlow 2.x.

Here are two options you can you: 

- Use OpenVINO 2021.4.2 with TF1.x
- Use a TF 2.x model with OpenVINO 2022.1.0 with TF2.x

**Comment by onurbarut** [comment]
hi @zulkifli-halim , the latest error I received when I was trying to convert my tf.saved_model (converted using tf 2.5). So, that actually means I was following the second option you provided. I'm attaching the keras saved model (trained using tf 2.x), and the tf.saved_model (loaded keras model and saved as tf.saved_model using tf 2.5). Please let me know how you can convert this model using openvino 2022.1.1

[keras_model.zip](https://github.com/openvinotoolkit/openvino/files/8992476/keras_model.zip)
[saved_model.zip](https://github.com/openvinotoolkit/openvino/files/8992480/saved_model.zip)

Thanks for your help! 
Onur

**Comment by zulkifli-halim** [comment]
@onurbarut, thank you for sharing. I'm checking this out and will update you soon.

**Comment by zulkifli-halim** [comment]
@onurbarut. Can you tell me which model topology or repository (link to repo) you are using? What type of model is it (classification, object detection, etc.)?

**Comment by onurbarut** [comment]
@zulkifli-halim , it is our custom design model for network traffic classification. The source code is not yet open to public.

**Comment by zulkifli-halim** [comment]
@onurbaru, I tried to use your convert.py to convert the model to saved_model, but failed with this error:
```
Traceback (most recent call last):
  File "convert.py", line 22, in <module>
    model = load_model(model_fname)
  File "C:\Users\GitHub\openvino_env\lib\site-packages\tensorflow\python\keras\saving\save.py", line 202, in load_model
    compile)
  File "C:\Users\GitHub\openvino_env\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 176, in load_model_from_hdf5
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.
```

How do you convert Keras to saved_model format? 

When you save your model to Keras format, is there a chance you save the weights instead of the model?

**Comment by onurbarut** [comment]
Hi, @zulkifli-halim, yes, I just confirmed that I saved the weights of Keras model. But that shouldn't be a problem because I can load weights back to keras model and save it using tf.save_model or freeze keras model  using convert_variables_to_constants_v2 and tf.io.write_grapgh methods. Am I correct?

Thanks,
Onur

**Comment by zulkifli-halim** [comment]
@onurbarut. We'll investigate further to provide some more alternatives for you and we'll get back asap.

**Comment by onurbarut** [comment]
Hi @zulkifli-halim , I found that the saved_model input shape doesn't match the mo command shape, fixing it solved this issue. Thanks for all the effort so far!
