### ISSUE TITLE
how to use multiclass_nms

### ISSUE THREAD

**Issue by WZMIAOMIAO** [openvinotoolkit/openvino#11921]
hi, I want to use `nms` for my predicted `objs` like this:
https://github.com/ultralytics/yolov5/blob/1156a323f8fc221d5c1a36c700e72e129419d187/utils/general.py#L776-L783

I find that there is a api(`multiclass_nms`), but the official documents are not clear. Could you explain in detail how to use it?
![image](https://user-images.githubusercontent.com/31005897/174517380-c79e0891-70ef-4377-85e5-bccf37c9b82e.png)

**Comment by zulkifli-halim** [comment]
Hi @WZMIAOMIAO. MulticlassNonMaxSuppression (multiclass_nms) performs multi-class non-maximum suppression of the boxes with predicted scores.

You can find details about the multiclass_nms operator in this document:
https://docs.openvino.ai/2022.1/openvino_docs_ops_sort_MulticlassNonMaxSuppression_8.html

**Comment by WZMIAOMIAO** [comment]
@zulkifli-halim @liubo-intel thank you for your reply, I got it. Is there an efficient method similar to [torchvision.ops.batched_nms](https://pytorch.org/vision/stable/generated/torchvision.ops.batched_nms.html?highlight=batched#torchvision.ops.batched_nms)?

**Comment by liubo-intel** [comment]
> @zulkifli-halim @liubo-intel thank you for your reply, I got it. Is there an efficient method similar to [torchvision.ops.batched_nms](https://pytorch.org/vision/stable/generated/torchvision.ops.batched_nms.html?highlight=batched#torchvision.ops.batched_nms)?

Hi, @WZMIAOMIAO From 'torchvision.ops.batched_nms' link you send, it looks like this Op is very similar to OpenVINO 'NonMaxSuppression' Op. 

To convert 'torchvision.ops.batched_nms' to OpenVINO 'NonMaxSuppression', I think the main thing is to reshape/reorder input 'boxes' from [N, 4] to  [num_batches, num_boxes, 4], reshape/reorder input 'scores' from [N] to [num_batches, num_classes, num_boxes]. these reorder/reshape will match the score index of each category NMS in OpenVINO 'NonMaxSuppression' internal process(const float* scoresPtr = scores_data + batch * (num_classes * num_boxes) + class_idx * num_boxes;), therefore 'idxs' is no more needed for OpenVINO 'NonMaxSuppression'.  if these inputs match OpenVINO 'NonMaxSuppression' format, then you can load this op, and get the outputs. if the outputs format is not what you want, then you may use some slice/gather/reorder ops to get the final outputs that you need.

Some additional tips that you may need to pay attention to:(1) it looks like boxes format in 'torchvision.ops.batched_nms' is (x1, y1, x2, y2), but in openvino is [y1, x1, y2, x2].
(2)please set "max_output_boxes_per_class" for OpenVINO 'NonMaxSuppression', although it's an 'optional parameters', but if you don't set it, its default value '0' will make 'NonMaxSuppression' generate no outputs.

**Comment by zulkifli-halim** [comment]
Closing, please re-open if additional assistance is needed.
