### ISSUE TITLE
Error : Unable to convert custom model from .onnx to IR format contains 2 outputs

### ISSUE THREAD

**Issue by Guemann-ui** [openvinotoolkit/openvino#11936]
##### System information (version)
<!-- Example
- OpenVINO => 2020.4
- Operating System / Platform => Ubuntu 18.04
- Problem classification: Model Conversion
- Framework: Pytorch

Hi, I'm trying to convert my custom model from onnx to IR OpenVINO which contains 2 outputs.

I always get the same error as the OpenVINO support only 1 output. 

Does Any solution please?

**Comment by jgespino** [comment]
@Guemann-ui Do you still need assistance? If you do, please fill out the issue template and re-open the ticket.
