### ISSUE TITLE
[Bug] can't install openvino==2022.1.0

### ISSUE THREAD

**Issue by rnwang04** [openvinotoolkit/openvino#11947]
##### System information (version)
- OpenVINO=> 2021.4.2
- Operating System / Platform => CentOS Linux release 7.5.1804 
- Problem classification => Version

##### Detailed description
Hi, I want to use OpenVINO to run other programs, but it requires OpenVINO==2022.1.0. However, I can only install OpenVINO==2021.4.2.
Is there any mistake in my installation ? And how can I install OpenVINO==2022.1.0?

##### Steps to reproduce
```
conda create -n myenv python=3.7
conda create myenv
pip install openvino-dev
```
I also tried `pip install openvino-dev==2022.1.0
`
and get error message `ERROR: Could not find a version that satisfies the requirement openvino==2022.1.0 (from openvino-dev) (from versions: 2021.2, 2021.3.0, 2021.4.0, 2021.4.1, 2021.4.2)`
Btw, I have upgraded my pip.

**Comment by mlukasze** [comment]
Hi @rnwang04 
please try to use syntax that has been shown in documentation, like:
`pip install openvino-dev[tensorflow2,onnx]==2022.1.0`
Follow documentation for more examples:
https://docs.openvino.ai/nightly/openvino_docs_install_guides_install_dev_tools.html

Please let me know about result of test :)

**Comment by brmarkus** [comment]
Unfortunately "CentOS" is not supported anymore... It has been announced with previous versions of OpenVINO - and got discontinued in the meantime.
See: https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes-2021.html
With the latest version v2022.1 also CentOS Docker containers and Dockerfiles have been discontinued, see "https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes.html".

**Comment by lolong** [comment]
hi, I am using ubuntu 20.04 and I go the same error message:

```
ERROR: Could not find a version that satisfies the requirement openvino==2022.1.0 (from openvino-dev[onnx,tensorflow2]==2022.1.0) (from versions: 2021.3.0, 2021.4.0, 2021.4.1, 2021.4.2)
ERROR: No matching distribution found for openvino==2022.1.0 (from openvino-dev[onnx,tensorflow2]==2022.1.0)
```
