### ISSUE TITLE
Unable to build model on vasurface when following the sample 'Direct Consuming of the NV12 VAAPI Video Decoder Surface on Linux '

### ISSUE THREAD

**Issue by Kizna1ver** [openvinotoolkit/openvino#11959]
Hello,

I am following the sample  

[Direct Consuming of the NV12 VAAPI Video Decoder Surface on Linux](https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_GPU_RemoteTensor_API.html#direct-nv12-video-surface-input)  

and try to build a model on the VASurface used in ffmpeg hardware decoder. But I encounterd some error below when calling the function compile_model().

My system infomation:

 - OpenVINO=> 2022.1(included in docker image openvino/ubuntu20_dev:2022.1.0)
 - Operating System / Platform => ubuntu20.04

Part of my codes:

    size_t input_height = 300;
    size_t input_width = 300;

    // initialize the core and load the network
    ov::Core core;
    auto model = core.read_model("/opt/intel/openvino_2022.1.0.643/samples/cpp/hello_remote_blob/public/ssd300/FP32/ssd300.xml");

    printf("Preprocessing...\n");  
    auto p = PrePostProcessor(model);
    p.input().tensor().set_element_type(ov::element::u8)
                    .set_color_format(ov::preprocess::ColorFormat::NV12_TWO_PLANES, {"y", "uv"})
                    .set_memory_type(ov::intel_gpu::memory_type::surface); 
            
    p.input().preprocess()
                    .convert_color(ov::preprocess::ColorFormat::BGR);
    p.input().model().set_layout("NCHW");
    model = p.build();
    printf("Build finished\n");  

    // create the shared context object
    auto shared_va_context = ov::intel_gpu::ocl::VAContext(core, display);
    // compile model within a shared context
    auto compiled_model = core.compile_model(model, shared_va_context);

    printf("Compile model finished\n");  
The error:

    terminate called after throwing an instance of 'ov::Exception'
    what(): Error has occured for: add:data/mean
    Sizes equal or broadcast is possible(true) should be false
    Invalid input shapes

The XML file seems to correct, I don't know why this error is raised. My complete code in [this repository](https://github.com/Kizna1ver/OpenVINO-RemoteBlob-Sample).ssd300.xml file can be found in the repository or obtained by omz_downloader, and you can follow the readme file to reproduce this issue.

I also made a [post](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Sizes-equal-or-broadcast-is-possible-true-should-be-false/m-p/1391674/thread-id/27495) on Intel Community, but still havn't found the answer yet

Thanks!

**Comment by Iffa-Meah** [comment]
@Kizna1ver could you share the complete files of your model? I could only find the .xml in your repo.
It's insufficient from my side to check your model with only .xml file.

![image](https://user-images.githubusercontent.com/79643476/175499256-baf62ec7-cdef-4254-96a1-7be7722ecce4.png)

**Comment by Kizna1ver** [comment]
Thansk for reply. I update the repo and upload complete file of my model.

**Comment by Iffa-Meah** [comment]
@Kizna1ver , I validated your model using OpenVINO Benchmark App to ensure the model actually works or not.

This might be the source of your issue.
Your bin file has incorrect weight values.

![image](https://user-images.githubusercontent.com/79643476/175877297-5087b357-348c-41ed-81b5-9615aa560c27.png)

**Comment by Kizna1ver** [comment]
@Iffa-Meah ，thanks for reply. The ssd300.bin file is larger then 100MB, I uploaded it by git lfs. You can directly download the raw file on [github repo](https://github.com/Kizna1ver/OpenVINO-RemoteBlob-Sample/raw/main/public/ssd300/FP32/ssd300.bin) or you can also obtain ssd300.bin file by omz_downloader and omz_converter.
Benchmark App works correctly in my machine
![image](https://user-images.githubusercontent.com/60084536/175898300-037be4e0-cf5c-49ad-91cb-5835ab59884a.png)

**Comment by Iffa-Meah** [comment]
@Kizna1ver Did you do any further changes to your files before compiling your custom code which you didn't mention in your repo?
I managed to compile my other binaries but not yours.


<img width="414" alt="nv12" src="https://user-images.githubusercontent.com/79643476/176201890-2f36dba7-eec5-4925-8c6d-ac729d433431.png">


could you share what you did with details? (such as modification to certain config, commands, things that need to be installed separately, etc)

**Comment by Kizna1ver** [comment]
@Iffa-Meah thans for reply, it seems that your CMakeLists file still contain thirdparty directory, I remove it in recent commit a few days ago. 
Initially, I build this project in this docker container [(openvino/ubuntu20_dev:2022.1.0),](https://hub.docker.com/r/openvino/ubuntu20_dev) where openvino is installed in /opt/intel/openvino, and this sample I created directly in /opt/intel/openvino/samples/cpp/ in hello_remote_blob. 
This is the original directory.
![image](https://user-images.githubusercontent.com/60084536/176219419-390f46bd-5c16-47db-aa26-c809ac20aec2.png)

In order to easily reproduce the problems I encountered, I created this repo separately, and made some changes in [CMakeList.txt ](https://github.com/Kizna1ver/OpenVINO-RemoteBlob-Sample/commits/main/CMakeLists.txt)(removed some unnecessary dependencies, such as thirdpary.), it can be compiled normally under the correct environment in docker container which is listed in readme.md.
Maybe using docker can easily reproduce my problem. Note that in the docker container you also need to build ffmpeg with vaapi support.

**Comment by Iffa-Meah** [comment]
@Kizna1ver  which version of ffmpeg with vaapi did you use? 
[This one](https://gist.github.com/Brainiarc7/eb45d2e22afec7534f4a117d15fe6d89) compatible with yours?
Would be great if you could share which library you are using.

**Comment by Kizna1ver** [comment]
@Iffa-Meah you can take a look at readme.md in my repo,a [link](https://github.com/intel/media-driver/releases/tag/intel-media-21.3.5) of Intel-media-driver dependency is listed there,which contain version infomation of libva and intel gmmlib. You can build and install such dependencis from source by following instruction in their readme file.
The image below is the output of the ldd command on my machine:
![image](https://user-images.githubusercontent.com/60084536/176341334-1f024117-133f-4359-a744-086594af1671.png)

**Comment by Iffa-Meah** [comment]
@Kizna1ver , I have my media workspace ready 

<img width="426" alt="1_" src="https://user-images.githubusercontent.com/79643476/176410383-05eedaab-3f72-4a89-aa84-1e3414dd9439.png">


but I need to build & install another 2 libraries (LibVA and GmmLib) beforehand as instructed in ReadMe you shared.

I had built & installed the GmmLib

<img width="366" alt="2_" src="https://user-images.githubusercontent.com/79643476/176410494-42c86282-a5c1-4997-aa9b-720cf438bd1e.png">

However, for LibVA, how did you build & install? the readme doesn't have a complete/details on that.
Did you simply cmake or run the script inside build folder?

<img width="354" alt="3" src="https://user-images.githubusercontent.com/79643476/176410740-59000d78-c81f-4ede-a168-b5c8c30af7e9.png">

<img width="454" alt="4_" src="https://user-images.githubusercontent.com/79643476/176410796-37497b8c-e874-459a-bba3-dc09f2a6778e.png">

**Comment by Kizna1ver** [comment]
@Iffa-Meah ,[this](https://01.org/linuxmedia/quickstart/linux-vaapi-videostack-environment) will be helpful. It seems that the version of GmmLib you installed is 12.1.0. Using compatible version mentioned in here would be better,as the GmmLib 12.x version have some abi changes compared to Gmmlib 11.x.
![image](https://user-images.githubusercontent.com/60084536/176413999-531ab857-e43b-4d73-bf24-7cd14d88c4b9.png)
Directly download the source in the [link](https://github.com/intel/media-driver/releases/tag/intel-media-21.3.5) of above image and then build & install will be better.
Maybe we can directly look at openvino source code. I found that in [eltwise.cpp line 256](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/src/graph/eltwise.cpp#L256) raise the error I encountered.But in the xml file,the two tensors could have been added normally and this logical judgment '!(sizes_equal || broadcast)' in line259 always be false.So the error shouldn't been raised.Is my understanding correct?

**Comment by Iffa-Meah** [comment]
@Kizna1ver did you try to test that particular line? probably try to return the value that the operators have calculated and make an indicator, maybe return the binary 1 for true and 0 for false.

Let the program run specific at that point and see whether it proves your theory.

**Comment by Kizna1ver** [comment]
@Iffa-Meah ,the error was resolved when I used the recent version of openvino([30bd4a905e](https://github.com/openvinotoolkit/openvino/tree/30bd4a905e20bd88570ef7faa4ccbcd54a35517d)) in the master branch. The following code also works fine.
But I don't know exactly what caused the error. I will try to debug in the next few days. It would be great if you can also help me find what cause the error. Thanks

**Comment by Iffa-Meah** [comment]
@Kizna1ver probably there are some complications with the previous version which fixed in the latest branch.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
