### ISSUE TITLE
Running the accuracy aware quantization sample python script on other object detection models

### ISSUE THREAD

**Issue by hitesh-anand** [openvinotoolkit/openvino#11953]
Hi,
I found a sample python script for running the accuracy aware quantization on the "ssd-mobilenetv1" model at the following link : [https://github.com/openvinotoolkit/openvino/tree/master/tools/pot/openvino/tools/pot/api/samples/object_detection](https://github.com/openvinotoolkit/openvino/tree/master/tools/pot/openvino/tools/pot/api/samples/object_detection)

Now I want to run the script for other object detection models such as yolov5. I tried to change the name and input shape in the preprocessing part of the "dataloader.py" : [https://github.com/openvinotoolkit/openvino/blob/master/tools/pot/openvino/tools/pot/api/samples/object_detection/data_loader.py](https://github.com/openvinotoolkit/openvino/blob/master/tools/pot/openvino/tools/pot/api/samples/object_detection/data_loader.py)

But, still I am getting the following error : Cannot reshape array of size 1228800 into shape (1,3,384,640). Here, the value 1228800 equals the product of input dimensions of ssd-mobilenet-v1 and the latter are the input dimensions for my model. 

Can someone please guide me on how to change the script for other models? I could not find any other change that could be made to run it on my model.

Regards,
Hitesh

**Comment by zulkifli-halim** [comment]
Hi @hitesh-anand. I'm checking this out. In the meantime, please share the model, and dataset with annotations with us. 

Here is another tutorial for [Object Detection Quantization](https://docs.openvino.ai/2022.1/notebooks/111-detection-quantization-with-output.html) that you might be interested in. This tutorial shows how to quantize an object detection model, using OpenVINO’s [Post-Training Optimization Tool API](https://docs.openvino.ai/2021.4/pot_compression_api_README.html).

**Comment by hitesh-anand** [comment]
Thanks for the reply!
I will have a look at the link you shared and let you know if it works.

The model I am using is yolov5s. And I am using the standard Coco 2017 validation dataset and the corresponding annotations. 

Actually, there is an update regarding my previous doubt. The reshaping error is resolved. I am getting a new error and it is generated at the line 174 of [metric.py](https://github.com/openvinotoolkit/openvino/blob/master/tools/pot/openvino/tools/pot/api/samples/object_detection/metric.py). 
It goes as following : ValueError: could not broadcast input array from shape (15120,85) into shape (1,)
Segmentation fault

The figure (15120, 85) is coming from the shape of the final output layer. (The exact shape is (1, 15120, 85)). But, I don't know why is this error showing up.

It will be very helpful if you could help in figuring out a solution for this.

Regards,
Hitesh

**Comment by zulkifli-halim** [comment]
Hi @hitesh-anand. Can you share your original YOLOv5 model and dataset with us for replication purposes?

**Comment by zulkifli-halim** [comment]
@hitesh-anand. I'm able to optimize the yolov5s model using [The Post-Training Optimization Tool (POT) Python* API](https://docs.openvino.ai/2021.4/pot_compression_api_README.html). Here is the script I that I used.

```
import os
import numpy as np
import os.path as osp
from openvino.tools.pot import DataLoader

model_name = "yolov5s"

class DummyDatasetLoader(DataLoader):

    def __init__(self, config):
        super().__init__(config)

    def __getitem__(self, index):

        if index >= len(self):
            raise IndexError

        return np.random.randn(256, 1056, 160, 3), None

    def __len__(self):
        """ Returns size of the dataset """
        return 10
from openvino.tools.pot import IEEngine
from openvino.tools.pot import load_model, save_model
from openvino.tools.pot import compress_model_weights
from openvino.tools.pot import create_pipeline

model_config = {
    "model_name": "yolov5s",
    "model": "yolov5s.xml",      #f"{model_name}/{model_name}.xml",
    "weights": "yolov5s.bin"    #f"{model_name}/{model_name}.bin",
}
engine_config = {"device": "CPU"}
'''
algorithms = [
    {
        "name": "DefaultQuantization",
        "params": {
            "target_device": "CPU",
            "stat_subset_size": 500
        },
    }
]
'''
algorithms = [
    {
        "name": "DefaultQuantization",
        "params": {
            "target_device": "CPU",
			"preset": "mixed",
            "stat_subset_size": 500
        },
    }
]
data_loader = DummyDatasetLoader({})

# Step 2: Load model
model = load_model(model_config=model_config)

# Step 3: Initialize the engine for metric calculation and statistics collection.
engine = IEEngine(config=engine_config, data_loader=data_loader)

# Step 4: Create a pipeline of compression algorithms and run it.
pipeline = create_pipeline(algorithms, engine)
compressed_model = pipeline.run(model=model)

# Step 5 (Optional): Compress model weights to quantized precision
#                     to reduce the size of the final .bin file.
compress_model_weights(compressed_model)

# Step 6: Save the compressed model to the desired path.
# Set save_path to the directory where the model should be saved
compressed_model_paths = save_model(
    model=compressed_model,
    save_path="optimized_model",
)
```

**Comment by hitesh-anand** [comment]
@zulkifli-halim 
I was trying to optimize it using Accuracy Aware Quantization. 
I have successfully executed the Default Quantization earlier.

It will be helpful if you could mention the steps for Accuracy Aware Quantization by making some changes in the same script or by any other means.

Thanks,
Hitesh

**Comment by zulkifli-halim** [comment]
The error is related to the incompatibility between the POT Accuracy Awareness object detection demo (as pot/api/samples/object_detection/obejct_detection_sample.py is using mobilenetv1) and yolov5s model.

The [ssd_mobilenet_v1_fpn](https://docs.openvino.ai/latest/omz_models_model_ssd_mobilenet_v1_fpn_coco.html#output) model has single output name `DetectionOutput` and shape: `1, 1, 100, 7`, whereas yolov5s model has 3 outputs with shapes `[1, 255, 80, 80]`, `[1, 255, 40, 40]` and `[1, 255, 20, 20]`.

Some changes in the sample are required to fit the yolov5 model (data_loader.py, metric.py, and obejct_detection_sample.py). We are still investigating the possibility of using this [quantization sample](https://github.com/openvinotoolkit/openvino/tree/master/tools/pot/openvino/tools/pot/api/samples/object_detection) with the yolov5s model.

**Comment by zulkifli-halim** [comment]
@hitesh-anand. We don't have any example that is related to the yolov5s model, because this model is not a part of the Intel Open Model Zoo. 

It requires major changes if you want to quantize an object detection model in accuracy-aware mode using yolov5s. We suggest you explore the network architecture of the yolov5s model and object detection algorithm to implement in this sample.

**Comment by zulkifli-halim** [comment]
Closing, please open a new issue if you have any other questions.
