### ISSUE TITLE
[Bug] build_samples_msvc.bat Error: could not load cache

### ISSUE THREAD

**Issue by biyuehuang** [openvinotoolkit/openvino#11954]
cd C:\Program Files (x86)\Intel\openvino_2022.1.0.643
setupvars.bat
cd C:\Program Files (x86)\Intel\openvino_2022.1.0.643\samples\cpp\
build_samples_msvc.bat

Error creating directory "C:\Users\username\Documents\Intel\OpenVINO\inference_engine_cpp_samples_build".

###############|| Build Inference Engine samples using MS Visual Studio (MSBuild.exe) ||###############

cmake --build . --config Release
Error: could not load cache
Error

# System information (version)
- OpenVINO => 2022.1
- Operating System / Platform => Windows10 64 Bit
- Compiler => Visual Studio 2019
- Cmake: 3.19
- Problem classification: sample/cpp
- TGL-U corei7

**Comment by peterchen-intel** [comment]
@biyuehuang It should be the permission issue. Try build_samples_msvc.bat -b C:\Users\username\OV_Samples"

**Comment by biyuehuang** [comment]
> @biyuehuang It should be the permission issue. Try build_samples_msvc.bat -b "C:\Users\username\OV_Samples"

Yes, you're right. I can built it.
