### ISSUE TITLE
Using Cubemos Skeleton Tracking SDK & OpenVINO

### ISSUE THREAD

**Issue by mhudnell** [openvinotoolkit/openvino#1196]
I want to use both [Cubemos' Skeleton Tracking SDK](https://www.intelrealsense.com/skeleton-tracking/) and Intel OpenVino to run a different model simultaneously.
There appears to be conflicts when attempting to import both and then initialize.

Running:
```python
from cubemos_helpers import check_license_and_variables_exist, default_license_dir
from cubemos.skeleton_tracking.nativewrapper import Api, SkeletonKeypoints
from openvino.inference_engine import IECore  # adding this causes error

api = Api(default_license_dir())
```

Results in the error:
```
Traceback (most recent call last):
  File "skele_tracking.py", line 144, in <module>
    api = Api(default_license_dir())
  File "D:\mhudnell\repos\python-d415-skeletontracking\venv\lib\site-packages\cubemos\skeleton_tracking\nativewrapper.py", line 172, in __init__
    handle_return_code(retval)
  File "D:\mhudnell\repos\python-d415-skeletontracking\venv\lib\site-packages\cubemos\skeleton_tracking\nativewrapper.py", line 115, in handle_return_code
    raise CubemosException("Non-Success Return Code", return_code)
cubemos.skeleton_tracking.nativewrapper.CubemosException: Non-Success Return Code
Exception ignored in: <function Api.__del__ at 0x0000015D7FF1EB88>
Traceback (most recent call last):
  File "D:\mhudnell\repos\python-d415-skeletontracking\venv\lib\site-packages\cubemos\skeleton_tracking\nativewrapper.py", line 261, in __del__
    del self.managed_handle
AttributeError: managed_handle
```
Along with:
![Image of Yaktocat](https://i.imgur.com/r5JYnXj.png)

Has anyone used OpenVINO with Cubemos? I've contacted support@cubemos.com, but figured I'd post here until I find a solution.

**Comment by avitial** [comment]
@mhudnell not sure what the issue could be here, looks like the problem is coming from such SDK and not from the OpenVINO package. I would suggest to wait for a response from the Cubemos support. 

From the OpenVINO side make sure the environment details are set, and also make sure you have verified your installation (ran a sample app). Based on the log above the issue does not seem to be from adding line `from openvino.inference_engine import IECore`, but from `nativewrapper.py` when OpenVINO env vars are set. I can suggest trying multiple CMD windows if you would like to use both environments (a CMD for OpenVINO and a separate CMD for Cubemos), hope that meets your needs.

~Luis

**Comment by mhudnell** [comment]
@avitial thanks for the quick reply.

I confirmed the OpenVINO environment is set and sample apps are working. I agree it does seem like an issue that would be caused by the environment variables. However I also confirmed that setting the OpenVINO env variables, then running a cubemos python app works no problem. But then adding the line: `from openvino.inference_engine import IECore` causes the error above involving `cubemos_intel_inference_engine_plugin.dll`. This behavior seems very strange to me.

Using multiple CMD windows could potentially work, but I want to share data between the apps so it may get confusing.
I tried moving the OpenVINO code to a subprocess, which gets called, and interestingly I get a missing DLL error on OpenVINO's end that way. 
Example:

process1.py:
```
from cubemos.skeleton_tracking.nativewrapper import Api, SkeletonKeypoints
from cubemos_helpers import check_license_and_variables_exist, default_license_dir
import subprocess

if __name__ == '__main__':
    api = Api(default_license_dir())

    subprocess.call(['python', 'process2.py'])
```

process2.py:
```
from openvino.inference_engine import IECore

if __name__ == '__main__':
    print("hello")
```

Running `python process1.py` results in:
```
Traceback (most recent call last):
  File "process2.py", line 1, in <module>
    from openvino.inference_engine import IECore
  File "C:\Program Files (x86)\IntelSWTools\openvino\python\python3.7\openvino\inference_engine\__init__.py", line 1, in <module>
    from .ie_api import *
ImportError: DLL load failed: The specified procedure could not be found.
```

Running `python process2.py` runs successfully

Any input is appreciated, I'll continue to search for an explanation of this weird behavior / hope that Cubemos gets back to me.

**Comment by mhudnell** [comment]
Cubemos support replied, unsure why the error was happening, but noted I was using an unsupported processor (Intel Xeon CPU).

Over the past few days however, we've switched from Windows to Linux (Ubuntu 18.04 on a machine with an Intel Core™ i7-8559U Processor), and fortunately we no longer get the error. Not sure if Windows or the Xeon processor was the issue, but either way it works now.
