### ISSUE TITLE
Issue loading keras model / VINO optimization rate

### ISSUE THREAD

**Issue by mrinmayk** [openvinotoolkit/openvino#120]
Hello;

While loading a specific model using keras.load(./<path>/name.model); I am having issue as the model had specific annotation as -

from keras.utils.generic_utils import CustomObjectScope
with CustomObjectScope({'relu6': keras.layers.ReLU(6.)
                                                        'DepthwiseConv2D': keras.layers.DepthwiseConv2D}):
                          self.ageNet = keras.models.load_model(os.path.join(agepath, 'model.h5'))

While the above works on the regular running of the original program which has just 4 dependencies -  dlib, tensorflow-1.8, keras-2.2.2 and opencv;
the above code did not work on trying to convert the model to tensorflow for which I had to load the model first (as above) **_and gave that the "relu6" as unidentified_**.

Also,

Can VINO optimize a network by up-to 50%? Typically is there a way to see the optimized network graphically or is the new model just in the generated .xml/.bin files?

Best Regards

**Comment by shubha-ramani** [comment]
Dearest @mrinmayk:

You cannot load a Keras model into Model Optimizer straightaway. That Keras model must be converted to a frozen Tensorflow protobuf first.  I provided a code snippet in [this IDZ forum thread](https://software.intel.com/en-us/forums/computer-vision/topic/805857) on how to exactly do that.

Hope it helps !

And thanks for using OpenVino !

Shubha
