### ISSUE TITLE
Is there any way to do Winograd algorithmic tuning with CLI?

### ISSUE THREAD

**Issue by wangg** [openvinotoolkit/openvino#12011]
I have used the Winograd algorithmic tuning (https://docs.openvino.ai/2021.4/workbench_docs_Workbench_DG_Winograd_Algorithmic_Tuning.html) in my project, and it does help some of my models. I am not sure this is the right place to ask questions, but I have 2 questions about the Winograd tuning.

1. Is there any way to do such tuning without DL workbench? I would like to include such tuning in a script, so CLI is preferred and the web interface is no longer suitable in this case.
2. It seems that Winograd tuning has been removed in DL workbench 2022.1? May I know why?

**Comment by Iffa-Meah** [comment]
@wangg did you use the Winograd tuning for optimization purposes or are there any other reasons?

**Comment by wangg** [comment]
@Iffa-Meah I use it for optimization purposes. It gives quite a boost to some of my models without hurting the accuracy at all.

**Comment by Iffa-Meah** [comment]
@wangg in that case, Post Training Optimization Tool (POT) won't be suitable for you. We'll get back to you with applicable workaround/suggestions asap.

**Comment by hbalasu1** [comment]
Hi @wangg to answer your questions 
1. Is there any way to do such tuning without DL workbench? I would like to include such tuning in a script, so CLI is preferred and the web interface is no longer suitable in this case.
**[Answer]** As for now Winograd tuning required the DL workbench platform to perform optimization, for Winograd tuning outside of the DL workbench has yet to be implemented.  

2. It seems that Winograd tuning has been removed in DL workbench 2022.1? May I know why?
**[Answer]** Regarding Winograd tuning on DL workbench 2022.1, yet to be implement for OpenVINO 2022.1.

**Comment by wangg** [comment]
@hbalasu1 Thank you for the answers.
