### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Aed-p** [openvinotoolkit/openvino#12026]
##### System information (version)
- OpenVINO => openvino_2022.1.0.643
- Operating System / Platform => Ubuntu20.04/intel e2583
- Compiler => gcc version 9.4.0
- Problem classification: Model Load takes long time in cpu
- Framework: TensorFlow, use tf2onnx 1.9.3 convert model.pb to model.onnx

##### Detailed description
When I use openvino to load the converted onnx model on the cpu, it takes about 3 minutes, but it only takes a few seconds to load using onnxruntime, the following are the output log of openvino and the output log of onnxruntime:
openvino: 
I20220701 02:23:52.059870  4203 extract_model.cpp:29]  model_ir init :/root/worksppace/test/lib/model.onnx
I20220701 02:24:37.234880  4203 extract_model.cpp:41]  read model takes :45.1724s 
I20220701 02:24:37.235159  4203 extract_model.cpp:77]  pre model input takes :8.2636e-05s 
I20220701 02:24:37.235184  4203 extract_model.cpp:82]  pre output, name and type: output_1:0 i64
I20220701 02:24:37.235209  4203 extract_model.cpp:82]  pre output, name and type: output_2:0 i64
I20220701 02:24:37.235235  4203 extract_model.cpp:82]  pre output, name and type: output_3:0 f32
I20220701 02:24:37.235255  4203 extract_model.cpp:82]  pre output, name and type: output_4:0 f32
I20220701 02:25:31.311035  4203 extract_model.cpp:93]  build model takes :54.0757s 
I20220701 02:26:33.595211  4203 extract_model.cpp:109]  compile_model takes :62.284s 
I20220701 02:26:33.597138  4203 extract_model.cpp:120]  infer_request takes :0.00172487s 
I20220701 02:26:33.597204  4203 extract_model.cpp:126] load and pre model spend Takes 161.537s 

c++ init_model code:
```.cpp
#ifdef GLOG_INIT
  LOG(INFO) << " model_ir init :" << ir_model_path << std::endl;
#endif
  auto beg_t = system_clock::now();

  ov::Core ie;
  auto beg = system_clock::now();
  std::shared_ptr<ov::Model> model = ie.read_model(ir_model_path);
  auto end = system_clock::now();
  duration<double> diff = end - beg;

#ifdef GLOG_INIT
  LOG(INFO) << " read model takes :" << diff.count() << "s " << std::endl;
#endif

  size_t data_size = input_shape[ov::layout::height_idx(model_layout)] *
                     input_shape[ov::layout::width_idx(model_layout)];

#ifdef GLOG_INIT
  LOG(INFO) << " input_data size :" << data_size << std::endl;
#endif

  input_data = new uchar[data_size * 4];

  beg = system_clock::now();
  ov::preprocess::PrePostProcessor ppp(model);
  ppp.input()
      .tensor()
      .set_element_type(input_type)
      .set_layout(model_layout)
      .set_spatial_static_shape(
          input_shape[ov::layout::height_idx(model_layout)],
          input_shape[ov::layout::width_idx(model_layout)]);
  ppp.input().preprocess().resize(
      ov::preprocess::ResizeAlgorithm::RESIZE_LINEAR);
  end = system_clock::now();
  diff = end - beg;

#ifdef GLOG_INIT
  LOG(INFO) << " pre model input takes :" << diff.count() << "s " << std::endl;
#endif

  for (int i = 0; i < output_name.size(); ++i) {
#ifdef GLOG_INIT
    LOG(INFO) << " pre output, name and type: " << output_name[i] << " "
              << outtype[i] << std::endl;
#endif
    ppp.output(output_name[i]).tensor().set_element_type(outtype[i]);
  }
  beg = system_clock::now();
  model = ppp.build();
  end = system_clock::now();
  diff = end - beg;

#ifdef GLOG_INIT
  LOG(INFO) << " build model takes :" << diff.count() << "s " << std::endl;
#endif

  beg = system_clock::now();
  ov::CompiledModel compiled_model = ie.compile_model(
      model, "CPU",
      ov::hint::performance_mode(ov::hint::PerformanceMode::THROUGHPUT),
      ov::affinity(ov::Affinity::NUMA), ov::num_streams(1),
      ov::inference_num_threads(thread_nums));
  end = system_clock::now();
  diff = end - beg;

#ifdef GLOG_INIT
  LOG(INFO) << " compile_model takes :" << diff.count() << "s " << std::endl;
#endif
 
  beg = system_clock::now();
  infer_request = compiled_model.create_infer_request();
  auto end_t = system_clock::now();
  diff = end_t - beg;

#ifdef GLOG_INIT
  LOG(INFO) << " infer_request takes :" << diff.count() << "s " << std::endl;
#endif

  duration<double> diff_t = end_t - beg_t;

#ifdef GLOG_INIT
  LOG(INFO) << "load and pre model spend Takes " << diff_t.count() << "s "
            << std::endl;
#endif
```

onnxruntime:
The model is checked!
loading model to infer takes  0.47814512252807617 s
ort_sess is intiated!

 ```.py
    print('The model is checked!')
    start_time = time.time()
    self.ort_sess = onnxruntime.InferenceSession(self.model_path, providers=[ 'CPUExecutionProvider'])
    end_time = time.time()
    print('loading model to infer takes ', end_time - start_time, 's')
    print('ort_sess is intiated!')
 ```

**Comment by Aed-p** [comment]
But the loading speed of the model I trained with pytouch is normal, This model is a single input single output. LOG INFO:
I20220701 02:46:29.917366  4224 extract_model.cpp:29]  model_ir init :/root/worksppace/test/model.onnx
I20220701 02:46:30.910486  4224 extract_model.cpp:41]  read model takes :0.988514s 
I20220701 02:46:30.910706  4224 extract_model.cpp:52]  input_data size :102400
I20220701 02:46:30.911067  4224 extract_model.cpp:77]  pre model input takes :0.000218585s 
I20220701 02:46:30.911233  4224 extract_model.cpp:82]  pre output, name and type: output f32
I20220701 02:46:30.984758  4224 extract_model.cpp:93]  build model takes :0.073335s 
I20220701 02:46:32.229470  4224 extract_model.cpp:109]  compile_model takes :1.24445s 
I20220701 02:46:32.229790  4224 extract_model.cpp:120]  infer_request takes :0.00018658s 
I20220701 02:46:32.229842  4224 extract_model.cpp:126] load and pre model spend Takes 2.31234s

**Comment by brmarkus** [comment]
Certain ONNX models can be loaded directly into the OpenVINO inference engine in the meantime, without compiling/converting it, i.e. for example you can just call `benchmark_app -m my-model.onnx`.

If you want or need to compile the model - then you can do so separately, e.g. at build-time only; then you `export()` the compiled model into a blob-file - and your application only calls `import()` to import and load the "pre-compiled" model.

**Comment by Aed-p** [comment]
Thank you for your reply

But I load other onnx models and the speed is normal

For example:
I20220701 05:21:46.457312  4767 extract_model.cpp:30]  model_ir init :/root/worksppace/test/lib/moqi.onnx
I20220701 05:21:47.344118  4767 extract_model.cpp:42]  read model takes :0.881236s 
I20220701 05:21:47.344466  4767 extract_model.cpp:52]  input_data size :102400 2 3
I20220701 05:21:47.344898  4767 extract_model.cpp:79]  pre model input takes :0.000190058s 
I20220701 05:21:47.344991  4767 extract_model.cpp:84]  pre output, name and type: output f32
I20220701 05:21:47.410356  4767 extract_model.cpp:95]  build model takes :0.0652643s 
I20220701 05:21:48.856087  4767 extract_model.cpp:111]  compile_model takes :1.44547s 
I20220701 05:21:48.856802  4767 extract_model.cpp:122]  infer_request takes :0.000503142s 
I20220701 05:21:48.856896  4767 extract_model.cpp:128] load and pre model spend Takes 2.39935s

**Comment by brmarkus** [comment]
There could be bigger differences in the model with respect to used operations, tensors, layers, size.
Could be version-specific regarding supported operations&tensor.
Could depend on the amount of system memory.

**Comment by Aed-p** [comment]
Thank you for your reply
