### ISSUE TITLE
OpenVINO inference using C++ failed. Procedure

### ISSUE THREAD

**Issue by fanxiaochen456** [openvinotoolkit/openvino#12039]

**Comment by Iffa-Meah** [comment]
@fanxiaochen456 did you[ build from source](https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows) or did you use the[ installation binary](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_windows.html) for this version of OpenVINO?

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
