### ISSUE TITLE
Integrated Haswell GPU not recognized

### ISSUE THREAD

**Issue by Finfalter** [openvinotoolkit/openvino#12044]
##### System information

- OpenVINO: __2022.1.0__
- Operating System: __Ubuntu Linux 20.04__
- GPU: __Haswell-ULT Integrated Graphics Controller (rev 09)__

##### Detailed description
The gpu is not recognized by OpenVINO, in that is to say: `hello_query_device` only lists a CPU but not a GPU:

```bash
[ INFO ] OpenVINO Runtime version ......... 2022.1.0
[ INFO ] Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
[ INFO ] 
[ INFO ] Available devices: 
[ INFO ] CPU
[ INFO ] 	SUPPORTED_PROPERTIES: 
[ INFO ] 		Immutable: AVAILABLE_DEVICES : ""
[ INFO ] 		Immutable: RANGE_FOR_ASYNC_INFER_REQUESTS : 1 1 1
[ INFO ] 		Immutable: RANGE_FOR_STREAMS : 1 4
[ INFO ] 		Immutable: FULL_DEVICE_NAME : Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
[ INFO ] 		Immutable: OPTIMIZATION_CAPABILITIES : FP32 FP16 INT8 BIN EXPORT_IMPORT
[ INFO ] 		Immutable: CACHE_DIR : ""
[ INFO ] 		Mutable: NUM_STREAMS : 1
[ INFO ] 		Mutable: AFFINITY : CORE
[ INFO ] 		Mutable: INFERENCE_NUM_THREADS : 0
[ INFO ] 		Mutable: PERF_COUNT : NO
[ INFO ] 		Mutable: INFERENCE_PRECISION_HINT : f32
[ INFO ] 		Mutable: PERFORMANCE_HINT : ""
[ INFO ] 		Mutable: PERFORMANCE_HINT_NUM_REQUESTS : 0
[ INFO ] 
```
I made to to [Configure Inference on Non-CPU Devices](https://docs.openvino.ai/nightly/openvino_docs_install_guides_installing_openvino_apt.html#doxid-openvino-docs-install-guides-installing-openvino-apt)

Any hint is appreciated.

**Comment by brmarkus** [comment]
From the output of `hello_query_device` it looks like your SOC is this:
`Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz`
This is a 4th generation SOC.

Referring to "https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_linux.html#system-requirements", under the tab "Hardware", this OpenVINO version "2022.1.0" supports "6th to 12th generation Intel® Core™ processors"...

Would it make sense to try to find out whether there is an older version of OpenVINO still supporting a 4th generation SOC?

**Comment by Finfalter** [comment]
Thank you, @brmarkus, your suggestion sounds reasonable.

**Comment by brmarkus** [comment]
Hmm, from the drop-down list this seems to be the oldest OpenVINO version:
https://docs.openvino.ai/2018_R5/_docs_install_guides_installing_openvino_linux.html

But the system requirements list:
`6th-8th Generation Intel® Core™`

@jgespino do you have an idea for an even older version of OpenVINO - or finding the corresponding OpenCL version for 4th generation SOC and `Haswell-ULT Integrated Graphics Controller (rev 09)`, still compatible with OpenVINO?

**Comment by Iffa-Meah** [comment]
According to the[ Official OpenVINO System Requirement ](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html)that that hardware is indeed unsupported.

For CPU (4th Generation Intel Core) might work as a user had a trial & error for this and anyway you managed to run the hello_query_device sample app on it. You may refer [here](https://krbnite.github.io/Intel-at-the-Edge-Installing-Intels-OpenVINO-on-MacBook-with-4th-Generation-Intel-Core-i7/).
