### ISSUE TITLE
i can not use mo to convert paddle model on openvino 2022

### ISSUE THREAD

**Issue by shixinlishixinli** [openvinotoolkit/openvino#12049]
https://github.com/openvinotoolkit/openvino/blob/master/docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Paddle.md

i have read this tutorial. and try to use mo convert paddle model.
first , i can not find mo command, i have ready source /opt/intel/openvino_2022/setupvars.sh.
then i try to use mo.py convert paddle model.
![image](https://user-images.githubusercontent.com/20768380/177257947-8abc9854-e1cd-4e01-9ddc-12e6ae7512d2.png)
mo.py can not convert paddle model directly

the openvino is openvino_2022.1.0.643
the paddle model is paddleocr det model

best
lisa Shi

**Comment by brmarkus** [comment]
Would it be possible to share the exact same model you used for reproduction and further analysis?
Have you tried other Paddle models?

**Comment by shixinlishixinli** [comment]
I know what caused this problem. I installed two different versions of openvino on the same device. sorry to bother you。
