### ISSUE TITLE
Customize operation

### ISSUE THREAD

**Issue by Mxx-001** [openvinotoolkit/openvino#12047]
**System information**
- OpenVINO: 2022.1.0
- Operating System: Ubuntu Linux 20.04
- Model name: VGG16-12-int8
- Customize operation: QLinearConv

**Detailed description**
Mismatch error reporting for custom operations:  

> [ 2022-07-05 13:03:42,221 ] [ DEBUG ] [ class_registration:272 ]  Run replacer <class 'openvino.tools.mo.middle.DeleteNotExecutable.DeleteNotExecutable'>
> [ 2022-07-05 13:03:42,222 ] [ DEBUG ] [ DeleteNotExecutable:27 ]  Removing the following not executable nodes:
> [ 2022-07-05 13:03:42,224 ] [ DEBUG ] [ eliminate:55 ]  The following nodes are seeded as output reachable:
> vgg0_dense2_fwd/sink_port_0
> [ ERROR ]  -------------------------------------------------
> [ ERROR ]  ----------------- INTERNAL ERROR ----------------
> [ ERROR ]  Unexpected exception happened.
> [ ERROR ]  Please contact Model Optimizer developers and forward the following information:
> [ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'openvino.tools.mo.middle.DeleteNotExecutable.DeleteNotExecutable'>)": Number of elements in input [512] and output [1, 256, 1, 1] of reshape node vgg0_conv7_fwd_quant/DequantizeLinear211/Reshape/Sub mismatch

Any hint is appreciated.

**Comment by Iffa-Meah** [comment]
@Mxx-001 
1. could you share your model files and also the commands that you used to convert them to IR?
2. What model is this? (Tensorflow, ONNX, etc)

**Comment by Mxx-001** [comment]
Hi @Iffa-Meah ,
- Model file:  vgg16-12-int8.onnx
- Commands: python mo_onnx.py --input_model ./vgg16-12-int8.onnx --input_shape=[1,3,224,224] --use_legacy_frontend --output_dir ./IR

**Comment by Mxx-001** [comment]
- Link of the model file： https://github.com/onnx/models/tree/main/vision/classification/vgg/model

**Comment by slyalin** [comment]
@Mxx-001, is there any specific reason to use `--use_legacy_frontend` option? Does it work w/o this option?

**Comment by tomdol** [comment]
I've tried running this model using OV's benchmark_app but it contains a non-standard ONNX operator called `com.microsoft.QLinearAdd`. The `QLinearConv` operation you mentioned in this issue is supported though.

**Comment by Mxx-001** [comment]
> @Mxx-001, is there any specific reason to use `--use_legacy_frontend` option? Does it work w/o this option?

@slyalin， I have to do personal research with the legacy frontend.

**Comment by Mxx-001** [comment]
@slyalin， the new FE currently seems to only support ONNX* and PaddlePaddle*.

**Comment by slyalin** [comment]
> @slyalin， the new FE currently seems to only support ONNX* and PaddlePaddle*.

That's correct, but the model that you mentioned is in ONNX format. Are you originally interested in a different framework?

**Comment by Mxx-001** [comment]
> > @slyalin， the new FE currently seems to only support ONNX* and PaddlePaddle*.
> 
> That's correct, but the model that you mentioned is in ONNX format. Are you originally interested in a different framework?

I just want to learn to use the extension of MO through the ONNX model and reuse it on other frameworks(Caffe*, TensorFlow*, etc).

**Comment by slyalin** [comment]
@Mxx-001, please refer to this guide https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_customize_model_optimizer_Customize_Model_Optimizer.html for basic instruction about how to extend legacy Model Optimizer Python code base. But anyway I would recommend you to avoid using the old extensibility. It is a hard topic. If you need support for a particular model, just place corresponding support request for the model itself or for operations with enough justification why it is valuable for you and/or for the community.
