### ISSUE TITLE
[Bug] Convert Segformer to BLOB myriad_compile hangs indefinitely

### ISSUE THREAD

**Issue by paulguerrie** [openvinotoolkit/openvino#12080]
##### System information
- OpenVINO => 2021.4.2
- Operating System / Platform => Docker Container --> openvino/ubuntu18_dev:2021.4.2
- Problem classification: Model Conversion
- Framework: pytorch --> onnx --> IR --> blob
- Model name: Segformer

##### Detailed description
Hello,

I'm trying to convert a Segformer model from pytorch to blob through onnx and IR formats. I can get the model into IR format, but from there, when I run the myriad_compile command to conver to blob format, it hangs indefinitely.

##### Steps to reproduce
First I load the pytorch model and conver to onnx with Python:
```
from transformers import SegformerFeatureExtractor, SegformerForSemanticSegmentation
from PIL import Image
import torch.onnx
import onnxruntime as ort
import numpy as np
from torch import nn

feature_extractor = SegformerFeatureExtractor.from_pretrained("nvidia/segformer-b0-finetuned-ade-512-512")
model = SegformerForSemanticSegmentation.from_pretrained("nvidia/segformer-b0-finetuned-ade-512-512", return_dict=False)
model.eval()
image = Image.open('input.jpg')
inputs = feature_extractor(images=image, return_tensors="pt")['pixel_values']

torch.onnx.export(
    model, 
    inputs, 
    'segformer-b0-finetuned-ade-512-512.onnx', 
    verbose=False,
    opset_version=11,
    )
```
Then, within the openvino docker container `openvino/ubuntu18_dev:2021.4.2` I run:
```
/opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py --input_model /<PATH TO>/segformer-b0-finetuned-ade-512-512.onnx --output_dir /<PATH TO>/openvino/ --scale_values [0.229,0.224,0.225] --mean_values [0.485,0.456,0.406]
```
Then, still within the openvino container I run:
```
/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/myriad_compile -ip U8 -c /<PATH TO>/blob/segformer-b0-finetuned-ade-512-512/myriad_compile_config.txt -m /<PATH TO>/openvino/segformer-b0-finetuned-ade-512-512.xml -o /<PATH TO>/blob/segformer-b0-finetuned-ade-512-512/segformer-b0-finetuned-ade-512-512.sh6NCE1
```

Here is the contents of my `myriad_compile_config.txt`:
```
MYRIAD_NUMBER_OF_SHAVES 6	
MYRIAD_NUMBER_OF_CMX_SLICES 6	
MYRIAD_THROUGHPUT_STREAMS 1	
```

**Comment by jgespino** [comment]
Hi @paulguerrie Appologies for the delay, I am able to see the same behavior when loading the model to an Intel Neural Comptue Stick 2 using OpenVINO 2022.1. I have enabled log_level Tracing to obtain additional details, so far it's still running but I will let you know what I find out. 

Also, I see this model has been enabled for CPU and GPU only so it may not be supported on MYRIAD.

**Comment by Iffa-Meah** [comment]
@paulguerrie I can see the same issue from my end.

Conversion to FP16
<img width="858" alt="12080_moFP16" src="https://user-images.githubusercontent.com/79643476/178393347-4129663c-68dc-493e-bf14-90cd457f6e56.png">

Hangs on blob creation
<img width="394" alt="blob_hangs_ub" src="https://user-images.githubusercontent.com/79643476/178393458-f5b16f01-fedf-47ad-b4f3-ee767ab1e1a5.png">

I tried on a different OS just to see whether it works but similar issue persists.
<img width="868" alt="blob_hangs_diffOS" src="https://user-images.githubusercontent.com/79643476/178393551-281d6df9-e78c-461f-8e3e-cf862c7957a5.png">


We will further investigate this and get back to you asap.

**Comment by paulguerrie** [comment]
Thanks for looking into this!  Also, can you explain more what you mean by:

> Also, I see this model is being analized to be supported on CPU and GPU only so it may not be supported on MYRIAD.

Is this to do with the architecture of the model?

**Comment by jgespino** [comment]
@paulguerrie The Segformer model is not supported on MYRIAD. We do have a list of public supported models and Intel Pre-trained models. Could you take a look at the following and see if any of these models fit your use case?

https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/device_support.md
https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/device_support.md

I am also going to open a bug for the development team to look at the hanging issue when loading the model or compiling the blob. 

Regards,
Jesus

**Comment by paulguerrie** [comment]
Thanks for tracking down that info @jgespino !  I'll take a look at the links you provided. Could we open a model enablement request for SegFormer for MYRIAD?

**Comment by jgespino** [comment]
@paulguerrie Could you send me an email as I need additional information from your side? My email is visable on my profile.

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.

**Comment by yuchenlichuck** [comment]
Hi, there, I come across the same issues and please let me know if the issues has been fixed
