### ISSUE TITLE
OpenVINO c++ achieve channel transpose. (From NWHC to NCHW) 

### ISSUE THREAD

**Issue by wenbufan** [openvinotoolkit/openvino#12091]
Hello there,
me and my team are trying to create a c++ code for a segmentation task. in this task, we need to transpose the input data from NWHC to NCHW. but there is no any tutorial online. we are trying use ov::op::Transpose and ngraph::op::Transpose, but they don't work. 

is there any tutorial or any code example that can solve this problem? 

thanks a lot.

**Comment by xipingyan** [comment]
hi @wenjiew Could you please refer this sample: https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/classification_sample_async/main.cpp#L94 ?
Latest OpenVINO provided "ov::preprocess::PrePostProcessor" to handle those similar situations.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
