### ISSUE TITLE
[Bug] floordiv_3 (Floor) types check error: input #0 has type S32, but FP16 is expected

### ISSUE THREAD

**Issue by LinBaoxin** [openvinotoolkit/openvino#12095]
##### System information (version)

- OpenVINO=> 2022.1.0
- Operating System / Platform => Windows 10 (64 Bit)
- Compiler => pip install openvino-dev[tensorflow2,caffe]
- Problem classification => Model Conversion
- Framework: TensorFlow
- Model name: MoveNet: Ultra fast and accurate pose detection model

##### Detailed description

Hi there,
When I tried running my IR model on NCS2, I saw the following error:

>RuntimeError: StatefulPartitionedCall/floordiv_3 of type Floor: [ GENERAL_ERROR ] 
C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\plugins\intel_myriad\graph_transformer\src\model\stage.cpp:305 Stage node StatefulPartitionedCall/floordiv_3 (Floor) types check error: input #0 has type S32, but FP16 is expected

There is a similar issue #7799.

##### Steps to reproduce

The model I used is downloaded from Tensorflow Hub.
Tensorflow Document Page: [MoveNet: Ultra fast and accurate pose detection model](https://tensorflow.google.cn/hub/tutorials/movenet)
I converted the [movenet_multipose_lightning_1.tar.gz](https://github.com/openvinotoolkit/openvino/files/9073503/movenet_multipose_lightning_1.tar.gz) SavedModel (TF 2. x) format to [movenet_multipose_192x256.pb](https://github.com/openvinotoolkit/openvino/files/9073453/model.zip) PB format (TF 1. x) format and then convert it to IR format.

Here is the command:
>mo --input_model "movenet_multipose_192x256.pb" --input_shape "[1,192,256,3]" --data_type FP16

Here is the code:
```
from openvino.runtime import Core

import numpy as np
import time


ie = Core()
model = ie.read_model(model="movenet_multipose_192x256.xml", weights="movenet_multipose_192x256.bin")
compiled_model = ie.compile_model(model=model, device_name='CPU')
# compiled_model = ie.compile_model(model=model, device_name='MYRIAD')
input_key = compiled_model.input(0)
output_key = compiled_model.output(0)

image = np.random.randint(0, 256, [192, 256, 3]).astype(np.uint8)
image = np.expand_dims(image, axis=0)
tic = time.time()
result = compiled_model([image])[output_key]
toc = time.time()
print(toc - tic)
```

I can run it on the CPU successfully, but no NCS2.

**Comment by Iffa-Meah** [comment]
@LinBaoxin I can see similar behaviour from my end.

Conversion into FP16 IR
<img width="639" alt="conversion" src="https://user-images.githubusercontent.com/79643476/178218788-37fe770c-fb5d-490b-a972-3633479b57be.png">

CPU infer (success)
<img width="641" alt="cpu" src="https://user-images.githubusercontent.com/79643476/178218913-a16aff62-938a-4707-9f1a-a4bb2c0c9cae.png">

NCS2 infer (failed)
<img width="643" alt="NCS2" src="https://user-images.githubusercontent.com/79643476/178218948-0fad1c51-68ca-4582-9e6c-7670b7b5a89b.png">

We'll further investigate this and get back to you asap.

**Comment by hbalasu1** [comment]
Hi @LinBaoxin 

Look like this is the bug since the issue happened on NCS2. I have escalated this issue to our development teams and will get back to you once I have the answer as soon as possible. 

Regards,
Hari Chand

Ref. 88871

**Comment by hbalasu1** [comment]
Hi @lsprior 

I received a reply from the Developer that Floor operation is only supported on Myriad for FP16. Such movenet model is not supported by the Myriad plugin. A possible workaround could be to include a convert operation in the model so that it works with the Myriad plugin.

Hope this information help

Thank you

**Comment by avitial** [comment]
Closing this. Feel free to reopen and ask any questions related to this topic.
