### ISSUE TITLE
Deploy models with OpenVINO under PyPI

### ISSUE THREAD

**Issue by songs18** [openvinotoolkit/openvino#12111]
##### System information (version)
- OpenVINO => 2022.1
- Operating System / Platform => Windows 11 64 Bit
- Compiler => GCC 8.1.0
- Problem classification: Model Deployment
- Framework: ONNX (if applicable)
- Model name: Any (if applicable)

##### Detailed description

I want to deploy one trained model with Python, but i cannot package it with pyinstaller/nuitka. I search some keywords, and I found i need to use openvino to pakcage it. But i do not know how to deploy it under PYPI environment. Do i need install Python and use pip to install openvino on one new machine? Is there an simple method?

1. During installing deployment tools, where is <INSTALL_DIR>/tools/requirements_tf.txt in https://docs.openvino.ai/latest/openvino_2_0_deployment.html#installing-openvino-development-tools-via-pypi？Since there is no <INSTALL_DIR>  in PYPI mode. I checked virtual environment directory/Lib/site-packages/openvino, but i cannot found it.

2. How to deploy models under PYPI? https://docs.openvino.ai/latest/openvino_docs_install_guides_deployment_manager_tool.html is not based on PYPI. PYPI gives some commands, such as mo.exe. Which one command should i use to deploy models just like .\deployment_manager.py?

**Comment by zulkifli-halim** [comment]
Hi @songs18. You can install the OpenVINO developer package via pip. The installation step is available in [OpenVINO Development Tools](https://pypi.org/project/openvino-dev/). The developer package also installs the OpenVINO Runtime package as a dependency. It includes a set of libraries for easy inference integration into your applications.

The requirement_tf.txt file is available in this location:
`C:\<INSTALL_DIR\openvino_env\Lib\site-packages\openvino\tools\mo`

Your custom model can be converted to IR format by using Model Optimizer command:
`mo --input_model model.onnx`

**Comment by songs18** [comment]
Thanks.

I want to integrate my trained onnx model (translated from .pth) into one Python application.
But i cannot use usual methods, like pyinstaller/nuitka, to package it into my exe file.
I am confused that how to package openvino  into my exe. Or openvino works like system-level services.

Are there some tutorials about it?
I know [Depolyment Manager](https://docs.openvino.ai/latest/openvino_docs_install_guides_deployment_manager_tool.html). But i do not where should i place my GUI code? How should my code communicate with Openvino.

**Comment by songs18** [comment]
Thanks@[jgespino](https://github.com/jgespino) for removing bug labels.

**Comment by zulkifli-halim** [comment]
@songs18. OpenVINO installed via pip does not support deployment packages. If you want to use Deployment Manager to create deployment packages, I recommend that you install the [Intel Distribution of OpenVINO Toolkit](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html) (runtime package), because [Deployment Manager](https://docs.openvino.ai/latest/openvino_docs_install_guides_deployment_manager_tool.html) is available in this distribution package.





![image](https://user-images.githubusercontent.com/79680111/179186083-693b3cc2-a846-4f83-ad4c-e4a2a0ed130e.png)

**Comment by songs18** [comment]
I can generate a zip from an older version of openvino, and publish it on the target machine. 
However, after running .\setupvars.bat on the target machine, how can I call it to inference new images? 
[Deployment Manager](https://docs.openvino.ai/latest/openvino_docs_install_guides_deployment_manager_tool.html) does not have relevant examples.

**Comment by zulkifli-halim** [comment]
@songs18. You can use the Deployment Manager tool in the [standard CLI mode](https://docs.openvino.ai/latest/openvino_docs_install_guides_deployment_manager_tool.html#run-standard-cli-mode) as an alternative. 

You also can refer to [Build Your Application with Deployment Package](https://docs.openvino.ai/2022.1/workbench_docs_Workbench_DG_Deployment_Package.html). But this is only compatible with Ubuntu 18.04 and 20.04.
