### ISSUE TITLE
Error: mo_result = %sx $mo_command

### ISSUE THREAD

**Issue by WangRuixin93** [openvinotoolkit/openvino#12188]
mo_result = %sx $mo_command
                ^
SyntaxError: invalid syntax

what does " %sx $" mean？I  can't find it google

**Comment by Iffa-Meah** [comment]
@WangRuixin93 may I know where you encountered that %sx? is it in an OpenVINO samples/demo?
If according to the standard C library, the %s expects a string while %x expects a hexadecimal number (format specifier).

If you are referring to the Jupyter Notebook/Lab command, the %sx command works exactly like the %system command where it executes any single line Unix shell command from the notebook.

**Comment by WangRuixin93** [comment]
Got it. It belongs to the latter. The code is from 'Convert a PyTorch Model to ONNX and OpenVINO IR' (https://docs.openvino.ai/latest/notebooks/102-pytorch-onnx-to-openvino-with-output.html) section 'Convert ONNX Model to OpenVINO IR Format'. 
I run it in Pycharm IDE under win10. Instead of running the original code, I have directly run mo_onnx.py in terminal.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by phutoan31299** [comment]
@WangRuixin93 can you share your mo_onnx.py file. Thanks

**Comment by WangRuixin93** [comment]
@phutoan31299 it is in my path "C:\Users\xx\AppData\Roaming\Python\Python37\site-packages\openvino\tools\mo" 
try to find it
