### ISSUE TITLE
Error when I use a converted  openvino model  to detect a image

### ISSUE THREAD

**Issue by mlchuxueing** [openvinotoolkit/openvino#122]
when i run this script:  ./object_detection_sample -i people.jpg -m /opt/intel/computer_vision_sdk_fpga_2018.3.343/deployment_tools/model_optimiz   er/model/faster_rcnn_resnet50/frozen_inference_graph.xml  -d CPU  --bbox_name SecondStageBoxPredictor/AvgPool   --proposal_name Proposal --pro   b_name do_softmax_conf,
the error is : Can't create detection output: Number of priors must match number of confidence predictions. please help me! Thank you!

**Comment by shubha-ramani** [comment]
Dear @mlchuxueing  can you kindly retry with the latest OpenVino version ? 2019 R1 was just released and 2018.3.343 is pretty old.

Thanks for using OpenVino !

Shubha

**Comment by mlchuxueing** [comment]
> Dear @mlchuxueing can you kindly retry with the latest OpenVino version ? 2019 R1 was just released and 2018.3.343 is pretty old.
> 
> Thanks for using OpenVino !
> 
> Shubha
when i install 2019R1, in the step :
sudo -E ./install_openvino_dependencies.sh
it occured:   sudo: ./install_openvino_dependencies.sh: command not found.
Can you tell me how to solve this problem?

**Comment by shubha-ramani** [comment]
Dear @mlchuxueing

The file install_openvino_dependencies.sh does not exist in the open source github for the latest dldt.  Did you install the non-open source version ?  Did you install the version of [OpenVino with FPGA Support](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux_fpga.html) ? The reason I ask is because I do see this file install_openvino_dependencies.sh in the docker script.

Thanks,

Shubha

**Comment by bkhi1** [comment]
I am also encountering this problem. 

Did you install the version of OpenVino with FPGA Support ? 
>> yes

Can you kindly go to your top level directory and see whether install_openvino_dependencies.sh exists somewhere within ? 
>> yes

**Comment by bkhi1** [comment]
solved by 
sudo chmod ugo+x install_openvino_dependencies.sh

**Comment by lazarevevgeny** [comment]
@mlchuxueing is this issue still actual?

**Comment by AnastasiaKazantaeva** [comment]
As problem doesn't exist any more, I am closing this issue. You may reopen it or create a new one
