### ISSUE TITLE
unresolved external symbol CreateFormatReader referenced in function "public: __cdecl FormatReader::ReaderPtr::ReaderPtr(char const *)" 

### ISSUE THREAD

**Issue by das-ankur** [openvinotoolkit/openvino#12202]
`const std::string image_path = "absolute_image_path.jpg";`
`FormatReader::ReaderPtr reader(image_path.c_str());`
I am getting error on the second line. I checked the constructor defintion of FormatReader::ReaderPtr. It takes argument as const char * . Here, I convert the string to const char * by c_str() and pass it. I also tried to stroe the whole string as const char* and passed that. In both the cases I am getting same error. Can anyone please help me with this error?

**Comment by das-ankur** [comment]
I am building it on visual studio. In external libraries it is also present but when I am writting this code it's generating error.

**Comment by brmarkus** [comment]
Is your VisualStudio-project based on MAKE, based on CMAKE? Is the project manually maintained (manually adding include search-paths, library-search-paths, libraries to link)?
Does your project allow to call "cmake" manually? Then CMAKE will create a file like "CMakeCache.txt", in which you can check whether "format_reader" was found and under which path.
Do you see a difference with a project-build config for RELEASE and for DEBUG?

**Comment by ilyachur** [comment]
@das-ankur Could you double check that your Visual Studio project is linked with FormatReader library?

**Comment by das-ankur** [comment]
@ilyachur Yes, I can find it inside external libraries of visual studio and I am also not getting error on the include statement of format_reader_ptr and format_reader.

**Comment by das-ankur** [comment]
@brmarkus Yes, it is based on CMAKE and some at first I was linking it manually and from now I am linking the format_reader using cmake file. As you have said I check the CMakeCache.txt file but I have not found the format_reader in this.

**Comment by das-ankur** [comment]
@tomdol I am new to openvino. Can you please tell me how can I link the target. I used include_directories in cmake file for linking but can't understand how to link with the target.

**Comment by brmarkus** [comment]
> @brmarkus Yes, it is based on CMAKE and some at first I was linking it manually and from now I am linking the format_reader using cmake file. As you have said I check the CMakeCache.txt file but I have not found the format_reader in this.

Can you run a clean-build, again, please?
I just checked again with the OpenVINO inference-engine demos and in "CMakeCache.txt" in my build-directory I can see this:

```
...
//Dependencies for the target
cnpy_LIB_DEPENDS:STATIC=general;zlib;

//Dependencies for the target
format_reader_LIB_DEPENDS:STATIC=general;opencv_core;general;opencv_imgproc;general;opencv_imgcodecs;general;ie_samples_utils;

//Value Computed by CMake
gflags_BINARY_DIR:STATIC=/localdisk/ARS/OpenVINO/inference_engine_samples/thirdparty/gflags
...
```

**Comment by brmarkus** [comment]
It might look like you have some dependencies in `CMakeLists.txt` files and some in your VisualStudio project-settings distributed.
If all dependencies (search-paths for header-files and libraries and the thirdparty libraries) are in `CMakeLists.txt` files, then calling `cmake` would immediately result in errors where dependencies could not be found - before calling `make` to compile and link.

**Comment by das-ankur** [comment]
> It might look like you have some dependencies in `CMakeLists.txt` files and some in your VisualStudio project-settings distributed. If all dependencies (search-paths for header-files and libraries and the thirdparty libraries) are in `CMakeLists.txt` files, then calling `cmake` would immediately result in errors where dependencies could not be found - before calling `make` to compile and link.

I am getting run time error. During calling cmake I am not getting any error. Should I share with you the cmake file?

**Comment by das-ankur** [comment]
> If possible please share the code by either pushing it to github or any other way. Perhaps there's some slight missing detail but without the actual project code it's difficult to figure it out.

Hey, sorry I can't share the whole code as I have some restrictions to do. But I can share the cmake file and some part of the code. Will it work?

**Comment by das-ankur** [comment]
I can't see format_reader inside references but it is created when I built samples. Any suggestions?

**Comment by brmarkus** [comment]
> > If possible please share the code by either pushing it to github or any other way. Perhaps there's some slight missing detail but without the actual project code it's difficult to figure it out.
> 
> Hey, sorry I can't share the whole code as I have some restrictions to do. But I can share the cmake file and some part of the code. Will it work?

The more you provide and explain the better.

**Comment by brmarkus** [comment]
> I can't see format_reader inside references but it is created when I built samples. Any suggestions?

What do you mean with "inside references"?

**Comment by das-ankur** [comment]
> > I can't see format_reader inside references but it is created when I built samples. Any suggestions?
> 
> What do you mean with "inside references"?

I am using visual studio. Inside my project there is a option called refeences and inside it I can't find format_reader

**Comment by das-ankur** [comment]
If someone is facing the same issue please follow the below article. In this article opencv is used to explain the solution but the steps to solve linking error of format_reader is also same. Article Link: [https://subwaymatch.medium.com/adding-opencv-4-2-0-to-visual-studio-2019-project-in-windows-using-pre-built-binaries-93a851ed6141](url)
