### ISSUE TITLE
[support_request] RUNTIME ERROR: Model references undeclared parameters

### ISSUE THREAD

**Issue by Daveorr** [openvinotoolkit/openvino#12236]
Hi, I'm trying to convert a model from ONNX to openvino IR and I'm getting the following message:

`RuntimeError: Model references undeclared parameters: v0::Parameter img2 () -> (f32{1,3,192,128})
v0::Parameter img1 () -> (f32{1,3,192,128})`

The ONNX has been obtained as follows:

```
    torch.onnx.export(model,               # model being run
                      (dummy_input['img1'] , dummy_input['img2']),                         # model input (or a tuple for multiple inputs)
                      onnx_out_name,   # where to save the model (can be a file or file-like object)
                      export_params=True,        # store the trained parameter weights inside the model file
                      verbose=False, 
                      opset_version=12,          # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names = ['img1', 'img2'],   # the model's input names
                      output_names = ['flows'],
                     ) # the model's output names
```

img1 and img2 are supposed to be my inputs (also the shapes are correct), for the conversion I'm running the following command:

`mo --input_model ffnet_opset12_simplified.onnx --input 'img1[1 3 192 128],img2[1 3 192 128]' --output 'flows' --static_shape`

What am I doing wrong? (ONNX model run without issues)

**Comment by Iffa-Meah** [comment]
@Daveorr could you share your model files including the images? The code that you share doesn't seem complete to generate the ONNX model from my side.

**Comment by Daveorr** [comment]
Thanks for the answer, here's the codebase: https://drive.google.com/drive/folders/1XFqjFn4OnyLBszWnVkA4uXNsD2RyAXEK?usp=sharing

**Comment by Iffa-Meah** [comment]
@Daveorr Starting from the 2020.4 release, OpenVINO™ supports reading native ONNX models. Therefore, if your ONNX ori model has no issues, you should be able to run it directly with OpenVINO Benchmark App.

I checked your ONNX model 
<img width="618" alt="ONNXresult" src="https://user-images.githubusercontent.com/79643476/180351659-f5e9f42d-c58e-4469-bf2e-a234e95e54d0.png">

Your issue seems to be originated from your ONNX model **instead of OpenVINO**.
You'll need to fix the error within your model itself.

**Comment by Daveorr** [comment]
Thanks for the answer, any idea on what can originate the error `RuntimeError: Model references undeclared parameters: v0::Parameter img2 () -> (f32{1,3,192,128}) v0::Parameter img1 () -> (f32{1,3,192,128})` so i can fix my model?

**Comment by Iffa-Meah** [comment]
@Daveorr it seems that you didn't declare those parameters in your model: (v0::Parameter img2 () -> (f32{1,3,192,128}) v0::Parameter img1 () -> (f32{1,3,192,128}) )

OpenVINO support varieties of frameworks but it does have its limitation, especially in framework layers.
There's also a possibility that your model is using an unsupported layer which you can cross-check [here](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html).

**Comment by Daveorr** [comment]
Thanks again for your answer,

>@Daveorr it seems that you didn't declare those parameters in your model: (v0::Parameter img2 () -> (f32{1,3,192,128}) v0::Parameter img1 () -> (f32{1,3,192,128}) )

I can see there's some issue with some parameter, the error message state it clearly, what confuses me is that the model works fine on ONNX, and even TF and TFlite. I didn't had to specify anything and `img1` and `img2` are just my inputs. I also I've tried to convert another model to OpenVINO IR (succesfully) and when I compared the 2 onnx graphs using netron I didn't see anything different in the inputs specification. Do I need to specify the input in a particular way to make them compatible with OpenVINO mo?

again, here is how I converted the model from torch to onnx (quite standard approach)
```
    torch.onnx.export(model,               # model being run
                      (dummy_input['img1'] , dummy_input['img2']),                         # model input (or a tuple for multiple inputs)
                      onnx_out_name,   # where to save the model (can be a file or file-like object)
                      export_params=True,        # store the trained parameter weights inside the model file
                      verbose=False, 
                      opset_version=12,          # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names = ['img1', 'img2'],   # the model's input names
                      output_names = ['flows'],
                     ) # the model's output names
```

Any hint is welcome, I couldn't find the reported error message anywere in any other issue

Thanks again

**Comment by Iffa-Meah** [comment]
@Daveorr we'll further assess this and get back to you with the appropriate solution/workaround asap.
Thank you for your patience.

**Comment by Daveorr** [comment]
Thanks a lot, let me know if I can help you with additional information

**Comment by jgespino** [comment]
@Daveorr I was able to convert your model using the following model optimizer command. Can you try from your side and let me know if it works for you too?

```
mo --input_model ffnet_opset12_simplified.onnx --use_legacy_frontend
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      C:\12236\ffnet_opset12_simplified.onnx
        - Path for generated IR:        C:\12236\.
        - IR output name:       ffnet_opset12_simplified
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         Not specified, inherited from the model
        - Source layout:        Not specified
        - Target layout:        Not specified
        - Layout:       Not specified
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - User transformations:         Not specified
        - Reverse input channels:       False
        - Enable IR generation for fixed input shape:   False
        - Use the transformations config file:  None
Advanced parameters:
        - Force the usage of legacy Frontend of Model Optimizer for model conversion into IR:   True
        - Force the usage of new Frontend of Model Optimizer for model conversion into IR:      False
ONNX specific parameters:
OpenVINO runtime found in:      c:\12236\openvino_env\lib\site-packages\openvino
OpenVINO runtime version:       2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version:        2022.1.0-7019-cdb9bec7210-releases/2022/1
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: C:\12236\ffnet_opset12_simplified.xml
[ SUCCESS ] BIN file: C:\12236\ffnet_opset12_simplified.bin
[ SUCCESS ] Total execution time: 64.18 seconds.
It's been a while, check for a new version of Intel(R) Distribution of OpenVINO(TM) toolkit here https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html?cid=other&source=prod&campid=ww_2022_bu_IOTG_OpenVINO-2022-1&content=upg_all&medium=organic or on the GitHub*
[ INFO ] The model was converted to IR v11, the latest model format that corresponds to the source DL framework input/output format. While IR v11 is backwards compatible with OpenVINO Inference Engine API v1.0, please use API v2.0 (as of 2022.1) to take advantage of the latest improvements in IR v11.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai
```

**Comment by Daveorr** [comment]
@jgespino I can confirm that the model now is converting. 

Thanks a lot for the kind support, I'm gonna close this issue and I'll come back here if I have some new problem.

Thanks a lot again!
