### ISSUE TITLE
[onnx model] read onnx model with fp16

### ISSUE THREAD

**Issue by wang7393** [openvinotoolkit/openvino#12256]
##### System information (version)
- OpenVINO=> :2022.1
- Operating System / Platform => :win10
- Problem classification => :read model

##### Detailed description

If I want to read model with onnx and compile with fp16, how to use it?
With cpu, I use core.set_property(ov::hint::inference_precision("bf16")); but the inference time increase very high comped with fp32? Is that normal?
With gpu, there is no such config, how to set fp16 with onnx?

**Comment by brmarkus** [comment]
Can you provide more details about your environment, HW and SW, please?
Can you call `hello_query_device` to get an overview of the device's default/optimal and supported precision?

**Comment by wang7393** [comment]
@brmarkus 
![image](https://user-images.githubusercontent.com/29936604/180373989-1569f2c4-0dcd-4822-bb38-935579a470d8.png)
![image](https://user-images.githubusercontent.com/29936604/180374013-9662bace-69a1-4377-a2ee-98b965f3b488.png)

**Comment by jane-intel** [comment]
@wang7393 Could you clarify which precision are you aiming for? You mentioned **f16** and here you set **bf16**:  `core.set_property(ov::hint::inference_precision("bf16"));`

GPU device doesn't support bf16 and you can see it here:
![image](https://user-images.githubusercontent.com/55839243/180408024-9dd3f765-af1e-4a78-91e2-c1c3fae1f360.png)

If you'd like to utilize f16 capabilities of GPU -- please use this code
`core.set_property(ov::hint::inference_precision("f16"));`

@wang7393 does it help?

For the part with CPU I need a little bit more details. Could you share the model?

> With cpu, I use core.set_property(ov::hint::inference_precision("bf16")); but the inference time increase very high comped with fp32? Is that normal?

**Comment by dmitry-gorokhov** [comment]
@wang7393 i7-11800H CPU doesn't have BF16 support in hardware so BF16 inference is being running in emulation mode which might be several times slower than FP32 inference. 
The only Intel CPU on market that has native BF16 support is Cooper Lake (CPX, third generation of Xeons).

**Comment by wang7393** [comment]
@jane-intel 
1. Load onnx model, and set "core.set_property(ov::hint::inference_precision("f16"));"  or "core.compile_model(m_model, "GPU", ov::hint::inference_precision(ov::element::f16));"the following errors report:
 [ NOT_FOUND ] Unsupported property key by plugin: INFERENCE_PRECISION_HINT
2. What is the difference between  "core.set_property(ov::hint::inference_precision("f16"));"  or "core.compile_model(m_model, "GPU", ov::hint::inference_precision(ov::element::f16));"  ?
3. As we know, onnx to IR model can set fp16 precision, and can successfully generate IR model, but directly load onnx model settings FP16 can not be set successfully? why?

**Comment by wang7393** [comment]
@dmitry-gorokhov 
Thanks for your reply.
I have transform a onnx model to IR model with FP16, it can run successfully.
But I load onnx model directly with "core.set_property("CPU", ov::hint::inference_precision("f16"));", the foloowings error report:
"Wrong value for property key INFERENCE_PRECISION_HINT. Supported values: bf16, f32". Why?

**Comment by jgespino** [comment]
@wang7393 CPU only support bf16 and f32 data types as inference precision. This information can be found on the OpenVINO [CPU device](https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_CPU.html#supported-inference-data-types) documentation. When loading an fp16 IR model, the plugin will convert all fp16 values to fp32 internally. 

> Load onnx model with gpu, and set "core.set_property(ov::hint::inference_precision("f16"));" or "core.compile_model(m_model, "GPU", ov::hint::inference_precision(ov::element::f16));"the following errors report:
[ NOT_FOUND ] Unsupported property key by plugin: INFERENCE_PRECISION_HINT

GPU does not support this property, see the [GPU device](https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_GPU.html#read-write-properties) documentation.

> What is the difference between "core.set_property(ov::hint::inference_precision("f16"));" or "core.compile_model(m_model, "GPU", ov::hint::inference_precision(ov::element::f16));" ?

[ov::Core::set_property](https://docs.openvino.ai/latest/classov_1_1Core.html#doxid-classov-1-1-core-1aa953cb0a1601dbc9a34ef6ba82b8476e) - Sets a new value for the property globally for specified device_name.
[ov::Core::compile_model](https://docs.openvino.ai/latest/classov_1_1Core.html#doxid-classov-1-1-core-1a46555f0803e8c29524626be08e7f5c5a) to load the model to a specific device with specific configuration properties.

See this [documentation ](https://docs.openvino.ai/latest/openvino_docs_OV_UG_query_api.html#working-with-properties-in-your-code)for more information.

**Comment by wang7393** [comment]
@jgespino Will GPU support ONNX-FP16 in the future？

**Comment by vladimir-paramuzov** [comment]
@wang7393 inference_precision hint support for GPU plugin is implemented in #12526

**Comment by wang7393** [comment]
Will it be the next official release of OpenVino?

**Comment by jgespino** [comment]
@wang7393 the pull request has been merged to master branch, you can [build ](https://github.com/openvinotoolkit/openvino/wiki/BuildingCode)openvino from source now if you need this. Otherwise, it should be included in the next release.
