### ISSUE TITLE
 Package with PyInstaller --RuntimeError: [ NETWORK_NOT_READ ] Unable to read the model  

### ISSUE THREAD

**Issue by tonycc521** [openvinotoolkit/openvino#12254]
hi, I am trying to package with PyIntaller and I am having some problems. Here is my configuration and the problem:

System information 
- OpenVINO = 2022.1.0
- Operating System / Platform = Windows10 64 Bit
- Compiler = Pycharm 2021.1.2
- python version = 3.9
- pyinstaller version = 5.2
- Model name: ch_ppocr_mobile_v2.0_det_infer/inference.pdmodel

Detailed description
     I want to use OpenVino to speed up a character recognition model for Paddle. It is fine to run the program using source code, but when I use PyInstaller to package the EXE, I get this error:
_RuntimeError: [ NETWORK_NOT_READ ] Unable to read the model: yolov5s.onnx Please check that model format: onnx is supported and the model is correct. Available frontends_
    I tried to convert .pdmodel to .onnx or IR, but the same mistake happened again. I have also used yolov5's simple example for packaging, and the error remains the same.
yolov5's simple example:  https://mp.weixin.qq.com/s/TBjoPf9HEdna1BjWgWSnCQ

What do I need to do to solve this problem?
Thanks

**Comment by slyalin** [comment]
Please refer to this reply in another very similar issue https://github.com/openvinotoolkit/openvino/issues/11293#issuecomment-1081842200. The summary is that you probably need to provide paths to all necessary binary dependencies manually to PyInstaller.

**Comment by tonycc521** [comment]
> Please refer to this reply in another very similar issue [#11293 (comment)](https://github.com/openvinotoolkit/openvino/issues/11293#issuecomment-1081842200). The summary is that you probably need to provide paths to all necessary binary dependencies manually to PyInstaller.

I looked at the issue according to your suggestion and successfully helped solve my problem,thank you!
