### ISSUE TITLE
Is the first generation Neural Compute Stick unavailable?

### ISSUE THREAD

**Issue by FeiSong123** [openvinotoolkit/openvino#12264]

**Comment by FeiSong123** [comment]
I find in this https://github.com/openvinotoolkit/openvino/wiki/BuildingCode that it only lists Intel® Neural Compute Stick 2.

**Comment by brmarkus** [comment]
With recent OpenVINO versions, only the Myriad-X, NCS2 is supported.
I found a reference in an older Release-Notes document, see "https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes-2020.html#inpage-nav-1-3-5".

**Comment by jgespino** [comment]
@FeiSong123 As @brmarkus mentioned, the current release of OpenVINO only supports the Intel Neural Compute Stick 2. The last OpenVINO release to support the Intel Movidius Neural Compute Stick was OpenVINO 2020.3 LTS Release. 

https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html
