### ISSUE TITLE
Slow Runtime using OpenVINO C API

### ISSUE THREAD

**Issue by mmonares** [openvinotoolkit/openvino#12331]
###### System information (version):

OpenVINO => 2021.4.752
System / Platform => Windows 10/11 64 Bit
Compiler => (C API)
Framework => Intermediate Representation (.xml and .bin)  
Problem Classification: Model Runtime w/ C API
Model name => All

###### Detailed description:

We are using OpenVINO’s C API in our C project, but we are facing terrible runtime. Our project is a multithreaded C environment, and initialization/loading of the model (ie_core_create(), ie_read_network(), ie_load_network()) take over an hour. We have tested the functions in our project with multiple .xml and .bin files - some taken from Open Model Zoo - with varied runtime, but all of them are take 10+ minutes to 60+ minutes. All OpenVINO functions take an order of magnitude longer in our project’s environment. We have run the same functions + models in a separate C project to sanity-check our implementation and the runtime performed as expected (initialization < 5-10 seconds). We are unsure how to root-cause the runtime issues.

This project is Intel internal. We can provide steps to reproduce the issue and additional information within Intel internally. 

Thank you for your help.

**Comment by ilya-lavrenov** [comment]
Could you please create a jira ticket on me then? 
We have other customers of C API and they don't complain about such issue.. looks quite strange.

**Comment by riverlijunjie** [comment]
There is no such terrible initialization/loading issue if run a separated OpenVINO C sample. But I cannot success to the customer project application to reproduce it in my Windows machine.

**Comment by riverlijunjie** [comment]
![image](https://user-images.githubusercontent.com/31196718/181664172-d9857716-7539-43b6-9e24-118f42ff0f32.png)

**Comment by jgespino** [comment]
@mmonares @riverlijunjie Please open an internal ticket, send me an email if you have any questions.

**Comment by riverlijunjie** [comment]
@jgespino a jira ticket has been created: https://jira.devtools.intel.com/browse/CVS-89506
@mmonares this issue only reproduced in your application, do you have any new update?
