### ISSUE TITLE
[Bug]OpenVINO do NOT support fake_quantize_moving_average_abs_max operator

### ISSUE THREAD

**Issue by dlod-openvino** [openvinotoolkit/openvino#12334]
##### System information (version)
- OpenVINO => 2022.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Python 3.8
- Problem classification: Model Compilation
- Framework: PaddlePaddle
- Model name: YOLOv5s

##### Detailed description

![54304111b9ebe5cefc510a0372eb8db](https://user-images.githubusercontent.com/59691336/181394738-931121bd-2c8b-4687-ab8a-a5d22f774864.png)

##### Steps to reproduce
Step1: Download the PaddlePaddle version pre-trained YOLOv5s model
link：https://pan.baidu.com/s/1Zs80Ps5sRIg96Awpb2Z9TQ?pwd=9ftg 
psw：9ftg 

Step2: Use the sample code to compile the model
```python
from openvino.runtime import Core

model_path = "./model.pdmodel"
core = Core()
yolov5 = core.compile_model(model=model_path, device_name="CPU")

print(yolov5.input)
```
You will get the error:
> super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Check 'creator_it != CREATORS_MAP.end()' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\frontends\paddle\src\frontend.cpp:40:
FrontEnd API failed with OpConversionFailure: :
No creator found for fake_quantize_moving_average_abs_max node.

**Comment by Iffa-Meah** [comment]
@dlod-openvino could you share your model through other alternatives? perhaps through my email or direct link download.
I don't have Baidu access and I don't have that software installed in my env (all Baidu installation involves Chinese characters which I'm afraid not my expertise).

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
