### ISSUE TITLE
[RuntimeError] Supported primitive descriptors list is empty for node when using sample pre-trained face-detection model

### ISSUE THREAD

**Issue by shankyb9** [openvinotoolkit/openvino#12359]
**System:**
Intel Xeon CPU E5-2620 v4, 16GB RAM, Windows Server 2016

**OpenVino Version:** 
2020.4

**Model Name:**
face-detection-0105 : tried all variants - FP16, FP32, INT8

**Error:**
Traceback (most recent call last):
  File "face_detection.py", line 233, in <module>
    sys.exit(main() or 0)
  File "face_detection.py", line 79, in main
    exec_net = ie.load_network(network=net, num_requests=2, device_name=args.device)
  File "ie_api.pyx", line 314, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 323, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Supported primitive descriptors list is empty for node: 381/variance/Fused_Add_

Can someone please help me in resolving this?

**Comment by jgespino** [comment]
@shankyb9  Could you share the steps or link where you obtained the face-detection-0105 model? Just want to make sure you are using the model version that matches your openvino release version.

https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-0105/FP16/face-detection-0105.xml
https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-0105/FP16/face-detection-0105.bin

Also, you are using a really old OpenVINO Release, is it possible for you to update your OpenVINO version to the latest release (2022.1) or the latest LTS release (2021.4.2)?

**Comment by shankyb9** [comment]
Hey @jgespino I have installed the models using downloader.py available post openvino installation inside 'C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\tools\model_downloader' folder.

I was using Openvino - 2020.4
Thanks, I'll try out using both versions you specified and update you regarding the status

Thanks for your reply!

**Comment by shankyb9** [comment]
Hey @jgespino Thanks for your support. The issue is resolved using LTS release (2021.4.2) along with some script changes. Was facing issues in other versions. Thanks again!
