### ISSUE TITLE
openvino model conversion issue 

### ISSUE THREAD

**Issue by shankarjadhav232** [openvinotoolkit/openvino#12398]
# System information

- OpenVINO => 2022.1
- Operating System / Platform =>Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz/ Windows 64 Bit
- Problem: labels not detected after Model Conversion 
- labels=['mango' ,'apple' , 'milk' , 'orange' ,'omelete']
- yolo model version =yolov5

issue:-
I have model train using Yolov5 with 6 labels. And then converted it using openvino 2022.1  After that when I did the testing with converted model (.xml, .bin) files using video and images in result  2 lables completely not detected out of 6 labels but same testing did with original yolov5 trained  model then  all labels detected properly. so please suggest what can i do for this issue.

**Comment by jgespino** [comment]
@shankarjadhav232 Could you please provide steps to reproduce including model, model optimizer command, input test image, expected output and code?

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
