### ISSUE TITLE
How to traverse a tensor?

### ISSUE THREAD

**Issue by Asthestarsfalll** [openvinotoolkit/openvino#12431]
Hi,
What can I do if I want to traverse a tensor? 
I find that  `Loop` or `TensorIterator` may help me.
But It's hard to me to figure out how do they work through the opsets docs.
I've tried to read the related codes, but they confused me more.

So can you give me an explanation or a code example?
Thanks in advance for your help.

**Comment by jgespino** [comment]
@Asthestarsfalll Do you have an issue specific to OpenVINO? Could you please provide additional information and link to the documentation you are following?
