### ISSUE TITLE
[Bug]when openvino loading one paddlepaddle-model, the exception ocurrs!

### ISSUE THREAD

**Issue by danve-fan** [openvinotoolkit/openvino#12443]
##### System information (version)
- OpenVINO => 2022.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: Model Loading
- Framework: PaddlePaddle
- Model name: mot_ppyoloe_l_36e_pipeline
-->

The problems:
when openvino loading one paddlepaddle-model, the exception ocurrs as follows:
RuntimeError: Check 'creator_it != CREATORS_MAP.end()' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\frontends\paddle\src\frontend.cpp:40:
FrontEnd API failed with OpConversionFailure: :
No creator found for swish node.

**Comment by danve-fan** [comment]
and the model can be download from page:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/pphuman/README_en.md

**Comment by zulkifli-halim** [comment]
Hi @danve-fan. As of now, PP-YOLOE model is not yet supported by OpenVINO. These are the list of supported PaddlePaddle models by OpenVINO:

- Detection (YoloV3, PPYolo, SSD-MobileNetV3), 
- Classification (Resnet-50, MobileNet-v2, MobileNet-V3), 
- Semantic Segmentation (BiSeNetV2, DeepLabV3p, FastSCNN, OCRNet, U-Net), OCR (PPOCR), and NLP (BERT). 

You can refer to [release note](https://docs.openvino.ai/latest/openvino_docs_IE_DG_Samples_Overview.html) for more detail.

For your information, Intel has pretrained PaddlePaddle models in Open Model Zoo. Here are the list of the models:
- [ocrnet-hrnet-w48-paddle](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/ocrnet-hrnet-w48-paddle)
- [mobilenet-v3-large-1.0-224-paddle](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mobilenet-v3-large-1.0-224-paddle)
- [mobilenet-v3-small-1.0-224-paddle](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mobilenet-v3-small-1.0-224-paddle)

**Comment by danve-fan** [comment]
> Hi @danve-fan. As of now, PP-YOLOE model is not yet supported by OpenVINO. These are the list of supported PaddlePaddle models by OpenVINO:
> 
> * Detection (YoloV3, PPYolo, SSD-MobileNetV3),
> * Classification (Resnet-50, MobileNet-v2, MobileNet-V3),
> * Semantic Segmentation (BiSeNetV2, DeepLabV3p, FastSCNN, OCRNet, U-Net), OCR (PPOCR), and NLP (BERT).
> 
> You can refer to [release note](https://docs.openvino.ai/latest/openvino_docs_IE_DG_Samples_Overview.html) for more detail.
> 
> For your information, Intel has pretrained PaddlePaddle models in Open Model Zoo. Here are the list of the models:
> 
> * [ocrnet-hrnet-w48-paddle](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/ocrnet-hrnet-w48-paddle)
> * [mobilenet-v3-large-1.0-224-paddle](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mobilenet-v3-large-1.0-224-paddle)
> * [mobilenet-v3-small-1.0-224-paddle](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mobilenet-v3-small-1.0-224-paddle)

thanks， I"ll try it!

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to reopen the thread if further assistance is needed.
