### ISSUE TITLE
How to read a OpenviNO IR bin file into ov::runtime::Tensor？

### ISSUE THREAD

**Issue by shiwenloong** [openvinotoolkit/openvino#12458]
I want to use the API:
```cpp
std::shared_ptr<ov::Function> Core::read_model(const std::string& model, const ov::runtime::Tensor& weights)
```
I can read the IR xml file into the model string. How to read the IR bin file into ov::runtime::Tensor?

**Comment by ilya-lavrenov** [comment]
Hi,

1. Understand the file size
2. Create u8 tensor with file size as a size e.g. `ov::Shape size { fileSize };`
3. Read from file to tensor

But why do you want to use this API? If you have files, it's more convenient to provide files to `load_model`.
Tensor and string are necessary if you have decrypted model in memory https://docs.openvino.ai/latest/openvino_docs_OV_UG_protecting_model_guide.html

**Comment by shiwenloong** [comment]
> Hi,
> 
> 1. Understand the file size
> 2. Create u8 tensor with file size as a size e.g. `ov::Shape size { fileSize };`
> 3. Read from file to tensor
> 
> But why do you want to use this API? If you have files, it's more convenient to provide files to `load_model`. Tensor and string are necessary if you have decrypted model in memory https://docs.openvino.ai/latest/openvino_docs_OV_UG_protecting_model_guide.html

Thanks. I use this API because I want to read decrypted model in memory.

**Comment by shiwenloong** [comment]
The problem is solved.
