### ISSUE TITLE
avx_vnni support on OpenVINO?

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino#12468]
I believe it comes with Gen 12 CPUs, and now AVX-512 is missing? Would we be porting to the AVX_VNNI? What is the best configuration to get best CPU performance on Gen12+OpenVINO?

**Comment by dmitry-gorokhov** [comment]
Hi @raymondlo84. OpenVINO supports ADL (and AVX-VNNI as a consequence) starting from 2022.1 release. New HW capabilities are utilized by default: no additional steps from a user is required. 
What do you mean by "configuration" here?
