### ISSUE TITLE
Node input index is out of range (arm64)

### ISSUE THREAD

**Issue by MdScntst** [openvinotoolkit/openvino#12476]
I am running the same code on x64 (Ubuntu 20.06) and arm64 platform (Rockchip rk3399, Ubuntu 20.04).
Code compiled on x64 works as expected, on arm64 I am getting error msg: node input index is out of range!
Samples on arm64 platform works well.
Code to reproduce, IR, onnx are included.

[error.zip](https://github.com/openvinotoolkit/openvino/files/9289353/error.zip)

**Comment by Iffa-Meah** [comment]
@MdScntst in order to use OpenVINO with ARM CPU, you need this OpenVINO ARM CPU plugin.

 This plugin is developed specific to enable deep neural networks inference on ARM CPUs, using OpenVINO API. 

You'll need to build it in your ARM environment. You may refer [here](https://github.com/openvinotoolkit/openvino_contrib/blob/master/modules/arm_plugin/README.md) for more detailed information.

**Comment by MdScntst** [comment]
@Iffa-Meah ,  thank you for your response. I've successfully built openvino with openvino contrib lib, arm cpu is recognized by inference engine, I`ve also successfully run hello_classification sample from arm plugin samples. Checked for limitations, specified [here](https://github.com/openvinotoolkit/openvino_contrib/wiki/ARM-plugin-operation-set-specification), only group GroupConvolution looks suspicious.

**Comment by Iffa-Meah** [comment]
@MdScntst usually, for example in PyTorch, let's say if the network output is 1-dimensional and we try to index it at position node=1 we’re going to get an out-of-bounds error which correlates to node input index is out of range. Perhaps you need to narrow down to which index of your model's node is out of range and maybe that will pinpoint the cause of the issue.

**Comment by MdScntst** [comment]
@Iffa-Meah Is there an easy way to do this? Also I would like to remind you, that the same IR model runs fine on x86-64

**Comment by Iffa-Meah** [comment]
@MdScntst I checked your model on both Ubuntu and arm environment.

The inferencing in Ubuntu works for both native ONNX and FP16
Native ONNX
<img width="456" alt="CPU_ubuntu" src="https://user-images.githubusercontent.com/79643476/184053523-ee86bdcf-ac44-4eb7-8b04-f7302c54df2d.png">

FP16
<img width="457" alt="FP16cpu_ubuntu" src="https://user-images.githubusercontent.com/79643476/184053545-5039b60d-1e7c-4550-b3de-0bfb4a1195ef.png">

However, when I tried to validate your model in arm environment (Raspberry Pi) for testing purpose, it doesn't work even on MYRIAD

Native ONNX
<img width="356" alt="12476_onnxPI" src="https://user-images.githubusercontent.com/79643476/184053676-28407845-92fc-43ba-80fd-c7340a7a13f6.png">

FP16
<img width="359" alt="12476_FP16pi" src="https://user-images.githubusercontent.com/79643476/184053696-31893bdb-4b8b-49bd-a6ad-3f2850091c8c.png">

We'll further investigate this and get back to you with the possible workaround asap.

**Comment by MdScntst** [comment]
@Iffa-Meah , I've investigated two models that fails on ARM platform, using onnx-gpaphsurgeon I've removed node by node untill model run without the error message, and it seems to be a problem with nodes with Resize op. I'm  trying to find some workaround, but if you have some suggestions, I kindly ask to share.

**Comment by MdScntst** [comment]
May be this will help
![IR_NODE](https://user-images.githubusercontent.com/36072671/184910034-2c66e089-a7b1-445c-b26b-992547aa6cef.jpg)
![ONNX_NODE](https://user-images.githubusercontent.com/36072671/184910071-9e2f8e43-0083-4f29-bc28-246981463be0.jpg)

**Comment by ilya-lavrenov** [comment]
@alvoron can we have a look?

**Comment by MdScntst** [comment]
I kinda solved "Node input index is out of range" error on arm platform: it seems that Resize node fails with some values of coordinate_transformation_mode attribute. For two different detectors I've got different results.

Yolov5-face:
asymmetric (generated by torch onnx) - fail (out of range)
half_pixel - ok
pytorch_half_pixel - ok
align_corners - ok
tf_half_pixel_for_nn - ok
tf_crop_and_resize - not supported;

Palm detection:
asymmetric - fail (out of range)
half_pixel - fail (out of range)
pytorch_half_pixel - ok
align_corners - fail (out of range)
tf_half_pixel_for_nn - ok
tf_crop_and_resize - not supported;

**Comment by MdScntst** [comment]
Hello! I've finally sloved this problem: IR model perfectly work if converted with --use_legacy_frontend flag, without any changes of resize coordinate_transformation_mode attribute. We can close this issue.

**Comment by ilya-lavrenov** [comment]
> Hello! I've finally sloved this problem: IR model perfectly work if converted with --use_legacy_frontend flag, without any changes of resize coordinate_transformation_mode attribute. We can close this issue.

CC @tomdol
