### ISSUE TITLE
Offload a sub-graph of operations to Tensorflow

### ISSUE THREAD

**Issue by mrinmayk** [openvinotoolkit/openvino#125]
Hello,

I am trying to generate .xml/.bin for a .pb file containing graph as per MO_FAQ.html point 97.

This is a SSD MobileNet model, similar to as mentioned here - https://software.intel.com/en-us/forums/computer-vision/topic/777945

What values do I input in the first command - 
python3 mo.py --input_model model/frozen_inference_graph.pb  --tensorflow_subgraph_pattern ""FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/FusedBatchNorm, FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Relu6, FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise, FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/BatchNorm/FusedBatchNorm, FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_1_depthwise/Relu6,..

Which nodes do I put above to offload a sub-graph of operations?

Thanks!

**Comment by shubha-ramani** [comment]
Dear @mrinmayk 

First may I ask why you feel that you need to offload a sub-graph of operations ? Is it that some Tensorflow operations are not supported ? The Intel Developer Zone url you mentioned above mentions graph cycles as the culprit. As far as which nodes to feed into the --tensorflow_subgraph_patterns argument, there is no one answer that fits all. 
[offloading tf subgraph](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html)

Did you obtain your SSD Mobilenet model from the [supported list](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html) and try mo_tf.py from OpenVino 2019 R1 ?

Looking forward to your response,

Shubha

**Comment by mrinmayk** [comment]
@shubha-ramani From your supported list; I downloaded SSD Mobilenet 300X300 v1 but could not run it. The instructions to run it said 
./ssd_... <arg1> <arg2> 
but the actual package just has a .cpp, .h, cMakeLists.txt and ReadMe.md

**Comment by shubha-ramani** [comment]
Dear @mrinmayk 
In general you shouldn't have to offload subgraphs to Tensorflow to get IR successfully from an ssd mobile net model. Please see my reply to your previous github post:

[https://github.com/opencv/dldt/issues/126](https://github.com/opencv/dldt/issues/126)

Thanks for using OpenVino !

Shubha

**Comment by mrinmayk** [comment]
Hello,

I downloaded a ssd mobilenet v1 from your supported list above and managed to generate a .xml and .bin

But when I use the code to get detections, I get error as -
face_net = IENetwork.from_ir(model=face_xml, weights=face_bin)
  File "ie_api.pyx", line 113, in inference_engine.ie_api.IENetwork.from_ir
  File "ie_api.pyx", line 236, in inference_engine.ie_api.IENetReader.read
**RuntimeError: Error reading network: cannot parse future versions: 5**
as I am using 2018.2.300

On the 2019 version, after setting all dependencies and running, I get 
DeprecationWarning: from_ir() method of IENetwork is deprecated. Please use IENetwork class constructor to create valid IENetwork instance
face_net = IENetwork.from_ir(model=face_xml, weights=face_bin)

I managed to run a demo which compiled correctly but closed since I am not using live video **but I am interested in running my own files** 

Please don't forward to anyone which won't solve my matter unless the code to generate predictions for the above xml is present.

**Comment by shubha-ramani** [comment]
Dear @mrinmayk 

Congrats on generating IR ! That's great news !

If you follow instructions to build IE here [https://github.com/opencv/dldt/blob/2018/inference-engine/README.md](https://github.com/opencv/dldt/blob/2018/inference-engine/README.md) you will find executables under dldt\inference-engine\bin\intel64\Debug<Release> which you can run from an Ubuntu terminal.

Thanks,

Shubha

**Comment by mrinmayk** [comment]
DLDT, KINDLY CHECK

/Downloads/dldt-2018/inference-engine$ cmake -DCMAKE_BUILD_TYPE=Release-- BUILD_CONFIGURATION: Release
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
-- GEMM should be set to MKL, OPENBLAS or JIT. Default option is JIT
-- THREADING should be set to TBB, OMP or SEQ. Default option is OMP
-- INTEL_VTUNE_DIR is not defined
-- Could NOT find INTEL_ITT (missing:  Located_ITT_INCLUDE_DIRS Located_ITT_LIBS) 
-- INTEL_ITT is disabled
-- Detected 64 bit architecture
-- CI_BUILD_NUMBER: custom_HEAD_HEAD
-- ENABLE_GNA = ON
-- ENABLE_MKL_DNN = ON
-- ENABLE_CLDNN = ON
-- ENABLE_PROFILING_ITT = ON
-- ENABLE_PROFILING_RAW = OFF
-- GEMM = JIT
-- THREADING = OMP
-- IE_DEBUG_POSTFIX = 
-- IE_RELEASE_POSTFIX = 
-- ENABLE_TESTS = OFF
-- ENABLE_GAPI_TESTS = OFF
-- GAPI_TEST_PERF = OFF
-- ENABLE_SAMPLES_CORE = ON
-- ENABLE_SANITIZER = OFF
-- COVERAGE = OFF
-- ENABLE_STRESS_UNIT_TESTS = OFF
-- VERBOSE_BUILD = OFF
-- ENABLE_UNSAFE_LOCATIONS = OFF
-- ENABLE_ALTERNATIVE_TEMP = ON
-- ENABLE_SEGMENTATION_TESTS = ON
-- ENABLE_OBJECT_DETECTION_TESTS = ON
-- ENABLE_OPENCV = ON
-- OS_FOLDER = OFF
-- ENABLE_PLUGIN_RPATH = ON
-- ENABLE_AFFINITY_GENERATOR = OFF
-- ENABLE_DEBUG_SYMBOLS = OFF
-- ENABLE_PYTHON = OFF
-- DL_SDK_TEMP envionment not set
-- PROJECT ............................... InferenceEngine
-- CMAKE_BINARY_DIR ...................... /home/facialstats/Downloads/dldt-2018/inference-engine
-- IE_MAIN_SOURCE_DIR .................... /home/facialstats/Downloads/dldt-2018/inference-engine
-- CMAKE_GENERATOR ....................... Unix Makefiles
-- CMAKE_C_COMPILER_ID ................... GNU
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
configuring file: /home/facialstats/Downloads/dldt-2018/inference-engine/test_model_repo.h
CMake Warning at tests/unit/opencv_test_gapi/CMakeLists.txt:6 (message):
  Skipping GAPI unit tests


CMake Error at thirdparty/ade/CMakeLists.txt:10 (add_subdirectory):
  add_subdirectory given source "pugixml" which is not an existing directory.


CMake Error at thirdparty/ade/CMakeLists.txt:11 (add_subdirectory):
  add_subdirectory given source "stb_lib" which is not an existing directory.


CMake Error at thirdparty/ade/CMakeLists.txt:12 (add_subdirectory):
  add_subdirectory given source "ade" which is not an existing directory.


CMake Error at thirdparty/ade/CMakeLists.txt:26 (add_subdirectory):
  add_subdirectory given source "clDNN" which is not an existing directory.


You have called ADD_LIBRARY for library mkldnn without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at thirdparty/ade/CMakeLists.txt:34 (add_subdirectory):
  add_subdirectory not given a binary directory but the given source
  directory
  "/home/facialstats/Downloads/dldt-2018/inference-engine/thirdparty/fluid/modules/gapi"
  is not a subdirectory of
  "/home/facialstats/Downloads/dldt-2018/inference-engine/thirdparty/ade".
  When specifying an out-of-tree source a binary directory must be explicitly
  specified.


-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.12", minimum required is "2.7") 
-- [clDNN] ======================== clDNN Project =======================
-- [clDNN] Version:          1.4.14.0
-- [clDNN]
-- [clDNN] Build type:       Release (for single-configuration generators)
-- [clDNN] Av. build types:  Debug;Release (for multi-configuration generators)
-- [clDNN]
-- [clDNN] Output bin directory:
-- [clDNN]  - "/home/facialstats/Downloads/dldt-2018/inference-engine/bin/intel64/Release/lib"
-- [clDNN] Output lib directory:
-- [clDNN]  - "/home/facialstats/Downloads/dldt-2018/inference-engine/bin/intel64/Release/lib"
-- [clDNN] Architecture:
-- [clDNN]  - target: Linux64    (detected: Linux64)
-- [clDNN]
-- [clDNN]
-- [clDNN] Advanced:
-- [clDNN]  - ICD version used to build:     6.3
-- [clDNN]
-- [clDNN]  - Include/Build cldnn core:      ON
-- [clDNN]  - Include/Build kernel selector: ON
-- [clDNN]  - Include/Build tests:           OFF
-- [clDNN]  - Include/Build tutorial:        OFF
-- [clDNN]
-- [clDNN]  - Run tests:                     OFF
-- [clDNN]
-- [clDNN]  - Use static C++ Runtime:        OFF
-- [clDNN]  - Allow unsafe size opts:        ON
-- [clDNN]  - CMake debug trace:             OFF
-- [clDNN]
-- [clDNN]
-- [clDNN] ICD:
-- [clDNN]  - Root:            /home/facialstats/Downloads/dldt-2018/inference-engine/thirdparty/clDNN/common/intel_ocl_icd/6.3
-- [clDNN]     + Headers:      /home/facialstats/Downloads/dldt-2018/inference-engine/thirdparty/clDNN/common/intel_ocl_icd/6.3/linux/include
-- [clDNN]     + Static libs:  /home/facialstats/Downloads/dldt-2018/inference-engine/thirdparty/clDNN/common/intel_ocl_icd/6.3/linux/Release/lib/x64
-- [clDNN]     + Shared libs:  /home/facialstats/Downloads/dldt-2018/inference-engine/thirdparty/clDNN/common/intel_ocl_icd/6.3/linux/Release/bin/x64
-- [clDNN]     + Libs to link: /home/facialstats/Downloads/dldt-2018/inference-engine/thirdparty/clDNN/common/intel_ocl_icd/6.3/linux/Release/bin/x64
-- [clDNN] =============================================================================
-- [clDNN] Selected capabilities: public
CMake Error at thirdparty/mkldnn.cmake:91 (add_library):
  add_library cannot create target "mkldnn" because another target with the
  same name already exists.  The existing target is a static library created
  in source directory
  "/home/facialstats/Downloads/dldt-2018/inference-engine/thirdparty/ade".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  thirdparty/CMakeLists.txt:31 (include)


CMake Error at cmake/ie_parallel.cmake:93 (target_link_libraries):
  Attempt to add link library
  "/home/facialstats/Downloads/dldt-2018/inference-engine/temp/omp/lib/libiomp5.so"
  to target "mkldnn" which is not built in this directory.
Call Stack (most recent call first):
  thirdparty/mkldnn.cmake:92 (set_ie_threading_interface_for)
  thirdparty/CMakeLists.txt:31 (include)


CMake Error at thirdparty/fluid/modules/gapi/cmake/standalone.cmake:2 (find_package):
  By not providing "Findade.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ade", but
  CMake did not find one.

  Could not find a package configuration file provided by "ade" (requested
  version 0.1.0) with any of the following names:

    adeConfig.cmake
    ade-config.cmake

  Add the installation prefix of "ade" to CMAKE_PREFIX_PATH or set "ade_DIR"
  to a directory containing one of the above files.  If "ade" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  thirdparty/fluid/modules/gapi/CMakeLists.txt:4 (include)


-- Configuring incomplete, errors occurred!
See also "/home/facialstats/Downloads/dldt-2018/inference-engine/CMakeFiles/CMakeOutput.log".
See also "/home/facialstats/Downloads/dldt-2018/inference-engine/CMakeFiles/CMakeError.log".

**Comment by shubha-ramani** [comment]
Dear @mrinmayk ,
Please do the following:
1) delete everything under inference-engine/build
2) Set OpenCV_DIR="" (basically set the OpenCV_DIR environment variable to an empty string)
3) Make sure that the wget executable **and it's dependencies** are in your PATH
4) Start from scratch (run the cmake command from the README)
5) Build (make -j16 on Ubuntu)

Those steps should work for you. Thanks for using OpenVino !

Shubha

**Comment by mrinmayk** [comment]
Dear @shubha-ramani, Which/what wget executable are you referring to here?

**Comment by shubha-ramani** [comment]
@mrinmayk 
The wget I'm referring to is this one:
[https://launchpad.net/ubuntu/xenial/+source/wget](https://launchpad.net/ubuntu/xenial/+source/wget)

**Comment by mrinmayk** [comment]
@shubha-ramani And what would I want to download with wget? I do not see any external web link in your README instructions?

**Comment by mrinmayk** [comment]
@shubha-ramani Okay got it, you are referring to the ssd net itself.

**Comment by mrinmayk** [comment]
@shubha-ramani Are there any openings in your team that you can refer me to or to Intel Canada?

**Comment by mrinmayk** [comment]
I can be reached at mrinmay235@yahoo.com

**Comment by lazarevevgeny** [comment]
The "--tensorflow_subgraph_patterns" had been deprecated and removed from the product. Closing the issue.
