### ISSUE TITLE
How to set the memory type of inference results ?

### ISSUE THREAD

**Issue by Kizna1ver** [openvinotoolkit/openvino#12548]
If I load the model and do inference on Intel integrated GPU like va surface memory, how can I get output tensors on GPU memory? I tried some codes, and it seems that the result tensor obtained by infer_request.get_tensor("output_tensor_name") is a ordinary Tensor, not a VASurfaceTensor.

**Comment by ilya-lavrenov** [comment]
Hi @Kizna1ver,

You need to create explicitly such tensor and set it via `infer_request.set_tensor("output_tensor_name", remote_tensor);`
I suppose we cannot use VA tensor as output one, but you can create `ClBufferTensor`, or more easily - get default remote context for your device via `Core::get_default_content("device_name.ID")` and call `create_tensor` with shape and element type, then pass this tensor as output one

**Comment by Kizna1ver** [comment]
Hi @ilya-lavrenov, thanks for reply.

Does this mean that we can't make the input and output both VASurfaceTensor currently?

**Comment by ilya-lavrenov** [comment]
Yes, only input.
And for this we need to to use a special API to denote that GPU plugin should expect VASurface.
See https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_GPU.html#preprocessing-acceleration:
```c++

using namespace ov::preprocess;
auto p = PrePostProcessor(model);
p.input().tensor().set_memory_type(ov::intel_gpu::memory_type::surface);
auto model_with_preproc = p.build();
```
So, based on this preprocessing information plugin will convert VASurface to OpenCL buffer internally

**Comment by Kizna1ver** [comment]
Got it, thx.

**Comment by Kizna1ver** [comment]
Hi @ilya-lavrenov , still hava a question. Does the model support input from a single Y channel on the VASurface? 
I have a Super-resolution model which input shape is [1,1,960,540], and this input is Y channel. I tried some code like this:
    
    auto model = core.read_model("srmodel.xml");
    auto p = PrePostProcessor(model);
    p.input().tensor().set_element_type(ov::element::u8)
                    .set_color_format(ov::preprocess::ColorFormat::UNDEFINED)
                    .set_memory_type(ov::intel_gpu::memory_type::surface); 
    p.input().model().set_layout("NCHW");
    model = p.build();
    // some code to get VAContext and surface_id
    auto nv12_blob = shared_va_context.create_tensor_nv12(input_height, input_width, surface_id);
    infer_request.set_tensor("model_input_name", nv12_blob.first);
    infer_request.infer();

But it raised this error when inference:

    terminate called after throwing an instance of 'ov::Exception'
    what():  trying to reinterpret image buffer as non-image buffer : nv12 --> bfyx
    Aborted (core dumped)
