### ISSUE TITLE
build openvino 2022.1.1 with centos 7.9

### ISSUE THREAD

**Issue by ViokingTung** [openvinotoolkit/openvino#12549]
##### System information (version)

- OpenVINO == 2022.1.1
- Operating System / Platform == CentOS Linux release 7.9.2009 (Core) Linux 5.4.199-1.el7.elrepo.x86_64
- cmake version 3.23.2
- gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
- Python 3.9.1

##### Detailed description

I build by follow steps:

```shell
git clone https://github.com/openvinotoolkit/openvino.git

cd openvino

git submodule update --init --recursive

chmod +x install_build_dependencies.sh
./install_build_dependencies.sh

conda create -n openvino-build python==3.9
conda activate openvino-build
pip install -r ./src/bindings/python/src/compatibility/openvino/requirements-dev.txt

mkdir build && cd build

cmake -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=~/miniconda3/envs/openvino-build/bin/python3.9 -DPYTHON_LIBRARY=~/miniconda3/envs/openvino-build/lib/libpython3.9.so -DPYTHON_INCLUDE_DIR=~/miniconda3/envs/openvino-build/include -DENABLE_WHEEL=ON -DENABLE_INTEL_CPU=ON -DENABLE_OV_ONNX_FRONTEND=ON -DENABLE_INTEL_GPU=OFF -DCMAKE_BUILD_TYPE=Release ..

make --jobs=$(nproc --all)

```

then catch errors:

```
In file included from /root/openvino/src/core/include/ngraph/pass/manager.hpp:12:0,
                 from /root/openvino/src/common/legacy/src/cnn_network_impl.cpp:17:
/root/openvino/src/core/include/ngraph/pass/pass.hpp:51:1: error: type attributes ignored after type is already defined [-Werror=attributes]
 };
 ^
[ 41%] Building CXX object thirdparty/protobuf/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/descriptor.pb.cc.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/common/CMakeFiles/dnnl_common.dir/lrn.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/common/CMakeFiles/dnnl_common.dir/matmul.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/common/CMakeFiles/dnnl_common.dir/memory.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/cpu/x64/CMakeFiles/dnnl_cpu_x64.dir/cpu_isa_traits.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/common/CMakeFiles/dnnl_common.dir/memory_debug.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/cpu/CMakeFiles/dnnl_cpu.dir/binary_injector_utils.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/common/CMakeFiles/dnnl_common.dir/memory_desc_wrapper.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/cpu/CMakeFiles/dnnl_cpu.dir/cpu_batch_normalization_list.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/common/CMakeFiles/dnnl_common.dir/memory_storage.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/cpu/x64/CMakeFiles/dnnl_cpu_x64.dir/cpu_reducer.cpp.o
[ 41%] Building CXX object src/plugins/intel_cpu/thirdparty/mkl-dnn/src/common/CMakeFiles/dnnl_common.dir/memory_tracking.cpp.o
cc1plus: all warnings being treated as errors
make[2]: *** [src/common/legacy/CMakeFiles/inference_engine_legacy_obj.dir/src/cnn_network_impl.cpp.o] Error 1
make[1]: *** [src/common/legacy/CMakeFiles/inference_engine_legacy_obj.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

...

[ 53%] Built target dnnl_cpu_x64
make: *** [all] Error 2
```

have any suggestions? thanks.

**Comment by ilya-lavrenov** [comment]
Could you please the attached instruction?
[Build OpenVINO with CMake 3.18.4 Python 3.6 and devtoolset-8 on CentOS 7 Guide.docx](https://github.com/openvinotoolkit/openvino/files/9333385/Build.OpenVINO.with.CMake.3.18.4.Python.3.6.and.devtoolset-8.on.CentOS.7.Guide.docx)
We are going to add it to OpenVINO Wiki soon.

**Comment by ViokingTung** [comment]
> Could you please the attached instruction? [Build OpenVINO with CMake 3.18.4 Python 3.6 and devtoolset-8 on CentOS 7 Guide.docx](https://github.com/openvinotoolkit/openvino/files/9333385/Build.OpenVINO.with.CMake.3.18.4.Python.3.6.and.devtoolset-8.on.CentOS.7.Guide.docx) We are going to add it to OpenVINO Wiki soon.


I'm so sorry for wasting your time, I just found some mistakes while wrote my installed instruction,I set the wrong parameter DPYTHON_INCLUDE_DIR and got confused when trying different cmake versions , I build again it success, I plan to testing the built openvino tomorrow and upload my installed document if work well, thanks.

**Comment by ilya-lavrenov** [comment]
> > Could you please the attached instruction? [Build OpenVINO with CMake 3.18.4 Python 3.6 and devtoolset-8 on CentOS 7 Guide.docx](https://github.com/openvinotoolkit/openvino/files/9333385/Build.OpenVINO.with.CMake.3.18.4.Python.3.6.and.devtoolset-8.on.CentOS.7.Guide.docx) We are going to add it to OpenVINO Wiki soon.
> 
> I'm so sorry for wasting your time, I just found some mistakes while wrote my installed instruction,I set the wrong parameter DPYTHON_INCLUDE_DIR and got confused when trying different cmake versions , I build again it success, I plan to testing the built openvino tomorrow and upload my installed document if work well, thanks.

Ok, thanks. It would be nice if we have your feedback on our instruction so we can publish it soon if you don't have any comments.

**Comment by ViokingTung** [comment]
> > > Could you please the attached instruction? [Build OpenVINO with CMake 3.18.4 Python 3.6 and devtoolset-8 on CentOS 7 Guide.docx](https://github.com/openvinotoolkit/openvino/files/9333385/Build.OpenVINO.with.CMake.3.18.4.Python.3.6.and.devtoolset-8.on.CentOS.7.Guide.docx) We are going to add it to OpenVINO Wiki soon.
> > 
> > 
> > I'm so sorry for wasting your time, I just found some mistakes while wrote my installed instruction,I set the wrong parameter DPYTHON_INCLUDE_DIR and got confused when trying different cmake versions , I build again it success, I plan to testing the built openvino tomorrow and upload my installed document if work well, thanks.
> 
> Ok, thanks. It would be nice if we have your feedback on our instruction so we can publish it soon if you don't have any comments.

this is my build instruction.
[Build OpenVINO 2022.1 with CMake 3.23.2 Python 3.9.0 and GCC 8.3.1 on CentOS 7.9 Guide.pdf](https://github.com/openvinotoolkit/openvino/files/9334854/Build.OpenVINO.2022.1.with.CMake.3.23.2.Python.3.9.0.and.GCC.8.3.1.on.CentOS.7.9.Guide.pdf)
