### ISSUE TITLE
[Bug] Model Optimizer - Could you please let me know the difference between data type FPS16 and FLOAT, FPS8 and HALF ?

### ISSUE THREAD

**Issue by MiraGaikwad** [openvinotoolkit/openvino#12569]
##### System information (version)

- OpenVINO => 2022
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
- Problem classification: Model OPTIMISER
- Framework: TensorFlow 
- Model name: ResNet50 

Could you please let me know the difference between data type FPS16 and FLOAT, FPS8 and HALF ?

python mo_tf.py -**_-data_type FP16 -_**-input_model tf_model.pb --model_name IR_model --output_dir IR_model_bkp/ --input_shape [1,224,224,3]

**Comment by andrei-kochin** [comment]
Hello @MiraGaikwad,
Thanks for using OpenVINO!

Actually as also listed in FAQ  [#50](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?highlight=half#what-does-the-message-data-type-is-unsupported-mean) Model Optimizer can compress data to FP16 if specified --data_type FP16 or --data_type Half. So in fact FP32 = float and FP16 = half.

Best regards,
Andrei
