### ISSUE TITLE
Error has occured when inferencing with Intel® Processor Graphics (GPU)

### ISSUE THREAD

**Issue by Greyman-Seu** [openvinotoolkit/openvino#1256]
**env:**
1.window 10
2.CPU:i5-6200U  GPU: HD 520(driver:21.20.16.4526)

**1.Inference successful when running this script** 
`classification_sample_async.exe -i "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\car.png" -m "C:\Users<username>\Documents\Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1\FP16\squeezenet1.1.xml" -d CPU`
**result**
```
Image C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\car.png

classid probability label
------- ----------- -----
817     0.6853030   sports car, sport car
479     0.1835197   car wheel
511     0.0917197   convertible
436     0.0200694   beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon
751     0.0069604   racer, race car, racing car
656     0.0044177   minivan
717     0.0024739   pickup, pickup truck
581     0.0017788   grille, radiator grille
468     0.0013083   cab, hack, taxi, taxicab
661     0.0007443   Model T

[ INFO ] Execution successful

[ INFO ] This sample is an API example, for any performance measurements please use the dedicated benchmark_app tool
```

**2.Fails when running this script with GPU** 
`classification_sample_async.exe -i "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\car.png" -m "C:\Users<username>\Documents\Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1\FP16\squeezenet1.1.xml" -d GPU`
**result**
```
[ INFO ] InferenceEngine:
        API version ............ 2.1
        Build .................. 2020.3.0-3467-15f2c61a-releases/2020/3
        Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\car.png
[ INFO ] Creating Inference Engine
        GPU
        clDNNPlugin version ......... 2.1
        Build ........... 2020.3.0-3467-15f2c61a-releases/2020/3

[ INFO ] Loading network files
[ INFO ] Preparing input blobs
[ WARNING ] Image is resized from (787, 259) to (227, 227)
[ INFO ] Batch size is 1
[ INFO ] Loading model to the device
[ ERROR ] Error has occured for: pooling:pool1
Best_kernel.empty()(true) should be false
Cannot find a proper kernel with this arguments
```

REF(install): https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_installing_openvino_windows_fpga.html#Update-Path

**Comment by jgespino** [comment]
Hi @Greyman-Seu 

From what you described, it appears you have all the software dependencies installed and are successfully running inference on the CPU. The GPU device should work too as the driver version is higher than 15.65 as mentioned in the installation guide. 

Have you tried re-installing the graphics driver or updating it to a newer version? Please give that a try and reboot your system before running the demo. Also, do you see the same issue when running the FP32 version of the model? 

Please note that the install guide you linked above if for Window FPGA devices, please follow the Windows documentation. 
https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_installing_openvino_windows.html

Regards,
Jesus

**Comment by brmarkus** [comment]
Can you run the sample `hello_query_device` and provide the output, to see whether OpenVINO can "see" the GPU as an available device, please?

**Comment by vladimir-paramuzov** [comment]
@Greyman-Seu Could you please check supported opencl extensions and make sure that there are both `cl_intel_subgroups_short` and `cl_intel_subgroups`? I think the possible issue is that the GPU plugin picks b_fs_yx_fsv16 as optimal memory format for squeezenet1.1, and most of the kernels for this format use subgroup extensions. If the driver for some reason doesn't support it, then such kernels might be rejected, and if there's no reference impl that supports this format, you'll get this `Best_kernel.empty()(true) should be false` error.

**Comment by Greyman-Seu** [comment]
> @Greyman-Seu Could you please check supported opencl extensions on your machine and make sure that there are both `cl_intel_subgroups_short` and `cl_intel_subgroups`? I think the possible issue is that the GPU plugin picks b_fs_yx_fsv16 as optimal memory format for squeezenet1.1, and most of the kernels for this format use subgroup extensions. If the driver for some reason doesn't support it, then such kernels might be rejected, and if there's no reference impl that supports this format, you'll get this `Best_kernel.empty()(true) should be false` error.

Thanks for your rely.  This reason of issure may be that the graphics driver which meets the requirements is not installed. And the latest official drivers for  graphics are not installed due to the lack of support from the hardware manufacturer.

**Comment by jgespino** [comment]
Hi @Greyman-Seu Please let us know if you need additional assistance.
