### ISSUE TITLE
[Bug] GPU custom layer config file

### ISSUE THREAD

**Issue by wang7393** [openvinotoolkit/openvino#12598]
##### System information (version)
- OpenVINO=> :2022.1
- Operating System / Platform => :win10
- Problem classification => :  GPU custom layer config file

`core.set_property("GPU", { { CONFIG_KEY(CONFIG_FILE), xmlPath } });`
the xmlPath  with Spaces are not supported.

In addition， as this issue https://github.com/openvinotoolkit/openvino/issues/12377#issue-1324027988
After the application goes live, I want to know how the GPU custom layer configuration files and kernel files can not be exposed to the customer. For example, the model loading interface can load the model from memory, and the model is encrypted beforehand.

**Comment by ilya-lavrenov** [comment]
Hi @wang7393 

> the xmlPath with Spaces are not supported

@p-durandin could your team try to address it?

> For example, the model loading interface can load the model from memory, and the model is encrypted beforehand.

@vladimir-paramuzov should we add a way to add GPU extensions from string? Not from file

**Comment by jgespino** [comment]
@vladimir-paramuzov Created internal ticket 90549 to track feature request for GPU extensions from string.
@p-durandin Created internal ticket 90550 to track feature requests to support XML path with Spaces.

CC: @ilya-lavrenov
