### ISSUE TITLE
Convert Net to VINO

### ISSUE THREAD

**Issue by mrinmayk** [openvinotoolkit/openvino#126]
Hello,

How do I convert  a Net to VINO when both .pb and pbtxt format are used to read the net - which of the two best serves ?

frozen_graph = str("detection/240x180_depth0.75_ssd_mobilenetv1/frozen_inference_graph.pb") text_graph = str("detection/240x180_depth0.75_ssd_mobilenetv1/graph.pbtxt")
cvNet = cv2.dnn.readNetFromTensorflow(frozen_graph, text_graph)

Which of the .pb and pbtxt do I use above?

**Comment by alalek** [comment]
Perhaps you should use "model optimizer" tool - see [here](http://docs.openvinotoolkit.org/2019_R1/index.html).

**Comment by shubha-ramani** [comment]
Dear @mrinmayk 
For ssd mobilenet models this Intel Developer Zone post should help you:
[https://software.intel.com/en-us/forums/computer-vision/topic/806159](https://software.intel.com/en-us/forums/computer-vision/topic/806159)

The answer refers to the R5 version of the documentation, so here is the latest version:
[https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html)

Hope it helps,
Thanks,

Shubha

**Comment by lazarevevgeny** [comment]
@mrinmayk is the issue still actual? Did you manage to solve the problem?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
