### ISSUE TITLE
[Bug] RuntimeError:  cannot estimate element if precision is UNSPECIFIED

### ISSUE THREAD

**Issue by HENNESSYxie** [openvinotoolkit/openvino#12605]
`return CompiledModel(
>           super().compile_model(model, device_name, {} if config is None else config)
>E       RuntimeError:  cannot estimate element if precision is UNSPECIFIED`
I have this error while trying to compile Person-reidentification model on Gitlab CI. I think that config will help me, but I can't find anything allowable fields for config dict.

**Comment by ilya-lavrenov** [comment]
Hi @HENNESSYxie 
Could you please provide more detailed steps how to reproduce the issue? 
We definitely have issue that needs to be addressed.

**Comment by HENNESSYxie** [comment]
Hi @ilya-lavrenov 
I have class that compiles model. I've created a pytest.fixture which returns instance of compiled model. I'm using person-reidentification-retail-0277. After this I'm trying to get outputs of this model by giving him image. On my local machine everything works fine, but on runner I'm getting error that wrote above. Can this happen due to the fact that in one test I compile the detection model, and in another test I already compile the re-identification model and at the same time with compile_device='CPU'. Maybe there is a way to specify that precision is not needed for compiling model.

**Comment by HENNESSYxie** [comment]
To reproduce that:
- Download https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/person-reidentification-retail-0277/README.md
- write test that inferences this model and try to make detections from image
- Run this test on GitLab CI/CD

**Comment by zulkifli-halim** [comment]
Hi @HENNESSYxie, can you share with us the full inference code you used to run the person-reidentification-retail-0277
model?

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to reopen if further assistance is needed.

**Comment by dhruvsinghal** [comment]
In case it helps anyone, I would like to mention that the problem likely has something to do with openvino running in a VM as opposed to on bare metal. I am trying to run https://github.com/bes-dev/stable_diffusion.openvino - it runs fine on bare metal machines on both Windows and Debian, but it fails when run in a Debian VM with the stated error.

This lines up with what @HENNESSYxie said:
> On my local machine everything works fine, but on runner I'm getting error that wrote above.
