### ISSUE TITLE
[Bug] Pad op in in8 can not parsed

### ISSUE THREAD

**Issue by jinfagang** [openvinotoolkit/openvino#12715]
RuntimeError: While validating ONNX node '<Node(Pad): Pad_13>':

![image](https://user-images.githubusercontent.com/21303438/186121267-bda931fc-245c-43bc-81e7-bf6bbe2fab7a.png)

this Pad value can not parsed.

**Comment by andrei-kochin** [comment]
@jinfagang thanks for contacting OpenVINO!

Unfortunately it's hard to start investigating the issue without following information so please provide it to speed-up investigation if possible.

- Could you please share the full MO log?

- Will it be possible for you to share the model as well?

Thank you!
