### ISSUE TITLE
[Bug]openvino-ep memory leak

### ISSUE THREAD

**Issue by quanzhang2020** [openvinotoolkit/openvino#12727]
##### System information (version)

ocr inference:
text detection model: dynamic input size dbnet
ocr model: static input size(320x32) crnn
problem: Only the dynamic input detection model or the static input OCR model running is ok， but first run the dynamic input detection model and then run the static input OCR model will be memory leak。set openvino-ep code like this:

        m_buseov = bUse;
	if (m_buseov > 0){
		OrtOpenVINOProviderOptions options;
	    options.device_type = "CPU_FP32"; //Other options are: GPU_FP32, GPU_FP16, MYRIAD_FP16
		LOG(INFO) << "OpenVINO device type is set to: " << options.device_type;
		if (m_buseov == 1) {
			options.enable_dynamic_shapes = 1;                    //dynamic input size
			LOG(INFO) << "openvino with dynamic input size";
		}
		else {
			LOG(INFO) << "openvino with static input size";
			options.enable_dynamic_shapes = false;                    //static input size
		}
		options.enable_vpu_fast_compile = 0;
		options.device_id = "";
		//options.num_of_threads = 8;
		options.use_compiled_network = false;
		options.blob_dump_path = "";
		//options.context = 0x123456ff;
		options.enable_opencl_throttling = false;
	    sessionOptions.AppendExecutionProvider_OpenVINO(options);
     }

**Comment by Iffa-Meah** [comment]
@quanzhang2020 could you provide:
1. Your model files for us to validate from our side
2. Model info, framework & topology. EG: framework: Tensorflow, topology: Inceptionv1
3. IR conversion command that you used

**Comment by Iffa-Meah** [comment]
@quanzhang2020  fyi, increasing memory usage during the inferencing of Dynamic Model/Shape over time is expected.
However, this[ PR #12053](https://github.com/openvinotoolkit/openvino/pull/12053) has been merged into the master branch and should stop this issue.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
