### ISSUE TITLE
[ERROR] Exception occurred during running replacer "None (<class 'openvino.tools.mo.front.tf.MapFNTransformation.MapFNInputSlicing'>)": unhashable type: 'list'

### ISSUE THREAD

**Issue by singhalshikha518** [openvinotoolkit/openvino#12737]
System information (version)
  OpenVINO => openvino/ubuntu18_dev:latest docker
  Operating System / Platform => ubuntu
  Problem classification: Tensorflow2 Model Conversion
  Framework: TensorFlow2

I have tensorflow2 trained distilbert based ner model. I am trying to convert it to IR.

Here is my command : mo --saved_model_dir prebuilt_ner/1 --input first_subword_mask_tensor,input_ids_tensor,num_subwords_per_word_tensor,tokens_tensor,words_tensor --input_shape [-1,-1],[-1,-1],[-1,-1],[-1,-1],[-1,-1] --output map/TensorArrayV2Stack_3/TensorListStack,Identity_4,Identity_1,Tile,Sum,Identity_3,ner/ReverseSequence_1,ner/Cast_4,Fill,ner/hash_table_Lookup/LookupTableFindV2,Identity,map/TensorArrayV2Stack_1/TensorListStack,map/TensorArrayV2Stack/TensorListStack,map/TensorArrayV2Stack_2/TensorListStack

I am getting below error:
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      None
        - Path for generated IR:        /home/openvino/.
        - IR output name:       saved_model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         first_subword_mask_tensor,input_ids_tensor,num_subwords_per_word_tensor,tokens_tensor,words_tensor
        - Output layers:        map/TensorArrayV2Stack_3/TensorListStack,Identity_4,Identity_1,Tile,Sum,Identity_3,ner/ReverseSequence_1,ner/Cast_4,Fill,ner/hash_table_Lookup/LookupTableFindV2,Identity,map/TensorArrayV2Stack_1/TensorListStack,map/TensorArrayV2Stack/TensorListStack,map/TensorArrayV2Stack_2/TensorListStack
        - Input shapes:         [-1,-1],[-1,-1],[-1,-1],[-1,-1],[-1,-1]
        - Source layout:        Not specified
        - Target layout:        Not specified
        - Layout:       Not specified
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - User transformations:         Not specified
        - Reverse input channels:       False
        - Enable IR generation for fixed input shape:   False
        - Use the transformations config file:  None
Advanced parameters:
        - Force the usage of legacy Frontend of Model Optimizer for model conversion into IR:   False
        - Force the usage of new Frontend of Model Optimizer for model conversion into IR:      False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
OpenVINO runtime found in:      /opt/intel/openvino/python/python3.6/openvino
OpenVINO runtime version:       2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version:        2022.1.0-7019-cdb9bec7210-releases/2022/1
[ WARNING ]  
Detected not satisfied dependencies:
        networkx: installed: 2.5.1, required: ~= 2.6

Please install required versions of components or run pip installation
pip install openvino-dev[tensorflow]
2022-08-24 11:08:35.085155: E tensorflow/core/grappler/grappler_item_builder.cc:669] Init node key_value_init/LookupTableImportV2 doesn't exist in graph
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "None (<class 'openvino.tools.mo.front.tf.MapFNTransformation.MapFNInputSlicing'>)": unhashable type: 'list'
[ ERROR ]  Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/utils/class_registration.py", line 278, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/middle/pattern_match.py", line 46, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/front/tf/MapFNTransformation.py", line 145, in find_and_replace_pattern
    MapFNInputSlicing.transform_map_fn_input_slicing(external_match, internal_match)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/front/tf/MapFNTransformation.py", line 114, in transform_map_fn_input_slicing
    unstack_node.out_port(0).get_connection().set_source(unstack_node.in_port(0).get_connection().get_source())
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/graph/connection.py", line 122, in set_source
    source_fw_names = list(set(source_fw_names))
TypeError: unhashable type: 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/main.py", line 407, in prepare_ir
    graph = unified_pipeline(argv)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/pipeline/unified.py", line 17, in unified_pipeline
    class_registration.ClassType.BACK_REPLACER
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/utils/class_registration.py", line 328, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/utils/class_registration.py", line 318, in apply_replacements_list
    num_transforms=len(replacers_order))
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/utils/logger.py", line 112, in wrapper
    function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/utils/class_registration.py", line 306, in apply_transform
    )) from err
Exception: Exception occurred during running replacer "None (<class 'openvino.tools.mo.front.tf.MapFNTransformation.MapFNInputSlicing'>)": unhashable type: 'list'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by singhalshikha518** [comment]
I even tried command without output i.emo --saved_model_dir prebuilt_ner/1 --input first_subword_mask_tensor,input_ids_tensor,num_subwords_per_word_tensor,tokens_tensor,words_tensor --input_shape [-1,-1],[-1,-1],[-1,-1],[-1,-1],[-1,-1]

I am getting below error:
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      None
        - Path for generated IR:        /home/openvino/.
        - IR output name:       saved_model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         first_subword_mask_tensor,input_ids_tensor,num_subwords_per_word_tensor,tokens_tensor,words_tensor
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [-1,-1],[-1,-1],[-1,-1],[-1,-1],[-1,-1]
        - Source layout:        Not specified
        - Target layout:        Not specified
        - Layout:       Not specified
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - User transformations:         Not specified
        - Reverse input channels:       False
        - Enable IR generation for fixed input shape:   False
        - Use the transformations config file:  None
Advanced parameters:
        - Force the usage of legacy Frontend of Model Optimizer for model conversion into IR:   False
        - Force the usage of new Frontend of Model Optimizer for model conversion into IR:      False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
OpenVINO runtime found in:      /opt/intel/openvino/python/python3.6/openvino
OpenVINO runtime version:       2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version:        2022.1.0-7019-cdb9bec7210-releases/2022/1
[ WARNING ]  
Detected not satisfied dependencies:
        networkx: installed: 2.5.1, required: ~= 2.6

Please install required versions of components or run pip installation
pip install openvino-dev[tensorflow]
2022-08-24 12:35:45.306754: E tensorflow/core/grappler/grappler_item_builder.cc:669] Init node key_value_init/LookupTableImportV2 doesn't exist in graph
[ WARNING ]  The model contains input(s) with partially defined shapes: name="input_ids_tensor" shape="[-1, -1]",name="tokens_tensor" shape="[-1, -1]",name="words_tensor" shape="[-1, -1]",name="first_subword_mask_tensor" shape="[-1, -1]",name="num_subwords_per_word_tensor" shape="[-1, -1]". Starting from the 2022.1 release the Model Optimizer can generate an IR with partially defined input shapes ("-1" dimension in the TensorFlow model or dimension with string value in the ONNX model). Some of the OpenVINO plugins require model input shapes to be static, so you should call "reshape" method in the Inference Engine and specify static input shapes. For optimal performance, it is still recommended to update input shapes with fixed ones using "--input" or "--input_shape" command-line parameters.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1453: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  run_metadata)
[ ERROR ]  Cannot infer shapes or values for node "map/TensorArrayV2_4".
[ ERROR ]  Input 1 of node map/TensorArrayV2_4 was passed double from map/strided_slice_port_0_ie_placeholder:0 incompatible with expected int32.
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function tf_native_tf_node_infer at 0x7f78548e4f28>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'openvino.tools.mo.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "map/TensorArrayV2_4" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)

**Comment by rkazants** [comment]
@singhalshikha518, thanks for reporting this. It definitely looks like a bug in MO. The problem looks with nested lists of tensor names that we should not have there. 
@popovaan, could you please take a look at tensor names, as a fast work around can we unroll such nested lists. Thanks!

**Comment by singhalshikha518** [comment]
Hi @popovaan Do you have any updates on above issue?

**Comment by popovaan** [comment]
> Hi @popovaan Do you have any updates on above issue?

Hi @singhalshikha518 It looks like this case is specific for the model. Could you please provide us the original model?

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
