### ISSUE TITLE
[Feature Request] in-place support on custom layer

### ISSUE THREAD

**Issue by youki-sada** [openvinotoolkit/openvino#12769]
In the following Identity template example, memcpy operation is costly. So it will be great to enable passing input pointer to output pointer in stead of memcpy.
https://github.com/openvinotoolkit/openvino/blob/cdb9bec7210f8c24fde3e416c7ada820faaaa23e/docs/template_extension/new/identity.cpp#L41
Currently, I got `munmap_chunk(): invalid pointer` when inference phase.
I used following pointer passing method.
```
float *out_ptr = (float *)out.data();
out_ptr = (float *)in.data();
```

**Comment by jgespino** [comment]
@ilyachur I created an internal ticket for you to look into.

CC: @ilya-lavrenov

Ref. 90403

**Comment by ilyachur** [comment]
At the current moment we cannot change pointers inside the operation.
Because for this optimisation we need to know the model structure. It is why we are using `memcpy`.
So I created PR #12813 where added a check if input and output tensors use the same memory, in this case we will avoid `memcpy`.

**Comment by youki-sada** [comment]
Thank you for the quick check. But I don't think there is a possibility of the address match.

Can we access to the optimization flow from the extension functionality of OpenVINO? I assume optimizations such as constant folding and layer fusion are conducted during model optimizer. I can solve this issue if we can do the layer fusion between the custom layer and supported convolutional layer.

**Comment by ilyachur** [comment]
> Thank you for the quick check. But I don't think there is a possibility of the address match.
> 
> Can we access to the optimization flow from the extension functionality of OpenVINO? I assume optimizations such as constant folding and layer fusion are conducted during model optimizer. I can solve this issue if we can do the layer fusion between the custom layer and supported convolutional layer.

@youki-sada You can add the transformation pass which will fuse your custom operation and convolution.
[Here](https://docs.openvino.ai/latest/openvino_docs_transformations.html#doxid-openvino-docs-transformations) you can find documentation for transformation API.

You cannot integrate your transformations to openvino plugins, but you can call this transformation pass on application side before `core.compile_model()` call.

I hope it should solve your issue and resolve the problem.

**Comment by youki-sada** [comment]
Thank you very much. I'll have a look. There are device independent optimization and device specific one. I understood the API supports not only a plugin independent optimization, but also a plugin-specific optimization. I also want to optimize dnnl memory layout transformation for CPU plugin. I will check how does the API support.
