### ISSUE TITLE
Bounding box position deviation problem

### ISSUE THREAD

**Issue by vdministrator** [openvinotoolkit/openvino#12780]
I trained a yolov5 model with my own dataset,then transform it to *.onnx model then get *.xml and *.bin format. But when i try to use it in openvino, the output are totally different with original model.My goal is to draw the bounding box and get the detected classes.
the AI ​​model was converted and deployed on Raspberry pi, and Intel Neural Compute Stick 2 was used, but the bounding box was not at the target position, but shifted; the unconverted model (.pt) directly There is no problem deploying on the GPU, so I would like to ask how to solve this problem
![WechatIMG154](https://user-images.githubusercontent.com/12219743/186954334-61276d98-0656-4f2d-a463-36ba0a38ac6b.jpeg)

**Comment by zulkifli-halim** [comment]
Hi @vdministrator. When you run inference on GPU, are you using the Pytorch model or the converted (.xml and .bin) model? Also, please share with us this information:
- Link to the repository (is it [ultralytics/yolov5](https://github.com/ultralytics/yolov5)?)
- Custom-trained model (.pt file)
- MO command

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to reopen the issue if further assistance is needed.
