### ISSUE TITLE
[Bug]Submodule_update_with_gitee.sh failed to clone the submodules from gitee

### ISSUE THREAD

**Issue by dlod-openvino** [openvinotoolkit/openvino#12782]
For users in China, [clone submodules via gitee mirrors:](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux#build-steps)

The Submodule_update_with_gitee.sh failed to clone the submodules from gitee, instead of clone from github as well
![fail_to_run_submodule_update_with_gitee](https://user-images.githubusercontent.com/59691336/187010238-6fbb7dd1-c1e8-4c49-84f0-06b711dacd0a.png)
![fail_to_run_gitee_on_win10](https://user-images.githubusercontent.com/59691336/187010240-4ca6c6f1-56e2-4ab4-a5b8-65bed2f3845d.png)
.

**Comment by Iffa-Meah** [comment]
@dlod-openvino could you share the git command that you use to clone the submodules? or the script that you had written, as I notice that you were running a script to automate the cloning process.

**Comment by Iffa-Meah** [comment]
Hi,
I tested this using both Windows 10 and Ubuntu 20. I don't see any issue from my side.

Windows 10:

<img width="454" alt="w10" src="https://user-images.githubusercontent.com/79643476/187170871-3723146f-410b-4f38-9a01-3bf91d17be52.png">
<img width="444" alt="w10_success" src="https://user-images.githubusercontent.com/79643476/187170903-c1402d87-1c51-4d40-ae0b-78cb4fd142ed.png">




Ubuntu 20:

<img width="370" alt="u20" src="https://user-images.githubusercontent.com/79643476/187171040-6d8581f0-85e2-440e-bf52-a0cd5d883d27.png">

<img width="370" alt="u20_success" src="https://user-images.githubusercontent.com/79643476/187171093-260ab8a8-56f5-47cf-a959-60674a8baf6b.png">



The "TLS connection was non-properly terminated" probably indicating that the handshake to the site failed.
Try to disable the SSL verify: git config --global http.sslVerify false.

If you are using IPv6, try to use IPv4 instead: git clone <git url> -4

**Comment by ilya-lavrenov** [comment]
@sammysun0711 do we have NCC clone in gitee?

**Comment by sammysun0711** [comment]
@ilya-lavrenov, yes, here is NCC mirror in gitee: https://gitee.com/openvinotoolkit-prc/ncc

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
