### ISSUE TITLE
[Bug]Cannot get dims for non static shape when dynamic model

### ISSUE THREAD

**Issue by Hap-Zhang** [openvinotoolkit/openvino#12793]
Hi,all

I installed openvino 2022 according the tutorial for python developers
[https://docs.openvino.ai/latest/openvino_docs_install_guides_install_dev_tools.html](url)

The model conversion is ok with dynamic input as follows:
mo --input_model model.onnx --input_shape [1,3,608,1..960]

However, i get an error when inferring:
**openvino RuntimeError: Cannot get dims for non static shape**

Can anyone tell me how to fix it, thanks.

**Comment by andrei-kochin** [comment]
Hello @Hap-Zhang,

Thank you for reaching us!
Have you tried to convert without specifying --input_shape at all to have fully dynamic dimensions?
Will it be possible for you to share model or reference model that was used?

Thank you!

**Comment by Hap-Zhang** [comment]
Hi, @andrei-kochin Thank you for your reply.

**> Have you tried to convert without specifying --input_shape at all to have fully dynamic dimensions?**
Yeah, i converted the model without specifying --input_shape, and the error still exists.

**> Will it be possible for you to share model or reference model that was used?**
You can get the origin model here:[https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_det_infer.tar](url)
I converted the paddle model to onnx firstly by following readme.md here: [https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/paddle2onnx/readme.md](url)
`paddle2onnx --model_dir ./inference/ch_PP-OCRv2_det_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/det_onnx/model.onnx \
--opset_version 10 \
--input_shape_dict="{'x':[-1,3,-1,-1]}" \
--enable_onnx_checker True`
and then converted the onnx model to openvino ir:
`mo --input_model model.onnx --input_shape [1,3,608,1..960]`

**Comment by andrei-kochin** [comment]
Hello @Hap-Zhang,

Thank you. Do you have any specific reason to export the model to ONNX first? PaddlePaddle models can work without prior conversion to ONNX. Have you tried it?

Of course these ONNX failure should be investigated but please meanwhile try to feed the model directly to OV Runtime or convert first if you like.

Best regards,
Andrei

**Comment by andrei-kochin** [comment]
@Hap-Zhang and for sure I haven't asked about the device you are trying to infer. Is it CPU or GPU or anything different?

Thanks

**Comment by Hap-Zhang** [comment]
Hi @andrei-kochin 
The device is Intel CPU(**Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz**).

I have tried to convert the paddle model to OV IR directly, and got the same error when executing this line:
`infer_request = self.predictor.create_infer_request()`

**Comment by andrei-kochin** [comment]
@Hap-Zhang thank you!

I've created internal ticket to track this. Ref. 90423

@yuxu42 and his team will take care

**Comment by yuxu42** [comment]
@liubo-intel Could you please take a look? Thanks!

**Comment by Hap-Zhang** [comment]
Hi, @yuxu42 @liubo-intel @andrei-kochin 
Is there any update? I'm appreciated if you could contact me in time. Thank you very much.

**Comment by liubo-intel** [comment]
Hi, @Hap-Zhang : we have tried this model on our side, it seems work fine. could you please have a try with following the way just as we do?:

First, Convert this Paddle OCR model directly to to openvino ir:
`python mo.py --input_model ./ch_ppocr_server_v2.0_det_infer/inference.pdmodel --output_dir ./IR --input_shape=[1,3,608,1..960] --framework=paddle --data_type=FP32 --reverse_input_channels --input=x --output=save_infer_model/scale_0.tmp_1`

then try to do openvino Infer with generated IR by using 'benchmark_app'(from 'openvino/samples' or 'openvino/tools'):
`./benchmark_app -m ./IR/inference.xml -d CPU -niter 2 -data_shape x[1,3,608,608]`

Please, pay attention to the input data shape when do openvino Infer in your application. from your description([1,3,608,1..960]), it looks like you intend to fix 'n','c','h' dimensions to '1','3','608' and keep 'w' dimension dynamic with the range from '1' to '960', so in your inference application please also follow this way(the only dimension that you can change during inference runtime is 'w' dimension, and its range should keep in[1,960]).

**Comment by Hap-Zhang** [comment]
Hi, @liubo-intel 
Thanks for your reply. I convert this Paddle model directly to openvino ir:
`python mo.py --input_model /opt/app/inferenced_models/ch_ppocr_server_v2.0_det_infer/inference.pdmodel --output_dir ./IR --input_shape=[1,3,608,1..960] --framework=paddle --data_type=FP32 --reverse_input_channels --input=x --output=save_infer_model/scale_0.tmp_1`

The conversion is ok. However, when execute this line, 
`infer_request = self.predictor.create_infer_request()`
the error still exists.
**RuntimeError: Cannot get dims for non static shape**

My openvino environment is built according to this document for python developers
[https://docs.openvino.ai/latest/openvino_docs_install_guides_install_dev_tools.html](url)
and i can not find "benchmark_app"

**Comment by Hap-Zhang** [comment]
OK, @liubo-intel 
Thanks very much. I will have a try.
