### ISSUE TITLE
MFX: Unsupported extension OpenVINO Windows

### ISSUE THREAD

**Issue by nedo99** [openvinotoolkit/openvino#1280]
Hi,

I installed openVINO package on Windows 10, but cannot get videos working. I am getting the following message:
`
MFX: Unsupported extension
[ WARN:0] global opencv\modules\videoio\src\cap_msmf.cpp (680) CvCapture_MSMF::initStream Failed to set mediaType (stream 0, (352x288 @ 25) MFVideoFormat_RGB32(unsupported media type)
`
I tried installing various codecs but I still have the issue. 

Platform info:
```
4.3.0-14-g9a54a3273 (OpenVINO/2020.3)
releases/openvino/2020.3
9a54a3273da58e5992a7cf4bed1e30277f26dd22

General configuration for OpenCV 4.3.0-openvino-2020.3.0 =====================================
  Version control:               9a54a3273da58e5992a7cf4bed1e30277f26dd22

  Platform:
    Host:                        Windows 10.0.18363 AMD64
    CMake:                       3.14.5
    CMake generator:             Visual Studio 14 2015 Win64
    MSVC:                        1900
```

Any help?

Regards,
Nedim

**Comment by dkurt** [comment]
related https://github.com/opencv/opencv/issues/17790

**Comment by mshabunin** [comment]
This issue have been fixed and will be released with OpenVINO 2020.4

**Comment by avitial** [comment]
@nedo99 in addition try to install FFmpeg as VideoCapture backend. If you installed the Intel® Distribution of OpenVINO™ toolkit package, there is  script under `C:\Program Files (x86)\IntelSWTools\openvino\opencv\ffmpeg-download.ps1`, just right click on script and run with PowerShell.

**Comment by jgespino** [comment]
@nedo99 OpenVINO 2020.4 has been release, feel free to re-open if you see the same issue on the latest release.
