### ISSUE TITLE
OpenVINO2022.1_Qt_Ubuntu18 undefined reference to tbb

### ISSUE THREAD

**Issue by linglongxian** [openvinotoolkit/openvino#12819]
hello, i used to compile and run the program with cmake successfully, but when i try to compile the program with qt, errors that "undefined reference to tbb" happen.

i tried to  change the path of tbb. tbb path of system and 3rdparty of openvino were tested, but it did not work.  And i tried to start qtcreator with sudo, errors still exist.

here is the screenshot of error.
![1](https://user-images.githubusercontent.com/36992313/187368476-e455b938-80f0-43b3-9384-17d47d481c07.PNG)

openvino：2020.1
qt: 5.12.5
os: ubuntu18.04

code:
#include <QApplication>
#include "openvino.hpp"

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    ov::Core core;
    printf("OpenVINO init...");

    return a.exec();
}

CMAKELISTS.txt:
cmake_minium_required(VERSION 3.5)

project(detect_test)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_BUILD_TYPE "Release")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -pthread -fopenmp")

#查找必要的依赖包
find_package(OpenCV REQUIRED)
set(OpenVINO_DIR /opt/intel/openvino_2022/runtime/cmake/)
find_package(OpenVINO REQUIRED)

target_include_directories(detector
        PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include
)

add_executable(detect_test main.cpp)
target_link_libraries(detect_test
        [detector](openvino::runtime)
)

pro:
QT += core
QT += gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

QT += network

CONFIG += c++11 console
CONFIG -= app_bundle

DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += \
        main.cpp

qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

INCLUDEPATH += /usr/local/include/opencv4
LIBS += -L/usr/local/lib -lopencv_core -lopencv_highgui -lopencv_video -lopencv_imgproc -lopencv_videoio -lopencv_imgcodecs -lopencv_dnn

#path of tbb in 3rdpaty of openvino
#INCLUDEPATH += /opt/intel/openvino_2022/runtime/3rdparty/tbb/include/tbb
#INCLUDEPATH += /opt/intel/openvino_2022/runtime/3rdparty/tbb/include/serial/tbb
#LIBS += -L/opt/intel/openvino_2022/runtime/3rdparty/tbb/lib -ltbb -ltbbmalloc -ltbbmalloc_proxy -ltbbbind -ltbb_preview

#path of system tbb
INCLUDEPATH += /usr/local/include/tbb/
LIBS += /usr/local/lib/libtbb.so

#win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../../../usr/local/lib/release/ -ltbb
#else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../../../usr/local/lib/debug/ -ltbb
#else:unix: LIBS += -L$$PWD/../../../usr/local/lib/ -ltbb

#INCLUDEPATH += $$PWD/../../../usr/local/include/tbb
#DEPENDPATH += $$PWD/../../../usr/local/include/tbb

INCLUDEPATH +=  /opt/intel/openvino_2022/runtime/include/ie/
INCLUDEPATH +=  /opt/intel/openvino_2022/runtime/include/ngraph/
INCLUDEPATH +=  /opt/intel/openvino_2022/runtime/include/openvino/
INCLUDEPATH +=  /opt/intel/openvino_2022/runtime/include/

LIBS += -L/opt/intel/openvino_2022/runtime/lib/intel64 -lopenvino
#LIBS += -L/opt/intel/openvino_2022/runtime/lib/intel64 -lopenvino -lgna -lopenvino_auto_batch_plugin -lopenvino_auto_plugin -lopenvino_ir_frontend -lopenvino_intel_cpu_plugin -lopenvino_gapi_preproc -lopenvino_hetero_plugin

**Comment by linglongxian** [comment]
update:
after i run "qmake" in qtcreator, i open a terminal, go to the debug folder and run "make", it build well and i can run the program with "./".
but if i comments "source /opt/intel/openvino_2022/setupvars.sh" in ~/.bashrc, run "make" in terminal, the "undefined reference to tbb" erros happen.

**Comment by linglongxian** [comment]
update 2:
i change the "LIBS += -L/opt/intel/openvino_2022.1.0.643/runtime/3rdparty/tbb/lib -ltbb -ltbbmalloc -ltbbmalloc_proxy -ltbbbind -ltbb_preview" to "LIBS += /opt/intel/openvino_2022.1.0.643/runtime/3rdparty/tbb/lib/libtbb.so.2", it can build in qt, but click "run",  "error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory" happen.

**Comment by linglongxian** [comment]
update 3:
after communication with a worker of intel china, i try open a terminal, type "source /opt/intel/openvino_2022/setupvars.sh" and "/opt/Qt5.12.5/Tools/QtCreator/bin/qtcreator" to start qtcreator, then it work.

but i still have a confusion why should i source and start qtcreator in the same terminal.

ps: i have added  "source /opt/intel/openvino_2022/setupvars.sh" in ~/.bashrc in update 1 and 2.

**Comment by brmarkus** [comment]
When adding "source setupvars.sh" to e.g. `~/.bashrc` then the script exposes ENV variables only for the created terminal-session; the ENV-variables are not exposed globally in this case.
If you open another terminal or start an application (like `qtcreator`) then it will get another (temporary) session/context and the ENV-variables are not visible.

So, the easiest is to source the setupvars.sh in a terminal and start all what you need from this same terminal.
Otherwise you would need to make sure you manually take-over all the ENV-variables in your (q)makefiles, QTCreator, VSCode etc.

**Comment by artkuli** [comment]
Hi @linglongxian,
You don't need to run `setupvars.sh` on the same terminal with the `QtCreator`. The `setupvars.sh` sets up the environment variables like: `LD_LIBRARY_PATH`, `TBB_DIR` so you can go (inside `QtCreator`) to the `Projects` and inside `Build Environment` set up them separately like:
`LD_LIBRARY_PATH`=`<INSTALL_OPENVINO_DIR>/runtime/3rdparty/tbb/lib`
`TBB_DIR`=`<INSTALL_OPENVINO_DIR>/runtime/3rdparty/tbb/lib64/cmake/TBB`
To check the correct paths to these variables you can run it like:
`$ source setupvars.sh
 $ echo $TBB_DIR
 $ echo $LD_LIBRARY_PATH`

**Comment by linglongxian** [comment]
@artkuli yeah, you are right. i test and find the difference between starting qtcreator after "source setupvars.sh" in a same terminal and only starting qtcreator  is the LD_LIBRARY_PATH，TBB_DIR.
thank you!

**Comment by artkuli** [comment]
Can we close the issue?
