### ISSUE TITLE
[API2.0] Blocked layout support for custom layers

### ISSUE THREAD

**Issue by youki-sada** [openvinotoolkit/openvino#12838]
How can we use blocked layout such as nChw8c for custom layers? I'd like to use nChw8C on my custom layer since costly Reorder operations frequently occurred when I used NCHW. I found the way on old 2018 version, but I couldn't find it on latest 2022.1 version. 
@ilyachur Could you please tell me how to use the nChw8c on latest OpenVINO?
Environment:
- OpenVINO 2022.1
- CPU Plugin
- Ubuntu18

Related links:
- [Performance Considerations for Custom Kernels and Custom Layers (old versions <=2019.R3)](https://www.intel.com/content/www/us/en/developer/articles/technical/openvino-custom-layers-support-in-inference-engine.html#inpage-nav-3)
- [Model Optimizer Extensibility (current API2.0)](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_customize_model_optimizer_Customize_Model_Optimizer.html#)
- [docs/template_extension/new/identity.hpp](../blob/2022.1.0/docs/template_extension/new/identity.hpp#L17)
- I have discussed in OpenVINO forum [here](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/OpenVINO-2022-1-CPU-Plugin-Blocked-layout-support-for-custom/td-p/1410858)
- #12769

**Comment by ilyachur** [comment]
Hi @youki-sada, at the current moment we doesn't provide an opportunity to use blocked layout for OV 2.0 extensions.

You have 2 ways, how to support operation with blocked layout at the current moment:

- Create old extension
- Contribute to OpenVINO CPU plugin

Could you provide a scenario which you want to support? 

CC @dmitry-gorokhov

**Comment by youki-sada** [comment]
Thank you for the quick answer, ilyachur.
> Create old extension

Do you mean we can load old extension in new OpenVINO 2022.1, or we must use load it in old OpenVINO 2020?

**Comment by youki-sada** [comment]
I successfully created a old .so extension by removing `openvino::core` linking in following line. Otherwise, I got `/usr/bin/ld: cannot find -lopenvino::core` error. I'll check later if this old extension works well in OpenVINO 2022.1 inference.
https://github.com/openvinotoolkit/openvino/blob/cdb9bec7210f8c24fde3e416c7ada820faaaa23e/docs/template_extension/old/CMakeLists.txt#L27

**Comment by youki-sada** [comment]
Loading old extension in OpenVINO 2022.1 was not possible. I got following error.
```
Model Optimizer version:        2022.1.0-7019-cdb9bec7210-releases/2022/1
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  dlSym cannot locate method 'create_extensions': /home/openvino/Lab/work/openvino/docs/template_extension/old/build/libtemplate_extension.so: undefined symbol: create_extensions
[ ERROR ]  Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/main.py", line 533, in main
    ret_code = driver(argv)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/main.py", line 489, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/main.py", line 393, in prepare_ir
    moc_front_end.add_extension(extension)
RuntimeError: dlSym cannot locate method 'create_extensions': /openvino/docs/template_extension/old/build/libtemplate_extension.so: undefined symbol: create_extensions

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
ERROR: 1
```

**Comment by ilyachur** [comment]
@youki-sada Yes OV 2022.1 and OV 2.0 support loading of old extensions.
But as I see you try to load old extension to the Model Optimizer, MO supports never this type of extensions, if you want to convert IR with custom operation you need to use MO legacy extension mechanism or new extensions.

Old extensions are needed for you only in order to provide implementation with blocked layouts to CPU plugin.

**Comment by youki-sada** [comment]
@ilyachur Thank you for your kind support. I will first start checking the first solution that is the legacy extension on OV2.0 couple of weeks later.

**Comment by ilya-lavrenov** [comment]
BTW, removed openvino::core from template extension https://github.com/openvinotoolkit/openvino/pull/12883

**Comment by youki-sada** [comment]
I tried legacy extension mechanism by using your Template addition example and onnx MO.
https://github.com/openvinotoolkit/openvino/blob/2022.1.0/docs/template_extension/old/op.hpp#L14

I used following MO command, onnx files, and Template.py on version 2022.1. However I got `[ ERROR ]  Cannot create Template layer 1 id:1 from unsupported opset: custom_opset` error.

Do you have any idea to fix this?

```bash
mo --model_name template --input_model template_co.onnx --output_dir vino_ir --data_type=FP32 --extensions legacy_ext --use_legacy_frontend
```
template onnx files: [template.zip](https://github.com/openvinotoolkit/openvino/files/9808472/template.zip)
```python
# legacy_ext/ops/Template.py
from openvino.tools.mo.front.common.partial_infer.elemental import copy_shape_infer
from openvino.tools.mo.graph.graph import Graph
from openvino.tools.mo.ops.op import Op

class Template(Op):
    op = 'Template'
    enabled = False
    def __init__(self, graph: Graph, attrs: dict):
        super().__init__(graph, {
            'type': self.op,
            'op': self.op,
            'version': 'custom_opset',
            'add': None,
            'in_ports_count': 1,
            'out_ports_count': 1,
            'infer': copy_shape_infer
        }, attrs)

    def backend_attrs(self):
        return ['add']
```

**Comment by ilyachur** [comment]
Hi @youki-sada 

Could you use new extensions and new frontends for the MO?
But also add the legacy extensions only in order to support blocked CPU extensions in the runtime?

CC @slyalin @andrei-kochin

**Comment by youki-sada** [comment]
@ilyachur Sorry I couldn't understand your advice and getting confusing about the legacy extension.

You meant we can add following blocked layout support on new extension or we can mix new extension and old one?
https://github.com/openvinotoolkit/openvino/blob/cdb9bec7210f8c24fde3e416c7ada820faaaa23e/docs/template_extension/old/cpu_kernel.cpp#L91-L93

I already implemented my custom layer using new extension and general memory layout. And then, I have tried old extension and legacy MO (i.e. `--use_legacy_frontend`) to support blocked layout today, since you taught me at https://github.com/openvinotoolkit/openvino/issues/12838#issuecomment-1232489518 that new extension does not support blocked layout. I started from the simple addition layer but it didn't work.

**Comment by ilyachur** [comment]
Hi @youki-sada, 

No I meat that maybe for your case will be easier to have 2 types of OpenVINO extensions:

- New extension to convert ONNX model to IR with new frontend and without legacy Python MO extensions
- Old OV extension for OV runtime only in order to execute your custom layer on CPU with blocked memory layout


Also for the your current problem with legacy python MO extension:

- Do you get error message from MO or from OpenVINO runtime? (Looks like you get an error when read the model)
- Can you share IR file if it was generated?

**Comment by youki-sada** [comment]
I see! I will try this procedure.

The error was from MO. I couldn't make an IR xml. All message for MO failure is attached bellow.
It seems shape_infer of Template layer is succeeded, but after that `[ ERROR ] Cannot create Template layer 1 id:1 from unsupported opset: custom_opset`.
[mo_full_log.txt](https://github.com/openvinotoolkit/openvino/files/9816617/mo_full_log.txt)

**Comment by ilyachur** [comment]
> The error was from MO. I couldn't make an IR xml. All message for MO failure is attached bellow.
> It seems shape_infer of Template layer is succeeded, but after that `[ ERROR ] Cannot create Template layer 1 id:1 from unsupported opset: custom_opset`.
> [mo_full_log.txt](https://github.com/openvinotoolkit/openvino/files/9816617/mo_full_log.txt)

@slyalin @andrei-kochin @jane-intel Can you advise? Is it expected?

**Comment by youki-sada** [comment]
This is the IR xml by new extension that I created for simple addition example.
[template_ir.zip](https://github.com/openvinotoolkit/openvino/files/9816809/template_ir.zip)
It is successfully executed via new libopenvino_template_extension.so, but failed via old libtemplate_extension.so.
### new .so execution
```
$ benchmark_app -d CPU -m vino_ir/template.xml -nireq 1 -niter 10 -l new_ext/build/libopenvino_template_extension.so
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] CPU (MKLDNN) extensions is loaded new_ext/build/libopenvino_template_extension.so
[ INFO ] OpenVINO: OpenVINO Runtime version ......... 2022.1.0
[ INFO ] Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
~~~ omit ~~~
[Step 11/11] Dumping statistics report
[ INFO ] Count:      10 iterations
[ INFO ] Duration:   1.94 ms
[ INFO ] Latency:
[ INFO ]        Median:     0.15 ms
[ INFO ]        Average:    0.18 ms
[ INFO ]        Min:        0.09 ms
[ INFO ]        Max:        0.59 ms
[ INFO ] Throughput: 5162.72 FPS
```
### old .so execution
```
$ benchmark_app -d CPU -m vino_ir/template.xml -nireq 1 -niter 10 -l legacy_ext/build/libtemplate_extension.so
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ ERROR ] dlSym cannot locate method 'create_extensions': legacy_ext/build/libtemplate_extension.so: undefined symbol: create_extensions
```

**Comment by youki-sada** [comment]
It seems the error is coming from core.add_extension. I tied it via Python API but I faced same error as benchmark_app
```
Traceback (most recent call last):
  File "tools/exec_vino.py", line 34, in <module>
    core.add_extension(args.extension)
RuntimeError: dlSym cannot locate method 'create_extensions': legacy_ext/build/libtemplate_extension.so: undefined symbol: create_extensions
```

**Comment by ilyachur** [comment]
Hi @youki-sada, unfortunately if you want to use 2022.1 release you need to modify benchmark app:

```
const auto extension_ptr = std::make_shared<InferenceEngine::Extension>(path_to_old_extension);
core.add_extension(extension_ptr);
```

Also you can check this PR: https://github.com/openvinotoolkit/openvino/pull/13543 I created it in order to fix your issue for the master branch.

**Comment by youki-sada** [comment]
Great, thank you. Now I could add old extension and got same error of `unsupported opset`. I think I need to learn the custom opset and custom domain of old extension. 
```
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] CPU (MKLDNN) extensions is loaded legacy_ext/build/libtemplate_extension.so
[ INFO ] OpenVINO: OpenVINO Runtime version ......... 2022.1.0
[ INFO ] Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
[ INFO ]
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] openvino_intel_cpu_plugin version ......... 2022.1.0
[ INFO ] Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT.
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ ERROR ] Cannot create Template layer 1 id:1 from unsupported opset: extension
```

**Comment by youki-sada** [comment]
@ilyachur I am now trying to use nChw8c or nChw16c. Firstly, I added two convolutional layers before and after the custom addition layer. And then, I checked a memory layout of conv layer output and I found that the layout is abcd16b (nChw16c). Thus, I modified following lines by 16.
https://github.com/openvinotoolkit/openvino/blob/cdb9bec7210f8c24fde3e416c7ada820faaaa23e/docs/template_extension/old/cpu_kernel.cpp#L68-L72
I could load the model to device, but I got `Cannot get memory!` error while `infer_request.infer();` model execution. I think the error is coming from following line. I attached a screen shot of execution graph. Any advice would be appreciated.
https://github.com/openvinotoolkit/openvino/blob/cdb9bec7210f8c24fde3e416c7ada820faaaa23e/src/plugins/intel_cpu/src/cpu_memory.h#L199-L205

![exec3](https://user-images.githubusercontent.com/107164289/196825709-2066da37-427f-4fdd-af49-523586380828.png)

**Comment by ilyachur** [comment]
Hi @youki-sada thank you for information.

@dmitry-gorokhov Could you advise?

**Comment by ilyachur** [comment]
@youki-sada Dynamic shapes are not supported in legacy extensions.

**Comment by youki-sada** [comment]
Okay, then I think I need to develop custom CPU plugin. Do you have any plan to support the blocked layout in new extension?

**Comment by ilyachur** [comment]
We don't have such plans in nearest future.
Could you explain what is your case that you want to solve?

**Comment by youki-sada** [comment]
In my case, I want to implement some sort of a custom gather operation with blocked layouts.
Input is two, a float "nChw8c"/"nChw16c" tensor and 1D int32 indices ({n,h,w} coordinate). Output is a float "nc" matrix stored by non blocked layout. "n" of output tensor corresponds to the length of indices. After this gather operation MLPs are performed.
Therefore, I want to use blocked layout for the float input tensor and dynamic axes for the input indices and the output matrix.

**Comment by ilyachur** [comment]
@youki-sada Do you have any results?
Do you see real performance improvements?

**Comment by ilyachur** [comment]
Also "custom gather" means that this gather op has different behaviour than ops which are presented in OpenVINO opsets?

**Comment by youki-sada** [comment]
Yes, compared with a combination of OpenVINO supported transpose and GatherND, our custom gather implementation achieved X4 to X10 faster. We carefully utilize AVX512 intrinsic and TBB. However, costly reorders occurred when we applied our gather operation with new extensions. So we would like to remove them for further optimizations.

**Comment by youki-sada** [comment]
Our custom gather operation is equivalent with OpenVINO transpose + GatherND. But our implementation is optimized for gathering n,h,w along with contiguous c memory access.

**Comment by ilyachur** [comment]
@youki-sada Maybe can you try to contribute your implementation into CPU plugin?
@dmitry-gorokhov CC

**Comment by youki-sada** [comment]
Sure, I can try. But I have no experience to modify CPU plugin and also build OpenVINO. I would give up if it's too complicated.

**Comment by ilyachur** [comment]
@dmitry-gorokhov Could you provide an instruction how to contribute to CPU plugin?

**Comment by ilyachur** [comment]
@youki-sada Could you share the code in order for we will be able to take a look on your implementation?

**Comment by dmitry-gorokhov** [comment]
Hi @youki-sada, 
I agree with @ilyachur. We would really appreciate if you can share you implementation for this custom layer and use-case (which subgraph is mapped on custom op) where it provides great performance improvement you shared. The team then will integrate you optimizations inside the product to make it available out-of-the-box.

**Comment by youki-sada** [comment]
@ilyachur @dmitry-gorokhov Thank you for your great offer. I think I can share my code but I have several concern about contributing the official intel_cpu plugin.
1. Our custom layers are for really special neural networks and many people do not use the combination of transpose and gather. I wonder our implementations are worth merging to the official plugin.
2. Our objective is to use blocked layout. Just contributing the plugin doesn't solve my problem. After contributing to the plugin, I need to support blocked layouts by following OV plugin coding.

**Comment by dmitry-gorokhov** [comment]
@youki-sada Our goal is to make OpenVINO sustainable and performant on any possible use-case. You valuable input highlights we have significant gaps from that standpoint and looking forward to fix it. The fix not necessarily means including the custom implementation as is, it might be some changes in existing CPU plugin kernels or extending code-generation capabilities. 

It is a requirement to use blocked layout for you case? OV CPU plugin is migrated on nhwc layout as default one for fp32 models starting from OV 2022.2 release since it provides almost the same level of performance as blocked one but significantly easier from maintenance perspective.

**Comment by youki-sada** [comment]
Can we use the layouts if I contribute to CPU plugin? or it's not possible on 2022.2?

**Comment by youki-sada** [comment]
@dmitry-gorokhov I'm sorry I forgot to mention.

**Comment by dmitry-gorokhov** [comment]
@youki-sada 
In 2022.2 we integrated new **brgemm** Convolutions from oneDNN with the top priority: https://github.com/openvinotoolkit/openvino/blob/releases/2022/2/src/plugins/intel_cpu/src/nodes/conv.cpp#L322-L323. These Convolutions are used on AVX512 platforms and assumes nhwc layout on activations. So I would suggest what exact convolution type was used on Xeon in your case.

>>> Can we use the layouts if I contribute to CPU plugin? or it's not possible on 2022.2?
Could you please clarify your ask? What exactly you want to achieve?

**Comment by youki-sada** [comment]
@dmitry-gorokhov Thank you very much for your precious info. I had not checked on Xeon at that time. Now, I confirmed that Xeon adopts nhwc on 2022.2 that is fantastic for me. This might solve my problem so please never mind about the question.
BTW, I'm curious about nchwc support for AVX2/brgconv_avx2. I assume nhwc migration is only for AVX512 now. It is because of hardware (ISA) limitation?

And about my custom gather implementation, this has done as my job and I'm asking my boss to contribute my source code.

**Comment by youki-sada** [comment]
Now I find that GatherND is faster than my implementation for nhwc case of Xeon.

@ilyachur Now I would like to use nhwc but not blocked layouts. But I think nchw is the default layout on IR and so new extensions support only nhwc and nc layouts. Are there any way to use nhwc instead of nchw layout on new extensions?

**Comment by dmitry-gorokhov** [comment]
@youki-sada Thank you for the update. 
Brgconv is enabled on avx512 platforms only at the moment. We are waiting [oneDNN](https://github.com/oneapi-src/oneDNN) (our thirdparty) to implement for avx2 as well. Not sure about exact timelines.
