### ISSUE TITLE
Inference performance issue?

### ISSUE THREAD

**Issue by largestcabbage** [openvinotoolkit/openvino#12899]
If I modify the shape of the model, such as changing [1,3,256,256] to [4,3,256,256], or [8,3,256,256], can the inference time for a single image be reduced？

**Comment by ilya-lavrenov** [comment]
Hi @largestcabbage,
You can modify [1,3,256,256] as [-1,3,256,256]. It means the model will be with dynamic batch and actual data size will be determined in runtime when you call:
```c++
ov::InferRequest r = ...;
r.set_input_tensor(tensor_with_batch2);
r.infer();
r.set_input_tensor(tensor_with_batch4);
r.infer(); // batch4 takes more time than batch2 because of data size
```
See https://docs.openvino.ai/latest/openvino_docs_OV_UG_DynamicShapes.html for more details. 
Such model can be inferenced on CPU or GPU device and inference time will depend on actual batch size.

**Comment by largestcabbage** [comment]
Yeah, I know. I wonder if the time-consuming of batch inference grows linearly? For example, when batch is 1, it takes 10ms. When the batch is 2, it takes about 20ms. When the batch is 4, it takes about 40ms. When the batch is 8, it takes about 80ms?
