### ISSUE TITLE
Do infer requests in AsyncInferQueue run in parallel?

### ISSUE THREAD

**Issue by hjzin** [openvinotoolkit/openvino#12900]
I'm trying to use `AsyncInferQueue` to do async inference, just curious that if I create multiple infer requests in  `AsyncInferQueue`, like the following code snippet, do the infer requests run in parallel or in sequence?
```python
def call_back(requests, userdata):
    pass

jobs = 4
infer_queue = AsyncInferQueue(model, jobs=jobs)
infer_queue.set_callback(call_back)
# create list of input data
data = [input_data for i in range(jobs)]
# start inference
for i in range(len(data)):
    infer_queue.start_async(data[i], user_data=i)
infer_queue.wait_all()
```

**Comment by JorgeRuizDev** [comment]
AsyncInferenceQueue can run in pararell, but it depends on the device.

For example, if you are working with multiple NCS2, you can use the [MULTI plugin](https://docs.openvino.ai/2021.4/openvino_docs_IE_DG_supported_plugins_MULTI.html?sw_type=switcher-python) to send an individual inference request to each device. 

I'm not sure about this behaviour in CPU, but I guess that you can send a request per core if the CPU usage is not maxed out in sync mode.

**Comment by hjzin** [comment]
Hi Jorge, thanks for your reply!

I am mainly working on CPU so I may focus more on the behavior of infer requests in CPU, and maybe the behavior will depend on many factors.

**Comment by zulkifli-halim** [comment]
Hi @hjzin. AsyncInferQueue represents a helper that creates a pool of asynchronous InferRequests and provides synchronization functions to control the flow of a simple pipeline. The `start_async` will run asynchronous inference using the next available InferRequest from the pool. The asynchronous approach runs multiple inferences in a parallel pipeline. 

You can refer to [Asynchronous Execution of the Inference Engine](https://www.youtube.com/watch?v=fzYe_E5sARA) for more explanation.
