### ISSUE TITLE
Missing U32 precision

### ISSUE THREAD

**Issue by adk9** [openvinotoolkit/openvino#1292]
I have a nGraph constant node with element type as u32 in an nGraph function that I'm using to create a `CNNNetwork`. When trying to load the network to the CPU plugin, I see the following error:
```
ie_ngraph_utils.hpp:117  Incorrect precision u32!
```

Looking at the API documentation [here](https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1Precision.html#ade75bd7073b4aa966c0dda4025bcd0f5), it looks like there's no `InferenceEngine::Precision::U32`. Is U32 precision type missing?

**Comment by ilyachur** [comment]
Yes at the current moment IE doesn't contain U32 precision. Due to this, we cannot convert nGraph u32 to Inference Engine precision

**Comment by ilyachur** [comment]
I added U32 precision in the next PR: https://github.com/openvinotoolkit/openvino/pull/1297

Please check that it works for your case.

**Comment by adk9** [comment]
@ilyachur Thanks for the quick PR. These changes work for my case and I'm now able to pass nGraph functions with U32 precision.

**Comment by ilyachur** [comment]
@adk9 Cool! The PR was merged to the master branch.

Please try to use the master branch and please close the issue if all is ok.

**Comment by adk9** [comment]
Everything looks good on master; closing the issue now.
