### ISSUE TITLE
[Bug] GPU InferRequest::~InferRequest() crash

### ISSUE THREAD

**Issue by wang7393** [openvinotoolkit/openvino#12944]
##### System information (version)
- OpenVINO=> :2022.1
- Operating System / Platform => :win10
- Problem classification => :  GPU InferRequest::~InferRequest() crash

With GPU inference,  the InferRequest as a member variables like this :
`ov::InferRequest m_inferRequest;`

At the end of the inference,  the destructor crashes, The stack as follows:
![image](https://user-images.githubusercontent.com/29936604/188780735-49e36250-d8aa-475a-b13a-b2659d6574a4.png)

With CPU inference, After the end of the inference, the program can exit normally.

So, The GPU_PLUGIN may has bug.

**Comment by andrei-kochin** [comment]
@vladimir-paramuzov @p-durandin have you seen something similar?

**Comment by wang7393** [comment]
@ilya-lavrenov 
The simplest way to reproduce: Load the model and create InferRequest. No subsequent inference is required.
In debug mode, the InferRequest destructor must crash, and release occasionally crashes.

**Comment by avitial** [comment]
@wang7393 could you provide steps to replicate in a minimal sample reproducer? In addition, which graphics driver version are you using? What kind of processor graphics do you have?

**Comment by avitial** [comment]
Closing this. Feel free to reopen to provide additional information and ask questions related to this topic.
