### ISSUE TITLE
[Bug] C++ did not find this interface

### ISSUE THREAD

**Issue by caopl** [openvinotoolkit/openvino#12969]
##### System information (version)
- OpenVINO => 2022.1.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2022

##### Detailed description
python: 
det_output_layer = det_compiled_model.output(0)
det_results = det_compiled_model([Image])[det_output_layer]

C++:
C++ did not find this interface, how to implement it? how to get det_results?

**Comment by ilya-lavrenov** [comment]
Hi @caopl,

Here is a guide how to work with OpenVINO Runtime in C++ and Python, code snippets are switchable between programmnig languages https://docs.openvino.ai/latest/openvino_docs_OV_UG_Integrate_OV_with_your_application.html
Methods of `ov::InferRequest` to get or set input tensors in C++ https://docs.openvino.ai/latest/classov_1_1InferRequest.html

based on that, you can use:
```c++
det_results = det_infer_request.get_output_tensor(0);
```
or simply:
```c++
det_results = det_infer_request.get_output_tensor();
```
if your model has a single output

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. 

Feel free to reopen and provide additional information or ask any questions related to this topic.
