### ISSUE TITLE
How to test for loss of precision？

### ISSUE THREAD

**Issue by largestcabbage** [openvinotoolkit/openvino#12984]
How to test the accuracy loss of the model after converting FP32 to FP16

**Comment by brmarkus** [comment]
How to you measure accuracy/accuracy-loss for your current model right now (you have the ground-truth/labels for reference?)?

You could use the "accuracy-checker" tool (see e.g. https://docs.openvino.ai/latest/omz_tools_accuracy_checker.html) from OpenVINO (e.g. used in the context of INT8-quantization).

Do you find something useful within the metrics under "https://docs.openvino.ai/latest/omz_tools_accuracy_checker_metrics.html"?
