### ISSUE TITLE
Exception "bad conversion" thrown while practicing with OpenVINO

### ISSUE THREAD

**Issue by PlohovEvg** [openvinotoolkit/openvino#1301]
I was practicing with OpenVINO toolkit, running Google Tests and one failed with "bad conversion" exception. But this exact build passed on TravisCI.

OS: Windows 10 Pro x64
CPU: Intel Core i5-4570
OpenVINO version: 2020.3.194
Link to PR, showing that build passed on Travis CI: https://github.com/dkurt/openvino_practice/pull/173
Screenshot, which shows failed test due to "bad conversion" exception: 
![test_fail](https://user-images.githubusercontent.com/42999373/87296409-5fc2ba80-c50f-11ea-8dfc-7f389801cc07.png)

**Comment by ilyachur** [comment]
@dkurt Could you take a look?

**Comment by dkurt** [comment]
Yeah, we tried to investigate an issue but it seems like user specific problem (code is correct and works on Linux).

@PlohovEvg , can you share which hardware is used? I mean desktop or laptop vendor?

**Comment by PlohovEvg** [comment]
There were Russian letters in path to datafiles, which caused this exception. Problem solved by moving datafiles to .exe.
