### ISSUE TITLE
[Bug] [MO] MO get error when seq_len != pos_embed_len in EmbedLayerNormalization

### ISSUE THREAD

**Issue by a3213105** [openvinotoolkit/openvino#13035]
I have a customized ONNX model which used "EmbedLayerNormalization" op, the struct is shown in picture below. and I have met an error when I load model with OpenVINO. it shows the mismatch of the shape between two input of "ADD" op after "EmbedLayerNormalization".
I have check the original implement of EmbedLayerNormalization in [ONNX-Runtime](https://github.com/microsoft/onnxruntime/blob/0c6037b5abe571fc43a55ef7a9d2f846820fbe5d/onnxruntime/contrib_ops/cpu/bert/embed_layer_norm.cc) , and i found some different between ONNX-Runtime and OpenVINO. 
![image](https://user-images.githubusercontent.com/12908251/189830894-6aa44de0-516c-4547-90d9-6d2eab4fdb80.png)

**Comment by andrei-kochin** [comment]
Hello @a3213105,

Thank you for reaching OpenVINO!
Could you please let us know which version of OpenVINO do you use? any simple model reproducer that you can provide?

Could you please share the full error log which is thrown by MO and the command line used?

Thank you!

**Comment by a3213105** [comment]
The position_embeddings=512, and the real seq len = 113, then got error below：
RuntimeError: [ PARAMETER_MISMATCH ] Can not clone with new dims. Descriptor's shape: {1, 512, 768} is incompatible with provided dimensions: {1, 113, 768}.

the xml file generated by MO is this (you can remove the txt in filename to get xml file)
[error_mo.xml.txt](https://github.com/openvinotoolkit/openvino/files/9571751/error_mo.xml.txt)

**Comment by avitial** [comment]
@a3213105 could you provide steps to replicate and minimal sample reproducer? Also share a simple model reproducer. 
Please also share the full error log thrown by the Model Optimizer (with _--log_level DEBUG_) and full command used.

**Comment by avitial** [comment]
Closing this. Feel free to reopen to provide additional information and ask questions related to this topic.
