### ISSUE TITLE
[Bug] [ FRAMEWORK ERROR ]  Cannot load input model: OOM when allocating tensor with shape[3,3,128,256] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu          [[{{node RestoreV2}}]]

### ISSUE THREAD

**Issue by MiraGaikwad** [openvinotoolkit/openvino#13052]
System information (version)
OpenVINO => 2022.1
Operating System / Platform => Windows 64 Bit
Compiler => Visual Studio 2017
Problem classification: Model Conversion
Framework: TensorFlow 2.8.0
Model name: Custom CNN
Detailed description
I have trained the model in google Colab and saved file in h5 format.
I then frozen that model.
Now trying to convert that mode into IR format

I have trained the model on google Collaboratory and trying to convert the model into IR but facing below error -

[ FRAMEWORK ERROR ]  Cannot load input model: OOM when allocating tensor with shape[3,3,128,256] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
         [[{{node RestoreV2}}]]

Process followed - 

1. Model trained can be found at link below - 
https://colab.research.google.com/drive/17fCQz7YZtSnuK8NcK5SDiNJ7g_HIqBR4?authuser=1

h5 model link is - https://drive.google.com/file/d/1Tnvrqcil6VAKAsjWtH2l9RZGS9IUQN46/view?usp=sharing

2. Frozen it using below code
import tensorflow as tf
model = tf.keras.models.load_model('CNN_model.h5')
tf.saved_model.save(model,'saved_model')

3. Trying to convert this model into IR using below command 
mo --saved_model_dir saved_model --data_type FP16 --output_dir IR_model_FP16 --input_shape [1,224,224,3]

**Comment by Iffa-Meah** [comment]
@MiraGaikwad I had requested access to your file.

![image](https://user-images.githubusercontent.com/79643476/190306359-f82ced87-0ca2-4a40-a48a-a4e72d6703ec.png)

**Comment by rkazants** [comment]
@MiraGaikwad, looks that the model is not correctly re-saved from `H5` into `SavedModel` format. Please try to load your `SavedModel` format by using TF API `tf.saved_model.load` and trying infer it. Thanks!

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
