### ISSUE TITLE
Coordinate space of the head pose estimate in head-pose-estimation-adas-0001

### ISSUE THREAD

**Issue by balegajay** [openvinotoolkit/openvino#13081]
Hello,

I was currently using the head-pose-estimation-adas-0001 model in a project. 

The model description [page](https://docs.openvino.ai/2019_R1/_head_pose_estimation_adas_0001_description_head_pose_estimation_adas_0001.html) describes the outputs and inputs for the model.

However the coordinate system of the output is not mentioned.

Can anyone please tell which coordinate space is the output defined in?

Regards,

**Comment by brmarkus** [comment]
When I run the OpenVINO Open-Model-Zoo example then I get this:
![image](https://user-images.githubusercontent.com/29976962/190630075-1958c0a9-5919-42e3-bc07-81fff7f7dd80.png)

**Comment by balegajay** [comment]
Hi Markus,

The model outputs head-pose-estimation-adas-0001 yaw, pitch and roll of the head. 
I wanted to know the reference coordinate system for these angles.

See below picture from gaze estimation demo (shows the yaw, pitch and roll output from head pose model)
![grafik](https://user-images.githubusercontent.com/102429106/190632512-e9513766-1296-4eda-8c5f-9dab0130a81f.png)

**Comment by balegajay** [comment]
@jgespino @andrei-kochin  @Wovchena could any of you guys please give an explanation.

Regards

**Comment by Wovchena** [comment]
The person who trained the model no longer works here. You should revers engineer the code snipped you have in https://github.com/openvinotoolkit/open_model_zoo/issues/3558

**Comment by Wovchena** [comment]
I've extended model description in https://github.com/openvinotoolkit/open_model_zoo/pull/3561

**Comment by avitial** [comment]
PR in OMZ has been merged, closing this. I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask any questions related to this topic.
