### ISSUE TITLE
infer() only works at first inference when using external CL context

### ISSUE THREAD

**Issue by yuechengmao** [openvinotoolkit/openvino#13099]
I'm try to pass external CL context to OV for remote tensor inference.
OV version: 2022.1.0.643
OS: windows 11
code sample:
cl::Context user_context;
		cl::Device user_device;
		cl::CommandQueue user_queue;

		// get Intel iGPU OCL device, create context and queue
		{
			const unsigned int refVendorID = 0x8086;
			cl_uint n = 0;
			cl_int err = clGetPlatformIDs(0, NULL, &n);

			// Get platform list
			std::vector<cl_platform_id> platform_ids(n);
			err = clGetPlatformIDs(n, platform_ids.data(), NULL);

			for (auto& id : platform_ids) {
				cl::Platform platform = cl::Platform(id);
				std::vector<cl::Device> devices;
				platform.getDevices(CL_DEVICE_TYPE_GPU, &devices);
				for (auto& d : devices) {
					if (refVendorID == d.getInfo<CL_DEVICE_VENDOR_ID>()) {
						auto DeviceName = d.getInfo<CL_DEVICE_NAME>();
						cout << "DeviceName: " << DeviceName << endl;
						user_device = d;
						user_context = cl::Context(user_device);
						break;
					}
				}
			}
			cl_command_queue_properties props = CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE;
			user_queue = cl::CommandQueue(user_context, user_device, props);
		}

		cout << "create user OCL context&queue ok" << endl;
		auto input = model->get_parameters().at(0);
		auto output = model->get_results().at(0);

		auto in_size = ov::shape_size(input->get_output_shape(0)) * input->get_output_element_type(0).size();
		auto out_size = ov::shape_size(output->get_output_shape(0)) * output->get_output_element_type(0).size();

		cout << "in_size= " << in_size << endl;

		cl_int err;
		// Allocate shared buffers for input and output data which will be set to infer request
		cl::Buffer shared_input_buffer(user_context, CL_MEM_READ_WRITE, in_size, NULL, &err);
		{
			void* buffer = _data.get();
			user_queue.enqueueWriteBuffer(shared_input_buffer, true, 0, in_size, buffer);
		}

		cl::Buffer shared_output_buffer(user_context, CL_MEM_READ_WRITE, out_size, NULL, &err);
		{
			//void* buffer = new unsigned char [out_size];
			//memset(buffer, 0, out_size);
			//user_queue.enqueueWriteBuffer(shared_output_buffer, true, 0, out_size, buffer);
			//delete[] buffer;
		}

		auto out_tensor = ov::Tensor(output->get_output_element_type(0), output->get_output_shape(0));
		memset(out_tensor.data(), 0, out_size);

		auto remote_context = ov::intel_gpu::ocl::ClContext(core, user_queue.get());
		auto exec_net_shared = core.compile_model(model, remote_context);
		auto gpu_context = exec_net_shared.get_context().as<ov::intel_gpu::ocl::ClContext>();

		auto gpu_in_tensor = gpu_context.create_tensor(input->get_output_element_type(0), input->get_output_shape(0), shared_input_buffer);
		auto gpu_out_tensor = gpu_context.create_tensor(output->get_output_element_type(0), output->get_output_shape(0), shared_output_buffer);

		auto inf_req_shared = exec_net_shared.create_infer_request();
		inf_req_shared.set_tensor(input, gpu_in_tensor);
		inf_req_shared.set_tensor(output, gpu_out_tensor);

		start_ms = duration_cast<milliseconds>(
			system_clock::now().time_since_epoch()
			);
		for (int cnt = 0; cnt < niters; cnt++) {
			//inf_req_shared.infer(); // here, when I use this one, only the first inference works, stuck at second round.
			inf_req_shared.start_async(); // this one works.
			inf_req_shared.wait();
		}
		end_ms = duration_cast<milliseconds>(
			system_clock::now().time_since_epoch()
			);

in the for loop above, the inf_req_shared.infer() cannot consecutively run, only the first inference. instead, by using start_async+wait it works fine. probably there is bug inside the synchronous function infer().

**Comment by ilya-lavrenov** [comment]
CC @p-durandin @vladimir-paramuzov
