### ISSUE TITLE
TFLite int8 model

### ISSUE THREAD

**Issue by NikolaMr** [openvinotoolkit/openvino#131]
Is it somehow possible to use TFLite int8 model for inference?

I can't export my model properly with the provided tools since the tools don't support regression (and this model solves a regression problem), but classification and object detection only at the moment.

Best regards,
Nikola

**Comment by shubha-ramani** [comment]
@NikolaMr 

Can you kindly give a link to the model ? 

Thanks,

Shubha

**Comment by NikolaMr** [comment]
I can't give you a link to the model since it is a production model.

Model optimizer works as expected, the calibration tool is the one causing me problems since it only supports object detection and classification as it is stated in the http://docs.openvinotoolkit.org/2018_R5/_samples_calibration_tool_README.html.

Is regression supported in the latest OpenVINO revision?

Best regards,
Nikola

**Comment by elvin-nnov** [comment]
DLDT does not support TFLite models, but you can feed TF model with fake quantizations (input to TF Lite) to Model Optmizer and it will produced IR whcih will be infrenced in int8 mode on CPU. One more important note - CPU does not support zero point != 0 and have quantization range [-127,+127], it does not mean that model will be rejected, it will be inferenced, but activations and weigths will be requantized that might affect accuracy. It does not matter for redundant models, but for for tight models like Mobilenet it is significant.
There are more restrictions dedicated to quantization - please see https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Int8Inference.html for reference which layers are supported in int8 mode

one more note - TF models with fake quantization were enabled in R1'19 release (that correspond to this https://github.com/opencv/dldt/tree/2019 branch)

**Comment by NikolaMr** [comment]
Thank you @elvin-nnov!

From what I have seen, fake quantization is supported only if one trains the model with fake quantization enabled. Is it possible to use fake quantization without retraining the model since I have an already trained model?

**Comment by elvin-nnov** [comment]
in this case you need to use calibration flow: https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Int8Inference.html

**Comment by NikolaMr** [comment]
The problem with this tool is that it doesn't support regression at the moment so this isn't the solution to my problem.

However, thank you for your help and engagement! :)

**Comment by andriyrizhiy** [comment]
Can i quantizate model to int8 with model optimizer? Can i decrease .bin file size to int8 with openvino?

**Comment by shubha-ramani** [comment]
@andriyrizhiy 
Yes you can definitely decrease the .bin file size and quantize the model to INT8. As  @elvin-nnov  recommended, please take a look at [https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Int8Inference.html](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Int8Inference.html).

Not all layers can be converted to INT8 though. If they can't be converted to INT8 then they'll remain at FP32 as a fallback.

Hope it helps,

Shubha

**Comment by lazarevevgeny** [comment]
Closing as the solution had been provided.
