### ISSUE TITLE
RuntimeError: While validating ONNX node '<Node(Resize): Resize_26>': Check 'low >= 0 && up >= 0' failed at core/src/validation_util.cpp:1318

### ISSUE THREAD

**Issue by XYZ-916** [openvinotoolkit/openvino#13115]
I got an error as follows:

 net = ie.read_model(args.onnx_path)
RuntimeError: While validating ONNX node '<Node(Resize): Resize_26>':
Check 'low >= 0 && up >= 0' failed at core/src/validation_util.cpp:1318

Can you tell me the methods I can try to solve the problem? Thank you!

**Comment by zulkifli-halim** [comment]
Hi @XYZ-916, could you share the model that you are using with us? Also, please provide the step to reproduce the issue.

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to reopen if further assistance is needed.
