### ISSUE TITLE
Problems occurred using OpenVino2021.4.752

### ISSUE THREAD

**Issue by fanxiaochen456** [openvinotoolkit/openvino#13160]
When I call openvino2020 version for deployment in my own project, it is very successful. When I change openvino2020 version to openvino2021.4.752, when using InferenceEngine::Core ie, C++ will show the following error: 0x00007FF9EB683B29 exception at cf_test.exe: Microsoft C++ exception: InferenceEngine: : GeneralError, located in the memory location 0 x000000be2b97eba0 place,

What is the reason for this?

**Comment by andrei-kochin** [comment]
Hello @fanxiaochen456,

Thank you for reaching OpenVINO!

Could you please provide a bit more details about the call stack and the steps causing the error?
By the way, is the same issue visible on 2022.1 release?

Best regards,
Andrei

**Comment by fanxiaochen456** [comment]
@andrei-kochin Hello Thank you very much for your suggestion, but the interface function of the algorithm 2022.1 that I want to deploy is not supported, and the ONNX model of the algorithm cannot be directly used in the version 2020.4. The error message that the conversion model does not support OPT11 appears, but the OpenVino export of version 2021.4.752 is OK. When using OpenVino 2021.4.752 in a project, this error message will appear: Microsoft C++ exception: InferenceEngine: :  The GeneralError, located in the memory location 0 x000000Be2B97eBa0 Place, is that because it conflicts with some of the libraries in the system or some of the libraries in this project?

**Comment by fanxiaochen456** [comment]
When I use OpencV2021.4.752 in another newly opened project, there will be no error, but as long as it is added to that project, there will be a problem. If possible, I can provide the corresponding project.

**Comment by ilya-lavrenov** [comment]
@fanxiaochen456 please, provide your project. Using words it's hard to understand what interface is not available and you experience GeneralError exception.

**Comment by andrei-kochin** [comment]
@fanxiaochen456 do you have any updates for us?

**Comment by avitial** [comment]
Closing this, feel free to reopen to provide the requested information or ask any questions related to this topic.
