### ISSUE TITLE
Axes input must be constant

### ISSUE THREAD

**Issue by yinzww** [openvinotoolkit/openvino#13164]
When I use OpenVino to accelerate video classification algorithm TSM，error occured：

Axes input must be constant...Maybe because numbers of channel dimension changed while model inferencing?
(1, 16, 3, 224, 224) -> (1, 48, 224, 224)，is there any problem?

![image](https://user-images.githubusercontent.com/39438193/191718129-81a76ad0-509d-4952-86ff-c8dc3ed06e8b.png)

How to solve the problem？

**Comment by mlukasze** [comment]
hi @yinzww
thank you for reaching us out!
Let us check it and look for a reason and possible fix.
Please stay tune :)

**Comment by mateusztabaka** [comment]
Looks line an old version of openvino. What version do you use currently? Can you try with 2022.2? We've had such restriction in the past in Slice (https://github.com/openvinotoolkit/openvino/commit/6855efd3151372e251d1bbb5975a77a9e2b382da#diff-3f1b917ca921065f5221c10871c0dd7abed41fdd274cb18586ec0c2510319898L149-L153), but it should be solved now.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed.

Feel free to reopen and provide additional information or ask any questions related to this topic.
