### ISSUE TITLE
OpenCV 4.4 with Inference Engine 

### ISSUE THREAD

**Issue by LorBordin** [openvinotoolkit/openvino#1317]
I've got a script that uses a yolov4 (for which I need opencv 4.4) and a pretrained OpenVINO model.
However I'm not able to build OpenCV 4.4 with Inference Engine. Is there a way to do it?

**Comment by alalek** [comment]
Workaround: use `releases/2020/4` branch instead of `master`.

**Comment by jgespino** [comment]
Hi @LorBordin 

Please let us know if the suggested workaround worked for you.

Regards,
Jesus

**Comment by LorBordin** [comment]
Hi @jgespino 

I haven't tried yet.

**Comment by LorBordin** [comment]
I have downloaded the `releases/2020/4` branch but I've not be able to install it.
