### ISSUE TITLE
OpenVINO does not support the following ONNX operations: com.microsoft.FusedConv [Bug]

### ISSUE THREAD

**Issue by PaulCahuana** [openvinotoolkit/openvino#13177]
##### System information
- OpenVINO => 2022.1.0
- Operating System / Platform => Ubuntu 22.04
- Problem classification: Model Conversion
- Framework: ONNX
- Architecture name: OpenSeeFace  from (https://github.com/emilianavt/OpenSeeFace)
      - Model name: lm_model3_opt.onnx

##### Detailed description
I was trying to load the model with openvino but I got  the error: 
"RuntimeError: Check 'unknown_operators.empty()' failed at frontends/onnx/frontend/src/core/graph.cpp:133:
OpenVINO does not support the following ONNX operations: com.microsoft.FusedConv"
##### Steps to reproduce

from openvino.runtime import Core
ie = Core()
model= ie.read_model(set_config_value("lm_model3_opt.onnx"))
 * and after I got the error *

So, do you have plans to add the "com.microsoft.FusedConv" layer?

**Comment by campos537** [comment]
Hey guys, I have the same issue when trying to convert this OpenSee model using the OpenVINO Workbench.

**Comment by andrei-kochin** [comment]
Hello @PaulCahuana, @campos537,

Thank you for reaching OpenVINO!

This operation is not from the standard ONNX opset while from the Microsoft ONNX RT extended opset which we haven't yet claimed to support. Actually there are some other models with such fused ops in our backlog and we are looking into it.

We should discuss this internally how to properly proceed with that. Stay tuned!

CC @mlukasze @tomdol

**Comment by PaulCahuana** [comment]
> Hello @PaulCahuana, @campos537,
> 
> Thank you for reaching OpenVINO!
> 
> This operation is not from the standard ONNX opset while from the Microsoft ONNX RT extended opset. Currently supported fused ops are listed [here ](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op/com.microsoft)
> 
> We should discuss this internally how to properly proceed with that. Stay tuned!
> 
> CC @mlukasze @tomdol

Sure. Thanks for all!

**Comment by mbencer** [comment]
Hello @PaulCahuana!
The support of `FusedConv` was added in https://github.com/openvinotoolkit/openvino/pull/13553
The model `lm_model3_opt.onnx` can be loaded and inference now.
Tested via `benchmark_app` (`./benchmark_app -shape [1,3,224,224] -m lm_model3_opt.onnx`).

Please let me know, if the change conver all your cases and if we can close the issue.

**Comment by campos537** [comment]
Wow, that is really great! This model is awesome!

**Comment by Apollo9999** [comment]
Detailing Information of  com.microsoft.FusedConv   


The fused convolution operator schema is the same as Conv besides it includes an attribute activation.
Version

This version of the operator has been available since version 1 of the 'com.microsoft' operator set.
Attributes

activation : string
activation_params : list of floats
auto_pad : string
dilations : list of ints
group : int
kernel_shape : list of ints
pads : list of ints
strides : list of ints

Inputs (2 - 4)

X : T
W : T
B (optional) : T
Z (optional) : T

Outputs

Y : T

Type Constraints

T : tensor(float16), tensor(float), tensor(double)
    Constrain input and output types to float tensors

**Comment by avitial** [comment]
Closing this, as PR with support for _FusedConv_ op has been merged. Feel free to reopen to ask any questions related to this topic.
