### ISSUE TITLE
[Bug] Openvino program stucked when loading network.

### ISSUE THREAD

**Issue by LHTcode** [openvinotoolkit/openvino#13182]
ROS_INFO("model_path:%s", (xml_path_ + bin_path_).c_str());
  Core core;
  auto model = core.ReadNetwork(xml_path_, bin_path_);
  std::vector<std::string> devices = core.GetAvailableDevices(); 
  for (std::string device : devices) {
    LOGD("GetAvailableDevices: %s", device.c_str());
  }
  ROS_INFO("BEFORE LOADNETWORK TO GPU");
  auto compiled_model = core.LoadNetwork(model, "GPU");    // STUCK HERE
  ROS_INFO("AFTER CREATE INFER REQUEST");

**Console output**
 /pose_solver_node: [OpvnProcessor::initialize]: model_path:/home/xxx/rm_ws/src/opvn_proc/model/mobilenetv2_32.xml/home/xxx/rm_ws/src/opvn_proc/model/mobilenetv2_32.bin
 /pose_solver_node: [E:] [BSL] found 0 ioexpander device
 /pose_solver_node: [/home/xxx/rm_ws/src/rm_opvn_proc/src/opvn_plugins.cpp][initialize][71]: GetAvailableDevices: CPU
 /pose_solver_node: [/home/xxx/rm_ws/src/rm_opvn_proc/src/opvn_plugins.cpp][initialize][71]: GetAvailableDevices: GNA
 /pose_solver_node: [/home/xxx/rm_ws/src/rm_opvn_proc/src/opvn_plugins.cpp][initialize][71]: GetAvailableDevices: GPU
 /pose_solver_node: [OpvnProcessor::initialize]: BEFORE LOADNETWORK TO GPU

**Comment by ilya-lavrenov** [comment]
Hi @LHTcode 

Without any topology it's hard to say what happens internally. Do you have some preproducer? 
Does it change something if we don't call `GetAvailableDevices` before `LoadNetwork` to GPU?

**Comment by brmarkus** [comment]
Can you check the system CPU-load?
I assume you see high CPU-load - as while loading a model for the GPU-plugin then OpenVINO is compiling OpenCL kernels in the background.
Depening on the model and the system-performance this OpenCL kernel compilation could take multiple minutes.

Can you export the ENV variable "cl_cache_dir" (pointing it to a writable directory) - and then watch the folder, do you see files being created in the folder, is the number growing while you see the `LoadNetwork()` being stuck?

**Comment by LHTcode** [comment]
> Hi @LHTcode
> 
> Without any topology it's hard to say what happens internally. Do you have some preproducer? Does it change something if we don't call `GetAvailableDevices` before `LoadNetwork` to GPU?



> Can you check the system CPU-load? I assume you see high CPU-load - as while loading a model for the GPU-plugin then OpenVINO is compiling OpenCL kernels in the background. Depening on the model and the system-performance this OpenCL kernel compilation could take multiple minutes.
> 
> Can you export the ENV variable "cl_cache_dir" (pointing it to a writable directory) - and then watch the folder, do you see files being created in the folder, is the number growing while you see the `LoadNetwork()` being stuck?

The CPU usage does reach 100%, but there is no output from cl_cache_dir.I have executed export cl_cache_dir=/home/dynamicx/Documents/cl_cache in terminal.

**Comment by LHTcode** [comment]
> Hi @LHTcode
> 
> Without any topology it's hard to say what happens internally. Do you have some preproducer? Does it change something if we don't call `GetAvailableDevices` before `LoadNetwork` to GPU?

It's normal when I don't call GetAvailableDevices and run core.LoadNetwork(model, "CPU").

**Comment by brmarkus** [comment]
Which version of OpenVINO do you use, is it 2021.x or 2022.x?
Which OS do you use?
Which HW (CPU, GPU) are you using (can you share excerpts of `lscpu` and `lspci | grep VGA`)?

Depending on the OpenVINO version you might try to enable the model-cache (e.g. "https://docs.openvino.ai/2021.4/openvino_docs_IE_DG_Model_caching_overview.html") instead of exporting the ENV variable and then watch the specified folder for growing files.

**Comment by brmarkus** [comment]
> 

What do you mean with "normal", it's working, not stuck anylonger?

**Comment by LHTcode** [comment]
> > 
> 
> What do you mean with "normal", it's working, not stuck anylonger?

it means it's working on cpu

**Comment by LHTcode** [comment]
> 

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           140
Model name:                      11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Stepping:                        1
CPU MHz:                         3777.925
CPU max MHz:                     4700.0000
CPU min MHz:                     400.0000
BogoMIPS:                        5606.40
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       128 KiB
L2 cache:                        5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled v
                                 ia prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Vulnerable: eIBRS with unprivileged eBPF
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

**Comment by LHTcode** [comment]
> lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Device 9a49 (rev 01)

**Comment by LHTcode** [comment]
> Which version of OpenVINO do you use, is it 2021.x or 2022.x? Which OS do you use? Which HW (CPU, GPU) are you using (can you share excerpts of `lscpu` and `lspci | grep VGA`)?
> 
> Depending on the OpenVINO version you might try to enable the model-cache (e.g. "https://docs.openvino.ai/2021.4/openvino_docs_IE_DG_Model_caching_overview.html") instead of exporting the ENV variable and then watch the specified folder for growing files.

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           140
Model name:                      11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Stepping:                        1
CPU MHz:                         3777.925
CPU max MHz:                     4700.0000
CPU min MHz:                     400.0000
BogoMIPS:                        5606.40
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       128 KiB
L2 cache:                        5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled v
                                 ia prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Vulnerable: eIBRS with unprivileged eBPF
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

**Comment by ilya-lavrenov** [comment]
@LHTcode it seems that initialization of some other plugin via calling `GetAvailableDevices` leads to dirty program state later. Could you please try to rename plugins one by one physically on file system (to prevent its loading) and check which one is a guilty? 
I suppose we can start with HDDL (I sin on this one), then MYRIAD, GNA, GPU
