### ISSUE TITLE
Unknown model format! Cannot find reader for model format: xml and read the model: bvlc_alexnet.xml. Please check that reader library exists in your PATH.

### ISSUE THREAD

**Issue by justcainiao** [openvinotoolkit/openvino#1325]
I tried to run the example : "Image Classification C++ Sample Async", and generate .bin and .xml of the alexnet using mo_caffe.py. 

But when I run  "classification_sample_async.exe -i images.jfif -m bvlc_alexnet.xml -d CPU",    an error occured:

[ ERROR ] Unknown model format! Cannot find reader for model format: xml and read the model: bvlc_alexnet.xml. Please check that reader library exists in your PATH.

I use windows10 ,vs2019

any suggestions?

**Comment by brmarkus** [comment]
Can you run any C/C++ sample using any model on your system?

You might have not called "setupvars.bat" under "C:\Program Files (x86)\IntelSWTools\openvino\bin\" (see https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_windows.html#set-the-environment-variables)?

**Comment by justcainiao** [comment]
not yet , the first C++ example,   I have called  "setupvars.bat"   and  not goes well, 
I found  the error occured in  function " CNNNetwork network = ie.ReadNetwork(FLAGS_m);"   the function is in   format_reader.dll ?

**Comment by brmarkus** [comment]
Which version of OpenVINO have you installed?

Can you share the command-line of how you converted the model, please (and where you got the model from, where you downloaded it)?

You might want to check the model-xml file with a tool like "Netron", whether the file could be read and understood, maybe something went wrong with your XML/BIN files.

**Comment by justcainiao** [comment]
I download the model from http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel    
the cmd of convert model is  :  
 python mo_caffe.py    --input_shape=[1,3,227,227]  --input=data --mean_values=data[104.0,117.0,123.0]  --output=prob   --input_model=alexnet.caffemodel  --input_proto=alexnet.prototxt      

**the xml file can not be opened by Netron**     is that  the  wrong place?

**Comment by jgespino** [comment]
Hi @justcainiao 

What version of OpenVINO are you using? I tested the model and sample application on the latest release (2020.4) and did not see the issue. 

**System details**
Windows 10
OpenVINO toolkit 2020.4
Cmake 3.18.0-rc4
Microsoft VS 2019
Python 3.6.5 (64-bit)

**Downloaded model and prototxt**
https://raw.githubusercontent.com/BVLC/caffe/88c96189bcbf3853b93e2b65c7b5e4948f9d5f67/models/bvlc_alexnet/deploy.prototxt
http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel

**Sourced Environment Variables**
`
"C:\Program Files (x86)\IntelSWTools\openvino\bin\setupvars.bat"
`

**Model Optimizer Command**
```
python "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\model_optimizer\mo.py" --framework caffe --input_shape [1,3,227,227] --input data --mean_values data[104.0,117.0,123.0] --input_model bvlc_alexnet.caffemodel --input_proto deploy.prototxt
```

**Comment by justcainiao** [comment]
thx  @brmarkus for your help， I delete the project，and   generate new projects use “build_samples_msvc.bat” ，and the error disappear， I think the problem might be  caused by  env path。
