### ISSUE TITLE
openvino Intel face_detection_retail 14 outputs - what are they?

### ISSUE THREAD

**Issue by willmendil** [openvinotoolkit/openvino#1329]
Hi, I'm playing around with the face_detection_retail_0004 with gocv. 
When I run the model I get a lot more outputs than are described in the documentation

https://docs.openvinotoolkit.org/latest/omz_models_intel_face_detection_retail_0004_description_face_detection_retail_0004.html

Indeed here are the raw values I get 

```
0.000 1.000 0.999 0.425 0.454 0.745 0.827 0.000 1.000 0.036 0.555 -0.002 0.985 0.298 -1.000 
```

According to the docs, the labels are as follow 

```
image_id     label       conf       x_min        y_min       x_max      y_max    ------ What are those???
0.000          1.000       0.999     0.425        0.454        0.745       0.827      0.000 1.000 0.036 0.555 -0.002 0.985 0.298 -1.000 
```

These values seam to change when I move my face. I wonder if it follows the orientation or something, but I cannot seem to find any description of this output online. Any clues?

**Comment by jgespino** [comment]
Hi @willmendil 

As you mentioned, the face_detection_retail_0004 model has net outputs with blob shape [1,1,N,7] where N is the number of detection. Each detection has the following format, [image_id, label, conf, x_min, y_min, x_max, y_max]. What you are seeing are multiple detection with lower confidence level or false positives. 

In your example above, you have two detection. The x and y values will change as the location of the boundary box chances (depending on the location of the face in the camera frame).
image_id     label       conf       x_min        y_min       x_max      y_max
0.000          1.000       0.999     0.425        0.454        0.745       0.827
0.000          1.000       0.036     0.555       -0.002        0.985       0.298 

Not sure where the -1.000 came from, maybe part of the next detection?

Regards,
Jesus
