### ISSUE TITLE
about build error for onednn

### ISSUE THREAD

**Issue by leizhu1989** [openvinotoolkit/openvino#13401]
hello，auther！
when I build this project on windows11,I got so many error like:

6>C:\downloading\openvino\src\plugins\intel_cpu\src\dnnl_descriptor.h(16,71): error C2039: "desc": is not the member of "dnnl::convolution_forward"  (source file C:\downloading\openvino\src\plugins\intel_cpu\src\nodes\matmul.cpp)
6>C:\downloading\openvino\src\plugins\intel_cpu\thirdparty\onednn\include\oneapi/dnnl/dnnl.hpp(4820): message : See statement 
 for “dnnl::convolution_forward” (source file C:\downloading\openvino\src\plugins\intel_cpu\src\nodes\matmul.cpp)
6>C:\downloading\openvino\src\plugins\intel_cpu\src\dnnl_descriptor.h(16): error C2065: “desc”: undeclared identifier (source file C:\downloading\openvino\src\plugins\intel_cpu\src\nodes\matmul.cpp)

my openvino is master branch and onednn is v2.6_for_ie_master, why is it?

**Comment by leizhu1989** [comment]
thank you for your reply, for thirdparty, I do not use    *git submodule update --init --recursive* . I download thirdparty one by one because of my poor internet, and I put them to its path. the protobuf version I used is 3.18.2 ,beacuse when I use high version ,there is a error : Protocol Buffers requires at least c++14 ,but 
is configured for c++11

Maybe I use the wrong method to download the thirdparty?

when I use update:
C:\downloading\openvino>git submodule update
fatal: destination path 'C:/downloading/openvino/thirdparty/protobuf/protobuf' already exists and is not an empty directory.
fatal: clone of 'https://github.com/protocolbuffers/protobuf.git' into submodule path 'C:/downloading/openvino/thirdparty/protobuf/protobuf' failed
Failed to clone 'thirdparty/protobuf/protobuf'. Retry scheduled
fatal: destination path 'C:/downloading/openvino/thirdparty/protobuf/protobuf' already exists and is not an empty directory.
fatal: clone of 'https://github.com/protocolbuffers/protobuf.git' into submodule path 'C:/downloading/openvino/thirdparty/protobuf/protobuf' failed
Failed to clone 'thirdparty/protobuf/protobuf' a second time, aborting

C:\downloading\openvino>git submodule update
Cloning into 'C:/downloading/openvino/thirdparty/protobuf/protobuf'...
fatal: unable to access 'https://github.com/protocolbuffers/protobuf.git/': Failed to connect to github.com port 443 after 21055 ms: Timed out
fatal: clone of 'https://github.com/protocolbuffers/protobuf.git' into submodule path 'C:/downloading/openvino/thirdparty/protobuf/protobuf' failed
Failed to clone 'thirdparty/protobuf/protobuf'. Retry scheduled
Cloning into 'C:/downloading/openvino/thirdparty/protobuf/protobuf'...
fatal: unable to access 'https://github.com/protocolbuffers/protobuf.git/': OpenSSL SSL_read: Connection was reset, errno 10054
fatal: clone of 'https://github.com/protocolbuffers/protobuf.git' into submodule path 'C:/downloading/openvino/thirdparty/protobuf/protobuf' failed
Failed to clone 'thirdparty/protobuf/protobuf' a second time, aborting

**Comment by leizhu1989** [comment]
ok, I know it, thank you for your reply

**Comment by ilyachur** [comment]
@leizhu1989 Does the submodules update help you to solve the issue?

**Comment by leizhu1989** [comment]
yeah!  when I use git submodule update --init --recursive for more times, I am successed build it.  But, I can not find the "include" list for installing ,only "bin" files in my openvino root directory. By the way, can openvino set the number of CPUs used?  I don’t want to use all cpu cores to inference, thank you

**Comment by leizhu1989** [comment]
> @leizhu1989 Does the submodules update help you to solve the issue?

yeah! when I use git submodule update --init --recursive for more times, I am successed build it. But, I can not find the "include" list for installing ,only "bin" files in my openvino root directory. By the way, can openvino set the number of CPUs used? I don’t want to use all cpu cores to inference, thank you

**Comment by avitial** [comment]
@leizhu1989 try using the _inference_num_threads_ property to set the number of threads to use for inference on the CPU. Refer to [Setting Properties for Compiled Model](https://docs.openvino.ai/latest/openvino_docs_OV_UG_query_api.html#setting-properties-for-compiled-model) for info. Setting this value to 1 results in application utilizing a single CPU core, refer to mpstat output for cpu usage below. 

`$ benchmark_app -d CPU -niter 30000 -api sync -m age-gender-recognition-retail-0013.xml -nthreads 1
`

![image](https://user-images.githubusercontent.com/20826577/199809220-d579fe06-e614-4cc5-a74d-aae5f9de76a2.png).


Closing this, I hope this and previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions related to this topic.
