### ISSUE TITLE
Yolov3 Python Demo erroneous detections

### ISSUE THREAD

**Issue by GotG** [openvinotoolkit/openvino#1341]
Using `object_detection_demo_yolov3_async.py` produces the following output on yolov3 tiny coco model:

![errors](https://user-images.githubusercontent.com/61444721/87575828-2dfd4f80-c6d9-11ea-8225-4fd3a74ef8c7.png)

**Comment by jgespino** [comment]
Hi @GotG 

Try adjusting the intersection over union threshold for overlapping (`-iout `or `--iou_threshold`) when running the `object_detection_demo_yolov3_async` demo. 

Couple of questions:

- Which OpenVINO version are you using?
- How did you convert the model (model optimizer command)?
- Do you see these overlapping boundary boxes on every object or certain objects? 

Regards,
Jesus

**Comment by jgespino** [comment]
Closing issue, please re-open if you need further assistance.
