### ISSUE TITLE
[Bug]Error using paddleOCR model

### ISSUE THREAD

**Issue by kc-w** [openvinotoolkit/openvino#13434]
##### System information (version)
- OpenVINO => 2020.2
- Operating System / Platform => Windows10 64 Bit
- Compiler => Visual Studio 2019
- Model name: ch_PP-OCRv3_det_infer (if applicable)

##### Detailed description
I used the benchmark_app to test the paddleOCR model. Using GPU gives me an error at the following line
![image](https://user-images.githubusercontent.com/39193398/195239537-17b21240-32a6-4481-8b6e-1e6c5034336d.png)
I used the command: -m E:\projectTest\FastDeploy\build\bin\Release\ch_PP-OCRv3_det_infer\inference.pdmodel -i C:\Users\wkc\Desktop\test.bmp -d CPU

**Comment by mlukasze** [comment]
Hey @kc-w 
Thank you for reaching us out and sorry for your inconvenience. 
We will check it out as soon as we can and will back to you. Stay tune :)

**Comment by yuxu42** [comment]
@liubo-intel Could you please take a look? 

@kc-w could you please clarify whether the issue happens with CPU or GPU or both in you side?

**Comment by kc-w** [comment]
If this happens on the gpu, the cpu executes the following function normally
![](https://user-images.githubusercontent.com/39193398/195239537-17b21240-32a6-4481-8b6e-1e6c5034336d.png)

**Comment by kc-w** [comment]
this happens on the gpu, the cpu executes the following function normally
![](https://user-images.githubusercontent.com/39193398/195239537-17b21240-32a6-4481-8b6e-1e6c5034336d.png)

**Comment by brmarkus** [comment]
@kc-w can you share with Intel CPU and which Intel GPU you are using, is it an SoC with integrated iGPU or a discrete dGPU, please?
Which graphics driver version is installed in your environment?

Is it Python-code or C/C++-code? Not sure there is a semicolon at the end of your core.compile() line.
Can you name the Python/VisualStudioCode version you are using, please?

**Comment by PiotrKrzem** [comment]
> @kc-w can you share with Intel CPU and which Intel GPU you are using, is it an SoC with integrated iGPU or a discrete dGPU, please? Which graphics driver version is installed in your environment?
> 
> Is it Python-code or C/C++-code? Not sure there is a semicolon at the end of your core.compile() line. Can you name the Python/VisualStudioCode version you are using, please?

I believe it's C++/VS 2019, as stated in the issue comment.

@kc-w Did you compile openvino with appropriate flags (DENABLE_INTEL_GPU=ON)?

**Comment by kc-w** [comment]
> and @kc-w , another thing that we want to double confirm with you: in your 'System information' description, I suppose OpenVINO version 'OpenVINO => 2020.2' is spelling mistake, the actual OpenVINO version you are using is '2022.2.0', right? :)

yes

**Comment by kc-w** [comment]
> > @kc-w can you share with Intel CPU and which Intel GPU you are using, is it an SoC with integrated iGPU or a discrete dGPU, please? Which graphics driver version is installed in your environment?
> > Is it Python-code or C/C++-code? Not sure there is a semicolon at the end of your core.compile() line. Can you name the Python/VisualStudioCode version you are using, please?
> 
> I believe it's C++/VS 2019, as stated in the issue comment.
> 
> @kc-w Did you compile openvino with appropriate flags (DENABLE_INTEL_GPU=ON)?

I use build_samples_msvc.bat for compiling, do not know how to set DENABLE_INTEL_GPU=ON,Can you tell me?
![image](https://user-images.githubusercontent.com/39193398/195280541-d5694e5c-6586-420d-9a0b-02cf225dd367.png)

**Comment by kc-w** [comment]
> @kc-w can you share with Intel CPU and which Intel GPU you are using, is it an SoC with integrated iGPU or a discrete dGPU, please? Which graphics driver version is installed in your environment?
> 
> Is it Python-code or C/C++-code? Not sure there is a semicolon at the end of your core.compile() line. Can you name the Python/VisualStudioCode version you are using, please?

CPU is i7-9700
GPU is UHD Graphics 630 Driver version is 31.0.101.2111

**Comment by liubo-intel** [comment]
Hi, @kc-w : about the 'ch_PP-OCRv3_det_infer' Paddle models you are using, is it dynamic models? if so, I think that maybe the reason why you can't run it successfully with OpenVINO GPU plugin.  OpenVINO CPU plugin supports dynamic models now. As far as I know, GPU plugin currently not fully support dynamic feature yet.

if so, you can have a try to use OpenVINO 'Model Optimizer' to convert this Paddle model to static shape IR before use it in inference runtime:
OpenVINO 'Model Optimizer' Guide document: _https://docs.openvino.ai/latest/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html_
For specific Paddle model: 
_https://github.com/openvinotoolkit/openvino/blob/master/docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Paddle.md_

And there's an example on how to convert 'ch_ppocr_mobile_v2.0_det' model:
`python mo.py --input_model ./ch_ppocr_mobile_v2.0_det_infer/inference.pdmodel --output_dir ./ch_ppocr_mobile_v2.0_det_infer/IR --input_shape=[1,3,640,640] --framework=paddle --data_type=FP32 --reverse_input_channels --input=x --output=save_infer_model/scale_0.tmp_1`

Then you can have a try with generated IR and GPU Plugin:
`./benchmark_app -m ./ch_ppocr_mobile_v2.0_det_infer/IR/inference.xml -d GPU -nireq 4 -niter 10 `

**Comment by kc-w** [comment]
@liubo-intel  thank you very much for your help!

**Comment by avitial** [comment]
Closing this, feel free to reopen to ask any questions related to this topic.
