### ISSUE TITLE
[Bug] openvino reports OpenCL compatibility on non compatible Intel GPUs

### ISSUE THREAD

**Issue by JulienMaille** [openvinotoolkit/openvino#13447]
##### System information (version)
- OpenVINO => 2022.1 & 2022.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2022
- Problem classification => Error message

##### Detailed description
When running inference with OpenCV compiled with OpenVino support on a PC with an **i7-3770 and an Intel HD4000**.
Some old Intel CPUs with an integrated GPU seems to be detected by OpenVino as capable of running with `clDNNPlugin.dll` but fails with the following error:
![image](https://user-images.githubusercontent.com/182520/195301340-a902fcf0-3ed6-406e-93f8-235023ac2025.png)

Tested and reproduced with 2022.2 and `openvino_intel_gpu_plugin.dll`
![image](https://user-images.githubusercontent.com/182520/195336063-6d5b589f-cb24-42e5-964f-46b050fadbd0.png)

##### Question
How does OpenVino checks for OpenCL compatibility?
It seems the error above is due to the GPU supporting OpenCL 1.2 but the requirement seems to be 2.0
Is there a way to filter those old GPUs?

**Comment by zulkifli-halim** [comment]
Hi @JulienMaille, you are using an old Intel CPU (gen 3). The supported CPU for OpenVINO is from 6th to 13th generation Intel Core. processor. For more info, you can refer to [Target System Platforms](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html).

**Comment by JulienMaille** [comment]
> Hi @JulienMaille, you are using an old Intel CPU (gen 3). The supported CPU for OpenVINO is from 6th to 13th generation Intel Core. processor. For more info, you can refer to [Target System Platforms](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html).
> 

Hi, yes I know this hardware is not support. But I was hoping the CPU generation could be detected to avoid trying to load a dll that will fail with the error message I posted above.

**Comment by zulkifli-halim** [comment]
Hi @JulienMaille. On Windows, OpenCL runtime is a part of the GPU driver, Intel HD4000 supports OpenCL 1.2 and it is not supported by OpenVINO. You may refer [here](https://docs.openvino.ai/2022.1/openvino_docs_install_guides_installing_openvino_windows.html#Install%252520GPU), this will help to check if you require driver installation 

OpenVINO has a [hello_query_device sample](https://docs.openvino.ai/latest/openvino_inference_engine_ie_bridges_python_sample_hello_query_device_README.html) application for all available OpenVINO Runtime devices and prints their supported metrics and plugin configuration parameters. With this option, you can check whether Intel XMX(Xe Matrix Extension) feature is properly recognized or not.

**Comment by vladimir-paramuzov** [comment]
@JulienMaille We target OCL 2.0+ indeed. I've implemented a [draft](https://github.com/vladimir-paramuzov/openvino/tree/ocl_1.2) of changes which add several things:
1. cmake option `INTEL_GPU_TARGET_OCL_VERSION` to control OCL API version used in GPU plugin (default is 200 == 2.0)
2. Check for supported OCL version in device detector. If plugin is compiled for OCL 2.0, but given device doesn't support it, then the device is rejected and won't be reported as available.
3. Several fixes to compile with OCL 1.2

Unfortunately, I don't have an old CPU on hand to test that patch at the moment. Would you be able to check if these changes resolve your issue? So if you compile OV with default options, then GPU plugin is expected to report 0 available devices. If you configure cmake with `-DINTEL_GPU_TARGET_OCL_VERSION=120` option, GPU plugin is expected to detect your GPU and hopefully will be able to infer models (at least if OCL driver works fine on your system)

**Comment by JulienMaille** [comment]
Thank you very much, I will compile that branch and report back

**Comment by JulienMaille** [comment]
@vladimir-paramuzov How am I supposed to compile the GPU plugin if my build machine does not have an Intel GPU?
I followed the readme https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows#build-steps but the GPU drivers won't install since no relevant hardware is detected

**Comment by vladimir-paramuzov** [comment]
@JulienMaille You don't need GPU drivers to compile the plugin (only to run inference). Any issues with compilation using steps from the guide?

**Comment by JulienMaille** [comment]
> @JulienMaille You don't need GPU drivers to compile the plugin (only to run inference). Any issues with compilation using steps from the guide?
```
    1218 Avertissement(s)
    0 Erreur(s)
```
no errors but I did not compile the `openvino_intel_gpu_plugin.dll` see

![image](https://user-images.githubusercontent.com/182520/196107634-2dc7b574-004c-496f-b8a9-107cc8782248.png)

**Comment by JulienMaille** [comment]
I was able to compile it from msvc. I will try it asap, however potential deployment is blocked by #13493

**Comment by zulkifli-halim** [comment]
Since the original issue has been resolved, I will close this issue. Feel free to reopen if you need further assistance.
