### ISSUE TITLE
[Bug] Memory grow and performance drop when using dynamic shape graph based nn model.

### ISSUE THREAD

**Issue by art3na** [openvinotoolkit/openvino#13440]
System information (version)
- OpenVINO => 2022.1.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

Detailed description

Memory grow and performance drop when setting.

core ov::core;
core.set_property("CPU",  ov::num_streams(24));
or
core.compile_model(model, "CPU", ov::hint::performance_mode(ov::hint::PerformanceMode::THROUGHPUT);

Model it self is graph based with dynamic shape input. I use it as static object.
If shape of input is fixed size there is no memory grow or performance drop.

**Comment by mlukasze** [comment]
hey @art3na 
Thanks for rising this issue, let us check what is a possible reason of such behavior.
Someone will contact you back, probably with additional questions.
Stay tuned ;)

**Comment by Iffa-Meah** [comment]
@art3na could you provide these:
1. Relevant model files
2. Which OpenVINO sample did you use to test this? if you are using custom code, please help to share/describe
3. Relevant commands you used

**Comment by art3na** [comment]
I found that my issue is the same as this:
[https://github.com/openvinotoolkit/openvino/issues/11669](url)
And I suppose that there is no solution to this issue.

**Comment by dmitry-gorokhov** [comment]
@art3na 
Higher memory consumption in case of dynamic shapes is something expected. However:
- It shouldn't growing continuously
- It shouldn't be several times higher
In order to help with our particular case with need information requested by @Iffa-Meah

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
