### ISSUE TITLE
[ ERROR ] Cannot create TopK layer 4262 id:368

### ISSUE THREAD

**Issue by justcainiao** [openvinotoolkit/openvino#1348]
I use openvino 2020.01, run an network include topK layer ， not support？

**Comment by jgespino** [comment]
Hi @justcainiao 

Thanks for reaching out, take a look at the [supported framwork Layers](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html) section in the documentation. TopK layer is supported on the ONNX framework. Which framework and topology are you trying to use?

Regards,
Jesus

**Comment by jgespino** [comment]
Closing issue, please re-open if you need further assistance.
