### ISSUE TITLE
Error converting shape to a TensorShape: Failed to convert 'masked_array(data=[1, --, --, 3]

### ISSUE THREAD

**Issue by shashank332** [openvinotoolkit/openvino#13508]
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	None
	- Path for generated IR: 	/home/obs-56/.
	- IR output name: 	saved_model
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Source layout: 	Not specified
	- Target layout: 	Not specified
	- Layout: 	Not specified
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- User transformations: 	Not specified
	- Reverse input channels: 	False
	- Enable IR generation for fixed input shape: 	False
	- Use the transformations config file: 	None
Advanced parameters:
	- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: 	False
	- Force the usage of new Frontend of Model Optimizer for model conversion into IR: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Use the config file: 	None
OpenVINO runtime found in: 	/home/obs-56/.local/lib/python3.9/site-packages/openvino
OpenVINO runtime version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version: 	2022.1.0-7019-cdb9bec7210-releases/2022/1
2022-10-17 15:45:47.565742: E tensorflow/core/framework/node_def_util.cc:623] NodeDef mentions attribute validate_shape which is not in the op definition: Op<name=AssignVariableOp; signature=resource:resource, value:dtype -> ; attr=dtype:type; is_stateful=true> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node model/stem_bn/AssignNewValue}}
2022-10-17 15:45:52.655234: E tensorflow/core/framework/node_def_util.cc:623] NodeDef mentions attribute validate_shape which is not in the op definition: Op<name=AssignVariableOp; signature=resource:resource, value:dtype -> ; attr=dtype:type; is_stateful=true> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node AssignNewValue}}
2022-10-17 15:45:57.725303: E tensorflow/core/framework/node_def_util.cc:623] NodeDef mentions attribute validate_shape which is not in the op definition: Op<name=AssignVariableOp; signature=resource:resource, value:dtype -> ; attr=dtype:type; is_stateful=true> This may be expected if your graph generating binary is newer  than this binary. Unknown attributes will be ignored. NodeDef: {{node AssignNewValue}}
[ WARNING ]  Failed to parse a tensor with Unicode characters. Note that Inference Engine does not support string literals, so the string constant should be eliminated from the graph.
[ WARNING ]  Failed to parse a tensor with Unicode characters. Note that Inference Engine does not support string literals, so the string constant should be eliminated from the graph.
[ WARNING ]  The model contains input(s) with partially defined shapes: name="serving_default_input_tensor" shape="[1, -1, -1, 3]". Starting from the 2022.1 release the Model Optimizer can generate an IR with partially defined input shapes ("-1" dimension in the TensorFlow model or dimension with string value in the ONNX model). Some of the OpenVINO plugins require model input shapes to be static, so you should call "reshape" method in the Inference Engine and specify static input shapes. For optimal performance, it is still recommended to update input shapes with fixed ones using "--input" or "--input_shape" command-line parameters.
[ ERROR ]  Cannot infer shapes or values for node "StatefulPartitionedCall".
[ ERROR ]  Error converting shape to a TensorShape: Failed to convert 'masked_array(data=[1, --, --, 3],
             mask=[False,  True,  True, False],
       fill_value=-1000000007)' to a shape: 'masked'could not be converted to a dimension. A shape should either be single dimension (e.g. 10), or an iterable of dimensions (e.g. [1, 10, None])..
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function tf_native_tf_node_infer at 0x7ff04211c3a0>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'openvino.tools.mo.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "StatefulPartitionedCall" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)

**Comment by Iffa-Meah** [comment]
@shashank332 Could you provide these:

1. Model files
2. Model & its topology, eg: Model: Tensorflow, Topology: inception_v1
3. Commands that you use with OpenVINO Model Optimizer

**Comment by yaswanthan** [comment]
1. I have used TensorFlow model and topology is efficientdet-d0
2. commands used for model optimizer is " mo --saved_model_dir /home/obs-56/effi/saved_model
3.how to attach the model files? can I send you through mail

**Comment by shashank332** [comment]
1. I have used TensorFlow model and topology is efficientdet-d0
2. commands used for model optimizer is " mo --saved_model_dir /home/obs-56/effi/saved_model
3. how to attach the model files? can I send you through mail

**Comment by shashank332** [comment]
I have attached the model files
https://drive.google.com/drive/folders/10HQKvcZTFqXL7jnOZNqemMs60Sr9vRVL?usp=sharing

**Comment by rkazants** [comment]
Hi @shashank332! I see that the model passing to MO is not frozen and we encounter a problem with `StatefulPartitionedCall` operation.

Let me figure out why MO is unable to freeze model and come back.

Best regards,
Roman

**Comment by shashank332** [comment]
hi @rkazants 
Thanks for the update waiting for your reply.

regards,
Shashank

**Comment by Iffa-Meah** [comment]
@shashank332 I managed to convert and infer your model.

Model optimizer:
<img width="705" alt="mo" src="https://user-images.githubusercontent.com/79643476/196360492-bb8eeb2b-2d17-4105-bfd4-a889b78b8bee.png">



Infer:

<img width="595" alt="benchmark" src="https://user-images.githubusercontent.com/79643476/196360755-b07d647d-e1e3-4d4b-94e9-6c4c62c8bad9.png">

**Comment by shashank332** [comment]
Hi @Iffa-Meah 
I managed to convert into IR but I am new to openvino platform. Is there any way to convert into static shape?

while reading network using the following command:

ie = IECore()
net = ie.read_network(saved_model.xml,saved_model.bin)

we encounter the following error: 
![dynamic_shape](https://user-images.githubusercontent.com/92209382/196398623-44bc0a90-32f4-4fb5-ab94-0a9acfb8b905.png)

**Comment by rkazants** [comment]
> Hi @Iffa-Meah I managed to convert into IR but I am new to openvino platform. Is there any way to convert into static shape?
> 
> while reading network using the following command:
> 
> ie = IECore() net = ie.read_network(saved_model.xml,saved_model.bin)
> 
> we encounter the following error: ![dynamic_shape](https://user-images.githubusercontent.com/92209382/196398623-44bc0a90-32f4-4fb5-ab94-0a9acfb8b905.png)

Hi @Iffa-Meah, you use API 1.0 that does not support dynamic shapes. You need to use API 2.0 for dynamic shapes. Here an example of how to infer for dynamic shapes using API 2.0:

```
from openvino.runtime import AsyncInferQueue, Core, InferRequest, Layout, Type
core = Core()
model = core.read_model("model.xml")
compiled_model = core.compile_model(model, "CPU")
output = compiled_model.infer_new_request({0: input_data})
```

In order to convert a model with static shapes, use MO `--input` or `--input_shape` options

Best regards,
Roman

**Comment by shashank332** [comment]
Hi @avitial @rkazants @Iffa-Meah @Munesh-Intel , My output layer is in dynamic shape. So, when i am try to infer a following error is occuring. Is there anything to do
![Screenshot from 2022-10-19 10-20-33](https://user-images.githubusercontent.com/92209382/196600689-91a32431-b167-4335-aa2e-19e28d8de026.png)

**Comment by rkazants** [comment]
> Hi @avitial @rkazants @Iffa-Meah @Munesh-Intel , My output layer is in dynamic shape. So, when i am try to infer a following error is occuring. Is there anything to do ![Screenshot from 2022-10-19 10-20-33](https://user-images.githubusercontent.com/92209382/196600689-91a32431-b167-4335-aa2e-19e28d8de026.png)

@shashank332, please provide the full script you are running.

**Comment by shashank332** [comment]
Hi @rkazants , We used the below link for reference to infer the model. I will also share the script here. 

Refered Link: **https://docs.openvino.ai/latest/notebooks/002-openvino-api-with-output.html**

Script: **https://drive.google.com/file/d/1UCVAB6pjq8v3HWM9T5ubz5-gipwCTLd_/view?usp=sharing**

**Comment by rkazants** [comment]
> Hi @rkazants , We used the below link for reference to infer the model. I will also share the script here.
> 
> Refered Link: **https://docs.openvino.ai/latest/notebooks/002-openvino-api-with-output.html**
> 
> Script: **https://drive.google.com/file/d/1UCVAB6pjq8v3HWM9T5ubz5-gipwCTLd_/view?usp=sharing**

@shashank332, use `output_layer.get_partial_shape()` to get a partial shape for dynamic shape.

**Comment by rkazants** [comment]
> @rkazants Thanks for the reply. We got the output as you mention when we try "**output_layer.get_partial_shape()**" . Our goal is to detect the objects (Object detection model). We used the below link for reference to detect.
> 
> **https://docs.openvino.ai/latest/notebooks/004-hello-detection-with-output.html**
> 
> Here when loading the model part, in the line output_layer_ir = compiled_model.output("boxes"), we got a error ![output_layer_error](https://user-images.githubusercontent.com/92209382/196615052-6e85e801-b300-4adc-868a-090ed75c78ed.png)
> 
> when we replace the line by output_layer_ir = compiled_model.output(0), we didn't got bounding box. How can we proceed with it. Thanks in advance

@shashank332, am I correct that bboxes output has 0 output index in TF2?
@popovaan, could you please check that we save the same order of outputs like in TF2 for this particular model?

Thanks,
Roman

**Comment by popovaan** [comment]
@rkazants As this model is saved using tf.saved_model interface it returns inference result as a dictionary, so outputs order cannot be preserved. 

@shashank332 regarding output names, currently we don't save original output names for saved_model format. 
After model saving model outputs are renamed to Identity_<output index> and these names are present in the converted model.
Here is the mapping of names which you can use to work with outputs:

Identity:0     'detection_anchor_indices' 
Identity_1:0  'detection_boxes'
Identity_2:0  'detection_classes'
Identity_3:0  'detection_multiclass_scores'
Identity_4:0  'detection_scores'
Identity_5:0  'num_detections'
Identity_6:0  'raw_detection_boxes'
Identity_7:0  'raw_detection_scores'

In future releases we will add support of original names for saved_model, currently it is not implemented.

**Comment by rkazants** [comment]
@shashank332, I think the original support request is resolved. Let us close this ticket.

Thanks,
Roman

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
