### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tiezhuli001** [openvinotoolkit/openvino#13527]
- OpenVINO => 2022.2
- Operating System / Platform => ubuntu 22.04
- Compiler => VS Code
- Problem classification: Model Conversion
- Framework: ONNX 

##### Detailed description

error:
```
openvino_asr_model.cc:262] error when encoder infer failed: Check 'false' failed at plugins/intel_cpu/src/nodes/eltwise.cpp:1906:
Can't compute static output shape for Eltwise node with name: Add_132. Input shapes = ( 0 port = {1, 8, 16, 16}, 1 port = {1, 8, 16, 0}, ). Output shape = ( {1,8,16,?} )
```
description:
As above, I don't know what to do to fix it. It looks like the outputs of reasoning are dynamic, but when constructing tensors, the argument is ov::Shape, which is static

##### Steps to reproduce

1、tensor is constructed by ov::Shape:
ov::Shape att_cache_shape = {12,8,0,128}
ov::Tensor att_cache_tensor(ov::element::Type_t::f32, att_cache_shape);

2、set infer tensor

encoder_infer.set_tensor("att_cache",att_cache_ort_);

3、infer request

encoder_infer.infer();

It returns an error。

--------
Please help me solve this problem. Thank you very much！！！

**Comment by tiezhuli001** [comment]
python code will run, c++ will fail
------------            
            encoder_inputs = {
                'chunk': feats_ov,
                'offset': offset_ov,
                'att_cache': att_cache_ov,
                'cnn_cache': cnn_cache_ov
            }
            encoder_request.infer(encoder_inputs)

**Comment by tomdol** [comment]
Could you please provide a full reproducer and the model(if possible)? Please share the working python script too for reference.
From the information you provided only this shape looks suspicious {1, 8, 16, 0} and this would for now be my hint on what to investigate.

**Comment by tiezhuli001** [comment]
ok,python:
----
            encoder_model = core.compile_model(args.encoder_openvino, 'CPU')
            encoder_request = encoder_model.create_infer_request()
            # encoder inference
            feats_ov = ov.Tensor(array=feats.numpy(), shared_memory=True)
            offset_ov = ov.Tensor('int64', [])
            offset_ov.data[()] = 0
            att_cache_ov = ov.Tensor('float32', [12, 8, 0, 128])
            att_cache_ov.data[:] = 0.0
            cnn_cache_ov = ov.Tensor('float32', [12, 1, 512, 7])
            cnn_cache_ov.data[:] = 0.0
            encoder_inputs = {
                'chunk': feats_ov,
                'offset': offset_ov,
                'att_cache': att_cache_ov,
                'cnn_cache': cnn_cache_ov
            }
            encoder_request.infer(encoder_inputs)
            encoder_output = encoder_request.get_output_tensor(0)
            maxlen = encoder_output.shape[1]
---- infer request success!

model: File upload is slow. Hold on，thanks.

-----

it is strange,i can not found this {1, 8, 16, 0}   in my c++ code

**Comment by rkazants** [comment]
Hi @tiezhuli001!

You have empty input tensor of shape `[12, 8, 0, 128]` that is passing along with another non-empty tensor of shape `[12, 1, 512, 7]` to `Eltwise` operation. It looks an invalid case to have empty and non-empty tensors for Eltwise, physically incorrect.

If you have a model from the original framework, does the framework infer with such shapes?

Best regards,
Roman

**Comment by tiezhuli001** [comment]
@rkazants 
yes,I found this problem.
There was something wrong with the code, the error has been fixed, thank you very much！
