### ISSUE TITLE
resut is wrong when run model-MobileFaceNet-arcface-ms1m-refine-v1?

### ISSUE THREAD

**Issue by baishiruyue** [openvinotoolkit/openvino#1352]
i download the model-MobileFaceNet-arcface-ms1m-refine-v1.zip file, and convet the mode to ir model successful.
then use an algined face image to run, below is the main processing:
-----------------------------------------------------------------------
 input_info->setLayout(Layout::NCHW);
 input_info->setPrecision(Precision::U8);

output_info->setPrecision(Precision::FP32);

 cv::Mat image = imread_t(input_image_path);
 Blob::Ptr imgBlob = infer_request.GetBlob(input_name);
 matU8ToBlob<uint8_t>(image, imgBlob, 0);

 infer_request.Infer();
 Blob::Ptr output = infer_request.GetBlob(output_name);
MemoryBlob::CPtr moutput = as<MemoryBlob>(output);
 auto moutputHolder = moutput->rmap();
const float *result_reco = moutputHolder.as<const float *>();
printf("features are：\n");
 for (int i = 0; i <128; i++){
			printf("%d,", result_reco[i]);
}
-------------------------------------------------------

it runs ok， but the result features are all wrong, i do not know how to check and solve the problem, is there anyone can help me?

**Comment by jgespino** [comment]
Hi @baishiruyue 

- Which version of the OpenVINO toolkit are you using?
- What OS are you using?
- Could you provide the model optimizer command used to convert the model?

Regards,
Jesus

**Comment by baishiruyue** [comment]
> Hi @baishiruyue
> 
> * Which version of the OpenVINO toolkit are you using?
> * What OS are you using?
> * Could you provide the model optimizer command used to convert the model?
> 
> Regards,
> Jesus

  hi@jgespino , Thank you for your reply. I have solved this problem. It is all my fault. I forgot the normalization.

**Comment by jgespino** [comment]
Hi @baishiruyue 

Thanks for confirming,  I will close the issue.

Regards,
Jesus
