### ISSUE TITLE
[Bug] error when include windows.h

### ISSUE THREAD

**Issue by yuechengmao** [openvinotoolkit/openvino#13523]
##### System information (version)

- OpenVINO => master branch (2022.2.0)
- Operating System / Platform => Windows 11 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

I'm trying to use "Sleep" function from <Windows.h>, but when the line "#include <Windows.h>" is added to the file 
"openvino\samples\cpp\benchmark_app\main.cpp". It cannot pass the build progress. build error is shown below,

ERROR:
11>main.cpp
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(109,72): warning C4003: not enough arguments for function-like macro invocation 'max'
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(109,72): error C2589: '(': illegal token on right side of '::'
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(109): error C2062: type 'unknown-type' unexpected
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(109,72): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(43,26): error C2065: 's_max': undeclared identifier
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(44,33): error C2065: 's_max': undeclared identifier
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(44,45): error C2065: 's_max': undeclared identifier
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(50,29): error C2065: 's_max': undeclared identifier
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(70,29): error C2065: 's_max': undeclared identifier
11>D:\projects\openvino\src\core\include\openvino/core/interval.hpp(115,26): error C2065: 's_max': undeclared identifier
11>D:\projects\openvino\src\core\include\openvino/core/dimension.hpp(184,25): message : see reference to function 'ov::Interval::Interval(void)'
11>D:\projects\openvino\src\core\include\openvino/core/dimension.hpp(184,25): fatal error C1903: unable to recover from previous error(s); stopping compilation
11>INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe'
11>    Please choose the Technical Support command on the Visual C++
11>    Help menu, or open the Technical Support help file for more information
11>Done building project "benchmark_app.vcxproj" -- FAILED.
17>------ Skipped Build: Project: PACKAGE, Configuration: Release x64 ------
17>Project not selected to build for this solution configuration 
18>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
18>Project not selected to build for this solution configuration 
========== Build: 5 succeeded, 1 failed, 89 up-to-date, 12 skipped ==========

thanks.

**Comment by ilya-lavrenov** [comment]
Hi @yuechengmao 

Add `#define NOMINMAX`. Please, read https://stackoverflow.com/questions/13416418/define-nominmax-using-stdmin-max
