### ISSUE TITLE
[Bug] How to load .yml models from open_model_zoo ?

### ISSUE THREAD

**Issue by jiapei100** [openvinotoolkit/openvino#13586]
##### System information (version)

- OpenVINO => 2022.2.0
- Operating System / Platform => Ubuntu 22.04
- Compiler => gcc/g++ 11.2.0
- Problem classification: testing **.yml**  from [open_model_zoo](https://github.com/openvinotoolkit/open_model_zoo)
- Framework: Googlenet
- Model name: googlenet-v1

##### Detailed description
Just wanna test out how to load **.yml** models downloaded from [open_model_zoo](https://github.com/openvinotoolkit/open_model_zoo) ?

##### Steps to reproduce

After successfully built and installed [OpenVINO](https://github.com/openvinotoolkit/openvino), I tried to test **OpenVINO** by:

```console
➜  hello_classification git:(master) ✗ python hello_classification.py "/opt/intel/open_model_zoo/models/public/googlenet-v1/model.yml" "/opt/intel/test_data/images/car.bmp" GPU
[ INFO ] Creating OpenVINO Runtime Core
[ INFO ] Reading the model: /opt/intel/open_model_zoo/models/public/googlenet-v1/model.yml
Traceback (most recent call last):
  File /opt/intel/openvino/samples/python/hello_classification/hello_classification.py", line 114, in <module>
    sys.exit(main())
  File /opt/intel/openvino/samples/python/hello_classification/hello_classification.py", line 34, in main
    model = core.read_model(model_path)
RuntimeError: [ NETWORK_NOT_READ ] Unable to read the model: /opt/intel/open_model_zoo/models/public/googlenet-v1/model.yml Please check that model format: yml is supported and the model is correct. Available frontends: onnx ir paddle 
```

It looks I failed to read AI models from [open_model_zoo](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models). Can anybody give me a hand please? 

Thank you ...

**Comment by eaidova** [comment]
@jiapei100 let's me explain how it works :) 
sample accepts models in OpenVINO IR format (it represented by `.xml` with topology and `.bin` file with weights. Open Model Zoo does not store models itself, it provides a way to download and convert models via tools. So before starting work with models from open model zoo you need to call following commands (please also make sure that you have installed `openvino-dev` package which contains tools):
omz_downloader --name <model> 
omz_converter --name <model>
After that model will be saved on your machine (the tool provides info where its located) and you can provide path to XML file to sample.
You can find detailed step-by-step instruction and example usage hello_classification sample with alexnet model in [openvino documentation](https://docs.openvino.ai/latest/openvino_inference_engine_ie_bridges_python_sample_hello_classification_README.html)

You also can find useful info about omz_downloader and omz_converter usage on this [page](https://docs.openvino.ai/latest/omz_tools_downloader.html#doxid-omz-tools-downloader)
and documentation about provided set of [public](https://docs.openvino.ai/latest/omz_models_group_public.html) and [intel](https://docs.openvino.ai/latest/omz_models_group_intel.html) models.

**Comment by jiapei100** [comment]
@eaidova 

Thank you @eaidova 
Can you please help to take a look at my this issue [https://github.com/openvinotoolkit/openvino/issues/13724](https://github.com/openvinotoolkit/openvino/issues/13724)
