### ISSUE TITLE
[API] Any API to avoid output tensor copy?

### ISSUE THREAD

**Issue by yszhou2019** [openvinotoolkit/openvino#13585]
Hi, community.
I choose to use OpenVINO library to deploy some ML model to productions. I wonder how can I skip the output tensor copy to std::vector. Is there any way to achieve the memory copy elision? Thank you!

Currently, the code is like:
```cpp

    ov::Tensor input_tensor(ov::element::f32, static_shape, input.data());
    inferRequests_[index].set_input_tensor(input_tensor);
    inferRequests_[index].infer();
    auto wav_out = inferRequests_[index].get_output_tensor(0);
    const float *output_buffer = wav_out.data<const float>();
    std::copy(output_buffer, output_buffer + newWavLen, output.data());
```

**Comment by tomdol** [comment]
Hi, you can use the values stored in the Tensor directly without copying them to an intermediate container. Have a look at https://github.com/openvinotoolkit/openvino/blob/master/src/core/include/openvino/runtime/tensor.hpp#L165-L168 
```
const auto wav_out = inferRequests_[index].get_output_tensor(0);
const float* first_value = wav_out.data<float>();
const float* last_value = first_value + wav_out.get_size(); //this one is equal to past-the-end iterator so it should not be dereferenced
```

**Comment by yszhou2019** [comment]
> Hi, you can use the values stored in the Tensor directly without copying them to an intermediate container. Have a look at https://github.com/openvinotoolkit/openvino/blob/master/src/core/include/openvino/runtime/tensor.hpp#L165-L168
> 
> ```
> const auto wav_out = inferRequests_[index].get_output_tensor(0);
> const float* first_value = wav_out.data<float>();
> const float* last_value = first_value + wav_out.get_size(); //this one is equal to past-the-end iterator so it should not be dereferenced
> ```

I knew it. Thy reason why I want to use std::vector is we don't want to modify the application interface and std::vector is more modern rather than raw pointer to the buffer. So, OpenVINO doesn't support infer and generate output to a defined tensor?

Maybe I can use some std class like `std::span` to achieve this. Anyway, thank you! @tomdol

**Comment by yszhou2019** [comment]
Emmm, I think using an raw pointer may be not a good choice if code like this.
```
{
// inference and get the output
   auto ouptut=inferRequest.get_output_tensor();
}
{
// post process with the inference result.
}
```

**Comment by tomdol** [comment]
I think I didn't understand what you wanted to achieve from your original question. You can create an output tensor the same way you've already created an input tensor (by passing a pointer to an underlying memory). This tensor can then be used as output tensor using for example this call https://github.com/openvinotoolkit/openvino/blob/master/src/inference/include/openvino/runtime/infer_request.hpp#L86-L93. Please have a look at the other overloads too.

**Comment by yszhou2019** [comment]
> Emmm, I think using an raw pointer may be not a good choice if code like this.
> 
> ```
> {
> // inference and get the output
>    auto ouptut=inferRequest.get_output_tensor();
> }
> {
> // post process with the inference result.
> }
> ```

I just realized vector memory would be released if out of the scope of variable `output`.

**Comment by yszhou2019** [comment]
> I think I didn't understand what you wanted to achieve from your original question. You can create an output tensor the same way you've already created an input tensor (by passing a pointer to an underlying memory). This tensor can then be used as output tensor using for example this call https://github.com/openvinotoolkit/openvino/blob/master/src/inference/include/openvino/runtime/infer_request.hpp#L86-L93. Please have a look at the other overloads too.

Thank you! I got it.
