### ISSUE TITLE
tf.split() and slice op not supported

### ISSUE THREAD

**Issue by TNTWEN** [openvinotoolkit/openvino#1358]
Hello!
i want to build yolov4tiny model ,and in this model i only need half of the  filters of some conv. 
in the convert_weighs_pb.py,i use"_,split=tf.split(net,num_or_size_splits=2,axis=1 if data_format =="NCHW" else 3)"  i converted the model to pb correctly and converted to IR correctly.But when i run the demo error occurs
 " out_blob = out_blob.reshape(net.layers[net.layers[layer_name].parents[0]].shape)
KeyError: 'detector/yolo-v3-tiny/split_2.0'  "

then i try code like this to replace tf.split "split =net[:,int(in_channels/2):,:,:]if data_format=="NCHW" else net[:,:,:,int(in_channels/2):]" 
i convert the model correctly too.but when i run the demo,error still occurs
"    out_blob = out_blob.reshape(net.layers[net.layers[layer_name].parents[0]].out_data[0].shape)
KeyError: 'detector/yolo-v3-tiny/strided_slice_1/Split.0'"

it seems that my openvino(2020.1) not support tf.split and slice op. 
is there any way to replace tf.split or the slice op?
Thanks!

**Comment by jgespino** [comment]
Hi @TNTWEN 

Slice and Split operations are both listed under the [TensorFlow supported operations](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#tensorflow_supported_operations) on the OpenVINO 2020.4 documentation. Could you please upgrade to OpenVINO 2020.4 and see if you continue to have this issue?

Regards,
Jesus

**Comment by TNTWEN** [comment]
Hi, @jgespino ,i tried OpenVINO2020R4 yesterday,and i convert YOLOV4 correctly, and even detects objects correctly in latest yolov3 demo "object_detection_demo_yolov3_async.py".And i update my code on github:https://github.com/TNTWEN/OpenVINO-YOLOV4.git
it seems that the model_optimizer still  doesn't support tf.split().but OpenVINO2020R4 supports slice op.  So far,i have converted yolov4-tiny to IR,but there are still some problems and i list them in the README.md

**Comment by jgespino** [comment]
Hi @TNTWEN 

I looked at the readme file and it sounds like you had issues with split but found a workaround and you need to make some adjustments for parsing YoloV4?

Regards,
Jesus

**Comment by TNTWEN** [comment]
Hi， @jgespino 
YOLOv4 could run correctly.but YOLOv4-tiny stll have some issues.
The model optimizer supports tf.split() and slice operation,but the inference engine only support slice operation.so i use replace tf.split() with slice operation. when the device is CPU,it got a NAN error and when the device is GPU,there is no NAN error,but it still can't detect objects correctly. i am still struggling  to find out what went wrong.

Thanks!

**Comment by TNTWEN** [comment]
Hi， @jgespino 
Recently,i fixed some bugs of tiny's structure and replaced all v3 interfaces name with v4 .Now there is no NAN error and the fps is normal. But it still detects nothing, even though I checked the structure of the model.I don't know where the problem is.

**Comment by jgespino** [comment]
Hi @TNTWEN 

Currently YOLOv4 is not supported by OpenVINO, please continue to share your progress with the community. 

Regards,
Jesus

**Comment by TNTWEN** [comment]
Hi @jgespino 
i have finished the OpenVINO-YOLOV4 adaptation 
https://github.com/TNTWEN/OpenVINO-YOLOV4
YOLOV4-Mish and YOLOV4-relu work well. And YOLOv4-TINY still has some problems

**Comment by AlexeyAB** [comment]
@TNTWEN Hi,
Great job!
When you manage to get Yolov4-tiny running on OpenVINO, please let me know. I will try to create a model that is optimal for the NPU.

**Comment by AlexeyAB** [comment]
Currently the fastest MISH-implementation: https://github.com/AlexeyAB/darknet/blob/6af4370c3fe0f43a8c2fea6e04fc3dd2930b1da5/src/activation_kernels.cu#L248-L256
```cpp
static float mish_yashas2(float x)
{
    float e = __expf(x);
    float n = e * e + 2 * e;
    if (x <= -0.6f) {
        return x * (n / (n + 2));
    }

    return x - 2 * (x / (n + 2));
}
```

More: https://github.com/AlexeyAB/darknet/issues/5922

**Comment by TNTWEN** [comment]
Hello, @AlexeyAB 
I have fixed YOLOv4-Tiny conversion.  Now OpenVINO YOLOV4,YOLOV4-Relu,YOLOV4-Tiny could run normally.
Just like YOLOv3-Tiny,When we  do model conversion (darkent->.pb->IR) , it is difficult to avoid the loss of accuracy .So we still need to train yolov4-tiny.weights more and then it could detect things correctly.

**Comment by AlexeyAB** [comment]
@TNTWEN 

* Do you use this repository https://github.com/mystic123/tensorflow-yolo-v3 or this https://github.com/hunglc007/tensorflow-yolov4-tflite for conversion Darknet->PB?

>So w**e still need to further** train yolov4-tiny.weights and then it could detect things correctly.

* Do you mean, that we should train yolov4-tiny.weights by using TensorFlow?

**Comment by TNTWEN** [comment]
My code is based on  https://github.com/mystic123/tensorflow-yolo-v3.
I think the loss of accuracy comes from OpenVINO Model Optimizer .  This problem has existed since YOLOV3tiny. i use darknet to further train yolov3-tiny before. This model(.weights) performs very well in darknet,Pytorch(use https://github.com/ultralytics/yolov3 convert .weights to .pt then use detect.py)and tensorflow( use https://github.com/mystic123/tensorflow-yolo-v3 convert .weights to .pb then use demo.py ).But when i convert this model (.weights) to tensorflow( https://github.com/mystic123/tensorflow-yolo-v3) and then to IR(OpenVINO Model Optimizer)according to OpenVINO document .The detection effect will be worse and less stable. v4-tiny also has this problem.
So i think the loss of accuracy comes from OpenVINO Model Optimizer.

**Comment by AlexeyAB** [comment]
@TNTWEN 
> But for yolov4-tiny ,if we use yolov4-tiny.weights (https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights) convert to IR directly ,it can't detect objects well.So we need to use COCO dataset to train this model futher using darknet. it will perform better in OpenVINO.

`yolov4-tiny.weights` is trained `500 000` iterations. How many more iterations should we train to get better accuracy in OpenVINO?

Can you provide detection result on this image for 4 cases by using `yolov4-tiny.cfg 416x416`?
1. by using https://github.com/AlexeyAB/darknet
2. by using https://github.com/mystic123/tensorflow-yolo-v3
3. by using OpenVINO
4. by using OpenVINO (but trained more iterations as you suggested)

----

source image:
![test](https://user-images.githubusercontent.com/4096485/88935710-b3acfd80-d28a-11ea-805c-a39d943ac5cf.png)

----

For example, I get this result by using https://github.com/AlexeyAB/darknet
![yolo_v4_tiny](https://user-images.githubusercontent.com/4096485/88935858-ddfebb00-d28a-11ea-9059-68ef1f5c9396.jpg)

**Comment by TNTWEN** [comment]
@AlexeyAB
After my preliminary tests, I think my previous ideas may be wrong. I am still training v4tiny model,and i share my completed tests first. I will update other test results later.

YOLOV4 :yolov4.weights (https://drive.google.com/open?id=1cewMfusmPjYWbrnuJRuKhPMwRe_b9PaT)

YOLOV4-tiny: yolov4-tiny.weights(https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights)

YOLOV3-tiny:yolov3-tiny.weights(https://pjreddie.com/media/files/yolov3-tiny.weights)

all 416*416

- YOLOV4
darknet:（https://github.com/AlexeyAB/darknet）
![darknet-v4](https://user-images.githubusercontent.com/49018311/89013749-05b35900-d347-11ea-816b-50fe38ba22c7.jpg)

 .pb(https://github.com/TNTWEN/OpenVINO-YOLOV4)
![v4](https://user-images.githubusercontent.com/49018311/89013821-24195480-d347-11ea-885b-e0e562dc43f7.png)

IR (OpenVINO Model Opeimizer):
![prob_threshold-0 2](https://user-images.githubusercontent.com/49018311/89013860-385d5180-d347-11ea-9898-cbbba7db3c16.png)

- YOLOv4-tiny
darknet:（https://github.com/AlexeyAB/darknet）
![darknet-v4tiny](https://user-images.githubusercontent.com/49018311/89013928-562ab680-d347-11ea-96d9-21bc15dbab95.jpg)
.pb(https://github.com/TNTWEN/OpenVINO-YOLOV4)
![v4tiny](https://user-images.githubusercontent.com/49018311/89013984-6cd10d80-d347-11ea-8d6c-79cffbda4853.png)
 IR(OpenVINO Model Opeimizer)
![v4tiny0 2](https://user-images.githubusercontent.com/49018311/89014012-7c505680-d347-11ea-8413-a6c067bd3450.png)

- YOLOv3-tiny
 darknet(https://github.com/AlexeyAB/darknet)
![darknet-v3tiny](https://user-images.githubusercontent.com/49018311/89014092-94c07100-d347-11ea-9d4f-caa1a4818e4e.jpg)

.pb(https://github.com/mystic123/tensorflow-yolo-v3)
![v3tiny](https://user-images.githubusercontent.com/49018311/89014148-abff5e80-d347-11ea-8e01-5651306aec25.png)

 IR(OpenVINO Model Opeimizer)
![v3tiny0 2](https://user-images.githubusercontent.com/49018311/89014190-bb7ea780-d347-11ea-97f0-25fc93345456.png)


Video Test: (OpenVINO v4tiny,v3tiny)

- YOLOv4-tiny

(yolov4-tiny.weights->https://github.com/TNTWEN/OpenVINO-YOLOV4->OpenVINO)
Video url :https://drive.google.com/file/d/1rik45EyFOsB13wWiAN-X3Oq31Dfjs1pZ/view?usp=sharing

-YOLOv3-tiny
(yolov3-tiny.weights->https://github.com/mystic123/tensorflow-yolo-v3->OpenVINO)
Video url:https://drive.google.com/file/d/1mIW7ITf7kkOShEftK5VNbJw8u2HW4jMq/view?usp=sharing


Summary:
The accuracy loss of v4tiny is mainly in .pb
.pb's accuracy is close to IR's accuracy
In the video test, v3tiny also does not work well（close to v4tiny).tiny's performance in Openvino has been unstable.
 So problems still exist in my v4tiny conversion code(.weights->.pb) which result in large loss of accuracy

**Comment by AlexeyAB** [comment]
@TNTWEN 

Try to use this TensorFlow implementation https://github.com/hunglc007/tensorflow-yolov4-tflite

There is converter: weights -> pb -> tflite.

And it seems there is smaller loss in accuracy: https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/165

**Comment by TNTWEN** [comment]
@AlexeyAB 
I have fix bugs of my code
And now :

- YOLOV4-tiny
darknet:（https://github.com/AlexeyAB/darknet）
![darknet-v4tiny](https://user-images.githubusercontent.com/49018311/89049875-817fc680-d384-11ea-9e7b-5d54a0753516.jpg)
.pb(https://github.com/TNTWEN/OpenVINO-YOLOV4)
![pb](https://user-images.githubusercontent.com/49018311/89049928-965c5a00-d384-11ea-905e-8e9353d7ec81.png)
IR(OpenVINO Model Opeimizer)
![IR](https://user-images.githubusercontent.com/49018311/89049961-9fe5c200-d384-11ea-9fd1-20f269d46169.png)

**Comment by jgespino** [comment]
@TNTWEN Great process! Please let me know if we can proceed to close this issue.
