### ISSUE TITLE
[Bug] RuntimeError: [GNAPlugin] in function void __cdecl GNAPluginNS::GNAPlugin::LoadNetwork(class InferenceEngine::CNNNetwork &): The plugin does not support layer: Tile_822:Tile

### ISSUE THREAD

**Issue by Raise-me-up** [openvinotoolkit/openvino#13655]
OpenVINO => 2022.2.0
Operating System / Platform => Windows 10 64 Bit
Compiler => Visual Studio 2019
Problem classification: InferenceEngine Supported Framework Layers
Framework: Pytorch

When I just run the following test codes to do the inference on the GNA, the error messages occur. However, I find the tile op is supported according to the document (https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html). What is the problem please?

ie = Core()
pdccrn_model_xml = "models\\PDCCRN_static.xml"
model = ie.read_model(pdccrn_model_xml)
compiled_model = ie.compile_model(model=model, device_name="GNA")

Traceback (most recent call last):
  File "D:\software\Pycharm\workspace\ov_infer_test\main.py", line 16, in <module>
    compiled_model = ie.compile_model(model=model, device_name="GNA")
  File "D:\workspace\openvino\openvino_2022.2\python\python3.9\openvino\runtime\ie_api.py", line 387, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: [GNAPlugin] in function void __cdecl GNAPluginNS::GNAPlugin::LoadNetwork(class InferenceEngine::CNNNetwork &): The plugin does not support layer: Tile_822:Tile

The model is in the attachment:

[PDCCRN_static.zip](https://github.com/openvinotoolkit/openvino/files/9868709/PDCCRN_static.zip)

**Comment by brmarkus** [comment]
Which HW/SoC do you use? Could it depend on the underlying HW (as there are different generations of GNA devices)?

**Comment by rkazants** [comment]
@Raise-me-up, according to the documentation (https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html#supported-layers), the GNA plugin does not support `Tile` operation.

@nkogteva, @dorloff, do you have a priority to support `Tile` in GNA plugin?

Thanks,
Roman

**Comment by nkogteva** [comment]
@Raise-me-up I quickly looked at the model. Tile is not only problem with this model. Broadcast, Gather are also unsupported. Besides that GNA has a limited support of Convolution. Please check https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_GNA.html#model-and-operation-limitations

**Comment by Raise-me-up** [comment]
> Which HW/SoC do you use? Could it depend on the underlying HW (as there are different generations of GNA devices)?

My laptop uses the 11th Gen Intel(R) Core(TM) i7-1165G7, which supports GNA2.0 However, the OEM doesn't implement the support to GNA. So, I just use the emulation mode.

**Comment by Raise-me-up** [comment]
> @Raise-me-up I quickly looked at the model. Tile is not only problem with this model. Broadcast, Gather, Pad are also unsupported. Besides that GNA has a limited support of Convolution. Please check https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_GNA.html#model-and-operation-limitations

OMG! So many ops are not supported by GNA！Is there any possible for us to deploy such a model on GNA by using extension plugin？

**Comment by nkogteva** [comment]
@Raise-me-up GNA is very limited and specific device which intended to be used for continuous audio workloads especially. GNA doesn't support extensions. Why did you choose GNA as target?

**Comment by dorloff** [comment]
@Raise-me-up , note that GNA is very specific HW with many restrictions (some of them are resolved by the GNA plugin, some are not), and it's quite common that a model needs some reformulation to be run on GNA. Could you give some context about your task?

**Comment by Raise-me-up** [comment]
> @Raise-me-up GNA is very limited and specific device which intended to be used for continuous audio workloads especially. GNA doesn't support extensions. Why did you choose GNA as target?

We want to deploy our speech enhancement models on GNA to achieve model acceleration.

**Comment by Raise-me-up** [comment]
> @Raise-me-up , note that GNA is very specific HW with many restrictions (some of them are resolved by the GNA plugin, some are not), and it's quite common that a model needs some reformulation to be run on GNA. Could you give some context about your task?

Our task is speech enhancement.

**Comment by nkogteva** [comment]
@Raise-me-up GNA is mostly used for power saving, not for acceleration, sometimes it gives no performance improvements. Have you try to use low precision on CPU?

**Comment by Raise-me-up** [comment]
> @Raise-me-up GNA is very limited and specific device which intended to be used for continuous audio workloads especially. GNA doesn't support extensions. Why did you choose GNA as target?

Dear, what does "GNA doesn't support extensions" mean?  Can't we use the custom ops to achieve the support of GNA?

**Comment by Raise-me-up** [comment]
> @Raise-me-up GNA is mostly used for power saving, not for acceleration, sometimes it gives no performance improvements. Have you try to use low precision on CPU?

OMG！Are we working towards the wrong direction? We have not tried the low precision on CPU yet.

**Comment by nkogteva** [comment]
@Raise-me-up As I said GNA doesn't support extensinos. But I'm not sure actually that GNA is suitable for your scenaraio. 
You can find information about possible futher optimization steps in the following section: https://docs.openvino.ai/latest/openvino_docs_optimization_guide_dldt_optimization_guide.html#improving-performance-model-vs-runtime-optimizations

**Comment by Raise-me-up** [comment]
> @Raise-me-up As I said GNA doesn't support extensinos. But I'm not sure actually that GNA is suitable for your scenaraio. You can find information about possible futher optimization steps in the following section: https://docs.openvino.ai/latest/openvino_docs_optimization_guide_dldt_optimization_guide.html#improving-performance-model-vs-runtime-optimizations

Thanks for your detailed reply! Maybe our tasks are not so suitable to the deployment of GNA.  However, we just wonder the details of power saving scenaraio which GNA applys to. Could you tell us more about it please? We have run the asr demo on HETERO:GNA, CPU mode before, which shows GNA does not support the HETERO mode. So, how can GNA be used to save power? We are so confused about it.

**Comment by nkogteva** [comment]
@Raise-me-up Currently there are only one way to load whole model to GNA because HETERO is not enabled back. But there are also several improtant aspects:

1. GNA is working in integer precision only (i16, i8), so that means that model should be quantized for GNA especcialy using POT. Plugin quantization (without POT) is still available, but POT is recommended way. CPU can execute model quantized for GNA, but CPU doesn't support i16, so you will have no performance improvement even HETERO mode will be enabled. 

3.  Since your model has a lot of unsupported by GNA layers, that means that a most part of model will be fallbacked to CPU. This will take away all possible benefits from GNA usage. Moreover, you will have a lot of device memory switching before devices.

So I don't see any adventages from GNA usage for this particular model currently.

**Comment by Raise-me-up** [comment]
> @Raise-me-up Currently there are only one way to load whole model to GNA because HETERO is not enabled back. But there are also several improtant aspects:
> 
> 1. GNA is working in integer precision only (i16, i8), so that means that model should be quantized for GNA especcialy using POT. Plugin quantization (without POT) is still available, but POT is recommended way. CPU can execute model quantized for GNA, but CPU doesn't support i16, so you will have no performance improvement even HETERO mode will be enabled.
> 2. Since your model has a lot of unsupported by GNA layers, that means that a most part of model will be fallbacked to CPU. This will take away all possible benefits from GNA usage. Moreover, you will have a lot of device memory switching before devices.
> 
> So I don't see any adventages from GNA usage for this particular model currently.

Thanks so much for your precious advice again! Regardless of our model, could you tell us more about the proper GNA usages, so that we can avoid the mistakes next time please? As far as I know, the ASR demo you provide is a successful application. Is there any guideline for us to produce the similar application? And, how can the power saving of GNA be understood?

**Comment by mdeisher** [comment]
GNA is primarily for purely neural, low latency, streaming audio processing (meaning one audio frame per inference).  It has no programmable core to handle loops or decision logic.  Many noise suppression networks have been run on GNA but they have primarily been streaming applications.  When they have used LSTM layers, it is always uni-directional LSTMCell, not LSTMSequence.  For example, the Microsoft DNS challenge baseline noise suppression model runs on GNA.  https://github.com/microsoft/DNS-Challenge

**Comment by Raise-me-up** [comment]
> 

I see. To my knowledge, GNA can implement the computation with low power alone, not bearing some computing from CPU to reduce its power. And the heterogeneous computing with CPU is not supported for now.  The network to be run on GNA should support the streaming audio processing . Am I right?

**Comment by Raise-me-up** [comment]
> GNA is primarily for purely neural, low latency, streaming audio processing (meaning one audio frame per inference). It has no programmable core to handle loops or decision logic. Many noise suppression networks have been run on GNA but they have primarily been streaming applications. When they have used LSTM layers, it is always uni-directional LSTMCell, not LSTMSequence. For example, the Microsoft DNS challenge baseline noise suppression model runs on GNA. https://github.com/microsoft/DNS-Challenge

I see. To my knowledge, GNA can implement the computation with low power alone, not bearing some computing from CPU to reduce its power. And the heterogeneous computing with CPU is not supported for now. The network to be run on GNA should support the streaming audio processing . Am I right?

**Comment by Raise-me-up** [comment]
> If I understand you correctly, I'd say you are right. But please keep in mind that GNA is a streaming co-processor. This makes it different than a GPU which has a large internal memory. On a GPU, "fine grained" offload (e.g., offload of single operators) is very inexpensive since communication with internal memory is very fast. Fine grained offload to GNA is very inefficient since there is a relatively long latency each time GNA is invoked. So the most benefit of offloading to GNA comes when large "chunks" of work (i.e., many operations) are offloaded all at once. Applications like streaming noise suppression can see a significant benefit (in power and CPU utilization reduction) if the algorithm is structured as preprocessing->neural compute->postprocessing. If preprocessing and postprocessing are small (running on CPU) and neural compute is large (running on GNA) we generally see a significant power benefit. Power is best measured at the battery but you can get a rough idea by measuring "package power" differences using socwatch (https://www.intel.com/content/www/us/en/develop/documentation/energy-analysis-user-guide/top.html). CPU utilization is also measurable using socwatch.

Thank you very much for your awesome answers!
