### ISSUE TITLE
openvino-dev[pytorch] will override default torch version

### ISSUE THREAD

**Issue by xiaoyu-work** [openvinotoolkit/openvino#13670]
When installing `openvino-dev[pytorch]` package, it will automatically override existing pytorch version with torch==1.8.1 in my environment. How can I avoid this? Or can the default pytorch version in `openvino-dev`  package be upgraded to latest stable version 1.12.1?

**Comment by andrei-kochin** [comment]
Hello @xiaoyu-work,

Thanks for reaching OpenVINO!
Seems like this limitation comes from OMZ which requires specific version to guarantee proper model export to ONNX. You can simply use `openvino-dev[onnx] ` for you Pytorch environment.

Meanwhile we'll think on how to make this more transparent.

**Comment by xiaoyu-work** [comment]
This workaround works for me. Thanks @andrei-kochin !

**Comment by andrei-kochin** [comment]
Hello @xiaoyu-work,

After internal discussion we agreed to have relaxed versions for dependencies in case no extras is specified `pip install openvino-dev ` assuming developer has setup ready for the model which is going to be optimized by OpenVINO.
And at the meantime there would be still extras like `pip install openvino-dev[pytorch] ` to setup which was verified by OpenVINO. So for `pytorch` extras torch version will still have upperbound.
You can see some  details more in  #13985 as well
