### ISSUE TITLE
How to do a inference for the model with multiple input node?

### ISSUE THREAD

**Issue by Raise-me-up** [openvinotoolkit/openvino#13707]
I have read lots of samples and documents you supplied,  all of which are about the inference for the model with single input node. Is there any C++ sample code for us to implement the inference of the model with multiple input node on CPU?   

The single input node version is as follows:

```c++
ov::Core core;
std::shared_ptr<ov::Model> model = core.read_model(model_path);
ov::Tensor input_tensor = ov::Tensor(input_type, input_shape, input_data.get());
ov::CompiledModel compiled_model = core.compile_model(model, device_name);
ov::InferRequest infer_request = compiled_model.create_infer_request();
infer_request.set_input_tensor(input_tensor);
infer_request.infer();
const ov::Tensor& output_tensor = infer_request.get_output_tensor();
```

**Comment by ilya-lavrenov** [comment]
Hi @Raise-me-up 
Please, have a look https://docs.openvino.ai/latest/openvino_docs_OV_UG_Infer_request.html#working-with-input-and-output-tensors

**Comment by brmarkus** [comment]
Find an example e.g. here: https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/common/cpp/models/src/super_resolution_model.cpp

**Comment by Raise-me-up** [comment]
> Hi @Raise-me-up Please, have a look https://docs.openvino.ai/latest/openvino_docs_OV_UG_Infer_request.html#working-with-input-and-output-tensors

Thanks for your kindness!

**Comment by Raise-me-up** [comment]
> Find an example e.g. here: https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/common/cpp/models/src/super_resolution_model.cpp

Thanks for your kindness!
