### ISSUE TITLE
[Bug] Operator support Col2Im 

### ISSUE THREAD

**Issue by wrchen-voxel** [openvinotoolkit/openvino#13744]
##### System information (version)

- OpenVINO=> 2022.2.0
- Operating System / Platform => Ubuntu20.04
- Compiler => gcc 9.4.0
- Problem classification => Model Conversion
- Framework: Pytorch
- Model name: torch.nn.Fold

##### Detailed description
Now Col2Im ops is supported by ONNX opset version18 ([Add Col2Im operator](https://github.com/onnx/onnx/pull/3948)), but not supported by openvino inference engine yet.

Looking for support to at new operator in Openvino, I found that [how_to_add_op.md](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md) is not finished yet.

It seems that the new ONNX operator should be implemented under src/frontends/onnx/frontend/src/op/,
I see most of the operator defined here using combination of default_opset::XX/ngraph::opsetN::XX, but Col2Im operator contains much operations like move element from somewhere of input matrix to somewhere of output matrix.

Do you have plans to support Col2Im recently?

##### Steps to reproduce

```
>>> from openvino.inference_engine import IECore
>>> ie = IECore()
>>> net_onnx = ie.read_network(model="/opt/mnt/onnx_model/model_contains_col2im_ops.onnx")
[WARN] 2022-10-17T09:27:51z frontends/onnx/frontend/src/ops_bridge.cpp 237      Currently ONNX operator set version: 18 is unsupported. Falling back to: 16
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ie_api.pyx", line 367, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 410, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Check 'unknown_operators.empty()' failed at frontends/onnx/frontend/src/core/graph.cpp:209:
OpenVINO does not support the following ONNX operations: Col2Im
```

**Comment by andrei-kochin** [comment]
Hello @wrchen-voxel.

Thanks for reaching OpenVINO!
@mlukasze and @tomdol can comment on further plans but meanwhile you can try Frontend Op Extensions for it:
[OV Documentation](https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Frontend_Extensions.html#single-operation-mapping-with-opextension)

Best regards,
Andrei

**Comment by slyalin** [comment]
@wrchen-voxel, as @andrei-kochin mentioned it is good to start adding an implementation as an operation extension first without digging into OpenVINO source tree. It will help you to focus at the operation code itself and you can test it in "user space", so to speak, with real models.

Let me add more details to help you.

For `col2im` it looks like you have to add a C++ implementation for the operation because just briefly looking at implementation in Pytorch (https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/im2col.h#L88) I cannot say how to easily decompose it to existing OpenVINO ops. If you know the decomposition, it will simplifies the enabling according to https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Frontend_Extensions.html#mapping-to-multiple-operations-with-conversionextension. There are similar approach in Python as well.

Suppose we don't know how to decompose to existing ops, in this case follow guide https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_add_openvino_ops.html#doxid-openvino-docs-extensibility-u-g-add-openvino-ops to implement a new OpenVINO op class. You have to implement in C++ and I think that the code from Pytorch which was referenced above can be modified to implement your new op `evaluate` method that will be called from within CPU plugin during model inference. You can actually grab some fragments from real ops here: https://github.com/openvinotoolkit/openvino/tree/master/src/core/include/openvino/op.

When implementing the class, enable direct mapping from ONNX by adding two lines of code within your class scope, like in this test: https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/op_extension.cpp#L21-L22. It will automatically enable conversion from ONNX operator to this new OV op. Please assign identical name for OV op as ONNX operator name to unlock this functionality. Then you can try to load a model with this ONNX op in read_model after adding the extension class to the core according to the guide. If you don't mind please use C++ environment for the time when new op is being developed, it will save you additional steps to prepare library with op and loading it in Python. Later you can do those additional steps and continue using Python.

If everything is fine with enabling it as an extension op, then we can continue talking about contributing the op directly to OV.

**Comment by slyalin** [comment]
@wrchen-voxel, are you in? We can guide you to add the op as quick as possible, and then it can be a part of OpenVINO. BTW, could you refer to a real model that requires this op to better motivate developers?

**Comment by wrchen-voxel** [comment]
@slyalin, I'm still trying to figure out where to convert attributes from onnx ops format to openvino ops extention format, and glad if someone could implement this operator or help me implement this extension ops. And here is the model layer using torch.nn.Fold(https://github.com/CVIU-CSU/M2MRF-Lesion-Segmentation/blob/master/mmseg/models/utils/m2mrf.py) which calls col2im operator in pytorch.

**Comment by slyalin** [comment]
@wrchen-voxel, this part https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Frontend_Extensions.html#attributes-mapping address specifically your question. In short, as long as you keep names of attributes the same on both ONNX and OV sides, they will be mapped automatically. So we have to define attributes as class fields of type std::vector<int> and implement `visit_attributes` according to that part of the documentation. You can see very similar definitions in `Convolution` class here: https://github.com/openvinotoolkit/openvino/blob/master/src/core/src/op/convolution.cpp#L41-L45.

Everything else with mapping will be done automatically, you will just use these attributes in your `evaluate` function then to implement the kernel.

You can copy `Identity` op class as a template for you op from https://github.com/openvinotoolkit/openvino/tree/master/src/core/template_extension/new directly to your app and populate methods according to the guide.

**Comment by wrchen-voxel** [comment]
@slyalin, thanks for your patient guide! Now I'm trying to use src/core/template_extension/new/CMakeLists.txt to build exetention lib of it in the build directory. And I met some new problems here.
Like guide above, I use some macro like  OPENVINO_FRAMEWORK_MAP(for ONNX mapping), NGRAPH_TYPE_CASE (call evaluate with template input/out type). how to include head file like "itt.hpp " and "openvino/frontend/onnx/extension/op.hpp" correctly so that the compiler could find it?
And  I'm also wondering that does the Operator Class construct itself with arguments accepted first with operator inputs and then with the operator attributes?

**Comment by ilya-lavrenov** [comment]
> 

Why do you need to include itt header? It's not required to write extensions. 
The information how to build the library is provided in this section https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Intro.html#create-library-with-extensions

**Comment by wrchen-voxel** [comment]
@ilya-lavrenov I used NGRAPH_TYPE_CASE implementing evaluate() which seems support multi kind of input data type like i32, u32, f32 etc. 
now i'm using 
include_directories(../../../frontends/onnx/frontend/include ../../../core/src ../../../common/conditional_compilation/include ../../../common/itt/include ../../../common/util/include)
which looks not graceful...

**Comment by slyalin** [comment]
@wrchen-voxel, please don't use NGRAPH_TYPE_CASE at this stage. Your case is simpler, just implement `evaluate` for one of data types as the first step, all these complexities shouldn't block you from writing the implementation of the kernel which can be tested with only one supported data type as the first step. Then we will reorganize it to something more flexible that may consume multiple types. @ilya-lavrenov gave a link to the guide, can you confirm that you can successfully build a library with Identity op following those steps? If yes, let's move on with populating `evaluate` as described above.

**Comment by wrchen-voxel** [comment]
@slyalin Sure that my environment supports building Identity operator with `libopenvino_template_extension.so ` generated when I follows the guide above.  
But before I can run the `evaluate`  for the test custom op(2D version col2im), I met another problem. Like below, I can set `output_shape ` in `validate_and_infer_types` with last 3 dimension `Dimension::dynamic()`.

```
Col2Im::Col2Im(
    const ov::Output<ov::Node>& input_data, 
    const ov::Output<ov::Node>& image_shape, 
    const ov::Output<ov::Node>& block_shape,
    const ov::Strides& dilations,
    const ov::Strides& pads,
    const ov::Strides& strides)
    : Op({input_data, image_shape, block_shape}),
      m_dilations(dilations),
      m_pads(pads),
      m_strides(strides) {
    printf("calling constructor Col2Im\n");
    constructor_validate_and_infer_types();
}

void Col2Im::validate_and_infer_types() {
    const auto& inputs_count = input_values().size();
    OPENVINO_ASSERT(inputs_count == 3,
                    "Input count must be 3, Got: ",
                    inputs_count);
    auto shape0 = get_input_partial_shape(0);
    auto shape1 = get_input_partial_shape(1);
    auto shape2 = get_input_partial_shape(2);
    auto rank0  = shape0.rank();
    auto rank1  = shape1.rank();
    auto rank2  = shape2.rank();

    OPENVINO_ASSERT(rank0.compatible(3) && rank1.compatible(1) && rank2.compatible(1),
                    "inputs must be 3D;1D;1D");

    auto output_shape = ov::PartialShape({shape0[0], ov::Dimension::dynamic(), ov::Dimension::dynamic(), ov::Dimension::dynamic()});
    set_output_size(1); 
    set_output_type(0, get_input_element_type(0), output_shape);
}
```

But the built custom app will raise error:
```
Check 'false' failed at plugins/intel_cpu/src/utils/shape_inference/shape_inference.cpp:256:
Can't compute static output shape on 0 port for Col2Im node with name: Col2Im_532126. Input shapes = ( 0 port = {1,1024,1024}, 1 port = {2}, 2 port = {2}, ). Output shapes = ( 0 port = {1,?,?,?}, )
```

Actually the `output_shape ` could be calculated with input value `image_shape` and `block_shape` value like:
`output_shape = {shape0[0], shape0[1] / (block_shape[0] * block_shape[1]), image_shape[0], image_shape[1]}`

Can we get the input value of operator in the scope of `validate_and_infer_types`?

**Comment by slyalin** [comment]
> Can we get the input value of operator in the scope of validate_and_infer_types?

We can do that only when real values are available in the graph, that means there is a data flow from constants nodes in the graph that can be propagated up to your specific inputs. To check the availability of constant value at particular input, please use `ov::get_constant_from_source ` from `openvino/core/validation_util.hpp` like it is used in this code https://github.com/openvinotoolkit/openvino/blob/master/src/core/src/op/interpolate.cpp#L141-L142. Usually when we are implementing `validate_and_infer_types` we handle both cases: static and dynamic. It should unlock shape propagation inside CPU plugin when real input data will be provided at those specific inputs even if in the original graph they are not constant-foldable.

**Comment by wrchen-voxel** [comment]
Got it! Here is the output extension [ud.tar.gz](https://github.com/openvinotoolkit/openvino/files/9960136/ud.tar.gz) I implemented. I have tried the 1batch 0pad situation, it seems the model speed up is not so obvious..

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic

**Comment by MasterHM-ml** [comment]
> Got it! Here is the output extension [ud.tar.gz](https://github.com/openvinotoolkit/openvino/files/9960136/ud.tar.gz) I implemented. I have tried the 1batch 0pad situation, it seems the model speed up is not so obvious..

Hey @wrchen-voxel ! Thanks for sharing the work. Can you please how do we use it? Where to put these files?

**Comment by MasterHM-ml** [comment]
> Got it! Here is the output extension [ud.tar.gz](https://github.com/openvinotoolkit/openvino/files/9960136/ud.tar.gz) I implemented. I have tried the 1batch 0pad situation, it seems the model speed up is not so obvious..

I got a guide from [OpenVINO](https://docs.openvino.ai/2022.3/openvino_docs_Extensibility_UG_Intro.html#create-a-library-with-extensions) to use the files that you shared. Thanks for sharing them.

In the provided files, a header `itt.hpp` is missing which is being called in `col2im.cpp`. Can you please share that `itt.hpp` file?

**Comment by MasterHM-ml** [comment]
> In the provided files, a header `itt.hpp` is missing which is being called in `col2im.cpp`. Can you please share that `itt.hpp` file?

By putting **absolute paths** before header files, I was able to fix these errors, and successfully `make` and `build` `col2im` extensions [(This guide helped a lot)](https://docs.openvino.ai/2022.3/openvino_docs_Extensibility_UG_Intro.html#registering-extensions). Now, as last part, when, I am adding extensions via this line of code, I am getting an error.
`core.add_extension("~/openvino/src/core/template_extension/new/build/libov_col2im_ext.so")`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Exception from src/inference/src/core.cpp:180:
Cannot add extension. Cannot find entry point to the extension library. This error happened: [ GENERAL_ERROR ] Cannot load library '/home/master/Downloads/openvino/src/core/template_extension/new/build/libov_col2im_ext.so': /home/master/Downloads/openvino/src/core/template_extension/new/build/libov_col2im_ext.so: undefined symbol: _ZTIN2ov8frontend4onnx19ConversionExtensionE
```
Any clue or hint, why the error is occurring and how one can solve it?

**Comment by ilya-lavrenov** [comment]
Hi @MasterHM-ml 
Please, add linkage with `openvino::frontend::onnx` in CMakeLists.txt:
```
target_link_libraries(${TARGET_NAME} PRIVATE openvino::frontend::onnx)
```

**Comment by MasterHM-ml** [comment]
> Hi @MasterHM-ml Please, add linkage with `openvino::frontend::onnx` in CMakeLists.txt:
> 
> ```
> target_link_libraries(${TARGET_NAME} PRIVATE openvino::frontend::onnx)
> ```


Hey, it solved my problem. Thanks a lot. I was able to convert [timm-volo based model](https://huggingface.co/timm/volo_d1_224.sail_in1k) (Pytorch -> ONNX) into OpenVINO format and do inference using OpenVINO runtime.

**Comment by abionics** [comment]
Hi everyone! I have the same issue. I'm also converting timm-volo based model (Pytorch -> ONNX) into OpenVINO

I use [this guide](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/custom_operations) in order to build [ud.tar.gz](https://github.com/openvinotoolkit/openvino/files/9960136/ud.tar.gz) extension from discussion above. I also added `target_link_libraries(${TARGET_NAME} PRIVATE openvino::frontend::onnx)` to CMakeLists.txt, but the .so file remains unchanged after rebuilding

Here's the error message:
```bash
(venv) user@user:~/Project$ mo --input_model volo.onnx --extension libov_col2im_ext.so
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Cannot load library '/home/user/Project/libov_col2im_ext.so: /home/user/Project/libov_col2im_ext.so: undefined symbol: _ZTVN2ov8frontend4onnx19ConversionExtensionE
[ ERROR ]  Traceback (most recent call last):
  File "/home/user/Project/venv/lib/python3.10/site-packages/openvino/tools/mo/convert_impl.py", line 915, in _convert
    ov_model, legacy_path = driver(argv, {"conversion_parameters": non_default_params})
  File "/home/user/Project/venv/lib/python3.10/site-packages/openvino/tools/mo/convert_impl.py", line 591, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/home/user/Project/venv/lib/python3.10/site-packages/openvino/tools/mo/convert_impl.py", line 403, in prepare_ir
    moc_front_end.add_extension(extension)
RuntimeError: Cannot load library '/home/user/Project/libov_col2im_ext.so: /home/user/Project/libov_col2im_ext.so: undefined symbol: _ZTVN2ov8frontend4onnx19ConversionExtensionE

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```

You can find my [CMakeLists.txt here](https://github.com/openvinotoolkit/openvino/files/12659954/CMakeLists.txt)

I would appreciate any assistance or insights into resolving this issue. Thank you!

**Comment by korotaS** [comment]
I had a similar issue and I managed to build an extension and then export model from ONNX to OpenVINO (and also run via OpenVINO).
My source files and .so file: [col2im_ext.zip](https://github.com/openvinotoolkit/openvino/files/15138619/col2im_ext.zip)

I followed guides from above, in CMakeLists.txt I changed absolute paths to locally cloned openvino repo and I changed .cpp code: removed `NGRAPH_TYPE_CASE` and replaced them with hardcoded CPP switch-case (btw I am very bad at CPP). 
Seems to work...
