### ISSUE TITLE
Cannot create non-max supression layer

### ISSUE THREAD

**Issue by yaswanthan** [openvinotoolkit/openvino#13774]
Hi team,

 I have tried to convert mobilenet model (TensorFlow version) to IR model.  The model gets converted and when i try to infer IR model, i get the following error.

![non_max_supresssion_layer](https://user-images.githubusercontent.com/51609619/199401503-d4ee661d-739d-4db6-9b50-60471848e5ac.png)

**Comment by rkazants** [comment]
Hi @yaswanthan,

Please update your `openvino` package for the runtime because now it looks outdated and does not support `opset9`. In the meantime, your `openvino_dev` looks fine.

Best regards,
Roman
