### ISSUE TITLE
How can I find "available devices" in the new API?

### ISSUE THREAD

**Issue by paularamo** [openvinotoolkit/openvino#13791]
What is the replacement function for running this using Python API OpenVINO 2022.2?
It seems that [this one](https://docs.openvino.ai/2021.3/ie_python_api/classie__api_1_1IECore.html#a3f993ba55b347922319023899e3e1d76) is not available anymore 
```
ie = Core()
devices = ie.available_devices
for device in devices:
    device_name = ie.get_property(device_name=device, name="FULL_DEVICE_NAME")
    print(f"{device}: {device_name}")
```

Thanks and BR

**Comment by tomdol** [comment]
There's the `ov::Core::get_available_devices` C++ method and it's exposed to Python as a property of the `Core` class https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/core/core.cpp#L550 so the snippet you provided should work. Are you getting any particular error when running that code?

**Comment by paularamo** [comment]
Yes, I got this error.

![image](https://user-images.githubusercontent.com/10940214/199503551-61561aa0-589c-4648-963d-47f7c3773f96.png)

**Comment by tomdol** [comment]
Looks like a mismatch between the arguments in the call to `get_property()` method:
![image](https://user-images.githubusercontent.com/22572387/199504344-661c35f4-77c9-4f17-9bab-647bdafb5809.png)

Please try this instead:
```
ie = Core()
devices = ie.available_devices
for device in devices:
    device_name = ie.get_property(device_name=device, property="FULL_DEVICE_NAME")
    print(f"{device}: {device_name}")
```

**Comment by paularamo** [comment]
That worked. Thanks.
![image](https://user-images.githubusercontent.com/10940214/199508336-7e2175ce-8f50-4121-886d-a4fcef961c8c.png)
