### ISSUE TITLE
EXC_BAD_ACCESS (code=1, address=0x80) on MacOS when invoking InferenceEngine::Core::LoadNetwork

### ISSUE THREAD

**Issue by impulsgraw** [openvinotoolkit/openvino#1380]
### Env: 

- MacBook Air (13-inch, 2017)
- macOS Mojave 10.14.6 (18G95)
- Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz

### Code to repro:

```c++
using namespace InferenceEngine;

void somewhat() {
    Core ie;

    // whatever example produces the same behavior, 
    // over there I tried to load https://github.com/shicai/DenseNet-Caffe converted into IR with ModelOptimizer
    // more info over there https://github.com/dkurt/openvino_practice/tree/master/modules/3_classification
    CNNNetwork net = ie.ReadNetwork("./DenseNet_121.xml", "./DenseNet_121.bin");
    ExecutableNetwork execNet = ie.LoadNetwork(net, "CPU");
}
```

### Actual result:
On Debug build type the last line of the code above crashes with:
```
Exception: EXC_BAD_ACCESS (code=1, address=0x80)
```
When running the Release build, an executable crashes with the segmentation fault.

The same code built on any other PC configuration (I tried Windows/Intel-i3) doesn't produce such error.

### Expected result:
The code doesn't crash and load up the specified network

### Note:
For some reason similar code piece on Python doesn't produce such error:
```python
from openvino.inference_engine import IECore

ie = IECore()
net = ie.read_network('DenseNet_121.xml', 'DenseNet_121.bin')
exec_net = ie.load_network(net, 'CPU')
```

**There are no non-english alphabet symbols in the file-path present**

**Comment by dkurt** [comment]
> For some reason similar code piece on Python doesn't produce such error:

Can you please check that relative paths in C++ code are correct? Please try absolute path to the model

**Comment by impulsgraw** [comment]
The path specified in the "code-to-repro" is simplified for readability.
If adding 
```c++
assert(std::ifstream{ /*...arg to Core::ReadNetwork()... */ });
```
it doesn't stop the execution due to positive assertion.
Besides, in the case specified path is not valid, then I've got the crash on line with `Core::ReadNetwork` invocation.
So I think it's not something related to incorrect file-path.

**Comment by impulsgraw** [comment]
Unfortunately right now I'm struggling to connect the InferenceEngine cpp sources to definitely locate the crash, but what is accessible right now is that the exception thrown at
```asm
InferenceEngine::Data::setPrecision(InferenceEngine::Precision const&):
	pushq  %rbp
	movq   %rsp, %rbp
	subq   $0x10, %rsp
	movq   0x74c19(%rip), %rax        ; (void *)0x00007fff93130070: __stack_chk_guard
	movq   (%rax), %rax
	movq   %rax, -0x8(%rbp)
	movq   0x10(%rsi), %rax
	movq   %rax, 0x80(%rdi)           ; <---- this line 
```
So it'd most probably finally caused by **InferenceEngine::Data::setPrecision(InferenceEngine::Precision const&)**. I'll try connecting IE sources and debugging more confidently.

**Comment by dkurt** [comment]
@impulsgraw, Please try to convert model with `--data_type FP32`

**Comment by impulsgraw** [comment]
@dkurt , is it possible to convert existing IR to FP32 somehow?

**Comment by dkurt** [comment]
No, just run Model Optimizer once again but without --data_type FP16.

**Comment by impulsgraw** [comment]
Done, nothing has changed

**Comment by dkurt** [comment]
Do you mind to try to uninstall OpenVINO 2020.3 and install new OpenVINO 2020.4? You will find it by the same link.

**Comment by impulsgraw** [comment]
Hmm, I've updated to the latest OpenVINO 2020.4 and the error message has changed to 
```bash
C++ exception with description "Cannot clone network! Cloned network doesn't contain all outputs
/localdisk/jenkins/workspace/private-ci/ie/build-linux-macos/b/repos/openvino/inference-engine/include/details/ie_exception_conversion.hpp:62" thrown in the test body.
```

**Comment by maxlytkin** [comment]
@impulsgraw 
Are you able to execute verification script demo_squeezenet_download_convert_run.sh in <openvino_dir>/deployment_tools/demo directory?

**Comment by impulsgraw** [comment]
Hi all, 
I've discovered the root cause -- I use JetBrains CLion editor for debug and I've accidentally set up the environmental variables wrong way. After fixing the env variables in the editor settings the issue has disappeared, sorry for disturbing.

Thanks,
Andrey
