### ISSUE TITLE
[API] What's the best practice to use OpenVINO in cpp?

### ISSUE THREAD

**Issue by yszhou2019** [openvinotoolkit/openvino#13815]
You know, with OpenVINO in cpp, we can load model and infer like this.
```cpp

// ctor of Class
std::shared_ptr<ov::Model> model = core.read_model(model_path);
model->reshape({some shape});
ov::CompiledModel static_model = core.compile_model(model, "CPU");
ov::InferRequest infer_req = static_model.create_infer_request();


// infer of Class
infer_req.set_input_tensor(input_tensor);
infer_req.infer();
infer_req.get_output_tensor();

```

In prod, we usually place the model reshaping and model compilation in the constructor of one class. And we expose the inference to another API of this class. 
So my question is, should we add CompiledModel as the data member of this class? Or we can just add infer_request as the data member? Or both of them? Is there any difference?
If we only use infer_request as data member, there is no need to place CompiledModel as member of class, we just need to declare it as a local variable in the constructor. After ctor is called and then out of the scope of ctor, CompiledModel is detroyed and memory it takes up is recycyled. Will this lead to some exceptions?

**Comment by ilya-lavrenov** [comment]
Hi @yszhou2019 

You can create inference requests and remove Core, CompiledModel objects.
InfereRequest keeps internally all references (including internals of CompiledModel) which are needed during its lifetime and correct destruction.

**Comment by yszhou2019** [comment]
Thank you! @ilya-lavrenov
