### ISSUE TITLE
Error running pedestrian tracker demo in debug

### ISSUE THREAD

**Issue by zvif** [openvinotoolkit/openvino#1382]
I can build and run the pedestrian tracker demo in release but when I build and run in debug I get an error (build is ok):
Assertion failed: !"unknown data_type", file C:\j\workspace\private-ci\ie\build-windows-icc2018\b\repos\openvino\inference-engine\thirdparty\mkl-dnn\src\common\type_helpers.hpp, line 70
I am using Visual Studio 2017 with OpenVino version 2020.4.287

**Comment by jgespino** [comment]
Hi @zvif 

Thanks for reaching out, I was able to reproduce your issue with the pedestrian tracker demo using person-reidentification-retail-0270 and have opened a bug for the dev team to take a look. In the meantime, could you try running the demo with the [person-reidentification-retail-0248](https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/person-reidentification-retail-0248/) model?

Regards,
Jesus

**Comment by jgespino** [comment]
@zvif Did you try running the demo in debug mode with the person-reidentification-retail-0248 model?

**Comment by jgespino** [comment]
Closing issue, please re-open or start a new issue if additional assistance is needed.

**Comment by zvif** [comment]
Yes - the 0248 model works. (sorry for the delay)

**Comment by jgespino** [comment]
@zvif Thank you for confirming, please feel free to start a new issue if you need further assistance.
