### ISSUE TITLE
Error when run ./build_samples.sh

### ISSUE THREAD

**Issue by sbin149x** [openvinotoolkit/openvino#13838]
- OpenVINO => 2022.2.0
- Operating System / Platform =>  Ubuntu 20.04.4 LTS (Docker) on Alderlake RVP

I setup Openvino toolkit on docker following this method https://dlstreamer.github.io/get_started/install/install_guide_ubuntu.html#id1. 
However when I want to use benchmark_app I got this error when build_samples.

root@590a81af132e:/opt/intel/openvino_2022/samples/cpp# ./build_samples.sh

Setting environment variables for building samples...
[setupvars.sh] OpenVINO environment initialized
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- gflags (2.2.2) is found at /usr/lib/x86_64-linux-gnu/cmake/gflags
-- zlib (1.2.11) is found at /usr
-- nlohmann_json (3.7.3) is found at /usr/lib/cmake/nlohmann_json
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.2")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/inference_engine_._samples_build
Scanning dependencies of target ie_samples_utils
Scanning dependencies of target cnpy
[  3%] Building CXX object thirdparty/cnpy/CMakeFiles/cnpy.dir/cnpy.cpp.o
[  9%] Building CXX object common/utils/CMakeFiles/ie_samples_utils.dir/src/common.cpp.o
[  9%] Building CXX object common/utils/CMakeFiles/ie_samples_utils.dir/src/args_helper.cpp.o
[ 12%] Building CXX object common/utils/CMakeFiles/ie_samples_utils.dir/src/slog.cpp.o
[ 15%] Linking CXX static library ../../intel64/Release/lib/libie_samples_utils.a
[ 15%] Built target ie_samples_utils
Scanning dependencies of target format_reader
Scanning dependencies of target hello_query_device
[ 18%] Building CXX object hello_query_device/CMakeFiles/hello_query_device.dir/main.cpp.o
[ 21%] Building CXX object common/format_reader/CMakeFiles/format_reader.dir/MnistUbyte.cpp.o
[ 24%] Building CXX object common/format_reader/CMakeFiles/format_reader.dir/bmp.cpp.o
[ 27%] Building CXX object common/format_reader/CMakeFiles/format_reader.dir/format_reader.cpp.o
[ 30%] Building CXX object common/format_reader/CMakeFiles/format_reader.dir/opencv_wrapper.cpp.o
[ 33%] Building CXX object common/format_reader/CMakeFiles/format_reader.dir/yuv_nv12.cpp.o
[ 36%] Linking CXX static library ../../intel64/Release/lib/libcnpy.a
[ 36%] Built target cnpy
Scanning dependencies of target speech_sample
[ 39%] Building CXX object speech_sample/CMakeFiles/speech_sample.dir/main.cpp.o
[ 42%] Building CXX object speech_sample/CMakeFiles/speech_sample.dir/fileutils.cpp.o
[ 45%] Linking CXX shared library ../../intel64/Release/lib/libformat_reader.so
[ 45%] Built target format_reader
Scanning dependencies of target hello_classification
Scanning dependencies of target classification_sample_async
Scanning dependencies of target benchmark_app
[ 48%] Linking CXX executable ../intel64/Release/hello_query_device
Scanning dependencies of target hello_nv12_input_classification
Scanning dependencies of target hello_reshape_ssd
[ 54%] Building CXX object classification_sample_async/CMakeFiles/classification_sample_async.dir/main.cpp.o
[ 54%] Building CXX object hello_classification/CMakeFiles/hello_classification.dir/main.cpp.o
[ 57%] Building CXX object hello_nv12_input_classification/CMakeFiles/hello_nv12_input_classification.dir/main.cpp.o
[ 60%] Building CXX object benchmark_app/CMakeFiles/benchmark_app.dir/inputs_filling.cpp.o
[ 60%] Built target hello_query_device
[ 63%] Building CXX object hello_reshape_ssd/CMakeFiles/hello_reshape_ssd.dir/main.cpp.o
Scanning dependencies of target model_creation_sample
[ 66%] Building CXX object model_creation_sample/CMakeFiles/model_creation_sample.dir/main.cpp.o
[ 69%] Building CXX object benchmark_app/CMakeFiles/benchmark_app.dir/main.cpp.o
[ 72%] Linking CXX executable ../intel64/Release/hello_classification
[ 75%] Linking CXX executable ../intel64/Release/classification_sample_async
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_origin_name'
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_table_name'
collect2: error: ld returned 1 exit status
make[2]: *** [hello_classification/CMakeFiles/hello_classification.dir/build.make:89: intel64/Release/hello_classification] Error 1
make[1]: *** [CMakeFiles/Makefile2:476: hello_classification/CMakeFiles/hello_classification.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 78%] Building CXX object benchmark_app/CMakeFiles/benchmark_app.dir/remote_tensors_filling.cpp.o
[ 81%] Linking CXX executable ../intel64/Release/hello_reshape_ssd
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_origin_name'
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_table_name'
collect2: error: ld returned 1 exit status
make[2]: *** [classification_sample_async/CMakeFiles/classification_sample_async.dir/build.make:89: intel64/Release/classification_sample_async] Error 1
make[1]: *** [CMakeFiles/Makefile2:448: classification_sample_async/CMakeFiles/classification_sample_async.dir/all] Error 2
[ 84%] Building CXX object benchmark_app/CMakeFiles/benchmark_app.dir/statistics_report.cpp.o
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_origin_name'
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_table_name'
collect2: error: ld returned 1 exit status
make[2]: *** [hello_reshape_ssd/CMakeFiles/hello_reshape_ssd.dir/build.make:89: intel64/Release/hello_reshape_ssd] Error 1
make[1]: *** [CMakeFiles/Makefile2:559: hello_reshape_ssd/CMakeFiles/hello_reshape_ssd.dir/all] Error 2
[ 87%] Building CXX object benchmark_app/CMakeFiles/benchmark_app.dir/utils.cpp.o
[ 90%] Linking CXX executable ../intel64/Release/speech_sample
[ 90%] Built target speech_sample
[ 93%] Linking CXX executable ../intel64/Release/hello_nv12_input_classification
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_origin_name'
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_table_name'
collect2: error: ld returned 1 exit status
make[2]: *** [hello_nv12_input_classification/CMakeFiles/hello_nv12_input_classification.dir/build.make:89: intel64/Release/hello_nv12_input_classification] Error 1
make[1]: *** [CMakeFiles/Makefile2:504: hello_nv12_input_classification/CMakeFiles/hello_nv12_input_classification.dir/all] Error 2
[ 96%] Linking CXX executable ../intel64/Release/model_creation_sample
[ 96%] Built target model_creation_sample
[100%] Linking CXX executable ../intel64/Release/benchmark_app
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_origin_name'
/usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to `sqlite3_column_table_name'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmark_app/CMakeFiles/benchmark_app.dir/build.make:151: intel64/Release/benchmark_app] Error 1
make[1]: *** [CMakeFiles/Makefile2:420: benchmark_app/CMakeFiles/benchmark_app.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Error on or near line 91; exiting with status 1

Can somebody help me to pointed out if my method wrong or if I miss something. Never face this issue before so I'm not sure how to debug. 
Thanks.

**Comment by brmarkus** [comment]
You could align with OpenVINO's Dockerfiles under "https://github.com/openvinotoolkit/docker_ci/tree/releases/2022/1/dockerfiles".

Or, just use one of the pre-built containers, pushed to the Docker Hub, like:

(Showing for version 2022.1)
`docker pull openvino/ubuntu20_dev:2022.1.0`

And then, inside the container, build the inference-engine samples:

```
cd /opt/intel/openvino_2022.1.0.643/install_dependencies
./install_openvino_dependencies.sh

cd /opt/intel/openvino_2022.1.0.643/extras/scripts
./download_opencv.sh

$> cd
$> mkdir inference_engine_samples
$> cd inference_engine_samples

cmake -DCMAKE_BUILD_TYPE=Release /opt/intel/openvino_2022.1.0.643/samples/cpp/
make -j `nproc`
```

**Comment by sbin149x** [comment]
Does it make a difference if setup openvino from repo or using package from https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.2/linux/ ? I try to understand the diff as we are having custom docker build.

**Comment by ilya-lavrenov** [comment]
> /usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to sqlite3_column_origin_name' /usr/bin/ld: /usr/lib/libgdal.so.26: undefined reference to sqlite3_column_table_name'

this is not used in OpenVINO. Maybe some problems with environment..

**Comment by brmarkus** [comment]
> Does it make a difference if setup openvino from repo or using package from https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.2/linux/ ? I try to understand the diff as we are having custom docker build.

The source-code repo only contains open-source components, but for instance doesn't contain support for the Myriad-X (NCS2) device VPU; but the pre-built OpenVINO installation contains support for e.g. Myriad-X.

You could use one of the different pre-built OpenVINO Docker contains as a base for your proprietary Dockerfile:

# https://github.com/openvinotoolkit/docker_ci/tree/releases/2022/1/dockerfiles
#    * runtime: IE core, nGraph, plugins
#    * dev: IE core, nGraph, plugins, samples, Python dev tools: Model Optimizer, Post training Optimization tool, Accuracy checker, Open Model Zoo tools (downloader, converter)
#    * base (only for CPU): IE core, nGraph

Like:
openvino/ubuntu20_dev
openvino/ubuntu20_runtime
openvino/ubuntu20_base

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
