### ISSUE TITLE
Convert pb to IR success, but when load IR model,  RuntimeError was happened

### ISSUE THREAD

**Issue by shihyulee** [openvinotoolkit/openvino#1383]
I tried to convert TensorFlow Object Detection API trained models and followed the below link
https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html

The model I choose was `faster_rcnn_inception_v2_coco_2018_01_28.tar.gz`
The transformations_config is `faster_rcnn_support.json`.
I converted it to IR successfully, but I can not load it.
I tried to use two methods to loaded model 
 `cv2.dnn.readNetFromModelOptimizer`  and `IENetwork(model=model_xml, weights=model_bin)`,
and return the same error issue:

> RuntimeError: Cannot create ROIPooling layer CropAndResize id:303

How could I deal with the issue?

**Comment by jgespino** [comment]
Hi @shihyulee 

I was able to read the IR with both the Inference Engine and OpenCV DNN module. I tested the following using OpenVINO 2020.4 release. Could you give the following a try and let me know if you have any issues?

Note: Steps below are for Windows, they should be similar for Linux too.

**Download model**
`python "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\tools\model_downloader\downloader.py" --name faster_rcnn_inception_v2_coco`

**Convert model**
`python "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\model_optimizer\mo.py" --framework tf --input_model frozen_inference_graph.pb --reverse_input_channels --data_type FP32 --tensorflow_use_custom_operations_config "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\model_optimizer\extensions\front\tf\faster_rcnn_support.json"  --tensorflow_object_detection_api_pipeline_config pipeline.config --input_shape [1,600,1024,3] --input image_tensor --output=detection_scores,detection_boxes,num_detections`

**Read model with inference engine**
```
from openvino.inference_engine import IECore
ie = IECore()
net = ie.read_network(model="frozen_inference_graph.xml", weights="frozen_inference_graph.bin")
```

**Read model with OpenCV DNN**
```
import cv2 as cv
net = cv.dnn.readNetFromModelOptimizer("frozen_inference_graph.xml", "frozen_inference_graph.bin")
```

Regards,
Jesus

**Comment by shihyulee** [comment]
Hello @jgespino, thanks for your reply.
I tried to follow your method to create IR model successfully, but some issues happened when I executed codes.
First time I executed it in my local environment (intel-openvino-ie-rt-2020.1.023.x86_64)
I got the error when I ran the line
`net = cv.dnn.readNetFromModelOptimizer('frozen_darknet_yolov3_model.xml','frozen_darknet_yolov3_model.bin')`
The error message is below

> terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Cannot create ROIPooling layer CropAndResize id:303

Then I executed same code in the docker container (openvino_2020.3.194)
I got the error when I ran the line
`net.setInput(blob)`
The error message is below

> cv2.error: OpenCV(4.3.0-openvino-2020.3.0) ../opencv/modules/dnn/src/dnn.cpp:3979: error: (-2:Unspecified error) in function > 'void cv::dnn::dnn4_v20200310::Net::setInput(cv::InputArray, const String&, double, const Scalar&)'
>  (expected: 'inputShapeLimitation.size() == blobShape.size()'), where
>     'inputShapeLimitation.size()' is 2
> must be equal to
>     'blobShape.size()' is 4

My code is below
```
net = cv.dnn.readNetFromModelOptimizer('frozen_darknet_yolov3_model.xml', 'frozen_darknet_yolov3_model.bin')
net.setPreferableBackend(cv.dnn.DNN_BACKEND_INFERENCE_ENGINE)
#net.setPreferableTarget(cv.dnn.DNN_TARGET_MYRIAD)
net.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)
frame = cv.imread(img)
blob = cv.dnn.blobFromImage(frame, size=(416, 416), ddepth=cv.CV_8U)
```

Could I ask how to solve the issue?

**Comment by jgespino** [comment]
Hi @shihyulee 

Do you see the same error when using the inference engine? Try using the python demo under C:\Program Files (x86)\IntelSWTools\openvino\inference_engine\demos\python_demos\object_detection_demo_ssd_async?

Regards,
Jesus

**Comment by shihyulee** [comment]
Hi @jgespino 
it was work when I used object_detection_demo_ssd_async.
It's a pity that using openCV's method exists issues.

**Comment by jgespino** [comment]
Hi @shihyulee 

Thanks for letting me know the model loads correctly with the OpenVINO toolkit Inference Engine using the demo code. For the OpenCV DNN method, could you please open an issue on the OpenCV GitHub?
https://github.com/opencv/opencv/issues

Regards,
Jesus
