### ISSUE TITLE
[Bug]Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'openvino.tools.mo.front.LayerNorm.LayerNorm'>)": The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by Raise-me-up** [openvinotoolkit/openvino#13851]
##### System information (version)
Mo Version:  2022.3.0-000--
Operating System / Platform => Windows 10 64 Bit
Compiler => Visual Studio 2019
Problem classification: Model optimizer
Framework: Pytorch

##### Detailed description
I just use the latest mo program built from the latest source codes to transform onnx model into IR model, but fail. Can anyone tell me how to solve the problem please? The command and bug reports are as follows:

mo --input_model DPCRN_static.onnx  --output_dir ./
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'openvino.tools.mo.front.LayerNorm.LayerNorm'>)": The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[ ERROR ]  Traceback (most recent call last):
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\utils\class_registration.py", line 278, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\middle\pattern_match.py", line 46, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\front\LayerNorm.py", line 80, in find_and_replace_pattern
    apply_pattern(graph, **self.pattern1(), action=self.replace_layer_norm)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\middle\pattern_match.py", line 83, in apply_pattern
    action(graph, match)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\front\LayerNorm.py", line 91, in replace_layer_norm
    if add_param.value.size == 1 and pow_param.value.size == 1 and add_param.value.item() <= 1e-05 \
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\main.py", line 44, in main
    ngraph_function = convert(**argv)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\convert.py", line 26, in convert
    return _convert(**args)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\convert_impl.py", line 591, in _convert
    raise e
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\convert_impl.py", line 581, in _convert
    ngraph_function = driver(argv)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\convert_impl.py", line 494, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\convert_impl.py", line 413, in prepare_ir
    graph = unified_pipeline(argv)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\pipeline\unified.py", line 13, in unified_pipeline
    class_registration.apply_replacements(graph, [
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\utils\class_registration.py", line 328, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\utils\class_registration.py", line 314, in apply_replacements_list
    apply_transform(
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\utils\logger.py", line 112, in wrapper
    function(*args, **kwargs)
  File "d:\workspace\openvino\openvino-master\tools\mo\openvino\tools\mo\utils\class_registration.py", line 302, in apply_transform
    raise Exception('Exception occurred during running replacer "{} ({})": {}'.format(
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'openvino.tools.mo.front.LayerNorm.LayerNorm'>)": The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

##### Steps to reproduce
mo --input_model DPCRN_static.onnx  --output_dir ./
[DPCRN_static.zip](https://github.com/openvinotoolkit/openvino/files/9936144/DPCRN_static.zip)

**Comment by andrei-kochin** [comment]
Hello @Raise-me-up,

Thanks for reaching OpenVINO!

Please tell me which OpenVINO version do you use?
It seems like issue is no visible on: e8c8ad19f43 which is 25 days old.
```
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: C:\Users\akochin\DPCRN_static.xml
[ SUCCESS ] BIN file: C:\Users\akochin\DPCRN_static.bin
PS C:\Users\akochin> mo --version
Version of Model Optimizer is: 2022.3.0-8242-e8c8ad19f43
```

**Comment by andrei-kochin** [comment]
@Raise-me-up Ok, seems I've managed to re-create your issue but with option `--use_legacy_frontend` on 2022.3 master baseline.
That means that you somehow using legacy(Python) ONNX frontend  instead of new(C++) frontend.
It is either old version of MO(2021.4 or earlier) or you've explicitly specified `--use_legacy_frontend` option which I hope you haven't done

```
PS C:\Users\akochin> mo -m .\Downloads\DPCRN_static\DPCRN_static.onnx --use_legacy_frontend

... <CUT HERE>

  File "C:\Users\akochin\AppData\Roaming\Python\Python39\site-packages\openvino\tools\mo\front\LayerNorm.py", line 91, in replace_layer_norm
    if add_param.value.size == 1 and pow_param.value.size == 1 and add_param.value.item() <= 1e-05 \
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by andrei-kochin** [comment]
@Raise-me-up please provide output of:
`mo --version`

Thanks !

**Comment by Raise-me-up** [comment]
> @Raise-me-up Ok, seems I've managed to re-create your issue but with option `--use_legacy_frontend` on 2022.3 master baseline. That means that you somehow using legacy(Python) ONNX frontend instead of new(C++) frontend. It is either old version of MO(2021.4 or earlier) or you've explicitly specified `--use_legacy_frontend` option which I hope you haven't done
> 
> ```
> PS C:\Users\akochin> mo -m .\Downloads\DPCRN_static\DPCRN_static.onnx --use_legacy_frontend
> 
> ... <CUT HERE>
> 
>   File "C:\Users\akochin\AppData\Roaming\Python\Python39\site-packages\openvino\tools\mo\front\LayerNorm.py", line 91, in replace_layer_norm
>     if add_param.value.size == 1 and pow_param.value.size == 1 and add_param.value.item() <= 1e-05 \
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> ```

Hi, andrei-kochin

Thanks for your reply!

The mo program I use is built from your source codes partially, and the version info is as follows:

(openvino_mo) D:\software\Pycharm\workspace\DPCRN_model\models>mo --version
fatal: not a git repository (or any of the parent directories): .git
Version of Model Optimizer is: unknown version

which is a liitle cofusing. 

I have search the version info in the build folder tool\mo, which is 

2022.3.0-000--

**Comment by Raise-me-up** [comment]
> @Raise-me-up please provide output of: `mo --version`
> 
> Thanks !

Can you provide the latest wheel file of openvio, so I can install the openvino without building?

**Comment by Raise-me-up** [comment]
@andrei-kochin It seems hard for me to completely build your source codes successfully,  as it shows in the following issue:

https://github.com/openvinotoolkit/openvino/issues/13605

Maybe a wheel file of the latest openvino will be helpful.

Thanks!

**Comment by Raise-me-up** [comment]
@andrei-kochin 

Hi, thanks to the proxy software, I have succeeded in building your source codes now! However, I can't find the proper way to install the built openvino in your wiki(https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows).  Could you provide more installation information please?

**Comment by Raise-me-up** [comment]
@andrei-kochin 

Hi, I have found the info I need in wiki(https://github.com/openvinotoolkit/openvino/wiki/BuildingCode#installing). Thank you for your help!
