### ISSUE TITLE
covert yolov3 onnx to IR success but ReadNetwork failed

### ISSUE THREAD

**Issue by syyxsxx** [openvinotoolkit/openvino#1386]
hi
when i use ReadNetwork() to load model xml file, it happened
terminate called after throwing an instance of 'std::invalid_argument'
  what():  get_shape was called on a descriptor::Tensor with dynamic shape

**Comment by ilya-lavrenov** [comment]
@syyxsxx could you please attach the result IR file? (you can upload to any file server and provide a link)

**Comment by syyxsxx** [comment]
@ilya-lavrenov
here is IR file:https://drive.google.com/file/d/1ONLIDg_bar_vw2lDffyCO5GAu-XHOXZz/view?usp=sharing
it seem because NonMaxSuppression layer but i don't know how to solve it

**Comment by ilya-lavrenov** [comment]
@jane-intel can you have a look?

**Comment by ilyachur** [comment]
I briefly looked to this issue, the problem happens because Gather operation with name: "**multiclass_nms_0.tmp_0@gather_select_scores1034**" has a dynamic output shapes.

It happens because the input with index 1 for this Gather operation also has a dynamic output shapes.

All these dynamic shapes exist on conversion to legacy step, but legacy representation don't support dynamic shapes.

**Comment by syyxsxx** [comment]
@ilyachur 
hi, do you mean openvino don't support dynamic shapes or just some op like Gather don't supoort dynamic shapes

**Comment by ilyachur** [comment]
At the current moment OpenVINO doesn't support dynamic shapes. All shapes should be defined before the inference of network.

**Comment by panshaohua** [comment]
export ir add params --static_shape

**Comment by jinfagang** [comment]
@ilya-lavrenov Does it support dynamic batchsize ？ I have a model with dynamic on batchsize still can not get shape?

**Comment by BKjungle** [comment]
> @ilya-lavrenov Does it support dynamic batchsize ？ I have a model with dynamic on batchsize still can not get shape?

I had the same problem, a single input [-1,83] onnx model could`t get shape after converting to ir, did you finally solve it?
my command: 
mo --input_model /root/onnx_ori/model.onnx  --output_dir  /root/onnx_open/ --input_shape [-1,83]
