### ISSUE TITLE
[Environment conflict]

### ISSUE THREAD

**Issue by LarryXing0** [openvinotoolkit/openvino#13878]
using the master version. 
my local enviroments: ubuntu 18.04, ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
building my example, there is a problem that intel64/libgna.so.3: error: undefined reference to 'log2', version 'GLIBC_2.29', how 
 to avoid this problem without update my enviroment. thanks very much.

**Comment by ilya-lavrenov** [comment]
Hi @LarryXing0 

This is a known issue that GNA library is built with higher version of glibc. I've left the same comment here https://github.com/openvinotoolkit/openvino/pull/13864/files#r1014144331

CC @kbruniec
