### ISSUE TITLE
[Contribution?] How do I make contribution to Wiki?

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino#13901]
https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows

I made some updates here, and how do I make a pull request/commit to this? 

[BuildingForWindows.md](https://github.com/openvinotoolkit/openvino/files/9954507/BuildingForWindows.md)

Thank you! 

-ray

**Comment by alalek** [comment]
AFAIK, There is no pull-request feature for Wiki pages on GitHub. However wiki is stored as git repository and we could clone them (read access is public)

You could enable "wiki" in your fork (through settings), edit wiki page in your fork and provide a link in comments below (or update issue's description).
Using provided link maintainers could check changes in your fork and then provide feedback/merge them to upstream project.

**Comment by ilyachur** [comment]
Hi @raymondlo84 

At the current moment we started the process of moving developer documentation from Wiki to markdown documents inside the main repository.
Windows build exists here: https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md

You can take a look and create PR with proposed changes.
Thanks.
