### ISSUE TITLE
Getting error in bounding box when we convert onnx model to IR

### ISSUE THREAD

**Issue by yaswanthan** [openvinotoolkit/openvino#13921]
Hi team,
   I have pre-train a model to detect objects. The inference comes well in onnx format. I have converted the model into openvino format and do the inference. In the inference, we get too many bounding boxes. So after that, we have done **NMS** to reduce the number of bounding box. We have used openvino API 2.0.  But still, there are too many bounding boxes. 

We have refered the following things:

1. https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/002-openvino-api
2. https://www.kaggle.com/code/raymondlo84/object-detection-mobilenetv2-with-openvino-2022-1/notebook
3.

Here I have attached our model for your reference:
[model.zip](https://github.com/openvinotoolkit/openvino/files/9968180/model.zip)

Can i know where I should focus? a) On conversion part b) Model Pre processing after conversion. 
Can i get any references?

**Comment by mlukasze** [comment]
hey @yaswanthan 
sorry for inconvenience. 
let us check it, we will back to you soon.

**Comment by brmarkus** [comment]
Can you maybe also share your ONNX-file, please?
Then it would allow to compare.
Can you provide details about how you converted the model (e.g. using model-optimizer, using which command-line parameters)?
Can you provide details about the expected inputs and outputs? Maybe something went wrong with the conversion.

Depending on the used operations and OPset-level you might be able to directly use your ONNX-model via OpenVINO - and not require to convert it to IR-format; have you already tried?

**Comment by yaswanthan** [comment]
Hi @mlukasze  @brmarkus ,

I have converted the model using "mo command"  => **mo --input model yolo.onnx**

My input shape will be **(1,416,416,3)**

My output shape will be **(n*7)**
n -> refer number of detection



I have attached the onnx file. 
[onnx_file.zip](https://github.com/openvinotoolkit/openvino/files/9969286/onnx_file.zip)

**Comment by zulkifli-halim** [comment]
Hi @yaswanthan, Can you share with us the inference code you used to run with the models (.ONNX and IR format)? 

In the meantime, please try to convert your model using this MO command and rerun the test, and see if there are any changes in your output:
`mo --input_model "yolov7-final.onnx" --input_shape [1,3,416,416] --scale 255 --use_new_frontend`

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to reopen if further assistance is needed.
