### ISSUE TITLE
fp64 and fp32, Argument element types are inconsistent.[Bug]

### ISSUE THREAD

**Issue by szu-lisili** [openvinotoolkit/openvino#14024]
I use "mo --input_model model.onnx" to convert my model.onnx to openvino IR, the onnx can be download using this url:
_https://pan.baidu.com/s/1C2cDHnCOzGkKJAPRLCJFMA?pwd=1111_
No error is reported during conversion.  But I can't open model.xml with Netron because I got the error like "**Unsupported precision "f64" in model.xml**".
I use "benchmark_app -m model.xml" to benchmark, but I got:

[ ERROR ] Check 'element::Type::merge(element_type, element_type, node->get_input_element_type(i))' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\core\src\op\util\elemen
twise_args.cpp:20:
While validating node 'v1::Subtract Subtract_6204 (Constant_6518[0]:f64{1,1,1,1}, Reshape_2639[0]:f32{1,1,1,1}) -> (dynamic...)' with friendly_name 'Subtract_6204':
Argument element types are inconsistent.
Traceback (most recent call last):
  File "D:\anaconda3\envs\py37\lib\site-packages\openvino\tools\benchmark\main.py", line 298, in run
    compiled_model = benchmark.core.compile_model(model, benchmark.device)
  File "D:\anaconda3\envs\py37\lib\site-packages\openvino\runtime\ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Check 'element::Type::merge(element_type, element_type, node->get_input_element_type(i))' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\core\src\op\util\el
ementwise_args.cpp:20:
**While validating node 'v1::Subtract Subtract_6204 (Constant_6518[0]:f64{1,1,1,1}, Reshape_2639[0]:f32{1,1,1,1}) -> (dynamic...)' with friendly_name 'Subtract_6204':
Argument element types are inconsistent.**

I tried to search for the same problem in Isuee, but they didn't solve my problem, is there anyone help me？ /(ㄒoㄒ)/~~

**Comment by mlukasze** [comment]
hey @szu-lisili of course we will try to help you :)
Let us check it, we will back to you soon.

**Comment by rkazants** [comment]
Hi @szu-lisili!

I cannot download your model because it makes me to register in some cloud stroage service. Can you share your model in a different way please?
Did you have a chance to infer your model via onnx-runtime to check if the original model is correct? It can be a case that the model is incorrectly exported.

Best regards,
Roman

**Comment by szu-lisili** [comment]
> 
I uploaded it to github:
https://github.com/szu-lisili/first_rep/blob/master/denseFCN_openvino.onnx
In fact, this model.onnx has some fake quantization nodes, so when running onnx check, an error will be reported.

**Comment by szu-lisili** [comment]
> Hi @szu-lisili!
> 
> I cannot download your model because it makes me to register in some cloud stroage service. Can you share your model in a different way please? Did you have a chance to infer your model via onnx-runtime to check if the original model is correct? It can be a case that the model is incorrectly exported.
> 
> Best regards, Roman
I uploaded it to github:
https://github.com/szu-lisili/first_rep/blob/master/denseFCN_openvino.onnx
In fact, this model.onnx has some fake quantization nodes, so when running onnx check, an error will be reported.

**Comment by szu-lisili** [comment]
> Hi @szu-lisili!
> 
> I cannot download your model because it makes me to register in some cloud stroage service. Can you share your model in a different way please? Did you have a chance to infer your model via onnx-runtime to check if the original model is correct? It can be a case that the model is incorrectly exported.
> 
> Best regards, Roman

Hi @rkazants 
I uploaded it to github:
https://github.com/szu-lisili/first_rep/blob/master/denseFCN_openvino.onnx
In fact, this model.onnx has some fake quantization nodes, so when running onnx check, an error will be reported.

**Comment by rkazants** [comment]
Hi @szu-lisili,

I also noticed some inconsistency in the model that `FakeQuantize` nodes have input of different types `fp32` and `fp64`.
@szu-lisili, could you please send details (tool, cmd-line) how you got such model with FakeQuantize?

cc @alexsu52

Best regards,
Roman

**Comment by szu-lisili** [comment]
The description of the problem is rather vague, and the reproduction process is a bit complicated. I haven't solved it. I changed another way to achieve my goal, so I close this issue
