### ISSUE TITLE
Different data types while converting via pot

### ISSUE THREAD

**Issue by HFVladimir** [openvinotoolkit/openvino#1404]
Hi! I've successfully created IR with mo.py from my Cascade Hrnet onnx model and can inference it with engine. Then I've tried to run pot from my IR model and after `INFO:compression.pipeline.pipeline:Finished: DefaultQuantization`  
I've got set of errors like `[ ERROR ] Elementwise operation 4288 has inputs of different data types: <class 'numpy.int64'> and <class 'numpy.float32'>`

All of this errors actually `type="Multiply"` layers which trying to multiply two `type="FakeQuantize"` layers and the first got int type based on previous first input and second got float. The problem is what original IR model has both Multiply input in int type and while converting pot added layer like `*/fq_input_1/Convert_to_float` before one FQ layer and hasn't added the same to second. Layers in original IR passed to Multiply are `type="Add"` and `type="Const"`. As I understood pot added coverter to float only for Const layer.

So how I can solve this problem? I've attached my original IR xml and xml after pot. Thanks!
[original.xml.zip](https://github.com/openvinotoolkit/openvino/files/4950649/original.xml.zip)
[converted.xml.zip](https://github.com/openvinotoolkit/openvino/files/4950730/converted.xml.zip)

**Comment by jgespino** [comment]
Hi @HFVladimir 

Are you seeing this error message when running inference with the optimized model or during optimization? 

Please provide the following information:

- What version of the OpenVINO toolkit are you using?
- Are you using a custom trained model or pre-trained model?
- Link to Cascade Hrnet onnnx model used, if custom trained please link the base model used.

Regards,
Jesus

**Comment by HFVladimir** [comment]
Hi @jgespino 

I've got errors while calling `ie.read_network` from python API.
<img width="851" alt="read_network" src="https://user-images.githubusercontent.com/30949271/88469354-d0031000-cf01-11ea-9165-f5482715c41b.png">

So this errors very similar to errors at the end of `pot` optimization.

I'm using the latest 2020.4 version, trying to optimize custom model built with mmdetection + onnx

I cant attach onnx file but I'll provide the problem sector from Netron visualization:
Original onnx model multiplying nms result with shape with another tensor both casted to int64.
<img width="389" alt="onnx_mul" src="https://user-images.githubusercontent.com/30949271/88469474-f8d7d500-cf02-11ea-846e-c84913e1eaa2.png">
As I understood, after running `mo.py` IR transformed slice+cast for nms into VariadicSplit and shape stored in custom field in Multiply layer. Input and custom both int64.
<img width="870" alt="openvino_mul" src="https://user-images.githubusercontent.com/30949271/88469502-2e7cbe00-cf03-11ea-8abf-580c8fa74099.png">
After using `pot` FakeQuantize was added after int64 VariadicSplit output and custom from Multiply was excluded to separate int64 Constant layer and FakeQuantize also applied. But between Constant and FakeQuantize here is additional cast to float32 which makes FakeQuantize result float32.
<img width="1232" alt="pot_mul" src="https://user-images.githubusercontent.com/30949271/88469594-4b65c100-cf04-11ea-8abc-93f9741fb0bc.png">

I've tried to exclude all Mul layers with errors from config.json for pot and haven't got any errors after pot optimization. Unfortunately, here is error `RuntimeError: Not supported layout C` on `ie.load_network` step:
<img width="553" alt="layoutC" src="https://user-images.githubusercontent.com/30949271/88469749-b2d04080-cf05-11ea-93fb-ce0814ac7325.png">

I think maybe some xml graph changes with adding skip for Const cast to float32 may help.

**Comment by jgespino** [comment]
Hi @HFVladimir 

Does your model contain 1 dimension input layout? OpenVINO only supports 2-5 dimension input layout on CPU. See [supported input layout](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_Supported_Devices.html#supported_input_layout) documentation.

Regards,
Jesus

**Comment by HFVladimir** [comment]
Hi! 

Thanks for your answer. My model has input size [1,3,800,800] in uncomperssed IR, I didn't see any keys to specify it for pot convertation. I assume it is the same. Model in uncomperssed IR has a lot of layers with layout C and it works correctly. 

Does to make sense to exclude all layers with errors from pot config as I did? How I can debug the last error with layout C?

Regards,
Vladimir

**Comment by jgespino** [comment]
@HFVladimir Let me reach out to some peers to get some additional input.

Ref. 35953

**Comment by AlexKoff88** [comment]
@HFVladimir, can you please provide information about what dataset do you use to quantize this model?

**Comment by jgespino** [comment]
@HFVladimir Do you still need assistance? Could you provide the additional information requested?

**Comment by jgespino** [comment]
I am closing the issue, please feel free to re-open or start a new issue if additional assistance is needed.
