### ISSUE TITLE
Total length of splits: 2 must match the length of the chosen axis: 0

### ISSUE THREAD

**Issue by qingyou97** [openvinotoolkit/openvino#14053]
openvino use ppyoloe_plus_crn_s_80e_coco.onnx
Traceback (most recent call last):
  File "D:\98project\HaiHang\camera\openvino\haihang_onnx_test\openvino_infer_baozhuangji.py", line 275, in <module>
    main()
  File "D:\98project\HaiHang\camera\openvino\haihang_onnx_test\openvino_infer_baozhuangji.py", line 270, in main
    res_onnx = compiled_model_onnx(inputs=[image])[output_layer_onnx]
  File "D:\anaconda\lib\site-packages\openvino\runtime\ie_api.py", line 274, in __call__
    return self.infer_new_request(inputs)
  File "D:\anaconda\lib\site-packages\openvino\runtime\ie_api.py", line 267, in infer_new_request
    return self.create_infer_request().infer(inputs)
  File "D:\anaconda\lib\site-packages\openvino\runtime\ie_api.py", line 151, in infer
    return super().infer(
RuntimeError: Check 'sum_of_splits == data_shape[axis].get_length()' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\shape_inference\include\variadic_split_shape_inference.hpp:93:
While validating node 'v1::VariadicSplit Split_1 (scale_factor[0]:f32{?,2}, Constant_1174[0]:i32{}, Constant_1175[0]:i32{2}) -> (f32{?,1}, f32{?,1})' with friendly_name 'Split_1':
Total length of splits: 2 must match the length of the chosen axis: 0

**Comment by mlukasze** [comment]
hi @qingyou97  
thanks for reaching us out.

can you share a model you tested, with us?
it would make investigation a lot easier.

**Comment by qingyou97** [comment]
My model is relatively large. Can I send it to your email address?Is your email [michal.lukaszewski@intel.com](mailto:michal.lukaszewski@intel.com)？

**Comment by mlukasze** [comment]
if it is large email may be not a best option ;)
maybe upload on github is possible?

**Comment by qingyou97** [comment]
> 如果是大电子邮件可能不是最佳选择;)也许可以在 GitHub 上上传？

Thank you. I trimmed the pdmodel and then ， The input of scaled-factor has been deleted. After being re exported to onnx, openvino can be used for reasoning, and the result is correct. ！ It's my input and output problem!

**Comment by avitial** [comment]
Closing this as it seems the issue has been resolved. Feel free to reopen to ask any questions related to this topic.
