### ISSUE TITLE
How to create and handle a multi dimension tensor by CPP?

### ISSUE THREAD

**Issue by Raise-me-up** [openvinotoolkit/openvino#14065]
As mentioned, I want to create a 4D tensor by CPP, but I don't know the correct way to store it. Can anyone support some guides please?

**Comment by Raise-me-up** [comment]
Is there any method to load the 4D tensor by file, such as np.load()?

**Comment by zulkifli-halim** [comment]
Hi @Raise-me-up,

You can refer to these pages for guidance on creating a C++ sample and application:

- [Model Creation C++ Sample](https://docs.openvino.ai/2022.2/openvino_inference_engine_samples_model_creation_sample_README.html)
- [Integrate OpenVINO™ with Your Application](https://docs.openvino.ai/2022.2/openvino_docs_OV_UG_Integrate_OV_with_your_application.html)

**Comment by Raise-me-up** [comment]
Hi @zulkifli-halim

I have read the docs you provide, which have no content about the multi dimension tensor process.

Thank you all the same!

**Comment by Raise-me-up** [comment]
@zulkifli-halim 

I notice the method to create a tensor, which is as follows:

ov::Tensor input_tensor(input_port.get_element_type(), input_port.get_shape(), memory_ptr);

And I wonder how can the multi dimension tensor be stored? Does the memory_ptr point to a 1D tensor?

**Comment by hbalasu1** [comment]
Hi @Raise-me-up 

You may want to refer to this documentation that explains Tensor (https://docs.openvino.ai/latest/classov_1_1Tensor.html#details-classov-1-1-tensor)
To answer your question, yes, memory_ptr is to point to a 1-dimensional tensor.

Hope this information help.
