### ISSUE TITLE
which instruction set will be selected?

### ISSUE THREAD

**Issue by YongtaoHuang1994** [openvinotoolkit/openvino#1407]
When my CPU supports AVX512, AVX2, SSE, which one will be selected?
Or using the combination of these 3 instruction set？
Can I specify the instruction set I want to use through the python API?

**Comment by avitial** [comment]
Hi @YongtaoHuang1994, the CPU plugin supports inference on Intel® Xeon® with Intel® Advanced Vector Extensions 2 (Intel® AVX2), Intel® Advanced Vector Extensions 512 (Intel® AVX-512), and AVX512_BF16, Intel® Core™ Processors with Intel® AVX2, Intel Atom® Processors with Intel® Streaming SIMD Extensions (Intel® SSE). You can use `-pc` the flag for samples to know which configuration is used by some layer. This flag shows execution statistics that you can use to get information about layer name, execution status, layer type, execution time, and the type of the execution primitive. For example:

```
data_U8_FP32_Scale1/Add_      EXECUTED       layerType: Reorder            realTime: 128       cpu: 128             execType: jit_uni_I8
fire11/expand3x3              EXECUTED       layerType: Convolution        realTime: 548       cpu: 548             execType: jit_avx2_FP32
Concat10_nChw8c_nchw_fc7_m... NOT_RUN        layerType: Reorder            realTime: 0         cpu: 0               execType: jit_uni_FP32
fc7_mbox_conf                 EXECUTED       layerType: Convolution        realTime: 600       cpu: 600             execType: jit_avx2_FP32
mbox_conf_softmax             EXECUTED       layerType: SoftMax            realTime: 66        cpu: 66              execType: jit_avx2_FP32
fc7_mbox_loc                  EXECUTED       layerType: Convolution        realTime: 1457      cpu: 1457            execType: jit_avx2_FP32

```

So if your CPU supports multiple instructions set, you can find out if it uses only one or a combination of instruction sets for each layer in your model. I'd suggest to check out the [benchmark_app ](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_samples_benchmark_app_README.html) if you'd like to try this out. I am not sure if there is a way to specify which instruction set to use, is there a specific reason why you want to do this?

Regards,
Luis

**Comment by YongtaoHuang1994** [comment]
Really thank you.

**Comment by brmarkus** [comment]
Plus the extension "AVX-512 Vector Neural Network Instructions (AVX512 VNNI)"

**Comment by avitial** [comment]
Closing this, I hope previous response were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
