### ISSUE TITLE
unsupported layer type "FakeQuantize" on Jetson Nano

### ISSUE THREAD

**Issue by mzwtjp** [openvinotoolkit/openvino#14078]
Trying to run OpenVINO demos on Jetson Nano.
I could build libraries from openvino source and also built open model zoo demos.

However, I am seeing "unsuppored layer type" errors like below:

> object_detection_demo -d MYRIAD -i xxxx.mp4 -m ./intel/yolo-v2-ava-0001/FP16-INT8/yolo-v2-ava-0001.xml -at yolo --labels openvino/model_zoo/data/dataset_classes/voc_20cl.txt
> [ INFO ] OpenVINO
> [ INFO ] version: 2022.3.0
> [ INFO ] build: 2022.3.0-8655-5ac06838cd8
> [ INFO ] Reading model ./intel/yolo-v2-ava-0001/FP16-INT8/yolo-v2-ava-0001.xml
> [ INFO ] Model name: yolo-v2-ava-0001
> [ INFO ] Inputs:
> [ INFO ] data, f32, {1,416,416,3}, [N,H,W,C]
> [ INFO ] Outputs:
> [ INFO ] yolo_out_postprocess/YoloRegion, f32, {1,21125}, [...]
> [ ERROR ] [ GENERAL_ERROR ]
> openvino/src/plugins/intel_myriad/graph_transformer/src/frontend/frontend.cpp:594 Failed to compile layer "yolov2/darknet19_model/conv1/Conv2D/fq_input_0": unsupported layer type "FakeQuantize"
> 

Using the same command line (using the same MYRIAD device only) and data files, on Intel based PC (using stock OpenVINO environment for that), I do not see this error and the demo sucessfully showing the demo output window.

Q) Does this mean my build on Jetson Nano is somewhere corrupted (is so, where?) and if I do it properly, the demo should be working?
Or, (though using exactly the same MYRIAD devie) something needed to be done for Jetson so that demo to work properly?

I am not sure how to proceed with this, since I am new to OpenVINO and omz demos.

Any advice is highly appreciated!

**Comment by Iffa-Meah** [comment]
@mzwtjp it seems that the issue originated from your model. 
Just to clarify, did you use OpenVINO downloader tool to download the model? I believe that model is an Intel Pre-trained model.

Another thing to note is that the OpenVINO build from source version  2022.3.0 is still under development and has not been fully fledged yet.

It is best to use 2022.2 as of now (until the official public release of 2022.3 has been announced), if you require a precise functionality instead of a try-out env.

Refer to [OpenVINO Release Notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes.html).

**Comment by mzwtjp** [comment]
Yes, models are intel pre-trained models downloaded by omz_downloader tool.

This is the cmake command line I used to build openvino libraries, not should if it is the same as the pre-built intel PC one (openvino/ubuntu20_runtime:2022.2.0 image).

> cmake -DCMAKE_BUILD_TYPE=Release \
>     -DENABLE_MKL_DNN=OFF \
>     -DENABLE_CLDNN=ON \
>     -DENABLE_GNA=OFF \
>     -DENABLE_SSE42=OFF \
>     -DTHREADING=SEQ \
>     -DENABLE_SAMPLES=OFF \
> \
>     -DPYTHON_EXECUTABLE=`which python3.6` \
>     -DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so \
>     -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 \
>     -DENABLE_WHEEL=ON \
> \
>     -DOPENVINO_EXTRA_MODULES=../openvino_contrib/modules \
>     -DBUILD_arm_plugin=ON \
>     -DBUILD_nvidia_plugin=OFF \
>     -DBUILD_java_api=OFF \
>     -DBUILD_mo_pytorch=OFF \
> 

 I just noticed I am using the 2022.2 one on intel PC.
 I will try rebuilding my Jetson build with the same version if it makes difference.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
