### ISSUE TITLE
[Bug] Inference crashes when model weights (~140MB) are loaded from memory 

### ISSUE THREAD

**Issue by sparupat** [openvinotoolkit/openvino#14103]
##### System information (version)
- OpenVINO => 2022.2. 
- OpenViNOBuild => 2022.2.0-7713-af16ea1d79a-releases/2022/2
- Operating System / Platform => OS X
- Problem classification => Model Loading Issue

##### Detailed description
I am seeing a crash upon infer request when I load large model XML and bins via memory (141MB). 

I did not encounter any issues when I load the model and weights using hard-coded paths.
I did not see any issue when I load weights up to 100MB size. 

##### Steps to reproduce
           std::string modelNamePath = "test.xml";
           std::string modelWeightsPath = "test.bin";
            ov::Core core;
            // Read xml
            std::ifstream ifs1(modelNamePath, std::ios::in | std::ios::binary);
            std::vector<uint8_t> modelData((std::istreambuf_iterator<char>(ifs1)), std::istreambuf_iterator<char>());
            // Read bin
            std::ifstream ifs2(modelWeightsPath, std::ios::in | std::ios::binary);
            std::vector<uint8_t> weightsData((std::istreambuf_iterator<char>(ifs2)), std::istreambuf_iterator<char>());

            std::string strModel(modelData.begin(), modelData.end());
            ov::Tensor weights(ov::element::u8, {weightsData.size()}, (void*) weightsData.data());
            std::shared_ptr<ov::Model> model  = core.read_model(strModel, weights);
       
           // Loading via paths work without any issue
           //model =  core.read_model(modelNamePath, modelWeightsPath);

          ov::CompiledModel compiled_model = core.compile_model(model, device_name, config);
          ov::InferRequest infer_request = compiled_model.create_infer_request();
         // Crash occurs while running the inference
          infer_request.infer()
     

          
 
##### Model zip file (111 MB)

 https://1drv.ms/u/s!AqF1wV3w5Pufgugx4uN-vpc5WLLRlA?e=wYb4tz
password:  openvino2022

**Comment by ilya-lavrenov** [comment]
```c++
std::shared_ptr<ov::Model> model  = core.read_model(_modelName, _modelWeights);
```
=>
```c++
std::shared_ptr<ov::Model> model  = core.read_model(strModel, weights);
```
?

**Comment by sparupat** [comment]
@ilya-lavrenov 
// In memory version of model and weights
std::shared_ptr<ov::Model> model  = core.read_model(strModel, weights);

// Model path version
_modelNamePath = 'test.xml'
_modelWeightsPath = 'test.bin'
 model =  core.read_model(_modelNamePath, _modelWeightsPath);

**Comment by Iffa-Meah** [comment]
@sparupat could you clarify these:
1. Which OS X version are you using?
2. Model details: Model framework & topology (e.g. Tensorflow), input/output shape (static/dynamic), any custom topology/framework layers used?

**Comment by sparupat** [comment]
1. Mac OS Monterey
2. ONNX model (Retinanet FPN architecture variant), static input and output shape with batch size = 1, no custom topology layers
3. Below URL contains IE graph generated from ONNX

https://1drv.ms/u/s!AqF1wV3w5Pufgugx4uN-vpc5WLLRlA?e=wYb4tz
password: openvino2022

**Comment by sparupat** [comment]
My main issue is the application runs fine if I load xml and bin file from path but loading from memory causes the issue. 
2. Loading the model from memory with the 100 Mb model without any issue. 

My custom inference code is derived from OpenVINO sample - hello_classification snippet.

**Comment by Iffa-Meah** [comment]
@sparupat that seems suspicious since you managed to infer the 100 Mb size without any issue.
We'll further investigate this and get back to you asap.

**Comment by hbalasu1** [comment]
Hi @sparupat 

1. Could you provide us with the error log or message you encountered? 

2. Could you also test your model with [classification_benchmark_demo](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/classification_benchmark_demo)?

**Comment by hbalasu1** [comment]
Hi @sparupat since we do not get response from you, can I close this case ?

**Comment by sparupat** [comment]
@hbalasu1 You can close the issue.

My apologies for the delay, few days back I tried loading weights to global scope vector array instead of vector at function scope, I did not run into any issue with this approach. It looks like the root cause of the issue was weights memory getting deallocated. 

std::vector<uint8_t> weightsData((std::istreambuf_iterator<char>(ifs2)), std::istreambuf_iterator<char>());
