### ISSUE TITLE
[Bug] Invalid link

### ISSUE THREAD

**Issue by djie1** [openvinotoolkit/openvino#14148]
See file: https://github.com/openvinotoolkit/openvino/blob/master/src/docs/architecture.md

The last line is "[OpenVINO Developer documentation](https://github.com/openvinotoolkit/openvino/blob/master/src/docs/index.md)", but this file does not exist.

**Comment by ilyachur** [comment]
Hi @djie1 Thank you for the issue. Created PR with the fix.
