### ISSUE TITLE
Problem format NCHW in TensorFlow to OpenVino 

### ISSUE THREAD

**Issue by AouatifZ** [openvinotoolkit/openvino#14152]
Hi all, 

I converted my tensorflow model to OpenVino Intermediate Representation 
but during the inference I had a format problem 

my tensorflow model ------> NCHW [1,3,640,640]

and during conversion to IR applies a transpose [0 3 1 2 ], and my format becomes ------------> [1,640,3,640] 

how to fix my problem 

thanks in advance

**Comment by rkazants** [comment]
Hi @AouatifZ,

Please clarify -  what OV API do you use: API 1.0 or API 2.0? 

And please share your MO cmd-line. It can be a case of incorrect usage of layout specific options. But it is just my assumption.

Best regards,
Roman

**Comment by AouatifZ** [comment]
my model tensorflow 
![b1](https://user-images.githubusercontent.com/111449259/203282199-3d3040ac-d62c-4c99-88fa-272e6c13c463.PNG)


Intermidaire Representation xml file 

![b2](https://user-images.githubusercontent.com/111449259/203282409-13ab115f-be90-4a67-9c2a-e0b7d0bbd4bf.PNG)

**Comment by AouatifZ** [comment]
Hi @rkazants 
thank you very much for your quick answer and your help too 

the command used is 
python3 openvino/tools/mo/openvino/tools/mo/mo_tf.py --saved_model_dir  'directory'  --output_dir 'directory'   --input_shape [1,3,640,640]

**Comment by rkazants** [comment]
@AouatifZ, looks a problem in MO. Can you please provide a model with fake weights or small reproducer (just cut after the first convolution operation)?
Also, please try the latest version of OV 2022.2.
Or if you use OO built from the latest source code, you can try this cmd-line:

```
mo --saved_model_dir 'directory' --output_dir 'directory' --input_shape [1,3,640,640] --use_new_frontend
```

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
