### ISSUE TITLE
Trouble with C inference example "stand alone"

### ISSUE THREAD

**Issue by ifadams** [openvinotoolkit/openvino#1424]
Hi,

To integrate into our work, we need to be able to do "standalone" compilations using generic GCC with the C (not C++) API. 

I've gotten OpenVino to build, and the C-API "inference hello" (https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/ie_bridges/c/samples/hello_classification/main.c)  example works fine and accurately using the included CMake infrastructure

However, the same exact code, which I can successfully compile and run on its own, and link to the opencv_c_wraper fails when trying to set the image size, and subsequently can't use any inference models.

Apologies for the vague problem, but wondering if there is something wrong with how I'm building and linking things.

Below are the steps I'm using to compile and link.

```
inference_include=$home/git_repos/openvino/inference-engine/ie_bridges/c/include/
inference_lib_loc=$home/git_repos/openvino/bin/intel64/Release/lib/

# Build shared library for opencv wrapper
echo "Building OpenCV Wrapper Library"
g++ -fPIC -c -Wall opencv_c_wraper.cpp
ld -shared opencv_c_wraper.o -o libopencv_c_wraper.so

echo "Building Inference Demonstrator"
gcc -I$inference_include -L$inference_lib_loc -L. main.c -linference_engine_c_api -lopencv_c_wraper
```

**Comment by ifadams** [comment]
Update: found I was missing the DUSE_OPENCV flag, but now getting a runtime error for an undefined symbol. May be an additional linking issue, continuing to dig in.

**Comment by avitial** [comment]
Hi @ifadams, what is the runtime error received for undefined symbol? Can you share any details of such? 

In addition checkout [Add Inference Engine to Your Project](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#add-inference-engine-to-your-project) section of the build instructions, perhaps missing `InferenceEngine_DIR` environment variable.


Regards,
Luis

**Comment by ifadams** [comment]
Hi Luis,

I'll take a look at what you suggested above.

In any case, here's the error

```
 symbol lookup error: libopencv_c_wraper.so: undefined symbol: _ZN2cv6imreadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi
```

I also updated the G++ build command to include the opencv libraries, but didn't seem to be helping.
```
-I$opencv_include -fPIC -c -Wall -DUSE_OPENCV -lopencv_videoio -lopencv_core -lopencv_imgcodecs opencv_c_wraper.cpp
```

**Comment by ifadams** [comment]
I think I got it working, it was needing to link the libraries in when creating the shared output, not in the original wrapper object file. Gonna keep testing but hopefully that took care of it.

**Comment by ifadams** [comment]
For interested folks in the future, below was my approach to compiling into a stand-alone  C (**Not** C++) application using GCC

```
inference_include=$HOME/openvino/inference-engine/ie_bridges/c/include/
opencv_include=$HOME/openvino/inference-engine/temp/opencv_4.3.0_ubuntu18/opencv/include/
opencv_lib_loc=$HOME/openvino/inference-engine/temp/opencv_4.3.0_ubuntu18/opencv/lib/
inference_lib_loc=$HOME/openvino/bin/intel64/Release/lib/

# Build shared library for opencv wrapper
echo "Building OpenCV Wrapper Library"
g++ -I$opencv_include -fPIC -c -Wall -DUSE_OPENCV opencv_c_wraper.cpp
g++ -L$opencv_lib_loc -shared opencv_c_wraper.o -lopencv_videoio -lopencv_core -lopencv_imgcodecs -o libopencv_c_wraper.so

# Building inference demonstration
echo "Building Inference Demonstrator"
gcc -I$inference_include -L$inference_lib_loc -L.  main.c -linference_engine_c_api -lopencv_c_wraper
```
