### ISSUE TITLE
Why must Input and Output dim orders equal? (InferenceEngine)

### ISSUE THREAD

**Issue by PG23I** [openvinotoolkit/openvino#1427]
I have a 5D input array to my model and I expect a 2D output of probabilities. I use a stack of images to generate 1 probability. If I try to implement this in C++ (works fine in Python), I get an InferenceEngine exception "input and output dim orders must equal". How can I fix this? 

Also, is NDHWC input format supported on a VPU? I don't seem to have any errors about that.

Thanks!

**Comment by ilyachur** [comment]
@PG23I Do you use VPU plugin for both cases (C++ and Python)?
"input and output dim orders must equal" is an error of VPU plugin.

@gladilov-gleb FYI

**Comment by PG23I** [comment]
Yeah, I assume specifying  device_name='MYRIAD' in the call to load_network uses the VPU plugin? Sorry if I've misunderstood something, just got started with OpenVINO.

**Comment by ilyachur** [comment]
Ok got it. you used Myriad for both cases.

Can you provide a short examples for python and C++ how do you read and load the model?

@gladilov-gleb please take a look.

**Comment by PG23I** [comment]
Hi, here's a link to the gist of the python code and my attempted C++ translation:
https://gist.github.com/PG23I/4fb0404bf9aacb954efafa43a97e9681

**Comment by ilyachur** [comment]
I looked to the code. On python all works good because you use the CPU plugin.
If in python code you change device name to MYRIAD I guess you will get the same error message.

**Comment by PG23I** [comment]
My bad, It should say MYRIAD on the python code. I'm using a raspberry pi and I've only run it on the NCS2 which works fine.

**Comment by gladilov-gleb** [comment]
@Maxim-Doronin FYI

**Comment by PG23I** [comment]
I just figured it out. My layout setting didn't match up with the actual layout used in the model in the xml file. Thanks for the help!
