### ISSUE TITLE
[Bug] `compile_model` for MYRIAD device leads to segmentation fault

### ISSUE THREAD

**Issue by Co1lin** [openvinotoolkit/openvino#14277]
##### System information (version)

- OpenVINO=> openvino_2022.2.0.7713
- Operating System / Platform => Raspbian 10
- Compiler => :grey_question:
- Problem classification => :grey_question:

##### Detailed description

Using the same XML model, model compilation in python for CPU works, but for MYRIAD (NCS 2) fails. 

```python
from openvino.runtime import Core
ie = Core()
model = ie.read_model(model="/home/pi/open_model_zoo/tools/model_tools/public/squeezenet1.1/squeezenet1.1.xml")
compiled_model = ie.compile_model(model=model, device_name="CPU") # <- works
compiled_model = ie.compile_model(model=model, device_name="MYRIAD") # <- fails
"""
Segmentation fault
"""
```

However, I can run inference on the NCS 2 with C++ example.

```python
./armv7l/Release/hello_classification ../open_model_zoo/tools/model_tools/public/squeezenet1.1/squeezenet1.1.xml ~/clock.bmp MYRIAD
[ INFO ] OpenVINO Runtime version ......... 2022.2.0
[ INFO ] Build ........... 2022.2.0-7713-af16ea1d79a-releases/2022/2
[ INFO ]
[ INFO ] Loading model files: ../open_model_zoo/tools/model_tools/public/squeezenet1.1/squeezenet1.1.xml
[ INFO ] model name: squeezenet1.1
[ INFO ]     inputs
[ INFO ]         input name: data
[ INFO ]         input type: f32
[ INFO ]         input shape: {1, 3, 227, 227}
[ INFO ]     outputs
[ INFO ]         output name: prob
[ INFO ]         output type: f32
[ INFO ]         output shape: {1, 1000, 1, 1}

Top 10 results:

Image /home/pi/clock.bmp

classid probability
------- -----------
892     0.8906250
409     0.1098022
8       0.0000000
4       0.0000000
9       0.0000000
7       0.0000000
3       0.0000000
1       0.0000000
5       0.0000000
0       0.0000000
```

**Comment by Iffa-Meah** [comment]
@Co1lin I tried the compiled_model function and I encountered the same issue as yours.

Check for available devices:
<img width="835" alt="1_dev" src="https://user-images.githubusercontent.com/79643476/204452241-cca29009-32b6-4f1b-a41a-92478e77fcc5.png">

CPU (success):
<img width="876" alt="2_cpu" src="https://user-images.githubusercontent.com/79643476/204452288-747ed1df-7905-40c4-b2c9-e8f798e9ae9c.png">


MYRIAD (failed):
<img width="810" alt="3_myriad" src="https://user-images.githubusercontent.com/79643476/204452338-90c6d855-b0db-4b12-874e-0a1d4c5ad6c4.png">


Plus, looking at this [official documentation](https://docs.openvino.ai/latest/notebooks/002-openvino-api-with-output.html), the information only covers CPU instead MYRIAD.

We'll further investigate this and get back to you asap.

**Comment by hbalasu1** [comment]
Hi @Co1lin 
Could you try on the latest OpenVINO master branch? There is a fix that is similar to your issue 2 days ago. 

#14331

**Comment by Co1lin** [comment]
Hi @hbalasu1 !

**Comment by Co1lin** [comment]
Hi @hbalasu1 !
I followed [this](https://docs.openvino.ai/nightly/openvino_docs_install_guides_installing_openvino_raspbian.html#doxid-openvino-docs-install-guides-installing-openvino-raspbian) to install Openvino Runtime on my Raspberry Pi. On this page, the download link is the same if I switch the version from latest to nightly in the right-top corner. Could you please provide a link for downloading nightly built package?

**Comment by hbalasu1** [comment]
Hi @Co1lin 
For the latest Build, you have to clone OpenVINO Github and compile based on the instruction [How to build ARM CPU plugin](https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin)

Thank you

**Comment by Co1lin** [comment]
Hi @hbalasu1 !
Actually, I also tried to compile the latest version on my own but I couldn't even use the Python API after compilation. As a result, I cannot find any way to use it now. Could you please see [this issue](https://github.com/openvinotoolkit/openvino/issues/14280)?

**Comment by hbalasu1** [comment]
Hi @Co1lin 
Have you tried using docker as suggested by @ilya-lavrenov in this #14280 
another way you could do this is to refer to [the note](https://hackmd.io/@HeywardLiu/Build-Openvino)

If you are still facing issues compiling OpenVINO on an ARM CPU, could you also screenshot the error message we will try our best to help up. 

Thank you

**Comment by hbalasu1** [comment]
Hi, @Co1lin. 
Do you able to compile OpenVINO on an ARM CPU? 
If yes, can we close this case?

**Comment by hbalasu1** [comment]
Hi @Co1lin, 
Since we have not received any response, we will close this case. 
If you have further questions on OpenVINO, feel free to file an issue.

Thank you
