### ISSUE TITLE
 Python ie_api

### ISSUE THREAD

**Issue by thibault390** [openvinotoolkit/openvino#1428]
Hi,

I correctly builded IE on raspberry pi4 with unbuntu 18.04 by following the tuto:

When I want to build Python API with the following cmake command:

cmake -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=`which python3.6` -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 ..

It says the following error:

By not providing "FindInferenceEngineDeveloperPackage.cmake" in
CMAKE_MODULE_PATH this project has asked CMake to find a package
configuration file provided by "InferenceEngineDeveloperPackage", but CMake
did not find one.

Could not find a package configuration file provided by
"InferenceEngineDeveloperPackage" with any of the following names:

InferenceEngineDeveloperPackageConfig.cmake
inferenceenginedeveloperpackage-config.cmake

Add the installation prefix of "InferenceEngineDeveloperPackage" to
CMAKE_PREFIX_PATH or set "InferenceEngineDeveloperPackage_DIR" to a
directory containing one of the above files. If
"InferenceEngineDeveloperPackage" provides a separate development package
or SDK, be sure it has been installed.

This package is built with inference engine, I don't understand why this package is not found.
Is possible to use our own python?

Thanks for help

**Comment by avitial** [comment]
Hi @thibault390 if I am not mistaken I believe your paths above are slightly inaccurate. Are you using Ubuntu Server 18.04 64-bit? If so for Python, v3.6.9 for example, the cmake command would look similar to:
`cmake -DENABLE_PYTHON=ON \`
`     -DPYTHON_EXECUTABLE=/usr/bin/python3.6 \`
`     -DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so \`
`     -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 \`
`     ..`

Also make sure to install all additional packages listed in the `/inference-engine/ie_bridges/python/requirements.txt` file:
`pip install -r requirements.txt`. Let me know if issue persists or you have any additional questions.

Regards,
Luis

**Comment by thibault390** [comment]
Thanks for help, I solved my problem.
It was due to incorrect default paths in the cmake and then make commands.

Now I have the ie_api.so folder and I'm trying to import openvino environment to my python version because I don't have a setupvars.sh folder so if you have an idea 👍  .

**Comment by avitial** [comment]
@thibault390 glad its working now! I will go ahead and close this issue, feel free to reopen and ask any additional questions related to this topic.
