### ISSUE TITLE
RuntimeError in aarch64 Pi

### ISSUE THREAD

**Issue by vividricky** [openvinotoolkit/openvino#14331]
Hi. 
I was trying to inference in 64-bit(aarch64) Pi and OS is Buster.

When I tried to run 

```
from openvino.runtime import Core
ie = Core()
model_xml = "p_model.xml"
pose_model = ie.read_model(model=model_xml)
pose_model = ie.compile_model(model=pose_model, device_name="CPU")
``` 
I got the error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/intel/openvino/python/python3.7/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Cannot load library: path 'libopenvino_arm_cpu_plugin.so' is not absolute.
```

My cmake command is:
```
cmake -DCMAKE_BUILD_TYPE=Release \
      -DENABLE_SSE42=OFF \
	-DCMAKE_INSTALL_PREFIX=/opt/intel/openvino \
	  -DENABLE_OPENCV=OFF \
      -DTHREADING=SEQ \
      -DENABLE_GNA=OFF \
	  -DENABLE_PYTHON=ON \
	-DCMAKE_CXX_FLAGS="-pthread" \
	-DARM_COMPUTE_SCONS_JOBS=$(nproc –all) \
	  -DIE_EXTRA_MODULES= /home/pi/openvino_contrib/modules/arm_plugin \
	  -DPYTHON_EXECUTABLE=/usr/bin/python3.7 \
      -DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.7m.so \
      -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 ..
```

Please let me know if you havea solution.

Thank you so much.

**Comment by brmarkus** [comment]
Can you provide more details about how you have built and installed the ARM plugin?
Using one of the options under "https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin"?

**Comment by vividricky** [comment]
Thanks for your reply.

I used 
```
docker image build -t arm-plugin -f dockerfiles/Dockerfile.RPi32_stretch .
docker container run --rm -ti -v $PWD/build:/arm_cpu_plugin arm-plugin
```
to install the ARM plugin.

And there was another error when I tried
```
docker image build -t arm-plugin -f dockerfiles/Dockerfile.RPi32_buster .
```

it showed
```
no module named "_queue"
```
Sorry that I didn't save the detailed log of it.

**Comment by ilya-lavrenov** [comment]
@vividricky could you please latest OpenVINO master? We reverted some breaking changes

**Comment by vividricky** [comment]
Thx. I will try it.

**Comment by vividricky** [comment]
Hi. 
I rebuilt the OpenVINO with the latest vision and installed the plugin followed by [ARM plugin](https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin). And it threw the error:
```
pose_model = ie.compile_model(model=pose_model, device_name="CPU")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/intel/openvino/python/python3.7/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Device with "CPU" name is not registered in the OpenVINO Runtime
```

Do you have any advice for this problem?
Thanks for the help!

**Comment by ilya-lavrenov** [comment]
Looks like plugins.xml file does not contain ARM plugin, so you have built the code differently comparing with the instruction

**Comment by vividricky** [comment]
I still used the above commands to build openvino and arm plugin.  According to [this](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/LibarmPlugin-so-and-Gstreamer-Plugin-missing/m-p/1300958), I build openvino first and then install the arm plugin. Do you have any idea to correct the commands/build?

**Comment by HeywardLiu** [comment]
@vividricky 
Hi, You can refer [the note](https://hackmd.io/@HeywardLiu/Build-Openvino) I took, which gives a detailed instructions to build from sources step by step. I hope this would help you.
