### ISSUE TITLE
How to reshape and transpose tensor in openvino?

### ISSUE THREAD

**Issue by Raise-me-up** [openvinotoolkit/openvino#14361]
Hi~

I have a request to handle data in openvino, such as reshape and transpose tensor, and the information about it is limited. Anyone can provide some useful tips, please?

I try the set_shape method, but it can't work.

**Comment by rkazants** [comment]
Hi @Raise-me-up,

Please elaborate your scenario. Would you like to have the pre-processing part additionally added into your original model? Or you just build OV model using OV opset.

If you would like to have pre-processing, use MO options like `--mean_values`, `--scale_values`, `--reverse_input_channels`, or changing layout (of input data to which one accepted by the model) using `--layout`. See `mo --help`.

If you would like to build your own graph. Here is an example how to build a graph and run it where you can replace it with `Transpose` and other operations you need. The whole opset python API is [here](https://docs.openvino.ai/latest/api/ie_python_api/_autosummary/openvino.runtime.opset8.html). 

```
import numpy as np
import openvino.runtime.opset8 as ov
from openvino.runtime import Model, Core

# create a model with TopK
param = ov.parameter([10], name="data", dtype=np.int32)
k = ov.constant(np.array(10, dtype=np.int32))
topk = ov.topk(param, k, 0, 'min', 'index', "i32")
model = Model([topk.output(0), topk.output(1)], [param], "model")

# infer it on CPU
data = np.array([1, 3, 1, 2, 4, 4, 0, 1, 3, 2], dtype=np.int32)
core = Core()
compiled_model = core.compile_model(model, "CPU")
output = compiled_model.infer_new_request({0: data})

```

**Comment by Raise-me-up** [comment]
Hi @rkazants 

Thank you for your reply!

I would like to add pre-processing part additionally before my original model in CPP, not intending to modify it. The reshape and transpose ops are only the data pre-processing part outside model.  Can I modify the tensor after it is created in openvino? Or do I have to try other cpp matrix libs to process the data as model requests?

**Comment by ilya-lavrenov** [comment]
@Raise-me-up 

You can do this by inserting preprocessing steps for specific input as a part of the model https://docs.openvino.ai/latest/openvino_docs_OV_UG_Preprocessing_Details.html

Preprocessing builder supports transpose via layout conversion, reshape operation can be inserted as custom preprocessing step.

**Comment by rkazants** [comment]
Hi @Raise-me-up,

As Ilya mentioned, you can use our documentation for more details. Here is a code sample for your case with Transpose and Reshape:

```
import numpy as np
import openvino.runtime.opset9 as ov
from openvino.runtime import Model, Core, Output, Type
from openvino.preprocess import PrePostProcessor
from openvino.runtime.utils.decorators import custom_preprocess_function

# create a model with TopK without the pre-processing
param = ov.parameter([10], name="data", dtype=np.int32)
k = ov.constant(np.array(10, dtype=np.int32))
topk = ov.topk(param, k, 0, 'min', 'index', "i32")
model = Model([topk.output(0), topk.output(1)], [param], "model")

@custom_preprocess_function
def custom_transpose_reshape(out_node: Output):
    transpose_order = ov.constant(np.array([1, 0]), dtype=np.int32)
    transpose = ov.transpose(out_node, transpose_order)
    new_shape = ov.constant(np.array([10]), dtype=np.int32)
    reshape = ov.reshape(transpose, new_shape, False)
    return reshape

ppp = PrePostProcessor(model)
inp = ppp.input()
inp.tensor().set_shape([2, 5])
inp.preprocess().custom(custom_transpose_reshape)
model = ppp.build()

# infer it on CPU
data = np.array([[1, 3, 1, 2, 4], [4, 0, 1, 3, 2]], dtype=np.int32)
core = Core()
compiled_model = core.compile_model(model, "CPU")
output = compiled_model.infer_new_request({0: data})

print("original data = ", data)
print("result = ", output)
```

**Comment by rkazants** [comment]
Hi @Raise-me-up,

Did we answer on your question?

Best regards,
Roman

**Comment by Raise-me-up** [comment]
Yes, thank you for your reply! I have close the issue now.
