### ISSUE TITLE
[Bug][Docs] No opset9 link in API Reference in docs.openvino.ai

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#14369]
Please see there is no link to opset9 in API Reference in docs.openvino.ai. The latest one is for opset8.
See the link: https://docs.openvino.ai/latest/api/api_reference.html

@ilyachur, @kblaszczak-intel

**Comment by akuporos** [comment]
Hello Roman,

I've prepared a PR https://github.com/openvinotoolkit/openvino/pull/14406 in which I added opset9 and opset10 in indexing.

Best regards,
Anastasia
