### ISSUE TITLE
Performance comparison data

### ISSUE THREAD

**Issue by YijinLiu** [openvinotoolkit/openvino#144]
This project is fantastic! 
Currently I am using tensorflow (w/MKLDNN), which is much faster than tensorflow w/o MKLDNN on intel CPUs. From reading the document, the inference engine also uses MKL. I wonder how much (or any) improvement I should expect to get by adopting DLDT?
It would be nice if you would provide a performance comparison page for those pretrained models,  which will help users decide whether they should move to DLDT.

**Comment by shubha-ramani** [comment]
Dear @YijinLiu 
I definitely agree with you. We should have such a performance comparison page but we don't for OpenVino. This is an ongoing discussion. But we do have tools which make it easy to compare and contrast models built in different ways. It's called [benchmark_app](https://docs.openvinotoolkit.org/latest/_inference_engine_samples_benchmark_app_README.html)

Hope it helps and thanks for using OpenVino !

Shubha

**Comment by YijinLiu** [comment]
@shubha-ramani Thanks.
I experimented it a bit on [ssdlite_mobilenet_v2_coco] (http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz)
If the input size is 300x300, it's about 3 times faster on i3-8300 (which is amazing). However, if the input is 1600x1600, it's about 5 times slower than tensorflow. Tensorflow speed barely changes when the input size is different. 
My code is here: https://github.com/YijinLiu/tf-cpu/blob/master/benchmark/obj_detect_dldt.cc#L403
Did I do sth. wrong?

**Comment by jgespino** [comment]
OpenVINO Performance Benchmarks can be found here: https://docs.openvino.ai/latest/openvino_docs_performance_benchmarks.html

Closing issue as it's really old, please feel free to start a new one if additional assistance is needed.
