### ISSUE TITLE
ReduceSum error on some reduction axes

### ISSUE THREAD

**Issue by bani-intelaipg** [openvinotoolkit/openvino#1441]
In 2020.4 branch (commit# a9c6e726), while invoking ReduceSum with tensor-shape=[2,4,3], axis=1, keep_dims=0, I see a mismatch between result from InferenceEngine (IE) compared to TensorFlow.
Try with input tensor = {1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6} & make it of shape (2,4,3).
TF results (correct): [10, 14, 18]
CNN/IE result (incorrect): [8, 16, 16]
The IE is invoked with ngraph-function: unit_test_Sum.json

[opv_reducesum_files.tar.gz](https://github.com/openvinotoolkit/openvino/files/4962097/opv_reducesum_files.tar.gz)

**Comment by bani-intelaipg** [comment]
I tried with few more axes combinations. It appears the issue happens only for the last-minus-1 axis. For example, in a {2,1,2,3} rank-4 shape, issue happens only for axis 2 (0 based index)

**Comment by bani-intelaipg** [comment]
Not sure about the failure pattern.. here are more cases...
`Status * FAIL -> tensor-shape=[2,3], axis=0, keep_dims=1
Status * FAIL -> tensor-shape=[2,3], axis=0, keep_dims=0
Status   PASS -> tensor-shape=[2,3], axis=1, keep_dims=1
Status   PASS -> tensor-shape=[2,3], axis=1, keep_dims=0
Status   PASS -> tensor-shape=[2,2,3], axis=0, keep_dims=1
Status   PASS -> tensor-shape=[2,2,3], axis=0, keep_dims=0
Status * FAIL -> tensor-shape=[2,2,3], axis=1, keep_dims=1
Status * FAIL -> tensor-shape=[2,2,3], axis=1, keep_dims=0
Status   PASS -> tensor-shape=[2,2,3], axis=2, keep_dims=1
Status   PASS -> tensor-shape=[2,2,3], axis=2, keep_dims=0
Status   PASS -> tensor-shape=[6,2], axis=0, keep_dims=1
Status   PASS -> tensor-shape=[6,2], axis=0, keep_dims=0
Status * FAIL -> tensor-shape=[6,2], axis=1, keep_dims=1
Status * FAIL -> tensor-shape=[6,2], axis=1, keep_dims=0
Status   PASS -> tensor-shape=[2,4,3], axis=0, keep_dims=1
Status   PASS -> tensor-shape=[2,4,3], axis=0, keep_dims=0
Status * FAIL -> tensor-shape=[2,4,3], axis=1, keep_dims=1
Status * FAIL -> tensor-shape=[2,4,3], axis=1, keep_dims=0
Status   PASS -> tensor-shape=[2,4,3], axis=2, keep_dims=1
Status   PASS -> tensor-shape=[2,4,3], axis=2, keep_dims=0
Status   PASS -> tensor-shape=[4,3,2,1], axis=0, keep_dims=1
Status   PASS -> tensor-shape=[4,3,2,1], axis=0, keep_dims=0
Status   PASS -> tensor-shape=[4,3,2,1], axis=1, keep_dims=1
Status   PASS -> tensor-shape=[4,3,2,1], axis=1, keep_dims=0
Status * FAIL -> tensor-shape=[4,3,2,1], axis=2, keep_dims=1
Status * FAIL -> tensor-shape=[4,3,2,1], axis=2, keep_dims=0
Status   PASS -> tensor-shape=[4,3,2,1], axis=3, keep_dims=1
Status   PASS -> tensor-shape=[4,3,2,1], axis=3, keep_dims=0
Status   PASS -> tensor-shape=[1,2,3,4], axis=0, keep_dims=1
Status   PASS -> tensor-shape=[1,2,3,4], axis=0, keep_dims=0
Status   PASS -> tensor-shape=[1,2,3,4], axis=1, keep_dims=1
Status   PASS -> tensor-shape=[1,2,3,4], axis=1, keep_dims=0
Status   PASS -> tensor-shape=[1,2,3,4], axis=2, keep_dims=1
Status   PASS -> tensor-shape=[1,2,3,4], axis=2, keep_dims=0
Status * FAIL -> tensor-shape=[1,2,3,4], axis=3, keep_dims=1
Status * FAIL -> tensor-shape=[1,2,3,4], axis=3, keep_dims=0
Status   PASS -> tensor-shape=[3,1,2,4,1], axis=0, keep_dims=1
Status   PASS -> tensor-shape=[3,1,2,4,1], axis=0, keep_dims=0
Status   PASS -> tensor-shape=[3,1,2,4,1], axis=1, keep_dims=1
Status   PASS -> tensor-shape=[3,1,2,4,1], axis=1, keep_dims=0
Status   PASS -> tensor-shape=[3,1,2,4,1], axis=2, keep_dims=1
Status   PASS -> tensor-shape=[3,1,2,4,1], axis=2, keep_dims=0
Status * FAIL -> tensor-shape=[3,1,2,4,1], axis=3, keep_dims=1
Status * FAIL -> tensor-shape=[3,1,2,4,1], axis=3, keep_dims=0
Status   PASS -> tensor-shape=[3,1,2,4,1], axis=4, keep_dims=1
Status   PASS -> tensor-shape=[3,1,2,4,1], axis=4, keep_dims=0
`

**Comment by avitial** [comment]
Hi @bani-intelaipg when you say "_The IE is invoked with ngraph-function: unit_test_Sum.json_", do you mean you are using the [IENetwork](https://docs.openvinotoolkit.org/latest/ie_python_api/classie__api_1_1IENetwork.html#detailed_description) constructor? If so please note such constructor is deprecated in recent releases, try to use [IECore.read_network()](https://docs.openvinotoolkit.org/latest/ie_python_api/classie__api_1_1IECore.html#a0d69c298618fab3a08b855442dca430f) method instead. Also which version of OpenVINO are you using? I see you attached the IR files and a .json, could you provide a code snippet enough to reproduce the issue you are facing? Or if it can be reproduced with one of our sample/demo, please let me know which one.


Best Regards,
Luis

**Comment by bani-intelaipg** [comment]
I used C++ nGraph based interface. Here is the pseudo-code / steps:
https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1CNNNetwork.html#ad436e9351bb26cf664bd7941658ee6b7
```
  shared_ptr<ngraph::Function> func;
  // then set func object from the json content (not shown here)
  m_network = InferenceEngine::CNNNetwork(func);
  if(debug) {
    auto& name = m_network.getName();
    m_network.serialize(name + ".xml", name + ".bin");
  }
  InferenceEngine::Core ie;
  InferenceEngine::ExecutableNetwork exe_network =
      ie.LoadNetwork(m_network, m_device);
  m_infer_req = exe_network.CreateInferRequest();
```

**Comment by ilyachur** [comment]
Hi @bani-intelaipg ,

Can you check that you generate right `ReduceMax` operations which are compatible with OpenVINO spec?
The last spec version is [here](https://github.com/openvinotoolkit/openvino/blob/f90f242626f38af773059e0d90c47a74ce416948/docs/ops/reduction/ReduceMax_1.md).

**Comment by bani-intelaipg** [comment]
Yes, I checked and it seems to be complying. Also, some examples do pass and IE infer() does give back correct results in those cases. Only some examples fail. Please see my test report in previous comment. Example:
Status * FAIL -> tensor-shape=[2,3], axis=0, keep_dims=0
Status PASS -> tensor-shape=[2,3], axis=1, keep_dims=0

**Comment by avitial** [comment]
Ref. 35955

**Comment by avitial** [comment]
This has been addressed, closing issue. 
https://github.com/openvinotoolkit/openvino/pull/3263
