### ISSUE TITLE
Error: when convert .pb to .xml and .bin 

### ISSUE THREAD

**Issue by boni-hu** [openvinotoolkit/openvino#1442]
hello everyone,

When I run
python3 mo_tf.py  --input_model /mnt/a409/users/tongpinmo/projects/R2CNN-Plus-Plus_Tensorflow/output/trained_weights/R2CNN_20200721_car_detection/5401_1.pb --output_dir /mnt/a409/users/tongpinmo/projects/R2CNN-Plus-Plus_Tensorflow/output/trained_weights/R2CNN_20200721_car_detection/ --log_level DEBUG

I ouuured an error as follows:
mo.utils.error.Error: Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.output_cut.OutputCut'>): Graph contains 0 node after executing <class 'extensions.front.output_cut.OutputCut'>. It considered as error because resulting IR will be empty which is not usual

At the meantime, I used python3.5,  openvino 2020.04.

Do you know how to fix it?
Thank you all very much!

Boni

**Comment by ilyachur** [comment]
@lazarevevgeny can you take a look?

**Comment by lazarevevgeny** [comment]
@boni-hu, looks like your model does not contain regular input nodes of type "Placeholder", so MO does not find any input in the graph and throw an error. You may need to specify the input node using --input command line parameter. Refer to [this](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Cutting_Model.html) documentation on how to use it.

**Comment by boni-hu** [comment]
Thank you for your help, and I changed the --input and --output  as your reference documentation, a bug occurred as follows 
' [ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.user_data_repack.UserDataRepack'>): No node with name Shape_4. '

So, Can I use openvino for the model trained by my own network? If can, what should be paid attention to when converting model?

Best regards,
Boni

**Comment by lazarevevgeny** [comment]
@boni-hu, Looks like you specified incorrect input/output node name "Shape_4". Could you share the model?

**Comment by boni-hu** [comment]
I used this network [network]( https://github.com/DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow), and the garph look like[ this](/home/huboni/graph.png)
Do you need any else?

**Comment by lazarevevgeny** [comment]
I would recommend to modify this [file](https://github.com/DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow/blob/master/tools/inference.py) and save the frozen model from the `inference` function after loading the checkpoint. So you will get a proper inference graph.

**Comment by jgespino** [comment]
@boni-hu Please let us know if you need additional assistance.
