### ISSUE TITLE
IEPlugin

### ISSUE THREAD

**Issue by thibault390** [openvinotoolkit/openvino#1455]
Hi,

I built inference engine from this link:
https://github.com/openvinotoolkit/openvino

Then I built python ie_api:
I have the ie_api.so folder and I imported environment to my python path. But the ie_api.so doesn't contain the IEPlugin, why?

The IECore and IENetwork are working but not IEPlugin.

Is that normal or did I make a mistake during the build? I used the following command:

cmake -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=`which python3.7` --DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.7m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 --CMAKE_CURRENT_LIST_DIR=/home/openvino/build/:/home/openvino/inference-engine/ie_bridges/python/ ..

It seems that the IEplugin doesn't exist anymore, is it true for this version?

**Comment by jgespino** [comment]
Hi @thibault390 

The IEPlugin is going to be removed in the next major release 2021.1, you should use Core API instead. See [release notes](https://software.intel.com/content/www/us/en/develop/articles/openvino-relnotes.html).

> The following Inference Engine public API will be removed in the next release (v.2021.1):
>       IEPlugin from Inference Engine Python API. Use Core API instead.

If you want to built OpenVINO from source and include IEPlugin, please checkout the [2020.4 ](https://github.com/openvinotoolkit/openvino/tree/2020.4)tag

`git clone https://github.com/openvinotoolkit/openvino.git`
`git checkout 2020.4`

Regards,
Jesus

**Comment by thibault390** [comment]
Thanks for the reply,

This given tag doesn't contain the IEPlugin. The last version including the plugin is 2019_R1.1 tag, but I don't if it could work with my ubuntu bionic.

Regards,
Thibault

**Comment by jgespino** [comment]
Hi @thibault390 

Could you confirm you are working on the correct git branch and you are setting the python paths? I built 2020.4 branch and have no issues importing IEPlugin. Testing on Ubuntu 18.04.

```
$ git rev-parse HEAD
023e7c2c3f8a8ac83564db09799d2049115d9cf6
```

```
$ cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON  -DPYTHON_EXECUTABLE=`which python3.6` -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 ..
```
```
$ export PYTHONPATH=$PYTHONPATH:<openvino_build_dir>/bin/intel64/Release/lib/python_api/python3.6
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<openvino_build_dir>/bin/intel64/Release/lib/python_api/python3.6

$ python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openvino.inference_engine import IENetwork
>>> from openvino.inference_engine import IEPlugin
>>> exit()
```

Regards,
Jesus

**Comment by thibault390** [comment]
I saw it was my fault sorry I was on the git master. I'm going to test with the good tag. Thanks

**Comment by jgespino** [comment]
@thibault390 Ok, please let me know the outcome of your test.

**Comment by jgespino** [comment]
@thibault390 I'm closing this issue, feel free to re-open or start a new issue.
