### ISSUE TITLE
Why must setLayout after autoresize?

### ISSUE THREAD

**Issue by Ludwig-Zh** [openvinotoolkit/openvino#1466]
Hi,

  I'm a beginner in openVINO. When I reading  net_wrappers.hpp in official demo: "security_barrier_camera_demo",
  get confused on the usage of  "setLayout()", like these code:
"
 if (FLAGS_auto_resize) {
        LprInputInfoFirst->getPreProcess().setResizeAlgorithm(InferenceEngine::ResizeAlgorithm::RESIZE_BILINEAR);
            LprInputInfoFirst->setLayout(InferenceEngine::Layout::NHWC);
        } else {
            LprInputInfoFirst->setLayout(InferenceEngine::Layout::NCHW);
        }
"

  So why use "setLayout(InferenceEngine::Layout::NHWC)" instead of "setLayout(InferenceEngine::Layout::NCHW)" after auto-resize configuration?

  what's the purpose of setLayout()?Is the layout must same to InferenceEngine::InputInfo and InferenceEngine::Blob? I read the API reference but still confused.

  Thx a lot.

**Comment by Ludwig-Zh** [comment]
Anybody can give some advice on the usage of "setLayout()" in class "InferenceEngine::InputInfo" and "InferenceEngine::Blob"? What is the relationship between the layout of ::InputInfo and the trained-model weight and input Imageblob? I'm very confused on these.

Do need some help,thanks.

**Comment by jgespino** [comment]
Hi @Ludwig-Zh 

This is a good question. OpenCV by default provides NHWC layout and OpenVINO inference engine by default is set to NCHW. The [setLayout ](https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1InputInfo.html#ae201671bc62fced623fe4b800ff5bcb2)function can be used to change the layout to the expected input data.

Hope this answers your question. 

Regards,
Jesus

**Comment by jgespino** [comment]
Closing issue, please feel free to re-open or start a new issue if further assistance is needed.
