### ISSUE TITLE
[Bug] Running Openvino model using MYRIAD plugin in Android

### ISSUE THREAD

**Issue by abdelmalek0** [openvinotoolkit/openvino#14676]
- OpenVINO = 2020.4.1

I buillt openvino successfully for arm64-8va devices , using ARM CPU plugin and MYRIAD plugin.
When I try to load the openvino model with ARM CPU, it works fine but when I try:
`ExecutableNetwork executableNetwork = core.LoadNetwork(net, "MYRIAD");`

I get an error saying:
`InferenceEngineException: 
    	LoadNetwork: [ GENERAL_ERROR ] `
`
    /mnt/c/openvino-sdk/openvino/inference-engine/src/vpu/graph_transformer/src/frontend/remove_const_layers.cpp:24 FrontEnd::removeConstLayers expects CNNNetworkImpl`

**Comment by abdelmalek0** [comment]
I found a solution but I don't think that's the best practice because it involves deleting a function call in the cpp files.

Before building Openvino for Android, I looked for the file `frontend.cpp` in the path: 
`openvino_sdk\openvino\inference-engine\src\vpu\graph_transformer\src\frontend`
In this file the function that raised the error was the call to: `removeConstLayers(network);`
I commented that line then I rebuilt Openvino and it worked without this error.

**Comment by Maxim-Doronin** [comment]
Hello! In case you build OpenVINO from sources, could you please check another newer version? Let's say 2022.3

**Comment by avitial** [comment]
Closing this as it seems there is a solution to your problem. Feel free to reopen, if the issue persists provide additional information to the issue or simply ask any questions related to this topic.
