### ISSUE TITLE
Wrong build path for demo_squeezenet_download_convert_run.bat and demo_security_barrier_camera.bat

### ISSUE THREAD

**Issue by Tai-Min** [openvinotoolkit/openvino#1473]
I have installed newest release of OpenVINO from https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit.html and followed this page to setup it correctly: https://docs.openvinotoolkit.org/2020.2/_docs_install_guides_installing_openvino_windows.html. Python, CMake and VS19 with build tools are installed and definied in PATH variable.
Both scripts create empty direcories in **"Documents\Intel\OpenVINO"** and executables are build in **"%INTEL_OPENVINO_DIR%\inference_engine\samples\cpp\intel64\Release"** for **demo_squeezenet_download_convert_run.bat** and in **"%INTEL_OPENVINO_DIR%\inference_engine\demos\intel64\Release"** for **demo_security_barrier_camera.bat** instead. This causes both scripts to fail at run stage as executables can't be found. I have fixed it by replacing line 231 in  **demo_squeezenet_download_convert_run.bat** from **cd "%SOLUTION_DIR64%\intel64\Release"** to **cd "%INTEL_OPENVINO_DIR%\inference_engine\samples\cpp\intel64\Release"** and line 200 in **demo_security_barrier_camera.bat** from **cd "%SOLUTION_DIR64%\intel64\Release"** to **"cd "%INTEL_OPENVINO_DIR%\inference_engine\demos\intel64\Release"**

Not sure if this is caused by my setup of Visual Studio but tought that it's worth sharing.

**Comment by avitial** [comment]
Hi @Tai-Min, thanks for reaching out. If you have v2020.4 installed which sounds like you do (please confirm), the demo scripts `demo_squeezenet_download_convert_run.bat` and `demo_security_barrier_camera.bat` when executed the first time they create and store binary files in `C:\Users\user\Documents\Intel\OpenVINO\inference_engine_samples_build\intel64\Release` and `C:\Users\user\Documents\Intel\OpenVINO\inference_engine_demos_build\intel64\Release` respectively. 

This is how it has been for previous OpenVINO releases as well. So if you had an older version of the OpenVINO software installed, I'd recommend removing or renaming such sample/demo folders as there is some logic in scripts that checks for the existence of these files/folders: 
- `C:\Users\user\Documents\Intel\OpenVINO\inference_engine_samples_build`
- `C:\Users\user\Documents\Intel\OpenVINO\inference_engine_demos_build`
- `C:\Users\user\Documents\Intel\OpenVINO\openvino_models`



Also note the guide you listed https://docs.openvinotoolkit.org/2020.2/_docs_install_guides_installing_openvino_windows.html applies to v2020.2, make sure the guide version matches the version of OpenVINO you are installing.

Best Regards,
Luis

**Comment by Tai-Min** [comment]
Hi, yes, I've installed v2020.4

Well, firstly I've tried to run the demos on v2020.2 (clean install) without success, so I've uninstalled it using installer's remove function. Then I've installed v2020.4 and tried again from scratch (using docs for v2020.2, my bad, but looks like both docs for v2020.4 and v2020.2 are identical) again without success.

**Comment by avitial** [comment]
@Tai-Min thanks for confirming the OpenVINO version. Can you share the actual error message received when executing verification scripts? I'd like to reproduce this issue so any details that could help me replicate are encouraged (OS, Visual Studio 19 Community/Pro/Enterprise?, Python, cmake, etc.).

Regards,
Luis

**Comment by Tai-Min** [comment]
Windows 10 Pro, VS19 Community, python 3.7.6, CMake 3.18.0.

Error for demo_squeezenet_download_convert_run.bat:
        1 file(s) copied.
System nie może odnaleźć określonej ścieżki. _(system cannot find the path specified in polish)_
classification_sample_async.exe -i "D:\Programy\Programowanie\ML\openvino\openvino\deployment_tools\demo\car.png" -m "C:\Users\Mateusz\Documents\Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1\FP16\squeezenet1.1.xml" -d CPU
'classification_sample_async.exe' is not recognized as an internal or external command,
operable program or batch file.
Error

Error for demo_security_barrier_camera.bat:
System nie może odnaleźć określonej ścieżki. _(system cannot find the path specified in polish)_
"C:\Users\Mateusz\Documents\Intel\OpenVINO\inference_engine_demos_build\intel64\Release\security_barrier_camera_demo.exe" -i "D:\Programy\Programowanie\ML\openvino\openvino\deployment_tools\demo\car_1.bmp"  -m "C:\Users\Mateusz\Documents\Intel\OpenVINO\openvino_models\ir\intel\vehicle-license-plate-detection-barrier-0106\FP16\vehicle-license-plate-detection-barrier-0106.xml" -m_lpr "C:\Users\Mateusz\Documents\Intel\OpenVINO\openvino_models\ir\intel\license-plate-recognition-barrier-0001\FP16\license-plate-recognition-barrier-0001.xml" -m_va "C:\Users\Mateusz\Documents\Intel\OpenVINO\openvino_models\ir\intel\vehicle-attributes-recognition-barrier-0039\FP16\vehicle-attributes-recognition-barrier-0039.xml" -d CPU -d_va CPU -d_lpr CPU
'security_barrier_camera_demo.exe' is not recognized as an internal or external command,
operable program or batch file.
Error

**Comment by avitial** [comment]
@Tai-Min if you check the contents of dir `C:\Users\Mateusz\Documents\Intel\OpenVINO\inference_engine_demos_build\intel64\Release\` do you see the `security_barrier_camera_demo.exe` binary? I see different locations for the binary and models/bmp image, perhaps this is what is causing the issue to begin with. Is your OpenVINO installation path in `C:\` or in `D:\`?

**Comment by Tai-Min** [comment]
My OpenVINO path is in D:\ and inference_engine_demos_build folder is empty. All stuff for this sample is recreated in "%INTEL_OPENVINO_DIR%\inference_engine\demos\intel64\Release"
