### ISSUE TITLE
Failed to  inference  a tensorflow model with OpenVINO 2019R1

### ISSUE THREAD

**Issue by nuaawzl** [openvinotoolkit/openvino#148]
Hi,
In OpenVINO 2019 R1,  I use mo_tf.py  to convert some model from tensorflow successfully. when I use Inference Engine  run the IR, find this error:
`terminate called after throwing an instance of "InferenceEngine::details::InferenceEngineException"
  what():  Failed to find reference implementation for "anchor_generator/Pad_1" Layer with "Pad" Type on constant propagation
/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/include/details/ie_exception_conversion.hpp:71`

what's wrong? thanks

**Comment by shubha-ramani** [comment]
Dear @nuaawzl 
Impossible to say without knowing more about your model and the inference code you are using. Which model did you convert successfully ? What type of model is it ? (i.e. classification, object detection, yolo, segmentation, etc...) Can you try running one of the many OpenVino samples first on that model ? 

Thanks,

Shubha

**Comment by nuaawzl** [comment]
Dear @shubha-ramani
First, thank you for your reply. Then,  the model I convert is FaceBoxes without nms, it should belong to object detection. For more Info:
1. convert cmd 
 `  python mo_tf.py --input_model=model_no_postv1.pb --input_shape=[1,1024,1024,3] --log_level=DEBUG`
2. the debug log 
[debug.txt](https://github.com/opencv/dldt/files/3185047/debug.txt)
3. the tensorboard log
[events.out.tfevents.1557969396.txt](https://github.com/opencv/dldt/files/3185073/events.out.tfevents.1557969396.txt)

**Comment by lazarevevgeny** [comment]
The issue should had been fixed already. Could you verify with the latest OpenVINO?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
