### ISSUE TITLE
[Bug] The attributes of a custom op are an array. How do I set the values of the attributes in the onnx model

### ISSUE THREAD

**Issue by zhaohb** [openvinotoolkit/openvino#14810]
##### System information (version)

- OpenVINO => 2022.1
- Problem classification: Model Conversion

##### Detailed description

Now I want to write a custom op, but one of the attributes of the op is a list, now I can only convert the list to a string type, so that it can be transferred to ov normally, but this custom op also needs to use string to receive that attributes, and then converted to list, this way is not friendly, is there any other way?

**Comment by rkazants** [comment]
Hi @zhaohb, for example, you can see conversion for ONNX `Squeeze` operation that has `axes` list attribute and how it is retrieved here: https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/squeeze.cpp#L19

Also, please take a look how to register your `ConversionExtension` here: https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Frontend_Extensions.html

**Comment by zhaohb** [comment]
@rkazants Thanks for your reply, but I can't see from here [https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Frontend_Extensions.html](url) which interface has Node object, what can I do?

**Comment by zhaohb** [comment]
@rkazants maybe I should use [ov::frontend::ConversionExtension](https://docs.openvino.ai/latest/classov_1_1frontend_1_1ConversionExtension.html#doxid-classov-1-1frontend-1-1-conversion-extension)?

**Comment by zhaohb** [comment]
@rkazants do we have a example of ConversionExtension?

**Comment by rkazants** [comment]
> , but I can't see fro

Hi @zhaohb, please scroll down to `Mapping to Multiple Operations with ConversionExtension` in https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Frontend_Extensions.html. There is an example of the custom extension for `ThresholdedReLU` operation.

Thanks,
Roman

**Comment by zhaohb** [comment]
@rkazants Yes, I'm looking at the documentation, and my understanding now is that it turns the list attribute into the input to the op, right？

**Comment by rkazants** [comment]
@zhaohb, yes, you are correct. It is specifics of given implementation but it considers the single value attribute. Your case can be different and you can do something different with attribute value. Since you have a deal with value list, you should have something like this:

```
auto attr_value = node.get_attribute<std::vector<float>>("attr")
```

**Comment by zhaohb** [comment]
@rkazants thank you very much, I had soved my problem
I changed the list attrs directly on the onnx graph to be the input to the operator.
