### ISSUE TITLE
How to save the compiled model through python api？

### ISSUE THREAD

**Issue by izZCrown** [openvinotoolkit/openvino#14884]
I'm a newbie using openvino.
Through python api I got openvino IR and I noticed that "ie.compile_model()" can be used to output IR as "openvino.runtime.CompiledModel". Is there any way to save the compiled result?

**Comment by ilya-lavrenov** [comment]
Hi @izZCrown,
Please, use [this document](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Model_caching_overview.html) how understand how to cache compiled model results.

**Comment by izZCrown** [comment]
Hi@ilya-lavrenov
Thank you for your reply. This is exactly what I need! It seems that I need to look at the document in more detail. Thanks again.

**Comment by izZCrown** [comment]
Hi @ilya-lavrenov 
Thank you for your reply. This is exactly what I need! It seems that I need to look at the document in more detail. Thanks again.
