### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by erinpark33** [openvinotoolkit/openvino#149]
Hello, 

I tried to compile it (2019 branch) and got the below error on Ubuntu 18.10.

Did I do something wrong?

[ 64%] Building CXX object thirdparty/clDNN/src/CMakeFiles/clDNN_shlib.dir/graph_optimizer/add_required_reorders.cpp.o
In file included from /home/pnp/repo/dldt/inference-engine/thirdparty/clDNN/src/include/layout_optimizer.h:31,
                 from /home/pnp/repo/dldt/inference-engine/thirdparty/clDNN/src/include/pass_manager.h:20,
                 from /home/pnp/repo/dldt/inference-engine/thirdparty/clDNN/src/graph_optimizer/add_required_reorders.cpp:21:
/home/pnp/repo/dldt/inference-engine/thirdparty/clDNN/src/include/generic_layer.hpp: In constructor ‘cldnn::generic_layer::generic_layer(const dto*)’:
/home/pnp/repo/dldt/inference-engine/thirdparty/clDNN/src/include/generic_layer.hpp:64:111: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
         , generic_params(*static_cast<const kernel_selector::generic_kernel_params* const>(dto->generic_params))
                                                                                                               ^
cc1plus: all warnings being treated as errors

**Comment by alalek** [comment]
> cc1plus: all warnings being treated as errors

Workaround: remove "-Werror" from CMake files (including submodules).
No idea why it is enabled unconditionally by default.

**Comment by pwuertz** [comment]
Is this being addressed yet? Should we propose a PR with the unconditional Werrors being removed?

**Comment by pwuertz** [comment]
Apparently this is fixed in 2020.2 (95a57795dcb0ed82324af87918339225148202ca)

**Comment by pwuertz** [comment]
Sub-project `inference-engine/thirdparty/ade` also fails due to Werror. Bumping `inference-engine/thirdparty/ade` to current master fixes it.

Another fail comes from `_deps/ext_onnx-build`, Werror is enabled there although ONNX_WERROR is false in the cmake dldt configuration.

**Comment by psyhtest** [comment]
> Another fail comes from `_deps/ext_onnx-build`, Werror is enabled there although ONNX_WERROR is false in the cmake dldt configuration.

https://github.com/openvinotoolkit/openvino/issues/462
