### ISSUE TITLE
openvino inference with mode latency

### ISSUE THREAD

**Issue by shuyuan-wang** [openvinotoolkit/openvino#14907]
I am trying to inference with openvino xml both with runtime and benchmark_app. I can see that if I set the  mode to latency, the latency I get varies a lot, the min and max latency are 4ms and 70ms. Why is this happening? I don't have any other programs running on my docker which has 8 cores.

**Comment by mlukasze** [comment]
Hi @shuyuan-wang 
thanks for noticing us up, let us check what could happen - someone will back to you with answers or additional questions shortly :)

**Comment by brmarkus** [comment]
@shuyuan-wang can you provide more details about your environment (HW and SW), versions of used components (which OpenVINO, which OS, which Python), please?
Do you use C/C++ or Python?
Can you provide more details about your used model, type of model, topology? Which kind of input and output is involved, static or dynamic shapes? mCan you share command-lines you have used?
Which device do you process the inference on, on CPU?

**Comment by shuyuan-wang** [comment]
I'm using openvino 202202, python 3.8, ubuntu18.04 on a docker. I'm using pure  CPU to test. I'm testing on the rpn, the neck part of pointpillar. there is only one input which is the output of the scatter. I'm using statistic shape.

using benchmark as an example:
benchmark_app -m rpn.xml -i 000.bin -d CPU -api sync.

The CPU I'm using is Intel(R) Xeon(R) Gold 6346 CPU @ 3.10GH

**Comment by wenjiew** [comment]
@riverlijunjie Please help take  a look.
@shuyuan-wang Can you share the model file? Thanks.

**Comment by riverlijunjie** [comment]
@shuyuan-wang totally latency mode will achieve more stable latency value than tput mode 
Could you run below command to check the max and min latency?
benchmark_app -m rpn.xml -d CPU -api sync -hint none -nthreads 1

I checked the same command with your but different model, the max/min latency is very close
[ INFO ] Count:               3605 iterations
[ INFO ] Duration:            15001.09 ms
[ INFO ] Latency:
[ INFO ]    Median:           4.08 ms
[ INFO ]    Average:          4.16 ms
[ INFO ]    Min:              4.03 ms
[ INFO ]    Max:              6.42 ms
[ INFO ] Throughput:          240.32 FPS

So could you share your model to reproduce in my local machine?

**Comment by shuyuan-wang** [comment]
If I add -nthreads 1 the min max are pretty stable, but the mean latency is much longer than what I got without the flag. I would  prefer not using it.
When using -nthreads 1:
min: 25.03ms
max: 35.66ms

The attached files are the xml and bin files I use. Please test it.
[rpn_int8.zip](https://github.com/openvinotoolkit/openvino/files/10380325/rpn_int8.zip)

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
