### ISSUE TITLE
Read model from "Tensor"

### ISSUE THREAD

**Issue by tim0x7b3** [openvinotoolkit/openvino#14939]
##### System information (version)

- OpenVINO => 2022.3
- Operating System / Platform => linux
- Compiler => 
- Problem classification: Read model
- Framework: 
- Model name: 

##### Detailed description
Is there any similar example as below for OpenVINO 2.0 API ?

```.cpp
SizeVector weight_sz(1);
weight_sz[0] = bin_length;
InferenceEngine::TensorDesc tensorDesc(InferenceEngine::Precision::U8, 
                                                   SizeVector(weight_sz.rbegin(), weight_sz.rend()), 
                                                   TensorDesc::getLayoutByDims(weight_sz));
TBlob<uint8_t>::Ptr weights = make_shared_blob<uint8_t>(tensorDesc);

weights->allocate();
memcpy(weights->data(), (uint8_t*)bin_data, weights->size());
m_net = m_ie.ReadNetwork(m_ir_xml, weights);
```

How to change to use new API to instead?
```.cpp
     /**
     * @brief Reads models from IR/ONNX/PDPD formats.
     * @param model String with a model in IR/ONNX/PDPD format.
     * @param weights Shared pointer to a constant tensor with weights.
     * Reading ONNX/PDPD models does not support loading weights from the @p weights tensors.
     * @note Created model object shares the weights with the @p weights object.
     * Thus, do not create @p weights on temporary data that can be freed later, since the model
     * constant data will point to an invalid memory.
     * @return A model.
     */
    std::shared_ptr<ov::Model> read_model(const std::string& model, const Tensor& weights) const;
```

**Comment by rkazants** [comment]
Hi @tim0x7b3,

You can take a look at some examples which can contain useful code like this one: https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/model_creation_sample/main.cpp#L70

In your case, it can be

```
ov::Tensor weights(ov::element::u8, {bin_length});
memcpy(weights.data(), (uint8_t*)bin_data, weights.get_byte_size());
read_model(..., weights);
```

**Comment by tim0x7b3** [comment]
> Hi @tim0x7b3,
> 
> You can take a look at OV samples which can contain useful code for you: https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/model_creation_sample/main.cpp#L70
> 
> In your case, it can be
> 
> ```
> ov::Tensor weights(ov::element::u8, {bin_length});
> memcpy(weights.data(), (uint8_t*)bin_data, weights.get_byte_size());
> read_model(..., weights);
> ```

This is very helpful. Thanks~
