### ISSUE TITLE
How to uninstall Development Tools on Ubuntu?

### ISSUE THREAD

**Issue by timousT** [openvinotoolkit/openvino#14943]
I use ubuntu 18.04
After I installed Development Tools installation step as below, How could I uninstall all of it?
ps: I didn't see any /opt/intel folder in /opt
https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html?elq_cid=2267636&erpm_id=3196635&elq_cid=2267636&erpm_id=3196635&elq_cid=2267636&erpm_id=3196635&elq_cid=2267636&erpm_id=3196635&elq_cid=2267636&erpm_id=3196635&elq_cid=2267636&erpm_id=3196635&elq_cid=2267636&erpm_id=3196635
<img width="394" alt="WeChat 圖片_20230105160341" src="https://user-images.githubusercontent.com/104662460/210731419-d1e7bead-657f-4f16-9a6c-fa3ea80cbcb9.png">

**Comment by ilya-lavrenov** [comment]
To uninstall tools, you should also use `pip` package manager. You can uninstall OpenVINO in the same way as any other pip package:
```
pip uninstall openvino
```
You can also completely removed virtual env:
```
rm -fr openvino_env
```

> ps: I didn't see any /opt/intel folder in /opt

Pip packages are installed into python env, not in `/opt`
