### ISSUE TITLE
transpose layer outputs value is nan

### ISSUE THREAD

**Issue by Lennon-cheng** [openvinotoolkit/openvino#14961]
paddle ernie model convert to  openvino。
There is transpose layer, after this transpose layer, why some positions of the output is become nan。
netron：
<img width="445" alt="image" src="https://user-images.githubusercontent.com/33142144/210811572-008dd2a3-da98-46b9-b7a1-f54f0e6350de.png">
transpose inputs：
<img width="513" alt="image" src="https://user-images.githubusercontent.com/33142144/210809582-e9465a5b-8493-4a4e-91cd-1e747d7a3672.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/33142144/210810919-63614ef9-6ce7-4968-bc9b-aa4ee59e2b18.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/33142144/210811087-ced0ffb7-bd5f-413d-8d59-878ca750a860.png">

transpose outputs：
<img width="569" alt="image" src="https://user-images.githubusercontent.com/33142144/210809851-63f6ce4d-a1d0-49f5-8869-359a07b7f8a6.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/33142144/210810618-16425bed-4d8a-4e95-8a23-ad9471c52c32.png">
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/33142144/210811256-e01dac95-22f1-464c-a800-4307e0cce6e1.png">

**Comment by xczhai** [comment]
@Lennon-cheng 
Thanks for your detailed log and info. That's really helpful to OpenVINO.
But I need to confirm something to accelerate the debug progress.

1. The model is from https://www.paddlepaddle.org.cn/lite/develop/demo_guides/intel_openvino.html, right?
2. Could you provide the reproduced script if possible?

Thanks

**Comment by Lennon-cheng** [comment]
I finetune paddlenlp "ernie-gram-zh" pretrain model used paddlepaddle framework. this is load model code
    pretrained_model = paddlenlp.transformers.ErnieGramModel.from_pretrained(
        'ernie-gram-zh')
    tokenizer = ppnlp.transformers.ErnieGramTokenizer.from_pretrained(
        'ernie-gram-zh')

then use paddle2onnx convert paddle to onnx. model.onnx in zip is onnx file.
But CumSum not support. Then I modify some node and result is model1.onnx. This code  convert.py is in zip.
Then I convert onnx to openvino used script.sh which is in zip.
Then I infer openvino used infer.py which is in zip.  
Run: python infer.py 你  好.  Can find the problem transpose node which name  p2o.Transpose.65

zip download from baidu drive
链接: https://pan.baidu.com/s/1h5osf5ad5HIu7vx17RMPfw?pwd=dv25 提取码: dv25

**Comment by yuxu42** [comment]
@Lennon-cheng as OV has already supported input of Paddle format model that OV handles the paddle to ngraph conversion internally, so that it can save additional Paddle to ONNX to IR conversion. Could you please have a try? 
https://docs.openvino.ai/nightly/openvino_docs_OV_UG_Integrate_OV_with_your_application.html#step-2-compile-the-model

**Comment by xczhai** [comment]
> 
@Lennon-cheng 
Hi,

1. I downloaded the zip file but failed to load the model.onnx in netron and openvino. It seems to be broken. Could you take a check?
2. The script is to do the inference of `ernie-gram-zh` model. The recommended step is `pretrained_model ==> paddle finetune ==> paddle save inference model ==> *.pdmodel & *.pdiparams format ==> OpenVINO`. 
3. OpenVINO can load and run the native paddle inference natively. I have checked that cumsum has been supported in OpenVINO. Could you take a try as the above comments?
https://github.com/openvinotoolkit/openvino/blob/master/docs/MO_DG/prepare_model/Supported_Frameworks_Layers.md
4. BTW, I find some lagacy api is still in your script. It is recommended to replace them with API2.0. That supports dynamic shape well.
https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html

Thanks.

**Comment by xczhai** [comment]
@Lennon-cheng 
Hi, 
- I try https://paddlelite-demo.bj.bcebos.com/NNAdapter/models/PaddleNLP/ernie_1.0.tgz and convert pdmodel to onnx using paddle2onnx. The model architecture is the same as your provided. 
- Could you please try to run pdmodel using openvino because we want to exclude the paddle2onnx effect?
- It is appreciated if you help provide pdmodel and pdiparams.
Thanks.

**Comment by Lennon-cheng** [comment]
@xczhai Thank you very much for your help！
First, I succeeded in running pdmodel using openvino！

I reorganized the whole process code.  Step is
paddle save inference model ==> *.pdmodel & *.pdiparams format ==> onnx ==> OpenVINO

The specific explanation is in the readme of the zip.

链接: https://pan.baidu.com/s/1oiW5SGqUPurg_IGZfDZt0A?pwd=65qu 提取码: 65qu

**Comment by xczhai** [comment]
@Lennon-cheng 
Thanks for your attachment. 
- I think the **legacy API** causes this bug. Please refer to the uploaded python scritpt. 
[ov_infer.zip](https://github.com/openvinotoolkit/openvino/files/10368504/ov_infer.zip)
- If you still encounter the cumsum bug, please refer to the fixed code in my temp branch https://github.com/xczhai/openvino/compare/fix_onnx_cumsum...openvinotoolkit:openvino:fix_onnx_cumsum
- We will make an internal review of the cumsum op before merged to master.
- BTW, if you want to hit the best latency or throughput performance, please refer to https://docs.openvino.ai/latest/openvino_docs_deployment_optimization_guide_dldt_optimization_guide.html#
- If it works, please tell us and close it.

Thanks.

**Comment by Lennon-cheng** [comment]
@xczhai  The problem is solved. Thank you very much for your help!!!
