### ISSUE TITLE
[Bug]compile error:openvino runtime porting to windows camera post process(DMFT)

### ISSUE THREAD

**Issue by MarkHung00** [openvinotoolkit/openvino#14964]
##### System information (version)
- OpenVINO => 2022.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2022
- Problem classification: Runtime
- Framework: TensorFlow
- Model name: classification

##### Detailed description

We add openvino runtime (for inference) in the DMFT of windows, and currently add openvino-related lib and inlclude header
#include "openvino/openvino.hpp"

After compile, an error occurs as follows

's_max' The identifier is undeclared @ interval.hpp

**Comment by MarkHung00** [comment]
Hi there,

thanks for your quick response, the compiler output as below

Severity	Code	Description	File	Line	Suppression State
Error	C2065	's_max': undeclared identifier	OpenVino\openvino\openvino\core\interval.hpp	43	


and the full log as below
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2334	unexpected token(s) preceding ':'; skipping apparent function body	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	109	
Error	C1907	unable to recover from previous error(s); stopping compilation	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\dimension.hpp	191	
Error	C2062	type 'unknown-type' unexpected	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	109	
Error	C2220	the following warning is treated as an error	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\attribute_adapter.hpp	38	
Warning	C4003	not enough arguments for function-like macro invocation 'max'	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	109	
Warning	C4100	'x': unreferenced formal parameter	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\attribute_adapter.hpp	38	
Error	C2065	's_max': undeclared identifier	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	43	
Error	C2065	's_max': undeclared identifier	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	44	
Error	C2065	's_max': undeclared identifier	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	44	
Error	C2065	's_max': undeclared identifier	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	50	
Error	C2065	's_max': undeclared identifier	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	70	
Error	C2065	's_max': undeclared identifier	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	115	
Error	C2589	'(': illegal token on right side of '::'	multipinmft	C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp	109

**Comment by ilya-lavrenov** [comment]
> Hi there,
> 
> thanks for your quick response, the compiler output as below
> 
> Severity Code Description File Line Suppression State Error C2065 's_max': undeclared identifier OpenVino\openvino\openvino\core\interval.hpp 43
> 
> and the full log as below Severity Code Description Project File Line Suppression State Error C2334 unexpected token(s) preceding ':'; skipping apparent function body multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 109 Error C1907 unable to recover from previous error(s); stopping compilation multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\dimension.hpp 191 Error C2062 type 'unknown-type' unexpected multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 109 Error C2220 the following warning is treated as an error multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\attribute_adapter.hpp 38 Warning C4003 not enough arguments for function-like macro invocation 'max' multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 109 Warning C4100 'x': unreferenced formal parameter multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\attribute_adapter.hpp 38 Error C2065 's_max': undeclared identifier multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 43 Error C2065 's_max': undeclared identifier multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 44 Error C2065 's_max': undeclared identifier multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 44 Error C2065 's_max': undeclared identifier multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 50 Error C2065 's_max': undeclared identifier multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 70 Error C2065 's_max': undeclared identifier multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 115 Error C2589 '(': illegal token on right side of '::' multipinmft C:\Project\ISP_SW\OpenVino\sampledevicemft-OpenVino\openvino\openvino\core\interval.hpp 109

You need to include:
```
#define NOMINMAX
```
Before you (or other header you use) include `Windows.h`

**Comment by hbalasu1** [comment]
Hi @MarkHung00 
Do you able to resolve the issue as suggested by @ilya-lavrenov ?

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
