### ISSUE TITLE
AUTO model priorities documentation confusion

### ISSUE THREAD

**Issue by ngaloppo** [openvinotoolkit/openvino#14963]
Is the explanation in the code snippet line referred [here](https://github.com/openvinotoolkit/openvino/blob/08b4c9cdd300b0906d3475352426fb171ec5cd6d/docs/snippets/AUTO4.cpp#L31) correct? Are the priorities `LOW`, `MEDIUM`, `LOW` truly mapped to devices `GPU`, `GPU`, `MYRIAD` (note, `CPU` is not used)? 

I can't propose a better explanation because I don't think I fully understand the priority logic.

**Comment by wangleis** [comment]
@ngaloppo Yes, the explanation is correct. Two example explained two logic policy of model priority in AUTO..

1. AUTO will not load lower priority model to device running higher priority model. Example 1 explain this policy.
2. AUTO will load higher priority model to device running lower priority model. Then device plugin like GPU plugin will handle model prioritization for two models on the same device. Example 2 explain this policy.

We will recommend developer to use model priority on AUTO as example 1 for better performance.

**Comment by ngaloppo** [comment]
@wangleis Thank you for explaining. Does that mean that the order of `compile_model()` matters? For example, what if example 2 was the following instead: 

```cpp
ov::CompiledModel compiled_model4 = core.compile_model(model, "AUTO",
    ov::hint::model_priority(ov::hint::Priority::MEDIUM));
ov::CompiledModel compiled_model3 = core.compile_model(model, "AUTO",
    ov::hint::model_priority(ov::hint::Priority::LOW));
ov::CompiledModel compiled_model5 = core.compile_model(model, "AUTO",
    ov::hint::model_priority(ov::hint::Priority::LOW));
```

**Comment by wangleis** [comment]
@ngaloppo Yes, the order of compile_model() in app matters. After you change order, model 4 use GPU, model 3 use MYRIAD and model 5 use CPU.

Model priority and cumulative throughput are two different features. They are independent.

1. Model priority load multiple models to multiple devices. One model only load to one device.
2. Cumulative throughput load one model to multiple devices.

**Comment by ngaloppo** [comment]
Thank you! I may suggest some documentation updates in a following PR. Closing this issue until then.
