### ISSUE TITLE
[Myriad] preprocess I420 and NV12 Error

### ISSUE THREAD

**Issue by twata342** [openvinotoolkit/openvino#14980]
##### System information (version)
- OpenVINO => 2022.2
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2019 C++
- Device => NCS2
##### Detailed description
I get the following error in compile_model() when I specify ColorFormat::I420 in preprocess in openvino api2.0.
It works fine on CPU and GPU.
Is there any plan to support ColorFormat::I420 in preprocess in NCS2?

##### Code
	ov::Core ie;
	std::shared_ptr<ov::Model> network;
	network = ie.read_model(model_path);

	ov::preprocess::PrePostProcessor ppp(network);
	ppp.input().tensor().set_element_type(ov::element::u8);
	ppp.input().tensor().set_color_format(ov::preprocess::ColorFormat::I420_SINGLE_PLANE);
	ppp.input().preprocess().convert_color(ov::preprocess::ColorFormat::BGR);
	network = ppp.build();

	ov::CompiledModel compiled_model = ie.compile_model(network, device_name);

##### Error
C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\plugins\intel_myriad\common\src\ngraph\transformations\dynamic_to_static_shape.cpp:200 DynamicToStaticShape transformation encountered dynamic node I420toBGR_897 of type I420toBGR ver. 0, but only [Abs ver. 0, Ceiling ver. 0, Clamp ver. 0, Concat ver. 0, Convert ver. 0, Exp ver. 0, ExpGatherElements ver. 0, Floor ver. 0, Log ver. 0, MatMul ver. 0, ...] types are supported for dynamic nodes

**Comment by rkazants** [comment]
Hi @twata342,

Can you please try to set a shape for the input tensor? Example:

```
ppp.input().tensor().set_shape({1, 480, 640, 3});
```

Best regards,
Roman

**Comment by twata342** [comment]
Hi  rkazants

No change.

Best regards,

**Comment by ilya-lavrenov** [comment]
Hi @twata342 

MYRIAD plugin does not support preprocessing operations via OpenVINO 2.0 API.

**Comment by twata342** [comment]
Hi@ilya-lavrenov 

I don't understand why the preprocessing API itself is not supported by the Myriad plugin.
In fact, I think Myriad plugin supports resize(), mean(), and scale() among preprocessing APIs.
How can I understand this?

The following URL says "selected device (CPU/GPU/VPU/etc.)".
https://docs.openvino.ai/latest/openvino_docs_OV_UG_Preprocessing_Overview.html

Is there any chance that ColorFormat::I420 will be supported in OpenVINO 2022.3.1?

Best regards,

**Comment by ilya-lavrenov** [comment]
> Is there any possibility that Myriad plugin supports ColorFormat::I420 in OpenVINO2022.3.1?

No, this HW is supported only in bug-fixing mode, while I420 requires implementation of new kernels.

> In fact, I think Myriad plugin supports resize(), mean(), and scale() among preprocessing APIs.
How can I understand this?

Yes, they are preprocessing calls, but some of them are mapped to already support operations lie scale => multiple, mean => subtract, etc. Such operations are supported by MYRIAD plugin for a long time, while I420 are relatively new operations and MYRIAD plugin lacks their support
