### ISSUE TITLE
OpenVINO 2019R1/R1.01 with mask rcnn error:Plugin MKLDNNPlugin cannot be loaded

### ISSUE THREAD

**Issue by stq054188** [openvinotoolkit/openvino#150]
##### System information (version)
OpenCV => 4.1.0
Operating System / Platform => Windows10 64 Bit
Compiler => Visual Studio 2017
OpenVINO => w_openvino_toolkit_p_2019.1.133

I think I have installed OpenVINO 2019R1 successfully, because I have run demo_security_barrier_camera.bat and get right result as follows.
![1](https://user-images.githubusercontent.com/15775782/57497086-cdba9300-7308-11e9-88e0-ae0d37453f75.JPG)
Also, I have trained a faster-rcnn model and tested with openvino and get right result. Then I test my mask-rcnn model, it showed error as follows.

[ ERROR ] Cannot find plugin to use :Tried load plugin : MKLDNNPlugin,  error: Plugin MKLDNNPlugin cannot be loaded: cannot load plugin: MKLDNNPlugin from ../../../lib/intel64: Cannot load library '../../../lib/intel64\MKLDNNPlugin.dll'

1. Model files and config files are here. https://drive.google.com/open?id=1xTI6_bqbZpi3vbeVcFxX1emBSa7QI58z
2. Test code is OpenCV_Mask_RCNN.cpp, test images are 2.png and 7.png. All files are packed as files.zip.
[files.zip](https://github.com/opencv/dldt/files/3164589/files.zip)

Dose anyone have the same problem or can you help me solve it? Thank you in advance.

**Comment by stq054188** [comment]
Has someone encountered a similar situation?

**Comment by elvin-nnov** [comment]
Failing of plugin loading does not depend on the model - loading of the model happens later into the plugin been presented in the process. You have something wrong with setting of environment of pointing the path where to look for the cpu plugin. We are using rpath in the samples that make them working even with partially environment. You need to use proper  LD_LIBRARY_PATH or rpath during linking of your app

**Comment by stq054188** [comment]
@elvin-nnov Thank you for your reply. But I still don't quite understand how to set LD_LIBRARY_PATH . Can you elaborate a little more or give an example? Thanks.

**Comment by alalek** [comment]
> Windows10 64 Bit

You need to specify `PATH` environment variable (`LD_LIBRARY_PATH` is for Linux).

Please read documentation carefully, especially in places with `setupvars`:
- https://docs.openvinotoolkit.org/2019_R1/_docs_IE_DG_inference_engine_intro.html

**Comment by elvin-nnov** [comment]
Ups, I have not noted that original message mentioned dll files. Answer from @alalek is correct

**Comment by stq054188** [comment]
@alalek I have already set the environment variable but still have no improvement.
![捕获](https://user-images.githubusercontent.com/15775782/57662473-3f088780-7622-11e9-8531-9d8dd7d9a365.JPG)

**Comment by shubha-ramani** [comment]
@stq054188

Have you been able to make progress ? What others @alalek and @elvin-nnov say above is correct.  If you are still stuck, here is a good option.  Build a debug version of IE using [these steps](https://github.com/opencv/dldt/blob/2019/inference-engine/README.md)

Step through your code. I guarantee you that you'll figure it out. That's the great thing about using DLDT - the errors will never be a mystery. You can see exactly why the plugin is refusing to load.

Hope this helps.

Thanks for using OpenVino !

Shubha

**Comment by fatalfeel** [comment]
C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\inference_engine\bin\intel64\Release
put dll to this
C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\inference_engine\bin\intel64\Release

**Comment by stq054188** [comment]
@fatalfeel What do you mean?

**Comment by bertbehappy** [comment]
The MKLDNNPlugin only support by Xeon/Core/Atom cpu.

**Comment by TheMasterRoot** [comment]
> The MKLDNNPlugin only support by Xeon/Core/Atom cpu.

i have core i7 3th and im having same insue here

**Comment by ilyachur** [comment]
Hi,

The issues is still relevant for the last OpenVINO package?
Did you use setup_vars script to set the right environment?

**Comment by TheMasterRoot** [comment]
yes the same problem.

**Comment by ilyachur** [comment]
@TheMasterRoot Can you check dependencies for MKLDNNPlugin? Maybe some dependencies were not resolved.

CC @dmitry-gorokhov

**Comment by TheMasterRoot** [comment]
how to check this plugins? or how to reinstall it?

**Comment by ilyachur** [comment]
@TheMasterRoot 
First of all try to find `MKLDNNPlugin.dll` and check that it exists.
After that please check dependencies for the plugin, you can use [Dependency Walker](http://www.dependencywalker.com/) for it. This tool shows you all dependencies for the plugin, please check that all dependencies are resolved.

 I think all should work if the Inference Engine detects the `MKLDNNPlugin.dll` and all plugin dependencies are resolved.

**Comment by TheMasterRoot** [comment]
thank you i ll look for it

**Comment by ilyachur** [comment]
@TheMasterRoot 
Please let us know about results. Thanks.

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
