### ISSUE TITLE
Formatting issue in APT install guide

### ISSUE THREAD

**Issue by ngaloppo** [openvinotoolkit/openvino#15038]
There seems to be some spacing issue, not correctly rendered.

https://github.com/openvinotoolkit/openvino/blob/fba025f1e7a9fbe1903be2859588d4a778ebd52e/docs/install_guides/installing-openvino-apt.md?plain=1#L40-L42

**Comment by rkazants** [comment]
@kblaszczak-intel, can you or your colleagues address this issue please?

Thanks,
Roman

**Comment by xu-yuan1** [comment]
Fixed in https://github.com/openvinotoolkit/openvino/pull/15023/files#diff-162a753320654ec9b584e693b4cfaf06ccb8463b1df6819b9a69cf2bedfe6cde

**Comment by ngaloppo** [comment]
LGTM. However, this has nothing to do with a script?
