### ISSUE TITLE
DL workbench accuracy checker doesn't work with unannotated data

### ISSUE THREAD

**Issue by divdaisymuffin** [openvinotoolkit/openvino#1506]

**Comment by divdaisymuffin** [comment]
Hi, I am using DL workbench of Openvino for SmartCity data, all the features in Dl workbench UI are working fine, except accuracy checker, as it suggests that accuracy checker will work only with annotated data and Smartcity data is unannotated, Please help me to solve this problem, How I can use accuracy checker with unannotated data?

**Comment by jgespino** [comment]
Hi @divdaisymuffin 

Thanks for reaching out. Unannotated Datasets can only be used in the simplified mode of the maximum performance calibration method and cannot be used for accuracy measurements. Take a look at the following link:
https://docs.openvinotoolkit.org/latest/workbench_docs_Workbench_DG_Dataset_Types.html#unannotated

Regards,
Jesus

**Comment by jgespino** [comment]
Closing issue, please feel free to re-open or start a new issue if further assistance is needed.
