### ISSUE TITLE
parsing object detection results - There are five layers of output sent to parsing，

### ISSUE THREAD

**Issue by RenLuXi** [openvinotoolkit/openvino#1509]
I converted yolov4-tiny to pb and pb to IR, and when I used the python API to infer the IR model, the parsing  result reported an error.
I print output layer_name use code as follows:
```if self.exec_net.requests[cur_request_id].wait(-1) == 0:
    output = self.exec_net.requests[cur_request_id].outputs
    for layer_name, out_blob in output.items():
        print(layer_name)
```
print as follows:
```
detector/yolo-v4-tiny/Conv_17/BiasAdd/YoloRegion
detector/yolo-v4-tiny/Conv_20/BiasAdd/YoloRegion
detector/yolo-v4-tiny/split.0
detector/yolo-v4-tiny/split_1.0
detector/yolo-v4-tiny/split_2.0

```
I think I should only need the first two layers, why are there four layers?

At last：
the error is 
```
 out_blob = out_blob.reshape(self.net.layers[self.net.layers[layer_name].parents[0]].out_data[0].shape)
KeyError: 'detector/yolo-v4-tiny/split.0'

```
Thanks！

**Comment by jgespino** [comment]
Hi @RenLuXi 

Thanks for reaching out, YOLOv4 is currently not supported. Could you provide the steps taken to convert the weights file to pb and pb to IR?

BTW, there is another discussion #1358 regarding YOLOv4 that may be of help.

Regards,
Jesus

**Comment by RenLuXi** [comment]
Hi @jgespino 

Thank you for your reply, I just submitted my method to [https://github.com/RenLuXi/tensorflow-yolov4-tiny](https://github.com/RenLuXi/tensorflow-yolov4-tiny).

You can try to run it and you will get that error.

This discussion [#1358 ](https://github.com/openvinotoolkit/openvino/issues/1358) is similar to my mistake.

**Comment by RenLuXi** [comment]
My problem has been solved, I borrowed this method[https://github.com/TNTWEN/OpenVINO-YOLOV4](https://github.com/TNTWEN/OpenVINO-YOLOV4)

Thank you everyone for giving.

**Comment by jgespino** [comment]
@RenLuXi Glad your problem has been resolved! Feel free to start a new issue if you have additional questions.
