### ISSUE TITLE
Possible to limit EUs used by GPU plugin?

### ISSUE THREAD

**Issue by kyflores** [openvinotoolkit/openvino#15121]
Hi,

I was wondering if it was possible for OpenVINO to limit the number of EUs utilized by the GPU plugin. I have an inference app  that was developed on an 80EU part, and I'd like to get a rough estimate of how it would perform on the 48EU part for instance, before trying to buy one.

If this can't be done in OpenVINO directly, is it possible to configure in some other part of the stack, such as the GPU driver, or with an OpenCL environment variable?

Thanks.

**Comment by vladimir-paramuzov** [comment]
OpenVINO doesn't have a knob to change max EUs num as there is no lower level API to control that. 

From the driver perspective there are 2 related debug options:
- [CFEFusedEUDispatch](https://github.com/intel/compute-runtime/blob/6dd7feb435cd1d54128aae7dbfc0a76af2754666/shared/source/debug_settings/debug_variables_base.inl#L96) - if set to 1, it cuts EUs num / 2
- [MaxHwThreadsPercent](https://github.com/intel/compute-runtime/blob/6dd7feb435cd1d54128aae7dbfc0a76af2754666/shared/source/debug_settings/debug_variables_base.inl#L285)

To use these options you need to set `NEOReadDebugKeys=1` env variable, e.g.:
`NEOReadDebugKeys=1 PrintDebugSettings=1 CFEFusedEUDispatch=1 ./app` or
`NEOReadDebugKeys=1 PrintDebugSettings=1 MaxHwThreadsPercent=50 ./app`

However, both options don't change Max EUs num reported by OCL, so openvino will still configure kernels for actual EUs num and perf may be quite different comparing to real HW.

@MichalMrozek any other suggestions besides 2 options above?

**Comment by kyflores** [comment]
Thanks for this, that's very informative! Those options didn't seem to impact my inference performance much, so I need to review how I'm measuring it too. I'll probably end up ordering one of the lower EU parts to work with.
