### ISSUE TITLE
Trying to do arithmetic operation in opset8

### ISSUE THREAD

**Issue by glennford49** [openvinotoolkit/openvino#15151]
from openvino import runtime as ov
x = ov.opset8.multiply(2,3)
print(x)

It prints output : 
 <Multiply: 'Multiply_2' ({})>   # pyopenvino.Node
expect or target output:
  Int 6

Can it return to my expected or target output?

**Comment by rkazants** [comment]
Hi @glennford49,

Please create a model first. After that you can infer and receive the output. Now you would like to create a model with one `Multiply` node with both constant nodes and infer it:

```
from openvino.runtime import Model, Core
x = ov.opset8.multiply(2,3)
model = Model([x.output(0)], [], "model")
core = Core()
compiled_model = core.compile_model(model, "CPU")
output = compiled_model.infer_new_request({})
print(output)
```

We have no eager execution mode for now.

Best regards,
Roman
