### ISSUE TITLE
custom CPU extensions: inShape and outShape are uninitialized

### ISSUE THREAD

**Issue by dkurt** [openvinotoolkit/openvino#1515]
https://github.com/openvinotoolkit/openvino/blob/2a96917e2acd7f3a5521cfd5117fec44d5add6f9/docs/template_extension/cpu_kernel.hpp#L25-L26

Where to get them? Used in getSupportedConfigurations:

https://github.com/openvinotoolkit/openvino/blob/2a96917e2acd7f3a5521cfd5117fec44d5add6f9/docs/template_extension/cpu_kernel.cpp#L77-L80

**Comment by jgespino** [comment]
Hi @dkurt I am reaching out to some folks to get additional information, you should hear back from us shorty.

ref. 35947

**Comment by ilyachur** [comment]
inShape, outShape should be filled in the constructor. 

I created a PR to fix it: https://github.com/openvinotoolkit/openvino/pull/1695
