### ISSUE TITLE
Specifying specific OpSet version to model optimizer

### ISSUE THREAD

**Issue by tersekmatija** [openvinotoolkit/openvino#15188]
Hey, I've noticed that certain operations (SoftMax) have different opsets (e.g., 1 and 8). I am curious if it's somehow possible to specify extra commands/config to `model optimizer`, which would prefer a certain version. By default, SoftMax uses opset version 8, but I'd like to export it with opset version 1. To do that now, I'd have to manually edit the XML file, adjust connections, and inputs/outputs.

I am curious if it's somehow possible to define the version so this does not need to be performed manually.

##### System information (version)
- OpenVINO => 2022.1
- Problem classification: Model Conversion
- Framework: ONNX

**Comment by andrei-kochin** [comment]
Hello @tersekmatija ,

Thanks for reaching OpenVINO!
Could you please explain for which purpose you might need to use older version? In general new version of operation can address the previous version of the implementation.
Currently the only possible way is to use the older ModelOptimizer 2021.3 for example to generate old-style IR.

Looking forward for you reply.

**Comment by slyalin** [comment]
The answer is no, there is no such option, but technically it is possible to implement.

Support for multiple versions of operations in the runtime is the consequence of two things: (1) continuous extension of existing operation set to aim better coverages of new models and (2) backward compatibility requirement to be able to still load old IR in the a newer runtime. To distinguish old semantics in operations from the new one, the version is attached to the operation. If operation is released in some opset, it is frozen and the semantics is never changed for that particular version.

That was from runtime side, the side which consumes IRs. From the other hand, from the side which produces IRs, ModelOptimizer, it is an extra burden to maintain multiple versions of generation code for different opsets without a clear purpose even if it may be technically possible to implement.

**Comment by andrei-kochin** [comment]
@tersekmatija any further comments from your side?

**Comment by andrei-kochin** [comment]
Closing. Please feel free to re-open if stil lrelevant
