### ISSUE TITLE
update  install_NEO_OCL_driver.sh for Ubuntu 22.04

### ISSUE THREAD

**Issue by anujm1** [openvinotoolkit/openvino#15349]
2022.3 says Ubuntu 22.04 is supported as a preview. Can this script be updated as well so the recommended/tested compute runtime version can be installed without having to do it manually?

**Comment by ilya-lavrenov** [comment]
Hi @anujm1 

Suggestion is to use packages from here https://dgpu-docs.intel.com/releases/stable_540_20221205.html#ubuntu-22-04
In future releases we will remove this script and rely on official instructions how to configure GPU / supported driver versions.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. 

Feel free to reopen to ask any questions related to this topic.
