### ISSUE TITLE
How does openvino IR accelerate the model inference compared to onnx？

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#15421]
In my experiment (only cpu，no gpu and igpu), I found that the speed of openvino IR may not change from that of onnx, but openvino IR will perform some DAG front-end optimization and better adapt to the specific ISA optimization operator of openvino, why the speed is not Great improvement?

Thank you very much.

**Comment by brmarkus** [comment]
Can you share some examples - of the used&compared models and results/benchmark/speed/latency/CPU-utilization you gained with them?
Certain operations, certain tensors, certain layers within the model could benefit greatly from underlying instruction-sets or other optimizations, where other models benefit less.

**Comment by sanbuphy** [comment]
> Can you share some examples - of the used&compared models and results/benchmark/speed/latency/CPU-utilization you gained with them? Certain operations, certain tensors, certain layers within the model could benefit greatly from underlying instruction-sets or other optimizations, where other models benefit less.

For example, the picodet of paddle, 

I loaded the original onnx model and converted it to openvino IR with `mo tool` and then used it on the cpu. I compared their speeds and found that they were almost the same.

**Comment by ilya-lavrenov** [comment]
@sanbuphy have you compared speed of ONNX and IR files using OpenVINO Runtime?
If yes, then the performance must be the same. The difference between `core.compile_model('model.xml')` and `core.compile_model('model.onnx')` is time to inference. I.e. how many ms OpenVINO needs to be ready to perform inference.
In case of IR, OpenVINO is fast as possible, while in case of ONNX file input, OpenVINO's `read_model` method converts ONNX to IR internally. When it comes to inference performance - it's the same

**Comment by sanbuphy** [comment]
> @sanbuphy have you compared speed of ONNX and IR files using OpenVINO Runtime? If yes, then the performance must be the same. The difference between `core.compile_model('model.xml')` and `core.compile_model('model.onnx')` is time to inference. I.e. how many ms OpenVINO needs to be ready to perform inference. In case of IR, OpenVINO is fast as possible, while in case of ONNX file input, OpenVINO's `read_model` method converts ONNX to IR internally. When it comes to inference performance - it's the same

Yes，I  compared speed of ONNX and IR files using OpenVINO Runtime.
So can I  understand that  `read_model`  method  converts  all model to OpenVINO IR in any case?(like ONNX Paddle TensorFlow......)  I don't need to convert any model to OpenVINO IR initiatively because it will be converted automatically？If you convert model to OpenVION IR  it just only influence the init time of OpenVINO runtime.

and then I get the another question: 

Normally I don't need to convert the model to openvino runtime initiatively  unless I want to speed up the initialization time , or 
 it can't be read by `read_model` so i need to do something DIY？

**Comment by ilya-lavrenov** [comment]
> If you convert model to OpenVION IR it just only influence the init time of OpenVINO runtime.

In the most of cases - yes, this is the main reason. Secondly, there are some cases which require additional arguments of Model Optimizer, while `read_model` performs something like `mo --input_model model.file`.

> Normally I don't need to convert the model to openvino runtime initiatively unless I want to speed up the initialization time , or
it can't be read by read_model so i need to do something DIY？

According to my previous sentence - yes.
Model optimizer is able to convert more model format with compare to `read_model`, e.g. Kaldi or MxNet models are not supported by `read_model` (because Kaldi and MxNet frontends are written in pure python and cannot be shared with C++ application). But what is supported by `read_model` - is supported by MO as well, since they share exactly the same blocks of code - OpenVINO C++ frontends.

**Comment by sanbuphy** [comment]
> > If you convert model to OpenVION IR it just only influence the init time of OpenVINO runtime.
> 
> In the most of cases - yes, this is the main reason. Secondly, there are some cases which require additional arguments of Model Optimizer, while `read_model` performs something like `mo --input_model model.file`.
> 
> > Normally I don't need to convert the model to openvino runtime initiatively unless I want to speed up the initialization time , or
> > it can't be read by read_model so i need to do something DIY？
> 
> According to my previous sentence - yes. Model optimizer is able to convert more model format with compare to `read_model`, e.g. Kaldi or MxNet models are not supported by `read_model` (because Kaldi and MxNet frontends are written in pure python and cannot be shared with C++ application). But what is supported by `read_model` - is supported by MO as well, since they share exactly the same blocks of code - OpenVINO C++ frontends.

I totally understand and get it, thank you very much for your kind answer.
