### ISSUE TITLE
[Bug] Benchmark_app crashes with Error: Argument shapes are inconsistent

### ISSUE THREAD

**Issue by just-sparta** [openvinotoolkit/openvino#15438]
##### System information

- OpenVINO => 2022.3
- Operating System / Platform => Ubuntu 20.04
- Problem classification: Inference
- Framework: openvino
- Model name: retinaface-resnet50-pytorch

##### Detailed description

benchmark_app since OpenVINO 2022.3.0 crashes with batch > 1 on model retinaface-resnet50-pytorch with the following exception:

```
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[ INFO ] For input  10 files were added. 
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] 
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] 
[ INFO ] 
[Step 3/11] Setting device configuration
[ WARNING ] Device(CPU) performance hint is set to LATENCY
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 88.71 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Network inputs:
[ INFO ]     data (node: data) : f32 / [N,C,H,W] / [1,3,640,640]
[ INFO ] Network outputs:
[ INFO ]     face_rpn_bbox_pred (node: face_rpn_bbox_pred) : f32 / [...] / [1,16800,4]
[ INFO ]     face_rpn_cls_prob (node: face_rpn_cls_prob) : f32 / [...] / [1,16800,2]
[ INFO ]     face_rpn_landmark_pred (node: face_rpn_landmark_pred) : f32 / [...] / [1,16800,10]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Number of test configurations is calculated basing on number of input images
[ INFO ] Reshaping model: 'data': [2,3,640,640]
[ ERROR ] Check 'T::merge_into(output_shape, input)' failed at src/core/shape_inference/include/concat_shape_inference.hpp:37:
While validating node 'v0::Concat face_rpn_landmark_pred (/LandmarkHead.0/Reshape[0]:f32[2,12800,10], /LandmarkHead.1/Reshape[0]:f32[2,3200,10], /LandmarkHead.2/Reshape[0]:f32[1,1600,10]) -> (f32[1,16800,10])' with friendly_name 'face_rpn_landmark_pred':
17:00:12  Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 1).
```

##### Steps to reproduce

1.     Install OpenVINO 2022.3
2.     omz_downloader --name retinaface-resnet50-pytorch
3.     omz_converter --name retinaface-resnet50-pytorch --precisions FP32
4.     benchmark_app -m public/retinaface-resnet50-pytorch/FP32/retinaface-resnet50-pytorch.xml -i wider_face -b 2 -d CPU -niter 100 -hint latency -nireq 10

**Comment by rkazants** [comment]
Hi @just-sparta,

The problem is that conversion of the original problem to onnx format does not preserve reshapability along the batch size. Most likely this is mistake of `torch.onnx.export` function. See why the model in onnx format is not reshapable:
![image](https://user-images.githubusercontent.com/35459624/216842443-0dbec87e-a39a-4140-a92e-df88f24fdb44.png)

I got the onnx model with static batch size equal to two:

```
pytorch_to_onnx.py --model-path=/home/rkazants/public/retinaface-resnet50-pytorch --model-path=/home/my_project/lib/python3.8/site-packages/openvino/model_zoo/models/public/retinaface-resnet50-pytorch --model-name=create_model --import-module=model --input-shape=2,3,640,640 '--model-param=weights=r"/home/public/retinaface-resnet50-pytorch/Resnet50_Final.pth"' --output-file=/home/public/retinaface-resnet50-pytorch/retinaface-resnet50-pytorch.onnx --input-names=data --output-names=face_rpn_bbox_pred,face_rpn_cls_prob,face_rpn_landmark_pred
```

This cmd-line you can see during `omz_converter` execution.

Best regards,
Roman

**Comment by eaidova** [comment]
@rkazants  thank you for your investigation, I updated config for export model with dynamic batch dimension to prevent onnx constant folding for batch.

@just-sparta please check https://github.com/openvinotoolkit/open_model_zoo/pull/3695

**Comment by just-sparta** [comment]
@eaidova @rkazants Appreciate the help!
