### ISSUE TITLE
Copyright date and authors in /openvino/LICENSE is blank

### ISSUE THREAD

**Issue by Meadosc** [openvinotoolkit/openvino#1543]
The copyright date and authors is left blank in the Apache 2.0 license.

https://github.com/openvinotoolkit/openvino/blob/master/LICENSE#L178-L189

**Comment by jgespino** [comment]
Hi @Meadosc 

Thank you for reporting, I will check with the dev team on this!

Regards,
Jesus

Ref. 35667

**Comment by jgespino** [comment]
Hi @Meadosc 

Pull request has been submitted, thanks again for reporting. 
https://github.com/openvinotoolkit/openvino/pull/2046

Regards,
Jesus

**Comment by alalek** [comment]
This request is wrong.

Mentioned lines are about "attach the following boilerplate notice".
OpenVINO uses SPDX approach instead.

see also https://github.com/openvinotoolkit/openvino/pull/1923#issuecomment-679625565
