### ISSUE TITLE
Loading the whisper openvino model from the following repository into the Core i7's internal GPUn results in a run-time error. https://github.com/zhuzilin/whisper-openvino

### ISSUE THREAD

**Issue by koudahts** [openvinotoolkit/openvino#15445]
Loading the whisper openvino model from the following repository into the Core i7's internal GPUn results in a run-time error.
https://github.com/zhuzilin/whisper-openvino

Runtime error message:.
RuntimeError: cldnn program build faild! [GPU] get_tensor() is called for dynamic shape

Is there any limitation?
Thank you.

**Comment by Aznie-Intel** [comment]
Hi @koudahts, have you installed the Intel-GPU specific package? You may refer here: [https://docs.openvino.ai/latest/openvino_docs_install_guides_configurations_for_intel_gpu.html](https://docs.openvino.ai/latest/openvino_docs_install_guides_configurations_for_intel_gpu.html)

I am using Intel Core i7 and able to load the model with Benchmark App with GPU.





![github_1](https://user-images.githubusercontent.com/123156850/216545703-be3242e2-2efe-4158-93bc-b4b112406f1c.JPG)


Regards,
Aznie

**Comment by brmarkus** [comment]
@koudahts which OS in which version do you use?
Which version of OpenVINO do you use, how have you installed it?

**Comment by AlfaLegion** [comment]
I have same problem. I converted model to onnx with dynamic shape. 
It's out info about  devices
![Screenshot from 2023-02-05 22-11-08](https://user-images.githubusercontent.com/25186185/216839820-b5aff822-ba80-4f50-b5ed-e610d739a09c.png)

**Comment by Aznie-Intel** [comment]
Hi @AlfaLegion , the output is supposed to be out when you run [ Hello Query Device Python Sample](https://docs.openvino.ai/latest/openvino_inference_engine_ie_bridges_python_sample_hello_query_device_README.html).

**Comment by vladimir-paramuzov** [comment]
@koudahts, @AlfaLegion As I can see, decoder model requires dynamic shapes support which is under development for GPU plugin. Part of required fixes was done in https://github.com/openvinotoolkit/openvino/pull/15176 and https://github.com/openvinotoolkit/openvino/pull/15543, but more work is needed for functional enabling and performance optimizations.

**Comment by AlfaLegion** [comment]
@koudahts @vladimir-paramuzov  I found a solution: https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_GPU.html#dynamic-shapes
GPU only supports dynamic axis for batch size with fixed upper limit

**Comment by avitial** [comment]
Closing this as the issue has been resolved. Feel free to reopen to ask any questions related to this topic.
