### ISSUE TITLE
Comparison between C + + and python using gpu memory

### ISSUE THREAD

**Issue by zhongqingyang** [openvinotoolkit/openvino#1545]
I load the same model with C++ and python,why C++ used gpu memory twice as much gpu memory as python.

**Comment by vladimir-paramuzov** [comment]
@zhongqingyang  Could you provide more details?  OV version, used model and application, system info.

**Comment by zhongqingyang** [comment]
> @zhongqingyang 您能否提供更多详细信息？OV版本，使用的型号和应用程序，系统信息。
I found that it is not a problem with video memory，I have 6 vpu,but one vpu can only load one model．
I using openvino.2020.1
what can I do.
Thank you for your answer

**Comment by maxlytkin** [comment]
Hi @zhongqingyang 
While your MYRIAD device is occupied by a single process, you can load multiple models within this process. 
Please take a look at these examples on how this being implemented: 
Action Recognition Python demo - https://github.com/opencv/open_model_zoo/tree/master/demos/python_demos/action_recognition 
Crossroad Camera demo - https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/crossroad_camera_demo

With regards to GPU memory question, please confirm if this is no longer the case for you.

Thanks.
Best regards, Max.

**Comment by maxlytkin** [comment]
@zhongqingyang 
We haven't heard back from you in a while. Hopefully previous responses were sufficient to help you in resolving this issue, so we are closing this thread.

Thanks for using OpenVINO toolkit.
Best regards, Max.
