### ISSUE TITLE
Python API wrapper init and Usage - ARM64

### ISSUE THREAD

**Issue by nullbyte91** [openvinotoolkit/openvino#1550]
Hello All, 

I'm trying to use OpenVino Toolkit on ARM64 CPU with NCS2. I'm able to build both the inference engine and the MYRIAD plugin from openvino source code.

Please find the CMake configuration,
```bash
cmake -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_MKL_DNN=OFF \
    -DENABLE_CLDNN=ON \
    -DENABLE_GNA=OFF \
    -DENABLE_SSE42=OFF \
    -DTHREADING=SEQ \
    -DENABLE_SAMPLES=ON \
    -DPYTHON_EXECUTABLE=`which python3.6` ..
```
I'm able to run a few examples written in C++. Now, I want to check the Python API, and I don't find any documentation that explains how to export OpenVino Python API. I checked the setupvars scripts and tried changing a few export path of the Inference engine. But, It didn't help me.

Regards,
Jegathesan S

**Comment by natxopedreira** [comment]
https://gist.github.com/dkurt/585f886a000d3afade62f66c25640148

**Comment by nullbyte91** [comment]
@natxopedreira I'm able to build Python wrapper by passing -DPYTHON_EXECUTABLE=`which python3.6` to CMake. Now I'm not sure how to export/initialize the OpenVino Python package so that I can import the openvino package from a python script.

**Comment by natxopedreira** [comment]
Ahhh ok, you have to put the vars inside .bashrc file LD_LIBRARY_PATH and PYTHONPATH

So when you open a terminal it will add the paths and python will find the module

**Comment by nullbyte91** [comment]
@natxopedreira I missing something here. When I searched the python folder under OpenVino build folder,

```bash
nullbyte@nullbyte:~/Desktop/openvino/openvino/openvino/build$ find . -name "python"
./_deps/ext_protobuf-src/python
./_deps/ext_protobuf-src/python/compatibility_tests/v2.5.0/protos/python
./_deps/ext_protobuf-src/src/google/protobuf/compiler/python
./_deps/ext_protobuf-src/kokoro/linux/python
./_deps/ext_protobuf-src/kokoro/macos/python
./_deps/ext_protobuf-src/kokoro/release/python
./_deps/ext_protobuf-src/util/python
./_deps/ext_protobuf-src/benchmarks/python
./_deps/ext_protobuf-build/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/python
``` 
I don't see any .so file build for Python wrapper. But, I will go through your gist page and I will let you know the status in some time. Thanks again for your help.

**Comment by natxopedreira** [comment]
[https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md)

Just make sure you build with python support..... 

According the doc 

```
Use the -DENABLE_PYTHON=ON option. To specify an exact Python version, use the following options:

-DPYTHON_EXECUTABLE=`which python3.7` \
-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.7m.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.7
```

**Comment by nullbyte91** [comment]
@natxopedreira Yes, I missed to pass -DENABLE_PYTHON=ON. Thanks again for the help.

Update:
Please export PYTHONPATH and LD_LIBRARY_PATH.
```
export PYTHONPATH=$PYTHONPATH:/~/openvino/bin/aarch64/Release/lib/python_api/python3.6/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/openvino/bin/aarch64/Release/lib/
```
