### ISSUE TITLE
[Bug] Regression w/ change "pull/11183" regarding unexposed Tblob<T> for linking w/ ov dlls on Windows

### ISSUE THREAD

**Issue by BinBYang** [openvinotoolkit/openvino#15510]
##### System information (version)
- OpenVINO => latest release
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

- Problem classification => failed to link w/ openvino dlls, due to undefined reference for TBlob<T> on Windows

##### Detailed description
After openvino change https://github.com/openvinotoolkit/openvino/pull/11183, TBLOB<T> seems no longer exposed for Windows build. I encountered link errors below due to this.

error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl InferenceEngine::TBlob<unsigned char,struct std::enable_if<1,void> >::TBlob<unsigned char,struct std::enable_if<1,void> >(class InferenceEngine::TensorDesc const &,unsigned char *,unsigned __int64)" (_imp??0?$TBlob@EU?$enable_if@$00X@std@@@inferenceengine@@qeaa@AEBVTensorDesc@1@PEAE_K@Z) referenced in function "public: __cdecl std::_Ref_count_obj2<class InferenceEngine::TBlob<unsigned char,struct std::enable_if<1,void> > >::_Ref_count_obj2<class InferenceEngine::TBlob<unsigned char,struct std::enable_if<1,void> > ><class InferenceEngine::TensorDesc const &,unsigned char * &,unsigned __int64 &>(class InferenceEngine::TensorDesc const &,unsigned char * &,unsigned __int64 &)" (??$?0AEBVTensorDesc@InferenceEngine@@AEAPEAEAEA_K@?$_Ref_count_obj2@V?$TBlob@EU?$enable_if@$00X@std@@@inferenceengine@@@std@@qeaa@AEBVTensorDesc@InferenceEngine@@AEAPEAEAEA_K@Z)

error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl InferenceEngine::TBlob<unsigned char,struct std::enable_if<1,void> >::~TBlob<unsigned char,struct std::enable_if<1,void> >(void)" (_imp??1?$TBlob@EU?$enable_if@$00X@std@@@inferenceengine@https://github.com/UEAA@XZ) referenced in function "public: virtual void * __cdecl InferenceEngine::TBlob<unsigned char,struct std::enable_if<1,void> >::`scalar deleting destructor'(unsigned int)" (??_G?$TBlob@EU?$enable_if@$00X@std@@@inferenceengine@@UEAAPEAXI@Z)

error LNK2001: unresolved external symbol "public: virtual void __cdecl InferenceEngine::TBlob<unsigned char,struct std::enable_if<1,void> >::allocate(void)" (?allocate@?$TBlob@EU?$enable_if@$00X@std@@@inferenceengine@@UEAAXXZ)

error LNK2001: unresolved external symbol "public: virtual class InferenceEngine::LockedMemory __cdecl InferenceEngine::TBlob<unsigned char,struct std::enable_if<1,void> >::buffer(void)" (?buffer@?$TBlob@EU?$enable_if@$00X@std@@@inferenceengine@https://github.com/UEAA?AV?$LockedMemory@X@2@XZ)

##### Steps to reproduce

Link openvino dlls on Windows, w/ app code like below,

      // "bin" is std::vector<uint8_t> containing weights data.
      auto weights = InferenceEngine::make_shared_blob<uint8_t>(
          {InferenceEngine::Precision::U8, {bin.size()}, InferenceEngine::C},
          bin.data());
      network = ie.ReadNetwork(model_xml, weights);
      executor = ie.LoadNetwork(network, device);

**Comment by ilya-lavrenov** [comment]
Hi @BinBYang 
How do you compile the application? What compiler do you use?
All our samples, etc are passing the compilation and nobody has experienced this issue.

**Comment by ilyachur** [comment]
I created PR https://github.com/openvinotoolkit/openvino/pull/15516. So let's take a look to our CI

**Comment by ilyachur** [comment]
As I see right now for VS 19:
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.5
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
```

I got the next error:
```
warning C4910: 'InferenceEngine::TBlob<float,std::enable_if<true,void>>': '__declspec(dllexport)' and 'extern' are incompatible on an explicit instantiation
```

**Comment by BinBYang** [comment]
I think you should use "ifndef _WIN32" instead of current "ifndef WIN32".

_WIN32 is windows compiler defined, but WIN32 is only defined by Windows header.

**Comment by BinBYang** [comment]
I had tried the solution I mentioned above, it works for me.

**Comment by ilyachur** [comment]
Ok, I will change
