### ISSUE TITLE
[Bug]: Inconsistent results with hello_query script

### ISSUE THREAD

**Issue by lalith-mcw** [openvinotoolkit/openvino#15552]
With I7-13600K Intel CPU:
INFERENCE_PRECISION_HINT: UNSUPPORTED TYPE

With I7-1165G Intel CPU:
INFERENCE_PRECISION_HINT: <Type: 'float32'>

With iGPUs:
Nothing is showing up as `INFERENCE_PRECISION_HINT`

Why the implementation of these options are inconsistent with devices ? Is this an Openvino issue or hardware specific issues ?

**Comment by lalith-mcw** [comment]
Even if the supported values are,
`Supported values: bf16, f32`

When trying to run with bf16 format precision hint, (tried with benchmark_app)
```
self.core.set_property(device, config[device])
RuntimeError: Platform doesn't support BF16 format

```

**Comment by andrei-kochin** [comment]
@dmitry-gorokhov  @wenjiew  could you please ask someone to take a look?

**Comment by wenjiew** [comment]
@xipingyan Can you help take a look? Please note the additional question in this link: https://github.com/openvinotoolkit/openvino/issues/15527

**Comment by xipingyan** [comment]
> With I7-13600K Intel CPU: INFERENCE_PRECISION_HINT: UNSUPPORTED TYPE
> 
> With I7-1165G Intel CPU: INFERENCE_PRECISION_HINT: <Type: 'float32'>
> 
> With iGPUs: Nothing is showing up as `INFERENCE_PRECISION_HINT`
> 
> Why the implementation of these options are inconsistent with devices ? Is this an Openvino issue or hardware specific issues ?

Hi @lalith-mcw, the answer is yes. Taking CPU as example, it will call low API to check if the current cpu supports it (dnnl::impl::cpu::x64::mayiuse).

**Comment by xipingyan** [comment]
> Even if the supported values are, `Supported values: bf16, f32`
> 
> When trying to run with bf16 format precision hint, (tried with benchmark_app)
> 
> ```
> self.core.set_property(device, config[device])
> RuntimeError: Platform doesn't support BF16 format
> ```

hi @lalith-mcw , How do you get "Supported values: bf16, f32"? From the source code "https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/src/config.cpp#L166", I think this is just an example, it expects the user to set it like this, not to say that the current CPU supports bf16 and fp32.

**Comment by xipingyan** [comment]
hi @lalith-mcw, I am not sure I explain it clearly. I did an example.
This is my test code:

```
import openvino.runtime as ov
core = ov.Core()
fn="../models/test_model_fp32.xml"
model = core.read_model(fn)
cfg=core.get_property("CPU", "INFERENCE_PRECISION_HINT")
print("cfg=", cfg)
core.set_property("CPU", {"INFERENCE_PRECISION_HINT": "fp32"})
cfg=core.get_property("CPU", "INFERENCE_PRECISION_HINT")
print("cfg=", cfg)
```

If your computer support bf16 and fp32 for CPU, bf16 will be default inference percision. Run this snippet, we will get:
```
cfg= <Type: 'bfloat16'>
cfg= <Type: 'float32'>
```

If your computer only support fp32 for CPU, but you still set bf16, you will get:

```
cfg= <Type: 'float32'>
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    core.set_property("CPU", {"INFERENCE_PRECISION_HINT": "bf16"})
RuntimeError: Platform doesn't support BF16 format
```

So I think it's reasonable, please let me know if I still don't get your question.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
