### ISSUE TITLE
[Bug]inference speed of OCR recognition with OpenVINO slower than onnxruntime

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#15573]
##### System information (version)

- OpenVINO=> 2022.1
- Operating System / Platform => ubuntu 22.04
![image](https://user-images.githubusercontent.com/96160062/217446086-d26591e8-51e0-4005-b3c4-2618714e31ec.png)

##### Detailed description

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/models_list.md
![image](https://user-images.githubusercontent.com/96160062/217445739-0da6213c-c716-4cde-a038-67de2fa7069a.png)

I am using this ocr model of paddle,   here is the download address：

https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_rec_infer.tar

##### Steps to reproduce

This is my configuration, I loaded the paddle model directly, and converted it to the onnx model with paddle2onnx, without any modification.

![image](https://user-images.githubusercontent.com/96160062/217446971-495f6cd5-f787-44ca-95a2-774a15f19e1a.png)

But I found that when I use openvino inference, it takes at least 2.5ms, although there are fluctuations, it is always above 2ms

![image](https://user-images.githubusercontent.com/96160062/217447615-b7b94ea3-8c10-44f6-a51a-90220efaae6f.png)

![image](https://user-images.githubusercontent.com/96160062/217447711-feb4b296-dfa1-47df-a18c-4ede29868259.png)

However, the inference time under onnxruntime only needs to be within 2ms, and even 1.6ms , compared with
openvino is much faster.

I have also tried to read the converted onnx file directly with openvino, the phenomenon is still unchanged.

I want to know what is the reason for this? How can I fix it, thanks!

**Comment by ilya-lavrenov** [comment]
@sanbuphy Please, don't use `infer_new_request` in a cycle. This method creates new inference requests each time leading to additional over-head. 
Proper way is to create an InferRequest before the loop (like you did for ONNX Runtime) and call infer method inside the loop

**Comment by ilya-lavrenov** [comment]
@jiwaszki should we deprecate `infer_new_request` in favor of callable `model(tensor)` ?

**Comment by sanbuphy** [comment]
> @sanbuphy Please, don't use `infer_new_request` in a cycle. This method creates new inference requests each time leading to additional overhead. Proper way is to create an InferRequest before the loop (like you did for ONNX Runtime) and call infer method inside the loop



> @sanbuphy Please, don't use `infer_new_request` in a cycle. This method creates new inference requests each time leading to additional overhead. Proper way is to create an InferRequest before the loop (like you did for ONNX Runtime) and call infer method inside the loop

May I ask which API to use, I saw this but it doesn't work, thanks.

![image](https://user-images.githubusercontent.com/96160062/217452688-5554e638-c723-45b0-af4c-7c51c69e36f2.png)

**Comment by sanbuphy** [comment]
![image](https://user-images.githubusercontent.com/96160062/217456135-122f792b-f418-4adc-97c7-3761d33f6fda.png)

I used this api, it's still a bit slow, I can provide this measurement file if needed

**Comment by ilya-lavrenov** [comment]
@sanbuphy you have not set any input data and started inference.
Please, read through this document https://docs.openvino.ai/latest/openvino_docs_OV_UG_Integrate_OV_with_your_application.html

**Comment by sanbuphy** [comment]
> @sanbuphy you have not set any input data and started inference. Please, read through this document https://docs.openvino.ai/latest/openvino_docs_OV_UG_Integrate_OV_with_your_application.html

![image](https://user-images.githubusercontent.com/96160062/217458663-cd32f373-69bb-44fd-846a-4b3c3a1b28f0.png)

I can use the above api to get the results normally, the speed is about the same as onnxruntime, but I read the tutorial to use the new api, and I found that the memory cannot be shared

**Comment by jiwaszki** [comment]
Hi @sanbuphy !

First, I would recommend to switch from 2022.1 to 2022.3, it brings a lot of improvements! If this is not possible, let me know. I will prepare similar examples for the older version:)

Here are inference scenarios that might be interesting to you:

* You do not have to add C++ aligned methods to your code. Python API provides shortcut methods and extensions that simplify the code and makes it more pythonic. Documentation for InferReuqest's `infer()` is [here](https://docs.openvino.ai/latest/api/ie_python_api/_autosummary/openvino.runtime.InferRequest.html#openvino.runtime.InferRequest.infer). So let's assume you have one-input model:
```python
# Data in numpy format
arr = numpy.array(...)

infer_request = compiled_model.create_infer_request()

# Case 1: use index of your input
result = infer_request.infer({0: arr})
# Case 2: use name of your input
result = infer_request.infer({"name_of_input": arr})
# Case 3: use Output port of your input
result = infer_request.infer({compiled_model.input(0): arr})
# Case 4: if model is only one-input, you can pass numpy array directly
result = infer_request.infer(arr)
```
What are the benefits? Firstly, short compact code. Secondly, it provides transparent mechanism that handles most cases where data is misaligned or there is a mismatch of inputs types.
* If you want to use special `shared_memory` mode that creates "zero-copy" Tensor, you need to [follow the rules explained here](https://docs.openvino.ai/latest/api/ie_python_api/_autosummary/openvino.runtime.Tensor.html#openvino.runtime.Tensor.__init__). Example:
```python
# Data in numpy format
arr = numpy.array(...)

# Create Tensor with shared memory
tensor = ov.Tensor(arr, shared_memory=True)
# And let's use case 4 from previous example
result = infer_request.infer(arr)
```
Where is the catch? Shared memory Tensor should match input type, shape and follow "C-style" of memory alignment. **Python memory (numpy arrays/lists) are not required to follow "C-style"!** It really depends on different variables like: data source, libraries, system preferences. Thus if one or more conditions do not apply, conversion should be done:
```python
import numpy as np
import openvino.runtime as ov

arr = np.ones((4, 64), dtype=np.float32)
# You can obtain OV types from inputs/outputs as well:
# ov_dtype = infer_request.inputs[0].get_element_type().to_dtype()
ov_type = ov.Type.i8
ov_dtype = ov_type.to_dtype()
# Check conditions if there is a chance of array to be either misaligned or in different type
# I left out shape differences as these might include custom handling like padding or resizing
adjusted_arr = arr if arr.flags['C_CONTIGUOUS'] and ov_dtype == arr.dtype else np.ascontiguousarray(arr, dtype=ov_dtype)
tensor = ov.Tensor(adjusted_arr, shared_memory=True)
```
Remember that user/developer is responsible for upkeeping shared memory lifetime in this scenario. If `arr` gets garbage collected, Tensor's memory is also removed (this is a cost of "zero-copy" approach). 

More reading can be found here:
https://docs.openvino.ai/latest/openvino_docs_OV_UG_Python_API_exclusives.html 
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html#numpy.ndarray.flags

Looking forward to your response, cheers!

**Comment by sanbuphy** [comment]
> Hi @sanbuphy !
> 
> First, I would recommend to switch from 2022.1 to 2022.3, it brings a lot of improvements! If this is not possible, let me know. I will prepare similar examples for the older version:)
> 
> Here are inference scenarios that might be interesting to you:
> 
> * You do not have to add C++ aligned methods to your code. Python API provides shortcut methods and extensions that simplify the code and makes it more pythonic. Documentation for InferReuqest's `infer()` is [here](https://docs.openvino.ai/latest/api/ie_python_api/_autosummary/openvino.runtime.InferRequest.html#openvino.runtime.InferRequest.infer). So let's assume you have one-input model:
> 
> ```python
> # Data in numpy format
> arr = numpy.array(...)
> 
> infer_request = compiled_model.create_infer_request()
> 
> # Case 1: use index of your input
> result = infer_request.infer({0: arr})
> # Case 2: use name of your input
> result = infer_request.infer({"name_of_input": arr})
> # Case 3: use Output port of your input
> result = infer_request.infer({compiled_model.input(0): arr})
> # Case 4: if model is only one-input, you can pass numpy array directly
> result = infer_request.infer(arr)
> ```
> 
> What are the benefits? Firstly, short compact code. Secondly, it provides transparent mechanism that handles most cases where data is misaligned or there is a mismatch of inputs types.
> 
> * If you want to use special `shared_memory` mode that creates "zero-copy" Tensor, you need to [follow the rules explained here](https://docs.openvino.ai/latest/api/ie_python_api/_autosummary/openvino.runtime.Tensor.html#openvino.runtime.Tensor.__init__). Example:
> 
> ```python
> # Data in numpy format
> arr = numpy.array(...)
> 
> # Create Tensor with shared memory
> tensor = ov.Tensor(arr, shared_memory=True)
> # And let's use case 4 from previous example
> result = infer_request.infer(arr)
> ```
> 
> Where is the catch? Shared memory Tensor should match input type, shape and follow "C-style" of memory alignment. **Python memory (numpy arrays/lists) are not required to follow "C-style"!** It really depends on different variables like: data source, libraries, system preferences. Thus if one or more conditions do not apply, conversion should be done:
> 
> ```python
> import numpy as np
> import openvino.runtime as ov
> 
> arr = np.ones((4, 64), dtype=np.float32)
> # You can obtain OV types from inputs/outputs as well:
> # ov_dtype = infer_request.inputs[0].get_element_type().to_dtype()
> ov_type = ov.Type.i8
> ov_dtype = ov_type.to_dtype()
> # Check conditions if there is a chance of array to be either misaligned or in different type
> # I left out shape differences as these might include custom handling like padding or resizing
> adjusted_arr = arr if arr.flags['C_CONTIGUOUS'] and ov_dtype == arr.dtype else np.ascontiguousarray(arr, dtype=ov_dtype)
> tensor = ov.Tensor(adjusted_arr, shared_memory=True)
> ```
> 
> Remember that user/developer is responsible for upkeeping shared memory lifetime in this scenario. If `arr` gets garbage collected, Tensor's memory is also removed (this is a cost of "zero-copy" approach).
> 
> More reading can be found here: https://docs.openvino.ai/latest/openvino_docs_OV_UG_Python_API_exclusives.html https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html#numpy.ndarray.flags
> 
> Looking forward to your response, cheers!

You completely answered my doubts, thank you very much for your serious reply!  👍 

I have one final question, where can I get the latest async API? The api manuals on the documentation seem to be aligned with the c++ version, i want to see the python code.

**Comment by jiwaszki** [comment]
@sanbuphy  If you want Python examples of asynchronous Python take a look at:
* [Integration guide](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Integrate_OV_with_your_application.html#doxid-openvino-docs-o-v-u-g-integrate-o-v-with-your-application) - please switch to "Python" above code cells. Additionally, `start_async` works similar to `infer` for core `InferRequest` class, async mode extends inference with callbacks and user metadata. 
* [AsyncInferQueue API](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Python_API_exclusives.html#asyncinferqueue) - it is something really useful for custom pipelines, here is [API reference for it](https://docs.openvino.ai/latest/api/ie_python_api/_autosummary/openvino.runtime.AsyncInferQueue.html) (PS this class is only available in Python, great exclusive!)
* [OpenVINO™ Notebooks](https://github.com/openvinotoolkit/openvino_notebooks) - I think this is the most helpful source, [notebook number 115](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/115-async-api) sounds like amazing example.

Let me know if you found these interesting! 😄

**Comment by sanbuphy** [comment]
> @sanbuphy If you want Python examples of asynchronous Python take a look at:
> 
> * [Integration guide](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Integrate_OV_with_your_application.html#doxid-openvino-docs-o-v-u-g-integrate-o-v-with-your-application) - please switch to "Python" above code cells. Additionally, `start_async` works similar to `infer` for core `InferRequest` class, async mode extends inference with callbacks and user metadata.
> * [AsyncInferQueue API](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Python_API_exclusives.html#asyncinferqueue) - it is something really useful in custom pipelines, here is [API reference for it](https://docs.openvino.ai/latest/api/ie_python_api/_autosummary/openvino.runtime.AsyncInferQueue.html) (PS this class is only available in Python, great exclusive!)
> * [OpenVINO™ Notebooks](https://github.com/openvinotoolkit/openvino_notebooks) - I think this is the most helpful source, [notebook number 115](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/115-async-api) sounds like amazing example.
> 
> Let me know if you found these interesting! 😄

HI @jiwaszki ！ Thank you for your information, I have read those documentations , but I think the api of the document may still be a little old, The api you gave is the most practical.

![image](https://user-images.githubusercontent.com/96160062/217756945-2ba3188b-c3bf-4b56-a8ac-95c1b4105b05.png)

I used this api to successfully run the program, but I found another very magical problem:

Assuming I run it 200 times, the time it takes is：

![image](https://user-images.githubusercontent.com/96160062/217758221-52b74bc9-df84-41c1-87d6-f65109ed2678.png)

But when I try to enable multithreading for onnxruntime

This shocked me very much. I don't understand why using multi-threading to remove the IO bottleneck can make onnx reasoning so much faster than openvino, obviously asynchronous should be the fastest

![image](https://user-images.githubusercontent.com/96160062/217758790-36f14e61-00b1-46ad-9099-527e6c2f295c.png)

Can you tell me their difference and reason, thank you very much.

I almost couldn't eat dinner because of this problem.  hah

**Comment by jiwaszki** [comment]
@sanbuphy "I don't understand why using multi-threading to remove the IO bottleneck can make onnxruntime inference so much faster than openvino, obviously asynchronous should be the fastest." - Short answer: yes... and no. 😄

First, there is a mismatch between two snippets. You created a pool of 10 workers for ONNX and only 2 workers(!) for OpenVINO. This creates a significant difference, both in a latency of data transfer and in the inference latency. If you have 10 workers to complete the task, it will be done faster (_usually:)_). BTW take a look at the time difference - only 0.12 vs 0.06 with 5x workers.

To create similar(?) snippet with OpenVINO, I would recommend using `AsyncInferQueue` (mentioned before):
```python
import numpy as np
import openvino.runtime as ov

# Create data
NUMBER_OF_IMAGES = 2000
IMAGE_SHAPE = (64, 64)
# I am not sure how data should look for the model, let's create some random ones
c = [np.ones(IMAGE_SHAPE) for _ in range(NUMBER_OF_IMAGES)]

# Now OV part
core = ov.Core()
# Let's create simple model
param1 = ov.opset10.parameter(ov.Shape(IMAGE_SHAPE), dtype=np.int32, name="data1")
param2 = ov.opset10.parameter(ov.Shape([]), dtype=np.int32, name="data2")
add = ov.opset10.add(param1, param2)

model = ov.Model(add, [param1, param2], "TestFunction")
compiled_model = core.compile_model(model, "CPU")

# Do not set jobs or keep `jobs=0` if you want OV to set automatically to the optimal number 
infer_queue = ov.AsyncInferQueue(compiled_model, jobs=10)
results = [None] * NUMBER_OF_IMAGES


def my_callback(request, job_id):
    # You need to copy to avoid a reference to a view of the array
    results[job_id] = np.copy(request.get_output_tensor(0).data)


infer_queue.set_callback(my_callback)

# You can add start-timer here...
for index in range(0, NUMBER_OF_IMAGES):
    infer_queue.start_async({0: c[index], 1: np.int32(index)}, userdata=index)
infer_queue.wait_all()
# and "end" it here.

# Test:
assert np.allclose(c[200] + 200, results[200])
```
There are many ways to handle this scenario. You can work with "batches" of requests and stopping after each full iteration or you can use callbacks as in the example. It really depends on the use-case and outside variables like libraries you work with. Actually, it is really hard to tell what is the goal of your snippets - could you share all the code as a gist/repository/notebook? Please try to adjust above snippet to your needs.

Hope it helps, cheers!

**Comment by sanbuphy** [comment]
> 



> @sanbuphy "I don't understand why using multi-threading to remove the IO bottleneck can make onnxruntime inference so much faster than openvino, obviously asynchronous should be the fastest." - Short answer: yes... and no. 😄
> 
> First, there is a mismatch between two snippets. You created a pool of 10 workers for ONNX and only 2 workers(!) for OpenVINO. This creates a significant difference, both in a latency of data transfer and in the inference latency. If you have 10 workers to complete the task, it will be done faster (_usually:)_). BTW take a look at the time difference - only 0.12 vs 0.06 with 5x workers.
> 
> To create similar(?) snippet with OpenVINO, I would recommend using `AsyncInferQueue` (mentioned before):
> 
> ```python
> import numpy as np
> import openvino.runtime as ov
> 
> # Create data
> NUMBER_OF_IMAGES = 2000
> IMAGE_SHAPE = (64, 64)
> # I am not sure how data should look for the model, let's create some random ones
> c = [np.ones(IMAGE_SHAPE) for _ in range(NUMBER_OF_IMAGES)]
> 
> # Now OV part
> core = ov.Core()
> # Let's create simple model
> param1 = ov.opset10.parameter(ov.Shape(IMAGE_SHAPE), dtype=np.int32, name="data1")
> param2 = ov.opset10.parameter(ov.Shape([]), dtype=np.int32, name="data2")
> add = ov.opset10.add(param1, param2)
> 
> model = ov.Model(add, [param1, param2], "TestFunction")
> compiled_model = core.compile_model(model, "CPU")
> 
> # Do not set jobs or keep `jobs=0` if you want OV to set automatically to the optimal number 
> infer_queue = ov.AsyncInferQueue(compiled_model, jobs=10)
> results = [None] * NUMBER_OF_IMAGES
> 
> 
> def my_callback(request, job_id):
>     # You need to copy to avoid a reference to a view of the array
>     results[job_id] = np.copy(request.get_output_tensor(0).data)
> 
> 
> infer_queue.set_callback(my_callback)
> 
> # You can add start-timer here...
> for index in range(0, NUMBER_OF_IMAGES):
>     infer_queue.start_async({0: c[index], 1: np.int32(index)}, userdata=index)
> infer_queue.wait_all()
> # and "end" it here.
> 
> # Test:
> assert np.allclose(c[200] + 200, results[200])
> ```
> 
> There are many ways to handle this scenario. You can work with "batches" of requests and stopping after each full iteration or you can use callbacks as in the example. It really depends on the use-case and outside variables like libraries you work with. Actually, it is really hard to tell what is the goal of your snippets - could you share all the code as a gist/repository/notebook? Please try to adjust above snippet to your needs.
> 
> Hope it helps, cheers!

@jiwaszki 
Thank you very much for your answer!
Let me think about it and give you an answer. I will try to sort out a file and let us study this interesting issue.
If I have a chance, I would like to buy you a cup of coffee. Is there anything way?
Thanks again for your help. 😄😄

**Comment by sanbuphy** [comment]
> @sanbuphy "I don't understand why using multi-threading to remove the IO bottleneck can make onnxruntime inference so much faster than openvino, obviously asynchronous should be the fastest." - Short answer: yes... and no. 😄
> 
> First, there is a mismatch between two snippets. You created a pool of 10 workers for ONNX and only 2 workers(!) for OpenVINO. This creates a significant difference, both in a latency of data transfer and in the inference latency. If you have 10 workers to complete the task, it will be done faster (_usually:)_). BTW take a look at the time difference - only 0.12 vs 0.06 with 5x workers.
> 
> To create similar(?) snippet with OpenVINO, I would recommend using `AsyncInferQueue` (mentioned before):
> 
> ```python
> import numpy as np
> import openvino.runtime as ov
> 
> # Create data
> NUMBER_OF_IMAGES = 2000
> IMAGE_SHAPE = (64, 64)
> # I am not sure how data should look for the model, let's create some random ones
> c = [np.ones(IMAGE_SHAPE) for _ in range(NUMBER_OF_IMAGES)]
> 
> # Now OV part
> core = ov.Core()
> # Let's create simple model
> param1 = ov.opset10.parameter(ov.Shape(IMAGE_SHAPE), dtype=np.int32, name="data1")
> param2 = ov.opset10.parameter(ov.Shape([]), dtype=np.int32, name="data2")
> add = ov.opset10.add(param1, param2)
> 
> model = ov.Model(add, [param1, param2], "TestFunction")
> compiled_model = core.compile_model(model, "CPU")
> 
> # Do not set jobs or keep `jobs=0` if you want OV to set automatically to the optimal number 
> infer_queue = ov.AsyncInferQueue(compiled_model, jobs=10)
> results = [None] * NUMBER_OF_IMAGES
> 
> 
> def my_callback(request, job_id):
>     # You need to copy to avoid a reference to a view of the array
>     results[job_id] = np.copy(request.get_output_tensor(0).data)
> 
> 
> infer_queue.set_callback(my_callback)
> 
> # You can add start-timer here...
> for index in range(0, NUMBER_OF_IMAGES):
>     infer_queue.start_async({0: c[index], 1: np.int32(index)}, userdata=index)
> infer_queue.wait_all()
> # and "end" it here.
> 
> # Test:
> assert np.allclose(c[200] + 200, results[200])
> ```
> 
> There are many ways to handle this scenario. You can work with "batches" of requests and stopping after each full iteration or you can use callbacks as in the example. It really depends on the use-case and outside variables like libraries you work with. Actually, it is really hard to tell what is the goal of your snippets - could you share all the code as a gist/repository/notebook? Please try to adjust above snippet to your needs.
> 
> Hope it helps, cheers!

@jiwaszki 

Hello! I tested the api in detail and found that openvino is indeed faster in the object detection model, but much slower in the recognition model. I suspect it is a problem with operators or operator fusion. I have prepared the complete code and information, can you please help me look, thank you very much.



[vino_onnx_diff.zip](https://github.com/openvinotoolkit/openvino/files/10718433/vino_onnx_diff.zip)

**Comment by sanbuphy** [comment]
> @sanbuphy I am happy to see `AsyncInferQueue` being integrated!
> 
> There are several techniques that can help. I will show two of them (_I tested them out on my Xeon CPU, **you might need to adjust them to your device**_).
> 
> * Dynamic inputs are supported, yet OpenVINO shines when shapes are known before inference. First you can make your inputs static:
> 
> ```python
> # ... code ...
> det_net = core.read_model(ONNX_MODEL_PATH)
> 
> det_net.reshape(input_image.shape)  # if you know shapes of your images, you can reshape model in advance
> 
> compiled_model = core.compile_model(det_net, "CPU")
> # ... code ...
> ```
> 
> * Additional configs can help as well. One simple key you can use:
> 
> ```python
> # ... code ...
> det_net = core.read_model(ONNX_MODEL_PATH)
> det_net.reshape(input_image.shape)
> 
> config = {
>     ov.properties.hint.performance_mode(): ov.properties.hint.PerformanceMode.THROUGHPUT,
>     # you can experiment with different keys as well
> }
> 
> compiled_model = core.compile_model(det_net, "CPU", config)
> # ... code ...
> ```
> 
> If I ran it all together OV is now faster on my machine. Once again this is very specific case and I advise to experiment on your own. More reading can be found in sections like ["Optimize Inference"](https://docs.openvino.ai/latest/openvino_docs_deployment_optimization_guide_dldt_optimization_guide.html#) and ["High-level Performance Hints"](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Performance_Hints.html).
> 
> ```
> gh_issue$ python recognition_test.py 
> Images:  1000
> Workers:  10
> Configs:
> PerformanceMode.THROUGHPUT
> OpenVINO:  1.2424111366271973
> ONNX:      1.6262636184692383
> ```
> 
> Also adding @maxnick for further investigation of this case. Cheers!

Hello @jiwaszki , I totally found the problem, the key is :

- first, we should set PerformanceMode.THROUGHPUT ( the other Performance option seems not work)
- second, we should set `det_net.reshape(input_image.shape)`, the static graph mode will run faster.

But for OCR task, we can't set the shape completely static, because the length may be different, so the last parameter can't be fixed：
`det_net.reshape([1,3,32,-1])`
That way it's not as fast, but still faster than onnx.

Overall I've completely solved this problem, cheers to openvino 😄

Thanks again for your serious help.

**Comment by jiwaszki** [comment]
@sanbuphy you are welcome! I am very happy that solution has been found so quickly.

I will close the issue now. Feel free to contact us anytime!:)
