### ISSUE TITLE
[Bug] Torch's affinity setting lead to openvino using only one core

### ISSUE THREAD

**Issue by CaoE** [openvinotoolkit/openvino#15597]
##### System information (version)
torch: 1.13.1
python: 3.7.10
cpu: Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz
Set up env with
```
conda create -n test -y python==3.7.10 setuptools==58.0.4 
conda activate test
conda install intel-openmp
pip3 install torch torchvision
pip3 install openvino openvino-dev
```

##### Detailed description
Please see https://github.com/pytorch/pytorch/issues/91989.

**Comment by FionaZZ92** [comment]
I do not think it's OV problem. It's clear that import torch impact thread_num and core util. The solution already obvious, call "import torch" after openvino execution. Ask IPEX team to modify their application program or send request to IPEX or pytorch team.

**Comment by wangleis** [comment]
@CaoE OpenVINO release is based on TBB. But the following customer operation make OpenMP work in application process. 
```
export LD_PRELOAD=conda_env_home/lib/libiomp5.so # like /usr/local/envs/test/lib/libiomp5.so
export KMP_AFFINITY=granularity=fine,compact,1,0
```
```
import torch 
```
Now there are two options:
- Do not use OpenMP in customer application. for example, do not export libiomp5.so in environment.
- Ask support team to provide OpenMP based OpenVINO release package. But we do not guarantee the performance is same as TBB based OpenVINO release.

**Comment by CaoE** [comment]
@wangleis  Thanks for your detailed explanation and solutions. We will replay the feedback to the customer.
