### ISSUE TITLE
[Bug] The inference speed of .infer() in C++ API is much slower than that in Python API

### ISSUE THREAD

**Issue by zhangzhenzhouzzz** [openvinotoolkit/openvino#15625]
##### System information (version)
- OpenVINO => 2021.3,  2022.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2022
- Problem classification: Inference Speed
- Model name: Retinaface (mobilenet)

##### Detailed description
I used the OpenVINO 2021.3 to accelerate the model inference in Python and C++, and I found the inference speed in C++ is much slower than that in python. (device is CPU)
Then I tried some load config (KEY_CPU_THROUGHPUT_STREAMS and KEY_CPU_THREADS_NUM) in C++，but there was no considerable improvement.
Finally, I thought it might be due to the Openvino version, so I updated the version of OpenVINO to 2022.3 (API2.0) in the C++. But  there was still no considerable improvement.
It seems counterintuitive.

I dont know whats wrong. What else can I do to improve the inference speed in C++ to make it comparable in Python.

##### Steps to reproduce
In python (version 2021.3):
![image](https://user-images.githubusercontent.com/110588164/217986885-9071efb2-915c-48b8-b6d1-1d9a8d2022c4.png)
![image](https://user-images.githubusercontent.com/110588164/217986949-f9e4c78c-6fd6-45d6-895b-f7e11364e8e3.png)
In C++ (version 2022.3)
![image](https://user-images.githubusercontent.com/110588164/217987166-44b3e9b3-4b27-451c-9ce0-9d5dbb5c8fe1.png)
![image](https://user-images.githubusercontent.com/110588164/217987818-f7e7a5b1-b0a6-4a4c-a064-2d5c1244ef9a.png)

Thanks a lot.

**Comment by ilya-lavrenov** [comment]
@zhangzhenzhouzzz could you please provide full code snippets you used to perform benchmarking?
Have you tried to use benchmark_app to compare performance? we have both C++ and Python version.

Technically, C++ cannot be slower than Python API, because Python is implemented on top of C++.
Looks lile you are comparing different things, so that is why we are asking reproducers.

**Comment by zhangzhenzhouzzz** [comment]
> @zhangzhenzhouzzz could you please provide full code snippets you used to perform benchmarking? Have you tried to use benchmark_app to compare performance? we have both C++ and Python version.
> 
> Technically, C++ cannot be slower than Python API, because Python is implemented on top of C++. Looks like you are comparing different things, so that is why we are asking reproducers.
---------------------------------------------------------------------------------------------------------------------------------
Thanks for your reply!
I have checked it and am sure they are the same xml and bin files.
I haven't tried the benchmark_app, and I'll try it later. Thanks for reminding.
I totally understand that C++ should be faster than Python in theory. So I think there may be some issues in my code that caused the speed problem now. I'm still a beginner, can you help me check it?

Here is the C++ code snippet: (openvino 2022.3)
(Please ignore that I have not include preprocessing in openvino inference yet)
![image](https://user-images.githubusercontent.com/110588164/218384555-ce4fbed5-c218-47e1-af98-28f68b832cf3.png)
![image](https://user-images.githubusercontent.com/110588164/218384662-fee462bf-5d7a-4cb3-a4a3-5ad81000309d.png)

Here is the Python code snippet: (openvino 2021.3)
![image](https://user-images.githubusercontent.com/110588164/218385332-dc5b44d3-3919-4ffa-a664-4fb0884b86a3.png)
![image](https://user-images.githubusercontent.com/110588164/218384961-b71195bf-f1c6-40fc-8e64-a9f0bc488dd3.png)
![image](https://user-images.githubusercontent.com/110588164/218385147-57afa40b-d3c6-486f-b330-687c54cf1227.png)
![image](https://user-images.githubusercontent.com/110588164/218385487-da99dfa0-d30a-4e20-8cf9-1a1317ed9461.png)

Sorry for taking up your time and thanks again for your help.

**Comment by zhangzhenzhouzzz** [comment]
I find that I have made a soooooooooo stupid mistake.       (T＿T)       
I forgot to switch the 'Solution Configuration' to 'Release'. The speed test result is consistent with the theoretical result.
Very sorry for bothering you.
