### ISSUE TITLE
new raspbian release 2020.4 issue

### ISSUE THREAD

**Issue by natxopedreira** [openvinotoolkit/openvino#1564]
Sure i'm missing something... because this makes no sense, so please help.

Your product is great, i really like it and we really want to use it on production.... but is a nightmare trying to use it on rpi.

I tried the new release for raspbian and i still have the same behaviour, cpu usage doing inference on myriad is very high, one core 100% usage, same problem as described here [https://github.com/openvinotoolkit/openvino/issues/1330](https://github.com/openvinotoolkit/openvino/issues/1330)

Please correct me if i'm wrong, you can only do inference on rpi platform with myriad device and in the other issue says that there is a bug in the myriad plugin.... so do a new release and keep the same bug... why?

And i also tried to run examples, benchmark_app and object_detection_sample_ssd with various models downloaded from 
[https://download.01.org/opencv/2020/openvinotoolkit/2020.3/open_model_zoo/models_bin/](https://download.01.org/opencv/2020/openvinotoolkit/2020.3/open_model_zoo/models_bin/) and the most funny is that i get segfault errors and others trying to run samples with your provided models. Only hello_query_device worked 

What im missing?

**Comment by jgespino** [comment]
Hi @natxopedreira 

The 2020.4 release that was published this morning is not a new built, it was suppose to be released along with 2020.4 release on 7/14/2020. The bug you reported a few days ago regarding high CPU usage is still under investigation.

> Please correct me if i'm wrong, you can only do inference on rpi platform with myriad device and in the other issue says that there is a bug in the myriad plugin.... so do a new release and keep the same bug... why?

Correct, Openvino for Raspbian OS only supports the MYRIAD plugin.

> And i also tried to run examples, benchmark_app and object_detection_sample_ssd with various models downloaded from
https://download.01.org/opencv/2020/openvinotoolkit/2020.3/open_model_zoo/models_bin/ and the most funny is that i get segfault errors and others trying to run samples with your provided models. Only hello_query_device worked

You are using 2020.3 models with 2020.4 release, please use the 2020.4 models from here: 
https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/

I did not see any issues with benchmark_app or object_detection_sample using [face-detection-adas-0001](https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-adas-0001/FP16/). Let me know which models you are seeing issues with.

Regards,
Jesus

**Comment by natxopedreira** [comment]
@jgespino  for example this one is trowing a segfault on object_detection_sample
[https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-retail-0004/FP16/](https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-retail-0004/FP16/)

with my app im able to load an run models without problem but get one core cpu usage 100%, its only me?

**Comment by natxopedreira** [comment]
I also get a segfault with the model you mentioned [https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-adas-0001/FP16/](https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/face-detection-adas-0001/FP16 32bit/)

rpi 3b 
latest 32 bit raspbian 
5.4.51-v7+ kernel

**Comment by jgespino** [comment]
Hi @natxopedreira I'm not seeing a segfault with neither of those two models using the benchmark_app.

I do see one core bump up to 100% while executing benchmark_app -d MYRIAD -m face-detection-adas-0001

**Environment**
Raspberry Pi 4
l_openvino_toolkit_runtime_raspbian_p_2020.4.28
```
$uname -a
Linux raspberrypi 4.19.118-v7l+ # 1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
```

**Comment by natxopedreira** [comment]
yes is extrange, with my app i'm able to load models and doing inference but have the 100% core usage....

when you say "bump" do you mean a temporary usage?

what os are you running? you have the older kernel....

**Comment by jgespino** [comment]
@natxopedreira 

> when you say "bump" do you mean a temporary usage?

Only during inference, same as you reported.

> what os are you running? you have the older kernel....

I am using Raspbian GNU/Linux 10 (buster), should be the default kernel included.

**Comment by natxopedreira** [comment]
ok, thank you.

If is useful i can confirm the same behaviour (excesive CPU usage doing inference on myriad device) on a x86 ubuntu 18 intel nuc

**Comment by jgespino** [comment]
I see that too from issue #1330. If you don't mind, let's close this issue and keep the other one open to tracking CPU utilization while running inference on MYRIAD 

Regards,
Jesus

**Comment by dkurt** [comment]
Hi! Please try this fix: https://github.com/openvinotoolkit/openvino/pull/2030
