### ISSUE TITLE
Outdated & incomplete MacOS Installation Instructions

### ISSUE THREAD

**Issue by noajshu** [openvinotoolkit/openvino#1566]
Hi!

I am trying to install on MacOS 10.15.6 and running into two problems.

**Problem 1:**
The documentation here is out of date (only work up to MacOS 10.14):

[https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#additional-build-options-3
](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#additional-build-options-3
)

Here is the issue: For MacOS 10.14 the documentation stands. For 10.15 (which was released Oct 2019), `/Library/Frameworks/Python.framework/` does not exist. This is not too hard to fix and I propose the following update to the docs:

For MacOS >= 10.15 you can install python with Homebrew and then use the following flags instead:
```
-DPYTHON_EXECUTABLE=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/bin/python3.7m \
-DPYTHON_LIBRARY=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib \
-DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m 
```
If you install Python some other way besides Homebrew (e.g., compile Python from source), you could use these 2 commands to find where the dylib and include_dir are located, respectively:
```
find /usr/ -name 'libpython*m.dylib'
find /usr/ -type d -name python3.7m
```

I think this information would help save a lot of time for others who are trying to compile the Python API wrapper and run Python examples like myself.

**Problem 2:**
The python install documentation is incomplete. After following the instructions here:
[https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#additional-build-options-3
](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#additional-build-options-3
)and compiling with my modified build flags as explained above (and running `make install`) which is successful, I am still unable to run the python examples. Here is the output I get when running a Bert example from the model zoo:
```
/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/bin/python3.7m bert_question_answering_demo.py 
Traceback (most recent call last):
  File "bert_question_answering_demo.py", line 29, in <module>
    from openvino.inference_engine import IECore
ModuleNotFoundError: No module named 'openvino'
```
It seems that my python installation does not know anything about the openvino module, and strangely the python installation documentation does not mention any such module. It's not clear what I could do besides try `pip install openvino` but that does not find any such module. Typically with python modules there is a `setup.py` or similar file inside the repository that I can use to install the python module. But I have found no such module files inside the OpenVINO source code. So perhaps I am missing something, but it seems like a simple yet crucial step is missing from the MacOS installation documentation.

Thanks!
N

**Comment by jgespino** [comment]
Hi @noajshu 

Thanks for reaching out. As noted in the build instructions, these steps have only been validated on macOS* 10.14. There may be minimal path changes as you pointed out. Regarding the `ModuleNotFoundError: No module named 'openvino'`, try exporting the LD_LIBRARY_PATH and PYTHONPATH as @natxopedreira suggested.

To give you an idea, I exported my paths as follows on macOS 10.14:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Users/jesus/openvino/bin/intel64/Release/lib
export PYTHONPATH=$PYTHONPATH:/Users/jesus/openvino/bin/intel64/Release/lib/python_api/python3.6
```
I will pass this information on to the development team to improve the documentation.

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please feel free to re-open or start a new issue.
