### ISSUE TITLE
Program build failed for gpu-based demo, but cpu-based is okay

### ISSUE THREAD

**Issue by Bear-kai** [openvinotoolkit/openvino#1568]
>classification_sample_async.exe -i "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\car.png" -m "C:\Users\bk\Documents\Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1\FP32\squeezenet1.1.xml" -d GPU

[ INFO ] InferenceEngine:
        API version ............ 2.1
        Build .................. 2020.3.0-3467-15f2c61a-releases/2020/3
        Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\car.png
[ INFO ] Creating Inference Engine
        GPU
        clDNNPlugin version ......... 2.1
        Build ........... 2020.3.0-3467-15f2c61a-releases/2020/3

[ INFO ] Loading network files
[ INFO ] Preparing input blobs
[ WARNING ] Image is resized from (787, 259) to (227, 227)
[ INFO ] Batch size is 1
[ INFO ] Loading model to the device
[ ERROR ] Program build failed:

Note that my laptop is Lenovo T470P with Inter(R) HD Graphics 630 and NVIDIA GeForce 940MX. The driver version of HD is 22.20.16.4749 which is higher than the required 15.65

--------------------
Update : find that I can run my own model using the inference engine.
>exec_net = ie.load_network(network=net, device_name="CPU")  # Here GPU and CPU are both okay 
res = exec_net.infer(inputs={input_blob: images})

So, the problem may be caused by the demo itself.

**Comment by vladimir-paramuzov** [comment]
@Bear-kai Is it full error log? I don't see any detailed description of the error after `[ ERROR ] Program build failed:`.

**Comment by Bear-kai** [comment]
> @Bear-kai Is it full error log? I don't see any detailed description of the error after `[ ERROR ] Program build failed:`.

Yes, I have pasted the full error log above.

**Comment by maxlytkin** [comment]
@Bear-kai 
Are you able to run demo_squeezenet_download_convert_run.bat script in <openvino>\deployment_tools\demo\ directory with -d GPU parameter?

**Comment by maxlytkin** [comment]
Closing this case. Please feel free to re-open or start a new issue if additional assistance is needed.

**Comment by pobin6** [comment]
I meet the same problem,
are you fix the problem? @Bear-kai 

root@Storage:/home/Openvino/bin/intel64/Release# ./benchmark_app_elf -m S3D-model/nnx-test.xml -d GPU
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
        API version ............ 2.1
        Build .................. custom_2021.1-offline_8104247c99b58491b3a7bf1da8a8b487c1c4461c
        Description ....... API
[ INFO ] Device info:
        GPU
        clDNNPlugin version ......... 2.1
        Build ........... custom_2021.1-offline_8104247c99b58491b3a7bf1da8a8b487c1c4461c

[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for GPU device. Although the automatic selection usually provides a reasonable performance,but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 93.76 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
[ ERROR ] Program build failed:









root@Storage:/home/Openvino/bin/intel64/Release#

just failed, no log

**Comment by Bear-kai** [comment]
@pobin6 
Sorry, I can not remember the problem clearly. It seems that I did not solve it but let it go, since I could infer my own model normally. Maybe it originated from the demo itself, and you should try your own model too.
