### ISSUE TITLE
How can i use int8 QAT or PTQ on my own onnx model?

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#15702]
I have a onnx model, for openvino IR, how can I use int8 QAT or PTQ for it?

Is there any case or tutorial that I can refer to, 

Thank you very much

**Comment by AlexKoff88** [comment]
@sanbuphy, thanks for the inference. Please take a look at the new PTQ API available in the NNCF. You can find the documentation here: https://docs.openvino.ai/latest/basic_qauntization_flow.html. There is a dedicated tab for ONNX.

**Comment by sanbuphy** [comment]
> @sanbuphy, thanks for your interest. Please take a look at the new PTQ API available in the NNCF. You can find the documentation here: https://docs.openvino.ai/latest/basic_qauntization_flow.html. There is a dedicated tab for ONNX. Unfortunately, there is a typo in the document. Please treat an input to `nncf.quantize(model,...)` model as an ONNX representation. An end-to-end ONNX example is available [here](https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/onnx/mobilenet_v2/main.py).

Thank you very much. I will have a try.
