### ISSUE TITLE
[Bug] Memory leak ch_ppocr_server_v2.0_det

### ISSUE THREAD

**Issue by newwhiteuser** [openvinotoolkit/openvino#15732]
##### System information (version)
- OpenVINO = 2022.1
- Operating System / Platform = Windows 64 Bit
- Compiler = Visual Studio 2022
- Problem classification: inference model
- Framework: Paddle
- Model name: ch_ppocr_server_v2.0_det   --https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_det_infer.tar

##### Detailed description
When I was using openvino, I found that the memory kept increasing without decreasing and causing the program to crash. I commented the rest of the code and found that the memory was added while reasoning the model. How should I solve this problem? Thanks!

##### Steps to reproduce
![20230215190651](https://user-images.githubusercontent.com/86700534/219010992-b3339db5-7121-4181-a370-dba893ceb788.png)

**Comment by Iffa-Meah** [comment]
Could you help to clarify & provide these:
1. Source of your Paddle model
2. Which inferencing code you are using (OpenVINO sample/custom code)
3. Please help to provide your custom code (if you are using & if it's possible to be shared)
4. Method that you use to measure memory consumption

**Comment by wenjiew** [comment]
@xczhai to help take a look

**Comment by xczhai** [comment]
@newwhiteuser 
Hi, I try to test this model on the latest mater on Ubuntu. It works well. Also, I will try it on windows.
BTW, could you provide more info as @Iffa-Meah mentioned above in order to help address this issue?

**Comment by xczhai** [comment]
@newwhiteuser 
I didn't see the memory leak. Could you take a try using the code below or provide a reproductive snippet?
```cpp
#include <openvino/openvino.hpp>

int main(int argc, char* argv[]) {
    // step 1: init OpenVINO Runtime Core
    ov::Core core;

    // step 2: read a model
    std::shared_ptr<ov::Model> model = core.read_model("ch_ppocr_server_v2.0_det_infer/inference.pdmodel");

    // step 3: compile a molde
    ov::CompiledModel compiled_model = core.compile_model(model, "CPU");

    // step 4: create a tensor from image
    size_t element_nums = 1 * 3 * 224 * 224;
    float* in_ptr = static_cast<float*>(malloc(element_nums * sizeof(float)));
    ov::Tensor input_tensor = ov::Tensor(compiled_model.input().get_element_type(), { 1,3,224,224}, in_ptr);

    // step 5: create a inference request
    ov::InferRequest infer_request = compiled_model.create_infer_request();
    infer_request.set_input_tensor(input_tensor);
    infer_request.infer();

    // step 6: retrieve inference results
    const ov::Tensor& output_tensor = infer_request.get_output_tensor();
    ov::Shape output_shape = output_tensor.get_shape();
    float* out_ptr = output_tensor.data<float>();

    return 0;
}
```
Thanks.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
