### ISSUE TITLE
[Model Optimizer] - Is BF16 IR conversion supported from ONNX FP32 ?

### ISSUE THREAD

**Issue by lalith-mcw** [openvinotoolkit/openvino#15751]
Is BF16 conversion supported from ONNX FP32 ?

Currently could see only four data_types [f16,f32,float and half]

**Comment by andrei-kochin** [comment]
Hello @lalith-mcw,
Actually what Model Optimizer provides is just weights compression to FP16(half).
May I know the usecase to have IR precision in BF16? It should be enough to set inference precision to BF16 on plugin side.

Thanks!

**Comment by ilya-lavrenov** [comment]
Hi @lalith-mcw 

BF16 is turned on automatically during inference on platforms where the HW supports specific instruction set to provide performance benefits. E.g. https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_CPU.html#supported-inference-data-types

**Comment by andrei-kochin** [comment]
Answers provided. Closing.

@lalith-mcw feel free to re-open if more clarifications are needed.

**Comment by LinGeLin** [comment]
Although BF16 can be automatically used during inference, the process of converting FP32 inputs to BF16 can also be very time-consuming. So, is there a way to convert the model to BF16?

**Comment by LinGeLin** [comment]
![image](https://github.com/user-attachments/assets/7bbe555f-86cc-4199-bef4-242a9b25d92c)
@ilya-lavrenov

**Comment by mlukasze** [comment]
hey @LinGeLin 
are you familiar with [NNCF](https://github.com/openvinotoolkit/nncf)?

**Comment by LinGeLin** [comment]
> hey @LinGeLin are you familiar with [NNCF](https://github.com/openvinotoolkit/nncf)?

Not familiar, I just took over someone else's work. Will this solve my problem?

**Comment by EgorDuplensky** [comment]
> > ![image](https://private-user-images.githubusercontent.com/24861783/365886299-7bbe555f-86cc-4199-bef4-242a9b25d92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODE3MjksIm5iZiI6MTcyNTk4MTQyOSwicGF0aCI6Ii8yNDg2MTc4My8zNjU4ODYyOTktN2JiZTU1NWYtODZjYy00MTk5LWJlZjQtMjQyYTliMjVkOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE1MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YTdhNjczZmU3MTY0YjJkYmNjN2E3ZDk3ODM3M2Q1N2Q5ZWRjMDA1ZTViMDZkNWFmYTg4ZjdmOTZhMDUwNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qr6aGP7tiClgixDyz1IJqNxDpjEi_PI0PBx2_tucGWY) @ilya-lavrenov
> 
> @LinGeLin, I would suppose you are feeding f32 tensors to the model that is already running in bf16 mode. Is that correct? In this case f32 to bf16 conversion can happen inside without much control from your side, don't know how converting the whole model to bf16 will help because f32 to bf16 will remain on input tensors and bf16 to f32. Maybe more details are needed.
> 
> @EgorDuplensky, please help us to identify a potential issue inside CPU plugin with f32 to bf16 conversion.

Can just agree, the use case needs to be clarified.
@LinGeLin that it is basically impossible to get rid of FP32->BF16 Reorders for the Parameter inputs, unless your input data is already in BF16 format.
Is it the case for you, do you have your input data already in BF16 format?
Are your concerns only about an inference overhead a not compile_model stage?

**Comment by LinGeLin** [comment]
> > > <img alt="image" width="55.14204406738281" height="20.99431800842285" src="https://private-user-images.githubusercontent.com/24861783/365886299-7bbe555f-86cc-4199-bef4-242a9b25d92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODE3MjksIm5iZiI6MTcyNTk4MTQyOSwicGF0aCI6Ii8yNDg2MTc4My8zNjU4ODYyOTktN2JiZTU1NWYtODZjYy00MTk5LWJlZjQtMjQyYTliMjVkOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE1MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YTdhNjczZmU3MTY0YjJkYmNjN2E3ZDk3ODM3M2Q1N2Q5ZWRjMDA1ZTViMDZkNWFmYTg4ZjdmOTZhMDUwNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qr6aGP7tiClgixDyz1IJqNxDpjEi_PI0PBx2_tucGWY"> @ilya-lavrenov
> > 
> > 
> > @LinGeLin, I would suppose you are feeding f32 tensors to the model that is already running in bf16 mode. Is that correct? In this case f32 to bf16 conversion can happen inside without much control from your side, don't know how converting the whole model to bf16 will help because f32 to bf16 will remain on input tensors and bf16 to f32. Maybe more details are needed.，我假设您正在将 f32 张量输入到已经在 bf16 模式下运行的模型。这是正确的吗？在这种情况下，f32 到 bf16 的转换可以在内部进行，而无需您过多控制，不知道将整个模型转换为 bf16 有什么帮助，因为 f32 到 bf16 将保留在输入张量上，而 bf16 到 f32 将保留在输入张量上。也许需要更多细节。
> > @EgorDuplensky, please help us to identify a potential issue inside CPU plugin with f32 to bf16 conversion.，请帮助我们识别 CPU 插件中 f32 到 bf16 转换的潜在问题。
> 
> Can just agree, the use case needs to be clarified.只能同意，用例需要澄清。 @LinGeLin that it is basically impossible to get rid of FP32->BF16 Reorders for the Parameter inputs, unless your input data is already in BF16 format.基本上不可能摆脱参数输入的 FP32->BF16 重新排序，除非您的输入数据已经是 BF16 格式。 Is it the case for you, do you have your input data already in BF16 format?您的情况是否如此，您的输入数据是否已经是 BF16 格式？ Are your concerns only about an inference overhead and not compile_model() stage?您只关心推理开销而不是compile_model() 阶段吗？

The model is in FP32, and the inference precision is BF16. Using benchmark_app for pressure testing, it was found that Reorder takes up a significant amount of time, and the overall time is similar to when the inference precision is FP32. If the model is in BF16, theoretically, the type conversion part can be shifted to other places in the online service pipeline. This model is special; the overall FP32 input exceeds 100MB, with several large inputs having a shape of 1*900*2900, which takes up nearly 10MB.

**Comment by LinGeLin** [comment]
> > > <img alt="image" width="55.14204406738281" height="20.99431800842285" src="https://private-user-images.githubusercontent.com/24861783/365886299-7bbe555f-86cc-4199-bef4-242a9b25d92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODE3MjksIm5iZiI6MTcyNTk4MTQyOSwicGF0aCI6Ii8yNDg2MTc4My8zNjU4ODYyOTktN2JiZTU1NWYtODZjYy00MTk5LWJlZjQtMjQyYTliMjVkOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE1MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YTdhNjczZmU3MTY0YjJkYmNjN2E3ZDk3ODM3M2Q1N2Q5ZWRjMDA1ZTViMDZkNWFmYTg4ZjdmOTZhMDUwNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qr6aGP7tiClgixDyz1IJqNxDpjEi_PI0PBx2_tucGWY"> @ilya-lavrenov
> > 
> > 
> > @LinGeLin, I would suppose you are feeding f32 tensors to the model that is already running in bf16 mode. Is that correct? In this case f32 to bf16 conversion can happen inside without much control from your side, don't know how converting the whole model to bf16 will help because f32 to bf16 will remain on input tensors and bf16 to f32. Maybe more details are needed.
> > @EgorDuplensky, please help us to identify a potential issue inside CPU plugin with f32 to bf16 conversion.
> 
> Can just agree, the use case needs to be clarified. @LinGeLin that it is basically impossible to get rid of FP32->BF16 Reorders for the Parameter inputs, unless your input data is already in BF16 format. Is it the case for you, do you have your input data already in BF16 format? Are your concerns only about an inference overhead and not compile_model() stage?

The model is in FP32, and the inference precision is BF16. Using benchmark_app for pressure testing, it was found that Reorder takes up a significant amount of time, and the overall time is similar to when the inference precision is FP32. If the model is in BF16, theoretically, the type conversion part can be shifted to other places in the online service pipeline. This model is special; the overall FP32 input exceeds 100MB, with several large inputs having a shape of 1*900*2900, which takes up nearly 10MB.

**Comment by slyalin** [comment]
If you set BF16 as inference precision, then it should be a signal for the plugin to convert as much as possible to BF16 inside the model graph. @EgorDuplensky, please confirm. In the same time precision of model inputs and outputs are not affected, because the inference precision is not allowed to change the model signature. You can use pre-processin API described here https://docs.openvino.ai/2024/openvino-workflow/running-inference/optimize-inference/optimize-preprocessing/preprocessing-api-details.html to try to convert inputs/outputs to bf16 as well if you see it more natural flow in your case. Especially if you see evidence that you can do that conversion faster outside of OV. I would consider slow f32 to bf16 conversion in this case as a bug in OpenVINO.

**Comment by LinGeLin** [comment]
> @LinGeLin, if you set BF16 as inference precision, then it should be a signal for the plugin to convert as much as possible to BF16 inside the model graph. @EgorDuplensky, please confirm. In the same time precision of model inputs and outputs are not affected, because the inference precision is not allowed to change the model signature. You can use pre-processing API described here https://docs.openvino.ai/2024/openvino-workflow/running-inference/optimize-inference/optimize-preprocessing.html to try to convert inputs/outputs to bf16 as well if you see it more natural flow in your case. Especially if you see evidence that you can do that conversion faster outside of OV. I would consider slow f32 to bf16 conversion in this case as a bug in OpenVINO.

I used OVC for the conversion, and after looking at the link you provided, I didn't quite understand it. It would be even better if there was an example of converting a saved_model into an OV model.

**Comment by EgorDuplensky** [comment]
> > > > <img alt="image" width="55.14204406738281" height="20.99431800842285" src="https://private-user-images.githubusercontent.com/24861783/365886299-7bbe555f-86cc-4199-bef4-242a9b25d92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODE3MjksIm5iZiI6MTcyNTk4MTQyOSwicGF0aCI6Ii8yNDg2MTc4My8zNjU4ODYyOTktN2JiZTU1NWYtODZjYy00MTk5LWJlZjQtMjQyYTliMjVkOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE1MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YTdhNjczZmU3MTY0YjJkYmNjN2E3ZDk3ODM3M2Q1N2Q5ZWRjMDA1ZTViMDZkNWFmYTg4ZjdmOTZhMDUwNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qr6aGP7tiClgixDyz1IJqNxDpjEi_PI0PBx2_tucGWY"> @ilya-lavrenov
> > > 
> > > 
> > > @LinGeLin, I would suppose you are feeding f32 tensors to the model that is already running in bf16 mode. Is that correct? In this case f32 to bf16 conversion can happen inside without much control from your side, don't know how converting the whole model to bf16 will help because f32 to bf16 will remain on input tensors and bf16 to f32. Maybe more details are needed.
> > > @EgorDuplensky, please help us to identify a potential issue inside CPU plugin with f32 to bf16 conversion.
> > 
> > 
> > Can just agree, the use case needs to be clarified. @LinGeLin that it is basically impossible to get rid of FP32->BF16 Reorders for the Parameter inputs, unless your input data is already in BF16 format. Is it the case for you, do you have your input data already in BF16 format? Are your concerns only about an inference overhead and not compile_model() stage?
> 
> The model is in FP32, and the inference precision is BF16. Using benchmark_app for pressure testing, it was found that Reorder takes up a significant amount of time, and the overall time is similar to when the inference precision is FP32. If the model is in BF16, theoretically, the type conversion part can be shifted to other places in the online service pipeline. This model is special; the overall FP32 input exceeds 100MB, with several large inputs having a shape of (1,900,2900), which takes up nearly 10MB.

Could you please explicitly clarify, in which precision you have your data which you are going to feed to the model. This is most important question here.
Basically, there are two alternatives:
1) You have your input data already in BF16 precision, then you need to tell that to the model (because the model expects FP32 input data by default, even if `inference_precision` is set to BF16), and this can be done by means of Preprocessing API, which @slyalin mentioned.
2) You have your input data in FP32 precision. Then, when you have `inference_precision` configured to BF16, at some point we need to convert FP32 input data to BF16 tensor. And this is done by means of Reorder operations you highlighted in the screenshot.

If you are thinking about the possible optimization, where you have the whole model in BF16 format, but your data is still in FP32, and you are going to perform the conversion outside the model - this most likely will be even slower.
