### ISSUE TITLE
[Bug] custom shape infer function <function MatMul.infer at 0x0000024CFF9BCC18> 

### ISSUE THREAD

**Issue by rico22github** [openvinotoolkit/openvino#15867]
Hi, everyone.  I am using the Intel OpenVINO 2022.1 on Windows OS for my project. I am trying to convert the input data shape of vgg16 CNN model from [1,3,224,224] to [2,3,300,300]. I tried to use the following command:

 

mo --input_model <path_to_model_directory>\vgg16.caffemodel --input data --input_shape [2,3,300,300] -o <path_to_vgg16_fp32_optimized_model_directory>

I went through the online documentation and followed every step. However, it showed me errors, such as:

OpenVINO runtime found in: C:\Program Files (x86)\Intel\openvino_2022\python\python3.7\openvino
OpenVINO runtime version: 2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version: 2022.1.0-7019-cdb9bec7210-releases/2022/1
[ ERROR ] Cannot infer shapes or values for node "fc6/WithoutBiases".
[ ERROR ] MatMul input shapes are incorrect. COL_INDEX_DIMs are not equal. Node: fc6/WithoutBiases. Shapes: [masked_array(data=[ 2, 51200],
mask=False,
fill_value=-1000000007,
dtype=int64), masked_array(data=[25088, 4096],
mask=False,
fill_value=-1000000007,
dtype=int64)]
[ ERROR ]
[ ERROR ] It can happen due to bug in custom shape infer function <function MatMul.infer at 0x0000024CFF9BCC18>.
[ ERROR ] Or because the node inputs have incorrect values/shapes.
[ ERROR ] Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ] Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ] Exception occurred during running replacer "REPLACEMENT_ID" (<class 'openvino.tools.mo.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "fc6/WithoutBiases" node.
For more information please refer to Model Optimizer FAQ, question #38. ([https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=...](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38))

I don't know what's happening.  The first error is 'Cannot infer shapes or values for node "fc6/WithoutBiases". What does it mean? OpenVINO supports Fully Connected layers, doesn't it? Can you guys please help me out? Thanks!

**Comment by andrei-kochin** [comment]
@rico22github  thanks for reaching OpenVINO!

Error means that there might be some bug in calculating shapes inside Model Optimizer.
Could you please try same model on 2022.3?

**Comment by ilya-lavrenov** [comment]
I suppose the error is because of VGG is not reshapable model (it's trained for specific image sizes only), so you cannot set different shape via Model Optimizer.
You have to preprocess your image on the application side before running Inference.

OpenVINO has an API to built in your preprocessing into the model, see the following [guide ](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Preprocessing_Details.html#resizing-image)

**Comment by rico22github** [comment]
> @rico22github thanks for reaching OpenVINO!
> 
> Error means that there might be some bug in calculating shapes inside Model Optimizer. Could you please try same model on 2022.3?

Thank you, Andrei.

**Comment by rico22github** [comment]
> I suppose the error is because of VGG is not reshapable model (it's trained for specific image size only), so you cannot set different shape via Model Optimizer. You have to preprocess your image on the application side before running Inference.
> 
> OpenVINO has an API to build in your preprocessing into the model, see the following [guide ](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Preprocessing_Details.html#resizing-image).
> 
> We also demonstrate how to embed preprocessing in our [samples](https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/hello_classification/main.cpp):
> 
> https://github.com/openvinotoolkit/openvino/blob/f41c75b965712da3b66e7059f1a67c28a6362406/samples/cpp/hello_classification/main.cpp#L73-L91

Thank you, Ilya. I am using the benchmark_app and the classification_benchmark_app. So, I have to change the shape of these applications. Then, build them again before running my model with it. Am I right, Ilya?

**Comment by ilya-lavrenov** [comment]
> So, I have to change the shape of these applications

You need to add preprocessing to the model, rebuild app and pass your model as an input to the app.
It will automatically resize image from `picture shape` to `model input shape`

**Comment by hbalasu1** [comment]
Hi @rico22github is your issue resolved?
