### ISSUE TITLE
could not download model open-closed-eye

### ISSUE THREAD

**Issue by xlla** [openvinotoolkit/openvino#1589]
host: ubuntu 18.04 LTS
openvino:2020.2.120
python: 3.6.9

propose: I want download open-closed-eye-0001, in FP16 format.

I use command:
`python3 /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py  --output ~/ml/models --cache_dir /downloads/openvino_cache --precisions FP16 --name open`

then got error:
<pre>
error: unrecognized arguments: opencv_bug.cpp openvino_models openvino-models.tar.gz openvino.sh
usage: downloader.py [-h] [--name PAT[,PAT...]] [--list FILE.LST] [--all]
                     [--print_all] [--precisions PREC[,PREC...]] [-o DIR]
                     [--cache_dir DIR] [--num_attempts N]
                     [--progress_format {text,json}]

optional arguments:
  -h, --help            show this help message and exit
  --name PAT[,PAT...]   download only models whose names match at least one of
                        the specified patterns
  --list FILE.LST       download only models whose names match at least one of
                        the patterns in the specified file
  --all                 download all available models
  --print_all           print all available models
  --precisions PREC[,PREC...]
                        download only models with the specified precisions
                        (actual for DLDT networks)
  -o DIR, --output_dir DIR
                        path where to save models
  --cache_dir DIR       directory to use as a cache for downloaded files
  --num_attempts N      attempt each download up to N times
  --progress_format {text,json}
                        which format to use for progress reporting

</pre>

then I use command, 
`python3 /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py  --output ~/ml/models --cache_dir /downloads/openvino_cache --precisions FP16 --name open-*`

then got error:
<pre>
No matching models: "open-*"
</pre>

then I use command, 
`python3 /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/downloader.py  --output ~/ml/models --cache_dir /downloads/openvino_cache --precisions FP16 --name open_*`

then got error:
<pre>
No matching models: "open_closed_eye.onnx"
</pre>

**Comment by xlla** [comment]
Sorry , I found these is no folder open-closed-eye-0001 in open_model_zoo at all.

**Comment by brmarkus** [comment]
I have OpoenVINO 2020.4 (2020.4.287) installed under Ubuntu and can find the "open-closed-eye" model like this:

```
$> /opt/intel/openvino/deployment_tools/tools/model_downloader/downloader.py --print_all | grep -i open
open-closed-eye-0001
```

Would it be possible for you to update to a newer OpenVINO version?
