### ISSUE TITLE
why  AFFINITY": "NUMA can speed up  CPU  when i using multiple models inference 

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#15908]
https://github.com/openvinotoolkit/openvino/issues/15730

Based on this issue, I tried the new method, the effect was not good at first, until I changed a few parameters, I found an amazing 5%~10% improvement!!

But I'm still curious how it's done, it's like magic. I observed the utilization rate of this cpu running process (by htop)，When I use other methods, the average CPU usage is 80%,But when I use NUMA and adjust the appropriate parameters, the average CPU utilization is 53%~54%, and I find that different logical cores are used in turn (sometimes 1/3 to 80%, the other core to 30%; and sometimes 2/4 to 80%. 1/3 to 30%),the speed at this time is surprisingly fast.

Can you tell me some possible reasons, or are there any recommended materials, books, documents to read, thank you very much for your help.

**Comment by sanbuphy** [comment]
And I found that this effect is only useful when there are many pictures（>=15）. For a single process task (such as ocr, single detection and multiple recognition) it is actually  multi-thread onnxruntime is the fastest , but as the task increases (dozens of The throughput of 100 sheets) The acceleration effect of openvino can really be displayed

**Comment by wangleis** [comment]
@sanbuphy When you load multiple network modes and do interface at the same time, using NUMA affinity will schedule all inference workloads to all CPU processors by the OS. Utilization of CPU is affected not only by OpenVINO settings for each model but also by model topology and input data parallelism, etc.

Please learn more performance tuning at https://docs.openvino.ai/latest/ovms_docs_performance_tuning.html
