### ISSUE TITLE
Did not get the expected number of literals for a constant of shape

### ISSUE THREAD

**Issue by Asthestarsfalll** [openvinotoolkit/openvino#15923]
Hi, I'm developing the frontend operation, it occurs error when concatenating `OutputVector`.
```
C++ exception with description "Check 'false' failed at src/frontends/paddle/src/frontend.cpp:65:
FrontEnd API failed with OpConversionFailure: :
Fail to convert set_value Exception Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at src/core/include/openvino/op/constant.hpp:55:
While validating node 'v0::Constant Constant_6713 () -> (i64[1])' with friendly_name 'Constant_6713':
Did not get the expected number of literals for a constant of shape [1] (got 3, expected 1).
```
What does the `number of literals for a constant of shape` stand for?

**Comment by meiyang-intel** [comment]
> Hi, I'm developing the frontend operation, it occurs error when concatenating `OutputVector`.
> 
> ```
> C++ exception with description "Check 'false' failed at src/frontends/paddle/src/frontend.cpp:65:
> FrontEnd API failed with OpConversionFailure: :
> Fail to convert set_value Exception Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at src/core/include/openvino/op/constant.hpp:55:
> While validating node 'v0::Constant Constant_6713 () -> (i64[1])' with friendly_name 'Constant_6713':
> Did not get the expected number of literals for a constant of shape [1] (got 3, expected 1).
> ```
> 
> What does the `number of literals for a constant of shape` stand for?

The error message mean that the shape of 'Constant' is not matched with the shape of values assigning to 'Constant'. Seems it happens when converting 'set_value'. Do you mind share your code?

**Comment by Asthestarsfalll** [comment]
Hi, @ilya-lavrenov 
I have a funtion to process minus indices:
```c++
Output<Node> handle_minus_index(const OutputVector& node, const Output<Node>& dim) {
    const auto zero = default_opset::Constant::create(node[0].get_element_type(), {1}, {0});
    const auto concat_node = std::make_shared<default_opset::Concat>(node, 0);
    const auto mask = std::make_shared<default_opset::Less>(concat_node, zero);
    const auto res = std::make_shared<default_opset::Add>(node, dim);
    return std::make_shared<default_opset::Select>(mask, res, node);
}
```
It's called from here:
```c++
const auto dim_node = default_opset::Constant::create(element::i64, {1}, {dims});
auto starts = handle_minus_index(node.get_ng_inputs("StartsTensorList"), dim_node);
auto ends = handle_minus_index(node.get_ng_inputs("EndsTensorList"), dim_node)
```
The shape of each elments in StartsTensorList or EndsTensorList are 1

**Comment by rkazants** [comment]
Hi @Asthestarsfalll,

I see a few bugs in your code:
you are passing `OutputVector` as operand to `Add`. `Add` expects both `Output<Node>` operands. The same issue is to create `Select` operation:

```
    const auto res = std::make_shared<default_opset::Add>(node, dim);
    return std::make_shared<default_opset::Select>(mask, res, node);
```

Please check a size of `dims` or what is it:

```
const auto dim_node = default_opset::Constant::create(element::i64, {1}, {dims});
```

Best regards,
Roman

**Comment by Asthestarsfalll** [comment]
Hi, @rkazants 
Sorry, I uploaded the wrong codes. I am used to coding in the remote evironment, the above codes was written with temporariness in local. So actually there is no bug with other lines but `Concat`.

**Comment by Asthestarsfalll** [comment]
![2023-02-25_17-20](https://user-images.githubusercontent.com/72954905/221349287-30faa206-46c1-49f2-b7f9-2ea9c5317b92.png)

**Comment by Asthestarsfalll** [comment]
Oh! I misread `Constant` as `Concat`😭
