### ISSUE TITLE
[Bug]sample/cpp/build_sample.sh Failed to find 'gflags' library using 'nothreads_static' component

### ISSUE THREAD

**Issue by KiwiHana** [openvinotoolkit/openvino#15985]
##### System information (version)

 OpenVINO => 2022.3 from openvino download 
- https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html
- Operating System / Platform => Ubuntu22.04
- sample/cpp/build_sample.sh
-->

##### Detailed description
~/Downloads/l_openvino_toolkit_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64$ source setupvars.sh
[setupvars.sh] OpenVINO environment initialized
~/Downloads/l_openvino_toolkit_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64$ cd /home/a380/Downloads/l_openvino_toolkit_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64/samples/cpp/
~/Downloads/l_openvino_toolkit_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64/samples/cpp$ ./build_samples.sh

Setting environment variables for building samples...
[setupvars.sh] OpenVINO environment initialized
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:135 (message):
  Failed to find 'gflags' library using 'nothreads_static' component

-- Configuring incomplete, errors occurred!
See also "/home/openvino_cpp_samples_build/CMakeFiles/CMakeOutput.log".
Error on or near line 96; exiting with status 1

**Comment by KiwiHana** [comment]
On Debian/Ubuntu Linux, gflags can be installed using the following command:

sudo apt-get install libgflags-dev

**Comment by KiwiHana** [comment]
New Error
l_openvino_toolkit_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64/samples/cpp$ ./build_samples.sh

Setting environment variables for building samples...
[setupvars.sh] OpenVINO environment initialized
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- gflags (2.2.2) is found at /usr/lib/x86_64-linux-gnu/cmake/gflags using 'nothreads_static' component
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Error at benchmark_app/CMakeLists.txt:67 (message):
  Failed to find / build nlohmann_json library


-- Configuring incomplete, errors occurred!
See also "/home/openvino_cpp_samples_build/CMakeFiles/CMakeOutput.log".
Error on or near line 96; exiting with status 1

**Comment by KiwiHana** [comment]
cd /home/l_openvino_toolkit_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64/install_dependencies/
sudo ./install_openvino_dependencies.sh

**Comment by KiwiHana** [comment]
~/l_openvino_toolkit_ubuntu20_2022.3.0.9052.9752fafe8eb_x86_64/samples/cpp$ ./build_samples.sh
……
/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_queue_base_v3::internal_pop(void*)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [speech_sample/CMakeFiles/speech_sample.dir/build.make:120: intel64/Release/speech_sample] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:657: speech_sample/CMakeFiles/speech_sample.dir/all] Error 2
[ 84%] Linking CXX executable ../intel64/Release/benchmark_app
……
……
collect2: error: ld returned 1 exit status
gmake[2]: *** [benchmark_app/CMakeFiles/benchmark_app.dir/build.make:168: intel64/Release/benchmark_app] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:469: benchmark_app/CMakeFiles/benchmark_app.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
Error on or near line 97; exiting with status 1

**Comment by ilya-lavrenov** [comment]
> On Debian/Ubuntu Linux, gflags can be installed using the following command:
> 
> sudo apt-get install libgflags-dev

Once you have downloaded and extracted OpenVINO archive, you need to install dependencies via:
```
./install_dependencies/install_openvino_dependencies.sh
```
As stated in [documentation](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_from_archive_linux.html) in step 5.
