### ISSUE TITLE
[Bug] Missed LICENSE file in openvino-dev 2022.3.0 package

### ISSUE THREAD

**Issue by mikhailk62** [openvinotoolkit/openvino#16026]
- OpenVINO=> 2022.3.0 release (https://pypi.org/project/openvino-dev/#files)
- Operating System / Platform =>Ubuntu
- Problem classification => Missed license file

##### Detailed description
When analyzing the latest openvino-dev package, we found that the package is missing a license file

##### Steps to reproduce
You need to download the latest openvino-dev 2022.3.0 package from PyPi (https://pypi.org/project/openvino-dev/#files) and check the **openvino_dev-2022.3.0.dist-info** folder

**Comment by Aznie-Intel** [comment]
Hi @mikhailk62, Thank you for reporting. We will escalate this to our development team.

**Comment by hbalasu1** [comment]
We have escalated this case to the development team. Ref 105255
