### ISSUE TITLE
what is the difference between throughput and latency.

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#16038]
Hello, I recently tested the quantization tool of openvino, and then found a strange place.
I used this demo：https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/110-ct-segmentation-quantize

 but I found that when the average and maximum delays are both small, why is the total throughput less than the latter with such a large delay?

nncf:
![image](https://user-images.githubusercontent.com/96160062/222322871-6bb24e6c-1efb-4c67-9b28-83134ca7cee7.png)

not nncf:
![image](https://user-images.githubusercontent.com/96160062/222322901-38f8e141-a016-484c-a852-55a1ccf9d2ee.png)

Thank you very much.

**Comment by wangleis** [comment]
@sanbuphy Latency in log indicates inference time for one input. Throughput in log indicates the number of inputs inferred per second. 

The reason for the difference you shared is that [110-ct-segmentation-quantize-nncf.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize-nncf.ipynb) and [110-ct-segmentation-quantize.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize.ipynb) work in different modes.

- [110-ct-segmentation-quantize-nncf.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize-nncf.ipynb) run inference on the CPU in synchronous mode as shown in the code below. Inputs are inferred one by one only on the CPU.
```
device = "CPU"
# Benchmark FP32 model
! benchmark_app -m $fp32_ir_path -d $device -t 15 -api sync
# Benchmark INT8 model
! benchmark_app -m $int8_ir_path -d $device -t 15 -api sync
```

- [110-ct-segmentation-quantize.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize.ipynb) run inference on the GPU and CPU in asynchronous mode as shown in the code below. Inputs are inferred in parallel on the GPU and CPU if GPU is available on platform. 
```
# By default, benchmark on MULTI:CPU,GPU if a GPU is available, otherwise on CPU.
ie = Core()
device = "MULTI:CPU,GPU" if "GPU" in ie.available_devices else "CPU"
# Benchmark FP16 model
! benchmark_app -m $ir_path -d $device -t 15 -api async
# Benchmark INT8 model
! benchmark_app -m $compressed_model_path -d $device -t 15 -api async
```

**Comment by sanbuphy** [comment]
> @sanbuphy Latency in log indicates inference time for one input. Throughput in log indicates the number of inputs inferred per second.
> 
> The reason for the difference you shared is that [110-ct-segmentation-quantize-nncf.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize-nncf.ipynb) and [110-ct-segmentation-quantize.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize.ipynb) work in different modes.
> 
> * [110-ct-segmentation-quantize-nncf.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize-nncf.ipynb) run inference on the CPU in synchronous mode as shown in the code below. Inputs are inferred one by one only on the CPU.
> 
> ```
> device = "CPU"
> # Benchmark FP32 model
> ! benchmark_app -m $fp32_ir_path -d $device -t 15 -api sync
> # Benchmark INT8 model
> ! benchmark_app -m $int8_ir_path -d $device -t 15 -api sync
> ```
> 
> * [110-ct-segmentation-quantize.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/110-ct-segmentation-quantize/110-ct-segmentation-quantize.ipynb) run inference on the GPU and CPU in asynchronous mode as shown in the code below. Inputs are inferred in parallel on the GPU and CPU if GPU is available on platform.
> 
> ```
> # By default, benchmark on MULTI:CPU,GPU if a GPU is available, otherwise on CPU.
> ie = Core()
> device = "MULTI:CPU,GPU" if "GPU" in ie.available_devices else "CPU"
> # Benchmark FP16 model
> ! benchmark_app -m $ir_path -d $device -t 15 -api async
> # Benchmark INT8 model
> ! benchmark_app -m $compressed_model_path -d $device -t 15 -api async
> ```

I ignored the benchmark mode, thank you
