### ISSUE TITLE
What data input is used for Openvino's benchmark testing?

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#16041]
As the title suggests, I am curious how benchmark creates different data to achieve different benchmark tests?

thank you very much.

**Comment by Wovchena** [comment]
Please specify what you mean by benchmark. This could mean benchmarking performance tests. Or just smoke tests for [benchmark_app](https://github.com/openvinotoolkit/openvino/tree/master/samples/cpp/benchmark_app).

Assuming you are interested in latter. I'm not aware of all tests. For smoke tests in most cases only one image is used

**Comment by sanbuphy** [comment]
> 



> Please specify what you mean by benchmark. This could mean benchmarking performance tests. Or just smoke tests for [benchmark_app](https://github.com/openvinotoolkit/openvino/tree/master/samples/cpp/benchmark_app).
> 
> Assuming you are interested in latter. I'm not aware of all tests. For smoke tests in most cases only one image is used

yes,I mean [benchmark_app](https://github.com/openvinotoolkit/openvino/tree/master/samples/cpp/benchmark_app).

Thanks!
