### ISSUE TITLE
Do I need fix the CPU frequency of my computer when I test the benchmark？

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#16046]
Do I need to fix the CPU frequency of my computer when I test the benchmark on my computer? Or does the benchmark app take into account frequency reduction?

Running calculation-type tasks on a home computer for a long time will inevitably lead to frequency reduction.

Thank you very much.

**Comment by ilya-lavrenov** [comment]
> does the benchmark app take into account frequency reduction

No, it does not take.

If you want stable results, you have to fix frequencies.

**Comment by sanbuphy** [comment]
> > does the benchmark app take into account frequency reduction
> 
> No, it does not take.
> 
> If you want stable results, you have to fix frequencies.

get it, thank you very much.
