### ISSUE TITLE
CPU plug-in doesn't support Squeeze operation with dynamic rank    p2o.Squeeze.7

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#16077]
Hello, I would like to ask about the p2o.Squeeze.7 op question . when I ran the benchmark app, I encountered an error like the title, and then I found that it was just a small operator in the nms stage. How can I modify the onnx calculation graph to make it support it? Or do I still just have to crop out the NMS? I want to perform subsequent NNCF quantization operations

![image](https://user-images.githubusercontent.com/96160062/222683597-aacb03f8-603f-4593-bb88-46d7fd601f69.png)
![image](https://user-images.githubusercontent.com/96160062/222683687-7bf124d6-7e9c-4caa-b48b-5f0668f62e6a.png)

thank you very much.

**Comment by AlexKoff88** [comment]
Hi @sanbuphy, thanks for your interest in OpenVINO and NNCF. Can you please describe the workflow? What kind of model do you start from (Torch, ONNX, etc.)? And what do you want to accomplish (e.g. quantize the model)? Any details about the model would be beneficial.

**Comment by sanbuphy** [comment]
> Hi @sanbuphy, thanks for your interest in OpenVINO and NNCF. Can you please describe the workflow? What kind of model do you start from (Torch, ONNX, etc.)? And what do you want to accomplish (e.g. quantize the model)? Any details about the model would be beneficial.

OK, I have already sent an email that contains the onnx file.

**Comment by slyalin** [comment]
@sanbuphy, technically, a combination of dynamic shapes and ONNX Squeeze operation may really lead to dynamic rank that is not supported in CPU plugin. And we have such place in the model. I see that input shape for that Squeeze is [1, ?, 1], so it is unclear whether ? can be 1 or not -- it is dynamic, so Squeeze should remove all 1 elements from the shape and the result can be 1D or 0D (scalar) tensor, which means the real rank is unknown at the moment of compilation. Probably this is an artifact of paddle-to-onnx conversion that inappropriately generate Squeeze without axes input.

Cannot say for sure (it requires more deep analysis of the model) if it is unavoidable in that particular part of the model, but it looks to be very localized piece of the model as after two operations we have Reshape that makes rank static again. Anyway, if you have successfully converted the model from paddle directly, it solves your issue.

**Comment by slyalin** [comment]
@itikhono, this is an example of "soft" dynamic rank that we can try to eliminate by applying some not very complex transformation to avoid CPU plugin trying to resolve it on its side.

**Comment by sanbuphy** [comment]
> @sanbuphy, technically, a combination of dynamic shapes and ONNX Squeeze operation may really lead to dynamic rank that is not supported in CPU plugin. And we have such place in the model. I see that input shape for that Squeeze is [1, ?, 1], so it is unclear whether ? can be 1 or not -- it is dynamic, so Squeeze should remove all 1 elements from the shape and the result can be 1D or 0D (scalar) tensor, which means the real rank is unknown at the moment of compilation. Probably this is an artifact of paddle-to-onnx conversion that inappropriately generate Squeeze without axes input.
> 
> Cannot say for sure (it requires more deep analysis of the model) if it is unavoidable in that particular part of the model, but it looks to be very localized piece of the model as after two operations we have Reshape that makes rank static again. Anyway, if you have successfully converted the model from paddle directly, it solves your issue.

Thank you very much. Yes, I have successfully converted the model from paddle directly, it can be a particular case that avoid the other model meet the same question .
