### ISSUE TITLE
[Bug] c++ is not good as python in detecting person with yolov8 int8 model

### ISSUE THREAD

**Issue by dchld** [openvinotoolkit/openvino#16148]
- OpenVINO=> :2022.3
- Operating System / Platform =>windows
- Compiler => Visual Studio 2019 and  Visual Studio 2022
- Problem classification => object detecting

##### Detailed description
 I get a int8 model(yolov8s.xml, yolov8s.bin) by following the steps in [notebooks](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks)/230-yolov8-optimization)( replacing yolov8n with yolov8s).
When I reference a video(or images), I get perfect result with python( in notebook230 or with a standalone python script file).  But when I reference the same video or images in Visual Studio with the same int8 model, some persons can not be detect out, i.e, 3 persons can be detected out with python, and only 1 or 2 persons can be detect out with Visual Studio 2019(2022).

The following is some code in VS:
// initialize
    
     ov::Core core;
	m_pModel = core.read_model("int8\\yolov8s.xml");
	if (NULL == m_pModel)
		return -1;	 
	ov::PartialShape tensor_shape = {1,3, 640,640 };//
        m_pModel->reshape(tensor_shape);
	ov::CompiledModel compiled_model = core.compile_model(m_pModel, "CPU");
	m_InferRequest = compiled_model.create_infer_request();
	CYolovCbObj obj(i, this);
	m_InferRequest.set_callback(std::bind(&CYolov5CbObj::OnYolovCallback, obj, std::placeholders::_1));

// reference

	double dFact = (double)1280 / matIn.cols;
	cv::Mat resizeFrame = matIn;
	cv::resize(mat, resizeFrame, cv::Size(), dFact, dFact, 3); // P1920-->P720
	int imgW = m_InputShape[2]; // 640
	int imgH = m_InputShape[3]; // 640
	cv::Mat modelInput = resizeFrame;
	modelInput = formatToSquare(resizeFrame);
	cv::Mat  srcimg = modelInput;
	ov::Tensor input_tensor = m_InferRequest.get_input_tensor();
	float* pData = input_tensor.data<float>();
	cv::Mat blob;
	cv::dnn::blobFromImage(srcimg, blob, 1.0 / 255.0, cv::Size(640, 640), cv::Scalar(), false, false);
	memcpy(pData, blob.data, imgW * imgH * 3 * 4);
	m_InferRequest.start_async(); 
 
At where I am wrong? Why C is not good as python?

**Comment by yury-gorbachev** [comment]
Not entirely sure but image in OpenCV has BGR format (when you read it via opencv) while in PIL (which is used in notebook I believe) is RGB. Model expects RGB.
So might be good to check if you are feeding correct channel order. 
Sometimes things like that result in model quality reduction but not complete failure and it's hard to troubleshoot.

**Comment by rkazants** [comment]
Hi @dchld,

In order to localize a problem (in using CV or OV), I can advice to dump numpy array (that you feed into infer request) into the file in your reference Python code and read this dump to feed in C++. This way you can compare this dump with your current dump in C++ and try inference with Python dump.

Best regards,
Roman

**Comment by ilya-lavrenov** [comment]
@dchld if you can share your working python-based pipeline, it can be helpful to understand where you made the difference in your C++ code

**Comment by dchld** [comment]
I got the reason.
The initialize and reference C++ codes are correct. 
But in postprocess, the call to  cv::dnn::NMSBoxes, I gave wrong values in the first "<Rect>& bboxes" parameter. So some box lost.
