### ISSUE TITLE
How can i control NNCF quantization error

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#16157]
Hi . I am using NNCF to quantize the model PP-YOLOE+_s（https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/configs/ppyoloe）. I got the quantized results and I can run roughly correct inference results, but when I tested the MAP, I found that the MAPhas decreased by 10%, from 0.41 to 0.378. 

I want to know how to make it don't drop too much.I I calculated the MAP with reference to this example: 
https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/226-yolov7-optimization

I can prepare a file that reproduces the results if needed.

Thank you very much.

**Comment by sanbuphy** [comment]
> Hi, @sanbuphy!
> 
> Sorry for the delayed response. You probably found it but just in case, we have samples that show "quantization with accuracy control": https://github.com/openvinotoolkit/nncf/tree/develop/examples/post_training_quantization/openvino. This feature is available for OpenVINO IR only. We are planning to expand it to other backends including ONNX and PyTorch.

Hi, @AlexKoff88 , thank you for your help. 

I am currently trying to use it, but I am not clear on the difference between calibration_dataset and validation_dataset in quantize_with_accuracy_control.

I'm not sure if the two datasets can be the same. Maybe I will get some results today.

**Comment by AlexKoff88** [comment]
calibration_dataset and validation_dataset can be the same in the simplest case. 
Regarding the metrics, it's your choice what metric you would like to trach. Potentially, you can come up with the implementation when you will compute both MAP and IOU in the validation function and report `max(iou, map)` in the range [0,1]

**Comment by sanbuphy** [comment]
Get it. Thank you very much .
