### ISSUE TITLE
Publish model optimizer to PyPI

### ISSUE THREAD

**Issue by wangzhenyu32** [openvinotoolkit/openvino#1618]
If release optimizer package to PyPI, User can install this by pip conveniently and quote this package in their project.

**Comment by jgespino** [comment]
Hi @wangzhenyu32 

We recently added the ability to install OpenVINO toolkit using yum, apt and conda. Pip is something the dev team is already working on. See #914 

https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_conda.html
https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_yum.html
https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_apt.html

Regards,
Jesus

**Comment by wangzhenyu32** [comment]
Can you close the issue until the issue be resolved or you ignore the issue? According to the situation, I can not find the Package on the PypI

**Comment by jgespino** [comment]
Hi @wangzhenyu32 As I previously mentioned in my response, Pip is being considered by the Development team and we have just added APT, YUM and Anaconda Cloud. I will re-open the issue.

**Comment by jgespino** [comment]
OpenVINO toolkit 2021.1 is now available through [PyPI](https://pypi.org/project/openvino-python/).

**Comment by clouds56** [comment]
@jgespino If I recall correctly, the openvino package only contains inference-engine but not model-optimizer, shall we add model-optimizer as well?
