### ISSUE TITLE
Can we use an android device to run inference using OpenVINO IE API?

### ISSUE THREAD

**Issue by TanveshT** [openvinotoolkit/openvino#1620]
This is a doubt that I am having that can we use the inference pipeline for an android device using the C++ API.

**Comment by ilya-lavrenov** [comment]
@TanveshT we are going to merge this PR soon https://github.com/openvinotoolkit/openvino/pull/506. It allows to build Java bindings for OpenVINO and use it on Android.

**Comment by TanveshT** [comment]
@ilya-lavrenov Thank you for updating me on # that. Do you need any help with the PR?  I'll be happy to contribute.

**Comment by ilya-lavrenov** [comment]
@dkurt we you need any help?

**Comment by dkurt** [comment]
What do you mean by Android device? Take a look at https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#build-on-android-systems. All depends on CPU architecture.

**Comment by TanveshT** [comment]
Thank you @ilya-lavrenov I'll try to go through it and @dkurt I will go through the docs you provided and get back to you if I have any problem.

**Comment by TanveshT** [comment]
So @dkurt OpenVINO isn't compatible with processors used by the Android devices yet. It is enabled for Intel Hardware like CPU, VPU, FPGA, GPU as we pass in these as a parameter when we load the network into the inference engine. Is this correct or wrong?

**Comment by dkurt** [comment]
Android is OS but not hardware device. Android may run as with ARM CPU as on x86. OpenVINO works on Intel Architecture, that's right but you may have almost any OS to run it.

**Comment by TanveshT** [comment]
Yes exactly as android mobile phone devices use ARM CPU, so my intuition was correct to a certain extent.

**Comment by dkurt** [comment]
Thanks for clarification. For x86 based solutions there are even known success stories. Please take a look at https://www.intel.cn/content/www/cn/zh/internet-of-things/xiaogu-3d-face-frictionless-payment-solution-en.html

**Comment by TanveshT** [comment]
Thank you I will go through it.
