### ISSUE TITLE
What is the process for Quantizing Model with Accuracy Control

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#16240]
Hi, I have noticed that the process involves multiple rounds of quantization, which can consume significant amounts of memory and swap. Despite this, results are not obtained even when memory is almost full.

How can I determine the number of times the quantization process needs to be run? If I print the results after each verification, I see many info be print, with memory usage increasing slowly and eventually filling up swap. Sometimes, the operating system even kills the process.

**Comment by AlexKoff88** [comment]
Hi again, @sanbuphy!

The number of iterations in the Quantization with Accuracy Control is not known in advance because it is impossible to predict how many layers should be returned to the original precision in order to satisfy the accuracy criterium. 

Regarding the memory usage issue, memory consumption should achieve a peak during the quantization process and fluctuate around it. There should not be an increasing trend during the quantization. 
Maybe @alexsu52 can comment more.

**Comment by sanbuphy** [comment]
> Hi again, @sanbuphy!
> 
> The number of iterations in the Quantization with Accuracy Control is not known in advance because it is impossible to predict how many layers should be returned to the original precision in order to satisfy the accuracy criterium.
> 
> Regarding the memory usage issue, memory consumption should achieve a peak during the quantization process and fluctuate around it. There should not be an increasing trend during the quantization. Maybe @alexsu52 can comment more.

HI, we meet again!

However, I noticed a significant increase in memory usage during the quantization process. At first, the images were loaded one by one, and the memory gradually increased. It occupied 50G of memory in my case. Then, the main quantization process started, and the fine-tuning data was tested to search for the operator which has the greatest error impact. This process may cause a memory increase of 5-10G.

**Comment by sanbuphy** [comment]
> Please note that for safety reasons we recommend using a synchronous OpenVINO inference API when implementing validation function that is passed to the quantization API.

Yes, I use the synchronous inference API

**Comment by sanbuphy** [comment]
> @sanbuphy Thanks for your question! Could you please share the POT config that you use?

OK, i will send you an email

**Comment by AlexKoff88** [comment]
> @sanbuphy Thanks for your question! Could you please share the POT config that you use?

This is about the new NNCF API.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
