### ISSUE TITLE
[Performance] onnxruntime with OpenVINO execution provider is slower than default CPU for ArcFace LResNet100E-IR

### ISSUE THREAD

**Issue by cyrusbehr** [openvinotoolkit/openvino#16263]
I opened a ticket on the onnxruntime github page, but have also opened one here as I am not sure which team the problem is more relevant to. To summarize, onnxruntime using the OpenVINO backend execution provider is slower than the default CPU execution provider when using the [ArcFace LResNet100E-IR](https://github.com/onnx/models/tree/main/vision/body_analysis/arcface) model. I would expect the OpenVINO execution provider to be faster on intel hardware, especially since the model [appears to be supported](https://docs.openvino.ai/latest/omz_models_model_face_recognition_resnet100_arcface_onnx.html).

You can find all the details, including the model, sample input, reproducible example code, and the outputs on the onnxruntime issues page, [here](https://github.com/microsoft/onnxruntime/issues/15027)

**Comment by Aznie-Intel** [comment]
Hi @cyrusbehr, from [Topology Support](https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html#topology-support) , mxnet_arcface is not supported by OpenVINO™ Execution Provider for ONNX Runtime for inferencing on CPU. It's only supported on GPU.

**Comment by cyrusbehr** [comment]
Ah ok I see. Thank you.
