### ISSUE TITLE
Cannot run OpenVino model using OpenCV

### ISSUE THREAD

**Issue by ArsenyStahkov** [openvinotoolkit/openvino#16287]
##### System information (version)

I build OpenCV with OpenVino using CMake (OpenCV 4.7.0 and OpenVino 2022.3). Then I created a project:

```
#include <iostream>
#include <vector>
#include <opencv2\opencv.hpp>

using namespace std;
using namespace cv;
using namespace cv::dnn;

void TestOpenVinoModel()
{
    // Our model
    //string mapping_path = "C:\\ROOT1\\opencv_build_test\\files_mobilenet_v2_openvino\\saved_model.mapping";
    //string xml_path = "C:\\ROOT1\\opencv_build_test\\files_mobilenet_v2_openvino\\saved_model.xml";
    //string bin_path = "C:\\ROOT1\\opencv_build_test\\files_mobilenet_v2_openvino\\saved_model.bin";
    
    // Another model
    string mapping_path = "C:\\ROOT1\\opencv_build_test\\files_openvino_2\\ssdlite_mobilenet_v2.mapping";
    string xml_path = "C:\\ROOT1\\opencv_build_test\\files_openvino_2\\ssdlite_mobilenet_v2.xml";
    string bin_path = "C:\\ROOT1\\opencv_build_test\\files_openvino_2\\ssdlite_mobilenet_v2.bin";

    // Load the OpenVINO plugin for OpenCV
    Net openvino_model = readNetFromModelOptimizer(xml_path, bin_path);
    
    // Set target device to CPU
    openvino_model.setPreferableTarget(DNN_TARGET_CPU);

    // Load an image
    Mat img = imread("C:\\ROOT1\\opencv_build_test\\car_300x300.jpg");

    // Preprocess the image
    //Mat blob = blobFromImage(img, 1.0, Size(), Scalar(), true, false);
    Mat blob = blobFromImage(img, 0.007843f, Size(300, 300), Scalar(127.5f, 127.5f, 127.5f), false);
    //Mat blob;
    //cvtColor(img, blob, COLOR_BGR2RGB);
    //blob = blob.reshape(1, { 1, 3, 300, 300 });

    // Set input data for the network
    openvino_model.setInput(blob);

    // Run forward pass to get the output
    Mat detections = openvino_model.forward();

    // Post-process the output to extract the bounding boxes
    Mat detections_reshaped = detections.reshape(1, detections.total() / 7);

    // Draw bounding boxes on the original image
    for (int i = 0; i < detections_reshaped.rows; ++i) {
        float confidence = detections_reshaped.at<float>(i, 2);
        if (confidence > 0.5) {
            int x_left = static_cast<int>(detections_reshaped.at<float>(i, 3) * img.cols);
            int y_top = static_cast<int>(detections_reshaped.at<float>(i, 4) * img.rows);
            int x_right = static_cast<int>(detections_reshaped.at<float>(i, 5) * img.cols);
            int y_bottom = static_cast<int>(detections_reshaped.at<float>(i, 6) * img.rows);

            rectangle(img, Point(x_left, y_top), Point(x_right, y_bottom), Scalar(0, 0, 255), 2);
        }
    }

    // Display the resulting image
    imshow("Image", img);
    waitKey();
}

int main()
{
    TestOpenVinoModel();

    return 0;
}

```

 and added a few dll files into the project:

![изображение](https://user-images.githubusercontent.com/76564343/224988906-2f7b793a-e52e-4c0f-baff-bdc18bd203d8.png)

And I added openvino.lib into the folder with libs. But the program crashes on reshape method:

![изображение](https://user-images.githubusercontent.com/76564343/224993472-cf3b5f65-2a9c-4984-9024-b0cc96770204.png)

Can anybody help?

**Comment by ilya-lavrenov** [comment]
Could you please provide full back-trace? 
It's impossible to guess why model reshaping has failed.

**Comment by ArsenyStahkov** [comment]
@ilya-lavrenov Do you mean the code? I added it.

**Comment by ArsenyStahkov** [comment]
@ilya-lavrenov and you can get the model that I use
[files_openvino_2.zip](https://github.com/openvinotoolkit/openvino/files/10968265/files_openvino_2.zip)

**Comment by ArsenyStahkov** [comment]
@songbell do you have any ideas?

**Comment by songbell** [comment]
can you share the full backtrace of the exeception below for a quick analyze of which component the issue may locate in?
![image](https://user-images.githubusercontent.com/32348500/225238953-ed81fe15-081e-4edf-93ca-fd9b35a36f50.png)

**Comment by ArsenyStahkov** [comment]
@songbell sure 

![изображение](https://user-images.githubusercontent.com/76564343/225241179-ce0d7be3-1c9b-400b-af38-ada479f6a4eb.png)

**Comment by ArsenyStahkov** [comment]
@songbell

![изображение](https://user-images.githubusercontent.com/76564343/225241793-967769d4-c7b4-4554-8d7b-dbf4fee736ae.png)

**Comment by ArsenyStahkov** [comment]
@songbell I set up kernelbase.pdb and backtrace of the exeception changed

![изображение](https://user-images.githubusercontent.com/76564343/225247771-c518ae1a-ea0b-455d-8713-339791e5dc82.png)

Where can I find this .dll file?

**Comment by songbell** [comment]
can you try enable this line?

blob = blob.reshape(1, { 1, 300, 300, 3 });

// Set input data for the network
openvino_model.setInput(blob);

// Run forward pass to get the output
 Mat detections = openvino_model.forward();

**Comment by ArsenyStahkov** [comment]
@songbell Thank you very much! I did as you adviced, after that I needed to add openvino_intel_cpu_plugind.dll into my project. I did that and the neuro was run.

**Comment by ilya-lavrenov** [comment]
@ArsenyStahkov can we close the ticket then? or any other question / problem we can help?

**Comment by ArsenyStahkov** [comment]
@ilya-lavrenov you can close.
