### ISSUE TITLE
How to transpose ov::Tensor object in c++

### ISSUE THREAD

**Issue by ashray21** [openvinotoolkit/openvino#16331]
**openvino version - 2022.3**

ov::Tensor output_tensor = infer_request.get_output_tensor();

I m inferencing yolov8 using openvino. I have successfully inferenced and my output_tensor shape is [1, 84, 8400]. I need to transpose the output_tensor into [1, 8400, 84] for post processing yolov8.

How can I do that?

**Comment by riverlijunjie** [comment]
Hi @ashray21 you can try ov::preprocess::PrePostProcessor class, reference to [this link](https://docs.openvino.ai/nightly/openvino_docs_OV_UG_Preprocessing_Details.html): 

Anyway, we can give you an example as below:

```
std::shared_ptr<ov::Model> model = core.read_model(model_path);
...
ov::preprocess::PrePostProcessor ppp(model);
// transpose [1, 84, 8400] to [1, 8400, 84]
ppp.output().postprocess().convert_layout({0, 2, 1});
model = ppp.build();
...
ov::CompiledModel compiled_model = core.compile_model(model, device_name);
```

**Comment by ashray21** [comment]
@riverlijunjie Thanks it wored
