### ISSUE TITLE
pip3 install openvino==2022.3.0 error

### ISSUE THREAD

**Issue by JinXiaozhao** [openvinotoolkit/openvino#16477]
pip3 install openvino-dev==2022.3.0
ERROR: Could not find a version that satisfies the requirement openvino==2022.3.0 (from openvino-dev==2022.3.0) (from versions: 2021.3.0, 2021.4.0, 2021.4.1, 2021.4.2, 2023.0.0.dev20230217)
ERROR: No matching distribution found for openvino==2022.3.0 (from openvino-dev==2022.3.0)

**Comment by ilya-lavrenov** [comment]
Please, use:
```
python3 -m pip install -U pip
```
Because you have old pip version.

**Comment by NasiRka** [comment]
Hi!
Have You fixed it?

**Comment by ilya-lavrenov** [comment]
It's pip version dependent. 
We cannot fix pip

**Comment by NasiRka** [comment]
> It's pip version dependent. We cannot fix pip

What pip version should I use so?

**Comment by ilya-lavrenov** [comment]
> What pip version should I use so?

pip >= 20.3
See https://github.com/pypa/manylinux

**Comment by NasiRka** [comment]
> > What pip version should I use so?
> 
> pip >= 20.3 See https://github.com/pypa/manylinux

I have pip 23.1.1 as you can see and have the same error.
If it can help I have Raspbian OS 64-bit, python 3.9, pip 23.1.1, OpenVINO Runtime 2022.3.0

**Comment by ilya-lavrenov** [comment]
>  Raspbian OS 64-bit, python 3.9, pip 23.1.1, OpenVINO Runtime 2022.3.0

Is it ARM64? We currently provide wheel packages only for x86_64 platform.
For python API you can currently use [archive](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_from_archive_linux.html).

**Comment by NasiRka** [comment]
> > Raspbian OS 64-bit, python 3.9, pip 23.1.1, OpenVINO Runtime 2022.3.0
> 
> Is it ARM64? We currently provide wheel packages only for x86_64 platform. For python API you can currently use [archive](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_from_archive_linux.html).
Okay, thanks

**Comment by David-OConnor** [comment]
2022.3.1 only supports up to Python 3.10. If on 3.11 or 3.12, you will get this error.

**Comment by tariq0101** [comment]
> 2022.3.1 only supports up to Python 3.10. If on 3.11 or 3.12, you will get this error. The latest OpenVINO supports Python 3.11, but not Movidius.

I'm getting that same error on python 3.11.2, latest available version is 2023.2.0.dev20230922

**Comment by ilya-lavrenov** [comment]
> > 2022.3.1 only supports up to Python 3.10. If on 3.11 or 3.12, you will get this error. The latest OpenVINO supports Python 3.11, but not Movidius.
> 
> I'm getting that same error on python 3.11.2, latest available version is 2023.2.0.dev20230922

```
python -m pip install -U pip
```

**Comment by tariq0101** [comment]
> > > 2022.3.1 only supports up to Python 3.10. If on 3.11 or 3.12, you will get this error. The latest OpenVINO supports Python 3.11, but not Movidius.
> > 
> > 
> > I'm getting that same error on python 3.11.2, latest available version is 2023.2.0.dev20230922
> 
> ```
> python -m pip install -U pip
> ```

Requirement already satisfied: pip in ./gimpenv3/lib/python3.11/site-packages (23.3.1)
