### ISSUE TITLE
Myriad Tests Error

### ISSUE THREAD

**Issue by EndIsComing** [openvinotoolkit/openvino#1656]
Hi,

I was trying to run myriadFuncTests and got this error. Could you please help me? Reason I'm running this test is because I want to add some tests myself.

E: [ncTool] [    744667] [myriadFuncTests] patchSetMemTypeCommand:250	Fail to find call command
E: [ncTool] [    744667] [myriadFuncTests] bootDevice:283	Fail to patch "Set memory type" command for firmware sc = -2

Also, is it possible to add custom operations for myriad plugin? 

Thanks

**Comment by jgespino** [comment]
Hi @EndIsComing 

Could you please provide additional information on how you are running this test? Is myriadFuncTests a code that you are implementing? Take a look at [How to Implement Custom Layers for VPU (Intel® Neural Compute Stick 2)](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Extensibility_DG_VPU_Kernel.html) documentation, I believe this is what you are looking for.

Regards,
Jesus

**Comment by EndIsComing** [comment]
Thanks for your reply.

** 1) I didn't add any custom code to openvino, just built it on Ubuntu 16.04 using: ** 

`cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=TBB -DENABLE_MKL_DNN=OFF -DENABLE_CLDNN=OFF -DENABLE_MYRIAD=ON -DENABLE_TESTS=ON ..`

and then I ran ./myriadFuncTests from debug folder with myriad connected and usb ports populated. I can connect to myriad using openvino 2020.1 but with 2020.4 I get this error: 

```
E: [ncTool] [ 744667] [myriadFuncTests] patchSetMemTypeCommand:250 Fail to find call command
E: [ncTool] [ 744667] [myriadFuncTests] bootDevice:283 Fail to patch "Set memory type" command for firmware sc = -2
```

2) In 2020.1 I could just pass my custom operation info (in/out, precision, parameters) through openvino to myriad by changing some header files and add a file in "vpu/graph_transformer/src/stages/" same as default layers while actual implementation was part of myriad firmware.  I need to create blob file using myriad_compile executable and it doesn't recognize my layer. I assume my custom layer needs registeration with inference engine. Is it possible to do it without going through OpenCL for now?

Thanks

**Comment by jgespino** [comment]
Hi @EndIsComing 

I built OpenVINO from source with the following commands and ran the myriadFuncTests without any issues on the Intel Neural Compute Stick 2. I am not aware of another method to implement custom layers for Myriad without OpenCL. 

```
git clone https://github.com/openvinotoolkit/openvino
cd openvino
git submodule update --init --recursive
git checkout 2020.4
chmod +x install_dependencies.sh
./install_dependencies.sh
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=TBB -DENABLE_MKL_DNN=OFF -DENABLE_CLDNN=OFF -DENABLE_MYRIAD=ON -DENABLE_TESTS=ON ..
make --jobs=$(nproc --all)
```

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please feel free to re-open or start a new issue if additional assistance is needed.
