### ISSUE TITLE
Using IR format model in an android app?

### ISSUE THREAD

**Issue by dsbyprateekg** [openvinotoolkit/openvino#16591]
Hi,

Is there any example code available for using IR format models in an android app?
I have a face detection model in IR (XML and bin) format and I would like to load that in android studio.

**Comment by ilya-lavrenov** [comment]
Hi @dsbyprateekg 

Please, have a look:
- https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin/demos/coco_detection_android_demo
- https://opencv.org/face-recognition-on-android-using-openvino-toolkit-with-arm-plugin/
