### ISSUE TITLE
inference-engine/thirdparty/mkl-dnn VS https://github.com/intel/mkl-dnn

### ISSUE THREAD

**Issue by YijinLiu** [openvinotoolkit/openvino#166]
I know that inference-engine/thirdparty/mkl-dnn is different from https://github.com/intel/mkl-dnn
Do you have any plan to merge these changes into https://github.com/intel/mkl-dnn ?

**Comment by banderlog** [comment]
Also, do you have any plans to switch from MKL-DNN to DNNL?

**Comment by ilyachur** [comment]
@dmitry-gorokhov Can you help?

**Comment by banderlog** [comment]
no answer is given
