### ISSUE TITLE
Does OpenVINO have a plan to support Web AI inference?

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino#16651]
I really like OpenVINO and would like to ask if there is a plan to support web-based deployment, such as OpenVINO.js, which utilizes WASM and WebGPU. Thank you!

**Comment by sanbuphy** [comment]
> yes :) but today I cannot provide any specific dates, but please track our announcements

WOW! that's amazing!  Can I know if it will be happening this year?

**Comment by mlukasze** [comment]
please keep fingers crossed for this 8)
