### ISSUE TITLE
[Bug] Compilation error in ARM plugin on Raspberry Pi

### ISSUE THREAD

**Issue by alain-lnpcrd** [openvinotoolkit/openvino#16694]
##### System information (version)
- OpenVINO => 2020.3
- Operating System / Platform => ubuntu 22.04
 sur raspberry pi 4B 8 Go mem

I am trying to build openvino with the sources

cmake -DCMAKE_BUILD_TYPE=Release\
       -DOPENVINO_EXTRA_MODULES=<OPENVINO_CONTRIB_PATH>/openvino_contrib/modules/arm_plugin\
       -DARM_COMPUTE_SCONS_JOBS=$(nproc --all)\
.. && cmake --build . --parallel

I am resuming after crashing the build at " cmake --build . --parallel "for the nth time for lack of swap and I have just mounted it to 16 GB
The build is not progressing, the memory is full, the occupied swap is at 8.5 GB.
The build was at 21% and just crashed.
I rerun cmake --build . --parallel and building quickly resumes at "Build Arm Compute Library"
The memory is totally occupied (8Go) the swap goes up: 8G ++ ..
I think I have enough for the week if it wants to go well.
For the moment nothing is progressing and always the same line "Build Arm Compute Library" and nothing more.

.Where is my error ...

**Comment by alain-lnpcrd** [comment]
Hi,
After two last tries where I saw the 16 Gb saturated without any progression of the build, I relaunched with make -j4.
The operation was completed after three hours without using the swap and it only remains for me to launch the installation.
With the "cmake --build . --parallel" a bunch of processes are started without restoring the memory.

**Comment by alain-lnpcrd** [comment]
Certain that you are able to give the best solution to the compilation of this project I launched the command "cmake --build . --parallel 4".
Memory usage averaged less than 54GB and less than 4MB of swap was used. The operation ended correctly and lasted less than 3 hours

**Comment by YuChern-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
