### ISSUE TITLE
corrupt openvino 2020_4 tgz file

### ISSUE THREAD

**Issue by dexception** [openvinotoolkit/openvino#1670]
![image](https://user-images.githubusercontent.com/31848222/89552529-e4140f00-d829-11ea-95ee-f1420bdb12b1.png)

**Comment by jgespino** [comment]
Hi @dexception 

Please try re-downloading the package and try again, it's possible your download is incomplete or corrupted. I just tested from my end and did not have any issues.

Regards,
Jesus

**Comment by dexception** [comment]
http://registrationcenter-download.intel.com/akdlm/IRC_NAS/16803/l_openvino_toolkit_p_2020.4.287.tgz

Tried extracting using winrar. Doesn't work !

Tried extracting on Fresh Centos 7 VM using the command. Doesn't work.

tar -xvzf l_openvino_toolkit_p_2020.4.287.tgz

**Comment by jgespino** [comment]
Your l_openvino_toolkit_p_2020.4.287.tgz has a different checksum value, the expected SHA1 should be `a2160105d776c0ac3be0d02586c55b126c84676b` and 582 MB file size. 

Try re-downloading the installation file. 

Regards,
Jesus

**Comment by dexception** [comment]
Not a bad idea to give checksum on the download page.
Now fixed. Closing.
