### ISSUE TITLE
Installing l_openvino_toolkit_p_2019.1.144 on Linux Ubuntu, does not contain OpenCV, so running the demos throws excption

### ISSUE THREAD

**Issue by Bahramudin** [openvinotoolkit/openvino#168]
I am trying to install **l_openvino_toolkit_p_2019.1.144** on my Ubuntu 2019, I am following [this ](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html) guide step by step. And while I getting to step running the **./demo_squeezenet_download_convert_run.sh** then it shows the error and says OpenCV not found, while I reinstalled and I found that OpenCV is not containing in the install package, a screenshot of my installation:
![微信截图_20190531142846](https://user-images.githubusercontent.com/13574895/58686240-dc004a00-83b0-11e9-9962-f2ebee7aa6a8.png)

a screenshot of the documentation guide:
![微信截图_20190531143136](https://user-images.githubusercontent.com/13574895/58686253-e28ec180-83b0-11e9-9d5e-47b42df773a1.png)

So there in my installation two packages are missing which are highlighted in the second screenshot, what is the reason?

Thanks!

**The entire Error message:**

> CMake Warning at common/format_reader/CMakeLists.txt:18 (message):
>   OPENCV is disabled or not found, format_reader is built without OPENCV
>   support
> 
> 
> CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Inference Engine cannot be found at
>   /opt/intel/openvino_2019.1.144/deployment_tools/inference_engine/share/../lib/intel64.
>   Please consult InferenceEgnineConfig.cmake module's help page.  (missing:
>   IE_LIBRARY) (Required is at least version "1.6")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   /opt/intel/openvino_2019.1.144/deployment_tools/inference_engine/share/InferenceEngineConfig.cmake:121 (find_package_handle_standard_args)
>   CMakeLists.txt:142 (find_package)
> 
> 
> CMake Error at CMakeLists.txt:142 (find_package):
>   Found package configuration file:
> 
>     /opt/intel/openvino_2019.1.144/deployment_tools/inference_engine/share/InferenceEngineConfig.cmake
> 
>   but it set InferenceEngine_FOUND to FALSE so package "InferenceEngine" is
>   considered to be NOT FOUND.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/adil/inference_engine_samples_build/CMakeFiles/CMakeOutput.log".
> Error on or near line 229; exiting with status 1
>

**Comment by shubha-ramani** [comment]
Dear @Bahramudin ,
After you run bin/setupvars.sh check for the following environment variable : OpenCV_DIR. $echo OpenCV_DIR should do the trick. What does it say ?

Thanks,

Shubha

**Comment by Bahramudin** [comment]
@shubha-ramani I tested that, but there was not OpenCV dir, in the installation screenshot if you look there are no ### OpenCV and **Inference Engine** options, so I think there is a problem with the installation package, it is not the same as the documentation, I have posted both screenshots, you have a look too.

**Comment by shubha-ramani** [comment]
@Bahramudin  The latest release of OpenVino is 1.48 not 1.44. Are you sure you have the latest OpenVino release ? So it looks like OpenCV_DIR (it's case sensitive so it's OpenCV_DIR not OpenCV_dir as you wrote) was never created ? Does it show empty string when you do echo $OpenCV_DIR ? It should at least show empty string.

**Comment by Bahramudin** [comment]
Dear @shubha-ramani I know that is case sensitive I have copied and pasted the command from your comment, `echo OpenCV_DIR`, then it shows only `OpenCV_DIR`.

I have downloaded the latest one, I have downloaded both the online and offline version and installed both of them, I don't know how to download the last version as you mention, I think there is a problem in the design of the webpage, not very readable.

This is the screenshot of the download page:
![image](https://user-images.githubusercontent.com/13574895/58752105-b6bc2a80-84db-11e9-8460-50128bd37001.png)

### So??

**Comment by alalek** [comment]
With clear system it works fine. Documentation screenshots are from clean systems.

You don't using clear system (perhaps you have OpenVINO2019R1.0.0 installed), so you see different information.
> Select components to **MODIFY**

**Comment by shubha-ramani** [comment]
Dear @Bahramudin 
What version of Linux are you using ? Please try the following. Completely uninstall what you have. You can do this by typing udo ./install_GUI.sh once more. Then next time, try and install using the command-line option sudo ./install.sh . It could very well be that the GUI version is broken. If you can get things working with the command-line option I will file a bug. Please also let me know what version of Linux you are using.

Really sorry that you're having so much trouble ! I know how it must be irritating.

Thanks,

Shubha

**Comment by Bahramudin** [comment]
@alalek In the first, I installed it in a clean system, there was not installed **OpenVINO** Toolkit before. So the screenshot above the same thing as the first time. I did not even download the **OpenVINO2019R1.0.0**, I just installed a new system and then downloaded the latest version (**OpenVINO2019R1.1.0**) as you can see in the screenshot above, I not new with OpenCV and **OpenVINO**. In windows 10 64bit it works well.

@shubha-ramani The Linux version is **Kunbunt 2019.04**. I have uninstalled almost three-four times, the first I installed from offline package, and then when it was not working, then I decided to install it from the online package, but the same error (the was no OpenCV and Inference Engine modules in the installation wizard) and then the third time after uninstalling by the way you mentioned above, installed it again from the offline package which I downloaded for the second time. And the same error.

So this time I will try to install it by command line and the result I will publish here.

**Comment by Bahramudin** [comment]
@shubha-ramani after I run the command-line installer, then it shows me a message this says 
> Missing optional prerequisites
> -- Unsupported OS

So the problem can be the operating system, which is not supported.
Anyway, I the GUI installer won't show any error or issue, so makes it hard to guess the reason.

Thanks!

**Comment by shubha-ramani** [comment]
Dear @Bahramudin,
At least we know why now. I guess Kubuntu is not supported. That said I'm filing a bug because you should not have suffered so much with the GUI version of the installer - it should also have given you the same error message of "Unsupported OS". 

Thanks for your patience !

Shubha

**Comment by Bahramudin** [comment]
@shubha-ramani Kubuntu, Ubuntu, ..., are all Debian based operating system, but why it is not supported, a little bit it makes me very strange?

Anyway, yes, the GUI installer should also give this error message, I think, a lot of users may use the GUI version for installation. So now if there was any error or issue, the installer does not show any message and then the user feeling the installation is OK, but indeed the problem is just with the installation.

Thanks for filing a bug due to this shortness!

**Comment by BalajiB197** [comment]
@Bahramudin 
Even I am facing the same problem.
Error: OPENCV is disabled or not found, format_reader is built without OPENCV support
My OS: ubuntu 18.04 LTS
its an 8 core machine.

**Comment by Bahramudin** [comment]
@BalajiB197 I think, in the new version it may have bugs because previously I was able to use on it the ubuntu 18.04 LTS.

Hope the next version be released as soon as possible and fix these bugs.

**Comment by BalajiB197** [comment]
@Bahramudin  any other solution to fix this?
Waiting up to next release, not a feasible solution.
Let me know proper steps to uninstall, at least I will give one more try in installing it.

**Comment by shubha-ramani** [comment]
@BalajiB197 
Technically though, OpenVino is not supported on Ubuntu 18.04 LTS. This is clearly laid out in [This doc](http://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html)
Ubuntu 16.04.x long-term support (LTS), 64-bit: Minimum supported kernel is 4.14
CentOS 7.4, 64-bit (for target only)
Yocto Project Poky Jethro v2.0.3, 64-bit (for target only and requires modifications)

OpenVino developers are well aware of the urgency of this.

Hope it helps,

Thanks,

Shubha

**Comment by BalajiB197** [comment]
@shubha-ramani  Hi, just found that issue is not only on ubuntu 18.04.
I tried installing in my Windows 10 machine, and  I am facing the same error.
And also i make sure of selecting OpenCv while installing the toolkit.
CMake Warning at common/format_reader/CMakeLists.txt:18 (message):
OPENCV is disabled or not found, format_reader is built without OPENCV
support

**Comment by Bahramudin** [comment]
@BalajiB197 Sorry I did not find and solution to this problem. I am uisng the uninstalling script to uninstall and also the documentaion recomended steps to delete some folders. I think there is no problem in installing or uninstalling, the problem is with the package itself.

**Comment by BalajiB197** [comment]
@Bahramudin @shubha-ramani I found the alternate solution it fix the above errors.
I just tried to build using provided shell script (i.e **build.sh** inside samples) and was able to successfully complete the installation for demos.

**Comment by shubha-ramani** [comment]
Dearest @Bahramudin  and @BalajiB197 

I am sorry you are having these problems with installation, particularly with the GUI installer. I have filed a bug on this. 

I build dldt on Windows all the time, and I've never had problems.  There is no need to execute "build.sh" . Did you follow [these instructions](https://github.com/opencv/dldt/blob/2019/inference-engine/README.md) ? Of if you want Python API, then [these build instructions with python api](https://github.com/opencv/dldt/blob/2019/inference-engine/ie_bridges/python/README.md) ?

These instructions work for me.

The GUI installer bug (not noticing when a Linux OS is unsupported) is a valid issue and yes, I have filed a bug on it.

Thanks !

Shubha

**Comment by BalajiB197** [comment]
@shubha-ramani I executed build.sh in Linux OS, not in Windows (as it is Shell script).
I have not built inference-engine, I am not finding these files "cd dldt/inference-engine
", there is no inference-engine file I am talking in Linux machine again.
I am following the other instruction with python api.
Let me come back, after following that!
Thanks

**Comment by jgespino** [comment]
Closing, issue is related to older release. Please start a new issue if additional assistance is needed with the latest release.
