### ISSUE TITLE
cannot convert onnx model to ir

### ISSUE THREAD

**Issue by QiangZhu123** [openvinotoolkit/openvino#16896]
Hello, I have read the official documentation on how to convert custom operators to IR, but there are still some questions that I haven't figured out yet.I haven't implemented the custom operation myself, I just want to convert it to an IR file because the official documentation suggests that it can be done, but I haven't been successful.
I have created a custom operator,it looks like 
[input: "x"
input: "y"
output: "2"
op_type: "Zhu"
]  in onnx 
 
=======mo_extension/ops=====

import numpy as np
from openvino.tools.mo.graph.graph import Node, Graph
from openvino.tools.mo.ops.op import Op

class ZHUEXT(Op):
    op = 'zhu'
    op_type='zhu'
    enabled = False

    def __init__(self, graph: Graph, attrs: dict):
        super().__init__(graph, {
            'type': __class__.op,
            'op': __class__.op,
            'in_ports_count': 2,
            'out_ports_count': 1,
            'infer': self.infer
        }, attrs)
        
    @staticmethod
    def infer(node: Node):
        input_shape = node.in_port(0).data.get_shape()
        input_value = node.in_port(0).data.get_value()
        
        node.out_port(0).data.set_shape(node.in_port(0).data.get_shape())
        if input_value is not None:
            node.out_port(0).data.set_value(node.in_port(0).data.get_value())
    def supported_attrs(self):
        return []

================mo_extension/front/onnx========

from mo_extension.ops.zhu import ZHUEXT
from openvino.tools.mo.front.extractor import FrontExtractorOp
from openvino.tools.mo.front.onnx.extractors.utils import onnx_attr

class ZhuFrontExtractor(FrontExtractorOp):
      op = 'ZHUEXT'
      enabled = True

    @classmethod
    def extract(cls, node):
        ZHUEXT.update_node_stat(node, {})
        return cls.enabled

mo --input_model model.onnx  --extension mo_extension

[ WARNING ]  Please set `version` attribute for node 24 with type=zhu
[ WARNING ]  Changing Const node '10_input_port_1/value1228' data type from int64 to float32 for Add operation
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check 'false' failed at src/frontends/common/src/frontend.cpp:53:
Converting input model
Cannot create zhu layer 24 id:3 from unsupported opset: extension

[ ERROR ]  Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/openvino/tools/mo/main.py", line 50, in main
    ngraph_function = convert_model(**argv)
  File "/opt/conda/lib/python3.7/site-packages/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "/opt/conda/lib/python3.7/site-packages/openvino/tools/mo/convert_impl.py", line 937, in _convert
    raise e.with_traceback(None)
RuntimeError: Check 'false' failed at src/frontends/common/src/frontend.cpp:53:
Converting input model
Cannot create zhu layer 24 id:3 from unsupported opset: extension

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

I have found that some files were generated,so I checked the file ''model.onnx'' and ''model.xml''
![360截图20230413003318404](https://user-images.githubusercontent.com/34334567/231525991-db235e60-adc4-472c-a331-97ceb8a066ae.jpg)
![360截图20230413003309871](https://user-images.githubusercontent.com/34334567/231526015-88a4deb5-41d5-4e36-8a3b-62c43c1b9ed4.jpg)

why the xml have Add? I don't understand what happened. Is it because I need to implement the operator?
what's that mean "Cannot create zhu layer 24 id:3 from unsupported opset: extension"?
ths!

**Comment by mbencer** [comment]
It's an extension defined in an old manner, using old ONNX MO path. Please consider using frontend extensions desribed in https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Frontend_Extensions.html. Please be awared, the you can also passing a path to .so/.dll with extensions via MO using --extensions flag.

@rkazants Could you please take a look at the error from MO?

**Comment by Wan-Intel** [comment]
Hi QiangZhu123,
Just wanted to follow up and see if your issue has been resolved.

**Comment by Wan-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
