### ISSUE TITLE
Neural Compute Stick 2 运行错误

### ISSUE THREAD

**Issue by Wuwjdd** [openvinotoolkit/openvino#169]
Traceback (most recent call last):
  File "run.py", line 293, in <module>
    sys.exit(main() or 0)
  File "run.py", line 204, in main
    exec_net = plugin.load(network=net)
  File "ie_api.pyx", line 395, in openvino.inference_engine.ie_api.IEPlugin.load
  File "ie_api.pyx", line 406, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: Failed to allocate graph: NC_ERROR

 **我使用神经计算棒2运行时，出现了上述错误。有人可以帮我解决吗？**

**Comment by shubha-ramani** [comment]
@Wuwjdd 
There could be many reasons behind why you're getting this error. But my guess is that your PYTHONPATH is not set correctly.

Please read the below document
[https://github.com/opencv/dldt/blob/2019/inference-engine/ie_bridges/python/README.md](https://github.com/opencv/dldt/blob/2019/inference-engine/ie_bridges/python/README.md)

Thanks,

Shubha

**Comment by ilyachur** [comment]
@Wuwjdd Is the issue still actual?

**Comment by AnastasiaKazantaeva** [comment]
It seems that provided solution worked as no response, closing this issue

**Comment by somodis** [comment]
To anyone who is still searching for the solution on Google page > 1: 

It seems obvious but you should check if you're not accidentally using the USB 2.0 port for the NCS 2. 
That could (also) cause this error. I've been an inattentive moron so you don't have to, have a nice day :)
