### ISSUE TITLE
better location for myriad firmware?

### ISSUE THREAD

**Issue by tripzero** [openvinotoolkit/openvino#170]
Looks like dldt is looking for firmware in libdir (in my case /usr/lib64/haswell).  The error was ambiguous so I didn't know that it failed to load the firmware, but that issue aside, is this the proper location for firmware files?  Can this be configured at build time?

Thanks

**Comment by shubha-ramani** [comment]
Dear @tripzero, 
What Myriad "Firmware" are you talking about ? Are you talking about the plugin ? The plugin can actually be located anywhere on your system, as long as Inference Engine knows how to find it.  We do not make Myriad firmware code available.

Please clarify and thanks for your patience,

Shubha

**Comment by tripzero** [comment]
I'm talking about the firmware blob the plugin tries to load before it actually works.  https://download.01.org/opencv/2019/openvinotoolkit/R1/inference_engine/

**Comment by shubha-ramani** [comment]
Dear @tripzero, you can put your Inference Engine Libraries and plugins wherever you want. For Myriad, please take a look at these CMakeLists.txt files:
[https://github.com/opencv/dldt/blob/2019/inference-engine/CMakeLists.txt](https://github.com/opencv/dldt/blob/2019/inference-engine/CMakeLists.txt)
[https://github.com/opencv/dldt/blob/2019/inference-engine/src/CMakeLists.txt](https://github.com/opencv/dldt/blob/2019/inference-engine/src/CMakeLists.txt)
[https://github.com/opencv/dldt/blob/2019/inference-engine/src/vpu/CMakeLists.txt](https://github.com/opencv/dldt/blob/2019/inference-engine/src/vpu/CMakeLists.txt)

The locations are definitely not hardcoded in source code, if that's what you mean.

Hope it helps. Thanks for using OpenVino !

Shubha

**Comment by bwarden** [comment]
We're asking specifically about the MvNCAPI-ma2450.mvcmd and MvNCAPI-ma2480.mvcmd files, which can and should be installed to a separate location than ELF shared objects like libmyriadPlugin.so. Looks like we'd have to patch the cmake files to make them install to separate locations.

**Comment by shubha-ramani** [comment]
Dear @bwarden 
Grepping for "MvNCAPI-ma2450" produces the following
[https://github.com/opencv/dldt/blob/2019/inference-engine/src/vpu/CMakeLists.txt](https://github.com/opencv/dldt/blob/2019/inference-engine/src/vpu/CMakeLists.txt)

You should be able to manipulate CMakeLists.txt to put those where-ever you want.

Shubha

**Comment by mshabunin** [comment]
@tripzero , check this function: https://github.com/opencv/dldt/blob/693ab4e79a428e0801f17f4511b129a3fa8f4a62/inference-engine/thirdparty/movidius/mvnc/src/mvnc_api.c#L470-L549
I think it is possible to add an environment variable which will control the firmware search algorithm. Feel free to propose pull request.

**Comment by AnastasiaKazantaeva** [comment]
It seems that issues is not actual anymore as no new responses. Close this issue. In case of any question feel free to create a new issue
