### ISSUE TITLE
RuntimeError: [ GENERAL_ERROR ]  /home/jenkins/agent/workspace/private-ci/ie/build-linux-debian_9_arm/b/repos/openvino/inference-engine/src/vpu/common/src/ngraph/transformations/dynamic_to_static_shape.cpp:199 DynamicToStaticShape transformation encountered dynamic node Tile_742 of type Tile ver. 0, but only [Ceiling ver. 0, Clamp ver. 0, Concat ver. 0, Convert ver. 0, Exp ver. 0, ExpGatherElements ver. 0, Floor ver. 0, Log ver. 0, MatMul ver. 0, Relu ver. 0, ...] types are supported for dynamic nodes 

### ISSUE THREAD

**Issue by RDXiaoLu** [openvinotoolkit/openvino#17001]
![3851c68e18d5fe3804e2f487d8e9400](https://user-images.githubusercontent.com/87572685/232568776-6af612ac-edc3-431c-ab15-74e4ba3b4b97.jpg)

PC机 openvino-dev 2021.4.0 使用openmmdeploy配置有dynamic 
![image](https://user-images.githubusercontent.com/87572685/232569603-a3a6a6e8-cc46-45be-8e40-1dc93537f12a.png)

树莓派openvino-runtime 2021.4.0  
运行.py 文件  为sample中 object_detection_ssd.py 修改而来。

如何解决？
File "detector_coral_faster_rcnn.py", line 102, in main
    exec_net = ie.load_network(network=net, device_name=args.device)

RuntimeError: [ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-debian_9_arm/b/repos/openvino/inference-engine/src/vpu/common/src/ngraph/transformations/dynamic_to_static_shape.cpp:199 DynamicToStaticShape transformation encountered dynamic node Tile_742 of type Tile ver. 0, but only [Ceiling ver. 0, Clamp ver. 0, Concat ver. 0, Convert ver. 0, Exp ver. 0, ExpGatherElements ver. 0, Floor ver. 0, Log ver. 0, MatMul ver. 0, Relu ver. 0, ...] types are supported for dynamic nodes

**Comment by ilya-lavrenov** [comment]
MYRIAD plugin is out of support.
Please, use CPU plugin to perform inference on ARM

**Comment by RDXiaoLu** [comment]
> MYRIAD plugin is out of support. Please, use CPU plugin to perform inference on ARM

I try face-detection-adas-0001 of open_model_zoo on MYRIAD,  it's fine
