### ISSUE TITLE
Unexpected CNNNetwork format with custom trained model using MYRIAD

### ISSUE THREAD

**Issue by nedo99** [openvinotoolkit/openvino#1705]
Hello,

I trained a custom model for object detection using MYRIAD as a device, but I am getting the following error:
```
[ INFO ] Loading model to the device
Traceback (most recent call last):
  File "test.py", line 213, in <module>
    sys.exit(main() or 0)
  File "test.py", line 166, in main
    exec_net = ie.load_network(network=net, device_name=args.device)
  File "ie_api.pyx", line 178, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 187, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Unexpected CNNNetwork format: it was converted to deprecated format prior plugin's call
```

I am using [object detection script](https://github.com/openvinotoolkit/openvino/blob/releases/2020/3/inference-engine/ie_bridges/python/sample/object_detection_sample_ssd/object_detection_sample_ssd.py), with OpenVINO 2020/3 release. MYRIAD gets loaded and it works fine when using `classification_sample_async ` from built examples.
```
[ INFO ] Device info:
        MYRIAD
        MKLDNNPlugin version ......... 2.1
        Build ........... 2020.3.0-3467-15f2c61a-releases/2020/3
``` 
The script works fine with my custom-built model when using CPU as a device. The issue appears only with the device set as MYRIAD.

Possible issue could be the command used for converting the model (I trained using tensorflow) to OpenVINO. I used following command for converting:
```
python3 mo_tf.py --input_model <path/to/tf/custom_model> --tensorflow_object_detection_api_pipeline_config <pipeline_config> --tensorflow_use_custom_operations_config openvino_2020.3.194/deployment_tools/model_optimizer/extensions/front/tf/ssd_v2_support.json
```

Regards,
Nedim

**Comment by jgespino** [comment]
Hi @nedo99 

Try adding a couple more options to the model optimizer:

`--input_shape` or `--batch`: specify the input shape or batch
`--data_type FP16`: Myriad uses FP16 models, if not specified Model Optimizer will use FP32

Which base model did you use for training? Which TensorFlow version are you using? Do you see the same error when using the latest OpenVINO toolkit 2020.4 release?

Regards,
Jesus

**Comment by nedo99** [comment]
Hi @jgespino 

As mentioned I am using 2020.3 release. Still did not test with newer release.

I set FP16, but the error is still the same. I use SSD Mobilenet v2 for training. Tensorflow version `1.15.3`. Regarding the input_shape, whatever I use i get: `no matches found: [1,3,300,300]`. I tried `(1,3,300,300)`, but then I get `unknown file attribute: 1`.

When converting this is the output:
```
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	rained-inference-graphs/output_inference_graph_v5.pb/frozen_inference_graph.pb
	- Path for generated IR: 	openvino_2020.3.194/deployment_tools/model_optimizer/.
	- IR output name: 	frozen_inference_graph
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP16
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	trained-inference-graphs/output_inference_graph_v5.pb/pipeline.config
	- Use the config file: 	None
Model Optimizer version:
The Preprocessor block has been removed. Only nodes performing mean value subtraction and scaling (if applicable) are kept.

[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: openvino_2020.3.194/deployment_tools/model_optimizer/./frozen_inference_graph.xml
[ SUCCESS ] BIN file: openvino_2020.3.194/deployment_tools/model_optimizer/./frozen_inference_graph.bin
[ SUCCESS ] Total execution time: 19.08 seconds.
[ SUCCESS ] Memory consumed: 567 MB.
```

**Comment by jgespino** [comment]
@nedo99 Could you share your frozen TensorFlow model and a sample input?

**Comment by nedo99** [comment]
After some additional debugging, it seems that [object_detection_sample_ssd.py](https://github.com/openvinotoolkit/openvino/blob/releases/2020/3/inference-engine/ie_bridges/python/sample/object_detection_sample_ssd/object_detection_sample_ssd.py) example has to be modified in order for MYRIAD device to work.

If I move the section "Prepare output blobs" after the call `exec_net = ie.load_network(network=net, device_name=args.device)` then it works.

**Comment by jgespino** [comment]
Hi @nedo99 

Thanks for providing a workaround. I tested your model with the latest release 2020.4 and the Runtime error is no longer observed. Please let me know if we can proceed to close this issue.

Regards,
Jesus
