### ISSUE TITLE
resize

### ISSUE THREAD

**Issue by linhaoqi027** [openvinotoolkit/openvino#1715]
how can i find "resize" op?

**Comment by ilyachur** [comment]
Hi @linhaoqi027 

All available operations you can find [here](https://docs.openvinotoolkit.org/latest/openvino_docs_ops_opset.html).

You can use [Reshape](https://docs.openvinotoolkit.org/latest/openvino_docs_ops_shape_Reshape_1.html) operation in order to change shapes of tensors.

**Comment by lazarevevgeny** [comment]
@linhaoqi027, please, post your questions on stackoverflow instead of creating an issue in the github.
