### ISSUE TITLE
Intel Atom x5-Z8550: No supported OCL devices found

### ISSUE THREAD

**Issue by Shassk** [openvinotoolkit/openvino#17290]
##### System information (version)
- OpenVINO Source => intel.com: Runtime / Windows/ 2022.3 (Recommended) / C++ / OpenVINO Archives
- OpenVINO Version => 2022.3
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017
- Problem classification => Model Conversion /Accuracy/TensorFlow FE 
- Device use => GPU
- Framework => ONNX models (if that's what that means)

##### Detailed description
I'm trying to run a model on multiple devices (code below). It compiles just fine. However when I try to run it I'm getting this error:
```
ERROR: Runtime error: Failed to create plugin openvino_intel_gpu_plugin.dll for device GPU
Please, check your environment
Check '!supported_devices.empty()' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-s2019\b\repos\openvino\src\plugins\intel_gpu\src\runtime\ocl\ocl_device_detector.cpp:212:
[GPU] No supported OCL devices found or unexpected error happened during devices query.
[GPU] Please check OpenVINO documentation for GPU drivers setup guide.
```
And the mentioned guide for Windows pretty much just says to go and check if GPU driver is installed: it does - version 20.19.15.4364 to be exact.

[The issue #452](https://github.com/openvinotoolkit/openvino/issues/452) mentiones that support is available for gen 8 or higher, but Cherry Trail HD Graphics is gen 8 as well.

##### Steps to reproduce

This code with any ONNX model I've tried so far as long as it's launched on my Z8550:
```
	std::shared_ptr<ov::Model> model = fEngine.read_model(modelFileName);
    	fEngine.set_property("MULTI", ov::device::priorities("GPU", "CPU"));
	fModel = fEngine.compile_model(model, "MULTI");
```

**Comment by ilya-lavrenov** [comment]
@Shassk could you please check whether this fix helps https://github.com/openvinotoolkit/openvino/pull/17288 ?

**Comment by Shassk** [comment]
> What input `clinfo` command provides?

It seems like Windows link in https://github.com/Oblomov/clinfo is not working for me, I might try to build it myself now.

**Comment by Shassk** [comment]
Any new ideas?

**Comment by Shassk** [comment]
> Recommendation is to use `fEngine.set_property("AUTO", ov::hint::performance_mode(ov::hint::PerformanceMode::CUMULATIVE_THROUGHPUT)))` which will automatically discover available devices and run model on all of them.

Also this way it requires device priorities (otherwise throws an error), and with priorities set manually still throws an error about GPU plugin.
