### ISSUE TITLE
opencv Vino Tried load plugin : MKLDNNPlugind,  error: Plugin MKLDNNPlugind cannot be loaded 

### ISSUE THREAD

**Issue by love6tao** [openvinotoolkit/openvino#173]
Win10+win32(vs2015)+openvino_2019.1.148 +i7-8750
I want to build a win32 project independently to test my deep learning model.
But just after writing the following lines of code, there is a problem running, I don't know why, the related lib and  dll I have added, this problem has plagued me for a week.

![360截图20190608174244042](https://user-images.githubusercontent.com/12590932/59144027-db9d2a00-8a14-11e9-8e4d-1002767e8863.jpg)

![360截图20190608173358393](https://user-images.githubusercontent.com/12590932/59143932-ca9fe900-8a13-11e9-99a8-38b68c3d6d60.jpg)
![360截图20190608173336370](https://user-images.githubusercontent.com/12590932/59143935-cd9ad980-8a13-11e9-96e4-1e1b217d482d.jpg)

Openvino can run my converted model under cmd， but I can't load MKLDNNPlugind in a separate project.
![360截图20190608173414516](https://user-images.githubusercontent.com/12590932/59143963-00dd6880-8a14-11e9-87ed-1647800d3076.jpg)

**Comment by shubha-ramani** [comment]
Dearest @love6tao 

I can promise you that your environment variables are incorrect and this is exactly why you're having such errors. Let's solve this problem using the following methodical steps:

1) Build Inference Engine as DEBUG (so you can step through and debug your code). Use [this README](https://github.com/opencv/dldt/blob/2019/inference-engine/README.md). However if you want to build with Python API, then use [Python API README](https://github.com/opencv/dldt/blob/2019/inference-engine/ie_bridges/python/README.md)

2) Copy the following classification_sample to a new sample in the same location - rename it to something unique
[https://github.com/opencv/dldt/tree/2019/inference-engine/samples/classification_sample](https://github.com/opencv/dldt/tree/2019/inference-engine/samples/classification_sample)

3) Put your code in the newly created folder.  Modify what you need to. You will have to change set (TARGET_NAME "classification_sample") in the CMakeLists.txt and also the name of the header file .

4)Study this [Open Model Zoo Demos README](https://github.com/opencv/open_model_zoo/blob/master/demos/README.md) as a guide but the most important things from this README are the following:

> please set InferenceEngine_DIR to a CMake folder you built the dldt project from, for example <dldt_repo>/inference-engine/build

> Please also set the OpenCV_DIR variable pointing to the required OpenCV package. 

5) Rebuild your samples only by creating a build directory in your samples folder and for Windows, cmake -G "Visual Studio 15 2017 Win64" . For Linux it will just be something like cmake -DCMAKE_BUILD_TYPE=Debug && make -j2

But in step 4 you must point 2 environment variables to the binaries you built in step 1.

Hope this works for you ! Please post here should you have questions.

Thanks,

Shubha

**Comment by mmbajo** [comment]
Hi,

I also have the same issue.
When you say

> please set InferenceEngine_DIR to a CMake folder you built the dldt project from, for example <dldt_repo>/inference-engine/build

Do you mean I should make InferenceEngine_DIR as an environment variable and set it to the build folder?

**Comment by avitial** [comment]
@mmbajo that is correct  `export InferenceEngine_DIR=/path/to/openvino/build/`, please refer to [Add Inference Engine to Your Project ](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#add-inference-engine-to-your-project) section of the build instructions.

Closing this, feel free to reopen and ask additional questions related to this topic.
