### ISSUE TITLE
Request - Please make a API 1.0 vs. 2.0 Samples Comparison

### ISSUE THREAD

**Issue by adammpolak** [openvinotoolkit/openvino#17300]
We based our workflows off of the hello_classification.cpp in the samples.

The updated samples are not exactly 1:1.

Understanding why we no longer need to do things like:

    input_info = network.getInputsInfo().begin()->second;
    input_name = network.getInputsInfo().begin()->first;
    

Would be helpful.

**Comment by ilya-lavrenov** [comment]
Transition guide is enough https://docs.openvino.ai/latest/openvino_2_0_transition_guide.html
We cannot explain each line of code, users have to spend a bit of time to understand the simple difference in syntax.

**Comment by adammpolak** [comment]
> 

It is interesting because this link you mention: https://docs.openvino.ai/latest/openvino_2_0_transition_guide.html
Does not provide any helpful direction and does provide any guide.
The articles that actually provide some direction are:
https://docs.openvino.ai/latest/openvino_2_0_preprocessing.html
https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html

but these are "hidden" and need to be found.

If those pages were built out, or a 3rd added that included the other common v1.0 operations and their v2.0 equivalents OpenVINO would have a passable transition guide.

I think all it would take is take the v1.0 samples, find the common procedures, and write out their v2.0 equivalents.
