### ISSUE TITLE
how to reduce the binary size of the generated dll when using gpu plugin?

### ISSUE THREAD

**Issue by dapengchen123** [openvinotoolkit/openvino#17301]
1, I am now can static openvino lib to generate gpu based dll to build other applications.  
2, The current dll is only related to one model. The dll size is around 15MB, which is too big for delivery.
3, I have known that  the selective build is  available for cpu but not for gpu.
4, Is these any solutions or hint that for me to reduce the binary for the specific dll?

thanks for advices.

**Comment by vladimir-paramuzov** [comment]
@dapengchen123  You may try to build with `-DENABLE_ONEDNN_FOR_GPU=OFF` cmake option which disabled kernels that utilize XMX instructions of discrete GPUs. I think with this option dll size will be ~9-10MB

**Comment by dapengchen123** [comment]
@vladimir-paramuzov, thanks for replying. In fact, I have already turned this option off.
The detailed cmake configuration is shown below:

-- Inference Engine enabled features:
--
--     CI_BUILD_NUMBER: custom__
--     ENABLE_LTO = OFF
--     OS_FOLDER = OFF
--     USE_BUILD_TYPE_SUBFOLDER = OFF
--     TREAT_WARNING_AS_ERROR = ON
--     ENABLE_INTEGRITYCHECK = OFF
--     ENABLE_SANITIZER = OFF
--     ENABLE_UB_SANITIZER = OFF
--     ENABLE_THREAD_SANITIZER = OFF
--     ENABLE_COVERAGE = OFF
--     ENABLE_SSE42 = OFF
--     ENABLE_AVX2 = OFF
--     ENABLE_AVX512F = OFF
--     BUILD_SHARED_LIBS = OFF
--     ENABLE_FASTER_BUILD = OFF
--     ENABLE_CPPLINT = OFF
--     ENABLE_CPPLINT_REPORT = OFF
--     ENABLE_CLANG_FORMAT = OFF
--     ENABLE_NCC_STYLE = OFF
--     VERBOSE_BUILD = OFF
--     ENABLE_UNSAFE_LOCATIONS = OFF
--     ENABLE_FUZZING = OFF
--     ENABLE_INTEL_CPU = OFF
--     ENABLE_TESTS = OFF
--     ENABLE_STRICT_DEPENDENCIES = ON
--     ENABLE_CLDNN = ON
--     ENABLE_INTEL_GPU = ON
--     ENABLE_ONEDNN_FOR_GPU = OFF
--     ENABLE_PROFILING_ITT = OFF
--     ENABLE_PROFILING_FILTER = ALL
--     ENABLE_PROFILING_FIRST_INFERENCE = ON
--     SELECTIVE_BUILD = ON
--     ENABLE_ERROR_HIGHLIGHT = OFF
--     ENABLE_PYTHON = OFF
--     ENABLE_DOCS = OFF
--     THREADING = TBB
--     ENABLE_TBBBIND_2_5 = OFF
--     ENABLE_INTEL_GNA = OFF
--     ENABLE_IR_V7_READER = OFF
--     ENABLE_GAPI_PREPROCESSING = OFF
--     ENABLE_MULTI = OFF
--     ENABLE_AUTO = OFF
--     ENABLE_AUTO_BATCH = OFF
--     ENABLE_HETERO = OFF
--     ENABLE_TEMPLATE = OFF
--     ENABLE_INTEL_MYRIAD_COMMON = OFF
--     ENABLE_INTEL_MYRIAD = OFF
--     ENABLE_MYRIAD_NO_BOOT = OFF
--     ENABLE_GAPI_TESTS = OFF
--     GAPI_TEST_PERF = OFF
--     ENABLE_MYRIAD_MVNC_TESTS = OFF
--     ENABLE_DATA = OFF
--     ENABLE_BEH_TESTS = OFF
--     ENABLE_FUNCTIONAL_TESTS = OFF
--     ENABLE_SAMPLES = OFF
--     ENABLE_OPENCV = OFF
--     ENABLE_V7_SERIALIZE = OFF
--     ENABLE_TBB_RELEASE_ONLY = OFF
--     ENABLE_SYSTEM_PUGIXML = OFF
--     ENABLE_DEBUG_CAPS = OFF
--     ENABLE_GPU_DEBUG_CAPS = OFF
--     ENABLE_CPU_DEBUG_CAPS = OFF
--     ENABLE_OV_ONNX_FRONTEND = OFF
--     ENABLE_OV_PADDLE_FRONTEND = OFF
--     ENABLE_OV_IR_FRONTEND = ON
--     ENABLE_OV_TF_FRONTEND = OFF
--     ENABLE_SYSTEM_PROTOBUF = OFF
--     ENABLE_OPENVINO_DEBUG = OFF
--     ENABLE_REQUIREMENTS_INSTALL = ON


Are there any other options I can turn off ? or How should I modify the source code to further reduce the binaries for a specific model?

**Comment by ilya-lavrenov** [comment]
Hi @dapengchen123 

You can also use different cmake build type which also affects binary size:
- By default, cmake selects `Release` as build type, which on Unix sets `-O3` optimization level. It hints the compiler to apply aggressive optimization like unrolling and vectoring the loops. Since you are using GPU, most of compute happens on device itself, so `-O3` does not lead to significant improvements on inference part, but it still can be useful to optimize `compile_model` stage, where reference implementation can be executed during model optimization stage. It heavily depends on the model, whether compiling with `-O3` improves / degrades `compile_model` stage. So, you can try `MinRelSize` (see [cmake docs](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) for reference)
- If you are on Linux (gcc compiler), you are recommended to use `-DENABLE_LTO` (see [cmake docs](https://cmake.org/cmake/help/latest/module/CheckIPOSupported.html)), while also optimizes binary size during link stage (the option is turned off by default, because it can be time consuming. Recommendation is to use gcc 10 or higher where this stage is performed using multiple threads)

**Comment by dapengchen123** [comment]
@ilya-lavrenov , thanks for your reply.  

(1) In fact,  I am on Windows platform with VS 2022 . I have tried MinRelSize to replace Release to generate dll. It still works, but the DLL size changed from 16.497KB to 16. 469KB,  I hope to keep the DLL size under 10MB.   

(2) I wonder whether reducing some unused network layers or options can help to reduce the size fo the final dll.

**Comment by ilya-lavrenov** [comment]
For CPU device we were able to generate binary less than 5 MB with conditional compilation feature (Ubuntu 20.04 with LTO and default compiler). So, looks like for GPU plugin the feature is also required to have as smaller size as possible.

**Comment by dapengchen123** [comment]
Yes. It is a product requirement. The customer would like us to optimize the size of provided SDK libraries as small as possible. This is because we previously utilize MNN (provided by Alibaba), which has a smaller size of under 10MB.  

At the same time, we found OpenVino can better utilize the resources of intel GPU. With the GPU mode, the computational cost of CPU significantly drops,  so we can choose to use a larger model for better performance. 

Currently, the DLL size is a problem. I have read the documents of conditional compilation. I believe the GPU plugin can have a similar feature by turning off some layers or operations. 

Developing the conditional compilation for GPU is appreciated. But currently, can you provide a straightforward way for me to do experiments for reducing the size.  I do not mind the DLL is specifically designed for the specific model.

**Comment by vladimir-paramuzov** [comment]
@dapengchen123 Thanks for the inputs. 

I think conditional compilation may still be useful for you as it may reduce binary size of common OV parts. And if you're ready to do some experiments with GPU plugin sources I'd suggest starting with the following changes:
 - Remove registrations of unused operations here: https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
 - Remove registrations of unused primitives here: https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/src/graph/impls/ocl/register.cpp 
 -  Remove registrations of unused kernels from https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_selector.cpp and similar files
 - And finally remove unused kernel files from https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/src/kernel_selector/cl_kernels

I think that may help to reduce gpu plugin binary size to 6-7MB, so hopefully total runtime size will be <10MB

**Comment by dapengchen123** [comment]
@vladimir-paramuzov, thanks for your advice. I will try and report the results later.

**Comment by dapengchen123** [comment]
@vladimir-paramuzov   I am now following the  1st step to continue to use conditional compilation to reduce the common OV part. 

Yes, the DLL size reduces from  16.497KB to 12.121KB. But the DLL cannot work. 

I have examined that it fails at " **this->compiled_model = core.compile_model(model,"GPU")**;"

There are also some differences that appeared during the generation of the DLL: the warnings are different.

Without conditional compilation, the warning is LNK4217:

The warning is:
[build]     正在创建库 D:/workspace_coding/visual_studio/MatingSDK_openvino_v3/build/mat/Release/MatService.lib 和对象 D:/workspace_coding/visual_studio/MatingSDK_openvino_v3/build/mat/Release/MatService.exp
[build] LINK : warning LNK4217: 符号“??0GeneralError@InferenceEngine@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (public: __cdecl InferenceEngine::GeneralError::GeneralError(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &))”(在“ openvino.lib(ov_tensor.obj)”中定义)已由“openvino_intel_gpu_kernels.lib(convert_color_kernel_base.obj)”(函数“"public: void __cdecl InferenceEngine::details::ThrowNow<struct InferenceEngine::GeneralError>::operator<<=(class std::basic_ostream<char,struct std::char_traits<char> > const &)" (??_3?$ThrowNow@UGeneralError@InferenceEngine@@@details@InferenceEngine@@QEAAXAEBV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)”中)导入 [D:\workspace_coding\visual_studio\MatingSDK_openvino_v3\build\mat\MatService.vcxproj]
[build] Starting build
[build] Build finished with exit code -1
[build]   MatService.vcxproj -> D:\workspace_coding\visual_studio\MatingSDK_openvino_v3\build\mat\Release\MatService.dll
[build]   Building Custom Rule D:/workspace_coding/visual_studio/MatingSDK_openvino_v3/mat/CMakeLists.txt
[build]   demo.vcxproj -> D:\workspace_coding\visual_studio\MatingSDK_openvino_v3\build\mat\Release\demo.exe
[driver] Build completed: 00:00:06.683
[build] Build finished with exit code 0

With conditional Compilation, the warning is LINK 4286.

[build]     正在创建库 D:/workspace_coding/visual_studio/MatingSDK_openvino_v3/build/mat/Release/MatService.lib 和对象 D:/workspace_coding/visual_studio/MatingSDK_openvino_v3/build/mat/Release/MatService.exp
[build] LINK : warning LNK4098: 默认库“LIBCMT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library [D:\workspace_coding\visual_studio\MatingSDK_openvino_v3\build\mat\MatService.vcxproj]
[build]   正在生成代码
[build]   已完成代码的生成
[build] LINK : warning LNK4286: 符号“??0GeneralError@InferenceEngine@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (public: __cdecl InferenceEngine::GeneralError::GeneralError(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &))”(在“openvino.lib(ov_tensor.obj)”中定义)已由“openvino_intel_gpu_kernels.lib(convert_color_kernel_base.obj)”导入 [D:\workspace_coding\visual_studio\MatingSDK_openvino_v3\build\mat\MatService.vcxproj]
[build]   MatService.vcxproj -> D:\workspace_coding\visual_studio\MatingSDK_openvino_v3\build\mat\Release\MatService.dll
[build]   demo.vcxproj -> D:\workspace_coding\visual_studio\MatingSDK_openvino_v3\build\mat\Release\demo.exe
[driver] Build completed: 00:00:11.417
[build] Build finished with exit code 0

Do you have any ideas to fix this ?

**Comment by dapengchen123** [comment]
1,  I previously used 2022.1 version, and the conditional compilation fails. The DLL can be generated, but the model inference fails.

2, Then I change the branch to the tag 2023.0427. Conditional compilation helps. It can reduce the size of both CPU and GPU-based DLLs.  Yes, it reduces the common OV parts.

The generated cvs files are different.  Besides different versions, another problem may be the option DENABLE_PLUGINS_XML.
I  have followed  the steps in  "https://github.com/openvinotoolkit/openvino/blob/2023.0.0.dev20230427/.ci/azure/windows_conditional_compilation.yml.". It works.
