### ISSUE TITLE
Question: C-API Example for simple "batch" inference?

### ISSUE THREAD

**Issue by ifadams** [openvinotoolkit/openvino#1733]
I'm working on creating a C based batch-inference program.

I can see there is the opportunity to do multiple inputs using the SSD C example, but its not clear to me what is specific and idiomatic to that example versus basic classification using an existing model (e.g. Alexnet). 

Are there plans (or am I simply missing it) for a batch async inference example like provided in the C++ samples? In the interim are there any references or examples elsewhere you could point me towards?

Thanks for your time and patience.

**Comment by jgespino** [comment]
Hi @ifadams 

Thanks for reaching out. I don't believe we have an example of batch inference in C. I recommend taking a look at the C++ classification_demo to help you create an application in C.
https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/classification_demo

Regards,
Jesus

**Comment by ifadams** [comment]
Hi Jesus,

Yeah, I took a look at the C++ example already, I had some minor confusion though in translating it to the C-API as the C++ examples rely heavily on abstractions and vectors, so I was a bit hazy on how to pack the infer request buffer with the input images.

Thanks though, I'll keep looking and poking at this.

**Comment by ilya-lavrenov** [comment]
@xiaoxial can we update C sample to demonstrate batch usage?

**Comment by xiaoxial** [comment]
Does the batch usage means multiple inputs with one infer request or multiple infer requests? The  C++ sample  hello_reshape_ssd  demonstrates how to  do multiple inputs inference with one infer request.

**Comment by ifadams** [comment]
@xiaoxial 

I'm referring to multiple inputs within a single request. I did see the C "hello_reshape" example had multiple inputs, but it was not clear to me what (if anything) was specific and idiomatic to that example versus a basic inference like the "hello_inference" examples.

**Comment by jgespino** [comment]
@xiaoxial Could you take a look at this request?

**Comment by xiaoxial** [comment]
@jgespino @ifadams  Yeah, I had look the request. In fact, you can refer to the C "hello_classification" and "object_detection_sample_ssd" to create a application with multiple inputs. 
So now we need to provide a  c classification sample that supports multiple inputs and supports to set batch size for network?

**Comment by jgespino** [comment]
@ifadams Could you confirm if this is what you are looking for?

**Comment by ifadams** [comment]
Yes, that would be helpful if possible.

Basically, while I recognize the object_detection_sample_ssd does do batching with the c-interface, for a relative novice like myself its relatively difficult to see whats going on with the additional complexity of that example.

If there was something simpler like the hello_classification example for the C API, using batch sizes that you can set, that would be very useful.

**Comment by jgespino** [comment]
Hi @ifadams 

I submitted a feature request for the development team to consider. We appreciate your input to improve OpenVINO!

@xiaoxial FYI

Regards,
Jesus

Ref. 39960

**Comment by jgespino** [comment]
This has been addressed by the following pull request that has been merged to master branch and should be included in the next software release.

https://github.com/openvinotoolkit/openvino/pull/3875

Regards,
Jesus
