### ISSUE TITLE
[Bug] openvino does not work with other shells besides bash

### ISSUE THREAD

**Issue by Thodoris1999** [openvinotoolkit/openvino#17392]
##### Detailed description
`setupvars.sh` as well as other shell scripts in this repository require the information of the location of the running script, which is unfortunately famously [not posix standardized](https://stackoverflow.com/a/29835459) and each shell implementation provides its own workaround. This repository uses `bash`'s workaround (`BASH_SOURCE[0]`), which silently does not work for any other shell implementation.

##### Solutions
- Create a complex function that gets the source path for each shell implementation
- Provide multiple setup scripts, e.g. `setupvars.bash` and `setupvars.zsh` (ROS approach)
- Use a user set environment variable (OPENVINO_HOME) and default to default path/symlink (/opt/intel/openvino), failing if it doesn't exist (nvidia approach)

##### Steps to reproduce
Execute any of openvino's scripts with a non bash shell

**Comment by avitial** [comment]
Ref. 111482

**Comment by p-wysocki** [comment]
Hi, should this issue be a GFI? Is it agreed that it should be done and is it a good fit for new contributors? @artanokhov

**Comment by Thodoris1999** [comment]
I'd take a look at this issue if it is decided which of the 3 options is best

**Comment by ilya-lavrenov** [comment]
I would keep a single script..
