### ISSUE TITLE
[Bug] RuntimeError: cldnn program build failed! [GPU] get_dims() is called for dynamic shape, when inference mobilenetV2 with dynamic shape on iGPU

### ISSUE THREAD

**Issue by biyuehuang** [openvinotoolkit/openvino#17403]
##### System information (version)

mobilenetV2 with dynamic shape can inference on CPU, but failed on iGPU

$ benchmark_app -m model_onnx/mobilenetv2/end2end.onnx -d CPU -shape [?,3,?,?] -data_shape [1,3,224,224][8,3,224,224][16,3,224,224]
[Step 11/11] Dumping statistics report
[ INFO ] Count:            3876 iterations
[ INFO ] Duration:         60067.97 ms
[ INFO ] Latency:
[ INFO ]    Median:        73.35 ms
[ INFO ]    Average:       77.08 ms
[ INFO ]    Min:           4.26 ms
[ INFO ]    Max:           197.38 ms
[ INFO ] Throughput:   64.53 FPS

$ benchmark_app -m model_onnx/mobilenetv2/end2end.onnx -d GPU.1 -shape [?,3,?,?] -data_shape [1,3,224,224][8,3,224,224][16,3,224,224]
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ]
[ INFO ] Device info:
[ INFO ] GPU
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(GPU.1) performance hint will be set to THROUGHPUT.
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 20.78 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Model inputs:
[ INFO ]     input (node: input) : f32 / [...] / [?,3,?,?]
[ INFO ] Model outputs:
[ INFO ]     output (node: output) : f32 / [...] / [?,1000]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Model batch size: 1
[ INFO ] Reshaping model: 'input': [?,3,?,?]
[ INFO ] Reshape model took 9.19 ms
[Step 6/11] Configuring input of the model
[ INFO ] Model inputs:
[ INFO ]     input (node: input) : f32 / [...] / [?,3,?,?]
[ INFO ] Model outputs:
[ INFO ]     output (node: output) : f32 / [...] / [?,1000]
[Step 7/11] Loading the model to the device
[ ERROR ] cldnn program build failed! [GPU] get_dims() is called for dynamic shape
Traceback (most recent call last):
  File "/home/a380/miniconda3/envs/ov2022.3/lib/python3.8/site-packages/openvino/tools/benchmark/main.py", line 414, in main
    compiled_model = benchmark.core.compile_model(model, benchmark.device)
  File "/home/a380/miniconda3/envs/ov2022.3/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: cldnn program build failed! [GPU] get_dims() is called for dynamic shape

**Comment by Aznie-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
