### ISSUE TITLE
[CPU][Inference][CPP]An exception occurred when loaded the PaddleOCR recognition model and inference

### ISSUE THREAD

**Issue by yao-xiaofei** [openvinotoolkit/openvino#17438]
System information (version):

- OpenVINO Source => Runtime
- OpenVINO Version => Version 2022.3
- Operating System / Platform => Windows 11 64 Bit
- Compiler => Visual Studio 2022
- Problem classification: PaddleOCR-2.6.0 
- Device use: CPU Intel i7-12700H
- Model name: ch_PP-OCRv3_rec_infer

Detailed description:

When loading the PaddleOCR recognition model and start inference, an error occurred at this point: 
infer_request.infer()
![1](https://github.com/openvinotoolkit/openvino/assets/54102844/e7e5d369-ee76-47c5-ad92-203c394c3d5d)

here's my demo code:

`	const std::string mRecModelPath = "Models/OCR/PaddleOCR/ch_PP-OCRv3_rec_infer/inference.pdmodel";
	const std::string mRecLabelPath = "Models/OCR/PaddleOCR/ch_PP-OCRv3_rec_infer/ppocr_keys_v1.txt";
	const int32_t mRecImageHeight = 48;
	const int32_t mRecImageWidth = 320;
	const std::vector<int32_t> mRecImageShape = { 3, mRecImageHeight, mRecImageWidth };
	std::vector<std::string> mRecLabels;
	ov::CompiledModel mRecModel;

	void ReadDict(std::vector<std::string>& results)
	{
		std::ifstream in(mRecLabelPath);
		std::string line;
		if (in)
		{
			while (std::getline(in, line))
			{
				results.push_back(line);
			}
		}
	}

	void Resize(const cv::Mat& img, cv::Mat& resizeImg, float whRatio, const std::vector<int32_t>& recImageShape)
	{
		int32_t imgC, imgH, imgW;
		imgC = recImageShape[0];
		imgH = recImageShape[1];
		imgW = recImageShape[2];

		imgW = int32_t(imgH * whRatio);

		float ratio = float(img.cols) / float(img.rows);
		int32_t resizeW, resizeH;

		if (ceilf(imgH * ratio) > imgW)
			resizeW = imgW;
		else
			resizeW = int32_t(ceilf(imgH * ratio));

		cv::resize(img, resizeImg, cv::Size(resizeW, imgH), 0.f, 0.f, cv::INTER_LINEAR);
		cv::copyMakeBorder(resizeImg, resizeImg, 0, 0, 0, int32_t(imgW - resizeImg.cols), cv::BORDER_CONSTANT, { 127, 127, 127 });
	}

	void Normalize(cv::Mat* im, const std::vector<float>& mean, const std::vector<float>& scale, const bool isScale)
	{
		double e = 1.0;
		if (isScale)
		{
			e /= 255.0;
		}
		(*im).convertTo(*im, CV_32FC3, e);
		std::vector<cv::Mat> bgrChannels(3);
		cv::split(*im, bgrChannels);
		for (auto i = 0; i < bgrChannels.size(); i++)
		{
			bgrChannels[i].convertTo(bgrChannels[i], CV_32FC1, 1.0 * scale[i], (0.0 - mean[i]) * scale[i]);
		}
		cv::merge(bgrChannels, *im);
	}

	void PermuteImage(const cv::Mat src, float* data)
	{
		int rh = src.rows;
		int rw = src.cols;
		int rc = src.channels();
		for (int i = 0; i < rc; ++i)
		{
			cv::extractChannel(src, cv::Mat(rh, rw, CV_32FC1, data + i * rh * rw), i);
		}
	}

	template <class ForwardIterator>
	inline static size_t ArgMax(ForwardIterator first, ForwardIterator last)
	{
		return std::distance(first, std::max_element(first, last));
	}

	void main(cv::Mat src,OCRResult& result)
	{
		ov::Core core;
		std::shared_ptr<ov::Model> model = core.read_model(mRecModelPath);
		model->reshape({ {ov::Dimension(1, 6), mRecImageShape[0], mRecImageShape[1], -1} });
		ov::CompiledModel recModel = core.compile_model(model, DL_DEVICE);
		ReadDict(mRecLabels);
		mRecLabels.insert(mRecLabels.begin(), "#");
		mRecLabels.push_back(" ");

		int32_t h = src.rows;
		int32_t w = src.cols;

		float whRatio = w * 1. / h;

		int32_t imgH = mRecImageShape[1];
		int32_t imgW = mRecImageShape[2];

		float whRatioMax = imgW * 1.0 / imgH;

		int32_t batchWidth = imgW;

		std::vector<float> mean = { 0.5f, 0.5f, 0.5f };
		std::vector<float> scale = { 1 / 0.5f, 1 / 0.5f, 1 / 0.5f };
		bool isScale = true;

		cv::Mat resizeImg;
		Resize(src, resizeImg, whRatioMax, mRecImageShape);

		Normalize(&resizeImg, mean, scale, isScale);

		batchWidth = std::max(resizeImg.cols, batchWidth);

		std::vector<float> input(3 * imgH * batchWidth, 0.0f);
		ov::Shape intput_shape = { (size_t)1, 3, (size_t)imgH, (size_t)batchWidth };
		PermuteImage(resizeImg, input.data());
		auto inputPort = mRecModel.input();

		ov::element::Type t = inputPort.get_element_type();
		ov::Tensor inputTensor(inputPort.get_element_type(), intput_shape, input.data());

		ov::InferRequest inferRequest = mRecModel.create_infer_request();
		inferRequest.set_input_tensor(inputTensor);

		/*************************************************************/
		/***********   Exception occurred at this Line    *************/
		/*************************************************************/
		inferRequest.infer();

		auto output = inferRequest.get_output_tensor();
		const float* outData = output.data<const float>();
		auto predictShape = output.get_shape();

		for (int m = 0; m < predictShape[0]; m++)
		{
			std::string strRes;
			int argmaxIdx;
			int lastIndex = 0;
			float score = 0.f;
			int count = 0;
			float maxValue = 0.0f;

			for (int n = 0; n < predictShape[1]; n++)
			{
				// get idx
				argmaxIdx = int(ArgMax(&outData[(m * predictShape[1] + n) * predictShape[2]], &outData[(m * predictShape[1] + n + 1) * predictShape[2]]));
				// get score
				maxValue = float(*std::max_element(&outData[(m * predictShape[1] + n) * predictShape[2]], &outData[(m * predictShape[1] + n + 1) * predictShape[2]]));

				if (argmaxIdx > 0 && (!(n > 0 && argmaxIdx == lastIndex)))
				{
					score += maxValue;
					count += 1;
					strRes += mRecLabels[argmaxIdx];
				}
				lastIndex = argmaxIdx;
			}
			score /= count;
			if (std::isnan(score)) {
				continue;
			}

			result.Text = strRes;
			result.Score = score;
		}

	}
`

**Comment by wenjiew** [comment]
@meiyang-intel Can you help take a look? Thanks!

**Comment by meiyang-intel** [comment]
Hi @yao-xiaofei , seems the openvino related code in your demo is not correct. Recommend to take openvino benchmark_app as a reference to write the openvino related code in your demo https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/benchmark_app/main.cpp . 

Besides, I also running the benchmark_app with ch_PP-OCRv3_rec_infer. It works fine.
`model=/home/iot/tmp/tmp/ch_PP-OCRv3_rec_infer/inference.pdmodel

/home/iot/tmp/benchmark_app/samples_bin/benchmark_app -m ${model} -t 5 \
        -shape x[-1,3,48,-1] \
        -layout x[NCHW] \
        -data_shape x[1,3,48,160][1,3,48,320] \
        -mean_values [127.5,127.5,127.5] \
        -scale_values [127.5,127.5,127.5] \
        -d CPU

[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2023.1.0-10925-1d59dab3628
[ INFO ]
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2023.1.0-10925-1d59dab3628
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT.
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 55.85 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Network inputs:
[ INFO ]     x (node: x) : f32 / [...] / [?,3,48,?]
[ INFO ] Network outputs:
[ INFO ]     softmax_5.tmp_0 (node: softmax_5.tmp_0) : f32 / [...] / [?,1..,6625]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Number of test configurations is calculated basing on -data_shape parameter
[ INFO ] Reshaping model: 'x': [?,3,48,?]
[ INFO ] Reshape model took 24.27 ms
[Step 6/11] Configuring input of the model
[ WARNING ] Mean/scale values are fused into the model. This slows down performance compared to --imean and --iscale which existed before
[ INFO ] Model batch size: 1
[ INFO ] Network inputs:
[ INFO ]     x (node: x) : u8 / [N,C,H,W] / [?,3,48,?]
[ INFO ] Network outputs:
[ INFO ]     softmax_5.tmp_0 (node: softmax_5.tmp_0) : f32 / [...] / [?,1..,6625]
[Step 7/11] Loading the model to the device
[ INFO ] Compile model took 228.39 ms
[Step 8/11] Querying optimal runtime parameters
[ INFO ] Model:
[ INFO ]   NETWORK_NAME: Model0
[ INFO ]   OPTIMAL_NUMBER_OF_INFER_REQUESTS: 11
[ INFO ]   NUM_STREAMS: 11
[ INFO ]   AFFINITY: CORE
[ INFO ]   INFERENCE_NUM_THREADS: 44
[ INFO ]   PERF_COUNT: NO
[ INFO ]   INFERENCE_PRECISION_HINT: f32
[ INFO ]   PERFORMANCE_HINT: THROUGHPUT
[ INFO ]   EXECUTION_MODE_HINT: PERFORMANCE
[ INFO ]   PERFORMANCE_HINT_NUM_REQUESTS: 0
[ INFO ]   ENABLE_CPU_PINNING: YES
[ INFO ]   SCHEDULING_CORE_TYPE: ANY_CORE
[ INFO ]   ENABLE_HYPER_THREADING: NO
[ INFO ]   EXECUTION_DEVICES: CPU
[ INFO ]   CPU_DENORMALS_OPTIMIZATION: NO
[ INFO ]   CPU_SPARSE_WEIGHTS_DECOMPRESSION_RATE: 1
[Step 9/11] Creating infer requests and preparing input tensors
[ INFO ] Test Config 0
[ INFO ] x  ([N,C,H,W], u8, [1,3,48,160], dyn:[?,3,48,?]):      random (image/numpy array is expected)
[ INFO ] Test Config 1
[ INFO ] x  ([N,C,H,W], u8, [1,3,48,320], dyn:[?,3,48,?]):      random (image/numpy array is expected)
[Step 10/11] Measuring performance (Start inference asynchronously, 11 inference requests, limits: 5000 ms duration)
[ INFO ] Benchmarking in full mode (inputs filling are included in measurement loop).
[ INFO ] First inference took 61.50 ms
[Step 11/11] Dumping statistics report
[ INFO ] Execution Devices: [ CPU ]
[ INFO ] Count:               9405 iterations
[ INFO ] Duration:            5011.75 ms
[ INFO ] Latency:
[ INFO ]    Median:           6.43 ms
[ INFO ]    Average:          5.82 ms
[ INFO ]    Min:              3.65 ms
[ INFO ]    Max:              47.92 ms
[ INFO ] Throughput:          1876.59 FPS`

**Comment by meiyang-intel** [comment]
> > meiyang-intel
> 
> **Hi @meiyang-intel, thanks for your suggestion. I tried to run the benchmark_app with ch_PP-OCRv3_rec_infer, but two errors occurred:**
> 
> -m D:/Workspace/Visual/trunk/Assembly/Models/OCR/PaddleOCR/ch_PP-OCRv3_rec_infer/inference.pdmodel -t 5 -shape x[-1,3,48,-1] -layout x[NCHW] -data_shape x[1,3,48,160][1,3,48,320] -mean_values [127.5,127.5,127.5] -scale_values [127.5,127.5,127.5] -d CPU -i x:C:/Users/Xiaofei/Desktop/1.png
> 
> [Step 1/11] Parsing and validating input arguments [ INFO ] Parsing input parameters ERROR: unknown command line flag 'mean_values' ERROR: unknown command line flag 'scale_values'
> 
> **Then I changed to the following command and ran it again. But the exception, I metioned at the beginning of this issue, still occurred. The OpenVINO version: 2022.3**
> 
> -m D:/Workspace/Visual/trunk/Assembly/Models/OCR/PaddleOCR/ch_PP-OCRv3_rec_infer/inference.pdmodel -t 5 -shape x[-1,3,48,-1] -layout x[NCHW] -data_shape x[1,3,48,160][1,3,48,320] -imean [127.5,127.5,127.5] -iscale [127.5,127.5,127.5] -d CPU -i x:C:/Users/Xiaofei/Desktop/1.png
> 
> [Step 1/11] Parsing and validating input arguments [ INFO ] Parsing input parameters [ INFO ] For input x 1 files were added. [Step 2/11] Loading OpenVINO Runtime [ INFO ] OpenVINO: [ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3 [ INFO ] [ INFO ] Device info: [ INFO ] CPU [ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3 [ INFO ] [ INFO ] [Step 3/11] Setting device configuration [ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT. [Step 4/11] Reading model files [ INFO ] Loading model files [ INFO ] Read model took 646.85 ms [ INFO ] Original model I/O parameters: [ INFO ] Network inputs: [ INFO ] x (node: x) : f32 / [...] / [?,3,48,?] [ INFO ] Network outputs: [ INFO ] softmax_5.tmp_0 (node: softmax_5.tmp_0) : f32 / [...] / [?,1..,6625] [Step 5/11] Resizing model to match image sizes and given batch [ INFO ] Number of test configurations is calculated basing on -data_shape parameter [ INFO ] Reshaping model: 'x': [?,3,48,?] [ INFO ] Reshape model took 303.48 ms [Step 6/11] Configuring input of the model [ INFO ] Model batch size: 1 [ INFO ] Network inputs: [ INFO ] x (node: x) : u8 / [N,C,H,W] / [?,3,48,?] [ INFO ] Network outputs: [ INFO ] softmax_5.tmp_0 (node: softmax_5.tmp_0) : f32 / [...] / [?,1..,6625] [Step 7/11] Loading the model to the device [ INFO ] Compile model took 4311.23 ms [Step 8/11] Querying optimal runtime parameters [ INFO ] Model: [ INFO ] NETWORK_NAME: Model0 [ INFO ] OPTIMAL_NUMBER_OF_INFER_REQUESTS: 6 [ INFO ] NUM_STREAMS: 6 [ INFO ] AFFINITY: HYBRID_AWARE [ INFO ] INFERENCE_NUM_THREADS: 18 [ INFO ] PERF_COUNT: NO [ INFO ] INFERENCE_PRECISION_HINT: f32 [ INFO ] PERFORMANCE_HINT: THROUGHPUT [ INFO ] PERFORMANCE_HINT_NUM_REQUESTS: 0 [Step 9/11] Creating infer requests and preparing input tensors [ WARNING ] Image is resized from (73, 28) to (160, 48) [ WARNING ] Image is resized from (73, 28) to (320, 48) [ INFO ] Test Config 0 [ INFO ] x ([N,C,H,W], u8, [1,3,48,160], dyn:[?,3,48,?]): C:/Users/Xiaofei/Desktop/1.png [ INFO ] Test Config 1 [ INFO ] x ([N,C,H,W], u8, [1,3,48,320], dyn:[?,3,48,?]): C:/Users/Xiaofei/Desktop/1.png [Step 10/11] Measuring performance (Start inference asynchronously, 6 inference requests, limits: 5000 ms duration) [ INFO ] Benchmarking in full mode (inputs filling are included in measurement loop).
> 
> ### Microsoft Visual C++ Runtime Library
> Debug Assertion Failed!
> 
> Program: ...dows\runtime\bin\intel64\Debug\openvino_intel_cpu_plugind.dll File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\vector Line: 1501
> 
> Expression: vector subscript out of range
> 
> For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.
> 
> (Press Retry to debug the application)

Ah, in releases/2022/3, the parameter is imean and iscale. The command should be 
`
/home/iot/tmp/benchmark_app/samples_bin/benchmark_app -m ${model} -t 5
-shape x[-1,3,48,-1]
-layout x[NCHW]
-data_shape x[1,3,48,160][1,3,48,320]
-imean [127.5,127.5,127.5]
-iscale [127.5,127.5,127.5]
-d CPU
`

**Comment by Iffa-Meah** [comment]
@yao-xiaofei   @meiyang-intel 
I also validated the model ch_PP-OCRv3_rec_infer using [custom PaddleOCR with OpenVINO code](https://docs.openvino.ai/2022.1/notebooks/405-paddle-ocr-webcam-with-output.html) & I didn't encounter any issues.
The model with the correct code/commands should work.

<img width="314" alt="paddleocr" src="https://github.com/openvinotoolkit/openvino/assets/79643476/cae423c9-460a-4905-bd2c-9c1592f64af2">


<img width="150" alt="model" src="https://github.com/openvinotoolkit/openvino/assets/79643476/0f42744a-811c-4b0f-a1bf-a0b4f612cd66">

**Comment by yao-xiaofei** [comment]
**Hi @meiyang-intel,**

**Forgive my poor text editing skills.**
**As mentioned above, I've tried the params -iscale & -imean，but the exception, I mentioned at the begining of this issue, still occured.**

**here is the command and info:**

-m D:/Workspace/Visual/trunk/Assembly/Models/OCR/PaddleOCR/ch_PP-OCRv3_rec_infer/inference.pdmodel
-t 5
-shape
x[-1,3,48,-1]
-layout x[NCHW]
-data_shape x[1,3,48,160][1,3,48,320]
-imean [127.5,127.5,127.5]
-iscale [127.5,127.5,127.5]
-d CPU
-i x:C:/Users/Xiaofei/Desktop/1.png

[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[ INFO ] For input x 1 files were added.
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ]
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT.
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 646.85 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Network inputs:
[ INFO ] x (node: x) : f32 / [...] / [?,3,48,?]
[ INFO ] Network outputs:
[ INFO ] softmax_5.tmp_0 (node: softmax_5.tmp_0) : f32 / [...] / [?,1..,6625]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Number of test configurations is calculated basing on -data_shape parameter
[ INFO ] Reshaping model: 'x': [?,3,48,?]
[ INFO ] Reshape model took 303.48 ms
[Step 6/11] Configuring input of the model
[ INFO ] Model batch size: 1
[ INFO ] Network inputs:
[ INFO ] x (node: x) : u8 / [N,C,H,W] / [?,3,48,?]
[ INFO ] Network outputs:
[ INFO ] softmax_5.tmp_0 (node: softmax_5.tmp_0) : f32 / [...] / [?,1..,6625]
[Step 7/11] Loading the model to the device
[ INFO ] Compile model took 4311.23 ms
[Step 8/11] Querying optimal runtime parameters
[ INFO ] Model:
[ INFO ] NETWORK_NAME: Model0
[ INFO ] OPTIMAL_NUMBER_OF_INFER_REQUESTS: 6
[ INFO ] NUM_STREAMS: 6
[ INFO ] AFFINITY: HYBRID_AWARE
[ INFO ] INFERENCE_NUM_THREADS: 18
[ INFO ] PERF_COUNT: NO
[ INFO ] INFERENCE_PRECISION_HINT: f32
[ INFO ] PERFORMANCE_HINT: THROUGHPUT
[ INFO ] PERFORMANCE_HINT_NUM_REQUESTS: 0
[Step 9/11] Creating infer requests and preparing input tensors
[ WARNING ] Image is resized from (73, 28) to (160, 48)
[ WARNING ] Image is resized from (73, 28) to (320, 48)
[ INFO ] Test Config 0
[ INFO ] x ([N,C,H,W], u8, [1,3,48,160], dyn:[?,3,48,?]): C:/Users/Xiaofei/Desktop/1.png
[ INFO ] Test Config 1
[ INFO ] x ([N,C,H,W], u8, [1,3,48,320], dyn:[?,3,48,?]): C:/Users/Xiaofei/Desktop/1.png
[Step 10/11] Measuring performance (Start inference asynchronously, 6 inference requests, limits: 5000 ms duration)
[ INFO ] Benchmarking in full mode (inputs filling are included in measurement loop).

Microsoft Visual C++ Runtime Library
Debug Assertion Failed!

Program: ...dows\runtime\bin\intel64\Debug\openvino_intel_cpu_plugind.dll
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\vector
Line: 1501

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

**Comment by yao-xiaofei** [comment]
> **Hi @meiyang-intel,**
> 
> **Forgive my poor text editing skills. Maybe you didn't see it above.** **I've tried the params -iscale & -imean，but the exception, I mentioned at the begining of this issue, still occured.**
> 
> **here is the command and info:**
> 
> -m D:/Workspace/Visual/trunk/Assembly/Models/OCR/PaddleOCR/ch_PP-OCRv3_rec_infer/inference.pdmodel -t 5 -shape x[-1,3,48,-1] -layout x[NCHW] -data_shape x[1,3,48,160][1,3,48,320] -imean [127.5,127.5,127.5] -iscale [127.5,127.5,127.5] -d CPU -i x:C:/Users/Xiaofei/Desktop/1.png
> 
> [Step 1/11] Parsing and validating input arguments [ INFO ] Parsing input parameters [ INFO ] For input x 1 files were added. [Step 2/11] Loading OpenVINO Runtime [ INFO ] OpenVINO: [ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3 [ INFO ] [ INFO ] Device info: [ INFO ] CPU [ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3 [ INFO ] [ INFO ] [Step 3/11] Setting device configuration [ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to THROUGHPUT. [Step 4/11] Reading model files [ INFO ] Loading model files [ INFO ] Read model took 646.85 ms [ INFO ] Original model I/O parameters: [ INFO ] Network inputs: [ INFO ] x (node: x) : f32 / [...] / [?,3,48,?] [ INFO ] Network outputs: [ INFO ] softmax_5.tmp_0 (node: softmax_5.tmp_0) : f32 / [...] / [?,1..,6625] [Step 5/11] Resizing model to match image sizes and given batch [ INFO ] Number of test configurations is calculated basing on -data_shape parameter [ INFO ] Reshaping model: 'x': [?,3,48,?] [ INFO ] Reshape model took 303.48 ms [Step 6/11] Configuring input of the model [ INFO ] Model batch size: 1 [ INFO ] Network inputs: [ INFO ] x (node: x) : u8 / [N,C,H,W] / [?,3,48,?] [ INFO ] Network outputs: [ INFO ] softmax_5.tmp_0 (node: softmax_5.tmp_0) : f32 / [...] / [?,1..,6625] [Step 7/11] Loading the model to the device [ INFO ] Compile model took 4311.23 ms [Step 8/11] Querying optimal runtime parameters [ INFO ] Model: [ INFO ] NETWORK_NAME: Model0 [ INFO ] OPTIMAL_NUMBER_OF_INFER_REQUESTS: 6 [ INFO ] NUM_STREAMS: 6 [ INFO ] AFFINITY: HYBRID_AWARE [ INFO ] INFERENCE_NUM_THREADS: 18 [ INFO ] PERF_COUNT: NO [ INFO ] INFERENCE_PRECISION_HINT: f32 [ INFO ] PERFORMANCE_HINT: THROUGHPUT [ INFO ] PERFORMANCE_HINT_NUM_REQUESTS: 0 [Step 9/11] Creating infer requests and preparing input tensors [ WARNING ] Image is resized from (73, 28) to (160, 48) [ WARNING ] Image is resized from (73, 28) to (320, 48) [ INFO ] Test Config 0 [ INFO ] x ([N,C,H,W], u8, [1,3,48,160], dyn:[?,3,48,?]): C:/Users/Xiaofei/Desktop/1.png [ INFO ] Test Config 1 [ INFO ] x ([N,C,H,W], u8, [1,3,48,320], dyn:[?,3,48,?]): C:/Users/Xiaofei/Desktop/1.png [Step 10/11] Measuring performance (Start inference asynchronously, 6 inference requests, limits: 5000 ms duration) [ INFO ] Benchmarking in full mode (inputs filling are included in measurement loop).
> 
> ### Microsoft Visual C++ Runtime Library
> Debug Assertion Failed!
> 
> Program: ...dows\runtime\bin\intel64\Debug\openvino_intel_cpu_plugind.dll File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\vector Line: 1501
> 
> Expression: vector subscript out of range
> 
> For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.
> 
> (Press Retry to debug the application)

Hi  @meiyang-intel,

I tried to update OpenVINO Runtime version to 2023.0.0 from this path:

https://storage.openvinotoolkit.org/repositories/openvino/packages/master/2023.0.0.dev20230427/

the exception no longer appears. Maybe it's bug in version 2022.3?

Thanks for your help and advice!
