### ISSUE TITLE
[Bug] Model Optimizer internal error

### ISSUE THREAD

**Issue by glucasol** [openvinotoolkit/openvino#17461]
Hi everyone,
I am trying to run model optimizer to convert an .onnx model to IR format, but it gives an internal error.
This is the command I ran:
````
mo --input_model q_model.onnx
````
**And this is the error:**
````
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check 'unknown_operators.empty()' failed at src/frontends/onnx/frontend/src/core/graph.cpp:213:
OpenVINO does not support the following ONNX operations: com.microsoft.QLinearAdd, com.microsoft.QLinearConcat, com.microsoft.QLinearMul

[ ERROR ]  Traceback (most recent call last):
  File "/home/gabrieloliveira/anaconda3/lib/python3.9/site-packages/openvino/tools/mo/main.py", line 50, in main
    ngraph_function = convert_model(**argv)
  File "/home/gabrieloliveira/anaconda3/lib/python3.9/site-packages/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "/home/gabrieloliveira/anaconda3/lib/python3.9/site-packages/openvino/tools/mo/convert_impl.py", line 937, in _convert
    raise e.with_traceback(None)
RuntimeError: Check 'unknown_operators.empty()' failed at src/frontends/onnx/frontend/src/core/graph.cpp:213:
OpenVINO does not support the following ONNX operations: com.microsoft.QLinearAdd, com.microsoft.QLinearConcat, com.microsoft.QLinearMul


[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

````

Can anyone help me?

Thanks!!

**Comment by tomdol** [comment]
Hi,

OpenVINO currently doesn't support those operators but there's an internal ticket where a discussion is happening. The ticket number is 108945. Please stay tuned for some updates.

**Comment by glucasol** [comment]
Hi @tomdol,
Thanks for your answer. How can I know if and when this feature will be implemented?

**Comment by tomdol** [comment]
For now we have a discussion and analysis in progress. We can update this GH issue when the decision is made. In the meantime you could try to implement those operators as ONNX frontend extensions or directly in the OpenVINO code (and compile the whole software afterwards). Would that be a temporary solution for you?

**Comment by glucasol** [comment]
Thanks, I would appreciate if you could update this issue when you decide to implement or not.
Meanwhile, I will try to implement these operators as a temporary solution. Do you have any follow up tutorial explaining how to do that?

**Comment by andrei-kochin** [comment]
@glucasol you can you conversion extensions to make OV able to read the model:
https://docs.openvino.ai/2023.0/openvino_docs_Extensibility_UG_Frontend_Extensions.html#mapping-to-multiple-operations-with-conversionextension
