### ISSUE TITLE
Cannot run single-image-super-resolution-1033-fp16.xml on GPU

### ISSUE THREAD

**Issue by umed** [openvinotoolkit/openvino#175]
Hi guys,

dldt: 2019 R1.1
OS: Ubuntu 18.04

When I try to run inference on GPU with **single-image-super-resolution-1033-fp16.xml** model I face following error:

> network allocation failed: /dldt/inference-engine/thirdparty/clDNN/src/reshape.cpp at line: 87
> Error has occured for: Reshape:86
> Output layout count(=16588800) is not equal to: input layout count(=72)
> Output layout of reshape primitive chan
> /dldt/inference-engine/include/details/ie_exception_conversion.hpp:71
> Setting pipeline to NULL ...
> Freeing pipeline ...

**Comment by shubha-ramani** [comment]
Dearest @umed,

If you look at our [Linux OpenVino Doc](http://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html) Ubuntu 18 is not supported yet.  Some community members have hacked it and gotten OpenVino working on Ubuntu 18 though. Please try the single-image-super-resolution sample on Ubuntu 16.04 and report back on this forum.

> Operating Systems

Ubuntu 16.04.x long-term support (LTS), 64-bit: Minimum supported kernel is 4.14
CentOS 7.4, 64-bit (for target only)
Yocto Project Poky Jethro v2.0.3, 64-bit (for target only and requires modifications)

Thanks for your patience !

Shubha

**Comment by umed** [comment]
@shubha-ramani actually, problem is related to clDNN. It doesn't support models with more than 4 dimensions.

**Comment by shubha-ramani** [comment]
Dear @umed,
Fair enough. Can you kindly tell me which code you are using for inference ?

Thanks,

Shubha

**Comment by umed** [comment]
@shubha-ramani ,

Do you mean my code? If so you can take a look [here](https://github.com/floor10/upscaler/blob/master/gst/elements/upscaler/openvino_inference.cpp).
If you mean dldt I'm building it out of sources from tag `2019 R1.1`.

By the way, I didn't mean to be rude. Thanks for your answers 👍

**Comment by shubha-ramani** [comment]
@umed 

Thanks for your concern but I didn't think you were rude at all ! So I saw your code. Is there anyway you can put it into the format of a main.cpp ? I wrote a lengthy answer to [issue 173](https://github.com/opencv/dldt/issues/173) on how to do that. If I massaged every single one of our forum customer's projects into a sample format, i'm sure you understand that I would never get any work done. Since you wrote your code, it should be easy for you to do. Would it be possible ? Because if I can reproduce the issue (and make it so that our developers can also repro it) I could easily file a bug and/or help you otherwise.

Thanks,

Shubha

**Comment by umed** [comment]
@shubha-ramani ,

Yeah, I will try.

**Comment by shubha-ramani** [comment]
Dear @umed ,
Thank You. I think you'll find the transformation simple. Once you do that, report back here and I'll reproduce and debug. Thanks so much for your cooperation !

Shubha

**Comment by shubha-ramani** [comment]
Dear @umed 
Perhaps I can save you the trouble. Please read [this forum post](https://software.intel.com/en-us/forums/computer-vision/topic/807472). The super-resolution demo on GPU has been fixed in OpenVino 2019R2 (which unfortunately you don't have yet).

Thanks,

Shubha

**Comment by vladimir-paramuzov** [comment]
@umed Do I understand correctly that the issue has been fixed and we can close the issue?

**Comment by umed** [comment]
@vladimir-paramuzov , closing it. Thanks!
