### ISSUE TITLE
Expand linter coverage to `openvino/tests/layer_tests`

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#17501]
# Expand Python linter coverage to `openvino/tests/layer_tests`

## Context
Currently there is no linter check in `openvino/tests/layer_tests`. You can find the layer tests find [here](https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests). New linter check can be added by expanding an existing code style workflow.

Help will be provided by the Python team when asked.

## Tips

- [A workflow for code style](https://github.com/openvinotoolkit/openvino/blob/master/.github/workflows/py_checks.yml) is already present in the repository
- It should be enough to expand it with another step for `openvino/tests/layer_tests`
- It may be a good idea to use some code formatter to fix all existing linter issues automatically

## Example
1. Add the following code to https://github.com/openvinotoolkit/openvino/blob/master/.github/workflows/py_checks.yml

```bash
- name: Run flake8 on tests/layer_tests
  run: python -m flake8 ./ --config=setup.cfg
  working-directory: tests/layer_tests

- name: Run mypy on tests/layer_tests
  run: python -m mypy ./ --config-file ./setup.cfg
  working-directory: tests/layer_tests
```

2. Run the checks locally
3. Fix the issues manually or using some tool
4. Prepare a Pull Request and wait for review

Contact points:
@p-wysocki
@jiwaszki
@akuporos

Ticket: 105564

**Comment by SANTHOSH-MAMIDISETTI** [comment]
I actually don't have much Idea what is it , but would love learn what it is and work on it , and contribute to opensource , Could you please assign me this  @p-wysocki @jiwaszki

**Comment by SANTHOSH-MAMIDISETTI** [comment]
Title: Issue encountered while building OpenVINO on Ubuntu 20.04
---

Description:
I have forked and cloned the OpenVINO repository to my Ubuntu 20.04 computer. I am following the build instructions provided in the [link](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_linux.md). However, I encountered an issue during the build process. Here is the screenshot of the error: 
![Screenshot from 2023-05-14 15-26-12](https://github.com/openvinotoolkit/openvino/assets/92091342/c6321145-0135-45cd-9766-af2b3ac912e3)


I would like to know if the build was successful despite the error, or if there is something else I need to do to resolve it. I also didn't install the optional [Intel Graphics Compute Runtime for OpenCL Driver package 19.41.14441](https://github.com/intel/compute-runtime/releases/tag/19.41.14441) for inference on Intel integrated GPUs.

Versions of the required software I have installed :
![Screenshot from 2023-05-14 15-34-18](https://github.com/openvinotoolkit/openvino/assets/92091342/5c411335-c69d-48d6-8b69-cecd46ca522f).

Can someone help me understand what might be causing this issue? @p-wysocki  @jiwaszki  @akuporos 

---

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@p-wysocki  @jiwaszki @akuporos   , I ran the command 
`python3 -m flake8 ./openvino/tests/layer_tests --config=/home/santu/github/openvino/samples/python/setup.cfg > ~/Desktop/test.txt`
which procuced me an output text file of size 3MB .  which looked something like this :
![Screenshot from 2023-0
[flake8_output.txt](https://github.com/openvinotoolkit/openvino/files/11472238/flake8_output.txt)
5-14 20-31-26](https://github.com/openvinotoolkit/openvino/assets/92091342/d24ad6d0-9cc8-4cb6-9180-4e7a095f29f8)
now I need to  correct all those and then commit , push my changes and then make a PR ? is that the thing to be done ? or am I missing something .

**Comment by SANTHOSH-MAMIDISETTI** [comment]
any suggestions on how to apply the changes @p-wysocki @jiwaszki @akuporos , I tries using black and autopep8 ; but I think the results aren't that good :upside_down_face:  , help is much appreciated.

**Comment by p-wysocki** [comment]
Hi @SANTHOSH-MAMIDISETTI, thank you so much! I'll get back to you as soon as possible and answer all your questions. :)

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> If the file with flake8 output is that big, correcting all the errors at once is a very time consuming task. I think that instead we could enable the linter workflow only on the files that changed - that way, if someone makes a PR to tests and changes for example 3 files, he has to fix linter only in those three.
> 
> I suggest the following behavior:
> 
> 1. Add flake8/mypy running on files which were modified only
> 2. When anyone makes a PR modifying a file in `openvino/tests` the linter runs a check on this particular file only
> 3. Python files in `openvino/tests` are being fixed one by one, instead of all at once with an insane amount of work
> 
> I found a GitHub Action which could be used https://github.com/tj-actions/changed-files
> 
> What do you think @SANTHOSH-MAMIDISETTI? cc @mvafin @jiwaszki @akuporos

 I have gone through the link and it seems good if we can include it , I'll try to add it , and would appreciate your help 
  when I face any difficulties .  @p-wysocki @akuporos @jiwaszki 
> 
> > I tries using black and autopep8 ; but I think the results aren't that good 🙃
> 
> Also I can see that `black` doesn't fix all the issues according to your comment, but maybe it fixes at least some of them? Could you please check if it does, even by output file size?

  Yes  sir , It is actually fixing many , but I guess in that process it is ending up creating some ,I 'll confirm it and let you know ASAP
> 
> > I encountered an issue during the build process. Can someone help me understand what might be causing this issue?
> 
> Could you please scroll the logs up? The errors during build display early, and the build stops a few seconds later. There should be an error displayed with white font. Out of the gate, some things you may check:
> 
> 1. run `git submodule update --init` in the repository
> 2. add `-DENABLE_INTEL_GPU=OFF` to your CMake

Thank you  @p-wysocki sir , I'll let you know once I do it .

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@p-wysocki  As disccussed earlier ,  I have compared the file size before and after formatting the files with black by the command 
`black layer_tests/`, before running it the output file had   45,487  lines .
![before_black](https://github.com/openvinotoolkit/openvino/assets/92091342/5dd5540b-389e-45b5-bc6e-612cf71d5f25) 

Once I ran the command , it almost became double 81.277 lines 

![after_black](https://github.com/openvinotoolkit/openvino/assets/92091342/9511cf17-a1ce-40f9-a30e-a2be51bd6fdd) . It seems black isn't helping that much . 


and after adding the line `-DENABLE_INTEL_GPU=OFF` to cmake  the build was successful.

**Comment by p-wysocki** [comment]
> I have gone through the link and it seems good if we can include it , I'll try to add it , and would appreciate your help
when I face any difficulties

Of course, just let us know. :)

> It seems black isn't helping that much

Thank you for checking! I think that fixing all the errors is a colossal task, we should opt for running linter on changed files only. Could you please use https://github.com/tj-actions/changed-files and change a single test file to see if the linter runs in precommit? That would help out a lot.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@p-wysocki  , is it fine if I start to work over it once my exams are done , it will take maximum of  8 days .

**Comment by mlukasze** [comment]
hey @SANTHOSH-MAMIDISETTI 
I wonder how it's going on your side.
Do you need any support from us, or simply a little bit more time? :)

**Comment by SANTHOSH-MAMIDISETTI** [comment]
Hello @mlukasze sir, my exams are just over and I'll start working from now.As of now I am clear about what has to be done, and will definitely message if I need some assistance in any case.

**Comment by mlukasze** [comment]
that's ok, only collecting a status.
Keeping fingers crossed for your exams!

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@mlukasze  @p-wysocki @jiwaszki @akuporos , I have made a PR , although I wasn't able to trigger the workflow , I have followed the guidelines and implemented it , waiting for maintainer to approve the workflow .  Please let me know if I have missed anything , Thanks

**Comment by p-wysocki** [comment]
Thank you for the PR! https://github.com/openvinotoolkit/openvino/pull/17956

> I wasn't able to trigger the workflow

If you mean the Python API workflow, it ran - the details are in my review. Overall your PR looks great, I think that we can just test everything works and proceed with review and merge.

**Comment by p-wysocki** [comment]
The PR has been merged. Thank you for your contribution @SANTHOSH-MAMIDISETTI!
