### ISSUE TITLE
MacOS Build Dependency List

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [openvinotoolkit/openvino#17523]
##### System information (version)
- OpenVINO Source => GitHub 
- OpenVINO Version => Github Master Branch
- Operating System / Platform => MacOS Ventura 13.3.1
	CPU:	2.5 GHz Quad-Core Intel Core i7
	GPU:	NVIDIA GeForce GT 750M 2 GB, Intel Iris Pro 1536 MB0
	MEM:	16GB
- Compiler => Cmake, Clang, GCC (Xcode 14.1)
- Problem classification: Build Instructions
- Device use: NCS2

##### Detailed description
I'm working through the MacOS build instructions and after resolving several CMake dependency issues, I've now realised that there are a few more coming down the road.
So, I'm wondering if anyone has a list of what's needed; e.g. protobuf, snappy, gflags, etc., and, if possible, instructions (or links to) on how to install.  I gather that somethings can be installed with homebrew, but not necessarily everything.

**Comment by ilyachur** [comment]
Hi @Napoleon-BlownApart ,

The current up-to-date build instructions are here: https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md I think you also used the instruction from this scope for macOS.

If we are talking about the list of components like: "protobuf, snappy, gflags, etc.", the OpenVINO allows to use system components if it is installed on the host, in other case OpenVINO will download all required components and use them for the build automatically, you don't need to install them manually.

These components are internal and in the majority cases use as static dependencies, so these components also don't introduce any additional dependencies on applications which use OpenVINO.

**Comment by ilya-lavrenov** [comment]
> doxyrest, and sphinx

It's not required if you don't build documentation.

> anaconda

It's not needed at all. Any python 3.7 and higher is OK

> warnings/comments in my output. Are any of them of concern?

Most useful warning is about Python API - if you want to work with OpenVINO API via Python, install;
```bash
python3 -m pip install -r /Users/user/Programming/Neural_Compute_2/openvino/src/bindings/python/src/compatibility/openvino/requirements-dev.txt
```

**Comment by ilya-lavrenov** [comment]
OpenCV is a different product. Use https://github.com/opencv/opencv to ask questions.

**Comment by Napoleon-BlownApart** [comment]
I tried to have a look at the update but I'm not certain if I can see the changes yet because the merge is awaiting approval.
I did however, see some changes that referred to the `arm64` architecture, though I have an intel i7 cpu in my Mac, so I'm not sure that is relevant for me.  I'll keep an eye out for the update to become visible.

**Comment by ilya-lavrenov** [comment]
> I tried to have a look at the update but I'm not certain if I can see the changes yet because the merge is awaiting approval. I did however, see some changes that referred to the `arm64` architecture, though I have an intel i7 cpu in my Mac, so I'm not sure that is relevant for me. I'll keep an eye out for the update to become visible.

Brew support both x86_64 and arm64. So, the list of dependencies is exactly the same, but you are right that I have to update Intel macOS instructions as well.

**Comment by Napoleon-BlownApart** [comment]
@ilyachur @ilya-lavrenov thank you for your assistance!

I have successfully built OpenVINO Dev 2023.1.0-10999 (`master`) using OpenCV 4.7.0, also built from source.
