### ISSUE TITLE
[Bug] - IRDFT not support 2d input format 

### ISSUE THREAD

**Issue by truicam** [openvinotoolkit/openvino#17544]
IRDFT not support 2d input format.

Currently Inside:
https://github.com/openvinotoolkit/openvino/blob/master/src/core/reference/src/runtime/reference/irdft.cpp

outer_fft_result will have rank=1. But first part of the function is not necessary if rank=2.

Probably just if rank=2, should skip first fft from function and for this case "extend_to_hermitian_symmetric" should be apply direct on the input.

**Comment by avitial** [comment]
Ref. 112743

**Comment by truicam** [comment]
The test not run was: 

// IRDFT openvino not support 2d input tensor
// https://github.com/openvinotoolkit/openvino/issues/17544
INSTANTIATE_TEST_SUITE_P(DISABLED_smoke_RDFT_2dx, VPUXRdftLayerTest,
                         combine({{10, 2}},         // input shapes
                                 {{0}},             // axes
                                 {{}, {3}, {11}}),  // signal sizes
                         RDFTLayerTest::getTestCaseName);

Where:
const auto combine = [](const std::vector<InferenceEngine::SizeVector>& inputShapes,
                        const std::vector<std::vector<int64_t>>& axes,
                        const std::vector<std::vector<int64_t>>& signalSizes) {
    return testing::Combine(testing::ValuesIn(inputShapes), testing::ValuesIn(inputPrecisions), testing::ValuesIn(axes),
                            testing::ValuesIn(signalSizes), testing::ValuesIn(opTypes),
                           testing::Values(LayerTestsUtils::testPlatformTargetDevice));
};

const std::vector<ngraph::helpers::DFTOpType> opTypes = {
        //ngraph::helpers::DFTOpType::FORWARD,
        ngraph::helpers::DFTOpType::INVERSE,
};

const std::vector<InferenceEngine::Precision> inputPrecisions = {
        InferenceEngine::Precision::FP16,
};

This was the only one issue. 2d tensor rank not work.
Thanks.

**Comment by mbencer** [comment]
@truicam Thank you for your info. We have plans to provide the fix very soon.

**Comment by mbencer** [comment]
The bug was fixed in https://github.com/openvinotoolkit/openvino/pull/18525, Please re-open if ony problems.
