### ISSUE TITLE
How to run my openvino inference on single thread on CPU in c++

### ISSUE THREAD

**Issue by ashray21** [openvinotoolkit/openvino#17566]
I'm not able to run my program on single thread on CPU in c++. Is their any way?
I found that we can set CPU_THREADS_NUM = 1 but how we can set this in c++?

**Comment by ilya-lavrenov** [comment]
```c++
core.compile_model(model, "CPU", ov::inference_threads(1));
```

**Comment by ashray21** [comment]
@ilya-lavrenov 
I'm using Openvino version - 2022.3.0 

I tried ov::inference_threads(1) but there is member of such name and showing error. If you meant by ov::inference_num_threads(1) I also tried this but it fails to run my program on single thread.

**Comment by ilya-lavrenov** [comment]
>  I tried this but it fails to run my program on single thread. Is their any other way?

Error message? The fail is not expected.

**Comment by ashray21** [comment]
@ilya-lavrenov 
After using ov::inference_num_threads(1) it is not able to run my program on single thread

**Comment by ilya-lavrenov** [comment]
> it is not able

without error messages  / descriptive information we cannot help

**Comment by wangleis** [comment]
@ashray21 Please try `core.compile_model(model, "CPU", ov::num_streams(1), ov::inference_num_threads(1))`;

**Comment by ashray21** [comment]
@wangleis 
I tried what you suggested but it still running on multiple threads. Moreover, I found that core.comple_model() is making multiple threads.

**Comment by ashray21** [comment]
@wangleis 
I got your point but actually my objective was to run the entire openvino runtime inference program under single thread.

**Comment by wangleis** [comment]
@ashray21 Then please build OpenVINO with `-DTHREADING=SEQ` to disable threading optimizations.

**Comment by ashray21** [comment]
@wangleis 
While building OpenVINO with -DTHREADING=SEQ its showing error.

**Comment by wangleis** [comment]
@ashray21 What's your platform and OS?

**Comment by ashray21** [comment]
@wangleis 
My problem got solved. Thanks
