### ISSUE TITLE
Extend ONNX Frontend with `com.microsoft.GatherND` operator

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#17577]
## Context
Neural networks are graphs consisting of nodes called operators. Each operator corresponds to a mathematical function, usually described in framework's documentation or an AI standard, such as ONNX.

OpenVINO ONNX Frontend is a component responsible for working with ONNX graphs and requires implementation of different ONNX operators in order to use ONNX models.

This task requires extending OpenVINO ONNX Frontend with `com.microsoft.GatherND` operator.

Necessary help will be provided by ONNX Fronted team.

## Operator specification
Operator details can be found in [official ONNX Runtime docs](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.GatherND).

## Todo list
1. Create `.hpp` and `.cpp` files for `com.microsoft.GatherND` [here](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op)
2. Prepare an implementation of this operator in form of a function. It should be placed in [opset 1 namespace](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/unique.hpp#L13). You can use the implementation of standard [ONNX GatherND operator](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/gather_nd.cpp) as a reference
3. Register the function in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560) while keeping alphabetical order
4. Create test model(s) in [ONNX models directory](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/tests/models/com.microsoft). OpenVINO test infrastructure then converts prototxt files to ONNX models - you will use those models later in tests
5. Add tests covering all use cases [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp)

More details in [adding operators to ONNX Frontend guide](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md)

## Resources
- Guides on [ONNX Frontend architecture](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/architecture.md) and [ONNX Frontend tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/tests.md) are also available
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- You can also see a [blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

## Example PRs
- https://github.com/openvinotoolkit/openvino/pull/15076
- https://github.com/openvinotoolkit/openvino/pull/14936
- https://github.com/openvinotoolkit/openvino/pull/12510

## Contact points
@tomdol
@mbencer
@p-wysocki
Don't hesitate to reach out, we're here to help!

**Comment by vashist99** [comment]
Hi. I would like to contribute to close this issue if it's not taken.

**Comment by p-wysocki** [comment]
Hello @vashist99! I assigned the issue to you, thanks for taking a look and please let us know if you have any questions. :)

**Comment by vashist99** [comment]
Hi! 
First of all, thank you for assigning this issue to me, :) resolving this issue has piqued my interest in OpenVINO and has motivated me contribute more!

I also hope this comment section is the right point of contact for my doubts.

I have implemented the GatherND operator extension. Next, I have to add the test models and implement the testcases.
I have a several doubts regarding this:
1) I was able to build the code with the steps given in the README,  but how can I run my newly added code, just to check if it's working right? 

2) I observed the existing prototxt models but I am not able to understand how to add a prototxt model for GatherND. I could not find any documentation for that as well. please help me.

3) I observed the exisiting C++ test points in "onnx_import_com_microsoft.in.cpp". I saw that each test point needs input, skip and expected output. My questions regarding this:
- What exactly is "skip"?
- How do I generate the sample input and how can I generate the expected output?

If this is not the appropriate point of contact for doubts, please let me know how I can reach out.

Thank you! :)

**Comment by p-wysocki** [comment]
Hello @vashist99! I'm not able to answer most of your questions as ONNX Frontend is outside of my area of expertise, @mbencer could you please take a look?

**Comment by vashist99** [comment]
@mbencer can you please help?

**Comment by mbencer** [comment]
Hi @vashist99, sorry for long time responding. About you questions:
> I was able to build the code with the steps given in the README, but how can I run my newly added code, just to check if it's working right?

The best way to check the implementation is writing unit tests. To achieve it, you should build OpenVINO with `-DENABLE_TESTS=ON` flag (you can use also `--target ov_onnx_frontend_tests` to avoid build all tests, which is time-consuming). Our basic approach to creating unit tests is preparing simple *.prototxt model (with only one operator, `GatherND` in your case). 

> I observed the existing prototxt models but I am not able to understand how to add a prototxt model for GatherND. I could not find any documentation for that as well. please help me.

You can just copy some existing `.prototxt` model and change name, domain, inputs, attributes. The other method can be using onnx helpers to create such a model (more details in https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#creating-an-onnx-model-using-helper-functions), saving your model as *.onnx via `onnx.save` and conversion to prototxt using https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_prototxt_converter.py.

> What exactly is "skip"?

If I understand your question correctly, `skip` is just a name of input of `SkipLayerNormalization` operator.

> How do I generate the sample input and how can I generate the expected output?

It's a good question. In a case, when we are implementing an operator from `com.microsoft` domain we can use `onnxruntime` to generate reference results. It means that you can generate some random (but acceptable) inputs of  `GatherND` and run inference of such models via onnxruntime. It can looks like:
```
import onnxruntime as rt

sess = rt.InferenceSession(path_to_your_test_model)

output_names = [out.name for out in sess.get_outputs()]
test_data = np.ones(shape).astype(np.float32) # your test data
ort_results = sess.run(output_names, {"input_name": test_data})

for idx, val in enumerate(ort_results):
    print(val)
```
> Finally, how can I run my testcases?

If you build OV with enabled tests, in your bin dir, (like openvino/bin/intel64/Release), you can find `ov_onnx_frontend_tests` test binary (with *.exe on Windows). Note, that you can filer tests to run using ` --gtest_filter`, like `./ov_onnx_frontend_tests --gtest_filter=*gather_nd*`.

**Comment by p-wysocki** [comment]
I'm returning the task to being open due to current assignee's inactivity.

**Comment by AvaterClasher** [comment]
Hello I would like to contribute to this if its not taken.

**Comment by p-wysocki** [comment]
I assigned you, thanks for your time!

**Comment by p-wysocki** [comment]
@AvaterClasher could you please confirm whether you're still working on this?

**Comment by AvaterClasher** [comment]
No sorry i couldnt do it.

**Comment by siddhant-0707** [comment]
.take
PR #21709

**Comment by p-wysocki** [comment]
I am happy to announce that we have created a channel dedicated to Good First Issues support on our [Intel DevHub Discord server](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by mitruska** [comment]
Hello @siddhant-0707, please take a look at the latest review comments I've left for your PR https://github.com/openvinotoolkit/openvino/pull/21709.
