### ISSUE TITLE
[IE] So much useless log information 

### ISSUE THREAD

**Issue by mingmingtasd** [openvinotoolkit/openvino#1757]
When I use IE to do inference, there is so much log information as below:
`== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 2==== 1==== 1==== 28==== 28==== 0==== 1==== 1==== 1==== 1==== 28==== 28==== 1==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 1==== 1==== 1==== 0==== 28==== 28==== 1==== 224==== 224==== 1==== 3==== 1==== 2==== 2==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 1==== 1==== 1==== 3==== 1==== 2==== 2==== 1==== 3==== 1==== 1==== 1==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 2==== 2==== 1==== 3==== 1==== 1==== 1==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 0==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 1==== 3==== 1==== 1==== 1==== 0==== 1==== 1==== 1==== 3`

**Comment by jgespino** [comment]
Hi @mingmingtasd Please provide additional information.

- What version of OpenVINO are you using?
- Steps to reproduce: code, model, command
- Are you using C, C++, Python?

Regards,
Jesus

**Comment by mingmingtasd** [comment]
Sorry, I find it is not related to openvino. Close it, thanks!
