### ISSUE TITLE
Extend ONNX Frontend with `com.microsoft.Pad` operator

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#17576]
## Context
Neural networks are graphs consisting of nodes called operators. Each operator corresponds to a mathematical function, usually described in framework's documentation or an AI standard, such as ONNX.

OpenVINO ONNX Frontend is a component responsible for working with ONNX graphs and requires implementation of different ONNX operators in order to use ONNX models.

This task requires extending OpenVINO ONNX Frontend with `com.microsoft.Pad` operator.

Necessary help will be provided by ONNX Fronted team.

## Operator specification
Operator details can be found in [official ONNX Runtime docs](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Pad).

## Todo list
1. Create `.hpp` and `.cpp` files for `com.microsoft.Pad` [here](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op)
2. Prepare an implementation of this operator in form of a function. It should be placed in [opset 1 namespace](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/unique.hpp#L13). You can use the implementation of standard [ONNX Pad operator](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/pad.cpp) as a reference
3. Register the function in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560) while keeping alphabetical order
4. Create test model(s) in [ONNX models directory](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/tests/models/com.microsoft). OpenVINO test infrastructure then converts prototxt files to ONNX models - you will use those models later in tests
5. Add tests covering all use cases [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp)

More details in [adding operators to ONNX Frontend guide](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md)

## Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/wPuqAujS) - engage in discussions, ask questions and talk to OpenVINO developers
- Guides on [ONNX Frontend architecture](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/architecture.md) and [ONNX Frontend tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/tests.md) are also available
- You can also see a [blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

## Example PRs
- https://github.com/openvinotoolkit/openvino/pull/15076
- https://github.com/openvinotoolkit/openvino/pull/14936
- https://github.com/openvinotoolkit/openvino/pull/12510

## Contact points
@tomdol
@mbencer
@p-wysocki
Don't hesitate to reach out, we're here to help!

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@p-wysocki  I would like to work on it , can you please assign this to me

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@ilya-lavrenov  Thanks

**Comment by SANTHOSH-MAMIDISETTI** [comment]
Please correct me if I am wrong and if possible elaborate the when I went wrong . 

Based on my understanding ,  
- a ```<a_suitable_name>.cpp``` and  ```<a_suitable_name>.hpp``` files are to be added into the https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op/com.microsoft/ directory ( if I am correct , that is because com.microsoft.Pad operator falls into com.microsoft directory , which is present in https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op/ directory). and implement both the files created . 


- Once that is done , the file has to be registered by modifying the [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560) .
 - Followed by that create ```<a_suitable_name>.prototxt``` in modules directory ( which looks similar to a schema file ).
 - create test cases in [onnx_import_com_microsoft.in.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp) .
 


While naming the files , are there any naming conventions to be followed ?  If yes can I be linked to them .

Once I successfully implement ```<a_suitable_name>.cpp``` and  ```<a_suitable_name>.hpp``` files , I am planning for a Draft PR so that it can be reviewed . 

@p-wysocki @tomdol  @mbencer @ilya-lavrenov

**Comment by SANTHOSH-MAMIDISETTI** [comment]
Please correct me if I am wrong and if possible elaborate the when I went wrong . 

Based on my understanding ,  
- a ```<a_suitable_name>.cpp``` and  ```<a_suitable_name>.hpp``` files are to be added into the https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op/com.microsoft/ directory ( if I am correct , that is because com.microsoft.Pad operator falls into com.microsoft directory , which is present in https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op/ directory). and implement both the files created . 


- Once that is done , the file has to be registered by modifying the [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560) .
 - Followed by that create ```<a_suitable_name>.prototxt``` in modules directory ( which looks similar to a schema file ).
 - create test cases in [onnx_import_com_microsoft.in.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp) .
 


While naming the files , are there any naming conventions to be followed ?  If yes can I be linked to them .

Once I successfully implement ```<a_suitable_name>.cpp``` and  ```<a_suitable_name>.hpp``` files , I am planning for a Draft PR so that it can be reviewed . 

@p-wysocki @tomdol  @mbencer @ilya-lavrenov

**Comment by p-wysocki** [comment]
I think that your list of steps is correct, however I'm not that knowledgeable about this component - let's wait for @mbencer or @tomdol for final confirmation. Thanks for picking up that task :)

**Comment by tomdol** [comment]
@SANTHOSH-MAMIDISETTI everything you described is correct, just a small comment from my side - the prototxt files that you need to create represent tiny, synthetic models that will later be used to test your implementation. You can look for existing models with the standard ONNX Pad operator, they can be found in OV's repository in ONNX FE tests.

Before the implementation please have a look at the spec https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Pad and compare it with the standard ONNX Pad op https://github.com/onnx/onnx/blob/main/docs/Operators.md#Pad Then you should be able to figure out if any part of the standard Pad implementation from OV could be reused to implement the one from the com.microsoft domain.

**Comment by gaganchapa** [comment]
@tomdol @p-wysocki @SANTHOSH-MAMIDISETTI 

> ## Context
> Neural networks are graphs consisting of nodes called operators. Each operator corresponds to a mathematical function, usually described in framework's documentation or an AI standard, such as ONNX.
> 
> OpenVINO ONNX Frontend is a component responsible for working with ONNX graphs and requires implementation of different ONNX operators in order to use ONNX models.
> 
> This task requires extending OpenVINO ONNX Frontend with `com.microsoft.Pad` operator.
> 
What has to be actually implemented here ?  I mean where is the `com.microsoft.Pad` file ? Like i would like to help @SANTHOSH-MAMIDISETTI  or contribute , but I didn't quite understand , and even the other open issues are almost the same , hence replying here 
> Necessary help will be provided by ONNX Fronted team.
> 
> ## Operator specification
> Operator details can be found in [official ONNX Runtime docs](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Pad).
> 
> ## Todo list
> 1. Create `.hpp` and `.cpp` files for `com.microsoft.Pad` [here](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op)
> 2. Prepare an implementation of this operator in form of a function. It should be placed in [opset 1 namespace](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/unique.hpp#L13). You can use the implementation of standard [ONNX Pad operator](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/pad.cpp) as a reference
> 3. Register the function in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560) while keeping alphabetical order
> 4. Create test model(s) in [ONNX models directory](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/tests/models/com.microsoft). OpenVINO test infrastructure then converts prototxt files to ONNX models - you will use those models later in tests
> 5. Add tests covering all use cases [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp)
> 
> More details in [adding operators to ONNX Frontend guide](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md)
> 
> ## Resources
> * Guides on [ONNX Frontend architecture](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/architecture.md) and [ONNX Frontend tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/tests.md) are also available
> * Contribution guidelines can be found [here](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
> * You can also see a [blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)
> 
> ## Example PRs
> * [ONNX Unique op support #15076](https://github.com/openvinotoolkit/openvino/pull/15076)
> * [ONNX CastLike operator tests #14936](https://github.com/openvinotoolkit/openvino/pull/14936)
> * [[ONNX FE] Extend ONNX FE for operation GenerateProposals #12510](https://github.com/openvinotoolkit/openvino/pull/12510)
> 
> ## Contact points
> @tomdol @mbencer @p-wysocki Don't hesitate to reach out, we're here to help!

**Comment by p-wysocki** [comment]
@gaganchapa thanks for taking a look! `com.microsoft.Pad` is an ONNX Runtime operator, specification of which can be found under https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Pad. 

This operator needs to be implemented (translated to OpenVINO code) on our side. There are three similar issues, because three different operators need implementation. I'd recommend to start by taking a look at the example PRs and the operator documentation.

> I mean where is the com.microsoft.Pad file ?

It doesn't exist in OpenVINO - it needs to be created, which is exactly the first point in the Todo list section.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@tomdol @p-wysocki  I have completed the first and second step I think , I am going to make a draft pr so that i can be pointed out on my mistakes and what corrections can be made

**Comment by SANTHOSH-MAMIDISETTI** [comment]
https://github.com/openvinotoolkit/openvino/pull/18229

**Comment by p-wysocki** [comment]
Thanks @SANTHOSH-MAMIDISETTI, I'll find someone for review as soon as possible. :)

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> Thanks @SANTHOSH-MAMIDISETTI, I'll find someone for review as soon as possible. :)

Thank you ! @p-wysocki

**Comment by kshitij01042002** [comment]
Hi @SANTHOSH-MAMIDISETTI are you still working on this issue?

Re @p-wysocki if the contributor is not working on this issue is it fine if I take this up?

**Comment by p-wysocki** [comment]
Hello,

Of course @kshitij01042002, I assigned you. :)

**Comment by kshitij01042002** [comment]
Hi @p-wysocki
I think you just unassigned the previous contributor but forgot to assign me instead.

Also I had a doubt while writing test cases for the new operator what are the conditions to consider. cc: @gkrivor

**Comment by p-wysocki** [comment]
A good starting point for tests is usually operator specification from the standard. I see that Microsoft hasn't given any examples in https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Pad, but I think some basic tests can be similar to for example:
- https://pytorch.org/docs/stable/generated/torch.nn.functional.pad.html
- https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Pad-19
- https://www.tensorflow.org/api_docs/python/tf/pad

After that it would be good to look for edge cases and possible differences which make `com.microsoft.Pad` unique, they should be tested as well. I am not certain if/how many differences there are, but they have to be taken into account.

**Comment by kshitij01042002** [comment]
Thanks @p-wysocki. I'll look into the references.

**Comment by p-wysocki** [comment]
I'm not sure I understand - you can either write a first, very simple test to get the basic functionality working, and that can be in either OpenVINO tests or in a completely separate OpenVINO script. Already existing tests can serve as a template, just change the operator being imported. Please let me know if that answers your question. :)

**Comment by kshitij01042002** [comment]
Actually my question was is there a way that I can use and test the new operator as a end user?

**Comment by p-wysocki** [comment]
I suppose that we could find a model which is using this operator, but I'm not certain how to do it. @gkrivor do we have any list of models vs supported ops or something similar?

**Comment by gkrivor** [comment]
> I suppose that we could find a model which is using this operator, but I'm not certain how to do it. @gkrivor do we have any list of models vs supported ops or something similar?

Hi, I'm not sure I have something you mentioned, especially I can share because it sounds like a something private. As I heard this operation might be inserted after onnx-model optimization step. Do you know something about that?

**Comment by p-wysocki** [comment]
Sadly, no. I think until we find a model with this operator, the only way to reliably test it is to write our own tests.

**Comment by kshitij01042002** [comment]
Hi @p-wysocki @gkrivor I have opened a draft PR, can you PTAL :) Thanks. PR #20221 .

**Comment by YaritaiKoto** [comment]
Hi @p-wysocki, I'm working on another operator now (LessOrEqual), and I found I need some help to understand how to write tests as well. Specifically, how to generate the model's prototxt file?

**Comment by p-wysocki** [comment]
Hi @YaritaiKoto, I believe these are small files which can be written by hand. However I'm not sure, @gkrivor could you please give a definitive answer?

**Comment by YaritaiKoto** [comment]
> Hi @YaritaiKoto, I believe these are small files which can be written by hand. However I'm not sure, @gkrivor could you please give a definitive answer?

Thank you for your help! I used ONNX python API to generate and export the graph successfully and added some manual modifications. However, when I was trying to run the tests (`./<OV_REPO>/bin/intel64/Release/ov_onnx_frontend_tests`), the tests failed, and the program said `Unable to read the model: /openvino/bin/intel64/Release/./test_model_zoo/onnx/<MODEL_NAME>.onnx`, and there was no model in the `test_model_zoo/onnx` directory. Would you mind to take a look at this problem?

Some extra information: I configured CMAKE with these flags: 
```
cmake .. -DENABLE_TESTS=ON -DNGRAPH_UNIT_TEST_ENABLE=ON -DENABLE_FUNCTIONAL_TESTS=ON -DENABLE_INTEL_CPU=ON -DENABLE_INTEL_GNA=OFF -DENABLE_INTEL_GPU=OFF -DENABLE_PYTHON=ON -DENABLE_NCC_STYLE=OFF -DENABLE_DEBUG_CAPS=ON -DENABLE_CPU_DEBUG_CAPS=ON -DPYTHON_EXECUTABLE=`which python3`
```

**Comment by p-wysocki** [comment]
Hello @YaritaiKoto, are your questions still relevant? @gkrivor 

Hi @kshitij01042002, are you still working on https://github.com/openvinotoolkit/openvino/pull/2022? If not, can I reopen the task for other contributors?

**Comment by p-wysocki** [comment]
I'm reopening the task due to inactivity in the thread. If you're still working on the issue please let me know, I'll reassign you. :)

**Comment by siddhant-0707** [comment]
.take

**Comment by siddhant-0707** [comment]
PR #22000

**Comment by mitruska** [comment]
Hello @siddhant-0707, thanks for contributing.
I've reviewed the mentioned PR https://github.com/openvinotoolkit/openvino/pull/22000.
Please take a look at the latest review comments.

**Comment by mlukasze** [comment]
PR has been abandoned, awaiting for Contributor response to make further steps
