### ISSUE TITLE
Remove `test-generator` dependency from Model Optimizer

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#17619]
## Context
Model Optimizer is currently using an extension to `unittest` called `test-generator`. When you take a look at its [PyPI page](https://pypi.org/project/test-generator/0.1.2/#history) it turns out that the package hasn't been updated in a while.

It needs to be removed and all of its usages replaced with `unittest` functionality.

Help will be provided by OpenVINO team when asked.

## What needs to be done?
1. Find `test-generator` usage in `openvino/tools/mo` by searching the codebase for `@generator` decorators in tests
2. Replace the generator's functionality with `unittest`'s `subTest`
3. Confirm the tests work correctly
4. Remove `test-generator` dependency from `openvino/tools/constraints.txt` and `openvino/tools/mo/requirements.txt`
5. Create a Pull Request

## Resources
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Running MO tests](https://github.com/openvinotoolkit/openvino/tree/master/tools/mo)
- `unittest`'s `subTest` [functionality documentation](https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests)
- [Python requirements management in OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/requirements_management.md)
- [Blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

## Contact points:
@p-wysocki
@jiwaszki
@rkazants

Don't hesitate to reach out, we're here to help!

Ticket: 110705

**Comment by hvsp2704** [comment]
I want to start contributing to OpenVINO, I read the contribution guide as well. Could you please assign me this issue?
Do let me know if I need to go through something else as well.
Thank you

**Comment by p-wysocki** [comment]
Hello @hvsp2704, I assigned you. I think all the required info is already listed in the description. Please let us know if you need help with anything or have questions. :)

**Comment by hvsp2704** [comment]
@p-wysocki Thank you for assigning it to me. I surely let you know if I need any help.

**Comment by hvsp2704** [comment]
@p-wysocki I have made changes to one of the files where "@generator" has been used, could you please check and verify if what I have done is what was expected?
Please use the following link to check it out.

https://github.com/openvinotoolkit/openvino/compare/master...hvsp2704:openvino:RemoveTestGenerator

**Comment by hvsp2704** [comment]
@p-wysocki I have made changes to one of the files with "@generator" usage, could you please verify that the changes I have made are what was expected?

You can use the following link to check out the changes.
Link: https://github.com/openvinotoolkit/openvino/compare/master...hvsp2704:openvino:RemoveTestGenerator

**Comment by p-wysocki** [comment]
@hvsp2704 That's correct, that's exactly what was expected. It would be perfect if you could extend this change to other `test-generator` uses and submit a PR :) Please let me know if you need help with anything else, including submitting the Pull Request.

**Comment by hvsp2704** [comment]
@p-wysocki That's great. I'll let you know if I need any further help. Thanks

**Comment by mlukasze** [comment]
hey @hvsp2704 
I wonder how it's going on your side.
Do you need any support from us, or simply a little bit more time? :)

**Comment by hvsp2704** [comment]
Really sorry for the delay, I would need more time. I'll do it as soon as possible.

**Comment by hvsp2704** [comment]
@mlukasze @p-wysocki I'm able to find time to get this done. I'm really sorry. Please assign this to someone else. I apologize for the inconvenience caused due to this.

**Comment by p-wysocki** [comment]
No worries, this task is now free to be taken.

**Comment by PRATHAM-SPS** [comment]
Hello @p-wysocki , I'm interested in starting my contributions to OpenVINO and would appreciate it if you could assign me this issue. Thank you.

**Comment by PRATHAM-SPS** [comment]
@p-wysocki  @mlukasze  @jiwaszki  @rkazants 
Please review my file edits and let me know if I'm on the correct track. If it's accurate, I'll make the necessary changes to the other files accordingly. Thank you.

Link:- https://github.com/openvinotoolkit/openvino/compare/master...PRATHAM-SPS:openvino:generator_to_unittest

**Comment by PRATHAM-SPS** [comment]
Thank you for assigning the issue; I will make the modifications as you suggested.

**Comment by PRATHAM-SPS** [comment]
Hello, @p-wysocki  Actually I want to know about this change I have made in this file are right or wrong, It passes all the test cases at once rather than passing it separately . Please can you check this file on your system for confirmation.   

old generator file:- Ran 27 tests
the modified file:- Ran 14 tests
 
Link for modified file :- https://github.com/openvinotoolkit/openvino/compare/master...PRATHAM-SPS:openvino:Testing_another_method-_for_conversion

**Comment by p-wysocki** [comment]
Hi @PRATHAM-SPS, the modified file looks good to me. :) That's exactly what we need, thanks!

**Comment by jiwaszki** [comment]
@PRATHAM-SPS would you like to create a PR with it?

**Comment by PRATHAM-SPS** [comment]
yes @jiwaszki  I would like to create PR to the master branch of main repo.

my_updates:- https://github.com/openvinotoolkit/openvino/compare/master...PRATHAM-SPS:openvino:generator_to_unittest
(This Branch have all the changes that I have made till now)


Should I proceed for creating PR?

**Comment by jiwaszki** [comment]
@PRATHAM-SPS feel free to create it, we will be happy to leave a review and trigger all related CIs!

Please mention us in the created PR (you can use "reviewers" directly), so we would be notified faster about the it.

**Comment by PRATHAM-SPS** [comment]
Hii @jiwaszki @p-wysocki @rkazants  I have Created a PR but I am not able to add reviewers in it .  Actually it's not accessible for me. 

Thank You.

**Comment by jiwaszki** [comment]
Just linking actual PR here: https://github.com/openvinotoolkit/openvino/pull/18512

**Comment by mlukasze** [comment]
PR has been merged, congratulations and thank you!

**Comment by rkazants** [comment]
@mlukasze, it is not yet done. some corner cases with test-generator still remained and @PRATHAM-SPS will fix it in separate PR(s).

Best regards,
Roman

**Comment by p-wysocki** [comment]
I believe that @PRATHAM-SPS has already done lots of work here and it would be unfair to ask him to keep working on the same thing, especially since this task was a few weeks worth of effort. Thank you so much for your contribution @PRATHAM-SPS and I apologize for the scope creep - we did not expect this task to take that long. I hope this won't discourage you from engaging in OpenVINO open source community. :)

@rkazants can we please close this issue and create a new one just for the edge cases?

**Comment by PRATHAM-SPS** [comment]
> I believe that @PRATHAM-SPS has already done lots of work here and it would be unfair to ask him to keep working on the same thing, especially since this task was a few weeks worth of effort. Thank you so much for your contribution @PRATHAM-SPS and I apologize for the scope creep - we did not expect this task to take that long. I hope this won't discourage you from engaging in OpenVINO open source community. :)
> 
> @rkazants can we please close this issue and create a new one just for the edge cases?

Hello @p-wysocki @rkazants actually I have created 2 PRs for the edge cases but I am not able to pass all the test cases within it..

Here are the links-
 https://github.com/openvinotoolkit/openvino/pull/20091

https://github.com/openvinotoolkit/openvino/pull/20313

**Comment by p-wysocki** [comment]
@rkazants is https://github.com/openvinotoolkit/openvino/pull/20091 the last PR needed to close this issue?

**Comment by PRATHAM-SPS** [comment]
@p-wysocki  hello can you please create new issue  for the edge cases hardly 10 files are remaining and i have done 59 files and they have been already merged with the main branch https://github.com/openvinotoolkit/openvino/pull/18512.

**Comment by p-wysocki** [comment]
I think it's a great idea, you've already done so much work on it it's incredible. Thank you very much for your contribution @PRATHAM-SPS, I'm closing this issue and you no longer need to worry about `test-generator` :)

The issue is continued in https://github.com/openvinotoolkit/openvino/issues/21641. Thank you again!
