### ISSUE TITLE
How to inference a model which have several outputs 

### ISSUE THREAD

**Issue by ashray21** [openvinotoolkit/openvino#17720]
I'm trying to inference a model which have 3 different output. When trying to get the output tensor 
an exception is throw get_output_tensor() must be called on a function with exactly one parameter.

ov::Tensor output_tensor = infer_request.get_output_tensor();

Is their any way we can get multiple outputs ?

**Comment by ilya-lavrenov** [comment]
Hi @ashray21

When you have several outputs, use need to use:
```c++
// by index
ov::Tensor tensor = requrest.get_output_tensor(0);
// or with name
ov::Tensor tensor = requrest.get_tensor("tensor_name");
```
`get_output_tensor()` with no args is a helper for cases when we have a single output. The error message is exactly about it, because request does not know which of 3 output tensors to return

**Comment by ashray21** [comment]
Thanks the solution works.
Also one more thing I need to know is how to set the element type of each output when we have multiple outputs. 

ov::preprocess::PrePostProcessor ppp(model);
ppp.output().tensor().set_element_type(ov::element::f32);

This code also throws error 
Check 'm_impl->m_outputs.size() == 1' 
PrePostProcessor::output() - Model must have exactly one output, got 3

**Comment by ashray21** [comment]
Thanks it worked.
