### ISSUE TITLE
[Setup]Unable to initialise Openvino environment on Raspberry Pi 3 

### ISSUE THREAD

**Issue by Adityasrinivas24** [openvinotoolkit/openvino#17742]
System Information

- NCS 2
- Raspberry pi 3 (1GB)
- Raspbian os 11 bullseye
- 32-bit (armv7l)
- Problem classification -> Installation

Hello,
I am unable to initialise OPENVINO ENVIRONMENT for 
I downloaded from [here](https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.3/linux/l_openvino_toolkit_debian9_2022.3.0.9052.9752fafe8eb_armhf.tgz) .Followed all the steps mentioned [here](https://docs.openvino.ai/2022.3/openvino_docs_install_guides_installing_openvino_raspbian.html#doxid-openvino-docs-install-guides-installing-openvino-raspbian) .
 There are some files missing in the package as i  cant build the inference engine runtime. I get this error  ` File '97-myriad-usbboot.rules' is missing. Please make sure you installed 'Inference Engine Runtime for Intel® Movidius™ VPU'.`

**Comment by ilya-lavrenov** [comment]
MYRIAD plugin is not a part of 2022.3 release
You can perform inference on Rasb PI CPU itself since ARM CPU plugin is a part of this package.

**Comment by Adityasrinivas24** [comment]
Hi,
What are the steps i should take to setup.I can't find any related documentation on the same.I am trying to run an object detection model on the pi, i need the ncstick 2  as i don't have enough ram or processing power on my pi.

**Comment by ilya-lavrenov** [comment]
Just try CPU instead of MYRIAD when perform `ov::Core::compile_model`

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
