### ISSUE TITLE
[Question] MacOS OpenVINO built, what next (and more)?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [openvinotoolkit/openvino#17766]
*I tried to asked this question in the Intel forum (that is referenced in the documentation), but it mangled my question text and then flagged it as spam.* (https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/MacOS-OpenVINO-built-what-next-and-more/m-p/1490656)

[MacBook Pro 2014, MacOS 13.3.1, OpenVINO `master`, OpenCV 4.7.0]

With an abstract understanding of deep learning and several of it's sub-fields and a NCS2, I now would like to tinker. So, I followed the OpenVINO build instructions for Intel MacOS (`master` branch) all the way up to step #4, and everything built/installed fine.

With  OpenVINO installed on my computer (in `/usr/local/OpenVINO`) and my NCS2 plugged into my USB port, I believe I have everything needed to start using OpenVINO.  Thus I created my working folder with a virtualenv and decided to try the `Hello Classification` sample.

Looking at the `Hello Classification C++ Sample` documentation page, it suggests to download the `googlenet-v1` model. When I tried to do that, the `omz_downloader` script was not found. When I looked around my filesystem, I could not find the script in my OpenVINO install location but I did find it in the openvino workspace I cloned from github, under `./build/tools/openvino_dev/build/usr/local/bin/`. However, when I run `omz_downloader` directly from that location, I got an error `importlib.metadata.PackageNotFoundError: No package metadata was found for omz-tools`.

Prior to the model download step, the `Hello Classification C++ Sample` documentation page says to install `openvino-dev[caffe]`, but I was reluctant to do this since I had just built everything and, to my mind, already have `omz-tools`. Whilst composing this question, I decided to try installing `pip install openvino-dev` anyway (`python -m pip install openvino-dev[caffe]` returned an error), thinking that maybe it would only download/install this particular part and any other dependencies that are needed. But, to my surprise, pip started installing openvino_dev-2022.3.0-9052-py3-none-any.whl. Sadly, this install failed! So now I seem to have two versions of OpenVINO on my system; the nightly I built and a broken 2022.3.0.

I then attempted to install `omz-tools` itself, but pip complained:
```
 pip install omz-tools
 ERROR: Could not find a version that satisfies the requirement omz-tools (from versions: none)
 ERROR: No matching distribution found for omz-tools
``` 
So, now I have several questions:
1) How do I remove all the files that were downloaded as a result of trying to install `openvino-dev`?
2) How do I get the `omz_downloader` that I already have to work? Do I need to install, clone, build anything else?
3) Could it be that I haven't installed everything I need, e.g. OMZ-Tools and other stuff, since I only did what was stated in the build guide.

**Comment by Napoleon-BlownApart** [comment]
In case the error generated by `../openvino/build/tools/openvino_dev/build/usr/local/bin/omz_downloader --name googlenet-v1` is useful in solving my real problem, below is the reported error message:

```
../openvino/build/tools/openvino_dev/build/usr/local/bin/omz_downloader --name googlenet-v1
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nap/Programming/Neural_Compute_2/mine/../openvino/build/tools/openvino_dev/build/usr/local/bin/omz_downloader", line 33, in <module>
    sys.exit(load_entry_point('omz-tools==1.0.3', 'console_scripts', 'omz_downloader')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nap/Programming/Neural_Compute_2/mine/../openvino/build/tools/openvino_dev/build/usr/local/bin/omz_downloader", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for omz-tools
```

**Comment by Napoleon-BlownApart** [comment]
I think I've found a way forward.
I cloned the `open_model_zoo` repo and found the tools there.  I was able to install them by following the instructions:
```
# Navigate to the open_model_zoo/tools/model_tools directory
pip install --upgrade pip
pip install .
```

**Comment by Napoleon-BlownApart** [comment]
Looks like I spoke too soon.  Whilst the download worked, none of the following steps did:
```
user@host:[17:23]$ omz_downloader  --name googlenet-v1
################|| Downloading googlenet-v1 ||################

========== Downloading /Users/user/Programming/Neural_Compute_2/mine/public/googlenet-v1/googlenet-v1.prototxt
... 100%, 35 KB, 66657 KB/s, 0 seconds passed

========== Downloading /Users/user/Programming/Neural_Compute_2/mine/public/googlenet-v1/googlenet-v1.caffemodel
... 100%, 52279 KB, 3293 KB/s, 15 seconds passed

========== Replacing text in /Users/user/Programming/Neural_Compute_2/mine/public/googlenet-v1/googlenet-v1.prototxt

[src_customWB]~/Programming/Neural_Compute_2/mine
user@host:[17:25]$ omz_converter --name googlenet-v1
Unable to locate Model Optimizer. Use --mo or run setupvars.sh/setupvars.bat from the OpenVINO toolkit.
[src_customWB]~/Programming/Neural_Compute_2/mine
user@host:[17:26]$ omz_converter --name public/googlenet-v1
No matching models: "public/googlenet-v1"
[src_customWB]~/Programming/Neural_Compute_2/mine
user@host:[17:26]$ omz_converter --name public/googlenet-v1/googlenet-v1.caffemodel
No matching models: "public/googlenet-v1/googlenet-v1.caffemodel"
[src_customWB]~/Programming/Neural_Compute_2/mine
user@host:[17:26]$ omz_converter --name public/googlenet-v1/googlenet-v1.prototxt
No matching models: "public/googlenet-v1/googlenet-v1.prototxt"
[src_customWB]~/Programming/Neural_Compute_2/mine
user@host:[17:27]$ omz_converter --name public/googlenet-v1/googlenet-v1.prototxt.orig
No matching models: "public/googlenet-v1/googlenet-v1.prototxt.orig"
[src_customWB]~/Programming/Neural_Compute_2/mine
user@host:[17:27]$ ../openvino/bin/intel64/Release/hello_classification public/googlenet-v1/ horse.jpg GPU
[ INFO ] Build ................................. 2023.1.0-10999-42ef81a9e6b
[ INFO ]
[ INFO ] Loading model files: public/googlenet-v1/
Check 'false' failed at src/inference/src/core.cpp:100:
[ NETWORK_NOT_READ ] Unable to read the model: public/googlenet-v1/ Please check that model format: public/googlenet-v1/ is supported and the model is correct. Available frontends: paddle tf pytorch tflite ir onnx

[src_customWB]~/Programming/Neural_Compute_2/mine
user@host:[17:30]$ ../openvino/bin/intel64/Release/hello_classification public/googlenet-v1 horse.jpg GPU
[ INFO ] Build ................................. 2023.1.0-10999-42ef81a9e6b
[ INFO ]
[ INFO ] Loading model files: public/googlenet-v1
Check 'false' failed at src/inference/src/core.cpp:100:
[ NETWORK_NOT_READ ] Unable to read the model: public/googlenet-v1 Please check that model format: public/googlenet-v1 is supported and the model is correct. Available frontends: paddle tf pytorch tflite ir onnx

[src_customWB]~/Programming/Neural_Compute_2/mine
user@host:[17:30]$ ../openvino/bin/intel64/Release/hello_classification googlenet-v1 horse.jpg GPU
[ INFO ] Build ................................. 2023.1.0-10999-42ef81a9e6b
[ INFO ]
[ INFO ] Loading model files: googlenet-v1
Check 'false' failed at src/inference/src/core.cpp:100:
[ NETWORK_NOT_READ ] Unable to read the model: googlenet-v1 Please check that model format: googlenet-v1 is supported and the model is correct. Available frontends: paddle tf pytorch tflite ir onnx

[src_customWB]~/Programming/Neural_Compute_2/mine
user@host:[17:30]$
```

**Comment by Iffa-Meah** [comment]
Answering your questions:

1. How do I remove all the files that were downloaded as a result of trying to install openvino-dev?
The best is not to remove those folders as they are dependencies to make the OV work


2. How do I get the omz_downloader that I already have to work? Do I need to install, clone, build anything else?

There are 2 steps to obtain the omz_downloader tool:
1. Through [PyPI OV installation](https://pypi.org/project/openvino-dev/) (you will get this together with the OV env)
2. Download/Clone the OMZ from the official OpenVINO GitHub repo & [install the tool from source](https://github.com/openvinotoolkit/open_model_zoo/tree/master/tools/model_tools)


3. Could it be that I haven't installed everything I need, e.g. OMZ-Tools and other stuff, since I only did what was stated in the build guide.

Option 1: Install using PyPI and you'll get a working OV with the tools required. You'll need to build OMZ from source afterward, if you need to use OV samples.

Option 2: Install OV from source,  compile & build required files. Then, do the same for OMZ.

This is what I did to install OMZ tool from source


<img width="433" alt="tool1" src="https://github.com/openvinotoolkit/openvino/assets/79643476/baae81ff-4577-4a54-9fe5-0560268838c0">

<img width="442" alt="tool2" src="https://github.com/openvinotoolkit/openvino/assets/79643476/247ac6db-215f-4f35-8b85-111c372e7b58">


<img width="425" alt="tool3" src="https://github.com/openvinotoolkit/openvino/assets/79643476/e09ecc90-d52e-486d-9e40-6615d668f660">


You may refer to this [Official Documentation](https://docs.openvino.ai/2022.3/openvino_docs_install_guides_overview.html) to explore the available ways to get OpenVINO running in your env.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
