### ISSUE TITLE
How to inference a batch of images using openvino runtime in python 

### ISSUE THREAD

**Issue by ashray21** [openvinotoolkit/openvino#17779]
Hey,
Can you please give me some example or references to how to inference a batch of images in openvino runtime using python.

**Comment by adrianboguszewski** [comment]
Yes, batch inference may be find in this [notebook](https://github.com/IntelSoftware/Jurassic/blob/main/09.1_Dino_bone_find_OpenVINO_batch_GPU.ipynb)

@ashray21, please look at sections "Run batch inference with OpenVINO IR formats" and "Running inference with OpenVINO IR format under AUTO-batching feature"

**Comment by codewithAshray** [comment]
Thanks I got the logic

**Comment by jiwaszki** [comment]
@codewithAshray you are welcome! I will close the issue for now, please reopen it if necessary (or create a new one with more questions about OpenVINO!:)).
