### ISSUE TITLE
Runtime Error because of some CPP file 

### ISSUE THREAD

**Issue by ashish-2005** [openvinotoolkit/openvino#17847]
I am contributing a notebook in the openvino_notebook repository ([871](https://github.com/openvinotoolkit/openvino_notebooks/pull/871)) and facing an error after upgrading to the latest 2023.0.0 version (no error while using 2022.3.0).

### ERROR
```RuntimeError                              Traceback (most recent call last)
Cell In[11], line 8
      5 model_ir = core.read_model(model=XML_PATH)
      7 # load model on CPU device
----> 8 compiled_model = core.compile_model(model_ir,'CPU')
     10 # save keys of required information
     11 CLASS_KEY = compiled_model.output(2)  

File /opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/openvino/runtime/ie_api.py:398, in Core.compile_model(self, model, device_name, config)
    392 if device_name is None:
    393     return CompiledModel(
    394         super().compile_model(model, {} if config is None else config),
    395     )
    397 return CompiledModel(
--> 398     super().compile_model(model,device_name,{}ifconfigisNoneelseconfig),
    399 )

RuntimeError: Check 'false' failed at src/inference/src/core.cpp:114:
TopK layer with name 'Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField/TopKV2' gets top_k out of range!
```

Another strange thing is, notebooks runs fine on my local environment and google collab but fails on CIs.

PS: the time to convert my model from TF-Saved_Model format to openvino's IR has reduced from 17min to 15s after latest updates which is great thanks!

**Comment by rkazants** [comment]
Hi @ashish-2005,

Can you share the model link and the command-line to convert to IR?

Thanks,
Roman

**Comment by ashish-2005** [comment]
Hii @rkazants ,

nice to meet you again :sweat_smile:.

again its a pretrained model from TF-hub called [EfficientDet](https://tfhub.dev/tensorflow/efficientdet/d0/1).

i used mo API for conversion,
```python
from openvino.tools import mo
from openvino.runtime import serialize

model_ir = mo.convert_model(saved_model_dir=str(MODEL_DIR_PATH))
XML_PATH = IR_PATH / 'efficientdet.xml'
serialize(model_ir,str(XML_PATH))
```

Thanks.

(you can see complete notebook [here](https://github.com/ashish-2005/openvino_notebooks/blob/EfficientDet-optimization-notebook/notebooks/250-efficient-object-detection/250-efficient-object-detection.ipynb) if you want)

**Comment by Wan-Intel** [comment]
I've validated your notebooks and it's working fine.

I launched your notebook with the following command and run all the cells:
jupyter lab notebooks/250-efficient-object-detection/250-efficient-object-detection.ipynb

![perfect](https://github.com/openvinotoolkit/openvino/assets/123156917/3756fd23-593f-42c3-81b5-77ab7b532edc)

**Comment by ashish-2005** [comment]
Hi @Wan-Intel,

Thanks for reply.
The notebooks function properly, however some CIs fail. Looks like a CIs issue, thanks for support anyways.
