### ISSUE TITLE
ie_precision.hpp defines == operator but not !=

### ISSUE THREAD

**Issue by mjvh80** [openvinotoolkit/openvino#17852]
See https://github.com/openvinotoolkit/openvino/blob/031f2cc7d1a9aa10fb8a242057735d7ef1fd7f71/src/inference/include/ie/ie_precision.hpp#L162

I just upgraded to Visual Studio 17.6 and in our codebase this header file generates error [C2666](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2666?view=msvc-170) . We are using `/std:c++latest`. I believe it disregards the == operator because of a missing != operator. Indeed adding 

```c++
  bool operator!=(const Precision& p) const noexcept { return !(*this == p); }
```

fixes our code.

I'm not in a position to compile OpenVino itself at the moment, otherwise I'd have done a PR with this suggestion, or is there a reason not to add the != operator?

**Comment by ilya-lavrenov** [comment]
I suppose in order to fix compilation, we have to fix it.

**Comment by ilyachur** [comment]
@mjvh80 I agree with Ilya, could you please create a PR?
