### ISSUE TITLE
How to use movidius neural compute stick on windows?

### ISSUE THREAD

**Issue by lukmiik** [openvinotoolkit/openvino#17898]
I want to use movidius neural compute stick on windows. I installed openvino from this website https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html?ENVIRONMENT=DEV_TOOLS&OP_SYSTEM=WINDOWS&VERSION=v_2023_0&DISTRIBUTION=PIP
and tried following this guide https://www.intel.com/content/www/us/en/developer/articles/guide/get-started-with-neural-compute-stick.html but after installing openvino I dont have IntelSWTools folder on my pc so I don't know what to do next. What should I do to use movidius neural compute stick?

**Comment by ilya-lavrenov** [comment]
Hi,

MYRIAD plugin for NCS devices is removed since 2023.0 release.
Latest release supporting such devices is 2022.1, use https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html?ENVIRONMENT=RUNTIME&OP_SYSTEM=WINDOWS&VERSION=v_2022_1&DISTRIBUTION=OFFLINE_INSTALLER to download such installer.

**Comment by lukmiik** [comment]
Hi, thanks that's what I was looking for. Although I followed the guide and the official video https://www.youtube.com/watch?v=XPvMrGobe7I. I still can't use NCS. From my understanding this code `import openvino.inference_engine as ie engine = ie.IECore() print(engine.available_devices)` should print ['cpu', 'gpu', 'myriad'] if NCS is available to use and on my pc it only prints ['cpu', 'gpu'] when I do it in vs code but prints ['cpu', 'gna']. Is 'gna' my NCS or I do something wrong?

**Comment by ilya-lavrenov** [comment]
> I still can't use NCS

See https://docs.openvino.ai/2022.1/openvino_docs_install_guides_configurations_for_ncs2.html for information how to configure NCS device.

> Is 'gna' my NCS

No, GNA is a different device https://docs.openvino.ai/2022.1/openvino_docs_OV_UG_supported_plugins_GNA.html

**Comment by lukmiik** [comment]
>See https://docs.openvino.ai/2022.1/openvino_docs_install_guides_configurations_for_ncs2.html for information how to configure NCS device.
But there isn't guide for windows
