### ISSUE TITLE
Open source HDDL Plugin

### ISSUE THREAD

**Issue by jrefi** [openvinotoolkit/openvino#179]
I recently purchased an [Up AI Core X](https://up-shop.org/featured/262-up-ai-core-xm-2280.html) device and am trying to get it to work on an arm64 board. 

I believe the HDDL plugin is the correct one to use for such a device, however, it appears that plugin is only available as a pre-built binary which would limit compatibility to x86_64 devices. Any chance you could open source the code for this plugin like you recently did for the Myriad plugin (thanks for that btw)?

**Comment by dkurt** [comment]
@jrefi, I think that you can work with it as with two VPUs. You can initialize two Myriad plugins, load networks to each of them and then manage asynchronous requests. At least it could simulate the behavior of HDDL plugin for now.

**Comment by jrefi** [comment]
@dkurt That was the first thing I attempted and unfortunately, it did not seem the work. OpenVino was unable to find any devices while initializing the plugin.

**Comment by dkurt** [comment]
@jrefi, have you enabled `ENABLE_MYX_PCIE` CMake's flag? Can you provide verbose summary of your build?

**Comment by jrefi** [comment]
@dkurt I did, but it appears I may have copied the wrong bits from my AWS build machine to my device. I just went through the build process again and am now able to access the VPUs using the MYRIAD plugin.

Sorry about that. Thanks for the help though.

Closing this issue as this workaround satisfies my requirements.

**Comment by dkurt** [comment]
I think it's better to keep it opened as a feature request to prevent duplicates.

**Comment by jrefi** [comment]
Reopening.

**Comment by dkurt** [comment]
@DoubleChuang, please open a separate issue and add text error log instead of screenshot.

**Comment by avitial** [comment]
At this time there are no plans to opensource HDDL plugin. 

Ref. 15990
