### ISSUE TITLE
Reshape Input Layer

### ISSUE THREAD

**Issue by carlosost** [openvinotoolkit/openvino#1793]
**The context**
I am using OpenVino to implement MTCNN. As known by theory, the first step is basically find candidate bounding boxes using P-Net. In practice it means perform a pyramid over the image, resizing it and setting the input tensor with the resized image to infer using the P-Net.

**The problem**
I followed this instruction (https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_ShapeInference.html) to reshape the network input layer and it works perfectly. The problem is that the function `LoadNetwork` costs too much and since the first step of the MTCNN usually take 5 to 7 iterations (in my case), the total time of 5 to 7 `LoadNetwork` calls is almost unacceptable.

**The question**
Is it possible to perform an input layer reshape, without the need of call `LoadNetwork` every time? Similar functions are so fast at `Caffe` or `ArmNN`, that I really believe I am doing something through the worst path.

I appreciate any help.

**Comment by jgespino** [comment]
Hi @carlosost 

Thanks for reaching out. From what I understand, you need to call LoadNetwork after reshape. Let me check with my peers to see if it's possible to reshape without calling LoadNetwork. 

Regards,
Jesus

**Comment by carlosost** [comment]
Hi @jgespino,

I think you've understood, but let me explain it again in another way. 

    iterate = true
    while iterate
        resize the image
        call reshape
        call LoadNetwork
        iterate = still need to iterate ? true : false
        
The point is that `call LoadNetwork` every iteration costs too much and I would like to know if there is another possibility. Maybe reshape only the input layer or use another approach not so expensive in terms of processing time.

Thank you.

**Comment by dmitryte** [comment]
Hi @carlosost.
Unfortunately, dynamic input shapes is not supported right now.

Currently, your approach is the only way to execute models when you need different shape.

Regards,
Dmitry

**Comment by carlosost** [comment]
Hi @dmitryte.

Thank you for the reply and time spent in my case. I found another approach that still calls `LoadNetwork` 5 to 7 times as before, but that is executed at a different moment. It cost me a vector of `InferenceEngine::InferRequest` and some previous assumptions, but It worked.

Would be awesome if you could include this functionality (dynamic input shapes) in the backlog. It is very useful and necessary for a large amount of AI applications. :-)

Regards,
Carlos Ost.
