### ISSUE TITLE
compile openvino with "armeabi-v7a with NEON" error: the clang compiler does not support '-march=armv7-a+fp'

### ISSUE THREAD

**Issue by dapengchen1234** [openvinotoolkit/openvino#17982]
I use the version of 2023.0, and the CMake configuration is 
```
 cmake ..  -DCMAKE_TOOLCHAIN_FILE=../../downloads/android-ndk-r20b/build/cmake/android.toolchain.cmake  -DANDROID_ABI="armeabi-v7a with NEON"  -DANDROID_PLATFORM=21   -DENABLE_OPENCV=OFF  -DENABLE_SAMPLES=OFF
```

It uses the default clang compiler in the toolchain.    During the make, the error happens :

clang++: error: the clang compiler does not support '-march=armv7-a+fp'
make[2]: *** [src/common/preprocessing/src/CMakeFiles/openvino_gapi_preproc_obj.dir/build.make:118: src/common/preprocessing/src/CMakeFiles/openvino_gapi_preproc_obj.dir/arm_neon/ie_preprocess_gapi_kernels_neon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3909: src/common/preprocessing/src/CMakeFiles/openvino_gapi_preproc_obj.dir/all] Error 2

**Comment by ilya-lavrenov** [comment]
@dapengchen1234 
Please, try to build with `-DENABLE_GAPI_PREPROCESSING=OFF`, this is an optional functionality
