### ISSUE TITLE
Static compilation problem "armeabi-v7a with NEON"  

### ISSUE THREAD

**Issue by dapengchen1234** [openvinotoolkit/openvino#17985]
The cmake configuration is: 
'''
cmake .. -DCMAKE_TOOLCHAIN_FILE=../../downloads/android-ndk-r21e/build/cmake/android.toolchain.cmake  -DANDROID_ABI="armeabi-v7a with NEON"  -DANDROID_PLATFORM=21 -DANDROID_STL=c++_shared  -DENABLE_OPENCV=OFF  -DENABLE_SAMPLES=OFF -DBUILD_SHARED_LIBS=OFF
'''
For dynamic compilation， it works well. But for static compilation, it reported the following error:

CMake Error at cmake/developer_package/IEDevScriptsConfig.cmake:256 (install):
  install TARGETS given target "arm_compute_core" which does not exist.
Call Stack (most recent call first):
  src/plugins/intel_cpu/thirdparty/CMakeLists.txt:146 (ov_install_static_lib)
  src/plugins/intel_cpu/thirdparty/CMakeLists.txt:151 (ie_add_onednn)

**Comment by ilya-lavrenov** [comment]
Hi @dapengchen1234 

I suppose you use 2023.0.0 tag / branch.
But in current master we have several improvements for static compilation and the issue is fixed. Please, try using master.
