### ISSUE TITLE
[shared memory]how to implement shared memory in openvino infer code

### ISSUE THREAD

**Issue by lucy3589** [openvinotoolkit/openvino#17998]
from:
https://docs.openvino.ai/2022.3/notebooks/109-latency-tricks-with-output.html

`
```
def benchmark_model(model: Any, input_data: np.ndarray, benchmark_name: str, device_name: str = "CPU") -> float:
    """
    Helper function for benchmarking the model. It measures the time and prints results.
    """
    # measure the first inference separately -  it may be slower as it contains also initialization
    start = time.perf_counter()
    model(input_data)
    end = time.perf_counter()
    first_infer_time = end - start
    print(f"{benchmark_name} on {device_name}. First inference time: {first_infer_time :.4f} seconds")

    # benchmarking
    start = time.perf_counter()
    for _ in range(INFER_NUMBER):
        model(input_data)
    end = time.perf_counter()

    # elapsed time
    infer_time = end - start

    # print second per image and FPS
    mean_infer_time = infer_time / INFER_NUMBER
    mean_fps = INFER_NUMBER / infer_time
    print(f"{benchmark_name} on {device_name}: {mean_infer_time :.4f} seconds per image ({mean_fps :.2f} FPS)")

    return mean_infer_time`


`
# it must be assigned to a variable, not to be garbage collected
c_input_image = np.ascontiguousarray(input_image, dtype=np.float32)
input_tensor = ov.Tensor(c_input_image, shared_memory=True)

result = ov_auto_model(input_tensor)[ov_auto_model.output(0)][0]
show_result(result)
ov_auto_shared_infer_time = benchmark_model(model=ov_auto_model, input_data=input_tensor, benchmark_name="OpenVINO model + shared memory", device_name="AUTO")

del ov_auto_model  # release resources`
```

**Comment by ilya-lavrenov** [comment]
Please, provide more details what you want to achieve.
Pasting code snippet with no description does not help us to provide advices.

**Comment by lucy3589** [comment]
> 

Shared memory is used in this example, showing that shared memory reduces inference time.



But I don't know how to implement the code for shared memory. How to apply in practical reasoning scenarios

**Comment by lucy3589** [comment]
> Please, provide more details what you want to achieve. Pasting code snippet with no description does not help us to provide advices.

i use shared_memory, but infer time as same as not use shared_memory

![image](https://github.com/openvinotoolkit/openvino/assets/33214551/54e975d6-0d51-4c2a-8f78-57ade35ec9ce)

**Comment by lucy3589** [comment]
> Please, provide more details what you want to achieve. Pasting code snippet with no description does not help us to provide advices.
Using multithreading or low latency mode, with or without shared_memory, the final inference speed is basically patterned.



109-latent-tricks-with-output display will speed up

But my test results don't feel accelerated



I don't know if it's my code or the device. Looking forward to your reply


![image](https://github.com/openvinotoolkit/openvino/assets/33214551/622449ee-49e8-4b17-ac1c-2861faa4ff78)


> Please, provide more details what you want to achieve. Pasting code snippet with no description does not help us to provide advices.

**Comment by jiwaszki** [comment]
Hello @lucy3589 ,

Could you please confirm that you are using AMD Ryzen for the inference? OpenVINO does provide optimizations for Intel-based hardware, I think that AMD CPU would not likely benefit from it.

As for shared memory, it looks correctly implemented for 2022.3 version. Could you provide more details on the model? Most of the shared memory benefits comes from the large input sizes. If model itself has small inputs, shared memory presence might be observable only on huge amount of iterations or even won't be visible.

Could you also try newer version of OpenVINO 2023.0? Now shared memory is even easier to implement. There is no need for explicit tensor creation, all is incorporated into `CompiledModel` call:
```python
results = compiled_model(inputs, shared_memory=True)  # also CompiledModel is now creating InferRequest and reusing it in consecutive calls!
```
In addition we have introduced `OVDict` which helps with accessing the data. It is worth checking it out.

Docs to read:
* https://docs.openvino.ai/2023.0/openvino_docs_OV_UG_Python_API_inference.html#direct-inference-with-compiledmodel
* https://docs.openvino.ai/2023.0/openvino_docs_OV_UG_Python_API_inference.html#shared-memory-on-inputs
* https://docs.openvino.ai/2023.0/openvino_docs_OV_UG_Python_API_exclusives.html#inference-results-ovdict

Let me know if it helps! Awaiting your response.

**Comment by lucy3589** [comment]
> 

I use openvino==2023.0.   my model is yolov8n-seg, input size is 640*640

```
c_input_image = np.ascontiguousarray(input_image, dtype=np.float32)
input_tensor = ov.Tensor(c_input_image, shared_memory=True)
res_ir = compiled_model_ir(input_tensor,shared_memory=True)[output_layer_ir][0]
```
or

```
c_input_image = np.ascontiguousarray(input_image, dtype=np.float32)
input_tensor = ov.Tensor(c_input_image, shared_memory=False)
res_ir = compiled_model_ir(input_tensor,shared_memory=False)[output_layer_ir][0]
```
infer time is same

**Comment by lucy3589** [comment]
> I use openvino==2023.0. my model is yolov8n-seg, input size is 640*640
> 
> ```
> c_input_image = np.ascontiguousarray(input_image, dtype=np.float32)
> input_tensor = ov.Tensor(c_input_image, shared_memory=True)
> res_ir = compiled_model_ir(input_tensor,shared_memory=True)[output_layer_ir][0]
> ```
> 
> or
> 
> ```
> c_input_image = np.ascontiguousarray(input_image, dtype=np.float32)
> input_tensor = ov.Tensor(c_input_image, shared_memory=False)
> res_ir = compiled_model_ir(input_tensor,shared_memory=False)[output_layer_ir][0]
> ```
> 
> infer time is same

I use openvino==2023.0. my model is yolov8n-seg, input size is 640*640

c_input_image = np.ascontiguousarray(input_image, dtype=np.float32)
input_tensor = ov.Tensor(c_input_image, shared_memory=True)
res_ir = compiled_model_ir(input_tensor,shared_memory=True)[output_layer_ir][0]
or

c_input_image = np.ascontiguousarray(input_image, dtype=np.float32)
input_tensor = ov.Tensor(c_input_image, shared_memory=False)
res_ir = compiled_model_ir(input_tensor,shared_memory=False)[output_layer_ir][0]
infer time is same

**Comment by lucy3589** [comment]
or run this code, infer time is same. shared_memory=False or shared_memory=True

```
input_image = np.expand_dims(np.transpose(normalized_image, (2, 0, 1)), 0)
# Get input and output layers.
output_layer_ir = compiled_model_ir.output(0)
t1 = time.perf_counter()
res_ir = compiled_model_ir(input_image,shared_memory=False)[output_layer_ir][0]
```

**Comment by lucy3589** [comment]
i use CPU:Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
shared_memory is true or false.  infer time is Almost the same

**Comment by avitial** [comment]
Ref. 114091
