### ISSUE TITLE
[Bug] Python multithread inference performance drop from 2022.3 to 2023.0

### ISSUE THREAD

**Issue by KindRoach** [openvinotoolkit/openvino#18071]
##### System information (version)
- OpenVINO Source=> pip install
- OpenVINO Version=> Version 2023.0
- Operating System / Platform => Ubuntu 20 / Ubuntu 22
- Problem classification => Inference Performance
- Device use: => CPU
- Framework => PyTorch
- Model name => ResNet50 from pytorch hub (any other models also )

##### Detailed description
When I create infer request and infer in multithread with 2023.0, I found a huge performance drop compared to 2022.3 (from 400+ fps to 40+ fps). 
The reason seems is that OpenVINO 2023.0 doesn't all cpu cores. 
I also test on Windows 11 64 bits, there is no such performance issue.

### behavior of 2023.0
![2023 0 fps](https://github.com/openvinotoolkit/openvino/assets/17931052/361884a3-10c5-497f-bac1-a2dc4eddeefd)
![2023 0 cpu](https://github.com/openvinotoolkit/openvino/assets/17931052/349bd197-68f9-4bea-8273-890a2b73f88a)

### behavior of 2022.3 
![2022 3 fps](https://github.com/openvinotoolkit/openvino/assets/17931052/4840f83d-2030-47df-839d-00eebeca9074)
![2022 3 cpu](https://github.com/openvinotoolkit/openvino/assets/17931052/cab90e56-b6be-4ff0-8c27-3e9601b99f8c)

##### Steps to reproduce

Here are a sample code to reproduce. 

```
from concurrent. Futures import ThreadPoolExecutor

import numpy.random
from openvino.runtime import Core
from tqdm import tqdm

N_ITER = 1000
N_STREAM = 24  # Core number of 13700K

ie = Core()
ie.set_property("CPU", {"PERFORMANCE_HINT": "THROUGHPUT"})
model_xml = f"model.xml"
compiled_model = ie.compile_model(model_xml, "CPU")

with tqdm(unit="frame") as pbar:
    input = numpy.random.rand(1, 3, 224, 224)


    def infer_stream():
        outputs = []
        infer_req = compiled_model.create_infer_request()
        for _ in range(N_ITER):
            infer_req.infer(input)
            pbar.update(1)
        return outputs


    with ThreadPoolExecutor(N_STREAM) as pool:
        tasks = []
        for _ in range(N_STREAM):
            tasks.append(pool.submit(infer_stream))
        outputs = [task.result() for task in tasks]

```

**Comment by wangleis** [comment]
@KindRoach May I know which platform is used in this test? Could you share the log of `lscpu` and `lscpu -e`?

**Comment by KindRoach** [comment]
> @KindRoach May I know which platform is used in this test? Could you share the log of `lscpu` and `lscpu -e`?

I'm using 13700k. lscpu output as below:

```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  24
  On-line CPU(s) list:   0-23
Vendor ID:               GenuineIntel
  Model name:            13th Gen Intel(R) Core(TM) i7-13700K
    CPU family:          6
    Model:               183
    Thread(s) per core:  2
    Core(s) per socket:  16
    Socket(s):           1
    Stepping:            1
    CPU max MHz:         5400.0000
    CPU min MHz:         800.0000
    BogoMIPS:            6835.20
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mc
                         a cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss 
                         ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art
                          arch_perfmon pebs bts rep_good nopl xtopology nonstop_
                         tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes6
                         4 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xt
                         pr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_
                         timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefet
                         ch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced t
                         pr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase ts
                         c_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx sm
                         ap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xget
                         bv1 xsaves split_lock_detect avx_vnni dtherm ida arat p
                         ln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_re
                         q hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme r
                         dpid movdiri movdir64b fsrm md_clear serialize pconfig 
                         arch_lbr ibt flush_l1d arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   640 KiB (16 instances)
  L1i:                   768 KiB (16 instances)
  L2:                    24 MiB (10 instances)
  L3:                    30 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-23
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer
                          sanitization
  Spectre v2:            Mitigation; Enhanced IBRS, IBPB conditional, RSB fillin
                         g, PBRSB-eIBRS SW sequence
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by KindRoach** [comment]
lscpu -e output as below:
`CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE    MAXMHZ   MINMHZ      MHZ
  0    0      0    0 0:0:0:0          yes 5300.0000 800.0000 3400.000
  1    0      0    0 0:0:0:0          yes 5300.0000 800.0000 3400.000
  2    0      0    1 4:4:1:0          yes 5300.0000 800.0000 3400.000
  3    0      0    1 4:4:1:0          yes 5300.0000 800.0000 3400.000
  4    0      0    2 8:8:2:0          yes 5300.0000 800.0000 3400.000
  5    0      0    2 8:8:2:0          yes 5300.0000 800.0000 3400.000
  6    0      0    3 12:12:3:0        yes 5300.0000 800.0000 3400.000
  7    0      0    3 12:12:3:0        yes 5300.0000 800.0000 3400.000
  8    0      0    4 16:16:4:0        yes 5400.0000 800.0000 1053.815
  9    0      0    4 16:16:4:0        yes 5400.0000 800.0000 3400.000
 10    0      0    5 20:20:5:0        yes 5400.0000 800.0000 3400.000
 11    0      0    5 20:20:5:0        yes 5400.0000 800.0000 3400.000
 12    0      0    6 24:24:6:0        yes 5300.0000 800.0000 3400.000
 13    0      0    6 24:24:6:0        yes 5300.0000 800.0000 3400.000
 14    0      0    7 28:28:7:0        yes 5300.0000 800.0000 3400.000
 15    0      0    7 28:28:7:0        yes 5300.0000 800.0000 3400.000
 16    0      0    8 32:32:8:0        yes 4200.0000 800.0000  799.997
 17    0      0    9 33:33:8:0        yes 4200.0000 800.0000 3400.000
 18    0      0   10 34:34:8:0        yes 4200.0000 800.0000 3400.000
 19    0      0   11 35:35:8:0        yes 4200.0000 800.0000 3400.000
 20    0      0   12 36:36:9:0        yes 4200.0000 800.0000 3400.000
 21    0      0   13 37:37:9:0        yes 4200.0000 800.0000 3400.000
 22    0      0   14 38:38:9:0        yes 4200.0000 800.0000 3400.000
 23    0      0   15 39:39:9:0        yes 4200.0000 800.0000 3400.000`

**Comment by wangleis** [comment]
@KindRoach Thanks for your information. 

The root cause of this issue is using `sync API` with multiple infer requests and throughout hint.

If you prefer high throughput, please refer Async Mode of https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/115-async-api/115-async-api.ipynb to use `async API` with multiple infer requests and throughput hint.

If you prefer short latency, please refer Sync Mode of https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/115-async-api/115-async-api.ipynb to use `sync API` with single infer request and latency hint.

**Comment by KindRoach** [comment]
@wangleis Thanks for your example code. 
This performance issue could be fixed by replacing `infer_req.infer(input)` with 
```
infer_req.start_async(input)
infer_req.wait()
```
