### ISSUE TITLE
Slow inference speed on android , any advice?

### ISSUE THREAD

**Issue by dapengchen1234** [openvinotoolkit/openvino#18109]
Model inference time on Android system is much slower than on Windows system
Here is a comparison of Inference Time
Windows system (12th Gen Intel(R) Core(TM) i7-1260P CPU) --openvino:  13.10ms

1. Android system （Snapdragon 778G 4G)--MNN:  21 ms

Android system （Snapdragon 778G 4G)--openvino: 571 ms

Here is CMake Config for Android :

OpenVINO version is 2023.1.0 (Build 11348)
-- OpenVINO Runtime enabled features:
--
--     CI_BUILD_NUMBER: 2023.1.0-11348-55156f9a6ce
--     ENABLE_LTO = OFF
--     OS_FOLDER = OFF
--     USE_BUILD_TYPE_SUBFOLDER = ON
--     CMAKE_COMPILE_WARNING_AS_ERROR = OFF
--     ENABLE_QSPECTRE = OFF
--     ENABLE_INTEGRITYCHECK = OFF
--     ENABLE_SANITIZER = OFF
--     ENABLE_UB_SANITIZER = OFF
--     ENABLE_THREAD_SANITIZER = OFF
--     ENABLE_COVERAGE = OFF
--     ENABLE_SSE42 = OFF
--     ENABLE_AVX2 = OFF
--     ENABLE_AVX512F = OFF
--     BUILD_SHARED_LIBS = OFF
--     ENABLE_LIBRARY_VERSIONING = OFF
--     ENABLE_FASTER_BUILD = OFF
--     ENABLE_CPPLINT = OFF
--     ENABLE_CPPLINT_REPORT = OFF
--     ENABLE_CLANG_FORMAT = OFF
--     ENABLE_NCC_STYLE = OFF
--     VERBOSE_BUILD = OFF
--     ENABLE_UNSAFE_LOCATIONS = OFF
--     ENABLE_FUZZING = OFF
--     ENABLE_INTEL_CPU = ON
--     ENABLE_ARM_COMPUTE_CMAKE = OFF
--     ENABLE_TESTS = OFF
--     ENABLE_COMPILE_TOOL = OFF
--     ENABLE_STRICT_DEPENDENCIES = ON
--     ENABLE_INTEL_GPU = OFF
--     ENABLE_ONEDNN_FOR_GPU = OFF
--     ENABLE_DEBUG_CAPS = OFF
--     ENABLE_GPU_DEBUG_CAPS = OFF
--     ENABLE_CPU_DEBUG_CAPS = OFF
--     ENABLE_PROFILING_ITT = OFF
--     ENABLE_PROFILING_FILTER = ALL
--     ENABLE_PROFILING_FIRST_INFERENCE = ON
--     SELECTIVE_BUILD = OFF
--     ENABLE_DOCS = OFF
--     ENABLE_PKGCONFIG_GEN = OFF
--     THREADING = TBB
--     ENABLE_TBBBIND_2_5 = OFF
--     ENABLE_INTEL_GNA = OFF
--     ENABLE_INTEL_GNA_DEBUG = OFF
--     ENABLE_V7_SERIALIZE = OFF
--     ENABLE_IR_V7_READER = OFF
--     ENABLE_GAPI_PREPROCESSING = OFF
--     ENABLE_MULTI = OFF
--     ENABLE_AUTO = OFF
--     ENABLE_AUTO_BATCH = OFF
--     ENABLE_HETERO = OFF
--     ENABLE_TEMPLATE = OFF
--     ENABLE_PLUGINS_XML = OFF
--     GAPI_TEST_PERF = OFF
--     ENABLE_DATA = OFF
--     ENABLE_FUNCTIONAL_TESTS = OFF
--     ENABLE_SAMPLES = ON
--     ENABLE_OPENCV = OFF
--     ENABLE_TBB_RELEASE_ONLY = OFF
--     ENABLE_OV_ONNX_FRONTEND = OFF
--     ENABLE_OV_PADDLE_FRONTEND = OFF
--     ENABLE_OV_IR_FRONTEND = ON
--     ENABLE_OV_PYTORCH_FRONTEND = OFF
--     ENABLE_OV_IR_FRONTEND = ON
--     ENABLE_OV_TF_FRONTEND = OFF
--     ENABLE_OV_TF_LITE_FRONTEND = OFF
--     ENABLE_SNAPPY_COMPRESSION = OFF
--     ENABLE_SYSTEM_TBB = OFF
--     ENABLE_SYSTEM_PUGIXML = OFF
--     ENABLE_SYSTEM_FLATBUFFERS = OFF
--     ENABLE_SYSTEM_OPENCL = OFF
--     ENABLE_SYSTEM_PROTOBUF = OFF
--     ENABLE_SYSTEM_SNAPPY = OFF
--     ENABLE_PYTHON_PACKAGING = OFF
--     ENABLE_OPENVINO_DEBUG = OFF

How could I speed up?

**Comment by dmitry-gorokhov** [comment]
Hi @dapengchen1234 , could you please specify for which model these numbers were collected? Is it possible to share it?

**Comment by avitial** [comment]
Closing this as we cannot help due to insufficient info. Feel free to reopen and provide requested additional information if issue persists.
