### ISSUE TITLE
OpenVINO Debug build is installed in Release folder

### ISSUE THREAD

**Issue by yrzhanov** [openvinotoolkit/openvino#1818]
OpenVINO Debug build is installed in Release folder.
Post-build event:
setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=$(Configuration) -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd

and $(Configuration) is indeed Debug. Is there anything wrong with cmake_install.cmake?

**Comment by jgespino** [comment]
Hi @yrzhanov 

Please provide additional information and steps to reproduce. 

- OpenVINO Version (branch)
- Operating System
- CMake Version
- Microsoft Visual Studio Version

Regards,
Jesus

**Comment by yrzhanov** [comment]
* # [OpenVINO™ Toolkit](https://01.org/openvinotoolkit) - Deep Learning Deployment Toolkit repository
[![Stable release](https://img.shields.io/badge/version-2020.4-green.svg)](https://github.com/openvinotoolkit/openvino/releases/tag/2020.4.0)
* Windows 10
* CMake 3.17.2
* Microsoft Visual Studio Community 2017 
Version 15.9.23
VisualStudio.15.Release/15.9.23+28307.1146
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA631
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Intel® C++ Compiler   Package ID: w_comp_lib_2020.1.216
Intel® C++ Compiler – extension version 19.1.0.15, Package ID: w_comp_lib_2020.1.216, Copyright © 2002-2020 Intel Corporation. All rights reserved.
* Other names and brands may be claimed as the property of others.

Intel® Performance Libraries   Package ID: w_comp_lib_2020.1.216
Intel® Performance Libraries – extension version 19.1.0.15, Package ID: w_comp_lib_2020.1.216, Copyright © 2002-2020 Intel Corporation. All rights reserved.
* Other names and brands may be claimed as the property of others.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Comment by jgespino** [comment]
@yrzhanov Thanks! Please also let me know which OpenVINO branch you checked out and commands used.

**Comment by yrzhanov** [comment]
I downloaded zip, used CMake Gui, compiled and installed.

**Comment by yrzhanov** [comment]
It seems that the installer version 2020.4.287 differs from the one that can be downloaded from the github (possibly 2020.4.0).  I wanted to compile OpenVINO myself because I need PDB files, which are not installed. Is it possible to get them to be able to debug the app? Or get from github 2020.4.287 version source?

**Comment by jgespino** [comment]
Hi @yrzhanov 

Try building OpenVINO from source in Debug and the PDB files should be generated under `bin\intel64\Debug`. Make sure to checkout the 2020.4 tag after cloning the repository.

`git checkout 2020.4`

Regards,
Jesus

**Comment by yrzhanov** [comment]
Hi Jesus,
the PDB files are created there allright. I'm reporting a different issue. Once I build a Debug version (CMakePredefinedTargets/ALL_BUILD) and then use INSTALL, all the LIBs and DLLs end up in deployment_tools\inference_engine\lib\intel64\Release folder rather than in deployment_tools\inference_engine\lib\intel64\Debug, although they have "d" in names (like in "inference_engined.lib").

I'm also wondering about the patch difference: when I clone 2020.4, is it 2020.4.287 (which is installed in C:\Program Files (x86)\IntelSWTools\openvino, or 2020.4.0, which I cloned from git? They are clearly different.

**Comment by ilya-lavrenov** [comment]
@yrzhanov could you please try to play with https://github.com/openvinotoolkit/openvino/blob/master/cmake/developer_package.cmake#L41-L45 and fix the issue?

**Comment by jgespino** [comment]
@yrzhanov Did you get a chance to play with the cmake file?

**Comment by jgespino** [comment]
Closing feel free to re-open if additional assistance is needed.
