### ISSUE TITLE
[Bug] Openvino 2022.3.1 LTS Release - No compiler tool?

### ISSUE THREAD

**Issue by CJavier11** [openvinotoolkit/openvino#18221]
- OpenVINO Source => pip install
- OpenVINO Version => Version 2022.3.1 LTS
- Operating System / Platform => Ubuntu 20
- Compiler => Colab
- Problem classification: Model Conversion to Blov
- Device use: CPU
- Model name:  Yolov7

In the most recent openvino 2022.3.1 release, I am unable to locate/utilize the ./compile_tool for blob conversion?  It is stated in the release notes the compile tool wouldn't be deprecated until 2023.0 and removed in 2023.1, is this not the case?

Thanks in advance.

<img width="585" alt="Screenshot 2023-06-23 at 6 29 51 PM" src="https://github.com/openvinotoolkit/openvino/assets/90358358/237f5e22-9635-4ca5-891d-3a00efb77269">

**Comment by ilya-lavrenov** [comment]
Hi @CJavier11,

Compile tool was never a part of OpenVINO wheel package on PyPi. Please, download OpenVINO archive and find compile_tool in tools folder.
A link how to use OpenVINO archives https://docs.openvino.ai/2022.3/openvino_docs_install_guides_installing_openvino_from_archive_linux.html

**Comment by CJavier11** [comment]
Hi @ilya-lavrenov ,

I need the compile tool for .blob conversion to deploy models on the MyriadX chip.  If I have already installed 2022.3.1 LTS via PyPi, should I pip uninstall openvino-dev, openvino prior to proceeding with installation via archive?

Thanks,
Chris

**Comment by CJavier11** [comment]
Hi @ilya-lavrenov ,

I need the compile tool for .blob conversion to deploy models on the MyriadX chip.  If I have already installed 2022.3.1 LTS via PyPi, should I pip uninstall openvino-dev, openvino prior to proceeding with installation via archive?

Thanks,
Chris

**Comment by ilya-lavrenov** [comment]
> If I have already installed 2022.3.1 LTS via PyPi, should I pip uninstall openvino-dev, openvino prior to proceeding with installation via archive?

No, you can download and extract archive without uninstalling wheel package.

> /opt/intel/openvino_2022.3.1/tools/compile_tool/compile_tool: error while loading shared libraries: libopenvino.so.2231: cannot open shared object file: No such file or directory

Call setupvars.sh before running the tools.

**Comment by CJavier11** [comment]
@ilya-lavrenov I do call setuptvars.sh before running via `!source /opt/intel/openvino_2022/setupvars.sh` which initializes the environment, yet yields the same error.  However, regardless of the outcome, I believe Myriad X doesn't support 8-bit quantization.  I am trying to optimize yolov7 for deployment on the Myriad X and was trying to leverage the NNCF library, any alternatives or methods you know of?

**Comment by ilya-lavrenov** [comment]
Right, MYRIAD plugin does not support int8 quantized models
