### ISSUE TITLE
[Bug] OpenVINO 2023.0.0 root directory

### ISSUE THREAD

**Issue by Satmaks** [openvinotoolkit/openvino#18243]
##### System information (version)
- OpenVINO Source => Runtime / GitHub 
- OpenVINO Version => Version 2023.0.0 / Github Master Branch / tag 2023.0 
- Operating System / Platform => Windows 64 Bit / Ubuntu 18/20
- Compiler => Cmake
- Problem classification: Read Model 
- Device use: CPU

##### Detailed description
In the case of a static build of OpenVINO, when I run the executable from the linux root directory, I get an error:
```
[ NETWORK_NOT_READ ] Unable to read the model. Please check if the model format is supported and model is correct.
```

I already found a solution to the problem.
The problem is [here](https://github.com/openvinotoolkit/openvino/blob/f306a11b824c0a7d6b4515cfcc374c11d722bb84/src/common/util/src/file_util.cpp#L90).
If `s = "/foo"` is passed to the `get_directory()` function, then the result is an empty string, although `/` should be returned.

The problem starts [here](https://github.com/openvinotoolkit/openvino/blob/f306a11b824c0a7d6b4515cfcc374c11d722bb84/src/frontends/common/src/manager.cpp#L220).
```fe_lib_dir``` will be an empty string and should be `/`.

I replaced [line](https://github.com/openvinotoolkit/openvino/blob/c3b7e8172237488a68d4887e861f1f7754bfcbf1/src/common/util/src/file_util.cpp#L90) with `rc = s.substr(0, pos ? pos ): 1);` perhaps a better solution would be `rc = s.substr(0, pos + 1);`, I'm not sure. And that's just for Linux.

**Comment by ilya-lavrenov** [comment]
Hi @Satmaks 

Could you please create a patch with your changes? We can continue about possible improvements in a PR.

**Comment by avitial** [comment]
@Satmaks to submit a PR, you can follow the contribution guidelines as described in https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md.

**Comment by vurusovs** [comment]
@Satmaks issue should be fixed with https://github.com/openvinotoolkit/openvino/pull/18820. Feel free to reopen if issue still persist
