### ISSUE TITLE
Slow inference on Windows build

### ISSUE THREAD

**Issue by FredericoPerimLopes** [openvinotoolkit/openvino#18300]
System information (version)

OpenVINO Source => pip install
OpenVINO Version => Version 2023.0
Operating System / Platform => Windows 11
Compiler => Visual Studio 2022
Problem classification: SSD Model inference
Device use: CPU / GPU
Model name: ssd300

I've compiled the demo for object detection, but the inference is too slow

[ INFO ] Metrics report:
[ INFO ]        Latency: 3136.3 ms
[ INFO ]        FPS: 1.6
[ INFO ]        Decoding:       4.0 ms
[ INFO ]        Preprocessing:  80.4 ms
[ INFO ]        Inference:      3038.4 ms
[ INFO ]        Postprocessing: 0.1 ms
[ INFO ]        Rendering:      3.6 ms

What could be the issue?

**Comment by wangleis** [comment]
@FredericoPerimLopes May I know what's the CPU in your system? Could you run `benchmark_app` and share the whole log?

**Comment by FredericoPerimLopes** [comment]
@wangleis  When I try to run the benchmark app I'm getting this output:
(openvino_env) E:\openvino_2023.0.0\openvino_2023.0.0\samples\build\intel64\Release>benchmark_app.exe -m ssd300.xml -d CPU -hint latency
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ]
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Device(CPU) performance hint is set to LATENCY
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ ERROR ] [ NETWORK_NOT_READ ] Unable to read the model: ssd300.xml Please check that model format: xml is supported and the model is correct. Available frontends:

**Comment by wangleis** [comment]
@FredericoPerimLopes  Looks like the OpenVINO is your `openvino_env` is still `releases/2022/3`. Could you create another clean python environment to install OpenVINO 2023.0 release and try again?

**Comment by wangleis** [comment]
@FredericoPerimLopes  Thanks for your update. 

Close this issue. Please feel free to reopen or create new issue if additional assistance is needed.
