### ISSUE TITLE
The generated dll based on static openvino runtime still rely on the openvino runtime to build other apps.

### ISSUE THREAD

**Issue by dapengchen1234** [openvinotoolkit/openvino#18308]
I want to use OpenVINO to build my own DLL.   The DLL should be further used to build other apps without depending on the original OpenVINO library, which is too big.  My problem is when I use the generated dll to build other apps. It still needs openvino library for building. 

Here are my Cmake files:

```
set(OpenVINO_DIR ${PROJECT_SOURCE_DIR}/openvino_runtime/runtime/cmake)
find_package(OpenVINO REQUIRED)

   ...

## generate a DLL 
add_library(MatService SHARED ${SRC_FILES} )
target_link_libraries(MatService **openvino::runtime** smallcv)

if(MIRROR_BUILD_MATSERVICE)
    set(OpenCV_DIR  ${CMAKE_CURRENT_SOURCE_DIR}/../opencv_install)
    find_package(OpenCV REQUIRED)
    add_executable(demo ${CMAKE_CURRENT_SOURCE_DIR}/demo.cpp )
    target_link_libraries(demo  MatService ${OpenCV_LIBS} )
endif()
```
When I generate the DLL, it can be built successfully, and the demo app also works.  The demo only depends on the generated MatService.dll and does not need original openvino DLLs. 

However, when I USE the generated dll to build the same app with the following cmake file:

```
set(OpenVINO_DIR ${PROJECT_SOURCE_DIR}/openvino_runtime/runtime/cmake)
find_package(OpenVINO REQUIRED)

...

## using the same dll , where I put the generated lib
link_directories(${PROJECT_SOURCE_DIR}/lib/x64/matting) 
link_libraries(MatService.lib)

if(MIRROR_BUILD_MATSERVICE)
    set(OpenCV_DIR  ${CMAKE_CURRENT_SOURCE_DIR}/../opencv_install)
    find_package(OpenCV REQUIRED)
    add_executable(demo ${CMAKE_CURRENT_SOURCE_DIR}/demo.cpp )
    target_link_libraries(demo  MatService ${OpenCV_LIBS} )
endif()
```
It reports errors. 
```
demo.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) class std::vector<class std::shared_ptr<class ov::Node>,class std::allocator<class std::shared_ptr<class ov::Node> > > __cdecl ov::as_node_vector(class std::vector<class ov::Output<class ov::Node>,class std::allocator<class ov::Output<class ov::Node> > > const &)" (__imp_?as_node_vector@ov@@YA?AV?$vecto
```
Which means it cannot parse external symbols.  It seems I must have to contain openivno::runtime to build any other apps.  Any advice?

**Comment by ilya-lavrenov** [comment]
Hi @dapengchen1234 

Are you using OpenVINO headers in public headers of your library?
Looks like yes, because compiler includes OpenVINO headers into demo.cpp via your library header. Please, try to avoid it.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
