### ISSUE TITLE
[Bug] Unable to import OpenVINO in python 3.9 - mac m1

### ISSUE THREAD

**Issue by mahimairaja** [openvinotoolkit/openvino#18348]
I tried to import OpenVINO on a mac m1 using python 3.9. It works pretty well on command line and script basis. But, I'm unable to import openvino from a jupyter notebook.

**Comment by ilya-lavrenov** [comment]
Hi @mahimairaja 
Please, provide any steps, error messages you have made / observed.

**Comment by avitial** [comment]
Closing this as we can't assist due to insufficient info. Feel free to reopen to provide the requested information or ask additional questions related to this topic.

**Comment by MinecraftPistachio** [comment]
I am trying to test if openvino inference exist in my venv: "from openvino.inference_engine import IECore", but it says No module named 'openvino.inference_engine', yet when I "pip list | grep openvino" there is openvino 2024.3.0, openvino-dev 2024.3.0, and openvino-telemetry 2024.1.0. Why won't the code run? I am working on MacBook pro intel i5 if that helps and python 3.9 on pycharm.

**Comment by mlukasze** [comment]
@akuporos  || @p-wysocki could you take a look for the last comment, please?

**Comment by ilya-lavrenov** [comment]
> I am trying to test if openvino inference exist in my venv: "from openvino.inference_engine import IECore", but it says No module named 'openvino.inference_engine', yet when I "pip list | grep openvino" there is openvino 2024.3.0, openvino-dev 2024.3.0, and openvino-telemetry 2024.1.0. Why won't the code run? I am working on MacBook pro intel i5 if that helps and python 3.9 on pycharm.

You are trying to import old API 1.0, which is removed since 2024.0
Please, use API 2.0 https://docs.openvino.ai/2024/get-started/install-openvino/install-openvino-pip.html#step-5-verify-that-the-package-is-installed
