### ISSUE TITLE
How to change Constant data after creation?

### ISSUE THREAD

**Issue by cansik** [openvinotoolkit/openvino#18361]
I am currently writing a model processor to change settings like for example  the iou and score threshold for `NonMaxSuppression` operators after training. Usually they are set as a [Constant](https://docs.openvino.ai/2023.0/api/ie_python_api/_autosummary/openvino.runtime.op.Constant.html#openvino.runtime.op.Constant.get_data) of type `fp32`  which I can read with `get_data()`.

But I can not figure out how to set the data to a new value?
Is the idea to delete the constant and recreate it?

**Comment by cansik** [comment]
I guess I was looking at the wrong place. Recreating the constant works and using it to replace the argument to the nms op is the solution:

```python
iou_input_index = 3

const = ov.opset1.constant(value, ov.Type.f32)
nms_op.set_argument(iou_input_index , const.output(0))
```

**Comment by cansik** [comment]
Currently I am working with `openvino==2023.3.0` and it seems that creating constants has changed. Here is an updated solution:

```python
const = ov.runtime.opset1.constant(value, ov.Type.f32)
```

**Comment by ilya-lavrenov** [comment]
> Currently I am working with `openvino==2023.3.0` and it seems that creating constants has changed. Here is an updated solution:
> 
> ```python
> const = ov.runtime.opset1.constant(value, ov.Type.f32)
> ```

@cansik do you mean the change is not BW compatible?
