### ISSUE TITLE
[Bug] OpenVINO YOLOv3  RGB OR BGR?

### ISSUE THREAD

**Issue by TNTWEN** [openvinotoolkit/openvino#1841]
Please see :https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/8  

Darknet and tensorflow(mystic123) are all RGB,but OpenVINO didn't use --reverse_input_channels,and i did't found code about 
BGR(Opencv) to RGB.  And i test my V4 models（https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/8  ）,the result is  --reverse_input_channels will get better results. So is it a mistake in the official documents？

**Comment by jgespino** [comment]
Hi @TNTWEN 

I believe the YOLOv3 model from pjreddie is RGB. The Inference Engine loads input images in BGR order, in this case, `--reverse_input_channels` is needed. The documentation includes the following note:

**Comment by TNTWEN** [comment]
Hi , @jgespino 
Yeah, i also found it.  And i hope https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html   which based on https://github.com/mystic123/tensorflow-yolo-v3  should correct this part in the future.Otherwise, it will be troublesome for the novice

To generate the IR of the YOLOv3 TensorFlow model, run:
python3 mo_tf.py
--input_model /path/to/yolo_v3.pb
--tensorflow_use_custom_operations_config $MO_ROOT/extensions/front/tf/yolo_v3.json
--batch 1
To generate the IR of the YOLOv3-tiny TensorFlow model, run:
python3 mo_tf.py
--input_model /path/to/yolo_v3_tiny.pb
--tensorflow_use_custom_operations_config $MO_ROOT/extensions/front/tf/yolo_v3_tiny.json
--batch 1

should be corrected to:


To generate the IR of the YOLOv3 TensorFlow model, run:
python3 mo_tf.py
--input_model /path/to/yolo_v3.pb
--tensorflow_use_custom_operations_config $MO_ROOT/extensions/front/tf/yolo_v3.json
--batch 1
--reverse_input_channels
To generate the IR of the YOLOv3-tiny TensorFlow model, run:
python3 mo_tf.py
--input_model /path/to/yolo_v3_tiny.pb
--tensorflow_use_custom_operations_config $MO_ROOT/extensions/front/tf/yolo_v3_tiny.json
--batch 1
--reverse_input_channels



Thanks!

**Comment by jgespino** [comment]
Thank you for your feedback @TNTWEN! I have submitted your feedback to the development team.
Please let me know if you have additional questions.

Regards,
Jesus

Ref. 37323
