### ISSUE TITLE
A Few Questions Regarding Post-training Quantization with Accuracy Control

### ISSUE THREAD

**Issue by edition3234** [openvinotoolkit/openvino#18425]
The official recommendation for the post-training quantization with accuracy control of OpenVINO models includes two methods: NNCF and Pot. I am wondering which one is better. It appears that the official side leans more towards NNCF, however, after gaining a rudimentary understanding of NNCF's quantization with accuracy control process, I discovered that it requires both a calibration dataset and a validation dataset. This seems different from Pot's approach, where it looks like an int8 model is being "retrained" based on the original model. NNCF seems to only decide whether to terminate the quantization process according to the validation function during the quantization. If I wish to pursue better quantization results, which method should I choose?

I have just started learning about quantization and I don't fully understand NNCF and Pot. Please forgive me if there are any errors in my description.

**Comment by rkazants** [comment]
@MaximProshin, @AlexKoff88, please advice

**Comment by avitial** [comment]
Closing this. I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
