### ISSUE TITLE
[Bug] Error in conversion of TF model with Lambda layers using MO

### ISSUE THREAD

**Issue by SmithaSPrem** [openvinotoolkit/openvino#18421]
- OpenVINO Source => pip install 
- OpenVINO Version => Version 2022.3 
- Operating System / Platform => Ubuntu 20

- Problem classification: Model Conversion 
- Device use: CPU 
- Framework: TensorFlow

Detailed description

conversion of tensor flow model with Lambda layers using openvino model optimizer is throwing errors. 

mo --saved_model_dir     projects/1.OPENVINO/model_1

UserWarning: model is not loaded, but a Lambda layer uses it. It may cause errors.
  function = cls._parse_function_from_config(
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'openvino.tools.mo.load.tf.loader.TFLoader'>): Unexpected exception happened during extracting attributes for node StatefulPartitionedCall/model/lambda_1/mul/x.

**Comment by rkazants** [comment]
HI @SmithaSPrem,

Can you please provide small reproducer for this issue? Can you try `2023.0.1` release?

Best regards,
Roman

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed or resolve the issue. Feel free to reopen and ask additional questions related to this topic if issue persists and share reproducer.
