### ISSUE TITLE
[Bug] Openvino gave NaN output on Arc770

### ISSUE THREAD

**Issue by Xiangyi1996** [openvinotoolkit/openvino#18449]
##### System information (version)
- OpenVINO Source => Runtime / GitHub 
- OpenVINO Version => Version 2023.0.0 / Github Master Branch 
- Operating System / Platform =>  Ubuntu 20
- Compiler => Cmake
- Problem classification: Model Conversion / Model Migration 
- Device use: GPU - Arc770
- Framework: Pytorch
- Model name: Zoedepth 

##### Detailed description
I am trying to migrate a model called ZoeDepth (https://github.com/isl-org/ZoeDepth), which is a depth estimation model (input: an image, output: a depth map). The .XML and .bin file is attached [here:](https://drive.google.com/drive/folders/1Aw9iHPCOTiRPDJgBkeC5w3S1FaI502Lo?usp=sharing)

The output is incorrect with NaN pixel value.
![zoedepth_error](https://github.com/openvinotoolkit/openvino/assets/22722992/7bf6bdf4-ba67-4b24-b728-feb2e431579d)

##### Steps to reproduce
```
cd reproducer/
pip install - r requirements.txt
python test_zoedepth.py
```

The printing the openvino infer output would be NaN for each pixel as mentioned above.

Here is the reproducer:
```
from os.path import join
import clip
import numpy as np
import torch
import time
from PIL import Image
from torchvision.transforms import ToTensor
from zoedepth.utils.misc import colorize

def get_dummy_input(image_path: str, scale: tuple):
    image = Image.open(image_path).convert('RGB')
    resized_image = image.resize(scale)

    transform = ToTensor()
    transformed_image = transform(resized_image)
    result = transformed_image.unsqueeze(0)
    print(result.shape)

    return result


def test_ov(ir_path: str, image_path: str, image_scale: tuple, ref_path='',
            alpha=0.5, device='cpu',
            out_dir='outputs', log_dir='logs', n_repeat: int = -1):
    from openvino.runtime import Core
    def to_numpy(tensor: torch.Tensor):
        return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

    core = Core()
    ir_model = core.read_model(ir_path)
    
    core.set_property("HETERO", {"MULTI_DEVICE_PRIORITIES": f"{device},CPU"})
    core.set_property(device, {"INFERENCE_PRECISION_HINT": "f32"})
    config = {"PERFORMANCE_HINT": "LATENCY"}
    model = core.compile_model(ir_model, device, config)
    image = get_dummy_input(image_path, image_scale)
    out = model.infer_new_request(image.numpy())
    #Error: out is NaN.
    print(out)
    out_list = list(out.values())[0]
    out_image = Image.fromarray(colorize(out_list)).convert('RGB')
    out_image.save('zd_ovDev_pred_gpu.png')


def main(test_mode=0):
    out_dir = './outputs'
    alpha = 0.5
    ir_path = './ov_release/ZoeDepth_opset16_480x360.xml'
    image_path = './room.jpg'
    image_scale = (480, 360)
    if test_mode != -1:
        n_repeat = 1
    else:
        n_repeat = -1

    if test_mode == 6 or test_mode == -1:
        device = 'GPU.1'
        print(f'Testing OpenVINO on {device}......')
        test_ov(ir_path, image_path, image_scale, alpha=alpha, device=device, n_repeat=n_repeat)
        print(f'Finished testing')

if __name__ == '__main__':
    main(6)
```

**Comment by Iffa-Meah** [comment]
@Xiangyi1996 

In regards to your custom inferencing code, may I know where the source of  `import clip` since I couldn't find it in the git repo you shared.



I quick-checked your model with an Intel UHD Graphic (to see whether this is related to hardware or else).
It seems that your model works with OpenVINO:

benchmark_app:
<img width="467" alt="image" src="https://github.com/openvinotoolkit/openvino/assets/79643476/a4912285-08b8-48a3-922f-46d9fdc597b9">

classification_sample_async:
<img width="481" alt="image" src="https://github.com/openvinotoolkit/openvino/assets/79643476/3412a08d-7e56-4abc-b898-5ec03d62638a">

**Comment by Xiangyi1996** [comment]
Hi @Iffa-Meah , here is the link of Clip: git+https://github.com/openai/CLIP.git in requirements.txt. And could you check your output of zoedepth? In my error case above, you can see that we can run with openvino without any error but if you debug into the code, the test_output is None.

**Comment by Iffa-Meah** [comment]
It seems that your model is unable to be inferred on both CPU and GPU (there's no error but it's hanging with no result):

<img width="851" alt="image" src="https://github.com/openvinotoolkit/openvino/assets/79643476/388ff856-1115-4c38-bb9f-e4098582fa98">

<img width="863" alt="image" src="https://github.com/openvinotoolkit/openvino/assets/79643476/3479ad6d-bcb7-4c07-9bdc-18a96eda257b">

I tested with the official OpenVINO demo since it's not likely to have issues.

The Clip library is related to CUDA which is a parallel computing platform and programming model developed by NVIDIA for general computing on graphical processing units (GPUs).

To use this library, you need NVIDIA GPU. However, the one you are using now is Intel Arc 770.

**Comment by Xiangyi1996** [comment]
Hi @Iffa-Meah thank you for your responding, but I think it is not the Clip issue. Since the Openai public [repo](https://github.com/openai/CLIP) of clip, it can run on CPU and GPU both. 

> The device to run the model can be optionally specified, and the default is to use the first CUDA device if there is any, otherwise the CPU.

**Comment by Iffa-Meah** [comment]
Your **custom code** doesn't work on both Intel UHD and ARC 770 GPU:

Intel UHD GPU:
<img width="594" alt="IntelUHDGPUfail" src="https://github.com/openvinotoolkit/openvino/assets/79643476/306e3c8a-8624-4719-87c6-6c9627a30a3d">

Intel Arc 770 GPU:
<img width="386" alt="testCodefail" src="https://github.com/openvinotoolkit/openvino/assets/79643476/3cce807b-8ffb-4a73-baca-34b0acf858c1">





Official OpenVINO Hello Classification Python Demo on Intel UHD GPU produced Nan:
<img width="865" alt="image" src="https://github.com/openvinotoolkit/openvino/assets/79643476/e6b462d9-b679-43cb-a911-4cb86653541f">


Official OpenVINO Hello Classification Python Demo on ARC 770 GPU produced Nan:
<img width="392" alt="arc770GPU" src="https://github.com/openvinotoolkit/openvino/assets/79643476/5be9dccc-8116-482f-b8c0-c7e3f1496811">


We'll further investigate this.

**Comment by avitial** [comment]
@Xiangyi1996 I am able to see the 'nan' output when executing on GPU plugin, would it be possible to share the ONNX model files? Also, does the IR model run on CPU plugin and return good output? I am having issues running the provided IR model files on CPU plugin, getting the following runtime error on v2023.0:
```
RuntimeError: Exception from src/inference/src/core.cpp:115:
[ GENERAL_ERROR ] Exception from src/common/snippets/src/lowered/pass/assign_registers.cpp:284:
can't allocate registers for a snippet
```
From the IR models provided, it seems MO from 2022.3 release was used to convert the model. Have you tried optimizing the model with MO from 2023.0 and is the result the same?

**Comment by avitial** [comment]
@Xiangyi1996 do you have any updates for us?

**Comment by Xiangyi1996** [comment]
@avitial The output on Xeon is right but in Arc machine's CPU is also NaN. Currently, we have solved this issue while updating the Ubuntu system to 22.04 and rewrite the Softplus function.
