### ISSUE TITLE
[Bug] Very strange behavior of ov::Core, not all processor cores are used

### ISSUE THREAD

**Issue by Satmaks** [openvinotoolkit/openvino#18443]
##### System information (version)
- OpenVINO Source => Runtime / GitHub 
- OpenVINO Version => Version 2023.0.0 / Github Master Branch / tag 2023.0
- Operating System / Platform => Ubuntu 18/20
- Compiler => Cmake
- Problem classification: ov::Core
- Device use: CPU

##### Detailed description
Actually, I don't have one problem. Very strange behavior of `ov::Core`.
I read in the documentation that you recommend using the `ov::Core` object in a single instance for all models. But at first I ignored this recommendation and paid for it)).
I created an `ov::Core` object for each model and noticed that the model inference only uses one processor core for multiple asynchronous `ov::InferRequest` even though I used all possible options to compile the model.
```.cpp
num_requests = 4; // For example
model_ = core.compile_model(
        model,
        "CPU",
        ov::hint::performance_mode(ov::hint::PerformanceMode::THROUGHPUT),
        ov::streams::num(num_requests),
        ov::inference_num_threads(num_requests),
        ov::hint::num_requests(num_requests),
        ov::hint::allow_auto_batching(false));
```
The thing was that the first model with the first initialization of `ov::Core` used `num_requests` processor cores, but after the destruction of the first model, I initialize the second model with the re-initialization of `ov::Core`, but this model already uses one processor core.
But after I wrote **static** `ov::Core` (the object is now in a single instance), my problem was solved. Model inference started using `num_requests` of processor cores.

I solved this problem, but that's not all.
It turned out that due to the peculiarities of my model, I cannot create parallel requests in one model.
I decided to compile multiple instances of the same model. I compiled each model with `num_requests = 1`. And I ran into the same problem again, for some reason model inferences use only one core.
Please help with this problem.
Perhaps I'm wrong about the fact that only one core is used, the htop utility shows the loading of one core ~ 60%, and the second core ~ 40%. I have 16 cores in total.

##### Steps to reproduce
Each individual thread with its own model performs such initialization.
```.cpp
num_requests = 1;
auto model = core.read_model(data_xml, ov::Tensor(ov::element::u8, {weights_.size()}, weights_.data()));
model->reshape(shapes_patch);
model_ = core.compile_model(
        model,
        "CPU",
        ov::hint::performance_mode(ov::hint::PerformanceMode::THROUGHPUT),
        ov::streams::num(num_requests),
        ov::inference_num_threads(num_requests),
        ov::hint::num_requests(num_requests),
        ov::hint::allow_auto_batching(false));
for (size_t i = 0; i < num_requests; i++)
        requests_.emplace_back(model_.create_infer_request());
```

And each separate thread processes one image.
```.cpp
num_requests = 1;
for (size_t i = 0; i < num_requests; i++) {
        auto &req = requests_[i];
        for (const auto &input_node : model_.inputs()) {
                ov::Tensor input_tensor(ov::element::f32, shape, data.ptr);
                req.set_tensor(input_node, input_tensor);
        }
        req.start_async();
}
for (size_t i = 0; i < num_requests; i++) {
        auto &req = requests_[i];
        for (const auto &output_node : model_.outputs()) {
                req.wait();
                auto output = req.get_tensor(output_node);
        }
}
```
This is pseudocode, I omitted the implementation details.
***
In addition, I have another question about the options for compiling the model.
I did not find a normal explanation in the documentation.
What is their difference?
```.cpp
ov::streams::num(num_requests),
ov::inference_num_threads(num_requests),
ov::hint::num_requests(num_requests),
```

**Comment by Satmaks** [comment]
proofs.
gdb:
```.cpp
core.compile_model()
[New Thread 0x7fffd488a700 (LWP 15688)]
[New Thread 0x7fffd1305700 (LWP 15689)]
[New Thread 0x7fffd0b04700 (LWP 15690)]
[New Thread 0x7fff8ffff700 (LWP 15691)]
[New Thread 0x7fff8f7fe700 (LWP 15692)]
model_.create_infer_request()
[New Thread 0x7fff8effd700 (LWP 15693)]
[New Thread 0x7fff8e7fc700 (LWP 15694)]
AddWorker
[New Thread 0x7fff8dffb700 (LWP 15695)] <-- my thread to process one model instance
core.compile_model()
[New Thread 0x7fff8d7fa700 (LWP 15696)]
[New Thread 0x7fff8cff9700 (LWP 15697)]
[New Thread 0x7fff7ffff700 (LWP 15698)]
[New Thread 0x7fff7f7fe700 (LWP 15699)]
[New Thread 0x7fff7effd700 (LWP 15700)]
model_.create_infer_request()
[New Thread 0x7fff7e7fc700 (LWP 15701)]
[New Thread 0x7fff7dffb700 (LWP 15702)]
AddWorker
[New Thread 0x7fff7d7fa700 (LWP 15703)] <-- my thread to process one model instance
core.compile_model()
[New Thread 0x7fff7cff9700 (LWP 15704)]
[New Thread 0x7fff7c7f8700 (LWP 15705)]
[New Thread 0x7fff7bff7700 (LWP 15706)]
[New Thread 0x7fff7b176700 (LWP 15707)]
[New Thread 0x7fff7a975700 (LWP 15708)]
model_.create_infer_request()
[New Thread 0x7fff7a174700 (LWP 15709)]
[New Thread 0x7fff79973700 (LWP 15710)]
AddWorker
[New Thread 0x7fff79172700 (LWP 15711)] <-- my thread to process one model instance
core.compile_model()
[New Thread 0x7fff78971700 (LWP 15713)]
[New Thread 0x7fff63fff700 (LWP 15714)]
[New Thread 0x7fff637fe700 (LWP 15715)]
[New Thread 0x7fff6293d700 (LWP 15716)]
[New Thread 0x7fff6213c700 (LWP 15717)]
model_.create_infer_request()
[New Thread 0x7fff6193b700 (LWP 15718)]
[New Thread 0x7fff6113a700 (LWP 15719)]
AddWorker
[New Thread 0x7fff60939700 (LWP 15720)] <-- my thread to process one model instance
```
htop:
![Снимок экрана от 2023-07-08 23-07-08](https://github.com/openvinotoolkit/openvino/assets/48041726/ff0ad6e6-6dff-4012-ba85-62d834f52866)

**Comment by ilyachur** [comment]
CC @dmitry-gorokhov @wangleis

**Comment by wangleis** [comment]
@Satmaks Could you share the detail of your platform information, log of `lscpu` and `lscpu -e`?

From my understanding, there are three situations:

1. After initialization of `ov::Core` and loading first model, multi threading works well which run inference on num_requests of processor cores. 
2. After destruction of the first model, re-initialization of `ov::Core` and loading second model, inference only run on single processor core. For this situation, could you please try to skip re-initialization of `ov::Core`?
3. After loading multiple models, multi threading cannot work well. For this situation, could you please try to set `ov::hint::enable_cpu_pinning` to  false on master branch?

**Comment by wangleis** [comment]
@Satmaks Please try `ov::affinity(ov::Affinity::NUMA)` instead of `ov::affinity(ov::Affinity::NONE)`

`ov::streams::num()` is used to set the number of infer requests to run in parallel on CPU.
`ov::inference_num_threads()` is used to set the number of processors used for inference
`ov::hint::num_requests` is used to set the number of infer requests application created for input.

**Comment by Satmaks** [comment]
@wangleis Compiling with the `ov::affinity(ov::Affinity::NUMA)` flag is twice as slow in performance as with the `ov::affinity(ov::Affinity::NONE)` flag.
I'll add that I benchmarked using all the `ov::Affinity` compilation flags along with the `ov::hint::enable_cpu_pinning` flag. The `ov::hint::enable_cpu_pinning` flag had no effect on performance.

**Comment by Satmaks** [comment]
> `ov::streams::num()` is used to set the number of infer requests to run in parallel on CPU.
`ov::inference_num_threads()` is used to set the number of processors used for inference
`ov::hint::num_requests` is used to set the number of infer requests application created for input.

I didn't fully understand.
ov::inference_num_threads() - how many CPU cores to use for inference.
ov::streams::num() - how many threads to create on allocated processor cores.
ov::hint::num_requests - if I understand correctly, this has nothing to do with the number of threads or processor cores, right? I can have a lot of requests, and how many requests will be executed in parallel depends on the previous settings, right?

**Comment by wangleis** [comment]
Please find more detail about `ov::streams` at https://docs.openvino.ai/2022.3/openvino_docs_deployment_optimization_guide_tput_advanced.html#openvino-streams. 

Please find more detail about `ov::hint::num_requests` at https://docs.openvino.ai/2022.3/openvino_docs_OV_UG_Performance_Hints.html#optimal-number-of-inference-requests.

**Comment by wangleis** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
