### ISSUE TITLE
[Bug]benchmark_app -d GPU Error GPU program build failed! Program build failed(0_part_0): You may enable OCL source dump to see the error log.

### ISSUE THREAD

**Issue by biyuehuang** [openvinotoolkit/openvino#18452]
- OpenVINO Source => Runtime /pip install 
- OpenVINO Version =>  2023.0.1
- Operating System / Platform => Ubuntu 22.04
- Device use: CPU / GPU / 
- Model name: ResNet50-pytoch

$ lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)

$ clinfo | grep "Driver Version"
  Driver Version                                  23.17.26241.21

$ benchmark_app -h
Available target devices:   CPU  GPU

$ benchmark_app -m /resnet-50-pytorch/FP16/resnet-50-pytorch.xml -d GPU
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ]
[ INFO ] Device info:
[ INFO ] GPU
[ INFO ] Build ................................. 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(GPU) performance hint will be set to PerformanceMode.THROUGHPUT.
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 7.56 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Model inputs:
[ INFO ]     data (node: data) : f32 / [N,C,H,W] / [1,3,224,224]
[ INFO ] Model outputs:
[ INFO ]     prob (node: prob) : f32 / [...] / [1,1000]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Model batch size: 1
[Step 6/11] Configuring input of the model
[ INFO ] Model inputs:
[ INFO ]     data (node: data) : u8 / [N,C,H,W] / [1,3,224,224]
[ INFO ] Model outputs:
[ INFO ]     prob (node: prob) : f32 / [...] / [1,1000]
[Step 7/11] Loading the model to the device
[ ERROR ] Check 'false' failed at src/inference/src/core.cpp:114:
Check 'false' failed at src/plugins/intel_gpu/src/plugin/program.cpp:386:
GPU program build failed!
Program build failed(0_part_0): You may enable OCL source dump to see the error log.

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/ov2023.0/lib/python3.8/site-packages/openvino/tools/benchmark/main.py", line 408, in main
    compiled_model = benchmark.core.compile_model(model, benchmark.device, device_config)
  File "/home/ubuntu/miniconda3/envs/ov2023.0/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 398, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Check 'false' failed at src/inference/src/core.cpp:114:
Check 'false' failed at src/plugins/intel_gpu/src/plugin/program.cpp:386:
GPU program build failed!
Program build failed(0_part_0): You may enable OCL source dump to see the error log.

**Comment by geunhwan** [comment]
@biyuehuang Is it regression on your side. I'm wondering if this model was working previously on your side. If so, what is changed compared to successful run? OpenVINO version is the only change?

**Comment by biyuehuang** [comment]
> @biyuehuang Is it regression on your side? I'm wondering if this model was working previously on your side. If so, what is changed compared to successful run? OpenVINO version is the only change?

Hi OpenVINO version 2023.0.1, model convert by omz_converter. "$ benchmark_app -m /resnet-50-pytorch/FP16/resnet-50-pytorch.xml -d CPU" is OK.

**Comment by biyuehuang** [comment]
Solved problem by install driver 23.09.25812.14 : https://github.com/intel/compute-runtime/releases
