### ISSUE TITLE
Extend ONNX Frontend with `BlackmanWindow`, `HammingWindow` and `HannWindow` operators

### ISSUE THREAD

**Issue by mbencer** [openvinotoolkit/openvino#18483]
## Context
Neural networks are graphs consisting of nodes called operators. Each operator corresponds to a mathematical function, usually described in framework's documentation or an AI standard, such as ONNX.

OpenVINO ONNX Frontend is a component responsible for working with ONNX graphs and requires implementation of different ONNX operators in order to use ONNX models.

This task requires extending OpenVINO ONNX Frontend with `BlackmanWindow`, `HammingWindow` and `HannWindow` operators.

Necessary help will be provided by ONNX Fronted team.

## Operator specification
Operator details can be found in [ONNX Operators](https://github.com/onnx/onnx/blob/main/docs/Operators.md).

## Todo list
1. Create `.hpp` and `.cpp` files for *Windows [here](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op)
2. Prepare an implementation of this operator in form of a function. It should be placed in [opset 1 namespace](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/unique.hpp#L13).
3. Register the function in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560) while keeping alphabetical order
4. Create test model(s) in [ONNX models directory](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/tests/models/). OpenVINO test infrastructure then converts prototxt files to ONNX models - you will use those models later in tests
5. Add tests covering all use cases [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import.in.cpp)

More details in [adding operators to ONNX Frontend guide](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md)

## Resources
- Guides on [ONNX Frontend architecture](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/architecture.md) and [ONNX Frontend tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/tests.md) are also available
- Contribution guidelines can be found [here](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- You can also see a [blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

## Example PRs
- https://github.com/openvinotoolkit/openvino/pull/15076
- https://github.com/openvinotoolkit/openvino/pull/14936
- https://github.com/openvinotoolkit/openvino/pull/12510

## Tips
In ONNX specification example code, you can find `numpy` implementation which can be a good reference. 
[BlackmanWindow](https://github.com/onnx/onnx/blob/main/docs/Operators.md#blackmanwindow)
```
# periodic window
size = np.int32(10)
a0 = 0.42
a1 = -0.5
a2 = 0.08
y = a0
y += a1 * np.cos(2 * 3.1415 * np.arange(0, size, 1, dtype=np.float32) / size)
y += a2 * np.cos(4 * 3.1415 * np.arange(0, size, 1, dtype=np.float32) / size)

# symmetric window
size = np.int32(10)
a0 = 0.42
a1 = -0.5
a2 = 0.08
y = a0
y += a1 * np.cos(
    2 * 3.1415 * np.arange(0, size, 1, dtype=np.float32) / (size - 1)
)
y += a2 * np.cos(
    4 * 3.1415 * np.arange(0, size, 1, dtype=np.float32) / (size - 1)
)
```
[HammingWindow](https://github.com/onnx/onnx/blob/main/docs/Operators.md#hammingwindow)
```
# periodic window
size = np.int32(10)
a0 = 25 / 46
a1 = 1 - a0
y = a0 - a1 * np.cos(
    2 * 3.1415 * np.arange(0, size, 1, dtype=np.float32) / size
)

#symmetric window
size = np.int32(10)
a0 = 25 / 46
a1 = 1 - a0
y = a0 - a1 * np.cos(
    2 * 3.1415 * np.arange(0, size, 1, dtype=np.float32) / (size - 1)
)
```
[HannWindow](https://github.com/onnx/onnx/blob/main/docs/Operators.md#hannwindow)
```
# periodic window
size = np.int32(10)
a0 = 0.5
a1 = 0.5
y = a0 - a1 * np.cos(
    2 * 3.1415 * np.arange(0, size, 1, dtype=np.float32) / size
)

# symmetric window
size = np.int32(10)
a0 = 0.5
a1 = 0.5
y = a0 - a1 * np.cos(
    2 * 3.1415 * np.arange(0, size, 1, dtype=np.float32) / (size - 1)
)
```
Note that OV equivalant of `numpy.arange` can be [OV Range op](https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/generation/Range_4.md)

## Contact points
@mbencer
@p-wysocki
Don't hesitate to reach out, we're here to help!

**Comment by abhamedewar** [comment]
Hi @p-wysocki, 

I want to start working on this can you assign this to me?

Thank you!!

**Comment by mlukasze** [comment]
hey @abhamedewar 
Thank you and welcome.
The task has been assigned as requested.
Good luck and happy coding! :)

**Comment by p-wysocki** [comment]
Hi @abhamedewar,
Could you please provide more details about your question? If you mean inputs to the operators themselves, the details can be found in the documentation linked in the issue description.
- [BlackmanWindow](https://github.com/onnx/onnx/blob/main/docs/Operators.md#blackmanwindow)
- [HammingWindow](https://github.com/onnx/onnx/blob/main/docs/Operators.md#hammingwindow)
- [HannWindow](https://github.com/onnx/onnx/blob/main/docs/Operators.md#hannwindow)

**Comment by p-wysocki** [comment]
I'm returning the task to being open due to current assignee's inactivity.

**Comment by p-wysocki** [comment]
Hey @siddhant-0707, thanks for taking an interest. :) I'm assigning the issue to you.

**Comment by p-wysocki** [comment]
PR: https://github.com/openvinotoolkit/openvino/pull/19428
