### ISSUE TITLE
[Bug] fail to run model with openvino

### ISSUE THREAD

**Issue by baaj2109** [openvinotoolkit/openvino#18523]
##### System information (version)

- OpenVINO Source=> Runtime
- OpenVINO Version=>  2022.3
- Operating System / Platform => :Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification => :grey_question:
- Device use: => GPU
- Framework => 
- Model name => 

##### Detailed description

Hi, I want to run my own inpatient model with openvino in C++, but when I run the code below
```
ov::Core m_core;
m_core.set_property(ov::cache_dir(cache_path));
m_model = m_core.read_model(xml_path);
m_compiled_model = m_core.compile_model(m_model, "GPU",
				ov::hint::performance_mode(ov::hint::PerformanceMode::LATENCY));
```
I always got an error message 

> The procedure entry point c|CreateCommandQueueWithProperties could not be located in the dynamic link library C:\Program Files\test\openvino_intel_gpu_plugin.dll.

Is there any solution to fix this error

my system info is
Processor Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz 3.10 GHz
Installed RAM 64.0 GB (63.8 GB usable)
System type 64-bit operating system, x64-based processor

Edition Windows 11 Pro
Version 21H2
OS build 22000.2057
OpenCL Version 3.0.1.0

**Comment by ilya-lavrenov** [comment]
Hi @baaj2109 

> C:\Program Files\test\openvino_intel_gpu_plugin.dll

Could you please explain why Intel GPU plugin is trying to be found in `C:\Program Files\test` ? It's not standard OpenVINO directory structure. How have you installed / built OpenVINO? where are other OpenVINO dlls are located?

Googling shows the link mentions link 
https://softwarekeep.com/help-center/repair-the-procedure-entry-point-could-not-be-located-error-in-windows-10#

**Comment by baaj2109** [comment]
Thank you for the prompt response.
 This C++ program will be packaged for others to use, so the folder structure will be slightly different, and that's why try to found openvino_intel_gpu_plugin.dll C:\Program Files\test. After installing the OpenVINO runtime, I will copy all the files from the "bin/intel64" and "tbb/bin" directories to my project.

**Comment by hbalasu1** [comment]
Hi @baaj2109 

Your code looks good to me, just when you compile your C++ code, the compiler is not able to locate the .dll file, 
I think it would be good if you could install the OpenVINO to the right directory by referring to this [documentation](https://docs.openvino.ai/2023.0/openvino_docs_install_guides_installing_openvino_from_archive_windows.html). 

After completing the OpenVINO installation, please make sure you have the GPU driver installed and initialized setupvars.bat

After you have followed the instruction and still received the error message, you can test with the CPU if it works and give us a log for further debugging.

**Comment by hbalasu1** [comment]
Hi @baaj2109 
Just to follow up, if your issue resolved by changing the installation directory?

**Comment by baaj2109** [comment]
Everything looks good, after move all dll to the right directory. But I still can't figure out what happen on this computer, other computers work fine if dll in wrong directory

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
