### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [openvinotoolkit/openvino#18572]
Hi!

Recently I checked Profile-Guided Optimization (PGO) improvements on multiple projects. The results are [here](https://github.com/zamazan4ik/awesome-pgo/). LLVM-related results are [here](https://github.com/llvm/llvm-project/issues/63486).

Since PGO showed measurable improvements in compiler-like loads (CPython, Clang, Clangd, clang-format, GCC, Rustc, etc.) I think it could be useful to check PGO on OpenVino as well.

We need to perform PGO benchmarks on OpenVino. And if it shows improvements - add a note about possible improvements in OpenVino performance with PGO. Providing an easier way (e.g. a build option) to build scripts with PGO can be useful for the end-users too. Maybe testing Post-Link Optimization techniques (like LLVM BOLT from Facebook) would be interesting too but I recommend starting from the usual PGO.

I think the good starting point here could be recompiling 3rd parties with PGO (that's usually a good thing to do if possible). Another possible piece of code, that highly-likely (according to my guess) can be well-optimized with PGO is [frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends). If you have better ideas - feel free to correct me!

**Comment by avitial** [comment]
@zamazan4ik thank you for providing feedback, we have captured your request and shared it with development team for consideration.


Ref. 116417

**Comment by zamazan4ik** [comment]
I think the results regarding optimizing Tensorflow (`tfcompile`) - https://github.com/tensorflow/tensorflow/issues/60944#issuecomment-1637143591 .
