### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by KhalilBDJ** [openvinotoolkit/openvino#18597]
- OpenVINO Source =>  GitHub 
- OpenVINO Version =>GitHub 2023/0 tags 2023.0.1-21-gafb2ebcdd4
- Operating System / Platform => Windows 64 Bit (Windows 10 and 11)
- Compiler => CMake 3.17 
- Problem classification: Error Building
- Device use: CPU (Processor	Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s))
Also happenned with another 8th generation CPU.

##### Detailed description
```
C:\Program Files (x86)\Intel\openvino\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\openvino_intel_cpu_plugin.vcxproj" (default t
       arget) (45) ->
       "C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\openvino_intel_cpu_plugin_version.vcxproj" (d
       efault target) (47) ->
       "C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\src\dnnl.vcxproj" (default
       target) (48) ->
       "C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\src\common\dnnl_common.vcxp
       roj" (default target) (49) ->
       (_MASM target) ->
         MASM : fatal error A1000: cannot open file : Files [C:\Program Files (x86)\Intel\openvino\build\src\plugins\in
       tel_cpu\thirdparty\onednn\src\common\dnnl_common.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\ma
       sm.targets(70,5): error MSB3721: The command "ml64.exe /c /nologo /Zi /Fo"dnnl_common.dir\Release\ittptmark64.ob
       j" /D"WIN32" /D"_WINDOWS" /D"_CRT_SECURE_NO_WARNINGS" /D"_SCL_SECURE_NO_WARNINGS" /D"NOMINMAX" /D"ITT_API_IPT_SU
       PPORT" /D"NDEBUG" /D"IE_BUILD_POSTFIX=""" /D"PROJECT_ROOT_DIR="C:/Program Files (x86)/Intel/openvino"" /D"DNNL_X
       64=1" /D"__STDC_LIMIT_MACROS" /D"__STDC_CONSTANT_MACROS" /D"DNNL_ENABLE_CONCURRENT_EXEC" /D"DNNL_ENABLE_MAX_CPU_
       ISA" /D"DNNL_ENABLE_CPU_ISA_HINTS" /D"_WIN" /D"WIN32_LEAN_AND_MEAN" /D"DNNL_XBYAK_NO_EXCEPTION" /D"__TBB_NO_IMPL
       ICIT_LINKAGE=1" /D"CMAKE_INTDIR="Release"" /I "C:\Program Files (x86)\Intel\openvino\src\plugins\intel_cpu\third
       party\onednn\include" /I "C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\in
       clude" /I "C:\Program Files (x86)\Intel\openvino\src\plugins\intel_cpu\thirdparty\onednn\src" /I "C:\Program Fil
       es (x86)\Intel\openvino\src\common\conditional_compilation\include" /I "C:\Program Files (x86)\Intel\openvino\sr
       c\common\itt\include" /I "C:\Program Files (x86)\Intel\openvino\src\common\util\include" /I "C:\Program Files (x
       86)\Intel\openvino\temp\tbb\include" /W3 /errorReport:prompt  /Ta"C:\Program Files (x86)\Intel\openvino\src\plug
       ins\intel_cpu\thirdparty\onednn\src\common\ittnotify\ittptmark64.asm"" exited with code 1. [C:\Program Files (x8
       6)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\src\common\dnnl_common.vcxproj]
       
Error	LNK1181	cannot open input file 'C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\src\common\dnnl_common.dir\Release\batch_normalization.obj'	dnnl	C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\src\LINK	1	

Error	A1000	cannot open file : Files	dnnl_common	C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\src\common\MASM	1	
```
       
       CPU is supposed to be compatible with openVino according to documentation

##### Steps to reproduce

   Build the solution, 1 error only happens which make the CPU device unusable for C++ programs. 
   ran the following command in the build directory (inside openvino directory) : "cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release ../" then "cmake --build . --config Release --verbose -j8"

**Comment by ilya-lavrenov** [comment]
@KhalilBDJ could you please provide a full build log?
Your log just reports a conclusion error, but the actual reason is not clear.

**Comment by KhalilBDJ** [comment]
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
2>------ Build started: Project: util, Configuration: Release x64 ------
2>util.vcxproj -> C:\Program Files (x86)\Intel\openvino\bin\intel64\Release\util.lib
3>------ Build started: Project: itt, Configuration: Release x64 ------
3>itt.vcxproj -> C:\Program Files (x86)\Intel\openvino\bin\intel64\Release\itt.lib
4>------ Build started: Project: dnnl_common, Configuration: Release x64 ------
5>------ Build started: Project: dnnl_cpu, Configuration: Release x64 ------
6>------ Build started: Project: dnnl_cpu_x64, Configuration: Release x64 ------
4>Assembling C:\Program Files (x86)\Intel\openvino\src\plugins\intel_cpu\thirdparty\onednn\src\common\ittnotify\ittptmark64.asm...
4>MASM : fatal error A1000: cannot open file : Files
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm.targets(70,5): error MSB3721: The command "ml64.exe /c /nologo /Zi /Fo"dnnl_common.dir\Release\ittptmark64.obj" /D"WIN32" /D"_WINDOWS" /D"_CRT_SECURE_NO_WARNINGS" /D"_SCL_SECURE_NO_WARNINGS" /D"NOMINMAX" /D"ITT_API_IPT_SUPPORT" /D"NDEBUG" /D"IE_BUILD_POSTFIX=""" /D"PROJECT_ROOT_DIR="C:/Program Files (x86)/Intel/openvino"" /D"DNNL_X64=1" /D"__STDC_LIMIT_MACROS" /D"__STDC_CONSTANT_MACROS" /D"DNNL_ENABLE_CONCURRENT_EXEC" /D"DNNL_ENABLE_MAX_CPU_ISA" /D"DNNL_ENABLE_CPU_ISA_HINTS" /D"_WIN" /D"DNNL_XBYAK_NO_EXCEPTION" /D"CMAKE_INTDIR="Release"" /I "C:\Program Files (x86)\Intel\openvino\src\plugins\intel_cpu\thirdparty\onednn\include" /I "C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\include" /I "C:\Program Files (x86)\Intel\openvino\src\plugins\intel_cpu\thirdparty\onednn\src" /I "C:\Program Files (x86)\Intel\openvino\src\common\conditional_compilation\include" /I "C:\Program Files (x86)\Intel\openvino\src\common\itt\include" /I "C:\Program Files (x86)\Intel\openvino\src\common\util\include" /W3 /errorReport:prompt  /Ta"C:\Program Files (x86)\Intel\openvino\src\plugins\intel_cpu\thirdparty\onednn\src\common\ittnotify\ittptmark64.asm"" exited with code 1.
4>Done building project "dnnl_common.vcxproj" -- FAILED.
5>dnnl_cpu.vcxproj -> C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\src\cpu\dnnl_cpu.dir\Release\dnnl_cpu.lib
6>dnnl_cpu_x64.vcxproj -> C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\src\cpu\x64\dnnl_cpu_x64.dir\Release\dnnl_cpu_x64.lib
7>------ Build started: Project: dnnl, Configuration: Release x64 ------
7>LINK : fatal error LNK1181: cannot open input file 'C:\Program Files (x86)\Intel\openvino\build\src\plugins\intel_cpu\thirdparty\onednn\src\common\dnnl_common.dir\Release\batch_normalization.obj'
7>Done building project "dnnl.vcxproj" -- FAILED.
8>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
8>Building Custom Rule C:/Program Files (x86)/Intel/openvino/src/plugins/intel_cpu/thirdparty/onednn/CMakeLists.txt
========== Build: 6 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

it seems that that the Program Files path isn't working since it has spaces in it no ? because it tries to open "Files" from "Program Files (x86)" in PROJECT_ROOT_DIR="C:/Program Files (x86)/Intel/openvino"

**Comment by ilya-lavrenov** [comment]
You can try with `ENABLE_PROFILING_ITT=OFF`

**Comment by ilya-lavrenov** [comment]
Yes:
```cmake
cmake -DENABLE_PROFILING_ITT=OFF -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019"  ../ 
```

**Comment by KhalilBDJ** [comment]
> Yes:
> 
> ```cmake
> cmake -DENABLE_PROFILING_ITT=OFF -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019"  ../ 
> ```

Still not working with the same error unfortunately :(

**Comment by ilya-lavrenov** [comment]
> but I still want to build the solution inside Program Files (x86) if possible

Why do you need it?
In any case you can build in any location, and then install into desired location by setting `CMAKE_INSTALL_PREFIX=C/Program Files (x86)`

**Comment by KhalilBDJ** [comment]
> Why do you need it? In any case you can build in any location, and then install into desired location by setting `CMAKE_INSTALL_PREFIX=C/Program Files (x86)`

Okay thanks !

**Comment by kuaiyouxiaozi** [comment]
> > Yes:
> > ```cmake
> > cmake -DENABLE_PROFILING_ITT=OFF -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019"  ../ 
> > ```
> 
> Still not working with the same error unfortunately :(
i meet the same question to you, what you how to  solve it !  thanks!
