### ISSUE TITLE
How to convert a model with custom operations in Model Optimizer?

### ISSUE THREAD

**Issue by Satmaks** [openvinotoolkit/openvino#18593]
- OpenVINO Source => pip install
- OpenVINO Version => tag 2023.0 
- Operating System / Platform => Ubuntu 18/20
- Compiler => Cmake
- Problem classification: Model Conversion
- Device use: CPU
- Framework: PyTorch

##### Detailed description
Hello, how can I convert a model with custom operations in Model Optimizer?
The documentation has this [clause](https://docs.openvino.ai/2023.0/openvino_docs_Extensibility_UG_Intro.html#create-a-library-with-extensions).
> Conversion of a model with custom operations in Model Optimizer.

But it is not written how to do it)))

I can convert the model without custom operations like this (pseudocode):
```.py
from openvino.tools.mo import convert_model
ov_model = convert_model(input_model=onnx_path, ...)
```
It's okay.

As stated in the [documentation](https://docs.openvino.ai/2023.0/openvino_docs_Extensibility_UG_Intro.html#create-a-library-with-extensions), I built my extension library for my custom operation, but what do I do with it next?
Help me please)

**Comment by Satmaks** [comment]
Other than that, I was trying to build an OpenVINO wheel with my custom operations so that I can install it later with pip. But I am getting an error.
```.py
Traceback (most recent call last):
  File "...", line 5, in <module>
    from openvino.tools.mo import convert_model
  File ".../.env3/lib/python3.9/site-packages/openvino/tools/mo/__init__.py", line 4, in <module>
    from .convert import convert_model, InputCutInfo, LayoutMap
  File ".../.env3/lib/python3.9/site-packages/openvino/tools/mo/convert.py", line 8, in <module>
    from openvino.runtime import PartialShape, Shape, Layout, Model
  File ".../.env3/lib/python3.9/site-packages/openvino/runtime/__init__.py", line 12, in <module>
    from openvino._pyopenvino import get_version
ImportError: .../.env3/lib/python3.9/site-packages/openvino/_pyopenvino.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
```

**Comment by Satmaks** [comment]
Sorry guys I found this link https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/custom_operations here https://docs.openvino.ai/2023.0/openvino_docs_Extensibility_UG_Frontend_Extensions.html#frontend-extensions. There is what I need.

**Comment by andrei-kochin** [comment]
@Satmaks feel free to re-open in case any clarification on extensions are required

**Comment by Satmaks** [comment]
@andrei-kochin I converted the model with custom operations.
According to the instructions, I build my extension, which dynamically uses the pre-installed `openvino::runtime`.
Can I build my extension statically with `openvino` and pass it to the Model Optimizer?

I statically compiled my extension, but the `mo` command does not respond in any way.
But other than that, I also use `mo` via the Python API. That is, I do this:
```.py
from openvino.tools.mo import convert_model
ov_model = convert_model(input_model=onnx_path, extensions=".so")
```
And I get this error:
```.py
Current thread 0x00007f520ffd6640 (most recent call first):
  File ".../.env3/lib/python3.9/site-packages/openvino/tools/mo/moc_frontend/pipeline.py", line 266 in moc_pipeline
  File ".../.env3/lib/python3.9/site-packages/openvino/tools/mo/convert_impl.py", line 404 in prepare_ir
  File ".../.env3/lib/python3.9/site-packages/openvino/tools/mo/convert_impl.py", line 591 in driver
  File ".../.env3/lib/python3.9/site-packages/openvino/tools/mo/convert_impl.py", line 915 in _convert
  File ".../.env3/lib/python3.9/site-packages/openvino/tools/mo/convert.py", line 348 in convert_model
[1]    28166 segmentation fault (core dumped) 
```
But if I call the command `source /opt/intel/openvino_2023/setupvars.sh` and repeat this:
```.py
from openvino.tools.mo import convert_model
ov_model = convert_model(input_model=onnx_path, extensions=".so")
```
In that case, it works. What am I missing?

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
