### ISSUE TITLE
How to Enable Qt to Link to OpenVINO in Linux Systems

### ISSUE THREAD

**Issue by OnlyForWW** [openvinotoolkit/openvino#18659]
**My Linux system is Ubuntu 22.04
I have successfully installed OpenViNO 2022.3.1 runtime**
How can I operate OpenVINO in Qt?
Thank you.

**Comment by ilyachur** [comment]
Hi,

OpenVINO is a library... So you can manually change Qt project settings to add OpenVINO libraries to your project.
Also Qt can use cmake for the project configuration: https://doc.qt.io/qt-6/cmake-get-started.html in this case you can use find package to find OpenVINO and link with your project (you can take a look to the cpp samples to find an example). 

Any way, OpenVINO from your project perspective is a third-party library. It will be better to ask this question on Qt forum.

**Comment by ilya-lavrenov** [comment]
Documentation how to find and link OpenVINO in cmake projects https://docs.openvino.ai/2023.0/openvino_docs_OV_UG_Integrate_OV_with_your_application.html#create-cmake-script

**Comment by OnlyForWW** [comment]
Thank you for your answer. I have successfully resolved this issue. @ilya-lavrenov @ilyachur
