### ISSUE TITLE
OpenVINO Wheel does not install Debug libraries when CMAKE_BUILD_TYPE is Debug

### ISSUE THREAD

**Issue by sspintel** [openvinotoolkit/openvino#18786]
- OpenVINO Source => GitHub 
- OpenVINO Version => master branch
- Operating System / Platform =>Ubuntu 20
- Compiler => Cmake 3.27.0
- Problem classification: Python Wheel
- Device use: CPU 

When building OpenVINO runtime and the python wheel using Debug mode, the libs installed onto the Python wheel seem to be Release libs. The runtime Debug libs are not being installed into the wheel. This makes it hard to debug OpenVINO libs when working with the Python API during development.

My CMake command:

`cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_MODELS=OFF -DENABLE_VALIDATION_SET=OFF -DENABLE_AVX2=ON -DENABLE_AVX512F=ON -DENABLE_TESTS=OFF -DENABLE_FUNCTIONAL_TESTS=OFF -DENABLE_PROFILING_ITT=ON -DENABLE_INTEL_GPU=ON -DENABLE_INTEL_CPU=ON -DENABLE_ONEDNN_FOR_GPU=OFF -DENABLE_PYTHON=OFF -DENABLE_INTEL_MYRIAD_COMMON=OFF -DENABLE_INTEL_MYRIAD=OFF -DENABLE_GAPI_TESTS=OFF -DENABLE_DATA=OFF -DENABLE_BEH_TESTS=OFF -DENABLE_OV_ONNX_FRONTEND=OFF -DENABLE_OV_PADDLE_FRONTEND=OFF -DENABLE_OV_TF_FRONTEND=OFF -DENABLE_OV_TF_LITE_FRONTEND=OFF -DENABLE_PLUGINS_XML=ON -DENABLE_INTEL_GNA=OFF -DENABLE_OPENCV=ON -DUSE_Z7=1 -DENABLE_PYTHON=ON -DENABLE_WHEEL=ON -DENABLE_OV_PYTORCH_FRONTEND=ON`

Relates to https://github.com/openvinotoolkit/openvino/pull/18029

**Comment by ilya-lavrenov** [comment]
You don't need to build wheels to debug Python API.
Just build OpenVINO and set `PYTHONPATH` to `<source dir>/bin/intel64/Debug/python`

**Comment by sspintel** [comment]
Hi Ilya, Thanks for the suggestion but I get this when I set PYTHONPATH instead of using the wheel. It's also a bit counterintuitive that we get wheels with release mode libs when building in debug mode. Earlier we used to get debug libs in the wheel.

`pybind11::handle::inc_ref() is being called while the GIL is either not held or invalid. Please see https://pybind11.readthedocs.io/en/stable/advanced/misc.html#common-sources-of-global-interpreter-lock-errors for debugging advice.The failing pybind11::handle::inc_ref() call was triggered on a NoneType object`
