### ISSUE TITLE
How to use C++API for image classification?

### ISSUE THREAD

**Issue by OnlyForWW** [openvinotoolkit/openvino#18804]
Can you provide a simple case? The C++example in the official file is too complex.
Thanks

**Comment by ilyachur** [comment]
Hi @OnlyForWW ,

You can take a look to the OpenVINO sample:
https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/hello_classification/main.cpp

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
