### ISSUE TITLE
How can I improve inference speed with OpenVINO tools?

### ISSUE THREAD

**Issue by glucasol** [openvinotoolkit/openvino#18828]
##### System information (version)

- OpenVINO Source => pip install openvino-dev
- OpenVINO Version => Version 2023.0.1
- Operating System / Platform => Ubuntu 20.04
- Device use: CPU

##### Detailed description
Hi everyone, I have followed this [Notebook](https://github.com/openvinotoolkit/anomalib/blob/main/notebooks/500_use_cases/501_dobot/501a_training_a_model_with_cubes_from_a_robotic_arm.ipynb) from [Anomalib repo](https://github.com/openvinotoolkit/anomalib) to train/validate an anomaly detection model. I have successfully trained, tested and exported to OpenVINO IR (bin and xml files) - the pipeline of the notebook generates this exported model. 

I was able to reproduce the inference with the OpenVINO model and the times are ok, **but I want to know how can I improve the inference speed? Is there a way to run the inference with the OpenVINO tools to improve the performance and get more FPS?** 

##### Steps to reproduce

Just follow the steps described in the Notebook attached below in the .zip file, which is the same as mentioned above.
[501a_training_a_model_with_cubes_from_a_robotic_arm.zip](https://github.com/openvinotoolkit/openvino/files/12187747/501a_training_a_model_with_cubes_from_a_robotic_arm.zip)

Thanks!!

**Comment by wenjiew** [comment]
Please take a look at this documentation to see whether it is helpful. Thanks!
https://docs.openvino.ai/2023.0/openvino_docs_deployment_optimization_guide_dldt_optimization_guide.html

**Comment by glucasol** [comment]
Hi @wenjiew ,
Is there an example of how to do these optimization mentioned in the guide? I am new to OpenVINO and don't have much knowledge about it.

Thanks!

**Comment by wenjiew** [comment]
I recommend starting with the OpenVINO samples, first with: 
https://github.com/openvinotoolkit/openvino/tree/master/samples/cpp/hello_classification
Then, a follow-up example is the benchmark tools for throughput:, where a number of methods are used: 
https://github.com/openvinotoolkit/openvino/tree/master/samples/cpp/benchmark/throughput_benchmark

**Comment by xczhai** [comment]
@glucasol 
please refer to https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/109-performance-tricks
It is about latency and throughput performance trick.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
