### ISSUE TITLE
Question: openvino support for Nvidia Jetson Xavier ?

### ISSUE THREAD

**Issue by moyu026** [openvinotoolkit/openvino#18831]
I wonder know if openvino supports for Nvidia Jetson Xavier. I try to pip install openvino-dev, it always fails and has a same error:

- Collecting scikit-learn~=0.24.1 (from openvino-dev[paddle])
-   Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
-   Installing build dependencies ... done
-   Getting requirements to build wheel ... done
-   Preparing metadata (pyproject.toml) ... error
-   error: subprocess-exited-with-error
-   
-   × Preparing metadata (pyproject.toml) did not run successfully.
-   │ exit code: 1
-   ╰─> [847 lines of output]
-       <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
-       Partial import of sklearn during the build process.
-       <string>:116: DeprecationWarning:
-       
-         `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
-         of the deprecation of `distutils` itself. It will be removed for
-         Python >= 3.12. For older Python versions it will remain present.
-         It is recommended to use `setuptools < 60.0` for those Python versions.
-         For more details, see:
-           https://numpy.org/devdocs/reference/distutils_status_migration.html
-       
-       
-       INFO: C compiler: gcc -pthread -B /home/nvidia/anaconda3/envs/openvino/compiler_compat -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -fPIC -O3 -isystem /home/nvidia/anaconda3/envs/openvino/include -fPIC -O3 -isystem /home/nvidia/anaconda3/envs/openvino/include -fPIC
-       
-       INFO: compile options: '-c'
-       INFO: gcc: test_program.c
-       INFO: gcc -pthread -B /home/nvidia/anaconda3/envs/openvino/compiler_compat objects/test_program.o -o test_program
-       INFO: C compiler: gcc -pthread -B /home/nvidia/anaconda3/envs/openvino/compiler_compat -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -fPIC -O3 -isystem /home/nvidia/anaconda3/envs/openvino/include -fPIC -O3 -isystem /home/nvidia/anaconda3/envs/openvino/include -fPIC
-

**Comment by ilya-lavrenov** [comment]
Hi @moyu026 
We don't currently provide prebuilt OpenVINO wheel package for Linux aarch64 platform.
You can use archives where Python API is also available https://docs.openvino.ai/2023.0/openvino_docs_install_guides_installing_openvino_from_archive_linux.html#step-1-download-and-install-the-openvino-core-components

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Comment by ilya-lavrenov** [comment]
We have released OpenVINO 2023.1.0 and published wheel packages for arm64 Linux https://pypi.org/project/openvino/#files
Please, try:
```sh
python3 -m pip install openvino
```
