### ISSUE TITLE
[Bug]Openvino python cannot add extension with openvino_XXX_extension.dll built by openvino C++.

### ISSUE THREAD

**Issue by xiangru123** [openvinotoolkit/openvino#18834]
##### System information (version)
- OpenVINO Source => Runtime（C++） / pip install （python） 
- OpenVINO Version => Version 2023.0.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Cmake
- Problem classification: Model Conversion  
- Device use: CPU

##### Detailed description

- I register some custom operations in C++ by "ov::frontend::onnx::OpExtension" according to https://docs.openvino.ai/2023.0/openvino_docs_Extensibility_UG_add_openvino_ops.html and build it into openvino_XXX_extension.dll. 
- In python I use add_extension() fuction with this openvino_XXX_extension.dll, but failed. (While this openvino_XXX_extension.dll can be added in openvino C++ successfully with add_extension() function.)

Why?

Here are two methods of adding extension in python i tried failed.
![python_openvino1](https://github.com/openvinotoolkit/openvino/assets/92160521/9b4884d5-908b-4f1f-8053-3e2b1cbe9fed)
![python_openvino2](https://github.com/openvinotoolkit/openvino/assets/92160521/36b37c13-96a9-4898-975b-c05a6a1ddf70)

Is this problem related to such an xml file below on windows?
![image](https://github.com/openvinotoolkit/openvino/assets/92160521/130e5ad0-48d5-4941-9bf4-88c94dbb826c)

I don't know how to solve the problem. Maybe it is a bug. 
Thanks.

**Comment by ilya-lavrenov** [comment]
Hi @xiangru123 
Does adding with absolute path works?

**Comment by xiangru123** [comment]
> Hi @xiangru123 Does adding with absolute path works?

Absolute paths don't work either.

**Comment by xiangru123** [comment]
Hi @mlukasze 
Could you please help me to solve this problem?
Need I provide my dll to you?

**Comment by ilya-lavrenov** [comment]
> Absolute paths don't work either.

It's quite strange, because we have tests which work with relative paths as well..
Maybe in case of Python your extension library is not able to find some dependencies? E.g. because C++ and Python are running from different CDW

**Comment by xiangru123** [comment]
Hi @ilya-lavrenov @mlukasze 
I have put my extension library and its all dependencies such as mkl dlls and openvino dlls into the path python   
Here is my dll and cmakelists, could you please have a try to add it in python? 
[extension.zip](https://github.com/openvinotoolkit/openvino/files/12193352/extension.zip)
onemkl version is 2023.1.0.46356

**Comment by xiangru123** [comment]
> > Absolute paths don't work either.
> 
> It's quite strange, because we have tests which work with relative paths as well.. Maybe in case of Python your extension library is not able to find some dependencies? E.g. because C++ and Python are running from different CDW

Hi @ilya-lavrenov @mlukasze
I have put my extension library and its all dependencies such as mkl dlls and openvino dlls into the path python program uses.

Here is my dll and cmakelists, could you please have a try to add it in python?
[extension.zip](https://github.com/openvinotoolkit/openvino/files/12193352/extension.zip)
onemkl version is 2023.1.0.46356

**Comment by xiangru123** [comment]
> > Absolute paths don't work either.
> 
> It's quite strange, because we have tests which work with relative paths as well.. Maybe in case of Python your extension library is not able to find some dependencies? E.g. because C++ and Python are running from different CDW

I have put my extension library and its all dependencies such as mkl dlls and openvino dlls into the path python program uses.

Hi @ilya-lavrenov @mlukasze
Here is my dll and cmakelists, could you please have a try to add it in python?
[extension.zip](https://github.com/openvinotoolkit/openvino/files/12193352/extension.zip)
onemkl version is 2023.1.0.46356

**Comment by mlukasze** [comment]
We are looking at it, will back to you soon. Stay tuned.

**Comment by xiangru123** [comment]
> We are looking at it, will back to you soon. Stay tuned.

Hi @mlukasze 
Can you give me an approximate solution time? Thank you very much.

**Comment by akuporos** [comment]
Hi @xiangru123,

I'll back to you with something in ~two days.

**Comment by akuporos** [comment]
Hi @xiangru123,

Could you please build and check with openvino template extension ([link](https://github.com/openvinotoolkit/openvino/blob/master/src/core/template_extension/new/CMakeLists.txt))?
I just want to be sure that everything besides this custom extension is working as expected.

**Comment by Nerdmust** [comment]
Hi, @akuporos, I have the same issue, but only debug mode compiled libraries don't work, while release-compiled linked libraries do. What is the cause of this?

**Comment by Nerdmust** [comment]
> > Hi, @akuporos, I have the same issue, but only debug mode compiled libraries don't work, while release-compiled linked libraries do. What is the cause of this?
> 
> Does your extension library named the same for Release and Debug? Or output paths are different?

yes, release and debug dll have same name
