### ISSUE TITLE
the test results on the CPU and GPU are very different. Why?

### ISSUE THREAD

**Issue by bjyzhsetqe** [openvinotoolkit/openvino#18841]
We've been testing the multi-camera multi-target tracking code, and we have a problem. The same model has the same input profile, but the test results on the CPU and GPU are very different. CPU results are good but GPU detection results are poor

python .\multi_camera_multi_target_tracking_demo.py -i gwh1.avi gwh2.avi --m_segmentation .\intel\instance-segmentation-security-0228\FP32\instance-segmentation-security-0228.xml --m_reid .\public\vehicle-reid-0001\FP16\vehicle-reid-0001.xml --config .\configs\vehicle.py --device GPU

python .\multi_camera_multi_target_tracking_demo.py -i gwh1.avi gwh2.avi --m_segmentation .\intel\instance-segmentation-security-0228\FP32\instance-segmentation-security-0228.xml --m_reid .\public\vehicle-reid-0001\FP16\vehicle-reid-0001.xml --config .\configs\vehicle.py --device CPU

how to solve this problem??

![image](https://user-images.githubusercontent.com/126636458/225216353-9a74ec12-941c-4d21-935e-7eb7dfea0fe5.png)

![image](https://user-images.githubusercontent.com/126636458/225216264-96b9de5d-f3be-4e36-a6e4-b22e5d6ea849.png)
![image](https://user-images.githubusercontent.com/126636458/225216392-322caf57-dec2-4bf8-855f-bb6539115bdc.png)

**Comment by jade-cho** [comment]
@bjyzhsetqe Could you provide sample videos? (gwh1.avi gwh2.avi)
