### ISSUE TITLE
[Feature Request] Support specifying output port of placeholders as inputs

### ISSUE THREAD

**Issue by EFanZh** [openvinotoolkit/openvino#1889]
##### System information (version)

- OpenVINO=> 2020.4
- Operating System / Platform => Linux 64 Bit
- Compiler => GCC 10
- Problem classification => Model Conversion
- Framework: TensorFlow

##### Detailed description

Currently, I can specify a placeholder operation as input, but not the output of that placeholder.

##### Steps to reproduce

Run this Python script:

```python
import subprocess
import sys
from os import path
from tempfile import TemporaryDirectory

import tensorflow as tf
from tensorflow import keras

_MO_TF = '/opt/intel/openvino/deployment_tools/model_optimizer/mo_tf.py'


def main():
    with tf.compat.v1.Session(graph=tf.Graph()) as session:
        model = keras.Sequential([keras.layers.Conv2D(filters=4,
                                                      kernel_size=3,
                                                      data_format='channels_first',
                                                      batch_input_shape=(4, 3, 10, 10)),
                                  keras.layers.Flatten(),
                                  keras.layers.Dense(units=4)])

        session.run([v.initializer for v in model.weights])

        frozen_graph = tf.compat.v1.graph_util.convert_variables_to_constants(sess=session,
                                                                              input_graph_def=session.graph_def,
                                                                              output_node_names=[model.output.op.name])

    with TemporaryDirectory() as workspace:
        frozen_graph_file = path.join(workspace, 'frozen-graph.pb')
        target_dir = path.join(workspace, 'target')

        with open(frozen_graph_file, 'wb') as file:
            file.write(frozen_graph.SerializeToString())

        subprocess.run(args=[sys.executable,
                             _MO_TF,
                             f'--input_model={frozen_graph_file}',
                             '--model_name=model',
                             f'--output_dir={target_dir}',
                             f'--input={model.input.name}',
                             f'--output={model.output.op.name}',
                             '--disable_nhwc_to_nchw'],
                       check=True)


if __name__ == "__main__":
    main()
```

Currently, this script reports the following error:

```
Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.input_cut.InputCut'>): Parameter node "conv2d_input" doesn't have input port, but input port 0 was provided.
```

Unless I change `f'--input={model.input.name}'` to `f'--input={model.input.op.name}'`. I wish that this script will run successfully without modification in the future.

**Comment by andrei-kochin** [comment]
@EFanZh greetings from 2023!

Just wanted to recap the request. Are you searching the way to cut off the beginning of the model or just specify input shapes?
This request require new API and was not planned for a long time. Please consider using your model with the latest OpenVINO Out-of-Box by using [convert_model API](https://docs.openvino.ai/latest/openvino_docs_MO_DG_Python_API.html) and provide feedback if this feature is still relevant for you.

Thank you for you patience.
Looking forward for you reply.

**Comment by EFanZh** [comment]
@andrei-kochin: Thank you, but this feature is now irrelevant for me.

**Comment by andrei-kochin** [comment]
@EFanZh have you managed to workaround this on our side and keep using OpenVINO as is?

**Comment by EFanZh** [comment]
Unfortunately, I currently do not use OpenVINO anymore, so it’s API design does not matter much to me now.

**Comment by andrei-kochin** [comment]
@EFanZh sad news...

Feel free to come back and try what changed after almost 3 years =)
Good luck in your projects!
