### ISSUE TITLE
Compute Runtime for OpenCL™ - Prerelease Version

### ISSUE THREAD

**Issue by ohlr** [openvinotoolkit/openvino#189]
[Here](https://github.com/opencv/dldt/blob/2019/inference-engine/README.md) you link a pre-release version of the compute runtime.

Is it possible to switch to an earlier or later release?

**Comment by asuhov** [comment]
Earlier or later releases of Intel Compute Runtime for OpenCL should be functionally compatible with dldt, but we validated dldt only with release mentioned in the readme file.
