### ISSUE TITLE
How to get the id of threads created in openvino?

### ISSUE THREAD

**Issue by Jsy0220** [openvinotoolkit/openvino#18940]
hi,
I have a special need to get the id of threads created in openvino, so I want to know that is there any interface or method ?

**Comment by wangleis** [comment]
@Jsy0220 OpenVINO does not support application getting the IDs of threads created in OpenVINO.

**Comment by Jsy0220** [comment]
okay, thank you

**Comment by wangleis** [comment]
Closing this. Feel free to reopen and ask additional questions related to this topic.
