### ISSUE TITLE
[Feature Request]: create a github action who can assign automate an issue

### ISSUE THREAD

**Issue by NsdHSO** [openvinotoolkit/openvino#19006]
### Request Description

I want to create a github action who will be triggered form '.want' ? 
Open to discuss for the command 

### Feature Use Case

I saw many people ask in the issue, can I work on this issue or can you assign me this issue ?? IMHO for the maintainer is so frustrating because the maintainer doesn't care who works on an issue, he wants only to resolve their bug/feature, etc. If you consider this good for this project I can create this action.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by p-wysocki** [comment]
Hi! 

Thanks for the idea, I want to make sure I understand your proposal - would it be a GitHub action which assigns a person to an issue when the user writes a specific command in a comment?

**Comment by NsdHSO** [comment]
@p-wysocki Hi, yes.

**Comment by p-wysocki** [comment]
I think it's a good idea. Are you able to contribute it?

Do you have an opinion on that @mlukasze?

**Comment by NsdHSO** [comment]
Yes, I can. This feature has some constraints, we must have GH_TOKEN in `secrets`

**Comment by mlukasze** [comment]
> Do you have an opinion on that @mlukasze?

LGMT

@dorloff may want to express his opinion as well

**Comment by p-wysocki** [comment]
The PR has been merged. Thank you for your contribution @NsdHSO!

**Comment by p-wysocki** [comment]
I tested the new functionality, everything works! I also updated the instructions for new contributors to use `.take`, thank you for the idea. :)

**Comment by NsdHSO** [comment]
🙏 Big thanks to @p-wysocki  @mlukasze , and @akashchi  for your invaluable support and collaboration throughout this journey. 🚀

I'm truly grateful for your guidance and assistance, and I'm delighted to have been able to contribute in a meaningful way. Your coaching and teamwork have made all the difference! 🌟
