### ISSUE TITLE
[url missing]

### ISSUE THREAD

**Issue by x1aoo** [openvinotoolkit/openvino#1900]
Hi,

In the document of [benchmark](https://github.com/openvinotoolkit/openvino/tree/master/tools/benchmark), the URL of [Introduction to Performance Topics](https://github.com/openvinotoolkit/openvino/blob/master/tools/benchmark/docs/IE_DG/Intro_to_Performance.md) in section Running is missing.

**Comment by ilya-lavrenov** [comment]
@x1aoo could you please provide a patch with such fix?

**Comment by jgespino** [comment]
Hi @x1aoo 

You can find the Introduction to Performance Topics at the following link:
https://github.com/openvinotoolkit/openvino/blob/master/docs/IE_DG/Intro_to_Performance.md

As @ilya-lavrenov mentioned, could you try to submit a patch? See [Contribute to Documentation](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING_DOCS.md#edit-existing-document) guide.

Regards,
Jesus

**Comment by x1aoo** [comment]
Hi,

Thanks for the guide and links @jgespino. And I already submit the patch @ilya-lavrenov 

Regards,
Xiao
