### ISSUE TITLE
Invalid logic in CLDNNGraph::IsValidSplitConvMerge

### ISSUE THREAD

**Issue by kostinalexey** [openvinotoolkit/openvino#192]
In my understanding the function supposed to return true or false, but instead it throws exception "CNNLayerPtr is not suitable for casting to requested layer type" when "outputs aren't convolutions".

This happening because as<>() function will throw exception on failure, not return nullptr. As result following lines 

```
    auto convLayer1 =
        as<InferenceEngine::ConvolutionLayer *> (GetNextSingleLayer(splitLayer->outData[0]));
    auto convLayer2 =
        as<InferenceEngine::ConvolutionLayer *> (GetNextSingleLayer(splitLayer->outData[1]));
    if (!convLayer1 || !convLayer2) {   // outputs aren't convolutions
        return false;
    }
```
will throw exception instead of check.

This bug manifests itself on certain model structures when loaded with clDNNPlugin. MKLDNNPlugin works ok.

**Comment by kostinalexey** [comment]
wrapping whole body of the CLDNNGraph::IsValidSplitConvMerge function in
```
try {
...
} cathc(...) {
  return false;
}
```
allows model to load. However later I got another error
```
Initialisation error:/home/jenkins/Projects/openVINO/opneVINO/inference-engine/thirdparty/clDNN/src/crop.cpp at line: 116
Error has occured for: Slice:slice1.0
Reference input sizes: [b:4, f:48, x:128, y:128]
input sizes sizes: [b:2, f:96, x:128, y:128]
All Reference input di
```

Look like this is just tip of the iceberg

**Comment by kostinalexey** [comment]
The crop.cpp error looks to be related to batch size. May be my CNN is too big. With batch 1 and try/catch wrap all loaded ok and result of CNN processing is correct.

**Comment by kostinalexey** [comment]
It looks as there are other instances of as<> function been used (for example in CLDNNGraph::CreateFusedSplitConvMergePrimitive) for testing types with expectation that it will return nullptr. Wouldn't it be easier to check value if CNNLayer::type?

**Comment by vladimir-paramuzov** [comment]
I believe the issue was fixed. @kostinalexey Feel free to reopen if you still have any concerns
