### ISSUE TITLE
openvino platform

### ISSUE THREAD

**Issue by foxnight2** [openvinotoolkit/openvino#19378]
Can the openvino run on the GTX 1060 (nvidia)?

what is the platform with openvino?

**Comment by vurusovs** [comment]
@foxnight2 hello!

You may find all officially supported hardware here https://github.com/openvinotoolkit/openvino#supported-hardware-matrix

However, you may try NVidia plugin from `openvino_contrib` https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/nvidia_plugin
