### ISSUE TITLE
Debug Assertion Failed when loading the plugin

### ISSUE THREAD

**Issue by fatalfeel** [openvinotoolkit/openvino#194]
https://software.intel.com/en-us/forums/computer-vision/topic/808636#comment-1941333

/////////////////////////////////////////modify as this
InferenceEnginePluginPtr getSuitablePlugin(TargetDevice device) const
    {
        FindPluginResponse result;
        ResponseDesc desc;
        FindPluginRequest req;
        req.device = device;
        if (InferenceEngine::OK != findPlugin(req, result, &desc))
        {
            THROW_IE_EXCEPTION << desc.msg;
        }

        /*std::stringstream err;
        for (std::string& name : result.names)
        {
            try
            {
                return getPluginByName(stringToFileName(name));
            }
            catch (const std::exception &ex)
            {
                err << "Tried load plugin : " << name << ",  error: " << ex.what() << "\n";
            }
        }
        THROW_IE_EXCEPTION << "Cannot find plugin to use :" << err.str() << "\n";*/

        //by stone
        std::stringstream    err;
        std::string            name;
        switch(device)
        {
            case TargetDevice::eCPU:
                name = "MKLDNNPlugin";
                break;
            case TargetDevice::eGPU:
                name = "clDNNPlugin";
                break;
            case TargetDevice::eMYRIAD:
                name = "myriadPlugin";
                break;
            default:
                name = "MKLDNNPlugin";
                break;
        }

#if defined(_DEBUG)
        name += "d";
#endif
        try
        {
            return getPluginByName(stringToFileName(name));
        }
        catch (const std::exception &ex)
        {
            err << "Tried load plugin : " << name << ",  error: " << ex.what() << "\n";
        }
    }

////////////////////////////////////////////inference_engined.dll source c++
https://github.com/opencv/dldt/blob/2019/inference-engine/src/inference_engine/ie_device.cpp

////////////////////////////////////inference_engine.dll  release version asm
.text:00000001800E3A00 ; __unwind { // __CxxFrameHandler3
.text:00000001800E3A00                 push    rbp
.text:00000001800E3A01                 sub     rsp, 0F0h
.text:00000001800E3A08                 lea     rbp, [rsp+20h]
.text:00000001800E3A0D                 mov     [rbp+0D0h+var_10], rbx
.text:00000001800E3A14                 mov     rbx, rdx
.text:00000001800E3A17                 mov     [rbp+0D0h+arg_10], r8
.text:00000001800E3A1E                 mov     rdx, rcx
.text:00000001800E3A21                 mov     [rbp+0D0h+var_18], 0FFFFFFFFFFFFFFFEh
.text:00000001800E3A2C
.text:00000001800E3A2C loc_1800E3A2C:                          ; DATA XREF: .rdata:00000001805D069C↓o
.text:00000001800E3A2C ;   try {
.text:00000001800E3A2C                 lea     rcx, [rbp+0D0h+var_30]
.text:00000001800E3A33                 call    sub_1800E3D10
.text:00000001800E3A38                 lea     rax, [rbp+0D0h+var_30]
.text:00000001800E3A3F                 cmp     rbx, rax
.text:00000001800E3A42                 jnz     loc_1800E3B00
.text:00000001800E3A48                 mov     rbx, [rbp+0D0h+var_30]
.text:00000001800E3A4F                 test    rbx, rbx
.text:00000001800E3A52                 jz      loc_1800E3BCE
.text:00000001800E3A58                 mov     rax, [rbp+0D0h+var_28]
.text:00000001800E3A5F                 cmp     rbx, rax
.text:00000001800E3A62                 jz      short loc_1800E3AA6
.text:00000001800E3A62 ;   } // starts at 1800E3A2C
.text:00000001800E3A62 ; } // starts at 1800E3A00

////////////////////////////////////inference_engined.dll  debug version asm
.text:00000001805D3E66 ; __unwind { // __CxxFrameHandler3
.text:00000001805D3E66                 push    rbp
.text:00000001805D3E67                 sub     rsp, 150h
.text:00000001805D3E6E                 lea     rbp, [rsp+20h]
.text:00000001805D3E73                 mov     [rsp+150h+var_150], rax
.text:00000001805D3E77                 mov     rax, 14Ch
.text:00000001805D3E7E
.text:00000001805D3E7E loc_1805D3E7E:                          ; CODE XREF: findPlugin_0+27↓j
.text:00000001805D3E7E                 mov     dword ptr [rsp+rax+150h+var_150], 0CCCCCCCCh
.text:00000001805D3E85                 sub     rax, 4
.text:00000001805D3E89                 cmp     rax, 4
.text:00000001805D3E8D                 jg      short loc_1805D3E7E
.text:00000001805D3E8F                 mov     rax, [rsp+150h+var_150]
.text:00000001805D3E93                 mov     dword ptr [rsp+150h+var_150], 0CCCCCCCCh
.text:00000001805D3E9A                 mov     dword ptr [rsp+150h+var_150+4], 0CCCCCCCCh
.text:00000001805D3EA2                 mov     [rbp+130h+arg_0], rcx
.text:00000001805D3EA9                 mov     [rbp+130h+arg_8], rdx
.text:00000001805D3EB0                 mov     [rbp+130h+arg_10], r8
.text:00000001805D3EB7                 mov     [rbp+130h+var_100], 0FFFFFFFFFFFFFFFEh
.text:00000001805D3EBF
.text:00000001805D3EBF loc_1805D3EBF:                          ; DATA XREF: .rdata:00000001812250C4↓o
.text:00000001805D3EBF ;   try {
.text:00000001805D3EBF                 lea     rax, [rbp+130h+var_F8]
.text:00000001805D3EC3                 mov     rdx, [rbp+130h+arg_0]
.text:00000001805D3ECA                 mov     rcx, rax
.text:00000001805D3ECD                 call    sub_18001B4FA
.text:00000001805D3ED2                 jmp     short loc_1805D3F01
.text:00000001805D3ED4 ; ---------------------------------------------------------------------------
.text:00000001805D3ED4
.text:00000001805D3ED4 loc_1805D3ED4:                          ; CODE XREF: findPlugin_0+9F↓j
.text:00000001805D3ED4                 mov     rax, [rbp+130h+var_D8]
.text:00000001805D3ED8                 mov     [rbp+130h+var_D0], rax
.text:00000001805D3EDC                 mov     rax, [rbp+130h+arg_8]
.text:00000001805D3EE3                 lea     rdx, [rbp+130h+var_F8]
.text:00000001805D3EE7                 mov     rcx, rax
.text:00000001805D3EEA                 call    sub_180009C6E
.text:00000001805D3EEF                 mov     [rbp+130h+var_C8], rax
.text:00000001805D3EF3                 lea     rax, [rbp+130h+var_F8]
.text:00000001805D3EF7                 mov     rcx, rax
.text:00000001805D3EFA                 call    sub_18000EBB5                //---------------------->crash here
.text:00000001805D3EFF                 jmp     short loc_1805D3F2B
.text:00000001805D3F01 ; ---------------------------------------------------------------------------
.text:00000001805D3F01
.text:00000001805D3F01 loc_1805D3F01:                          ; CODE XREF: findPlugin_0+6C↑j
.text:00000001805D3F01                 mov     [rbp+130h+var_D8], rax
.text:00000001805D3F05                 jmp     short loc_1805D3ED4
.text:00000001805D3F05 ;   } // starts at 1805D3EBF
.text:00000001805D3F07 ; ---------------------------------------------------------------------------
.text:00000001805D3F07
.text:00000001805D3F07 loc_1805D3F07:                          ; CODE XREF: findPlugin_0+270↓j
.text:00000001805D3F07                                         ; DATA XREF: findPlugin_0+261↓o ...
.text:00000001805D3F07                 mov     eax, [rbp+130h+var_10C]
.text:00000001805D3F0A                 mov     [rbp+130h+var_108], eax
.text:00000001805D3F0D                 lea     rax, unk_181084F48
.text:00000001805D3F14                 mov     rdx, rax
.text:00000001805D3F17                 mov     rcx, rbp
.text:00000001805D3F1A                 call    sub_180035D46
.text:00000001805D3F1F                 mov     eax, [rbp+130h+var_108]
.text:00000001805D3F22                 lea     rsp, [rbp+130h]
.text:00000001805D3F29                 pop     rbp
.text:00000001805D3F2A                 retn
.text:00000001805D3F2B ; ---------------------------------------------------------------------------
.text:00000001805D3F2B
.text:00000001805D3F2B loc_1805D3F2B:                          ; CODE XREF: findPlugin_0+99↑j
.text:00000001805D3F2B                 mov     eax, 0
.text:00000001805D3F30                 mov     [rbp+130h+var_104], eax
.text:00000001805D3F33                 lea     rax, unk_181084F48
.text:00000001805D3F3A                 mov     rdx, rax
.text:00000001805D3F3D                 mov     rcx, rbp
.text:00000001805D3F40                 call    sub_180035D46
.text:00000001805D3F45                 mov     eax, [rbp+130h+var_104]
.text:00000001805D3F48                 lea     rsp, [rbp+130h]
.text:00000001805D3F4F                 pop     rbp
.text:00000001805D3F50                 retn
.text:00000001805D3F50 ; } // starts at 1805D3E66
.text:00000001805D3F51 ; ---------------------------------------------------------------------------
.text:00000001805D3F51
.text:00000001805D3F51 loc_1805D3F51:                          ; DATA XREF: .rdata:0000000181084FB8↓o
.text:00000001805D3F51                                         ; .pdata:0000000181439244↓o ...
.text:00000001805D3F51 ;   cleanup() // owned by 1805D4024
.text:00000001805D3F51                 push    rbp
.text:00000001805D3F52                 sub     rsp, 150h
.text:00000001805D3F59                 lea     rbp, [rdx+20h]
.text:00000001805D3F5D                 mov     [rsp+0], rax
.text:00000001805D3F61                 mov     rax, 14Ch
.text:00000001805D3F68
.text:00000001805D3F68 loc_1805D3F68:                          ; CODE XREF: findPlugin_0+111↓j
.text:00000001805D3F68                 mov     dword ptr [rsp+rax+0], 0CCCCCCCCh
.text:00000001805D3F6F                 sub     rax, 4
.text:00000001805D3F73                 cmp     rax, 4
.text:00000001805D3F77                 jg      short loc_1805D3F68
.text:00000001805D3F79                 mov     rax, [rsp+0]
.text:00000001805D3F7D                 mov     dword ptr [rsp+0], 0CCCCCCCCh
.text:00000001805D3F84                 mov     dword ptr [rsp+4], 0CCCCCCCCh
.text:00000001805D3F8C                 mov     [rsp+2A8h+var_148], rcx
.text:00000001805D3F94                 mov     [rsp+2A8h+var_140], rdx
.text:00000001805D3F9C                 lea     rax, [rbp+130h+var_C0]
.text:00000001805D3FA0                 mov     rcx, rax
.text:00000001805D3FA3                 call    sub_18001D5CA
.text:00000001805D3FA8                 add     rsp, 150h
.text:00000001805D3FAF                 pop     rbp
.text:00000001805D3FB0                 retn

**Comment by shubha-ramani** [comment]
Dear @fatalfeel 

Please set your PATH variable to point to the directory which contains your debug plugins. It's here in DLDT (Windows version):

C:\Intel\dldt\inference-engine\bin\intel64\Debug

Your IDE (if Visual Studio) needs to be aware of this path. That IDZ link you posted is a Visual Studio issue.

Sometimes you may need to run [dependency walker](http://www.dependencywalker.com/) on Windows 10 or [binscan](https://sourceforge.net/projects/binscan/) or [ldd](http://man7.org/linux/man-pages/man1/ldd.1.html) to detect missing dependencies.

Thanks and I hope it helps,

Shubha

**Comment by fatalfeel** [comment]
I modify this and build in vs2015
debug and release all ok~~~
http://www.mediafire.com/file/2m1ungbb86rgi46/OpenVINO_2019.1.148.rar/file

**Comment by shubha-ramani** [comment]
@fatalfeel 
Great news. But you shouldn't have had to use vs2015. It also works in vs2017.
Thanks,

Shubha

**Comment by pengguanjun** [comment]
By follow up **@fatalfeel** these steps,I also meet some error:
C4996: 'InferenceEngine::PluginDispatcher::getSuitablePlugin': is declared as deprecated
**@shubha-ramani** I also prepared the path.
D:\Program Files (x86)\IntelSWTools\openvino_2019.3.334\opencv\bin

The position is selected to put the modified codes.
D:\Program Files (x86)\IntelSWTools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin_dispatcher.hpp
![图片](https://user-images.githubusercontent.com/29192658/68531243-6038ff00-034b-11ea-9e07-32b3ee14b9b0.png)

Next,how could I do?

**Comment by alalek** [comment]
> C4996

It is warning, not error.
Try to disable forcing warnings as errors through `-WX` option (for some strange reason is still may be enabled).

BTW, to get details, avoid using of MSVS errors view - use compiler output directly.

**Comment by pengguanjun** [comment]
**@alalek** Thank you.
The compiler output  show some similiar error:
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin_dispatcher.hpp(55): error C4996: 'InferenceEngine::FindPluginResponse::~FindPluginResponse': is declared as deprecated

For -WX option ,I consider this link.
https://docs.microsoft.com/en-us/previous-versions/ms235592%28v%3dvs.140%29
I have a try,but I have the same error.
![图片](https://user-images.githubusercontent.com/29192658/68531873-fc660480-0351-11ea-94b6-4b0b6d65e954.png)
How to use it in VS Tool?
A Picture like up, I appreciate it very much.

**Comment by pengguanjun** [comment]
`1>------ 已启动生成: 项目: GOVINO, 配置: Debug x64 ------
1>6GOVINO-异步机制.cpp
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layouts.h(127): warning C4251: “InferenceEngine::BlockingDesc::blockedDims”: class“std::vector<size_t,std::allocator<_Ty>>”需要有 dll 接口由 class“InferenceEngine::BlockingDesc”的客户端使用
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_common.h(26): note: 参见“std::vector<size_t,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layouts.h(129): warning C4251: “InferenceEngine::BlockingDesc::strides”: class“std::vector<size_t,std::allocator<_Ty>>”需要有 dll 接口由 class“InferenceEngine::BlockingDesc”的客户端使用
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_common.h(26): note: 参见“std::vector<size_t,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layouts.h(131): warning C4251: “InferenceEngine::BlockingDesc::order”: class“std::vector<size_t,std::allocator<_Ty>>”需要有 dll 接口由 class“InferenceEngine::BlockingDesc”的客户端使用
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_common.h(26): note: 参见“std::vector<size_t,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layouts.h(134): warning C4251: “InferenceEngine::BlockingDesc::offsetPaddingToData”: class“std::vector<size_t,std::allocator<_Ty>>”需要有 dll 接口由 class“InferenceEngine::BlockingDesc”的客户端使用
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_common.h(26): note: 参见“std::vector<size_t,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layouts.h(321): warning C4251: “InferenceEngine::TensorDesc::dims”: class“std::vector<size_t,std::allocator<_Ty>>”需要有 dll 接口由 class“InferenceEngine::TensorDesc”的客户端使用
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_common.h(26): note: 参见“std::vector<size_t,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layouts.h(325): warning C4251: “InferenceEngine::TensorDesc::precision”: class“InferenceEngine::Precision”需要有 dll 接口由 class“InferenceEngine::TensorDesc”的客户端使用
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_precision.hpp(19): note: 参见“InferenceEngine::Precision”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layouts.h(363): warning C4251: “InferenceEngine::LayoutOffsetCounter::_dims”: class“std::vector<size_t,std::allocator<_Ty>>”需要有 dll 接口由 class“InferenceEngine::LayoutOffsetCounter”的客户端使用
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_common.h(26): note: 参见“std::vector<size_t,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layouts.h(371): warning C4251: “InferenceEngine::LayoutOffsetCounter::_muls”: class“std::vector<size_t,std::allocator<_Ty>>”需要有 dll 接口由 class“InferenceEngine::LayoutOffsetCounter”的客户端使用
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_common.h(26): note: 参见“std::vector<size_t,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_data.h(34): warning C4251: “InferenceEngine::Data::precision”: class“InferenceEngine::Precision”需要有 dll 接口由 class“InferenceEngine::Data”的客户端使用
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_precision.hpp(19): note: 参见“InferenceEngine::Precision”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_data.h(46): warning C4251: “InferenceEngine::Data::dims”: class“std::vector<size_t,std::allocator<_Ty>>”需要有 dll 接口由 class“InferenceEngine::Data”的客户端使用
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_common.h(26): note: 参见“std::vector<size_t,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Ty=size_t
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_data.h(52): warning C4251: “InferenceEngine::Data::creatorLayer”: class“std::weak_ptr<InferenceEngine::CNNLayer>”需要有 dll 接口由 class“InferenceEngine::Data”的客户端使用
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_common.h(40): note: 参见“std::weak_ptr<InferenceEngine::CNNLayer>”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_data.h(58): warning C4251: “InferenceEngine::Data::name”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 class“InferenceEngine::Data”的客户端使用
1>d:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_data.h(65): warning C4251: “InferenceEngine::Data::inputTo”: class“std::map<std::string,InferenceEngine::CNNLayerPtr,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>”需要有 dll 接口由 class“InferenceEngine::Data”的客户端使用
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=InferenceEngine::CNNLayerPtr
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_data.h(65): note: 参见“std::map<std::string,InferenceEngine::CNNLayerPtr,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>”的声明
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=InferenceEngine::CNNLayerPtr
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layers.h(933): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin.hpp(56): warning C4251: “InferenceEngine::QueryNetworkResult::supportedLayers”: class“std::set<std::string,std::less<_Kty>,std::allocator<_Ty>>”需要有 dll 接口由 struct“InferenceEngine::QueryNetworkResult”的客户端使用
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::string
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin.hpp(56): note: 参见“std::set<std::string,std::less<_Kty>,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::string
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin.hpp(63): warning C4251: “InferenceEngine::QueryNetworkResult::supportedLayersMap”: class“std::map<std::string,std::string,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>”需要有 dll 接口由 struct“InferenceEngine::QueryNetworkResult”的客户端使用
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::string
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_layers.h(517): note: 参见“std::map<std::string,std::string,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>”的声明
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::string
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_ihetero_plugin.hpp(126): warning C4275: 非 dll 接口 class“InferenceEngine::IInferencePlugin”用作 dll 接口 class“InferenceEngine::IHeteroInferencePlugin”的基
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin.hpp(109): note: 参见“InferenceEngine::IInferencePlugin”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_ihetero_plugin.hpp(126): note: 参见“InferenceEngine::IHeteroInferencePlugin”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin_dispatcher.hpp(119): warning C4251: “InferenceEngine::PluginDispatcher::pluginDirs”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 class“InferenceEngine::PluginDispatcher”的客户端使用
1>        with
1>        [
1>            _Ty=std::string
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_device.hpp(145): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
1>        with
1>        [
1>            _Ty=std::string
1>        ]
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin_dispatcher.hpp(55): error C4996: 'InferenceEngine::FindPluginResponse': 被声明为已否决
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_device.hpp(141): note: 参见“InferenceEngine::FindPluginResponse”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin_dispatcher.hpp(57): error C4996: 'InferenceEngine::FindPluginRequest': 被声明为已否决
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_device.hpp(129): note: 参见“InferenceEngine::FindPluginRequest”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin_dispatcher.hpp(58): error C4996: 'InferenceEngine::FindPluginRequest::device': 被声明为已否决
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_device.hpp(133): note: 参见“InferenceEngine::FindPluginRequest::device”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin_dispatcher.hpp(55): error C4996: 'InferenceEngine::FindPluginResponse::~FindPluginResponse': 被声明为已否决
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_device.hpp(146): note: 编译器已在此处生成“InferenceEngine::FindPluginResponse::~FindPluginResponse”
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_core.hpp(27): warning C4251: “InferenceEngine::Core::_impl”: class“std::shared_ptr<InferenceEngine::Core::Impl>”需要有 dll 接口由 class“InferenceEngine::Core”的客户端使用
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_core.hpp(27): note: 参见“std::shared_ptr<InferenceEngine::Core::Impl>”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\inference_engine\src\extension\ext_list.hpp(25): warning C4275: 非 dll 接口 class“InferenceEngine::IExtension”用作 dll 接口 class“InferenceEngine::Extensions::Cpu::CpuExtensions”的基
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_iextension.h(237): note: 参见“InferenceEngine::IExtension”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\inference_engine\src\extension\ext_list.hpp(25): note: 参见“InferenceEngine::Extensions::Cpu::CpuExtensions”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\demos\common\samples\common.hpp(451): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\demos\common\samples\common.hpp(452): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\demos\common\samples\common.hpp(454): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\demos\common\samples\common.hpp(455): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\demos\common\samples\common.hpp(923): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>g:\机器视觉\禾路资料\端到端\l9\6govino-异步机制.cpp(210): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
1>g:\机器视觉\禾路资料\端到端\l9\6govino-异步机制.cpp(211): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据
1>g:\机器视觉\禾路资料\端到端\l9\6govino-异步机制.cpp(275): warning C4326: “main”的返回类型应为“int”而非“void”
1>g:\机器视觉\禾路资料\端到端\l9\6govino-异步机制.cpp(284): error C4996: 'InferenceEngine::PluginDispatcher::getSuitablePlugin': 被声明为已否决
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\include\ie_plugin_dispatcher.hpp(53): note: 参见“InferenceEngine::PluginDispatcher::getSuitablePlugin”的声明
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\demos\common\samples\ocv_common.hpp(32): warning C4267: “参数”: 从“size_t”转换到“_Tp”，可能丢失数据
1>        with
1>        [
1>            _Tp=int
1>        ]
1>g:\机器视觉\禾路资料\端到端\l9\6govino-异步机制.cpp(67): note: 参见对正在编译的函数 模板 实例化“void matU8ToBlob<uint8_t>(const cv::Mat &,InferenceEngine::Blob::Ptr &,int)”的引用
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\demos\common\samples\ocv_common.hpp(35): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\demos\common\samples\ocv_common.hpp(40): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
1>d:\program files (x86)\intelswtools\openvino_2019.3.334\deployment_tools\inference_engine\demos\common\samples\ocv_common.hpp(48): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
1>已完成生成项目“GOVINO.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========`

**Comment by alalek** [comment]
Fix **compiler** command line first (you are fixing **linker** command-line)

**Comment by pengguanjun** [comment]
Today,I have attempt three methods to fix the plugin problem,but those were all false results.
1>g:\机器视觉\禾路资料\端到端\l9\6govino-异步机制.cpp(283): error C4996: 'InferenceEngine::PluginDispatcher::getSuitablePlugin': was declared rejected

(1) I also attempt to fix compiler command line.Using -wx or wx[:NO] ,but it was useless.

(2) I wiped out the blank and Chinese chapter in these dependencies below,but it was useless.

D:\IntelSWTools\openvino_2019.3.334\deployment_tools\inference_engine\demos\intel64\Debug\format_reader.lib
D:\IntelSWTools\openvino_2019.3.334\deployment_tools\inference_engine\demos\intel64\Debug\gflags_nothreads_static.lib
D:\IntelSWTools\openvino_2019.3.334\deployment_tools\inference_engine\demos\intel64\Debug\inference_engined.lib
D:\IntelSWTools\openvino_2019.3.334\opencv\lib\opencv_world412d.lib
D:\IntelSWTools\openvino_2019.3.334\deployment_tools\inference_engine\demos\intel64\Debug\cpu_extension.lib
D:\IntelSWTools\openvino_2019.3.334\deployment_tools\inference_engine\demos\intel64\Debug\tbb_debug.lib
shlwapi.lib

(3) Considering model format,I changed the FP32 to int8.It was useless.
https://software.intel.com/en-us/comment/1947738
-i f:/OpenVINO_modelZoo/JinCX8888.jpg -m  f:/OpenVINO_modelZoo/vehicle-license-plate-detection-barrier-0106/INT8/vehicle-license-plate-detection-barrier-0106.xml -m_va f:/OpenVINO_modelZoo/vehicle-attributes-recognition-barrier-0039/INT8/vehicle-attributes-recognition-barrier-0039.xml -m_lpr f:/OpenVINO_modelZoo/license-plate-recognition-barrier-0001/INT8/license-plate-recognition-barrier-0001.xml

**Comment by pengguanjun** [comment]
error C4996: 'InferenceEngine::PluginDispatcher::getSuitablePlugin': was declared rejected
For this problem,I add this code to solve it.
**#pragma warning(disable : 4996)**
Considering this link:
https://docs.microsoft.com/zh-cn/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(C4996)%26rd%3Dtrue&view=vs-2019
