### ISSUE TITLE
Cannot read model format : XML

### ISSUE THREAD

**Issue by devipramita** [openvinotoolkit/openvino#1941]
Hi,

I have Openvino 2020.4.287 in my Ubuntu 18.04. When I'm running my code using openvino, i got this error 

`RuntimeError:` Unknown model format! Cannot find reader for model format: xml and read the model: ./<DIR>/model.xml. Please check that reader library exists in your PATH.

Anyone can help? Thank you

**Comment by brmarkus** [comment]
Looks like your model was created/converted by an older OpenVINO version, or downloaded from open-model-zoo some time ago using a "download.py" of an older OpenVINO version: IR7 versus IR10 ?

Is this your own model, or can you download/convert it again using OpenVINO 2020.4?

**Comment by jgespino** [comment]
Closing issue, feel free to re-open if additional assistance is needed.
