### ISSUE TITLE
[Feature Request]: Add SeLu activation in the OpenVino IR (TensorFlow Conversion)

### ISSUE THREAD

**Issue by VimalWill** [openvinotoolkit/openvino#19469]
### Request Description

I  quantized my TensorFlow model to INT-8 using NNCF and trying to convert to OpenVino IR for performance analysis , but I was struck with the error as I'm using SeLu activation in my model. Ig OpenVino IR don't have support for SeLu? 

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by VimalWill** [comment]
Hi @vurusovs 
This is the issue and my version is (2023.0.1-11005-fa1c41994f3-releases/2023/0)
OpConversionFailure: Check 'is_conversion_successful' failed at src/frontends/tensorflow/src/frontend.cpp:264:
FrontEnd API failed with OpConversionFailure: :
[TensorFlow Frontend] Internal error, no translator found for operation(s): Selu

**Comment by VimalWill** [comment]
ov_model = mo.convert_model(tf_model)
ov_quantized_model = mo.convert_model(tf_quantized_model)

I followed this code from doc of nncf

**Comment by rkazants** [comment]
https://github.com/openvinotoolkit/openvino/pull/19528 with Selu support is under review.

**Comment by rkazants** [comment]
@VimalWill, PR was merged to master. If you have a chance, please build the master. And the operation is going to the next release 2023.2

Best regards,
Roman

**Comment by VimalWill** [comment]
@rkazants  thanks, let me try building it

**Comment by VimalWill** [comment]
can any one suggest me the steps to build from master, I'm still getting the issue and ig i'm not building it properly. 
Python ver: 3.10

**Comment by vurusovs** [comment]
@VimalWill could you provide more details what the problem you met?
Please, take a look at https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md

**Comment by VimalWill** [comment]
@vurusovs  I  followed the same steps only for building for source in linux machine, but the get the same error as i reported earlier when I try to convert my nncf based int 8 quantized tf model to openvino IR using convert_model()

**Comment by andrei-kochin** [comment]
@VimalWill do you have any good news on your trials?

**Comment by andrei-kochin** [comment]
Closing as operation was enabled on master.
@VimalWill  Feel free to re-open in case of any concerns
