### ISSUE TITLE
[Feature Request]: How should I set the parameters to make the cpu utilization as little as possible?

### ISSUE THREAD

**Issue by yukaizhou** [openvinotoolkit/openvino#19474]
### Request Description

To have OpenVINO support yolov8 model (with description)

### Feature Use Case

Recent autonomous vehicles have been using the yolov8 model to perform object segmentation.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by vurusovs** [comment]
@yukaizhou you may check official OpenVINO notebook about Yolo v8 https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/230-yolov8-optimization

**Comment by wangleis** [comment]
@yukaizhou May I know if you want to limit CPU resource for CPU inference? 

If yes, please set `ov::inference_num_threads` to the maximum number of candidate processors during compile_model().

**Comment by yukaizhou** [comment]
> @yukaizhou May I know if you want to limit CPU resource for CPU inference?
> 
> If yes, please set `ov::inference_num_threads` to the maximum number of candidate processors during compile_model().
 
Yes, I need to limit the cpu utilization to no more than 10% for model inference. Below is the basic information about my computer and the way I set it up in the code. Is that correct? If it is correct and the cpu utilization is basically unchanged in this way, what is the reason for this?

<img width="504" alt="1693803886503" src="https://github.com/openvinotoolkit/openvino/assets/38181468/cc0f533e-3d1b-4fee-b709-0b3d1322ce9f">

**Comment by wangleis** [comment]
@yukaizhou Please set `ov::inference_num_threads` to 1 in your case. Then OpenVINO will only use one processor for inference. 

Since your platform is 4 cores 8 processors, not sure if full workload of 1 processors is less than 10%.

**Comment by wangleis** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
