### ISSUE TITLE
RuntimeError: AssertionFailed: input->desc().numDims() == output->desc().numDims()

### ISSUE THREAD

**Issue by srivastava-ayush** [openvinotoolkit/openvino#1956]
Hi
I am running Neural Compute stick 2 on a latte panda board(OS: ubuntu 18.04.3). I am getting the following error "RuntimeError: AssertionFailed: input->desc().numDims() == output->desc().numDims()". I am running 2 models together one involving CNN and other LSTM, output of CNN model acts as an input to LSTM model. When I use CPU plugin, both model works fine but while using MYRIAD, LSTM model throws an error. Also if I use a combination of Dense layer + Flatten instead of LSTM, model works fine. So its something to do with LSTM layer when I run it on Neural Compute stick 2 but I am not able to figure out what it is. I am using latest version of openvino(2020 R4). LSTM is shown as supported layer in openvino toolkit documentation still I am not able to run my program. Please help me in this?

**Comment by jgespino** [comment]
Hi @srivastava-ayush 

Thanks for reaching out! Are both of these custom model? Have you checked that all layers are supported on MYRIAD (Plugin for Intel NCS 2) using the QueryNetwork from the Inference Engine? See the following support article: https://www.intel.com/content/www/us/en/support/articles/000057238/software/development-software.html

Would it be possible to share your model and simple test code to reproduce?

Regards,
Jesus

**Comment by srivastava-ayush** [comment]
Hi jesus
Thanks for your reply
Yes, both are custom models. I am getting following layers as unsupported using query network

['separable_conv1d_input', 'lstm/while/Enter_3/Output_0/Data__const', 'lstm/while/Enter_2/Output_0/Data__const', 'lstm/strided_slice_7/Cast_31406_const', 'lstm/strided_slice_7/Cast_21404_const', 'lstm/strided_slice_7/Cast_11402_const', 'Constant_9789', 'Constant_9767', 'Constant_9765']

Does this mean lstm or depthwise seperable conv1d is unsupported?

Thanks
Ayush

**Comment by jgespino** [comment]
@srivastava-ayush Could you share your models and command given to Model Optimizer? Feel free to share private via email. 

Regards,
Jesus

**Comment by jgespino** [comment]
@srivastava-ayush Closing issue, feel free to re-open if additional assistance is needed.
