### ISSUE TITLE
[Help] About get_output_tensor is repeat in c++ .

### ISSUE THREAD

**Issue by DDreame** [openvinotoolkit/openvino#19570]
When I use an IR model (it is come from the toolkit [Jupyter notebook](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/225-stable-diffusion-text-to-image/225-stable-diffusion-text-to-image.ipynb)) in python, it was work very good.

But I load this model by c++,  it always get same output tensor, and i didn't know what is happened.

So, I want some help about how to fix this error and what mistake did I make

this is my simple code:
```
#include <openvino/openvino.hpp>
#include <sstream>
#include <iostream>
#include <vector>
int main() {
    ov::Core core;
    // get ov Version
    slog::info << ov::get_openvino_version() << slog::endl;

    // get all devices
    std::vector<std::string> devices = core.get_available_devices();
    for (int i = 0; i < devices.size(); i++) {
        slog::info << devices[i] << slog::endl;
    }

    // try to load model
    std::string model_path = "C:\\Users\\User\\Desktop\\sd-xl\\225-sd-ok\\text_encoder.xml";
    std::shared_ptr<ov::Model> model = core.read_model(model_path);

    int inputIds[77] = { 49406, 36896, 40808,   789,  49407,   686,  2705,   593,  7771,
         8866,   536, 19708,  3878,  2232, 25602,  5799,   49407,  49407,
        49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407,
        49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407,
        49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407,
        49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407,
        49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407,
        49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407, 49407,
        49407, 49407, 49407, 49407, 49407 };
    ov::element::Type input_type = ov::element::i64;
    ov::Shape input_shape = { 1, 77 };
    ov::Tensor input_tensor = ov::Tensor(input_type, input_shape, inputIds);
    ov::Shape in_shape = input_tensor.get_shape();
    ov::CompiledModel compiled_model = core.compile_model(model, "CPU");
    ov::InferRequest infer_request = compiled_model.create_infer_request();
    infer_request.set_input_tensor(input_tensor);
    infer_request.infer();
    const ov::Tensor& output_tensor = infer_request.get_output_tensor(1);
    ov::Shape shape = output_tensor.get_shape();
    const float* result = output_tensor.data<const float>();

    // get ten value
    for (int i = 0; i < 10; ++i) {
        std::cout << "Element " << i << ": " << result[i] << std::endl;
       
    }
    return 0;
}
```

The output always is:
```
Element 0: -0.37633
Element 1: 0.0175534
Element 2: -0.0550534
Element 3: -0.181142
Element 4: -0.0308092
Element 5: -0.343307
Element 6: -0.0157949
Element 7: -0.189905
Element 8: 0.181095
Element 9: -0.0844363
```

**Comment by rkazants** [comment]
HI @DDreame,

Can you please share your python code for which the stuff works well? Now your C++ code is quite different from the notebook code where we pass data from the previous iteration to the next one.

Best regards,
Roman

**Comment by DDreame** [comment]
> HI @DDreame,
> 
> Can you please share your python code for which the stuff works well? Now your C++ code is quite different from the notebook code where we pass data from the previous iteration to the next one.
> 
> fyi, @eaidova.
> 
> Best regards, Roman

Hi,

Very thanks for your reply, and I corrected my mistake in today.  That error is because I only compare some tensor, not total tensor.  

About this mistake have two reaseon : 
First, In text encoder, the first 768 always same output.
Second, except for the 768 at the beginning, there are partially identical Tensors in two different sentences in C++. 

So, I mistakenly thought they were two identical Tensors, and I will close this issue.

Thanks for your work in this repo, this is a very good repo.
