### ISSUE TITLE
Add a clear error message when creating an empty `Constant`

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#19617]
### Context

Current Constant implementation does not allow for creating empty Constants:
https://docs.openvino.ai/2023.0/openvino_docs_ops_infrastructure_Constant_1.html

Trying to do so results in a cryptic error message:
```python
IndexError: index 0 is out of bounds for axis 0 with size 0
```

### What needs to be done?

1. Add a clear error message for the user trying to create an empty Constant
This can be done in either Python wrapper: https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/openvino/runtime/opset1/ops.py#L334-L347
Or in C++ to Python binding: https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/ops/constant.cpp

It's up to you to decide where the error message implementation will be a good fit.

2. Make sure the error message appears
This can be done either manually or by writing a test.

3. Create a Pull Request

### Resources 

- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [How to extend OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/code_examples.md)
- [How to test OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md)
- [Blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

### Contact points

@p-wysocki
@jiwaszki
@akuporos

Don't hesitate to reach out, we're here to help!

Ticket: 114374

**Comment by p-wysocki** [comment]
PR: https://github.com/openvinotoolkit/openvino/pull/19674

**Comment by p-wysocki** [comment]
The PR has been merged. Thank you @siddhant-0707!

**Comment by siddhant-0707** [comment]
Glad to help! 😃

**Comment by p-wysocki** [comment]
I'm moving the issue to the completed section in Contributions Welcome list.
