### ISSUE TITLE
Align `openvino.compile_model` and `openvino.Core.compile_model` functions

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#19616]
### Context

There are two namespaces from which you can call a `compile_model` function:
 - `openvino.compile_model`
The code for it can be found under https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/openvino/runtime/ie_api.py#L600-L610
 - `openvino.Core.compile_model`
 The code for it can be found under 
https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/openvino/runtime/ie_api.py#L495-L544

Currently, you can only give `model_path` argument to `openvino.compile_model`, which makes its behavior different from `openvino.Core.compile_model`, which can take three arguments. The goal of this task is to align the functions.

### What needs to be done?

1. Align the function behavior
This can be done by changing the code for `openvino.compile_model` from
```python
def compile_model(model_path: Union[str, Path]) -> CompiledModel:
```
to something along the lines of 
```python
def compile_model(
    self,
    model: Union[Model, str, Path],
    device_name: Optional[str] = “AUTO”,
    config: Optional[dict] = None,
) -> CompiledModel:
```
2. Add tests for `openvino.compiled_model` covering the new functionality
3. Create a Pull Request

### Resources
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [How to extend OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/code_examples.md)
- [How to test OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md)
- [Blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

### Contact points

@p-wysocki
@jiwaszki
@akuporos

Don't hesitate to reach out, we're here to help!

Ticket: 118851

**Comment by siddhant-0707** [comment]
.take
