### ISSUE TITLE
Does openvino infer support in-place buffer ?

### ISSUE THREAD

**Issue by Jsy0220** [openvinotoolkit/openvino#19743]
Hi
   I have a special network using the previous output as the next input, so I use the same tensor as input of `set_input_tensor` and `set_output_tensor` for one request as it can save one copy operation, but it cored dump. 
  So is `infer` support in-place buffer ? If not, is there any way to deal with this situation without copy ?
Thank you

**Comment by ilyachur** [comment]
Hi @Jsy0220 it depends on plugin implementation.
What plugin do you use?

**Comment by Jsy0220** [comment]
I use CPU plugin
