### ISSUE TITLE
[Feature Request]: Improve the ov_core_read_model_from_memory API Definition in OpenVINO Library

### ISSUE THREAD

**Issue by sdcb** [openvinotoolkit/openvino#19833]
### Request Description

The current OpenVINO library API ov_core_read_model_from_memory seems to have a design issue. Specifically, the model_str parameter, which appears to be a string, actually points to the model file in memory. Internally, it is then converted into a string for processing. This leads to a problem where if the model file includes a null character ('\0'), the read-in model size will be smaller than the actual size. Conversely, if the model file does not contain a null character, it will inevitably cause a memory error.

```c
/**
 * @brief Reads models from IR / ONNX / PDPD / TF / TFLite formats.
 * @ingroup ov_core_c_api
 * @param core A pointer to the ie_core_t instance.
 * @param model_str String with a model in IR / ONNX / PDPD / TF / TFLite format.
 * @param weights Shared pointer to a constant tensor with weights.
 * @param model A pointer to the newly created model.
 * Reading ONNX / PDPD / TF / TFLite models does not support loading weights from the @p weights tensors.
 * @note Created model object shares the weights with the @p weights object.
 * Thus, do not create @p weights on temporary data that can be freed later, since the model
 * constant data will point to an invalid memory.
 * @return Status code of the operation: OK(0) for success.
 */
OPENVINO_C_API(ov_status_e)
ov_core_read_model_from_memory(const ov_core_t* core,
                               const char* model_str,
                               const ov_tensor_t* weights,
                               ov_model_t** model);
```

I propose to modify the API by renaming the model_str parameter to model_data, and adding a new integer parameter model_data_size after it, to accurately represent the memory size of model_data.

```c
OPENVINO_C_API(ov_status_e)
ov_core_read_model_from_memory(const ov_core_t* core,
                               const char* model_data,
                               const int model_data_size,
                               const ov_tensor_t* weights,
                               ov_model_t** model);
```

### Feature Use Case

This proposed change would prevent potential memory errors and inaccurate model size readings that can occur if model files contain or lack null characters. It would increase the robustness of the API, making it more reliable and easier to use for developers. This improvement could also potentially increase the efficiency of model loading operations, as it provides clearer information about the memory size required for the operation.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by riverlijunjie** [comment]
Char string contains '\0' at the end to mean string is ended. So for char string, we don't need data size.
And in C application, we suggest adding a '\0' at the end of string.

Can you share your model string, why it contains a '\0'  in the middle of its contents?

**Comment by sdcb** [comment]
[ppocrv3-det-cn.zip](https://github.com/openvinotoolkit/openvino/files/12614667/ppocrv3-det-cn.zip)
let's say this model, it's from PaddleOCR detection model v3, this model contains over 4000 '\0'

**Comment by riverlijunjie** [comment]
@sdcb have you ever tried C++ API to read model from memory?

https://github.com/openvinotoolkit/openvino/blob/d62348337fe3a5af2cab66dd38778cc07b6291d6/src/inference/include/openvino/runtime/core.hpp#L104-L115

You know, C API is just a wrapper of C++ API, so I have tried to check C++ API like this, which should be the similar behavior of C API you reported:

```
        auto read_file = [&](const std::string& file_name, size_t& size) {
            FILE* sFile = fopen(file_name.c_str(), "r");
            fseek(sFile, 0, SEEK_END);
            size = ftell(sFile);
            std::cout << "file_name: " << file_name << ", size = " << size << std::endl;
            uint8_t *ss = (uint8_t *)malloc(size);
            rewind(sFile);
            fread(&ss[0], 1, size, sFile);
            fclose(sFile);
            return ss;
        };

        size_t xml_size, bin_size;
        auto xml_str = read_file(model_path, xml_size);
        auto bin_str = read_file(bin_path, bin_size);
        ov::Tensor weight_tensor = ov::Tensor(ov::element::u8, {1, bin_size}, bin_str);
        std::string model_str = std::string((char *)xml_str, xml_size);
        std::shared_ptr<ov::Model> model = core.read_model(model_str, weight_tensor);
```

But it failed like this:

```
[ INFO ] Build ................................. 2023.2.0-12393-e3f1ff7f2a7-river/string_test
[ INFO ] 
[ INFO ] Loading model files: /mnt/data1_1c41/river//models/ppocrv3-det-cn/inference.pdmodel
file_name: /mnt/data1_1c41/river//models/ppocrv3-det-cn/inference.pdmodel, size = 1413260
file_name: /mnt/data1_1c41/river//models/ppocrv3-det-cn/inference.pdiparams, size = 2377917
Exception from src/inference/src/core.cpp:103:
Check 'ext_stream && ext_stream.is_open()' failed at src/frontends/paddle/src/frontend.cpp:151:
FrontEnd API failed with InitializationFailure:
Cannot open model file.
```

It seems there is some issue in PDPD frontend, as we known `ov::util::read_model` will  convert weight tensor into `ngraph::runtime::AlignedBuffer` and put it into `std::vector<ov::Any>& variants` to pass to frontend:
https://github.com/openvinotoolkit/openvino/blob/619c4bfce1dad7e7abe6fd46c058160ac28b9ca2/src/inference/src/model_reader.cpp#L157-L169

But in PDPD frontend, it doesn't handle this `ngraph::runtime::AlignedBuffer` type, so it report error as above:
https://github.com/openvinotoolkit/openvino/blob/d62348337fe3a5af2cab66dd38778cc07b6291d6/src/frontends/paddle/src/frontend.cpp#L138-L153


Anyhow, let's come back the problem you reported: how to handle string with multiple '\0' 
In C API, the input char string will be converted to std::string() and then as C++ API's input argument:
https://cplusplus.com/reference/string/string/string/

`string (const char* s);`

If there are multiple '\0', we should adopt below std::string constructor:

`string (const char* s, size_t n);`

It should store all char data(contain '\0') into std::string object, and plus openvino will convert std::string into std::istream to parse it in frontend, it should be not problem.

**Comment by riverlijunjie** [comment]
If we plan to support '\0' character in string, we cannot use `char* model_str`, which may mislead user, it will be better to change it to be `char[] model_str`. 
In general convention, if we use  `char* model_str`, it always means that it is string with null-terminated, but if we add string length argument, it should be a special usage, so I suggest we can add a new C API for such case, for example:

```
OPENVINO_C_API(ov_status_e)
ov_core_read_model_from_array(const ov_core_t* core,
                               const char[] model_data,
                               const int model_data_size,
                               const ov_tensor_t* weights,
                               ov_model_t** model);
```

@ilya-lavrenov how do you think about this ticket?

**Comment by sdcb** [comment]
> @sdcb have you ever tried C++ API to read model from memory?
@riverlijunjie I think it's OK to using C++ API, because C++ std::string contains both memory and length, it does not care about '\0' actually. But our C API don't have a length here.

**Comment by riverlijunjie** [comment]
@sdcb If we use std::string(str, str_size), it should can contain '\0' chars,  but as previous experience I have done, there is PDPD frontend issue to make C++ API cannot work. Could you also try C++ api to confirm it? 
https://github.com/openvinotoolkit/openvino/blob/d62348337fe3a5af2cab66dd38778cc07b6291d6/src/inference/include/openvino/runtime/core.hpp#L104-L115

But for the C convention, char* data almost uses '\0' as terminator, right?

**Comment by sdcb** [comment]
As I said, I believe C++ API don't have any issue because std::string contains both memory address **and memory length**, but it's not useful to me because I'm invoking OpenVINO from other programming language, only C API is binary compatible.

**Comment by riverlijunjie** [comment]
ok, we need do 2 tasks:
1. Enable C API support char pointer with many '\0' chars.
2. Enable PDPD frontend to support parsing `ngraph::runtime::AlignedBuffer` @ceciliapeng2011 please help!
