### ISSUE TITLE
Change Windows shared object loader to accept loading flags

### ISSUE THREAD

**Issue by rominf** [openvinotoolkit/openvino#199]
Use case:
We want to supply our software with OpenVINO and OpenCV libraries bundled in one dir. This dir is not the same as the current dir of the main binary. That's why we are using the `PluginDispatcher` argument to pass the plugin dirs. The problem is that it works only with plugin library, but not with other dependent libraries, and the plugin doesn't load.

The solution would be to add to `PluginDispatcher` constructor additional `unsigned long` argument with a default value of 0, that is used only on Windows, and pass it to the `LoadLibraryExA` (instead of current `LoadLibrary`) function. Thus, the user could pass `LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR` and everything would work for him.

Do you agree with me? If so, should I make a PR?

**Comment by esmirno** [comment]
Hi, we briefly discussed your proposed improvement, and  what we would like to modify is to enable unconditionally following flags for LoadLibraryEx: LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR | LOAD_LIBRARY_SEARCH_DEFAULT_DIRS
Right now as i know, we cannot integrate PR-s directly, so I believe we can fix this issue without PR from your side. Thanks for smart catching the problem.

--eugene
