### ISSUE TITLE
[Good First Issue]: Refactor `torchvision` preprocessing converter into Python `singledispatch`

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#19912]
### Context

We strive to keep our code as clean as possible - one of the ways to do it is to use advanced Python features. One of them is `singledispatch` method, which you can read more about [here](https://docs.python.org/3/library/functools.html#functools.singledispatch).

This feature has been introduced in Python 3.8, so we were hesitant to use it, and in the end used a workaround - we download `singledispatchmethod` from [PyPI](https://pypi.org/project/singledispatchmethod/) as a dependency, for Python 3.7 only (we support a range of Python versions).

Right now we are in the process of [dropping Python 3.7 support](https://github.com/openvinotoolkit/openvino/pull/19534), which means we can use `singledispatch` freely. This task regards refactoring some code in our `torchvision` preprocessing converter to use `singledispatch` feature.

### What needs to be done?

The task regards addressing these two TODO comments:

- https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/openvino/preprocess/torchvision/torchvision_preprocessing.py#L50
- https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/openvino/preprocess/torchvision/torchvision_preprocessing.py#L70

The functions need to have "overloads" for different types of inputs. Right now it's being done by simple `if` conditions, but it should be done with `singledispatch`. An example implementation of `singledispatch` can be found in our [data dispatcher](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/openvino/runtime/utils/data_helpers/data_dispatcher.py).

### Example Pull Requests

An example usage of `singledispatch` in our repository can be found in https://github.com/openvinotoolkit/openvino/pull/15290, to be specific in the `data_dispatcher.py` file.

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- [How to test OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md)

### Contact points

@p-wysocki 
@jiwaszki
@akuporos

**Comment by mlukasze** [comment]
thanks @mahimairaja, good job!
