### ISSUE TITLE
ReadNetwork / ReadWeights

### ISSUE THREAD

**Issue by Ziv-Huang** [openvinotoolkit/openvino#20]
is ie_cnn_net_reader.cpp  an open-source code ?

Because I want to read network and weights in memory, the function needs to be modified.
is another solution to do?

**Comment by aiopeniot** [comment]
ie_cnn_net_reader.h just a function header, you can find the implement in ie_icnn_net_reader_impl.cpp. Good luck.

**Comment by elvin-nnov** [comment]
@Ziv-Huang Not sure if I understood question correctly, do you mean reading network not from disk but from "in-memory storage"? There are two functions allowing to do this: `CNNReader::ReadNetwork(const void *model, size_t size)` and `CNNReader::SetWeights(const TBlob<uint8_t>::Ptr &weights)`

**Comment by ilyachur** [comment]
@Ziv-Huang  OpenVINO provides API which allow to read model from memory:
`InferenceEngine::Core::ReadNetwork(const std::string& model, const Blob::CPtr& weights)`

I will close the issue. Feel free to reopen it if this approach doesn't work for your cases.
