### ISSUE TITLE
how to convert pth2IR?

### ISSUE THREAD

**Issue by Masque555** [openvinotoolkit/openvino#20023]
Hello, I have noticed that OpenVino's compatibility with PyTorch has improved. The function of directly converting PyTorch models to IR is now mature. Can you add some examples of pth2IR, such as object detection and semantic segmentation? Thank you.

You can find notebook to quantize segmentation model here: https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/110-ct-segmentation-quantize

I highly recommend using OpenVINO model to obtain quantized model with the best performance in OpenVINO.

_Originally posted by @alexsu52 in https://github.com/openvinotoolkit/openvino_notebooks/issues/1223#issuecomment-1663706764_

**Comment by eaidova** [comment]
@Masque555  we have general instruction  how to convert pytorch models to openvino in notebooks here https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/102-pytorch-to-openvino/102-pytorch-to-openvino.ipynb
This flow should not be dependent from task.

Also provided by you link on notebook also uses conversion pytorch models to IR :)
Additional examples for semantic segmentation can be found in https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/204-segmenter-semantic-segmentation
and https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/249-oneformer-segmentation
One more example will be added soon based on torchvision https://github.com/openvinotoolkit/openvino_notebooks/pull/1345
For object detection, we have example based on detectron2 https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/123-detectron2-to-openvino

**Comment by Masque555** [comment]
> @Masque555 we have general instruction how to convert pytorch models to openvino in notebooks here https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/102-pytorch-to-openvino/102-pytorch-to-openvino.ipynb This flow should not be dependent from task.
> 
> Also provided by you link on notebook also uses conversion pytorch models to IR :) Additional examples for semantic segmentation can be found in https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/204-segmenter-semantic-segmentation and https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/249-oneformer-segmentation One more example will be added soon based on torchvision [openvinotoolkit/openvino_notebooks#1345](https://github.com/openvinotoolkit/openvino_notebooks/pull/1345) For object detection, we have example based on detectron2 https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/123-detectron2-to-openvino

thank you,i will try.

**Comment by andrei-kochin** [comment]
@Masque555 have you succeed with this?
