### ISSUE TITLE
How to implement MediaPipe using OpenVINO runtime

### ISSUE THREAD

**Issue by jerin-scalers-ai** [openvinotoolkit/openvino#20031]
As per latest release, Media pipe is integrated with OpenVINO runtime and OVMS. 
I found examples of Media Pipe with OVMS but I couldn't find example/guide on implementing/integrating Media Pipe using OpenVINO runtime.  

I am looking to implement Media pipe for YOLO v8 using OpenVINO runtime in Python.

**Comment by duy1851999** [comment]
The same question, how can it fit the implement Media pipe for YOLO v8 using OpenVINO runtime in Python
