### ISSUE TITLE
Enabling AMX instruction

### ISSUE THREAD

**Issue by js333031** [openvinotoolkit/openvino#20065]
While converting Yolov4 model on a Xeon 4th Gen system, omz_converter printed following line:

`omz_converter --name yolo-v4-tf --output_dir=$HOME/My-Notebooks/models/`
`To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.`

```
$ pip list | grep -e openvino -e tensorflow
openvino                      2023.1.0
openvino-dev                  2023.1.0
openvino-telemetry            2023.1.1
tensorflow                    2.12.1
tensorflow-estimator          2.12.0
tensorflow-io-gcs-filesystem  0.34.0
```

Using Python 3.9.10, Intel(R) Xeon(R) Platinum 8480+, Ubuntu 22.04.2 LTS

Some more output:
```
========== Running pre-convert script for yolo-v4-tf
Pre-convert command: /home/sdp/miniconda3/envs/yolov4/bin/python -- /home/sdp/miniconda3/envs/yolov4/lib/python3.9/site-packages/openvino/model_zoo/models/public/yolo-v4-tf/pre-convert.py -- /home/sdp/yolov4_flex_test/public/yolo-v4-tf /home/sdp/My-Notebooks/models/public/yolo-v4-tf

2023-09-26 20:24:48.717487: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-26 20:24:48.719124: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-26 20:24:48.749581: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-26 20:24:48.749891: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-26 20:24:49.148224: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading weights.
Weights Header:  0 2 5 [32032000]
Parsing Darknet config.
Creating Keras model.
Parsing section net_0
```

**Comment by ilya-lavrenov** [comment]
> To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

It's printed by TF itself, not by OMZ downloader.
See https://stackoverflow.com/questions/66092421/how-to-rebuild-tensorflow-with-the-compiler-flags

**Comment by js333031** [comment]
I understand that TF is printing the message and that those instructions are not compiled in. However, is there a version of TF with those instructions in use? The requirements.txt file or openvino-dev[tensorflow] is specifying the TF install. So the dependency (TF version) needs to be updated in OV/OMZ requirements.txt file.

**Comment by ilya-lavrenov** [comment]
You can install any TensorFlow version you need and to not use `openvino-dev[tensorflow]`
From OpenVINO perspective it's does not matter what versions to use, `[tensorflow]` was originally provided as a helper to install TensorFlow version OpenVINO was validated with

**Comment by js333031** [comment]
My initial comment shows TF 2.12.1 is present. Aren't the AMX instructions in use in TF, starting w/2.12?

**Comment by ilya-lavrenov** [comment]
> My initial comment shows TF 2.12.1 is present. Aren't the AMX instructions in use in TF, starting w/2.12?

This is a question to TensorFlow forum, not to OpenVINO
