### ISSUE TITLE
C++ Runtime Model Optimization 

### ISSUE THREAD

**Issue by carlosost** [openvinotoolkit/openvino#2014]
I will distribute my solution with the models and weights, but I would like to keep them encrypted.

Is there a way to run the Model Optimizer within a C++ context, keep the generated IR in memory and use it as parameter to the function `ReadNetwork`? So, at the end I have two main questions here:

1. Is there a way to run Model Optimizer using C++ ?
2. Is there a `ReadNetwork` function that receives a model as `string` or `buffer`?

The idea would be something like:

    load original encrypted models
    decrypt original models and have it as string in memory
    run Model Optimizer
    store the resulting IR in memory
    use the "in memory" IR as parameters to ReadNetwork
    use the InferenceEngine::CNNNetwork as usual

Regards.

**Comment by yury-gorbachev** [comment]
Any reason you cannot encrypt/decrypt IR directly?
Thanks,
/Yury

**Comment by yury-gorbachev** [comment]
Did mean to send this link as well:
https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_protecting_model_guide.html

**Comment by carlosost** [comment]
Yury,

There is no reason I can not encrypt IR directly. My question was broad to cover all the possibilities I foresee and then, avoid create a long thread. I think it worked, since your contribution seems to be the answer I was looking for.

Thank you so much and I will let you know if I succeeded with this approach.

Regards.

**Comment by yury-gorbachev** [comment]
OK, I was thinking maybe there is some restriction in terms of application that forces you to keep model in original format...
Will wait for your feedback, thanks...
/Yury

**Comment by jgespino** [comment]
Closing, feel free to re-open if additional assistance is needed.
