### ISSUE TITLE
Extend ONNX Frontend with `Shape-15` operator

### ISSUE THREAD

**Issue by mitruska** [openvinotoolkit/openvino#20194]
## Context
Neural networks are graphs consisting of nodes called operators. Each operator corresponds to a mathematical function, usually described in framework's documentation or an AI standard, such as ONNX.

OpenVINO ONNX Frontend is a component responsible for working with ONNX graphs and requires implementation of different ONNX operators in order to use ONNX models.

This task requires extending OpenVINO ONNX Frontend with `Shape-15` ([ONNX Shape](https://onnx.ai/onnx/operators/onnx__Shape.html#l-onnx-doc-shape) operator since ONNX Opset 15). 
ONNX Shape operator has been extended with additional "start, end" attributes, what should be reflected in the conversion logic.
Currently those attributes are ignored by ONNX FE, and ONNX Shape is converted directly to [`ov::ShapeOf`](https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/shape/ShapeOf_3.md),
but it can be supported at the ONNX FE conversion step, with additional [`ov::Slice`](https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/movement/Slice_8.md) layer.

Necessary help will be provided by ONNX Fronted team.

## Operator specification
Operator details can be found in [ONNX Operators](https://github.com/onnx/onnx/blob/main/docs/Operators.md).

## Todo list
1. Update `.hpp` and `.cpp` files: 
[/openvino/src/frontends/onnx/frontend/src/op/shape.hpp](https://github.com/openvinotoolkit/openvino/blob/a6e5f6bdb45897758cd720489de29350d415f1bd/src/frontends/onnx/frontend/src/op/shape.hpp)
[/openvino/src/frontends/onnx/frontend/src/op/shape.cpp](https://github.com/openvinotoolkit/openvino/blob/a6e5f6bdb45897758cd720489de29350d415f1bd/src/frontends/onnx/frontend/src/op/shape.cpp)
2. Prepare an implementation of this operator in form of a function. It should be placed in [set_15 namespace](https://github.com/openvinotoolkit/openvino/blob/a6e5f6bdb45897758cd720489de29350d415f1bd/src/frontends/onnx/frontend/src/op/shape.hpp#L16).
3. Register the next version of the Shape operator: `REGISTER_OPERATOR("Shape", 15, shape);` in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/a6e5f6bdb45897758cd720489de29350d415f1bd/src/frontends/onnx/frontend/src/ops_bridge.cpp#L474) while keeping alphabetical order
4. Create ONNX Shape-15 test model(s) in [ONNX models directory](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/tests/models/). OpenVINO test infrastructure then converts prototxt files to ONNX models - you will use those models later in tests. Double check the ONNX opset version of the model that should be at least 15.
5. Add tests covering all use cases [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import.in.cpp)

More details in [adding operators to ONNX Frontend guide](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md)

## Resources
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- Guides on [ONNX Frontend architecture](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/architecture.md) and [ONNX Frontend tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/tests.md)

## Example PRs
- https://github.com/openvinotoolkit/openvino/pull/15076
- https://github.com/openvinotoolkit/openvino/pull/14936
- https://github.com/openvinotoolkit/openvino/pull/12510

## Tips
Proper implementation should enable the following tests:
https://github.com/openvinotoolkit/openvino/blob/a6e5f6bdb45897758cd720489de29350d415f1bd/src/frontends/onnx/tests/__init__.py#L138
https://github.com/openvinotoolkit/openvino/blob/a6e5f6bdb45897758cd720489de29350d415f1bd/src/frontends/onnx/tests/tests_python/test_backend.py#L322-L329
Also for compatibility API: https://github.com/openvinotoolkit/openvino/blob/a6e5f6bdb45897758cd720489de29350d415f1bd/src/bindings/python/tests_compatibility/test_onnx/test_backend.py#L330

## Contact points
@mitruska
@p-wysocki
@gkrivor 
Don't hesitate to reach out, we're here to help!

**Comment by hotcheetofiend** [comment]
If no one has been assigned yet, could I work on this issue?

**Comment by p-wysocki** [comment]
Hello @hotcheetofiend, thanks for taking a look! I assigned you.

**Comment by p-wysocki** [comment]
Hi @hotcheetofiend, are you still working on it? I'm updating the tasks' statuses.

**Comment by hotcheetofiend** [comment]
> Hi @hotcheetofiend, are you still working on it? I'm updating the tasks' statuses.

Yes; sorry! I will try to get it done by Friday.

**Comment by mitruska** [comment]
Hello @hotcheetofiend, let us know if you find this task challenging.
We are here to help 💡

**Comment by p-wysocki** [comment]
Hi @hotcheetofiend, are you still working on this or can we reopen the issue for pickup by other contributors?

**Comment by BharathSatheeshKumar** [comment]
may i just get a brief idea on this issue

**Comment by BharathSatheeshKumar** [comment]
may i work upon this issue with @hotcheetofiend

**Comment by BharathSatheeshKumar** [comment]
May I get guided by anyone. Like i just want a simple description on the issue so that i can work on it. 
Even tho im new i can give results

**Comment by mitruska** [comment]
Hello @BharathSatheeshKumar, thank you for taking this issue, the idea is explained in the [issue description above](https://github.com/openvinotoolkit/openvino/issues/20194#issue-1921961998):

> This task requires extending OpenVINO ONNX Frontend with Shape-15 ([ONNX Shape](https://onnx.ai/onnx/operators/onnx__Shape.html#l-onnx-doc-shape) operator since ONNX Opset 15).
> ONNX Shape operator has been extended with additional "start, end" attributes, what should be reflected in the conversion logic.
> Currently those attributes are ignored by ONNX FE, and ONNX Shape is converted directly to [ov::ShapeOf](https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/shape/ShapeOf_3.md),
> but it can be supported at the ONNX FE conversion step, with additional [ov::Slice](https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/movement/Slice_8.md) layer.

In other words, the goal is to add support for the `start` and `end` attributes of the ONNX Shape-15, by conversion to `Slice(ShapeOf(data), start, end, 1, 0)` subgraph.
Also please take a look at the TODO steps and example PRs, where related files are mentioned.

**Comment by BharathSatheeshKumar** [comment]
Thank You.
And Do I Get a deadline for this so that i can give my best at anycost

**Comment by mitruska** [comment]
Happy to help 🚀 
Currently there is no specific deadline for this task, but you can share your approximate time estimation and let us know about any troubles.

**Comment by BharathSatheeshKumar** [comment]
I've updated the hpp and cpp files but cant create a PR.  Help me out
I'll let you know about the deadline within a few days of working with this issue

**Comment by mitruska** [comment]
Step by step contribution guide, including how to create a Pull Request [PR], can be found in the Resources section of the issue description, please follow:

>[blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

**Comment by p-wysocki** [comment]
Hello @BharathSatheeshKumar, do you need any help?

Just yesterday our CONTRIBUTING.md has been updated [with a technical guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md) - I highly recommend checking it out. :)

**Comment by BharathSatheeshKumar** [comment]
yea sure will check and report 
And I do need some help with the shapes if someone can team up very appreciable

**Comment by BharathSatheeshKumar** [comment]
Yea sure will check that out and will let you guys know soon.
And i still have problems in creating a pr for this base even tho I followed what @mitruska sent

**Comment by BharathSatheeshKumar** [comment]
PR link?

**Comment by p-wysocki** [comment]
Hello @BharathSatheeshKumar, could you please let us know what issues you're having?

**Comment by BharathSatheeshKumar** [comment]
Just now sorted the problem thanks....and will update within a day or so

**Comment by BharathSatheeshKumar** [comment]
i cant access the main file any ideas?

**Comment by p-wysocki** [comment]
Due to long inactivity I'm unassigning the issue for other contributors. If you're still working on this task @BharathSatheeshKumar please let us know, you'll be reassigned.

**Comment by AlexFierro9** [comment]
.take

**Comment by BharathSatheeshKumar** [comment]
sorry for the delay tho
let me work with @AlexFierro9 for the next project

**Comment by MeeCreeps** [comment]
.take

**Comment by MeeCreeps** [comment]
Hi @p-wysocki  , I have raised PR #23492  for this issue,  please let me know if any modifications are needed.

**Comment by mlukasze** [comment]
thanks @MeeCreeps!
@gkrivor will take a look soon

**Comment by mitruska** [comment]
Hello @MeeCreeps your PR has been reviewed, approved and merged 🚀 
Thanks, Looking forward to your further contribution!
