### ISSUE TITLE
[Good First Issue]: Automate the Good First Issues board - "In review" column

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#20211]
### Context

We have recently switched to managing the Good First Issues using GitHub Projects. Another step towards easier management is automating the board, so the tasks move between columns without having to manually drag them.

The board can be found under https://github.com/orgs/openvinotoolkit/projects/3

The board has been partially automated using the default GitHub Workflows:

- Newly added issues with label "good first issue" are automatically added to "Contributors needed" column
- When an issue is closed, it automatically moves to the "Closed" column

However, the columns "Assigned" and "In review" cannot be automated using the default GitHub Workflows. This task regards automating the "In review" column.

### What needs to be done?

Use a GitHub Action to move tasks from column "Assigned" to "In review", when there is a Pull Request assigned to the issue. This action should work both ways - sometimes the Pull Requests are abandoned, in which case we'll unlink the PR. In that case the issue should be automatically reverted to the "Assigned" column.

### Example Pull Requests

Examples can be found under https://docs.github.com/en/actions/managing-issues-and-pull-requests/using-github-actions-for-project-management

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- [Using GitHub Actions for project management](https://docs.github.com/en/actions/managing-issues-and-pull-requests/using-github-actions-for-project-management)

### Contact points

@p-wysocki 
@mlukasze 

### Ticket

N/A

**Comment by ilya-lavrenov** [comment]
When you create or change the issue, you can change the status here:
![image](https://github.com/openvinotoolkit/openvino/assets/2566854/112adf9f-facd-42a8-8934-13864be5a750)
is it not convinient?
For me - it perfectly works.

**Comment by p-wysocki** [comment]
It works for me too actually, I didn't see it before. Great feature. I guess we could settle for manually marking issues as in review - that way, if a contributor opens a WIP PR, the issue will not be falsely marked as "In review". What do you think?

One way to look at it is we could start worrying about it once it's actually a problem, as of now we could manage doing it manually with this helpful button you found.

**Comment by ilya-lavrenov** [comment]
For me a good way to denote that an issue has a corresponding PR, is to link this PR via these set of keywords https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Example https://github.com/openvinotoolkit/openvino/issues/20069, which has 2 linked PRs.

**Comment by p-wysocki** [comment]
I agree. Let's close this issue and reopen when/if we get to the point when we have so many good first issues that managing their "in review" status manually is too time consuming.
