### ISSUE TITLE
[Bug]opencv 4.4.0 build with openvino can't  load model.

### ISSUE THREAD

**Issue by tangtang666** [openvinotoolkit/openvino#2025]
##### System information (version)

I had built a opencv with openvino.and used it to load the openvino model in vc2019,but I get the follow error.This model can run in mac or linux,I had link format_reader.lib opencv_world440.lib inference_engine.lib. if any lib I not link?
**Unknown model format! Cannot find reader for model format: xml and read the model: C:\Users\ASUS\Documents\openvino_app\model\xxx.xml. Please check that reader library exists in your PATH.**

```c++
    try {
        net = readNetFromModelOptimizer(xml, bin);
        net.setPreferableBackend(DNN_BACKEND_INFERENCE_ENGINE);
        net.setPreferableTarget(DNN_TARGET_CPU);
    }
    catch (const std::exception& ex) {
        std::cerr << ex.what() << std::endl;
    }
```

**Comment by dkurt** [comment]
Hi!

Can you reproduce the issue with OpenVINO API? Just to check if this is OpenVINO issue or OpenCV's one.

**Comment by tangtang666** [comment]
> Hi!
> 
> Can you reproduce the issue with OpenVINO API? Just to check if this is OpenVINO issue or OpenCV's one.

Hi, thanks for your reply.If I use the opencv where it in openvino directory，it work，but it not easy to deploy，that link to many lib and need to setupvars.bat first。Are there any easy ways to deploy it in Windows 10.

**Comment by dkurt** [comment]
Well, please try prebuilt OpenCV with IE binaries this way: https://github.com/opencv/opencv/releases (dldt suffix).

**Comment by tangtang666** [comment]
> Well, please try prebuilt OpenCV with IE binaries this way: https://github.com/opencv/opencv/releases (dldt suffix).

yeah, it work,and I find the miss library,if miss the inference_engine_ir_reader.dll,i can get this error.But the library whice use to   inference by openvino is too big, it all need almost 90M.

**Comment by dkurt** [comment]
Can we close this issue?

**Comment by tangtang666** [comment]
yeah,thaks.
