### ISSUE TITLE
[Good First Issue]: Extend Python API with `ScatterNDUpdate-3`

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#20284]
### Context

Instead of doing C++ to Python bindings for each and every OpenVINO operator, we are using internal `NodeFactory`, which takes the name of the operator as an argument:
```python
scatter = NodeFactory().create("ScatterNDUpdate", *args, **kwargs)  # pseudocode
```
Such an API is counter intuitive for an end user, so we are also adding Python API extensions with a proper, Pythonic and clear functions. The Python extensions are just wrappers around `NodeFactory` object call, and their primary goal is to provide appropriate inputs docs and a more Pythonic API:
```python
scatter = ops.ScatterNDUpdate(*args, **kwargs)  # pseudocode
```

This task regards adding such a Python API extension for ScatterNDUpdate-3 operator.

### What needs to be done?

1. Extend Python API and Python compatibility API with ScatterNDUpdate (operator should be added to the newest available opset)
2. Add tests for both APIs
3. Create a PR

Please see attached PR, this task is very similar to the linked `GeneralProposals` extension.

### Example Pull Requests

https://github.com/openvinotoolkit/openvino/pull/11723

### Resources

- [ScatterNDUpdate documentation](https://docs.openvino.ai/2023.1/openvino_docs_ops_movement_ScatterNDUpdate_3.html)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@p-wysocki 
@jiwaszki 
@akuporos 

### Ticket

121506

**Comment by kk271kg** [comment]
Hello,
Can I contribute on this issue? I would like to try to solve this.

**Comment by p-wysocki** [comment]
Hello @kk271kg, thanks for taking a look! I assigned you. Feel free to ask questions.

**Comment by p-wysocki** [comment]
Hello @kk271kg, are you still working on this? Do you need any assistance?

**Comment by kk271kg** [comment]
Hi @p-wysocki ,
Yes, I am working on it. I am familiarising myself with code. Please allow me some time to get back to you with an update.

**Comment by p-wysocki** [comment]
Sure! I was just checking. :) Please let us know if you have any questions.

**Comment by p-wysocki** [comment]
Hi @kk271kg, are you still working on this issue or can I return it to be picked up by other contributors?

**Comment by kk271kg** [comment]
Hi @p-wysocki ,
Yes, of course. You can expect a suggested solution this month.

**Comment by kk271kg** [comment]
Hi @p-wysocki ,
Just top be sure which opset should contain the implementation?(I suppose the opset 11)

I will try commit my suggested solution in the beginig of the next week. Would you be able to check if I am on the right way?

Just an inquery:
Do you use any DevOps technology in your project?

**Comment by akuporos** [comment]
Hi @kk271kg,
> (I suppose the opset 11)

Actually we have [opset13](https://github.com/openvinotoolkit/openvino/tree/master/src/bindings/python/src/openvino/runtime/opset13), so it'd be better place.
> Do you use any DevOps technology in your project?

Your PR will automatically trigger validation jobs.

**Comment by p-wysocki** [comment]
> Would you be able to check if I am on the right way?

Of course, we'll review your PR as soon as possible once it's up.
