### ISSUE TITLE
Model can't detect anything after quantization

### ISSUE THREAD

**Issue by davidvct** [openvinotoolkit/openvino#20437]
I converted a Yolo v8 instance segmentation model to Openvino format, and it was able to detected objects in an image.

However after I quantized the Openvino format, it couldn't detect anything.

I suspect it is because the ignore scope or the quantization data didn't set correctly. 

An example of ignore_scope from [here](https://docs.openvino.ai/2023.1/notebooks/230-yolov8-optimization-with-output.html) . 

```
ignored_scope = nncf.IgnoredScope(
    types=["Multiply", "Subtract", "Sigmoid"],  # ignore operations
    names=[
        "/model.22/dfl/conv/Conv",           # in the post-processing subgraph
        "/model.22/Add",
        "/model.22/Add_1",
        "/model.22/Add_2",
        "/model.22/Add_3",
        "/model.22/Add_4",
        "/model.22/Add_5",
        "/model.22/Add_6",
        "/model.22/Add_7",
        "/model.22/Add_8",
        "/model.22/Add_9",
        "/model.22/Add_10"
    ]
)


# Detection model
quantized_det_model = nncf.quantize(
    det_ov_model,
    quantization_dataset,
    preset=nncf.QuantizationPreset.MIXED,
    ignored_scope=ignored_scope
)
```
Given a model, how do I know what/which layers I should include in the ignore scope to maintain the detection accuracy/mAP?

```
import nncf  # noqa: F811
from typing import Dict


def transform_fn(data_item:Dict):
    """
    Quantization transform function. Extracts and preprocess input data from dataloader item for quantization.
    Parameters:
       data_item: Dict with data item produced by DataLoader during iteration
    Returns:
        input_tensor: Input data for quantization
    """
    input_tensor = det_validator.preprocess(data_item)['img'].numpy()
    return input_tensor

quantization_dataset = nncf.Dataset(det_data_loader, transform_fn)
```
For the `det_data_loader`, I was using a `list` containing image arrays `[image1 image2 image3 ...... ]`. Do I need to include mask? I prefer not to use dataloader from PyTorch or Tensorflow as the target device will not have these frameworks installed.

**Comment by alexsu52** [comment]
Hi @davidvct,

it's okay if you use a "list" of images as a calibration data set. The main thing is that the calibration data is representative and the size is sufficient (default is 300 images).

I kindly recomend to try nncf.quantize_with_accuracy_control(...) for your model. This method quantizes model with specified accuracy. The example for yolo8 segmentation model you can find here https://github.com/openvinotoolkit/nncf/tree/develop/examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control

**Comment by davidvct** [comment]
Thanks @alexsu52 for the py file!

I will try out the code and feedback if any issue.

**Comment by davidvct** [comment]
Hi @alexsu52 

I encountered the following error:

`AttributeError: 'YOLO' object has no attribute 'smart_load'`

I also posted the question here: https://github.com/ultralytics/ultralytics/issues/6021#issuecomment-1785389975

It seems that we need a `Model` class object in order to use `smart_load`, but I couldn't find it in main.py. Could you confirm?

**Comment by alexsu52** [comment]
Did you install requirements from the https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/openvino/yolov8_quantize_with_accuracy_control/requirements.txt?

**Comment by davidvct** [comment]
Hi, I re-installed the environment using your `requirements.txt`, and it seems to be able to run the quantization, and judging from the metrics, it seems to be able to predict well. 

I am still trying to understand how to apply it to my custom model, but a big thanks for the script :)

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions related to this topic.
