### ISSUE TITLE
ngraph::NodeValidationFailure when loading IR model

### ISSUE THREAD

**Issue by potatozrollin** [openvinotoolkit/openvino#2052]
Hi decided to open a new thread as the error is different from the NCS compiling issue I had. Would really appreciate if anyone can give some tips on the error!

@dkurt Sorry to disturb again but I seem to run into another error when trying to load the model via `net = cv2.dnn.readNet(xmlFile, binFile)`: 

```
terminate called after throwing an instance of 'ngraph::NodeValidationFailure'
  what():  Check 'window_dilated_dim <= data_padded_dilated_dim' failed at ngraph/core/src/validation_util.cpp:214:
While validating node 'v1::MaxPool MaxPool_11 (relu1_2[0]:f16{1,64,1,1}) -> (dynamic?)' with friendly_name 'MaxPool_11':
Window after dilation has dimension (dim: 2) larger than the data shape after padding (dim: 1) at axis 0.
```
I am trying to run an optimized model that was successfully converted from my pre-trained caffemodel using `py mo_caffe.py` on my windows machine.  May I know if you have seen such an error before?

```
C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\model_optimizer>py mo_caffe.py --input_model ~/hand/pose_iter_102000.caffemodel --input_proto ~/hand/pose_deploy.prototxt --output_dir ~/MV_HandKeyPointDetector/hand/
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      ~/hand/pose_iter_102000.caffemodel
        - Path for generated IR:        ~/hand/
        - IR output name:       pose_iter_102000
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP16
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       False
Caffe specific parameters:
        - Path to Python Caffe* parser generated from caffe.proto:      mo\front\caffe\proto
        - Enable resnet optimization:   True
        - Path to the Input prototxt:   ~/hand/pose_deploy.prototxt
        - Path to CustomLayersMapping.xml:      extensions\front\caffe\CustomLayersMapping.xml
        - Path to a mean file:  Not specified
        - Offsets for a mean file:      Not specified
Model Optimizer version:
Please expect that Model Optimizer conversion might be slow. You are currently using Python protobuf library implementation.
However you can use the C++ protobuf implementation that is supplied with the OpenVINO toolkitor build protobuf library from sources.
Navigate to "install_prerequisites" folder and run: python -m easy_install protobuf-3.5.1-py($your_python_version)-win-amd64.egg
set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp


 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #80.

[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: ~/hand/pose_iter_102000.xml
[ SUCCESS ] BIN file: ~/hand/pose_iter_102000.bin
[ SUCCESS ] Total execution time: 167.84 seconds.
```

(The caffemodel that I am using is from the hand detector model (102000) from openpose)

Thank you so much again!

**Comment by dkurt** [comment]
Please always specify source code commits hashes or libraries versions.

**Comment by manuiiitv** [comment]
@dkurt @potatozrollin @cepera @wistal @cpriebe 
Intel openvino version used in deployment setup openvino_2020.1.023.
Openvino engines for detection models created on Machine M1.

Deployment Setup 1 :: machine M2
Deployment Setup 2 :: machine M3

CPUs of machine M1, M2 and machine M3 are different.

Everything is same on Deployment setup machines like all the version of the dependencies required and openvino.

Engines generated on machine M1 gives different detections on Machine M2 and Machine M3 with binary generated from same code file written in cpp.

Any help in finding what could be the possible reasons for this?

Thanks in advance for your reply.

**Comment by potatozrollin** [comment]
> Please always specify source code commits hashes or libraries versions.
> 
> To localize the problem, try to load the model with native API:
> 
> ```python
> from openvino.inference_engine import IECore
> 
> ie = IECore()
> net = ie.read_network('pose_iter_102000.xml', 'pose_iter_102000.bin')
> ie.load_network(net, 'MYRIAD')
> ```

I have tried the native API and obtained the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ie_api.pyx", line 261, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 293, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Check 'window_dilated_dim <= data_padded_dilated_dim' failed at /home/jenkins/agent/workspace/private-ci/ie/build-linux-debian_9_arm/b/repos/openvino/ngraph/src/ngraph/validation_util.cpp:212:
While validating node 'v1::MaxPool MaxPool_11(Relu_10[0]:f32{1,64,1,1}) -> (dynamic?)':
Window after dilation has dimension (dim: 2) larger than the data shape after padding (dim: 1) at axis 0.


Intel openvino version used in deployment setup openvino_2020.4.287
For the conversion of models I used a windows machine using the openvino version of 2020.4.287 as well. Sorry, am new to this but hope the details are enough thank you! @dkurt

**Comment by potatozrollin** [comment]
I found my solution in https://github.com/openvinotoolkit/openvino/issues/1307 - thank you so much for your help :)
