### ISSUE TITLE
[Feature Request] Add a C API to Retrieve and Reset the Last Error Message

### ISSUE THREAD

**Issue by sdcb** [openvinotoolkit/openvino#20536]
### Request Description

In the OpenVINO C++ API, it is straightforward to use try-catch to obtain error messages. However, in the C API, the error messages are not as informative. Here's an example of how the error handling looks in C++:

```cpp
#include <openvino/openvino.hpp>

int main()
{
	try {
		ov::Core core;
		ov::CompiledModel compiled = core.compile_model(LR"~(C:\Users\ZhouJie\AppData\Roaming\paddleocr-models\ch_PP-OCRv4_det\inference2.pdmodel)~", "GPU");
	}
	catch (const std::exception& error) {
		std::cout << error.what() << std::endl;
	}
}
```

The error message might look like this(it's pretty obvious that it's caused by model incorrect):

```
Exception from C:\_\3rd\vcpkg\buildtrees\openvino\src\d109628fc6-fd5abe61db\src\inference\src\core.cpp:134:

C:\_\3rd\vcpkg\buildtrees\openvino\src\d109628fc6-fd5abe61db\src\inference\src\ie_network_reader.cpp:480 [ NETWORK_NOT_READ ] Unable to read the model: C:\Users\ZhouJie\AppData\Roaming\paddleocr-models\ch_PP-OCRv4_det\inference2.pdmodel Please check that model format: pdmodel is supported and the model is correct. Available frontends: ir paddle pytorch tflite
```

In contrast, an error message using the C API might look like this:

```cpp
#include <openvino/c/openvino.h>
#include <stdlib.h>

void Check(ov_status_e status)
{
	if (status != OK) {
		printf("Error: %d, Reason=%s\n", status, ov_get_error_info(status));
		exit(-1);
	}
}

int main()
{
	ov_core* core;
	Check(ov_core_create(&core));

	ov_compiled_model* compiled;
	Check(ov_core_compile_model_from_file_unicode(core, LR"~(C:\Users\ZhouJie\AppData\Roaming\paddleocr-models\ch_PP-OCRv4_det\inference2.pdmodel)~", "GPU", 0, &compiled));
}
```

With a typical output:

```
Error: -1, Reason=general error
```

(You can't tell the reason if you encountered this error)
This lack of useful error messages significantly weakens the functionality and debug capabilities when creating wrappers for other programming languages in OpenVINO, such as my C# wrapper (https://github.com/sdcb/OpenVINO.NET).

Below is an implementation of the `ov_get_and_reset_last_error()` function and the required modifications to the `CATCH_IE_EXCEPTION`, `CATCH_OV_EXCEPTION`, and `CATCH_OV_EXCEPTIONS` macros:

In a C API file:

```c
#include <openvino/c/openvino.h>
#include <string.h>

static thread_local char* last_error = NULL;

const char* ov_get_and_reset_last_error() {
    char* result = last_error;
    if (last_error != NULL) {
        free(last_error);
        last_error = NULL;
    }
    return result;
}

#define SET_LAST_ERROR(ExceptionType) \
    do { \
        const char* message = ExceptionType.what(); \
        if (last_error != NULL) free(last_error); \
        last_error = strdup(message); \
    } while (0)
```

Then, modify the `CATCH_IE_EXCEPTION`, `CATCH_OV_EXCEPTION`, and `CATCH_OV_EXCEPTIONS` macros like so:

```c
#define CATCH_IE_EXCEPTION(StatusCode, ExceptionType) \
    catch (const InferenceEngine::ExceptionType& e) { \
        SET_LAST_ERROR(e); \
        return ov_status_e::StatusCode; \
    }

#define CATCH_OV_EXCEPTION(StatusCode, ExceptionType) \
    catch (const ov::ExceptionType& e) { \
        SET_LAST_ERROR(e); \
        return ov_status_e::StatusCode; \
    }

#define CATCH_OV_EXCEPTIONS \
    CATCH_OV_EXCEPTION(NOT_IMPLEMENTED, NotImplemented) \
    CATCH_OV_EXCEPTION(GENERAL_ERROR, Exception) \
    CATCH_IE_EXCEPTION(GENERAL_ERROR, GeneralError) \
    CATCH_IE_EXCEPTION(NOT_IMPLEMENTED, NotImplemented) \
    CATCH_IE_EXCEPTION(NETWORK_NOT_LOADED, NetworkNotLoaded) \
    CATCH_IE_EXCEPTION(PARAMETER_MISMATCH, ParameterMismatch) \
    CATCH_IE_EXCEPTION(NOT_FOUND, NotFound) \
    CATCH_IE_EXCEPTION(OUT_OF_BOUNDS, OutOfBounds) \
    CATCH_IE_EXCEPTION(UNEXPECTED, Unexpected) \
    CATCH_IE_EXCEPTION(REQUEST_BUSY, RequestBusy) \
    CATCH_IE_EXCEPTION(RESULT_NOT_READY, ResultNotReady) \
    CATCH_IE_EXCEPTION(NOT_ALLOCATED, NotAllocated) \
    CATCH_IE_EXCEPTION(INFER_NOT_STARTED, InferNotStarted) \
    CATCH_IE_EXCEPTION(NETWORK_NOT_READ, NetworkNotRead) \
    CATCH_IE_EXCEPTION(INFER_CANCELLED, InferCancelled) \
    catch (...) { \
        if (last_error != NULL) free(last_error); \
        last_error = strdup("An unknown exception occurred"); \
        return ov_status_e::UNKNOW_EXCEPTION; \
    }
```

These modifications to the exception macros ensure that when an exception is caught, its message is captured and stored in the thread-local `last_error` string. Then, `ov_get_and_reset_last_error()` can be used to retrieve and clear this error message. This allows detailed error information to be propagated up to the C API level, providing valuable debugging information for wrappers written in other languages.

### Feature Use Case

To address this issue, I suggest adding a new C API method: `const char* ov_get_and_reset_last_error();`. This method should be implemented in a way that assigns a value to a thread-local `char*` string variable in the `CATCH_OV_EXCEPTIONS` macro definition, and it should return and reset the value of this variable. This would make error handling more informative and similar to the first-class treatment that C++ and Python enjoy, making it easier for developers to debug their applications.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by vurusovs** [comment]
@riverlijunjie @ilyachur @ilya-lavrenov please, take a look

**Comment by riverlijunjie** [comment]
ok, will take it.
