### ISSUE TITLE
[Good First Issue]: Align behavior of ONNX Frontend operator ReduceMin-11, 12, 13, 18, 20 with original framework

### ISSUE THREAD

**Issue by gkrivor** [openvinotoolkit/openvino#20557]
### Context

eural networks are graphs consisting of nodes called operators. Each operator corresponds to a mathematical function, usually described in framework's documentation or an AI standard, such as ONNX.
OpenVINO ONNX Frontend is a component responsible for working with ONNX graphs and requires implementation of different ONNX operators in order to use ONNX models.
This task requires alignment between OpenVINO ONNX Frontend and original framework implementations of ReduceMin for next list of opsets: [opset 11](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-11),  [opset 12](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-12),  [opset 13](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-13),  [opset 18](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-18),  [opset 20](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-20)
Necessary help will be provided by ONNX Fronted team.

### What needs to be done?

First of all, please, take a look on [ReduceMax](https://github.com/openvinotoolkit/openvino/pull/23475) PR for a reference.

Operator details can be found in [ONNX Operators](https://github.com/onnx/onnx/blob/main/docs/Operators.md#ReduceMin)
More details can be found in ONNX Changelog: [opset 11](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-11),  [opset 12](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-12),  [opset 13](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-13),  [opset 18](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-18),  [opset 20](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceMin-20)
1. Operator already has a common implementation in OpenVINO. First of all, you need to review a documentation and prepare a table with differences between versions. It could be, for instance, a missing property, extended/reduced coverage of existing property, etc...
2. Copy existing implementation [here](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op) to make it aligned with original framework (extend or reduce coverage of a common implementation). Copy of modified implementation should be in a defined opset, or in opset 1 in case it implements oldest implementation. [Example of multi-opset operation](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/softmax.cpp#L50).
3. Register the function in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560) while keeping alphabetical order
4. Create test model(s) in [ONNX models directory](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/tests/models/). OpenVINO test infrastructure then converts prototxt files to ONNX models - you will use those models later in tests
5. Add tests covering all use cases [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import.in.cpp)
6. Check [Python xfailed tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/tests_python/test_backend.py) to find a test marked as a xfailed for added functionality. If any exist - remove corresponding lines and try to verify by using cmdline "python -m pytest -k name_of_test".
More details in [adding operators to ONNX Frontend guide](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md)

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [User documentation](https://docs.openvino.ai/)
- Guides on [ONNX Frontend architecture](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/architecture.md) and [ONNX Frontend tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/tests.md) are also available
- You can also see a [blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

### Contact points

@gkrivor

**Comment by salmanra** [comment]
.take

**Comment by salmanra** [comment]
@gkrivor 

1. I have set up [a table](https://docs.google.com/spreadsheets/d/1cagXu0agZlseDv6Hy3HrsKfEwB1kl4WlrH4bNnMauSU/edit?usp=sharing) detailing the difference between the different ONNX Opsets' ReduceMin operators. 
2. It seems that [reduce.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/reduce.cpp) has most of the necessary logic supporting the differences between each version of this operator (barring varied support for tensor types). Therefore, should I define namespaces for each of the opsets 11, 12, 13, 18, and 20, and make sure they call make_ng_reduction_op with the proper parameters? Additionally, how do we specify supported types for the input and output tensors? Right now, the common impl of ReduceMin uses a set defined in [element_type.hpp](https://github.com/openvinotoolkit/openvino/blob/master/src/core/include/openvino/core/type/element_type.hpp). Do we want to define different sets of element types corresponding to those supported by each ONNX opset?
3. I haven't figured out how to register a function in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560). Do we register each version of ReduceMin? Or do we register ReduceMin exactly once regardless of how many different opsets it appears in?

**Comment by p-wysocki** [comment]
Hello @salmanra, sorry for the late reply, the holiday season just ended. :) @gkrivor could you please take a look?

Also, I am happy to announce that we have created a channel dedicated to Good First Issues support on our [Intel DevHub Discord server](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by gkrivor** [comment]
@salmanra sorry for the delay.
1. Great! You've identified difference correct, especially important one - axes as an input instead of attribute
2. Yep, you are right, most of logic is available and should be re-used. Yes, translators should be placed in a separate namespaces. No, you don't need to define some additional types, just use existing list.
3. Yes, in should be registered for each opset.

**Comment by p-wysocki** [comment]
Hello @salmanra, are you still working on that issue?

**Comment by salmanra** [comment]
@p-wysocki Hi, apologies, work has been busy, and I am transitioning from work to starting a PhD later this Summer. 

Best for me would be to drop this issue and pick up a new one sometime in April or May.

**Comment by mlukasze** [comment]
No problem at all!
Have a nice time and we will wait for you in April :)

**Comment by YaritaiKoto** [comment]
.take
