### ISSUE TITLE
[Good First Issue]: Extend ONNX Frontend with Function Mish-18

### ISSUE THREAD

**Issue by gkrivor** [openvinotoolkit/openvino#20550]
### Context

Neural networks are graphs consisting of nodes called operators. Each operator corresponds to a mathematical function, usually described in framework's documentation or an AI standard, such as ONNX.
OpenVINO ONNX Frontend is a component responsible for working with ONNX graphs and requires implementation of different ONNX operators in order to use ONNX models.
This task requires extending OpenVINO ONNX Frontend with Function Mish.
Necessary help will be provided by ONNX Fronted team.

### What needs to be done?

Operator details can be found in [ONNX Operators](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Mish)
More details can be found in [ONNX Changelog](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Mish-18)
1. Create `.hpp` and `.cpp` files [here](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op)
2. Prepare an implementation of this operator in form of a function. Mish-18 should be placed in [opset 1 namespace](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/unique.hpp#L13).
3. Register the function in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L554-L560) while keeping alphabetical order
4. Create test model(s) in [ONNX models directory](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/tests/models/). OpenVINO test infrastructure then converts prototxt files to ONNX models - you will use those models later in tests
5. Add tests covering all use cases [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import.in.cpp)
6. Check [Python xfailed tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/tests_python/test_backend.py) to find a test marked as a xfailed for added functionality. If any exist - remove corresponding lines and try to verify by using cmdline "python -m pytest -k name_of_test".
More details in [adding operators to ONNX Frontend guide](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md)

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/15076
- https://github.com/openvinotoolkit/openvino/pull/14936
- https://github.com/openvinotoolkit/openvino/pull/12510
- https://github.com/openvinotoolkit/openvino/pull/19428

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- Guides on [ONNX Frontend architecture](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/architecture.md) and [ONNX Frontend tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/tests.md) are also available
- You can also see a [blog post on contributing to OpenVINO](https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e)

### Contact points

@gkrivor

**Comment by urbalke** [comment]
Hello, why do You have *Windows in 1st ToDo? Is this platform specific?

**Comment by ilya-lavrenov** [comment]
> Hello, why do You have *Windows in 1st ToDo? Is this platform specific?

No, OpenVINO is cross platform product and steps are the same for all the systems.
Corrected description.

**Comment by sydarb** [comment]
Hey @p-wysocki I would like to work on this.

**Comment by p-wysocki** [comment]
Hello @sydarb, are you still working on this? I see that the PR is nearly finished.

Also, I am happy to announce that we have created a channel dedicated to Good First Issues support on our [Intel DevHub Discord server](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by kshitij01042002** [comment]
Hi @p-wysocki is this issue up for grab? Also I tried joining the discord channel via the link provided but it says invalid link, can you please double check? Thanks.

**Comment by p-wysocki** [comment]
Hi @kshitij01042002, you can pick it up, thanks for taking a look!

The correct Discord link is https://discord.com/invite/7pVRxUwdWG, it has been corrected everywhere but in the issues created before we realized that the link is dead. Sorry for that! :)

**Comment by PRATHAM-SPS** [comment]
Hi @p-wysocki , it's nice to see you again! Could you please assign me this task?  I'd like to do it.

**Comment by kshitij01042002** [comment]
Hi @p-wysocki I am currently working on #20562. You can assign it to @PRATHAM-SPS

**Comment by PRATHAM-SPS** [comment]
Hello , please review the pull request I've created at the following link:-https://github.com/openvinotoolkit/openvino/pull/22833. Your feedback would be greatly appreciated, @gkrivor and  @p-wysocki.

**Comment by mitruska** [comment]
Hello @PRATHAM-SPS, thank you for this contribution.
I've reviewed the mentioned PR https://github.com/openvinotoolkit/openvino/pull/22833, please take a look at the comments there.

**Comment by PRATHAM-SPS** [comment]
Hello @p-wysocki,  can I get more such operators to wotk on  ??

**Comment by PRATHAM-SPS** [comment]
Thankyou , @p-wysocki  and  @mitruska , I've taken responsibility for this task.
