### ISSUE TITLE
[Good First Issue]: Support aten::erfc for pytorch models

### ISSUE THREAD

**Issue by mvafin** [openvinotoolkit/openvino#20577]
### Context

OpenVINO component responsible for support of PyTorch models is called as PyTorch Frontend (PT FE). PT FE converts a model represented as TorchScript model to a model in [OpenVINO opset](https://docs.openvino.ai/latest/openvino_docs_ops_opset.html).

### What needs to be done?

- Implement conversion rule and/or transformation to support the new operation.
- Implement operation tests in tests/layer_tests/pytorch_tests. Please consider different data types, but keep reasonable number of test cases

### Example Pull Requests

#18998

### Resources

- [torch.erfc description](https://pytorch.org/docs/stable/generated/torch.erfc.html)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO PyTorch Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/pytorch/README.md)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-pytorch-frontend-maintainers 

### Ticket

TBD

**Comment by ahmadchalhoub** [comment]
`.take`

**Comment by p-wysocki** [comment]
Hello @ahmadchalhoub, thanks for taking a look! Please let us know if you have any questions or need any help. :)

You can use our WIP roadmap for contributors at https://github.com/openvinotoolkit/openvino/pull/21322, if you do - please let us know if it helped and give us any feedback on how it could be improved. :)
