### ISSUE TITLE
[Good First Issue]: Support aten::gcd for pytorch models

### ISSUE THREAD

**Issue by mvafin** [openvinotoolkit/openvino#20580]
### Context

OpenVINO component responsible for support of PyTorch models is called as PyTorch Frontend (PT FE). PT FE converts a model represented as TorchScript model to a model in [OpenVINO opset](https://docs.openvino.ai/latest/openvino_docs_ops_opset.html).

### What needs to be done?

- Implement conversion rule and/or transformation to support the new operation.
- Implement operation tests in tests/layer_tests/pytorch_tests. Please consider different data types, but keep reasonable number of test cases

### Example Pull Requests

#18998

### Resources

- [torch.gcd description](https://pytorch.org/docs/stable/generated/torch.gcd.html)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO PyTorch Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/pytorch/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-pytorch-frontend-maintainers 

### Ticket

TBD

**Comment by karanjakhar** [comment]
hi @mvafin @ilya-lavrenov  I would like to work on this.

**Comment by karanjakhar** [comment]
Hi @mvafin @ilya-lavrenov ,
I would appreciate your help. I have implemented it here: https://github.com/karanjakhar/openvino/blob/issue_20580/src/frontends/pytorch/src/op/gcd.cpp
I have written the tests and I am getting below output when I am running tests:
![Screenshot from 2023-10-30 09-54-21](https://github.com/openvinotoolkit/openvino/assets/29913676/57291861-13b9-485d-845f-293d372ad424)
![Screenshot from 2023-10-30 09-55-01](https://github.com/openvinotoolkit/openvino/assets/29913676/ea784af8-cff7-4521-8d39-fba26c075078)

I am using the Euclidean algorithm for finding gcd. Please guide me on where I should look and what I can try.

**Comment by mvafin** [comment]
Hi @karanjakhar,
I looked into your code and I see you use input type to create `Constant`:
https://github.com/karanjakhar/openvino/blob/af5c909a7723721ad9a3ba263b9a42417a93e14a/src/frontends/pytorch/src/op/gcd.cpp#L32
That will not work in majority of cases, because type of input is not known and is `ov::element::dynamic`, so `Constant` can't be created with this type. You need to create it with some static and reasonable type and if needed convert it using `ConvertLike`

**Comment by p-wysocki** [comment]
Hi @karanjakhar, are you still working on this issue or can I return it to be picked up by other contributors?

**Comment by karanjakhar** [comment]
Hi @p-wysocki , 
I am still working on this. I was on leave for a festival. I have implemented it, but there is some error. I will resolve it soon. 
Sorry for the delay.

**Comment by p-wysocki** [comment]
Hello @karanjakhar, is there anything we can help you with?

**Comment by karanjakhar** [comment]
Hi @p-wysocki ,
I need help. https://github.com/karanjakhar/openvino/blob/issue_20580/src/frontends/pytorch/src/op/gcd.cpp
This is the current implementation and tests: https://github.com/karanjakhar/openvino/blob/issue_20580/tests/layer_tests/pytorch_tests/test_gcd.py
 I am getting:  
 
![Screenshot from 2023-12-09 00-38-26](https://github.com/openvinotoolkit/openvino/assets/29913676/4bc0318f-1520-4e17-b3c3-b64291f77fdb)
![Screenshot from 2023-12-09 00-38-12](https://github.com/openvinotoolkit/openvino/assets/29913676/be258952-767a-4afd-9094-67ca76eb5f57)
![Screenshot from 2023-12-09 00-37-47](https://github.com/openvinotoolkit/openvino/assets/29913676/be4073f9-4826-423e-bb28-e755ac7043c4)
![Screenshot from 2023-12-09 00-37-26](https://github.com/openvinotoolkit/openvino/assets/29913676/9a0245c9-9290-42cf-a084-276c0ca742a2)

Please point me in the right direction.   
Thanks

**Comment by p-wysocki** [comment]
@openvinotoolkit/openvino-pytorch-frontend-maintainers could you please take a look?

**Comment by p-wysocki** [comment]
@mvafin

**Comment by mvafin** [comment]
@karanjakhar I checked your code, looks like you didn't return the condition from the body.
With the code `loop->set_special_body_ports({-1, 0});` you specify that 0 output from body is condition, but in fact 0-output from body is `new_x`, so you just need to add the condition output.
After that there will be an issue that `condition` is not a scalar, so you would need to reduce it to boolean scalar.
However the scalar case will still not work, because `new_x` output from body have `[1]` shape while `x` input has `[0]` shape, because of that merged input shape cannot be determined, to fix that you need to make `zero` constant have `[0]` shape instead of `[1]`.

**Comment by karanjakhar** [comment]
Hi @mvafin ,
I want to understand it in depth. What resources would you recommend? Any book? or link? 
So far I am using this https://docs.openvino.ai/2023.2/openvino_docs_ops_infrastructure_Loop_5.html 
Are there any other resources?

Thanks :)

**Comment by p-wysocki** [comment]
Thank you for your contribution @karanjakhar!

I am happy to announce that we have created a channel dedicated to Good First Issues support on our [Intel DevHub Discord server](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by karanjakhar** [comment]
@p-wysocki Nice!! 
Thanks
