### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [openvinotoolkit/openvino#206]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [DIR](https://github.com/opencv/dldt/blob/b235c73481a6f133e1d182d91e5e2c29e8a460e5/inference-engine/samples/common/os/windows/w_dirent.h#L73 "Destructor for DIR")
- [mkldnn_primitive_desc_iterator](https://github.com/opencv/dldt/blob/b235c73481a6f133e1d182d91e5e2c29e8a460e5/inference-engine/thirdparty/mkl-dnn/src/common/primitive_iterator.hpp#L37 "Destructor for mkldnn_primitive_desc_iterator")
- [mkldnn_primitive_destroy](https://github.com/opencv/dldt/blob/b235c73481a6f133e1d182d91e5e2c29e8a460e5/inference-engine/thirdparty/mkl-dnn/src/common/primitive.cpp#L82 "mkldnn_primitive_destroy function")

**Comment by shubha-ramani** [comment]
Dear @elfring 
You bring up a valid point and it's currently being discussed by OpenVino developers.

Thanks !

Shubha

**Comment by elfring** [comment]
How do you think about to [improve any remaining source code places](https://github.com/openvinotoolkit/openvino/blob/ec3283ebe1dd4ee3b76f21fb9994d1da8b077154/src/bindings/c/src/ie_c_api.cpp#L266 "Update candidate: ie_param_free()") according to the mentioned transformation pattern?
