### ISSUE TITLE
multi_camera_multi_target_tracking_demo crushes on start

### ISSUE THREAD

**Issue by MoscowskyAnton** [openvinotoolkit/openvino#20623]
Hello!
I am trying to launch multi_camera_multi_target_tracking_demo with following command:
```
python3 multi_camera_multi_target_tracking_demo.py     -i 0 2     --m_detector intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml     --m_reid intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml
```

But it throws this:
```
[ DEBUG ] Reading config from /home/anton/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/configs/person.py
[ INFO ] OpenVINO Runtime
[ INFO ]        build: 2023.1.0-12185-9e6b00e51cd-releases/2023/1
[ INFO ] Reading Object Detection model intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml
[ INFO ] The Object Detection model intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml is loaded to CPU
[ INFO ] Reading Object Reidentification model intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml
Traceback (most recent call last):
  File "multi_camera_multi_target_tracking_demo.py", line 284, in <module>
    sys.exit(main() or 0)
  File "multi_camera_multi_target_tracking_demo.py", line 276, in main
    object_recognizer = VectorCNN(core, args.m_reid, args.device)
  File "/home/anton/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py", line 113, in __init__
    super().__init__(core, model_path, device, 'Object Reidentification', self.max_reqs)
  File "/home/anton/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/utils/ie_tools.py", line 25, in __init__
    self.load_model(core, model_path, device, model_type, num_reqs)
  File "/home/anton/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/utils/ie_tools.py", line 76, in load_model
    compiled_model = core.compile_model(self.model, device)
  File "/home/anton/.local/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/core.cpp:114:
[ GENERAL_ERROR ] label is too far
```

Any ideas this comes from and how to fix that?
Using python OpenVIVO ver. 2023.1.0-12185-9e6b00e51cd-releases/2023/1 on Kubuntu 20.04
Thanks!

**Comment by wenjiew** [comment]
@MoscowskyAnton Please let us know whether the latest model fixes this issue. Thanks!

**Comment by MoscowskyAnton** [comment]
Hi! Sorry for the late answer, was in hospital.
I tried to download that model, and running command you posted, but error seems the same
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/anton/.local/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/core.cpp:131:
[ GENERAL_ERROR ] label is too far
```

**Comment by peterchen-intel** [comment]
`
python3 -m venv test_py
source  test_py/bin/activate
pip install openvino==2023.1.0
`
`$ md5sum person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.*
01c85d68d7174c243071a2b261fd2aa7  person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.bin
0bf91ab497f4e405265c5f9174420983  person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml
`
python3 -c "import openvino.runtime as ov; ov.Core().compile_model('./person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml', 'CPU')"
`$ benchmark_app -d CPU -m ./person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2023.1.0-12185-9e6b00e51cd-releases/2023/1
[ INFO ] 
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2023.1.0-12185-9e6b00e51cd-releases/2023/1
[ INFO ] 
[ INFO ] 
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to PerformanceMode.THROUGHPUT.
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 45.48 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Model inputs:
[ INFO ]     data (node: data) : f32 / [N,C,H,W] / [1,3,256,128]
[ INFO ] Model outputs:
[ INFO ]     reid_embedding (node: reid_embedding) : f32 / [...] / [1,256]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Model batch size: 1
[Step 6/11] Configuring input of the model
[ INFO ] Model inputs:
[ INFO ]     data (node: data) : u8 / [N,C,H,W] / [1,3,256,128]
[ INFO ] Model outputs:
[ INFO ]     reid_embedding (node: reid_embedding) : f32 / [...] / [1,256]
[Step 7/11] Loading the model to the device
[ INFO ] Compile model took 452.92 ms
[Step 8/11] Querying optimal runtime parameters
[ INFO ] Model:
[ INFO ]   NETWORK_NAME: torch-jit-export
[ INFO ]   OPTIMAL_NUMBER_OF_INFER_REQUESTS: 12
[ INFO ]   NUM_STREAMS: 12
[ INFO ]   AFFINITY: Affinity.CORE
[ INFO ]   INFERENCE_NUM_THREADS: 36
[ INFO ]   PERF_COUNT: False
[ INFO ]   INFERENCE_PRECISION_HINT: <Type: 'float32'>
[ INFO ]   PERFORMANCE_HINT: PerformanceMode.THROUGHPUT
[ INFO ]   EXECUTION_MODE_HINT: ExecutionMode.PERFORMANCE
[ INFO ]   PERFORMANCE_HINT_NUM_REQUESTS: 0
[ INFO ]   ENABLE_CPU_PINNING: True
[ INFO ]   SCHEDULING_CORE_TYPE: SchedulingCoreType.ANY_CORE
[ INFO ]   ENABLE_HYPER_THREADING: False
[ INFO ]   EXECUTION_DEVICES: ['CPU']
[ INFO ]   CPU_DENORMALS_OPTIMIZATION: False
[ INFO ]   CPU_SPARSE_WEIGHTS_DECOMPRESSION_RATE: 1.0
[Step 9/11] Creating infer requests and preparing input tensors
[ WARNING ] No input files were given for input 'data'!. This input will be filled with random values!
[ INFO ] Fill input 'data' with random values 
[Step 10/11] Measuring performance (Start inference asynchronously, 12 inference requests, limits: 60000 ms duration)
[ INFO ] Benchmarking in inference only mode (inputs filling are not included in measurement loop).
[ INFO ] First inference took 21.53 ms`

**Comment by MoscowskyAnton** [comment]
@peterchen-intel  thanks for your reply, i did every step as you mention, but still get the same when compile model

```
(test_py) anton@anton:~/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/intel$ md5sum person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.*
01c85d68d7174c243071a2b261fd2aa7  person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.bin
0bf91ab497f4e405265c5f9174420983  person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml

(test_py) anton@anton:~/Projects/open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/intel$ python3 -c "import openvino.runtime as ov; ov.Core().compile_model('./person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml', 'CPU')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/anton/test_py/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/core.cpp:131:
[ GENERAL_ERROR ] label is too far
```

**Comment by peterchen-intel** [comment]
@MoscowskyAnton What is your CPU model? Can you run lscpu and give the output?

**Comment by MoscowskyAnton** [comment]
@peterchen-intel sorry for long answer, sir

`Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      36 bits physical, 48 bits virtual
CPU(s):                             8
On-line CPU(s) list:                0-7
Thread(s) per core:                 2
Core(s) per socket:                 4
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              58
Model name:                         Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Stepping:                           9
CPU MHz:                            1778.081
CPU max MHz:                        3900,0000
CPU min MHz:                        1600,0000
BogoMIPS:                           6800.11
Virtualization:                     VT-x
L1d cache:                          128 KiB
L1i cache:                          128 KiB
L2 cache:                           1 MiB
L3 cache:                           8 MiB
NUMA node0 CPU(s):                  0-7
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        KVM: Vulnerable
Vulnerability L1tf:                 Mitigation; PTE Inversion
Vulnerability Mds:                  Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:             Mitigation; PTI
Vulnerability Mmio stale data:      Unknown: No mitigations
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS No
                                    t affected
Vulnerability Srbds:                Vulnerable: No microcode
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr
                                     sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtop
                                    ology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16
                                     xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm 
                                    cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
                                     xsaveopt dtherm ida arat pln pts md_clear flush_l1d
`

**Comment by peterchen-intel** [comment]
@MoscowskyAnton I suspect this issue may relate to this old CPU, do you have a newer SKU to try?
I found only "Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz" with Ubuntu 20.04.6 LTS, and couldn't reproduce the issue.
The previous CPU i used is "Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz"

**Comment by MoscowskyAnton** [comment]
On other CPU everything is works, but is it expected behavior for same video? 
![Screenshot_20231204_130106](https://github.com/openvinotoolkit/openvino/assets/49156277/4ec20185-bd6e-4abe-a9f2-282b72d4523a)
Everyone matched wrong
Used command
```
python3 multi_camera_multi_target_tracking_demo.py -i /home/anton/Videos/XI_Luckash.mp4 /home/anton/Videos/XI_Luckash.mp4 --m_detector intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml     --m_reid intel/person-reidentification-retail-0277/FP32/person-reidentification-retail-0277.xml --config configs/person.py 
```

**Comment by Wovchena** [comment]
That happens. Neural networks are just approximators. You can try running on iGPU. If the results are similar, there's nothing to fix in OpenVINO about it.

**Comment by xipingyan** [comment]
Hi @MoscowskyAnton , 
Could you please check if you have correct OpenVINO.
For example:
```
import openvino.runtime as ov
ov.get_version()
```
BTW, solving this problem depends on two PRs: https://github.com/openvinotoolkit/openvino/pull/21534 + https://github.com/openvinotoolkit/openvino/pull/21455.

**Comment by chenhu-wang** [comment]
fix is merged to master, https://github.com/openvinotoolkit/openvino/pull/21534

**Comment by xipingyan** [comment]
Hi @MoscowskyAnton , the fix has been merged to master, have you tried it? if you verify pass, could you please help close this issue?

**Comment by MoscowskyAnton** [comment]
Well when build I faced next error:

```
/home/anton/Lib/openvino/src/bindings/python/src/compatibility/pyngraph/node.cpp: In member function ‘virtual std::shared_ptr<ov::Node> PyNode::clone_with_new_inputs(const OutputVector&) const’:
/home/anton/Lib/openvino/src/bindings/python/src/compatibility/pyngraph/node.cpp:23:61: error: expected primary-expression before ‘,’ token
   23 |         PYBIND11_OVERRIDE_PURE(std::shared_ptr<ngraph::Node>, ngraph::Node, clone_with_new_inputs, inputs);
      |                                                             ^
/home/anton/Lib/openvino/src/bindings/python/src/compatibility/pyngraph/node.cpp:23:75: error: expected primary-expression before ‘,’ token
   23 |         PYBIND11_OVERRIDE_PURE(std::shared_ptr<ngraph::Node>, ngraph::Node, clone_with_new_inputs, inputs);
      |                                                                           ^
/home/anton/Lib/openvino/src/bindings/python/src/compatibility/pyngraph/node.cpp:23:9: error: ‘PYBIND11_OVERRIDE_PURE’ was not declared in this scope; did you mean ‘PYBIND11_OVERLOAD_PURE’?
   23 |         PYBIND11_OVERRIDE_PURE(std::shared_ptr<ngraph::Node>, ngraph::Node, clone_with_new_inputs, inputs);
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         PYBIND11_OVERLOAD_PURE

```

**Comment by xipingyan** [comment]
Because your demo is based on python, so the command(I suggested) enables python on.
Please refer: https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_linux.md, **Additional Build Options** part,  and then **To build the OpenVINO Runtime Python API:**.
`pip install -r requirements-dev.txt`

You also can check your build log, maybe you can find some tips. 

BTW, python ENV is complex, python virtual env is better in order to avoid some ENV exceptions.

**Comment by MoscowskyAnton** [comment]
Yup, that WAS already installed

**Comment by peterchen-intel** [comment]
@MoscowskyAnton  
You can try pip install openvino-nightly without build openvino yourself.

**Comment by MoscowskyAnton** [comment]
@peterchen-intel  that does the trick, errors are gone!
