### ISSUE TITLE
[Feature request] Improve the handling of return values for ov_infer_request_wait_for C API function 

### ISSUE THREAD

**Issue by sdcb** [openvinotoolkit/openvino#20684]
### Request Description

Currently, the handling of return values for the ov_infer_request_wait_for function in the OpenVINO C API does not seem to reflect the actual status of the inference request. Regardless of whether an inference request is completed or not, this function returns `ov_status_e::OK` (i.e., "0" or "success").

Please find the minimal reproducible code snippet below:

```cpp
#include <openvino/openvino.hpp>
#include <openvino/c/openvino.h>

int main()
{
    ov_core_t* core = nullptr;
    ov_core_create(&core);
    
    ov_compiled_model_t* compiled = nullptr;
    ov_core_compile_model_from_file_unicode(core, L"C:\\path_to_your_model\\model.onnx", "CPU", 0, &compiled);
    
    ov_infer_request_t* ir = nullptr;
    ov_compiled_model_create_infer_request(compiled, &ir);
    
    int64_t dims[] = { 1,3,960,960 };
    ov_shape_t shape = { 4, dims };

    ov_tensor_t* input_tensor = nullptr;
    ov_tensor_create(F32, shape, &input_tensor);
    ov_infer_request_set_input_tensor(ir, input_tensor);
    ov_infer_request_start_async(ir);

    ov_status_e st1 = ov_infer_request_wait_for(ir, 1);
    printf("C IR wait_for(1ms) ov_status_e: %d, reason=%s\n", st1, ov_get_error_info(st1));

    ov_status_e st2 = ov_infer_request_wait_for(ir, 10000);
    printf("C IR wait_for(10_000ms) ov_status_e: %d, reason=%s\n", st2, ov_get_error_info(st2));

    return 0;
}
```

Please update `"C:\\path_to_your_model\\model.onnx"` to a model of your choosing. 

In the output, no matter if the inference is accomplished or not, `ov_infer_request_wait_for()` always returns `ov_status_e::OK` ("0" or "success"): 

```
C IR wait_for(1ms) ov_status_e: 0, reason=success
C IR wait_for(10_000ms) ov_status_e: 0, reason=success
```

This does not accurately represent the outcome of inference process.

The current behavior is observed in the following function, located at `C:\_\3rd\vcpkg\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\bindings\c\src\ov_infer_request.cpp`:
```cpp
ov_status_e ov_infer_request_wait_for(ov_infer_request_t* infer_request, const int64_t timeout) {
    if (!infer_request) {
        return ov_status_e::INVALID_C_PARAM;
    }

    try {
        infer_request->object->wait_for(std::chrono::milliseconds(timeout));
    }
    CATCH_OV_EXCEPTIONS

    return ov_status_e::OK;
}
```
In this function, the return value of the `wait_for` function call is ignored. However, this return value is significant because it can indicate whether or not the inference request is completed. 

I suggest introducing a new `ov_status_e` enumeration value, or utilizing existing ones (for instance, `RESULT_NOT_READY` or `REQUEST_BUSY`) to provide more informative feedback about the status of the inference request. This could help users to better handle different scenarios with their inference requests.

### Feature Use Case

As a user, when performing asynchronous inference using the C API, I need to confirm whether the inference is completed. If the `ov_infer_request_wait_for` function does not accurately reflect the actual status of the inference request execution, it can cause ambiguities or even lead to incorrect handling decisions. 

For example, the lack of differentiation between a successfully completed inference, an unsuccessful inference, and a still on-going inference request can lead to inefficient resource allocation, or can lead a user to prematurely handle results. 

Given a more informative return value, users can write more robust and efficient code. For example:

```cpp
ov_status_e status = ov_infer_request_wait_for(ir, 10000);
if(status == ov_status_e::OK){
    /* Handle successful case */
} else if(status == ov_status_e::RESULT_NOT_READY){
    /* Retry or handle accordingly */
} else if(status == ov_status_e::REQUEST_BUSY){
    /* Retry or handle accordingly */
}
``` 

Thank you and looking forward to seeing this improvement in the upcoming version of OpenVINO.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by riverlijunjie** [comment]
C API is a wrapper of C++ API, we can see the definition of C++ API:

```
    /**
     * @brief Waits for the result to become available. Blocks until the specified timeout has elapsed or the result
     * becomes available, whichever comes first.
     *
     * @param timeout Maximum duration, in milliseconds, to block for.
     * @return True if inference request is ready and false, otherwise.
     */
    bool wait_for(const std::chrono::milliseconds timeout);
```

It returns boolean value - true or false, only some exception will be thrown, so for current C++ API, we cannot support to return some status, such as RESULT_NOT_READY or REQUEST_BUSY.
@ilya-lavrenov  do we have plan to support wait_for()/wait() return above status for C++ API?

**Comment by sdcb** [comment]
Hi @riverlijunjie , actually I don't necessary want return RESULT_NOT_READY and REQUEST_BUSY, but c api must indicates the status is success or not.
