### ISSUE TITLE
Accuracy issue of face recognition model after conversion to IR

### ISSUE THREAD

**Issue by sabrinasst** [openvinotoolkit/openvino#20693]
Hello community,

I am encountering an issue while attempting to convert my custom ONNX model to an OpenVINO representation.

Description:

I conducted tests on my custom ONNX model for face recognition and obtained the correct results. However, when I attempted to convert this ONNX model into an intermediate OpenVINO representation, I ended up with incorrect results.

I'm uncertain about the exact nature of the problem. Below,
 you can find the details of my custom ONNX model.

[arcface_mobilefacenet.zip](https://github.com/openvinotoolkit/openvino/files/13166131/arcface_mobilefacenet.zip)

I kindly request your assistance in resolving this issue. Thank you.

**Comment by andrei-kochin** [comment]
Hello @sabrinasst, thank you for contacting us!

Could you please share with us some script which you've used to check inference results?
Thank you

**Comment by andrei-kochin** [comment]
@sabrinasst do you have any updates for us?

**Comment by avitial** [comment]
Closing this. Feel free to reopen and provide additional information or ask any questions related to this topic.
