### ISSUE TITLE
[Feature Request]: BENCHMARK FOR YOLOV8 IN RASPBERRY PI 3,4,5

### ISSUE THREAD

**Issue by Rasantis** [openvinotoolkit/openvino#20753]
### Request Description

Hello, i didn´t find in the docs some kind of benchmark in the performance of yolov8, with and without using the openvino optimization ! if you guys could test and give us some kind of benchmark of performance in machines with gpu, cpus, both, raspberry pis.... would be very helpfull, thanks, and congrats, openvino its amazing !

### Feature Use Case

better docs and benchmark about the power of openvino in computer vision in diferent machines

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by vurusovs** [comment]
@Rasantis hello, thank you for your interest in OpenVINO!

Could you take a look at https://docs.openvino.ai/2023.1/openvino_docs_performance_benchmarks.html# ?

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions related to this topic.
