### ISSUE TITLE
[Feature Request]: attention operator support?

### ISSUE THREAD

**Issue by fengyuentau** [openvinotoolkit/openvino#20850]
### Request Description

Hi, I took a lookt at the [openvino documentation about operators](https://docs.openvino.ai/2023.1/openvino_docs_ops_opset12.html) and did not find an attention operator. So my question is, do you plan to add such as thing like https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Attention? I think running the attention subgraph as a single operator with optimization can be much faster.

### Feature Use Case

vit-based models.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by mlukasze** [comment]
hey @fengyuentau 
let us take a look and compare it against our roadmap for model enabling.
do you need it for personal or professional reasons?

**Comment by fengyuentau** [comment]
I was wondering whether I can support it as a single operation for the openvino backend in opencv dnn: https://github.com/opencv/opencv/pull/24476.

**Comment by mlukasze** [comment]
There is always an option to use extension API, please read more here: 
https://docs.openvino.ai/2023.1/openvino_docs_Extensibility_UG_add_openvino_ops.html

**Comment by fengyuentau** [comment]
> There is always an option to use extension API, please read more here: https://docs.openvino.ai/2023.1/openvino_docs_Extensibility_UG_add_openvino_ops.html

Ok, good to know that. So is this in your roadmap?

**Comment by mlukasze** [comment]
It's a big roadmap, I need a little more time to confirm it ;)
In the meantime I can recommend to make yourself familiar with Extension API :)
