### ISSUE TITLE
openvino supports IR/onnx/pdpd，much looking forward to support Encry_onnx, such as bytes serialization

### ISSUE THREAD

**Issue by brilliant-soilder** [openvinotoolkit/openvino#20851]
### Context

openvino supports IR and onnx, but when it comes to Encrypt, I find only encryed IR was supported, How does encryed_onnx was supported to read_model or compile_model to infer?
openvino supports IR/onnx/pdpd，much looking forward to support Encry_onnx, such as bytes serialization, or the new API 2022 have already supports yet?

### What needs to be done?

my advice is gave APi for Encryed_onnx to be compiled, such as serialized bytes

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

someone trying to use encryed onnx bytes

**Comment by andrei-kochin** [comment]
@brilliant-soilder could you please share some example of that encrypted model and the way users can get the original ONNX model encrypted?

**Comment by ilya-lavrenov** [comment]
Hi @brilliant-soilder 
I suppose you have looked at https://docs.openvino.ai/2023.1/openvino_docs_OV_UG_protecting_model_guide.html, where it's demonstrated how to work with encrypted IR models, but actually any files format can be encrypted / decrypted using this approach. 

The tricky case is when model stores its weights in external files, because you cannot pass `weights` as a `ov::Tensor` to `read_model`.

**Comment by brilliant-soilder** [comment]
> Hi @brilliant-soilder I suppose you have looked at https://docs.openvino.ai/2023.1/openvino_docs_OV_UG_protecting_model_guide.html, where it's demonstrated how to work with encrypted IR models, but actually any files format can be encrypted / decrypted using this approach.
> 
> The tricky case is when model stores its weights in external files, because you cannot pass `weights` as a `ov::Tensor` to `read_model`.

It works. Thanks a lot for your advice!

**Comment by p-wysocki** [comment]
Hi! Has this issue been resolved? If yes, can we close it?

**Comment by brilliant-soilder** [comment]
> Hi! Has this issue been resolved? If yes, can we close it?

Yes, Thanks much, it's been resolved. Another question by the way,  Serializing by the way of 'openvino\src\core\src\pass\serialize.cpp '  shows the detail,  I want to combile them(xml .bin) together into one byte serialization while inside converting,  is it enough, can I get an example .

**Comment by andrei-kochin** [comment]
@brilliant-soilder if I get you right it is not possible to get the single file after the serialization. It would be a pair .bin + .xml
