### ISSUE TITLE
[Good First Issue]: Enable parallel execution of MO Python API python tests

### ISSUE THREAD

**Issue by mryzhov** [openvinotoolkit/openvino#20921]
### Context

Current CI (https://github.com/openvinotoolkit/openvino/blob/c0381ab08d2fcdc51c621196e935aa02c64a4b50/.github/workflows/linux.yml#L869) runs all the python tests sequentially one by one and it takes too much time.
The idea is to run all those tests in parallel by using pytest-xdist plugin, but tests should be modified for that.
Please find bellow the common tests issues:
- Random inputs generation as parametrization arguments. Solution: all random test arguments should be generated inside of the tests 
- Tests create, use and remove the same artifacts (temporary data, models, etc). Hot fix solution: all test data should be generated in the system temporary directory (TMPDIR) which can be unique for each thread. Long term solution: all test data should be generated in the unique temporary directory or with unique names.

### What needs to be done?

- Modify MO Python API tests to solve issues described in the Context. Tests are located here - https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/mo_python_api_tests
- Enable parallel execution of those test in the CI (https://github.com/openvinotoolkit/openvino/blob/4a0098b26ad6c4cbae97fbe34505fa63c08036eb/.github/workflows/linux.yml#L991C15-L991C34)

### Example Pull Requests

https://github.com/openvinotoolkit/openvino/pull/20613

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@mryzhov @akashchi

**Comment by AnshMasand** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @AnshMasand! Thank you for taking a look, please let us know if you have any questions. Just yesterday our CONTRIBUTING.md has been updated [with a technical guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md) - I highly recommend checking it out. :)

**Comment by AnshMasand** [comment]
Hey @p-wysocki thank you for the link! This will help immensely. Meanwhile, I've been looking into a few things. Could you let me know if I'm going in the right direction? 
- Setting the cores to auto using the -n auto in pytest-xdist plugin for the CI which would enable parallelization. 
- Generating random inputs, the linked PR has good examples, I will most probably use the same code. 
- Using tempfile.mkdtemp() to create a unique directory for temp files. 

Thank you for your time! :)

**Comment by mlukasze** [comment]
hey @mryzhov, could you help tp @AnshMasand with questions, please?

**Comment by mryzhov** [comment]
Hi @AnshMasand, yes, you are in the right direction. 
I would recommend you as the 2nd step (when you added  -n auto argument) to run tests manually and review the list of the failed tests.

**Comment by AnshMasand** [comment]
.take

**Comment by AnshMasand** [comment]
Hey @mryzhov I'm having a little bit of trouble fully building out the repo. 

Im on a Macbook M2 pro and I've followed [this guide](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_mac_arm.md)

However, I'm running macOS 14.2, on which this software hasn't been validated. I've been running into some issues while trying to test out the python API to validate that the tests are taking too long. This is the most common error im facing: [Link](https://gist.github.com/AnshMasand/a6e4e81f12b8e3d67e2c12dfcda8f98a) 

Is there something I'm doing wrong? I've followed the [guide](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md) given to test it out very closely, replacing obvious details like intel64 -> arm64. I am also using python 3.8 while building the repo and executing pytest commands.

**Comment by p-wysocki** [comment]
I am happy to announce that we have created a channel dedicated to Good First Issues support on our [Intel DevHub Discord server](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by AnshMasand** [comment]
Thank you for the link!

**Comment by p-wysocki** [comment]
Hello @AnshMasand, do you need any help?

**Comment by AnshMasand** [comment]
Hey @p-wysocki, thank you for reaching out. At the moment I don't need any help, but I will reach out in Discord if I do :) 

Thank you again!

**Comment by p-wysocki** [comment]
Hello, @AnshMasand, are you still working on that issue?

**Comment by AnshMasand** [comment]
Hey! Yes, I am. Sorry I've been inactive for so long. I will post updates soon!

**Comment by p-wysocki** [comment]
No need to be sorry, we're just looking for abandoned issues to have more open tasks for other contributors. :)

**Comment by mlukasze** [comment]
Thank you for your time!
If you will be interested we will have more topics to train on, soon :)

**Comment by Developer-atomic-amardeep** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @Developer-atomic-amardeep, are you still working on that issue? Do you need any help?

**Comment by Viditagarwal7479** [comment]
Hey @p-wysocki, If this issue is abandoned can I pick it?

**Comment by Developer-atomic-amardeep** [comment]
I am working on it just it is taking time, I am beginner.

**Comment by p-wysocki** [comment]
Hello @Developer-atomic-amardeep, are you still working on this?

**Comment by mmrbulbul** [comment]
.take

**Comment by hub-bla** [comment]
.take
