### ISSUE TITLE
[Good First Issue]: Enable parallel execution of OVC Python API python tests

### ISSUE THREAD

**Issue by mryzhov** [openvinotoolkit/openvino#20922]
### Context

Current CI (https://github.com/openvinotoolkit/openvino/blob/c0381ab08d2fcdc51c621196e935aa02c64a4b50/.github/workflows/linux.yml#L869) runs all the python tests sequentially one by one and it takes too much time.
The idea is to run all those tests in parallel by using pytest-xdist plugin, but tests should be modified for that.
Please find bellow the common tests issues:
- Random inputs generation as parametrization arguments. Solution: all random test arguments should be generated inside of the tests 
- Tests create, use and remove the same artifacts (temporary data, models, etc). Hot fix solution: all test data should be generated in the system temporary directory (TMPDIR) which can be unique for each thread. Long term solution: all test data should be generated in the unique temporary directory or with unique names.

### What needs to be done?

- Modify OVC Python API tests to solve issues described in the Context. Tests are located here - https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/ovc_python_api_tests
- Enable parallel execution of those test in the CI (https://github.com/openvinotoolkit/openvino/blob/4a0098b26ad6c4cbae97fbe34505fa63c08036eb/.github/workflows/linux.yml#L1001C15-L1001C35)

### Example Pull Requests

https://github.com/openvinotoolkit/openvino/pull/20613

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/wPuqAujS) - engage in discussions, ask questions and talk to OpenVINO developers
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@mryzhov @akashchi

**Comment by boringlyBoring** [comment]
I would be happy to help with the issue. Could you assign this issue to me?

**Comment by boringlyBoring** [comment]
Thanks, I will working on it Friday night

**Comment by p-wysocki** [comment]
Please let us know if you have any questions! :)

**Comment by p-wysocki** [comment]
Hello @boringlyBoring, is there anything we can help you with? Do you have any questions?

**Comment by p-wysocki** [comment]
The task has been returned to be picked up due to current assignee's inactivity. @boringlyBoring if you're still out there working on it, please let us know - we'll return the task to you. :)

**Comment by Prakhar314** [comment]
Hi! I'd like to work on this issue. 
For the temporary directory issue, we can modify the `temp_dir` fixture [here](https://github.com/openvinotoolkit/openvino/blob/17fb201433bf6097b70972801a612f8e3defdd9e/tests/layer_tests/conftest.py#L111) to generate unique temporary directory per thread, right?
I couldn't figure out where the random test inputs are. Can you link an example test taking random arguments?

**Comment by mryzhov** [comment]
Hi @Prakhar314, I would recommend  you to run those tests in parallel as first step and collect list of the failed tests. It may help to find out the root cause.
tmp_dir issue could not be applicable for those tests.

**Comment by ilya-lavrenov** [comment]
@rajatkrishna could you please take this one?

**Comment by Ruman-12** [comment]
Hey @mryzhov i would like work on this issue.
could you please assign me this issue?

**Comment by Ruman-12** [comment]
hey @mlukasze @mryzhov  
I wanted to provide an update regarding the GitHub issue assigned to me. I've been diligently working on it for the past week, but unfortunately, progress has been slower than anticipated due to unforeseen personal commitments. Specifically, I have exams scheduled that require my immediate attention and focus. I acknowledge that it may take some time for me to resolve this issue. I would appreciate your patience as I navigate through my exams and allocate time to address the problem effectively. I am committed to contributing to the project and will do my best to resolve this issue as soon as my schedule permits.

**Comment by p-wysocki** [comment]
Hello @Ruman-12, is there anything we could help with?

**Comment by SaltTheClouds** [comment]
I would like to contribute.

**Comment by p-wysocki** [comment]
Hello @SaltTheClouds, thanks for taking a look! Please let us know if you have any questions, we're here to help. :)

**Comment by SaltTheClouds** [comment]
> Hello @SaltTheClouds, thanks for taking a look! Please let us know if you have any questions, we're here to help. :)

Thank you for including me

**Comment by SaltTheClouds** [comment]
> Hello @SaltTheClouds, thanks for taking a look! Please let us know if you have any questions, we're here to help. :)

I just wanted to check in with you. I'm still working on this issue, but I'm very new to this and I had some technical problems that I didn't expect. I believe I have them worked out now though.

**Comment by SaltTheClouds** [comment]
I'm sorry, I'm just not ready for this one.

**Comment by mahajanparth** [comment]
.take

**Comment by mahajanparth** [comment]
Hey folks, I would like to contribute, could I take a look at it?
 Seems interesting !!!

**Comment by mlukasze** [comment]
@SaltTheClouds do not worry, maybe some other Good First Issue will fit to you better? 
For now I'm reassigning task to @mahajanparth

**Comment by mahajanparth** [comment]
@mlukasze  . Just wanted to confirm some things , even with no parallelism , i can see there are 8 test cases failing and a few skipped. Are there any additional requirements that i am failing to install or is it okay for now  ? 

Program : test_tf_output_order.py .x.x....xxx.xx.x   is the culprit 

![Image](https://github.com/openvinotoolkit/openvino/assets/32522286/230260a1-0331-4fdb-9c33-ab5c075cd0eb)

**Comment by mlukasze** [comment]
@mryzhov could you check it out, please?

**Comment by mahajanparth** [comment]
Hey, @mlukasze  

1) I have converted all the test cases to be run in parallel using pytest-xdist . 
2) Also converted removed Random vectors created in the test data before parameteritization and shifted their creation into the test cases itself.
3)The temp dir fixture was already there so the second part of the ticket didn't need any attention as per now .
4) I am still finding a few test cases to be failing with both sequential and parallelized approach does it need attention from my end ?
Please find the running Time difference in the images below : 

- parallel execution 8 core : 98 seconds ( 542 passed , 12 skipped , 8 failed )
- sequential execution : 407 seconds ( 542 passed , 12 skipped , 8 failed ) 


![Image](https://github.com/openvinotoolkit/openvino/assets/32522286/2824b9a9-4a11-4408-a07d-8c20fa01e156)

[Parallel_execution.txt](https://github.com/openvinotoolkit/openvino/files/14480684/Parallel_execution.txt)



should i raise a PR for the changes ?

**Comment by p-wysocki** [comment]
That sounds like a significant speedup! Could you please open a PR with your changes? It would speed up the review process a lot.

**Comment by hub-bla** [comment]
.take
