### ISSUE TITLE
[Feature Request]: we can add a billing and feedback form in this 

### ISSUE THREAD

**Issue by Tuba-786** [openvinotoolkit/openvino#20939]
### Request Description

According to me it will look good if we add a feedback form and a billing system or calculator for calculating the values 

### Feature Use Case

It will be useful to upgrade and access provide easily 

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by mlukasze** [comment]
hey @Tuba-786 
what kind of billing do you expect? of what?
