### ISSUE TITLE
Convert ONNX model to OpenVINO

### ISSUE THREAD

**Issue by ShidiDaisy** [openvinotoolkit/openvino#2095]
# Ask a Question

### Question
Hi, I'm trying to use OpenVINO toolkit to convert an ONNX pretrained model from [here](https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-10.onnx). Steps are from [here](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html)
But when I ran the command

```
sudo python3 mo.py --input_model FasterRCNN-10.onnx
```

I got these issues:

```
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/FasterRCNN-10.onnx
	- Path for generated IR: 	/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/.
	- IR output name: 	FasterRCNN-10
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
ONNX specific parameters:
Model Optimizer version: 	
[ ERROR ]  Shape [ 1 64 -1 -1] is not fully defined for output 0 of "5". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "5".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "5". 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #40. 
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Elementwise.__init__.<locals>.<lambda> at 0x7f65a6129e18>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "5" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 
```

Looks like the input shape in the model is invalid? How should I solve this issue? What input shape should I use to overwrite the model input shape?

**Comment by maxlytkin** [comment]
@ShidiDaisy 
Try this
`python3 mo_onnx.py --input_shape=[1,3,800,800] --input "0:2"`
I also have to say this model is not presented in the list of Model Optimizer validated ONNX topologies - https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html

**Comment by ShidiDaisy** [comment]
> @ShidiDaisy
> Try this
> `python3 mo_onnx.py --input_shape=[1,3,800,800] --input "0:2"`
> I also have to say this model is not presented in the list of Model Optimizer validated ONNX topologies - https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html

Hi @maxlytkin 
Thanks for your reply. I have tried your comment, but I still got the issue regarding cannot infer shapes or values for some nodes.
`sudo python3 mo.py --input_model FasterRCNN-10.onnx --input_shape
=[1,3,800,800] --input "0:2"`

```
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/FasterRCNN-10.onnx
	- Path for generated IR: 	/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/.
	- IR output name: 	FasterRCNN-10
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	0:2
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	[1,3,800,800]
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
ONNX specific parameters:
Model Optimizer version: 	
[ ERROR ]  Cannot infer shapes or values for node "2086".
[ ERROR ]  astype() takes no keyword arguments
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Cast.infer at 0x7f7881de5158>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "2086" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 
```
And may I double-check with you, does OpenVINO supports [MMDetection's Faster-RCNN_ResNet50_fpn model](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/faster_rcnn_r50_fpn.py), it's pretrained with torchvision resnet50.

Thanks.

**Comment by maxlytkin** [comment]
@ShidiDaisy 
That's strange, I am able to convert it. Unfortunately the file is too big to attach it here. 
Try the same command that I used:
`$ /usr/bin/python3 -- /opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo_onnx.py --input_shape=[1,3,800,800] --input "0:2" --input_model=/home/user/Downloads/FasterRCNN-10.onnx 
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/user/Downloads/FasterRCNN-10.onnx
	- Path for generated IR: 	/home/user/.
	- IR output name: 	FasterRCNN-10
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	0:2
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	[1,3,800,800]
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	False
	- Reverse input channels: 	False
ONNX specific parameters:
Model Optimizer version: 	
[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /home/user/./FasterRCNN-10.xml
[ SUCCESS ] BIN file: /home/user/./FasterRCNN-10.bin
[ SUCCESS ] Total execution time: 153.87 seconds. 
[ SUCCESS ] Memory consumed: 771 MB. `

About MMDetection's Faster-RCNN_ResNet50_fpn model, as per [the list of officially validated model](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html#supported_pytorch_models_via_onnx_conversion) resnet50 from torchvision 0.2.1 should be supported as a public model. However, it does not mention Faster-RCNN one.

**Comment by maxlytkin** [comment]
I'm closing this case. Please feel free to re-open if additional assistance is needed.
