### ISSUE TITLE
[Good First Issue]: implement get_element_type for PaddlePaddle FrontEnd

### ISSUE THREAD

**Issue by ceciliapeng2011** [openvinotoolkit/openvino#20978]
### Request Description

1. implement get_element_type for PaddlePaddle FrontEnd
2. add corresponding unit test

### Feature Use Case

It is needed by ModelOptimizer to freeze placeholders without specifying types. 
Similar implementation is seen https://github.com/openvinotoolkit/openvino/pull/13984 for TensorFlow FE and https://github.com/openvinotoolkit/openvino/pull/14481 for ONNX FE.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

### Contact points
@ceciliapeng2011 

### Ticket
98150

**Comment by jvr0123** [comment]
Hi, I'm interested in working on this. Could I please be assigned to this issue?

**Comment by jvr0123** [comment]
.take

**Comment by jvr0123** [comment]
I've gone ahead and created a draft PR with the getters for the Frontend. I'm a little stumped on the testcases, however. There is a guide [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/paddle/docs/tests.md), but I don't quite follow a few things.

- Which files should I be modifying, the Cpp files or the python test scripts (under `test_models/gen_scripts')? The reference PRs have the implemented modifying python files, but I don't quite see how to do that in the same style. I didn't see any of the python scripts making direct calls to the interface I modified, either.
-The guide says "OpenVINO Paddle Frontend is covered by tests from the binary paddle_tests. This binary can be built by the target with the same name." What does this mean? This binary is not build by default when I run `make` in the build folder.

**Comment by yuxu42** [comment]
Thanks @jvr0123 for the contrubution!  We will take a look.

**Comment by meiyang-intel** [comment]
> I've gone ahead and created a draft PR with the getters for the Frontend. I'm a little stumped on the testcases, however. There is a guide [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/paddle/docs/tests.md), but I don't quite follow a few things.
> 
> * Which files should I be modifying, the Cpp files or the python test scripts (under `test_models/gen_scripts`)? The reference PRs modify the python test files for the other frontends, but I don't quite see how to do that in the same style. I didn't see any of the python scripts making direct calls to the interface I modified, either.
> * The guide says "OpenVINO Paddle Frontend is covered by tests from the binary paddle_tests. This binary can be built by the target with the same name." What does this mean? This binary is not build by default when I run `make` in the build folder.

Hi @jvr0123 , In this case, I think you don't need to add testcase in paddle_tests or modify files in test_models/gen_scripts. Just follow the reference PR to add the testcases.

**Comment by p-wysocki** [comment]
Hello @jvr0123, could you please share a link to the PR? Are you still working on this? Please let us know if you require any help. :)

I am happy to announce that we have created a channel dedicated to Good First Issues support on our [Intel DevHub Discord server](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by ceciliapeng2011** [comment]
https://github.com/openvinotoolkit/openvino/pull/21458
