### ISSUE TITLE
[Good First Issue]: Add Python bindings for PILLOW interpolation modes

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#21042]
### Context

Python API currently supports the following interpolation modes:
- `RESIZE_LINEAR`,
- `RESIZE_CUBIC`,
- `RESIZE_NEAREST`,

which determine how the new values will be calculated when resizing a tensor. More details on interpolation modes can be found in the Resources section.

Implementations for PILLOW interpolation modes have been added to OpenVINO, but the- C++ to Python bindings do not yet exist. This task regards adding them.

### What needs to be done?

1. Add new entries to the `regenum_graph_ResizeAlgorithm` enum:

https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/preprocess/pre_post_process.cpp#L462

The new interpolation modes are:
- `ov::preprocess::ResizeAlgorithm::RESIZE_BILINEAR_PILLOW`
- `ov::preprocess::ResizeAlgorithm::RESIZE_BICUBIC_PILLOW`

2. Add tests for new interpolation modes in https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_graph/test_preprocess.py#L368

3. Submit a Pull Request

### Example Pull Requests

--

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- [Python bindings docs](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/code_examples.md)
- [What are interpolation modes?](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-use-interpolation-mode-to-control-image-quality-during-scaling?view=netframeworkdesktop-4.8)

### Contact points

@openvinotoolkit/openvino-ie-python-api-maintainers 

### Ticket

124943

**Comment by meetpatel0963** [comment]
Hi @p-wysocki, I would like to work on this issue, Could you please assign it to me?

**Comment by meetpatel0963** [comment]
.take

**Comment by meetpatel0963** [comment]
PR #21188

**Comment by p-wysocki** [comment]
The PR has been merged, thank you for your contribution @meetpatel0963! You'll be mentioned in the next release notes with a thank you. :)

**Comment by meetpatel0963** [comment]
Hi @p-wysocki, Thank you! It was a nice issue to get started with the project setup and code. Currently, I'm exploring the code to contribute to new issues, particularly those suitable for beginners. I would greatly appreciate it if you could suggest some documentation that might help me better understand the flow of the code. 

Also, I wanted to know about any community forums or channels on Slack/Discord where I can engage with the community, ask questions, and seek guidance on any challenges I may face. Thank you in advance!

**Comment by p-wysocki** [comment]
Thanks for taking an interest in OpenVINO! Looking at the available good first issues, it seems that the most are related to [ONNX](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/README.md) and [TensorFlow](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/README.md) Frontends. However, the idea behind good first issues is to give as clear issue description as possible, so that's where you can find the most useful information - very closely related to the task.

> Also, I wanted to know about any community forums or channels on Slack/Discord where I can engage with the community, ask questions, and seek guidance on any challenges I may face. Thank you in advance!

For now we do not have any forum for the community, but (I hope) that could change soon. :) Instead, please ask any sort of questions under a specific issue or open a discussion - we're very committed to growing an open source community around OpenVINO and we would love to help you get into the project.
