### ISSUE TITLE
[Good First Issue]: `openvino.save_model(None, ...)` crashes instead of raising an exception

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#21086]
### Context

We strive to have a clear, user friendly API in OpenVINO. An issue has been found where when giving `None` as an argument to `openvino.save_model()` function, the result is a segmentation fault, instead of an exception.

Reproducer:
```bash
>>> import openvino as ov
>>> ov.save_model(None, 'model.xml')
Segmentation fault (core dumped)
``` 

The binding can be found [here](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/pyopenvino.cpp#L163-L193).

### What needs to be done?

`save_model` function binding needs to be modified in a way which will check the type of `model` argument. If it's None, a proper Python exception should be raised. 

Tip:
Please use pybind functionalities for [types](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/object.html) and [errors](https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html)for implementation, for example:
- `py::None`
- `py::attribute_error`

### Example Pull Requests

--

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- [Python bindings docs](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/code_examples.md)

### Contact points

@openvinotoolkit/openvino-ie-python-api-maintainers 

### Ticket

125053

**Comment by adesh1998** [comment]
I would be happy to help with the issue. Could you assign this issue to me?

**Comment by mlukasze** [comment]
> I would be happy to help with the issue. Could you assign this issue to me?

be my guest, happy coding! :)

**Comment by adesh1998** [comment]
could you help me understand how to reproduce this issue so that i will get clear idea in which way i should proceed.

**Comment by p-wysocki** [comment]
Running these two commands should be sufficient:
```python
import openvino as ov
ov.save_model(None, 'model.xml')
```

Their execution should result in a segmentation fault.

**Comment by adesh1998** [comment]
I have build the project as it describe in readme. but i am getting below error 
>>> import openvino as ov
>>> ov.save_model(None, 'model.xml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'openvino' has no attribute 'save_model'

**Comment by jiwaszki** [comment]
Hi @adesh1998 are you using latest OpenVINO version? Can you show us what is the result of calling `dir(ov)` and simply calling `ov` in your interpreter?

**Comment by adesh1998** [comment]
this is dir(ov) looks like:
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

**Comment by jiwaszki** [comment]
@adesh1998 are you using wheels or PYTHONPATH after build of the project? It looks like the package is empty, so it could be a case that it is not installed at all. Please verify that it is installed first.

**Comment by daksh-code** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @sydarb, thanks for taking a look! Please let us know if you have any questions or issues. :)

Hi @daksh-code, we're sorry but @sydarb picked up the issue a few hours before you, as seen in comment history - please pick up another Good First Issue!
