### ISSUE TITLE
Bert issue 

### ISSUE THREAD

**Issue by fengxiaoshuai** [openvinotoolkit/openvino#211]
after optimized by the lastest  version of openvino , the bert model always run on one cpu  though there are eight cpus， but the other model can run on eight cpus.( the bert model need a cpu_extension :/opt/intel/openvino_2019.2.242/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so )

**Comment by shubha-ramani** [comment]
Dear @fengxiaoshuai 
Thanks for jumping on OpenVino R2 so quickly. It should be added to dldt soon. What do you mean by this statement ?

>  but the other model can run on eight cpus.

What other model are you talking about ?

Bert Model only running on 1 CPU when there are 8 available seems weird.  What code are you using for inference ? Can you kindly attach a simple main.cpp which demonstrates the issue ?

Thanks,

Shubha

**Comment by fengxiaoshuai** [comment]
Dear @shubha-ramani 

Thank you for your reply in your tight schedules. 
I used OpenVINO to optimize vgg_16 and some other visual models. Yesterday I found that the latest version started to support the language model, so I used the model provided by the official website to experiment. It is successful in both the model optimization phase and the inference phase, however, only  a cpu is running in the inference phase, that is too weird. Trying various settings has no effect. Here is the python code:
---------------------------------------------------------------------------------------------------------------
def main():
    # load model
    model_xml = "/work/DownLoad/multilingual_L-12_H-768_A-12/bert/bert_model.ckpt.xml"
    model_bin = "/work/DownLoad/multilingual_L-12_H-768_A-12/bert/bert_model.ckpt.bin"
    ie = IECore()

    # ie.set_config({'CPU_THREADS_NUM': '8'}, 'CPU')
    # ie.set_config({'CPU_THROUGHPUT_STREAMS': str(1)}, 'CPU')
    # ie.set_config({'CPU_BIND_THREAD': 'NO'}, 'CPU')
    # ie.set_config({'EXCLUSIVE_ASYNC_REQUESTS': 'YES'}, 'CPU')
    ver = ie.get_versions("CPU")["CPU"]
    print(
        "{descr}: {maj}.{min}.{num}".format(descr=ver.description, maj=ver.major, min=ver.minor, num=ver.build_number))

    # adde the cpu extension, because the default plugin don't support bert model
    ie.add_extension(
        '/opt/intel/openvino_2019.2.242/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so', 'CPU')
    net = IENetwork(model=model_xml, weights=model_bin)

    supported_layers = ie.query_network(net, "CPU")
    not_supported_layers = [l for l in net.layers.keys() if l not in supported_layers]
    if len(not_supported_layers) != 0:
        print("Following layers are not supported by the plugin for specified device {}:\n {}".
              format('CPU', ', '.join(not_supported_layers)))
        print("Please try to specify cpu extensions library path in sample's command line parameters using -l "
              "or --cpu_extension command line argument")

    # show some metric_val
    device = 'CPU'
    for metric in ie.get_metric(device, "SUPPORTED_METRICS"):
        metric_val = ie.get_metric(device, metric)
        print("\t\t{}: {}".format(metric, str(metric_val)))

    for cfg in ie.get_metric(device, "SUPPORTED_CONFIG_KEYS"):
        cfg_val = ie.get_config(device, cfg)
        print("\t\t{}: {}".format(cfg, str(cfg_val)))

    # prepare input and output
    input_blob = [i for i in net.inputs]
    out_blob = [i for i in net.outputs]

    print('input:', input_blob)
    print('output:', out_blob)

    in1 = np.ones([1, 128]).astype(np.int32)
    in2 = np.ones([1, 128]).astype(np.int32)
    in3 = np.ones([1, 128]).astype(np.int32)

    # execute 
    exec_net = ie.load_network(network=net, device_name="CPU")

    # print the time 
    time2 = time.time()
    res = exec_net.infer(inputs={input_blob[0]: in1, input_blob[1]: in2, input_blob[2]: in3})
    time3 = time.time()
    res = res[out_blob[0]]
    print(time3 - time2)


if __name__ == "__main__":
    main()
---------------------------------------------------------------------------------------------------------------
Thanks,

fengxiaoshuai

**Comment by shubha-ramani** [comment]
Dear @fengxiaoshuai 
One of my colleagues tried BERT with the [benchmark_app](http://docs.openvinotoolkit.org/latest/_inference_engine_samples_benchmark_app_README.html) and he was able to see full utilization of the cores. Please see [this IDZ post](https://software.intel.com/en-us/forums/computer-vision/topic/815110)

Thanks,

Shubha

**Comment by fengxiaoshuai** [comment]
Dear @shubha-ramani

I tried the benchmark_app depend on the IDZ post。the time of inference is 160ms when I use tensorflow,  however the inference time is  900ms when I use OpenVION。 
In addition, when I set the parameter nireq to 1(I  have only one request actually ), a single CPU was actually computing in the inference stage, and the problems raised before were still not solved.
I don't know if you have tried the code I provided. I hope OpenVINO can explain it。

Thanks,

fengxiaoshuai

**Comment by shubha-ramani** [comment]
Dear @fengxiaoshuai 
I will try your code today. Thanks for your patience.

Shubha

**Comment by shubha-ramani** [comment]
Dear @fengxiaoshuai 

please give me your bert input data by attaching it to this github ticket as *.zip. Or please tell me how to get that data. Namely, what did you pass into -i when you ran the benchmark_app ? 

Thanks,

Shubha

**Comment by 111Moderato** [comment]
@fengxiaoshuai
I have a question ：
Is the output of the bert model you run in openvino correct?

**Comment by seanxcwang** [comment]
> Dear @fengxiaoshuai
> 
> please give me your bert input data by attaching it to this github ticket as *.zip. Or please tell me how to get that data. Namely, what did you pass into -i when you ran the benchmark_app ? I would like to exactly repeat your experiment.
> 
> Thanks,
> 
> Shubha

hi Shubha，have the problem been solved by the latest version

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
