### ISSUE TITLE
Import error while using OpenVINO Deep Learning Workbench

### ISSUE THREAD

**Issue by Fatinnadiah** [openvinotoolkit/openvino#2119]
OpenVINO version: openvino_2020.4.287
Operating System: Ubuntu 18.04

Hi, I have a FP16 model for face mask classification. I want to convert the model into INT8 model using OpenVINO Workbench. I can convert the model into INT8 model but using not annotated dataset and I get very low accuracy from 98% on using FP16 to 75% on using INT8. With not annotated dataset, I cannot control the AccuracyAware Method parameter under Optimization Method.
![image](https://user-images.githubusercontent.com/59385438/92429390-5890f380-f1c4-11ea-867d-ddc4ebf5e0a3.png)

So I decide to annotate my dataset so that I can control the AccuracyAware Method. I annotating my dataset using Labelimg tool. After annotating the dataset I cannot import it inside the OpenVINO Workbench. The error show below
![image](https://user-images.githubusercontent.com/59385438/92429628-20d67b80-f1c5-11ea-8164-2f90a7b54e21.png)

All the images inside Annotation.zip folder is JPEG format. Refer below for some example images inside Annotation.zip folder.
![image](https://user-images.githubusercontent.com/59385438/92428411-a0624b80-f1c1-11ea-8cd7-fa6f4e358d53.png)

I also try to import ImageNet classification dataset format and it is same, I also cannot import it. Example images inside the Classification.zip folder as below
![image](https://user-images.githubusercontent.com/59385438/92428341-65601800-f1c1-11ea-8b52-cc915f3171c1.png)

And the error stated that it cannot find any annotation file
![image](https://user-images.githubusercontent.com/59385438/92430195-ae669b00-f1c6-11ea-8fef-164867a5188d.png)

I'm not sure what is the problem regarding on importing dataset. The only dataset that I can import is not annotated dataset. I also have some doubt why the accuracy drop in very huge number from FP16 to INT8. Did I convert it correctly? For the annotation dataset, did I need to use any specific tools? 

Please help me on this since I want to reduce CPU usage as many as I can. 
Thank you

**Comment by raushan2767** [comment]
Hi,
For ImageNet classification dataset format your annotation.txt file should contain name of image and corresponding label id.
For ex:- mask10.jpeg 1
             withoutMask11.jpeg 0
for above example 0,1 if u have two classes.
![imagenet_dataset](https://user-images.githubusercontent.com/65812965/92434666-0e0c7880-f1be-11ea-80c8-c5fbc2a3d61e.JPG)

**Comment by Fatinnadiah** [comment]
> Hi,
> For ImageNet classification dataset format your annotation.txt file should contain name of image and corresponding label id.
> For ex:- mask10.jpeg 1
> withoutMask11.jpeg 0
> for above example 0,1 if u have two classes.
> ![imagenet_dataset](https://user-images.githubusercontent.com/65812965/92434666-0e0c7880-f1be-11ea-80c8-c5fbc2a3d61e.JPG)
> 
> After this Zip your folder and try to import. i was facing same issue, but now i'm able to resolve this.

Hi,
Thank you for response. Now I can load the dataset using ImageNet format

**Comment by Fatinnadiah** [comment]
Hi, now I'm converting the FP16 model to INT8 using ImageNet dataset format. Is it normal the conversion time took so long? Because I left it for almost 2 hours already.
And I still cannot import an annotation dataset

**Comment by brmarkus** [comment]
Conversoin could take longer, depending on which machine you are using, plus depending on whether you are using the default-mode or accuracy-aware-mode.
On my Intel-Core-i9 (10 cores plus hyper-threading) I saw conversions could take multiple hours for bigger networks - or minutes for smaller/easier ones.

**Comment by jgespino** [comment]
Closing, feel free to re-open if additional assistance is needed.
