### ISSUE TITLE
when will dldt be updated to l_openvino_toolkit_p_2019.2.242

### ISSUE THREAD

**Issue by MrJBSwe** [openvinotoolkit/openvino#212]
HI,

I can't yet see any changes to dldt yet, guess it will need to be updated to latest l_openvino_toolkit_p_2019.2.242

**Comment by shubha-ramani** [comment]
Dearest @MrJBSwe 
We are working on it !  Sorry for the delay but stay tuned.

Shubha

**Comment by lazarevevgeny** [comment]
The repository has been updated. Closing.
