### ISSUE TITLE
[Feature Request]: Does openvino support fp16/fp32 mixed precision inference?

### ISSUE THREAD

**Issue by kklots** [openvinotoolkit/openvino#21238]
### Request Description

I have a model. When it works on FP16 inference, the layers with Pow operation will result in an unacceptable low precision in the final result. When it works on FP32, the inference speed is too slow.
Does openvino support FP32/FP16 mixed precision inference, specifying some  layers to work on predefined precision?

### Feature Use Case

fp8/fp16/fp32 mixed precision inference

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by andrei-kochin** [comment]
Hello @kklots,
Thanks for reaching OpenVINO!

Actually when compress_to_fp16 is used for model conversion(starting from 23.1 it is by default) in fact some layers are still remains in FP32 to avoid significant accuracy drops. Layer selection is based on internal logic and can't be controlled from outside.

Am I getting you right that you want to have some kind of "ignored scope" similar to NNCF to specify layers which should skip compression?

CC @slyalin

**Comment by kklots** [comment]
Hi @andrei-kochin ,
Thanks for your reply.

Yes, you are right. I need some way to control the compression of specific layers.

**Comment by pavel-esir** [comment]
hi @kklots thanks for your message! Yes we have a mechanism for mixed precision. GPU device can infer some nodes in fp32 while most of the other nodes in fp16. When models contain ReduceMean + exponen, ReduceSum + exponent, x / (y + eps) (eps a small value which does not fit into fp16), etc. openvino automatically infer such parts in fp32. Looks like in your case subgraph is different from that cases.

But still, there is one more way to make mixed precision work. You can use `model_upcast_utils.py` form `openvino_notebooks` it will automatically upcast nodes with significant errors to fp32. You will need to download this utility and just run utility with provided inputs, below is example:

```
# Fetch `model_upcast_utils` which helps to restore accuracy when inferred on GPU
import urllib.request
urllib.request.urlretrieve(
    url='https://raw.githubusercontent.com/openvinotoolkit/openvino_notebooks/main/notebooks/utils/model_upcast_utils.py',
    filename='model_upcast_utils.py'
)
from model_upcast_utils import partially_upcast_nodes_to_fp32

ov_model = core.read_model(ir_path)
if 'GPU' in core.available_devices:
    mixed_precision_ov_model = partially_upcast_nodes_to_fp32(ov_model, example_input = ...)
```

This should work automatically. We implemented the latest experimental feature just recently and are ready to improve it. But if it doesn't work please give us feedback

**Comment by kklots** [comment]
OK, I will try it. Thanks a lot! @pavel-esir

**Comment by pavel-esir** [comment]
Here is an example how we use this utility in openvino notebooks https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1382/

**Comment by andrei-kochin** [comment]
@kklots any luck with Pavel's suggestion?

**Comment by andrei-kochin** [comment]
@kklots closing for now. Feel free to re-open in case of any issues
