### ISSUE TITLE
FacesBoxes

### ISSUE THREAD

**Issue by dexception** [openvinotoolkit/openvino#213]
https://github.com/TropComplique/FaceBoxes-tensorflow

Can you provide support for the above repo ?

**Comment by shubha-ramani** [comment]
Dearest @dexception 

So I tried Model Optimizer on that repo (the frozen pb provided [here](https://drive.google.com/drive/folders/1DYdxvMXm6n6BsOy4dOTbN9h43F0CoUoK?usp=sharing), with my "bag of tricks" and you are correct - this one is not supported by OpenVino 2019R2 Model Optimizer. I will definitely file a feature request on your behalf.

In the meantime, would [facenet](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_FaceNet_From_Tensorflow.html) work for you ?

Sorry for the inconvenience,
Thanks !

Shubha

**Comment by dexception** [comment]
@shubha-ramani 
facenet is not for detection ? right ?

I am just looking for an extremely fast scalable face detector on CPU.

**Comment by eaidova** [comment]
@dexception , do you not try face detection models from [Open Model Zoo](https://github.com/opencv/open_model_zoo)? It contains several models which can be suitable for you (e.g. [face-detection-retail-0005](https://github.com/opencv/open_model_zoo/blob/master/intel_models/face-detection-retail-0005/description/face-detection-retail-0005.md))

**Comment by dexception** [comment]
@eaidova 
These models are not accurate. They are giving plenty of false positives. Thus not fit enough to be used in production.

**Comment by dexception** [comment]
@eaidova 
Any updates on this ?

MultiBlock-LBP based face detection is 10 times faster than even FaceBoxes...
Looking forward to that also.

**Comment by lazarevevgeny** [comment]
The models contain "while" loops which are not support in general. So the model is still not supported.
