### ISSUE TITLE
[Good First Issue]: Support Div operation for TensorFlow

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#21464]
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.1/openvino_docs_ops_opset.html).

In order to infer TensorFlow models with [Div](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Div) operation by OpenVINO, TF FE needs to be extended with this operation support.

### What needs to be done?

For [Div](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Div) operation support, you need to add the corresponding loader into TF FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of TensorFlow operation.

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/19007

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-tf-frontend-maintainers

**Comment by rkazants** [comment]
Hi @sami0i, sure. The task is yours.

Best regards,
Roman

**Comment by sami0i** [comment]
Thanks @rkazants, I'm starting to work on it.

**Comment by daksh-code** [comment]
.take

**Comment by sami0i** [comment]
Hello @p-wysocki! This issue has been assigned to me. Thank you for the guidance. I'll review CONTRIBUTING.md before submitting the PR.

**Comment by p-wysocki** [comment]
You're right @sami0i, sorry! I was updating all the issues with the information about CONTRIBUTING.md and didn't read the whole comment history. Let us know if we can help. :)

**Comment by sami0i** [comment]
Hello @rkazants, could you please review my pull request? #21730

**Comment by mlukasze** [comment]
hey @sami0i 
Roman is on short vacation, but he will review just after he will back.
Sorry for inconvenience.

**Comment by p-wysocki** [comment]
I am happy to announce that we have created a channel dedicated to Good First Issues support on our [Intel DevHub Discord server](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by rkazants** [comment]
@sami0i, congratulations! Your PR was merged. Hope to see you again contributing to other OpenVINO GFIs.

Best regards,
Roman

**Comment by sami0i** [comment]
Hi @rkazants,
Thank you so much for your guidance and patience! I truly appreciate it. Looking forward to contributing to more issues in the future.
