### ISSUE TITLE
[Bug] Fails finding python during onnx build

### ISSUE THREAD

**Issue by helmutg** [openvinotoolkit/openvino#2147]
##### System information (version)
- OpenVINO => git master as of 2020-09-09
- Operating System / Platform => Debian 11 (Bullseye) amd64
- Compiler => gcc
- Problem classification: build failure

##### Detailed description
On more recent versions of Debian (and other distributions), the unversioned `/usr/bin/python` no longer exists. More specifically, the dependencies installed by `install_dependencies.sh` do not include Python 2.x for apt-based systems. While building onnx, there is a failure running `python gen_proto.py`. The onnx build has a detection mechanism for `PYTHON_EXECUTABLE` that does not consider `python3`, which would work.

##### Steps to reproduce

Build OpenVINO on a system that lacks `/usr/bin/python` and Python 2.x in general.

##### Possible mitigations

One option is explicitly installing `python` via `install_dependencies.sh`. While this works for now, Debian wants to completely remove `/usr/bin/python` leaving only `/usr/bin/python2` and `/usr/bin/python3`.

Another way to work around the issue is passing `-DPYTHON_EXECUTABLE=python3` to the CMake invocation. This flag is passed down to the onnx build and overrides its own detection. `gen_proto.py` works with Python 3.x.

A real solution likely would include changes to onnx itself. If onnx were using `find_package (Python REQUIRED COMPONENTS Interpreter)`, it would likely discover a Python 3.x installation. Should the issue be directed there?

**Comment by jgespino** [comment]
Hi @helmutg 

Thanks for reaching out, the build instructions have only been validated on the following software:

> Ubuntu* 18.04 (64-bit) with default GCC* 7.5.0
> Ubuntu* 16.04 (64-bit) with default GCC* 5.4.0
> CentOS* 7.4 (64-bit) with default GCC* 4.8.5

It would be great if you can contribute your findings, take a look at the [How to Contribute](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md) section.

Regards,
Jesus

**Comment by helmutg** [comment]
I've attempted fixing this in onnx itself. See https://github.com/onnx/onnx/pull/3022. If onnx merges this and is openvino updates onnx, this issue is resolved.

**Comment by jgespino** [comment]
Great, thanks for sharing!

**Comment by jgespino** [comment]
@helmutg Do you still need this issue opened in the OpenVINO repository?

**Comment by helmutg** [comment]
That's a good question. It still is a bug and it still affects OpenVINO master. The onnx issue is still open and OpenVINO needs to update its onnx to a fixed version (which does not exist yet) to get rid of it.

**Comment by jgespino** [comment]
Hi @helmutg 

The [build instructions](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#build-on-linux-systems) for OpenVINO list Python 3.6 or higher as a requirement and specify using the -DENABLE_PYTHON=ON along with the following additional options depending on the python version.
```
-DPYTHON_EXECUTABLE=`which python3.7`
-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.7m.so
-DPYTHON_INCLUDE_DIR=/usr/include/python3.7
```
I also want to note that Debian has not been validated with the build instructions. We have validated on Ubuntu 18.04, Ubuntu 20.04 and CentOS 7.6.

This is similar to your second possible solution, please let me know if you tried this and are able to build successfully.

Regards,
Jesus

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or start a new issues if additional assistance is needed.

Sincerely,
Sahira
