### ISSUE TITLE
vpu_graph_transformer tagged 2019.1 does not compile on Win32/Release configuration with VS14

### ISSUE THREAD

**Issue by balmurat** [openvinotoolkit/openvino#215]
vpu_graph_transformer tagged 2019.1 does not compile on Win32/Release configuration with VS14 Giving following Error:

 1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\vpu\graph_transformer\src\model\data_desc.cpp(30): error C4146: unary minus operator applied to unsigned type, result still unsigned
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\vpu\graph_transformer\src\model\data_desc.cpp(35): error C4146: unary minus operator applied to unsigned type, result still unsigned

**Comment by shubha-ramani** [comment]
Dear @balmurat 
As I reported in [your previous post](https://github.com/opencv/dldt/issues/216) Visual Studio 2015 and Windows 10 are the minimum supported for OpenVino.

Hope it helps,

Thanks,

Shubha

**Comment by balmurat** [comment]
I need support for windows 32 bit environment.

**Comment by shubha-ramani** [comment]
Dearest @balmurat,
Repeated from [your previous post issue 216](https://github.com/opencv/dldt/issues/216)

> I'm sorry for your inconvenience. The OpenVino team has not built 32-bit for more than two years and doing so is not a priority at this time.

Thanks,

Shubha
