### ISSUE TITLE
Correct ONNX and Successful conversion to OpenVino, But FAIL generating correct results 

### ISSUE THREAD

**Issue by songtaoshi** [openvinotoolkit/openvino#2154]
![image](https://user-images.githubusercontent.com/20240391/92708569-cdad2600-f388-11ea-92bd-65e82d66b510.png)  
Hi, I convert my pytorch model into onnx, and check the correctness of the conversion by using onnx to do the inference.     
And I also transfer the onnx to the openvino successfully, but I get wrong results (all the same).   
But I do not know where I made the mistake.   

here is my inference script.  
```python
    log.basicConfig(format="[ %(levelname)s ] %(message)s", level=log.INFO, stream=sys.stdout)
    args = build_argparser().parse_args()
    model_xml = args.model
    model_bin = os.path.splitext(model_xml)[0] + ".bin"

    # Plugin initialization for specified device and load extensions library if specified
    log.info("Creating Inference Engine")
    ie = IECore()
    if args.cpu_extension and 'CPU' in args.device:
        ie.add_extension(args.cpu_extension, "CPU")
    # Read IR
    log.info("Loading network files:\n\t{}\n\t{}".format(model_xml, model_bin))
    net = ie.read_network(model=model_xml, weights=model_bin)

    # check all the transfered layer supported by the CPU 
    if "CPU" in args.device:
        supported_layers = ie.query_network(net, "CPU")
        not_supported_layers = [l for l in net.layers.keys() if l not in supported_layers]
        if len(not_supported_layers) != 0:
            log.error("Following layers are not supported by the plugin for specified device {}:\n {}".
                      format(args.device, ', '.join(not_supported_layers)))
            log.error("Please try to specify cpu extensions library path in sample's command line parameters using -l "
                      "or --cpu_extension command line argument")
            sys.exit(1)

    # Loading model to the plugin
    log.info("Loading model to the plugin")
    exec_net = ie.load_network(network=net, device_name=args.device)


    # loading feature
    temp = np.load(args.feature)
    feature, length = temp['arr_0'], temp['arr_1']

   
    ort_session = onnxruntime.InferenceSession(args.onnx_model)

    # I have also tried with a random input, also get the same results
    # feature = np.random.normal(size=(1,64,352))
    # length = np.array([20])
    ort_inputs = {
        'audio_signal': feature,
        'length': length
    }
    ort_outs = ort_session.run(None, ort_inputs)

    # Start sync inference
    log.info("Starting inference in synchronous mode")
    t0 = time.perf_counter()
    res = exec_net.infer(inputs=ort_inputs)
    t1 = time.perf_counter()
    print("INFERENCE TIME\t\t: {} ms".format((t1-t0)*1000.0))
```

the results:    
![image](https://user-images.githubusercontent.com/20240391/92709730-bd497b00-f389-11ea-9482-e91040a4e5a0.png)

**Comment by songtaoshi** [comment]
I am wondering about the version matching.

**Comment by songtaoshi** [comment]
BTW, I have "prediction" as the output of the onnx model, but when I am using python mo.py to do the conversion, it says that could not find the prediction  node

**Comment by songtaoshi** [comment]
@cepera @wistal @cpriebe @anton-potapov really hope to get some hints

**Comment by jgespino** [comment]
Hi @songtaoshi 

Would it be possible to share your ONNX model for me to reproduce on my end?

Regards,
Jesus

**Comment by songtaoshi** [comment]
Are there any insight? I would like to try first. 
```bash
sudo docker run -p 0.0.0.0:22223:22223 --name st_vino -it openvino/workbench:latest
```
I use the command but it seems that the docker cannot be visited by this port.  
It still tells me that    

> DL Workbench is available at: http://127.0.0.1:5665/?token=69e9586d842ddec1c4a9eb705580c739a5952f7f01171427d4020c4cbeb5d1f6

**Comment by songtaoshi** [comment]
Are there any other hints?  I would like to try first, and BTW, this is an automatic speech processing task, the input is an audio signal, the model input is a processed feature, the shape is (batchsize, feature, timestep) (1,64,352) . I see there is requirements for RGB channel (CV task), are there any shape requirement?

**Comment by jgespino** [comment]
Hi @songtaoshi 

What model topology are you using? Is this a custom trained model? Have you checked if the model is listed under the OpenVINO supported models?
https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html#supported_pytorch_models_via_onnx_conversion

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @songtaoshi Do you still need assistance?
