### ISSUE TITLE
ModuleNotFoundError: No module named 'openvino.tools.mo'

### ISSUE THREAD

**Issue by zzulidamao** [openvinotoolkit/openvino#21591]
我使用mo.py把caffe模型转为openvino IR的时候，提示ModuleNotFoundError: No module named 'openvino.tools.mo'。
openvino2023.2 python3.11 win11

**Comment by andrei-kochin** [comment]
Hello @zzulidamao,
Have you installed openvino-dev package with no issues?
Do you have another openvino instance in your env build from source?

**Comment by zzulidamao** [comment]
我使用pip install openvino-dev命令，安装了openvino-dev package之后就解决了&nbsp;ModuleNotFoundError: No module named 'openvino.tools.mo'这个问题。我的环境中没有其他的openvino instance.
你可以参考openvino-source/tools/mo/README.md
&nbsp;


知乎者也
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrei ***@***.***&gt;; 
发送时间: 2023年12月12日(星期二) 下午4:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [openvinotoolkit/openvino] ModuleNotFoundError: No module named &#39;openvino.tools.mo&#39; (Issue #21591)





 
Hello @zzulidamao,
 Have you installed openvino-dev package with no issues?
 Do you have another openvino instance in your env build from source?

**Comment by p-wysocki** [comment]
Helli @zzulidamao, could you please share what's the console output of `pip install openvino-dev`?

**Comment by zzulidamao** [comment]
![屏幕截图 2023-12-13 110435](https://github.com/openvinotoolkit/openvino/assets/49369253/b498d572-df71-4ae4-9369-7b704f21e47e)
你可以参考一下，我使用miniconda创建虚拟环境，在虚拟环境中安装的openvino-dev package

**Comment by andrei-kochin** [comment]
@zzulidamao so am I getting it right that after installing openvino-dev package the issue with missing MO is gone?
If that is right then it is expected behavior as MO is not part of openvino while only part of openvino-dev package.

**Comment by zzulidamao** [comment]
我安装了openvino-dev以后，mo模块找不到的这个问题的确解决了。
应该和你认为的一样，mo是openvino-dev 的一部分。

发自我的iPhone


------------------ Original ------------------
From: Andrei Kochin ***@***.***&gt;
Date: Wed,Dec 13,2023 0:08 PM
To: openvinotoolkit/openvino ***@***.***&gt;
Cc: zzulidamao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [openvinotoolkit/openvino] ModuleNotFoundError: No module named'openvino.tools.mo' (Issue #21591)





 
@zzulidamao so am I getting it right that after installing openvino-dev package the issue with missing MO is gone?
 If that is right then it is expected behavior as MO is not part of openvino while only part of openvino-dev package.

**Comment by jiwaszki** [comment]
@zzulidamao as I assume from your messages you are using miniconda/conda based environment. Please check `pip show openvino-dev` especially the path to actual installation of the package itself. It is highly possible that simple pip installation put it into system Python instead of your venv. As Anaconda is very different from vanilla Python, it is always better to use `conda install ...` or `python -m pip install ...`.

Refer to:
- https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment
- https://docs.openvino.ai/2023.2/openvino_docs_install_guides_installing_openvino_conda.html

Regards,
Jan - OpenVINO Python API maintainer

**Comment by zzulidamao** [comment]
好的，十分感谢你的回复。
现在我遇到一个新的问题：我使用core.compile_model()加载resnet50模型在没有集成显卡的i7-9700F上时候，我的程序挂起，卡在这一句话没有任何反应。但是当我把同样的程序放到有集成显卡的cpu上时候，是可以正常运行的。你有处理类似问题的经验吗？



发自我的iPhone


------------------ Original ------------------
From: Jan Iwaszkiewicz ***@***.***&gt;
Date: Wed,Dec 13,2023 6:35 PM
To: openvinotoolkit/openvino ***@***.***&gt;
Cc: zzulidamao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [openvinotoolkit/openvino] ModuleNotFoundError: No module named'openvino.tools.mo' (Issue #21591)





 
@zzulidamao as I assume from your messages you are using miniconda/conda based environment. Please check pip show openvino-dev especially the path to actual installation of the package itself. It is highly possible that simple pip installation put it into system Python instead of your venv. As Anaconda is very different from vanilla Python, it is always better to use conda install ... or python -m pip install ....
 
Refer to:
  
https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment
 
https://docs.openvino.ai/2023.2/openvino_docs_install_guides_installing_openvino_conda.html
  
Regards,
 Jan - OpenVINO Python API maintainer
