### ISSUE TITLE
inference_engine tagged 2019.1 does not compile on win32/release configuration with VS14

### ISSUE THREAD

**Issue by balmurat** [openvinotoolkit/openvino#216]
inference_engine tagged 2019.1 does not compile on win32/release configuration with VS14 giving following errors:

1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_data_sse42.cpp(194): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_data_sse42.cpp(196): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_data_sse42.cpp(198): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_data_sse42.cpp(200): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_data_sse42.cpp(278): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_data_sse42.cpp(280): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_data_sse42.cpp(282): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_data_sse42.cpp(284): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(202): error C2719: 'b': formal parameter with requested alignment of 16 won't be aligned
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(290): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(292): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(294): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(296): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(583): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(585): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(587): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(589): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(710): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(712): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(714): error C3861: '_mm_insert_epi64': identifier not found
1>E:\DevelopmentLibraries\dldt-2019_R1.1\inference-engine\src\inference_engine\cpu_x86_sse42\ie_preprocess_gapi_kernels_sse42.cpp(716): error C3861: '_mm_insert_epi64': identifier not found

**Comment by shubha-ramani** [comment]
Dear @balmurat 
Actually OpenVino has never worked with VS14 or 32-bit Windows. Please refer to the following documentation:
[http://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_windows.html](http://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_windows.html)

Thanks,

Shubha

**Comment by balmurat** [comment]
The main problem is to compile it on Win32/Release configuration. VS19 will give the same error. But this error ha to be fixed in order to compile it.

**Comment by shubha-ramani** [comment]
Dearest @balmurat 
I'm sorry for your inconvenience. The OpenVino team has not built 32-bit for more than two years and doing so is not a priority at this time.

Thanks,

Shubha

**Comment by aisnote** [comment]
@balmurat  did you make win32 bit working? I need the win32 version too. thanks.

**Comment by avinash31d** [comment]
@aisnote did you get the 32 bit working?

**Comment by balmurat** [comment]
No I did not work on it. Instead I used a raspberry  pi computer which was
officially supported by openvino.

But according my initial inspection It might not be too difficult. I
compiled almost everything except some 64 intrinsic functions which could
be replaced by 32 bit equivalent instructions with conditional
compilations. I gave up in this place and decided to use raspberry pi in my
Project.

**Comment by AnastasiaKazantaeva** [comment]
Closing this issue as 'The OpenVino team has not built 32-bit for more than two years and doing so is not a priority at this time.'
