### ISSUE TITLE
[Good First Issue][Internal]: Remove PyPI version of `singledispatchmethod` from OV

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#21639]
### Context

We wanted to use `singledispatch` method from built-in Python library, but it has been introduced in Python 3.8. This was an issue because OpenVINO supports a range of Python versions, and Python 3.7 would have been broken if we introduced it to the codebase.

Instead, we used `singledispatch` in form of a [package available on PyPI](https://pypi.org/project/singledispatch/). This allowed us to use `singledispatch` functionality even with Python 3.7.

Recently we have dropped support for Python 3.7, so this workaround is no longer needed.

### What needs to be done?

1. Remove `singledispatchmethod` from:
https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/requirements_test.txt#L42
https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/requirements.txt#L2

2. From the linked code delete everything but `from functools import singledispatchmethod` line and then adjust the code indent to match the rest of the imports
https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/openvino/runtime/utils/data_helpers/wrappers.py#L7-L12

3. Create a Pull Request

### Example Pull Requests

--

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/wPuqAujS) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@p-wysocki 

### Ticket

N/A

**Comment by p-wysocki** [comment]
Please do not pick this issue - it's for an internal use.

**Comment by guy-tamir** [comment]
Hi there, I would like to take this issue.

**Comment by p-wysocki** [comment]
Thank you for taking a look! You're assigned, let us know if you have any questions. You can reach us on Discord or here, in the GitHub Issue. :)

**Comment by guy-tamir** [comment]
I've created a pull-request
https://github.com/openvinotoolkit/openvino/pull/22058

**Comment by p-wysocki** [comment]
Thank you for your contribution! Let's wait for review and merge.
