### ISSUE TITLE
[Consult] Inquire about OpenVINO's support on MacOS systems

### ISSUE THREAD

**Issue by guojin-yan** [openvinotoolkit/openvino#21754]
Dear developer, hello. I have a question to inquire about. I have been developing the OpenVINO CSharp API before, but the previous development was only implemented on Windows and Linux. According to the official data released by OpenVINO, OpenVINO currently supports Mac OS and Apple M-series chips, but I currently do not have corresponding machines around me for testing. So in order to fully develop this project, I need to have my own device for testing.
So I would like to inquire about the current support of OpenVINO for Mac OS system and Apple M-series chips here:
1. What are the current MacOS system versions supported by OpenVINO?
2. What Apple chips does OpenVINO currently support, M1 or M2?
3. Based on the development of OpenVINO, if you want to test on a MacOS system, it is recommended to purchase M-series chips or Intel CPUs?

**Comment by ilya-lavrenov** [comment]
Hi @guojin-yan 

> What are the current MacOS system versions supported by OpenVINO?

Supported HW and OSes are listed here https://docs.openvino.ai/2023.2/system_requirements.html 
![image](https://github.com/openvinotoolkit/openvino/assets/2566854/e47a7a33-8091-4f50-baa7-e4a38f730ec4)

> What Apple chips does OpenVINO currently support, M1 or M2?

All chips are supported, but inference is performed only on CPU.

> Based on the development of OpenVINO, if you want to test on a MacOS system, it is recommended to purchase M-series chips or Intel CPUs?

macOS + Intel is kind of archaism now. Apple goes with ARM processors since 2020.

**Comment by guojin-yan** [comment]
Thank you very much for your detailed reply, which will be very helpful for me to choose a platform in the future. I will continue to focus on developing OpenVINO related projects and promoting OpenVINO model deployment kits in the future.

**Comment by mlukasze** [comment]
thank you for your work @guojin-yan 
we mentioned your bindings in our [Awesome OpenVino](https://github.com/openvinotoolkit/awesome-openvino) list :)

**Comment by guojin-yan** [comment]
@mlukasze  Thank you very much for your recognition of this project. I will continue to work hard to gradually improve and maintain it.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions related to this topic.
