### ISSUE TITLE
[Good First Issue]: Extend ONNX Frontend with Multinomial-7 operator

### ISSUE THREAD

**Issue by mmikolajcz** [openvinotoolkit/openvino#21789]
### Context

Neural networks are graphs consisting of nodes called operators. Each operator corresponds to a mathematical function, usually described in framework's documentation or an AI standard, such as ONNX.
OpenVINO ONNX Frontend is a component responsible for working with ONNX graphs and requires implementation of different ONNX operators in order to use ONNX models.

This task requires extending OpenVINO ONNX Frontend with `Multinomial` operator, using the existing [ov::op::v13::Multinomial](https://github.com/openvinotoolkit/openvino/blob/master/src/core/include/openvino/op/multinomial.hpp).

Necessary help will be provided by ONNX Fronted team.

### What needs to be done?

Operator details can be found in [ONNX Operators](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Multinomial)
More details can be found in [ONNX Changelog](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Multinomial-7)
1. Create `.hpp` and `.cpp` files [here](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/frontend/src/op)
2. Prepare an implementation of this operator in form of a function, `multinomial` should be placed in [opset 1 namespace](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/op/unique.hpp#L13).
3. Register the function in [ops_bridge.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/frontend/src/ops_bridge.cpp#L329-L532) while keeping alphabetical order
4. Create test model(s) in [ONNX models directory](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/onnx/tests/models/). OpenVINO test infrastructure then converts prototxt files to ONNX models - you will use those models later in tests
5. Add tests covering all use cases [here](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/onnx_import.in.cpp)
6. Check [Python xfailed tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/tests_python/test_backend.py) to find a test marked as a xfailed for added functionality. If any exist - remove corresponding lines and try to verify by using cmdline "python -m pytest -k name_of_test".
More details in [adding operators to ONNX Frontend guide](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/how_to_add_op.md)

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/15076
- https://github.com/openvinotoolkit/openvino/pull/14936
- https://github.com/openvinotoolkit/openvino/pull/12510
- https://github.com/openvinotoolkit/openvino/pull/19428
- https://github.com/openvinotoolkit/openvino/pull/21755

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- Guides on [ONNX Frontend architecture](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/architecture.md) and [ONNX Frontend tests](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/docs/tests.md) are also available

### Contact points

@mitruska
@mmikolajcz
@gkrivor
@p-wysocki 

### Ticket

118986
Related https://github.com/openvinotoolkit/openvino/issues/19344

**Comment by rghvsh** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @rghvsh, are you still working on this?

I am happy to announce that we have created a channel dedicated to Good First Issues support on our [Intel DevHub Discord server](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by dev-seek** [comment]
Yep,

**Comment by wonkicho** [comment]
Hello, I have also recently had a problem with this error. Could you please let me know if there are any plans to update related information?

**Comment by mlukasze** [comment]
@dev-seek how is your progress? People are asking ;)

**Comment by dev-seek** [comment]
Hey @mlukasze make this issue open again, 
Not geeting enough time to look on it.. 
Sry..

**Comment by mlukasze** [comment]
do not worry!
if you wil find more time later - please feel invited :)

**Comment by PRATHAM-SPS** [comment]
.take

**Comment by andrei-kochin** [comment]
@PRATHAM-SPS do you have any updates on this ticket?

**Comment by PRATHAM-SPS** [comment]
I have almost completed my work but will be afk for a while.

**Comment by andrei-kochin** [comment]
@PRATHAM-SPS thanks for the update!
For how long do you plan to be afk? =)

**Comment by PRATHAM-SPS** [comment]
> @PRATHAM-SPS thanks for the update!
> For how long do you plan to be afk? =)

I will be back  to my system within 3-4 days

**Comment by PRATHAM-SPS** [comment]
PR :- https://github.com/openvinotoolkit/openvino/pull/23491
