### ISSUE TITLE
Can support 3d LiDAR detection network voxelnext?

### ISSUE THREAD

**Issue by zyxcambridge** [openvinotoolkit/openvino#21849]
### Request Description

https://github.com/dvlab-research/VoxelNeXt

cpu run  in i9 ，

100ms 

pointcloud  

input 30W 

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by zyxcambridge** [comment]
spconv 

https://github.com/mit-han-lab/bevfusion/tree/main/mmdet3d/ops/spconv

**Comment by vurusovs** [comment]
@mlukasze @andrei-kochin please, take a look

**Comment by rkazants** [comment]
Hi @zyxcambridge,

Can you please elaborate more your request or issue? Is your model not converted and not inferred using OpenVINO?
Try take a look at documentation how to convert PyTorch models: https://docs.openvino.ai/2023.2/openvino_docs_OV_Converter_UG_prepare_model_convert_model_Convert_Model_From_PyTorch.html

Best regards,
Roman

**Comment by zyxcambridge** [comment]
pth
 is here https://drive.google.com/file/d/1IV7e7G9X-61KXSjMGtQo579pzDNbhwvf/view?usp=share_link

infrence code is here https://github.com/dvlab-research/VoxelNeXt/blob/master/tools/demo.py

unsupport os  is  called  spconv  https://github.com/mit-han-lab/bevfusion/tree/main/mmdet3d/ops/spconv ;


the network  is smilar to  pointpillars ,but  now  openvino not support any of op in voxelnext  ?

**Comment by rkazants** [comment]
> pth is here https://drive.google.com/file/d/1IV7e7G9X-61KXSjMGtQo579pzDNbhwvf/view?usp=share_link
> 
> infrence code is here https://github.com/dvlab-research/VoxelNeXt/blob/master/tools/demo.py
> 
> unsupport os is called spconv https://github.com/mit-han-lab/bevfusion/tree/main/mmdet3d/ops/spconv ;
> 
> the network is smilar to pointpillars ,but now openvino not support any of op in voxelnext ?

Hi @zyxcambridge,

Can you please share your logs you received during `convert_model` to see a concrete list of unsupported ops?

Best regards,
Roman
