### ISSUE TITLE
OpenVINO 2019 R2 demo fail

### ISSUE THREAD

**Issue by FenixFly** [openvinotoolkit/openvino#219]
Hello! 
I installed OpenVINO R2 2019 on the Ubuntu 16.04, run setupvars.sh, run  install_requirements.sh, and run ./demo_squeezenet_download_convert_run.sh.

Demo fails. 

Traceback (most recent call last):
  File "/usr/lib/python3.5/pathlib.py", line 1220, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/itmm/openvino_models/models/FP16/classification/squeezenet/1.1/caffe'

script demo_squeezenet_download_convert_run.sh has string: 
model=FP16

I replaced it to:
model=FP32

and it is working.

**Comment by FenixFly** [comment]
Oops...
Now it failed when trying to run inference:

cp: cannot remove '/home/itmm/openvino_models/ir/FP32//classification/squeezenet/1.1/caffe/squeezenet1.1.labels': Permission denied

**Comment by FenixFly** [comment]
Also I try to run demo from R2 on Windows, but there is an error, because folder for samples project allowed only for reading after installing.

**Comment by shubha-ramani** [comment]
Dear @FenixFly 
Two things may have happened. Did you install your Model Optimizer pre-requisites ? That is also an important part of installation. Also your internet connection may not be working properly.  demo_squeezenet_download_convert_run.sh  downloads topologies from the Internet as it needs them.
I just ran it in fact on Windows, OpenVino 2019R2 and it succeeded.

Hope it helps,

Thanks,

Shubha

**Comment by AnastasiaKazantaeva** [comment]
It seems that problem has been solved as no response. Closing this issue. Feel free to create a new one in case of some problems/questions
