### ISSUE TITLE
[Feature Request]: save model in memory

### ISSUE THREAD

**Issue by AIgiraffe** [openvinotoolkit/openvino#21902]
### Request Description

i want to know how can i save the .xml and .bin data in memory with ByteIO or something else,  not save them on disk

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by sammysun0711** [comment]
@AIgiraffe, Thanks for your question. 

OpenVINO already provides `export_model` and `import_model` API to save compiled model in memory as io.BytesIO. 

Here is python API and samples for your reference:
https://docs.openvino.ai/2023.2/api/ie_python_api/_autosummary/openvino.runtime.CompiledModel.html#openvino.runtime.CompiledModel.export_model

**Comment by AIgiraffe** [comment]
> @AIgiraffe, Thanks for your question.
> 
> OpenVINO already provides `export_model` and `import_model` API to export & import compiled model in memory as io.BytesIO.
> 
> Here is python API and samples for your reference: https://docs.openvino.ai/2023.2/api/ie_python_api/_autosummary/openvino.runtime.CompiledModel.html#openvino.runtime.CompiledModel.export_model

thanks for you reply. Is there an interface similar to export_model can export model as bin and xml to ByteIO
