### ISSUE TITLE
[Good First Issue][PyOV]: Support direct comparison of PartialShape and Shape with list and tuple

### ISSUE THREAD

**Issue by jiwaszki** [openvinotoolkit/openvino#21969]
### Context

This change will align the behavior of container-like OpenVINO structure to feel more pythonic.

### What needs to be done?

* Edit existing or add overloads of `__eq__` for `PartialShape` and `Shape` classes to directly compare with tuple and list.
* Add various testcases to verify changes.
* [optional] Refactor already existing tests to use new feature.

Example code that should be passing:
```python
from openvino import Shape, PartialShape

a = [1, 2, 3]
s = Shape(a)
assert a == s

t = (1, 2, 3)
ps = PartialShape(t)
assert t == ps
```

### Example Pull Requests

N/A

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/wPuqAujS) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@jiwaszki @akuporos @p-wysocki 

### Ticket

128813

**Comment by EJ-enun** [comment]
I am working on this.

**Comment by EJ-enun** [comment]
can this issue be assigned to me?

**Comment by Lymah123** [comment]
Hi

I am working on this. @jiwaszki , @adk9 , @tpwrules , @EJ-enun 

Can I submit the PR?

**Comment by Lymah123** [comment]
Hi @rafalxintel, I don't seem to see the file I will make modifications in.

**Comment by p-wysocki** [comment]
Hello @Lymah123, we're following the policy of whoever picks the issue first, is the issue owner. The task remains in the hands of @EJ-enun, if you wish to collaborate on this you should ask them.

**Comment by Lymah123** [comment]
> Hello @Lymah123, we're following the policy of whoever picks the issue first, is the issue owner. The task remains in the hands of @EJ-enun, if you wish to collaborate on this you should ask them.

Okay.

**Comment by p-wysocki** [comment]
Hi @EJ-enun, are you still working on this?

**Comment by EJ-enun** [comment]
Yes I am working on this but I am having issues identifying the requisite
files in the repository to make the changes requested. I have been stumped
on this for a few days now and I am just a little confused and embarrassed
to say that on the thread. If you could point me towards them that would be
great.

**Comment by p-wysocki** [comment]
Don't worry, we're here to help. The changes need to be made to:
Shape: `openvino/src/bindings/python/src/pyopenvino/graph/shape.cpp`
PartialShape: `openvino/src/bindings/python/src/pyopenvino/graph/partial_shape.cpp`.

You're also welcome to join [Intel DevHub Discord](https://discord.com/invite/7pVRxUwdWG), it's sometimes easier to ask questions on the chat. Sorry if you're already there, there's a lot of names. :)

**Comment by EJ-enun** [comment]
I am in the discord and it is completely alright!

**Comment by Saharshjain78** [comment]
Hey @akuporos , I followed the chat and am interested in solving this issue, can you please assign this issue to me and a quick recap of what needs to be done to be more efficient pr?

**Comment by akuporos** [comment]
Hello @Saharshjain78,

Thank you for your interest in the development of OpenVINO!

It's need to edit existing/add overloads of `_eq_` for [PartialShape](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/partial_shape.cpp) and [Shape](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/shape.cpp) classes to directly compare with tuple and list.
Also, please, add tests [to this file](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_graph/test_core.py) to cover this feature. Here you may find the document [How to test OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md#how-to-test-openvino-python-api).
The example of how it should work you may find in the description of this issue.

**Comment by Saharshjain78** [comment]
@mlukasze and @akuporos here is the pull request to solve this issue- https://github.com/openvinotoolkit/openvino/pull/25137

**Comment by Saharshjain78** [comment]
@mlukasze and @akuporos here is the pull request to solve this issue- https://github.com/openvinotoolkit/openvino/pull/25137

**Comment by hub-bla** [comment]
.take
