### ISSUE TITLE
[Good First Issue]: Support aten::_unique2 operation

### ISSUE THREAD

**Issue by mvafin** [openvinotoolkit/openvino#21972]
### Context

OpenVINO component responsible for support of PyTorch models is called as PyTorch Frontend (PT FE). PT FE converts a model represented as TorchScript model to a model in [OpenVINO opset](https://docs.openvino.ai/latest/openvino_docs_ops_opset.html).

### What needs to be done?

This operation can be found in `dandelin/vilt-b32-finetuned-vqa` model from [huggingface](https://huggingface.co/dandelin/vilt-b32-finetuned-vqa). You can reproduce the issue with the following code:

```python
from transformers import ViltProcessor, ViltForQuestionAnswering
import requests
import inspect
import torch
from PIL import Image
import openvino as ov
from openvino.frontend.pytorch.utils import prepare_example_inputs_and_model

name = "dandelin/vilt-b32-finetuned-vqa"

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
text = "How many cats are there?"

processor = ViltProcessor.from_pretrained(name)
model = ViltForQuestionAnswering.from_pretrained(name, torchscript=True)

encoding = processor(image, text, return_tensors="pt")
example = dict(encoding)

s_params = inspect.signature(model.forward).parameters
input_parameters, _, model, _ = prepare_example_inputs_and_model(example, s_params, model)

model.eval()
tm = torch.jit.trace(model, **input_parameters)
print(tm.inlined_graph)

m = ov.convert_model(model, example_input=example)
```

The operation is produced by [this code](https://github.com/huggingface/transformers/blob/35e9d2b223067d8e5da8aa96d254747d6f9ab352/src/transformers/models/vilt/modeling_vilt.py#L159)

- Implement conversion rule and/or transformation to support the new operation.
- Implement operation tests in tests/layer_tests/pytorch_tests. Please consider different data types, but keep reasonable number of test cases

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO PyTorch Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/pytorch/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- PyTorch specification: [torch.unique](https://pytorch.org/docs/stable/generated/torch.unique.html#torch.unique)
- OpenVINO specification: [Unique-10](https://docs.openvino.ai/2023.2/openvino_docs_ops_movement_Unique_10.html)

### Contact points

@openvinotoolkit/openvino-pytorch-frontend-maintainers

**Comment by AbhijithGanesh** [comment]
Hi @mvafin Can I work on this issue?

**Comment by mvafin** [comment]
> Hi @mvafin Can I work on this issue?

Yes, please do

**Comment by p-wysocki** [comment]
Hii @AbhijithGanesh, there's now a Discord channel for Good First Issue support -  [Intel DevHub](https://discord.gg/wPuqAujS)! Join it to receive support, engage in discussions, ask questions and talk to OpenVINO developers.

**Comment by AbhijithGanesh** [comment]
I will definitely join it @p-wysocki Thanks

**Comment by p-wysocki** [comment]
Hi @AbhijithGanesh, are you still working on this?

**Comment by Kamakshi8104** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @Kamakshi8104, are you still working on that issue or can we reassign it?

**Comment by p-wysocki** [comment]
Hello @AsakusaRinne, are you still working on this? Is there anything we could help you with?
