### ISSUE TITLE
[Good First Issue]: Support aten::add and aten::mul for boolean inputs

### ISSUE THREAD

**Issue by mvafin** [openvinotoolkit/openvino#21971]
### Context

OpenVINO component responsible for support of PyTorch models is called as PyTorch Frontend (PT FE). PT FE converts a model represented as TorchScript model to a model in [OpenVINO opset](https://docs.openvino.ai/latest/openvino_docs_ops_opset.html).

### What needs to be done?

- Implement conversion rule and/or transformation to support the new operation.
- Implement operation tests in tests/layer_tests/pytorch_tests. Please consider different data types, but keep reasonable number of test cases

### Example Pull Requests

Refer to `aten::sum` [operation conversion](https://github.com/openvinotoolkit/openvino/blob/058f0206e2076a7b580eef06120850ce79625072/src/frontends/pytorch/src/op/sum.cpp#L21) for a similar case when we need to change logic when input is boolean.

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO PyTorch Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/pytorch/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-pytorch-frontend-maintainers

**Comment by PulkitGarg777** [comment]
.take

**Comment by PulkitGarg777** [comment]
Hello
This is the first issue i've taken up, so far to my understanding
1. Need to modify add.cpp to accommodate boolean inputs
2. Create "mul.cpp" to accommodate multiplication for boolean inputs
3. Create test case for the above mentioned

Looking forward to working and learning from you all :) !!

**Comment by mvafin** [comment]
@PulkitGarg777 yeah, seems right to me.

**Comment by PulkitGarg777** [comment]
Greetings!

Wanted to update you on the progress so far
 - ***Modified add.cpp*** to accommodate boolean inputs during addition
 - ***Modified test_add.py*** to accommodate boolean inputs test case
 - ***Added mul.cpp*** to accommodate multiplication as well as extended it to work with boolean inputs
 - ***Modified mul.py*** to accommodate boolean inputs during multiplication

Moving on to testing now

**Comment by andrei-kochin** [comment]
Moving back to "Ready for Contribution" due to 2 weeks of inactivity
