### ISSUE TITLE
[Good First Issue]: Support aten::index_copy_ operation

### ISSUE THREAD

**Issue by mvafin** [openvinotoolkit/openvino#21970]
### Context

OpenVINO component responsible for support of PyTorch models is called as PyTorch Frontend (PT FE). PT FE converts a model represented as TorchScript model to a model in [OpenVINO opset](https://docs.openvino.ai/latest/openvino_docs_ops_opset.html).

### What needs to be done?

This operation can be found in `transfo-xl-wt103` model from [huggingface](https://huggingface.co/transfo-xl-wt103). You can reproduce the issue with the following code:

```python
import inspect
import os
import torch
import openvino as ov
from openvino.frontend.pytorch.utils import prepare_example_inputs_and_model
from transformers import TransfoXLTokenizer, TransfoXLLMHeadModel

os.environ["TRUST_REMOTE_CODE"] = "True"

checkpoint = 'transfo-xl-wt103'
revision = '40a186da79458c9f9de846edfaea79c412137f97'

tokenizer = TransfoXLTokenizer.from_pretrained(checkpoint, revision=revision)
model = TransfoXLLMHeadModel.from_pretrained(checkpoint, revision=revision, torchscript=True)

text = "Hello, my dog is cute"
encoded_input = tokenizer(text, return_tensors='pt')
example_inputs = dict(encoded_input)

s_params = inspect.signature(model.forward).parameters
input_parameters, _, model, _ = prepare_example_inputs_and_model(example_inputs, s_params, model)

model.eval()
tm = torch.jit.trace(model, **input_parameters)
print(tm.inlined_graph)

om = ov.convert_model(model, example_input=example_inputs)
```

This model also has issue with `aten::add` for boolean inputs, but that is covered by a different ticket: #21971

- Implement conversion rule and/or transformation to support the new operation.
- Implement operation tests in tests/layer_tests/pytorch_tests. Please consider different data types, but keep reasonable number of test cases

### Example Pull Requests

Good place to start is `aten::index_put_` operation as reference for `aten::index_copy_`

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO PyTorch Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/pytorch/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-pytorch-frontend-maintainers

**Comment by Sar2580P** [comment]
I want to give it a try, though it is my first issue , I think it is do-able with references provided.

I will share updates on my work. 
Thank You

**Comment by Sar2580P** [comment]
.take

**Comment by mvafin** [comment]
> Good place to start is aten::index_put_ operation as reference for aten::index_copy_
> 
> Unable to locate the path , please provide more info regarding how to locate them.

It is located here https://github.com/openvinotoolkit/openvino/blob/16acb8d75e2965534763ea252e6f0773dbe13e27/src/frontends/pytorch/src/transforms/aten_index_put_replacer.cpp#L50

It is a transformation to replace `aten::index_put_` operation

**Comment by Sar2580P** [comment]
@mvafin 
Pls tell, what should be the logic or what I am expected to code for transformation --> aten::index_copy_ . Like I am not able to find out any meaning of line: 
"This operation can be found in transfo-xl-wt103 model from huggingface."

I am new to this setup of open-source , so I may be sounding like a dumb... But hope you will help me out.

**Comment by mvafin** [comment]
> @mvafin Pls tell, what should be the logic or what I am expected to code for transformation --> aten::index_copy_ . Like I am not able to find out any meaning of line: "This operation can be found in transfo-xl-wt103 model from huggingface."
> 
> I am new to this setup of open-source , so I may be sounding like a dumb... But hope you will help me out.

`transfo-xl-wt103` is a model where this issue is reproduced. I provided a python script to load such model and observe the failure. So the expectation is that this model will work after `aten::index_copy_` is implemented.

**Comment by Sar2580P** [comment]
I am trying to gues what does v0,v1,v2,v3 .... mean in code_base?
Like  v0::Constant , v3::ShapeOf

Any idea, how to interpret them and know which class is in which namespace?

**Comment by mvafin** [comment]
> I am trying to gues what does v0,v1,v2,v3 .... mean in code_base? Like v0::Constant , v3::ShapeOf
> 
> Any idea, how to interpret them and know which class is in which namespace?

This is a version of each operation. You can open header file of each operation and see what version is latest.

**Comment by mvafin** [comment]
@Sar2580P Based on ONNX conversion for `aten::index_copy` it is not as complicated as `aten::index_put` (https://github.com/pytorch/pytorch/blob/b4a35632f9cf5bb76fb7576d6f3e0052c124fcf5/torch/onnx/symbolic_opset9.py#L3234), so I would recommend trying to do implementation for translation rather then transformation first.

**Comment by Sar2580P** [comment]
In above link, there were 4 steps written-->
 1. reshape index => [1, ..., 1, dim, 1, ..., 1]
 2. expand index => [..., dim, ...], same shape as self except for dim.
 3. expand value as well.
 4. apply onnx::scatter.
 
 I have unsqueezed the index array, but no idea how to expand it, could you suggest any operation for it? If you want, I can share the code or logic I implemented till now. 
 
 Please cooperate as its my first contribution to open src in current life.

**Comment by Sar2580P** [comment]
As far as I understand, I need to firstly check that :
- rank of self, tensor (names used by pytorch) are same or not  (done)
- handled case of dim being negative  (done)
- check that rest all dimensions of self, tensor match except the dimension : dim (done)

Remaining : 
- copy the values from tensor to self along axis : dim for given indices

Planning Ahead:
- unsqueeze the index array such that it is of same rank as self, tensor (done)
- then inflate the index such that it has same dimension as self , except the dim_th dimension (*)
- then use ScatterNDUpdate and task would be complete (*)

Please guide on issues marked with (*) and review work till now.

**Comment by Sar2580P** [comment]
Please put more emphasis on how to move ahead after unsqueezing the index array.

**Comment by Sar2580P** [comment]
I have implemented index_copy_replacer similar to index_put_replacer. But when I run the above snippet, the problem is same. I have also written for index_copy wherever index_put was , like in 
- frontend.cpp
But no change in error. 
I think my file is not reached by the above code. Pls help

**Comment by mvafin** [comment]
> I have implemented (transformation) _**index_copy_replacer**_ similar to _**index_put_replacer**_. But when I run the above snippet, the problem is same. I have also written for index_copy wherever index_put was , like in
> 
> * frontend.cpp
>   https://github.com/Sar2580P/openvino/blob/e7ad182e602b9e2d0bbedd56ff0cb43c8d73a8cc/src/frontends/pytorch/src/frontend.cpp#L27C12-L27C12
> 
> But no change in error. I think my file is not reached by the above code. Pls help

Please write a simpler test for your operations, like a test for index_put: https://github.com/openvinotoolkit/openvino/blob/master/tests/layer_tests/pytorch_tests/test_index_put_.py

That way you can check only your operation, not the whole model. The snippet I provided is to help you understand how this operation is used in model.

**Comment by Sar2580P** [comment]
I tried setting up test environment as per the readme : 
https://github.com/openvinotoolkit/openvino/blob/master/tests/layer_tests/README.md

But got the following error :
```
collecting ... Traceback (most recent call last):
  File "/home/bala/Desktop/NITIN_DATA/vino/openvino/src/bindings/python/thirdparty/pybind11/tests/conftest.py", line 20, in <module>
    import pybind11_tests
ModuleNotFoundError: No module named 'pybind11_tests'
collected 0 items / 1 error                                                                                                            
```

**Comment by mvafin** [comment]
> I tried setting up test environment as per the readme : https://github.com/openvinotoolkit/openvino/blob/master/tests/layer_tests/README.md
> 
> But got the following error :
> 
> ```
> collecting ... Traceback (most recent call last):
>   File "/home/bala/Desktop/NITIN_DATA/vino/openvino/src/bindings/python/thirdparty/pybind11/tests/conftest.py", line 20, in <module>
>     import pybind11_tests
> ModuleNotFoundError: No module named 'pybind11_tests'
> collected 0 items / 1 error                                                                                                            
> ```
> 
> I also could not find what to put in "path to python api" in readme. So I removed it from PYTHON_PATH. May be error is due to that...
> 
> Pls help

Did you try to run tests in the root directory? I would recommend running only pytorch `tests/layer_tests/pytorch_tests`. 
You can run something like this:
`pyhton -m pytest tests/layer_tests/pytorch_tests/test_add.py`
to run only specific test.

**Comment by Raya679** [comment]
Hi @mvafin I see that this issue is not assigned anymore. Can I work on this issue?

**Comment by Raya679** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @Raya679, are you still working on that issue? Do you need any help?

**Comment by AsakusaRinne** [comment]
.take
