### ISSUE TITLE
[Good First Issue]: Adding OpenVINO GPU operator to support PP-OCRv4_det model 

### ISSUE THREAD

**Issue by guojin-yan** [openvinotoolkit/openvino#21986]
### Context

The PP-OCR series model, which PaddleOCR specializes in, has been widely praised since its launch. In previous development, OpenVINO has been used to deploy the entire PP-OCR series model and has been tested on the CPU. However, the PP-OCRv4_det model under the PP-OCR series model encountered problems when tested on GPU, which posed a great challenge for using Intel GPU to accelerate PP-OCR for text implementation.

### What needs to be done?

The inference output using OpenVINO on the CPU is：
![image](https://github.com/openvinotoolkit/openvino/assets/91110433/4543ade1-e295-45fc-a562-8d57164d3db9)
But the inference output using OpenVINO on GPU is：
![image](https://github.com/openvinotoolkit/openvino/assets/91110433/37957559-b624-4401-b70c-782238fd5a1b)

You can refer to the following documents to reproduce the problem:
https://github.com/guojin-yan/IssuesFile/blob/master/OpenVINO_PP-OCRv4_det/main.ipynb

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)

### Contact points

none

**Comment by priyanshyy** [comment]
Can I work on this issue ? @guojin-yan

**Comment by guojin-yan** [comment]
I'm very sorry, I don't have the authority to assign this issue. Please wait for the official response from OpenVINO staff. So far, no one has claimed this issue. You are the first one, you can solve the problem first, and then wait for the official response before submitting a solution to the problem. @priyanshyy

**Comment by vurusovs** [comment]
@priyanshyy you're welcome to start working on issue

**Comment by p-wysocki** [comment]
Hi @priyanshyy, are you still working on this issue?

**Comment by AlessandroTesi8** [comment]
Can I work on this issue ?

**Comment by mlukasze** [comment]
you bet! It's yours now! :)

**Comment by AlessandroTesi8** [comment]
trying to reproduce the error, when I run the inference with 'GPU.0' Exception from src/inference/scr/infer_request.cpp: 231 raises with error code -54

**Comment by guojin-yan** [comment]
Which version of OpenVino are you using?

**Comment by p-wysocki** [comment]
I'm unassigning @AlessandroTesi8 due to inactivity. Let's let other contributors pick up the issue. :)

**Comment by mahajanparth** [comment]
Hello folks , Seems like a fun problem to solve . May i have a look at it ?

**Comment by p-wysocki** [comment]
Hello @mahajanparth, sure! Please let us know if you have any questions.

**Comment by michal-miotk** [comment]
Hi,
I am on commit e6dc08651284e9798bd5bb3383136563e3c401ed and changing in file transformations_pipeline.cpp::232 to  auto infer_precision = ov::element::f32; produces same image on gpu as on cpu

**Comment by mahajanparth** [comment]
@p-wysocki i can confirm the same. 
![Screenshot from 2024-03-13 12-04-21](https://github.com/openvinotoolkit/openvino/assets/32522286/3cd59b47-f7bf-4fe3-8951-afb16018bb7a)
![Screenshot from 2024-03-13 12-04-53](https://github.com/openvinotoolkit/openvino/assets/32522286/fafce148-8e06-4e9a-b287-55681861154b)
[main.zip](https://github.com/openvinotoolkit/openvino/files/14583363/main.zip)

Please find the main.ipynb for the perusual as well !
