### ISSUE TITLE
Two errors occured while using MO

### ISSUE THREAD

**Issue by ghost** [openvinotoolkit/openvino#220]
OpenVINO version: 2019 R1
TensorFlow version: 1.11.0

The first error is that:
```
[ ERROR ]  BiasAdd operation has unsupported `data_format`=NCHW
```
Then I add the `--disable_nhwc_to_nchw`, it still doesn't work.
Another error is that I have a `ToIn64` op in TensorFlow but the MO doesn't convert `int32` to `int64` so that it reports:
```
[ ERROR ]  Input 0 of node Lstm_cell/Block was passed int32 from Lstm_cell/ToInt64_port_0_ie_placeholder:0 incompatible with expected int64.
```
What should I do?

**Comment by shubha-ramani** [comment]
@ZhePang dldt github is a little bit behind. It would be worth it for you to try the latest release 2019R2. The dldt github will be updated soon with R2.

Please try again on R2 and if it fails, please attach a copy of your frozen model (I assume Tensorflow) as well as the exact Model Optimizer command which you used.

Also, if you can give us a bit of history about this model that would be helpful. What kind of model is it ? Is it your own or is it something downloadable on the Internet ?

Thanks kindly,

Shubha

**Comment by ZhePang** [comment]
Dear @shubha-ramani 
I try the 2019R2 but still encounter these errors. It seems that OpenVINO only supports `NHWC`   data format when processing tf model. But in my model, there are `NHWC` and `NCHW` .
Then I try to rewrite the `.pb` file to fix these problems. But it seems that my tf version is not same with the version which generated the `.pb` file. Do you have any ideas to read the data correctly?
Besides, it is a speech recognize model with custom LSTM ops but I'm sorry that this model is not allowed to be shared in public.

**Comment by shubha-ramani** [comment]
@ZhePang 
I appreciate your concern about not sharing the model publicly. There are ways to get around that but let me first answer your question. Inference Engine uses an internal layout of  NCHW actually. And every topology uses NCHW except for Tensorflow, which uses NHWC.  You do not need to tell Model Optimizer how to convert to NCHW, Model Optimizer inherently knows this when you call mo_tf.py . However if you pass in --input_shape to mo_tf.py then of course you must pass it in as [N,C,H,W]. 

Does this answer your question ? Please let me know if you are still stuck.

Thanks,

Shubha

**Comment by lazarevevgeny** [comment]
This issue has been fixed. Please, take the Model Optimizer from the master branch.
