### ISSUE TITLE
[Feature Request]: network XML visualization

### ISSUE THREAD

**Issue by hardingyan** [openvinotoolkit/openvino#22008]
### Request Description

How do I visualize a graph model XML file?

### Feature Use Case

I would like to see a visual representation of the xml file to better observe the network structure

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by andrei-kochin** [comment]
@hardingyan  does Netron solution works for you?

**Comment by avitial** [comment]
Closing this as it seems issue has been addressed. Feel free to reopen and ask additional questions related to this topic.
