### ISSUE TITLE
[Docs]: How to use  ov.core().read_model() with io.BytesIO?

### ISSUE THREAD

**Issue by AIgiraffe** [openvinotoolkit/openvino#22027]
### Documentation link

https://docs.openvino.ai/2022.3/api/ie_python_api/_autosummary/openvino.runtime.Core.html

### Description

when i use ov.core.read_model() with a io.BytesIO object, it throw a error of RuntimeError: Model file <_io.BytesIO object at 0x7fe722b46e00> cannot be opened!. how can i use the read_model correctly in the case

this is my code:
byte_object = io.BytesIO()
model = onnx.load(onnx_path)
onnx.save(model,byte_object)
byte_object.seek(0)
ov_model = ov.Core().read_model(byte_object)

### Issue submission checklist

- [X] I'm reporting a documentation issue. It's not a question.

**Comment by rkazants** [comment]
@kblaszczak-intel, please correct documentation for Python `read_model` that only supports a path to a model in IR / ONNX / PDPD / TF and TFLite format.

@slyalin, fyi.

Best regards,
Roman

**Comment by andrei-kochin** [comment]
Hello @AIgiraffe,

For io.BytesIO you can use convert_model + compile_model like following:

`
byte_object = io.BytesIO()
model = onnx.load(onnx_path)
onnx.save(model,byte_object)
byte_object.seek(0)
ov_model = ov.convert_model(byte_object)
compiled_model = ov.Core().compile_model(ov_model)
`

**Comment by AIgiraffe** [comment]
> Hello @AIgiraffe,
> 
> For io.BytesIO you can use convert_model + compile_model like following:
> 
> `byte_object = io.BytesIO() model = onnx.load(onnx_path) onnx.save(model,byte_object) byte_object.seek(0) ov_model = ov.convert_model(byte_object) compiled_model = ov.Core().compile_model(ov_model)`

thanks for your reply
