### ISSUE TITLE
A memory leak occurred after including afxwin.h

### ISSUE THREAD

**Issue by 994028510** [openvinotoolkit/openvino#22038]
I use openvino in a dll. This dll exports a class, in which ov::Core is a static variable and shared_ptr<ov::Model> is a common member variable. When read_model is used, leaks will occur. And this situation only occurs when the project calling this dll contains afxwin.h.
I tried calling shutdown() after DLL_PROCESS_DETACH, but it didn't work。
Is this my usage incorrect or a bug? How can I avoid it?

**Comment by 994028510** [comment]
[demo.zip](https://github.com/openvinotoolkit/openvino/files/13873095/demo.zip)
This is a simple demo, dll4 is a packaged openvino, ConsoleApplication1 uses dll4, calls the initialization function, and actually just uses read_model to read the onnx file. When ConsoleApplication1 uses mfc and includes afxwin.h, a memory leak will occur.
Compiled using vs2022, this is the debugging result:
Detected memory leaks!
Dumping objects ->
{424841} normal block at 0x000001500A63BD40, 16 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF 
{424840} normal block at 0x000001500A63B700, 16 bytes long.
 Data: <                > C8 06 9A 8C F8 7F 00 00 00 00 00 00 00 00 00 00 
{4709} normal block at 0x000001506AE8F7F0, 16 bytes long.
 Data: <   jP           > C0 E6 E8 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{4708} normal block at 0x000001506AE8E6B0, 72 bytes long.
 Data: <`  jP   `  jP   > 60 DF E8 6A 50 01 00 00 60 DF E8 6A 50 01 00 00 
{4707} normal block at 0x000001506AE516E0, 128 bytes long.
 Data: <`  jP   `  jP   > 60 DF E8 6A 50 01 00 00 60 DF E8 6A 50 01 00 00 
{4706} normal block at 0x000001506AE90470, 16 bytes long.
 Data: <                > 10 08 9A 8C F8 7F 00 00 00 00 00 00 00 00 00 00 
{4705} normal block at 0x000001506AE8DF60, 72 bytes long.
 Data: <   jP      jP   > B0 E6 E8 6A 50 01 00 00 B0 E6 E8 6A 50 01 00 00 
{4704} normal block at 0x000001506AE90240, 16 bytes long.
 Data: <                > F8 07 9A 8C F8 7F 00 00 00 00 00 00 00 00 00 00 
{4700} normal block at 0x000001506AE8A460, 24 bytes long.
 Data: <  9             > 08 04 39 8C F8 7F 00 00 01 00 00 00 01 00 00 00 
{2659} normal block at 0x000001506AE636B0, 16 bytes long.
 Data: <                > EA 0B 19 89 F8 7F 00 00 D0 02 DF 89 F8 7F 00 00 
{2658} normal block at 0x000001506AE639D0, 16 bytes long.
 Data: <`  jP           > 60 0F E5 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2657} normal block at 0x000001506AE50F60, 120 bytes long.
 Data: < 9 jP    6 jP   > D0 39 E6 6A 50 01 00 00 B0 36 E6 6A 50 01 00 00 
{2656} normal block at 0x000001506AE63660, 16 bytes long.
 Data: <                > D0 02 DF 89 F8 7F 00 00 00 00 00 00 00 00 00 00 
{2577} normal block at 0x000001506AE63D90, 16 bytes long.
 Data: < * jP           > 20 2A E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2576} normal block at 0x000001506AE63A70, 16 bytes long.
 Data: < ) jP           > F8 29 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2575} normal block at 0x000001506AE63D40, 16 bytes long.
 Data: < ) jP           > D0 29 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2574} normal block at 0x000001506AE629B0, 152 bytes long.
 Data: < * jP      jP   > 90 2A E6 6A 50 01 00 00 F0 20 E6 6A 50 01 00 00 
{2573} normal block at 0x000001506AE63020, 16 bytes long.
 Data: < # jP           > 20 23 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2572} normal block at 0x000001506AE635C0, 16 bytes long.
 Data: < " jP           > F8 22 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2571} normal block at 0x000001506AE638E0, 16 bytes long.
 Data: < " jP           > D0 22 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2570} normal block at 0x000001506AE622B0, 152 bytes long.
 Data: <   jP    # jP   > F0 20 E6 6A 50 01 00 00 90 23 E6 6A 50 01 00 00 
{2569} normal block at 0x000001506AE63570, 16 bytes long.
 Data: <`! jP           > 60 21 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2568} normal block at 0x000001506AE63CF0, 16 bytes long.
 Data: <8! jP           > 38 21 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2567} normal block at 0x000001506AE63340, 16 bytes long.
 Data: < ! jP           > 10 21 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2566} normal block at 0x000001506AE620F0, 152 bytes long.
 Data: < * jP    " jP   > 90 2A E6 6A 50 01 00 00 B0 22 E6 6A 50 01 00 00 
{2565} normal block at 0x000001506AE63200, 16 bytes long.
 Data: < $ jP           > 00 24 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2564} normal block at 0x000001506AE63DE0, 16 bytes long.
 Data: < # jP           > D8 23 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2563} normal block at 0x000001506AE51E70, 16 bytes long.
 Data: < # jP           > B0 23 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2562} normal block at 0x000001506AE62390, 152 bytes long.
 Data: <   jP    * jP   > 10 20 E6 6A 50 01 00 00 90 2A E6 6A 50 01 00 00 
{2561} normal block at 0x000001506AE3A770, 16 bytes long.
 Data: <   jP           > 80 20 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2560} normal block at 0x000001506AE426C0, 16 bytes long.
 Data: <X  jP           > 58 20 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2559} normal block at 0x000001506AE429E0, 16 bytes long.
 Data: <0  jP           > 30 20 E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2558} normal block at 0x000001506AE62010, 152 bytes long.
 Data: < * jP    # jP   > 90 2A E6 6A 50 01 00 00 90 23 E6 6A 50 01 00 00 
{2557} normal block at 0x000001506AE42530, 16 bytes long.
 Data: < , jP           > C0 2C E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2556} normal block at 0x000001506AE424E0, 16 bytes long.
 Data: < , jP           > 98 2C E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2555} normal block at 0x000001506AE42DF0, 16 bytes long.
 Data: <p, jP           > 70 2C E6 6A 50 01 00 00 00 00 00 00 00 00 00 00 
{2554} normal block at 0x000001506AE62C50, 152 bytes long.
 Data: < * jP    " jP   > 90 2A E6 6A 50 01 00 00 B0 22 E6 6A 50 01 00 00 
{2553} normal block at 0x000001506AE62A90, 152 bytes long.
 Data: <   jP    # jP   > 10 20 E6 6A 50 01 00 00 90 23 E6 6A 50 01 00 00 
{2552} normal block at 0x000001506AE42440, 16 bytes long.
 Data: <                > D0 07 9A 8C F8 7F 00 00 00 00 00 00 00 00 00 00 
Object dump complete.
程序“[25916] ConsoleApplication1.exe”已退出，返回值为 0 (0x0)。

**Comment by vurusovs** [comment]
@994028510 unfortunately, `CrtDumpMemoryLeaks()` treats any object that still alive as memory leaks, even global/static objects with long lifetime, so we can't rely on such report as valid. Please, find more details in https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/OpenVINO-seems-to-leak-memory/m-p/1508558/highlight/true#M29868

More details about how we are tracking memory leaks may be found here: https://github.com/openvinotoolkit/openvino/blob/master/docs/articles_en/openvino_workflow/running_inference_with_openvino/dldt_deployment_optimization_guide/memory_optimization_guide.rst?plain=1#L30-L34

**Comment by vurusovs** [comment]
@994028510 I'm closing the issue, feel free to reopen or create new one if you have more questions
