### ISSUE TITLE
[Good First Issue][TF FE]: Fix IndexError list index out of range for Squeeze

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#22078]
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.2/openvino_docs_ops_opset13.html).

We have 23 models from TensorFlow Hub that are failing due to issue `IndexError list index out of range for Squeeze`. Your fix greatly helps to make OpenVINO better.

### What needs to be done?

The task is to fix a problem `IndexError list index out of range for Squeeze`.

How to reproduce the issue:
1. Build OpenVINO following [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md) document
2. Install built `openvino-*.whl` package using `pip`. You can find the package in `openvino/build/wheels` directory. Do not install `openvino-dev-*.whl` package. Also, it is recommended to use new virtual environment to avoid mess with previously installed OV packages in the system.
3. Run the model conversion as follows:

```
import tensorflow_hub as hub
import openvino as ov

model_link='https://www.kaggle.com/models/google/delf/frameworks/tensorFlow1/variations/delf/versions/1'
model = hub.load(model_link)

ov.convert_model(model)
```

Received error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openvino/tools/ovc/convert.py", line 101, in convert_model
    ov_model, _ = _convert(cli_parser, params, True)
  File "openvino/tools/ovc/convert_impl.py", line 534, in _convert
    raise e
  File "openvino/tools/ovc/convert_impl.py", line 476, in _convert
    ov_model = driver(argv, {"conversion_parameters": non_default_params})
  File "openvino/tools/ovc/convert_impl.py", line 227, in driver
    ov_model = moc_emit_ir(prepare_ir(argv), argv)
  File "openvino/tools/ovc/convert_impl.py", line 177, in prepare_ir
    ov_model = moc_pipeline(argv, moc_front_end)
  File "openvino/tools/ovc/moc_frontend/pipeline.py", line 244, in moc_pipeline
    ov_model = moc_front_end.convert(input_model)
  File "openvino/frontend/frontend.py", line 18, in convert
    converted_model = super().convert(model)
openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at src/frontends/tensorflow/src/frontend.cpp:428:
FrontEnd API failed with OpConversionFailure:
[TensorFlow Frontend] Internal error, conversion is failed for Squeeze operation with a message:
IndexError: list index out of range

At:
  openvino/frontend/tensorflow/node_decoder.py(39): tf_attr_to_numpy
  openvino/frontend/tensorflow/node_decoder.py(46): tf_attr_to_ov
  openvino/frontend/tensorflow/node_decoder.py(167): get_attribute
  openvino/frontend/frontend.py(18): convert
  openvino/tools/ovc/moc_frontend/pipeline.py(244): moc_pipeline
  openvino/tools/ovc/convert_impl.py(177): prepare_ir
  openvino/tools/ovc/convert_impl.py(227): driver
  openvino/tools/ovc/convert_impl.py(476): _convert
  openvino/tools/ovc/convert.py(101): convert_model
  <stdin>(1): <module>
```

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@openvinotoolkit/openvino-tf-frontend-maintainers

**Comment by abhinav231-valisetti** [comment]
@rkazants  If no one has been assigned yet, could I work on this issue?

**Comment by rkazants** [comment]
Hi @abhinav231-valisetti, sure. The task is yours.

Best regards,
Roman

**Comment by rkazants** [comment]
Fyi, please use new link to join [Intel DevHub Discord server](https://discord.gg/7pVRxUwdWG), if you have not yet joined. The previous one is outdated.

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @abhinav231-valisetti, do you have any update on this task? Please let me know in case questions and you can create a preliminary PR to discuss.

Best regards,
Roman

**Comment by abhinav231-valisetti** [comment]
Hi @rkazants, I encountered some issues while building the project on Windows, but I finally managed to resolve them with a few workarounds. Now, I'm facing a new challenge: debugging **.pyd files** generated by **CPython**. I've tried delving into the extensive C++ code and rebuilding it, but it's quite a complex and time taking task. Do you have any simpler methods or strategies for debugging .pyd files? Any guidance would be greatly appreciated.

**Comment by abhinav231-valisetti** [comment]
Hello @rkazants, I have addressed the current issue, and the bug fix seems to be effective for the link provided in the example. Could you please share links for other models so I can verify the accuracy of the fix?

**Comment by rkazants** [comment]
> Hello @rkazants, I have addressed the current issue, and the bug fix seems to be effective for the tensorflow Model link provided in the example. Could you please share links for other models so I can verify the accuracy of the fix?

Hi @abhinav231-valisetti, sounds great. Take a look at this list of models https://github.com/openvinotoolkit/openvino/blob/master/tests/model_hub_tests/tf_hub_tests/nightly_models, where you can find models failing due to "IndexError list index out of range for Squeeze". Of course, some of them can start to fail due to different reason and it is a separate story to fix:)

Best regards,
Roman

**Comment by abhinav231-valisetti** [comment]
Hi @rkazants Thank you for the resource, I will run the tests and create a PR asap.

**Comment by abhinav231-valisetti** [comment]
Hi @rkazants , To fix this bug, I have modified the code in the **openvino-*.whl** file, which is a Python library. However, this wheel file was generated after building it using CMake. I am looking for guidance to locate the exact files that need to be modified, so that when I rebuild the project, the updated code is included in the openvino-*.whl file.

**Comment by rkazants** [comment]
Hi @abhinav231-valisetti, you can find this file here: https://github.com/openvinotoolkit/openvino/tree/master/src/bindings/python/src/openvino/frontend/tensorflow. Please create PR with your changes.

Best regards,
Roman

**Comment by rkazants** [comment]
@abhinav231-valisetti, congratulations, your PR was merged.

Best regards,
Roman

**Comment by abhinav231-valisetti** [comment]
Thank you, @rkazants, for all the guidance throughout the process.
