### ISSUE TITLE
[Good First Issue]: Support aten::mv for pytorch models

### ISSUE THREAD

**Issue by mvafin** [openvinotoolkit/openvino#22073]
### Context

OpenVINO component responsible for support of PyTorch models is called as PyTorch Frontend (PT FE). PT FE converts a model represented as TorchScript model to a model in [OpenVINO opset](https://docs.openvino.ai/latest/openvino_docs_ops_opset.html).

### What needs to be done?

- Implement conversion rule and/or transformation to support the new operation.
- Implement operation tests in tests/layer_tests/pytorch_tests. Please consider different data types, but keep reasonable number of test cases

### Example Pull Requests

#18998

### Resources

- [torch.mv description](https://pytorch.org/docs/stable/generated/torch.mv.html)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO PyTorch Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/pytorch/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-pytorch-frontend-maintainers 

### Ticket

TBD

**Comment by Sar2580P** [comment]
.take

**Comment by rkazants** [comment]
Fyi, please use new link to join [Intel DevHub Discord server](https://discord.gg/7pVRxUwdWG), if you have not yet joined. The previous one is outdated.

Best regards,
Roman

**Comment by Aryan8912** [comment]
I am working on one issue and My PR is going for review so can I work on this issue if yes please assign it to me

**Comment by Aryan8912** [comment]
I am working on this issue, give one days I will update by tomorrow
