### ISSUE TITLE
[Good First Issue][TF FE]: Fix (AttributeError) NoneType object has no attribute shape or dtype

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#22076]
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.2/openvino_docs_ops_opset13.html).

We have 14 models from TensorFlow Hub that are failing due to issue `AttributeError: NoneType object has no attribute shape or dtype`. Your fix greatly helps to make OpenVINO better.

### What needs to be done?

The task is to fix a problem `AttributeError: NoneType object has no attribute shape or dtype`.

How to reproduce the issue:
1. Build OpenVINO following [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md) document
2. Install built `openvino-*.whl` package using `pip`. You can find the package in `openvino/build/wheels` directory. Do not install `openvino-dev-*.whl` package. Also, it is recommended to use new virtual environment to avoid mess with previously installed OV packages in the system.
3. Run the model conversion as follows:

```
import tensorflow_hub as hub
import openvino as ov

model_link = 'https://www.kaggle.com/models/google/gnews-swivel/frameworks/tensorFlow2/variations/tf2-preview-20dim/versions/1'
model = hub.load(model_link)

ov.convert_model(model)
```

Received error message:

```
  File "<stdin>", line 1, in <module>
  File "openvino/tools/ovc/convert.py", line 101, in convert_model
    ov_model, _ = _convert(cli_parser, params, True)
  File "openvino/tools/ovc/convert_impl.py", line 534, in _convert
    raise e
  File "openvino/tools/ovc/convert_impl.py", line 476, in _convert
    ov_model = driver(argv, {"conversion_parameters": non_default_params})
  File "openvino/tools/ovc/convert_impl.py", line 227, in driver
    ov_model = moc_emit_ir(prepare_ir(argv), argv)
  File "openvino/tools/ovc/convert_impl.py", line 177, in prepare_ir
    ov_model = moc_pipeline(argv, moc_front_end)
  File "openvino/tools/ovc/moc_frontend/pipeline.py", line 64, in moc_pipeline
    input_model = moc_front_end.load(argv.input_model, share_weights)
RuntimeError: Check 'false' failed at src/frontends/common/src/frontend.cpp:47:
Loading input model
AttributeError: 'NoneType' object has no attribute 'dtype'

At:
  openvino/frontend/tensorflow/node_decoder.py(149): get_attribute
  openvino/tools/ovc/moc_frontend/pipeline.py(64): moc_pipeline
  openvino/tools/ovc/convert_impl.py(177): prepare_ir
  openvino/tools/ovc/convert_impl.py(227): driver
  openvino/tools/ovc/convert_impl.py(476): _convert
  openvino/tools/ovc/convert.py(101): convert_model
  <stdin>(1): <module>
```

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@openvinotoolkit/openvino-tf-frontend-maintainers

**Comment by RitikaxShakya** [comment]
Hello! Discord invite link is not working.

**Comment by rkazants** [comment]
> Hello! Discord invite link is not working. Also I would like to discuss more about this issue.

Hi @RitikaxShakya, try to use this one regenerated link: https://discord.gg/xhcYcs3M. Shall I assign this task to you?

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @RitikaxShakya, you can ask your question here. Do you take this issue?

Best regards,
Roman

**Comment by vikasgrewal16** [comment]
i want to try this issue can you please assign it to me ?

**Comment by abhinav231-valisetti** [comment]
Hi @vikasgrewal16, your insights on this issue would be helpful for me.

**Comment by rkazants** [comment]
Fyi, please use new link to join [Intel DevHub Discord server](https://discord.gg/7pVRxUwdWG), if you have not yet joined. The previous one is outdated.

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @vikasgrewal16, do you have any update on this task? Please let me know in case questions and you can create a preliminary PR to discuss.

Best regards,
Roman

**Comment by vikasgrewal16** [comment]
Hi @rkazants I am not able to build this on my windows laptop as cmake command is getting me into trouble because i have already tried different generators of Visual Studio as well as Ninja but I am not able to build this project locally.

**Comment by rkazants** [comment]
> Hi @rkazants I am not able to build this on my windows laptop as cmake command is getting me into trouble because i have already tried different generators of Visual Studio as well as Ninja but I am not able to build this project locally.

I am also using Windows and VS. I use MSVS2019. Just try to strictly follow prerequisites and instructions from here: https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_windows.md.

Please also share build error logs.

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @vikasgrewal16, any update on this task?

**Comment by rkazants** [comment]
Hi @vikasgrewal16, any update on this task? Take a look at the fix for `IndexError` issue: https://github.com/openvinotoolkit/openvino/pull/22326

Best regards,
Roman

**Comment by abhinav231-valisetti** [comment]
Hi @rkazants could I work on this issue?

**Comment by rkazants** [comment]
> Hi @rkazants could I work on this issue?

Hi @abhinav231-valisetti, okay, agree since you are already familiar with quite similar bug. The task is yours.

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @abhinav231-valisetti, @vikasgrewal16, any update on the fix?

Best regards,
Roman

**Comment by abhinav231-valisetti** [comment]
Hi @rkazants I have started working on this issue but i am having trouble while handling the following case,
`variable_value = TFGraphNodeDecoder.get_variable(self.m_operation)
if variable_value is None:
          return OVAny(Type.undefined)`

I implemented a check to ensure that the returned variable value is not `None` before attempting to access its `dtype`. In cases where it returns None, I added a statement to return `OVany(Type.undefined)`. However, I am encountering the following error after incorporating this condition.

`openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at src\frontends\tensorflow\src\frontend.cpp:429:
FrontEnd API failed with OpConversionFailure:
[TensorFlow Frontend] Internal error, no translator found for operation(s): Const of unknown type, LookupTableFindV2, LookupTableSizeV2, SparseFillEmptyRows, SparseSegmentSqrtN, StaticRegexReplace, StringSplit, StringToHashBucketFast
To facilitate the conversion of unsupported operations, refer to Frontend Extension documentation: https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Frontend_Extensions.html`

**Comment by rkazants** [comment]
Hi @abhinav231-valisetti,

Your solution is sufficient. Please post PR with this fix.
The error you received is a different story and it just requires translators for new operations.

Best regards,
Roman

**Comment by rkazants** [comment]
PR: https://github.com/openvinotoolkit/openvino/pull/22813

**Comment by yangchengxin** [comment]
i met this bug when i converted the pth model to xml model, how can i fix this bug, i am looking forward to your reply, thank you
> RuntimeError: Check 'false' failed at src\frontends\common\src\frontend.cpp:47:
Loading input model
AttributeError: 'torch._C.TensorType' object has no attribute 'dtype'

**Comment by rkazants** [comment]
> i met this bug when i converted the pth model to xml model, how can i fix this bug, i am looking forward to your reply, thank you
> 
> > RuntimeError: Check 'false' failed at src\frontends\common\src\frontend.cpp:47:
> > Loading input model
> > AttributeError: 'torch._C.TensorType' object has no attribute 'dtype'

@yangchengxin, I believe this is a separate bug for PyTorch frontend. Can you provide a reproducer for this?
@mvafin, fyi.

Best regards,
Roman

**Comment by yangchengxin** [comment]
> > i met this bug when i converted the pth model to xml model, how can i fix this bug, i am looking forward to your reply, thank you
> > > RuntimeError: Check 'false' failed at src\frontends\common\src\frontend.cpp:47:
> > > Loading input model
> > > AttributeError: 'torch._C.TensorType' object has no attribute 'dtype'
> 
> @yangchengxin, I believe this is a separate bug for PyTorch frontend. Can you provide a reproducer for this? @mvafin, fyi.
> 
> Best regards, Roman

thanks for your reply! Does it mean the version of pytorch is in compatible? my pytorch version is 1.10.0 and my torchvision version is 0.11.0. And i don't really understand what is the reproducer.

**Comment by yangchengxin** [comment]
ok, I will follow your reaponse, thanks



---- Replied Message ----
| From | Maxim ***@***.***> |
| Date | 02/22/2024 20:25 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [openvinotoolkit/openvino] [Good First Issue][TF FE]: Fix (AttributeError) NoneType object has no attribute shape or dtype (Issue #22076) |

@yangchengxin Yes, we do not support torch 1.10, please update to torch>=2.0

**Comment by yangchengxin** [comment]
@mvafin @rkazants Most thanks for both of you！i have fix the problem under the environment of torch=2.0.1, openvino=2023.1.0
