### ISSUE TITLE
[Good First Issue][TF FE]: Support Angle operation for TensorFlow models

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#22083]
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.1/openvino_docs_ops_opset.html).

In order to infer TensorFlow models with [Angle](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Angle) operation by OpenVINO, TF FE needs to be extended with this operation support.

### What needs to be done?

For [Angle](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Angle) operation support, you need to implement the corresponding loader into TF FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of TensorFlow operation.

Here is an example of loader implementation for TensorFlow `Einsum` operation:

```cpp
OutputVector translate_einsum_op(const NodeContext& node) { 
     auto op_type = node.get_op_type(); 
     TENSORFLOW_OP_VALIDATION(node, op_type == "Einsum", "Internal error: incorrect usage of translate_einsum_op."); 
     auto equation = node.get_attribute<std::string>("equation"); 
  
     OutputVector inputs; 
     for (size_t input_ind = 0; input_ind < node.get_input_size(); ++input_ind) { 
         inputs.push_back(node.get_input(input_ind)); 
     } 
  
     auto einsum = make_shared<Einsum>(inputs, equation); 
     set_node_name(node.get_name(), einsum); 
     return {einsum}; 
 } 
```

In this example, `translate_einsum_op` converts TF `Einsum` into OV `Einsum`. `NodeContext` object passed into the loader packs all info about inputs and attributes of `Einsum` operation. The loader retrieves an attribute of the equation by using the `NodeContext::get_attribute()` method, prepares input vector, creates `Einsum` operation from OV opset and returns a vector of outputs.

Responsibility of a loader is to parse operation attributes, prepare inputs and express TF operation via OV operations sub-graph. Example for `Einsum` demonstrates the resulted sub-graph with one operation. In PR https://github.com/openvinotoolkit/openvino/pull/19007 you can see operation decomposition into multiple node sub-graph.

Once you are done with implementation of the translator, you need to implement the corresponding layer tests `test_tf_ApproximateEqual.py` and put it into [layer_tests/tensorflow_tests](https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/tensorflow_tests) directory. Example how to run some layer test:

```
export TEST_DEVICE=CPU
cd openvino/tests/layer_tests/tensorflow_tests
pytest test_tf_Shape.py -m use_new_frontend
```

### Hint

OpenVINO does not support directly complex tensors. For supporting this, we use `ComplexTypeMark` that loader for `Angle` should resolve it or remove this mark so the output will not have this mark after translation. Input complex tensor to `Angle` is represented as floating-point tensor having additional dimension in the tail to contain real and imaginary parts. See examples of support complex tensors by `ComplexAbs` loader from https://github.com/openvinotoolkit/openvino/pull/20860.

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/20860
- https://github.com/openvinotoolkit/openvino/pull/21076
- https://github.com/openvinotoolkit/openvino/pull/19007

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@openvinotoolkit/openvino-tf-frontend-maintainers

**Comment by harryhritik12** [comment]
Hey I Would Like to contribute on this .

**Comment by rkazants** [comment]
Hi @harryhritik12, sure. The task is yours.

Best regards,
Roman

**Comment by rkazants** [comment]
Fyi, please use new link to join [Intel DevHub Discord server](https://discord.gg/7pVRxUwdWG). The previous one is outdated.

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @harryhritik12, do you have any update on this task? Please let me know in case questions and you can create a preliminary PR to discuss.

Best regards,
Roman

**Comment by harryhritik12** [comment]
yes, I am testing  it .

**Comment by rkazants** [comment]
Hi @harryhritik12, any update on this task?

**Comment by harryhritik12** [comment]
There is an Error in my approach I am try to fix it.

**Comment by harryhritik12** [comment]
Hey , I  think I fix an Error now How to check whether  program work or not?

**Comment by rkazants** [comment]
> Hey , I think I fix an Error now How to check whether program work or not. Basically how test?

Please implement a layer test. You can find details about the layer test in the ticket description.

Best regards,
Roman

**Comment by harryhritik12** [comment]
Respected Sir,

I hope this email finds you well. I am writing to inform you about an issue
I recently encountered with my motherboard. Unfortunately, it seems to have
malfunctioned, and after consulting with the support team, I was informed
that it will take approximately three days weeks to replace  or more.

**Comment by rkazants** [comment]
Hi @harryhritik12, any update on this task?

Best regards,
Roman

**Comment by ViswanathBalla22** [comment]
Hi @rkazants I want solve this issue . @harryhritik12 are you working on this issue ? or can you Assignees
 I will solve this issue

**Comment by ViswanathBalla22** [comment]
.take

**Comment by harryhritik12** [comment]
@ViswanathBalla22  go for it.

**Comment by rkazants** [comment]
This GFI is free

**Comment by rghvsh** [comment]
.take

**Comment by rghvsh** [comment]
Hey, @rkazants! Since we already implemented atan2 can we use that or do the different conditions be hardcoded.

Thanks
Raghav

**Comment by rkazants** [comment]
> Hey, @rkazants! Since we already implemented atan2 can we use that or do the different conditions be hardcoded.
> 
> Thanks Raghav

Hi @rghvsh, sure, you can use your knowledge gained for aten2. Try not to think about duplicate code at the first step and just implement `Angle` support. On the second step we can try to avoid the duplication if any. 

Best regards,
Roman

**Comment by rghvsh** [comment]
#23028
