### ISSUE TITLE
[Good First Issue][TF FE]: Support ApproximateEqual operation for TensorFlow

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#22082]
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.2/openvino_docs_ops_opset13.html).

In order to infer TensorFlow Hub models with [ApproximateEqual](https://www.tensorflow.org/api_docs/python/tf/raw_ops/ApproximateEqual) operation by OpenVINO, TF FE needs to be extended with this operation support.

### What needs to be done?

For [ApproximateEqual](https://www.tensorflow.org/api_docs/python/tf/raw_ops/ApproximateEqual) operation support, you need to implement the corresponding loader into TF FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of TensorFlow operation.

Here is an example of loader implementation for TensorFlow `Einsum` operation:

```cpp
OutputVector translate_einsum_op(const NodeContext& node) { 
     auto op_type = node.get_op_type(); 
     TENSORFLOW_OP_VALIDATION(node, op_type == "Einsum", "Internal error: incorrect usage of translate_einsum_op."); 
     auto equation = node.get_attribute<std::string>("equation"); 
  
     OutputVector inputs; 
     for (size_t input_ind = 0; input_ind < node.get_input_size(); ++input_ind) { 
         inputs.push_back(node.get_input(input_ind)); 
     } 
  
     auto einsum = make_shared<Einsum>(inputs, equation); 
     set_node_name(node.get_name(), einsum); 
     return {einsum}; 
 } 
```

In this example, `translate_einsum_op` converts TF `Einsum` into OV `Einsum`. `NodeContext` object passed into the loader packs all info about inputs and attributes of `Einsum` operation. The loader retrieves an attribute of the equation by using the `NodeContext::get_attribute()` method, prepares input vector, creates `Einsum` operation from OV opset and returns a vector of outputs.

Responsibility of a loader is to parse operation attributes, prepare inputs and express TF operation via OV operations sub-graph. Example for `Einsum` demonstrates the resulted sub-graph with one operation. In PR https://github.com/openvinotoolkit/openvino/pull/19007 you can see operation decomposition into multiple node sub-graph.

Once you are done with implementation of the translator, you need to implement the corresponding layer tests `test_tf_ApproximateEqual.py` and put it into [layer_tests/tensorflow_tests](https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/tensorflow_tests) directory. Example how to run some layer test:

```
export TEST_DEVICE=CPU
cd openvino/tests/layer_tests/tensorflow_tests
pytest test_tf_Shape.py -m use_new_frontend
```

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/19007

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@openvinotoolkit/openvino-tf-frontend-maintainers

**Comment by Sar2580P** [comment]
.take

**Comment by Sar2580P** [comment]
I'll let you know if any updates or help is needed.

**Comment by rkazants** [comment]
Fyi, please use new link to join [Intel DevHub Discord server](https://discord.gg/7pVRxUwdWG), if you have not yet joined. The previous one is outdated.

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @Sar2580P, do you have any update on this task? Please let me know in case questions and you can create a preliminary PR to discuss.

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @Sar2580P, any update on this task?

**Comment by ViswanathBalla22** [comment]
.take

**Comment by ViswanathBalla22** [comment]
Hi @rkazants,

I'm working on issue  and I want to confirm the approach. To resolve the issue, I've implemented changes in both C++ and Python code, creating new files as necessary. After making these changes, I plan to run the tests to ensure everything works as intended. Could you please confirm if this is the correct approach or provide any guidance?

**Comment by rkazants** [comment]
> Hi @rkazants,
> 
> I'm working on issue and I want to confirm the approach. To resolve the issue, I've implemented changes in both C++ and Python code, creating new files as necessary. After making these changes, I plan to run the tests to ensure everything works as intended. Could you please confirm if this is the correct approach or provide any guidance?

Your approach is correct. Python part is only for tests.

Best regards,
Roman

**Comment by rkazants** [comment]
> Hey @rkazants
> 
> I hope you're doing well. I'm currently facing an issue at the `cmake -G "Visual Studio 17 2022" <path/to/openvino>` step while building OpenVINO on Windows. I've carefully followed the instructions in 'build_windows.md' but haven't been able to resolve it. I've tried several solutions without success.
> 
> I appreciate any guidance or insights you can provide.

Hi @ViswanathBalla22, any update on this task.
I use the following cmake command for VS:

```
cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DENABLE_TESTS=ON ..
```

Just try to replace with your version of VS and remain other options as is.

Best regards,
Roman

**Comment by ViswanathBalla22** [comment]
hi @rkazants ,
         I have facing this issue while testing ===
 ERRORS  ERROR collecting tensorflow_tests/test_tf_approximate_equal.py ________________________________________________ 
ImportError while importing test module 'D:\OPENVINO\openvino\tests\layer_tests\tensorflow_tests\test_tf_approximate_equal.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\viswa\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_tf_approximate_equal.py:4: in <module>
    from common.tf_layer_test_class import CommonTestUtils
..\common\tf_layer_test_class.py:5: in <module>
    from common.utils.tf_utils import summarize_graph
..\common\utils\tf_utils.py:10: in <module>
    from openvino.tools.mo.ops.op import PermuteAttrs
E   ModuleNotFoundError: No module named 'openvino.tools.mo'

**Comment by ViswanathBalla22** [comment]
hi  @rkazants ,
        While testing I am getting this error 

  ERRORS ===========================
________________________________________________ ERROR collecting tensorflow_tests/test_tf_approximate_equal.py ________________________________________________ 
ImportError while importing test module 'D:\OPENVINO\openvino\tests\layer_tests\tensorflow_tests\test_tf_approximate_equal.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\viswa\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_tf_approximate_equal.py:4: in <module>
    from common.tf_layer_test_class import CommonTestUtils
E   ImportError: cannot import name 'CommonTestUtils' from 'common.tf_layer_test_class' (D:\OPENVINO\openvino\tests\layer_tests\common\tf_layer_test_class.py)

**Comment by ViswanathBalla22** [comment]
hi @rkazants @p-wysocki 
     while I am running test case I am getting this error I am unable to find how to resolve this 

 ________________________ ERROR collecting tensorflow_tests/test_tf_approximate_equal.py ________________________________________________ 
ImportError while importing test module 'D:\OPENVINO\openvino\tests\layer_tests\tensorflow_tests\test_tf_approximate_equal.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\viswa\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_tf_approximate_equal.py:4: in <module>
    from common.tf_layer_test_class import CommonTestUtils
E   ImportError: cannot import name 'CommonTestUtils' from 'common.tf_layer_test_class' (D:\OPENVINO\openvino\tests\layer_tests\common\tf_layer_test_class.py)

**Comment by ViswanathBalla22** [comment]
hi @rkazants 
        I send pr but it merging is blocked can I know what is reason any changes to be made.

**Comment by ViswanathBalla22** [comment]
hi @rkazants ,
I hope you're well. I encountered a small challenge while trying to push the latest changes for the "ApproximateEqual" implementation. After closing the initial pull request, I made some additional updates and now aim to submit a new pull request.

However, when attempting to push the changes, Git is reporting that everything is up-to-date.

**Comment by rkazants** [comment]
Hi @ViswanathBalla22, please prepare normal PR with relevant changes.

**Comment by MonalSD** [comment]
.take

**Comment by MonalSD** [comment]
Hi @rkazants raised the PR for the above issue. Please do take a look.
Thanks,
Monal
