### ISSUE TITLE
[Good First Issue][TF FE]: Support MatrixBandPart operation for TensorFlow Hub models

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#22081]
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.2/openvino_docs_ops_opset13.html).

In order to infer TensorFlow Hub models with [MatrixBandPart](https://www.tensorflow.org/api_docs/python/tf/raw_ops/MatrixBandPart) operation by OpenVINO, TF FE needs to be extended with this operation support.

We have 21 models from TF Hub containing this operation. Example:
- [wiki40b-lm-ro](https://www.kaggle.com/models/google/wiki40b-lm/frameworks/tensorFlow1/variations/ro/versions/1)

### What needs to be done?

For [MatrixBandPart](https://www.tensorflow.org/api_docs/python/tf/raw_ops/MatrixBandPart) operation support, you need to implement the corresponding loader into TF FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of TensorFlow operation.

Here is an example of loader implementation for TensorFlow `Einsum` operation:

```cpp
OutputVector translate_einsum_op(const NodeContext& node) { 
     auto op_type = node.get_op_type(); 
     TENSORFLOW_OP_VALIDATION(node, op_type == "Einsum", "Internal error: incorrect usage of translate_einsum_op."); 
     auto equation = node.get_attribute<std::string>("equation"); 
  
     OutputVector inputs; 
     for (size_t input_ind = 0; input_ind < node.get_input_size(); ++input_ind) { 
         inputs.push_back(node.get_input(input_ind)); 
     } 
  
     auto einsum = make_shared<Einsum>(inputs, equation); 
     set_node_name(node.get_name(), einsum); 
     return {einsum}; 
 } 
```

In this example, `translate_einsum_op` converts TF `Einsum` into OV `Einsum`. `NodeContext` object passed into the loader packs all info about inputs and attributes of `Einsum` operation. The loader retrieves an attribute of the equation by using the `NodeContext::get_attribute()` method, prepares input vector, creates `Einsum` operation from OV opset and returns a vector of outputs.

Responsibility of a loader is to parse operation attributes, prepare inputs and express TF operation via OV operations sub-graph. Example for `Einsum` demonstrates the resulted sub-graph with one operation. In PR https://github.com/openvinotoolkit/openvino/pull/19007 you can see operation decomposition into multiple node sub-graph.

Once you are done with implementation of the translator, you need to implement the corresponding layer tests `test_tf_MatrixBandPart.py` and put it into [layer_tests/tensorflow_tests](https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/tensorflow_tests) directory. Example how to run some layer test:

```
export TEST_DEVICE=CPU
cd openvino/tests/layer_tests/tensorflow_tests
pytest test_tf_Shape.py -m use_new_frontend
```

### Hint

`MatrixBandPart` operation requires decomposition using OV opset. The following idea is proposed to use for the decomposition but you may implement your more elegant and performance efficient idea:
1. Find sizes `m` and `n` of two last dimension of `input` and generate ranges `[0, m)` and `[0, n)`. Unsqueeze these ranges so that to have tensor of shapes `[m, 1]` and `[1, n]`
2. Using logical operations from OV opset such as `LogicalAnd`, `LogicalOr`, `LessEqual`, etc. compute `in_band` indicator function. Unsqueeze the indicator function to have a tensor of shape `[1,..,1, m, n]`. The further steps are clear.

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/19007

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@openvinotoolkit/openvino-tf-frontend-maintainers

**Comment by Sar2580P** [comment]
I would like to contribute to this issue, pls assign it to me.

**Comment by rkazants** [comment]
> I would like to contribute to this issue, pls assign it to me.

Hi @Sar2580P,
You have three other tickets. I propose you to complete them first. Don't worry we will open new tickets if this one will be busy at the moment when you are done with your current backlog.:)
So **let us leave this ticket available now**.

Best regards,
Roman

**Comment by rkazants** [comment]
Fyi, please use new link to join [Intel DevHub Discord server](https://discord.gg/7pVRxUwdWG), if you have not yet joined. The previous one is outdated.

Best regards,
Roman

**Comment by himanshugupta11002** [comment]
Hey, I want to contribute to this issue. Can you assign it to me

**Comment by rkazants** [comment]
> Hey, I want to contribute to this issue. Can you assign it to me

Hi @himanshugupta11002, sure. The task is yours.

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @himanshugupta11002, do you have any update on this task? Please let me know in case questions and you can create a preliminary PR to discuss.

Best regards,
Roman

**Comment by himanshugupta11002** [comment]
Hi, I am currently working on this but facing issue in registering it into the dictionary of loaders. I have implement' a MatrixBandPart code in TF FE op and while registering it into loader I have issue with the code. Can you help me with that. I will make a PR(asap) so you can see the changes.

**Comment by rkazants** [comment]
> Hi, I am currently working on this but facing issue in registering it into the dictionary of loaders. I have implement' a MatrixBandPart code in TF FE op and while registering it into loader I have issue with the code. Can you help me with that. I will make a PR(asap) so you can see the changes.

Is it a build issue or run-time? Share your logs and post PR with your preliminary changes.

**Comment by rkazants** [comment]
Hi @himanshugupta11002, any update on this task?

**Comment by AlexFierro9** [comment]
.take

**Comment by rkazants** [comment]
Hi @himanshugupta11002, any update on this task?
