### ISSUE TITLE
[Feature Request]: compile_model() add a new function to load a  ONNX model file in memory binary

### ISSUE THREAD

**Issue by Kaze816** [openvinotoolkit/openvino#22144]
### Request Description

the method interface maybe like this:   
 CompiledModel compile_model(const void* model_data, size_t model_data_length,
        const std::string& device_name,
        const AnyMap& properties = {});

### Feature Use Case

1, model data file can be decrypt in memory when needing 
2, run as a plugin parallel to onnxruntime which has such  interface.
（ Session::Session(const Env& env, const void* model_data, size_t model_data_length, const SessionOptions& options) ） 

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by ilya-lavrenov** [comment]
We already have similar method, which can read from memory:
https://github.com/openvinotoolkit/openvino/blob/53d7c501bd49209a8fc8a5f1cbfe1619c81312f3/src/inference/include/openvino/runtime/core.hpp#L295-L311

**Comment by Kaze816** [comment]
thanks to your answer, but "Reading ONNX/PDPD models does not support loading weights from the @p weights tensors."

when to support onnx?

**Comment by Kaze816** [comment]
> We already have similar method, which can read from memory:
> 
> https://github.com/openvinotoolkit/openvino/blob/53d7c501bd49209a8fc8a5f1cbfe1619c81312f3/src/inference/include/openvino/runtime/core.hpp#L295-L311

thanks to your answer, but "Reading ONNX/PDPD models does not support loading weights from the @p weights tensors."

when to support onnx?

**Comment by ilya-lavrenov** [comment]
@Kaze816 do you have a model with external weights?
If no `weights` can be empty.

**Comment by Kaze816** [comment]
if so,  will the onnx model_data be cutted  off  when converting to std::string?  @ilya-lavrenov

**Comment by andrei-kochin** [comment]
@Kaze816 do you need more clarifications?

**Comment by Kaze816** [comment]
> @Kaze816 do you have a model with external weights? If no `weights` can be empty.
I have tried following codes, which it seems run ok.
                ov::Core core;
                const std::string model((const char *)model_data, (const char*)model_data+ length);
                ov::Tensor weights;
                ov::CompiledModel compiled_model = core.compile_model(model, weights, "AUTO");  

Thank you very much!

**Comment by Kaze816** [comment]
> @Kaze816 do you need more clarifications?

no, thanks.  The question seems been killed.
