### ISSUE TITLE
[Good first issue] [API CONFORMANCE] [CPU PLUGIN] Support unsupported property EXECUTION_DEVICES  in CPU plugin

### ISSUE THREAD

**Issue by tiger100256-hu** [openvinotoolkit/openvino#22153]
## Description:
API conformance suite is OV validation tool checks a plugin conditions from API implementation perspective.
`ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={EXECUTION_DEVICES:}`  fails on `CPU` Plugin

### RO (ReadOnly):
* EXECUTION_DEVICES

## How to reproduce:
1. Build the OV using `-DENABLE_TESTS=ON -DENABLE_FUNACTIONAL_TESTS=ON -DENABLE_INTEL_CPU=ON`
2. Build `ov_api_conformance_tests` target
```
 ./ov_api_conformance_tests --gtest_filter="ov_plugin_mandatory/OVCheckGetSupportedRO
MetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={EXECUTION_DEVICES*"
Note: Google Test filter = ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={EXECUT
ION_DEVICES*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests
[ RUN      ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={EXECUTION_DEVICES:}

MEM_USAGE=47184KB
[ CONFORMANCE ] Influence coefficient: 1
src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp:356: Failure
Value of: supported
  Actual: false
Expected: true
property is not supported: EXECUTION_DEVICES
[  FAILED  ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={EXECUTION_DEVICES:},
 where GetParam() = ("CPU", { ("EXECUTION_DEVICES", ) }) (5 ms)
[----------] 1 test from ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests (5 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (5 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={EXECUTION_DEVICES:},
 where GetParam() = ("CPU", { ("EXECUTION_DEVICES", ) })

```

## How to fix
ov::intel_cpu::CompiledModel has already supported ov::execution_devices, so Only need to support it in ov::intel_cpu::Engine, Example PR https://github.com/openvinotoolkit/openvino/pull/22007

## Useful links:
* [Intel DevHub Discord channel](https://discord.gg/wPuqAujS) - engage in discussions, ask questions and talk to OpenVINO developers
* [Conformance readme](https://github.com/openvinotoolkit/openvino/tree/master/src/tests/functional/plugin/conformance/test_runner)
* [CPU plugin](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/README.md)
* [OV CONTRIBUTION GUIDE](https://github.com/openvinotoolkit/openvino/tree/master/?tab=readme-ov-file#how-to-contribute)
* [PROPERIES Description](https://docs.openvino.ai/2023.2/groupov_runtime_cpp_prop_api.html)
* [EXECUTION_DEVICES](https://github.com/openvinotoolkit/openvino/blob/7c37e0916c6cc2c4df14877c10346a9cbbf844bd/src/inference/include/openvino/runtime/properties.hpp#L1159)

## Contacts:
* @tiger100256-hu

**Comment by lukazlim** [comment]
.take

**Comment by lukazlim** [comment]
Hi @tiger100256-hu ,

I've also noticed that the properties DEVICE_ARCHITECTURE and DEVICE_TYPE are also not supported in the CPU plugin:
```
./ov_api_conformance_tests --gtest_filter="ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties*"
Note: Google Test filter = ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties*
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests
[ RUN      ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={FULL_DEVICE_NAME:}

MEM_USAGE=45584KB
[ CONFORMANCE ] Influence coefficient: 1
[       OK ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={FULL_DEVICE_NAME:} (41 ms)
[ RUN      ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={DEVICE_ARCHITECTURE:}

MEM_USAGE=130176KB
[ CONFORMANCE ] Influence coefficient: 1
src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp:434: Failure
Value of: supported
  Actual: false
Expected: true
property is not supported: DEVICE_ARCHITECTURE
[  FAILED  ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={DEVICE_ARCHITECTURE:}, where GetParam() = ("CPU", { ("DEVICE_ARCHITECTURE", ) }) (8 ms)
[ RUN      ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={DEVICE_TYPE:}

MEM_USAGE=130248KB
[ CONFORMANCE ] Influence coefficient: 1
src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp:434: Failure
Value of: supported
  Actual: false
Expected: true
property is not supported: DEVICE_TYPE
[  FAILED  ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={DEVICE_TYPE:}, where GetParam() = ("CPU", { ("DEVICE_TYPE", ) }) (7 ms)
[ RUN      ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={EXECUTION_DEVICES:}

MEM_USAGE=130248KB
[ CONFORMANCE ] Influence coefficient: 1
[       OK ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={EXECUTION_DEVICES:} (7 ms)
[----------] 4 tests from ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests (63 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (63 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={DEVICE_ARCHITECTURE:}, where GetParam() = ("CPU", { ("DEVICE_ARCHITECTURE", ) })
[  FAILED  ] ov_plugin_mandatory/OVCheckGetSupportedROMetricsPropsTests.ChangeCorrectProperties/target_device=CPU_properties={DEVICE_TYPE:}, where GetParam() = ("CPU", { ("DEVICE_TYPE", ) })

 2 FAILED TESTS
```
Since those failures are similar to this issue, I can also take a look at them if a fix is not being worked on yet.

Also, is the following correct?
DEVICE_ARCHITECTURE = ov::device::architecture
DEVICE_TYPE = ov::device::type

**Comment by tiger100256-hu** [comment]
@lukazlim yes, thanks very much, the fix is not being worked yet. this is the code about the two properties
 https://github.com/openvinotoolkit/openvino/blob/637920ce9154f47ca2c1992753406d8dbca39649/src/inference/include/openvino/runtime/properties.hpp#L840
https://github.com/openvinotoolkit/openvino/blob/637920ce9154f47ca2c1992753406d8dbca39649/src/inference/include/openvino/runtime/properties.hpp#L959

**Comment by lukazlim** [comment]
Alright thanks, I will take a look on those

**Comment by lukazlim** [comment]
Must it also be supported in src/plugins/intel_cpu/src/compiled_model.cpp? I see that compiled_model.cpp does not have any mentions of ov::device::* properties

**Comment by tiger100256-hu** [comment]
@lukazlim  only need to support them in ov::intel_cpu::Engine, thanks very much.

**Comment by lukazlim** [comment]
I have created a pull request for supporting DEVICE_TYPE and DEVICE_ARCHITECTURE in CPU
https://github.com/openvinotoolkit/openvino/pull/22374

Regarding DEVICE_ARCHITECTURE property, instead of using preprocessor directives, are there any classes in the OV code that retrieves the device architecture?
