### ISSUE TITLE
[Good First Issue] [NNCF] Introduce NNCF-specific exception classes across NNCF code base for expected/avoidable error cases instead of standard `RuntimeError`

### ISSUE THREAD

**Issue by vshampor** [openvinotoolkit/openvino#22192]
## Context
Historically, [NNCF](https://github.com/openvinotoolkit/nncf) development has used standard `RuntimeError` or `ValueError` exception classes for all exception-throwing purposes. At this point in development, however, we need to be able to discern between error states that originated due to a misconfiguration on part of the user (e.g. an API call with a combination of parameters which is known beforehand to be invalid) and therefore "expected" in a sense, and error states that were truly unexpected to the NNCF developers as well.

Consider, for instance:
https://github.com/openvinotoolkit/nncf/blob/8dd593e20222993fee09dd80f245850353f1493a/nncf/quantization/algorithms/min_max/algorithm.py#L192-L209

```python3
    def _review_defaults_based_on_mode(self):
        """
        Reviews default values because mode option doesn't support them.
        """
        nncf_logger.warning(f"You're using experimental option mode with {self._mode} value.")

        if self._preset != QuantizationPreset.PERFORMANCE:
            raise RuntimeError(f"preset option with {self._preset} value is not supported with the mode option!")

        if self._target_device not in [TargetDevice.CPU, TargetDevice.ANY]:
            raise RuntimeError(
                f"target_device option with {self._target_device} value is not supported with the mode option!"
            )

        if self._overflow_fix != OverflowFix.DISABLE:
            raise RuntimeError(
                f"overflow_fix option with {self._overflow_fix} value is not supported with the mode option!"
            )
# ...
```
The three conditions above check the consistency of the parameters passed to this point in code from an `nncf.quantize(...)` call, which is a documented API function that, ideally, specifies that certain API parameter combinations are incompatible with each other - hence the checks. However, in the failure cases the code throws Python built-in `RuntimeError` exceptions, and because of that, the user cannot effectively distinguish (and handle) the error state that has arisen due to this particular reason, and, for example, cases when an unforeseen overflow, timeout or resource unavailability forced the NNCF execution to halt abnormally. The code below is currently impossible to be written:
```python
try:
    nncf.quantize(/* some_param_set */)
except ???:  # cannot write this exception branch for "expected" errors only since almost all exceptions 
             # are RuntimeErrors, including the "unexpected" ones.
    print("Looks like the parameters to nncf.quantize were wrong to begin with")
except RuntimeError:
    print("Something really unexpected happened")
```

The solution to this problem would be to raise NNCF-specific exceptions instead of Python built-in ones, e.g. in the original code we would have:
```python3
        if self._preset != QuantizationPreset.PERFORMANCE:
            # suppose we only use nncf.ValidationError when raising errors due to failing internal 
            # validation checks of the user-supplied parameters
            raise nncf.ValidationError(f"preset option with {self._preset} value is not supported with the mode option!")

        if self._target_device not in [TargetDevice.CPU, TargetDevice.ANY]:
            raise nncf.ValidationError(
                f"target_device option with {self._target_device} value is not supported with the mode option!"
            )

```
and it now becomes possible to do:
```python3
try:
    nncf.quantize(/* some_param_set */)
except nncf.ValidationError:  # will only catch errors due to invalid user-supplied params
    print("Looks like the parameters to nncf.quantize were wrong to begin with")
except RuntimeError:  # will catch everything else
    print("Something really unexpected happened")
```

Accomplishing this would enable better user/developer experience for NNCF, and also would allow the developers to apply [fuzzing](https://github.com/google/atheris) techniques more effectively.

## Task

1. Introduce the NNCF-specific exception classes. Create a new source file `nncf/errors.py` in the repository root and define the new classes there, e.g.:
```python3
# in nncf/errors.py
class ValidationError(Exception):
    """
    Raised when an internal NNCF validation check fails, for example, if the user supplied an invalid or inconsistent set of arguments.
    """
    pass  # the functionality of the base `Exception` is enough for all such classes for now

class SomeOtherError(Exception):
    """
    * documentation for SomeOtherError *
    """
    pass
```
The exact number and naming of the exception classes is discretionary, but should reflect the basic sense of each exception type. Use the following set as a guide:

* `nncf.ValidationError` - for failures in validating user-supplied parameters, e.g. when parameter is not specified, or parameters are inconsistent etc. This kind of errors would usually be raised on upper levels of call stack in the execution of [NNCF API functions](https://openvinotoolkit.github.io/nncf/autoapi/nncf/index.html#functions) or their backend-specific implementations.

* `nncf.InternalError` - for errors and failed internal checks at deeper NNCF algorithm stages, especially those that do not specify any kind of remediation in their associated messages ([example 1](https://github.com/openvinotoolkit/nncf/blob/8dd593e20222993fee09dd80f245850353f1493a/nncf/openvino/graph/model_transformer.py#L510), [example 2](https://github.com/openvinotoolkit/nncf/blob/8dd593e20222993fee09dd80f245850353f1493a/nncf/torch/compression_method_api.py#L168)) and those that the user cannot influence.

2. Expose the exceptions on the `nncf` import level by adding the import-as lines to `nncf/__init__.py`, e.g.:
```python3
from nncf.errors import ValidationError
from nncf.errors import InternalError
```
so that the exception classes could be avalable for import/usage from the `nncf` namespace directly:
```
import nncf
try:
    ...
except nncf.ValidationError:
    ...
```

3. Review the exception usage in [NNCF code base](https://github.com/openvinotoolkit/nncf) (basically just ctrl+F/grep for `raise `) and replace the built-in Python exception types in the `raise ...` expressions with proper exception classes introduced in the step 1 based on the meaning of each exceptional case. 

The built-in exception types to be replaced are:
    * `RuntimeError` - replace in all cases, ideally we do not want NNCF code to raise this since this built-in is too generic, and instead reserve it for failures outside NNCF responsibility
    * `ValueError` - same as above, except for cases where the `ValueError` is defined on lowest-level, simple container classes and mimics the regular Python `ValueError` seen in the wild

The built-in exception types NOT to be replaced are:
    * `NotImplementedError` - since this is mostly used in "abstract" classes and specific enough already so as not to necessitate a distinction between NNCF and non-NNCF lack of implementation. 

4. Adjust the test cases in `tests` that used to expect built-in error exception types to the new types accordingly ([example](https://github.com/openvinotoolkit/nncf/blob/8dd593e20222993fee09dd80f245850353f1493a/tests/post_training/test_templates/test_ptq_params.py#L291))

5. Document the new exception usage guidelines in the [style guide](https://github.com/openvinotoolkit/nncf/blob/develop/docs/styleguide/PyGuide.md), and make sure that your PR conforms to it too.

**Comment by Om-Doiphode** [comment]
.take

**Comment by Om-Doiphode** [comment]
https://github.com/openvinotoolkit/nncf/pull/2412
Please review this Pull Request, thanks!

**Comment by vshampor** [comment]
The PR has passed the precommit and installation checks and has been merged. Will review the nightly job runs and close this tomorrow if the situation is satisfactory for development purposes.

**Comment by vshampor** [comment]
The nightlies are running without known regressions. Thank you, @Om-Doiphode, for the great work!
