### ISSUE TITLE
much more sys time consumed when change from CPU path to GPU path

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/openvino#2239]
I'm using ubuntu 18.04 x64 + skylake with 4 cpu cores and Gen9 GPU with OpenCL kernel installed from https://github.com/intel/compute-runtime/releases/tag/20.35.17767

I'm building openvino from source code at 95a57795dcb0ed82324af87918339225148202ca, and the gcc version is: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

I found that the GPU path consumes much more sys time than CPU path, and I narrow down it with hello_classification_c, see the changes at https://github.com/guoyejun/openvino/commit/afa6b06a5049ffc97405e1390cbfe966431add28. Please ignore the functionality, i just want to narrow down the issue with it.

the files espcn.xml/bin and 480p.jpg to reproduce the issue are zipped and uploaded here.
[systimeissue.zip](https://github.com/openvinotoolkit/openvino/files/5223660/systimeissue.zip)

the commands to reproduce the issue:
$ time ./hello_classification_c ./espcn.xml 480p.jpg CPU
program finished.

real    1m26.910s
user    5m36.441s
sys     0m0.644s

$ time ./hello_classification_c ./espcn.xml 480p.jpg GPU
program finished.

real    1m14.393s
user    0m48.983s
sys     0m26.964s

we can see that the sys time increases from 0.644s to 26.964s!

I tried perf record/report for the GPU path, see below. How to understand the bottle neck? thanks.
$ perf record ./hello_classification_c ./espcn.xml 480p.jpg GPU 

![image](https://user-images.githubusercontent.com/10448440/93189280-8651db80-f774-11ea-9ceb-324950e3ede2.png)

**Comment by jgespino** [comment]
Hi @guoyejun 

The model load time on the GPU plugin depends on OpenCL kernel compilation, try enabling [cl_cache ](https://github.com/intel/compute-runtime/blob/master/opencl/doc/FAQ.md#feature-cl_cache)in the application's directory. The time should improve after the first run on GPU.

Regards,
Jesus

**Comment by guoyejun** [comment]
hi, my concern is on the sys time, not user time, it has nothing to do with the kernel compiling time which is done at user mode.

and, in my test, i iterate 1000 times to set/execute/get the model, the kernel compiling time (before the for loop) should be very small comparing to the loop time. I also copy the code here for your convenient.
```
    for (int i = 0; i < 1000; ++i) {
        status = ie_infer_request_set_blob(infer_request, input_name, imgBlob);
        if (status != OK)
            goto err;
        // -----------------------------------------------------------------------------------------------------

        // --------------------------- 7. Do inference --------------------------------------------------------
        /* Running the request synchronously */
        status = ie_infer_request_infer(infer_request);
        if (status != OK)
            goto err;
        // -----------------------------------------------------------------------------------------------------

        // --------------------------- 8. Process output ------------------------------------------------------
        status = ie_infer_request_get_blob(infer_request, output_name, &output_blob);
        if (status != OK) {
            image_free(&img);
            goto err;
        }
    }
```

anyway, I also tried the cl_cache, but no meaningful difference.

I guess the issue might be an endless query which calls KMD to check some status.

In the meantime, i'll try to look into it when have time. Any help are welcome, thanks.

**Comment by jgespino** [comment]
Hi @guoyejun,

You are right, this is not related to OpenCL for kernel compilation. I saw the same behavior on my system using your code modifications and model. Let me check with my peers to see if they have any additional suggestions. 

Regards,
Jesus

**Comment by guoyejun** [comment]
fyi,

i did some investigation and found the stack that consumes the sys time.
```
(gdb) bt
#0  0x00007ffff76a1f37 in sched_yield () at ../sysdeps/unix/syscall-template.S:78
#1  0x00007ffff055738a in NEO::CommandStreamReceiver::waitForCompletionWithTimeout(bool, long, unsigned int) () from /usr/local/lib/intel-opencl/libigdrcl.so
#2  0x00007ffff0518a9f in NEO::CommandStreamReceiverHw<NEO::SKLFamily>::waitForTaskCountWithKmdNotifyFallback(unsigned int, unsigned long, bool, bool) () from /usr/local/lib/intel-opencl/libigdrcl.so
#3  0x00007ffff02adc9b in NEO::CommandQueue::waitUntilComplete(unsigned int, unsigned int, unsigned long, bool) () from /usr/local/lib/
intel-opencl/libigdrcl.so
#4  0x00007ffff02bccd4 in NEO::Event::waitForEvents(unsigned int, _cl_event* const*) () from /usr/local/lib/intel-opencl/libigdrcl.so
#5  0x00007ffff02850f2 in clWaitForEvents () from /usr/local/lib/intel-opencl/libigdrcl.so
#6  0x00007ffff10b66da in ?? () from /usr/local/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so
#7  0x00007ffff10512ca in ?? () from /usr/local/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so
#8  0x00007ffff0fa7177 in ?? () from /usr/local/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so
#9  0x00007ffff0fac191 in ?? () from /usr/local/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so
#10 0x00007ffff0f3ca01 in ?? () from /usr/local/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so
#11 0x00007ffff7313a42 in ?? () from /usr/local/deployment_tools/inference_engine/lib/intel64/libinference_engine.so
#12 0x00007ffff67a56df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff2d776db in start_thread (arg=0x7fffdcf04700) at pthread_create.c:463
#14 0x00007ffff76bfa3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by vladimir-paramuzov** [comment]
@guoyejun This sys time increase is caused by the gpu driver which uses polling to check kernels completion by default. You can set the following plugin key to enable throttling and reduce sys time:
config["GPU"][CLDNN_CONFIG_KEY(PLUGIN_THROTTLE)] = "1";

Note: this key might lead to some performance drop.

**Comment by guoyejun** [comment]
thanks
