### ISSUE TITLE
Ultralytics YOLOv8 OpenVINO PyInstaller Not Working

### ISSUE THREAD

**Issue by osvpl** [openvinotoolkit/openvino#22475]
I have made an EXE of my object detection program.
I am using Ultralytics YOLOv8 with OpenVINO model.
Everything is working fine when I am running the .py file.

But when I am making an EXE using pyinstaller, it shows that OpenVINO is not installed.

**Loading best_openvino_model for OpenVINO inference ...
requirements: Ultralytics requirement ['openvino>=2023.0'] not found, attempting AutoUpdate ...
'pip' is not recognized as an internal or external command,
operable program or batch file.
requirements: X Command 'pip install -- no-cache "openvino>=2023.0" ' returned non-zero exit status 1.**

Here's the screenshot of error
![image](https://github.com/openvinotoolkit/openvino/assets/156005125/07ab3f81-5df6-4f4b-855b-de2b9b52e4b2)

I have tried all possible commands like below

pyinstaller --collect-data=ultralytics --collect-data=openvino --collect-submodules openvino --collect-binaries openvino --hidden-import openvino --hidden-import openvino-dev --hidden-import openvino-telemetry VPS.py

pyinstaller --collect-data=ultralytics --collect-data=openvino VPS.py

pyinstaller --collect-data=ultralytics --collect-data=openvino --collect-submodules openvino --collect-binaries openvino VPS.py

Please help

**Comment by krish1209** [comment]
Could you give steps as to how to reproduce this error? I can try to solve.

**Comment by osvpl** [comment]
Thanks for replying bro.

The problem got solved.
Someone in other forum replied to my query.

We need to add --collect-metadata openvino along with some other parameters

**Comment by krish1209** [comment]
Oh okay. Thats great.
I would also recommend you to add the directory containing the 'pip' executable to your system's PATH environment variable so that pip becomes available globally. You can also run in a venv.
Anyways, Have a nice day!

**Comment by camachoandres88** [comment]
@osvpl Could you elaborate or send the link to the forum?
