### ISSUE TITLE
Inference Engine  make  error

### ISSUE THREAD

**Issue by mathpopo** [openvinotoolkit/openvino#225]
[ 76%] Building CXX object thirdparty/clDNN/src/CMakeFiles/clDNN_shlib.dir/lstm.cpp.o
cc1plus: all warnings being treated as errors
thirdparty/CMakeFiles/mkldnn.dir/build.make:1596: recipe for target 'thirdparty/CMakeFiles/mkldnn.dir/mkl-dnn/src/cpu/jit_uni_binary_convolution.cpp.o' failed
make[2]: *** [thirdparty/CMakeFiles/mkldnn.dir/mkl-dnn/src/cpu/jit_uni_binary_convolution.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

[ 77%] Building CXX object thirdparty/clDNN/src/CMakeFiles/clDNN_shlib.dir/reduce.cpp.o
CMakeFiles/Makefile2:1915: recipe for target 'thirdparty/CMakeFiles/mkldnn.dir/all' failed
make[1]: *** [thirdparty/CMakeFiles/mkldnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

[ 86%] Linking CXX shared library ../../../bin/intel64/Release/lib/libinference_engine.so
Remove clDNNPlugin from the plugins.xml file
Remove dliaPlugin from the plugins.xml file
Remove GNAPlugin from the plugins.xml file
Remove MKLDNNPlugin from the plugins.xml file
Remove myriadPlugin from the plugins.xml file
Register MKLDNNPlugin plugin
Register clDNNPlugin plugin
Register myriadPlugin plugin
Register GNAPlugin plugin
Registering plugins to plugins.xml config file
[ 86%] Built target inference_engine
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by asuhov** [comment]
Hello, which OS and gcc version do you use? The build failed due to warning being treated as errors (but exact warning message is missed in the log above). Could you try to remove "-Werror" option from inference-engine/cmake/os_flags.cmake file and re-run cmake and make?

**Comment by AnastasiaKazantaeva** [comment]
It seems that problem is not actual anymore. Closing this issue. Feel free to open a new one in case of some questions/problems
