### ISSUE TITLE
[Feature Request]: Adding a follow along manual for helping with the build process

### ISSUE THREAD

**Issue by rghvsh** [openvinotoolkit/openvino#22587]
### Request Description

I was recently building OpenVINO on my system during which a lot of jargon seemed difficult to comprehend. We could add a guide on how the user's system should respond.

### Feature Use Case

As it is a long process it can help the user know the build is going properly.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by ilya-lavrenov** [comment]
Hi @rghvsh 
Could you please be more specific?

**Comment by rghvsh** [comment]
Hello! @ilya-lavrenov 
ah sorry for the vague wording I meant that building the entire project is long so we could add a note specifying commands to build specific frontends.
eg: this for tensorflow frontend
```
cmake ...
make openvino_tensorflow_frontend
```
would be happy to do this

**Comment by ilya-lavrenov** [comment]
@rghvsh cmake provides a way to list all available targets via:
```bash
cmake --build . --target help
```

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask any questions related to this topic.
