### ISSUE TITLE
RuntimeError: AssertionFailed: StatusCode::OK == network-getLayerByName(layerName.c_str(), layer, &resp)

### ISSUE THREAD

**Issue by neso613** [openvinotoolkit/openvino#227]
HI
I am trying to deploy my deep neural network on RaspberryPi using OPENVINO R2 but I am stuck with this error- 
`RuntimeError: AssertionFailed: StatusCode::OK == network-getLayerByName(layerName.c_str(), layer, &resp)`

I have 2 different and  separate CNN model and their output act as input to LSTM. LSTM shows this error on loading.

net = IENetwork(model=model_xml, weights=model_bin)
exec_net = plugin.load(network=net)

Please help me in this matter.

**Comment by shubha-ramani** [comment]
Dear @nehasoni3 
I'm going to require more information before I can help you. Can you perhaps attach your model as a *.zip ? Also in that *.zip file kindly provide a simple script or program which demonstrates the assertion.

Sorry for the inconvenience.

Thanks,

Shubha

**Comment by nehasoni3** [comment]
hi @shubha-ramani 
Thanks for replying!!
I am sorry I can't share my model or inferencing script. But I can provide you some more information regarding the error.

The below line of codes is for LSTM model - 

`exec_net1_Query = ie.query_network(network=net1, device_name="HETERO:MYRIAD,CPU")`
Output at console--
`{'lstm1/Tile_1': 'MYRIAD', 'lstm1/Sum/Pool': 'MYRIAD', 'lstm1/Sum/FinalReshape': 'MYRIAD', 'lstm1/while/LoopCond/TensorIteratorCondition_/TensorIterator': 'CPU', 'dense1/MatMul': 'MYRIAD', 'dense1/Softmax': 'MYRIAD', 'lstm1/zeros_like/Power/': 'MYRIAD', 'input_1': 'CPU', 'lstm1/transpose': 'MYRIAD', 'lstm1/Tile': 'MYRIAD', 'lstm1/Sum/FinalReshapePower/After': 'MYRIAD', 'lstm1/Sum/Reshape': 'MYRIAD', 'lstm1/ExpandDims': 'MYRIAD'}`

`net = IENetwork(model=model_xml, weights=model_bin)
net.inputs['input_1'].shape`
Output at console---
`[1, 90, 3]`

Please do needful

**Comment by shubha-ramani** [comment]
Dear @nehasoni3 
I'm sorry but looking at your output I don't see an error or a specific problem. Can you share your inference script or model privately ? I will PM you if you give me your email address. 

Let me know,

Shubha

**Comment by nehasoni3** [comment]
> Dear @nehasoni3
> I'm sorry but looking at your output I don't see an error or a specific problem. Can you share your inference script and model privately ? I will PM you if you give me your email address.
> 
> Let me know,
> 
> Thanks,
> 
> Shubha

Please check my email address - soni.neha45@gmail.com
Thanks !!!

**Comment by shubha-ramani** [comment]
Dear @nehasoni3 
I have sent you an email via Syncplicity. You will be provided a folder to add your model and inference script to. Also please provide your Model Optimizer command.

Thanks,

Shubha

**Comment by nehasoni3** [comment]
Hi shubha

Thank you for your email. But I cannot share model with anyone because of
organization policy.

I have getting this error on Neural Compute Stick2.

**Comment by nehasoni3** [comment]
Thanks @shubha for the mail. But I cannot share model with anyone because of organizations policy. I am getting this error with MYRIAD (NCS2).


I have seen in documentation that openvino R2 support 'tensorIterator' supported by VPU. Would you please specify whether it is supported on MYRIAD VPU.

**Comment by shubha-ramani** [comment]
Dear @nehasoni3  
TensorIterator is definitely supported on VPU, please see [The Supported Devices Doc](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html)

Well maybe you can make a small sample which demonstrates the problem, since you can't share code outside of your organization ?

Unless it's reproduce-able I cannot file a bug, especially because so far you're the only customer who has brought this up as an issue - the issue being TensorIterator is not supported by Myriad.

Shubha

**Comment by nehasoni3** [comment]
Hi @shubha

Ok. Will try to make it work for new demo model. Meanwhile will you please
share inference python script for LSTM which support these listed layers.

Please let me know and do the needful.
Thank

**Comment by nehasoni3** [comment]
HI @shubha-ramani 
text-recogination model is LSTM bi-directional model. Will you please confirm me that Is this model uses tanH activation function.

**Comment by shubha-ramani** [comment]
@nehasoni3  Without seeing your LSTM bi-directional model it's hard to say. You can print it out and see for yourself, however. But yes, most LSTM uses tanH activation function.  Please refer to [StackOverflow article regarding tanh Intution in LSTM](https://stackoverflow.com/questions/40761185/what-is-the-intuition-of-using-tanh-in-lstm). Thanks.
 And OpenVino definitely supports LSTM and of course the Tanh Activation function.

Shubha

**Comment by nehasoni3** [comment]
Hi @shubha-ramani 
OpenVINO suppports LSTM. Its working fine with FP16 on CPU but not with NCS2.
This is something which troubles me. Same model is working absolutely fine with FP16 CPU but not with NCS2.

There might be some thing which is not supported by NCS2.

Thanks!!

**Comment by nehasoni3** [comment]
Hi @shubha-ramani 

I have trained model and sharing with you on Syncplicity . 
Please do needful.
Looking forward.

Thanks!!

**Comment by shubha-ramani** [comment]
Dear @nehasoni3 

I understand that you're troubled by this. In fact I am also ! LSTM should definitely be supported by NCS2, as told by the [Supported Devices](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html) document. GRU is not supported but LSTM certainly is. So if you can provide me a sample model and inference script which demonstrates the failure of LSTM on NCS2, that would be quite helpful. It may in fact be a bug.

Thanks,

Shubha

**Comment by nehasoni3** [comment]
Hi @shubha-ramani 
Please acknowledge me if you have go through the model.

Thanks!!

**Comment by chandnibohra** [comment]
> Dear @nehasoni3
> 
> I understand that you're troubled by this. In fact I am also ! LSTM should definitely be supported by NCS2, as told by the [Supported Devices](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html) document. GRU is not supported but LSTM certainly is. So if you can provide me a sample model and inference script which demonstrates the failure of LSTM on NCS2, that would be quite helpful. It may in fact be a bug.
> 
> Thanks,
> 
> Shubha

hi shubha please add me on pm so that i can share my model with u.

**Comment by nehasoni3** [comment]
> Dear @nehasoni3
> 
> I understand that you're troubled by this. In fact I am also ! LSTM should definitely be supported by NCS2, as told by the [Supported Devices](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_Supported_Devices.html) document. GRU is not supported but LSTM certainly is. So if you can provide me a sample model and inference script which demonstrates the failure of LSTM on NCS2, that would be quite helpful. It may in fact be a bug.
> 
> Thanks,
> 
> Shubha

Hi @shubha-ramani 

While reading documentation of OpenVino, I have found this
[TensorFlow* Supported Operations and the Mapping to Intermediate Representation Layers](url)

In this link, TanH or LSTM is not mentioned in supported list of TensorFlow.

Please confirm me that is LSTM/TanH is supported for TensorFlow or not.

Waiting for your response.
Thanks!!
