### ISSUE TITLE
Original ONNX/PTH/TF model based on an existing IR as in Open Model Zoo

### ISSUE THREAD

**Issue by saeidn95** [openvinotoolkit/openvino#22894]
### Request Description

Hello, I was checking if you can point me to original ONNX/PTH model based on an existing IR as in Open Model Zoo for the following networks:

https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/face-detection-adas-0001

https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/facial-landmarks-35-adas-0002

https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/gaze-estimation-adas-0002

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by Wovchena** [comment]
Hello. No, they are private.

**Comment by saeidn95** [comment]
Thank you. I hope they can be made available publicly.
