### ISSUE TITLE
[Good First Issue][TF FE]: Support complex tensors for Sub operation

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#22948]
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.1/openvino_docs_ops_opset.html).
Some audio models use tensors of complex type. Complex type tensor is a tensor that has elements of complex type. For example, 1D tensor with three elements `x = [1+2j, 2, -2j]`.

For supporting [Sub](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Sub) operation on complex type tensor, you need to extend the corresponding [loader for Sub](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow_common/src/op/binary_op.cpp).

### What needs to be done?

The existing [loader for Sub](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow_common/src/op/binary_op.cpp) needs to be extended by propagating `ComplexTypeMark` from input to output and to represent output complex type tensor as a floating-point type tensor with auxiliary dimension that concatenates real and imaginary parts of complex tensor.
To validate the extension, the corresponding layer test needs to be updated with complex tensor cases.

Here is an example of how to extend `Reshape` loader to support complex type tensors:

```cpp
OutputVector translate_reshape_op(const NodeContext& node) {
    default_op_checks(node, 2, {"Reshape"}, true);
    auto tensor = node.get_input(0);
    auto complex_type_mark = as_type_ptr<ComplexTypeMark>(tensor.get_node_shared_ptr());
    auto shape = node.get_input(1);
    if (complex_type_mark) {
        element::Type complex_part_type = complex_type_mark->get_complex_part_type();
        tensor = complex_type_mark->input_value(0);

        OutputVector concat_inputs;
        concat_inputs.push_back(shape);
        concat_inputs.push_back(make_shared<v0::Constant>(shape.get_element_type(), Shape{1}, 2));

        auto concat = make_shared<v0::Concat>(concat_inputs, 0);
        auto reshape = make_shared<v1::Reshape>(tensor, concat, false);
        set_node_name(node.get_name(), reshape);
        auto complex_reshape = make_shared<ComplexTypeMark>(reshape, complex_part_type);
        return {complex_reshape->output(0)};
    }

    auto reshape = make_shared<v1::Reshape>(tensor, shape, false);
    set_node_name(node.get_name(), reshape);
    return {reshape};
}
```

Since OpenVINO does not have native support of complex tensors, we handle complex type in intermediate layers by representing them as a floating-point type with additional dimension (specially created) to store real and imaginary parts of the original complex tensor so slicing by the last dimension will give either real or imaginary parts: `x[...,0]` - real and `x[...,1]` - imaginary parts.

On the first step, we update `default_op_checks` with `true` flag to indicate that loader for `Reshape` operation now handles complex tensors:

```
default_op_checks(node, 2, {"Reshape"}, true);
```

Secondly, we check if complex type mark exists by anticipated inputs. This mark indicates that input tensor of complex type:

```
auto complex_type_mark = as_type_ptr<ComplexTypeMark>(tensor.get_node_shared_ptr());
```

Thirdly, we retrieve a floating-point tensor (with additional dimension to store real and imaginary parts) simulating complex tensor:

```
tensor = complex_type_mark->input_value(0);
```

After that, we implement conversion for `Reshape` for this particular case. Since a floating-point tensor simulating complex tensor has additional dimension equal to 2,
we update input target shape by appending `2` value and perform reshape on a floating-point tensor simulating complex tensor.

Finally, since `Reshape` should produce complex tensor by output we insert a new mark `ComplexTypeMark` into the output.

To validate support of complex tensors for `Reshape`, the new layer test [TestComplexReshape](https://github.com/openvinotoolkit/openvino/blob/master/tests/layer_tests/tensorflow_tests/test_tf_Reshape.py#L53) was added.

Example how to run the layer test:

```
export TEST_DEVICE=CPU
cd openvino/tests/layer_tests/tensorflow_tests
pytest test_tf_Reshape.py
```

### Example Pull Requests

- Extensions for `Shape`, `Mul`, `Reshape` in https://github.com/openvinotoolkit/openvino/pull/21477
- Extension for `Roll` operation in https://github.com/openvinotoolkit/openvino/pull/20860

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

- @openvinotoolkit/openvino-tf-frontend-maintainers
- rkazants in Discord

**Comment by noelp2500** [comment]
.take

**Comment by noelp2500** [comment]
Hi @rkazants 

####
## **_So, I extended the loader for sub like this --->_**

`OutputVector translate_sub_op(const NodeContext& node) {
    default_op_checks(node, 2, {}, true);
    auto lhs = node.get_input(0);
    auto rhs = node.get_input(1);
    auto result = make_shared<v1::Subtract>(lhs, [rhs);](url)
    auto complex_type_mark_lhs = as_type_ptr<ComplexTypeMark>(lhs.get_node_shared_ptr());
    auto complex_type_mark_rhs = as_type_ptr<ComplexTypeMark>(rhs.get_node_shared_ptr());

    if (complex_type_mark_lhs || complex_type_mark_rhs) {
        FRONT_END_GENERAL_CHECK(complex_type_mark_lhs != nullptr && complex_type_mark_rhs != nullptr,
                                "Sub got complex and non-complex inputs. Inputs should be of same type.");
        lhs = complex_type_mark_lhs->input_value(0);
        rhs = complex_type_mark_rhs->input_value(0);

        element::Type complex_part_type_lhs = complex_type_mark_lhs->get_complex_part_type();
        element::Type complex_part_type_rhs = complex_type_mark_rhs->get_complex_part_type();
        FRONT_END_GENERAL_CHECK(complex_part_type_lhs == complex_part_type_rhs,
                                "Sub got complex inputs of different types. Inputs should be of same type.");
        
        auto gather_index_real = make_shared<v0::Constant>(element::i32, Shape{}, 0);
        auto gather_index_imag = make_shared<v0::Constant>(element::i32, Shape{}, 1);

        auto minus_one = make_shared<v0::Constant>(element::i32, Shape{1}, -1);
        auto lhs_real = make_shared<v8::Gather>(lhs, gather_index_real, minus_one)->output(0);
        auto lhs_imag = make_shared<v8::Gather>(lhs, gather_index_imag, minus_one)->output(0);
        auto rhs_real = make_shared<v8::Gather>(rhs, gather_index_real, minus_one)->output(0);
        auto rhs_imag = make_shared<v8::Gather>(rhs, gather_index_imag, minus_one)->output(0);

        // result_real = lhs_real - rhs_real
        auto result_real = make_shared<v1::Subtract>(lhs_real, rhs_real);
        // result_imag = lhs_imag - rhs_imag
        auto result_imag = make_shared<v1::Subtract>(lhs_imag, rhs_imag);

        auto real_unsqueeze = make_shared<v0::Unsqueeze>(result_real, minus_one);
        auto imag_unsqueeze = make_shared<v0::Unsqueeze>(result_imag, minus_one);

        auto concat_result = make_shared<v0::Concat>(OutputVector{real_unsqueeze, imag_unsqueeze}, -1);

        set_node_name(node.get_name(), concat_result);

        auto complex_result = make_shared<ComplexTypeMark>(concat_result->output(0), complex_part_type_lhs);
        return {complex_result};
    }
    
    set_node_name(node.get_name(), result);
    
    return {result};
}`

####
## **_And wrote the pytest as -->_** 

`class TestComplexSub(CommonTFLayerTest):
    def _prepare_input(self, inputs_info):

        rng = np.random.default_rng()
        assert "param_real_1:0" in inputs_info
        assert "param_imag_1:0" in inputs_info
        assert "param_real_2:0" in inputs_info
        assert "param_imag_2:0" in inputs_info
        param_real_shape_1 = inputs_info["param_real_1:0"]
        param_imag_shape_1 = inputs_info["param_imag_1:0"]
        param_real_shape_2 = inputs_info["param_real_2:0"]
        param_imag_shape_2 = inputs_info["param_imag_2:0"]

        inputs_data = {}
        inputs_data["param_real_1:0"] = (
            4 * rng.random(param_real_shape_1).astype(np.float32) - 2
        )
        inputs_data["param_imag_1:0"] = (
            4 * rng.random(param_imag_shape_1).astype(np.float32) - 2
        )
        inputs_data["param_real_2:0"] = (
            4 * rng.random(param_real_shape_2).astype(np.float32) - 2
        )
        inputs_data["param_imag_2:0"] = (
            4 * rng.random(param_imag_shape_2).astype(np.float32) - 2
        )
        return inputs_data

    def create_complex_sub_net(self, input_shape):
        import tensorflow as tf

        tf.compat.v1.reset_default_graph()
        # Create the graph and model
        with tf.compat.v1.Session() as sess:
            param_real1 = tf.compat.v1.placeholder(
                np.float32, input_shape, "param_real_1"
            )
            param_imag1 = tf.compat.v1.placeholder(
                np.float32, input_shape, "param_imag_1"
            )
            param_real2 = tf.compat.v1.placeholder(
                np.float32, input_shape, "param_real_2"
            )
            param_imag2 = tf.compat.v1.placeholder(
                np.float32, input_shape, "param_imag_2"
            )
            complex1 = tf.raw_ops.Complex(real=param_real1, imag=param_imag1)
            complex2 = tf.raw_ops.Complex(real=param_real2, imag=param_imag2)
            sub = tf.raw_ops.Sub(x=complex1, y=complex2, name="complex_sub")
            real = tf.raw_ops.Real(input=sub)
            img = tf.raw_ops.Imag(input=sub)
            tf.compat.v1.global_variables_initializer()
            tf_net = sess.graph_def
        return tf_net, None

    test_data_basic = [
        dict(input_shape=[]),
        dict(input_shape=[2]),
        dict(input_shape=[1, 3]),
        dict(input_shape=[2, 3, 4]),
        dict(input_shape=[3, 4, 5, 6]),
    ]

    @pytest.mark.parametrize("params", test_data_basic)
    @pytest.mark.precommit_tf_fe
    @pytest.mark.nightly
    def test_complex_sub(
        self, params, ie_device, precision, ir_version, temp_dir, use_legacy_frontend
    ):
        self._test(
            *self.create_complex_sub_net(params["input_shape"]),
            ie_device,
            precision,
            ir_version,
            temp_dir=temp_dir,
            use_legacy_frontend=use_legacy_frontend
        )`

####

## _**And while running pytest, I get the error ->**_ 
####################################################################################
_______________ TestComplexSub.test_complex_sub[ ie_device:CPU - precision:FP16 - params:{'input_shape': [3, 4, 5, 6]} ] ________________

self = <test_tf_Sub.TestComplexSub object at 0x2db92b750>, params = {'input_shape': [3, 4, 5, 6]}, ie_device = 'CPU', precision = 'FP16'
ir_version = 11, temp_dir = '/Users/noelpereira/Desktop/openvino2/openvino/tests/layer_tests/common/out/CPU_test_complex_sub0_2skik_'
use_legacy_frontend = False

    @pytest.mark.parametrize("params", test_data_basic)
    @pytest.mark.precommit_tf_fe
    @pytest.mark.nightly
    def test_complex_sub(
        self, params, ie_device, precision, ir_version, temp_dir, use_legacy_frontend
    ):
>       self._test(
            *self.create_complex_sub_net(params["input_shape"]),
            ie_device,
            precision,
            ir_version,
            temp_dir=temp_dir,
            use_legacy_frontend=use_legacy_frontend
        )

test_tf_Sub.py:391: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../common/layer_test_class.py:79: in _test
    exit_code, stderr = generate_ir_python_api(**mo_params)
../common/utils/common_utils.py:83: in generate_ir_python_api
    ov_model = convert_model(**kwargs)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openvino/tools/ovc/convert.py:101: in convert_model
    ov_model, _ = _convert(cli_parser, params, True)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openvino/tools/ovc/convert_impl.py:534: in _convert
    raise e
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openvino/tools/ovc/convert_impl.py:476: in _convert
    ov_model = driver(argv, {"conversion_parameters": non_default_params})
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openvino/tools/ovc/convert_impl.py:227: in driver
    ov_model = moc_emit_ir(prepare_ir(argv), argv)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openvino/tools/ovc/convert_impl.py:177: in prepare_ir
    ov_model = moc_pipeline(argv, moc_front_end)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openvino/tools/ovc/moc_frontend/pipeline.py:244: in moc_pipeline
    ov_model = moc_front_end.convert(input_model)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <FrontEnd 'tf'>, model = <openvino._pyopenvino.InputModel object at 0x2f1453fb0>

    def convert(self, model: Union[Model, InputModel]) -> Model:
>       converted_model = super().convert(model)
E       openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at src/frontends/tensorflow/src/frontend.cpp:428:
E       FrontEnd API failed with OpConversionFailure:
E       [TensorFlow Frontend] Internal error, conversion is failed for Real operation with a message:
E       Check 'complex_type_mark' failed at src/frontends/tensorflow_common/src/op/real_imag.cpp:36:
E       FrontEnd API failed with OpValidationFailureWhile validating node 'Real':
E       [TensorFlow Frontend] internal error: ComplexTypeMark is not set at the input of Real
E       
E       [TensorFlow Frontend] Internal error, conversion is failed for Imag operation with a message:
E       Check 'complex_type_mark' failed at src/frontends/tensorflow_common/src/op/real_imag.cpp:36:
E       FrontEnd API failed with OpValidationFailureWhile validating node 'Imag':
E       [TensorFlow Frontend] internal error: ComplexTypeMark is not set at the input of Imag
E       
E       [TensorFlow Frontend] Internal error, conversion is failed for Sub operation with a message:
E       Check '!has_input_complex_type || supported_complex' failed at src/frontends/tensorflow_common/src/utils.cpp:285:
E       FrontEnd API failed with OpValidationFailureWhile validating node 'Sub':
E       [TensorFlow Frontend] internal error: translator for Sub does not support input complex type
E       
E       [TensorFlow Frontend] Internal error, no translator found for operation(s): ComplexTypeMark
E       To facilitate the conversion of unsupported operations, refer to Frontend Extension documentation: https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Frontend_Extensions.html

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openvino/frontend/frontend.py:18: OpConversionFailure
##################################################################################

Can you give me any advice on how to move forward.

**Comment by p-wysocki** [comment]
Hello @noelp2500, can we help you with anything?

**Comment by noelp2500** [comment]
Hi @p-wysocki, I've created a pull request and made some edits from comments left by @rkazants.

I would appreciate if you could take a look, and provide any comments or feedback too!
[PR](https://github.com/openvinotoolkit/openvino/pull/23126)

**Comment by RitikaxShakya** [comment]
I would like to take up this issue. Thank you!

**Comment by RitikaxShakya** [comment]
.take

**Comment by rkazants** [comment]
Hi @RitikaxShakya, any update on this task?

Best regards,
Roman

**Comment by RitikaxShakya** [comment]
@rkazants Hello! Yes, i am adding tests.

**Comment by p-wysocki** [comment]
Hello @RitikaxShakya, are you still working on that issue? Do you need any help?

**Comment by hub-bla** [comment]
.take
