### ISSUE TITLE
[Good First Issue][TF FE]: Support MatrixInverse operation for TensorFlow

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#22957]
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.2/openvino_docs_ops_opset13.html).

In order to infer TensorFlow models with [MatrixInverse](https://www.tensorflow.org/api_docs/python/tf/raw_ops/MatrixInverse) operation by OpenVINO, TF FE needs to be extended with this operation support.

### What needs to be done?

For [MatrixInverse](https://www.tensorflow.org/api_docs/python/tf/raw_ops/MatrixInverse) operation support, you need to implement the corresponding loader into TF FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of TensorFlow operation.

Here is an example of loader implementation for TensorFlow `Einsum` operation:

```cpp
OutputVector translate_einsum_op(const NodeContext& node) { 
     auto op_type = node.get_op_type(); 
     TENSORFLOW_OP_VALIDATION(node, op_type == "Einsum", "Internal error: incorrect usage of translate_einsum_op."); 
     auto equation = node.get_attribute<std::string>("equation"); 
  
     OutputVector inputs; 
     for (size_t input_ind = 0; input_ind < node.get_input_size(); ++input_ind) { 
         inputs.push_back(node.get_input(input_ind)); 
     } 
  
     auto einsum = make_shared<Einsum>(inputs, equation); 
     set_node_name(node.get_name(), einsum); 
     return {einsum}; 
 } 
```

In this example, `translate_einsum_op` converts TF `Einsum` into OV `Einsum`. `NodeContext` object passed into the loader packs all info about inputs and attributes of `Einsum` operation. The loader retrieves an attribute of the equation by using the `NodeContext::get_attribute()` method, prepares input vector, creates `Einsum` operation from OV opset and returns a vector of outputs.

Responsibility of a loader is to parse operation attributes, prepare inputs and express TF operation via OV operations sub-graph. Example for `Einsum` demonstrates the resulted sub-graph with one operation. In PR https://github.com/openvinotoolkit/openvino/pull/19007 you can see operation decomposition into multiple node sub-graph.

Once you are done with implementation of the translator, you need to implement the corresponding layer tests `test_tf_MatrixInverse.py` and put it into [layer_tests/tensorflow_tests](https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/tensorflow_tests) directory. Example how to run some layer test:

```
export TEST_DEVICE=CPU
cd openvino/tests/layer_tests/tensorflow_tests
pytest test_tf_Shape.py
```

### Hint

Use newly added operation [Inverse](https://github.com/openvinotoolkit/openvino/blob/master/docs/articles_en/documentation/openvino-ir-format/operation-sets/operations-specifications/matrix/Inverse_14.rst) into OV opset-14

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/19007

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

- @openvinotoolkit/openvino-tf-frontend-maintainers
- @rkazants in GitHub
- rkazants in Discord

**Comment by koookieee** [comment]
.take

**Comment by koookieee** [comment]
Hello @rkazants  , I will be working on this issue. Let me know if you have any comments or suggestions .

**Comment by rkazants** [comment]
Hi @koookieee, any update on the task?

Best regards,
Roman

**Comment by dyogaharshitha** [comment]
.take

**Comment by rkazants** [comment]
No update for long time, I have to release this task.

Best regards,
Roman

**Comment by hongbo-wei** [comment]
.take

**Comment by hongbo-wei** [comment]
Hello @rkazants, I've built OpenVINO locally, does this mean I can start coding and contributing? OpenVINO is a software toolkit, compared to other simpler applications, it's hard to have a direct visual of what is going on there, hence it is easier for developers to know what to do next. So I wonder if I'm on the right track.

<img width="848" alt="Screenshot 2024-03-18 at 1 31 06 PM" src="https://github.com/openvinotoolkit/openvino/assets/112866063/abc4d564-182f-450c-9f30-24ca9044fa21">

**Comment by rkazants** [comment]
> Hello @rkazants, I've built OpenVINO locally, does this mean I can start coding and contributing? OpenVINO is a software toolkit, compared to other simpler applications, it's hard to have a direct visual of what is going on there, hence it is easier for developers to know what to do next. So I wonder if I'm on the right track : )
> 
> <img alt="Screenshot 2024-03-18 at 1 31 06 PM" width="848" src="https://private-user-images.githubusercontent.com/112866063/313628863-abc4d564-182f-450c-9f30-24ca9044fa21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDgwMDMsIm5iZiI6MTcxMTMwNzcwMywicGF0aCI6Ii8xMTI4NjYwNjMvMzEzNjI4ODYzLWFiYzRkNTY0LTE4MmYtNDUwYy05ZjMwLTI0Y2E5MDQ0ZmEyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxOTE1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjQzNzE3ZTUwZDViMzYxNmM0ODRiZjQ0NmJjZGU0NTliZTNmODZjNDkzMjE5MzY1ZjQ3M2RhNTQ2NmNlZjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MvLw6tgWNpnQFxG223TdsH0dnAiz5xIVtGjD2R-3DG8">

Hi @hongbo-wei,

Now you need to implement translator for TF MatrixInverse to OV opset Inverse. Please check: https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/operation-specs/matrix/Inverse_14.html

Should simple translator. Check translators for other operations and description above.

Best regards,
Roman

**Comment by hongbo-wei** [comment]
> > Hello @rkazants, I've built OpenVINO locally, does this mean I can start coding and contributing? OpenVINO is a software toolkit, compared to other simpler applications, it's hard to have a direct visual of what is going on there, hence it is easier for developers to know what to do next. So I wonder if I'm on the right track : )
> > <img alt="Screenshot 2024-03-18 at 1 31 06 PM" width="848" src="https://private-user-images.githubusercontent.com/112866063/313628863-abc4d564-182f-450c-9f30-24ca9044fa21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDgwMDMsIm5iZiI6MTcxMTMwNzcwMywicGF0aCI6Ii8xMTI4NjYwNjMvMzEzNjI4ODYzLWFiYzRkNTY0LTE4MmYtNDUwYy05ZjMwLTI0Y2E5MDQ0ZmEyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxOTE1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjQzNzE3ZTUwZDViMzYxNmM0ODRiZjQ0NmJjZGU0NTliZTNmODZjNDkzMjE5MzY1ZjQ3M2RhNTQ2NmNlZjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MvLw6tgWNpnQFxG223TdsH0dnAiz5xIVtGjD2R-3DG8">
> 
> Hi @hongbo-wei,
> 
> Now you need to implement translator for TF MatrixInverse to OV opset Inverse. Please check: https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/operation-specs/matrix/Inverse_14.html
> 
> Should be simple translator. Check translators for other operations and description above.
> 
> Best regards, Roman

Hello Roman, I'm stuck in building OpenVINO™ runtime for macOS systems (Apple Silicon). In the second final step:
(CMake configure) OpenVINO project uses a CMake-based build system. In the created build directory, run cmake to fetch project dependencies and create build rules:
`cmake -G "Ninja Multi-Config" -DENABLE_SYSTEM_PUGIXML=ON -DENABLE_SYSTEM_SNAPPY=ON -DENABLE_SYSTEM_PROTOBUF=ON ..`

Error message "ImportError while loading conftest '/Users/hongbo_wei/.Trash/openvino/tests/layer_tests/tensorflow_tests/conftest.py'.
conftest.py:10: in <module>
    from common.layer_test_class import get_params
../common/layer_test_class.py:13: in <module>
    from common.layer_utils import InferAPI
../common/layer_utils.py:8: in <module>
    from openvino.runtime import Core, get_version as ie2_get_version
E   ModuleNotFoundError: No module named 'openvino'"

However, I already installed `protobuf` by running `brew install protobuf`. Still, CMake couldn't find it. How to solve this problem?

**Comment by hongbo-wei** [comment]
Hello Roman @rkazants, I want to build OpenVINO runtime to test my contributed program, and I follow the instructions in [Mac (ARM)](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_mac_arm.md). In the last step I encountered an error says missing a file called transforms.cpp in OpenVINO, and I cannot find one in the GitHub repo. All previous steps run successfully.

```
hongbo_wei@Champ-Pro build % cmake --build . --config Release --parallel $(sysctl -n hw.ncpu)
ninja: error: '/Users/hongbo_wei/Downloads/GitHub/openvino/src/frontends/pytorch/src/transforms.cpp', needed by 'src/frontends/pytorch/src/CMakeFiles/openvino_pytorch_frontend.dir/transforms.cpp.o', missing and no known rule to make it
```

**Comment by hongbo-wei** [comment]
> Mac (ARM)

Correct path of `Protobuf` found and fixed. Encounter error when building.
```
error: no member named 'in_place_type_t' in namespace 'absl'
struct IsInPlaceType<absl::in_place_type_t<T>> : std::true_type {};
                     ~~~~~~^
/opt/homebrew/include/absl/functional/internal/any_invocable.h:380:44: error: 'T' does not refer to a value
struct IsInPlaceType<absl::in_place_type_t<T>> : std::true_type {};
                                           ^
/opt/homebrew/include/absl/functional/internal/any_invocable.h:379:17: note: declared here
template <class T>
                ^
/opt/homebrew/include/absl/functional/internal/any_invocable.h:380:46: error: expected unqualified-id
struct IsInPlaceType<absl::in_place_type_t<T>> : std::true_type {};
                                             ^
/opt/homebrew/include/absl/functional/internal/any_invocable.h:476:27: error: no template named 'in_place_type_t' in namespace 'absl'
  explicit CoreImpl(absl::in_place_type_t<QualTRef>, Args&&... args) {
                    ~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
ninja: build stopped: subcommand failed.
```
