### ISSUE TITLE
[Good First Issue][TFL FE]: Support GELU operation for TensorFlow Lite

### ISSUE THREAD

**Issue by jane-intel** [openvinotoolkit/openvino#22964]
### Context

OpenVINO component responsible for support of TensorFlow Lite models is called as TensorFlow Lite Frontend (TFL FE). TFL FE converts a model represented in TensorFlow Lite opset to a model in [OpenVINO opset](https://docs.openvino.ai/2023.2/openvino_docs_ops_opset13.html).

TensorFlow Lite opset is specified via
- reference implementation: [link](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/kernels)
- attributes definition in schema: [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema_v3c.fbs)

### What needs to be done?

For GELU operation support, you need to implement:
- common gelu loader [directory link](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) and register it in [common operation table](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow_common/include/common_op_table.hpp).
```
OutputVector translate_gelu_op(const NodeContext& node) {
    default_op_checks(node, 1, {"GELU"});
    auto x = node.get_input(0);

    // update these lines for best translation
    auto approximate = node.get_attribute<element::boolean>("approximate");
    auto res = make_shared<v7::Gelu>(x, ...);
    //

    set_node_name(node.get_name(), res);
    return res->outputs();
}
```

- TFL specific loader [directory link](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_lite/src/op)
```
OutputVector gelu(const ov::frontend::tensorflow_lite::NodeContext& node) {
    const auto& decoder = get_decoder(node);
    std::map<std::string, ov::Any> attrs{
        {"approximate", decoder->get_attribute(&GeluOptions::approximate)},
    };
    return attribute_helper(node, attrs, ov::frontend::tensorflow::op::translate_gelu_op);
}
```
- register loader into the dictionary of Loaders: [header](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow_lite/src/op_table.hpp#L41), [source](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow_lite/src/op_table.cpp#L89).
    - header: ```TFL_OP_CONVERTER(gelu);```
    - source: ```{"GELU", DEQUANTIZE_INPUTS(gelu)},```

- implement layer test for your solution: [link](https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/tensorflow_lite_tests)

One loader is responsible for conversion (or decomposition) of one type of TensorFlow Lite operation.

Useful links for TFL GELU support:
- TFL [Reference implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/gelu.h)
- TFL [Attributes](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema_v3c.fbs#L1167)
- OpenVINO operation to use [link](https://github.com/openvinotoolkit/openvino/blob/master/src/core/include/openvino/op/gelu.hpp#L36:L70)
- OpenVINO Gelu specification [link](https://docs.openvino.ai/2023.3/openvino_docs_ops_activation_GELU_7.html)

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@jane-intel

**Comment by kartik912** [comment]
.take

**Comment by koookieee** [comment]
.take

**Comment by rkazants** [comment]
Hi @kartik912,

Please share your update on this task.

Best regards,
Roman

**Comment by p-wysocki** [comment]
I'm reopening the issue due to current assignee's inactivity.

**Comment by Shubham-Sahoo** [comment]
Hi @p-wysocki ! Would love to contribute to this issue. Can you assign it to me?

**Comment by mlukasze** [comment]
so it's yours, have fun :)
