### ISSUE TITLE
Problem with converting the Reshape operator of MXNet

### ISSUE THREAD

**Issue by rocketbear** [openvinotoolkit/openvino#23]
Currently I have problem with converting the Reshape operator of MXNet.
The Reshape operator is defined as follows in my model-symbol.json file:

    {
      "op": "Reshape", 
      "name": "backbone_stage2_blk1_reshape0", 
      "attrs": {"shape": "(0, -4, 2, -1, -2)"}, 
      "inputs": [[53, 0, 0]]
    }, 

The following error message is generated by the Model Optimizer:

    [ ERROR ]  Number of elements in input [1, 2, -4, 2352, -2] and output [1, -3, -2] of reshape node backbone_stage2_blk1_reshape1 mismatch
    [ ERROR ]  Shape is not defined for output 0 of "backbone_stage2_blk1_reshape1".
    [ ERROR ]  Cannot infer shapes or values for node "backbone_stage2_blk1_reshape1".

Apparantly the MO fails to calculate the output size for the Reshape operator. MO relies on mo.front.common.partial_infer.reshape.tf_reshape_shape_infer to calculate the output size for the Reshape operator, but this function is only able to process shape vectors with values in {-1, 0, >0}. However, MXNet applies more complex rules for Reshape, using values in {-4, -3, -2, -1, 0, >0}:
* 0 copy this dimension from the input to the output shape.
* -1 infers the dimension of the output shape by using the remainder of the input dimensions keeping the size of the new array same as that of the input array. At most one dimension of shape can be -1.
* -2 copy all/remainder of the input dimensions to the output shape.
* -3 use the product of two consecutive dimensions of the input shape as the output dimension.
* -4 split one dimension of the input into two dimensions passed subsequent to -4 in shape (can contain -1).

For the case above, {"shape": "(0, -4, 2, -1, -2)"}, the original dims[1] is split to 2 dimensions [2, -1], where  the -1 is to be calculated as dims[1]/2. This case is used in the ShuffleNet, where the channel dimension is reshaped to 2-d and then transposed to implement a channel shuffle operation.

Hopefully the Reshape operator of MXNet would be fully supported in the future.

**Comment by rocketbear** [comment]
Although this problem can be circumvented by providing the full specification of the new shape if all the dims are known, it is still desirable to let MO be able to fully handle MXNet's Reshape operator. To this end, I have implemented the Reshape shape infer for MXNet with the following code:

in mo.front.common.partial_infer.reshape.py:


    def _mx_reshape_shape_infer(in_shape : list, reshape : list):
        num_minus_1 = np.sum(np.array(reshape) == -1)
        if num_minus_1 > 1:
            log.error('num_minus_1=%d' % num_minus_1)
            return None

        out_shape = []
        in_shape_idx = 0

        reshape_idx = 0
        while reshape_idx < len(reshape):
            x = reshape[reshape_idx]

            if x > 0:
                out_shape.append(x)
                reshape_idx += 1
                in_shape_idx += 1
            else:
                if in_shape_idx >= len(in_shape):
                    log.error('in_shape_idx=%d' % (in_shape_idx))
                    return None

            if x == 0:
                out_shape.append(in_shape[in_shape_idx])
                in_shape_idx += 1
                reshape_idx += 1
            elif x == -1:
                out_shape.append(-1)
                reshape_idx += 1
            elif x == -2:
                while in_shape_idx < len(in_shape):
                    out_shape.append(in_shape[in_shape_idx])
                    in_shape_idx += 1
                reshape_idx += 1
            elif x == -3:
                if in_shape_idx + 1 >= len(in_shape):
                    log.error('in_shape_idx + 1=%d' % (in_shape_idx + 1,))
                    return None
                out_shape.append(in_shape[in_shape_idx] * in_shape[in_shape_idx+1])
                in_shape_idx += 2
                reshape_idx += 1
            elif x == -4:
                if reshape_idx + 2 >= len(reshape):
                    log.error('reshape_idx + 2=%d' % (reshape_idx + 2,))
                    return None
                dim1 = reshape[reshape_idx + 1]
                dim2 = reshape[reshape_idx + 2]
                if dim1 < -1 or dim2 < -1 or dim1 == 0 or dim2 == 0:
                    log.error('dim1=%d, dim2=%d' % (dim1, dim2))
                    return None
                if dim1 < 0 and dim2 < 0:
                    log.error('dim1=%d, dim2=%d' % (dim1, dim2))
                    return None
                if dim1 == -1:
                    dim1 = in_shape[in_shape_idx] / dim2
                if dim2 == -1:
                    dim2 = in_shape[in_shape_idx] / dim1
                if dim1 * dim2 != in_shape[in_shape_idx]:
                    log.error('dim1=%d, dim2=%d, original=%d' % (dim1, dim2, in_shape[in_shape_idx]))
                    return None
                out_shape.append(dim1)
                out_shape.append(dim2)
                reshape_idx += 3
                in_shape_idx += 1
            elif x < -4:
                log.error('x=%d' % x)
                return None

        known = 1
        unknown_pos = -1
        for i in range(len(out_shape)):
            x = out_shape[i]
            if x > 0:
                known *= x
            else:
                unknown_pos = i

        if unknown_pos >= 0:
            unknown_val = total / known
            out_shape[unknown_pos] = unknown_val

        return out_shape


    def mxnet_reshape_shape_infer(node):
        if node.in_node(0).shape is None:
            return None

        input_shape = node.in_node(0).shape
        reshape_output = node.in_node(1).value if len(node.in_nodes()) > 1 else node.dim
        if node.in_node(0).shape is None:
            return None
        total = 1
        for index, i in enumerate(input_shape):
            total *= i

        output_shape = _mx_reshape_shape_infer(input_shape, reshape_output)
        out_shape_total = 1
        for index, i in enumerate(output_shape):
            assert i != -1
            out_shape_total *= i

        if total != out_shape_total:
            log.error(
                "Number of elements in input {} and output {} of reshape node {} mismatch".format(input_shape, output_shape,
                                                                                                  node.name))
            return None

        return np.array(output_shape, dtype=np.int64)

in mo.front.mxnet.extractors.reshape.py:

    from mo.front.common.partial_infer.elemental import single_output_infer
    from mo.front.common.partial_infer.reshape import mxnet_reshape_shape_infer


    def reshape_ext(attr):
        dim = attr.tuple("shape", int, None)
        node_attrs = {
            'type': 'Reshape',
            'axis': 0,
            'num_axes': -1,
            'dim': np.array(dim),
            'infer': lambda node: single_output_infer(node, mxnet_reshape_shape_infer)
        }
        return node_attrs

**Comment by rocketbear** [comment]
In addition, when converting my ShuffleNet model to IR, I find that the MO is able to process the subgraph pattern of channel shuffle (reshape-transpose-reshape), as by the code in extensions.middle.ShufflenetReshape.py. However, this script is buggy and will produce the following error:

    File "/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/extensions/middle/ShufflenetReshape.py", line 96, in replace_pattern
        if not np.array_equal(feature_dims_split[::-1], transpose.order[feature_dims_split]):
    TypeError: only integer scalar arrays can be converted to a scalar index

To fix this error, the following change should be made:

original code:

    if not np.array_equal(feature_dims_split[::-1], transpose.order[feature_dims_split]):

changed to:

    if not np.array_equal(feature_dims_split[::-1], np.array(transpose.order)[feature_dims_split]):

**Comment by lazarevevgeny** [comment]
@rocketbear thank you for the information! We will add full support for MxNet Reshape operation in the future github repo updates.

And thank you for noticing bug in the ShufflenetReshape.py!

**Comment by rocketbear** [comment]
After the changes to the code, the IR can be generated correctly, and the result is correct if CNNNetwork::reshape is not called during run time. However, if the CNNNetwork::reshape is called, the output shape cannot be correctly computed. The Inference Engine fails to compute the correct output shape in this case. 

I have checked the code of 
[ie_reshape_shape_infer.hpp](https://github.com/opencv/dldt/blob/2018/inference-engine/src/inference_engine/shape_infer/built-in/ie_reshape_shape_infer.hpp#L35), and find that it is highly doubtful if this script could fulfil its purpose.

**Comment by lazarevevgeny** [comment]
The shape inference feature in the Inference Engine is in preview mode in current version, but it will be highly improved with the next update of the git repo.

**Comment by ljaljushkin** [comment]
@rocketbear you are right, current implementation of shape inference for Reshape layer does not support MXNet format. We will fix it later. 

But for now, I suggest removing all logic with "in2out" attribute in ie_reshape_shape_infer.cpp , because it was need for backward compatibility issues and add the corresponding implementation for more complex rules of MXNet Reshape (with values in {-4, -3, -2, -1, 0, >0})

**Comment by lazarevevgeny** [comment]
The support for -1, -2, -3 and -4 had been added to the MO. Please, take the latest OpenVINO and verify. Closing the ticket.
