### ISSUE TITLE
[Good First Issue]: Get rid of hardcoded properties name such as "EXPORT_IMPORT" from Python tests

### ISSUE THREAD

**Issue by akuporos** [openvinotoolkit/openvino#23047]
### Context

We have properties instead and should use them instead of hardcoded strings like "EXPORT_IMPORT", "OPTIMIZATION_CAPABILITIES" which are actually implementation details.

### What needs to be done?

Search across [this folder](https://github.com/openvinotoolkit/openvino/tree/master/src/bindings/python/tests) and find where properties are used like string objects (e.g. "OPTIMIZATION_CAPABILITIES"). 
OpenVINO Python API has dedicated [submodule](https://docs.openvino.ai/2023.3/api/ie_python_api/_autosummary/openvino.properties.html) for properties, so these string should be replaced by objects from `openvino.properties`.

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to test OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md#how-to-test-openvino-python-api)

### Contact points

@akuporos @jiwaszki @p-wysocki 

### Ticket

132906

**Comment by inbasperu** [comment]
.take
