### ISSUE TITLE
[Good First Issue]: Add 'pad' operator support for ov::preprocess::PrePostProcessor

### ISSUE THREAD

**Issue by riverlijunjie** [openvinotoolkit/openvino#23068]
### Context

Often computer vision models are trained on images with preserved aspect ratio. When feeding such models for inference, we must add padding after image resizing to avoid possible result distortions and inaccuracies.

The simplest way of padding is to add dummy pixels at the bottom (landscape orientation) or on the right-hand (portrait orientation) side of the image. Like this, we don't need any special post-processing compensation in case of object detection, pose estimation, or similar use-cases.

For performance reasons, it would help to embed this padding operation as part of the PrePostProcessor() module so that we can re-build the IR graph that handles padding natively.

Linked to: https://jira.devtools.intel.com/browse/CVS-121548

### What needs to be done?

1. Add new `pad` API for PreProcessSteps:
       https://github.com/openvinotoolkit/openvino/blob/master/src/core/include/openvino/core/preprocess/preprocess_steps.hpp

 2. Support padding mode:
     1) constant value - pads with a constant value.
     2) edge - pads with the edge values of array.

3. Test cases added:
      https://github.com/openvinotoolkit/openvino/blob/master/src/core/tests/preprocess.cpp

    

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

Preprocessing reference documation:
   - https://docs.openvino.ai/2023.3/openvino_docs_OV_UG_Preprocessing_Details.html

Target source code:
 - https://github.com/openvinotoolkit/openvino/tree/master/src/core/include/openvino/core/preprocess
 - https://github.com/openvinotoolkit/openvino/tree/master/src/core/src/preprocess

### Contact points

@ilya-lavrenov  @riverlijunjie

**Comment by ccinv** [comment]
.take
