### ISSUE TITLE
[Feature Request]: C API. A sets of post-process function which are similar to pre-process functions

### ISSUE THREAD

**Issue by wenbinc-Bin** [openvinotoolkit/openvino#23076]
### Request Description

 A sets of **post-process** functions including (convert_element_type, convert_color, convert_layout, scale, mean, color_format, memory_type). And these functions work when vaSuface is used as output. Also please add related **C API**. 

### Feature Use Case

I am adding openvino into ffmpeg, and I want to connect openvino to vaapi codec by using remote_context API. The vaSurface support is added into classify and detect filter, but blocked at dnn_processing filter. Dnn_processing filter inputs and outputs images. It needs "scale", "mean" and "color_format" change as pre-process and do reverse operations as post-processing. When the vaSurface is used, we cannot get desired output vaSurface, so I want to add post-processing functions. Because FFmpeg is a pure C project, please add related **C API**.

### Issue submission checklist

- [x] The feature request or improvement must be related to OpenVINO

**Comment by riverlijunjie** [comment]
We have 2 GFIs to implement this requirement in C++ API level, once they are done we can easily to implement the related C APIs:
https://github.com/openvinotoolkit/openvino/issues/22985
https://github.com/openvinotoolkit/openvino/issues/23004

**Comment by rkazants** [comment]
@jiwaszki, @mlukasze, fyi.
