### ISSUE TITLE
[Good First Issue]: BATCH Plugin doesn't support mandatory properties PERF_COUNT, NUM_STREAMS

### ISSUE THREAD

**Issue by zhaixuejun1993** [openvinotoolkit/openvino#23075]
### Context

Some api conformance tests are fails due to unsupported properties.

Unsupported properties:  PERF_COUNT 

Conformance tests are fails:
ov_plugin_mandatory/OVCheckSetSupportedRWMetricsPropsTests.ChangeCorrectProperties/target_device=BATCH_properties=\{PERF_COUNT:NO}
ov_plugin_mandatory/OVCheckSetSupportedRWMetricsPropsTests.ChangeCorrectProperties/target_device=BATCH_properties=\{PERF_COUNT:YES}
ov_plugin_mandatory/OVPropertiesTests.SetCorrectProperties/target_device=BATCH_properties=\{PERF_COUNT:YES}
ov_plugin_mandatory/OVPropertiesTests.canSetPropertyAndCheckGetProperty/target_device=BATCH_properties=\{PERF_COUNT:YES}
ov_plugin_mandatory/OVCheckSetIncorrectRWMetricsPropsTests.ChangeIncorrectProperties/target_device=BATCH_properties=\{PERF_COUNT:-1}
 

To reproduce, please, build ov_api_conformance_tests, then run run_conformance.py with appropriate filter:

python openvino/src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_conformance.py --device=BATCH --gtest_filter="*ov_plugin_mandatory/OVCheckSetSupportedRWMetricsPropsTests.ChangeCorrectProperties/target_device*BATCH*properties*NUM_STREAMS*"  --type=API{code}
or ov_api_conformance_tests directly:

openvino/bin/intel64/Debug/ov_api_conformance_tests --device=BATCH --input_folders=/some/path/conformance_ir_files.lst --gtest_filter=*ov_plugin_mandatory/OVCheckSetSupportedRWMetricsPropsTests.ChangeCorrectProperties/target_device*BATCH*properties*NUM_STREAMS*{code}

### What needs to be done?

- [ ] Add PERF_COUNT, NUM_STREAMS to BATCH Plugin support properties
https://github.com/openvinotoolkit/openvino/blob/f9605cd8d4c488ad405397bc4294e35a403ae803/src/plugins/auto_batch/src/plugin.cpp#L22
- [ ] Add test
https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/auto_batch/tests/unit/plugin_get_property_test.cpp

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@zhaixuejun1993 @riverlijunjie @peterchen-intel @vurusovs 

### Ticket

CVS-130236

**Comment by himanshugupta11002** [comment]
.take

**Comment by p-wysocki** [comment]
Hi @zhaixuejun1993, could you please check if you can link the PR to the issue here?
![image](https://github.com/openvinotoolkit/openvino/assets/55858107/d69b28da-e7a1-4b5e-97ec-e3ff935ddb90)
For some reason the search bar can't find the PR for me, neither with branch name, PR name nor PR number.

**Comment by zhaixuejun1993** [comment]
> Hi @zhaixuejun1993, could you please check if you can link the PR to the issue here? ![image](https://private-user-images.githubusercontent.com/55858107/312035698-d69b28da-e7a1-4b5e-97ec-e3ff935ddb90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTg5MDIsIm5iZiI6MTcxMDM5ODYwMiwicGF0aCI6Ii81NTg1ODEwNy8zMTIwMzU2OTgtZDY5YjI4ZGEtZTdhMS00YjVlLTk3ZWMtZTNmZjkzNWRkYjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA2NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZDA5MTkzNTdiZWY4NGI3NDYwYTk4ODJhY2ZhMTJlMzQ3OTNmYTNhOTQwODA3MzA4MmIwOGY4MzVkZDA1MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z3tUTUopPoGutpeHRu7wrPGH1PCm1smosU942SxjNeo) For some reason the search bar can't find the PR for me, neither with branch name, PR name nor PR number.

can u find your own repo, such as mine:
![image](https://github.com/openvinotoolkit/openvino/assets/52686861/b57fa74e-92d5-453a-87e0-68ba6c2d367b)

**Comment by mlukasze** [comment]
I've linked them together, please check is it correct
