### ISSUE TITLE
[Feature Request]: How to check whether OneDNN work well for GPU plugin 

### ISSUE THREAD

**Issue by zhangnju** [openvinotoolkit/openvino#23070]
### Request Description

I found in the CMakelist file of GPU plugin has include the building macro for oneDNN, as shown below.
# # oneDNN for GPU plugin #
if(ENABLE_ONEDNN_FOR_GPU)

how do we check whether oneDNN for GPU plugin has been compiled successfully and work well when running GPU inference?

or could you help share the detailed compilation command for GPU plugin inference with oneDNN?  

### Feature Use Case

GPU inference through oneDNN 

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by ilya-lavrenov** [comment]
Hi @zhangnju 
oneDNN is compiled by default for GPU plugin, when dynamic build (default is `ON`) is used.
During static build oneDNN for GPU is disabled, because oneDNN for CPU has higher priority.

CPU and GPU use different versions of oneDNN, that is why we can have conflicts in case of static build.

**Comment by zhangnju** [comment]
HI  @ilya-lavrenov 

Thanks for your reply. for the below codes, we will run into get_engine().create_onednn_engine(config) by default, is it right? 
 
    if (need_onednn_engine) {
#ifdef ENABLE_ONEDNN_FOR_GPU
        get_engine().create_onednn_engine(config);
#else
        OPENVINO_THROW("[GPU] Current model cache requires OneDNN, but cannot use it.");
#endif  // ENABLE_ONEDNN_FOR_GPU
    }

**Comment by sshlyapn** [comment]
@zhangnju additionally, you can check if oneDNN is used for inference by setting `ONEDNN_VERBOSE=1` environment variable. If it's being utilized, you will see logs like these in the console:
```
onednn_verbose,info,oneDNN v3.3.0 (commit 41e05c66f91fa6fbbddedff0eb9b33913cf44fdc)
onednn_verbose,info,gpu,runtime:OpenCL
onednn_verbose,info,gpu,engine,0,name:Intel(R) Arc(TM) A770 Graphics
onednn_verbose,primitive,info,template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,primitive,exec,gpu:0,convolution,jit:ir,forward_inference,src_s8::blocked:abcd::f0 wei_s8:ap:blocked:AcdB8a4b::f0 bia_f32:a:blocked:a::f0 dst_u8::blocked:aBcd32b::f0,attr-scratchpad:user attr-post-ops:binary_mul:f32:2 ,alg:convolution_direct,mb1_ic3oc32_ih299oh149kh3sh2dh0ph0_iw299ow149kw3sw2dw0pw0,0.11084
...
```
Please note, currently oneDNN is utilized only for HW with Intel Xe Matrix Extensions (Intel XMX) support

**Comment by zhangnju** [comment]
HI @sshlyapn  Thanks for your info. ONEDNN_VERBOSE=1 is a very useful setting for checking log.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
