### ISSUE TITLE
[Good First Issue]: Throw exception for invalid device list to BATCH

### ISSUE THREAD

**Issue by peterchen-intel** [openvinotoolkit/openvino#23125]
### Context

Following executions should throw correct exception.
```
python3 -c "import openvino; openvino.Core().compile_model(<model path>, 'BATCH:-GPU')" 
Execute successfully
```

**Expected behavior:** Throw exception "Invalid device name '-GPU' for BATCH"

```
python3 -c "import openvino; openvino.Core().compile_model(<model path>, 'BATCH:GPU,CPU')" 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/openvino-ci-42/peter/py39/lib/python3.9/site-packages/openvino/runtime/ie_api.py", line 547, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/core.cpp:116:
[ GENERAL_ERROR ] Exception from src/inference/src/dev/core_impl.cpp:560:
Device with "GPU,CPU" name is not registered in the OpenVINO Runtime
```
**Expected behavior:** Throw exception "BATCH accepts only one device in list."

### What needs to be done?

Validate the device name in BATCH plugin while doing the compile_model

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [BATCH user guide](https://docs.openvino.ai/2023.3/openvino_docs_OV_UG_Automatic_Batching.html)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@zhaixuejun1993  @riverlijunjie  @ilya-lavrenov @vurusovs @peterchen-intel

### Ticket

CVS-132276

**Comment by AsakusaRinne** [comment]
.take

**Comment by AsakusaRinne** [comment]
@peterchen-intel Hi, the reason of 'BATCH:-GPU' with no exception is the following code ([src/inference/src/dev/core_impl.cpp:542](https://github.com/openvinotoolkit/openvino/blob/master/src/inference/src/dev/core_impl.cpp#L542)).

```
stripDeviceName(deviceName, "-");
```

Since it's added by a developer intentionally in the past, could you please help to confirm whether it's an unexpected behavior? Thank you!

**Comment by riverlijunjie** [comment]
> @peterchen-intel Hi, the reason of 'BATCH:-GPU' with no exception is the following code ([src/inference/src/dev/core_impl.cpp:542](https://github.com/openvinotoolkit/openvino/blob/master/src/inference/src/dev/core_impl.cpp#L542)).
> 
> ```
> stripDeviceName(deviceName, "-");
> ```
> 
> Since it's added by a developer intentionally in the past, could you please help to confirm whether it's an unexpected behavior? Thank you!

@AsakusaRinne I supposed above code line is correct, and we should check `ov::device::Priorities` property to BATCH plugin doesn't contain "-", such as "-GPU" value is invalid.

**Comment by AsakusaRinne** [comment]
@riverlijunjie Thank you a lot for your comment, though I think I'm still lost. When I have device name as `BATCH:-GPU`, here's the processing of it.

```cpp
ov::Plugin ov::CoreImpl::get_plugin(const std::string& pluginName) const {
    OV_ITT_SCOPE(FIRST_INFERENCE, ov::itt::domains::LoadTime, "CoreImpl::get_plugin");

    auto deviceName = pluginName;
    // deviceName = "-GPU"
    if (deviceName == ov::DEFAULT_DEVICE_NAME)
        deviceName = "AUTO";
    stripDeviceName(deviceName, "-");
    // After the strip, we have deviceName = "GPU"
    std::map<std::string, PluginDescriptor>::const_iterator it;
    {
        std::lock_guard<std::mutex> g_lock(get_mutex());

        it = pluginRegistry.find(deviceName);
        // "GPU" is a valid device name so we find plugin successfully with no exception.
        if (it == pluginRegistry.end()) {
            if (pluginName == ov::DEFAULT_DEVICE_NAME)
                OPENVINO_THROW("No device is provided, so AUTO device is used by default, which is not registered in "
                               "the OpenVINO Runtime.");
            else
                OPENVINO_THROW("Device with \"", deviceName, "\" name is not registered in the OpenVINO Runtime");
        }
    }
```

Once I removed the code line of stripping device name, "-GPU" could be successfully checked and throw an exception. Therefore I wonder if we should remove the code line if "BATCH:-GPU" is really an unexpected behavior.

**Comment by riverlijunjie** [comment]
From BATCH plugin behavior perspective, it makes sense to remove this line. But we not sure whether it will bring any side effect for other meta plugin or `ov::device::Priorities` property. @peterchen-intel can help comment it?
As we known, `-pluginName` means to exclude this specified device, AUTO plugin has logic to do such work; but BATCH plugin doesn't check it, so we can fix it in BATCH plugin without any side effect.

**Comment by mlukasze** [comment]
Congratulations @AsakusaRinne for your first merged PR into OpenVINO project!
Your change will be a part of 2024.1 release :)
