### ISSUE TITLE
[Improvement] Allow configuration of library download directory

### ISSUE THREAD

**Issue by abrown** [openvinotoolkit/openvino#2316]
When attempting to build OpenVINO using the [build instructions](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md), I do not see a way to configure the library download directory. Currently, libraries are downloaded to `inference-engine/temp` but these changes in-tree cause issues with build tools like Cargo; I would like to be able to specify a `LIB_DOWNLOAD_DIR` or the like so that CMake will download the files outside of the OpenVINO tree and link to them there. I have searched through the CMake files to determine if there is an undocumented variable to do this but cannot find this. Could someone document such a variable if it exists or add it otherwise?

**Comment by jgespino** [comment]
Hi @abrown 

I don't see any cmake options to specify the library download directory. I went ahead and opened a feature request on your behalf for the development team to consider.

Regards,
Jesus

Ref. 39402

**Comment by abrown** [comment]
@sahira-rizvi, what is the resolution of the feature request @jgespino opened? I feel like that should be noted here when closing the issue.
