### ISSUE TITLE
[Good First Issue][Bug][Core]: Lack of support for "::" in the network input name

### ISSUE THREAD

**Issue by mlukasze** [openvinotoolkit/openvino#23193]
### Context

The defect is noticeable in the GNA plugin during the speech_sample run when the input name is "onnx::input".
Looks like problem is in core/include/openvino/core/any.hpp

class:
template <typename K, typename T, typename C, typename A>
struct Read...

method:
void operator()(std::istream& is, std::map<K, T, C, A>& map) const

used by GNAPlugin for reading configuration from the map.
Introduced by:
https://github.com/openvinotoolkit/openvino/commit/0c99135d44ecc0708b44b78efcaaaada1fa79dac#diff-edee69cfd9ef2465d19b979385c61a944b5eacd7780d1a3ae03784f324b941a8

### What needs to be done?

to fix a problem in described scenario

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@vurusovs @nkogteva 

### Ticket

CVS-119173

**Comment by vurusovs** [comment]
Closing as not reproducible

**Comment by ilya-lavrenov** [comment]
> Closing as not reproducible

Do we have a test which shows it's not reproduced?
