### ISSUE TITLE
[Good First Issue][Bug]Core]: ov::Any::as does not work with bad_cast on clang and -stdlib=libc++

### ISSUE THREAD

**Issue by mlukasze** [openvinotoolkit/openvino#23191]
### Context

Exception from src/inference/src/core.cpp:245:
Exception from src/inference/src/dev/core_impl.cpp:739:
Failed to create plugin /home/conan/.conan2/p/b/openv4aa89cf30cc41/p/lib/libopenvino_intel_cpu_plugin.so for device CPU
Please, check your environment
Exception from src/core/include/openvino/core/any.hpp:835:
Bad cast from: NSt3_16vectorIN2ov12PropertyNameENS_9allocatorIS2_EEEE to: NSt3_16vectorIN2ov12PropertyNameENS_9allocatorIS2_EEEE

 

Can be reproduced with:

docker run -it --rm -v `pwd`/openvino:/home/conan//openvino -v `pwd`/conan-center-index:/home/conan/conan-center-index conanio/clang12-ubuntu16.04:latest

conan create . --version 2023.1.0 -b missing -s build_type=Debug -s compiler.libcxx=libc++

### What needs to be done?

to extend `ov::Any::as` to cover scenario described in title

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@vurusovs 

### Ticket

CVS-120052

**Comment by jdecorte-be** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @jdecorte-be, are you still working on this? Is there anything we could help you with?

**Comment by jdecorte-be** [comment]
Hello @p-wysocki, It took me a little while to understand Conan, but now I think I understand it better. I guess I had to comment out this part of the code:

```
        # OpenVINO has unresolved symbols, when clang is used with libc++
 #       if self.settings.compiler == "clang" and self.settings.compiler.libcxx == "libc++":
  #          raise ConanInvalidConfiguration(
   #             f"{self.ref} cannot be built with clang and libc++ due to unresolved symbols. "
    #            f"Please, use libstdc++ instead."
     #       )

        if self.settings.os == "Emscripten":
            raise ConanInvalidConfiguration(f"{self.ref} does not support Emscripten")

        # TODO: resolve it later, since it is not critical for now
        # Conan Center CI fails with our of memory error when building OpenVINO
 #       if self.settings.build_type == "Debug":
  #          raise ConanInvalidConfiguration(f"{self.ref} does not support Debug build type")

```

So now I managed to reproduce the "conan create"
I should be able to move faster now!

Is there a way to "conan create" faster?

**Comment by p-wysocki** [comment]
cc @vurusovs

**Comment by Aryan8912** [comment]
.take

**Comment by Aryan8912** [comment]
ERROR: Conanfile not found at C:\Users\aryan\Desktop\openvino\conanfile.py

**Comment by p-wysocki** [comment]
Hello @Aryan8912, there are currently three issues with open PRs assigned to you. Please finish them before picking more tasks.

**Comment by t-jankowski** [comment]
Closing this issue because:
OpenVINO 2023.1 is not supported on Ubuntu 16 - https://docs.openvino.ai/archive/2023.1/system_requirements.html
clang-12 libc++ doesn't fully support c++11 - https://libcxx.llvm.org/index.html
