### ISSUE TITLE
[Good First Issue][TF FE]: Support TensorScatterUpdate operation for TensorFlow

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#23247]
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.2/openvino_docs_ops_opset13.html).

In order to infer TensorFlow models with [TensorScatterUpdate](https://www.tensorflow.org/api_docs/python/tf/raw_ops/TensorScatterUpdate) operation by OpenVINO, TF FE needs to be extended with this operation support.

### What needs to be done?

For [TensorScatterUpdate](https://www.tensorflow.org/api_docs/python/tf/raw_ops/TensorScatterUpdate) operation support, you need to implement the corresponding loader into TF FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of TensorFlow operation.

Here is an example of loader implementation for TensorFlow `Einsum` operation:

```cpp
OutputVector translate_einsum_op(const NodeContext& node) { 
     auto op_type = node.get_op_type(); 
     TENSORFLOW_OP_VALIDATION(node, op_type == "Einsum", "Internal error: incorrect usage of translate_einsum_op."); 
     auto equation = node.get_attribute<std::string>("equation"); 
  
     OutputVector inputs; 
     for (size_t input_ind = 0; input_ind < node.get_input_size(); ++input_ind) { 
         inputs.push_back(node.get_input(input_ind)); 
     } 
  
     auto einsum = make_shared<Einsum>(inputs, equation); 
     set_node_name(node.get_name(), einsum); 
     return {einsum}; 
 } 
```

In this example, `translate_einsum_op` converts TF `Einsum` into OV `Einsum`. `NodeContext` object passed into the loader packs all info about inputs and attributes of `Einsum` operation. The loader retrieves an attribute of the equation by using the `NodeContext::get_attribute()` method, prepares input vector, creates `Einsum` operation from OV opset and returns a vector of outputs.

Responsibility of a loader is to parse operation attributes, prepare inputs and express TF operation via OV operations sub-graph. Example for `Einsum` demonstrates the resulted sub-graph with one operation. In PR https://github.com/openvinotoolkit/openvino/pull/19007 you can see operation decomposition into multiple node sub-graph.

Once you are done with implementation of the translator, you need to implement the corresponding layer tests `test_tf_MatrixInverse.py` and put it into [layer_tests/tensorflow_tests](https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/tensorflow_tests) directory. Example how to run some layer test:

```
export TEST_DEVICE=CPU
cd openvino/tests/layer_tests/tensorflow_tests
pytest test_tf_Shape.py
```

### Hint

Check ScatterNDUpdate in OV opset for this support

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/19007

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

- @openvinotoolkit/openvino-tf-frontend-maintainers
- @rkazants in GitHub
- rkazants in Discord

**Comment by MonalSD** [comment]
.take

**Comment by dyogaharshitha** [comment]
.take

**Comment by swapna1507** [comment]
.take

**Comment by mlukasze** [comment]
hey @swapna1507 do you need any support? :)

**Comment by swapna1507** [comment]
Hello Michal,

Thank you for checking on me. Just got caught up with work and
unfortunately I won’t be able to contribute and commit to this as much
until September.

Thank you for your understanding, apologies from my end for committing to
this and not giving enough.

Regards,
Swapna Manikandan

**Comment by mlukasze** [comment]
No problem at all, we will be here at September for sure, in case you would like to work with us at this time :)

**Comment by swapna1507** [comment]
Perfect! Thank you so much. Will definitely love to!

**Comment by hub-bla** [comment]
.take
