### ISSUE TITLE
[Good First Issue]: Add test for `CoreImpl::get_versions()`

### ISSUE THREAD

**Issue by vurusovs** [openvinotoolkit/openvino#23298]
### Context

After https://github.com/openvinotoolkit/openvino/pull/22667 method `CoreImpl::get_versions()` has new logic based on string parsing:

`if (exception.find("not registered in the OpenVINO Runtime")...`

Need to add test to cover such case in order to prevent any unexpected changes

### What needs to be done?

Test for https://github.com/openvinotoolkit/openvino/blob/3bdd728995fc2fbe9c91f00cc406145918f099b3/src/inference/src/dev/core_impl.cpp#L1630-L1632 to be added in src\inference\tests\functional\ov_register_plugin_test.cpp

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@vurusovs @olpipi

### Ticket

CVS-132140

**Comment by awayzjj** [comment]
.take

**Comment by awayzjj** [comment]
There is already a test case

**Comment by awayzjj** [comment]
@vurusovs @olpipi  Hi, I found there is already a test case below that should cover these three lines. The call stack is as follows:
https://github.com/openvinotoolkit/openvino/blob/4f8f5731958cbe6a7aeb3dd18f24d1f74249cf32/src/inference/tests/functional/ov_register_plugin_test.cpp#L77
https://github.com/openvinotoolkit/openvino/blob/4f8f5731958cbe6a7aeb3dd18f24d1f74249cf32/src/inference/src/dev/core_impl.cpp#L1626
https://github.com/openvinotoolkit/openvino/blob/4f8f5731958cbe6a7aeb3dd18f24d1f74249cf32/src/inference/src/dev/core_impl.cpp#L582

https://github.com/openvinotoolkit/openvino/blob/4f8f5731958cbe6a7aeb3dd18f24d1f74249cf32/src/common/util/src/os/lin/lin_shared_object_loader.cpp#L33
This test case is designed to raise an exception from lin_shared_object_loader.cpp, but the type of exception thrown is `std::runtime_error`. As a result, it cannot be caught by `ov::Exception` as seen in the following code:
https://github.com/openvinotoolkit/openvino/blob/4f8f5731958cbe6a7aeb3dd18f24d1f74249cf32/src/inference/src/dev/core_impl.cpp#L1628-L1633
However, it is caught by the macro OV_CORE_CALL_STATEMENT used in the following code:
https://github.com/openvinotoolkit/openvino/blob/4f8f5731958cbe6a7aeb3dd18f24d1f74249cf32/src/inference/src/cpp/core.cpp#L80-L82
https://github.com/openvinotoolkit/openvino/blob/4f8f5731958cbe6a7aeb3dd18f24d1f74249cf32/src/inference/src/cpp/core.cpp#L54-L61

I am wondering if I can replace `} catch (const ov::Exception& ex) {` with `} catch (const std::runtime_error& ex) {` in the 1628 line of core_impl.cpp, so the exception won't be caught in core.cpp

I tested this locally on my PC, and the log output indicates that the exception is indeed of type `std::runtime_error` and the 3 lines is covered by the test case. The attached screenshots show the details.
<img width="929" alt="截屏2024-03-07 23 47 47" src="https://github.com/openvinotoolkit/openvino/assets/38181615/0ba7be74-b2bf-4223-b4ee-30869222f141">



<img width="1279" alt="截屏2024-03-07 23 44 26" src="https://github.com/openvinotoolkit/openvino/assets/38181615/0a401b0d-21fa-4203-886e-4223d95ebc95">

**Comment by awayzjj** [comment]
@vurusovs Thank you for your reply! I have found a test case for an unregistered plugin name, which checks that no exception are thrown. Is there still a need for me to add a new test case, or is the existing one sufficient?

https://github.com/openvinotoolkit/openvino/blob/4f8f5731958cbe6a7aeb3dd18f24d1f74249cf32/src/inference/tests/functional/ov_register_plugin_test.cpp#L53-L55

**Comment by vurusovs** [comment]
@awayzjj yes, it's actually what we needed, but I missed that it's already implemented. Anyway, could you extend the test with check that `get_versions(...)` return empty value?

**Comment by awayzjj** [comment]
@vurusovs Thank you for your reply! I extended the test with check that get_versions(...) return empty value. Could you please review the PR?
