### ISSUE TITLE
Model Optimizer : Error while creating IR files of Tensorflow Model

### ISSUE THREAD

**Issue by nehasoni3** [openvinotoolkit/openvino#233]
Hi
I am getting error on converting tensorflow model (frozen .pb) into IR files. I have installed all pre-requistics for model optimizer. 
I have used this command to convert model into IR files-
`python3 mo_tf.py --input_model /path_of_model --output_dir /path_of_destination_folder --data_type FP16`

I am getting this error-
`[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  shapes (128,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)
[ ERROR ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2019.2.242/deployment_tools/model_optimizer/mo/main.py", line 302, in main
    return driver(argv)
  File "/opt/intel/openvino_2019.2.242/deployment_tools/model_optimizer/mo/main.py", line 251, in driver
    is_binary=not argv.input_model_is_text)
  File "/opt/intel/openvino_2019.2.242/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 159, in tf2nx
    for_graph_and_each_sub_graph_recursively(graph, fuse_linear_ops)
  File "/opt/intel/openvino_2019.2.242/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/opt/intel/openvino_2019.2.242/deployment_tools/model_optimizer/mo/middle/passes/fusing/fuse_linear_ops.py", line 267, in fuse_linear_ops
    is_fused = _fuse_add(graph, node, fuse_nodes, False)
  File "/opt/intel/openvino_2019.2.242/deployment_tools/model_optimizer/mo/middle/passes/fusing/fuse_linear_ops.py", line 206, in _fuse_add
    fuse_node.in_port(2).data.set_value(bias_value + np.dot(fuse_node.in_port(1).data.get_value(), value))
ValueError: shapes (128,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------`

please do needful.

**Comment by shubha-ramani** [comment]
Dear @nehasoni3 
Can you kindly tell me more about your model ? Is it Tensorflow Object Detection API ? Because if so, your command is incorrect.

[The Model Optimizer Tensorflow Object Detection API Doc ](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html) will highlight several missing arguments in your mo_tf.py command.

Let me know if you need more help.

Thanks,

Shubha

**Comment by nehasoni3** [comment]
hi @shubha-ramani 

Thanks for responding.
Model is simple CNN based. It is not Tensorflow Object Detection API. It is a custom CNN model.

**Comment by shubha-ramani** [comment]
@nehasoni3 that's fine. CNN should definitely be supported by Model Optimizer. Can you kindly attach your model to this ticket as a *.zip ?

Thanks,

Shubha

**Comment by lazarevevgeny** [comment]
@nehasoni3 is this issue still actual? Can you share the model?

**Comment by AnastasiaKazantaeva** [comment]
It seems that this issue is not actual anymore, close it. Feel free to create a new issue in cases of some questions/problems
