### ISSUE TITLE
[Good First Issue]: Support aten::index_fill_ for pytorch models

### ISSUE THREAD

**Issue by mvafin** [openvinotoolkit/openvino#23326]
### Context

OpenVINO component responsible for support of PyTorch models is called as PyTorch Frontend (PT FE). PT FE converts a model represented as TorchScript model to a model in [OpenVINO opset](https://docs.openvino.ai/latest/openvino_docs_ops_opset.html).

### What needs to be done?

- Implement conversion rule and/or transformation to support the new operation.
- Implement operation tests in tests/layer_tests/pytorch_tests. Please consider different data types, but keep reasonable number of test cases

### Example Pull Requests

#18998

### Resources

- [torch.Tensor.index_fill_ description](https://pytorch.org/docs/stable/generated/torch.Tensor.index_fill_.html#torch.Tensor.index_fill_)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO PyTorch Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/pytorch/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-pytorch-frontend-maintainers 

### Ticket

TBD

**Comment by AKFORTY7** [comment]
.take

**Comment by atharvameshram** [comment]
.take

**Comment by muhd360** [comment]
I would like to be assigned this issue

**Comment by mlukasze** [comment]
the task is yours now @muhd360 :)

**Comment by muhd360** [comment]
thanks

**Comment by mlukasze** [comment]
hey @muhd360 any help needed?

**Comment by cocoshe** [comment]
Hello there! @mvafin @mlukasze @p-wysocki May I take the issue?

**Comment by mlukasze** [comment]
@cocoshe  - it's all yours, have fun!

**Comment by cocoshe** [comment]
@mlukasze Hi, pls review my pr here~ https://github.com/openvinotoolkit/openvino/pull/27420

**Comment by cocoshe** [comment]
@mlukasze Anything else needs to be done? Or just wait for the review?👀

**Comment by cocoshe** [comment]
> yes, we are waiting for the review, sorry for the delay, it's on us

Never mind~
