### ISSUE TITLE
[Good First Issue]: Support aten::masked_select for pytorch models

### ISSUE THREAD

**Issue by mvafin** [openvinotoolkit/openvino#23325]
### Context

OpenVINO component responsible for support of PyTorch models is called as PyTorch Frontend (PT FE). PT FE converts a model represented as TorchScript model to a model in [OpenVINO opset](https://docs.openvino.ai/latest/openvino_docs_ops_opset.html).

### What needs to be done?

- Implement conversion rule and/or transformation to support the new operation.
- Implement operation tests in tests/layer_tests/pytorch_tests. Please consider different data types, but keep reasonable number of test cases

### Example Pull Requests

#18998

### Resources

- [torch.masked_select description](https://pytorch.org/docs/stable/generated/torch.masked_select.html#torch-masked-select)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO PyTorch Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/pytorch/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-pytorch-frontend-maintainers 

### Ticket

TBD

**Comment by YutingGao7** [comment]
.take

**Comment by psmaxwell** [comment]
#WLB# + .take

**Comment by p-wysocki** [comment]
Hello @psmaxwell, are you still working on that issue? Do you need any help?

**Comment by hub-bla** [comment]
.take

**Comment by hub-bla** [comment]
This issue should be closed after this PR #26162.

**Comment by mlukasze** [comment]
@mvafin please verify and make actions accordingly
