### ISSUE TITLE
[Docs]: Release notes link to model conversion transition guide is 404

### ISSUE THREAD

**Issue by veikk0** [openvinotoolkit/openvino#23320]
### Documentation link

https://docs.openvino.ai/2024/openvino_docs_OV_Converter_UG_prepare_model_convert_model_MO_OVC_transition.html

### Description

From [the release notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino/2024-0.html) for 2024.0:

>* Model Optimizer will be discontinued with OpenVINO 2025.0. Consider using OpenVINO [Model Converter](https://docs.openvino.ai/2024/openvino-workflow/model-preparation/convert-model-to-ir.html) (API call: OVC) instead. Follow the model conversion [transition guide](https://docs.openvino.ai/2024/openvino_docs_OV_Converter_UG_prepare_model_convert_model_MO_OVC_transition.html) for more details.

However, the transition guide link leads to a 404 page.

### Issue submission checklist

- [X] I'm reporting a documentation issue. It's not a question.

**Comment by mlukasze** [comment]
thanks for info, Karol will take a look on that.

**Comment by avitial** [comment]
Ref. 138074

**Comment by kblaszczak-intel** [comment]
The link has been fixed, thanks for catching the bug!
