### ISSUE TITLE
[Good first issue] Port Core.get_versions() method to JS API

### ISSUE THREAD

**Issue by vishniakov-nikolai** [openvinotoolkit/openvino#23430]
### Context

JS API is a young branch of other OpenVINO bindings.
The bindings essentially map the functions or methods exposed by the API in the original language to equivalent constructs in the target language.
Original language in this case it's C++ and JS is the target language.
We propose to start learning OpenVINO from the implementation simple feature for JS API.

**Port **Core.get_versions()** method to JS API**

In C++ API, Core has [get_versions](https://docs.openvino.ai/2024/api/c_cpp_api/classov_1_1_core.html#_CPPv4NK2ov4Core12get_versionsERKNSt6stringE) method.
It would be great to have this method in JS API. You need to implement Node.js bindings for this method.
As examples of implementation, please, review Example PRs section below.

You can learn:
- How to compile OpenVINO from sources
- How Node.js bindings works
- Write some TypeScript code
- Be prepared for the next feature request in big opensource product

### What needs to be done?

- Add interface implementation to addon.ts
- Write js test for this method
- Add method definition into bindings (core_wrap.hpp)
- Implement this method in bindings (core_wrap.cpp)

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/22100
- https://github.com/openvinotoolkit/openvino/pull/23338

### Resources
- [JS API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@vishniakov-nikolai @almilosz

### Ticket

134816

**Comment by hiirrxnn** [comment]
Hey , can I take this up?

**Comment by vishniakov-nikolai** [comment]
> Hey , can I take this up?

Sure! I assigned it to you. Please let us know if you have any questions or require any help.

**Comment by vishniakov-nikolai** [comment]
Hi @hiirrxnn, I unassigned you because @adismort14 already implemented this issue.

**Comment by adismort14** [comment]
.take
