### ISSUE TITLE
[Good First Issue]: Expose Tensor.get_size() method to Node.js API

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#23440]
### Context

Node.js API is the newest binding of OpenVINO.
The task is to expose `Tensor.get_size()` method. 
[C++ API](https://docs.openvino.ai/2024/api/c_cpp_api/classov_1_1_tensor.html#_CPPv4NK2ov6Tensor8get_sizeEv) and[ Python API](https://docs.openvino.ai/2022.3/api/ie_python_api/_autosummary/openvino.runtime.Tensor.html#openvino.runtime.Tensor.get_size) documentation of this method

### What needs to be done?

 - add `get_size()` method on C++ side (_src/bindings/js/node/src/tensor.cpp_)
 - update TypeScript definition (_src/bindings/js/node/lib/addon.ts_)
 - create unit test for added functionality using Node.js Test Runner

### Example Pull Requests

Here is the link to a PR with a very similar task that covers the steps listed above:
- https://github.com/openvinotoolkit/openvino/pull/22100

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai 

### Ticket

134826

**Comment by hiirrxnn** [comment]
Hi , can I work on this ? Thank you.

**Comment by qxprakash** [comment]
Hi @almilosz I would like to work on this issue thanks.

**Comment by qxprakash** [comment]
.take

**Comment by vishniakov-nikolai** [comment]
> Hi , can I work on this ? Thank you.

Hi @hiirrxnn, thank you for your interest! Unfortunately this issue has taken, but this JS API issue is still waiting to be assigned: https://github.com/orgs/openvinotoolkit/projects/3/views/1?pane=issue&itemId=56296668, feel free to take it!

**Comment by qxprakash** [comment]
hello @vishniakov-nikolai , Ideally I should also validate the parameters of Tensor.get_size() right ? , if user passes any arguments it should throw an error similar to something like the python api ? 
`TypeError: get_size(): incompatible function arguments. The following argument types are supported:
    1. (self: openvino._pyopenvino.Tensor) -> int`

**Comment by qxprakash** [comment]
@vishniakov-nikolai , do you have other unassigned JS-api issues which are not being worked upon ? , I would like to contribute to it , Thanks.

**Comment by mlukasze** [comment]
Hey @qxprakash !

Nikolai is on short vacation but on behalf of him I can guarantee that more tasks related to JS bindings is coming :)
Stay tune and check our [JS GFI Project](https://github.com/orgs/openvinotoolkit/projects/3/views/14) board from time to time :)

**Comment by qxprakash** [comment]
hello @mlukasze , can you please review my pr ? Thanks !
