### ISSUE TITLE
[Good First Issue]: Node.get_attributes() doesn't return all attributes

### ISSUE THREAD

**Issue by mlukasze** [openvinotoolkit/openvino#23455]
### Context

Looks like there is some unintentional filtering for attributes, possibly because of unsupported attribute types in get_attributes implementation.

### What needs to be done?

Fix behavior for attributes:

* Parameter: shape (element_type exists)
* ReadValue: variable_shape, variable_id (variable_type exists)
* Assign: variable_id

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@jiwaszki 
@akuporos 

### Ticket

CVS-130832

**Comment by BHbean** [comment]
.take

**Comment by BHbean** [comment]
Hi there! I am a really new comer to this project, and i choose this issue as my startup for GSoC 2024. It might take me some time to read related docs first and it would be really helpful if you could offer me a helping hand!

 My first question is: which files should i focus on to solve this issue?

Thanks in advance for your help!

**Comment by akuporos** [comment]
Hi @BHbean,

Good point to start is [this file](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/node.cpp#L374).
Please, also try this reproduction. It may help you to resolve the issue and base tests on it.
```python
import numpy as np
import openvino.runtime.opset14 as ops

parameter = ops.parameter([2, 2], dtype=np.float32, name="InputData")
parameter_attributes = parameter.get_attributes()
assert parameter_attributes["element_type"] == 'f32'
# uncomment -- will fail, need to fix
# assert parameter_attributes["pshape"] == [2, 2]
print(parameter_attributes)

read_value = ops.read_value(parameter, "var_id_667", np.float32, [2, 2])
read_value_attributes = read_value.get_attributes()
assert read_value_attributes["variable_type"] == 'f32'
# uncomment -- will fail, need to fix
# assert read_value_attributes["variable_id"] == "var_id_667"
# assert read_value_attributes["variable_shape"] == [2, 2]
print(read_value_attributes)

assign = ops.assign(read_value, "var_id_667")
assign_attributes = assign.get_attributes()
# uncomment -- will fail, need to fix
# assert read_value_attributes["variable_id"] == "var_id_667"
print(assign_attributes)
```

**Comment by BHbean** [comment]
Thanks a lot for your guidance! I will try to go through the files and to fix this issue! :)
