### ISSUE TITLE
[Good First Issue]: Simplify `AvgPool-14` and `AvgPool-1` by implementing `AvgPoolBase`

### ISSUE THREAD

**Issue by p-wysocki** [openvinotoolkit/openvino#23465]
### Context

We strive to have our codebase as clean and readable as possible. A recent PR introduced `MaxPool-14`, which is different from `MaxPool-1` only in selectable values of `RoundingType`. The rest of the implementation stays the same, which means a lot of code is duplicated.

That duplicated code can be merged into an `AvgPoolBase` class, which then can be used in `MaxPool-1` and `MaxPool-14`.

### What needs to be done?

1. Create `AvgPoolBase` class.
2. Move the common functionality from `AvgPool-1` and `AvgPool-14` into it - it should be pretty much everything, since the only change in `AvgPool-14` is a new value selectable in `ov::op::RoundingType` enum.
3. Use the `AvgPoolBase` class to implement `AvgPool-1` and `AvgPool-14` without unnecessary code dupliaction.
4. Take a look at `MaxPoolBase` - maybe it's possible to simplify both even further? Let us know about any ideas that you have. Some exploration may be required, since there are some slight differences in attributes between `MaxPool` and `AvgPool`.

### Example Pull Requests

There are no example PRs since this task is a refactor, but here are some related PRs:

- https://github.com/openvinotoolkit/openvino/pull/22796
- https://github.com/openvinotoolkit/openvino/pull/22930

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)
- [MaxPool-8 operator docs](https://docs.openvino.ai/2023.3/openvino_docs_ops_pooling_MaxPool_8.html)
- [AvgPool-1 operator docs](https://docs.openvino.ai/2023.3/openvino_docs_ops_pooling_AvgPool_1.html)
- [AvgPool-14 and MaxPool-14 docs](https://github.com/openvinotoolkit/openvino/pull/22930), yet to be merged at the time of writing

### Contact points

@p-wysocki 
@praasz 
@mitruska 

### Ticket

135527

**Comment by Vladislav-Denisov** [comment]
.take
