### ISSUE TITLE
[Good First Issue]: [OP CONFORMANCE][TEMPLATE] MaxPool test failed in op conformance

### ISSUE THREAD

**Issue by iefode** [openvinotoolkit/openvino#23551]
### Context

OP conformance suite is validation tool checks a plugin conditions from operation implementation status perspective.
OP conformance is based on extracted from OMZ model scope operations and graphs by `ov_subgraphs_dumper` tool. Extracted graphs are saved as IR (OpenVINO Intermediate representation) and is stored in the public share.
OP conformance suite contains the following test types:
* `OpImplCheck` validates operation support by plugin. Return `true` or `false`.
* `Inference` compare device inference results vs reference over extracted IR as a model. We generate synthetic tensors to get a result. Possible results are `passed`, `failed`, `hanged` (interrupted by timeout), `crashed` and `skipped` (just in case `-shape_mode` is misaligned with graph inputs).
* `QueryModel` check possibility of graph execution per device. Have the same status as `Inference`
* `ImportExport` exports compiled model, imports it and check that models are same. Have the same status as `Inference`

Template is a simple plugin run inference using reference implementation. It means if we will run conformance over template, we should compare `TEMPLATE` vs `TEMPLATE` results. Sometimes we have bugs inside the plugin, reference implementation or test infrastructure leads to negative test result.

### What needs to be done?

**Description**:
We have several Reshape tests failed in operation conformance over TEMPLATE plugin. Do contributor should fix them:
* `conformance_MaxPool/ReadIRTest.Inference/Op=MaxPool.8_Type=f32_Shape=dynamic_IR=fc530f5b6bbe8f06808eeaba33889867e705fa69591d01da4dd3dee9515f323f_Device=TEMPLATE_Config=()`

**How to reproduce:**
1. Build the OV using -DENABLE_TESTS=ON -DENABLE_FUNCTIONAL_TESTS=ON
2. Build `ov_op_conformance_tests` target
3. Run OP conformance to download conformance IRs and run executable file with args: 
```
python3 /openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/run_conformance.py -d=TEMPLATE --gtest_filter="conformance_MaxPool/ReadIRTest.Inference/Op=MaxPool.8_Type=f32_Shape=dynamic_IR=fc530f5b6bbe8f06808eeaba33889867e705fa69591d01da4dd3dee9515f323f_Device=TEMPLATE_Config=()"
```
>**NOTE**: `run_conformance` log contains all commands to run `ov_op_conformance_tests`! You can take them to debug!
4. Check the logs inside working directory and get the results as an example:
```
[ RUN      ] [ RUN      ] conformance_MaxPool/ReadIRTest.Inference/Op=MaxPool.8_Type=f32_Shape=dynamic_IR=fc530f5b6bbe8f06808eeaba33889867e705fa69591d01da4dd3dee9515f323f_Device=TEMPLATE_Config=()

MEM_USAGE=71872KB
[ CONFORMANCE ] Influence coefficient: 1.16885e-05
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is started
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is finished successfully. Duration is 0.048517s
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is started
/home/efode/repo/openvino/src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp:94: Failure
Exception from src/inference/src/cpp/infer_request.cpp:223:
Check 'cmp::le(kernel, dim.get_length())' failed at src/core/shape_inference/include/pooling_shape_inference_util.hpp:145:
While validating node 'opset8::MaxPool MaxPool-8 (opset1::Parameter MaxPool-8_0[0]:f32[1,64,1,1]) -> (f32[?,64,1..,1..], i64[?,64,1..,1..])' with friendly_name 'MaxPool-8':
Kernel after dilation has size (dim: 2) larger than the data shape after padding (dim: 1) at axis 0.


[  FAILED  ] conformance_MaxPool/ReadIRTest.Inference/Op=MaxPool.8_Type=f32_Shape=dynamic_IR=fc530f5b6bbe8f06808eeaba33889867e705fa69591d01da4dd3dee9515f323f_Device=TEMPLATE_Config=(), where GetParam() = ("/home/efode/repo/openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/temp/models/2023.3.0-13657-d5b0f4d2d73/operation/dynamic/MaxPool-8/f32/fc530f5b6bbe8f06808eeaba33889867e705fa69591d01da4dd3dee9515f323f.xml", "") (219 ms)


```
5. To debug the test in C++ Use the following command (just an example, refer to note in third item):
```
openvino/bin/intel64/Release/ov_op_conformance_tests --device=TEMPLATE --input_folders=openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/temp/models/conformance_ir_files.lst, --report_unique_name --output_folder="openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/temp/report/parallel" --gtest_filter="conformance_MaxPool/ReadIRTest.Inference/Op=MaxPool.8_Type=f32_Shape=dynamic_IR=fc530f5b6bbe8f06808eeaba33889867e705fa69591d01da4dd3dee9515f323f_Device=TEMPLATE_Config=()" --config_path="" --shape_mode=
```

>Important NOTE: The issue can be connected with [input generation for Gather Operation](src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp). We should generate input tensor according OV specification!

### Example Pull Requests

As an example of extending input generation per specific layer: https://github.com/openvinotoolkit/openvino/pull/20897/

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)
- [Conformance readme](https://github.com/openvinotoolkit/openvino/tree/master/src/tests/functional/plugin/conformance/test_runner)
- [TEMPLATE plugin](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/template/README.md)
- [OV CONTRIBUTION GUIDE](https://github.com/openvinotoolkit/openvino/tree/master/?tab=readme-ov-file#how-to-contribute)

### Contact points

@iefode

**Comment by Vladislav-Denisov** [comment]
.take

**Comment by Vladislav-Denisov** [comment]
I was able to reproduce the problem and understand why it was happening.

Next I will try to explain what I did:
1. The error message says: "Kernel after dilation has size (dim: 2) larger than the data shape after padding (dim: 1) at axis 0.".
This gave me the idea to check the dimensions for the problematic `MaxPool-8` operation.
2. Using [Netron.app](https://netron.app/), I opened the `MaxPool-8` structure, taking it from `openvino\src\tests\test_utils\functional_test_utils\layer_tests_summary\temp\models\2023.3.0-13657-d5b0f4d2d73\operation\dynamic\MaxPool-8\f32\fc530f5b6bbe8f06808eeaba33889867e705fa69591d01da4dd3dee9515f323f.xml` and analyzed.
 -- `MaxPool-8` has input dynamic shape and Kernel dimension = 2 (see screenshot).
![max_pool_netron](https://github.com/openvinotoolkit/openvino/assets/43005366/947d15a5-4b70-4bf3-973d-39c965a561de)
3. In the [file](https://github.com/openvinotoolkit/openvino/blob/4760b5b75b4bf4ad6071d352a6cbce9d8ad0d757/src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir.cpp) I noticed that the testing data is prepared for 3 scenarios:
3.1 Shape with minimum values of dynamic dimensions.
3.2 With random values.
3.3 With maximum values.
https://github.com/openvinotoolkit/openvino/blob/4760b5b75b4bf4ad6071d352a6cbce9d8ad0d757/src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir.cpp#L241-L243
4. For cases when the dimension of the input shape < kernel dimension (=2 for MaxPool-8 in this case), the error occurs:
-- In 3.1 - always.
-- In 3.2 - sometimes.
-- In 3.3 - never.

I think that to solve the problem, when generate a test-tensor, it is necessary to limit the permissible input shape by the Kernel-dimension (and, most likely, other constant values for the operation, for example, Strides, Dilations etc).

@iefode Can you advise what I should do next?

**Comment by iefode** [comment]
@Vladislav-Denisov 

Thanks for looking the issue!

According your investigation, the solution could be to implement static shape generation for any specific operation like maxpool based on op attributes. I can advice to implement the same solution as for input_generation or tensor comparation:
https://github.com/openvinotoolkit/openvino/blob/master/src/tests/functional/shared_test_classes/src/base/utils/compare_results.cpp
Using: https://github.com/openvinotoolkit/openvino/blob/644d87a527e3efbd6666e2b264e72e2fb9cab9a2/src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp#L259

Please, let me know, if you will meet any issues!

**Comment by Vladislav-Denisov** [comment]
@iefode
Thank you for your answer! :)
I will try to implement a similar approach for generating shapes.
