### ISSUE TITLE
[Good First Issue]: [OP CONFORMANCE][TEMPLATE] Convolution tests are failed in opset conformance

### ISSUE THREAD

**Issue by iefode** [openvinotoolkit/openvino#23554]
### Context

OP conformance suite is validation tool checks a plugin conditions from operation implementation status perspective.
OP conformance is based on extracted from OMZ model scope operations and graphs by `ov_subgraphs_dumper` tool. Extracted graphs are saved as IR (OpenVINO Intermediate representation) and is stored in the public share.
OP conformance suite contains the following test types:
* `OpImplCheck` validates operation support by plugin. Return `true` or `false`.
* `Inference` compare device inference results vs reference over extracted IR as a model. We generate synthetic tensors to get a result. Possible results are `passed`, `failed`, `hanged` (interrupted by timeout), `crashed` and `skipped` (just in case `-shape_mode` is misaligned with graph inputs).
* `QueryModel` check possibility of graph execution per device. Have the same status as `Inference`
* `ImportExport` exports compiled model, imports it and check that models are same. Have the same status as `Inference`

Template is a simple plugin run inference using reference implementation. It means if we will run conformance over template, we should compare `TEMPLATE` vs `TEMPLATE` results. Sometimes we have bugs inside the plugin, reference implementation or test infrastructure leads to negative test result.

### What needs to be done?

**Description**:
We have several Reshape tests failed in operation conformance over TEMPLATE plugin. Do contributor should fix them:
* `conformance_Convolution/ReadIRTest.Inference/Op=Convolution.1_Type=f32_Shape=dynamic_IR=1e56a3e2379d29d81af93174e56ef91408af41dfc085d4851ff58dbec781b8fa_Device=TEMPLATE_Config=()`
* `conformance_Convolution/ReadIRTest.Inference/Op=Convolution.1_Type=f32_Shape=dynamic_IR=dd9fee8f7cd289b97050e22cb465637c6439230d0d3ebcb20452eb544b40617e_Device=TEMPLATE_Config=()`
* `conformance_Convolution/ReadIRTest.Inference/Op=Convolution.1_Type=f32_Shape=dynamic_IR=789949951bc3afd20fdff943ca2a706f79eb4f95be60086ddf632b43c3e401e6_Device=TEMPLATE_Config=()`

**How to reproduce:**
1. Build the OV using -DENABLE_TESTS=ON -DENABLE_FUNCTIONAL_TESTS=ON
2. Build `ov_op_conformance_tests` target
3. Run OP conformance to download conformance IRs and run executable file with args: 
```
python3 /openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/run_conformance.py -d=TEMPLATE --gtest_filter="conformance_Convolution/ReadIRTest.Inference/Op=Convolution.1_Type=f32_Shape=dynamic_IR=789949951bc3afd20fdff943ca2a706f79eb4f95be60086ddf632b43c3e401e6_Device=TEMPLATE_Config=()"
```
>**NOTE**: `run_conformance` log contains all commands to run `ov_op_conformance_tests`! You can take them to debug!
4. Check the logs inside working directory and get the results as an example:
```
[ RUN      ] conformance_Convolution/ReadIRTest.Inference/Op=Convolution.1_Type=f32_Shape=dynamic_IR=789949951bc3afd20fdff943ca2a706f79eb4f95be60086ddf632b43c3e401e6_Device=TEMPLATE_Config=()

MEM_USAGE=71864KB
[ CONFORMANCE ] Influence coefficient: 8.2448e-05
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is started
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is finished successfully. Duration is 0.257973s
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is started
/home/efode/repo/openvino/src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp:94: Failure
Exception from src/inference/src/cpp/infer_request.cpp:223:
Check 'cmp::le(kernel, dim.get_length())' failed at src/core/shape_inference/include/pooling_shape_inference_util.hpp:145:
While validating node 'opset1::Convolution Convolution-1 (opset1::Parameter Convolution-1_0[0]:f32[1,512,1], opset1::Constant Convolution-1_1[0]:f32[512,512,2]) -> (f32[?,512,1..])' with friendly_name 'Convolution-1':
Kernel after dilation has size (dim: 2) larger than the data shape after padding (dim: 1) at axis 0.


[  FAILED  ] conformance_Convolution/ReadIRTest.Inference/Op=Convolution.1_Type=f32_Shape=dynamic_IR=789949951bc3afd20fdff943ca2a706f79eb4f95be60086ddf632b43c3e401e6_Device=TEMPLATE_Config=(), where GetParam() = ("/home/efode/repo/openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/temp/models/2023.3.0-13657-d5b0f4d2d73/operation/dynamic/Convolution-1/f32/789949951bc3afd20fdff943ca2a706f79eb4f95be60086ddf632b43c3e401e6.xml", "") (687 ms)


```
5. To debug the test in C++ Use the following command (just an example, refer to note in third item):
```
openvino/bin/intel64/Release/ov_op_conformance_tests --device=TEMPLATE --input_folders=openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/temp/models/conformance_ir_files.lst, --report_unique_name --output_folder="openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/temp/report/parallel" --gtest_filter="conformance_Convolution/ReadIRTest.Inference/Op=Convolution.1_Type=f32_Shape=dynamic_IR=789949951bc3afd20fdff943ca2a706f79eb4f95be60086ddf632b43c3e401e6_Device=TEMPLATE_Config=()" --config_path="" --shape_mode=
```

>Important NOTE: The issue can be connected with [input generation for Gather Operation](src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp). We should generate input tensor according OV specification!

### Example Pull Requests

As an example of extending input generation per specific layer: https://github.com/openvinotoolkit/openvino/pull/20897/

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)
- [Conformance readme](https://github.com/openvinotoolkit/openvino/tree/master/src/tests/functional/plugin/conformance/test_runner)
- [TEMPLATE plugin](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/template/README.md)
- [OV CONTRIBUTION GUIDE](https://github.com/openvinotoolkit/openvino/tree/master/?tab=readme-ov-file#how-to-contribute)

### Contact points

@iefode

**Comment by awayzjj** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @awayzjj, are you still working on this?

**Comment by awayzjj** [comment]
@iefode @p-wysocki  Hello, I've reproduced the negative test results and would appreciate some guidance. 
Specifically, I have two questions, take scenarios where `dynamic_IR=1e56a3e....` for example:

1. Regarding the test suite, it evaluates three different shapes (min_shape, random shape, and max shape) for input to ensure conformance as the code snippet illustrates:
https://github.com/openvinotoolkit/openvino/blob/421f8a013599421fc3808291896988ac423e4c4e/src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir.cpp#L241-L271
I printed `inputShapes[0]` and received `[?.512.1..]_([1,512,1].[15,512,35].[127,512,127])`. Notably, the min shape `[1,512,1]` has a final axis dimension of 1, which is smaller than the last axis dimension of the kernel `[512,512,2]`. This discrepancy violates the requirements of the convolution operation, leading to test failure , just as the error message of the test result shows:
```
While validating node 'opset1::Convolution Convolution-1 (opset1::Parameter Convolution-1_0[0]:f32[1,512,1], opset1::Constant Convolution-1_1[0]:f32[512,512,2]) -> (f32[?,512,1..])' with friendly_name 'Convolution-1':
Kernel after dilation has size (dim: 2) larger than the data shape after padding (dim: 1) at axis 0.
```
Modifying the minimum shape's last dimension(Changing `data shape="?,512,1.."` to `data shape="?,512,2"` resulted in the input shapes becoming `[1,512,2].[15,512,2].[127,512,2].`) in the following downloaded IR to match the kernel's last dimension (2) resulted in successful testing:
```
		<layer id="0" name="Convolution-1_0" type="Parameter" version="opset1">
			<data shape="?,512,1.." element_type="f32" />
			<output>
				<port id="0" precision="FP32">
					<dim>-1</dim>
					<dim>512</dim>
					<dim>-1</dim>
				</port>
			</output>
		</layer>
```
Thus, I'm considering whether constraining the input shape of the exported model IR to be smaller than the kernel could mitigate this issue effectively.

2. The aforementioned modification ensures that the last dimension of the input is greater than that of the convolution kernel, but the first dimension may still not comply. For instance, `[1,512,2]` vs. `[512,512,2]`. When there is no padding applied to the input, I expected negative test results actually. The configuration of the operation in IR is as follows:
```
		<layer id="2" name="Convolution-1" type="Convolution" version="opset1">
			<data strides="2" dilations="1" pads_begin="0" pads_end="0" auto_pad="explicit" />
```

**Comment by iefode** [comment]
Hello @awayzjj,

Thanks for investigation! Looks reasonable.

Let Me share some technical details related to conformance IR with dynamic shapes. In this case we can infer the subgraph with different static shapes from possible shape range. To check dynamism feature we generate 3 different static shapes to infer the subgraph.

But some operation types like provided example need to generate static shapes based on some op attributes or any input shape. The best solution is to use the same mechanism as for input tensor generation/output tensor comparation.

The other source contributor @Vladislav-Denisov  met the same issue for other [`good first issue`](https://github.com/openvinotoolkit/openvino/issues/23551). Please check the comments under the mentioned issue.

@awayzjj Could you please collaborate with @Vladislav-Denisov to provide the solution to solve both issues for `Convolution` and `MaxPool` operations? Please let me know in case of some questions/issues?

**Comment by awayzjj** [comment]
@iefode I've submit a PR and I'll appreciate it if you'd like to review it. :)
