### ISSUE TITLE
[Good First Issue]: [OP CONFORMANCE][TEMPLATE] Fix GatherND test in opset conformance

### ISSUE THREAD

**Issue by iefode** [openvinotoolkit/openvino#23555]
### Context

OP conformance suite is validation tool checks a plugin conditions from operation implementation status perspective.
OP conformance is based on extracted from OMZ model scope operations and graphs by `ov_subgraphs_dumper` tool. Extracted graphs are saved as IR (OpenVINO Intermediate representation) and is stored in the public share.
OP conformance suite contains the following test types:
* `OpImplCheck` validates operation support by plugin. Return `true` or `false`.
* `Inference` compare device inference results vs reference over extracted IR as a model. We generate synthetic tensors to get a result. Possible results are `passed`, `failed`, `hanged` (interrupted by timeout), `crashed` and `skipped` (just in case `-shape_mode` is misaligned with graph inputs).
* `QueryModel` check possibility of graph execution per device. Have the same status as `Inference`
* `ImportExport` exports compiled model, imports it and check that models are same. Have the same status as `Inference`

Template is a simple plugin run inference using reference implementation. It means if we will run conformance over template, we should compare `TEMPLATE` vs `TEMPLATE` results. Sometimes we have bugs inside the plugin, reference implementation or test infrastructure leads to negative test result.

### What needs to be done?

**Description**:
We have several GatherND tests failed in operation conformance over TEMPLATE plugin. Do contributor should fix them:
* `conformance_GatherND/ReadIRTest.Inference/Op=GatherND.8_Type=i64_Shape=dynamic_IR=c1cd785825e1b2794d4bc74f6dc257e92a382e95a868a864125da70acc5cdbf4_Device=TEMPLATE_Config=()`

**How to reproduce:**
1. Build the OV using -DENABLE_TESTS=ON -DENABLE_FUNCTIONAL_TESTS=ON
2. Build `ov_op_conformance_tests` target
3. Run OP conformance to download conformance IRs and run executable file with args: 
```
python3 /openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/run_conformance.py -d=TEMPLATE --gtest_filter="conformance_GatherND/ReadIRTest.Inference/Op=GatherND.8_Type=i64_Shape=dynamic_IR=c1cd785825e1b2794d4bc74f6dc257e92a382e95a868a864125da70acc5cdbf4_Device=TEMPLATE_Config=()"
```
>**NOTE**: `run_conformance` log contains all commands to run `ov_op_conformance_tests`! You can take them to debug!
4. Check the logs inside working directory and get the results as an example:
```
[ RUN      ] conformance_GatherND/ReadIRTest.Inference/Op=GatherND.8_Type=i64_Shape=dynamic_IR=c1cd785825e1b2794d4bc74f6dc257e92a382e95a868a864125da70acc5cdbf4_Device=TEMPLATE_Config=()

MEM_USAGE=71868KB
[ CONFORMANCE ] Influence coefficient: 9.17486e-06
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is started
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is finished successfully. Duration is 0.0240023s
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is started
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is finished successfully. Duration is 0.00160112s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] Calculate reference in runtime
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.00136988s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.00139864s
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is started
[ COMPARATION ] rel_threshold: 1.79769e+308
[ COMPARATION ] abs_threshold: 1
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is finished successfully. Duration is 0.00095375s
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is started
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is finished successfully. Duration is 0.000508201s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] Calculate reference in runtime
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.00103948s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.00110662s
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is started
[ COMPARATION ] rel_threshold: 1.79769e+308
[ COMPARATION ] abs_threshold: 1
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is finished successfully. Duration is 0.000686005s
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is started
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is finished successfully. Duration is 0.000555563s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] Calculate reference in runtime
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.000962828s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.0014357s
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is started
[ COMPARATION ] rel_threshold: 1.79769e+308
[ COMPARATION ] abs_threshold: 1
/home/efode/repo/openvino/src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp:94: Failure
abs_max < abs_threshold && rel_max < rel_threshold
	 abs_max: 9.4653e+13
		 coordinate 21; abs errors count 10; abs mean 6.45361e+12; abs threshold 1
	 rel_max: 736
		 coordinate 45; rel errors count 0; rel mean 33.5227; rel threshold 1.79769e+308
[  FAILED  ] conformance_GatherND/ReadIRTest.Inference/Op=GatherND.8_Type=i64_Shape=dynamic_IR=c1cd785825e1b2794d4bc74f6dc257e92a382e95a868a864125da70acc5cdbf4_Device=TEMPLATE_Config=(), where GetParam() = ("/home/efode/repo/openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/temp/models/2023.3.0-13657-d5b0f4d2d73/operation/dynamic/GatherND-8/i64/c1cd785825e1b2794d4bc74f6dc257e92a382e95a868a864125da70acc5cdbf4.xml", "") (115 ms)


```
5. To debug the test in C++ Use the following command (just an example, refer to note in third item):
```
openvino/bin/intel64/Release/ov_op_conformance_tests --device=TEMPLATE --input_folders=openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/temp/models/conformance_ir_files.lst, --report_unique_name --output_folder="conformance_GatherND/ReadIRTest.Inference/Op=GatherND.8_Type=i64_Shape=dynamic_IR=c1cd785825e1b2794d4bc74f6dc257e92a382e95a868a864125da70acc5cdbf4_Device=TEMPLATE_Config=()" --config_path="" --shape_mode=
```

>Important NOTE: The issue can be connected with [input generation for Gather Operation](src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp). We should generate input tensor according OV specification!

### Example Pull Requests

As an example of extending input generation per specific layer: https://github.com/openvinotoolkit/openvino/pull/20897/

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)
- [Conformance readme](https://github.com/openvinotoolkit/openvino/tree/master/src/tests/functional/plugin/conformance/test_runner)
- [TEMPLATE plugin](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/template/README.md)
- [OV CONTRIBUTION GUIDE](https://github.com/openvinotoolkit/openvino/tree/master/?tab=readme-ov-file#how-to-contribute)

### Contact points

@iefode

**Comment by HikaruSadashi** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @HikaruSadashi, are you still working on this?

**Comment by HikaruSadashi** [comment]
Hi @p-wysocki , I still am. I am having trouble recreating the failed tests. I built and then installed dependencies for the Conformance Test Runner including `make --jobs=$(nproc --all) ov_op_conformance_tests`  to "Build `ov_op_conformance_tests target`" as this issue mentions. I also built the OpenVino runtime with no errors. 

 I am in the `/openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary` directory and I run the following command `python3 run_conformance.py -d=TEMPLATE --gtest_filter="conformance_GatherND/ReadIRTest.Inference/Op=GatherND.8_Type=i64_Shape=dynamic_IR=c1cd785825e1b2794d4bc74f6dc257e92a382e95a868a864125da70acc5cdbf4_Device=TEMPLATE_Config=()"`. The tests run and when I do check `openvino/src/tests/test_utils/functional_test_utils/layer_tests_summary/temp/TEMPLATE_logs/logs` all test result directories are empty except the `passed` directory which includes the following log file:

```
[ RUN      ] conformance_GatherND/ReadIRTest.Inference/Op=GatherND.8_Type=i64_Shape=dynamic_IR=c1cd785825e1b2794d4bc74f6dc257e92a382e95a868a864125da70acc5cdbf4_Device=TEMPLATE_Config=()

MEM_USAGE=43380KB
[ CONFORMANCE ] Influence coefficient: 9.17486e-06
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is started
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is finished successfully. Duration is 0.00644703s
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is started
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] Calculate reference in runtime
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is finished successfully. Duration is 0.000786279s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.00096037s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.00112781s
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is started
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is finished successfully. Duration is 0.000879316s
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is started
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] Calculate reference in runtime
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is finished successfully. Duration is 0.000320471s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.000719872s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.00078164s
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is started
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is finished successfully. Duration is 0.000819983s
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is started
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] Calculate reference in runtime
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is finished successfully. Duration is 0.000379303s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.000957545s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is finished successfully. Duration is 0.00104456s
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is started
[ COMPARATION ] `ov_tensor_utils.hpp::compare()` is finished successfully. Duration is 0.000841434s
[       OK ] conformance_GatherND/ReadIRTest.Inference/Op=GatherND.8_Type=i64_Shape=dynamic_IR=c1cd785825e1b2794d4bc74f6dc257e92a382e95a868a864125da70acc5cdbf4_Device=TEMPLATE_Config=() (40 ms)
```

**Comment by sbalandi** [comment]
Hello, thanks for your interest to the issue ! I have checked and found that the test is passing now. The issue will closed.

**Comment by HikaruSadashi** [comment]
That explain why the test was passing, someone fixed it I see, thanks!
