### ISSUE TITLE
[Good First Issue]: Expose Model.get_output_shape() method to Node.js API

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#23568]
### Context

Node.js API is the newest binding of OpenVINO.
The task is to expose Model.get_output_shape() method.
[C++ API](https://docs.openvino.ai/2022.3/classov_1_1Model.html#doxid-classov-1-1-model-1aaf18684d50c61029dcfdf7f5e1ab7702) and [Python API](https://docs.openvino.ai/2022.3/api/ie_python_api/_autosummary/openvino.runtime.Model.html#openvino.runtime.Model.get_output_shape) documentation of this method

### What needs to be done?

 - add `get_output_shape()` method on C++ side (src/bindings/js/node/src/model.cpp)
 - update TypeScript definition (src/bindings/js/node/lib/addon.ts)
 - create unit test for added functionality using Node.js Test Runner

 Note: Remember about parameter validation

### Example Pull Requests

Here is the link to a PR with a very similar task that covers the steps listed above:
- https://github.com/openvinotoolkit/openvino/pull/22100

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai

**Comment by almilosz** [comment]
@Ragini252000 you can take this task as the [Prerequisite task](https://github.com/openvinotoolkit/openvino/wiki/Google-Summer-Of-Code#prerequisite-task) or select one of the tasks listed under "good first issues" on [this page](https://github.com/orgs/openvinotoolkit/projects/3).

**Comment by AjaySDwivedi1** [comment]
Can I work on this issue?

**Comment by Ragini252000** [comment]
Yes , we can talk on this . On the  discord account. Thank you.

**Comment by RitikaxShakya** [comment]
Hello! I would like to work on this issue.

**Comment by mlukasze** [comment]
This is prerequisite task, as part of evaluation for GSoC, and we are dedicating this one for @Ragini252000
But give us a moment, there will be more ;)

**Comment by RitikaxShakya** [comment]
Okay I will also participate on GSoC, so would like to work on such issue. Thank you!

**Comment by vishniakov-nikolai** [comment]
Hi @Ragini252000! How is your progress of working on this task?
If you have any questions, please, do not hesitate to ask us.

**Comment by hegdeadithyak** [comment]
Hi there, @vishniakov-nikolai 

I'm interested in working on this issue. I've reviewed the description and it seems like a good fit for my skills.  Before I dive in, I wanted to check if there's anything specific I should keep in mind while working on it, or if someone else has already claimed it.

**_

> Please let me know if this is still unassigned and if you'd be happy for me to take it on.

_**

Thanks,
**Adithya Hegde Kota**

**Comment by vishniakov-nikolai** [comment]
@Ragini252000, I have to reassign this issue, because you didn't reply.

Hi @hegdeadithyak! I assigned you to this issue. Thanks!

**Comment by hegdeadithyak** [comment]
To clarify, if implementing the `get_shape` function from `node_output.cpp` into `model_wrap.cpp` as `get_output_shape` function is it  the **correct** approach?

Thanks,
**Adithya Hegde Kota**

**Comment by vishniakov-nikolai** [comment]
> @vishniakov-nikolai To clarify, if implementing the `get_shape` function from `node_output.cpp` into `model_wrap.cpp` as `get_output_shape` function is it the **correct** approach?
> 
> Thanks, **Adithya Hegde Kota**

No, it's incorrect approach.
Please pay attention that they even have different signatures:
- [ov::Model.get_output_shape](https://docs.openvino.ai/2024/api/c_cpp_api/classov_1_1_model.html#_CPPv4NK2ov5Model16get_output_shapeE6size_t)
- [ov::Output.get_shape](https://docs.openvino.ai/2024/api/c_cpp_api/classov_1_1_node.html#_CPPv4NK2ov4Node9get_shapeEv)

You can start PR from extending [addon.ts](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/src/addon.cpp) and moving step by step. Having PR it would be easier to look at your ideas.
