### ISSUE TITLE
[Good First Issue]: Expose Model.is_dynamic() method to Node.js API

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#23565]
### Context

Node.js API is the newest binding of OpenVINO.
The task is to expose Model.is_dynamic() method.
[C++ API](https://docs.openvino.ai/2022.3/classov_1_1Model.html#doxid-classov-1-1-model-1ace78bc92f1046ac2ba8207029b1206fc) and [Python API](https://docs.openvino.ai/2022.3/api/ie_python_api/_autosummary/openvino.runtime.Model.html#openvino.runtime.Model.is_dynamic) documentation of this method

### What needs to be done?

 - add `is_dynamic()` method on C++ side (src/bindings/js/node/src/model.cpp)
 - update TypeScript definition (src/bindings/js/node/lib/addon.ts)
 - create unit test for added functionality using Node.js Test Runner
 
 Note: Remember about parameter validation

### Example Pull Requests

Here is the link to a PR with a very similar task that covers the steps listed above:
- https://github.com/openvinotoolkit/openvino/pull/22100

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai

**Comment by qxprakash** [comment]
hello @almilosz I am interested in contributing to the JS API , I am taking this one as well if you don't mind ?

**Comment by qxprakash** [comment]
.take

**Comment by almilosz** [comment]
Hi Prakash,
I'm glad that you are so enthusiastic to contribute to OpenVINO Node.js API!
I reviewed [PR](https://github.com/openvinotoolkit/openvino/pull/23498) for this GFI. Please take a look ;)

**Comment by qxprakash** [comment]
> Hi Prakash, I'm glad that you are so enthusiastic to contribute to OpenVINO Node.js API! I reviewed [PR](https://github.com/openvinotoolkit/openvino/pull/23498) for this GFI. Please take a look ;)

Thanks for the feedback @almilosz , I have made the requested changes.

**Comment by qxprakash** [comment]
@almilosz the tests for Model Interface should be present in `openvino/src/bindings/js/node/tests/basic.test.js`  right ? , I see tests for CompiledModel , Output class , Input class , but there are no tests for Model interface present ? , am I looking at the wrong location here ?

**Comment by almilosz** [comment]
You should create a new file called `model.test.js` and put there tests for `Model.is_dynamic()`  (Node,js isDynamic())

**Comment by qxprakash** [comment]
ok @almilosz , got it.
