### ISSUE TITLE
[Good First Issue]: Expose Model get/set _friendly_name() method to Node.js API

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#23566]
### Context

Node.js API is the newest binding of OpenVINO.
The task is to expose 2 methods: 
 - Model[.set_friendly_name()](https://docs.openvino.ai/2022.3/api/ie_python_api/_autosummary/openvino.runtime.Model.html#openvino.runtime.Model.set_friendly_name)
 - Model.[get_friendly_name()](https://docs.openvino.ai/2022.3/api/ie_python_api/_autosummary/openvino.runtime.Model.html#openvino.runtime.Model.get_friendly_name)
 
 You can take a look at C++ or Python API documentation.

### What needs to be done?

 - add methods on C++ side (src/bindings/js/node/src/model.cpp)
 - update TypeScript definition (src/bindings/js/node/lib/addon.ts)
 - create unit test for added functionality using Node.js Test Runner
 
 Note: Remember about parameter validation

### Example Pull Requests

Here is the link to a PR with a very similar task that covers the steps listed above:
- https://github.com/openvinotoolkit/openvino/pull/22100

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai

**Comment by qxprakash** [comment]
.take
