### ISSUE TITLE
when i use NCS2, ncDeviceOpen:672	Failed to find suitable device, rc: X_LINK_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by user-redans** [openvinotoolkit/openvino#236]
Hi,
I recently bought Neural Compute Stick 2, Powered by Intel movidius myriad x vpu, NCS 2. I follwed those steps : https://software.intel.com/en-us/articles/get-started-with-neural-compute-stick and when I tried to test my install. (step 4), I recevied next error: 
[ INFO ] Loading model to the plugin
E: [ncAPI] [    231949] ncDeviceOpen:672	Failed to find suitable device, rc: X_LINK_DEVICE_NOT_FOUND
[ ERROR ] Can not init USB device: NC_ERROR
Error on or near line 241; exiting with status 1

I used this distribution of Ubuntu, in VMware Worksation, it is a VM guest, in a Win10 host.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	        16.04
Codename:	xenial

OpenVINO toolkit works great, no error. I've tried this tutorial https://github.com/incluit/OpenVino-For-SmartCity and all examples works on CPU and now I want to execute them with MYRIAD . Do you have any suggestions?

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
