### ISSUE TITLE
Yet another Import Error [Bug]

### ISSUE THREAD

**Issue by Westerby** [openvinotoolkit/openvino#2369]
##### System information (version)

- OpenVINO: 2020.4
- Operating System / Platform: Windows 10 64 Bit
- Compiler: Visual Studio 2019
- Problem classification: Python module import error
- Python: 3.7.1
- Cython: 0.29.17

##### Detailed description
Can't import newly built openvino Python wrapper. I get: ImportError: DLL load failed

##### Steps to reproduce

1. Build (tried various combinations, with/withount Ngraph, separate build for Python as in instructions [here](https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/ie_bridges/python)): 

`git submodule update --init --recursive`

`cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE="...\python-3.7.1.amd64\python.exe" -DPYTHON_LIBRARY="...\python-3.7.1.amd64\libs\python37.lib" -DPYTHON_INCLUDE_DIR="...\python-3.7.1.amd64\include" ..`

`cmake --build . --config Release`

2. Usage

Tried different ways of setting paths:

In CMD:

`set PATH =.../openvino/bin/intel64/Release/python_api/python3.7;%PATH%`

In Python:
```
import sys
sys.path.append('.../openvino/bin/intel64/Release/python_api/python3.7')
sys.path.append('.../openvino/bin/intel64/Release')
```

Tried adding other paths (as desctribed in [build instructions](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#build-on-windows-systems)):

```
sys.path.append('.../openvino/inference-engine/temp/tbb/bin')
sys.path.append('.../openvino/openvino/inference-engine/temp/opencv_4.5.0/opencv/bin')
sys.path.append('.../openvino/inference-engine')
```

Tried setting variables with `setupvars.bat`, but it doesn't work either. Plus I think it adds some paths that are not valid, like `openvino\scripts\deployment_tools\inference_engine\external\hddl` or` openvino\scripts\opencv\x64\vc14\bin`  Is the script outdated?

Path for openvino Python wrapper seems to be OK, because I can import it. 
However `from openvino.inference_engine import IECore` returns `ImportError: DLL load failed!
`

I also tried openvino on Linux, and it works fine.

**Comment by jgespino** [comment]
Hi @Westerby,

The `setupvars.bat` is only to be used with the Intel® Distribution of OpenVINO™ toolkit. You will need to manually setup the variables if you are building from source. On Linux, you have to set `PYTHONPATH` and `LD_LIBRARY_PATH`. Should be something similar on Windows but I have not tried this yet. I am currently building OpenVINO on Windows to give it a try and let you know.

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @Westerby
 
Quick update, I was able to build OpenVINO from source on Windows and also ran into the DLL load failed error.
`ImportError: DLL load failed: The specified module could not be found.`

Let me check with my peers and get back to you.

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @Westerby 

I apologize for the delay, please try to set `PYTHONPATH` and `PATH `as shown below. Your locations may be a little different depending on the built directory location. 

```
set PYTHONPATH=C:\..\openvino\bin\intel64\Release\python_api\python3.7 and
set PATH=C:\..\openvino\bin\intel64\Release;C:\..\openvino\inference-engine\temp\tbb\bin;%PATH%
```

Let me know if this works for you.

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open or start a new issue if additional assistance is needed.
