### ISSUE TITLE
[Build]: Getting the undefined reference to `napi_get_undefined' error when I am trying to make the project.

### ISSUE THREAD

**Issue by ShathirHussain** [openvinotoolkit/openvino#23744]
Download and Extract ndk :
wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip

unzip android-ndk-r20-linux-x86_64.zip

mv android-ndk-r20 android-ndk

Clone and build openvino :

git clone https://github.com/openvinotoolkit/openvino.git
git clone https://github.com/openvinotoolkit/openvino_contrib.git

cd openvino
git submodule update --init --recursive
mkdir build && cd build

cmake command : cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=SEQ -DIE_EXTRA_MODULES=../../openvino_contrib/modules -DBUILD_java_api=ON -DCMAKE_TOOLCHAIN_FILE=~/Downloads/android-ndk/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=24 -DANDROID_STL=c++_shared -DENABLE_SAMPLES=OFF -DENABLE_OPENCV=OFF -DENABLE_CLDNN=OFF -DENABLE_TESTS=OFF -DENABLE_GAPI_TESTS=OFF -DENABLE_BEH_TESTS=OFF -DENABLE_PYTHON=OFF ..

make command : make --jobs=$(nproc --all)

Error Log : 

[ 54%] Building CXX object src/frontends/paddle/src/CMakeFiles/openvino_paddle_frontend.dir/op/p_norm.cpp.o
CMakeFiles/ov_node_addon.dir/src/infer_request.cpp.o: In function `Napi::Env::Undefined() const':
/home/sr/Downloads/openvino/build/_deps/node-addon-api-src/napi-inl.h:463: undefined reference to `napi_get_undefined'
CMakeFiles/ov_node_addon.dir/src/infer_request.cpp.o: In function `ObjectWrap':
/home/sr/Downloads/openvino/build/_deps/node-addon-api-src/napi-inl.h:4430: undefined reference to `napi_wrap'
CMakeFiles/ov_node_addon.dir/src/infer_request.cpp.o: In function `Napi::Reference<Napi::Object>::Reset()':
/home/sr/Downloads/openvino/build/_deps/node-addon-api-src/napi-inl.h:3295: undefined reference to `napi_delete_reference'

**Comment by ilya-lavrenov** [comment]
Was fixed by https://github.com/openvinotoolkit/openvino/pull/23679
