### ISSUE TITLE
How to apply LoRA adapter to a model loaded with OVModelForCausalLM()?

### ISSUE THREAD

**Issue by nai-kon** [openvinotoolkit/openvino#23759]
### Request Description

In the transformers library, we can load multiple adapters to the original model by load_adapter then switch the specified adapter with set_adapter like below.

```
# base model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
)

# load multiple adapters
model.load_adapter("model/adapter1/", "adapter1")
model.load_adapter("model/adapter2/", "adapter2")

# switch adapter
model.set_adapter("adapter2")
```
Now I want to apply LoRA adapters with OpenVINO, but I can't find an example of it.
Is it possible to do it with OVModelForCausalLM?

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by Aryan8912** [comment]
can I also work on this issue @eaidova

**Comment by ilya-lavrenov** [comment]
Now, you can apply LoRA to LLMPipeline
https://github.com/openvinotoolkit/openvino.genai/blob/653b2aeb92885eb44f664ad221418ac72eb0d9ab/samples/python/text_generation/lora.py#L16-L26
