### ISSUE TITLE
build error: gna_helper.cpp error: ‘int ftime(timeb*)’ is deprecated 

### ISSUE THREAD

**Issue by justalittlenoob** [openvinotoolkit/openvino#2392]
I am trying to use openvino in graphene.   
Accroding to this [doc](https://github.com/oscarlab/graphene/tree/master/Examples/openvino), I got the following issue when building openvino. Did I miss something?  
Any advice would be appreciated.  

os: ubuntu 20.04
`libopencv-dev` and `python3-opencv` are installed.

`python3 -c "import cv2; print(cv2.__version__)"`
>4.2.0

`make SGX=1`
>2020-09-23 07:01:34 (22.6 MB/s) - ‘/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/temp/download/iomp.tgz’ saved [685885/685885]
-- extracting...
         src='/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/temp/download/iomp.tgz'
         dst='/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/temp/omp'
-- extracting... [tar xfz]
CMake Error at inference-engine/cmake/dependencies.cmake:240 (message):
  **OpenCV is not available on current platform**
Call Stack (most recent call first):
  inference-engine/CMakeLists.txt:18 (include)
-- Configuring incomplete, errors occurred!
See also "/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build/CMakeFiles/CMakeOutput.log".
See also "/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:62: openvino/inference-engine/bin/intel64/Release/object_detection_sample_ssd] Error 1

**Comment by jgespino** [comment]
Hi @justalittlenoob 

According to the guide you are following, Ubuntu 18.04 is a pre-requisite. However, you seem to be using Ubuntu 20.04. The guide you are following is not from Intel. I recommend opening an issue on that particular GitHub repository.

Regards,
Jesus

**Comment by alalek** [comment]
Using custom OpenCV builds (special case to work with "other" configurations):
- https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#use-custom-opencv-builds-for-inference-engine

if used, then `OpenCV_DIR` should point to directory with `OpenCVConfig.cmake` file.

**Comment by justalittlenoob** [comment]
@alalek   
Thank you for your reply. I took your advice([Use Custom OpenCV Builds for Inference Engine](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#use-custom-opencv-builds-for-inference-engine))and the opencv problem seems gone.    
But in the building process, I encountered other problems.
1. error: `redundant move in return statement`
I fix this according to this [PR](https://github.com/openvinotoolkit/openvino/pull/1431/commits/4aed60a0629bb9ec727b88b0770d124ac01853f5)  

2. error: `openvino/inference-engine/src/gna_plugin/gna_helper.cpp:59:20: error: ‘int ftime(timeb*)’ is deprecated [-Werror=deprecated-declarations]`  
I haven't found a way to fix this problem. Maybe you can give me some guidance.

**Comment by alalek** [comment]
Try `cmake -DTREAT_WARNING_AS_ERROR='OFF' ...`

**Comment by justalittlenoob** [comment]
@alalek  Thank you very much for your patience. You helped me a lot:)
