### ISSUE TITLE
[Good First Issue][PyOV]: Extend name appending functionality in all opsets 

### ISSUE THREAD

**Issue by jiwaszki** [openvinotoolkit/openvino#24030]
### Context

PR https://github.com/openvinotoolkit/openvino/pull/23712 introduces automatic appending of the operator's name to all autogenerated Constant nodes created via Python API. This functionality needs to be exposed in all affected operators.

### What needs to be done?

Starting from opset1 to current opset, extend all implementations to pass down `name` argument in `as_node`/`as_nodes` calls.

### Example Pull Requests

Example changes applied to `fake_quantize` https://github.com/openvinotoolkit/openvino/pull/23712

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@mitruska 
@akuporos
@jiwaszki  

### Ticket

Continuation of CVS-133139

**Comment by LucaTamSapienza** [comment]
.take

**Comment by LucaTamSapienza** [comment]
PR #24135
