### ISSUE TITLE
Questions about PaddlePaddle Hackathon No.45 task

### ISSUE THREAD

**Issue by Patrick-Star125** [openvinotoolkit/openvino#24046]
reference：
1.[Task Description](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/%E3%80%90Hackathon%206th%E3%80%91%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E4%B8%AA%E4%BA%BA%E6%8C%91%E6%88%98%E8%B5%9B%E5%90%88%E4%BD%9C%E4%BC%99%E4%BC%B4%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#no45%E4%B8%BA-openvino-%E5%AE%9E%E7%8E%B0-paddle-%E7%AE%97%E5%AD%90-scaled_dot_product_attention-%E8%BD%AC%E6%8D%A2)
2.[scaled_dot_product_attention documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/scaled_dot_product_attention_en.html#scaled-dot-product-attention)

Task: No45. Implement the Paddle operator scaled_dot_product_attention for OpenVINO

1.The Paddle API documentation indicates support only for float16 and bfloat16. Currently, it seems that Paddle only supports float16 and bfloat16 in GPU mode, while OpenVINO, to my knowledge, is a CPU inference platform. Testing under float16 seems to fail in this scenario. How should testing be conducted in this case?

![image](https://github.com/openvinotoolkit/openvino/assets/69072522/3b5876cb-a72b-4ed5-b951-677e240ea7b3)

2.This API was added after Paddle 2.6, and it seems that OpenVINO's support for Paddle 2.6 will take some time. This means that this task is currently stuck.

**Comment by Patrick-Star125** [comment]
I personally suggest switching to a different API for mapping, such as No.43 tril/triu and No.44 rsqrt.

Because, setting aside the previous points, looking at the task itself, OpenVINO has the ScaledDotProductAttention API, which is almost identical in functionality and parameters to scaled_dot_product_attention.

So, this task might only require reading parameters and calling an API. Considering the overall difficulty of this activity, this task might not reach a difficulty level of two stars.

**Comment by yuxu42** [comment]
@Patrick-Star125  Thank you very much for the issue analysis! As Paddle SDPA cannot support Intel CPU. It means this SDPA mapping task is not valid. Closing the ticket.
