### ISSUE TITLE
How to support ONNX if op?

### ISSUE THREAD

**Issue by xiaoweiChen** [openvinotoolkit/openvino#2406]
I use the 2020.4 OpenVINO source code to process my onnx model.

This is a Faster-RCNN model exported by pytorch official implement(in torchvision). 
I export the model include the preprocess and postprocess, as [test_onnx.py](https://github.com/pytorch/vision/blob/master/test/test_onnx.py)
And I fix the input(3x500x500) and ouput (sorce:1000, label:1000, box:1000x4), set the opset is 12, not use the dynamic_axes.

While, I found the onnx model have `If` op, here the [link](https://github.com/onnx/onnx/blob/master/docs/Operators.md#If).

The doc make me know, `else_branch `and `then_branch` is a onnx graph. This is may as the sub-graph in one onnx model.

I don't know how to make openvino mo.py to prase this op, and convert the openvino model.

Hopeful, someone can give me suggestions.

Thanks!

**Comment by jgespino** [comment]
Hi @xiaoweiChen 

According to the [Supported Layers](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#onnx_supported_operators) document, ONNX `If` op is not supported by OpenVINO. However, it should be possible to create a custom layer, see the [Custom Layers Guide](https://docs.openvinotoolkit.org/latest/openvino_docs_HOWTO_Custom_Layers_Guide.html#ONNX-models-with-custom-layers).

Regards,
Jesus

**Comment by xiaoweiChen** [comment]
Thanks @jgespino for you reply. 
I add some custom op base on the guide, like SequenceAt, SplitToSequence... This is just like a function.

While `If` is different: 
From https://github.com/onnx/onnx/blob/master/docs/Operators.md#If 
> Attributes
>else_branch : graph (required)
>Graph to run if condition is false. Has N outputs: values you wish to be live-out to the enclosing scope. The number of outputs must match the number of outputs in the then_branch.
>then_branch : graph (required)
>Graph to run if condition is true. Has N outputs: values you wish to be live-out to the enclosing scope. The number of outputs must match the number of outputs in the else_branch.

The branch is a graph, it just like the sub-onnx model in the original model, and some ops in sub-onnx model is supported by OpenVINO. 

I don't know how to process the sub-onnx or sub-graph in OpenVINO  model optimizer, then open this issue.

**Comment by slyalin** [comment]
Hi @xiaoweiChen,

There is a challenge to support `If` in Model Optimizer because may require dynamic control flow during execution which is currently not supported. I'm not familiar with that place in the model where `If` is required, is it possible to share ONNX model somehow to look at that particular place? Does it have large branches inside `If`?

**Comment by xiaoweiChen** [comment]
Hi @slyalin

You are right!

as my above words:
>This is a Faster-RCNN model exported by pytorch official implement(in torchvision).
>I export the model include the preprocess and postprocess, as test_onnx.py
>And I fix the input(3x500x500) and ouput (sorce:1000, label:1000, box:1000x4), set the opset is 12, not >use the dynamic_axes.

This nodel is a Pytorch official model in torchvision.(I use Pytorch 1.6)

In [vision](https://github.com/pytorch/vision), [test_onnx.py](https://github.com/pytorch/vision/blob/master/test/test_onnx.py) can export the Faster-RCNN model.

I modify the test_onnx.py, make it just test and export Faster-RCNN(Not do the things wit Mask-RCNN and Keypoint-RCNN).

(waiting update code)

`faster-crnn-1.onnx` is same with `faster-crnn-2.onnx`.

Base on OpenVINO version `2020.4.0-359-21e092122f4-release/2020/4`, I add ONNXResize11(from master branch), SplitToSequence, SequenceAt, Min, GreaterOrEqual for onnx extension.

En... You can try running this script and export the onnx for test.

**Comment by slyalin** [comment]
@xiaoweiChen,

If the branches are really small and execution of both `then` and `else` isn't so expensive in comparison to the whole inference time, then you cat try to eliminate `if` by executing both branches and then use `Select` to merge the results depending on condition.

At this moment OpenVINO doesn't support `If` and only thing that I can propose for now is to use Mask-RCNN conversion hint that is described here: https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_onnx_specific_Convert_Mask_RCNN.html. There is a config file that eliminates unsupported things in the model replacing them by complex layers in xml, and you can try to adopt it for corresponding faster-rcnn model, but I don't know how hard it would be.

**Comment by bianxg** [comment]
Is this problem solved? I meet same problem. Thanks.

**Comment by slyalin** [comment]
@bianxg, do you have exactly the same case (Faster-RCNN), or it's a different unrelated model with 'If' operator? Generic 'If' operator is not supported as-is right now.

**Comment by bianxg** [comment]
> @bianxg, do you have exactly the same case (Faster-RCNN), or it's a different unrelated model with 'If' operator? Generic 'If' operator is not supported as-is right now.

https://github.com/openvinotoolkit/openvino/issues/3846
