### ISSUE TITLE
Text Detection C++ Demo - working with VPU ( Intel® Neural Compute Stick 2 )

### ISSUE THREAD

**Issue by nehasoni3** [openvinotoolkit/openvino#241]
Hi

I am surprised to see that **Text Detection C++ Demo** is working with Intel® Movidius™ Neural Compute Stick2.However, it is clearly mentioned in documentation that it is not supported.

Please clear the reasons behind this.
Thanks!!

**Comment by shubha-ramani** [comment]
Dear @nehasoni3,

The statement made on [The text detection Demo doc](http://docs.openvinotoolkit.org/latest/_demos_text_detection_demo_README.html) is that non-Intel models (i.e. such as those obtained via downloader.py) may not work properly. But intel pre-trained models should work fine. Which model(s) did you use for this demo ? 

If you used these, then it's fine. These should actually work well.

> text-detection-0003, which is a detection network for finding text.
text-detection-0004, which is a lightweight detection network for finding text.
text-recognition-0012, which is a recognition network for recognizing text.
handwritten-score-recognition-0001, which is a recognition network for recognizing handwritten score marks like <digit> or <digit>.<digit>.

> NOTE: On VPU devices (Intel® Movidius™ Neural Compute Stick, Intel® Neural Compute Stick 2, and Intel® Vision Accelerator Design with Intel® Movidius™ VPUs) this demo is not supported with any of the Model Downloader available topologies. Other models may work incorrectly on these devices as well.

**Comment by nehasoni3** [comment]
Hi @shubha-ramani 

I have tried model dowmloaded via downloader.py and it is working properly with CPU and Intel's Movidius NCS2. OpenVINO R2 supports FP16 on CPU too. So I have tried FP16 model on CPU and NCS2 and its working fine.

Thanks!!

**Comment by shubha-ramani** [comment]
Dear @nehasoni3 

That's great news !! Please close this ticket if you are satisfied.

Thanks,

Shubha

**Comment by nehasoni3** [comment]
> Dear @nehasoni3
> 
> That's great news !! Please close this ticket if you are satisfied.
> 
> Thanks,
> 
> Shubha

HI @shubha-ramani 
Now I am bit confused.
As you said Model downloaded via downloader.py should not working . But it is.
I have downloaded model 
text-detection-0003, text-detection-0004, text-recognition-0012 via downloader.py.

Are these model are non-Intels?

**Comment by shubha-ramani** [comment]
Dear @nehasoni3 ,

No those ones you mention are definitely intel models. But downloader.py also downloads some models which aren't intel models. If you are curious as to which models get downloaded please take a look at C:\Program Files (x86)\IntelSWTools\openvino_2019.2.275\deployment_tools\tools\model_downloader\list_topologies.yml

Hope it helps,

Thanks,

Shubha
