### ISSUE TITLE
[Bug] openvino does not recognise gpu on atomic pi (cherry trail)

### ISSUE THREAD

**Issue by mosheliv** [openvinotoolkit/openvino#2417]
##### System information (version)
- OpenVINO => 2020.4
- Operating System / Platform => ubuntu 18.04
- Compiler => gcc
- Problem classification: gpu support

I am running this on atomic pi, lspci output:
```
00:00.0 Host bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SoC Transaction Register (rev 36)
00:02.0 VGA compatible controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Configuration Registers (rev 36)
00:14.0 USB controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series USB xHCI Controller (rev 36)
00:16.0 USB controller: Intel Corporation Device 22b7 (rev 36)
00:1a.0 Encryption controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series Trusted Execution Engine (rev 36)
00:1c.0 PCI bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #1 (rev 36)
00:1f.0 ISA bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCU (rev 36)
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0c)

```

##### Detailed description
I was following the installation guide, downloaded the gpu drivers, then run:
`./classification_sample_async -i /opt/intel/openvino/deployment_tools/demo/car.png -m ~/openvino_models/ir/public/squeezenet1.1/FP16/squeezenet1.1.xml -d GPU

and got :
```
/squeezenet1.1/FP16/squeezenet1.1.xml -d GPU
[ INFO ] InferenceEngine: 
        API version ............ 2.1
        Build .................. 2020.4.0-359-21e092122f4-releases/2020/4
        Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     /opt/intel/openvino/deployment_tools/demo/car.png
[ INFO ] Creating Inference Engine
[ ERROR ] Failed to create plugin /opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
[CLDNN ERROR]. clGetPlatformIDs error -1001

```
`##### Steps to reproduce
see problem description

**Comment by jgespino** [comment]
Hi @mosheliv 

Thanks for reaching out, could you confirm you ran the `./install_NEO_OCL_driver.sh` scrip as mentioned in the [Steps for Intel Processor Graphics (GPU)](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#additional-GPU-steps) section? The script is located in `/opt/intel/openvino/install_dependencies/`.

Regards,
Jesus

**Comment by mosheliv** [comment]
I did, but decided to do it again. However, this was not the best idea, as the install tried to removed intel-igl-core and failed:
```
dpkg: dependency problems prevent removal of intel-igc-core:
 intel-igc-opencl depends on intel-igc-core (= 1.0.2597).

dpkg: error processing package intel-igc-core (--purge):
 dependency problems - not removing
Errors were encountered while processing:
 intel-igc-core
ERROR: unable to remove intel-igc-core
       please resolve it manually and try to launch the script again.

```

**Comment by jgespino** [comment]
Hi @mosheliv 

Try removing the package with apt-get and re-running the script.
```
sudo apt-get remove intel-igc-core
sudo ./install_NEO_OCL_driver.sh
```

Regards,
Jesus

**Comment by mosheliv** [comment]
alas, same thing happens as before:

```
[ INFO ] Creating Inference Engine
[ INFO ] Loading network files:
        /home/m/openvino_models/ir/public/squeezenet1.1/FP16/squeezenet1.1.xml
        /home/m/openvino_models/ir/public/squeezenet1.1/FP16/squeezenet1.1.bin
[ INFO ] Preparing input blobs
[ WARNING ] Image /opt/intel/openvino/deployment_tools/demo/car.png is resized from (259, 787) to (227, 227)
[ INFO ] Batch size is 1
[ INFO ] Loading model to the plugin
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "./classification_sample_async.py", line 183, in <module>
    sys.exit(main() or 0)
  File "./classification_sample_async.py", line 142, in main
    exec_net = ie.load_network(network=net, device_name=args.device)
  File "ie_api.pyx", line 314, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 323, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Failed to create plugin /opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
[CLDNN ERROR]. clGetPlatformIDs error -1001

```

**Comment by jgespino** [comment]
Hi @mosheliv 

Thank you for re-running the script to ensure the Intel Graphics Compute Runtime for OpenCL is setup. Usually the error means there is an incorrect environment setup or missing openCL. However, per the [supported hardware](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/hardware.html) document, the OpenVINO toolkit does not support Cherry Trail:

> 6th to 10th generation Intel Core processors with Intel® Iris® Pro graphics and Intel HD Graphics

I apologize for the inconvenience, please let me know if you have any additional questions.

Regards,
Jesus

**Comment by ddfabbro** [comment]
Hi @jgespino 

Does newer versions of OpenVINO (e.g. 2021.1) support Cherry Trail GPU?

I am sorry, but I checked [supported hardware](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/hardware.html) documents and couldn't find where it says OpenVINO toolkit does not support Cherry Trail.

How can I confirm that?

**Comment by jgespino** [comment]
@ddfabbro Let me check with the dev team if Cherry Trail GPU is supported.

**Comment by jgespino** [comment]
Hi @ddfabbro 

The OpenVINO toolkit has not been validated on Cherry Trail, we have validated the following processors for the GPU Plugin.

- 6th to 10th generation Intel Core processors with Intel® Iris® Pro graphics and Intel HD Graphics
- Intel Xeon processor with Intel Iris Pro graphics and Intel HD Graphics (excluding the e5 family which does not include graphics)

Regards,
Jesus

**Comment by mosheliv** [comment]
I don't really understand... This page
https://docs.openvinotoolkit.org/2020.2/_docs_IE_DG_supported_plugins_Supported_Devices.html
clearley states that Intel HD GPU is supported (which is what cherry trail
is using)
in the CPU section, it says all Atom with SSE, which Cherry trail has.

Either fix your requirements or your code... I actually bought my cherry
trail based on this.

**Comment by ddfabbro** [comment]
> 
> 
> Hi @ddfabbro
> 
> The OpenVINO toolkit has not been validated on Cherry Trail, we have validated the following processors for the GPU Plugin.
> 
>     * 6th to 10th generation Intel Core processors with Intel® Iris® Pro graphics and Intel HD Graphics
> 
>     * Intel Xeon processor with Intel Iris Pro graphics and Intel HD Graphics (excluding the e5 family which does not include graphics)
> 
> 
> Regards,
> Jesus

Thank you for your answer. The processor is an Atom x5-z8350 which does have an Intel HD Graphics, so GPU inference is supported, right?

Where does it say specifically that Cherry Trail architectures are not supported?

**Comment by mtolubaeva** [comment]
Hi ddfabbro, 
could you please run "clinfo" command and paste the output here? If the drivers are correctly installed, we should see Intel HD Graphics there. Thank you.
