### ISSUE TITLE
[Bug] Build Instruction is missing?

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino#2428]
If you go into the documentation, the "build instructions" link is broken.

https://github.com/openvinotoolkit/openvino/blob/master/get-started-linux.md

**Comment by jgespino** [comment]
Hi @raymondlo84 

It would be great if you can submit a merge request, please see the [contributing](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING_DOCS.md#edit-existing-document) document for guidance.

This is the correct location for the build instructions: https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md

Regards,
Jesus
