### ISSUE TITLE
[Bug] setupvars.sh error

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino#2429]
Just followed the build instruction here. After 'make install', I opened a new terminal and the setupvars.sh seems not to be able to pick up the python module.

I'm on Ubuntu 18.04
```
Linux raymondlo84-850XBC 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
cmake --version
cmake version 3.18.2
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 

```

Error I got. 
```
raymondlo84@raymondlo84-850XBC:/usr/local$ source setupvars.sh
[setupvars.sh] ERROR: Can not find OpenVINO Python module for python3.6 by path /usr/local/python/python3.6

```

**Comment by raymondlo84** [comment]
I figured it out. We have to force the toolkit to pick up the 3.6. Otherwise, it will use python2.7

cmake -DPYTHON_EXECUTABLE=`which python3.6` -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6         ../

**Comment by jjustinm4** [comment]
still im recieving the same error , python is 3.6

**Comment by blazczak** [comment]
@jjustinm4 double-check that the value in PYTHON_EXECUTABLE is the (absolute) path to the installed python3 interpreter, not the verbatim value of `which python3.6`; I think the github markup characters masked the correct string value in the above post.

so ```cmake -DPYTHON_EXECUTABLE=`which python3.6` ``` plus other switches applicable to your particular configuration. You may also need ```-DENABLE_PYTHON=ON```.

Once openvino is built, you will need to set PYTHONPATH and LD_LIBRARY_PATH before sourcing setupvars.sh

See also https://www.intel.com/content/www/us/en/support/articles/000057448/software/development-software.html
