### ISSUE TITLE
[Good First Issue]: [OV JS] Support core.query_model()

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#24373]
### Context

Node.js API is the newest binding of OpenVINO.
The task is to expose Core::query_model() method.
[Python API](https://docs.openvino.ai/2024/api/ie_python_api/_autosummary/openvino.Core.html#openvino.Core.query_model) documentation of this method

### What needs to be done?

 - add `query_model()` method on C++ side (src/bindings/js/node/src/core_wrap.cpp)
 - update TypeScript definition (src/bindings/js/node/lib/addon.ts)
 - create unit test for added functionality using Node.js Test Runner
 Tip: Before creating a new function to convert an argument, take a look at helper methods to see if it doesn't exist already

### Example Pull Requests

 - https://github.com/openvinotoolkit/openvino/pull/22100 
 - https://github.com/openvinotoolkit/openvino/pull/23743
 - https://github.com/openvinotoolkit/openvino/pull/24023

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai 

### Ticket

134822

**Comment by Aryan8912** [comment]
.take

**Comment by p-wysocki** [comment]
Hello @Aryan8912, there are currently three issues with open PRs assigned to you. Please finish them before picking more tasks.

**Comment by hegdeadithyak** [comment]
.take

**Comment by hegdeadithyak** [comment]
@almilosz To implement this method, I should call ` _core.query_model(...)` , Am I right ?

**Comment by almilosz** [comment]
Yes, [C++ docs](https://docs.openvino.ai/2024/api/c_cpp_api/classov_1_1_core.html#_CPPv4NK2ov4Core11query_modelERKNSt10shared_ptrIKN2ov5ModelEEERKNSt6stringERK6AnyMap)

**Comment by almilosz** [comment]
I don't know why it was closed. Sorry

**Comment by vishniakov-nikolai** [comment]
Hello @hegdeadithyak! Do you need any help with this issue?
Do you have a time to continue work on this task?

**Comment by hegdeadithyak** [comment]
Yes, ont it will open a PR by tomorrow

**Comment by nashez** [comment]
.take
