### ISSUE TITLE
[Good First Issue] [ARM]: Implement CPU plugin just-in-time emitter for LogicalNot operation

### ISSUE THREAD

**Issue by eshoguli** [openvinotoolkit/openvino#24445]
### Context

[JIT Emitters](https://github.com/openvinotoolkit/openvino/blob/42f1cb095143f19c0b9ee25836c29748bc8d9bf2/src/plugins/intel_cpu/src/emitters/README.md) are part of code generation feature (a.k.a. tensor compiler) that automatically produces highly-efficient optimized fused subgraph binary code. Each emitter implements specific operation from low level OpenVINO dialect.

### Prerequisites
Recommended to use ARM CPU based platform for development (e.g. Mac, Raspberry Pi etc). Emulators (e.g. QEMU) is still an option, but not that convenient, especially for final performance evaluation. 

### What needs to be done?

* Create `fp32` [LogicalNot](https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/operation-specs/logical/logical-not-1.html) operation JIT emitter for ARM64 SIMD platform. Use OpenVINO [CPU plugin JIT emitters](https://github.com/openvinotoolkit/openvino/blob/42f1cb095143f19c0b9ee25836c29748bc8d9bf2/src/plugins/intel_cpu/src/emitters/README.md) documentation and [Arm A-profile A64 Instruction Set Architecture](https://developer.arm.com/documentation/ddi0602/2024-03/SIMD-FP-Instructions) documentation for details.
* Modify [ARM64 executor](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp#L20) and [ARM64 kernel](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.hpp#L80) (in both places: [create_eltwise_emitter](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp#L601) and [get_supported_precisions](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp#L766)) to apply developed JIT emitter.

Before emitter implementation, please, modify tests to be sure that deveoped functionality is covered by test:
  * Add `jit` kernel check in [element-wise](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/eltwise.cpp#L257) or [activation](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp#L155) test, the test must fail.
  * If test doesn't fail then add supported operation in [element-wise test instantiation](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/eltwise.cpp) or [activation test instantiation](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp) if it's absent.

### Tests
Tests are disabled in default build, so ensure to add `-DENABLE_TESTS=ON` into cmake command.

[GoogleTest](https://github.com/google/googletest) is used for testing. CPU functional test target is [ov_cpu_func_tests](https://github.com/openvinotoolkit/openvino/tree/master/src/plugins/intel_cpu/tests/functional). You can use two `GoogleTest` filters for element-wise and activation operations:
* for element-wise operations:
```sh
./bin/[platform]/[build_type]/ov_cpu_func_tests --gtest_filter="*smoke*Eltwise*"
```
* for activations:
```sh
./bin/[platform]/[build_type]/ov_cpu_func_tests --gtest_filter="*smoke*Activation*"
```

### Example Pull Requests

* [Abs](https://docs.openvino.ai/2023.3/openvino_docs_ops_arithmetic_Abs_1.html) operation: https://github.com/openvinotoolkit/openvino/pull/23692
* [Sigmoid](https://docs.openvino.ai/2023.3/openvino_docs_ops_activation_Sigmoid_1.html) operation, which reuses [Exp emitter](https://github.com/openvinotoolkit/openvino/blob/4ef40f0f0e70abf04f13310f3e7a8f6784667dbf/src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp#L820): https://github.com/openvinotoolkit/openvino/pull/23065

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [CPU plugin JIT emitters](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/src/emitters/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@eshoguli, @dmitry-gorokhov

### Ticket

CVS-137699

**Comment by jvr0123** [comment]
.take

**Comment by jvr0123** [comment]
I'm currently having some issues with compiling Openvino on my Raspberry Pi 4. I have followed the build guide but have also been unable to get the release version to compile without the terminal freezing up after reaching about 30%. Here is the command I'm currently trying:

 `cmake -DCMAKE_BUILD_TYPE=Debug -DTHREADING=SEQ -DENABLE_OV_ONNX_FRONTEND=OFF -DENABLE_OV_PADDLE_FRONTEND=OFF -DENABLE_OV_TF_FRONTEND=OFF -DENABLE_OV_TF_LITE_FRONTEND=OFF -DENABLE_OV_PYTORCH_FRONTEND=OFF -DENABLE_OV_IR_FRONTEND=OFF -DENABLE_TESTS=ON -DENABLE_CLANG_FORMAT=OFF -DENABLE_FASTER_BUILD=ON -DENABLE_SYSTEM_FLATBUFFERS=OFF -DARM_COMPUTE_SCONS_JOBS=$(nproc --all)  .. && cmake --build . --parallel `

I have llvm and clang installed, as well as the other dependencies in install_build_dependencies.sh.

**Comment by eshoguli** [comment]
CPU overheating? Possible solutions:
1. Build with `cmake --build . --parallel 2` to prevent CPU overheating.
2. Use `qemu`: https://www.qemu.org/docs/master/system/target-arm.html. Note, please, you need aarch64 (not 32).
3. Cross compilation: https://forums.raspberrypi.com/viewtopic.php?t=343710

**Comment by jvr0123** [comment]
> CPU overheating? Possible solutions:
> 
>     1. Build with `cmake --build . --parallel 2` to prevent CPU overheating.
> 
>     2. Use `qemu`: https://www.qemu.org/docs/master/system/target-arm.html. Note, please, you need aarch64 (not 32).
> 
>     3. Cross compilation: https://forums.raspberrypi.com/viewtopic.php?t=343710

I actually just figured it out, the Raspberry Pi I'm using only has 4GB of ram, and it looks like adding 8GB of swap ram fixed the issue as the build process very quickly ate all of the system's ram. CPU temp isn't a huge issue, it stays around the ~52 C mark for the most of the build.  I don't know how much ram the RPi docker image gets, but do you think it might be worth updating the RPi build instructions with minimum RAM requirements if this is a replicable issue?

**Comment by jvr0123** [comment]
Should the supported precision be element::f32 or element::boolean? The documentation for the operation specifies that it should only come as a boolean but the issue has fp32

**Comment by eshoguli** [comment]
> Should the supported precision be element::f32 or element::boolean? The documentation for the operation specifies that it should only come as a boolean but the issue has fp32

You should support `ov::element::f32`. It means the emitter accept `float` values and returns `boolean`. To speedup computing `boolean` return value has the same size as `float` (4 bytes) but used only the least significant bit.

**Comment by jvr0123** [comment]
I currently have everything minus the emit_isa implementation done, and I'm having some trouble with the unit tests. I would like to just use a bitmask where only the LSB is 1, store it into a register and then do XOR to perform the negation on the LSB, but I can't think of a good way to get this mask. Do you have any suggestions?

> > Should the supported precision be element::f32 or element::boolean? The documentation for the operation specifies that it should only come as a boolean but the issue has fp32
> 
> You should support `ov::element::f32`. It means the emitter accept `float` values and returns `boolean`. To speedup computing `boolean` return value has the same size as `float` (4 bytes) but used only the least significant bit.
