### ISSUE TITLE
[Bug] Do inference in openvino2019.3 & openvino2020.4, but get different results

### ISSUE THREAD

**Issue by tingggggg** [openvinotoolkit/openvino#2451]
##### Detailed description
I use the python to do inference on Reitnanet(model file from onnx model zoo) with gpu,
and I do in openvino2019.3 & openvino2020.4 env. Do inference successful in openvino2019.3 but not in openvino2020.4
(use the same .onnx model convert to .xml .bin)

ERROR like this:

> Reshape failed: Check 'PartialShape::broadcast_merge_into(pshape, get_input_partial_shape(i), autob)' failed at /home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu18/b/repos/openvino/ngraph/src/ngraph/node.cpp:922:
> While validating node 'v1::Add Add_1248(Interpolate_1245[0]:f32{1,256,30,40}, Add_1247[0]:f32{1,256,26,26}) -> (f32{1,256,30,40})':
> Argument shapes are inconsistent.

I can't find any similar question, so give me help, pls~

**Comment by jgespino** [comment]
Hi @tingggggg 

Could you confirm this is the model you are using?
https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/retinanet#model

Please provide the model optimizer command and sample code to reproduce. 

Regards,
Jesus

**Comment by tingggggg** [comment]
Hi @jgespino 

Thanks for your help first.

model optimize: openvino_2020.4.287 (mo_onnx.py)
Then model is from above link.

 infer_request_handle = exec_net.start_async(request_id=0, inputs=inputs)
  if infer_request_handle.wait(timeout) != 0:
    return None, None

Part of code is as follow
  ```
net, plugin = load_net(device.upper(), (model_xml, model_bin))
exec_net = update_net(net, plugin, input_blob, batch, (1, shape[0], shape[1], shape[2]))

for i in range(number_iter):
    t0 = time()
    infer_request_handle = exec_net.start_async(request_id=0, inputs=inputs)
    if infer_request_handle.wait(timeout) != 0:
      return None, None
    infer_time.append((time() - t0) * 1000)
  res = infer_request_handle.outputs[out_blob]
  return res, np.average(np.asarray(infer_time))
```

**Comment by jgespino** [comment]
Hi @tingggggg 

I converted the model with the following command and was able to inference using the benchmark_app on the latest release OpenVINO toolkit 2021.1.

`python3 mo.py --framework onnx --input_model retinanet-9.onnx`

I recommend checking your application for deprecated API calls as there were many changes from 2019.3 release to date. See the [deprecated dist](https://docs.openvinotoolkit.org/latest/deprecated.html) and [release notes](https://software.intel.com/content/www/us/en/develop/articles/openvino-relnotes.html). I also recommend reviewing release notes from 2019R3 to 2020.4.

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, feel free to re-open if additional assistance is needed.

**Comment by tingggggg** [comment]
> Hi @tingggggg
> 
> I converted the model with the following command and was able to inference using the benchmark_app on the latest release OpenVINO toolkit 2021.1.
> 
> `python3 mo.py --framework onnx --input_model retinanet-9.onnx`
> 
> I recommend checking your application for deprecated API calls as there were many changes from 2019.3 release to date. See the [deprecated dist](https://docs.openvinotoolkit.org/latest/deprecated.html) and [release notes](https://software.intel.com/content/www/us/en/develop/articles/openvino-relnotes.html). I also recommend reviewing release notes from 2019R3 to 2020.4.
> 
> Regards,
> Jesus

Thanks for your help!
