### ISSUE TITLE
Custom Operation Subgraph replacement

### ISSUE THREAD

**Issue by Hussni-V** [openvinotoolkit/openvino#2462]
One of my models has a custom operation called FR, I was hoping to break the operation down to other ops instead of implementing an IE extension. The operation works like this.

given 2 input tensors- The first input contains box points coordinates(10000x4), the second one is the feature map (1x256x100x100)

each box corresponds to a point in the feature map (10000=100x100)

The operation is
0. Create a new feature map with the same dims as the input feature map

1. Sample from the input feature map using the coordinates of the 4 corners of the box by bilinear interpolation
2. After getting 4 vectors, sum them together and insert the vector on the new feature map
3. Repeat from 1 for all boxes  
4. output new feature map

Is this operation able to be broken down into available ops or not?

Currently, I don't see a way to do it.

**Comment by geexie** [comment]
@Hussni-V, could you please provide some code snippet or something? I didn't quite get by which plain you actually do sampling to apply 4 coordinates to 256 features to gen 256 features again.

**Comment by Hussni-V** [comment]
here's a pseudo-code

Input: original feature map (F), bounding boxes (B)
Output: reconstructed feature map (F_r)

**for** i : 0 **to** h-1 **do**
   **for** j: 0 **to** w-1 **do**
      P <- GetFourCornerPoints( B(i,j) )
      **for** p in P **do**
         F_r(i,j) <- F_r(i,j) + BilinearInterpolate (F,p)
      **end for**
   **end for**

**Comment by Hussni-V** [comment]
I have went the route of implementing my custom op as an IE extension instead
