### ISSUE TITLE
[Feature Request]:  adding yolov7-tf to the public pre-trained model

### ISSUE THREAD

**Issue by Neoyning** [openvinotoolkit/openvino#24766]
### Request Description

I have been testing yolov7 on openvino c++ for a while.

I first download the pre-trained model `yolov7-tiny.pt` from their github release page [link](https://github.com/WongKinYiu/yolov7/releases) .

And then convert the pytorch model format to onnx format by
`python3 -W ignore export.py --weights yolov7-tiny.pt --grid --end2end --max-wh 640 --fp16 --device cpu`

Then generating the `.xml` and `.bin` by following python script

```
from openvino.tools import mo
from openvino.runtime import serialize

if __name__ == '__main__':
    model = mo.convert_model('yolov7-tiny.onnx')
    # serialize model for saving IR
    serialize(model, 'yolov7-tiny.xml')
```

 Now I have the `yolov7-tiny.xml` and `yolov7-tiny.bin`, ready for object detection task.

However, when I implemented the model on  `object_detection_demo` in open model zoo c++

`./object_detection_demo -d CPU -i ./imgs -m yolov7-tiny.xml -at yolo`

I get result

```
[ INFO ] OpenVINO
[ INFO ] 	version: 2023.1.0
[ INFO ] 	build: 2023.1.0-12185-47b736f63ed-HEAD
[ INFO ] Reading model yolov7-tiny.xml
[ INFO ] Model name: torch_jit
[ INFO ] 	Inputs: 
[ INFO ] 		images, f32, [1,3,640,640], [...]
[ INFO ] 	Outputs: 
[ INFO ] 		output, f32, [..100,7], [...]
[ WARNING ] Automatically detected layout '[N,C,H,W]' for input 'images' will be used.\
[ ERROR ] get_shape was called on a descriptor::Tensor with dynamic shape
```

Or (when use conversion `python3 -W ignore export.py --weights yolov7-tiny.pt --grid` )

```
[ INFO ] OpenVINO
[ INFO ] 	version: 2023.1.0
[ INFO ] 	build: 2023.1.0-12185-47b736f63ed-HEAD
[ INFO ] Reading model yolov7-tiny.xml
[ INFO ] Model name: torch_jit
[ INFO ] 	Inputs: 
[ INFO ] 		images, f32, [1,3,640,640], [...]
[ INFO ] 	Outputs: 
[ INFO ] 		output, f32, [1,25200,85], [...]
[ WARNING ] Automatically detected layout '[N,C,H,W]' for input 'images' will be used.
[ INFO ] The model yolov7-tiny.xml is loaded to CPU
[ INFO ] 	Device: CPU
[ INFO ] 		Number of streams: 1
[ INFO ] 		Number of threads: 6
[ INFO ] 	Number of inference requests: 2
frameNum: 0
frameNum: 1
Segmentation fault (core dumped)
```

The executable `object_detection_demo` can not successfully run... 
Since then I suggest adding yolov7-tf to the public pre-trained model, which can then be downloaded by omz_downloader.

Thanks~

### Feature Use Case

adding yolov7-tf to the public pre-trained model

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by andrei-kochin** [comment]
@Neoyning as currently we are not adding any public models to the OMZ so we'll not add yolov7 to the omz_downloader

For step-by-step execution of yolov7 we had a notebook https://github.com/openvinotoolkit/openvino_notebooks/blob/2024.0/notebooks/226-yolov7-optimization/226-yolov7-optimization.ipynb
