### ISSUE TITLE
[Good First Issue]: Set/Get Properties in C-API

### ISSUE THREAD

**Issue by rahulchaphalkar** [openvinotoolkit/openvino#24911]
### Context

In C-API, one can set/get properties for Core, compiled model etc. The core method 
```
ov_core_get_property(const [ov_core_t](https://docs.openvino.ai/2024/api/c_cpp_api/group__ov__core__c__api.html#_CPPv49ov_core_t) *core, const char *device_name, const char *property_key, char **property_value)
```
and other similar ones have `device_name` as an argument.
However, some properties like `CacheDir` don't need a device.
Also, some properties are device specific i.e. available for one device but not another.

### What needs to be done?

Can the C-API have a variant where `device_name` is not required? How to access `CacheDir` and other non-device specific properties if not?

How to determine which property applies for which device? I'm currently getting errors trying to access `CacheMode` for `CPU` for example from `ov_core_get_property`. Some documentation or examples would be helpful.

### Resources

- https://docs.openvino.ai/2024/api/c_cpp_api/group__ov__core__c__api.html

### Contact points

rahulchaphalkar

**Comment by ANSH-PANT** [comment]
Yes, it is possible to have a C-API variant where **device_name** is not required for global properties. You should be able to access properties not specific to any device (like **CacheDir**) without specifying a device. 

To get a global property like **CacheDir**, you can create a helper function or check if the API already provides such a mechanism:
```
#include <openvino/openvino.h>
#include <stdio.h>
#include <stdlib.h>

// Function to get a global property
ov_status_e ov_core_get_global_property(const ov_core_t* core, const char* property_key, char** property_value) {
    // Call the original function with an empty device name
    return ov_core_get_property(core, "", property_key, property_value);
}

int main() {
    ov_core_t* core;
    char* cache_dir;

    // Initialize the core
    if (ov_core_create(NULL, &core) != OV_OK) {
        printf("Failed to create OV core\n");
        return -1;
    }

    // Get the CacheDir property
    if (ov_core_get_global_property(core, "CACHE_DIR", &cache_dir) != OV_OK) {
        printf("Failed to get CACHE_DIR property\n");
    } else {
        printf("Cache Directory: %s\n", cache_dir);
        free(cache_dir);  // Free the property value when done
    }

    // Clean up
    ov_core_free(core);

    return 0;
}
``` 

For device-specific properties, you specify the device name:

```
#include <openvino/openvino.h>
#include <stdio.h>
#include <stdlib.h>

int main() {
    ov_core_t* core;
    char* cache_mode;

    // Initialize the core
    if (ov_core_create(NULL, &core) != OV_OK) {
        printf("Failed to create OV core\n");
        return -1;
    }

    // Get the CacheMode property for CPU
    if (ov_core_get_property(core, "CPU", "CACHE_MODE", &cache_mode) != OV_OK) {
        printf("Failed to get CACHE_MODE property for CPU\n");
    } else {
        printf("Cache Mode for CPU: %s\n", cache_mode);
        free(cache_mode);  // Free the property value when done
    }

    // Clean up
    ov_core_free(core);

    return 0;
}
```

**Comment by rahulchaphalkar** [comment]
Thanks. 
Right now there is no documentation for which properties do not require a device specified (or if they're supported only by a specific device, etc.). Can I get some clarity on that front?
Also, does `cache_mode` property apply to CPU? I see that in the example above, however I can't find it in the code, and in my local testing, cache_mode via `ov_core_get_property` failed.

**Comment by riverlijunjie** [comment]
> Thanks. Right now there is no documentation for which properties do not require a device specified (or if they're supported only by a specific device, etc.). Can I get some clarity on that front? Also, does `cache_mode` property apply to CPU? I see that in the example above, however I can't find it in the code, and in my local testing, cache_mode via `ov_core_get_property` failed.

Hi @rahulchaphalkar OpenVINO C APIs provide properties can be found in 
https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/c/docs/api_overview.md#properties
https://docs.openvino.ai/2024/api/c_cpp_api/group__ov__property__c__api.html

It contains 3 types properties: Common properties, GPU plugin specified properties and AUTO plugin specified properties. As we known common properties can be used to multiple plugins but need query whether the plugin support it by `ov_core_get_property` before use it.
About `cache_mode`property, it should be supported by CPU plugin, what error you got?

**Comment by riverlijunjie** [comment]
> > Thanks. Right now there is no documentation for which properties do not require a device specified (or if they're supported only by a specific device, etc.). Can I get some clarity on that front? Also, does `cache_mode` property apply to CPU? I see that in the example above, however I can't find it in the code, and in my local testing, cache_mode via `ov_core_get_property` failed.
> 
> Hi @rahulchaphalkar OpenVINO C APIs provide properties can be found in https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/c/docs/api_overview.md#properties https://docs.openvino.ai/2024/api/c_cpp_api/group__ov__property__c__api.html
> 
> It contains 3 types properties: Common properties, GPU plugin specified properties and AUTO plugin specified properties. As we known common properties can be used to multiple plugins but need query whether the plugin support it by `ov_core_get_property` before use it. About `cache_mode`property, it should be supported by GPU plugin, seems not supported by CPU plugin.

**Comment by rahulchaphalkar** [comment]
Thank you, that provides some clarity. Closing issue.
