### ISSUE TITLE
Attribute "factor" missing in Resample layer of IR converted from a MXNet model with UpSampling op

### ISSUE THREAD

**Issue by rocketbear** [openvinotoolkit/openvino#25]
Following is the UpSampling op in MXNet's json file:

    {
      "op": "UpSampling", 
      "name": "fpn3_upsample_", 
      "attrs": {
        "num_args": "1", 
        "sample_type": "nearest", 
        "scale": "2"
      }, 
      "inputs": [[214, 0, 0]]
    }, 

Following is the Resample layer in the xml file of the IR:

		<layer id="53" name="fpn3_upsample_" precision="FP32" type="Resample">
			<data antialias="0" scale="2" type="caffe.ResampleParameter.NEAREST"/>
			<input>
				<port id="0">
					<dim>1</dim>
					<dim>96</dim>
					<dim>16</dim>
					<dim>16</dim>
				</port>
			</input>
			<output>
				<port id="1">
					<dim>1</dim>
					<dim>96</dim>
					<dim>32</dim>
					<dim>32</dim>
				</port>
			</output>
		</layer>

It turns out that the inference engine relies on the "factor" attribute to infer the output shape during calling CNNNetwork::reshape. So an exception is raised when trying to reshape the input at the inference engine side.

In order to fix this problem,  function mo.front.mxnet.extractors.up_sampling.up_sampling_ext is modified as follows:

    def up_sampling_ext(attrs):
	    node_attrs = {
	        'type': 'Resample',
	        'scale': attrs.int("scale", 1),
	        'factor': attrs.int("scale", 1),
	        'sample_type': 'caffe.ResampleParameter.NEAREST',
	        'antialias': 0,
	        'infer': up_sampling_infer
	    }
	    return node_attrs

**Comment by rocketbear** [comment]
This issue is resolved in the latest Intel's release of OpenVINO 2018R4.

**Comment by rocketbear** [comment]
This issue seems to be fixed in the 2018R4 release of Intel's OpenVINO.
Now the Resample layer works without attribute "factor", as long as attribute "scale" is provided.

**Comment by lazarevevgeny** [comment]
The issue should had been fixed already. Please, take the latest OpenVINO and verify.
