### ISSUE TITLE
[Good First Issue]: Add a new method overload to the Python API

### ISSUE THREAD

**Issue by akuporos** [openvinotoolkit/openvino#25119]
### Context

Needs to add an overload for the `get_result_index` method to openvino.Model class in Python API.

### What needs to be done?

There is method [get_result_index](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/src/pyopenvino/graph/model.cpp#L567) which takes as the input argument `openvino.runtime.Output`.
Please, add one more overloaded method which will take `op.Result` as input argument.

Also please cover a new overload of the method by adding test to [this file](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_runtime/test_model.py#L126).

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)
- [How to test OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md#how-to-test-openvino-python-api)

### Contact points

@akuporos @p-wysocki @jiwaszki

### Ticket

131040

**Comment by amkarn258** [comment]
Hi @akuporos ,
I can take this if no one else is assigned yet

**Comment by amkarn258** [comment]
.take

**Comment by amkarn258** [comment]
Added a [PR](https://github.com/openvinotoolkit/openvino/pull/25160) for this issue
