### ISSUE TITLE
[Good First Issue]: Extend Python API with `ROIAlignRotated-15`

### ISSUE THREAD

**Issue by mitruska** [openvinotoolkit/openvino#25325]
### Context

Instead of doing C++ to Python bindings for each and every OpenVINO operator, we are using internal `NodeFactory`, which takes the name of the operator as an argument:
```python
op = NodeFactory().create("ROIAlignRotated", *args, **kwargs)  # pseudocode
```
Such an API is counter intuitive for an end user, so we are also adding Python API with a proper, pythonic and clear functions. Those Python functions are just wrappers around `NodeFactory` object call, and their primary goal is to provide appropriate inputs docs and more pythonic API:
```python
op = ops.roi_align_rotated(*args, **kwargs)  # pseudocode
```

This task regards adding such a Python API function for ROIAlignRotated-15 operator.

### What needs to be done?

1. Extend Python API and Python compatibility API with ROIAlignRotated (operator should be added to the opset15/ops.py)
2. Add tests for both APIs
3. Create a PR

`ROIAlignRotated` is a similar op to `ROIAlign`, with some modifications to enable rotation.

Python API `roi_align` can be used as an example:
https://github.com/openvinotoolkit/openvino/blob/bc505ba8ddafe938e01fa5530ac5d6cc492efe17/src/bindings/python/src/openvino/runtime/opset9/ops.py#L97-L141

Python API `roi_align_rotated` function should reflect ROIAlignRotated C++ constructor:
https://github.com/openvinotoolkit/openvino/blob/bc505ba8ddafe938e01fa5530ac5d6cc492efe17/src/core/include/openvino/op/roi_align_rotated.hpp#L20-L39

Please see attached PR, this task is very similar to the linked `Col2Im` Python API.

### Example Pull Requests

https://github.com/openvinotoolkit/openvino/pull/24569

### Resources

- [ROIAlignRotated documentation](docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/detection/roi-align-rotated-15.rstl)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [How to test OpenVINO Python API](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/docs/test_examples.md#how-to-test-openvino-python-api)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@mitruska
@p-wysocki 
@akuporos 

### Ticket

141569

**Comment by awayzjj** [comment]
.take

**Comment by hub-bla** [comment]
.take

**Comment by mitruska** [comment]
@hub-bla The PR  https://github.com/openvinotoolkit/openvino/pull/25755 has been merged, thank you for this contribution! 
Feel free to take a look at [Good First Issues Board](https://github.com/orgs/openvinotoolkit/projects/3/views/1) and select your next assignment 🚀
