### ISSUE TITLE
[Good First Issue]: Enable Model.clone() method

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#25402]
### Context

Node.js API is the newest binding of OpenVINO.
The task is to expose  [Model::clone()](https://docs.openvino.ai/2024/api/ie_python_api/_autosummary/openvino.Model.html#openvino.Model.clone)  method
C++ docs [here](https://docs.openvino.ai/2024/api/c_cpp_api/classov_1_1_model.html#_CPPv4NK2ov5Model5cloneEv)

### What needs to be done?

- add methods on C++ side (src/bindings/js/node/src/model_wrap.cpp)
 - update TypeScript definition (src/bindings/js/node/lib/addon.ts)
 - create unit test for added functionality using Node.js Test Runner, 
 Tip: Before creating a new function to convert an argument, take a look at helper methods to see if it doesn't exist already

### Example Pull Requests

 - https://github.com/openvinotoolkit/openvino/pull/23743
 - https://github.com/openvinotoolkit/openvino/pull/24023

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai 

### Ticket

-

**Comment by nashez** [comment]
.take

**Comment by nashez** [comment]
@almilosz @mlukasze Please review the PR
