### ISSUE TITLE
Problems building on jetson nano

### ISSUE THREAD

**Issue by blackantywj** [openvinotoolkit/openvino#255]
When I ran make on nvidia jetson nano, the following error occurred. It seems that this file format is not supported

> https://paste.ubuntu.com/p/3QJNxnFpTF/

I want to know how I can solve this problem...Thank you very much

**Comment by shubha-ramani** [comment]
Dear @blackantywj 

The problem you are having has nothing to do with OpenVino or Intel. I did a little research. Perhaps you forgot to flash the Nvidia Jetson Nano.
[https://devtalk.nvidia.com/default/topic/1048059/general/-solved-libcudart-so-error-adding-symbols-file-in-wrong-format/](https://devtalk.nvidia.com/default/topic/1048059/general/-solved-libcudart-so-error-adding-symbols-file-in-wrong-format/)

Thanks and Hope it helps,

Shubha

**Comment by blackantywj** [comment]
> Dear @blackantywj
> 
> The problem you are having has nothing to do with OpenVino or Intel. I did a little research. Perhaps you forgot to flash the Nvidia Jetson Nano.
> https://devtalk.nvidia.com/default/topic/1048059/general/-solved-libcudart-so-error-adding-symbols-file-in-wrong-format/
> 
> Thanks and Hope it helps,
> 
> Shubha
First of all, thank you very much for your reply. 
After reading the link you sent me, I am sorry that I found that it didn't work on my question.
But I found that the version of the error file (libopencv_imgcs...) in /usr/local/lib is opencv 3.4.4, and the version in /temp/opencv_4.1.1_ubuntu18/lib is opencv 4.1.1 .
Could you please tell me whether it is ok to use the file under my path to replace the file under temp and what i should do if that doesn't work.
Thank you

**Comment by alalek** [comment]
> adding symbols: File in wrong format

How did you build OpenCV?

Output of this utility may help: `file <path to libopencv_imgcodecs.so.4.1.1>`

CMake output and `make VERBOSE=1` should help too.

**Comment by blackantywj** [comment]
> > adding symbols: File in wrong format
> 
> How did you build OpenCV?
> 
> Output of this utility may help: `file <path to libopencv_imgcodecs.so.4.1.1>`
> 
> CMake output and `make VERBOSE=1` should help too.

Thank you 

> > adding symbols: File in wrong format
> 
> How did you build OpenCV?
> 
> Output of this utility may help: `file <path to libopencv_imgcodecs.so.4.1.1>`
> 
> CMake output and `make VERBOSE=1` should help too.

Thank you for your reply.
I did as you said, but it seems to remind me of the previous mistake
In addition, I followed a blog to build opencv, but I'm sorry I couldn't find the link

**Comment by avitial** [comment]
There are some instructions available on how to build from source on ARM64 SBCs for usage with NCS2, please checkout the following guide: https://software.intel.com/content/www/us/en/develop/articles/arm64-sbc-and-ncs2.html.

Closing this, feel free to reopen and ask additional questions related to this topic.
