### ISSUE TITLE
misplaced double quote (") causing batch file error

### ISSUE THREAD

**Issue by mfhansen** [openvinotoolkit/openvino#25524]
https://github.com/openvinotoolkit/openvino/blame/874aead52cfc9bae422946098867af78130a5297/scripts/setupvars/setupvars.bat#L37

current code:
set "OpenVINO_DIR=%INTEL_OPENVINO_DIR%\runtime\cmake"

correct code:
set OpenVINO_DIR="%INTEL_OPENVINO_DIR%\runtime\cmake"

**Comment by chux0519** [comment]
Hit a bug probably causing by this line. It will wrongly set the path like `C:\XXXXX\Intel\openvino_2024\\runtime\cmake`

**Comment by artanokhov** [comment]
Folks, could you please clarify with which OV version and the package(GenAI or regular one) you have this error?

Missed quotes for GenAI fixed by this commit
https://github.com/openvinotoolkit/openvino/commit/d840d86905f013d95cccbafaa0ddff266e250f75
