### ISSUE TITLE
Unsupported layer type "ScatterNDUpdate on NPU

### ISSUE THREAD

**Issue by IkrameBeggar** [openvinotoolkit/openvino#25607]
Hello everyone, I have a pose estimation model(SPNv2). I converted the model from Pytorch FP32 to OpenVINO FP16 IR representation (passing by onnx).

OpenVINO version: 2022.3.1

When I tried to run the model on NCS2 I had this error:

Traceback (most recent call last):
  File "test_spnv2_myriad.py", line 49, in <module>
    compiled_model = ie_core.compile_model(model=model, device_name="MYRIAD")
  File "/opt/intel/openvino_2022.3.1/python/python3.8/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: [ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/frontend/frontend.cpp:596 Failed to compile layer "ScatterND_8672": unsupported layer type "ScatterNDUpdate"

Can anyone help me with this please?

**Comment by Maxim-Doronin** [comment]
Hi! Please indicate OpenVINO version that you're currently using

**Comment by IkrameBeggar** [comment]
> Hi! Please indicate OpenVINO version that you're currently using

I'm using OpenVINO version 2022.3.1

**Comment by avitial** [comment]
@IkrameBeggar AFAIK and as per https://github.com/openvinotoolkit/openvino/issues/13594, ScatterNDUpdate is not supported by Myriad/HDDL plugins (NCS2), only ScatterUpdate type is. In case you are using PyTorch check this comment and see if its relevant to your model https://github.com/openvinotoolkit/openvino/issues/3882#issuecomment-834382914. Hope this helps.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
