### ISSUE TITLE
Errata on benchmark page

### ISSUE THREAD

**Issue by jstumpin** [openvinotoolkit/openvino#2582]
https://docs.openvinotoolkit.org/latest/openvino_docs_performance_benchmarks.html

*i9-10920X is written as i7-10920X

**Comment by ilya-lavrenov** [comment]
@jstumpin could you please create a PR with the fix?

**Comment by jstumpin** [comment]
There's nothing (or at least I couldn't find one) in this [repo](https://github.com/openvinotoolkit/openvino/blob/master/docs/benchmarks/performance_benchmarks.md) that would reflect on the mislabeling of the graphs on the webpage.

**Comment by ilya-lavrenov** [comment]
@ntyukaev do you know where is the document with such content?

**Comment by jgespino** [comment]
Hi @jstumpin 

Could you check once more? I'm not seeing any mention of i7-10920X in https://docs.openvinotoolkit.org/latest/openvino_docs_performance_benchmarks.html. It may have already been updated.

Regards,
Jesus

**Comment by jgespino** [comment]
@jstumpin I apologize for my oversight, I now see what you are referring to. I have submitted a ticket for the team to update the documentation. 

Regards,
Jesus

Ref. 40467

**Comment by jstumpin** [comment]
Sources: 
https://docs.openvinotoolkit.org/latest/bert-large-uncased-whole-word-masking-squad-int8-0001-ov-2021-1-096.js
...
https://docs.openvinotoolkit.org/latest/yolo-v3-tf-ov-2021-1-096.js

**Comment by jgespino** [comment]
@jstumpin Benchmark page has been updated, thanks for reporting!
