### ISSUE TITLE
[Feature Request]: Tool / Webpage with all supported ops per plugin per frontend

### ISSUE THREAD

**Issue by anikulk** [openvinotoolkit/openvino#25845]
### Request Description

Hi OpenVINO team,

Do we have a landing page or tool to report ( I couldnt find anything maybe I missed it) which lists what operations are supported in OpenVINO per frontend per device type/plugin type

### Feature Use Case

This feature will help customers evaluate graphs from different frameworks and if support exists.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by ilya-lavrenov** [comment]
- supported frontend operations https://docs.openvino.ai/2024/about-openvino/compatibility-and-support/supported-operations-framework-frontend.html
- supported per-plugin operations https://docs.openvino.ai/2024/about-openvino/compatibility-and-support/supported-operations-inference-devices.html

**Comment by anikulk** [comment]
Thanks! looks like NPU isnt listed in per plugin. Can that be updated?

**Comment by avitial** [comment]
Ref. 150421

**Comment by avitial** [comment]
The following PR https://github.com/openvinotoolkit/openvino/pull/25932 contains the refactoring of the articles and also the updated conformance reports with NPU on board. 

The changes are live and report can be found here: [https://docs.openvino.ai/2024/about-openvino/compatibility-and-support/supported-operations.html](https://docs.openvino.ai/2024/about-openvino/compatibility-and-support/supported-operations.html). Closing this as it has been addressed. Feel free to reopen and ask additional questions related to this topic.
