### ISSUE TITLE
Face detection: Conversion issue from Tensorflow to OpenVINO IR format.

### ISSUE THREAD

**Issue by SaiKrishnaDyavarasetti** [openvinotoolkit/openvino#259]
While converting tensorflow based SSD-Mobilenet (one class: face) model for face detection to Openvino IR format, we are facing following error:
“[ERROR] shape [-1,-1,-1,3] is not fully defined for output 0 of image tensor.

This was the command used to do the conversion:
python3 mo.py --input_model  ~/ssd_mobilenet_face.pb  --output_dir ~/output_model /

Below is the link to the SSD mobilenet model which was used for conversion
https://drive.google.com/open?id=1veX2EF46QGknnvVwVYd3EnCAZzClECbv

**Comment by shubha-ramani** [comment]
Dear @SaiKrishnaDyavarasetti ,

Please follow the [MO Facenet Tensorflow Conversion DOC](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_FaceNet_From_Tensorflow.html). Your MO command looks different from what our documentation suggests.

Thanks,

Shubha

**Comment by lazarevevgeny** [comment]
@SaiKrishnaDyavarasetti is this issue still actual?

**Comment by AnastasiaKazantaeva** [comment]
It seems that this issue is not actual anymore, close it. Feel free to create a new issue in cases of some questions/problems
