### ISSUE TITLE
[Bug] Does anyone know what could cause glitching like this?

### ISSUE THREAD

**Issue by BlohoJo** [openvinotoolkit/openvino#2613]
I'm using OpenVINO as built into Topaz Gigapixel. This is an image upscaler that uses tensorflow.dll. Because it's a third party app, I don't know exactly how they compiled OpenVINO.

Everything was working fine until the released version 5.1.7 several days ago. In this version, they mentioned in the release notes that they updated OpenVINO for Windows.

I have a unusual set up.

Machine is a VM, running VMware.
 
OS is Windows Server 2008 R2 SP1. (Should be same as Windows 7 x64 SP1)

Application requires OpenGL. I'm using MESA 19.3.3, the mingw build of opengl32.dll, placed in the application directory. Enviroment variable is set to OpenGL version 4.2. (MESA_GL_VERSION_OVERRIDE=4.2COMPAT / MESA_GLSL_VERSION_OVERRIDE=420)

This setup has worked great in every build of the application, until the most recent release, 5.1.7, where they updated OpenVINO on Windows.

Now, with OpenVINO enabled, the output looks like this:

[https://imgur.com/a/kn69Xpn](https://imgur.com/a/kn69Xpn)

Has anyone ever seen glitching like that?

I tried raising an issue with the developers of the application but given my unique setup, I don't think there's much of a drive to want to solve this, as other users don't seem to be experiencing this. (Probably no one else is running it in a VM!)

Could this be:

VMWare related?

Windows 7 related?

MESA related? (I tried various different MESA drivers, including the latest, and setting OpenGL version overrides to different settings, and got the exact same glithing every time.)

The application creates logs, and by all indications the application seems to think I have a compatible OS and CPU and uses OpenVINO. The render time is about the same as previous releases. But it gives this weird distorted output that almost looks like a bad graphcics card or bad software drivers.

Any guesses as to what changed in OpenVINO recently that could cause a glitch like this when upscaling an image with tensorflow?

Here's the CPU info as seen by the CPU-Z:

![cpu](https://user-images.githubusercontent.com/8242464/95635458-76b77100-0a5a-11eb-88cf-c70bcd17ac30.png)

Of course I can't possibly expect anyone to be able to solve this here, I'm just hoping someone might recognize this type of glitching and can post some info as to better understand what could be happening here.

**Comment by BlohoJo** [comment]
In case it might prove useful to anyone taking a look at this, here's an archive containing logs produced by the application, as well as compiled dll files that I believe are the OpenVINO ones.

https://www49.zippyshare.com/v/LCD4g6BA/file.html

**Comment by jgespino** [comment]
Hi @BlohoJo 

Thanks for reaching out, this is a very interesting setup with many factors to consider. Unfortunately, I am not familiar with Topaz Gigapixel or how OpenVINO was integrated by the app developer. This question should really be addressed by the app developer on Topaz [Community](https://community.topazlabs.com/).

It may be worth a try to test Gigapixel on a system that is configured according to the system requirements specified by the app developer.

Regards,
Jesus
