### ISSUE TITLE
generated IR model successfully but with not support error 

### ISSUE THREAD

**Issue by WilliamZhaoz** [openvinotoolkit/openvino#262]
Hi,
When I gererated IR model from a tensorflow pb modle, I got some error messages like:
[ ERROR ]  Reduce with not consecutive axes [2, 3, 1] is not supported
but eventually I get:
[ SUCCESS ] Generated IR model.

should I do something to remove those error messages or the IR model will works well even though there are some error information?

please help me.

Thanks!

**Comment by shubha-ramani** [comment]
Dear @WilliamZhaoz ,
That is very strange actually.  Usually in Model Optimizer, [ ERROR ] is not followed by [ SUCCESS ]. Can you kindly attach your model as a *.zip as well as supply your model optimizer command ?

Thanks, kindly,

Shubha

**Comment by WilliamZhaoz** [comment]
Hi Shubha,
Of course,
You can find in this link:
https://1drv.ms/u/s!AujirVkYRH1asV6Kz3LVQwBjs8zv?e=C94Ije

a .pt file which is pytorch model, I get the trained model in pytorch.

a .onnx file which is onnx model, I converted the pytorch model into it
using
`torch.onnx.export(model, dummy_input, onnx_model_path, verbose=True)` in
python with torch.onnx tools.

a .pb file which is tensorflow model, I converted the onnx model into it
using
`onnx-tf convert -t tf -i /path/to/input.onnx -o /path/to/output.pb` in
command line with onnx-tf tools.

I got .xml, .bin, .mapping files after I using:
`python mo.py --input_model trained -o output_dir` in command line with
dldt.

but I got:

[image: Screen Shot 2019-10-03 at 11.36.26 PM.png]
I'll appreciate it if you can help me out.
Thanks.


shubha-ramani <notifications@github.com> 于2019年10月1日周二 上午1:20写道：

**Comment by lazarevevgeny** [comment]
@WilliamZhaoz , could you check the model conversion using the latest Model Optimizer from the master branch?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
