### ISSUE TITLE
How to define a customized data format?

### ISSUE THREAD

**Issue by WilliamZhaoz** [openvinotoolkit/openvino#263]
Hi,
Now I have the IR model files.
But my task is not a image related task, it is a denoising model.

The input is a matrix produced from my data preparing module and out put is a mask matrix.
The input and out put matrix like[N, T, F, C], N-batchsize, T-time length, F-Frequency, C-channel
and the evaluation criterion is also different with image, it is [SNR](https://en.wikipedia.org/wiki/Signal-to-noise_ratio)

How can I quantize my model and inference my quantized model since I install the OpenVINO from a binary package, I can modify anything.

Please help me.
Thanks.

**Comment by shubha-ramani** [comment]
Dear @WilliamZhaoz 
You can quantize your mode using [low precision 8-bit integer Inference](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_Int8Inference.html). Also take a look at the calibration tools under [https://github.com/opencv/dldt/tree/2019/tools/accuracy_checker](https://github.com/opencv/dldt/tree/2019/tools/accuracy_checker) and [https://github.com/opencv/dldt/tree/2019/tools/calibration](https://github.com/opencv/dldt/tree/2019/tools/calibration)

**Comment by WilliamZhaoz** [comment]
thanks shubha-ramani,
yes, I read the docs, and then I found all examples define the fixed input
and output format, more examples are image related, but I have a task which
is not image task, so I need to write the dataset .etc codes by myself?

Thanks.

shubha-ramani <notifications@github.com> 于2019年10月1日周二 上午1:39写道：

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
