### ISSUE TITLE
Openvino 2020.3 docker container cannot access HDDL in host machine (ubuntu 18.04) 

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/openvino#2638]
From the ${HDDL_INSTALL_DIR}/drivers/setup.sh, I can see that due to kernel incompatible issue, myd_ion installation is disabled in ubuntu 18.04

but without the myd_ion, docker container cannot access the HDDL in host machine

**Comment by jgespino** [comment]
Hi @tankienleong 

What kernel version are you using on Ubuntu 18.04? Did you install the OpenVINO toolkit on your host system first per the [installation instructions](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_docker_linux.html#use_a_docker_image_for_intel_vision_accelerator_design_with_intel_movidius_vpus)? You will need to setup the environment on the host machine which will be running hddldaemon that is responsible for communicating to the HDDL device.

Please share the full error related to myd_ion.

Regards,
Jesus

**Comment by tankienleong** [comment]
Hi @jgespino , the ubuntu 18.04 kernel version is 5.4.0-48-generic
I also installed openvino 2021.1 in ubuntu 18.04 but it only installed myd_vsc, no myd_ion

My docker container able to access HDDL (openvino 2020.3) when the host machine is ubuntu 16.04 (4.15.0-118-generic)

**Comment by jgespino** [comment]
Hi @tankienleong 

Currently, the ION driver is only supported on Kernel 5.3 or earlier. Could you try downgrading the your Kernel to 5.3? Please make sure you are using matching OpenVINO versions on the host system and docker container.

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, feel free to re-open if additional assistance is needed.

**Comment by tankienleong** [comment]
My docker container able to access HDDL after downgrade kernel to 5.3
