### ISSUE TITLE
[Feature Request]: support python3.12 on macos

### ISSUE THREAD

**Issue by cole-dda** [openvinotoolkit/openvino#26408]
### Request Description

on mac, openvion only support python3.11，on linux/windows，support python3.12。

so when a project use python3.12，can't develop/test on macos

### Feature Use Case

on mac python3.12

pip install openvino

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by ilya-lavrenov** [comment]
Hi @cole-dda 
2024.4 will support python 3.12 on all platforms.
Currently, you can install OpenVINO nightly version which is available for python 3.12 using:
```
pip install --pre -U openvino --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
```
