### ISSUE TITLE
Inputs with 4 or more dimensions cause RuntimeError: AssertionFailed: perm.size() == 4

### ISSUE THREAD

**Issue by chloroaqua** [openvinotoolkit/openvino#265]
I'm doing some testing to try to get a model to work with more than 3 inputs. When I try to load a simple model (onto a Neural Compute Stick 2 on Windows 10 2019.2.0-436-gf5827d4) I get this error:

  File "ie_api.pyx", line 551, in openvino.inference_engine.ie_api.IEPlugin.load
  File "ie_api.pyx", line 561, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: AssertionFailed: perm.size() == 4

[model_example.txt](https://github.com/opencv/dldt/files/3674106/model_example.txt)

**Comment by shubha-ramani** [comment]
Dear @chloroaqua 
3 or 4D should work though. There is an [IDZ Poster who couldn't run 5D on MYRIAD](https://software.intel.com/en-us/forums/computer-vision/topic/821181) and if you'll notice, he got a specific error 

>  ['RuntimeError: [VPU] Convolution supports only 3D or 4D input].

Thank you for your IR above. Can you attach your original model as a *.zip ? Also which Model Optimizer command did you use ?

Thanks,

Shubha

**Comment by chloroaqua** [comment]
The PB file is too large to attach. The command used is:
python3 "C:\\Program Files (x86)\\IntelSWTools\\openvino\\deployment_tools\\model_optimizer\\mo_tf.py" --input_model model_example.pb -b 1 --data_type FP16

I'm using Keras with TF as the backend and saving as PB. The simplified model having issues is only a few lines though:

xin_cam_one = Input(shape=(9, 50, 50, 3), name='input_cam_one')
flt = Flatten()(xin_cam_one)
x = Dense(128, activation='relu')(flt)
angle_output = Dense(1, name='angle_output')(x)

model = Model(inputs=[xin_cam_one], outputs=[angle_output])
learning_rate = 0.001
decay_rate = learning_rate / 32
optimizer = Adam(lr=learning_rate, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=decay_rate)
model.compile(loss='mean_squared_error', optimizer=optimizer)

**Comment by shubha-ramani** [comment]
Dear @chloroaqua 
If you can provide your email address I will provide a way for you to send me your model through Syncplicity. let me know if you want to do this.

Thanks,

Shubha

**Comment by chloroaqua** [comment]
Sure thing: fbicamera@outlook.com

**Comment by chloroaqua** [comment]
Data added on Syncplicity

**Comment by chloroaqua** [comment]
I downloaded the new version today. I still get an error, but it's different one (let me know if you want me to open a new issue).

  File "ie_api.pyx", line 547, in openvino.inference_engine.ie_api.IEPlugin.load
  File "ie_api.pyx", line 557, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: AssertionFailed: newDims[newPerm[i]] == 1


I've attached the data as a zip file.

[model_new.zip](https://github.com/opencv/dldt/files/3681850/model_new.zip)

**Comment by shubha-ramani** [comment]
Dear @chloroaqua 
OK so you re-tried on 2019R3 already ? Thanks for doing that. And also, thanks for attaching your *.zip. Promise to take a look shortly.

Thanks for your patience !

Shubha

**Comment by chloroaqua** [comment]
Yep, got the email this morning and upgraded. No problem!

**Comment by shubha-ramani** [comment]
Dear @chloroaqua 
I didn't get your *.py script which produces the error - it's not in your *.zip. Can you kindly attach it also ? 
I was able to generate IR from your frozen pb (found in the above *.zip).

Thanks !

Shubha

**Comment by chloroaqua** [comment]
Sure thing. Added to the zip.
[model_new.zip](https://github.com/opencv/dldt/files/3683456/model_new.zip)

**Comment by shubha-ramani** [comment]
Dear @chloroaqua 
You gave me the wrong *.py. I'm looking for the specific script which caused this error :

> File "ie_api.pyx", line 547, in openvino.inference_engine.ie_api.IEPlugin.load
File "ie_api.pyx", line 557, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: AssertionFailed: newDims[newPerm[i]] == 1

You actually gave me model_tester_v2.py which is your Keras/TF Freezing script.

Thanks,

Shubha

**Comment by chloroaqua** [comment]
Sure thing. I've attached the zip again with the added file that causes the error (model_tester_intel.py on line 72). It's a copy of one of the example scripts to load something onto the neural compute stick.

[model_new.zip](https://github.com/opencv/dldt/files/3688241/model_new.zip)

**Comment by shubha-ramani** [comment]
Dear @chloroaqua 
4-dimensional models should be supported by MYRIAD. But looking at your model I noticed that you are using MatMul. Tensorflow (and therefor Keras) MatMul will not be supported until 2019R4. So actually, the MatMul in your model may be causing issues, not the fact that your model is 4-dimensions. 

Please see this github issue for more info:
[https://github.com/opencv/dldt/issues/80](https://github.com/opencv/dldt/issues/80)

Hope it helps,

Thanks,

Shubha

**Comment by chloroaqua** [comment]
Awesome, I think we're getting close. Attached is the same model, but only with three dimensions. I see in the XML MatMul, but there is no loading error. As a side note, when is the expected release of 2019R4?

[model_new_2.zip](https://github.com/opencv/dldt/files/3708078/model_new_2.zip)

**Comment by shubha-ramani** [comment]
Dear @chloroaqua 
Hello and thank you for your new *.zip (I will definitely take a look) ! R4 will happen toward the end of the year or maybe January-ish (next year).

Shubha
