### ISSUE TITLE
[Good First Issue][JAX FE]: Support jax.lax.select_n operation for JAX

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#26570]
### Context

OpenVINO component responsible for support of JAX/Flax models is called as JAX Frontend (JAX FE). JAX FE converts a JAX/Flax model represented by `ClosedJAXpr` graph object with operations from [jax.lax opset](https://jax.readthedocs.io/en/latest/jax.lax.html) to OpenVINO IR containing operations from [OpenVINO opset](https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/available-opsets/opset14.html).

In order to infer JAX/Flax models containing [jax.lax.select_n](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.select_n.html) operation by OpenVINO, JAX FE needs to be extended with this operation support.

### What needs to be done?

For [ jax.lax.select_n](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.select_n.html) operation support, you need to implement the corresponding loader into JAX FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/jax/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/jax/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of JAX operation.

Here is an example of loader implementation for [jax.lax.reshape](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.reshape.html) operation:

```cpp
OutputVector translate_reshape(const NodeContext& context) {
    num_inputs_check(context, 1, 1);
    Output<Node> input = context.get_input(0);
    auto new_sizes = context.const_named_param<std::vector<int64_t>>("new_sizes");
    if (context.has_param("dimensions")) {
        auto dimensions = context.const_named_param<std::vector<int64_t>>("dimensions");
        // transpose the input first.
        auto permutation_node = std::make_shared<v0::Constant>(element::i64, Shape{dimensions.size()}, dimensions);
        input = std::make_shared<v1::Transpose>(input, permutation_node);
    }

    auto new_shape_node = std::make_shared<v0::Constant>(element::i64, Shape{new_sizes.size()}, new_sizes);
    Output<Node> res = std::make_shared<v1::Reshape>(input, new_shape_node, false);
    return {res};
};
```

In this example, `translate_reshape` expresses `jax.lax.reshape` using OpenVINO opset. Since `jax.lax.reshape` performs transposition and tensor reshaping according to JAX documentation, the resulted decomposition contains OpenVINO `Transpose`  and `Reshape` operations. For `Transpose` and `Reshape` nodes, this conversion parses constant parameters `dimensions` to permute input tensor and `new_size` that is the target shape of the result.

Once you are done with implementation of the translator, you need to implement the corresponding layer tests `test_select_n.py` and put it into [layer_tests/jax_tests](https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/jax_tests) directory. Example how to run some layer test:

```
export TEST_DEVICE=CPU
export JAX_TRACE_MODE=JAXPR
export 
cd openvino/tests/layer_tests/jax_tests
pytest test_reshape.py
```

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/26288
- https://github.com/openvinotoolkit/openvino/pull/26254

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

- @openvinotoolkit/openvino-jax-frontend-maintainers 
- @rkazants in GitHub and Discord

**Comment by gagankonana** [comment]
would like to take this up!

**Comment by rkazants** [comment]
@gagankonana, the task is yours

**Comment by mlukasze** [comment]
hey @gagankonana - do you need any support or you will have no time to finish the task?

**Comment by gagankonana** [comment]
HI @mlukasze, I did start working on it but got sidetracked. I will get back to it this weekend and have an update by then.

**Comment by mlukasze** [comment]
sure, please leave any update you will have, we completely understand you may not have a time, I'm only trying to keep tickets up to date :)

**Comment by gagankonana** [comment]
Hi @mlukasze, I am having a hard time allocating some time to finish the task. Sorry about that. I’ll unassign myself for now, and I hope to pick up another issue when I have more availability.

**Comment by mlukasze** [comment]
no worries, thanks for your time!

**Comment by 11happy** [comment]
Hello @rkazants, @mlukasze  I am interested to work on this can you please assign this to me.
Thank you

**Comment by 11happy** [comment]
I have linked my PR,also while going thorugh the documentation I found these two typos should I open an issue or make a correction?. https://docs.openvino.ai/2024/documentation/openvino-extensibility.html
<img width="452" alt="image" src="https://github.com/user-attachments/assets/46631d03-ae63-4ac4-9d7d-ef012141d771" />

**Comment by rkazants** [comment]
> I have linked my PR,also while going thorugh the documentation I found these two typos should I open an issue or make a correction?. https://docs.openvino.ai/2024/documentation/openvino-extensibility.html <img alt="image" width="452" src="https://private-user-images.githubusercontent.com/76656712/394879530-46631d03-ae63-4ac4-9d7d-ef012141d771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NDM3MTEsIm5iZiI6MTczMzk0MzQxMSwicGF0aCI6Ii83NjY1NjcxMi8zOTQ4Nzk1MzAtNDY2MzFkMDMtYWU2My00YWM0LTlkN2QtZWYwMTIxNDFkNzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDE4NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZGU2MjBhMjhmYThlMTM4MmExYzY3NGU2YmVjZWM2MjUyMjFhM2FmYzQyMGE1ZWQwMTIxYjBlNDFmZWUxZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.--jnGIj-OrqkJ6YvDp2yUSZo3NbAvVlp1zhMAWin3ec">

please open up separate PR because it is independent topic.
