### ISSUE TITLE
[Good First Issue][JAX FE]: Support jax.lax.lt and jax.lax.neg operation for JAX

### ISSUE THREAD

**Issue by rkazants** [openvinotoolkit/openvino#26577]
### Context

OpenVINO component responsible for support of JAX/Flax models is called as JAX Frontend (JAX FE). JAX FE converts a JAX/Flax model represented by `ClosedJAXpr` graph object with operations from [jax.lax opset](https://jax.readthedocs.io/en/latest/jax.lax.html) to OpenVINO IR containing operations from [OpenVINO opset](https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/available-opsets/opset14.html).

In order to infer JAX/Flax models containing [jax.lax.lt](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.lt.html) operation by OpenVINO, JAX FE needs to be extended with this operation support.

### What needs to be done?

For [jax.lax.lt](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.lt.html) operation support, you need to implement the corresponding loader into JAX FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/jax/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/jax/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of JAX operation.

Here is an example of loader implementation for [jax.lax.reshape](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.reshape.html) operation:

```cpp
OutputVector translate_reshape(const NodeContext& context) {
    num_inputs_check(context, 1, 1);
    Output<Node> input = context.get_input(0);
    auto new_sizes = context.const_named_param<std::vector<int64_t>>("new_sizes");
    if (context.has_param("dimensions")) {
        auto dimensions = context.const_named_param<std::vector<int64_t>>("dimensions");
        // transpose the input first.
        auto permutation_node = std::make_shared<v0::Constant>(element::i64, Shape{dimensions.size()}, dimensions);
        input = std::make_shared<v1::Transpose>(input, permutation_node);
    }

    auto new_shape_node = std::make_shared<v0::Constant>(element::i64, Shape{new_sizes.size()}, new_sizes);
    Output<Node> res = std::make_shared<v1::Reshape>(input, new_shape_node, false);
    return {res};
};
```

In this example, `translate_reshape` expresses `jax.lax.reshape` using OpenVINO opset. Since `jax.lax.reshape` performs transposition and tensor reshaping according to JAX documentation, the resulted decomposition contains OpenVINO `Transpose`  and `Reshape` operations. For `Transpose` and `Reshape` nodes, this conversion parses constant parameters `dimensions` to permute input tensor and `new_size` that is the target shape of the result.

Once you are done with implementation of the translator, you need to implement the corresponding layer tests `test_lt.py` and put it into [layer_tests/jax_tests](https://github.com/openvinotoolkit/openvino/tree/master/tests/layer_tests/jax_tests) directory. Example how to run some layer test:

```
export TEST_DEVICE=CPU
export JAX_TRACE_MODE=JAXPR
export 
cd openvino/tests/layer_tests/jax_tests
pytest test_reshape.py
```

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/26288
- https://github.com/openvinotoolkit/openvino/pull/26254

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

- @openvinotoolkit/openvino-jax-frontend-maintainers 
- @rkazants in GitHub and Discord

**Comment by aku221b** [comment]
.take
I would like to work on this!

**Comment by aku221b** [comment]
@rkazants after building,  running `pytest test_reshape.py` is causing some testcases to fail. 

`self = <test_reshape.TestReshapeWithDimensions object at 0x11fce56d0>
model = <function TestReshapeWithDimensions.create_model.<locals>.jax_reshape_with_dimensions at 0x1609fd760>, ref_net = None
kind = 'reshape', ie_device = 'CPU', precision = 'FP32', ir_version = 11, infer_timeout = 60, dynamic_shapes = True, kwargs = {}
inputs = [Array([[[0.8054124 , 0.55377144],
        [0.05172348, 0.3188859 ]],

       [[0.3447107 , 0.27374998],
        [0.14...      [0.69242996, 0.31861413]],

       [[0.23660219, 0.2276755 ],
        [0.2721476 , 0.80212355]]], dtype=float32)]
converted_model = <Model: 'Model795'
inputs[
<ConstOutput: names[jaxpr_invar_0] shape[16,2,2] type: f32>
]
outputs[
<ConstOutput: names[jaxpr_outvar_0] shape[2,4,2,2,2] type: f32>
]>
jaxpr = { lambda ; a:f32[16,2,2]. let
    b:f32[2,4,2,2,2] = reshape[dimensions=(2, 1, 0) new_sizes=(2, 4, 2, 2, 2)] a
  in (b,) }
core = <Core: available plugins[CPU]>
compiled = <CompiledModel:
inputs[
<ConstOutput: names[jaxpr_invar_0] shape[16,2,2] type: f32>
]
outputs[
<ConstOutput: names[jaxpr_outvar_0] shape[2,4,2,2,2] type: f32>
]>
infer_res = {<ConstOutput: names[jaxpr_outvar_0] shape[2,4,2,2,2] type: f32>: array([[[[[0.8051758 , 0.34472656],
          [0.764...[0.6171875 , 0.76904297]],

         [[0.75      , 0.81347656],
          [0.31860352, 0.8022461 ]]]]], dtype=float32)}
fw_res = (Array([[[[[0.8054124 , 0.3447107 ],
          [0.76399314, 0.44476834]],

         [[0.34610146, 0.5069819 ],
       ...0.6174102 , 0.7688001 ]],

         [[0.74989253, 0.8132805 ],
          [0.31861413, 0.80212355]]]]], dtype=float32),)

    def _test(self, model, ref_net, kind, ie_device, precision, ir_version, infer_timeout=60, dynamic_shapes=True,
              **kwargs):
        """
        :param enabled_transforms/disabled_transforms: string with idxs of transforms that should be enabled/disabled.
                                                       Example: "transform_1,transform_2"
        """
        inputs = self._prepare_input()
        if self.use_jaxpr_tracing():
            converted_model, jaxpr = self.convert_via_jaxpr(model, inputs)
            # check that expected operation presents in a graph
            if kind is not None:
                assert self._check_kind_exist(jaxpr, kind), '{} operation does not present in a graph'.format(kind)
        else:
            converted_model = self.convert_via_tensorflow_function(model, inputs)
    
        # OV infer:
        core = Core()
        compiled = core.compile_model(converted_model, ie_device)
        infer_res = compiled(deepcopy(inputs))
    
        # Framework infer:
        fw_res = model(*deepcopy(inputs))
    
        if not isinstance(fw_res, (tuple)):
            fw_res = (fw_res,)
    
        output_list = ov_res_to_list(infer_res)
    
        def flattenize_dict_outputs(res):
            if isinstance(res, dict):
                return flattenize_outputs(res.values())
    
        def flattenize_outputs(res):
            results = []
            for res_item in res:
                # if None is at output we skip it
                if res_item is None:
                    continue
                # If input is list or tuple flattenize it
                if isinstance(res_item, (list, tuple)):
                    decomposed_res = flattenize_outputs(res_item)
                    results.extend(decomposed_res)
                    continue
                if isinstance(res_item, dict):
                    decomposed_res = flattenize_dict_outputs(res_item)
                    results.extend(decomposed_res)
                    continue
                results.append(res_item)
            return results
    
        flatten_fw_res = flattenize_outputs(fw_res)
    
        assert len(flatten_fw_res) == len(
            output_list), f'number of outputs not equal, {len(flatten_fw_res)} != {len(output_list)}'
        # check if results dtypes match
        for fw_tensor, ov_tensor in zip(flatten_fw_res, output_list):
            fw_tensor_type = np.array(fw_tensor).dtype
            ov_tensor_type = ov_tensor.dtype
            assert ov_tensor_type == fw_tensor_type, f"dtype validation failed: {ov_tensor_type} != {fw_tensor_type}"
    
        if 'custom_eps' in kwargs and kwargs['custom_eps'] is not None:
            custom_eps = kwargs['custom_eps']
        else:
            custom_eps = 1e-4
    
        # compare OpenVINO results with JAX results
        fw_eps = custom_eps if precision == 'FP32' else 5e-2
        is_ok = True
        for i in range(len(flatten_fw_res)):
            cur_fw_res = np.array(flatten_fw_res[i])
            cur_ov_res = infer_res[compiled.output(i)]
            print(f"fw_re: {cur_fw_res};\n ov_res: {cur_ov_res}")
            if not np.allclose(cur_ov_res, cur_fw_res,
                               atol=fw_eps,
                               rtol=fw_eps, equal_nan=True):
                is_ok = False
                print("Max diff is {}".format(
                    np.array(
                        abs(cur_ov_res - cur_fw_res)).max()))
            else:
                print("Accuracy validation successful!\n")
                print("absolute eps: {}, relative eps: {}".format(fw_eps, fw_eps))
>       assert is_ok, "Accuracy validation failed"
E       AssertionError: Accuracy validation failed

jax_layer_test_class.py:111: AssertionError
-------------------------------------------------------- Captured stdout call --------------------------------------------------------
fw_re: [[[[[0.8054124  0.3447107 ]
    [0.76399314 0.44476834]]

   [[0.34610146 0.5069819 ]
    [0.11804432 0.7345962 ]]]


  [[[0.2418952  0.7409584 ]
    [0.89076895 0.6199153 ]]

   [[0.81347024 0.37722892]
    [0.57778764 0.23660219]]]


  [[[0.05172348 0.14655651]
    [0.24883513 0.9700344 ]]

   [[0.51335037 0.5993138 ]
    [0.32928634 0.9670116 ]]]


  [[[0.33809486 0.7044292 ]
    [0.11421409 0.9522909 ]]

   [[0.28843316 0.44503054]
    [0.69242996 0.2721476 ]]]]



 [[[[0.55377144 0.27374998]
    [0.534359   0.8691551 ]]

   [[0.3535344  0.10807244]
    [0.36357433 0.5109851 ]]]


  [[[0.28853622 0.9381393 ]
    [0.41878104 0.24664299]]

   [[0.15035032 0.7435074 ]
    [0.96173537 0.2276755 ]]]


  [[[0.3188859  0.7332105 ]
    [0.77982676 0.89989406]]

   [[0.5186375  0.00590186]
    [0.22407565 0.9664396 ]]]


  [[[0.51532084 0.33258602]
    [0.6174102  0.7688001 ]]

   [[0.74989253 0.8132805 ]
    [0.31861413 0.80212355]]]]];
 ov_res: [[[[[0.8051758  0.34472656]
    [0.76416016 0.44482422]]

   [[0.3461914  0.50683594]
    [0.11804199 0.734375  ]]]


  [[[0.24194336 0.74072266]
    [0.890625   0.6201172 ]]

   [[0.81347656 0.37719727]
    [0.5776367  0.23657227]]]


  [[[0.05172729 0.14660645]
    [0.2487793  0.97021484]]

   [[0.5131836  0.5991211 ]
    [0.3293457  0.9667969 ]]]


  [[[0.33813477 0.70458984]
    [0.11419678 0.95214844]]

   [[0.28833008 0.44506836]
    [0.6923828  0.2722168 ]]]]



 [[[[0.55371094 0.27368164]
    [0.5341797  0.8691406 ]]

   [[0.35351562 0.10809326]
    [0.3635254  0.5107422 ]]]


  [[[0.28857422 0.9379883 ]
    [0.41870117 0.24658203]]

   [[0.15039062 0.74365234]
    [0.96191406 0.22766113]]]


  [[[0.31884766 0.73339844]
    [0.77978516 0.89990234]]

   [[0.5185547  0.00590134]
    [0.2241211  0.9663086 ]]]


  [[[0.5151367  0.33251953]
    [0.6171875  0.76904297]]

   [[0.75       0.81347656]
    [0.31860352 0.8022461 ]]]]]
Max diff is 0.0002428889274597168`
================================================== 236 failed, 240 passed in 20.81s ==================================================

**Comment by hub-bla** [comment]
Hi @aku221b, there's a PR that just got merged and you might find it helpful ;)
#26719

**Comment by aku221b** [comment]
Thanks @hub-bla, will look into it.

**Comment by aku221b** [comment]
@rkazants Please review PR [ #26771  ](https://github.com/openvinotoolkit/openvino/pull/26771) for this issue.

**Comment by aku221b** [comment]
@rkazants By mistake I made commits with the wrong email😅, and its becoming tricky to find some commits and reset the email. Shall I raise a fresh PR with the latest code? Sorry for the unnecessary trouble.
