### ISSUE TITLE
reading network error: cannot parse future versions:6

### ISSUE THREAD

**Issue by lihengMo** [openvinotoolkit/openvino#266]
Here i followed the instruction from here [https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html) and created the yolo bin and xml file with the latest dldt. And i use the _l_openvino_toolkit_raspbi_p_2019.1.144.tgz_ to set up the raspberry pi openvino environment and built the  object_detection_demo_yolov3_async. but when i use it to load the xml file, it raised the reading network error below:
`./armv7l/Release/object_detection_demo_yolov3_async -m /home/pi/bo_openvino/tiny_yolov3.xml -d MYRIAD -i /home/pi/bo_openvino/testv.mp4`

 `InferenceEngine:
        API version ............ 1.6
        Build .................. 23780
[ INFO ] Parsing input parameters
[ INFO ] Reading input
[ INFO ] Loading plugin
        API version ............ 1.6
        Build .................. 23780
        Description ....... myriadPlugin
[ INFO ] Loading network files
[ ERROR ] Error reading network: cannot parse future versions: 6`

Is it because the version of openvino toolkit on raspbeery pi that i used did not match the dldt?
How can i solve this problem ? 
thank you.

**Comment by shubha-ramani** [comment]
Dear @lihengMo 

You asked:

> Is it because the version of openvino toolkit on raspbeery pi that i used did not match the dldt?

Yes you hit the nail on the head @lihengMo . For best results, always generate IR and use Core Inference Engine API using the same exact release. If you regenerate your IR using Model Optimizer from Raspberry PI, then you must also use IE from Raspberry PI.

Hope it helps,

Thanks,

Shubha

**Comment by lihengMo** [comment]
Thank you for your reply shubha.
So it means that if i use the model-optimizer in dldt to generate the IR files, it must also use the inference_engine in the dldt to run the network? Because i also tried using the _l_openvino_toolkit_p_2019.1.133_  to generate the IR files and can be analyzed on the raspberry pi with _l_openvino_toolkit_raspbi_p_2019.1.144_ . 
And by the way, if i use the dldt inference_engine, should i need to compile the ie_api by myself ? Since i can find the _ie_api.so_ under armv7l in _l_openvino_toolkit_raspbi_p_2019.1.144_, but i just find the _ie_api.cpp_ in the dldt.

Thanks

**Comment by shubha-ramani** [comment]
Dear @lihengMo 
Yes you have to use the same release/package to generate IR via Model Optimizer and write code as well, using Inference Engine Core API. You cannot mix and match MO and IE versions.

And to your question:

> And by the way, if i use the dldt inference_engine, should i need to compile the ie_api by myself ? Since i can find the ie_api.so under armv7l in l_openvino_toolkit_raspbi_p_2019.1.144, but i just find the ie_api_impl.cpp in the dldt.

Yes you must build Inference Engine from scratch in dldt using [this readme](https://github.com/opencv/dldt/blob/2019/inference-engine/README.md)

Hope it helps.

Thanks,

Shubha
