### ISSUE TITLE
Stable Diffusion V3 Generates Blurry Images in GPU Mode

### ISSUE THREAD

**Issue by cheahber** [openvinotoolkit/openvino#26608]
**Describe the bug**
Stable Diffusion V3 in GPU mode always generates pictures that are blurry, regardless of the input or settings, making them unsuitable for use in the intended application. 

Steps to reproduce the issue:

1. Execute the Jupyter Notebook titled 'stable-diffusion-v3.ipynb' located in the 'openvino_notebooks/notebooks/stable-diffusion-v3' directory.
2. Utilize the **flash SD3 feature**, **bypassing the use of the t5 text encoder**, with the **GPU set as the processing device.**
3. Initialize the Stable Diffusion V3 model.
4. Continue execution up to the point where the "Run OpenVINO model" section produces an image.

![image](https://github.com/user-attachments/assets/dfee7d2b-d4ab-4899-a6a5-1d3ee0a3fbbf)

 **Expected behavior**
The generated images in GPU mode should be sharp and clear, comparable to those generated in CPU or AUTO mode.

**Screenshots**

![image](https://github.com/user-attachments/assets/4162a2d4-987d-4129-bbfc-1a86910863fa)

_What I have done:_ Adjusting "num_inference_steps", "guidance_scale", and the resolution to (1024, 1024) randomly has not resulted in any notable impact.

 **Installation instructions (Please mark the checkbox)**
- [x] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

**Environment information**

- CPU - Intel® Core™ i7-7700K CPU
- GPU - Mesa Intel® Arc(tm) A770 Graphics (DG2)

 
**Additional context**
- N/A

**Comment by avitial** [comment]
Ref. 152556

**Comment by dnkurek** [comment]
Issue was reproduced in 2024.3 for me, but it doesn't reproduce in openvino-nightly

Looks like issue is already solved in newer version

**Comment by dnkurek** [comment]
Also, the image is not "blurry". It's outputting wrong values.

**Comment by dnkurek** [comment]
Issue was not reproduced in OV 2024.4

**Comment by dnkurek** [comment]
Since issue is already solved in a newer version, we may close issue
