### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zvif** [openvinotoolkit/openvino#2664]
##### System information (version)

- OpenVINO => 2020.4 + 2021.1.110
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
-Using multi_camera_multi_target_tracking demo
-->

##### Detailed description
When the CPU is fully utilized the program crashes.
Message: 
Exception in Thread-1
MemoryError:Unable to allocate 5.93 MiB for an array with shape (1080,1920,3) and data type uint8
The above exception was the direct cause of the following exception:
File "..Shared\Python37_64\lib\threading.py", line 926 in bootstrap_inner
self.run()
..
..\utils\video.py in get_frames
has_frame,frame = capture.read()
systemError: <method 'read' of 'cv2.VideoCapture' objects> returned a result with an error set

We have found this to happen when there are other programs running at the same time or on a weaker cpu (but that satisfies the OpenVino requirements).

**Comment by jgespino** [comment]
Hi @zvif 

Please provide the following information to help us reproduce. 

- CPU model
- CMake version
- Python version
- full demo command

Regards,
Jesus

**Comment by alalek** [comment]
> MemoryError:Unable to allocate 5.93 MiB for an array with shape (1080,1920,3) and data type uint8

Please check memory consumption.
Probably queues for input frames are full and consumed all available memory.

**Comment by zvif** [comment]
This happens when I am running and I open a different application. Since this is running on recorded clips (not live) - is it possible to check the memory and wait till the queue clears before trying to load a new frame? Even though the queue get's filled up - there should be a way to gracefully handle this (not to cause and exception). This can always be a problem since it is difficult to predict video size/number of people in clip etc that all contribute to the memory usage.

**Comment by jgespino** [comment]
Hi @zvif 

Could you please check if the issue is still present in OpenVINO 2021.2 release?

Regards,
Jesus

**Comment by zvif** [comment]
Sure

**Comment by jgespino** [comment]
Hi @zvif 

Please let me know if you had a chance to test on the latest release.

Regards,
Jesus

**Comment by zvif** [comment]
I think it is dependent on the media processing backend (ffmpeg/GStreamer/MSMF ..) and maybe also the codecs. The problem occurred with the default backend when running Windows. Since then I have switched to ffmpeg (found it to be fastest and consistent cross-platform). I am working on the latest version  with ffmpeg (Windows + Linux) and haven't seen this happen (but I am not testing this across the different backends / codecs).
