### ISSUE TITLE
[Bug] 2020.1 build is broken

### ISSUE THREAD

**Issue by eero-t** [openvinotoolkit/openvino#2665]
##### System information (version)

* Ubuntu 20.04 (container)
* libdrm, libva, gmmlib, media-driver, vc-intrinsics, IGT, L0, compute-runtime and opencv built from today's latest Git tags
* OpenVINO sources from "2021.1" Git tag

##### Detailed description

Buliding OpenVINO "2020.1" fails.

##### Steps to reproduce

```
$ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release \
      -DENABLE_OPENCV=OFF -DENABLE_CLDNN=ON \
      -DENABLE_MYRIAD=OFF -DENABLE_VPU=OFF \
      -DENABLE_GNA=OFF -DENABLE_PROFILING_ITT=OFF
$ ninja
```
Fails with following error:
```
-- [clDNN] =============================================================================
CMake Error at inference-engine/thirdparty/CMakeLists.txt:60 (add_subdirectory):
  The source directory

    /home/nobody/source/openvino/inference-engine/thirdparty/ade

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  inference-engine/thirdparty/CMakeLists.txt:82 (build_with_lto)


CMake Error at inference-engine/samples/CMakeLists.txt:126 (add_subdirectory):
  The source directory

    /home/nobody/source/openvino/inference-engine/samples/thirdparty/gflags

  does not contain a CMakeLists.txt file.


CMake Error at inference-engine/samples/CMakeLists.txt:127 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  gflags_nothreads_static
```

Changing "ENABLE_LTO" to ON or OFF doesn't affect first error.

Changing "ENABLE_SAMPLES" to ON or OFF doesn't affect the second error.

**Comment by eero-t** [comment]
This is fixed by initializing submodules.  CMake could have a check for whether the submodule directories have some content (e.g. the CMakeLists.txt files), and if not, complain that user had forgotten to init submodules.

**Comment by jgespino** [comment]
Hi @eero-t 

As you mentioned, the submodules need to be initialized after cloning the repository. Glad you were able to solve the issue quickly.
I will pass this feedback to the development team. 

Regards,
Jesus

**Comment by eero-t** [comment]
Another issue is "secretly" doing git clones during the build (e.g. for ONNX).  Like with "wget", there should be some indication when build goes outside the machine.  It should also use checksums to verify that the sources it fetches are actually what they were supposed to be.
