### ISSUE TITLE
setup.py for python*/openvino/tools module

### ISSUE THREAD

**Issue by js333031** [openvinotoolkit/openvino#2705]
In the Intel Distribution of OpenVINO Toolkit, `$INTEL_OPENVINO_DIR/python/python<ver>/openvino/tools` containing benchmark python module is present.

Is there a setup.py file for creating the python package when compiling openvino from source? ngraph provides the instructions [here](https://github.com/openvinotoolkit/openvino/blob/master/ngraph/python/BUILDING.md). Looking for similar methodology for benchmark module.

**Comment by luoyiroy** [comment]
Hi @js333031 
We have no setup.py for benchmark_app. To use benchmark_app you need OpenVINO itself. So you have to build this module from the sources. After building it from the source, then set the python path to the build with 'export PYTHONPATH=<openvino_repo>/bin/intel64/Release/lib/python_api/python3.x', and then using it as 'python <openivno_repo>/inference-engine/tools/benchmark_tool/benchmark_app.py'

**Comment by js333031** [comment]
I have compiled from source (on ArchLinux) and compared it against Intel distribution install (on Ubuntu). Ubuntu has tools module under Python directory but it is not installed on Arch Linux where I built from source.

Ubuntu (Intel distribution install):
```
user@user-Virtual-Machine:/opt/intel/openvino_2021/python/python3.8$ tree openvino/ -d
openvino/
├── inference_engine
└── tools
    └── benchmark
        └── utils

4 directories
user@user-Virtual-Machine:/opt/intel/openvino_2021/python/python3.8$
```

```

ArchLinux (Compiled from source):
[user@archlinux python3.8]$ tree -d openvino
openvino
├── inference_engine
│   └── __pycache__
└── __pycache__

3 directories
[user@archlinux python3.8]$
```

**Comment by luoyiroy** [comment]
This source code of benchmark is not generated by compiled, it is directly from the git clone. Could you have a check to make sure you have cloned the source code to your ArchLinux locally?

**Comment by js333031** [comment]
I have and the code is present. Currently, after the openvino` make install` step, I'm manually copying the benchmark to install location as follows:
```
  # for benchmark tools python module
  if [ -d ${OV_SRC_DIR}/bin/intel64/Release/lib/python_api ]; then
    cd ${OV_SRC_DIR}/bin/intel64/Release/lib/python_api
    cp -vr . ${PRJ_INSTALL}/python
    cd -
  else
    echo "No bin/intel64/Release/lib/python_api in `pwd`"
  fi
```

**Comment by luoyiroy** [comment]
Hi @js333031 
After you have manually copied the benchmark code to the install location, can your problem be solved?

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
