### ISSUE TITLE
[Good First Issue]: Expose ov.saveModel() functionality

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#27092]
### Context

OpenVINO works in Node.js environment!
We are looking for new contributors who can help with enabling C++ API methods 
in JavaScript side.

First of all read Node.js API [Contribution Guide](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/CONTRIBUTING.md).

#### Task Details

Expose `ov::save_model()` method. 
From JavaScript side it will be `ov.saveModel()` method.
This method takes 3 arguments: model to save, path to output model file and bool value whether to compress floating point weights to FP16.

#### Useful links

- C++ API [implementation](https://github.com/openvinotoolkit/openvino/blob/master/src/core/src/graph_util.cpp#L334) of `ov::save_model()` method

### What needs to be done?

 - Propose the place where the `ov.saveModel()` method should be implemented. It might be 
[./src/bindings/js/node/src/addon.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/src/addon.cpp). Implement the method. 
-  Test manually if the functionality is working with different models. Describe in the PR what models were tested in which formats.
- Update TypeScript definitions in [./src/bindings/js/node/lib/addon.ts](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/lib/addon.ts)
- Create unit test for added functionality using Node.js Test Runner. The logic might be similar to the Python tests for this functionality. [Link to Python API tests](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_transformations/test_offline_api.py#L219)

### How to take this issue

To take this issue leave text: `.take` as the comment in this issue.
It will assign this issue to you automatically. Please, make sure that the issue has the status **Contributors Needed** and doesn't have another user in Assingnees.

### Example Pull Requests

 - https://github.com/openvinotoolkit/openvino/pull/23743
 - https://github.com/openvinotoolkit/openvino/pull/24023

### Resources

- [[NEW] Contribution Guide](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/CONTRIBUTING.md)
- [JavaScript API Developer Documentation](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/docs/README.md#openvino-node-package-developer-documentation)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai 

Please, mention us in this issue discussion if you have any questions.

**Comment by hub-bla** [comment]
.take

**Comment by MVARUNREDDY8203** [comment]
.take

**Comment by MVARUNREDDY8203** [comment]
@hub-bla are you still working on the issue?

**Comment by hub-bla** [comment]
@MVARUNREDDY8203 It's already done but not merged yet.

**Comment by almilosz** [comment]
Merged. Thanks for contribution!
