### ISSUE TITLE
RuntimeError when loading the network to the MYRIAD plugin

### ISSUE THREAD

**Issue by cocokale** [openvinotoolkit/openvino#2713]
OpenVINO: latest master branch
OS: Ubuntu 18.04.5
Some other models works well on MYRIAD (mainly convolutional and fully connected layers.)
Reference issue:
https://github.com/openvinotoolkit/openvino/issues/2476

The current model is the same as the [2476](https://github.com/openvinotoolkit/openvino/issues/2476). There were RuntimeErrors both on the GPU plugin and MYRIAD plugin. Thanks for @vladimir-paramuzov 's help, after I built the latest master branch, the GPU one disappeared.

However, the MYRIAD plugin RuntimeError still exists:
` exec_net = ie.load_network(network=net, device_name=args.device)
  File "ie_api.pyx", line 311, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 320, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: [Internal Error]: Allocation check failed: data actual_input5@FP16 with usage Intermediate must have at least one data/stage depending on it, but it doesn't have either`

Looking forward to some help, many thanks!

**Comment by jgespino** [comment]
Hi  @cocokale 

I tried loading the model you shared via email to CPU/GPU and MYRIAD. I am able to load the model to CPU and GPU, however, I am running into a different error when loading to MYRIAD. Do you know the commit ID of the master branch you used? I am currently rebuilding with the latest ([ff7fc01](https://github.com/openvinotoolkit/openvino/commit/ff7fc01c7614b5b50442410b9dbd4f66d22fbd47)) as I am using an older build from last week.

```
  File "load.py", line 11, in <module>
    exec_net = ie.load_network(network = net, device_name = "MYRIAD")
  File "ie_api.pyx", line 311, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 320, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Cast_1316 of type Convert: [Internal Error]: Final check for stage Cast_1316 with type Convert has failed: Conversion from FP16 to U8 is unsupported
```

Regards,
Jesus

**Comment by cocokale** [comment]
> Hi @cocokale
> 
> I tried loading the model you shared via email to CPU/GPU and MYRIAD. I am able to load the model to CPU and GPU, however, I am running into a different error when loading to MYRIAD. Do you know the commit ID of the master branch you used? I am currently rebuilding with the latest ([ff7fc01](https://github.com/openvinotoolkit/openvino/commit/ff7fc01c7614b5b50442410b9dbd4f66d22fbd47)) as I am using an older build from last week.
> 
> ```
>   File "load.py", line 11, in <module>
>     exec_net = ie.load_network(network = net, device_name = "MYRIAD")
>   File "ie_api.pyx", line 311, in openvino.inference_engine.ie_api.IECore.load_network
>   File "ie_api.pyx", line 320, in openvino.inference_engine.ie_api.IECore.load_network
> RuntimeError: Cast_1316 of type Convert: [Internal Error]: Final check for stage Cast_1316 with type Convert has failed: Conversion from FP16 to U8 is unsupported
> ```
> 
> Regards,
> Jesus

Hi Jesus,
Thanks for your kind reply.
Previously, I actually got the same error as you, and the IR I shared with you before was generated by the model optimizer of the OpenVINO **2020.4** Release.
This current error was triggered by the IRs generated from the model optimize of the OpenVINO **2021.1** Release (which means, they come from the same ONNX, but different version of model optimizer).
I'll send you the link to the latest IR in both FP16 and FP32 format (generated by OpenVINO 2021.1 Release MO. )

Best regards

**Comment by jgespino** [comment]
Thanks @cocokale for sending the new IRs over. I am seeing the same error as your post with fp32.xml, however, fp16.xml is still throwing the `Final check for stage Cast_1316 with type Convert has failed: Conversion from FP16 to U8 is unsupported` error. Could you confirm fp16.xml was also converted with 2021.1?

**Comment by cocokale** [comment]
> Thanks @cocokale for sending the new IRs over. I am seeing the same error as your post with fp32.xml, however, fp16.xml is still throwing the `Final check for stage Cast_1316 with type Convert has failed: Conversion from FP16 to U8 is unsupported` error. Could you confirm fp16.xml was also converted with 2021.1?

Hi Jesus,

I checked again. Sorry, FP16 was a mistake. I've sent you the latest link. Please replace the old FP16 IR with the new one. Thanks.

**Comment by jgespino** [comment]
Hi @cocokale thanks for sending the model over, I was able to reproduce the same error with fp16.xml. Let me check with my peers  about this and get back to you.

**Comment by luoyiroy** [comment]
Hi @cocokale 
Can you send out the IR file to me? Thank you.

**Comment by jgespino** [comment]
Hi @cocokale 

Do you still need assistance? Please try the latest OpenVINO toolkit 2021.2 release and let us know if the issue is still present.

Regards,
Jesus
