### ISSUE TITLE
[Bug] Inference results differ on cpu and NCS2 for yolov5

### ISSUE THREAD

**Issue by iamwandering** [openvinotoolkit/openvino#2723]
##### System information (version)

OpenVINO => 2020.4/2021.1
- Operating System / Platform => ubuntu18.04
- Problem classification: MYRIAD vs CPU
- Framework: Pytorch
- Model name: Yolov5

##### Detailed description

Very different results obtained from using CPU vs MYRIAD, and setting VPU_HW_STAGES_OPTIMIZATION does not work

##### Steps to reproduce

I have successfully converted a customized yolov5 model from Pytorch -> onnx -> IR

The performance of the IR model on CPU was very satisfactory.  However when I tried inferencing on the MYRIAD vpu, the results were very different.  I suspected it was a FP32 and FP16 issue so I converted the model again specifying FP16, but the performance was actually just the same.  I compared the inference outputs between the cpu and vpu, and some numbers were off by quite a big margin, which seemed too much to be just a precision problem.  I was at first using openvino 2020.4, and have just updated to 2021.1, but the results were the same.

I found that other people had previously reported this issue of different results on cpu and vpu, and the suggested solution was to set "VPU_HW_STAGES_OPTIMIZATION" to false.  I did that and there was a deprecation warning, then got a NC_ERROR...cannot read from fifo or something like that. (The model seemed to have loaded ok, the error occurred when trying to do inference).  The NCS2 is connected to a usb hub with external power supply that can support up to 2.4A, power issue is unlikely the cause.

Any idea what's causing the issue??  Or are there any settings (scale?) that I should have specified when doing the conversion?

**Comment by jgespino** [comment]
Hi @iamwandering 

`VPU_HW_STAGES_OPTIMIZATION` should always be on, if a model works by turning VPU_HW_STAGES_OPTIMIZATION off then it's considered a bug. This parameter was meant for debugging purposes and should be deprecated soon.

This question is very similar to https://github.com/openvinotoolkit/openvino/issues/2637, YOLOv5 has not been validated with OpenVINO so it may or may not work. Could you try converting the model using `--scale 255`? Could you share your onnx model, input image and code to reproduce?

Regards,
Jesus

**Comment by iamwandering** [comment]
I tried with the --scale 255 and it seems to work!  Thanks a lot!  Will do more testing tomorrow to confirm.

**Comment by jgespino** [comment]
@iamwandering Great! Please do let me know what you find out.

**Comment by jgespino** [comment]
Closing, feel free to re-open if additional assistance is needed.
