### ISSUE TITLE
Ubuntu 18.04.4 Openvino 2021.1 HDDL hardware initialization failed

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/openvino#2727]
##### System information (version)
- OpenVINO => 2021.1
- Operating System / Platform => Ubuntu 18.04.4  kernel version 4.15.0-121-generic

The hddldaemon of Openvino 2021.1 failed to run in Ubuntu 18.04.4 kernel version 4.15.0-121-generic. 

![Capture](https://user-images.githubusercontent.com/25731934/96528761-0f998800-12b6-11eb-8bef-b9c3a9b94f97.JPG)
![WhatsApp Image 2020-10-19 at 5 46 09 PM](https://user-images.githubusercontent.com/25731934/96528851-3f489000-12b6-11eb-8da1-9b8322188aac.jpeg)

**Comment by tankienleong** [comment]
I able to run the hddldaemon after I modified the install.sh from Mustang-V100_Linux_Plugin_1.0.3.20200212.

I changed all the "openvino" to "openvino_2021" inside install.sh

**Comment by jgespino** [comment]
Hi @tankienleong 

Thanks for reporting your workaround, let me reproduce from my end and open a bug with the development team.

Regards,
Jesus

**Comment by jgespino** [comment]
@tankienleong I was able to reproduce and it seems the IEI script needs to be updated to point to the new OpenVINO installation directory. I have passed this information on to the development team.

Regards,
Jesus

Ref. 41443

**Comment by jgespino** [comment]
Hi @tankienleong 

The latest Mustang-V100-MX8-R11 does not require any changes to the reset script and should work with the script included with the OpenVINO toolkit. Please follow the HDDL installation guidance: https://docs.openvinotoolkit.org/2021.1/openvino_docs_install_guides_installing_openvino_linux_ivad_vpu.html

Regards,
Jesus
