### ISSUE TITLE
 No module named 'generator'

### ISSUE THREAD

**Issue by peckhart89** [openvinotoolkit/openvino#275]
When I run:

`python3 mo.py --input_model custom_frozen_inference_graph.pb --data_type FP16 --output_dir tmp` 

I get this errror:
```
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  No module named 'generator'
[ ERROR ]  Traceback (most recent call last):
  File "/home/myriad/dldt/model-optimizer/mo/main.py", line 269, in main
    return driver(argv)
  File "/home/myriad/dldt/model-optimizer/mo/main.py", line 218, in driver
    import_extensions.load_dirs(argv.framework, extensions, get_front_classes)
  File "/home/myriad/dldt/model-optimizer/mo/utils/import_extensions.py", line 100, in load_dirs
    load_dir(framework, path, get_front_classes)
  File "/home/myriad/dldt/model-optimizer/mo/utils/import_extensions.py", line 85, in load_dir
    import_by_path(os.path.join(path, *p), [ext, *p])
  File "/home/myriad/dldt/model-optimizer/mo/utils/import_extensions.py", line 31, in import_by_path
    importlib.import_module('{}.{}'.format('.'.join(middle_names), name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/myriad/dldt/model-optimizer/mo/ops/expand_dims_test.py", line 20, in <module>
    from generator import generator, generate
ModuleNotFoundError: No module named 'generator'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```

Where is the generator module and how do I get the model optimizer script to find it?

I just cloned the [Deep Learning Development Toolbox](https://github.com/opencv/dldt), built the inference engine as directed in the [Build on Linux Systems](https://github.com/opencv/dldt/blob/master/inference-engine/README.md#build-on-linux-systems) readme, and followed the [Additional Installation Steps for the Intel Movidius Neural Compute Stick2](https://github.com/opencv/dldt/blob/master/inference-engine/README.md#optional-additional-installation-steps-for-the-intel-movidius-neural-compute-stick-and-neural-compute-stick-2) instructions on an Guest Ubuntu 18.04 VM hosted on a mac

**Comment by shubha-ramani** [comment]
Dear @peckhart89 
Please add the --framework switch to your command after mo.py. 

>  --framework {tf,caffe,mxnet,kaldi,onnx}

Alternative you can do mo_tf.py and your command above would avoid the 'ModuleNotFoundError: No module named 'generator' error.

Shubha

**Comment by peckhart89** [comment]
I tried both of your suggestions. They produce the same output and error message.

**Comment by shubha-ramani** [comment]
@peckhart89 

Hmm. It looks like a similar problem was seen here:
[https://github.com/opencv/dldt/issues/82](https://github.com/opencv/dldt/issues/82)

Are you sure you installed your [model optimizer pre-requisites](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Config_Model_Optimizer.html) ?

Thanks,

Shubha

**Comment by peckhart89** [comment]
I followed option 1 from the instructions found [in the DLDT repo](https://github.com/opencv/dldt/blob/master/get-started-linux.md#model-optimizer-configuration-steps).

Do I need to do something else to meet the pre requisites?

**Comment by shubha-ramani** [comment]
@peckhart89 
No. That option is correct. The only thing that could have happened is that when you installed the Model Optimizer pre-requisites, perhaps they did not install properly. Was there an error during the process ?

Well, normally you shouldn't have to do this, but perhaps you can recover from this situation by following [#82](https://github.com/opencv/dldt/issues/82)

**Comment by peckhart89** [comment]
test-generator was the missing module. It was able to run the script. Yay!

However if was unable to convert the FusedBatchNormV3 operation. Are you familiar with this operation and do you know how I can resolve this issue?

**Comment by remarkableJ** [comment]
I have the same trouble, could you please tell me how to figure it out if you have solved it? @peckhart89

**Comment by remarkableJ** [comment]
https://github.com/opencv/dldt/issues/82  It worked, thx @shubha-ramani

**Comment by ilya-lavrenov** [comment]
@lazarevevgeny is it fixed now?

**Comment by lazarevevgeny** [comment]
If you install prerequisites from "requirements_dev.txt" then everything works. So I am closing the issue.
