### ISSUE TITLE
[Docs]: How to load onnx model from memory?

### ISSUE THREAD

**Issue by kq566** [openvinotoolkit/openvino#27546]
### Documentation link

https://docs.openvino.ai/2024/api/c_cpp_api/classov_1_1_core.html#_CPPv4N2ov4Core12import_modelERNSt7istreamERKNSt6stringERK6AnyMap

### Description

I have a onnx model file, and I need to read the model file to char* first. **Is there a way to read this model from char*?**I used openvino2024.3. Here is my code for reading the file to char*. 

```
std::ifstream inputFile(model_file, std::ios::binary | std::ios::ate);
int data_size;
char* model_data;
if (inputFile.is_open())
{
    data_size = inputFile.tellg();
    inputFile.seekg(0, std::ios::beg);
    inputFile.read(model_data, data_size);
    inputFile.close();
}
```

### Issue submission checklist

- [X] I'm reporting a documentation issue. It's not a question.

**Comment by kq566** [comment]
I solved this problem with the following code.

```
const std::string model_ss(static_cast<char*>(model_data),  static_cast<char*>(model_data) + model_data_length);
ov::Tensor weights;
m_compiledModel = m_core->compile_model(model_ss, weights, device);
```

**Comment by gkrivor** [comment]
I see you already closed this question, but it may not be good option from memory consumption point. Probably, you may need to call FrontEnd->convert_model(...) directly using FrontEnd API. It accepts an std::istream for an input, which could be mapped on an existing memory.

**Comment by kq566** [comment]
> I see you already closed this question, but it may not be good option from memory consumption point. Probably, you may need to call FrontEnd->convert_model(...) directly using FrontEnd API. It accepts an std::istream for an input, which could be mapped on an existing memory.

Thank you for your comments and suggestions. I followed your advice and used the frontend to import the ONNX model from memory. The following code worked successfully.

```
std::istringstream model_ss(std::string(static_cast<char*>(model_data), data_size));
ov::frontend::FrontEndManager manager;
ov::frontend::FrontEnd::Ptr front_end;
ov::frontend::InputModel::Ptr input_model;

front_end = manager.load_by_framework("onnx");
input_model = front_end->load(dynamic_cast<std::istream*>(&model_ss));
m_model = front_end->convert(input_model);
```
