### ISSUE TITLE
[Docs]: Openvino c++ get the labels of the model

### ISSUE THREAD

**Issue by hujhcv** [openvinotoolkit/openvino#27574]
### Documentation link

https://docs.openvino.ai/2024/api/c_cpp_api/classov_1_1_any.html

### Description

I saw the following node information at the end of the openvino model xml file exported by pytorch
```
	<rt_info>
		<Runtime_version value="2024.4.0-16579-c3152d32c9c-releases/2024/4" />
		<conversion_parameters>
			<framework value="pytorch" />
			<is_python_object value="True" />
		</conversion_parameters>
		<model_info>
			<iou_threshold value="0.7" />
			<labels value="baise_ymq huangse_ymq heise_gangzi lanse_qiupai baise_qiupai wang" />
			<model_type value="YOLO" />
			<pad_value value="114" />
			<resize_type value="fit_to_window_letterbox" />
			<reverse_input_channels value="YES" />
			<scale_values value="255" />
		</model_info>
	</rt_info>
```

I can get the model_info object using the following C++ code

```
    ov::Core core;
    std::shared_ptr<ov::Model> model = core.read_model("model.xml");
    ov::RTMap rt_info = model->get_rt_info();
    ov::Any model_info = rt_info["model_info"];
```

But how do I get the values ​​of iou_threshold and labels from the model_info object of type ov::Any?
I searched the openvino documentation but couldn't find any relevant instructions.

### Issue submission checklist

- [ ] I'm reporting a documentation issue. It's not a question.

**Comment by ilya-lavrenov** [comment]
```c++
rt_info["model_info"]["iou_threshold"].as<float>()
```

**Comment by hujhcv** [comment]
> ```c++
> rt_info["model_info"]["iou_threshold"].as<float>()
> ```

The rt_info["model_info"] type is ov::Any , rt_info["model_info"]["iou_threshold"] gives the following error: error: no viable overloaded operator[] for type 'std::map<std::basic_string<char>, ov::Any>::mapped_type' (aka 'ov::Any')

**Comment by ilya-lavrenov** [comment]
@hujhcv corrected the answer, you are right.
