### ISSUE TITLE
[Good First Issue] [ARM]: Implement CPU plugin just-in-time emitter for Round operation 

### ISSUE THREAD

**Issue by a-sidorova** [openvinotoolkit/openvino#27668]
### Context

[JIT Emitters](https://github.com/openvinotoolkit/openvino/blob/42f1cb095143f19c0b9ee25836c29748bc8d9bf2/src/plugins/intel_cpu/src/emitters/README.md) are part of code generation feature (a.k.a. tensor compiler) that automatically produces highly-efficient optimized fused subgraph binary code. Each emitter implements specific operation from low level OpenVINO dialect.

### Prerequisites
Recommended to use ARM CPU based platform for development (e.g. Mac, Raspberry Pi etc). Emulators (e.g. QEMU) is still an option, but not that convenient, especially for final performance evaluation. 

### What needs to be done?

* Create `fp32` [Round](https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/operation-specs/arithmetic/round-5.html) operation JIT emitter for ARM64 SIMD platform. Use OpenVINO [CPU plugin JIT emitters](https://github.com/openvinotoolkit/openvino/blob/42f1cb095143f19c0b9ee25836c29748bc8d9bf2/src/plugins/intel_cpu/src/emitters/README.md) documentation and [Arm A-profile A64 Instruction Set Architecture](https://developer.arm.com/documentation/ddi0602/2024-03/SIMD-FP-Instructions) documentation for details. Notice that the op `Round` has two modes of rounding: `half_to_even` and `half_away_from_zero`. The JIT emitter should support the both modes.
* Modify [ARM64 executor](https://github.com/openvinotoolkit/openvino/blob/22f3fef72727961b0c94625cdafaa97f014075b0/src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp#L20) and [ARM64 kernel](https://github.com/openvinotoolkit/openvino/blob/22f3fef72727961b0c94625cdafaa97f014075b0/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.hpp#L81) (in both places: [create_eltwise_emitter](https://github.com/openvinotoolkit/openvino/blob/22f3fef72727961b0c94625cdafaa97f014075b0/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp#L633) and [get_supported_precisions](https://github.com/openvinotoolkit/openvino/blob/22f3fef72727961b0c94625cdafaa97f014075b0/src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp#L818)) to apply developed JIT emitter.

Before emitter implementation, please, modify tests to be sure that developed functionality is covered by test:
  * Add `jit` kernel check in [activation](https://github.com/openvinotoolkit/openvino/blob/52b4ea038e7646e3e3ea91a5b0ada4be1e9c72f8/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp#L180) test, the test must fail.
* If test doesn't fail then add supported activation type (`RoundHalfToEven` and `RoundHalfAwayFromZero`) in [CPU activation test instantiation](https://github.com/openvinotoolkit/openvino/blob/22f3fef72727961b0c94625cdafaa97f014075b0/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp) if it's absent.
* For the better test coverage, update input generation [algorithm](https://github.com/openvinotoolkit/openvino/blob/bafe635b5b1c6184d04adec24a8f4738c3452cc4/src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp#L54) to generate values with floating point.

### Tests
Tests are disabled in default build, so ensure to add `-DENABLE_TESTS=ON` into cmake command.

[GoogleTest](https://github.com/google/googletest) is used for testing. CPU functional test target is [ov_cpu_func_tests](https://github.com/openvinotoolkit/openvino/tree/master/src/plugins/intel_cpu/tests/functional). You can use `GoogleTest` filter:
```sh
./bin/[platform]/[build_type]/ov_cpu_func_tests --gtest_filter="*smoke*Activation*Round*"
```

### Example Pull Requests

* [Abs](https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/operation-specs/arithmetic/abs-1.html) operation: https://github.com/openvinotoolkit/openvino/pull/23692
* [Sigmoid](https://docs.openvino.ai/2024/documentation/openvino-ir-format/operation-sets/operation-specs/activation/sigmoid-1.html) operation, which reuses [Exp emitter](https://github.com/openvinotoolkit/openvino/blob/e19724e2c4815a06003937662da8508cf806d8a0/src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp#L1945): https://github.com/openvinotoolkit/openvino/pull/23065

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [CPU plugin JIT emitters](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/src/emitters/README.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@a-sidorova, @dmitry-gorokhov

**Comment by emir05051** [comment]
.take

**Comment by emir05051** [comment]
May I get some help please ? I get this error, when I'm trying to push. Also should Round be implemented as one operator for two modes or two operators for two modes like in src/nodes/eltwise.cpp? 

```
Run # Needed as the Linux CC does not require setupvars to work
[setupvars.sh] OpenVINO environment initialized
ERROR:conformance_utilities:/__w/openvino does not contain applicable directories to pattern: bin
WARNING:test_parallel_runner:Please set the above env variable to get the same conformance ir names run by run!
INFO:test_parallel_runner:[ARGUMENTS] --exec_file=/__w/openvino/openvino/install/tests/ov_cpu_func_tests
INFO:test_parallel_runner:[ARGUMENTS] --working_dir=/__w/openvino/openvino/install/tests
INFO:test_parallel_runner:[ARGUMENTS] --process_timeout=3600
INFO:test_parallel_runner:[ARGUMENTS] --cache_path=/__w/openvino/openvino/install/tests/test_cache.lst
INFO:test_parallel_runner:[ARGUMENTS] --workers=8
INFO:test_parallel_runner:[ARGUMENTS] --parallel_devices=0
INFO:test_parallel_runner:[ARGUMENTS] --split_unit=suite
INFO:test_parallel_runner:[ARGUMENTS] --repeat_failed=0
INFO:test_parallel_runner:[ARGUMENTS] --excluded_tests_file=None
INFO:test_parallel_runner:[ARGUMENTS] Executable file arguments = ['--gtest_print_time=1', '--gtest_filter=*smoke*']
INFO:test_parallel_runner:Run test parallel is started. Worker num is 8
INFO:test_parallel_runner:Get test list using command: /__w/openvino/openvino/install/tests/ov_cpu_func_tests --gtest_print_time=1 --gtest_filter=*smoke* --gtest_list_tests > /__w/openvino/openvino/install/tests/test_list.lst
INFO:test_parallel_runner:Len test_list_runtime (without disabled tests): 1555
INFO:test_parallel_runner:Get test list from cache file: /__w/openvino/openvino/install/tests/test_cache.lst
INFO:test_parallel_runner:Len tests_dict_cache: 1555
INFO:test_parallel_runner:Total test counter is [17](https://github.com/openvinotoolkit/openvino/actions/runs/12147153611/job/33874519329?pr=27885#step:13:18)6458
INFO:test_parallel_runner:Execute jobs taken from cache and runtime
Worker initialization: [........................................] 0/8
Worker initialization: [#####...................................] 1/8
Worker initialization: [##########..............................] 2/8
Worker initialization: [###############.........................] 3/8
Worker initialization: [####################....................] 4/8
Worker initialization: [#########################...............] 5/8
Worker initialization: [##############################..........] 6/8
Worker initialization: [###################################.....] 7/8
Worker initialization: [########################################] 8/8
Worker execution: [........................................] 0/16
Worker execution: [##......................................] 1/16
Worker execution: [#####...................................] 2/16
Worker execution: [#######.................................] 3/16
Worker execution: [##########..............................] 4/16
Worker execution: [############............................] 5/16
Worker execution: [###############.........................] 6/16
Worker execution: [#################.......................] 7/16
Worker execution: [####################....................] 8/16
Worker execution: [######################..................] 9/16
Worker execution: [#########################...............] 10/16
Worker execution: [###########################.............] 11/16
Worker execution: [##############################..........] 12/16
Worker execution: [################################........] 13/16
Worker execution: [###################################.....] 14/16
Worker execution: [#####################################...] 15/16
Worker execution: [########################################] 16/16
INFO:test_parallel_runner:Compeleting processes: Active process counter: 7...
INFO:test_parallel_runner:Compeleting processes: Active process counter: 6...
INFO:test_parallel_runner:Compeleting processes: Active process counter: 5...
INFO:test_parallel_runner:Compeleting processes: Active process counter: 4...
INFO:test_parallel_runner:Compeleting processes: Active process counter: 3...
INFO:test_parallel_runner:Compeleting processes: Active process counter: 2...
INFO:test_parallel_runner:Compeleting processes: Active process counter: 1...
INFO:test_parallel_runner:Compeleting processes: Active process counter: 0...
INFO:test_parallel_runner:Get test list using command: /__w/openvino/openvino/install/tests/ov_cpu_func_tests --gtest_print_time=1 --gtest_filter=*smoke* --gtest_list_tests > /__w/openvino/openvino/install/tests/test_list.lst
INFO:test_parallel_runner:Len test_list_runtime (without disabled tests): 175871
INFO:test_parallel_runner:Run test parallel is finished successfully. Total time is 0h:[20](https://github.com/openvinotoolkit/openvino/actions/runs/12147153611/job/33874519329?pr=27885#step:13:21)m:10.02s
INFO:test_parallel_runner:Log analize is started
INFO:test_parallel_runner:Hashed test list is saved to: /__w/openvino/openvino/install/tests/logs/hash_table.csv
INFO:test_parallel_runner:Fix priorities list is saved to: /__w/openvino/openvino/install/tests/logs/fix_priority.csv
INFO:test_parallel_runner:Disabled test list is saved to: /__w/openvino/openvino/install/tests/logs/disabled_tests.log
INFO:test_parallel_runner:Get test list using command: /__w/openvino/openvino/install/tests/ov_cpu_func_tests --gtest_print_time=1 --gtest_filter=*smoke* --gtest_list_tests > /__w/openvino/openvino/install/tests/test_list.lst
INFO:test_parallel_runner:Len test_list_runtime (without disabled tests): 175871
INFO:test_parallel_runner:passed test counter is: 154111
INFO:test_parallel_runner:skipped test counter is: [21](https://github.com/openvinotoolkit/openvino/actions/runs/12147153611/job/33874519329?pr=27885#step:13:22)754
INFO:test_parallel_runner:failed test counter is: 6
INFO:test_parallel_runner:disabled test counter is: 20
INFO:test_parallel_runner:Total test count with disabled tests is 175891. All logs is saved to /__w/openvino/openvino/install/tests/logs
ERROR:test_parallel_runner:Run is not successful
```

**Comment by dmitry-gorokhov** [comment]
@emir05051 Thanks for the contribution!
It is ok to have to seprate emitters.
As of CI issue: anwered in the PR.
