### ISSUE TITLE
[Good First Issue]: Expose Tensor.isContinuous() functionality

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#27701]
### Context

OpenVINO works in Node.js environment!
We are looking for new contributors who can help with enabling C++ API methods 
in JavaScript side.

First of all read Node.js API [Contribution Guide](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/CONTRIBUTING.md).

#### Task Details

Expose `ov::Tensor::is_continuous()` method. 
From JavaScript side it will be `ov.isContinuous()` method.

#### Useful links

- C++ API [implementation](https://github.com/openvinotoolkit/openvino/blob/f6e0ba02a580cebfb4a4f9305b07a806c5e9509f/src/core/src/runtime/tensor.cpp#L107) of `Tensor::is_continuous()` method

### What needs to be done?

 - Implement the method in [node/src/tensor.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/src/tensor.cpp)
- Update TypeScript definitions in [./src/bindings/js/node/lib/addon.ts](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/lib/addon.ts)
- Create unit test for added functionality using Node.js Test Runner. The logic might be similar to the Python tests for this functionality. [Link to Python API tests](https://github.com/openvinotoolkit/openvino/blob/f6e0ba02a580cebfb4a4f9305b07a806c5e9509f/src/bindings/python/tests/test_runtime/test_tensor.py#L557)

### How to take this issue

To take this issue leave text: `.take` as the comment in this issue.
It will assign this issue to you automatically. Please, make sure that the issue has the status **Contributors Needed** and doesn't have another user in Assingnees.

### Example Pull Requests

 - https://github.com/openvinotoolkit/openvino/pull/23743
 - https://github.com/openvinotoolkit/openvino/pull/24023

### Resources

- [[NEW] Contribution Guide](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/CONTRIBUTING.md)
- [JavaScript API Developer Documentation](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/docs/README.md#openvino-node-package-developer-documentation)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai 

Please, mention us in this issue discussion if you have any questions.

**Comment by nashez** [comment]
.take

**Comment by sahil07-rg** [comment]
.take

**Comment by nashez** [comment]
Hi @sahil07-rg I am still working on this issue and the PR is open

Just a few open comments I need to resolve on the PR

I shall resolve it all by today

**Comment by nashez** [comment]
.take
