### ISSUE TITLE
[Feature Request]: Clarify Unix group requirements for using GPU plugin

### ISSUE THREAD

**Issue by frenchwr** [openvinotoolkit/openvino#27762]
### Request Description

Hello, could you please clarify whether a user needs to be in the `video` Unix group in order to fully utilize the GPU plugin? I gather from other doc pages that a user needs to be in the `render` group - could you please confirm? I think these details would be helpful in the following section on the OpenVINO docs: https://docs.openvino.ai/2024/get-started/configurations/configurations-intel-gpu.html

### Feature Use Case

Clarify GPU plugin usage and configuration, improved ease of use, fewer support issues for maintainers

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by yury-gorbachev** [comment]
@vladimir-paramuzov @isanghao  - could you please help with this?

**Comment by isanghao** [comment]
Hi @frenchwr, sorry for the belated response. AFAIK, it is sufficient to put it in render group.(and it is how I am using it) Let me check with driver team for official response and follow-up.

**Comment by isanghao** [comment]
HI @frenchwr, I checked with driver team and it is actually about Linux distro's configuration for access permission of device node.
Ubuntu seems to set group of  /dev/dri/render* as `render`. In such case, adding user to `render` is sufficient.
