### ISSUE TITLE
[Good First Issue]: [OV JS] Add check for arguments to Tensor.getData()

### ISSUE THREAD

**Issue by almilosz** [openvinotoolkit/openvino#27796]
### Context

OpenVINO works in Node.js environment!
We are looking for new contributors who can help with enabling C++ API methods 
in JavaScript side.

First of all read Node.js API [Contribution Guide](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/CONTRIBUTING.md).

#### Task Details

The `Tensor.getData()` method, which takes no arguments, should return an error if an argument is passed.

### What needs to be done?

- modify `Tensor.getData()` method [node/src/tensor.cpp#L69](https://github.com/openvinotoolkit/openvino/blob/f2d2c221ef34f8300a1a7460c9532247d343bb54/src/bindings/js/node/src/tensor.cpp#L69)
- you can take a look at [this method](https://github.com/openvinotoolkit/openvino/blob/f2d2c221ef34f8300a1a7460c9532247d343bb54/src/bindings/js/node/src/tensor.cpp#L169)
- add a test to [this suite](https://github.com/openvinotoolkit/openvino/blob/f2d2c221ef34f8300a1a7460c9532247d343bb54/src/bindings/js/node/tests/unit/tensor.test.js#L85)

### How to take this issue

To take this issue leave text: `.take` as the comment in this issue.
It will assign this issue to you automatically. Please, make sure that the issue has the status **Contributors Needed** and doesn't have another user in Assingnees.

### Example Pull Requests

 - https://github.com/openvinotoolkit/openvino/pull/23743
 - https://github.com/openvinotoolkit/openvino/pull/24023

### Resources

- [[NEW] Contribution Guide](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/CONTRIBUTING.md)
- [JavaScript API Developer Documentation](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/docs/README.md#openvino-node-package-developer-documentation)
- [Node.js API Reference](https://docs.openvino.ai/2024/api/nodejs_api/addon.html)
- [Node.js bindings examples of usage](https://github.com/nodejs/node-addon-examples)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [How to contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@almilosz @vishniakov-nikolai 

Please, mention us in this issue discussion if you have any questions.

### Ticket

-

**Comment by Pranjal0901** [comment]
.take

**Comment by Pranjal0901** [comment]
which repo i have to download to implement this

**Comment by mlukasze** [comment]
> which repo i have to download to implement this

https://github.com/openvinotoolkit/openvino

**Comment by Manideep-Kanna** [comment]
Hi, I have seen this issue been open for three days. Thought of working on it. I have raised a PR for these changes can you please look at them and let me know if additional changes are required.
