### ISSUE TITLE
[Sample][Custom Layer]No instructions for using the 'inPlaceExtension' in hello_reshape_ssd sample

### ISSUE THREAD

**Issue by cosmos1982** [openvinotoolkit/openvino#2791]
There is  a code sample of "CustomReLU" op implementation in samples/cpp/hello_reshape_ssd/reshape_ssd_extension.hpp, but no instructions for the corresponding models with 'CustomReLU',  where can I get an IR with 'CustomReLU' op? I need to implement an custom layer and an executable sample is strongly required.

**Comment by jgespino** [comment]
Hi @cosmos1982 

Have you tried downloading ssd300 using the model downloader included with OpenVINO? I downloaded the ssd300 model with the following command.

`python3 /opt/intel/openvino_2021/deployment_tools/tools/model_downloader/downloader.py --name ssd300`

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
