### ISSUE TITLE
#dldt i was trying to convert tensorflow fastercnn  frozengraph.pb  which i trained with custom data to modeloptimizer ir file i am getting this error

### ISSUE THREAD

**Issue by manoj652** [openvinotoolkit/openvino#28]
#dldt The Preprocessor block has been removed. Only nodes performing mean value subtraction and scaling (if applicable) are kept.
[ ERROR ]  Found the following nodes '[]' with name 'swapped_proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalAndROIPoolingReplacement replacement didn't work.

**Comment by lazarevevgeny** [comment]
@manoj652 Looks like the sub-graph replacement configuration file that you specified with the --tensorflow_object_detection_api_pipeline_config command line parameter is not suitable for your version of the FasterRCNN topology. Could you re-run the Model Optimizer with the --log_level DEBUG command line option and attach the log file?

**Comment by manoj652** [comment]
@lazarevevgeny 

--log_level DEBUG
SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ChangeCoordinateFrame/truediv_1/mul_
SecondStagePostprocessor/scale_logits/reciprocal_
SecondStagePostprocessor/scale_logits/mul_
[ ERROR ]  Found the following nodes '[]' with name 'swapped_proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalAndROIPoolingReplacement replacement didn't work.
[ 2018-11-15 21:55:55,244 ] [ DEBUG ] [ main:327 ]  Traceback (most recent call last):
  File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/main.py", line 321, in main
    return driver(argv)
  File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/main.py", line 263, in driver
    mean_scale_values=mean_scale)
  File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 171, in tf2nx
    class_registration.apply_replacements(graph, class_registration.ClassType.FRONT_REPLACER)
  File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 102, in apply_replacements
    replacer.find_and_replace_pattern(graph)
  File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/front/tf/replacement.py", line 91, in find_and_replace_pattern
    self.replace_sub_graph(graph, match)
  File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/front/common/replacement.py", line 115, in replace_sub_graph
    new_sub_graph = self.generate_sub_graph(graph, match)
  File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/extensions/front/tf/ObjectDetectionAPI.py", line 261, in generate_sub_graph
    format(proposal_nodes_ids))
mo.utils.error.Error: Found the following nodes '[]' with name 'swapped_proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalAndROIPoolingReplacement replacement didn't work.

**Comment by manoj652** [comment]
@lazarevevgeny  
the entire --log_level DEBUG


[logleveldebug.txt](https://github.com/opencv/dldt/files/2586192/logleveldebug.txt)

**Comment by roburst2** [comment]
@manoj652  @lazarevevgeny i am also getting same error "**mo.utils.error.Error: Found the following nodes '[]' with name 'swapped_proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalAndROIPoolingReplacement replacement didn't work**."

**I ran the below command.**

python3 mo_tf.py --input_model tensorflow_faster_rcnn_resnet_frozen_inference_graph.pb --tensorflow_use_custom_operations_config /opt/intel/computer_vision_sdk/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support_api_v1.7.json --tensorflow_object_detection_api_pipeline_config pipeline.config

Logs are same as @manoj652

**Comment by manoj652** [comment]
@roburst2 @lazarevevgeny i was able to convert the tensorflow community models to ir format but when we  use those pretrained models i was able to convert mobilenetssdv2 which was custom trained also converted  

but for fasterrcnn i am getting this error

**Comment by roburst2** [comment]
@manoj652  with the same command were you able to convert?
and i am trying to convert the fasterrcnn which custom trained

**Comment by lazarevevgeny** [comment]
@manoj652 @roburst2 please, wait for the repo update or download the OpenVINO 2018R4 package https://software.intel.com/en-us/openvino-toolkit/ with the fix.

**Comment by roburst2** [comment]
@lazarevevgeny  I am using **Converting TensorFlow* Object Detection API Models 2018 R4 release** only.I am using the below command and getting error "**[ ERROR ]  Found the following nodes '[]' with name 'swapped_proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalAndROIPoolingReplacement replacement didn't work**"

python3 mo_tf.py --input_model=/home/hasmeet/Subin/faster_rcnn_resnet/models/research/fine_tuned_model/frozen_inference_graph.pb --tensorflow_use_custom_operations_config=/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json --tensorflow_object_detection_api_pipeline_config=/home/hasmeet/Subin/faster_rcnn_resnet/models/research/pretrained/faster_rcnn_resnet101/faster_rcnn_resnet.config

**Comment by lazarevevgeny** [comment]
@roburst2 could you try 'faster_rcnn_support_api_v1.7.json'?

**Comment by roburst2** [comment]
@lazarevevgeny  i tried with this one also. it is giving same error

**Comment by lazarevevgeny** [comment]
@roburst2 could you run the MO with --log_level DEBUG and attach generated output?

**Comment by manoj652** [comment]
@lazarevevgeny  
[logleveldebug.txt](https://github.com/opencv/dldt/files/2594930/logleveldebug.txt)

**Comment by lazarevevgeny** [comment]
@roburst2 you can try to debug the issue yourself. Open the 'faster_rcnn_support_api_v1.7.json', find description of the `ObjectDetectionAPIProposalReplacement`. Take a look at the graph in the TensorBoard and check that all nodes mentioned in the "start_points" and "end_points" arrays exist. If no, then find where these nodes are located in the pre-trained models from the TF models repo and find analogue in your model.

**Comment by lazarevevgeny** [comment]
@manoj652 I see in the log the following error:

> [ 2018-11-15 21:55:55,037 ] [ DEBUG ] [ class_registration:100 ]  Run replacer <class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIProposalAndROIPoolingReplacement'>
[ INFO ]  Node "CropAndResize" does not exist in the graph. Failed to match sub-graph by points "ObjectDetectionAPIProposalAndROIPoolingReplacement".

Find node of type CropAndResize in your model and update the json file with that name.

**Comment by roburst2** [comment]
Executed this command:
python3 mo_tf.py 
--input_model=<fine_tuned_model1/frozen_inference_graph.pb> 
--tensorflow_use_custom_operations_config=/opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support_api_v1.7.json 
--tensorflow_object_detection_api_pipeline_config=<fine_tuned_model/pipeline.config >
--log_level=DEBUG

Debug log file:
[logleveldebugroburst2.txt](https://github.com/opencv/dldt/files/2594956/logleveldebugroburst2.txt)

**Comment by lazarevevgeny** [comment]
@roburst2 you have the same issue as @manoj652 . Please, try to find correct name for the CropAndResize operation in your graph and update the json file with that name.

**Comment by roburst2** [comment]
@lazarevevgeny  could you tell me frrom where i can find the name for CropAndResize and update.
can you elaborate.

**Comment by manoj652** [comment]
@roburst2 @lazarevevgeny 
![fixeissue](https://user-images.githubusercontent.com/22527200/48706408-35c5d180-ec22-11e8-8c8d-b274c43411fc.png)
![cropandresize](https://user-images.githubusercontent.com/22527200/48706424-40806680-ec22-11e8-802b-f6cbfbe5ae3c.png)

**Comment by lazarevevgeny** [comment]
@roburst2 the file that you specified with the --tensorflow_use_custom_operations_config command line parameter: /opt/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support_api_v1.7.json

**Comment by manoj652** [comment]
@lazarevevgeny @roburst2 i changed in config file_api.1.7.json file
i am still getting the error @lazarevevgeny  any suggestions

**Comment by lazarevevgeny** [comment]
The name of the node is "CropAndResize/CropAndResize" and not "CropAndResize" (this is the name of the scope). And this will probably not work with the 2018R3 release which you use.

**Comment by lazarevevgeny** [comment]
@manoj652 you need 2018R4 to get updates of the MO scripts converting these models.

@roburst2 you have updated the file correctly. Could you take a look at the log file (generated with the --log_level DEBUG command line) for the string "Run replacer <class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIProposalAndROIPoolingReplacement'>"? It will show you why the replacer didn't work.

**Comment by manoj652** [comment]
@roburst2 did u tried in 2018R4

**Comment by roburst2** [comment]
@manoj652 @lazarevevgeny I was also using 2018R3. I will install and try again

**Comment by roburst2** [comment]
I tried with 2018R4 and now getting this error

**mo.utils.error.Error: Exception occurred during running replacer "ObjectDetectionAPIDetectionOutputReplacement": Found the following nodes '[]' with name 'proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalReplacement replacement didn't work**

logfile:
[loglevelR4.txt](https://github.com/opencv/dldt/files/2595397/loglevelR4.txt)

**Comment by manoj652** [comment]
@lazarevevgeny  i installed R4 version i tried i am getting new error

--loglevel_debug

[ 2018-11-19 18:48:49,974 ] [ DEBUG ] [ infer:133 ]  --------------------
[ 2018-11-19 18:48:49,974 ] [ DEBUG ] [ infer:134 ]  Partial infer for stack_3/Concat_
[ 2018-11-19 18:48:49,974 ] [ DEBUG ] [ infer:135 ]  Op: Concat
[ 2018-11-19 18:48:49,975 ] [ DEBUG ] [ infer:146 ]  Inputs:
[ 2018-11-19 18:48:49,976 ] [ DEBUG ] [ infer:39 ]  input[0]: shape = [1], value = [300]
[ 2018-11-19 18:48:49,976 ] [ DEBUG ] [ infer:39 ]  input[1]: shape = [1], value = [14]
[ 2018-11-19 18:48:49,976 ] [ DEBUG ] [ infer:39 ]  input[2]: shape = [1], value = [14]
[ 2018-11-19 18:48:49,977 ] [ DEBUG ] [ infer:39 ]  input[3]: shape = [1], value = [576]
[ 2018-11-19 18:48:49,977 ] [ DEBUG ] [ infer:148 ]  Outputs:
[ 2018-11-19 18:48:49,977 ] [ DEBUG ] [ infer:39 ]  output[0]: shape = [4], value = [300  14  14 576]
[ 2018-11-19 18:48:49,977 ] [ DEBUG ] [ infer:133 ]  --------------------
[ 2018-11-19 18:48:49,977 ] [ DEBUG ] [ infer:134 ]  Partial infer for Reshape_5
[ 2018-11-19 18:48:49,978 ] [ DEBUG ] [ infer:135 ]  Op: Reshape
[ ERROR ]  Number of elements in input [  1 100  14  14 576] and output [300, 14, 14, 576] of reshape node Reshape_5 mismatch
[ 2018-11-19 18:48:49,979 ] [ DEBUG ] [ infer:146 ]  Inputs:
[ 2018-11-19 18:48:49,979 ] [ DEBUG ] [ infer:39 ]  input[0]: shape = [  1 100  14  14 576], value = <UNKNOWN>
[ 2018-11-19 18:48:49,979 ] [ DEBUG ] [ infer:39 ]  input[1]: shape = [4], value = [300  14  14 576]
[ 2018-11-19 18:48:49,979 ] [ DEBUG ] [ infer:148 ]  Outputs:
[ 2018-11-19 18:48:49,980 ] [ DEBUG ] [ infer:39 ]  output[0]: shape = <UNKNOWN>, value = <UNKNOWN>
[ ERROR ]  Shape is not defined for output 0 of "Reshape_5".
[ ERROR ]  Cannot infer shapes or values for node "Reshape_5".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "Reshape_5". 
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #40. 
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function tf_reshape_ext.<locals>.<lambda> at 0x7f0bd1ed61e0>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ 2018-11-19 18:48:49,981 ] [ DEBUG ] [ infer:198 ]  Node "Reshape_5" attributes: {'pb': name: "Reshape_5"
op: "Reshape"
input: "CropAndResize/Reshape_2"
input: "stack_3"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "Tshape"
  value {
    type: DT_INT32
  }
}
, 'kind': 'op', 'name': 'Reshape_5', 'op': 'Reshape', 'precision': 'FP32', 'IE': [('layer', [('id', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6268>), 'name', 'precision', 'type'], [('data', ['auto_pad', 'epsilon', 'min', 'max', ('axis', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed62f0>), 'tiles', ('dim', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6378>), 'num_axes', ('pool-method', 'pool_method'), 'group', ('rounding-type', 'rounding_type'), ('exclude-pad', 'exclude_pad'), 'operation', 'out-size', 'power', 'shift', 'alpha', 'beta', 'coords', 'classes', 'num', ('local-size', 'local_size'), 'region', 'knorm', 'num_classes', 'keep_top_k', 'variance_encoded_in_target', 'code_type', 'share_location', 'nms_threshold', 'confidence_threshold', 'background_label_id', 'top_k', 'eta', 'visualize', 'visualize_threshold', 'save_file', 'output_directory', 'output_name_prefix', 'output_format', 'label_map_file', 'name_size_file', 'num_test_image', 'prob', 'resize_mode', 'height', 'width', 'height_scale', 'width_scale', 'pad_mode', 'pad_value', 'interp_mode', 'img_size', 'img_h', 'img_w', 'step', 'step_h', 'step_w', ('offset', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6400>), 'variance', 'flip', 'clip', ('min_size', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6488>), ('max_size', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6510>), ('aspect_ratio', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6598>), 'decrease_label_id', 'normalized', 'scale_all_sizes', ('type', 'norm_type'), 'eps', 'across_spatial', 'channel_shared', 'negative_slope', 'engine', 'num_filter', ('type', 'sample_type'), ('order', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6620>), 'pooled_h', 'pooled_w', 'spatial_scale', 'cls_threshold', 'max_num_proposals', 'iou_threshold', 'min_bbox_size', 'feat_stride', 'pre_nms_topn', 'post_nms_topn', ('type', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed66a8>), ('value', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6730>), ('output', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed67b8>), ('input_nodes_names', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6840>), ('output_tensors_names', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed68c8>), ('real_input_dims', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6950>), ('protobuf', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed69d8>), {'custom_attributes': None}, ('strides', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6a60>), ('kernel', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6ae8>), ('dilations', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6b70>), ('pads_begin', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6bf8>), ('pads_end', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6c80>), ('scale', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6d08>), 'crop_width', 'crop_height', 'write_augmented', 'max_multiplier', 'augment_during_test', 'recompute_mean', 'write_mean', 'mean_per_pixel', 'mode', 'bottomwidth', 'bottomheight', 'chromatic_eigvec', 'kernel_size', 'max_displacement', 'stride_1', 'stride_2', 'single_direction', 'do_abs', 'correlation_type', 'antialias', 'resample_type', 'factor', 'coeff', ('ratio', <function update_ie_fields.<locals>.<lambda> at 0x7f0bd1ed6d90>)], []), '@ports', '@consts'])], 'dim_attrs': ['batch_dims', 'spatial_dims', 'axis', 'channel_dims'], 'shape_attrs': ['window', 'shape', 'pad', 'stride', 'output_shape'], 'is_output_reachable': True, 'is_undead': False, 'is_const_producer': False, 'infer': <function tf_reshape_ext.<locals>.<lambda> at 0x7f0bd1ed61e0>, 'type': 'Reshape', 'prev': None, 'is_partial_inferred': False, 'dim': array([300,  14,  14, 576])}
[ ERROR ]  Stopped shape/value propagation at "Reshape_5" node. 
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #38. 
[ 2018-11-19 18:48:49,982 ] [ DEBUG ] [ main:331 ]  Traceback (most recent call last):
  File "/home/manojvasi/intel/computer_vision_sdk_2018.4.420/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 170, in partial_infer
    node_name)
mo.utils.error.Error: Not all output shapes were inferred or fully defined for node "Reshape_5". 
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #40. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/manojvasi/intel/computer_vision_sdk_2018.4.420/deployment_tools/model_optimizer/mo/main.py", line 325, in main
    return driver(argv)
  File "/home/manojvasi/intel/computer_vision_sdk_2018.4.420/deployment_tools/model_optimizer/mo/main.py", line 267, in driver
    mean_scale_values=mean_scale)
  File "/home/manojvasi/intel/computer_vision_sdk_2018.4.420/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 230, in tf2nx
    partial_infer(graph)
  File "/home/manojvasi/intel/computer_vision_sdk_2018.4.420/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 200, in partial_infer
    refer_to_faq_msg(38)) from err
mo.utils.error.Error: Stopped shape/value propagation at "Reshape_5" node. 
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #38.

**Comment by roburst2** [comment]
@lazarevevgeny  as given in the log **"[ INFO ]  Node "map_1/TensorArrayStack/TensorArrayGatherV3" does not exist in the graph. Failed to match sub-graph by points "ObjectDetectionAPIProposalReplacement""**

How can i add this node in a graph file

**Comment by roburst2** [comment]
@manoj652 can you send me the fasterrcnn config file which you are used.

**Comment by manoj652** [comment]
[pipeline.txt](https://github.com/opencv/dldt/files/2598568/pipeline.txt)
@roburst2 my config file is fasterrcnn_inceptionv2
if u use fasterrcnnresnet use old modelsmaster github pipelineconfig

**Comment by roburst2** [comment]
Thanks @manoj652 i will try with the old fasterrcnnresnet config

**Comment by roburst2** [comment]
@manoj652 I am able to convert with the faster_rcnn_resnet101_coco

**Comment by manoj652** [comment]
@lazarevevgeny tensorlfow 1.12 is not supporting its asking me to install above tensorflow 1.2 

right now i am running tensorflow 1.10 for 3000 steps i was able to covert the same model
but for 36000 steps same model is throwing these errors

**Comment by manoj652** [comment]
> @manoj652 I am able to convert with the faster_rcnn_resnet101_coco

**Comment by manoj652** [comment]
> @manoj652 I am able to convert with the faster_rcnn_resnet101_coco

@roburst2 put config file of faster_rcnn_resnet101_coco which u converted to ir format

**Comment by roburst2** [comment]
[pipeline.txt](https://github.com/opencv/dldt/files/2603496/pipeline.txt)

**Comment by manoj652** [comment]
@roburst2 did u  converted in OPENVINO R4 ,how many steps u trained ,can u tell me the checkpoints of frozengraph.pb

**Comment by roburst2** [comment]
yes i converted in OPENVINO R4 and for 10000 steps i trained

**Comment by manoj652** [comment]
@roburst2 i am getting same error for fasterrcnn_resnet which tensorflow version u used to convert

**Comment by roburst2** [comment]
Metadata-Version: 2.0
Name: tensorflow
Version: 1.9.0


Metadata-Version: 2.0
Name: tensorflow-gpu
Version: 1.4.0

**Comment by manoj652** [comment]
could u send u r mail id i may send my frozengraph to see if it able to convert in ur machine

**Comment by manoj652** [comment]
i tried with both fastercnn resent and fasterrcnn inception i may abl e to convert the files in ir format for 5000 steps but after that i am getting an error
i trained my model upto 33500 steps i can t able to converti tried with both r3 and r4 openvino with tensorflow 1.9 cpu

**Comment by abhishekns** [comment]
[BugReport-ssd_mobilenet-conversion.docx](https://github.com/opencv/dldt/files/2624995/BugReport-ssd_mobilenet-conversion.docx)
[log_level_debug-out.txt](https://github.com/opencv/dldt/files/2624996/log_level_debug-out.txt)

I tried converting the ssd_mobilenet_v2_coco....  model from model zoo but failed. Not sure what went wrong.

The primary error message at the end is 
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  'pb'
[ ERROR ]  Traceback (most recent call last):
  File "C:\Intel\computer_vision_sdk_2018.4.420\deployment_tools\model_optimizer\mo\main.py", line 325, in main
    return driver(argv)
  File "C:\Intel\computer_vision_sdk_2018.4.420\deployment_tools\model_optimizer\mo\main.py", line 267, in driver
    mean_scale_values=mean_scale)
  File "C:\Intel\computer_vision_sdk_2018.4.420\deployment_tools\model_optimizer\mo\pipeline\tf.py", line 184, in tf2nx
    if update_custom_replacement_config_file(graph, argv.tensorflow_custom_operations_config_update):
  File "C:\Intel\computer_vision_sdk_2018.4.420\deployment_tools\model_optimizer\mo\utils\custom_replacement_config.py", line 394, in update_custom_replacement_config_file
    replacement_desc.update_custom_replacement_attributes(graph)
  File "C:\Intel\computer_vision_sdk_2018.4.420\deployment_tools\model_optimizer\mo\utils\custom_replacement_config.py", line 249, in update_custom_replacement_attributes
    output_tensors.add(('^' + dst_node['pb'].input[edge_attrs['in']] + '$', edge_attrs['out']))
KeyError: 'pb'
 
[ ERROR ]  ---------------- END OF BUG REPORT --------------

the full command line as well as the debug log output are attached.

Any help would be appreciated.

Thanks

**Comment by manoj652** [comment]
@abhishekns i converted ssd mobilenet v2 coco using R3 openvino

 python3 mo_tf.py --input_model frozen_inference_graph.pb --tensorflow_use_custom_operations_config  legacy_ssd_v2_support.json
with this i was able to convert

**Comment by abhishekns** [comment]
With R3, I am able to convert, but R4 I am still facing the problem.

**Comment by lazarevevgeny** [comment]
@abhishekns you are using wrong command line parameter "--tensorflow_custom_operations_config " it should be "--tensorflow_use_custom_operations_config". You have missed the word "use" in the command line parameter name.

**Comment by abhishekns** [comment]
Sorry for messaging so late. Thanks @lazarevevgeny for pointing out the mistake.

**Comment by ahmedtalbi** [comment]
> @lazarevevgeny tensorlfow 1.12 is not supporting its asking me to install above tensorflow 1.2
> 
> right now i am running tensorflow 1.10 for 3000 steps i was able to covert the same model
> but for 36000 steps same model is throwing these errors

Hi @manoj652 
can you please tell me how you solved this issue. the converter is also asking for tensorflow 1.2 and so I cant use tensorflow 1.11 to solve the same issue you were having with the tensorflow versions.
Thank you

**Comment by Sanyam2095** [comment]
Hi @manoj652  @lazarevevgeny 

python3 mo_tf.py --input_model /home/ada/Downloads/faster_rcnn_resnet101_coco_2018_01_28/frozen_inference_graph.pb  --output_dir /media/ada/Laika/test/optimized_models --tensorflow_use_custom_operations_config /opt/intel/computer_vision_sdk_2018.5.455/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support.json  --tensorflow_object_detection_api_pipeline_config /media/ada/Laika/tensorFlow/model/pretrained_models/faster_rcnn_resnet101_coco_2017_11_08/pipeline.config --input_shape [1,224,224,3] --reverse_input_channels --log_level=DEBUG

This is the command i am using and I am getting error 

[ ERROR ]  Stopped shape/value propagation at "Reshape_5" node. 
 For more information please refer to Model Optimizer FAQ (<INSTALL_DIR>/deployment_tools/documentation/docs/MO_FAQ.html), question #38. 
[ 2019-03-18 17:00:37,968 ] [ DEBUG ] [ main:331 ]  Traceback (most recent call last):
  File "/opt/intel/computer_vision_sdk_2018.5.455/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 153, in partial_infer
    node.infer(node)
  File "/opt/intel/computer_vision_sdk_2018.5.455/deployment_tools/model_optimizer/mo/front/tf/extractors/reshape.py", line 27, in <lambda>
    lambda node: np.reshape(node.in_node().value,
  File "/opt/intel/computer_vision_sdk_2018.5.455/deployment_tools/model_optimizer/mo/front/common/partial_infer/elemental.py", line 19, in single_output_infer
    node.out_node(0).shape = shape_infer(node)
  File "/opt/intel/computer_vision_sdk_2018.5.455/deployment_tools/model_optimizer/mo/front/common/partial_infer/reshape.py", line 65, in tf_reshape_shape_infer
    node.name))
mo.utils.error.Error: Number of elements in input [  1 300   4] and output [100, 4] of reshape node Reshape_5 mismatch

Please help me figuring out the error or any other issue there is with my command.
Thank you in advance.

**Comment by siva2k16** [comment]
I have the same issue Single class custom model failed for both faster_rcnn_resnet101_coco_2018_01_28, 
faster_rcnn_inception_v2_coco_2018_01_28. Posted in OpenVino forum with logs https://software.intel.com/en-us/forums/computer-vision/topic/809546. Please let me know the fix for this error - Exception occurred during running replacer "ObjectDetectionAPIDetectionOutputReplacement" (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIDetectionOutputReplacement'>): Found the following nodes '[]' with name 'crop_proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalReplacement replacement didn't work.

**Comment by didopop3** [comment]
@siva2k16  have you solved the issue, I got exact same error

**Comment by lazarevevgeny** [comment]
Is the issue still actual?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
