### ISSUE TITLE
Media-driver, OpenCL version for use with OpenVINO 2021.1

### ISSUE THREAD

**Issue by js333031** [openvinotoolkit/openvino#2808]
Is compute-runtime version 19.41.14441 still the right version for 2021.1? I need to know the versions for these, ideally a github tag/branch link for each:
msdk
libva
libva-utils
gmm
compute-runtime

**Comment by jgespino** [comment]
Hi @js333031 

Thanks for reaching out, the Intel Distribution for OpenVINO toolkit 2021.1 release includes Intel MediaSDK 19.3.0. Please see the release notes for Intel MediaSDK under `/opt/intel/mediasdk/docs` (Linux) which contains the GitHub tags for the components mentioned above. The same information can also be found on the release tag for [MediaSDK 19.3.0](https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-19.3.0).

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @js333031 

As I looked further into the Intel Media SDK included with the OpenVINO toolkit 2021.1 release, the release notes in the `/opt/intel/mediasdk/doc` directory belongs to Media SDK 19.3.1. However, the Media SDK software version is 19.3.1. Please see the [release page for Media SDK 19.3.1](https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-19.3.1) for the component list and respective tags.

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
