### ISSUE TITLE
Onnx Conversion Missing Op

### ISSUE THREAD

**Issue by GotG** [openvinotoolkit/openvino#2812]
Hello

I am trying to convert a CNN model from ONNX to OpenVINO.

The following 2 ops are missing:

Instructions/layers that do not have attribute extractors:
[ WARNING ]      Sub (2)
[ WARNING ]          Sub_78
[ WARNING ]          Sub_140
[ WARNING ]      Min (3)
[ WARNING ]          Min_87
[ WARNING ]          Min_88
[ WARNING ]          Min_89

Min and Sub. Can you please provide some guidance as to how/where to add them?

Thank you

**Comment by jgespino** [comment]
Hi @GotG 

Which version of the OpenVINO toolkit are you using? Sub Op should be supported in the latest OpenVINO 2021.1 release see [Supported Framework Layers](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#onnx_supported_operators). Min Op is not listed, see this [tutorial](https://github.com/david-drew/OpenVINO-Custom-Layers/tree/master/2019.r2.0) for adding custom layers.

Hope this helps!

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.

**Comment by GotG** [comment]
Is this a naming problem? 
I see Minimum is supported here: https://docs.openvinotoolkit.org/latest/openvino_docs_ops_arithmetic_Minimum_1.html

**Comment by jgespino** [comment]
Hi @GotG 

Would it be possible to share your model to take a closer look?

Regards,
Jesus

**Comment by GotG** [comment]
Sure, here it is. Thanks!
https://drive.google.com/file/d/1gw9qU_VJbgGph7p8Xd4O6L_cBKwRte3W/view?usp=sharing

**Comment by jgespino** [comment]
Hi @GotG 

Thanks for sharing the model, the model includes Min Op for ONNX which is not supported on OpenVINO toolkit. The Minimum Op you shared is supported on OpenVINO for Tensorflow. See the list of [supported Operations](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html) based on Framework.

Regards,
Jesus

**Comment by GotG** [comment]
Thank you for clarifying.
