### ISSUE TITLE
convert Capsule Network to IR-openvino

### ISSUE THREAD

**Issue by TranThanh96** [openvinotoolkit/openvino#2814]
I am working with FSA-model using capsule network (https://github.com/shamangary/FSA-Net) for head-pose estimation purposes. I convert the model to the protocol buffer format successfully (.pb format). And now, I want to convert .pb format to IR format, but meet some issues: 
 `While validating node 'v0::Squeeze Squeeze_326(Transpose_324[0]:f32{3,64,64,16}, Constant_325[0]:i64{1}) -> (dynamic?)':
provided axis value is invalid. Only axes of size 1 may be removed.`
Can you support it? I can provide the .pb file.

**Comment by lazarevevgeny** [comment]
@TranThanh96 , thank you for filing the bug! Could you share the pb file for the analysis?

**Comment by TranThanh96** [comment]
I worked around my code and changed something.

when I convert a pb file -> IR format with the command: 

     `python mo_tf.py --input_model headpose_FSA.pb --input_shape '[1, 64, 64, 3]' -o FSA`

   converted successfully and I got file xml and bin.
   But when I test the IR model and loading from Inferinference_engine, an error occurred:

`RuntimeError: Check 'arg0_shape[axis_index_arg0].compatible(arg1_shape[axis_index_arg1])' failed at /home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu18/b/repos/closed-dldt/ngraph/src/ngraph/op/dot.cpp:130:
While validating node 'v0::Dot Dot_341(Reshape_338[0]:f32{64,21}, Reshape_340[0]:f32{16,21}) -> (dynamic?)':
Paired axes (axis 1 from arg0, axis 0 from arg1) do not have same length (arg0 shape: {64,21}, arg1 shape: {16,21}, reduction axes count: 1).`

I worked around and cut off some parts of my network to figure it out what is happening, and I found that: maybe, error when converting  batch_dot. The above error (`While validating node 'v0::Squeeze Squeeze_326(Transpose_324[0]:f32{3,64,64,16}, Constant_325[0]:i64{1}) -> (dynamic?)': provided axis value is invalid. Only axes of size 1 may be removed.`) occurred when I was investigating batch_dot ops.

You can access my pb file: https://drive.google.com/file/d/1FsuHPNypiE0FIZv0NBK6WO0qlsUmfKzI/view?usp=sharing

**Comment by lazarevevgeny** [comment]
@TranThanh96 , the fix has been merged as part of https://github.com/openvinotoolkit/openvino/pull/3159/. Please, verify
