### ISSUE TITLE
Supported primitive descriptors list is empty for node: ModCosh/cosh/Cosh

### ISSUE THREAD

**Issue by Surya1208** [openvinotoolkit/openvino#282]
Hi,
   I am getting the below :

u28225@c003-n222:~/10th-October/smart-video-workshop/custom-layer/extgen_output/user_ie_extensions/cpu/build$  /$HOME/inference_engine_samples_build/intel64/Release/classification_sample_async -i /opt/intel/openvino/deployment_tools/demo/car.png -m ../../../../create_tf_model/tf_model/model.ckpt.xml -d CPU -l ../../../../cl_ext_cosh/libcosh_cpu_extension.so
[ INFO ] InferenceEngine:
        API version ............ 1.6
        Build .................. custom_releases/2019/R1_c9b66a26e4d65bb986bb740e73f58c6e9e84c7c2
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     /opt/intel/openvino/deployment_tools/demo/car.png
[ INFO ] Loading plugin
[ INFO ] CPU Extension loaded: ../../../../cl_ext_cosh/libcosh_cpu_extension.so

        API version ............ 1.6
        Build .................. 22443
        Description ....... MKLDNNPlugin
[ INFO ] Loading network files
[ INFO ] Preparing input blobs
[ WARNING ] Image is resized from (787, 259) to (128, 128)
[ INFO ] Batch size is 1
[ INFO ] Preparing output blobs
[ INFO ] Loading model to the plugin
[ ERROR ] Supported primitive descriptors list is empty for node: ModCosh/cosh/Cosh
Segmentation fault (core dumped)

Can you please suggest me how to debug the above issue?

**Comment by shubha-ramani** [comment]
Dear @Surya1208 

First of all it looks like you are using an ancient version of OpenVino. API version ............ 1.6 is old !

Please kindly upgrade to 2019R3 which was recently released. Finally you can find the updated version of the cosh tutorial here also:

The OpenVINO workshop content on [github, https://github.com/intel-iot-devkit/smart-video-workshop ](github, https://github.com/intel-iot-devkit/smart-video-workshop )

Hope it helps,

Thanks,

Shubha

**Comment by stormy-sandy** [comment]
![d44](https://user-images.githubusercontent.com/37416806/71526980-4ce3f200-28ff-11ea-8592-e964cc919e0e.png)

I have version 2.1 adn still same error

**Comment by jgespino** [comment]
Closing, please re-open if assistance is still needed.
