### ISSUE TITLE
Multiple inputs

### ISSUE THREAD

**Issue by edwardnguyen1705** [openvinotoolkit/openvino#2886]
Dear openvino team,

I want to convert an `ONNX` [model](https://github.com/cleardusk/3DDFA_V2/blob/70e7cde4a893905c90bba08b66a69fae31917f07/bfm/bfm_onnx.py#L80) having multiple inputs to `OpenVINO`:
```
    dummy_input = torch.randn(3, 3), torch.randn(
        3, 1), torch.randn(40, 1), torch.randn(10, 1)
    R, offset, alpha_shp, alpha_exp = dummy_input
    torch.onnx.export(
        bfm_decoder,
        (R, offset, alpha_shp, alpha_exp),
        bfm_onnx_fp,
        input_names=['R', 'offset', 'alpha_shp', 'alpha_exp'],
        output_names=['output'],
        dynamic_axes={
            'alpha_shp': [0],
            'alpha_exp': [0],
        },
        do_constant_folding=True
    )
```

But, I do knot how to specify the parameter `input_shape`.
Do you have any suggestion?

**Comment by jgespino** [comment]
Hi @edwardnguyen1705 

Thanks for reaching out, please take a look at the [General Conversion Parameters](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html) for converting models.

> If there are multiple inputs in the model, --input_shape should contain definition of shape for each input separated by a comma, for example: [1,3,227,227],[2,4] for a model with two inputs with 4D and 2D shapes.

Hope this helps!

Regards,
Jesus

**Comment by edwardnguyen1705** [comment]
Dear @jgespino ,

I have successfully converted and inferenced the model. Thanks for your help.
