### ISSUE TITLE
How to build the opencv4.1.1 with the dldt on arm platform?

### ISSUE THREAD

**Issue by zhaozj0529** [openvinotoolkit/openvino#290]
How to build the opencv4.1.1 with the dldt on arm platform? THX

**Comment by shubha-ramani** [comment]
Dear @zhaozj0529 

Hopefully these online resources will help:
[https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend#raspbian-stretch](https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend#raspbian-stretch)

This one is not written by Intel but I find it's really helpful and written nicely.

[https://www.pyimagesearch.com/2019/04/08/openvino-opencv-and-movidius-ncs-on-the-raspberry-pi/](https://www.pyimagesearch.com/2019/04/08/openvino-opencv-and-movidius-ncs-on-the-raspberry-pi/)

Thanks ! Hope it helps,

Thanks,

Shubha
