### ISSUE TITLE
[Bug] GPU  inference bug in OpenVINO 2021.1

### ISSUE THREAD

**Issue by TNTWEN** [openvinotoolkit/openvino#2925]
Hello everyone!

https://github.com/TNTWEN/OpenVINO-YOLOV4

When I adapted this project to the latest openvino version, it seemed that GPU could not inference correctly under fp16

I've located the error .it's mish activation function： `activation_fn=lambda x:x* tf.math.tanh(tf.math.softplus(x))`
because yolov4-relu works well

Tensorflow1.15.4+OpenVINO2021.1
CPU +FP32/FP16 works well
GPU+FP32     works well
GPU+FP16    no bounding boxes!!

https://github.com/TNTWEN/OpenVINO-YOLOV4/issues/18

So I think it maybe a bug when GPU inferences FP16's  tanh and softplus function

**Comment by TNTWEN** [comment]
Note:
In OpenVINO2020r4 yolov4 is slower than yolov3 because of mish function
But OpenVINO2021.1+tf1.15.4 makes mish function faster.Now the speed of yolov4 is greatly indicated！
So i think OpenVINO2021.1 optimizes the implementation of mish（tanh and softplus)  activation function.
So I guess this is a bug in the GPU FP16 when optimizing the activation function

**Comment by LoSealL** [comment]
Could it be FP16 overflow?

**Comment by jgespino** [comment]
@Lyamin-Roman @vladimir-dudnik Could you please take a look at this issue?

**Comment by ritabugking** [comment]
Met the same problem when trying to run inference with OpenVINO 2021.1. any update on this issue?

**Comment by jgespino** [comment]
Hi @ritabugking 

Are you using the same model as the original post? If not, could you share your model and MO command used to reproduce?

Regards,
Jesus

**Comment by martinlyons** [comment]
Hi @jgespino 

I am having the same problem as well. I have a simple reproduction I can share with you. It reproduces the bug perfectly as described.

I'd prefer to share the files privately if you don't mind. My company is under an NDA with Intel so I have no problems in doing that.

**Comment by jgespino** [comment]
Hi @martinlyons 

Sure, please send me the files via email.

Regards,
Jesus

**Comment by jgespino** [comment]
Ref. 45001
