### ISSUE TITLE
how can I change the shape of input after I CreateInferRequest

### ISSUE THREAD

**Issue by jlygit** [openvinotoolkit/openvino#293]
how can I change the shape of input after I CreateInferRequest.
is the openvino support the Dynamic shape of the input node?

**Comment by elvin-nnov** [comment]
You can change only batch dimension on some plugins for some restricted networks calling InferRequest::SetBatch. 
There are number of limitations, please take a look into https://docs.openvinotoolkit.org/latest/_docs_IE_DG_DynamicBatching.html

For changing of arbitrary dimension, you will have to reshape original network loaded from IR using CNNNetwork::reshape and load to device one more time. You can take a look into https://github.com/opencv/dldt/tree/2019/inference-engine/samples/hello_reshape_ssd for example

**Comment by lazarevevgeny** [comment]
@jlygit OpenVINO does not support dynamic input shape. But you can change the inputs shapes using the "reshape" method described here https://docs.openvinotoolkit.org/2020.2/_docs_IE_DG_ShapeInference.html. Please, make sure that you convert your model with the Model Optimizer with command line parameter "--keep_shape_ops".

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issue is not actual as no response. Closing it. Feel free to reopen or better create a new one.
