### ISSUE TITLE
[Bug] The MyriadX USB NCS2 device re-enumerates while running demos

### ISSUE THREAD

**Issue by md-sami** [openvinotoolkit/openvino#2933]
##### System information (version)

- OpenVINO=>  2019.1.094
- Operating System / Platform => Linux 64 Bit Ubuntu 18.04 LTS
- Compiler => GCC 7.5.0
- Problem classification => USB re-connects while running demos (example demo_security_barrier_camera application)

##### Detailed description
 We attached the Myriad NCS2 on Ubuntu 18.04 and ran the demo_security_barrier_camera application.
The demo application runs successfully but we can see that the USB device re-connects at the start of the application and when the application is finished. 

##### Steps to reproduce
Install openvino from l_openvino_toolkit_p_2019.1.094.tgz

cd /opt/intel/openvino/deployment_tools/demo 

change target to MYRIAD in demo_security_barrier_camera.sh 

run the demo 

```
sudo ./demo_security_barrier_camera.sh 


dmesg when the NCS2 is attached on USB3.0  port:

[   56.522009] usb 1-1: new high-speed USB device number 3 using xhci_hcd
[   56.669291] usb 1-1: New USB device found, idVendor=03e7, idProduct=2485, bcdDevice= 0.01
[   56.669299] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   56.669304] usb 1-1: Product: Movidius MyriadX
[   56.669309] usb 1-1: Manufacturer: Movidius Ltd.
[   56.669313] usb 1-1: SerialNumber: 03e72485

dmesg when the  demo_security_barrier_camera is running. 
[  236.377012] usb 1-1: USB disconnect, device number 3
[  236.721758] usb 2-1: new SuperSpeed Gen 1 USB device number 2 using xhci_hcd
[  236.742376] usb 2-1: New USB device found, idVendor=03e7, idProduct=f63b, bcdDevice= 1.00
[  236.742378] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  236.742380] usb 2-1: Product: VSC Loopback Device
[  236.742381] usb 2-1: Manufacturer: Intel Corporation
[  236.742383] usb 2-1: SerialNumber: 3044FC1071D1C4BA00
[  242.671571] usb 2-1: USB disconnect, device number 2
[  242.853226] usb 1-1: new high-speed USB device number 4 using xhci_hcd
[  243.001703] usb 1-1: New USB device found, idVendor=03e7, idProduct=2485, bcdDevice= 0.01
[  243.001706] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  243.001708] usb 1-1: Product: Movidius MyriadX
[  243.001709] usb 1-1: Manufacturer: Movidius Ltd.
[  243.001711] usb 1-1: SerialNumber: 03e72485

```
 
Note: 
1) the same issue is observed with the benchmark_app demo. 
2) the same issue is observed with the latest toolkit (commit id: ac65ea30fd90ec04bcf9a3c326f846d8f86f516d )
Please find the log of the application attached. 

Expectation:
The device should not re-connect every time we run the demo application. 

[usb_reenumeration_issue.txt](https://github.com/openvinotoolkit/openvino/files/5472388/usb_reenumeration_issue.txt)

**Comment by brmarkus** [comment]
This is expected behavior with NCS2 on USB bus. It first appears as USB2 High-Speed device, then disappears and appears again as USB3 SuperSpeed device "VSC Loopback Device". When the application exists gracefully it turns into USB2 as a HighSpeed device again.

**Comment by md-sami** [comment]
Is there some way that you can force into USB2.0 mode only (or USB3.0 mode only ) all the time and avoid this re-enumeration / switching during the demo? Is there an updated firmware for NCS2 that achieves the above?

**Comment by brmarkus** [comment]
Not that I'm aware of - this happens due to loading the firmware once and then "starting the device".
Could you make your application a kind of daemon, which loads the MYRIAD plugin once, and keeps it for as long as you would need the MyriadX "ready"?

**Comment by md-sami** [comment]
Hi @brmarkus , I am using the `security_barrier_camera_demo` app and as per your comment I need to run this app like a daemon . Can you please provide me insight on running the `security_barrier_camera_demo` as a daemon to load MYRIAD plugin once, and keep it ready to avoid this re-enumeration?

**Comment by md-sami** [comment]
hi @brmarkus , Is there some way of delaying after loading the network before going to the run phase? 
Can you point us to the code where the LoadNetwork opens the USB device? Where in the code does it handle the device re-enumeration.  We are using the device via usbip, and as a consequence, it is slow. If there is no support for usbip, could you point us into the code where the device is re-enumerated? Is there any time delays you have in the code for slow devices? 
Are there any options in openvino to support such a slow USB interface? We are finding that LoadNetwork doesn't return due to disconnect. We get the error "Failed to find booted device after boot".
Perhaps there is a race condition between the software and the USB stick. Could you please give us pointers in the code where we would need to modify it to support a slow USB interface? 

What are the steps during the loadNetwork (what data elements loaded into the USB device)? 

What do I need to modify to enable the source-level debugging?
Is there any way to build openvino with the device reset disabled? How to enable the NO_BOOT mode?

**Comment by jgespino** [comment]
Hi @md-sami 

Please take a look at the [source code](https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/thirdparty/movidius) for the Myriad Plugin.

Regards,
Jesus
