### ISSUE TITLE
[Bug] Linking error on raspberry 4, undefined reference to __atomic_fetch_add_8 

### ISSUE THREAD

**Issue by deb-dsc20** [openvinotoolkit/openvino#2956]
##### System information (version)
- OpenVINO => Git clone from master (comit id  3f4d8b49ff6e3f8e7e039c4075e45cab53e55ebe)
- Operating System / Platform => Raspbian on raspberry pi 4
- Compiler => Cmake, gcc, etc
- Problem classification: Build issue

##### Detailed description
Facing following build issue:
[ 12%] Built target ngraph
[ 16%] Built target libprotobuf
[ 20%] Built target libprotoc
[ 20%] Linking CXX executable ../../../bin/armv7l/Release/protoc
/usr/bin/ld: ../../../bin/armv7l/Release/lib/libprotobuf.a(arena.cc.o): in function `google::protobuf::internal::ArenaImpl::Init()':
arena.cc:(.text._ZN6google8protobuf8internal9ArenaImpl4InitEv+0x2c): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [_deps/ext_protobuf-build/CMakeFiles/protoc.dir/build.make:87: ../bin/armv7l/Release/protoc-3.7.1.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:1454: _deps/ext_protobuf-build/CMakeFiles/protoc.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

##### Steps to reproduce
- Run ./install_build_dependencies.sh
- mkdir build; cd build
- cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_SSE42=OFF -DTHREADING=SEQ  -DTHREADS_PTHREAD_ARG="-pthread" -DENABLE_GNA=OFF ..
- make

**Comment by dkurt** [comment]
Please take a look on similar issue: https://github.com/opencv/opencv/issues/15278#issuecomment-521903165

**Comment by deb-dsc20** [comment]
Thanks dkurt.
By adding -latomic in external_protobuf.cmake, Linking error was resolved. Build was successfull.
Attaching the file
[external_protobuf.zip](https://github.com/openvinotoolkit/openvino/files/5491891/external_protobuf.zip)
