### ISSUE TITLE
Question on how to use an HDDL device inside a docker container with OpenVINO 2020.4

### ISSUE THREAD

**Issue by fabianoboril** [openvinotoolkit/openvino#2962]
##### System information (version)
- OpenVINO => 2020.4
- Operating System / Platform => Ubuntu 18.04

##### Detailed description
We are running a docker container (based on Ubuntu 18.04) on a host system with Ubuntu 18.04. The host system is prepared to run the hddldaemon. Note that inference with using the HDDL device is successful on the host system. Now, we want to use the HDDL device inside the docker. However, when we start our gstreamer pipeline that refers to the HDDL device, we always get the following errors:

> [18:06:23.6103][805]ERROR[GlobalMutex_linux.cpp:23] Error: Open GlobalMutex /var/tmp/hddl_start_exit.mutex failed. errno = 13 [Permission denied]
> [18:06:23.6103][805]ERROR[GlobalMutex_linux.cpp:23] Error: Open GlobalMutex /var/tmp/hddl_service_alive.mutex failed. errno = 13 [Permission denied]
> [18:06:23.6103][805]ERROR[GlobalMutex_linux.cpp:23] Error: Open GlobalMutex /var/tmp/hddl_service_ready.mutex failed. errno = 13 [Permission denied]
> [18:06:23.6104][805]ERROR[GlobalMutex_linux.cpp:23] Error: Open GlobalMutex /var/tmp/hddl_service_failed.mutex failed. errno = 13 [Permission denied]
> [18:06:23.6104][805]ERROR[GlobalMutex_linux.cpp:45] Error: GlobalMutex /var/tmp/hddl_start_exit.mutex is not initialized.
> [18:06:23.6104][805]ERROR[ServiceStarter.cpp:117] Error: Lock StartExitMutex:/var/tmp/hddl_start_exit.mutex failed. errno = 13 [Permission denied]
> [18:06:23.6104][805]ERROR[ServiceStarter.cpp:30] Error: Failed to start HDDL Service
> [18:06:23.6104][805]ERROR[HddlClient.cpp:256] Error: Failed to boot service.
> 
> ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin intitialization failed
> Additional debug info:
> /root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(136): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:
> 
> Failed to construct OpenVINOImageInference
>  _client->query(QUERY_TYPE_DEVICE, &query) failed: HDDL_NOT_INITIALIZED
> 
> Execution ended after 0:00:00.369878927
> Setting pipeline to PAUSED ...
> Setting pipeline to READY ...
> Setting pipeline to NULL ...
> Freeing pipeline ...

The error itself can be understood easily, as the access permissions of all files under /var/tmp/hddl_* are 660 (i.e. user + group can read/write the files), and the user in the docker container is different to the host system user. A workaround is to change the permissions, which however feels not right.

Next, we then get the following errors:

> [HDDLPlugin] [18:16:08.5901][1251]W[Dispatcher2.cpp:115] Warning: Try to connect to service (socket: /var/tmp/hddl_service.sock) for 0-th time, failed. errno = 2[No such file or directory]
> [HDDLPlugin] [18:16:09.5903][1251]W[Dispatcher2.cpp:115] Warning: Try to connect to service (socket: /var/tmp/hddl_service.sock) for 1-th time, failed. errno = 2[No such file or directory]
> [HDDLPlugin] [18:16:10.5906][1251]W[Dispatcher2.cpp:115] Warning: Try to connect to service (socket: /var/tmp/hddl_service.sock) for 2-th time, failed. errno = 2[No such file or directory]
> Redistribute latency...
> [HDDLPlugin] [18:16:11.5908][1251]ERROR[Dispatcher2.cpp:121] Error: Can not connect to service (socket: /var/tmp/hddl_service.sock). errno = 2[No such file or directory]
> WARNNING: errorWithException() replacing existing terminate_handler!!!
> error at /home/jenkins/agent/workspace/IE-Packages/BuildAndPush/hddl-service/utils/platform/linux/IPCLinux.cpp:272
>         invalid argument: m_fd=-1 buffer=0x7efe9bbc3dec bufferSize=4
> [HDDLPlugin] [18:16:11.5912][1447]ERROR[hddl_protocol.cpp:228] invalid argument: m_fd=-1 buffer=0x7efe9bbc3dec bufferSize=4
> [HDDLPlugin] [18:16:11.5912][1447]ERROR[Dispatcher2.cpp:191] [Sender] Send request 0 failed
> [HDDLPlugin] [18:16:11.5913][1251]ERROR[HddlClient.cpp:317] Error: emit registerClient [HDDLPlugin] failed.
> [HDDLPlugin] [18:16:11.5914][1251]ERROR[HddlClient.cpp:1106] Error: dispatcher send request failed
> [HDDLPlugin] [18:16:11.5914][1251]ERROR[HddlClient.cpp:342] Error: emit unregisterClient [HDDLPlugin] failed.
> ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin intitialization failed
> Additional debug info:
> /root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(136): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:
> 
> Failed to construct OpenVINOImageInference
>  _client->query(QUERY_TYPE_DEVICE, &query) failed: HDDL_CONNECT_ERROR
> 
> Execution ended after 0:00:03.655604265

However, the sock file is there, and /var/tmp is mounted as described here:
https://github.com/openvinotoolkit/openvino/blob/cf5055745a4b625ab62580b87512f39e39814a70/docs/install_guides/installing-openvino-docker-linux.md

Has anybody an idea, of how to proceed here?

**Comment by brmarkus** [comment]
From the documentation:
```
NOTE:
* When building docker images, create a user in the docker file that has the same UID and GID as the user which runs hddldaemon on the host.
* Run the application in the docker with this user.
```

Does mounting the volume like this `-v /var/tmp:/var/tmp:rw` makes a difference?

**Comment by fabianoboril** [comment]
The problem is that we are using our containers in a company setup, i.e. the user accounts are managed through ldap and have unique IDs. The container itself has its own user. Hence, passing userids wouldn't help in our case.

**Comment by fabianoboril** [comment]
I continued testing using the `-v /var/tmp:/var/tmp:rw` instead of `-v /var/tmp:/var/tmp` and manually modifying the access rights for /var/tmp/hddl_*.

Now, gstreamer using the HDDL device for inference starts inside the docker container. However, the hddldaemon running outside, starts to throw the following errors:

> [08:22:10.8565][4468]I[main.cpp:106] SERVICE IS READY ...
> [08:28:01.7435][4780]I[ClientManager.cpp:159] client(id:1) registered: clientName=HDDLPlugin socket=2
> [08:28:12.8972][4781]I[GraphManager.cpp:491] Load graph success, graphId=1 graphName=frozen_darknet_yolov3_model
> [08:28:12.9953][6810]ERROR[ShareMemory_linux.cpp:57] Error: shm_open() failed: errno=2 (No such file or directory)
> 
> [08:28:12.9953][6810]ERROR[HddlMyriadXDevice.cpp:1370] Error: share memory buffer('hddl_280_139709010683648_0') mapping failed
> [08:28:12.9954][6810]ERROR[HddlMyriadXDevice.cpp:649] Error: map inputTensor failed, device=16.2 taskId=1
> [08:28:12.9954][6810]ERROR[SlaveWorker.cpp:181] [Wt16.2S0] Error: loadTensor(1) failed, rc=-118
> [08:28:12.9954][6810]I[SlaveWorker.cpp:282] [Wt16.2S0] Return task(1) to TaskManager, loadCount=1 error=-118

**Comment by brmarkus** [comment]
Can you try to stop the daemon, then `source /opt/intel/openvino/bin/setupvars.sh` and `${HDDL_INSTALL_DIR}/bin/bsl_reset` (with your installation on the HOST) (as described under `https://docs.openvinotoolkit.org/2019_R2/_docs_install_guides_installing_openvino_linux_ivad_vpu.html#unable_to_run_inference_with_the_myriad_plugin_after_running_with_the_hddl_plugin`?
You said on the HOST-side HDDL is working and inferences are working? So you have the UDEV rules in place?
Your current user is included in the users groups?

Can you try to start the container with `--privileged` to see whether there is anything user-rights/permission related missing? Do you start the container with your user (being added to the docker group) or with `sudo`?

**Comment by fabianoboril** [comment]
> You said on the HOST-side HDDL is working and inferences are working? So you have the UDEV rules in place?
> Your current user is included in the users groups?
Yes and Yes

**Comment by fabianoboril** [comment]
> Can you try to stop the daemon, then source /opt/intel/openvino/bin/setupvars.sh and ${HDDL_INSTALL_DIR}/bin/bsl_reset (with your installation on the HOST)

Tested and has no effect.

> Can you try to start the container with `--privileged` to see whether there is anything user-rights/permission related missing? Do you start the container with your user (being added to the docker group) or with `sudo`?

The user is in the docker group (no sudo required), and  `--privileged` has no effect.

**Comment by fabianoboril** [comment]
Hi all,
I found a solution to this problem :)
Since we use a different user in the docker container, it is important to add the docker user to the "users" group (inside the container). As a result, we can start the hddldaemon on the host side with our normal user (which is not the docker user), but who is part of the users group. Then we start the container with `--privileged--device=/dev/ion:/dev/ion -v /var/tmp:/var/tmp `, and start gstreamer and it works :)
Thank you all for the tipps.
