### ISSUE TITLE
How to run the image classification

### ISSUE THREAD

**Issue by cezane** [openvinotoolkit/openvino#2975]
It seems the section "Run the Image Classification Sample Application" is outdated. The first step says "Go to the samples build directory" with the following command `cd <OPENVINO_DIR>/inference-engine/bin/intel64/Release`. As we can see below, there is no such directory:

```
/workspace/openvino/inference-engine$ ls
cmake           ie_bridges  samples  src   tests             thirdparty
CMakeLists.txt  include     scripts  temp  tests_deprecated  tools
```

How to proceed with the tutorial "Get Started with OpenVINO™ Toolkit on Linux*"?

**Comment by cezane** [comment]
I searched my directories for `intel64/Release` and found this folder in the following path `/openvino/bin/intel64/Release` which is not located at the `inference-engine` folder as pointed by the tutorial.

Then, I run the recommended command and got the following error:

```
/workspace/openvino/bin/intel64/Release$ ./classification_sample_async -i ../../../scripts/demo/car.png -m ../../../ir_dir/squeezenet1.1.xml -d CPU
[ INFO ] InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_master_1e67eaf03099d613f05c8b351345fb6e5eaddd08
	Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     ../../../scripts/demo/car.png
[ INFO ] Creating Inference Engine
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... custom_master_1e67eaf03099d613f05c8b351345fb6e5eaddd08

[ INFO ] Loading network files
[ INFO ] Preparing input blobs
[BMP] file is not bmp type
[ WARNING ] Image ../../../scripts/demo/car.png cannot be read!
[ ERROR ] Valid input images were not found!
```

According to the received message, I searched for a `bmp` file in the `demo` folder, finding the `car_1.bmp`. But I got the following error:

```
/workspace/openvino/bin/intel64/Release$ ./classification_sample_async -i ../../../scripts/demo/car_1.bmp -m ../../../ir_dir/squeezenet1.1.xml -d CPU
[ INFO ] InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_master_1e67eaf03099d613f05c8b351345fb6e5eaddd08
	Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     ../../../scripts/demo/car_1.bmp
[ INFO ] Creating Inference Engine
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... custom_master_1e67eaf03099d613f05c8b351345fb6e5eaddd08

[ INFO ] Loading network files
[ INFO ] Preparing input blobs
[ WARNING ] Image won't be resized! Please use OpenCV.
[ ERROR ] Valid input images were not found!
```
How to deal with this? Is there some updated documentation?

**Comment by ilyachur** [comment]
@mryzhov Could you take a look?

**Comment by jgespino** [comment]
Hi @cezane 

Thanks for reporting, we will definelty need to update our documentation as the [Get Started with OpenVINO™ Toolkit on Linux*](https://github.com/openvinotoolkit/openvino/blob/master/get-started-linux.md#run-the-image-classification-sample-application) is outdated. 

I tested on my OpenVINO build and did not run into the error you are seeing. I will rebuild with the latest Master branch and test again.

```
[ WARNING ] Image won't be resized! Please use OpenCV.
[ ERROR ] Valid input images were not found!
```

How did you build OpenVINO? Could you provide your cmake command? Did you enable python?

Regards,
Jesus

**Comment by jgespino** [comment]
@cezane I've submitted a pull request to update the get-started-linux documentation.
See https://github.com/openvinotoolkit/openvino/pull/3016

Regards,
Jesus

**Comment by cezane** [comment]
Is there some suggestion regarding the problems (png and bmp) found when executing the inference model?

**Comment by jgespino** [comment]
@cezane I did not run into this problem when I tested with the latest master branch last week. How did you build OpenVINO? Could you provide your cmake command? Did you enable python?

**Comment by cezane** [comment]
To build OpenVINO, I followed the following instructions: https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md

Here is the `cmake` command: `cmake -DCMAKE_BUILD_TYPE=Release ..`

**Comment by jgespino** [comment]
@cezane I believe I was able to reproduce your issue on master branch. It seems the `<OPENVINO_DIR>/scripts/demo/car.png` is corrupted after the build. Could you check if you can open it from the file explorer? 

Try downloading it manually from here and see if the demo works for you.
https://github.com/openvinotoolkit/openvino/blob/master/scripts/demo/car.png

Regards,
Jesus

**Comment by cezane** [comment]
Hi, @jgespino . I downloaded the car.png image, but the same problem occurs:

```
./classification_sample_async -i ../../../scripts/demo/car.png -m ../../../ir_dir/squeezenet1.1.xml -d CPU
[ INFO ] InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_master_1e67eaf03099d613f05c8b351345fb6e5eaddd08
	Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     ../../../scripts/demo/car.png
[ INFO ] Creating Inference Engine
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... custom_master_1e67eaf03099d613f05c8b351345fb6e5eaddd08

[ INFO ] Loading network files
[ INFO ] Preparing input blobs
[BMP] file is not bmp type
[ WARNING ] Image ../../../scripts/demo/car.png cannot be read!
[ ERROR ] Valid input images were not found!
```
It also occurs with the car_1.bmp image:
```
./classification_sample_async -i ../../../scripts/demo/car_1.bmp -m ../../../ir_dir/squeezenet1.1.xml -d CPU
[ INFO ] InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_master_1e67eaf03099d613f05c8b351345fb6e5eaddd08
	Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     ../../../scripts/demo/car_1.bmp
[ INFO ] Creating Inference Engine
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... custom_master_1e67eaf03099d613f05c8b351345fb6e5eaddd08

[ INFO ] Loading network files
[ INFO ] Preparing input blobs
[ WARNING ] Image won't be resized! Please use OpenCV.
[ ERROR ] Valid input images were not found!
```

**Comment by jgespino** [comment]
Hi @cezane 

This is very strange, I thought it may be with the openvino commit you are using. However, I tested on that same commit and the sample works as expected with both .png and .bmp files. 

The error you are seeing with the .png image was fixed for me by re-download the .png as it was corrupted in this commit too. These are the commands I used:

```
cd <OPENVINO_DIR>/scripts/demo
mv car.png car.png.org
wget https://github.com/openvinotoolkit/openvino/raw/master/scripts/demo/car.png
cd <OPENVINO_DIR>/bin/intel64/Release
./classification_sample_async ../../../scripts/demo/car.png -m <ir_dir>/squeezenet1.1.xml -d CPU
```

I am not able to reproduce your second error:
```
[ WARNING ] Image won't be resized! Please use OpenCV.
[ ERROR ] Valid input images were not found!]
```
Do you have another system that you can test on?

Regards,
Jesus

**Comment by mryzhov** [comment]
Sorry for the late answer, we can face such problems with bmp or png images when building samples without OpenCV.
@cezane could you please check CmakeCache:
//enables OpenCV
ENABLE_OPENCV:BOOL=ON

It may be disabled manually or OpenCV was not found on the system (cmake should throw a warning about that)

**Comment by cezane** [comment]
Hello, @mryzhov . I did not find the cmakecache file here. Is there another option?

**Comment by mryzhov** [comment]
@cezane it should be in build directory when you did cmake build.  
You can check if compiled samples are linked with opencv using the ldd command: 
`ldd ./classification_sample_async | grep opencv `

**Comment by cezane** [comment]
Thank you, @mryzhov . I found the CMakeCache.txt file. OpenCV is enabled:
```
//enables OpenCV
ENABLE_OPENCV:BOOL=ON
```
But the compiled samples are not linked. The output of `ldd ./classification_sample_async | grep opencv` is empty.

**Comment by mryzhov** [comment]
@cezane, thanks for the info, then cmake could not find the OpenCV.  Could you please verify that OpenCV libs were downloaded by cmake configure here:
<openvino_sources>/inference-engine/temp/opencv_4.5.0 
btw, what OS do you use?

**Comment by cezane** [comment]
The OpenCV libs were not downloaded:
```
~/workspace/openvino$ ls inference-engine/temp/
download/            tbb/                 
gna_02.00.00.1047.1/ vpu/
```

I am using Ubuntu 18.04.

**Comment by mryzhov** [comment]
Yeh, that is the reason( Could you please create the new build directory, run cmake configure there one more time and send the log?

**Comment by cezane** [comment]
@mryzhov solved after a new build. Thank you.

**Comment by zengjie617789** [comment]
what about if I use the latest compild package `openvino_toolkit_windows_2025.2.0.19140.c01cd93e24d_x86_64` which has not build options?
Futhermore, I found the USE_OPENCV option in source file which default is false.
```
#ifdef USE_OPENCV
Register<OCVReader> OCVReader::reg;
#else
Register<BitMap> BitMap::reg;
#endif 
```
