### ISSUE TITLE
Error Compiling 

### ISSUE THREAD

**Issue by sgriset** [openvinotoolkit/openvino#299]
When compiling dldt repository i get a fatal error see below

/home/pi/dldt/inference-engine/build/ie_bridges/python/src/openvino/tools/statistics_collector/statistics_collector_api.cxx:617:10: fatal error: statistics_processor.hpp: No such file or directory
 #include <statistics_processor.hpp>
  
I use the following CMAKE commands 
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_SSE42=OFF -DTHREADING=SEQ -DENABLE_GNA=OFF -DENABLE_OPENCV=OFF -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3.7 -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 ..

This is being compiled on raspberry 4 buster OS

**Comment by lwhuq** [comment]
same me in ubuntu18.4 with below command

cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENCV=OFF -DENABLE_CLDNN=OFF -DENABLE_MYRIAD=OFF -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=`which python3.6` -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 ..

**Comment by blackantywj** [comment]
> same me in ubuntu18.4 with below command
> 
> cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENCV=OFF -DENABLE_CLDNN=OFF -DENABLE_MYRIAD=OFF -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=`which python3.6` -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 ..

I'm running your commands on jetson nano, and I've corrected some of the paths according to my system, but it still doesn't work.

**Comment by guischmitd** [comment]
Just had the same problem while compiling on a Raspberry Pi 4 4GB running Raspbian Buster OS.
These are the cmake flags I used:
````
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_SSE42=OFF -DTHREADING=SEQ -DENABLE_GNA=OFF -DENABLE_OPENCV=OFF -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3.7 -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 ..
```

My full cmake and make outputs are in this pastebin:
https://pastebin.com/ixCahpbj

**Comment by BB142** [comment]
The statistics_collector subdirectory is only added when opencv is enabled.
So if you use the cmake flag -DENABLE_OPENCV=OFF 
go to dldt/inference-engine/tools open the CMakeLists.txt and change:
if (ENABLE_OPENCV)
     add_subdirectory(calibration_tool/statistics_collector)
endif()
to:
add_subdirectory(calibration_tool/statistics_collector)
and save. Now the subdirectory is allways added and make should work

**Comment by sgriset** [comment]
Thank you for the update and I will test today and tomorrow and get back to you

**Comment by lazarevevgeny** [comment]
@sgriset is this issue actual?

**Comment by ilya-lavrenov** [comment]
@sgriset @BB142 the `statistics_collector` tool has been removed. I've tried to compile with `-DENABLE_OPENCV=OFF` and have not found any new issues. Closing as revolsed.
