### ISSUE TITLE
Yolov5 Model conversion error [Bug]

### ISSUE THREAD

**Issue by manumenon** [openvinotoolkit/openvino#2992]
This issue : https://github.com/ultralytics/yolov5/issues/891
![image](https://user-images.githubusercontent.com/25078680/98273280-17e10b00-1fb8-11eb-8c65-1b78bac31203.png)

**Comment by jgespino** [comment]
Hi @manumenon 

Thanks for reaching out, please provide your yolov5s.onnx file and Model Optimizer command used.

Regards,
Jesus

**Comment by jgespino** [comment]
@manumenon Do you still need assistance or can we close this issue?
