### ISSUE TITLE
[Bug] Caffe: convert xxx.prototxt failed !!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by ladyxuxu** [openvinotoolkit/openvino#3023]
"Error(str(e).replace('<SUB-ELEMENT>', '{} (id = {})'.format(node.soft_get('name'), node.id))) from emo.utils.error
Error: Error while emitting attributes for layer layer1_bn/variance/Fused_Add_ (id = 4). It usually means that there is unsupported pattern around this node or unsupported combination of attributes."

can you help me and give me some directions ?

**Comment by ladyxuxu** [comment]
commond is : python mo.py  --input_model D:\belt.caffemodel --input_proto D:\belt.prototxt

**Comment by jgespino** [comment]
Hi @ladyxuxu 

Could you share your model? Also, what version of OpenVINO are you using?

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.

**Comment by meifannao** [comment]
> Closing, please re-open if additional assistance is needed.

I have a similar problem, do you have a solution

### MO ERROR
[ ERROR ]  Error while emitting attributes for layer Resize_1/Mul_ (id = 4). It usually means that there is unsupported pattern around this node or unsupported combination of attributes.

OpenVINO VIsion : 2021.2.185

command  python mo_onnx.py --input_model  C:\Users\meifannao\source\repos\openvino_rvm\x64\Release\epoch-81.onnx --output_dir "C:\Users\meifannao\source\repos\openvino_rvm\x64\Release"

### Model Input

![image](https://user-images.githubusercontent.com/58097859/164954267-f431da47-3038-49aa-8cf9-dce6af66f935.png)
