### ISSUE TITLE
Cannot find JTAG cable. Aborting installation.

### ISSUE THREAD

**Issue by NSVR57** [openvinotoolkit/openvino#3028]
Hi,
I am trying to setup FPGA installation in azure VM. My azure VM comes with intel Arria 10 card. when i tried to run FPGA_install.sh I am getting the following error.

```
root@azlwu2testvm01:/home/azureuser# source fpga_install.sh
Found a compatible OS.
Intel FPGA Download Cable Driver is installed.
+--------------------------------------------------------+
| OpenVINO FPGA Environment Setup Script |
+--------------------------------------------------------+
Using the QUARTUS_ROOTDIR value: /home/azureuser/intelFPGA/18.1/qprogrammer/bin/bin
Using INTELFPGAOCLSDKROOT value: /opt/altera/aocl-pro-rte/aclrte-linux64
INTELFPGAOCLSDKROOT is set to /opt/altera/aocl-pro-rte/aclrte-linux64. Using that.

aoc was not found, but aocl was found. Assuming only RTE is installed.

AOCL_BOARD_PACKAGE_ROOT is set to /opt/altera/aocl-pro-rte/aclrte-linux64/board/a10_1150_sg1. Using that.
Adding /opt/altera/aocl-pro-rte/aclrte-linux64/bin to PATH
Adding /opt/altera/aocl-pro-rte/aclrte-linux64/linux64/lib to LD_LIBRARY_PATH
Adding /opt/altera/aocl-pro-rte/aclrte-linux64/host/linux64/lib to LD_LIBRARY_PATH
Adding /opt/altera/aocl-pro-rte/aclrte-linux64/board/a10_1150_sg1/linux64/lib to LD_LIBRARY_PATH
[setupvars.sh] OpenVINO environment initialized
Creating initialization script /home/azureuser/init_openvino.sh ...
Installing the new OpenCL BSP for the 2020.1 BSP. Enter Y when prompted to install (Enter sudo credentials when prompted):
Cannot find board_env.xml in /opt/altera/aocl-pro-rte/aclrte-linux64/board/a10_1150_sg1
Cannot find JTAG cable. Aborting installation.
```

**Comment by jgespino** [comment]
Hi @NSVR57 

What version of OpenVINO toolkit and OS are you using? What is the exact model of the FPGA card? 

We have two available guides depending on the type of FPGA card that you are using.
[Configuration Guide for the Intel® Distribution of OpenVINO™ toolkit 2020.3 and the Intel® Vision Accelerator Design with an Intel® Arria® 10 FPGA SG2 (IEI's Mustang-F100-A10) on Linux*
](https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_VisionAcceleratorFPGA_Configure.html)

[Configuration Guide for Intel® Distribution of OpenVINO™ toolkit 2020.3 and the Intel® Programmable Acceleration Card with Intel® Arria® 10 FPGA GX on CentOS or Ubuntu*](https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_PAC_Configure.html)

Regards,
Jesus

**Comment by NSVR57** [comment]
Hi @jgespino 

OS version: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1031-azure x86_64)

I am using https://docs.openvinotoolkit.org/2019_R1.1/_docs_install_guides_GX_Configure_2019R1.html. I am able to install Quartus prime software, able to get jtagconfig verision.

**Comment by jgespino** [comment]
Hi @NSVR57 

Same feedback as your other post, what is the exact card that you are using? What version of OpenVINO toolkit are you using? It looks like you are following the guide for version 2019 R1.1 but in your other post you are following version 2018 R5. 

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, will continue troubleshooting here:
https://github.com/openvinotoolkit/openvino/issues/3051
