### ISSUE TITLE
Undefined symbol: _ZN15InferenceEngine7details14CNNNetworkImplC1ERKNS_11ICNNNetworkE

### ISSUE THREAD

**Issue by dipendra009** [openvinotoolkit/openvino#3047]
I have installed openvino 2021.1.110 from source using the build instruction provided on OpenVino Installation site. Although I can import openvino, I am not able to import inference engine due to the following error, could you please let me know what's the issue? 

ImportError                               Traceback (most recent call last)
<ipython-input-7-cee3ca61adb9> in <module>
----> 1 from openvino.inference_engine import IECore
      2 device='CPU'

/opt/intel/openvino_2021/python/python3.6/openvino/inference_engine/__init__.py in <module>
----> 1 from .ie_api import *
      2 __all__ = ['IENetwork', "TensorDesc", "IECore", "Blob", "PreProcessInfo", "get_version"]
      3 __version__ = get_version()
      4 

ImportError: /opt/intel/openvino_2021/python/python3.6/openvino/inference_engine/ie_api.so: undefined symbol: _ZN15InferenceEngine7details14CNNNetworkImplC1ERKNS_11ICNNNetworkE

**Comment by jgespino** [comment]
Hi @dipendra009 

Looking at the import error message, it looks like it's pointing to the Intel Distribution of OpenVINO install not built from source. Did you source your environment variables for the Intel Distribution of OpenVINO prior to using the open source? 

Try specifying the environment variables as specified in step 2 of this guide:
https://www.intel.com/content/www/us/en/support/articles/000057448/software/development-software.html

Regards,
Jesus

Regards,
Jesus

**Comment by dipendra009** [comment]
Hi Jesus,
Actually, I followed the instructions from https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html. It seems to work fine while I run from terminal in a docker, but it does not work when I am trying to import in Juyter lab. Also, there is no python library for python3.8, it builds for python3.6. How do I change it during installation so that I can import it in python3.8?

**Comment by jgespino** [comment]
Hi @dipendra009 

I don't believe the Intel Distribution of OpenVINO toolkit includes python libraries for Python 3.8, I will double-check and confirm. You should be able to import OpenVINO to Jupyter lab by sourcing the environment variables before running jupyter lab. 

`source /opt/intel/openvino_2021/bin/setupvars.sh`

Regards,
Jesus

**Comment by dipendra009** [comment]
Thank you, I was able to solve this issue by using same python during building and in jupyter lab.
