### ISSUE TITLE
How To do : Unplug and replug the Micro-USB  cable from the Intel Arria 10 GX board for JTAG. In Virtual environment.

### ISSUE THREAD

**Issue by NSVR57** [openvinotoolkit/openvino#3051]
Hi 

Currently,  I have azure VM with Intel Arria 10 GX. I tried to configure openvino, while following the steps from the following link `https://docs.openvinotoolkit.org/2018_R5/_docs_install_guides_installing_openvino_linux_fpga.html`, its asked me to unplug-replug usb, how once can do that in VM's.

Is this really possible to configure in vm's?

**Comment by jgespino** [comment]
Hi @NSVR57 

In order to give you an accurate response, we need to know the exact card that you are using. Is it a A10 dev kit? If that is the case, OpenVINO toolkit 2018 R5 version does not have support for it.

Regards,
Jesus

**Comment by NSVR57** [comment]
Hi 

I am currently using Arria10 (PCIe) in azure with a VM.  Its was mentioned as PB6s family with 112 GiB RAM. I have tried 2019.R1.1 version as well. but  no luck.

**Comment by jgespino** [comment]
Hi @NSVR57 

Do you have the exact model number? There are multiple Arria 10 PCe cards, here are a couple:

1. IEI Technology Mustang-F100-A10 AI Accelerator Card (https://www.ieiworld.com/mustang-f100/en/)
2. Intel® Programmable Acceleration Card with Intel Arria® 10 GX FPGA (https://www.intel.com/content/www/us/en/programmable/products/boards_and_kits/dev-kits/altera/acceleration-card-arria-10-gx/overview.html )
3. Arria® 10 GX FPGA Development Kit (https://www.intel.com/content/www/us/en/programmable/products/boards_and_kits/dev-kits/altera/kit-a10-gx-fpga.html )

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
