### ISSUE TITLE
Cmake error on RPI 4

### ISSUE THREAD

**Issue by JVTEAM** [openvinotoolkit/openvino#307]
CMake Error at thirdparty/CMakeLists.txt:49 (add_subdirectory):
  The source directory

    /home/pi/dldt/inference-engine/thirdparty/ade

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  thirdparty/CMakeLists.txt:58 (build_with_lto)

**Comment by brmarkus** [comment]
Have you initialized the submdules ("git submodule update --init --recursive")?

**Comment by JVTEAM** [comment]
clearly not!  thank you

**Comment by ilya-lavrenov** [comment]
Closing as resolved
