### ISSUE TITLE
Document link is error [Bug]

### ISSUE THREAD

**Issue by wangzhenyu32** [openvinotoolkit/openvino#3070]
https://docs.openvinotoolkit.org/latest/omz_models_public_resnet_50_tf_resnet_50_tf.html

the link  "freeze_saved_model.py" can not be found

**Comment by avitial** [comment]
@wangzhenyu32 thanks for reporting this, I am able to see the broken link. In the meantime, you can get the [freeze_saved_model.p](freeze_saved_model)y script from the Open Model Zoo repo.

Regards,
Luis

Ref. 43021
