### ISSUE TITLE
Error using webcam for text detection demo

### ISSUE THREAD

**Issue by manetelpian** [openvinotoolkit/openvino#3087]
##### System information (version)

- OpenVINO => 2020.1
- Operating System / Platform => Ubuntu 18.04.5
##### Steps to reproduce

I am attempting to run the following OpenVINO model demo using the command:

./text_detection_demo -m_tr /opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/downloader/intel/text-recognition-0012/FP32/text-recognition-0012.xml -i /dev/video0 -r

When I run a text detection demo using a sample image uploaded on the computer, the demo successfully runs; however when I attempt to use my webcam, I get the following error:

InferenceEngine: 	API version ......... 2.1
	Build ........... 2021.1.0-1237-bece22ac675-releases/2021/1
[ INFO ] Parsing input parameters
[ INFO ] Loading Inference Engine
[ INFO ] Device info: 
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... 2021.1.0-1237-bece22ac675-releases/2021/1

[ INFO ] Loading network files
[ WARN:0] global ../opencv/modules/videoio/src/cap_gstreamer.cpp (1761) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0] global ../opencv/modules/videoio/src/cap_gstreamer.cpp (888) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /opt/intel/mediasdk/lib64/iHD_drv_video.so init failed
libva info: va_openDriver() returns 18
MFX: Can't initialize session
[ ERROR ] Can't set the frame to begin with

Any help is appreciated!

**Comment by avitial** [comment]
Hi @manetelpian, thanks for reaching out. Please try giving the index number of the camera instead of the actual video device. For example in your case for input try `-i 0` instead of `-i /dev/video0`. Give this a try, I am confident this should resolve the issue you are observing, let me know the outcome. 

Regards,
Luis

**Comment by manetelpian** [comment]
Hi @avitial , it worked! Thank you. I do have a new issue now: 
./interactive_face_detection_demo: error while loading shared libraries: libopencv_highgui.so.4.3: cannot open shared object file: No such file or directory

Does this relate to the one I have before?

Thanks again.

**Comment by avitial** [comment]
@manetelpian glad it worked! 

For this other issue, could you share the full command when running the interactive_face_detection_demo? Are you using the webcam or a video file as input?

**Comment by manetelpian** [comment]
I am using the webcam as input.

Here is the command I use to run the demo.
./interactive_face_detection_demo -i 0 -r -m /opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/downloader/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml -m_ag /opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/downloader/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml 

Thanks!

**Comment by avitial** [comment]
@manetelpian I am not able to see such error, I'd suggest to double check the environment variables are set (run setupvars.bat). Are you using your own build of OpenCV or the one included in the OpenVINO package?

**Comment by avitial** [comment]
Closing this issue. I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions.

**Comment by YaroslavSchubert** [comment]
> Hi @manetelpian, thanks for reaching out. Please try giving the index number of the device instead of the actual video device. For example in your case for input try `-i 0` instead of `-i /dev/video0`. Give this a try, I am confident this should resolve the issue you are observing, let me know the outcome.
> 
> Regards, Luis

It helped me thank you!
