### ISSUE TITLE
[ ERROR ] Device with "CPU" name is not registered in the InferenceEngine - Jetson Nano

### ISSUE THREAD

**Issue by JVTEAM** [openvinotoolkit/openvino#310]
I'm trying to run the compute stick on a aarch64 jetson nano.  I have all the pre-reqs built and installed.  I'm running the benchmark app and getting this error.

./benchmark_app I ~/models/president_reagan-62x62.png -m ~/models/age-gender-recognition-retail-0013.xml

How do I modify to fix?

**Comment by vladimir-dudnik** [comment]
I think you need to specify device MyriadX. ARM CPU as compute device not supported in current version of OpenVINO Inference Engine.

**Comment by ilya-lavrenov** [comment]
Closing as arm cpu is not supported for now
