### ISSUE TITLE
Inference in the presence of unsupported layer

### ISSUE THREAD

**Issue by dipendra009** [openvinotoolkit/openvino#3112]
Hi,
I am using OpenVINO on a p=PyTorch EfficientDet-d0 model using PyTorch->ONNX->OpenVINO conversion. While checking for the supported layers, I am getting the following issue:

Following layers are not supported by the plugin for specified device CPU:
Constant_12264,Constant_12262,Constant_12260,Constant_12258,Constant_12256,Constant_12255,Constant_12250,Constant_12245,Constant_12240,Constant_12235,Constant_12140,Constant_12133,Constant_12126,Constant_12119,Constant_12112,Constant_12105,Constant_12098,Constant_12091,Constant_12084,Constant_12077,Constant_12070,Constant_12063

When I inference using the imported model in openvino, the inference appears to agree with ONNX and PyTorch inference output. Could you please tell me what are these Constant layers? Can I rely on OpenVINO inference if I have these layers as a part of the model? Note that I am using constant_folding while converting from PyTorch to ONNX.

**Comment by jgespino** [comment]
Hi @dipendra009 

ONNX Constant operation is supported, please take a look at the OpenVINO toolkit documentation for [ONNX Supported Operators](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#onnx_supported_operators). Which version of OpenVINO toolkit are you using? Could you share your model to confirm?

Regards,
Jesus

**Comment by ilyachur** [comment]
@dipendra009 If I understand right, you use hetero plugin or QueryNetwork method.
If I am right, this bug already was fixed for the master branch. Could you recheck?

**Comment by dipendra009** [comment]
Hi, thank for you quick response. I am using openvino_2021.1.110, which I suppose is the latest one. I am not using Hetero plugin, I am device='cpu'; however, I am using the ie.query_network. Are we not supposed to use the query_network to check for support layers?

**Comment by ilya-lavrenov** [comment]
CC @apankratovantonp to comment

**Comment by dipendra009** [comment]
Hi, I see something weird going on. When I check the .xml file, I can not find those layers that is output using the following code:

`supported_layers = ie.query_network(net, device)
not_supported_layers = [l for l in net.layers.keys() if l not in supported_layers]
if len(not_supported_layers):
    print('Following layers are not supported by the plugin for specified device {}:\n{}'.
         format(device, ','.join(not_supported_layers)))
`

Output:

Following layers are not supported by the plugin for specified device CPU:
Constant_16549,Constant_16547,Constant_16545,Constant_16543,Constant_16541,Constant_16540,Constant_16535,Constant_16530,Constant_16525,Constant_16520,Constant_16425,Constant_16418,Constant_16411,Constant_16404,Constant_16397,Constant_16390,Constant_16383,Constant_16376,Constant_16369,Constant_16362,Constant_16355,Constant_16348.

Note that the name of these layers keep changing. Why does that happen?

Also, there are only 7668 nodes in the graph, how come the unsupported layers have numbers in the range of 12250? I am attaching my onnx model file and the openvino converted model for your reference in case you want to check.

BTW, I also checked for the accuracy of the converted model. The output of the ONNX and OpenVINO does not agree. Since I am using EfficientDet-d0, some of the disagreement seems to come from difference in order of objects being detected. Out of 5000 images that I tested for, the ONNX output matches with PyTorch for all of them but OpenVINO only matches for around 97.92%. Is it normal and expected? 

However, the outputs seem to match perfectly for a ResNet-50 model converted PyTorch->ONNX->OpenVINO.

**Comment by ilyachur** [comment]
@dipendra009 names of these operations are changing, because we get these layers after the constant folding (the original model doesn't contain such operations) and you see auto generated names.
Looks like a bug. May I ask you try to use hetero plugin with next parameters: `HETERO:CPU`? Do query network still have the issue?

**Comment by dipendra009** [comment]
Hi, I have tried hetero plugin as you suggested, still have the same issue.

**Comment by jgespino** [comment]
Hi @dipendra009 

Could you please try the latest OpenVINO toolkit 2021.2 release and let us know if the issue is still present?

Regards,
Jesus
