### ISSUE TITLE
Single threaded inference using one cpu core

### ISSUE THREAD

**Issue by mingzhang96** [openvinotoolkit/openvino#314]
Hi, 
I'm using OPENVINO 2019 R1.1 on Ubuntu 18.04.
My CPU is Xeon R CPU E5-2630 v4 @ 2.20GHz processors.

I have two questions.

1. As the question in #185 , I want my inference to run single-threaded, with the following code.
```cpp
InferenceEngine::Core ie;
ie.SetConfig({{ CONFIG_KEY(CPU_THREADS_NUM), std::to_string(1) }}, device_name);
ie.SetConfig({{ CONFIG_KEY(CPU_BIND_THREAD), "YES" }}, device_name);
map<string, string> config = {{ CONFIG_KEY(PERF_COUNT), CONFIG_VALUE(NO) }};
InferenceEngine::ExecutableNetwork exeNetwork = ie.LoadNetwork(cnnNetwork, "cpu", config);
```
But it didn't work. When I use `top -H -b -n1` command and `grep` on the executable name, I found 17 threads. Is it possible to only use **ONE** thread when doing inference?

2. Now my application with the same config works on one cpu core, but when I use `fork()` in c++, I found that still only one cpu core was used. Can I make my application work on one cpu core but work one multi core when using `fork()`?

Thanks in advanced!

**Comment by brmarkus** [comment]
I use the ENV variable "export OMP_NUM_THREADS=10" to limit the number of used threads to 10 - you might want to try to set it to "1" - but I haven't tested it with "1"... Single-threaded is not my use-case...

Sorry about the CPU-core... In the past I was able to pin a process to a specific core ("CPU affinity") in a shell/console:

> Change CPU affinity of all the tasks of process “my-process” to core 2 and 3.

```
ps | grep my-process
cd /proc/<pid>/task
for i in *
>do
>taskset -pc 2,3 $i
>done
```

**Comment by mingzhang96** [comment]
@brmarkus Thanks for your response! It is quite a smart way to attach it, but could I solve this problem in my c++ codes? My application doesn't allow me to do anything in Linux enviroment.

Thanks again!

**Comment by crystalwan** [comment]
I also encountered the same problem, did you solve it?@mingzhang96

**Comment by avitial** [comment]
To disable all internal threading, use the following set of configuration parameters as specified by [CPU plugin documentation](https://github.com/openvinotoolkit/openvino/blob/master/docs/IE_DG/supported_plugins/CPU.md) in v2021.2: `KEY_CPU_THROUGHPUT_STREAMS=0`, `KEY_CPU_THREADS_NUM=1`, `KEY_CPU_BIND_THREAD=NO`. 

Closing this, I believe this response should address the main question. Feel free to reopen and ask additional questions related to this topic.

**Comment by mmenxin** [comment]
> To disable all internal threading, use the following set of configuration parameters as specified by [CPU plugin documentation](https://github.com/openvinotoolkit/openvino/blob/master/docs/IE_DG/supported_plugins/CPU.md) in v2021.2: `KEY_CPU_THROUGHPUT_STREAMS=0`, `KEY_CPU_THREADS_NUM=1`, `KEY_CPU_BIND_THREAD=NO`.
> 
> Closing this, I believe this response should address the main question. Feel free to reopen and ask additional questions related to this topic.

I did as yo said, but there are 5 threads when running, here is my code:
`InferenceEngine::Core core;
    std::map<std::string, std::string> config = {
        { CONFIG_KEY(CPU_THROUGHPUT_STREAMS), std::to_string(0)},
        { CONFIG_KEY(CPU_THREADS_NUM), std::to_string(1)},
        { CONFIG_KEY(CPU_BIND_THREAD), CONFIG_VALUE(NO)}
        };
    InferenceEngine::CNNNetwork network;
    InferenceEngine::ExecutableNetwork executable_network;
    network = core.ReadNetwork(model_path);
    executable_network = core.LoadNetwork(network, "CPU", config);`
