### ISSUE TITLE
Openvino Post processing

### ISSUE THREAD

**Issue by NSVR57** [openvinotoolkit/openvino#3152]
Hi ,

I am inferencing SSD_mobile net _v1(trained on pytorch converted to onnx) but after inferencing I am getting 12 different 4 dim arrays as outputs. where as my colleagues are using  `https://github.com/qfgaohao/pytorch-ssd` for inferencing. As pytorch has inbuilt support for CUDA, they are getting final outpu such as boxes, labesl ..etc. how can post process this result. ?

**Comment by NSVR57** [comment]
In their case NMS is calling for final output. how can we achieve the same

**Comment by jgespino** [comment]
Hi @NSVR57 

We have not tested Pytorch SSD_mobile_net_v1 model via ONNX conversion, please see the list of [supported models](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html#supported_pytorch_models_via_onnx_conversion). 

Could you share your SSD_mobile_net_v1 ONNX model? You may need to specify the `--output` node in the model optimizer command. For example, [mobilenet-v1-1.0-224-tf](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mobilenet-v1-1.0-224-tf), the output layer is `--output=MobilenetV1/Predictions/Reshape_1`.

Also, please see the [object_detecion_demo_ssd_async](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/python_demos/object_detection_demo_ssd_async) demo for post processing implementation. 

Regards,
Jesus

**Comment by NSVR57** [comment]
I Have tried Object_detection_demo_ssd_async. but finally, stuck  up with following issue.

```
u50737@s099-n004:~$ python3 object_detection_demo_ssd_async.py -m /home/u50737/model/FP16/ssd_mob_v1.xml -i /home/u50737/test_1000/000019.jpg
[ INFO ] Initializing Inference Engine...
[ INFO ] Loading network...
[ INFO ] Using USER_SPECIFIED mode
[ INFO ] Reading network from IR...
[ INFO ] Loading network to plugin...
[ WARNING ] Suitable layer for "labels" output is not found. Treating detector as class agnostic with output label 1
Traceback (most recent call last):
  File "object_detection_demo_ssd_async.py", line 565, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_ssd_async.py", line 424, in main
    caught_exceptions=exceptions),
  File "object_detection_demo_ssd_async.py", line 185, in __init__
    self.output_parser = self._get_output_parser(self.net, self.image_blob_name)
  File "object_detection_demo_ssd_async.py", line 224, in _get_output_parser
    raise RuntimeError('Unsupported model outputs')
RuntimeError: Unsupported model outputs
```

**Comment by NSVR57** [comment]
I have included my files in this link.

https://github.com/NSVR57/openvinomodels/blob/main/model.zip

**Comment by NSVR57** [comment]
Please find the model file in the below link.

https://github.com/NSVR57/openvinomodels/blob/main/ssd_mob_v2.onnx

**Comment by jgespino** [comment]
Hi @NSVR57 

Thanks for sharing the model! I took a look using Netron and the model architecture looks very different to the SSD Mobilenet V2 we support. The object_detection_demo_ssd_async is expecting detection_out with shape [1,1,N,7] and each detection is expected in the following format: [image_id, label, conf, x_min, y_min, x_max, y_max].

I recommend checking the [SSD with MobileNet V2](https://docs.openvinotoolkit.org/latest/omz_models_public_ssd_mobilenet_v2_coco_ssd_mobilenet_v2_coco.html) model and the [object_detection_demo_ssd_async](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/python_demos/object_detection_demo_ssd_async) to understand how the post-processing was done. 

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
