### ISSUE TITLE
Question about clDNN on Intel Iris Plus Graphics(Ice Lake 8x8GT2)

### ISSUE THREAD

**Issue by Christywl** [openvinotoolkit/openvino#316]
The ["System Requirements"](https://github.com/opencv/dldt/tree/2019/inference-engine/thirdparty/clDNN#system-requirements) on the main github page doesn't mention that clDNN supports Intel® Iris(R) Plus Graphics(Ice Lake 8x8GT2). In fact, the following exception is thrown when attempting to run our use cases on clDNN backend:
```
[WARNING]. Device ID (0x8A52) not supported. Pretending to behave like SKL GT2.
[2511:2611:1108/000708.204004:ERROR:compilation_delegate_cl_dnn.cc(155)] [clDNN] failed to create cldnn ocl engine -1 _Map_base::at
```
Does clDNN support on this system?

**Comment by vladimir-paramuzov** [comment]
@Christywl cldnn used to have white-list with supported device IDs which was removed long ago to avoid errors like this. At this moment cldnn checks only vendor and device type, so I assume that your issue has been fixed. If not - feel free to reopen the issue.
