### ISSUE TITLE
 No support for CombinedNonMaxSuppression 

### ISSUE THREAD

**Issue by Shyam4801** [openvinotoolkit/openvino#3165]
Running a custom Yolo model , ended up with this error

List of operations that cannot be converted to Inference Engine IR:
[ ERROR ] CombinedNonMaxSuppression (1)
[ ERROR ] detector/yolo_nms/combined_non_max_suppression/CombinedNonMaxSuppression
[ ERROR ] Part of the nodes was not converted to IR. Stopped.

Ran the Model optimiser using Openvino 2020.3 LTS as well as the latest version , Couldn't convert to IR files . Is there a way to add CombinedNonMaxSuppression support ? I also came across supported ops where Nonmaxsuppression is not supported for VPU . Does that mean even if I convert it it won't work on myriad ?

**Comment by jgespino** [comment]
Hi @Shyam4801 

Thanks for reaching out, the TensorFlow CombinedNonMaxSuppression op is not supported by OpenVINO toolkit. You can try to implement a custom layer, please see this [tutorial](https://github.com/david-drew/OpenVINO-Custom-Layers/tree/master/2019.r2.0). As you mentioned, the operation Non-Max Suppression is only supported on CPU.

We do support certain YOLO implementations, see [Convert YOLO From Tensorflow](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html) documentation.

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
