### ISSUE TITLE
Is there a plan to open source HDDL plugin?

### ISSUE THREAD

**Issue by huichuno** [openvinotoolkit/openvino#317]
Hi, is there a plan to open source HDDL plugin? We have customers that use mPCIe Movidius module which requires HDDL plugin and they are looking for open source solution. Btw, thanks for making MYRIAD plugin open source.

**Comment by avitial** [comment]
@huichuno if you'd like to simulate the behavior of HDDL plugin you can try to initialize multiple Myriad plugin, load network(s) to each one and then manage asynchronous requests. Refer to https://github.com/openvinotoolkit/openvino/issues/179 for more info.

**Comment by avitial** [comment]
@huichuno at this time there are no plans to opensource HDDL plugin. See https://github.com/openvinotoolkit/openvino/issues/179 

Ref. 15990
