### ISSUE TITLE
 Multi-Myriad support

### ISSUE THREAD

**Issue by eljuguetero** [openvinotoolkit/openvino#318]
We need to perform an inference in multiple myriads, duplicate model between myriads, multiple inferences using interlaced frames. 
 
My test was based in this documentation:
https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_MULTI.html

This is the code under test: 
```
   std::string allDevices = "MULTI:";
   std::vector<std::string> myriadDevices = ie.GetMetric("MYRIAD", METRIC_KEY(AVAILABLE_DEVICES));
   for (int i=0; i< myriadDevices.size(); i++)
   { 
      std::cout << myriadDevices[i] << std::endl;
 
      allDevices += std::string("MYRIAD.")
                       + myriadDevices[i]     
                       + std::string(i < (myriadDevices.size() -1) ? "," : "");
   }

   std::cout << myriadDevices.size() << " " << allDevices << std::endl;
   netExec = ie.LoadNetwork(net, allDevices);
```
The output:
```
3-ma2450
9-ma2450
2 MULTI:MYRIAD.3-ma2450,MYRIAD.9-ma2450
```

Finally, I only get one exception:
```
Device with "MULTI" name is not registered in the InferenceEngine
```
I'm using the release `2019_R3.1` compiled by me.

available libraries: 
```
libformat_reader.so
libGNAPlugin.so
libHeteroPlugin.so
libinference_engine.so
libMKLDNNPlugin.so
libmyriadPlugin.so
```
unavailable libraries: 
```
libMultiDevicePlugin.so 
```

Is there support for Multi-Myriad? Is there any documentation or example?

**Comment by eljuguetero** [comment]
I'm using the release `2019_R3.1`, compiled by me.

available libraries: 
```
libformat_reader.so
libGNAPlugin.so
libHeteroPlugin.so
libinference_engine.so
libMKLDNNPlugin.so
libmyriadPlugin.so
```
unavailable libraries: 
```
libMultiDevicePlugin.so 
```

**Comment by elvin-nnov** [comment]
Multi-device plugin was not open sourced yet. You need to use binary distribution of OpenVINO.

**Comment by dkurt** [comment]
MULTI plugin is about simultaneous execution on different targets. To use multiple myriads you need to create separate  netExec instances by LoadNetwork.

**Comment by eljuguetero** [comment]
> Multi-device plugin was not open sourced yet. You need to use binary distribution of OpenVINO.

It works perfect with  binary distribution of OpenVINO.

**Comment by eljuguetero** [comment]
@elvin-nnov are there any plans to open the multi-device plugin?

**Comment by heekinho** [comment]
Any updates on that, guys?

**Comment by ilyachur** [comment]
@gladilov-gleb Can you comment?

**Comment by gladilov-gleb** [comment]
> @gladilov-gleb Can you comment?

@ilyachur I'm not sure I can add something here. The question above is about open source of MULTI plugin, right? I don't know much about it, so I think we should ask someone else.

Regarding Multi + Myriad - such a use case is supported. The issue in the ticket is about missing multi plugin libraries. So @ilyachur could you change labels and direct question to the right developer?

Feel free to correct me if I got the situation in a wrong way.

**Comment by ilyachur** [comment]
Yes thank you @gladilov-gleb.

Sorry guys for misunderstanding, I thought about Myriad plugin. Sorry! 
Multi device plugin was successfully added to open source.
You can find it here: https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/src/multi_device

I will close this ticket. If you have any questions feel free to reopen it.
