### ISSUE TITLE
Is openvino  auto put multi requests into a batch to compute when run the benchmark in async mode to test throughout? [Bug]

### ISSUE THREAD

**Issue by wangzhenyu32** [openvinotoolkit/openvino#3185]

**Comment by jgespino** [comment]
Hi @wangzhenyu32 

The infer requests metrics are based on the batch size and total execution duration, please refer to the Benchmark Tool [documentation](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_benchmark_tool_README.html#asynchronous_api). 

Regards,
Jesus
