### ISSUE TITLE
Setting CPU_BIN_THREAD = NO cause bad performance

### ISSUE THREAD

**Issue by mingzhang96** [openvinotoolkit/openvino#320]
Hi,
I'm using OPENVINO 2019 R1.1 on CentOS7.6.
My CPU is Xeon R CPU E5-2630 v4 @ 2.20GHz processors.

I use the following code to load network:
```
std::map<std::string, std::string> config = {
        {InferenceEngine::PluginConfigParams::KEY_CPU_THREADS_NUM, "1"},
        {InferenceEngine::PluginConfigParams::KEY_CPU_BIND_THREAD, InferenceEngine::PluginConfigParams::NO},
        {InferenceEngine::PluginConfigParams::KEY_CPU_THROUGHPUT_STREAMS, "1"}
        };
```

When I set `KEY_CPU_BIND_THREAD=YES`, I find the time of `Infer()` is 800ms. However, when it is set to `NO`, the time of `Infer()` raises to 1100ms. I want to know what happen when this param changes?

Besides, it is necessary for me to set `KEY_CPU_BIND_THREAD=NO`, because I need to use `fork()` in c++ to multi process my code. If I set `KEY_CPU_BIND_THREAD=YES`, all threads will run on just **one cpu core**. Is there anything I could do to solve this problem?

Thanks!

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual as no response, closing it. Feel free to reopen it or better create a new one.
