### ISSUE TITLE
how can we do multiple inputs inference?

### ISSUE THREAD

**Issue by michaelbuddy** [openvinotoolkit/openvino#3207]
For openvino, any good example for multi inputs inference?  Recently I converted pytorch model to onnx and then to IR, using openvino for inference. The model take image and masks as inputs, I tried lots of sample codes but failed or have incorrect inference results. What's the correct way for multi inputs inference?  Can anybody help on this? thanks 
(ps: I already named the inputs in onnx and IR model) 

print('inputs:'+str(list(net.inputs.keys())))  -- ['input1','input2']
print('outputs:'+str(list(net.outputs.keys())))  -- ['output1']

**Comment by jgespino** [comment]
Hi @michaelbuddy 

Thanks for reaching out, let me check with my peers about this and get back to you.

Regards,
Jesus

**Comment by mtolubaeva** [comment]
Hi @michaelbuddy, 
could you please take a look at  Multi Camera Multi Target demo in https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/python_demos/multi_camera_multi_target_tracking/multi_camera_multi_target_tracking.py and see if it helps? Thanks

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
