### ISSUE TITLE
Custom preprocess command

### ISSUE THREAD

**Issue by NikolaMr** [openvinotoolkit/openvino#322]
Greetings!

I am interested in implementing custom preprocess command.
I had had a look at the geometric_transformations.py and implemented a custom command with `Resize` in mind.
I also added that command inside the __init__.py in preprocessor folder but it doesn't get called for when added inside the `.yml` file's `preprocess` entry.

Any thoughts on how to implement this? 

Best regards,
Nikola

**Comment by ilyachur** [comment]
@NikolaMr At the current moment OpenVINO doesn't support custom preprocess commands.
You can do preprocess on application side or you can implement extension layers and include preprocess as a custom layers in your network.

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
