### ISSUE TITLE
Missed requirements reporting does not include sign

### ISSUE THREAD

**Issue by bwarden** [openvinotoolkit/openvino#323]
With `networkx 2.4` installed, running model optimizer results in an error message that doesn't accurately reflect the issue:
```
...
Model Optimizer version: 	unknown version
[ ERROR ]  
Detected not satisfied dependencies:
	networkx: installed: 2.4, required: 2.4
...
```
The underlying problem is the generation of the error message, which does not include the comparison operator:

https://github.com/opencv/dldt/blob/b0c5accaf8e0c0fac17aaef688478d7f391d05bb/model-optimizer/mo/utils/versions_checker.py#L139

Changing the line to look like this:
```python
        not_satisfied_v.append((name, 'installed: {}'.format(installed_v), 'required: {} {}'.format(sign, required_v)))
```
results in a more clear error message:
```
[ ERROR ]
Detected not satisfied dependencies:
        networkx: installed: 2.4, required: < 2.4
```

**Comment by bwarden** [comment]
...but it would probably be even more clear to just report the line from requirements.txt, e.g.:
```
networkx>=1.11,<2.4
```

**Comment by lazarevevgeny** [comment]
The issue has been fixed already. Please, verify with the latest master branch.
