### ISSUE TITLE
[Feature] Provide a way to examine errors from C API

### ISSUE THREAD

**Issue by abrown** [openvinotoolkit/openvino#3231]
As a user of the Inference Engine C API, it is difficult to diagnose what is wrong with calls that only return an error code (e.g. `IEStatusCode::GENERAL_ERROR`). The C++ exceptions have a helpful error message but this is not propagated through the C API. I believe that [`desc_t`](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/ie_bridges/c/include/c_api/ie_c_api.h#L118-L124) was intended for this, but it is unused by the API. The C API would benefit from some mechanism to retrieve the error message (even something along the lines of `strerror`).

**Comment by jgespino** [comment]
Hi @abrown 

Thank you for providing your input, I have passed this feature request to the development team for consideration.

Regards,
Jesus

Ref. 43684

**Comment by jgespino** [comment]
Hi @abrown 

The development team has decided not to implement this feature request. We encourage users to contribute to the OpenVINO repository by submitting changes via pull requests. Please take a look at the [contribute guide](https://github.com/openvinotoolkit/openvino/wiki/Contribute) for additional information.

Regards,
Jesus

**Comment by abrown** [comment]
@jgespino, can we reconsider this? Once again I ran into an issue where this would be extremely helpful: when I run a SqueezeNet example using the release libraries I get an `UNEXPECTED` error code (the default error code) when loading a model but when using the locally-built, debug libraries I don't see the error at all. Because the release libraries are stripped, it is rather tricky to figure out where the error is occurring and what the error string might be. So the only way I have to replicate the error is in a circumstance where I can't inspect the error.

**Comment by jgespino** [comment]
@abrown I've passed your feedback to the development team.
