### ISSUE TITLE
[Feature] Provide and document a mechanism for logging the Inference Engine

### ISSUE THREAD

**Issue by abrown** [openvinotoolkit/openvino#3232]
Currently I do not see a way to enable logging in the Inference Engine nor do I see any logging implemented in the classes I have used. If this _is_ implemented, could it be documented? Otherwise, could it be added? Logging is a great mechanism for troubleshooting errors both in the Inference Engine and in code using the Inference Engine.

**Comment by jgespino** [comment]
Hi @abrown,

Thank you for your input, I will pass your feedback to the development team for consideration.

Regards,
Jesus

Ref. 32595

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or start a new issues if additional assistance is needed.

Sincerely,
Sahira

**Comment by abrown** [comment]
@sahira-rizvi, what is the resolution of this issue? I suspect that this will not be implemented, but a comment here to that effect would be useful.
