### ISSUE TITLE
 Unknown model format

### ISSUE THREAD

**Issue by WenzhiShao** [openvinotoolkit/openvino#3242]
When try to load a converted model like:
 net = ie.read_network(model=model_xml, weights=model_bin)
a error is reported as ：
RuntimeError: Unknown model format! Cannot find reader for model format: bin and read the model: D:\project\PyCharm\Fontre\torch_model.bin. Please check that reader library exists in your PATH.

this *.bin and *.xml is converted from onnx from pt which is a resnet18 model

please help me

**Comment by jgespino** [comment]
Hi @WenzhiShao 

Please double check the IR model (.xml & .bin) as they may be corrupted. Try converting the ONNX model using the Model Optimizer (MO) once more. If the issue persist, please share the ONNX model, OpenVINO version and MO command used.

Regards,
Jesus

**Comment by ilyachur** [comment]
@WenzhiShao The error looks like you pass *bin file instead of *.xml file as a path to model_xml.

**Comment by jgespino** [comment]
Closing, please re-open or start a new issue if additional assistance is needed.
