### ISSUE TITLE
New ModelOptimizer based on OpenCV DNN backend

### ISSUE THREAD

**Issue by r0l1** [openvinotoolkit/openvino#325]
I had some troubles importing YOLO models with the model optimizer. As noted in the official OpenVino docs, the model has to be first converted to a tensorflow model with third-party partly broken software. Afterwards the model can be imported with the model optimizer. However the converted model contains multiple conversion errors and it does not produce the same output as the original one.

Looking at the OpenCV DNN source code, these problems do not exists, even when using the OpenVino backend. The DNN module has its own powerful model importer with various support for different formats. Darknet models are also supported.

I would suggest to make use of this powerful parser and integrate it into the model optimizer project. I will help to accomplish this. Any thoughts or ideas?

Kind Regards
Roland

**Comment by dkurt** [comment]
Maybe it's better to add to OpenCV something like IR serialization procedure? You know, in case of IE backend it's possible to dump OpenVINO IR so we can introduce an environment variable which can trigger it.

**Comment by r0l1** [comment]
@dkurt sounds like a plan! I just looked at the [OpenVINO C++ API](https://docs.openvinotoolkit.org/latest/annotated.html), but didn't find any method to dump or get the IR. That's the only part missing right now. Do you  have a hint how to do it?

**Comment by lazarevevgeny** [comment]
@r0l1 can we close this issue?

**Comment by ilya-lavrenov** [comment]
Agree to close, not related to IE

**Comment by alalek** [comment]
@r0l1 OpenCV can serialize model into IRs as a debugging feature (no OpenCV API for that): https://github.com/opencv/opencv/pull/17388
(model should not contain OpenCV custom layers)
