### ISSUE TITLE
check openvino verision

### ISSUE THREAD

**Issue by x1aoo** [openvinotoolkit/openvino#3278]
Hi, 

Since I installed several openvino version(e.g. 2021.1.110, 2019.1.114) and when I activate the environment the comment return the same logs.

> [setupvars.sh] OpenVINO environment initialized

Is there any way to check the current OpenVINO version? Like the python

Regards,
Xiao

**Comment by brmarkus** [comment]
You could check where the symbolic link of "/opt/intel/openvino" points to, e.g. "ls -al /opt/intel/openvino".

**Comment by jgespino** [comment]
Hi @x1aoo 

As an alternative you could check the plugin and build version from your python script. Please take a look at the python samples included with OpenVINO. You can find them under `/opt/intel/openvino_2021/inference_engine/samples/python`.

```
# ------------- 2. Load Plugin for inference engine and extensions library if specified --------------
    log.info("Device info:")
    versions = ie.get_versions(args.device)
    print("{}{}".format(" " * 8, args.device))
    print("{}MKLDNNPlugin version ......... {}.{}".format(" " * 8, versions[args.device].major,
                                                          versions[args.device].minor))
    print("{}Build ........... {}".format(" " * 8, versions[args.device].build_number))

    if args.cpu_extension and "CPU" in args.device:
        ie.add_extension(args.cpu_extension, "CPU")
        log.info("CPU extension loaded: {}".format(args.cpu_extension))
    # -----------------------------------------------------------------------------------------------------
```

Regards,
Jesus

**Comment by x1aoo** [comment]
Hi @jgespino 

Thanks for your help, I got the verision by `ie.get_versions(args.device)[args.device].build_number`
it will return

> '2021.1.0-1237-bece22ac675-releases/2021/1'

since I use the 2021 version

Sincerely,
Xiao
