### ISSUE TITLE
Plan to support "RandomUniform" for Tensorflow?

### ISSUE THREAD

**Issue by sharronliu** [openvinotoolkit/openvino#328]
Hello, is there any plan to support the "RandomUniform" layer for Tensorflow? This is mentioned not supported in the [latest doc](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#tensorflow_supported_operations_and_the_mapping_to_intermediate_representation_layers). Thanks.

I created a PR for this, and verified with the tensorflow model. Would you please review https://github.com/opencv/dldt/pull/338?

**Comment by ilyachur** [comment]
@sharronliu Can you please rebase your PR on the last master?

@lazarevevgeny FYI

**Comment by lazarevevgeny** [comment]
There "Floor" operation has been supported.

There are no plans to support "RandomUniform" which is mostly training related operation.
