### ISSUE TITLE
Incorrect output dimensions for SSD model

### ISSUE THREAD

**Issue by dxxhjk** [openvinotoolkit/openvino#3292]
hi!
i'm using openvino to do the object detection. i download yolo-v2-ava-0001 with downloader and try to detect the cars in a picture with the model. i used the command`/opt/openvino/object_detection_sample_ssd_c -i /home/pi/hello_vino/cars.jpg -m  /opt/openzoo_models/intel/yolo-v2-ava-0001/FP16/yolo-v2-ava-0001.xml -d MYRIAD` and told "Incorrect output dimensions for SSD model" after "[ INFO ] Preparing output blobs".
can you help me? thanks.

**Comment by jgespino** [comment]
Hi @dxxhjk 

The sample application that you are trying to use with the yolo-v2-ava-0001 model is for SSD (single shot detection) models. We currently do not have a sample/demo application for yolo-v2 models. However, you can use the [Object Detection Demo YOLOv3](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/object_detection_demo_yolov3_async) as a reference and make modifications to parse YOLOv2 instead of YOLOv3. 

Regards,
Jesus

**Comment by dxxhjk** [comment]
> Hi @jgespino
Thanks, I'm trying YOLOv3 now.

**Comment by jgespino** [comment]
@dxxhjk great, please let me know how it goes.

**Comment by dxxhjk** [comment]
@jgespino I used the demo from open_model_zoo and the yolo-v3 model downloaded with the downloader. But while i was trying testing them with a video,  the process was "Killed" strangely.
the command i used was:
`~/hello_vino$ ./Release/object_detection_demo_yolov3_async -i ./AVSS_AB_Easy_Divx.avi -m yolo-v3.xml -d MYRIAD`
and i was told：
```
pi@raspberrypi:~/hello_vino$ ./Release/object_detection_demo_yolov3_async -i ./AVSS_AB_Easy_Divx.avi -m yolo-v3.xml -d MYRIAD
InferenceEngine:        API version ......... 2.1
        Build ........... custom_master_fec3bc09904fbaf919fb2ab8872d3b115134cda3
[ INFO ] Parsing input parameters
[ INFO ] Loading Inference Engine
[ INFO ] Device info:
        MYRIAD
        myriadPlugin version ......... 2.1
        Build ........... custom_master_fec3bc09904fbaf919fb2ab8872d3b115134cda3
[ INFO ] Loading network files
[ INFO ] Checking that the inputs are as the demo expects
[ INFO ] Checking that the outputs are as the demo expects
[ INFO ] Loading model to the device
Killed
pi@raspberrypi:~/hello_vino$
```
How can i get more information to fix it?

**Comment by jgespino** [comment]
Hi @dxxhjk 

That is strange, which OpenVINO toolkit did you install? Which MYRIAD device are you using? Are you able to run any other demo and model on the Pi and MYRIAD device?

Regards,
Jesus

**Comment by dxxhjk** [comment]
Hi @jgespino 
i added `--data_type=FP16` and `--reverse_input_channels` when i converted the model, then the yolov3 worked. but i got the wrong predictions as [https://github.com/openvinotoolkit/openvino/issues/1593](https://github.com/openvinotoolkit/openvino/issues/1593) said. then i followed your advice in issue1593, and the "killed-problem" i've met before appeared again. 
Could you help me with the problem? Or maybe you can send me the model you converted in to .bin and .xml file so i can have a try. My address: dxxhjk@126.com, thanks.
By the way, i could run face-detection-adas-0001 model correctly.

My environments:
openvino2020.2
NCS2

**Comment by jgespino** [comment]
Hi @dxxhjk 

The models I used were converted using the latest release 2021.1, I believe they will not work on 2020.2. Could you try upgrading your OpenVINO version to the latest? Use the following link as you are using a Raspberry Pi.

https://download.01.org/opencv/2021/openvinotoolkit/2021.1/

Please let me know the outcome. 

Regards,
Jesus

**Comment by dxxhjk** [comment]
Hi @jgespino 
i have installed openvino2021.1 on my pi and heve tried `face-detection-adas-0001`, it worked correctly. But when i want to use model-optimizer om my pi to convert the YOLOv3-tf model, i found that i cant install tensorflow>1.15.2 <2.0.0 as requirements.txt said. No tensorflow-1.15.3-cp37-cp37m...arm... .whl file was found. i could only find:
tensorflow-1.15.3-cp37-cp37m-macosx_10_11_x86_64.whl
tensorflow-1.15.3-cp37-cp37m-manylinux2010_x86_64.whl
tensorflow-1.15.3-cp37-cp37m-win_amd64.whl
So how can i run model-optimizer on my pi?

**Comment by jgespino** [comment]
Hi @dxxhjk 

The Model Optimizer is not supported on the Raspberrry Pi, the recommended flow is to convert your model to IR using the full installation of OpenVINO toolkit on a separate host machine. However, It should be possible to use the model optimizer on the Raspberry Pi but you would need to install all the pre-requisites manually.

Regards,
Jesus
