### ISSUE TITLE
Power Layer uses unsupported power value

### ISSUE THREAD

**Issue by kaixuanliu** [openvinotoolkit/openvino#33]
Hi, when I use inference engine to run a CPN model, it returns "Power Layer tower_0/resnet_v1_50/conv1/BatchNorm/moments/SquaredDifference/squared_uses unsupported power value". After checking the code, I find this:
```
if (powerLayer->power != 1.0f && powerLayer->power != 0.5f) {
        THROW_CLDNN_EXCEPTION("Power Layer " << layer->name << "uses unsupported power value");
}
```
in the file ./src/cldnn_engine/cldnn_graph.cpp:1954
So I do not know why the power value in Power layer should be only 1 or 0.5?

**Comment by avbelova** [comment]
Hello,
Do you use CPN from here: https://github.com/chenyilun95/tf-cpn ?

Best wishes, 
Anna

**Comment by kaixuanliu** [comment]
> Hello,
> Do you use CPN from here: https://github.com/chenyilun95/tf-cpn ?
> 
> Best wishes,
> Anna

Yes

**Comment by lazarevevgeny** [comment]
The issue should had been fixed already. Please, use the latest OpenVINO package or github to verify.
