### ISSUE TITLE
no directory '/inference-engine/bin/intel64/Release' or samples build directory

### ISSUE THREAD

**Issue by zhaojw219** [openvinotoolkit/openvino#330]
After I generate .xml and .bin file,I can not find the directory './inference-engine/bin/intel64/Release'.Maybe anything I missed when I build?Please help me .Thanks

**Comment by asuhov** [comment]
This folder will be created during inference engine building, please use instruction published at https://github.com/opencv/dldt/tree/2019/inference-engine page.

**Comment by ilyachur** [comment]
@zhaojw219 As @asuhov said, this folder is created when OpenVINO is building.
At the current moment bin folder is created on the top level.
I will close the ticket, please feel free to reopen it, if you have any questions.
