### ISSUE TITLE
build error with add_subdirectory given source "ade" which is not an existing directory.

### ISSUE THREAD

**Issue by zhaojw219** [openvinotoolkit/openvino#331]
When I build MKL in directory build/,I met the error like this: 
CMake Error at thirdparty/CMakeLists.txt:49 (add_subdirectory):
add_subdirectory given source "ade" which is not an existing directory.
Call Stack (most recent call first):
thirdparty/CMakeLists.txt:58 (build_with_lto)

Who can help me?Thanks!

**Comment by asuhov** [comment]
Hello, please make sure that you have cloned git submodules using "git submodule update --recursive  --init" command.

**Comment by ilya-lavrenov** [comment]
The solution is provided. Closing

**Comment by banderlog** [comment]
> Hello, please make sure that you have cloned git submodules using "git submodule update --recursive --init" command.

Please, correct me if I am wrong, but it will not work if you just extracted tar.gz without any `git init` or something like that.

Example:
```
wget -c https://github.com/openvinotoolkit/openvino/archive/2020.4.tar.gz
tar -xf 2020.4.tar.gz
cd openvino-2020.4/
git submodule update --init --recursive

>> fatal: not a git repository (or any of the parent directories): .git
```

**Comment by eltonfernando** [comment]
What is not in README.md ??
