### ISSUE TITLE
yolov5_v3 support

### ISSUE THREAD

**Issue by x1aoo** [openvinotoolkit/openvino#3339]
Hi,

I converted the yolov5_v3 model(both yolov5s and yolov5x) to the IR model, but when I try to inference, the output is really strange. The shape of the output layer is not supposed to be[1,3,80,80,85].
Did OPENVINO support the [yolov5_v3](https://github.com/ultralytics/yolov5/releases/tag/v3.0)?

**Comment by jgespino** [comment]
Hi @x1aoo 

Thanks for reaching out, YOLOv5 is not officially supported with OpenVINO. However, it may work as other users have converted to IR format. What model optimizer command did you use? There are a couple of models available from the link you shared, which one are you using?

Regards,
Jesus

**Comment by x1aoo** [comment]
Hi @jgespino 
I used mo.py to transform the onnx model into the IR model. The command is:
``` python
python /opt/intel/openvino_20217/deployment_tools/model_optimizer/mo.py \
    --input_model {input_dir}/yolov5s.onnx \
    --output_dir {output_dir}  \
    --input_shape [1,3,640,640]
```
I tried [yolov5_v2](https://github.com/ultralytics/yolov5/releases/tag/v2.0) which works and can inference fine. But for [yolov5_v3](https://github.com/ultralytics/yolov5/releases/tag/v3.0) and [yolov5_v3.1](https://github.com/ultralytics/yolov5/releases/tag/v3.1), I also transformed into IR models but could not inference properly for **both [yolov5x ](https://github.com/ultralytics/yolov5/releases/download/v3.1/yolov5x.pt)and [yolov5s](https://github.com/ultralytics/yolov5/releases/download/v3.1/yolov5s.pt)**.

Regards,
Xiao

**Comment by violet17** [comment]
Please refer the conversion method and yolov5 demo on OpenVINO on (yolov5_demo)[https://github.com/violet17/yolov5_demo]

**Comment by x1aoo** [comment]
Hi @violet17 
Thanks for your help, I converted and inference but it seems that the NMS has some problems?
<img width="505" alt="1" src="https://user-images.githubusercontent.com/19789999/100329349-80943400-3008-11eb-9160-510cad035c9c.png">


> Hi @x1aoo
> Please refer the conversion method and yolov5 demo on OpenVINO on [yolov5_demo](https://github.com/violet17/yolov5_demo)

**Comment by x1aoo** [comment]
Hi @violet17 

I tried several models,  only the first one got some problems(I will check later), others are fine. It is really great! However, there is not any acceleration on OpenVINO, it is the same for you?

Regards,
Xiao

**Comment by jgespino** [comment]
Hi @x1aoo 

Could you please try on latest OpenVINO toolkit 2021.2 release?

Regards,
Jesus

**Comment by LifeIsSoSolong** [comment]
> Hi @violet17
> Thanks for your help, I converted and inference but it seems that the NMS has some problems?
> <img alt="1" width="505" src="https://user-images.githubusercontent.com/19789999/100329349-80943400-3008-11eb-9160-510cad035c9c.png">
> 
> > Hi @x1aoo
> > Please refer the conversion method and yolov5 demo on OpenVINO on [yolov5_demo](https://github.com/violet17/yolov5_demo)

My detected results of IR model also like this, many boxes(like anchors) in one object.  How you solve this problem?

**Comment by ATidiane** [comment]
Hey, 
Did you try dividing your inference input image by 255 before testing the converted model ? 
I kinda had a similar issue and resolved it by doing that. 
Ahmed.
