### ISSUE TITLE
How to download models with web site？

### ISSUE THREAD

**Issue by linrio** [openvinotoolkit/openvino#3340]
I follow the guide [Model Downloader and other automation tools](https://docs.openvinotoolkit.org/latest/omz_tools_downloader_README.html), it shows that I should download models by
```
./downloader.py --all
```
However, my server can not reach web site, also I have not  proxy server. I want to download the models from web site, and running the demo such as squeezenet, speech_recognition etc [Run the Verification Scripts to Verify Installation](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html). How I should modify the demo and download script? 
```
    def start_download(self, session, chunk_size, offset):
        range_headers = self.http_range_headers(offset)
        URL = 'https://docs.google.com/uc?export=download'
        response = session.get(URL, params={'id' : self.id}, headers=range_headers,
            stream=True, timeout=DOWNLOAD_TIMEOUT)
        response.raise_for_status()

        for key, value in response.cookies.items():
            if key.startswith('download_warning'):
                params = {'id': self.id, 'confirm': value}
                response = session.get(URL, params=params, headers=range_headers,
                    stream=True, timeout=DOWNLOAD_TIMEOUT)
                response.raise_for_status()

        return self.handle_http_response(response, chunk_size)
```

```
./demo_squeezenet_download_convert_run.sh
```

**Comment by linrio** [comment]
I download squeezenet from [SqueezeNet](https://github.com/forresti/SqueezeNet)
copy and rename:
SqueezeNet_v1.1.caffemodel --> squeezenet1.1.caffemodel
deploy.prototxt                       --> squeezenet1.1.prototxt
to
~/openvino_models/models/public/squeezenet1.1/
It worked.

**Comment by jgespino** [comment]
@linrio Glad that worked for you!
