### ISSUE TITLE
There are some errors related to undefined reference to pugi

### ISSUE THREAD

**Issue by mingmingtasd** [openvinotoolkit/openvino#3370]
Hi，
I am building openvino into chrome image and find that there are some errors related to undefined reference to pugi, such as:
**ld.lld: error: /build/octopus/tmp/portage/chromeos-base/inference-engine-9999/work/inference-engine-9999/bin/intel64/Debug/lib/libinference_engine_legacy.so: undefined reference to pugi::xml_attribute::set_value(float).** 
Please get details as below:

![image](https://user-images.githubusercontent.com/52519066/100301870-12357e80-2fd4-11eb-8cc2-796bbadd23c9.png)
![image](https://user-images.githubusercontent.com/52519066/100301942-3b560f00-2fd4-11eb-8662-33bc424558b5.png)

Would help to give some suggestions? Thanks a lot!

**Comment by ilya-lavrenov** [comment]
@mingmingtasd could you please provide link command for legacy library?
