### ISSUE TITLE
Inference Engine can not make full use of all logic CPUs

### ISSUE THREAD

**Issue by lionkunonly** [openvinotoolkit/openvino#3389]
I try to use the inference engine to run the network on my CPU. I want to make full use of my logic CPUs, but the fact is that it usually uses half of the logic CPUs. Is there any way to use all logic CPUs with the inference engine?

System Info: Unbuntu 18.04 64bit
CPU Info: Intel(R) Core(TM) i7-8700 CPU
OpenVINO version: 2020.3

**Comment by dkurt** [comment]
Half of your cores are virtual - try to disable hyperthreading. OpenVINO utilizes physical cores so be sure that is uses 100% of them.

**Comment by lionkunonly** [comment]
Thanks for your reply. I want to check if I understand. You mean that the OpenVINO makes full use of all physical cores though I see that only half of the cores are used in the command `top`.  I want to ask one more question. If I disable the hyperthreading, what will happen to the performance of the OpenVINO? Will it make the performance worse or similar?

**Comment by dkurt** [comment]
@lionkunonly, it's not necessary to disable HT, I just wanted to highlight that with and without HT OpenVINO performance should be the same (at least this is what I have observed in my experiments, maybe there is more generic statistics).

**Comment by lionkunonly** [comment]
I understand. Thanks for your help.
