### ISSUE TITLE
onnx::ReduceMax support

### ISSUE THREAD

**Issue by gristovski** [openvinotoolkit/openvino#339]
I am trying to convert an onnx model (that I obtained by converting a pytorch model) and I am getting an error at a ReduceMax node.
Concretely, the pytorch line:
`depth_wise_max = torch.max(batch, dim=1)[0]
`
got converted to an onnx node:
`Float(1, 119, 159) = onnx::ReduceMax[i=[1], keepdims=0](%0)
`
that I then try to optimize. But the optimizer throws an error:
`[ ERROR ]  Can not deduce `reduce_axis` for ReduceMax: only one in_port and no `axis` parameter.
`
from 
> /opt/intel/openvino/deployment_tools/model_optimizer/extensions/front/reduce_axis_normalizer.py 

I tried to poke around in the file, and the node it gets is:
```
{'pb': input: "0"
output: "13"
op_type: "ReduceMax"
attribute {
  name: "axes"
  ints: 1
  type: INTS
}
attribute {
  name: "keepdims"
  i: 0
  type: INT
}
, 'kind': 'op', '_in_ports': {0: {'control_flow': False}}, '_out_ports': {0: {'control_flow': False}}, 'name': '13', 'op': 'ReduceMax', 'precision': 'FP32', 'is_output_reachable': True, 'is_undead': False, 'is_const_producer': False}
```
Even if I try to hardcode the dimension, I get an:

> There is no registered "infer" function for node "13" with op = "ReduceMax". Please implement this function in the extensions. 

The release nodes for OpenVINO 2019 Toolkit 2019 R3.1 list ReduceMax as supported.

Any ideas what I am doing wrong, and how to fix it?

**Comment by lmmcc** [comment]
same question

**Comment by lazarevevgeny** [comment]
@gristovski have you tried the Model Optimizer from the master branch? Could you attach the reproducer model?

**Comment by mvafin** [comment]
@gristovski I cannot reproduce the issue as you described on the current master. So if you still experience that on the master ModelOptinizer, please provide onnx model on which that happens.

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issue is not actual anymore as no response, closing it. Feel free to reopen it or create a new one
