### ISSUE TITLE
Asking for recommendation for a mic array

### ISSUE THREAD

**Issue by smitesh-sutaria** [openvinotoolkit/openvino#3390]
Hello Team,

We are using kaldi and deepspeech ASR with openvino. 

Looking for a compatible mic array or if someone has tested any mic array with openvino audio ingestion, recommendation is welcomed.

Is there any official recommendation of mic array from openvino team ? 

Regards,
Smitesh

**Comment by jgespino** [comment]
Hi @smitesh-sutaria 

Thanks for reaching out, I would need to check with the dev team to see if any mic array's were validated. The [Live Speech Recognition Demo](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_samples_speech_libs_and_demos_Live_speech_recognition_demo.html) has the option to chose the microphone, however, I'm not sure if this will work with a mic array.

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @smitesh-sutaria 

Thank you for your patience, we have not tested any mic arrays with OpenVINO. The OpenVINO toolkit demos are using a single channel audio as input. You may be able to modify the demo code to read data from all the mics on the device and pass them to the demo one by one or train another network that supports multi-channel audio. There may be a need for additional pre-processing of your input data.

Hope this helps!

Regards,
Jesus
