### ISSUE TITLE
Inference issues with HDDL device and YoloV3 (OpenVINO 2021.1)

### ISSUE THREAD

**Issue by fabianoboril** [openvinotoolkit/openvino#3401]
##### System information (version)
- OpenVINO => 2021.1
- Operating System / Platform => Ubuntu 18.04
- Compiler => Visual Studio 2017
- Problem classification: Model Conversion
- Model name: YoloV3

##### Detailed description
We are using YoloV3 for object detection in combination with OpenVINO 2021.1. When using the CPU as inference device, all works fine. However, when we change the device from CPU to HDDL (we have 2 cards installed in our system), the inference no longer works. Instead we receive the following status "INFER_NOT_STARTED" (or -11).

The code for the device setup looks as follows:
```
 mCNNNetwork = std::make_shared<InferenceEngine::CNNNetwork>();
  mNetwork = std::make_shared<InferenceEngine::ExecutableNetwork>();

  // Runtime parameters
  const std::size_t numThreads = std::thread::hardware_concurrency();
  std::string device = "CPU"; //"HDDL";
  std::cout<<"Using device "<<device<<std::endl;
  const std::string modelFile = getConfigPath() + "/frozen_darknet_yolov3_model.xml";

  // --------------------------- 1. Load inference engine -------------------------------------
  InferenceEngine::Core inferenceEngine;
  if (device == "CPU") {inferenceEngine.SetConfig({{CONFIG_KEY(CPU_THREADS_NUM), std::to_string(numThreads)}}, device);}
  else if (device == "HDDL") { inferenceEngine.SetConfig({{InferenceEngine::PluginConfigParams::KEY_PERF_COUNT, InferenceEngine::PluginConfigParams::YES}}, device);   }
```

The code for the inference and status report is as follow:

```
  InferenceEngine::SizeVector tensorSize = {batchSize, channels, height, width};
  InferenceEngine::TensorDesc tensorDesc(InferenceEngine::Precision::U8, tensorSize, InferenceEngine::Layout::NHWC);
  InferenceEngine::Blob::Ptr imageBlob = InferenceEngine::make_shared_blob<uint8_t>(tensorDesc, inputImage.data.data());
  InferenceEngine::InferRequest::Ptr inferRequestPtr = mNetwork->CreateInferRequestPtr();
  inferRequestPtr->SetBlob(mInputName, imageBlob);

  // Perform inference
  inferRequestPtr->Infer();
  auto inferenceResultStatus = inferRequestPtr->Wait(InferenceEngine::IInferRequest::WaitMode::RESULT_READY);

  if (inferenceResultStatus != InferenceEngine::OK)
  {
    std::cout<<"Inference failed with "<<inferenceResultStatus<<std::endl;
  }
```

The code is basically a class-based adaptation of the OpenModelZoo implementation provided here:
https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/object_detection_demo_yolov3_async

The HDDL cards itself work fine, when we use for example a GStreamer Pipeline that uses the very same YoloV3 model. Hence, the HDDL setup seems fine, and we believe we are missing something in our code. Hence, any help and suggestion is welcome. Thank you in advance.

**Comment by jgespino** [comment]
Hi @fabianoboril 

Which HDDL cards are you using? I will try and setup  an environment similar to yours. Are you able to run the Object Detection Demo YoloV3 on HDDL without any modifications? If not, does the Object Detection Demo YoloV3 run with just one HDDL Card?

Regards,
Jesus

**Comment by fabianoboril** [comment]
Hi @jgespino 
thank you very much for your support. We are using a Musting V8 card.

I tested the standard Demo with:
`./object_detection_demo_yolov3_async -i test_001.jpg -m frozen_darknet_yolov3_model.xml -d HDDL`
This throws no errors, surprisingly.

At first glance, the only difference in our code to the demo code is that we use
`inferRequestPtr->Infer();`
while the demo uses
`inferenceRequestPtr->StartAsync();`
to perform the inference. Not sure, if this is an issue (I will test that).

Is there a way to check if the blob was properly copied onto the HDDL device?

**Comment by jgespino** [comment]
Hi @fabianoboril 

There aren't any known issues with HDDL and the Infer() call that I am aware of. I verified that it works using the `benchmark_app` with the `-api sync` flag (which calls `Infer() `instead of `StartAsync()`). 

Please try to run the benchmark_app with your model using `-api sync`. I recommend looking at the [benchmark app source](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/samples/benchmark_app/main.cpp#L533) code to see what other changes are needed. 

Regards,
Jesus

**Comment by fabianoboril** [comment]
Hi @jgespino 

I just did a test with the open_model_zoo YoloV3 demo and our HDDL device. The demo works fine out-of-the-box using only StartAsync() calls. However, if I change Line 345
https://github.com/openvinotoolkit/open_model_zoo/blob/75ec8ad4b6c4fd7fb161ae9d2c3056281b2443de/demos/object_detection_demo_yolov3_async/main.cpp#L345
to use Infer() instead of StartAsync() it fails. On the CPU both versions are working fine. Note that I am running this demo only in synchronous mode.

Best regards,
Fabian

**Comment by jgespino** [comment]
Hi @fabianoboril 

I was able to reproduce the issue by modifying the object_detection_yolov3_asyc and have opened a bug with the development team. I will let you know as soon as I find out more. 

Regards,
Jesus

Ref. 44782

**Comment by jgespino** [comment]
Hi @fabianoboril 

Apologies for the delay, the object_detection_yolo3_asyc has been deprecated. Are you still seeing this issue on the latest OpenVINO 2021.3 release? 

Regards,
Jesus

**Comment by fabianoboril** [comment]
Hi,
we haven't tested 2021.3 yet. However, as we have a working solution with StartAsync, we might not update that soon. We can close the issue for now, and re-open it if we find problems with 2021.3.
