### ISSUE TITLE
squeezenet1.1 Error on or near line 178; exiting with status 1

### ISSUE THREAD

**Issue by orionJag** [openvinotoolkit/openvino#3425]
##### System information (version)

- OpenVINO =>  2021.1 
- Operating System / Platform => Ubuntu 18.04.5 LTS  
	NAME="Ubuntu"
	VERSION="18.04.5 LTS (Bionic Beaver)"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 18.04.5 LTS"
	VERSION_ID="18.04"
	HOME_URL="https://www.ubuntu.com/"
	SUPPORT_URL="https://help.ubuntu.com/"
	BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
	PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
	VERSION_CODENAME=bionic
	UBUNTU_CODENAME=bionic
- CPU information
	Architecture:        x86_64
	CPU op-mode(s):      32-bit, 64-bit
	Byte Order:          Little Endian
	CPU(s):              4
	On-line CPU(s) list: 0-3
	Thread(s) per core:  1
	Core(s) per socket:  4
	Socket(s):           1
	NUMA node(s):        1
	Vendor ID:           GenuineIntel
	CPU family:          6
	Model:               122
	Model name:          Intel(R) Celeron(R) J4105 CPU @ 1.50GHz
	Stepping:            1
	CPU MHz:             852.257
	CPU max MHz:         2500.0000
	CPU min MHz:         800.0000
	BogoMIPS:            2995.20
	Virtualization:      VT-x
	L1d cache:           24K
	L1i cache:           32K
	L2 cache:            4096K
- Problem classification: Model Conversion
Model Name: squeezenet1.1.caffemodel

##### Detailed description
Image Classification verification script fails (refer attachment for detailed error) 

##### Steps to reproduce

  Once successful installation of the OpenVINO toolkit, as part of the verification, run the following cmd
   sudo -H ./demo_squeezenet_download_convert_run.sh
	get an error on the model conversion   
		FAILED: squeezenet1.1
		Error on or near line 178; exiting with status 1
                Detailed log file is attached 
[Image_Class_verif_Errors.txt](https://github.com/openvinotoolkit/openvino/files/5619418/Image_Class_verif_Errors.txt)

Also the  demo_security_barrier_camera works fine using the following cmd 
     sudo -H ./demo_security_barrier_camera.sh

 Appreciate all your timely help and support.

**Comment by jgespino** [comment]
Hi @orionJag 

Thanks for reaching out, could you try to delete the following directories to force the demo script to re-download the Caffe model? Once you delete the directory, please run the script once more without sudo and provide the log file. Sudo should not be needed to run the verification script.

```
/home/user/openvino_models
/root/openvino_models
```

Regards,
Jesus

**Comment by orionJag** [comment]
Hi  Jesus 
             Thanks for the prompt response. As suggested, I deleted both the folders and ran the script without "Sudo -H" and it still errors out. The log is in the attached file "squeezenet_Errors". 

           Also, I need to let you know, my Tensor flow (tf & tf2) were failing on the install_prerequisites.sh and hence I used the Samuel's blog (refer link below) to successful install tf & tf2  
            
          BTW,  I also was trying to optimize mobilenet-ssd (with cmd below), which is also failing, which tells me my environment might be messed up.  Attached also the error log "mobilenet-ssd_Errors"

python3 /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py \ 
--input_model /home/<USER>/public/mobilenet-ssd/mobilenet-ssd.caffemodel \
--output_dir /home/<USER>/Desktop/mobilenet-ssd/FP32 \ 
--data_type FP32 \ 
--input_shape=[1,3,300,300] \ 
--mean_values=data[127.5,127.5,127.5]  \ 
--scale_values=data[127.5]
		
      I have included both the files, hoping to help you troubleshoot.  

  Appreciate all your support. 

Thanks 


[squeezenet_Errors.txt](https://github.com/openvinotoolkit/openvino/files/5626703/squeezenet_Errors.txt)
[mobilenet-ssd_Errors.txt](https://github.com/openvinotoolkit/openvino/files/5626726/mobilenet-ssd_Errors.txt)

**Comment by jgespino** [comment]
Hi @orionJag 

What errors were you running into when installing the pre-requisites? 

Please configure the model optimizer once more and provide any logs or errors you run into.
https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#configure-model-optimizer

Regards,
Jesus

**Comment by orionJag** [comment]
Hi 

     Thanks again, as suggested I re-ran the Model optimizer install cmds (refer below) and the logs are in the attachment. 

       cd /opt/intel/openvino_2021/deployment_tools/model_optimizer/install_prerequisites
       sudo ./install_prerequisites.sh

       As I stated previously I was erroring out with the cmd  "sudo ./install_prerequisites.sh", but after following Samuel's blog I was able to successfully install the prerequisites, but something else seems to be preventing Squeezenet now. 


Thanks 

[MO_install_prerequisitesOutput.txt](https://github.com/openvinotoolkit/openvino/files/5631644/MO_install_prerequisitesOutput.txt)

**Comment by jgespino** [comment]
Hi @orionJag 

I am not seeing anything obvious from your environment. The error may be due to the processor (Intel(R) Celeron(R) J4105 CPU) on your system but I need to double check with my peers as the system requirements mentions `6th to 10th generation Intel® Core™ and Intel® Xeon® processors` for development platforms.

Regards,
Jesus

**Comment by mtolubaeva** [comment]
Hi orionJag, 
is it possible for you to try installing OpenVINO in a clean virtual environment, try demos and mobine-net ssd conversion as well? in each case, can you please save output from "dmesg" command and attach here? thank you

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.

**Comment by orionJag** [comment]
Jesus  Thanks, please go ahead. Appreciate all your help and support.  Sent from Mail for Windows 10 From: Jesus EspinozaSent: Friday, December 18, 2020 11:03 AMTo: openvinotoolkit/openvinoCc: orionJag; MentionSubject: Re: [openvinotoolkit/openvino] squeezenet1.1 Error on or near line 178; exiting with status 1 (#3425) Closing, please re-open if additional assistance is needed.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by AlbertA0789** [comment]
Hi can anyone please share what the solution is ? I am encountering the exact same problems right now.
