### ISSUE TITLE
[Bug] Compilation error OpenVino 2020.3.1 release

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/openvino#3428]
- OpenVINO => 2020.3.1
- Operating System / Platform => ubuntu 18.04 LTS
- Compiler => gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
- Problem classification: Compilation

##### Detailed description
Can't compile 2020.3.1 release

because there is excess parenthesis in file 
DLDT_DIR/build/_deps/ext_onnx-src/onnx/defs/tensor/defs.cc:1363:23
for (size_t(i) = 0; i < axes.size(); ++i) {
##### Steps to reproduce

1) git clone https://github.com/openvinotoolkit/openvino.git DLDT_DIR
2) cd DLDT_DIR
3) git checkout tags/2020.3.1
4) git submodule init
5) git submodule update --recursive
6) mkdir build; cd build;
7) cmake -DENABLE_TESTS=OFF -DVERBOSE_BUILD=ON -DENABLE_PERFORMANCE_TESTS=OFF -DENABLE_INTEGRATION_TESTS=OFF -DENABLE_FUNCTIONAL_TESTS=OFF -DENABLE_BEH_TESTS=ON -DENABLE_PLUGIN_RPATH=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_GNA=OFF -DENABLE_CLDNN=OFF -DENABLE_VALIDATION_SET=OFF -DENABLE_DLIA=OFF -DENABLE_VPU=OFF -DENABLE_PRIVATE_MODELS=OFF -DENABLE_PYTHON=ON -DENABLE_TOOLS=ON -DPYTHON_EXECUTABLE=/home/achurkin/miniconda3/envs/opt-toolkit/bin/python3.7 ..
8 ) make -j12

When I just delete this parenthesis Openvino builds normal

**Comment by jgespino** [comment]
Hi @daniil-lyakhov 

I built OpenVINO 2020.3.1 tag using the following commands and did not see the error you mentioned. My system is running Ubuntu 18.04.5 LTS with Python 3.6.9 and gcc 7.5.0.

```
git clone https://github.com/openvinotoolkit/openvino.git
cd openvino
git checkout tags/2020.3.1
git submodule update --init --recursive
./install_dependencies.sh
mkdir build && cd build
cmake -DENABLE_TESTS=OFF -DVERBOSE_BUILD=ON -DENABLE_PERFORMANCE_TESTS=OFF -DENABLE_INTEGRATION_TESTS=OFF -DENABLE_FUNCTIONAL_TESTS=OFF -DENABLE_BEH_TESTS=ON -DENABLE_PLUGIN_RPATH=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_GNA=OFF -DENABLE_CLDNN=OFF -DENABLE_VALIDATION_SET=OFF -DENABLE_DLIA=OFF -DENABLE_VPU=OFF -DENABLE_PRIVATE_MODELS=OFF -DENABLE_PYTHON=ON -DENABLE_TOOLS=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
make --jobs=$(nproc --all)
```

Please note that gcc 8.4.0 has not been validated with this software, take a look at the [building from Linux](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux) documentation.

Regards,
Jesus
