### ISSUE TITLE
[Bug] Unable to convert Tensorflow: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

### ISSUE THREAD

**Issue by tobymcclean** [openvinotoolkit/openvino#3439]
##### System information (version)
- OpenVINO => 2021.1
- Operating System / Platform => Ubuntu 18.04
- Compiler => N/A
- Problem classification: Model Conversion
- Framework: TensorFlow 
- Model name: Lobe.ai model

##### Detailed description
When converting a Tensorflow model exported from Lobe.ai tool. The conversion shows 100% progress, but then it fails with the message.

/opt/intel/openvino_2021.1.110/deployment_tools/model_optimizer/extensions/back/fuse_sub_div_min.py:104: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
('const_d', {'value': lambda val: val is not None and np.all(val == -1)}),
Data type "<U9" is not supported

##### Steps to reproduce

Model Optimizer arguments:
Common parameters:
- Path to the Input Model: None
- Path for generated IR: /home/workbench/.workbench/models/4/original
- IR output name: CastingQualityInspection TensorFlow
- Log level: ERROR
- Batch: Not specified, inherited from the model
- Input layers: Image
- Output layers: Not specified, inherited from the model
- Input shapes: [1,224,224,3]
- Mean values: Not specified
- Scale values: Not specified
- Scale factor: Not specified
- Precision of IR: FP16
- Enable fusing: True
- Enable grouped convolutions fusing: True
- Move mean values to preprocess section: None
- Reverse input channels: False
TensorFlow specific parameters:
- Input model in text protobuf format: False
- Path to model dump for TensorBoard: None
- List of shared libraries with TensorFlow custom layers implementation: None
- Update the configuration file with input/output node names: None
- Use configuration file used to generate the model with Object Detection API: None
- Use the config file: None
Model Optimizer version: 2021.1.0-1237-bece22ac675-releases/2021/1

Unable to attach model due to size

**Comment by jgespino** [comment]
Hi @tobymcclean 

Thanks for reaching out, could you please help answer the following questions? It would also be great if you could share a link to your model via email.

- Which model architecture was used?
- Which base model was used?
- Is it a classification model or object detection model?

Regards,
Jesus

**Comment by tobymcclean** [comment]
Hi @jgespino,
I just sent you an email with a link to the model.

The classification model was built with the tool from Lobe.ai so I am not sure what architecture that it selected for the training data that I provided it.

Let me know if there is anything else you need.

**Comment by jgespino** [comment]
Hi @tobymcclean 

Thanks for sending the model over. However, I am unable to read it using Netron and passing it to the Model Optimizer throws the following error. I believe it may be corrupted as the frozen model (.pb) is only 2 MB. Could you confirm?

```
Model Optimizer version:        2021.1.0-1237-bece22ac675-releases/2021/1
[ FRAMEWORK ERROR ]  Cannot load input model: TensorFlow cannot read the model file: "C:\Users\<user>\Downloads\tf_model\tf_model\saved_model.pb" is incorrect TensorFlow model file.
The file should contain one of the following TensorFlow graphs:
1. frozen graph in text or binary format
2. inference graph for freezing with checkpoint (--input_checkpoint) in text or binary format
3. meta graph
```

Regards,
Jesus

**Comment by tobymcclean** [comment]
There is a checkpoint file included in the variables directory.

The model loads fine with the attached script. 
[example.zip](https://github.com/openvinotoolkit/openvino/files/5637552/example.zip)

**Comment by jgespino** [comment]
Hi @tobymcclean 

The example code is reading the TensorFlow SavedModel export package from Lobe. Unfortunately, I am not familiar with Lobe. You will need to take the export package and freeze the TensorFlow model prior to passing it to the model optimizer or use the checkpoint file. I don’t see the checkpoint file under the variable directory, it only includes a .meta and .index file. Please provide all the necessary files and model optimizer command used to reproduce the issue.

Regards,
Jesus
