### ISSUE TITLE
AssertionError when convert TF model

### ISSUE THREAD

**Issue by remarkableJ** [openvinotoolkit/openvino#344]
Dear sir,
I got an error on converting tensorflow model (fasttext frozen.pb to Text Classification) into IR files. I have installed all pre-requistics for model optimizer.

I used this command-
python mo_tf.py --input_model /path_of_model --input "input_x[100 100],keep_prob->1.0" --tensorflow_operation_patterns "RandomUniform,Floor"

and I got this error-
...
File ".\dldt-2019\model-optimizer\mo\graph\praph.py", line 529, in add_edg
assert vnode.has_port('in', attr['in']), "{} Node {} has no in port ({})".format(message, vnode.name, attr['in'])
AssertionError: Attempt to connect dropout/dropout/add/Output_0/Data_ to Reshaor_. Node Reshape_ has no in port (0)
...

please help to figure it out, thx

**Comment by lazarevevgeny** [comment]
The command line parameter "--tensorflow_operation_patterns" is not supported anymore. Could you try to convert the model with the latest Model Optimizer without use of this pattern?

Also, when you see an issue related to RandomUniform it usually means that you have some training operations in the model. When you freeze the model make sure that you use "is_train=False" in operations that behave differently in training/inference mode.
