### ISSUE TITLE
[ERROR] [Jetson Nano] Device doesn't appear after boot

### ISSUE THREAD

**Issue by FXRer** [openvinotoolkit/openvino#346]
Hello,

I faced with the following problem while building then running the face-detection example from [here](https://github.com/BeloborodovDS/NCS-face) : 

```
MYRIAD plugin version: myriadPlugin custom_2019_b0c5accaf8e0c0fac17aaef688478d7f391d05bb 2.1
E: [ncAPI] [    257984] [demo] ncDeviceOpen:859	Device doesn't appear after boot
Cannot load network into NCS, probably device not connected
```
I'd followed the installation of DLDT on Jetson Nano here : https://github.com/MrJBSwe/NCS2-and-Coral-TPU-on-aarch64

Any hint?

Thanks in advance.
Pascal

**Comment by dkurt** [comment]
Please check usb rules: /etc/udev/rules.d/97-*

And post an output of "lsusb"

**Comment by brmarkus** [comment]
From the link you mentioned (https://github.com/MrJBSwe/NCS2-and-Coral-TPU-on-aarch64) it is this important section:

> 8.0 Myriad-rules ? ( seems to work without it )
> from l_openvino_toolkit_raspbi_p_2019.1.094.tgz
> 
> $sudo cp 97-myriad-usbboot.rules_.txt /etc/udev/rules.d/97-myriad-usbboot.rules
> $udevadm control --reload-rules
> $udevadm trigger
> $ldconfig 

Then plugin the MyriadX NeuralComputeStick2.

Then call "lsusb"; you should see the device, note the vendorid and deviceid.

When you run your application immediately call "lsusb" again; while the vendorid stays the same the deviceid changes.

When the application exists (and after a little timeout) call "lsusb" again and you will see the previous vendorid and deviceid.

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issue is not actual as no response. Closing it. Feel free to reopen it or better create a new one.
