### ISSUE TITLE
Intel Quartrus Prime installation for Openvino

### ISSUE THREAD

**Issue by NSVR57** [openvinotoolkit/openvino#3460]
Hi ,

I have intel Arria 10 physical hardware. I just want to inference some of the AI models, do we need to buy Quartus prime software just for inference purpose?.  As per link only standard and pro versions has support for Intel Arria 10 Gx card.

https://www.intel.com/content/www/us/en/software/programmable/quartus-prime/download.html

**Comment by jgespino** [comment]
Hi @NSVR57

Which Intel Arria 10 card do you have? Assuming you have the Intel Arria 10 GX, you do need the Intel Quartus software. There are two options as mentioned in the [documentation](https://docs.openvinotoolkit.org/2019_R1.1/_docs_install_guides_GX_Configure_2019R1.html#2_program_the_intel_arria_10_fpga_gx_development_kit).

> Use one of the following two links to download the Intel® Quartus® software, depending on the version you want:
> If you have an Intel® Quartus® software license, use QuartusProProgrammerSetup-18.1.0.222-linux. This software uses about 500 MB of disk space.
> If you do not have the license, use QuartusPrimeLiteProgrammerSetup-18.1.0.625-linux. This software uses about 500 MB of disk space.

Regards,
Jesus

**Comment by SAIVENKATARAJU** [comment]
Hi
Thanks for the reply. Yes I have intel Arria 10 GX card and I don't have license. Is there any work around to inference AI models on Arria 10 GX with lite edition?

**Comment by jgespino** [comment]
Hi @SAIVENKATARAJU 

From my understanding, the Quartus lite software is only used to configure the device and upload the specified files to the Intel Arria 10 GX card. Once all the steps are completed, you should use the OpenVINO toolkit for inference and specify the FPGA device with `-d FPGA`.

Please go through the [configuration guide](https://docs.openvinotoolkit.org/2019_R1.1/_docs_install_guides_GX_Configure_2019R1.html#2_program_the_intel_arria_10_fpga_gx_development_kit) and let me know if you run into any issues. Note that you will need to use the OpenVINO toolkit 2019 R1.1 as it is no longer supported on newer releases. 

Regards,
Jesus
