### ISSUE TITLE
[ERROR] unsupported primitive of type: Gather name: embedding_lookup

### ISSUE THREAD

**Issue by remarkableJ** [openvinotoolkit/openvino#347]
I have converted tf model to IR successfully, but failed in inference with error: 

unsupported primitive of type: Gather name: embedding_lookup

obviously, embedding_lookup is an unsupported operation in tf. 
Why could I achieve the model conversion? or maybe there are other mistakes?

Looking forward to your reply.
Thanks.

**Comment by ArtemSkrebkov** [comment]
Please post such information as:
* version of OpenVINO
* command line used for running inference
* TF model and IR, model optimizer command line used (if possible)

I believe it can shed some light on the issue you have. 
Thanks!

**Comment by lazarevevgeny** [comment]
@remarkableJ is this issue still actual?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issue is not actual as no response. Closing it. Feel free to reopen it or better create a new one.
