### ISSUE TITLE
[Bug] Problem convertin fastrcnn inseption v2

### ISSUE THREAD

**Issue by Warday** [openvinotoolkit/openvino#3470]
##### System information (version)

the network was trained on tensorflow 1.15.x using Tensorflow objet detection api (for tensorflow 1.x)
conversion script (jupiter notebook)
`import platform

mo_tf_path = '/opt/intel/openvino_2021/deployment_tools/model_optimizer/mo_tf.py'

pb_file = '/home/warday/Documentos/CNN/Convert/Convertido/my_model/frozen_inference_graph.pb'
checkpoint = '/home/warday/Documentos/CNN/Convert/Convertido/my_model/model.ckpt.index'
output_dir = '/home/warday/Documentos/CNN/Convert/Openvivo'
configuration_file = '/opt/intel/openvino_2021/deployment_tools/model_optimizer/extensions/front/tf/faster_rcnn_support_api_v1.15.json'

pipeline = '/home/warday/Documentos/CNN/Convert/Convertido/my_model/pipeline.config'

input_shape = [1,800,800,3]
input_shape_str = str(input_shape).replace(' ','')
input_shape_str

!python3 {mo_tf_path} --input_model {pb_file}  --output_dir {output_dir} --transformations_config {configuration_file} --tensorflow_object_detection_api_pipeline_config {pipeline} --input_shape {input_shape_str} --reverse_input_channels --data_type FP16 `

if I use that I get the error 

Failed to match nodes from custom replacement description with id 'ObjectDetectionAPIProposalReplacement':

If I use aster_rcnn_support.json' it works but I got the next error in inverence
ValueError: could not broadcast input array from shape (3,600,600) into shape (1,3)

I make a costum faster_rcnn_support_api_v1.15.json replaceing only ObjectDetectionAPIProposalReplacement  from faster_rcnn_support.json and I got the same error when i try inference 
ValueError: could not broadcast input array from shape (3,600,600) into shape (1,3)

When conversion is saccesfull it sed Suitable inputs {'image_tensor': [1, 3, 600, 600]} so I reshepe image to that instead of 800 * 800
I have no problem to share .pb and checkpoint files
thax

**Comment by jgespino** [comment]
Hi @Warday,

Could you share your frozen TensorFlow (.pb) model and pipeline.config via email?

Regards,
Jesus

**Comment by Warday** [comment]
Email sent. 
IMPORTANT: I try to convert and test original model (without retraining) and with faster_rcnn_support.json. Transform worked good but inference fail. I sent inference code. I have successfully make inference with custom trained inceptionv3 without problem.

ie = IECore()
net = ie.read_network(model=model_xml , weights=model_bin) 
exec_net = ie.load_network(network=net, device_name="CPU")
input_blob = next(iter(exec_net.inputs))
image = Image.open(IMAGE_DIR)
n, c, h, w = [1, 3, 1024, 1024]
processed_img = image.resize((h,w), resample=Image.BILINEAR)
processed_img = np.array(processed_img).astype(np.uint8)
processed_img = processed_img.transpose((2, 0, 1))
processed_img = processed_img.reshape((n, c, h, w))
print(processed_img.shape)
result = exec_net.infer(inputs = {input_blob: processed_img})

**Comment by jgespino** [comment]
Hi @Warday 

Thanks for sending your model over, I was able to convert to IR (.xml and .bin) successfully using the following command and run inference using the object_detection_ssd_async demo. What object is your model trained to recognize? Please provide an input image for me to test the results (email is okay too). 

```
python3 /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py \
--framework tf \
--input_model model/frozen_inference_graph.pb \
--reverse_input_channels \
--data_type FP16 \
--tensorflow_object_detection_api_pipeline_config model/pipeline.config \
--transformations_config json/faster_rcnn_support_api_v1.10.json \
--input_shape [1,600,1024,3]
```

I am having some issues running inference with our Python demos that I'm still looking into.

Regards,
Jesus

**Comment by Warday** [comment]
![IMG_20200108_113046](https://user-images.githubusercontent.com/13140248/101538417-d909f080-397b-11eb-8975-ff0b5115df90.jpg)
Hi, it have so detect leaves on trees (olive leaves).  Teasting

**Comment by jgespino** [comment]
Hi @Warday 

Good news! I tested your model using our [object_detection_sample_ssd](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/ie_bridges/python/sample/object_detection_sample_ssd/object_detection_sample_ssd.py) python application and it detected the leaves in the image (see below). Please take a look at the application code to understand how image and info are read and preprocessed.

Use the following model optimizer command:
```
python3 /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py \
--framework tf \
--input_model model/frozen_inference_graph.pb \
--reverse_input_channels \
--data_type FP16 \
--tensorflow_object_detection_api_pipeline_config model/pipeline.config \
--transformations_config json/faster_rcnn_support_api_v1.10.json \
--input_shape [1,600,1024,3] \
--static_shape
```

![out](https://user-images.githubusercontent.com/18014973/101653517-3e99c380-39f4-11eb-9d4e-88e50718898d.png)

[0,1] element, prob = 0.999997    (1782,1293)-(2260,1818) batch id : 0 WILL BE PRINTED!
[1,1] element, prob = 0.999317    (596,1682)-(794,2115) batch id : 0 WILL BE PRINTED!
[2,1] element, prob = 0.989105    (417,888)-(704,1261) batch id : 0 WILL BE PRINTED!
[3,1] element, prob = 0.830984    (1171,1866)-(1830,2430) batch id : 0 WILL BE PRINTED!
[4,1] element, prob = 0.518357    (1225,936)-(1832,1382) batch id : 0 WILL BE PRINTED

Regards,
Jesus

**Comment by Warday** [comment]
Thax! I will check code

**Comment by Warday** [comment]
Hi I will send my code. Its a modification from [object_detection_sample_ssd](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/ie_bridges/python/sample/object_detection_sample_ssd/object_detection_sample_ssd.py).

` from openvino.inference_engine import IENetwork 
from openvino.inference_engine import IECore
from matplotlib import pyplot as plt
import sys
from PIL import Image
import numpy as np
import glob
import cv2
import tensorflow as tf
import ngraph as ng
model_xml = '/home/warday/Documentos/CNN/Convert/original/frozen_inference_graph.xml'
model_bin = '/home/warday/Documentos/CNN/Convert/original/frozen_inference_graph.bin'
IMAGE_DIR = '/home/warday/Documentos/CNN/Convert/Convertido/fast_insep_v2/images/test/hojasred_4.jpg'

# We prepare input image

n, c, h, w = [1, 3, 600, 1024]
images = np.ndarray(shape=(n, c, h, w))
images_hw = []
image = cv2.imread(IMAGE_DIR)
ih, iw = image.shape[:-1]
images_hw.append((ih, iw))
if image.shape[:-1] != (h, w):
    image = cv2.resize(image, (w, h))
image2 = image.transpose((2, 0, 1))
images[0] = image2

# We load network

ie = IECore()
net = ie.read_network(model=model_xml , weights=model_bin) 

# we prepare input blob
# As older version of Openvino worked with 1 input and newer with 2. 
# first we check and prepare inputs (1 or 2) and the we fill it with the data.
# as we use Openvino 2021 we have 2 inputs ( ['image_info', 'image_tensor'])
# you and check that using print('network.inputs = ' + str(list(exec_net.inputs)))
# we prepare both inputs in a variable called data

for input_key in net.input_info:
        if len(net.input_info[input_key].layout) == 4:
            input_name = input_key
            net.input_info[input_key].precision = 'U8'
        elif len(net.input_info[input_key].layout) == 2:
            input_info_name = input_key
            net.input_info[input_key].precision = 'FP32'
            if net.input_info[input_key].input_data.shape[1] != 3 and net.input_info[input_key].input_data.shape[1] != 6 or \
                net.input_info[input_key].input_data.shape[0] != 1:
                log.error('Invalid input info. Should be 3 or 6 values length.')

data = {}
data[input_name] = images


if input_info_name != "":
        infos = np.ndarray(shape=(n, c), dtype=float)
        for i in range(n):
            infos[i, 0] = h
            infos[i, 1] = w
            infos[i, 2] = 1.0
        data[input_info_name] = infos
     
        
# we prepare output blob

out_blob = next(iter(net.outputs)) # more than enough

# prepare net
exec_net = ie.load_network(network=net, device_name="CPU")
#execute
image_tensor = tf.convert_to_tensor(images)
result = exec_net.infer(inputs = data)
# if you wont to pritn the boxes
res = result[out_blob]
boxes, classes = {}, {}
data = res[0][0]
for number, proposal in enumerate(data):
    if proposal[2] > 0:
        imid = np.int(proposal[0])
        ih, iw = images_hw[imid]
        label = np.int(proposal[1])
        confidence = proposal[2]
        xmin = np.int(iw * proposal[3])
        ymin = np.int(ih * proposal[4])
        xmax = np.int(iw * proposal[5])
        ymax = np.int(ih * proposal[6])
        print("[{},{}] element, prob = {:.6}    ({},{})-({},{}) batch id : {}" \
                .format(number, label, confidence, xmin, ymin, xmax, ymax, imid), end="")
        if proposal[2] > 0.5:
            print(" WILL BE PRINTED!")
            if not imid in boxes.keys():
                boxes[imid] = []
            boxes[imid].append([xmin, ymin, xmax, ymax])
            if not imid in classes.keys():
                classes[imid] = []
            classes[imid].append(label)
        else:
            print()

for imid in classes:
    tmp_image = cv2.imread(IMAGE_DIR)
    for box in boxes[imid]:
        cv2.rectangle(tmp_image, (box[0], box[1]), (box[2], box[3]), (232, 35, 244), 2)
    
    cv2.imwrite("out.bmp", tmp_image)
    plt.imshow(tmp_image) # wrong colors but useful to check
    plt.show() `

**Comment by jgespino** [comment]
@Warday Thanks for sharing! Glad it's all working for you now.
