### ISSUE TITLE
Error while trying to convert custom-trained faster-rcnn model to IR format.

### ISSUE THREAD

**Issue by san999p** [openvinotoolkit/openvino#348]
I have been trying to convert a trained faster-rcnn model to IR format using this tool. If I download a pretrained model from tensorflow detection api's model zoo and convert it to IR, then it works. But these models are older with older config files, so it will throw an error if I will try to train it with TF 1.13. To solve this issue, I had to enter second_stage_batch_size in the config file. Then, I trained the model and tried to convert it into IR. But it throws following error.

[ ERROR ]  Exception occurred during running replacer "ObjectDetectionAPIDetectionOutputReplacement" (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIDetectionOutputReplacement'>): Found the following nodes '[]' with name 'proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalReplacement replacement didn't work.

I am not sure where I am wrong. I saw one more thread on this issue, but didn't help. Any inputs will be appreciated. Thanks!

**Comment by brmarkus** [comment]
Can you provide a link to the model you tried and which caused the converter to through the error you mentioned?
A description how to reproduce it is always welcome and helps a lot to analyze the root cause.
Which version(s) are you using?

**Comment by san999p** [comment]
Thanks @brmarkus.

Here is a link (https://c.onepanel.io/onepanel-demo/projects/cvat-public-demo/jobs/110) to frozen_inference_graph.pb and pipeline.config to generate the IR format. You need to go to `Output` tab just above the terminal. There you will find both of these files.

I used pre-trained model from TF Zoo to train this model. As I mentioned, if I try to convert the pre-trained model then it works fine. But if I try to convert this newly trained model (which was trained on top of the pre-trained model) then it throws an error. Also note that I changed first_stage_max_proposals (from 20 to 100) in the config file during training because TF 1.13 threw an error when this value is less than second_stage_batch_size. I also tried reducing second_stage_batch_size, both of these approaches work to start the training. But it throws an error while converting this model to IR.

Please note that I use dldt_2018_R5 as the latest version throws some error while trying to convert ssd-mobilenet-v2 model.

**Comment by lazarevevgeny** [comment]
@san999p is this issue actual? Have you tried to use different versions json configuration files?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issue is not actual as no response. Closing it. Feel free to reopen it or better create a new one.
