### ISSUE TITLE
BUG: There are big differences  between DNN_BACKEND_OPENCV and DNN_BACKEND_INFERENCE_ENGINE

### ISSUE THREAD

**Issue by olojuwin** [openvinotoolkit/openvino#349]
Test vision: openvino_ 2019.2.275   openvino_2019.1.148
Test script:https://github.com/Star-Clouds/CenterFace/tree/master/prj-opencv-cpp
 i  set net.setPreferableBackend(DNN_BACKEND_OPENCV) ,it work well,but  set net.setPreferableBackend(DNN_BACKEND_INFERENCE_ENGINE) ,it work bad。
I compared their output, there is a very big gap。

**Comment by alalek** [comment]
To localize problem try to inference through Inference Engine API (using Model Optimizer to generate IR from ONNX models).

**Comment by olojuwin** [comment]
> To localize problem try to inference through Inference Engine API (using Model Optimizer to generate IR from ONNX models).
@alalek 
Thanks,i will try

**Comment by olojuwin** [comment]
@alalek Thanks a lot,it work now

**Comment by olojuwin** [comment]
@alalek There's a new problem here，I have try to inference through Inference Engine API with iR models,but  it doesn't support multiscale。And then,i try to DNN_BACKEND_OPENCV to inference,There are also problems with multiscale。
Test 1:same picture inference twice with same scale,output is same
Test 2:same picture inference twice ,first picture  change input scale,second picture not change,the output will be different from Test1。
but i use python todo this,It works well.

**Comment by dkurt** [comment]
@olojuwin, please make it reproducible - upload mentioned .onnx file somewhere.

**Comment by olojuwin** [comment]
@dkurt https://github.com/Star-Clouds/CenterFace/tree/master/models/onnx, Thanks a lot！
The author now updates the code,But fixed input scale is selected。

**Comment by ilyachur** [comment]
@dkurt Is this ticket still relevant?

**Comment by dkurt** [comment]
Let's transfer this issue to OpenCV or please assign it to me.
