### ISSUE TITLE
Inference Engine crash when using Activation layer with type="sigmoid"

### ISSUE THREAD

**Issue by rocketbear** [openvinotoolkit/openvino#35]
Using the latest 2018R4 release of Intel's OpenVINO, a very simple network with a Convolution layer and a Activation layer crashes at run time with the following error:

    Illegal instruction (core dumped)

But the network is ok if the activation type is changed from sigmoid to tanh. 
The net is defined as follows in the IR xml:

	<layers>
		<layer id="0" name="data" precision="FP32" type="Input">
			<output>
				<port id="0">
					<dim>16</dim>
					<dim>32</dim>
					<dim>8</dim>
					<dim>8</dim>
				</port>
			</output>
		</layer>
		<layer id="1" name="conv_fwd" precision="FP32" type="Convolution">
			<data dilations="1,1" group="1" kernel="3,3" output="32" pads_begin="1,1" pads_end="1,1" strides="1,1"/>
			<input>
				<port id="0">
					<dim>16</dim>
					<dim>32</dim>
					<dim>8</dim>
					<dim>8</dim>
				</port>
			</input>
			<output>
				<port id="2">
					<dim>16</dim>
					<dim>32</dim>
					<dim>8</dim>
					<dim>8</dim>
				</port>
			</output>
			<blobs>
				<weights offset="0" size="36864"/>
			</blobs>
		</layer>
		<layer id="2" name="act_fwd" precision="FP32" type="Activation">
			<data type="sigmoid"/>
			<input>
				<port id="0">
					<dim>16</dim>
					<dim>32</dim>
					<dim>8</dim>
					<dim>8</dim>
				</port>
			</input>
			<output>
				<port id="1">
					<dim>16</dim>
					<dim>32</dim>
					<dim>8</dim>
					<dim>8</dim>
				</port>
			</output>
		</layer>
	</layers>
	<edges>
		<edge from-layer="0" from-port="0" to-layer="1" to-port="0"/>
		<edge from-layer="1" from-port="2" to-layer="2" to-port="0"/>
	</edges>

**Comment by ilyachur** [comment]
Hi, 
Could you provide more information (command line or something like that)? 

Illegal instruction

It looks like you are using CPU plugin. Am I right? 
Could you provide your hardware configuration? I mean the CPU model if you are using the CPU plugin.

**Comment by rocketbear** [comment]
My CPU model is E5-2650v2. It's not on the supported list of OpenVINO. This could be the problem.

But the odd thing is, if the positions of the two layers are exchanged, i.e. from conv-act(sigmoid) to act(sigmoid)-conv, the inference engine has no problem running the net.
