### ISSUE TITLE
ERROR: crash when create cnn network

### ISSUE THREAD

**Issue by kalcohol** [openvinotoolkit/openvino#351]
Crash message:
```
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Cannot create convolution forward descriptor for layer: conv_sub_1/sep
/openvino/include/details/ie_exception_conversion.hpp:71
Aborted
```

i'm tracking this issue, and may found the key point. Some model layer loading behavior may cause these issue. So this issue was binding to the special model, and the only model.
It is very easy reappeared in virtualized CPU, but bare metal will not so easy.

**Comment by ilya-lavrenov** [comment]
@kalcohol could you please attach the model?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
