### ISSUE TITLE
Unable to load network for HDDL device on OpenVINO 2021.1

### ISSUE THREAD

**Issue by tnoczyns** [openvinotoolkit/openvino#3524]
**System information (version)**
- OpenVINO 2021.1.110
- Platform: Xeon Silver 4210 + 2 HDDL cards IEI Mustang-V100-MX8
- Operating System: Ubuntu 18.04 (kernel 4.15.0-122)
- Problem classification: failed to load network
- Model name: custom, FP16, size < 1MB

**Details**
When calling InferenceEngine::Core::LoadNetwork function for HDDL device the following exception is thrown:
`_client->loadGraph(_graph, networkName, graphFileContent.data(), graphFileContent.size(), config) failed: HDDL_DEVICE_ERROR`

I'm attaching logs from 'hddldaemon'.
[hddldaemon_log.txt](https://github.com/openvinotoolkit/openvino/files/5660507/hddldaemon_log.txt)

I can share the IR model via email. Any help and suggestion is welcome. Thank you in advance.

**Comment by jgespino** [comment]
Hi @tnoczyns 

My email is on my profile, could you please share your IR, frozen model and Model Optimizer command used? Also include any additional information/files required to convert.

Regards,
Jesus

**Comment by tnoczyns** [comment]
Hi @jgespino,

Thanks for looking into that. I sent you the model binaries. Please let me know if more information is needed.

Thanks,
Tomasz

**Comment by jgespino** [comment]
Thanks @tnoczyns I was able to reproduce the issue, let me take a closer look and get back to you.

**Comment by jgespino** [comment]
Hi @tnoczyns 

Issue was also reproduced on OpenVINO 2021.2 release, I have filed a bug for the development team to take a look. I will let you know once I have more information.

Regards,
Jesus

Ref. 46157

**Comment by jgespino** [comment]
Hi @tnoczyns 

The development team determined that both model are unable to load to the HDDL device as there is not enough memory to allocate the graph.

Regards,
Jesus

**Comment by brmarkus** [comment]
Without disclosing too many (confidential?) details about the shared model - could you provide general information about the model's size, architecture, layers etc, please? Let us learn about what type and size models would cause the mentioned exception to indicate not enough memory to allocate the graph.
