### ISSUE TITLE
[Bug] Cannot find reader for model format

### ISSUE THREAD

**Issue by RenyanDiao** [openvinotoolkit/openvino#3526]
- OpenVINO => 2020.4
- Operating System / Platform => linux x86 ubuntu16

- Problem: Model Read
- Framework: ir
- Model name: Any

Unknown model format! Cannot find reader for model format: 1607480335093-98388486 and read the model: /..../m.23661.1607480335093-98388486. Please check that reader library exists in your PATH.
Aborted (core dumped)

Do I need add anything else in my CMakeList?
 And I'm sure I use IRV10 not V7

**Comment by tomdol** [comment]
"m.23661.1607480335093-98388486" is a very unusual name for a model. Can you please check if this is a correct file containing OpenVINO IR or an ONNX model? Those are the 2 formats currently supported and the files should end with .xml or .onnx accordingly. Perhaps you just need to rename the file you're trying to read.
