### ISSUE TITLE
Custom dataset format?

### ISSUE THREAD

**Issue by BorisLestsov** [openvinotoolkit/openvino#353]
Hi,

Following the docs, I was able to successfully quantize ResNet-50 model and run it in INT8 mode from python. I converted ResNet-50 model from pytorch to ONNX and used ImageNet Val dataset for quantization, which I converted to OpenVINO dataset format with convert_annotation.py. 

However, I do not understand what should I do to quantize another ONNX model on my custom dataset with custom input format and custom metrics. Could you please elaborate on this problem?

Boris

**Comment by maxlytkin** [comment]
If you got your model in ONNX format, then first you have to convert this to IR format of data type FP32 or FP16 thru Model Optimizer and then quantize the resulted IR into INT8 via Post-Training Optimization Toolkit using one of quantization algorithms as per https://docs.openvinotoolkit.org/latest/pot_compression_algorithms_quantization_README.html

**Comment by maxlytkin** [comment]
Closing, please re-open if additional assistance is needed.
