### ISSUE TITLE
[ ERROR ]  List of operations that cannot be converted to Inference Engine IR:

### ISSUE THREAD

**Issue by bogireddytejareddy** [openvinotoolkit/openvino#354]
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx

class TNet(nn.Module):
    def __init__(self):
        super(TNet, self).__init__()

    def forward(self, x):
        return F.upsample(x, (480, 640), mode='nearest')

net = TNet()
x = torch.randn(1, 3, 300, 300)
out = net(x)

print('out.size ', out.size())
torch.onnx.export(net, x, "test.onnx", verbose=True, opset_version=9)
model = onnx.load("test.onnx")
onnx.checker.check_model(model)

when I try using the onnx model that is created above to convert it into intelopenvino, I am getting this error.

[ ERROR ]  List of operations that cannot be converted to Inference Engine IR:
[ ERROR ]      Upsample (1)
[ ERROR ]          2
[ ERROR ]  Part of the nodes was not converted to IR. Stopped.
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #24.

Need help resolving this error

**Comment by dkurt** [comment]
@bogireddytejareddy, please try [torch.nn.Upsample](https://pytorch.org/docs/stable/nn.html#torch.nn.Upsample) instead of `torch.functional.nn.Upsample`

**Comment by bogireddytejareddy** [comment]
> @bogireddytejareddy, please try [torch.nn.Upsample](https://pytorch.org/docs/stable/nn.html#torch.nn.Upsample) instead of `torch.functional.nn.upsample`

No Luck

**Comment by dkurt** [comment]
Which version of OpenVINO is used? Can you please share

**Comment by bogireddytejareddy** [comment]
openvino_2019.2.275

**Comment by dkurt** [comment]
@bogireddytejareddy, Can you try newer version (openvino_2019.3.376)?

**Comment by bogireddytejareddy** [comment]
Hi, it works when I upsample it to 
F.upsample(x, (600, 600), mode='nearest')
F.upsample(x, (900, 900), mode='nearest')

but not when,
F.upsample(x, (640, 480), mode='nearest')

**Comment by dkurt** [comment]
@bogireddytejareddy, Oh I got it. It looks like OpenVINO supports only symmetric upsampling for `nearest` mode (`bilinear` is fine).

**Comment by bogireddytejareddy** [comment]
bilinear also doesn't work

## with pytorch 1.2.0
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    torch.onnx.export(net, x, "test.onnx", verbose=True, opset_version=9)
  File "/Users/bogireddyteja/.virtualenvs/myvenv/lib/python3.7/site-packages/torch/onnx/__init__.py", line 132, in export
    strip_doc_string, dynamic_axes)
  File "/Users/bogireddyteja/.virtualenvs/myvenv/lib/python3.7/site-packages/torch/onnx/utils.py", line 64, in export
    example_outputs=example_outputs, strip_doc_string=strip_doc_string, dynamic_axes=dynamic_axes)
  File "/Users/bogireddyteja/.virtualenvs/myvenv/lib/python3.7/site-packages/torch/onnx/utils.py", line 329, in _export
    _retain_param_name, do_constant_folding)
  File "/Users/bogireddyteja/.virtualenvs/myvenv/lib/python3.7/site-packages/torch/onnx/utils.py", line 225, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/Users/bogireddyteja/.virtualenvs/myvenv/lib/python3.7/site-packages/torch/onnx/utils.py", line 127, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/Users/bogireddyteja/.virtualenvs/myvenv/lib/python3.7/site-packages/torch/onnx/__init__.py", line 163, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/Users/bogireddyteja/.virtualenvs/myvenv/lib/python3.7/site-packages/torch/onnx/utils.py", line 563, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/Users/bogireddyteja/.virtualenvs/myvenv/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'upsample_bilinear2d'

## pytorch 1.0.1.post2
I converts to onnx using bilinear but not openvino

**Comment by dkurt** [comment]
@bogireddytejareddy, What is input size of tensor?

**Comment by bogireddytejareddy** [comment]
> @bogireddytejareddy, What is input size of tensor?

x = torch.randn(1, 3, 300, 300)

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
