### ISSUE TITLE
Trying to find `convert_annotations.py` and `calibrate.py`

### ISSUE THREAD

**Issue by Nedae** [openvinotoolkit/openvino#3544]
Hi, 

I am trying to perform int8 calibration on a detection model, to be calibrated with wider dataset format, however I am unable to locate `convert_annotations.py` and `calibrate.py` on my computer.

I have also found this question 
https://github.com/openvinotoolkit/openvino/issues/3114

I cd-ed into `/opt/intel/openvinoXX/deployment_tools/open_model_zoo/tools/accuracy_checker` and installed accuracy checker using `python3 setup.py install` . 
Still I don't see any `convert_annotation` and `calibrate.py`! where are those?

**Comment by jules-ai** [comment]
these toos need to be charged now. you should pay before using.
