### ISSUE TITLE
Can I add TBB to my own platform? It's not x86

### ISSUE THREAD

**Issue by nmanhong** [openvinotoolkit/openvino#3547]
Can I add TBB to my own platform? It's not x86

**Comment by nmanhong** [comment]
Is openvino completely open source?

**Comment by nmanhong** [comment]
@jgespino

**Comment by alexey-katranov** [comment]
> Can I add TBB to my own platform? It's not x86

Yes, but you need to build it from sources. What platform are you interested in?

As for TBB 2020, you might need to add your own `*.inc` file to the build directory (https://github.com/oneapi-src/oneTBB/tree/tbb_2020/build). E.g. `ios.clang.inc`.

As for oneTBB, we migrated to CMake, so if your platform supports CMake it might work without additional changes. (I think OpenVINO is not migrated to oneTBB yet, so TBB 2020 might be the only choice).

**Comment by nmanhong** [comment]
> > Can I add TBB to my own platform? It's not x86
> 
> Yes, but you need to build it from sources. What platform are you interested in?
> 
> As for TBB 2020, you might need to add your own `*.inc` file to the build directory (https://github.com/oneapi-src/oneTBB/tree/tbb_2020/build). E.g. `ios.clang.inc`.
> 
> As for oneTBB, we migrated to CMake, so if your platform supports CMake it might work without additional changes. (I think OpenVINO is not migrated to oneTBB yet, so TBB 2020 might be the only choice).

I just want to compile openvino to my own platform. Unfortunately, it indicates that TBB does not support this platform, so I consider compiling TBB. Is there any way I can directly compile openvino to my own platform?

**Comment by jgespino** [comment]
Closing issue as you were able to build OpenVINO with SEQ instead of TBB.
https://github.com/openvinotoolkit/openvino/issues/3592
