### ISSUE TITLE
POT config (Adapter) for ssd-based onnx model with nonmaxsuppression

### ISSUE THREAD

**Issue by Nedae** [openvinotoolkit/openvino#3565]
Hello,
I am trying to perform POT on an ssd-based onnx model with nms. I am at the first stage of running the `accuracy_check` test
```
accuracy_check -c <config_path>
```
The outputs of my onnx model are `bboxes`, `scores`, and `indices` (indices are what we get from onnx graph surgeon). 
I am not clear what Adapter I should use in my config file!

- ssd-onnx expects bboxes, scores, and labels (not indices)
- yolo_v3_onnx also drops an `index error` for me,  and when I debug through the code it seems that the format of indices is different that that of what we get from onnx graph surgeon 
- ssd expectations in terms of output dimensions are not clear 

Can you please provide some guidance?

**Comment by Nedae** [comment]
@jgespino could you help please?

**Comment by jgespino** [comment]
Hi @Nedae

I'd have to check with my peers on this one. I know we have a sample config file for [SSD-ResNet34-1200-onnx](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/ssd-resnet34-1200-onnx/accuracy-check.yml) in the Open Model Zoo using the ssd_onnx adapter that is expecting scores, labels and bboxes.

Regards,
Jesus

**Comment by Nedae** [comment]
Thanks @jgespino! I looked at SSD-ResNet34-1200-onnx in Netron and clearly some other ops are there after nonMaxSuppression  to modify the `selected_indices` output to `labels`.

Thus, the topic of this issue can more be like a feature request for future. Since onnx NonMaxSuppression output is `selected_indices`, it might be helpful if ssd_onnx operator accepts `boxes, scores, and indices` as well!

Thanks,

**Comment by sevhabert** [comment]
In latest release - 2021.2, we have an adaptor for ssd-onnx: https://docs.openvinotoolkit.org/latest/omz_tools_accuracy_checker_accuracy_checker_adapters_README.html The attribute names are different labels_out, scores_out, bboxes_out. You can then personalize this adapter to match the outputs of your ssd-onnx.

**Comment by Nedae** [comment]
Thanks @sevhabert! How should I personalize the adapter to get `indices` rather than `labels`? Since the output of my onnx model are the defaults of nms-onnx which are boxes, scores and indices!

**Comment by sevhabert** [comment]
You can find the adapter in <OpenVINO_DIR>\deployment_tools\open_model_zoo\tools\accuracy_checker\accuracy_checker\adapters\ssd.py . There is the SSDONNXAdapter class that needs to be adapted to your model. In this class,  "label" needs to be simply replaced by "indices" where it appears.
