### ISSUE TITLE
What is the difference between dldt and openvino?

### ISSUE THREAD

**Issue by jiapei100** [openvinotoolkit/openvino#359]
Sorry for my naive question, but what is the relationship between dldt and openvino?

Cheers
Pei

**Comment by dkurt** [comment]
OpenVINO is a toolkit consists of multiple libraries:
* DLDT (deep learning deployment toolkit) - Model Optimizer and Inference Engine to effectively run deep learning networks among Intel hardware
* [Open Model Zoo](https://github.com/opencv/open_model_zoo) - big repository with ready to use and free public deep learning networks and trained by Intel teams.
* [Training extensions](https://github.com/opencv/openvino_training_extensions)  TensorFlow and PyTorch based frameworks which can help you to train Intel's models on your own data.
* OpenCV - computer vision library with traditional algorithms, machine learning and deep learning functionality.
* [GStreamer extensions](https://github.com/opencv/gst-video-analytics) - to use DLDT pipelines as GStreamer plugin. Helps to optimize data flow.

**Comment by jiapei100** [comment]
@dkurt 

Thank you so much... So, with [DLDT](https://github.com/opencv/dldt), can I just built each libraries (components) respectively? Because when I tried to install OpenVINO, I obtained the following **ERROR** info:

```
Intel® GPU is not detected on this machine
Installation can continue; however, GPU optimization will not be available for the product.

Intel® Graphics Compute Runtime for OpenCL™ Driver is missing but you will be prompted to install later
You will be prompted later to install the required Intel® Graphics Compute Runtime for OpenCL™ Driver For applications that offload computation to your Intel® GPU, the Intel® Graphics Compute Runtime for OpenCL™ Driver package for Linux is required.

Missing required libraries or packages. You will be prompted to install them later
Install the following libraries or packages required for Intel-optimized OpenCV, the Inference Engine, and the Model Optimizer tools: 
libgtk2.0-dev
libswscale-dev
libavcodec-dev
libavformat-dev
After completing this part of the installation, use the installation guide to install this dependency.

Non root installation
You are running the installation as a regular Linux user. Installation of the Intel(R) Media SDK requires privileges escalation. To install the component, restart the installation script in root/sudo mode.
```

**Comment by dkurt** [comment]
Looks like warning messages, not errors. Have you checked that OpenVINO installed? /opt/intel/openvino

**Comment by ilya-lavrenov** [comment]
Looks like not an issue. Closing
