### ISSUE TITLE
Can openvino be ported to other platforms? It's not x86

### ISSUE THREAD

**Issue by nmanhong** [openvinotoolkit/openvino#3592]
Can openvino be ported to other platforms? It's not x86？
How to do it

**Comment by nmanhong** [comment]
@jgespino

**Comment by ilya-lavrenov** [comment]
@nmanhong you can also use OpenVINO Wiki pages to build for different platforms https://github.com/openvinotoolkit/openvino/wiki/BuildingCode

**Comment by nmanhong** [comment]
My system is based on mips64, can I compile openvino? I tried to compile from the source code, and it told me that the tbb library was wrong. I was trying to compile oneTBB. Can you provide mips64 to compile the source code?

**Comment by nmanhong** [comment]
@jgespino

**Comment by ilya-lavrenov** [comment]
@nmanhong you can compile with `-DTHREADING=SEQ`

**Comment by nmanhong** [comment]
> @nmanhong you can compile with `-DTHREADING=SEQ`

@ilya-lavrenov 
Thank you very much for your help. I compiled it successfully, but when I was testing, I was prompted with another error, 
"Can not init Myriad device: NC_ERROR"
and I was at a loss. Need your help
My system is based on mips64

**Comment by jgespino** [comment]
Hi @nmanhong 

> "Can not init Myriad device: NC_ERROR"

Have you configured the Linux USB Driver for the Intel Neural Compute Stick 2? Please follow section "Configuring the Linux* USB Driver" in the this [guide](https://software.intel.com/content/www/us/en/develop/articles/intel-neural-compute-stick-2-and-open-source-openvino-toolkit.html#inpage-nav-8). Note: the required files are attached the the end of the guide.

Regards,
Jesus

**Comment by nmanhong** [comment]
@jgespino 
@ilya-lavrenov 
If I want to use openvino, do I have to have the Intel Neural Compute Stick 2 device? Without Intel Neural Compute Stick 2, can I use it on the mips64 platform?

**Comment by ilya-lavrenov** [comment]
CC @dkurt

**Comment by dkurt** [comment]
@nmanhong, for CPU OpenVINO uses [MKL-DNN](https://github.com/oneapi-src/oneDNN). Please try to build OpenVINO first - we have no MIPS arch to test.

**Comment by nmanhong** [comment]
@dkurt  @ilya-lavrenov @jgespino 
Thank you very much, I have compiled and can run, but when I ran the official case, an error was prompted, "Supported primitive descriptors list is empty for node: 661", I tested resnet50-binary, when I changed to other model There is still this error. Excuse me, how can I solve it

**Comment by nmanhong** [comment]
@dkurt  @ilya-lavrenov @jgespino 
My test command is "/home/loongson/openvino/bin/mips64/Release/classification_sample_async -m resnet50-binary-0001.xml -i /home/loongson/models/202012081820397.bmp"
Do I have to set up FP32?

**Comment by dkurt** [comment]
@nmanhong, yes, try FP32 first. Binary model probably rely on Intel Architecture based primitives.

**Comment by nmanhong** [comment]
@dkurt 
I tried FP32, but the same error was reported. If I want to run on my platform, is there any way?

**Comment by TechnikEmpire** [comment]
@nmanhong It'd be really nice if you'd specify why you closed the issue. Did you have success on MIPS?

**Comment by Yrij-Zhavoronkov** [comment]
Hello. I also don’t see information on assembling openvino to use VPU, but on MIPS systems.

**Comment by ilya-lavrenov** [comment]
Hi @Yrij-Zhavoronkov 
> I also don’t see information on build openvino to use VPU

OpenVINO NPU plugin will be open sourced soon.

> but on MIPS (for e.x.: 74Kc core) systems.

OpenVINO does not support it.

**Comment by Yrij-Zhavoronkov** [comment]
> OpenVINO does not support it.
It would be good if there was support. VPU is just needed for devices that have little computing power of their own)

**Comment by ilya-lavrenov** [comment]
You can try compiling OpenVINO for MIPS using public cmake toolchains.
OpenVINO core itself does not have anything which prevents from working on MIPS, but e.g. CPU plugin will not work optimally on it.
