### ISSUE TITLE
sample_data documented but not available

### ISSUE THREAD

**Issue by thkukuk** [openvinotoolkit/openvino#360]
The dldt/get-started-linux.md documented references <DLDT_DIR>/inference-engine/samples/sample_data in several places, but I'm not able to find that directory or any references to it except in the documentation.

**Comment by Mushfiq147** [comment]
That is great.

**Comment by avitial** [comment]
The documentation issue with get-started-linux.md has been addressed by this PR https://github.com/openvinotoolkit/openvino/pull/750. Find updated guide here https://github.com/openvinotoolkit/openvino/blob/releases/2020/4/get-started-linux.md.
