### ISSUE TITLE
Error running model optimizer on custom Tensorflow object detection 1 API model

### ISSUE THREAD

**Issue by TonyTheTaiga** [openvinotoolkit/openvino#3610]
##### System information (version)
- OpenVINO => 2019.R1.1
- Operating System / Platform => Linux 64 Bit
- Problem classification: Model Optimizer
- Framework: TensorFlow 1.14.0
- Model name: Mobilenet V1

##### Detailed description
I am trying to optimize a model I retrained using tensorflow's object detection API but am running into the issue below.

Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /model/frozen_inference_graph.pb
        - Path for generated IR:        /.
        - IR output name:       frozen_inference_graph
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP16
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       False
        - Reverse input channels:       True
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  /model/pipeline.config
        - Operations to offload:        None
        - Patterns to offload:  None
        - Use the config file:  /openvino/ssd_1.14.json
Model Optimizer version:        unknown version
The Preprocessor block has been removed. Only nodes performing mean value subtraction and scaling (if applicable) are kept.
[ ERROR ]  ----------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.middle.DeleteNotExecutable.DeleteNotExecutable'>)": 
[ ERROR ]  Traceback (most recent call last):
  File "/openvino/model-optimizer/mo/utils/class_registration.py", line 174, in apply_replacements
    graph_clean_up)
  File "/openvino/model-optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/openvino/model-optimizer/mo/middle/passes/eliminate.py", line 186, in graph_clean_up_tf
    graph_clean_up(graph, ['TFCustomSubgraphCall', 'Shape'])
  File "/openvino/model-optimizer/mo/middle/passes/eliminate.py", line 181, in graph_clean_up
    add_constant_operations(graph)
  File "/openvino/model-optimizer/mo/middle/passes/eliminate.py", line 145, in add_constant_operations
    Const(graph, dict(value=node.value, shape=np.array(node.value.shape))).create_node_with_data(data_nodes=node)
  File "/openvino/model-optimizer/mo/ops/op.py", line 207, in create_node_with_data
    [np.array_equal(old_data_value[id], data_node.value) for id, data_node in enumerate(data_nodes)])
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/openvino/model-optimizer/mo/main.py", line 312, in main
    return driver(argv)
  File "/openvino/model-optimizer/mo/main.py", line 263, in driver
    is_binary=not argv.input_model_is_text)
  File "/openvino/model-optimizer/mo/pipeline/tf.py", line 128, in tf2nx
    class_registration.apply_replacements(graph, class_registration.ClassType.MIDDLE_REPLACER)
  File "/openvino/model-optimizer/mo/utils/class_registration.py", line 190, in apply_replacements
    )) from err
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.middle.DeleteNotExecutable.DeleteNotExecutable'>)": 

[ ERROR ]  ---------------- END OF BUG REPORT ----------
[ ERROR ]  -------------------------------------------------

**Comment by jgespino** [comment]
Hi @TonyTheTaiga 

The OpenVINO toolkit version used is quite old, could you please try on the latest OpenVINO toolkit 2021.1 release? If the issue is still present, please share the full model optimizer command, error message and if possible frozen tensorflow model and config file. 

Regards,
Jesus
