### ISSUE TITLE
Broken urls on accuracy checker

### ISSUE THREAD

**Issue by tonyreina** [openvinotoolkit/openvino#362]
I'm trying to follow the accuracy checker documentation: https://github.com/opencv/dldt/tree/2019/inference-engine/tools/accuracy_checker_tool

However, several of the links on this page are broken (404). In particular, the url https://github.com/opencv/dldt/blob/2019/inference-engine/tools/accuracy_checker_tool/tools/accuracy_checker/accuracy_checker/annotation_converters/README.md doesn't work. It is supposed to give detailed examples on how to define a custom annotation converter.

**Comment by eaidova** [comment]
Hi @tonyreina 
Sorry for misleading, but following script is not part of accuracy checker, more over it will be removed in the next release as I know...
You can find accuracy checker and its documentation in https://github.com/opencv/open_model_zoo
Also as example how to define custom annotation converter I can recommend look on this file and comments in code: https://github.com/opencv/open_model_zoo/blob/master/tools/accuracy_checker/accuracy_checker/annotation_converters/sample_converter.py

**Comment by wdkwyf** [comment]
Hi, I find OMZ in OpenVINO is not synchronized with the latest version. Therefore, many models are missing such as yolo-v3. OpenVINO's OMZ is 2019-R1 now and I want to know how often will it update?

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
