### ISSUE TITLE
[Bug] Compatibility issue with raspberry and openvino 2021

### ISSUE THREAD

**Issue by Warday** [openvinotoolkit/openvino#3631]
##### System information (version)

Hi I generate a system that detect leaves and then classify them. There are 2 network's, first is faster rcnn inception 2 and the other is inception v3 for classification. 
In my computer (ubuntu 18.4 lts) I have generate a python program that load both networks and execute both of them without any problem (inside the neural stick 2). The program works great and fast. When I port the program to raspberry it give the error:

```

RuntimeError                              Traceback (most recent call last)
<ipython-input-3-4a6222ea3de8> in <module>
     38 
     39 #print(threads_per_dev*simultaneous_infer_per_thread)
---> 40 exec_net_list= ie.load_network(network=net, num_requests=threads_per_dev*simultaneous_infer_per_thread, device_name = inference_device)
     41 del net

ie_api.pyx in openvino.inference_engine.ie_api.IECore.load_network()

ie_api.pyx in openvino.inference_engine.ie_api.IECore.load_network()

RuntimeError: Check 'shape_size(inputs[0]->get_shape()) == shape_size(output_shape)' failed at ngraph/core/src/op/reshape.cpp:395:
While validating node 'v1::Reshape Reshape_2609 (Constant_2685[0]:f16{1,512}, Constant_2608[0]:i64{1}) -> (f16{512})' with friendly_name 'Reshape_2609':
Requested output shape Shape{4294967295} is incompatible with input shape Shape{1, 512}
```

if I use OpenVino 2020.4 The classifier works good but the detector doesn't work 
Version 2021.1 also breaks 

https://github.com/movidius/ncappzoo/blob/master/apps/classifier_flash/classifier_flash.py

**Comment by dkurt** [comment]
That's issue similar to https://github.com/openvinotoolkit/openvino/pull/1721

**Comment by jgespino** [comment]
Hi @Warday 

Do you see the same issue on OpenVINO toolkit 2021.2 release? Please make sure both your Ubuntu 18.04 and Raspberry Pi have the same OpenVINO toolkit installed.

OpenVINO toolkit 2021.2 for Raspbian OS is available here:
https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.2/l_openvino_toolkit_runtime_raspbian_p_2021.2.185.tgz

Regards,
Jesus

**Comment by Warday** [comment]
Hi I fix it with open vino 2020.4. I will try on 2021.2

**Comment by Warday** [comment]
Fixed on 2021.2

**Comment by jgespino** [comment]
Great! I will close this issue, feel free to re-open if additional assistance is needed.

**Comment by lvbenson** [comment]
I'm having this same issue on 2021.2......
I'm trying to use retinanet-tf with object_detection_demo_py.
I downloaded and converted the model, and imported the .xml and .bin files to my raspberry pi, where I'm trying to deploy this demo. However, I keep getting faced with the error:

Requested output shape Shape{4294967295,1} is incompatible with input shape Shape{167}.

Has anyone been able to solve this issue?
