### ISSUE TITLE
How to use a batch of inputs when calling InferRequest

### ISSUE THREAD

**Issue by ayy345** [openvinotoolkit/openvino#364]
Hi,

I can not figure out how to make use of a batch of images(inputs) for inference. 

This is what I am trying to do.

InferenceEngine::BlobMap batchInputBlobs;
InferenceEngine::BlobMap outputBlobs;
InferenceEngine::InferRequest infer_request = ...

**// Here it takes BlobMap which is map of <string, Blob>.
// I would like to something like <string, vector<Blob>)
//  Is there an API for that ?**
infer_request.SetInput(batchInputBlobs);

infer_request.SetOutput(outputBlobs);
infer_request.Infer();

Please help.

Thanks,
- VS

**Comment by elvin-nnov** [comment]
Currently  batch should be presented in one blob objects havinf continuous memory with appropriate dimension reflecting batch. You can see such example in https://github.com/opencv/dldt/tree/2019/inference-engine/samples/hello_reshape_ssd
Shortly you need :
1. reshape ICNNNetwork to have batch axis more than 1
2. load such network on device and create at least one infer request
3. get blob from infer request which would have NCHW shape or create such blob yourself
4. fill input by multiple pictures

**Comment by ayy345** [comment]
@elvin-nnov Thank you very much. 

If the inputs are Tensors (all of the same shape and precision as defined in InferenceEngine::TensorDesc), is the input blob - for the Infer() request - simply a concatenation of the individual buffers ?

Thanks,
-VS

**Comment by elvin-nnov** [comment]
> simply a concatenation of the individual buffers ?
Yes

**Comment by ayy345** [comment]
Reshape is failing with error. Any ideas?

When calling 

**CNNNetwork::reshape(...)**

Failed to infer shapes for Reshape layer (MobilenetV2/Predictions/Reshape)
  with error: Invalid reshape mask (dim attribute): number of elements in
  input: [2,14] and output: [1,14] mismatch
openvino_r3_mac/inference-engine/include/details/ie_exception_conversion.hpp:71

**Comment by elvin-nnov** [comment]
there might be several reasons
1. network cannot be reshaped by its nature. For example it contains fully connected layers
2. there might be issues with insufficient information for reshape after conversion by MO. This most likely happens with  networks from TF.
3. There might be a bug in IE

what is a model and from which framework?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
