### ISSUE TITLE
Request for supporting Warp layers

### ISSUE THREAD

**Issue by hocop** [openvinotoolkit/openvino#3659]
Modern optical flow archtectures like FlowNetC and PWCNet use warping layer as their part.

Implementation of this layer in tensorflow: [tfa.image.dense_image_warp](https://www.tensorflow.org/addons/api_docs/python/tfa/image/dense_image_warp)
In torch: [F.grid_sample](https://pytorch.org/cppdocs/api/function_namespacetorch_1_1nn_1_1functional_1ace61741a63d41fc84376dbd24f4f05b2.html)

Will this layer be supported by OpenVINO in the future?

**Comment by jgespino** [comment]
Hi @hocop 

Thanks for opening this feature request, I can go ahead and pass this information to the development team for consideration. Is there a particular framework that you are already using with FlowNetC and PWCNet?

Regards,
Jesus

**Comment by hocop** [comment]
Hi @jgespino 

Thanks for the reply. Currently all implementations of PWCNet I know work only with cuda. My code is in pytorch, so no inference on devices are available.

**Comment by jgespino** [comment]
Hi @hocop 

Thank you, I have submitted a feature request for the development team to consider. At this time there is no commit, I will let you know once I have additional information.

Regards,
Jesus

Ref. 46160

**Comment by DunguTmp** [comment]
Hi, @jgespino 
Is there any progress for the F.grid_sample op?

Thanks!

**Comment by jgespino** [comment]
@DunguTmp There is no progress on this feature request. Do you have a specific model where this layer is used?

**Comment by hocop** [comment]
@DunguTmp I have found an implementation of `grid_sample` which works identically and was able to export it to OpenVINO without problems:
```python
def bilinear_sample_noloop(image, grid):
    """
    Bilinear sampling with no loops.
    from: https://forums.developer.nvidia.com/t/how-to-optimize-the-custom-bilinear-sampling-alternative-to-grid-sample-for-tensorrt-inference/178920/5
    :param image: sampling source of shape [N, C, H, W]
    :param grid: integer sampling pixel coordinates of shape [N, 2, grid_H, grid_W]
    :return: sampling result of shape [N, C, grid_H, grid_W]
    """
    Nt, C, H, W = image.shape
    grid_H = grid.shape[2]
    grid_W = grid.shape[3]
    xgrid, ygrid = grid.split([1, 1], dim=1)
    mask = ((xgrid >= 0) & (ygrid >= 0) & (xgrid < W - 1) & (ygrid < H - 1)).float()
    x0 = torch.floor(xgrid)
    x1 = x0 + 1
    y0 = torch.floor(ygrid)
    y1 = y0 + 1
    wa = ((x1 - xgrid) * (y1 - ygrid)).permute(1, 0, 2, 3) #.permute(3, 0, 1, 2)
    wb = ((x1 - xgrid) * (ygrid - y0)).permute(1, 0, 2, 3) #.permute(3, 0, 1, 2)
    wc = ((xgrid - x0) * (y1 - ygrid)).permute(1, 0, 2, 3) #.permute(3, 0, 1, 2)
    wd = ((xgrid - x0) * (ygrid - y0)).permute(1, 0, 2, 3) #.permute(3, 0, 1, 2)
    x0 = (x0 * mask).view(Nt, grid_H, grid_W).long()
    y0 = (y0 * mask).view(Nt, grid_H, grid_W).long()
    x1 = (x1 * mask).view(Nt, grid_H, grid_W).long()
    y1 = (y1 * mask).view(Nt, grid_H, grid_W).long()
    ind = torch.arange(Nt, device=image.device)
    ind = ind.view(Nt, 1).expand(-1, grid_H).view(Nt, grid_H, 1).expand(-1, -1, grid_W).long()
    image = image.permute(1, 0, 2, 3)
    output_tensor = (image[:, ind, y0, x0] * wa + image[:, ind, y1, x0] * wb + image[:, ind, y0, x1] * wc + \
                    image[:, ind, y1, x1] * wd).permute(1, 0, 2, 3)
    return output_tensor, mask
```

**Comment by DunguTmp** [comment]
> @DunguTmp I have found an implementation of `grid_sample` which works identically and was able to export it to OpenVINO without problems:
> 
> ```python
> def bilinear_sample_noloop(image, grid):
>     """
>     Bilinear sampling with no loops.
>     from: https://forums.developer.nvidia.com/t/how-to-optimize-the-custom-bilinear-sampling-alternative-to-grid-sample-for-tensorrt-inference/178920/5
>     :param image: sampling source of shape [N, C, H, W]
>     :param grid: integer sampling pixel coordinates of shape [N, 2, grid_H, grid_W]
>     :return: sampling result of shape [N, C, grid_H, grid_W]
>     """
>     Nt, C, H, W = image.shape
>     grid_H = grid.shape[2]
>     grid_W = grid.shape[3]
>     xgrid, ygrid = grid.split([1, 1], dim=1)
>     mask = ((xgrid >= 0) & (ygrid >= 0) & (xgrid < W - 1) & (ygrid < H - 1)).float()
>     x0 = torch.floor(xgrid)
>     x1 = x0 + 1
>     y0 = torch.floor(ygrid)
>     y1 = y0 + 1
>     wa = ((x1 - xgrid) * (y1 - ygrid)).permute(1, 0, 2, 3) #.permute(3, 0, 1, 2)
>     wb = ((x1 - xgrid) * (ygrid - y0)).permute(1, 0, 2, 3) #.permute(3, 0, 1, 2)
>     wc = ((xgrid - x0) * (y1 - ygrid)).permute(1, 0, 2, 3) #.permute(3, 0, 1, 2)
>     wd = ((xgrid - x0) * (ygrid - y0)).permute(1, 0, 2, 3) #.permute(3, 0, 1, 2)
>     x0 = (x0 * mask).view(Nt, grid_H, grid_W).long()
>     y0 = (y0 * mask).view(Nt, grid_H, grid_W).long()
>     x1 = (x1 * mask).view(Nt, grid_H, grid_W).long()
>     y1 = (y1 * mask).view(Nt, grid_H, grid_W).long()
>     ind = torch.arange(Nt, device=image.device)
>     ind = ind.view(Nt, 1).expand(-1, grid_H).view(Nt, grid_H, 1).expand(-1, -1, grid_W).long()
>     image = image.permute(1, 0, 2, 3)
>     output_tensor = (image[:, ind, y0, x0] * wa + image[:, ind, y1, x0] * wb + image[:, ind, y0, x1] * wc + \
>                     image[:, ind, y1, x1] * wd).permute(1, 0, 2, 3)
>     return output_tensor, mask
> ```

Hi @hocop 
Thanks you alot. 
Are you converting the torch model to onnx and then to the OpenVino?

Regards,
DwenGu

**Comment by DunguTmp** [comment]
> @DunguTmp There is no progress on this feature request. Do you have a specific model where this layer is used?

Hi, @jgespino 
The backward warp op is always used in the research of the optical flow. And the F.grid_sample is a importent sub module of the backward op.

Thanks, 
DwenGu

**Comment by hocop** [comment]
@DunguTmp yes

> Are you converting the torch model to onnx and then to the OpenVino?

**Comment by DunguTmp** [comment]
> @DunguTmp yes
> 
> > Are you converting the torch model to onnx and then to the OpenVino?

@hocop Thanks for your quickly reply!

**Comment by DunguTmp** [comment]
> @DunguTmp yes
> 
> > Are you converting the torch model to onnx and then to the OpenVino?

Hi, @hocop 
I have used your code and compared the result with F.grid_sampleas follows:
`def bilinear_sample_noloop(image, grid):
    """
    Bilinear sampling with no loops.
    :param image: sampling source of shape [N, C, H, W]
    :param grid: integer sampling pixel coordinates of shape [N, grid_H, grid_W, 2]
    :return: sampling result of shape [N, C, grid_H, grid_W]
    """
    Nt, C, H, W = image.shape
    grid_H = grid.shape[1]
    grid_W = grid.shape[2]
    xgrid, ygrid = grid.split([1, 1], dim=-1)
    mask = ((xgrid >= 0) & (ygrid >= 0) & (xgrid < W - 1) & (ygrid < H - 1)).float()
    x0 = torch.floor(xgrid)
    x1 = x0 + 1
    y0 = torch.floor(ygrid)
    y1 = y0 + 1
    wa = ((x1 - xgrid) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wb = ((x1 - xgrid) * (ygrid - y0)).permute(3, 0, 1, 2)
    wc = ((xgrid - x0) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wd = ((xgrid - x0) * (ygrid - y0)).permute(3, 0, 1, 2)
    x0 = (x0 * mask).view(Nt, grid_H, grid_W).long()
    y0 = (y0 * mask).view(Nt, grid_H, grid_W).long()
    x1 = (x1 * mask).view(Nt, grid_H, grid_W).long()
    y1 = (y1 * mask).view(Nt, grid_H, grid_W).long()
    ind = torch.arange(Nt, device=image.device) #torch.linspace(0, Nt - 1, Nt, device=image.device)
    ind = ind.view(Nt, 1).expand(-1, grid_H).view(Nt, grid_H, 1).expand(-1, -1, grid_W).long()
    image = image.permute(1, 0, 2, 3)
    output_tensor = (image[:, ind, y0, x0] * wa + image[:, ind, y1, x0] * wb + image[:, ind, y0, x1] * wc + \
                     image[:, ind, y1, x1] * wd).permute(1, 0, 2, 3)
    #output_tensor *= mask.permute(0, 3, 1, 2).expand(-1, C, -1, -1)
    return output_tensor

class BilinearSamplingBlock(torch.nn.Module):
    def __init__(self):
        super(BilinearSamplingBlock, self).__init__()

    def forward(self, inputs):
        image, grid = inputs
        samples = bilinear_sample_noloop(image, grid)
        torch_samples = F.grid_sample(image, grid)
        return samples, torch_samples

model = BilinearSamplingBlock()
model.cuda()
dummy_image = torch.ones(3600, 1, 45, 80, device='cuda').float()
dummy_grid = torch.ones(3600, 9, 9, 2, device='cuda').float()
dummy_inputs = [dummy_image, dummy_grid]
with torch.no_grad():
    model.eval()
    openvino_warp_out, original_warp_out = model(dummy_inputs)
    diff = original_warp_out - openvino_warp_out
    print("the diff bettwen the openvino and original:", diff.max(), diff.min())
`
the results of the function you provided seems to be different from F.grid_sample. I want to to know if you have compared the results of these two funcitons.  Or maybe it's my wrong way of using that caused the above error.


Regards,
DwenGu

**Comment by DunguTmp** [comment]
`import torch
import numpy
import torch.nn as nn
import torch.nn.functional as F

def bilinear_sample_noloop(image, grid):
    """
    Bilinear sampling with no loops.
    :param image: sampling source of shape [N, C, H, W]
    :param grid: integer sampling pixel coordinates of shape [N, grid_H, grid_W, 2]
    :return: sampling result of shape [N, C, grid_H, grid_W]
    """
    Nt, C, H, W = image.shape
    grid_H = grid.shape[1]
    grid_W = grid.shape[2]
    xgrid, ygrid = grid.split([1, 1], dim=-1)
    mask = ((xgrid >= 0) & (ygrid >= 0) & (xgrid < W - 1) & (ygrid < H - 1)).float()
    x0 = torch.floor(xgrid)
    x1 = x0 + 1
    y0 = torch.floor(ygrid)
    y1 = y0 + 1
    wa = ((x1 - xgrid) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wb = ((x1 - xgrid) * (ygrid - y0)).permute(3, 0, 1, 2)
    wc = ((xgrid - x0) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wd = ((xgrid - x0) * (ygrid - y0)).permute(3, 0, 1, 2)
    x0 = (x0 * mask).view(Nt, grid_H, grid_W).long()
    y0 = (y0 * mask).view(Nt, grid_H, grid_W).long()
    x1 = (x1 * mask).view(Nt, grid_H, grid_W).long()
    y1 = (y1 * mask).view(Nt, grid_H, grid_W).long()
    ind = torch.arange(Nt, device=image.device) #torch.linspace(0, Nt - 1, Nt, device=image.device)
    ind = ind.view(Nt, 1).expand(-1, grid_H).view(Nt, grid_H, 1).expand(-1, -1, grid_W).long()
    image = image.permute(1, 0, 2, 3)
    output_tensor = (image[:, ind, y0, x0] * wa + image[:, ind, y1, x0] * wb + image[:, ind, y0, x1] * wc + \
                     image[:, ind, y1, x1] * wd).permute(1, 0, 2, 3)
    #output_tensor *= mask.permute(0, 3, 1, 2).expand(-1, C, -1, -1)
    return output_tensor

class BilinearSamplingBlock(torch.nn.Module):
    def __init__(self):
        super(BilinearSamplingBlock, self).__init__()

    def forward(self, inputs):
        image, grid = inputs
        samples = bilinear_sample_noloop(image, grid)
        torch_samples = F.grid_sample(image, grid)
        return samples, torch_samples

model = BilinearSamplingBlock()
model.cuda()
dummy_image = torch.ones(3600, 1, 45, 80, device='cuda').float()
dummy_grid = torch.ones(3600, 9, 9, 2, device='cuda').float()
dummy_inputs = [dummy_image, dummy_grid]
with torch.no_grad():
    model.eval()
    openvino_warp_out, original_warp_out = model(dummy_inputs)
    diff = original_warp_out - openvino_warp_out
    print("the diff bettwen the openvino and original:", diff.max(), diff.min())



# if __name__ == '__main__':
#     model = torch.nn.DataParallel(BilinearSamplingBlock())
#     model.cuda()
#     dummy_image = torch.ones(3600, 1, 45, 80, device='cuda').float()
#     dummy_grid = torch.ones(3600, 9, 9, 2, device='cuda').float()
#     dummy_inputs = [dummy_image, dummy_grid]
#     with torch.no_grad():
#         model.module.eval()
#         smax = 100
#         stime = 0
#         for i in range(smax):
#             t1 = time_stamp()
#             ex_out = model.module(dummy_inputs)
#             t2 = time_stamp()
#             stime += t2 - t1
#         print("Mean model time = ", 1000 * stime / smax, " ms")
#         torch.onnx.export(model.module, dummy_inputs, "sampling_block.onnx", opset_version=11, example_outputs=ex_out, verbose=True)
`

**Comment by DunguTmp** [comment]
`import torch
import numpy
import torch.nn as nn
import torch.nn.functional as F

def bilinear_sample_noloop(image, grid):
    """
    Bilinear sampling with no loops.
    :param image: sampling source of shape [N, C, H, W]
    :param grid: integer sampling pixel coordinates of shape [N, grid_H, grid_W, 2]
    :return: sampling result of shape [N, C, grid_H, grid_W]
    """
    Nt, C, H, W = image.shape
    grid_H = grid.shape[1]
    grid_W = grid.shape[2]
    xgrid, ygrid = grid.split([1, 1], dim=-1)
    mask = ((xgrid >= 0) & (ygrid >= 0) & (xgrid < W - 1) & (ygrid < H - 1)).float()
    x0 = torch.floor(xgrid)
    x1 = x0 + 1
    y0 = torch.floor(ygrid)
    y1 = y0 + 1
    wa = ((x1 - xgrid) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wb = ((x1 - xgrid) * (ygrid - y0)).permute(3, 0, 1, 2)
    wc = ((xgrid - x0) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wd = ((xgrid - x0) * (ygrid - y0)).permute(3, 0, 1, 2)
    x0 = (x0 * mask).view(Nt, grid_H, grid_W).long()
    y0 = (y0 * mask).view(Nt, grid_H, grid_W).long()
    x1 = (x1 * mask).view(Nt, grid_H, grid_W).long()
    y1 = (y1 * mask).view(Nt, grid_H, grid_W).long()
    ind = torch.arange(Nt, device=image.device) #torch.linspace(0, Nt - 1, Nt, device=image.device)
    ind = ind.view(Nt, 1).expand(-1, grid_H).view(Nt, grid_H, 1).expand(-1, -1, grid_W).long()
    image = image.permute(1, 0, 2, 3)
    output_tensor = (image[:, ind, y0, x0] * wa + image[:, ind, y1, x0] * wb + image[:, ind, y0, x1] * wc + \
                     image[:, ind, y1, x1] * wd).permute(1, 0, 2, 3)
    #output_tensor *= mask.permute(0, 3, 1, 2).expand(-1, C, -1, -1)
    return output_tensor

class BilinearSamplingBlock(torch.nn.Module):
    def __init__(self):
        super(BilinearSamplingBlock, self).__init__()

    def forward(self, inputs):
        image, grid = inputs
        samples = bilinear_sample_noloop(image, grid)
        torch_samples = F.grid_sample(image, grid)
        return samples, torch_samples

model = BilinearSamplingBlock()
model.cuda()
dummy_image = torch.ones(3600, 1, 45, 80, device='cuda').float()
dummy_grid = torch.ones(3600, 9, 9, 2, device='cuda').float()
dummy_inputs = [dummy_image, dummy_grid]
with torch.no_grad():
    model.eval()
    openvino_warp_out, original_warp_out = model(dummy_inputs)
    diff = original_warp_out - openvino_warp_out
    print("the diff bettwen the openvino and original:", diff.max(), diff.min())



# if __name__ == '__main__':
#     model = torch.nn.DataParallel(BilinearSamplingBlock())
#     model.cuda()
#     dummy_image = torch.ones(3600, 1, 45, 80, device='cuda').float()
#     dummy_grid = torch.ones(3600, 9, 9, 2, device='cuda').float()
#     dummy_inputs = [dummy_image, dummy_grid]
#     with torch.no_grad():
#         model.module.eval()
#         smax = 100
#         stime = 0
#         for i in range(smax):
#             t1 = time_stamp()
#             ex_out = model.module(dummy_inputs)
#             t2 = time_stamp()
#             stime += t2 - t1
#         print("Mean model time = ", 1000 * stime / smax, " ms")
#         torch.onnx.export(model.module, dummy_inputs, "sampling_block.onnx", opset_version=11, example_outputs=ex_out, verbose=True)`

**Comment by DunguTmp** [comment]
`def bilinear_sample_noloop(image, grid):
    """
    Bilinear sampling with no loops.
    :param image: sampling source of shape [N, C, H, W]
    :param grid: integer sampling pixel coordinates of shape [N, grid_H, grid_W, 2]
    :return: sampling result of shape [N, C, grid_H, grid_W]
    """
    Nt, C, H, W = image.shape
    grid_H = grid.shape[1]
    grid_W = grid.shape[2]
    xgrid, ygrid = grid.split([1, 1], dim=-1)
    mask = ((xgrid >= 0) & (ygrid >= 0) & (xgrid < W - 1) & (ygrid < H - 1)).float()
    x0 = torch.floor(xgrid)
    x1 = x0 + 1
    y0 = torch.floor(ygrid)
    y1 = y0 + 1
    wa = ((x1 - xgrid) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wb = ((x1 - xgrid) * (ygrid - y0)).permute(3, 0, 1, 2)
    wc = ((xgrid - x0) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wd = ((xgrid - x0) * (ygrid - y0)).permute(3, 0, 1, 2)
    x0 = (x0 * mask).view(Nt, grid_H, grid_W).long()
    y0 = (y0 * mask).view(Nt, grid_H, grid_W).long()
    x1 = (x1 * mask).view(Nt, grid_H, grid_W).long()
    y1 = (y1 * mask).view(Nt, grid_H, grid_W).long()
    ind = torch.arange(Nt, device=image.device) #torch.linspace(0, Nt - 1, Nt, device=image.device)
    ind = ind.view(Nt, 1).expand(-1, grid_H).view(Nt, grid_H, 1).expand(-1, -1, grid_W).long()
    image = image.permute(1, 0, 2, 3)
    output_tensor = (image[:, ind, y0, x0] * wa + image[:, ind, y1, x0] * wb + image[:, ind, y0, x1] * wc + \
                     image[:, ind, y1, x1] * wd).permute(1, 0, 2, 3)
    #output_tensor *= mask.permute(0, 3, 1, 2).expand(-1, C, -1, -1)
    return output_tensor`

**Comment by DunguTmp** [comment]
`
def bilinear_sample_noloop(image, grid):
    """
    Bilinear sampling with no loops.
    :param image: sampling source of shape [N, C, H, W]
    :param grid: integer sampling pixel coordinates of shape [N, grid_H, grid_W, 2]
    :return: sampling result of shape [N, C, grid_H, grid_W]
    """
    Nt, C, H, W = image.shape
    grid_H = grid.shape[1]
    grid_W = grid.shape[2]
    xgrid, ygrid = grid.split([1, 1], dim=-1)
    mask = ((xgrid >= 0) & (ygrid >= 0) & (xgrid < W - 1) & (ygrid < H - 1)).float()
    x0 = torch.floor(xgrid)
    x1 = x0 + 1
    y0 = torch.floor(ygrid)
    y1 = y0 + 1
    wa = ((x1 - xgrid) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wb = ((x1 - xgrid) * (ygrid - y0)).permute(3, 0, 1, 2)
    wc = ((xgrid - x0) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wd = ((xgrid - x0) * (ygrid - y0)).permute(3, 0, 1, 2)
    x0 = (x0 * mask).view(Nt, grid_H, grid_W).long()
    y0 = (y0 * mask).view(Nt, grid_H, grid_W).long()
    x1 = (x1 * mask).view(Nt, grid_H, grid_W).long()
    y1 = (y1 * mask).view(Nt, grid_H, grid_W).long()
    ind = torch.arange(Nt, device=image.device) #torch.linspace(0, Nt - 1, Nt, device=image.device)
    ind = ind.view(Nt, 1).expand(-1, grid_H).view(Nt, grid_H, 1).expand(-1, -1, grid_W).long()
    image = image.permute(1, 0, 2, 3)
    output_tensor = (image[:, ind, y0, x0] * wa + image[:, ind, y1, x0] * wb + image[:, ind, y0, x1] * wc + \
                     image[:, ind, y1, x1] * wd).permute(1, 0, 2, 3)
    return output_tensor
`

**Comment by DunguTmp** [comment]
```
import torch
import numpy
import torch.nn as nn
import torch.nn.functional as F

def bilinear_sample_noloop(image, grid):
    """
    Bilinear sampling with no loops.
    :param image: sampling source of shape [N, C, H, W]
    :param grid: integer sampling pixel coordinates of shape [N, grid_H, grid_W, 2]
    :return: sampling result of shape [N, C, grid_H, grid_W]
    """
    Nt, C, H, W = image.shape
    grid_H = grid.shape[1]
    grid_W = grid.shape[2]
    xgrid, ygrid = grid.split([1, 1], dim=-1)
    mask = ((xgrid >= 0) & (ygrid >= 0) & (xgrid < W - 1) & (ygrid < H - 1)).float()
    x0 = torch.floor(xgrid)
    x1 = x0 + 1
    y0 = torch.floor(ygrid)
    y1 = y0 + 1
    wa = ((x1 - xgrid) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wb = ((x1 - xgrid) * (ygrid - y0)).permute(3, 0, 1, 2)
    wc = ((xgrid - x0) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wd = ((xgrid - x0) * (ygrid - y0)).permute(3, 0, 1, 2)
    x0 = (x0 * mask).view(Nt, grid_H, grid_W).long()
    y0 = (y0 * mask).view(Nt, grid_H, grid_W).long()
    x1 = (x1 * mask).view(Nt, grid_H, grid_W).long()
    y1 = (y1 * mask).view(Nt, grid_H, grid_W).long()
    ind = torch.arange(Nt, device=image.device) #torch.linspace(0, Nt - 1, Nt, device=image.device)
    ind = ind.view(Nt, 1).expand(-1, grid_H).view(Nt, grid_H, 1).expand(-1, -1, grid_W).long()
    image = image.permute(1, 0, 2, 3)
    output_tensor = (image[:, ind, y0, x0] * wa + image[:, ind, y1, x0] * wb + image[:, ind, y0, x1] * wc + \
                     image[:, ind, y1, x1] * wd).permute(1, 0, 2, 3)
    #output_tensor *= mask.permute(0, 3, 1, 2).expand(-1, C, -1, -1)
    return output_tensor

class BilinearSamplingBlock(torch.nn.Module):
    def __init__(self):
        super(BilinearSamplingBlock, self).__init__()

    def forward(self, inputs):
        image, grid = inputs
        samples = bilinear_sample_noloop(image, grid)
        torch_samples = F.grid_sample(image, grid)
        return samples, torch_samples

model = BilinearSamplingBlock()
model.cuda()
dummy_image = torch.ones(3600, 1, 45, 80, device='cuda').float()
dummy_grid = torch.ones(3600, 9, 9, 2, device='cuda').float()
dummy_inputs = [dummy_image, dummy_grid]
with torch.no_grad():
    model.eval()
    openvino_warp_out, original_warp_out = model(dummy_inputs)
    diff = original_warp_out - openvino_warp_out
    print("the diff bettwen the openvino and original:", diff.max(), diff.min())



# if __name__ == '__main__':
#     model = torch.nn.DataParallel(BilinearSamplingBlock())
#     model.cuda()
#     dummy_image = torch.ones(3600, 1, 45, 80, device='cuda').float()
#     dummy_grid = torch.ones(3600, 9, 9, 2, device='cuda').float()
#     dummy_inputs = [dummy_image, dummy_grid]
#     with torch.no_grad():
#         model.module.eval()
#         smax = 100
#         stime = 0
#         for i in range(smax):
#             t1 = time_stamp()
#             ex_out = model.module(dummy_inputs)
#             t2 = time_stamp()
#             stime += t2 - t1
#         print("Mean model time = ", 1000 * stime / smax, " ms")
#         torch.onnx.export(model.module, dummy_inputs, "sampling_block.onnx", opset_version=11, example_outputs=ex_out, verbose=True)
```

**Comment by hocop** [comment]
@DunguTmp, made a working example for you:

```python
import torch
import numpy
import torch.nn as nn
import torch.nn.functional as F

def bilinear_sample_noloop(image, grid):
    """
    Bilinear sampling with no loops.
    :param image: sampling source of shape [N, C, H, W]
    :param grid: integer sampling pixel coordinates of shape [N, grid_H, grid_W, 2]
    :return: sampling result of shape [N, C, grid_H, grid_W]
    """
    Nt, C, H, W = image.shape
    grid_H = grid.shape[1]
    grid_W = grid.shape[2]
    xgrid, ygrid = grid.split([1, 1], dim=-1)
    mask = ((xgrid >= 0) & (ygrid >= 0) & (xgrid <= W - 1) & (ygrid <= H - 1)).float()
    x0 = torch.floor(xgrid)
    x1 = x0 + 1
    y0 = torch.floor(ygrid)
    y1 = y0 + 1
    wa = ((x1 - xgrid) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wb = ((x1 - xgrid) * (ygrid - y0)).permute(3, 0, 1, 2)
    wc = ((xgrid - x0) * (y1 - ygrid)).permute(3, 0, 1, 2)
    wd = ((xgrid - x0) * (ygrid - y0)).permute(3, 0, 1, 2)
    x0 = (x0.clamp(0, W - 1)).view(Nt, grid_H, grid_W).long()
    y0 = (y0.clamp(0, H - 1)).view(Nt, grid_H, grid_W).long()
    x1 = (x1.clamp(0, W - 1)).view(Nt, grid_H, grid_W).long()
    y1 = (y1.clamp(0, H - 1)).view(Nt, grid_H, grid_W).long()
    ind = torch.arange(Nt, device=image.device) #torch.linspace(0, Nt - 1, Nt, device=image.device)
    ind = ind.view(Nt, 1).expand(-1, grid_H).view(Nt, grid_H, 1).expand(-1, -1, grid_W).long()
    image = image.permute(1, 0, 2, 3)
    output_tensor = (image[:, ind, y0, x0] * wa + image[:, ind, y1, x0] * wb + image[:, ind, y0, x1] * wc + \
                     image[:, ind, y1, x1] * wd).permute(1, 0, 2, 3)
    output_tensor *= mask.permute(0, 3, 1, 2).expand(-1, C, -1, -1)
    return output_tensor

class BilinearSamplingBlock(torch.nn.Module):
    def __init__(self):
        super(BilinearSamplingBlock, self).__init__()

    def forward(self, inputs):
        image, grid = inputs
        samples = bilinear_sample_noloop(image, grid)
        grid_scaled = torch.cat([
            grid[:, :, :, 0:1] / (grid.shape[2] - 1) * 2 - 1,
            grid[:, :, :, 1:] / (grid.shape[1] - 1) * 2 - 1,
        ], -1)
        torch_samples = F.grid_sample(image, grid_scaled, align_corners=True)
        return samples, torch_samples

model = BilinearSamplingBlock()
#model.cuda()
dummy_image = torch.randn(1, 1, 6, 6, device='cpu').float()
#dummy_image = torch.arange(0, 6).view(1, 1, -1, 1).repeat(1, 1, 1, 6).float()

# Mesh grid
B, _, H, W = dummy_image.size()
xx = torch.arange(0, W).view(1,-1).repeat(H,1)
yy = torch.arange(0, H).view(-1,1).repeat(1,W)
xx = xx.view(1,H,W,1).repeat(B,1,1,1)
yy = yy.view(1,H,W,1).repeat(B,1,1,1)
grid = torch.cat((xx,yy), -1).float() # [B, H, W, 2]

flow = torch.zeros(B, H, W, 2, device='cpu').float()
flow[:, :, :, 0] = 1

dummy_grid = grid + flow

dummy_inputs = [dummy_image, dummy_grid]
with torch.no_grad():
    model.eval()
    openvino_warp_out, original_warp_out = model(dummy_inputs)
    print('Original:')
    print(dummy_image)
    print('F.grid_sample:')
    print(original_warp_out)
    print('openvino sample:')
    print(openvino_warp_out)
    diff = torch.abs(original_warp_out - openvino_warp_out)
    print("the diff bettwen the openvino and original:", diff.mean())
```

1. For `F.grid_sample` grid needs to be scaled to [-1, 1]
2. Added `align_corners=True`, so that behaviour is the same
3. I also changed `* mask` to `.clamp(0, W - 1)` in `bilinear_sample_noloop`. This works more correct on edges. Thanks to you, I noticed that :)

Output of this script:

```
Original:
tensor([[[[ 0.4901,  0.5032, -0.6352, -0.2302,  0.4369,  0.6042],
          [ 0.3520, -1.7715, -0.2524, -1.0266,  1.1973,  0.7915],
          [ 0.2708, -0.9614, -1.3354, -1.1176,  0.0639, -2.0700],
          [-0.0564, -0.3655, -1.0210, -0.4482, -1.0725,  0.3052],
          [-2.0207,  0.2248,  0.5578, -2.4132, -0.2780,  0.7859],
          [ 0.2179, -0.9936, -0.5161, -0.4167, -0.4414,  0.8001]]]])
F.grid_sample:
tensor([[[[ 0.5032, -0.6352, -0.2302,  0.4369,  0.6042,  0.0000],
          [-1.7715, -0.2524, -1.0266,  1.1973,  0.7915,  0.0000],
          [-0.9614, -1.3354, -1.1176,  0.0639, -2.0700,  0.0000],
          [-0.3655, -1.0210, -0.4482, -1.0725,  0.3052,  0.0000],
          [ 0.2248,  0.5578, -2.4132, -0.2780,  0.7859,  0.0000],
          [-0.9936, -0.5161, -0.4167, -0.4414,  0.8001,  0.0000]]]])
openvino sample:
tensor([[[[ 0.5032, -0.6352, -0.2302,  0.4369,  0.6042,  0.0000],
          [-1.7715, -0.2524, -1.0266,  1.1973,  0.7915,  0.0000],
          [-0.9614, -1.3354, -1.1176,  0.0639, -2.0700, -0.0000],
          [-0.3655, -1.0210, -0.4482, -1.0725,  0.3052,  0.0000],
          [ 0.2248,  0.5578, -2.4132, -0.2780,  0.7859,  0.0000],
          [-0.9936, -0.5161, -0.4167, -0.4414,  0.8001,  0.0000]]]])
the diff bettwen the openvino and original: tensor(1.5315e-08)
```

**Comment by DunguTmp** [comment]
@hocop ，Thank you very much for the sample code. This is very helpful to my follow-up work, thank you again.

Best regards,
DwenGu

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or start a new issues if additional assistance is needed.

Sincerely,
Sahira
