### ISSUE TITLE
truble build samples 

### ISSUE THREAD

**Issue by LorenzoGorza** [openvinotoolkit/openvino#366]
Hi, I'm trying to build the sample using cmake, but I get this error: 

`CMake Error at samples/CMakeLists.txt:54 (message):
  Only 64-bit supported on Windows`
anyone solve the issue? 

thanks

**Comment by asuhov** [comment]
Hello, which cmake generator did you use? Probably you didn't specify x64 platform in the generator name, please try one of the following commands:

```
cmake -G "Visual Studio 15 2017 Win64" <path_to_the_samples>
cmake -G "Visual Studio 16 2019" -A x64 <path_to_the_samples>
```

Windows 32-bit systems are not supported by dldt.

**Comment by ilyachur** [comment]
@LorenzoGorza OpenVINO doesn't support 32-bit systems. I will close the ticket. Feel free to reopen it if you have any questions.
