### ISSUE TITLE
Request for supporting Cost Volume layers

### ISSUE THREAD

**Issue by hocop** [openvinotoolkit/openvino#3660]
Optical flow archtectures like FlowNetC and PWCNet use Cost Volume operation.
It computes correlation (dot product) between neighboring features in 2d feature maps.

Implementation example in cuda: https://github.com/ClementPinard/Pytorch-Correlation-extension

This layer cannot be implemented with usual convolutions.
Are there any plans of supporting this layer in the future?

**Comment by jgespino** [comment]
Hi @hocop 

Same question as your other feature request: Is there a particular framework that you are already using with FlowNetC and PWCNet?

Regards,
Jesus

**Comment by hocop** [comment]
Hi @jgespino 

Same answer also:)
Currently all implementations of PWCNet I know work only with cuda. My code is in pytorch, so no inference on ML-specialized devices are available.

**Comment by jgespino** [comment]
Hi @hocop

Thank you, I have submitted a feature request for the development team to consider. At this time there is no commit, I will let you know once I have additional information.

Regards,
Jesus

Ref. 46161

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or start a new issues if additional assistance is needed.

Sincerely,
Sahira
