### ISSUE TITLE
Error Inference Engin EXCEPTION C++

### ISSUE THREAD

**Issue by masgh021** [openvinotoolkit/openvino#367]
hello everybody 

i installed openvino library with this tutorial this
and i link visual studio to inference engine library like this image 
image1 
IMAGE ADDRESS : pasteboard.co/INjdlBx.png
and lib folder and Files are in this image 

 image2 
IMAGE ADDRESS : pasteboard.co/INjf2Cc.png

my problem is in c++ code  sample 
when visual studio runinng program 
i get this error exception that .

 exceptionErrorImage   
IMAGE ADDRESS : pasteboard.co/INjgyc5.png

this is the error text 

Unhandled exception at 0x00007FF9D7BF4048 in Openvino_cv64_number2.exe: Microsoft C++ exception: InferenceEngine::details::InferenceEngineException at memory location 0x000000BF8EAFE5D0.
for the first line .
Core ie;

my laptop is lenovoE530
intel i5-3210M

i test my code with other system 

with this details 
intel corei7 8700k

but same error for running .

please help me .

**Comment by vladimir-dudnik** [comment]
@masgh021 could you please try to build OpenVINO samples and see if there are any difference with your application?

**Comment by ilyachur** [comment]
@masgh021 Can you try to use the last version of the OpenVINO?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issue is not actual as no response. Closing it. Feel free to reopen it or better create a new one.
