### ISSUE TITLE
Documentation: OpenCL Kernel

### ISSUE THREAD

**Issue by OliverScherf** [openvinotoolkit/openvino#368]
Hello,
I'm having a hard time to understand how the Kernels work that are in the [inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels](https://github.com/opencv/dldt/tree/2019/inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels) directory. 

Is there any more documentation of how they work and how they are structured? The names are rather cryptic as well, making it hard to conclude from they are actually doing.

Any help is much appreciated.

**Comment by vladimir-paramuzov** [comment]
@OliverScherf  Unfortunately we don't have docs for cldnn internals. 

Basically, each kernel have 2 parts: host part and device part. 

Host part is cpp+h files for each kernel located in inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/<primitive_type>/<kernel_name>.{cpp,h}
Usually <kernel_name> is built as `<primitive_type>_kernel_<layout_or_precision_description>{any_additional_suffix}`. 
E.g. **convolution_kernel_fs_byx_fsv32_1x1.cpp**:
- primitive type - convolution
- main layout - fs_byx_fsv32
- additional suffix - 1x1 - which means that the kernel has some specific optimizations for 1x1 convolutions

Device part is located in inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/<kernel_template_name.cl>

<kernel_template_name> has pretty similar pattern: 
`<primitive_type>_gpu_<layout_or_precision_description>{any_additional_suffix}`.
 E.g. **convolution_gpu_fs_byx_fsv32_1x1.cl**

Each kernel's class in the host code specifies corresponding ocl template name:
```cpp
ConvolutionKernel_fs_byx_fsv32_1x1::ConvolutionKernel_fs_byx_fsv32_1x1()
    : ConvolutionKernelBase("convolution_gpu_fs_byx_fsv32_1x1") {}
``` 
 
The logic might be a bit different for more complex kernels, but this is the most common naming rules for now.

As for "how they work": each .cl file is a template which is used to generate actual code for each layer in a network. cldnn automatically adds a lot of definitions for given tensor sizes / operation parameters / used data types / etc (see https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/thirdparty/clDNN/kernel_selector/core/kernel_base.cpp#L43 for details)

If you want to dump fully defined ocl kernels for your network, you might want to use `KEY_CLDNN_SOURCES_DUMPS_DIR` plugin option (see https://docs.openvinotoolkit.org/latest/_docs_IE_DG_supported_plugins_CL_DNN.html for details)

**Comment by ilya-lavrenov** [comment]
@vladimir-paramuzov may be we can put these notes into some readme for cldnn?

**Comment by vladimir-paramuzov** [comment]
Docs for developers have been added to the wiki: https://github.com/openvinotoolkit/openvino/wiki/GPUPluginArchitecture
