### ISSUE TITLE
Intel Neural Compute Stick 2 Issue in installing openvino on raspberrypi 

### ISSUE THREAD

**Issue by dhruvsheth-ai** [openvinotoolkit/openvino#3683]
##### System information (version)
 I get the following issue while setting up Intel Neural Compute Stick 2 on Raspberry Pi 4
The issue comes when I enter the command - `make && make install`
The following is the error that I see:
`make[1]: Entering directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
make[2]: Entering directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
make[2]: Leaving directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
[  4%] Built target libjpeg-turbo
make[2]: Entering directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
make[2]: Leaving directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
[  7%] Built target libtiff
make[2]: Entering directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
make[2]: Leaving directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
make[2]: Entering directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
[  7%] Building C object 3rdparty/libwebp/CMakeFiles/libwebp.dir/src/utils/utils.c.o
cc1: warning: ‘-Werror=’ argument ‘-Werror=non-virtual-dtor’ is not valid for C
cc1: warning: command-line option ‘-Wsign-promo’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-delete-non-virtual-dtor’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-fvisibility-inlines-hidden’ is valid for C++/ObjC++ but not for C
[  7%] Linking C static library ../lib/liblibwebp.a
make[2]: Leaving directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
[ 14%] Built target libwebp
make[2]: Entering directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
Scanning dependencies of target libjasper
make[2]: Leaving directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
make[2]: Entering directory '/home/raspberrypi/OpenVINO/opencv-4.1.0/build'
[ 14%] Building C object 3rdparty/libjasper/CMakeFiles/libjasper.dir/jas_cm.c.o
cc1: warning: ‘-Werror=’ argument ‘-Werror=non-virtual-dtor’ is not valid for C
cc1: warning: command-line option ‘-Wsign-promo’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-delete-non-virtual-dtor’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-fvisibility-inlines-hidden’ is valid for C++/ObjC++ but not for C
[ 14%] Building C object 3rdparty/libjasper/CMakeFiles/libjasper.dir/jas_debug.c.o
cc1: warning: ‘-Werror=’ argument ‘-Werror=non-virtual-dtor’ is not valid for C
cc1: warning: command-line option ‘-Wsign-promo’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-delete-non-virtual-dtor’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-fvisibility-inlines-hidden’ is valid for C++/ObjC++ but not for C
[ 14%] Building C object 3rdparty/libjasper/CMakeFiles/libjasper.dir/jas_getopt.c.o
cc1: warning: ‘-Werror=’ argument ‘-Werror=non-virtual-dtor’ is not valid for C
cc1: warning: command-line option ‘-Wsign-promo’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-delete-non-virtual-dtor’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-fvisibility-inlines-hidden’ is valid for C++/ObjC++ but not for C
[ 14%] Building C object 3rdparty/libjasper/CMakeFiles/libjasper.dir/jas_icc.c.o
cc1: warning: ‘-Werror=’ argument ‘-Werror=non-virtual-dtor’ is not valid for C
cc1: warning: command-line option ‘-Wsign-promo’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wno-delete-non-virtual-dtor’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-fvisibility-inlines-hidden’ is valid for C++/ObjC++ but not for C
^Cmake[2]: *** wait: No child processes.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1760: 3rdparty/libjasper/CMakeFiles/libjasper.dir/all] `

**Comment by dhruvsheth-ai** [comment]
Here is a screenshot:
![Screenshot from 2020-12-18 22-56-35](https://user-images.githubusercontent.com/67831664/102642871-56a3dc80-4184-11eb-8788-1bd024ced8d7.png)

**Comment by jgespino** [comment]
Hi @dhruvsheth-ai 

Is there a particular documentation you are following? It looks like you are building OpenVINO from source to use the Intel Neural Compute Stick 2. There is an easier route if you are just getting started, please follow this [guide](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_raspbian.html) to install the pre-built package of the OpenVINO toolkit for Raspbian OS. This will be a lot quicker than building from source. Is there any reason you are trying to built from source?

Regards,
Jesus

**Comment by dhruvsheth-ai** [comment]
Hi @jgespino thanks for the reply!
I was trying to follow this tutorial on Intel to get started, but seems that the one you suggested is a better one, will try that out and let uk, if I encounter any error
The one I was following: https://software.intel.com/content/www/us/en/develop/articles/raspberry-pi-4-and-intel-neural-compute-stick-2-setup.html

Just out of curiosity, what is the error I am facing when I build from source 
PS: I am using Ubuntu 20.10 on the Pi 4-8gb, so I hope the one you suggested works on Ubuntu as well
Thanks!

**Comment by jgespino** [comment]
Hi @dhruvsheth-ai 

Both guides are written for Raspberry Pi running Raspbian OS, the pre-built package may not work as well. In this case, I recommend building from source as your initial question.

What is the cmake command used with opencv prior to running make && make install?

Regards,
Jesus
