### ISSUE TITLE
[Bug] Object detection results are different on CPU and MYRIAD

### ISSUE THREAD

**Issue by alrzmshy** [openvinotoolkit/openvino#3690]
##### System information (version)

- OpenVINO => 2021.2
- Operating System / Platform => Ubuntu
- Problem classification: Performance mismatch
- Framework: ONNX/IR
- Model name: YOLOv5

##### Detailed description
After obtaining an ONNX model from training model in PyTorch, I test mAP on my dataset using OpenVINO for inference. I can run inference on CPU and MYRIAD with no problem. However, there's a significant drop in performance when I switch to MYRIAD for inference. I have checked conversion to IR. The results on the different devices match what I obtain with the ONNX weights and the difference between CPU and MYRIAD still remains. In the preprocessing of the image before passing it to the model, I checked and saw that division by 255 inside and outside the model has absolutely no effect on the performance. So I'm wondering what is really happening. Are there layers that are not supported by MYRIAD? Is it possible to identify them?

##### Steps to reproduce

I attach a sample ONNX weight: [yolov5s.zip](https://github.com/openvinotoolkit/openvino/files/5724430/yolov5s.zip)

Results on CPU:
<pre>
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95
                 all         497    3.42e+03       0.882       0.924        0.98       0.745
             class_1         497    1.16e+03       0.891       0.946       0.983       0.741
             class_2         497    2.14e+03       0.884        0.94       0.983       0.777
             class_3         497         122       0.871       0.885       0.975       0.717
</pre>
Results on MYRIAD:
<pre>
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95 
                 all         497    3.42e+03       0.934       0.845       0.982       0.676
             class_1         497    1.16e+03       0.922       0.894       0.983       0.69
             class_2         497    2.14e+03        0.95       0.872       0.988       0.735
             class_3         497         122       0.931        0.77       0.974       0.605
</pre>

Update:
I reverted to version 2020.4 and with `ie.set_config({'VPU_HW_STAGES_OPTIMIZATION': 'NO'}, "MYRIAD")` , the results on CPU and MYRIAD match. I don't understand why this option has been deprecated in the new versions.

**Comment by jgespino** [comment]
Hi @alrzmshy 

Could you try to convert your model again and adding `--scale 255` to the model optimizer command? Then in your inference code, do not do any scaling (image/255). If you continue to see a difference, please share your inference code, Model Optimizer command and test input to reproduce.

> I reverted to version 2020.4 and with ie.set_config({'VPU_HW_STAGES_OPTIMIZATION': 'NO'}, "MYRIAD") , the results on CPU and MYRIAD match. I don't understand why this option has been deprecated in the new versions.

This configuration was only for internal testing, if inference results are not accurate with optimization turned on then it's considered a bug.

Regards,
Jesus

**Comment by alrzmshy** [comment]
I just tested after installing the most recent version 2021.2.200 and the results are good. I had tested `--scale 255` before with 2021.1 version and it was not effective. I think this issue needs proper documentation for future releases. It's a very subtle point and not at all evident.

**Comment by jgespino** [comment]
Hi @alrzmshy 

I am glad it's working on OpenVINO 2021.2 release, we will add this to our support knowledge base!

Regards,
Jesus
