### ISSUE TITLE
My code with -fopenmp costs more times than without  -fopenmp. 

### ISSUE THREAD

**Issue by jlygit** [openvinotoolkit/openvino#370]
My code with -fopenmp costs more times than without  -fopenmp. 
PS: i use Inference Engine with OpenMP threading library

**Comment by yury-gorbachev** [comment]
Support for OpenMP is generally being phased out in favor of TBB. Is there a reason why OpenMP is preferred solution for you?
Also, what do you mean by costs? Size/performance/etc?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
