### ISSUE TITLE
Feature request: oneDNN partial/full update to one of the recent releases

### ISSUE THREAD

**Issue by dev0x13** [openvinotoolkit/openvino#3706]
As far as I can see, `master` branch of the OpenVINO toolkit uses a forked version of oneDNN from `v0.21_for_ie_master` branch. However, this version of oneDNN seems to have a lot of unsafe `malloc` invocations (e.g. in `cpu_primitve_t` struct, which as basically a basis for all the computation kernels) which are not followed by the null pointer checks, i.e. there are no checks whether the allocation failed. This leads to segfaults when not enough memory is available instead of correct error handling and exiting. This behavior is observed on my side at least for default Windows OS configuration. I assume that malloc never fails on Linux, but anyway - it is implementation defined.
I've tried to fix this by myself, but found out that this is hard to achieve since some of the unsafe malloc calls are happening in constructors, so we can't handle them by returning the error code. Then I checked oneDNN master for these unsafe allocations and found out that all the places where they had happened were heavily refactored, perhaps specifically in order to handle this kind of situation.
So feature request is either to bump oneDNN version used in OpenVINO or to update these particular parts of its code (I don't know whether it is possible). Or is this kind of work is already planned?
Anyway, thank you for your work, and I hope that even if this issue won't be fixed, it will help ones facing weird segmentation fault crashes of the toolkit on low RAM to figure out what is happening.

**Comment by ilya-lavrenov** [comment]
CC @dmitry-gorokhov

**Comment by ilya-lavrenov** [comment]
@dev0x13 see https://github.com/openvinotoolkit/openvino/pull/3725

**Comment by dev0x13** [comment]
@ilya-lavrenov Thank you! This seems to be exactly I was looking for. Don't you mind if I'll keep this issue opened until the PR is merged for tracking sake?

**Comment by ilya-lavrenov** [comment]
@dev0x13 sure!

**Comment by dmitry-gorokhov** [comment]
@dev0x13 Related PR was merged into master branch

**Comment by dev0x13** [comment]
@dmitry-gorokhov Thank you!
