### ISSUE TITLE
[Bug]label:What is the default annotation data set of openvino

### ISSUE THREAD

**Issue by nmanhong** [openvinotoolkit/openvino#3726]
After I ran the test case rennet50-tf, there was only the number 285. I don’t know what it is. What annotation data set is used?

**Comment by nmanhong** [comment]
@jgespino

**Comment by nmanhong** [comment]
@ilya-lavrenov

**Comment by ilya-lavrenov** [comment]
CC @snosov1

**Comment by maxlytkin** [comment]
Hi @nmanhong 
According to [resnet-50-tf](https://docs.openvinotoolkit.org/latest/omz_models_public_resnet_50_tf_resnet_50_tf.html) documentation, it was pretrained on the ImageNet dataset. Depending on a demo or sample used, you might see different output. For example, [Hello Classification C++ Sample](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_samples_hello_classification_README.html) and [Image Classification Python* Sample](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_ie_bridges_python_sample_classification_sample_README.html) show Top-10 class IDs and their probability.

Top 10 results:
Image cat.bmp
classid probability
754 0.2142971
540 0.1585525
859 0.1001580
905 0.0999501
906 0.0711121
808 0.0357422
78 0.0212184
704 0.0110239
717 0.0107170
784 0.0103809

In your case, 285 looks like a class id for your image provided, so you have to further specify a labels file if needed. Please see particular demo/sample documentation on how to do so.

Hope this helps.
Best regards, Max.
