### ISSUE TITLE
[Bug]oneDNN adapts to openvino

### ISSUE THREAD

**Issue by nmanhong** [openvinotoolkit/openvino#3738]
If I have compiled oneDNN and it has been changed by us, how can I compile it into openvino? Is this okay?

**Comment by nmanhong** [comment]
@jgespino  @ilya-lavrenov  @dkurt

**Comment by ilya-lavrenov** [comment]
@nmanhong I suppose you need to update submodule here https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/thirdparty

But now sure that CPU plugin will work with your updated version.

**Comment by dkurt** [comment]
Seems like a duplicate with https://github.com/openvinotoolkit/openvino/issues/3706. If you custom oneDNN is based on OpenVINO's thirdparty oneDNN version - just apply the patch to thirdparty folder as @ilya-lavrenov pointed. If you use the newest version of oneDNN - see related topic regarding oneDNN update + PR.
