### ISSUE TITLE
YOLOv3: Loading Network to the Device

### ISSUE THREAD

**Issue by mmbajo** [openvinotoolkit/openvino#374]
OS: Windows 10
OpenVINO: openvino_2019.3.379

Hi,

I am trying to use YOLOv3 and OpenVINO through C++.
My code is in the link below.
https://github.com/mmbajo/OpenVINO/tree/master/open_yolo

![image](https://user-images.githubusercontent.com/47946517/73148005-672b0e80-40fd-11ea-81fa-051c9aaaabe4.png)

I have followed this post -> https://github.com/opencv/dldt/issues/173
But i can't seem to get my code to work.
Please help.

**Comment by jgespino** [comment]
Hi mmbajo,

Do you see the same behavior with our [Object Detection YOLO* V3 C++](https://github.com/opencv/open_model_zoo/tree/master/demos/object_detection_demo_yolov3_async) Demo? Could you try to load your model using the latest [OpenVINO toolkit 2020.1 release](https://software.intel.com/en-us/openvino-toolkit/choose-download) and our demo application?

Regards,
Jesus

**Comment by lazarevevgeny** [comment]
@mmbajo is the question actual? What is the reason to not use proposed YOLO* V3 demo?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
