### ISSUE TITLE
Interactive Mode

### ISSUE THREAD

**Issue by nmanhong** [openvinotoolkit/openvino#3763]
I want to enter the interactive mode, because of my yolov3 pb model, the nms node indicates that it does not support, but I found that under my deployment_tools/tools directory, there is only the folder compile_tool, and I cannot enter the interactive mode

**Comment by nmanhong** [comment]
@ilya-lavrenov  @jgespino

**Comment by nmanhong** [comment]
tensorflow model

**Comment by avitial** [comment]
@nmanhong, please fill out the issue template and provide additional information.
- Environment details (OS, branch version, python version, cmake version, etc.)
- Executed commands
- Steps to reproduce

Regards,
Luis

**Comment by nmanhong** [comment]
@avitial 
I have tried both the x86 ubuntu system and mips64 linux system. They are both like this. The branches I tested are master and releases/2020/4.1. They are all in the same situation. I refer to "https://github. com/openvinotoolkit/openvino/issues/3165#issuecomment-729130304" This is for operation, but I found that my deployment_tools/tools directory does not contain the file they said

**Comment by nmanhong** [comment]
My python version is 3.7.9 and cmake version is 3.18

**Comment by nmanhong** [comment]
https://github. com//issues/3165#issuecomment-729130304

**Comment by nmanhong** [comment]
https://github.com/david-drew/OpenVINO-Custom-Layers/tree/master/2019.r2.0

**Comment by nmanhong** [comment]
My command is this:
"Python3 /home/loongson/openvino/model-optimizer/mo_tf.py --input_model /home/loongson/models/frozen_graph_yolov3.pb --input_shape=[1,608,608,3] --data_type=FP32"

Prompted this:
"[ WARNING] Please set `version` attribute for node yolov3/yolo_nms/combined_non_max_suppression/CombinedNonMaxSuppression with type=<UNKNOWN>
[ERROR] List of operations that cannot be converted to Inference Engine IR:
[ERROR] CombinedNonMaxSuppression (1)
[ERROR] yolov3/yolo_nms/combined_non_max_suppression/CombinedNonMaxSuppression
[ERROR] Part of the nodes was not converted to IR. Stopped.
  For more information please refer to Model Optimizer FAQ, question #24. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=24#question-24)"

**Comment by nmanhong** [comment]
@avitial 
I just want to know how to add a custom layer

**Comment by avitial** [comment]
@nmanhong thanks for the info, the tutorial you were following from the referenced issue seems to apply to 2019R2. If you'd like to implement custom operations please take a look at the following document [Custom Operations Guide](https://docs.openvinotoolkit.org/latest/openvino_docs_HOWTO_Custom_Layers_Guide.html) which applies to your used version.

If you still however face the interactive mode issue let me know.

Regards,
Luis
