### ISSUE TITLE
[Bug]error with slice

### ISSUE THREAD

**Issue by nmanhong** [openvinotoolkit/openvino#3779]
[ ERROR ]  Failed to match nodes from custom replacement description with id 'RetinaNetFilteredDetectionsReplacement':
It means model and custom replacement description are incompatible.
Try to correct custom replacement description according to documentation with respect to model node names
[ ERROR ]  Cannot infer shapes or values for node "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Slice".
[ ERROR ]  The non-constant start/end values for Slice operation "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Slice" are not supported
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Slice.infer at 0xffc96dd5f0>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.

**Comment by nmanhong** [comment]
python3 /home/loongson/openvino/model-optimizer/mo_tf.py --input_model /home/loongson/models/frozen_inference_graph.pb --input_shape=[1,640,640,3] --data_type=FP32

**Comment by nmanhong** [comment]
@ilya-lavrenov @jgespino

**Comment by jgespino** [comment]
Hi @nmanhong 

Please complete the issue template and share additional information about your model (Tensorflow version, custom or pre-trained model, topology). Your model optimizer command may need additional parameters such as  `--transformations_config` to use a custom sub-graph replacement file. Depending on the model you are using, we have some available under `/opt/intel/openvino_2021/deployment_tools/model_optimizer/extensions/front/tf`.

Regards,
Jesus

**Comment by nmanhong** [comment]
My tensorflow version is 1.18 and my model is retinanet. I forgot what the pre-training model is? I guess it is imagenet.

**Comment by nmanhong** [comment]
![sendpix0](https://user-images.githubusercontent.com/60744164/103842331-4d0ee580-505b-11eb-817b-03e856d505aa.jpg)

**Comment by nmanhong** [comment]
@jgespino

**Comment by nmanhong** [comment]
input_value = node.in_port(0).data.get_value()
        input_shape = node.in_port(0).data.get_shape()
        print("node.in_port(0): ",node.in_port(0))
        print("input_value: ",input_value)
        print("input_shape: ",input_shape)
        starts = node.in_port(1).data.get_value()
        ends = node.in_port(2).data.get_value()
        print("starts: ",starts)
        #print("\n")
        print("ends: ",ends)
        #print("\n")
        if starts is None or ends is None:
            raise Error('The non-constant start/end values for Slice operation "{}" are not supported'.format(node.name))

I want to print out that ends is the output of the previous node is empty, what should I do

**Comment by nmanhong** [comment]
the ends is none

**Comment by nmanhong** [comment]
https://drive.google.com/file/d/1eVqCopUJS8bsL3Rbi7mpuTxeNwC1XLBO/view?usp=sharing
this is my model

**Comment by nmanhong** [comment]
shape is 800*800

**Comment by nmanhong** [comment]
@dkurt

**Comment by jgespino** [comment]
Hi @nmanhong 

Is the frozen model you provided custom trained or pre-trained (model from TensorFlow Repository). We have a replacement file for retinanet (retinanet.jsos) under /opt/intel/openvino_2021/deployment_tools/model_optimizer/extensions/front/tf but it does not match your model architecture. 

If you are using the pre-trained model could you try using the supported [retinanet-tf model](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/retinanet-tf/retinanet-tf.md)? You can download and convert using the following commands:

```
python3 /opt/intel/openvino_2021/deployment_tools/tools/model_downloader/downloader.py --name retinanet-tf
python3 /opt/intel/openvino_2021/deployment_tools/tools/model_downloader/converter.py --name retinanet-tf
```

Regards,
Jesus

**Comment by nmanhong** [comment]
Hi @jgespino
         The key is the model we trained. Can you help me see what went wrong?
         I also downloaded related models(mask_rcnn_resnet50_atrous_coco_2018_01_28.tar.gz/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz) for testing on your website "https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html", and found that the same error was prompted. It should all be in the post-processing of the model.

**Comment by jgespino** [comment]
Hi @nmanhong 

Could you try to freeze the model using tensorflow 1.15.4?

Regarding the two additional models from the open model zoo, please try to download and convert using the scripts. You should be able to see the entire model optimizer command when converting. Additionally, you can see the model optimizer parameters being used in the model.yml for [ssd_resnet50_v1_fpn_coco](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/ssd_resnet50_v1_fpn_coco/model.yml) and [mask_rcnn_resnet50_atrous_coco](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/mask_rcnn_resnet50_atrous_coco/model.yml).

ssd_resnet50_v1_fpn_coco:
```
python3 /opt/intel/openvino_2021/deployment_tools/tools/model_downloader/downloader.py --name ssd_resnet50_v1_fpn_coco
python3 /opt/intel/openvino_2021/deployment_tools/tools/model_downloader/converter.py --name ssd_resnet50_v1_fpn_coco
```
mask_rcnn_resnet50_atrous_coco:
```
python3 /opt/intel/openvino_2021/deployment_tools/tools/model_downloader/downloader.py --name mask_rcnn_resnet50_atrous_coco
python3 /opt/intel/openvino_2021/deployment_tools/tools/model_downloader/converter.py --name mask_rcnn_resnet50_atrous_coco
```

Regards,
Jesus

**Comment by nmanhong** [comment]
@jgespino
Hi
   Unfortunately, I tested the same problem, is there any way to solve it? Or just use my model to solve this problem, because our training and deployment are not the same person in the same department, and their model can be tested by tensorflow

**Comment by jgespino** [comment]
@nmanhong Do you have a pipeline.config file available for your custom trained model?

**Comment by nmanhong** [comment]
@jgespino 
no,i don't have
