### ISSUE TITLE
 Some questions about openvino

### ISSUE THREAD

**Issue by menggege321** [openvinotoolkit/openvino#3782]
Hello, openvino can complete the acceleration by calling the integrated graphics card. Is this principle completed by calling the OpenCL library? 
Looking forward to your reply， Thank you！

**Comment by jgespino** [comment]
Hi @menggege321 

Thanks for reaching out! The OpenVINO toolkit uses the Intel® Compute Library for Deep Neural Networks (clDNN) to infer on Intel® Processor Graphics. Please take a look at the [GPU Plugin documentation](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_CL_DNN.html) for additional information.

Regards,
Jesus
