### ISSUE TITLE
Help upgrading from openvino 2019

### ISSUE THREAD

**Issue by antithing** [openvinotoolkit/openvino#3783]
Hi, I am updating some old code to use the new version of openvino, and cannot find any help anywhere.

There are three issues:
1
```
    InferenceEngine::Core ie;
    std::cout << "\n1. Load plugin..." << std::endl;
    std::cout << ie.GetVersions(DEVICE) << std::endl;
    ie.AddExtension(std::make_shared<Extensions::Cpu::CpuExtensions>(), "CPU");
```
will no longer compile. Looking at the samples, i need to do this:

```
	IExtensionPtr extension_ptr = make_so_pointer<IExtension>(xmlFile);
	ie.AddExtension(extension_ptr, "CPU");
```

Is this correct? Is it the model xml that is loaded there?

2.
```
InferenceEngine::CNNNetReader networkReader;
	networkReader.ReadNetwork(xmlFile);
	networkReader.ReadWeights(binFile);
	InferenceEngine::CNNNetwork network = networkReader.getNetwork();
	std::string networkName = networkReader.getName();
	std::cout << "    networkName is " << networkName << std::endl;
```
 I have adjusted to :
```
	CNNNetwork network = ie.ReadNetwork(xmlFile);
	std::string networkName = network.getName();
	std::cout << "    networkName is " << networkName << std::endl;
```

Is this correct? Is it the model xml that is loaded there?

3.
```
InferenceEngine::DataPtr outputInfo;
	for(const auto &out : outputsInfo)
	{	
		if(out.second->getCreatorLayer().lock()->type == "Eltwise") //alpha
		{
			outputName = out.first;
			std::cout << "    outputName is " << outputName << std::endl;
			outputInfo = out.second;
		}
	}
```
This one has me stuck. `getCreatorLayer` no longer exists. What should this replacement be?

Thanks!

**Comment by jgespino** [comment]
Hi @antithing 

Thanks for reaching out, the methods you are referencing have been deprecated in 2020.2 release, take a look at the [deprecated list](https://docs.openvinotoolkit.org/2020.2/deprecated.html#_deprecated000073) for additional information.

The first two changes to your application code seem to be done correctly, do you see any issues? The model is loaded when calling `LoadNetwork()`. As `getCreatorLayer()` was deprecated with the migration to IR v10 you can use ngraph function directly. Take a look at the following sample code on how to implement. 

https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/samples/object_detection_sample_ssd/main.cpp#L163

Regards,
Jesus

**Comment by antithing** [comment]
Hi, thanks for getting back to me!

Does this look right?

OLD:

```
	for(const auto &out : outputsInfo)
	{
		if(out.second->getCreatorLayer().lock()->type == "Eltwise") //alpha
		{
			outputName = out.first;
			std::cout << "    outputName is " << outputName << std::endl;
			outputInfo = out.second;
		}
	}
```
NEW:

```
if (auto ngraphFunction = network.getFunction()) {
		for (const auto& out : outputsInfo) {
			for (const auto & op : ngraphFunction->get_ops()) {
				if (op->get_type_name == "Eltwise")  //Is this correct?
				{
					outputName = out.first;
					std::cout << "    outputName is " << outputName << std::endl;
					outputInfo = out.second;
				}
			}
		}

	}
```

Thanks again!

**Comment by antithing** [comment]
...related question:

Are there binary installers for old versions so that I can quickly test this code?

Specifically: openvino  2019.3.334

Thanks!

**Comment by jgespino** [comment]
Hi @antithing 

What error messages are you running into? Is it possible for you to share your code and model to try on my end?

Regards,
Jesus

**Comment by antithing** [comment]
[src.zip](https://github.com/openvinotoolkit/openvino/files/5788302/src.zip)

Hi Jesus, thank you again! Please see attached. I actually have it compiling now, but it will not run...

**Comment by avitial** [comment]
@antithing glancing at provided code in src.zip, lines 50 and 51 extension file is NOT _xmlFile_ file. Commenting these lines works but if you have custom operations, you need to pass the generated custom extension file. CPU extensions library was removed in OpenVINO >=2020.1, extensions were moved into the plugin. In other words no need to specify the extensions file unless you require it (for more info on this change see [Release Notes](https://software.intel.com/content/www/us/en/develop/articles/openvino-relnotes-2020.html)).

Line 117 which is part of your NEW code, throws _warning: comparison with string literal results in unspecified behavior [-Waddress]_, the following gets rid of that warning: `if (strcmp(op->get_type_name(),"Eltwise"))` **OR** `if (strcmp(op->get_type_info().name,"Eltwise"))`. These changes seem to make the code compile and run, although resulting _save.png_ looks odd, may need additional check and see if the NEW code is equivalent to your OLD code. Hope this helps. 

~Luis

**Comment by antithing** [comment]
@avitial Thank you very much! This compiles, but I am seeing an error when I run it, on the very first line:
`InferenceEngine::Core ie;`

Unhandled exception at 0x00007FF9F7593B29 in OV_Matte.exe: Microsoft C++ exception: InferenceEngine::details::InferenceEngineException at memory location 0x0000006FDBEFD140. occurred

Am I missing a lib perhaps? Is there an example cmake available for building openvino projects?

Thanks again!

**Comment by avitial** [comment]
@antithing I usually just add samples by duplicating an app from the inference engine samples and modify it according to the app needs, then compile the app that way. For example in Linux for the app _upgrade_from_2019_, in a directory of your choice run `cmake /opt/intel/openvino_2021.2.185/inference_engine/samples/cpp/ .`  then run `make upgrade_from_2019` (in my case _upgrade_from_2019_ is the name of the app). In Windows it might be slightly different, running `build_samples_msvc.bat` should do it for you. If you still face issues, share details on how you compiled your app. BTW your app is running on Windows as well, hope this helps.

upgrade_from_2019/
├── CMakeLists.txt
├── main.cpp
└── README.md

--- CMakeLists.txt ---
ie_add_sample(NAME upgrade_from_2019
              SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/main.cpp"
              DEPENDENCIES format_reader)

find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
find_package(ngraph REQUIRED)
target_link_libraries(upgrade_from_2019 PRIVATE ${OpenCV_LIBRARIES})
target_link_libraries(upgrade_from_2019 PRIVATE ${NGRAPH_LIBRARIES})

~Luis

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
