### ISSUE TITLE
[Bug] some error of "aocl install" using Intel FPGA

### ISSUE THREAD

**Issue by YongtaoHuang1994** [openvinotoolkit/openvino#3789]
##### System information

- OpenVINO => 2020.3
- Operating System / Platform => Ubuntu 18.04
- Hardware => Intel® Arria® 10 FPGA (Mustang-F100-A10) Speed Grade 1

##### Detailed description
When I installed aocl, something wrong happened.

```
root@2fee3bb6cca3:/usr/src# aocl install
Do you want to install /opt/altera/aocl-pro-rte/aclrte-linux64/board/a10_1150_sg1? [y/n] y
aocl install: Adding the board package /opt/altera/aocl-pro-rte/aclrte-linux64/board/a10_1150_sg1 to the list of installed pckages
aocl install: Setting up FCD
aocl install: Running install from /opt/altera/aocl-pro-rte/aclrte-linux64/board/a10_1150_sg1/linux64/libexec
Looking for kernel source files in /lib/modules/4.15.0-128-generic/build
Using kernel source files from  /lib/modules/4.15.0-128-generic/build
Building driver for BSP with name a10_1150_sg1
make: Entering directory '/usr/src/linux-headers-4.15.0-128-generic'
  CC [M]  /tmp/opencl_driver_3mSJGV/aclpci_queue.o
  CC [M]  /tmp/opencl_driver_3mSJGV/aclpci.o
  CC [M]  /tmp/opencl_driver_3mSJGV/aclpci_fileio.o
  CC [M]  /tmp/opencl_driver_3mSJGV/aclpci_dma.o
  CC [M]  /tmp/opencl_driver_3mSJGV/aclpci_pr.o
  CC [M]  /tmp/opencl_driver_3mSJGV/aclpci_cmd.o
  LD [M]  /tmp/opencl_driver_3mSJGV/aclpci_a10_1150_sg1_drv.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /tmp/opencl_driver_3mSJGV/aclpci_a10_1150_sg1_drv.mod.o
  LD [M]  /tmp/opencl_driver_3mSJGV/aclpci_a10_1150_sg1_drv.ko
make: Leaving directory '/usr/src/linux-headers-4.15.0-128-generic'
modprobe: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'aclpci_a10_1150_sg1_drv': Operation not permitted
root@2fee3bb6cca3:/usr/src#

```
Could you please tell me what this error means? Thank you.
```
modprobe: ERROR: ../libkmod/libkmod-module.c:793 kmod_module_remove_module() could not remove 'aclpci_a10_1150_sg1_drv': Operation not permitted

```

**Comment by avitial** [comment]
@YongtaoHuang1994 have you tried rebooting your system and re-run `aocl install`? If not please do so and let us know the outcome. Error might be related to UEFI secure boot, is this the first time you run into this problem? I've just realized you are on OpenVINO v2020.3, please note Intel® Arria® 10 FPGA (Mustang-F100-A10) Speed Grade 1 is not available in the OpenVINO 2020.3 package. If you use Intel® Vision Accelerator Design with an Intel® Arria 10 FPGA (Mustang-F100-A10) Speed Grade 1, we recommend continuing to use the Intel® Distribution of OpenVINO™ toolkit 2020.1 release. This info can be found [here](https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_VisionAcceleratorFPGA_Configure.html), it could also be the source of the problem.

Regards,
Luis

**Comment by YongtaoHuang1994** [comment]
@avitial 
Really thank you for your help. I have tested different version of openvion, including 2019.01, 2020.03, 2020.04. The errors are all the same. 
In fact, I successfully tested it on my host computer. But I still want the Intel FPGA can work in a Docker container.  The error happened in the Docker container.
Thank you.

**Comment by avitial** [comment]
@YongtaoHuang1994 got it, not sure if the regular way of installing the OpenVINO package as per [install instructions](https://docs.openvinotoolkit.org/2020.1/_docs_install_guides_installing_openvino_linux_fpga.html) work on a regular Docker container. Perhaps that is the reason of `aocl install` not working, is this what you are attempting to do? My advise would be to refer to [Use a Docker* Image for FPGA](https://docs.openvinotoolkit.org/2020.1/_docs_install_guides_installing_openvino_docker_linux.html#use_a_docker_image_for_fpgal) and follow the pre-requites listed there. 

~Luis

**Comment by YongtaoHuang1994** [comment]
@avitial Thank you. These info is really helpful. Let me have a try.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Comment by belanasaikiran** [comment]
when I tried to run `aocl diagnose` on a basic docker container after  install Intel_RTE and sourcing all variables with inti_env.sh fil, I was getting an error which says `Error opening AFC: no driver available`

Can someone help me fix this ? I tried installing on a docker ubuntu container. regularly it works but not in containers.

Here's the output I'm getting when i run `aocl diagnose` :

`root@e757ccef1864:~# aocl diagnose
--------------------------------------------------------------------
ICD System Diagnostics                                              
--------------------------------------------------------------------

Using the following location for ICD installation: 
        /etc/OpenCL/vendors

Found 2 icd entry at that location:
        /etc/OpenCL/vendors/Altera.icd
        /etc/OpenCL/vendors/Intel_FPGA_SSG_Emulator.icd

the following OpenCL libraries are referenced in the icd files:
        libalteracl.so
        libintelocl_emu.so

checking LD_LIBRARY_PATH for registered libraries:
        libalteracl.so was registered on the system at /opt/opencl_rte/aclrte-linux64/host/linux64/lib
        libintelocl_emu.so was registered on the system at /opt/opencl_rte/aclrte-linux64/host/linux64/lib

Using the following location for fcd installations:
        /opt/Intel/OpenCL/Boards

Found 1 fcd entry at that location:
        /opt/Intel/OpenCL/Boards/dcp_bsp.fcd

the following OpenCL libraries are referenced in the fcd files:
        /root/intelrtestack/a10_gx_pac_ias_1_2_1_pv/opencl/opencl_bsp/linux64/lib/libintel_opae_mmd.so

checking LD_LIBRARY_PATH for registered libraries:
        /root/intelrtestack/a10_gx_pac_ias_1_2_1_pv/opencl/opencl_bsp/linux64/lib/libintel_opae_mmd.so was registered on the system.

ERROR: OpenCL host failed
--------------------------------------------------------------------
ICD diagnostics FAILED                                              
--------------------------------------------------------------------
--------------------------------------------------------------------
BSP Diagnostics                                                     
--------------------------------------------------------------------
Error opening AFC: no driver available
Error opening AFC: no driver available
Error opening AFC: no driver available
--------------------------------------------------------------------
Device Name:
acl0

BSP Install Location:
/root/intelrtestack/a10_gx_pac_ias_1_2_1_pv/opencl/opencl_bsp

Vendor: Intel Corp

DIAGNOSTIC_PASSED
--------------------------------------------------------------------
Error opening AFC: no driver available
--------------------------------------------------------------------
Device Name:
acl1

BSP Install Location:
/root/intelrtestack/a10_gx_pac_ias_1_2_1_pv/opencl/opencl_bsp

Vendor: Intel Corp

DIAGNOSTIC_PASSED
--------------------------------------------------------------------

Call "aocl diagnose <device-names>" to run diagnose for specified devices
Call "aocl diagnose all" to run diagnose for all devices
`
