### ISSUE TITLE
[Bug]Why do I not have relevant script files

### ISSUE THREAD

**Issue by nmanhong** [openvinotoolkit/openvino#3792]
deployment_tools/tools/model_downloader/downloader.py

I downloaded the master branch, but there is no model_downloader in my tools, only benchmark

**Comment by ilya-lavrenov** [comment]
@nmanhong this [file ](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/downloader/downloader.py)is a part of another [repo](https://github.com/openvinotoolkit/open_model_zoo)

**Comment by nmanhong** [comment]
> @nmanhong this [file ](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/downloader/downloader.py)is a part of another [repo](https://github.com/openvinotoolkit/open_model_zoo)

Which repo is that, can you tell me?

**Comment by nmanhong** [comment]
@ilya-lavrenov

**Comment by ilya-lavrenov** [comment]
@nmanhong just click on the link and you will go to https://github.com/openvinotoolkit/open_model_zoo

**Comment by nmanhong** [comment]
@ilya-lavrenov 
This is not the case. I don’t need a model. I’m just wondering why I don’t have the path "/opt/intel/openvino/deployment_tools". Someone told me that it was downloaded from the official website, but the one here is different from the official website? Can the ones here still work?

**Comment by ilya-lavrenov** [comment]
https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/downloader/downloader.py

**Comment by nmanhong** [comment]
@ilya-lavrenov 
Maybe I haven’t said clear what I mean. First of all, I don’t need to download the model. I just take this as an example. For example, why is there no folder "/opt/intel/openvino/deployment_tools/ngraph/include/" .
I need to write deployment code now, but I cannot locate the libraries I need

**Comment by ilya-lavrenov** [comment]
> why is there no folder "/opt/intel/openvino/deployment_tools/ngraph/include/" .

Repo structure and release package structure are different things. 

If you need the same structure and in release package:
1. build using cmake first
2. run `make install` and it will create the same structure as in OpenVINO package. But, it will contain only artifacts which are part of this repo (e.g. model_download is a part of different repo and it will not be installed during `make install`, as well as opencv and some other components)
