### ISSUE TITLE
#dldt Inference Engine samples giving error Error on or near line 198; exiting with status 1

### ISSUE THREAD

**Issue by roburst2** [openvinotoolkit/openvino#38]
**./demo_squeezenet_download_convert_run.sh**

Build Inference Engine samples

-- /etc/*-release distrib: Ubuntu 16.04
CMake Error at /opt/intel/computer_vision_sdk_2018.4.420/deployment_tools/inference_engine/src/extension/cmake/CPUID.cmake:324 (file):
  file STRINGS file
  "/opt/intel/computer_vision_sdk_2018.4.420/deployment_tools/inference_engine/samples/cpuid.txt"
  cannot be read.
Call Stack (most recent call first):
  /opt/intel/computer_vision_sdk_2018.4.420/deployment_tools/inference_engine/src/extension/cmake/feature_defs.cmake:30 (include)
  /opt/intel/computer_vision_sdk_2018.4.420/deployment_tools/inference_engine/src/extension/CMakeLists.txt:21 (include)

-- Host CPU features:
-- Validation app build is switched off
-- Configuring incomplete, errors occurred!
See also "/opt/intel/computer_vision_sdk_2018.4.420/deployment_tools/inference_engine/samples/CMakeFiles/CMakeOutput.log".
See also "/opt/intel/computer_vision_sdk_2018.4.420/deployment_tools/inference_engine/samples/CMakeFiles/CMakeError.log".
Error on or near line 198; exiting with status 1

**Comment by wanghanyang123** [comment]
Hello, have you solved your issues?

**Comment by roburst2** [comment]
Yes

**Comment by wanghanyang123** [comment]
Thank you, and could you tell me how to do?

**Comment by wanghanyang123** [comment]
I have solved it, thank you.

**Comment by roburst2** [comment]
@wanghanyang123 I used python instead of c++ inference script.
could you tell how you have solved the issue

**Comment by AnastasiaKazantaeva** [comment]
Close this issue as no active question exists
