### ISSUE TITLE
Please add native support for Pytorch models

### ISSUE THREAD

**Issue by Coderx7** [openvinotoolkit/openvino#380]
I'd like to ask for the native support for Pytorch models. rather than being dependent on ONNX. 
Are  there any complications in this regard that need to be addressed by Pytorch team before OpenVINO can start working on it?
Any clafirication on this regard is greatly appreciated.

**Comment by dkurt** [comment]
There are two ways to export PyTorch model: https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-for-inference

> The reason for this is because pickle does not save the model class itself. Rather, it saves a path to the file containing the class, which is used during load time. 

However both of them are not standalone but require Python code with a graph nearby

**Comment by Coderx7** [comment]
You got me wrong! I know how to export a model in Pytorch. the issue is, not all pytorch operators are supported by ONNX at the moemnt and also, having a first class citizen like TF, MXNet, is a lot better than a second class one! based on the documentations, only the torch models, based on torchvision 0.2 are supported ( we are now at 0.6 at the nightlies and 0.5 stable) .

**Comment by dkurt** [comment]
> not all pytorch operators are supported by ONNX at the moemnt

@Coderx7, That means this is ONNX issue

Can you give an example of unsupported nodes? Probably it's already fixed in new release.

**Comment by Coderx7** [comment]
Yes , but it becomes Pytorch's, since you support only ONNX(unlike, supporting MXNet, TF along side ONNX), and not Pytorch , and a Pytorch model which is not supported by ONNX yet, will be in big trouble!
Couple of operators that come to my mind at the moment are, `leakey_relu, cat, interpolate`

**Comment by jgespino** [comment]
Please see openvino_contrib repository, there is a [PyTorch extension for model optimizer](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/mo_pytorch).
