### ISSUE TITLE
[Bug] Convert squeezenet caffe model to the IR giving errors

### ISSUE THREAD

**Issue by anujm1** [openvinotoolkit/openvino#3823]
##### System information (version)

- OpenVINO=> 2021.2
- Operating System / Platform => Linux - Fedora 33
- Compiler => gcc 10.2.1
- Problem classification => Model conversion

##### Detailed description
Trying to convert squeezenet1.1 model to IR using model optimizer fails with error:
```
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/anujm/models/public/squeezenet1.1/squeezenet1.1.caffemodel
	- Path for generated IR: 	/home/anujm/models/public/squeezenet1.1/ir
	- IR output name: 	squeezenet1.1
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP16
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
Caffe specific parameters:
	- Path to Python Caffe* parser generated from caffe.proto: 	./mo/front/caffe/proto
	- Enable resnet optimization: 	True
	- Path to the Input prototxt: 	/home/anujm/models/public/squeezenet1.1/squeezenet1.1.prototxt
	- Path to CustomLayersMapping.xml: 	Default
	- Path to a mean file: 	Not specified
	- Offsets for a mean file: 	Not specified
Model Optimizer version: 	unknown version
Please expect that Model Optimizer conversion might be slow. You are currently using Python protobuf library implementation. 
However you can use the C++ protobuf implementation that is supplied with the OpenVINO toolkitor build protobuf library from sources. 
Navigate to "install_prerequisites" folder and run: python -m easy_install protobuf-3.5.1-py($your_python_version)-win-amd64.egg 
set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp


 For more information please refer to Model Optimizer FAQ, question #80. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=80#question-80)
[ ERROR ]  Error while emitting attributes for layer relu_conv1 (id = 5). It usually means that there is unsupported pattern around this node or unsupported combination of attributes.
```

##### Steps to reproduce

Following getting started guide for Linux steps here:
https://github.com/openvinotoolkit/openvino/blob/master/docs/get_started/get_started_linux.md

1. python3 ./downloader.py --name squeezenet1.1 --output_dir ~/models
2. python3 ./mo.py --input_model ~/models/public/squeezenet1.1/squeezenet1.1.caffemodel --data_type FP16 --output_dir ~/models/public/squeezenet1.1/ir

**Comment by jgespino** [comment]
Hi @anujm1 

Thanks for reaching out, OpenVINO has not been validated on Fedora. I confirm your commands are correct and successfully converted the model on Ubuntu 18.04. Are you using the Intel Distribution of OpenVINO toolkit or did you built OpenVINO from source? If built from source, did you use the master branch?

Regards,
Jesus

**Comment by anujm1** [comment]
I am cloning the github repository and not using the installer. Just cloned and ran the commands, nothing else. I tried the master branch as well and same problem. Yocto also fails with the same error.

I realized that one common thing between Yocto & Fedora that is different from Ubuntu is the python version. So I tried using python3.6 on Fedora and then it works. It looks like you need to fix things to work with python 3.9. Can that be done please?

**Comment by jgespino** [comment]
Hi @anujm1

I'm glad you were able to resolve your issue by downgrading Python. There is a feature request to validate Python 3.9, I will add your input.

Regards,
Jesus

Ref. 45351

**Comment by jgespino** [comment]
Python3.9 is now supported on OpenVINO 2022.1, please see the [release notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes.html) for more information.
