### ISSUE TITLE
[Bug]Failed when run object_detection_sample_ssd.py

### ISSUE THREAD

**Issue by Chenzixi1** [openvinotoolkit/openvino#3827]
**environment:** Windows10
                            OpenVino 2021.2

**when run：**
python object_detection_sample_ssd.py

it work

**when run：**
python object_detection_sample_ssd.py -m F:\Programs\openvino\mymodel\face-detection-0200\face-detection-0200.xml -i C:\Users\admin\Desktop\people.jpg -d CPU
**error:**
F:\Anaconda\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
[ INFO ] Loading Inference Engine
[ INFO ] Loading network:
        F:\Programs\openvino\mymodel\face-detection-0200\face-detection-0200.xml
[ INFO ] Device info:
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 2021.2.0-1877-176bdf51370-releases/2021/2
inputs number: 1
input shape: [1, 3, 256, 256]
input key: image
[ INFO ] File was added:
[ INFO ]         C:\Users\admin\Desktop\people.jpg
[ INFO ] Preparing input blobs
[ INFO ] Batch size is 1
[ INFO ] Preparing output blobs
Traceback (most recent call last):
  File "object_detection_sample_ssd.py", line 207, in <module>
    sys.exit(main() or 0)
  File "object_detection_sample_ssd.py", line 147, in main
    output_dims = output_info.shape
ValueError: **get_shape was called on a descriptor::Tensor with dynamic shape**

Another one fave the problem before？

**Comment by jgespino** [comment]
Hi @Chenzixi1 

Thank you for reporting, I am able to reproduce the issue and have reached out to the development team. 
I will let you know once I hear back.

Regards,
Jesus

Ref. 45165

**Comment by jgespino** [comment]
Hi @Chenzixi1 

This has been fixed by Pull Request https://github.com/openvinotoolkit/openvino/pull/3976.

Regards,
Jesus
