### ISSUE TITLE
Custom IR Model throwing error for MYRIAD

### ISSUE THREAD

**Issue by gferraro** [openvinotoolkit/openvino#383]
The model loads fine when using CPU for for MYRIAD i get the following error:
How do i get more info about what this even means? Any help is appreciated thanks

  INFO Creating Inference Engine
   INFO Loading network files:
	inference_graph.xml
	inference_graph.bin
   INFO Preparing input blobs
   INFO Batch size is [1, 48, 1, 5, 48]
   INFO Loading model to the plugin
Traceback (most recent call last):
  File "neural.py", line 55, in <module>
    main()
  File "neural.py", line 38, in main
    exec_net = ie.load_network(network=net, device_name=device)
  File "ie_api.pyx", line 85, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 92, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: AssertionFailed: _allocatedIntermData.count(topParent) > 0

**Comment by leavim** [comment]
@gferraro 
Please provide more details about your model, if possible also share your original model and your inference script (basic .py to replicate the issue). Please include the MO command used to convert your model to IR format. 

Thanks,
Luis

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
