### ISSUE TITLE
different results on CPU and MYRIAD

### ISSUE THREAD

**Issue by OrysB** [openvinotoolkit/openvino#3840]
Hey there,

System information (version)

    OpenVINO => 2021.2
    Operating System / Platform => Ubuntu 20.04
    Problem classification: Performance mismatch
    Framework: IR
    Model name: [https://github.com/AASHISHAG/deepspeech-german](https://github.com/AASHISHAG/deepspeech-german) 

Detailed description

converted using:
python ./mo_tf.py --input_model=./models/model0.9.0/output_graph.pb --input="input_node,previous_state_h,previous_state_c" --input_shape=[1,16,19,26],[1,2048],[1,2048] --output=logits,cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/GatherNd,cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/GatherNd_1 --freeze_placeholder_with_value="input_lengths->[16]" --disable_nhwc_to_nchw

using the speech_recognitin_demo from openvino_model_zoo on a test file the outputs are:
CPU:
./speech_recognition_demo.py -d CPU -i test.wav -m output_graph.xml -p models/model0.9.0/profile.yml -L models/model0.9.0/lm.binary 
./speech_recognition_demo.py:53: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  profile = yaml.load(f)
Loading, including network weights, IE initialization, LM, building LM vocabulary trie, loading audio: 5.15623848299947 s
Audio file length: 1.82 s
MFCC time: 0.018354936000832822 s
100%|███████████████████████████████████████| 6/6 [00:07<00:00,  1.25s/it]
RNN time: 7.5175357929983875 s
Beam search time: 0.4264053389997571 s
Overall time: 13.119200126999203 s

Transcription and confidence score:
0.5707385540008545	das ist ein test  [correct]

MYRIAD:
 ./speech_recognition_demo.py -d MYRIAD -i test.wav -m output_graph.xml -p models/model0.9.0/profile.yml -L models/model0.9.0/lm.binary 
./speech_recognition_demo.py:53: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  profile = yaml.load(f)
Loading, including network weights, IE initialization, LM, building LM vocabulary trie, loading audio: 9.656273693999537 s
Audio file length: 1.82 s
MFCC time: 0.0207113489996118 s
100%|███████████████████████████████████████| 6/6 [00:01<00:00,  5.07it/s]
RNN time: 1.1926335879979888 s
Beam search time: 0.4157999920025759 s
Overall time: 11.286259911001252 s

Transcription and confidence score:
8.351923942565918	das i intist

Greetings,
Orys

@jgespino Sorry ^^ created issue before I finished the comment

**Comment by jgespino** [comment]
@OrysB Please follow the issue template to provide additional information.

**Comment by jgespino** [comment]
Hi @OrysB 

No worries! :)

Could you share the .pb file? I used [version 0.9.0](https://drive.google.com/drive/folders/1L7ILB-TMmzL8IDYi_GW8YixAoYWjDMn1?usp=sharing) but am running into the same issue as your other post `'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)`. In the meantime also try adding `--scale 255` to your model optimizer command and see if that give you closer results with Myriad.

Regards,
Jesus

**Comment by OrysB** [comment]
Dear @jgespino ,

sure thing!
You can find all relevant files [here](https://drive.google.com/file/d/1tHcRieVVdsNluAovLYhJstiG83_LXV2l/view?usp=sharing).

Trying to convert with --scale 255 results in the following error:

python ./mo_tf.py --input_model=./models/model0.9.0/output_graph.pb --input="input_node,previous_state_h,previous_state_c" --input_shape=[1,16,19,26],[1,2048],[1,2048] --output=logits,cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/GatherNd,cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/GatherNd_1 --freeze_placeholder_with_value="input_lengths->[16]" --disable_nhwc_to_nchw --scale 255
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	[path to]/open_model_zoo/demos/python_demos/speech_recognition_demo/./models/model0.9.0/output_graph.pb
	- Path for generated IR: 	[path to]/open_model_zoo/demos/python_demos/speech_recognition_demo/.
	- IR output name: 	output_graph
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	input_node,previous_state_h,previous_state_c
	- Output layers: 	logits,cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/GatherNd,cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/GatherNd_1
	- Input shapes: 	[1,16,19,26],[1,2048],[1,2048]
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	255.0
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Use the config file: 	None
Model Optimizer version: 	custom_HEAD_4795391b73381660b69b4cd3986c7a0bf902e868
[ WARNING ]  Failed to parse a tensor with Unicode characters. Note that Inference Engine does not support string literals, so the string constant should be eliminated from the graph.
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.middle.ScaleInput.ScaleInput'>)":
[ ERROR ]  Traceback (most recent call last):
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 288, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/utils/replacement_pattern.py", line 27, in find_and_replace_pattern
    apply_pattern(graph, **self.pattern(), action=self.replace_pattern)  # pylint: disable=no-member
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 95, in apply_pattern
    action(graph, match)
  File "[openVINO install dir]/deployment_tools/model_optimizer/extensions/middle/ScaleInput.py", line 50, in replace_pattern
    AddMeanScaleValues.apply_scale(graph, match['placeholder'], {'scale': np.array([scale])})
  File "[openVINO install dir]/deployment_tools/model_optimizer/extensions/middle/AddMeanScaleValues.py", line 49, in apply_scale
    features_dim_idx = get_features_dim(graph.graph['layout'], len(input_node.shape))
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/front/common/layout.py", line 84, in get_features_dim
    assert 4 <= shape_len <= 5
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/main.py", line 297, in main
    ret_code = driver(argv)
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/main.py", line 264, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/main.py", line 233, in prepare_ir
    graph = unified_pipeline(argv)
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/pipeline/unified.py", line 29, in unified_pipeline
    class_registration.ClassType.BACK_REPLACER
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 338, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 328, in apply_replacements_list
    num_transforms=len(replacers_order))
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/utils/logger.py", line 124, in wrapper
    function(*args, **kwargs)
  File "[openVINO install dir]/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 316, in apply_transform
    )) from err
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.middle.ScaleInput.ScaleInput'>)":

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by jgespino** [comment]
@OrysB This looks like a new bug in this release, I created a bug for the development team to take a look. I will let you know once I hear back.

Regards,
Jesus

Ref. 46956

**Comment by OrysB** [comment]
Dear @jgespino ,
thanks for your last reply. The model optimizer converts the model successfully, but now there is no output anymore at all ...

I also used --log_level DEBUG just in case it helps. I don't really know what to look for tough ... 

[BugReport.txt](https://github.com/openvinotoolkit/openvino/files/5858781/BugReport.txt)

Greetings,
Orys

**Comment by jgespino** [comment]
Hi @OrysB 

Thanks for providing that additional information, let me check with my peers and get back to you.

Regards,
Jesus

**Comment by dmitryte** [comment]
Hi  @OrysB.  I'm getting 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)' when trying to convert the shared .pb model. Is it possible to also upload .bin file into your google drive folder. I can see only .xml file. I mean the original converted model that was giving you the correct output?

**Comment by OrysB** [comment]
Dear @dmitryte ,
thanks for taking a look at it.
I have uploaded both the output_graph.mapping and the output_graph.bin file.

**Comment by dmitryte** [comment]
Hi @OrysB ! I spent some time experimenting with the model you shared and it's working fine on MYRIAD. Because of the lower precision(we use FP16 to do inference on MYRIAD devices) you need to tweak some parameters in the profile.yaml file.

I managed to get the following output from the demo:
2.83510422706604        das ist ein tet
3.08158540725708        das ist ein test
3.1851367950439453      das ist einen tet
3.391294002532959       dass ist ein tet
3.4316177368164062      das ist einen test

And the content of my profile.yaml is this:
alphabet: alphabet.conf
alpha: 0
beta: 0
model_sampling_rate: 16000
frame_window_size_seconds: 0.032
frame_stride_seconds: 0.035
mel_num:  60
mel_fmin: 20.
mel_fmax: 8000.
num_mfcc_dct_coefs: 26
num_context_frames: 19


Hope, this will help you!

**Comment by OrysB** [comment]
Dear @dmitryte , thanks a lot! It is very accurat for the example I uploaded. Others are still quite scrambled.
I will make a small dataset for tuning those parameters.

**Comment by dmitryte** [comment]
Great! Then I'm closing this ticket. If you need any more help with this model, please create a new one.
