### ISSUE TITLE
CPU Usage High when Running Inference on GPU

### ISSUE THREAD

**Issue by vt911001** [openvinotoolkit/openvino#3845]
Hi,

I have run the following pipeline with inference executed on GPU:
```
gst-launch-1.0 -v \
filesrc location= $VIDEO ! qtdemux ! h264parse ! vaapih264dec ! gvadetect device="GPU" model=ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.xml ! fakesink sync=false \
filesrc location= $VIDEO ! qtdemux ! h264parse ! vaapih264dec ! gvadetect device="GPU" model=ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.xml ! fakesink sync=false \
filesrc location= $VIDEO ! qtdemux ! h264parse ! vaapih264dec ! gvadetect device="GPU" model=ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.xml ! fakesink sync=false \
filesrc location= $VIDEO ! qtdemux ! h264parse ! vaapih264dec ! gvadetect device="GPU" model=ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.xml ! fakesink sync=false \
filesrc location= $VIDEO ! qtdemux ! h264parse ! vaapih264dec ! gvadetect device="GPU" model=ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.xml ! fakesink sync=false \
filesrc location= $VIDEO ! qtdemux ! h264parse ! vaapih264dec ! gvadetect device="GPU" model=ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.xml ! fakesink sync=false \
filesrc location= $VIDEO ! qtdemux ! h264parse ! vaapih264dec ! gvadetect device="GPU" model=ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.xml ! fakesink sync=false \
filesrc location= $VIDEO ! qtdemux ! h264parse ! vaapih264dec ! gvadetect device="GPU" model=ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.xml ! fakesink sync=false \
```

However, I noticed that the CPU consumption is high(98-100%). 
From some searching, it looked similar to the issue in [https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/100-CPU-usage-when-using-OpenVINO-GPU-inference/td-p/1130077](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/100-CPU-usage-when-using-OpenVINO-GPU-inference/td-p/1130077)

In the link, there is suggestion of using config key as below:
`CLDNNConfigParams::KEY_CLDNN_PLUGIN_THROTTLE`

Thus, is there any way to apply this config key?
I have tested it with `ie-config` in `gvadetect` and it is not supported.

Please advise.

Thanks,
Vincent

**Comment by vt911001** [comment]
Hi Mark,

Thanks for your help.

Vincent

**Comment by vt911001** [comment]
Hi,

I have profiled the gstreamer pipeline with VTune and found that most of time CPU time was spent on waiting for DetectionOutput from `ssd_mobilenet`.

![waiting_for_detection_output](https://user-images.githubusercontent.com/68520732/105327890-6d69a300-5c0a-11eb-8a9a-8e1b8991ab57.PNG)

Is there anyway to mitigate this?


Thanks,
Vincent

**Comment by jgespino** [comment]
Hi @vt911001 

Do you see the behavior when running this model with the OpenVINO samples/demos? Which version of the OpenVINO toolkit are you using? What processor are you using? I would like to setup a similar environment to yours to reproduce the issue.

Regards,
Jesus

**Comment by vt911001** [comment]
Hi Jesus,

I was using DLStreamer to run the workload.
Though, let me check if the behaviour can be reproduced by any samples.

BTW, I am using OpenVINO 2021.2 though rebuilt with debug information.

Will get back to you once I have the minimal reproducible sample.

Thanks,
Vincent

**Comment by vt911001** [comment]
Hi Jesus,

I am able to reproduce the behaviour by executing the model with OpenVINO benchmark app by using this model:
[https://docs.openvinotoolkit.org/latest/omz_models_public_mobilenet_ssd_mobilenet_ssd.html](https://docs.openvinotoolkit.org/latest/omz_models_public_mobilenet_ssd_mobilenet_ssd.html)

`./benchmark_app -m /home/vincent/ssd_mobilenet_v1_coco_2018_01_28/frozen_inference_graph.xml -d GPU -api async -nireq 8 -nstreams 8`


Thanks,
Vincent

**Comment by jgespino** [comment]
Hi @vt911001 

Thanks for giving that a try and providing steps to reproduce. I took a closer look and this is a known issue caused by the absence of callback interrupt ability on Intel iGPU. If the CPU usage is an issue for the application and you can sacrifice some waiting time, you could try and configure the [GPU plugin](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_CL_DNN.html#supported_configuration_parameters) `KEY_CLDNN_PLUGIN_THROTTLE `to a lower value `1` or `2`. 

Hope this helps!

Regards,
Jesus

**Comment by vt911001** [comment]
Hi Jesus, 

Thanks a lot for your explanation.
When you were saying about sacrificing waiting time, I couldn't really get it.
Can you illustrate how setting the `KEY_CLDNN_PLUGIN_THROTTLE  `to lower value 1 will help to solve CPU usage issue?


Thanks,
Vincent

**Comment by brmarkus** [comment]
I found the documentation on "https://docs.openvinotoolkit.org/2019_R3/_docs_IE_DG_supported_plugins_CL_DNN.html", saying:


> KEY_CLDNN_PLUGIN_THROTTLE | <0-3> | 0 | OpenCL queue throttling (before usage, make sure your OpenCL driver supports appropriate extension)Lower value means lower driver thread priority and longer sleep time for it. 0 disables the setting.

**Comment by vt911001** [comment]
Hi Markus,

Thanks, I have seen that too.
Please help to correct me if I am wrong:
My understanding was that the lower driver thread priority as well as longer sleep time means that it is not constantly spinning and polling for kernel completion.

Thanks,
Vincent

**Comment by jgespino** [comment]
@brmarkus do you have any additional input?

**Comment by jgespino** [comment]
Hi @vt911001 Not sure if your issue is still present in the latest release. If you could please check and re-open the issue if you need further assistance.

**Comment by saratpoluri** [comment]
I have verified that using GPU_PLUGIN_THROTTLE setting in OpenVino 2022.1, the CPU utilization of the benchmark app drops to 2%. When not using that setting the CPU util is at 100%. As recommended in one of the comments above use the below config option when Loading network. In the case of benchmark_app you can pass it through a config.json file.
https://docs.openvinotoolkit.org/2019_R3/_docs_IE_DG_supported_plugins_CL_DNN.html
