### ISSUE TITLE
[Bug]Convert onnx model to the IR errors

### ISSUE THREAD

**Issue by bianxg** [openvinotoolkit/openvino#3846]
System information (version)
OpenVINO=> 2021.2
Operating System / Platform => Linux - Ubuntu 18.04.5 LTS
Problem classification => Model conversion

python /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py --input_model onnx_mobilenetv2_hd.onnx --log_level=DEBUG

Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/test/project/BackgroundMattingV2/onnx_mobilenetv2_hd.onnx
	- Path for generated IR: 	/home/test/project/BackgroundMattingV2/.
	- IR output name: 	onnx_mobilenetv2_hd
	- Log level: 	DEBUG
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
ONNX specific parameters:
Model Optimizer version: 	2021.2.0-1877-176bdf51370-releases/2021/2

[ 2021-01-14 14:49:50,201 ] [ DEBUG ] [ infer:131 ]  Op: Conv
[ 2021-01-14 14:49:50,201 ] [ DEBUG ] [ infer:132 ]  Inputs:
[ 2021-01-14 14:49:50,202 ] [ DEBUG ] [ infer:32 ]  input[0]: shape = [0 6 0 0], value = <UNKNOWN>
[ 2021-01-14 14:49:50,204 ] [ DEBUG ] [ infer:32 ]  input[1]: shape = [32  6  3  3], value = [[[[ 2.85400972e-02  1.47299776e-02  2.23990325e-02]
   [-1.24595696e-02  3.78485918e-02 -5.96722...
[ 2021-01-14 14:49:50,204 ] [ DEBUG ] [ infer:32 ]  input[2]: shape = [32], value = [ 0.01663086  0.43697682  0.26748052  0.46283084  1.1200132   0.66423345
  0.53411824  0.5674907 ...
[ ERROR ]  Cannot infer shapes or values for node "Conv_59".
[ ERROR ]  Data after padding has dimension less than window size. Possible reason of error is incorrectly specified model input shape(s).
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Convolution.infer at 0x7f5c93061170>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ 2021-01-14 14:49:50,206 ] [ DEBUG ] [ infer:197 ]  Node "Conv_59" attributes: {'pb': input: "442"
input: "1350"
input: "1351"
output: "1349"
name: "Conv_59"
op_type: "Conv"
attribute {
  name: "dilations"
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "group"
  i: 1
  type: INT
}
attribute {
  name: "kernel_shape"
  ints: 3
  ints: 3
  type: INTS
}
attribute {
  name: "pads"
  ints: 1
  ints: 1
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "strides"
  ints: 2
  ints: 2
  type: INTS
}
, 'kind': 'op', '_in_ports': {0: {'control_flow': False}, 1: {'control_flow': False}, 2: {'control_flow': False}}, '_out_ports': {0: {'control_flow': False}}, 'name': 'Conv_59', 'op': 'Conv', 'type': 'Convolution', 'version': 'opset1', 'infer': <function Convolution.infer at 0x7f5c93061170>, 'multiplication_transparent': True, 'multiplication_transparent_ports': [(0, 0), (1, 0)], 'in_ports_count': 3, 'out_ports_count': 1, 'auto_pad': None, 'bias_addable': True, 'bias_term': True, 'pad': array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1]]), 'pad_spatial_shape': array([[1, 1],
       [1, 1]]), 'dilation': array([1, 1, 1, 1]), 'output_spatial_shape': None, 'output_shape': None, 'stride': array([1, 1, 2, 2]), 'group': array(1), 'output': 32, 'kernel_spatial': array([3, 3]), 'input_feature_channel': 1, 'output_feature_channel': 0, 'kernel_spatial_idx': array([2, 3]), 'spatial_dims': array([2, 3]), 'channel_dims': array([1]), 'batch_dims': array([0]), 'layout': 'NCHW', 'dim_attrs': ['spatial_dims', 'channel_dims', 'batch_dims', 'axis'], 'shape_attrs': ['pad', 'stride', 'output_shape', 'window', 'shape'], 'IE': [('layer', [('id', <function Op.substitute_ie_attrs.<locals>.<lambda> at 0x7f5c9297b830>), 'name', 'type', 'version'], [('data', ['auto_pad', ('strides', <function Convolution.backend_attrs.<locals>.<lambda> at 0x7f5c9297b950>), ('dilations', <function Convolution.backend_attrs.<locals>.<lambda> at 0x7f5c9297b9e0>), ('pads_begin', <function Convolution.backend_attrs.<locals>.<lambda> at 0x7f5c9297ba70>), ('pads_end', <function Convolution.backend_attrs.<locals>.<lambda> at 0x7f5c9297bb00>), ('output_padding', <function Convolution.backend_attrs.<locals>.<lambda> at 0x7f5c9297bb90>), 'pad_value', 'mode'], []), '@ports', '@consts'])], 'is_output_reachable': True, 'is_undead': False, 'is_const_producer': False, 'is_partial_inferred': False, 'kernel_shape': array([32,  6,  3,  3]), 'output_padding': array([0, 0, 0, 0])}
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "Conv_59" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)
[ 2021-01-14 14:49:50,206 ] [ DEBUG ] [ main:310 ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 135, in partial_infer
    node.infer(node)
  File "/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/mo/ops/convolution.py", line 205, in infer
    kernel_extent)
  File "/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/mo/ops/convolution.py", line 77, in calc_convolution
    raise Error("Data after padding has dimension less than window size. " +
mo.utils.error.Error: Data after padding has dimension less than window size. Possible reason of error is incorrectly specified model input shape(s).

The above exception was the direct cause of the following exception:

**Comment by bianxg** [comment]
I have attached the onnx model for reference.
https://drive.google.com/drive/folders/1onSGHYmNRROI2R39lqxf2CvtTaIVRXnB
https://github.com/PeterL1n/BackgroundMattingV2

**Comment by ilya-lavrenov** [comment]
@bianxg does the same model work well in ONNX model is passed directly to IE application? We can consume ONNX files in IE directly.

**Comment by avitial** [comment]
@bianxg in addition, glancing at the .onnx models provided this network seems to have two inputs (_src_ and _bgr_) and six outputs (_pha_, _fgr_, _pha_sm_, _fgr_sm_, _err_sm_ and _ref_sm_). As it seems, these inputs don't have a pre-defined input shape, looking at model in Netron these have `float32[batch, 3, height, width]`. If you try to specify these inputs with their respective input shapes and outputs in MO (experimented with input shape [1,3,1920,1080]), MO complains about node _If_433_ `[ ERROR ]  There is no registered "infer" function for node "If_433" with op = "If". Please implement this function in the extensions. For more information please refer to Model Optimizer FAQ, question` [#37](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=37#question-37) which is self explanatory. Check out [Model Optimizer Extensibility](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_customize_model_optimizer_Customize_Model_Optimizer.html).

The following seems to convert fine, but its cutting and leaving out _pha_ and _fgr_ outputs:
`python3 /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo_onnx.py --input_model onnx_mobilenetv2_hd.onnx --input_shape [1,3,1920,1080],[1,3,1920,1080] --input src,bgr --output pha_sm,fgr_sm,err_sm,ref_sm`.

Regards,
Luis

**Comment by bianxg** [comment]
> @bianxg does the same model work well in ONNX model is passed directly to IE application? We can consume ONNX files in IE directly.
> 
> From MO FAQ:
> 
> ```
> 38. What does the message "Stopped shape/value propagation at node" mean?
> Model Optimizer cannot infer shapes or values for the specified node. It can happen because of a bug in the custom shape infer function, because the node inputs have incorrect values/shapes, or because the input shapes are incorrect.
> ```
When ONNX model is passed directly to IE application, there is error:

Traceback (most recent call last):
  File "matte_test.py", line 207, in <module>
    sys.exit(main() or 0)
  File "matte_test.py", line 60, in main
    net = ie.read_network(model=model)
  File "ie_api.pyx", line 261, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 285, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Check 'unknown_operators.empty()' failed at ngraph/frontend/onnx_import/src/core/graph.cpp:165:
nGraph does not support the following ONNX operations: If
