### ISSUE TITLE
maskrcnn demo

### ISSUE THREAD

**Issue by abcxs** [openvinotoolkit/openvino#385]
I use the latest version-2020.1. 
Follow the procedures
1. Convert ONNX* Mask R-CNN Model to the Intermediate Representation(https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_onnx_specific_Convert_Mask_RCNN.html)
2. Run the Mask demo(https://docs.openvinotoolkit.org/latest/_demos_python_demos_instance_segmentation_demo_README.html)

In the first part, I don't understand the step-3. But I get the *.xml and *.bin after the step-2.
I use the result from the first part to run the mask demo. The output of part-2 is that:
![image](https://user-images.githubusercontent.com/13503336/74518475-e0748f00-4f4e-11ea-9574-a564c80d5a72.png)
Also, I change the names of inputs, 
but the num of outputs is three, and the names is strange.

**Comment by abcxs** [comment]
Have anybody give some suggestions？

**Comment by jgespino** [comment]
Hi @abcxs 

Which model are you using? The [demos table](https://github.com/opencv/open_model_zoo/tree/master/demos#demos-that-support-pre-trained-models) shows the following models work with this demo.

instance-segmentation-security-0010
instance-segmentation-security-0050
instance-segmentation-security-0083

Regards,
Jesus

**Comment by abcxs** [comment]
Hi, @jgespino 
In the first part, the pre-trained model file is downloaded  and converte to IR according to step-2. I want to use the generated  IR to run maskrcnn demo. But it fails.

**Comment by abcxs** [comment]
Two parts:
1. Convert ONNX* Mask R-CNN Model to the Intermediate Representation(https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_onnx_specific_Convert_Mask_RCNN.html)
2. Run the Mask demo(https://docs.openvinotoolkit.org/latest/_demos_python_demos_instance_segmentation_demo_README.html)
I want to use the IR from the first part to serve the second part

**Comment by jgespino** [comment]
Hi @abcxs 

The demo expects the model to have two inputs, **im_data** and **im_info** and at least four outputs including **boxes**, **scores**, **classes** and **raw_masks**. The model you are trying to use does meet the expectations. Could you try using one of the models mentioned above?

Regards,
Jesus

**Comment by abcxs** [comment]
Hi @jgespino
Thanks for your replay.
In the first part, I download the  pre-trained model file and convert it to IR according to the orders. 
![image](https://user-images.githubusercontent.com/13503336/74966184-90fff880-5451-11ea-9812-c2ce74ce9c0f.png)
I didn't do step-3 as shown in the picture below. And if i use the IR from step 2 in this [case](https://docs.openvinotoolkit.org/latest/_demos_python_demos_instance_segmentation_demo_README.html),  it will fails.
![image](https://user-images.githubusercontent.com/13503336/74966293-c573b480-5451-11ea-9416-88abcf36b1d6.png)
Is this the result of step-3? What do I need to change?

**Comment by jgespino** [comment]
Hi @abcxs 

Step 3 describes the expected output from inference and how to interpreter. I am checking with the development team about running the ONNX Mask R-CNN model with the Instance Segmentation demo. I will let you know once I hear back.

Regards,
Jesus

**Comment by lazarevevgeny** [comment]
@abcxs the Mask-RCNN demo mentioned above is not suitable for running model converted from ONNX Mask-RCNN. You need to implement your own post-processing for the IR output.

**Comment by abcxs** [comment]
> @abcxs the Mask-RCNN demo mentioned above is not suitable for running model converted from ONNX Mask-RCNN. You need to implement your own post-processing for the IR output.

Thanks.
I use the [repo](https://github.com/opencv/openvino_training_extensions) to convert Mask-RCNN weights and export to onnx and IR.

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
