### ISSUE TITLE
[Bug] bash install_prerequisites_tf.sh and install_prerequisites_mxnet.sh error

### ISSUE THREAD

**Issue by alixiu** [openvinotoolkit/openvino#3850]
##### System information (version)

- OpenVINO => openvino_2019.3.376
- Operating System / Platform => linux ubuntu 64 Bit
- Compiler =>Linux version 5.4.0-60-generic (buildd@lgw01-amd64-007) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) 
- Problem classification: Model Conversion

##### Detailed description

run the command: 
bash **$OPENVINO_HOME/model_optimizer/install_prerequisites/install_prerequisites_tf.sh** or
bash **$OPENVINO_HOME/model_optimizer/install_prerequisites/install_prerequisites_mxnet.sh**
generating the following error
` ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_5kqugpv/networkx_ed2f65781a41483bb7f95aba94913b66/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_5kqugpv/networkx_ed2f65781a41483bb7f95aba94913b66/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0rsbyffi
         cwd: /tmp/pip-install-_5kqugpv/networkx_ed2f65781a41483bb7f95aba94913b66/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by mryzhov** [comment]
@alixiu thanks for reporting the issue. 
As a quick workaround, could you please install setuptools module manually "pip install setuptools" then try to run those scripts one more time?

**Comment by alixiu** [comment]
@mryzhov 
I run the command "pip install setuptools",  get the following result:

`Requirement already satisfied: setuptools in /home/xiu/anaconda3/lib/python3.7/site-packages (51.1.2)`

Next, when "bash install_prerequisites_tf.sh" or "bash install_prerequisites_mxnet.sh",  the same error is generated

` ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9e_r9oab/networkx_7b2b792e7d734293a4c3eee334d4fbe1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9e_r9oab/networkx_7b2b792e7d734293a4c3eee334d4fbe1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z5140xob
         cwd: /tmp/pip-install-9e_r9oab/networkx_7b2b792e7d734293a4c3eee334d4fbe1/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by slyubimt** [comment]
@alixiu,
 Consider to install in virtualenv:
` ./install_prerequisites.sh tf venv` 
or
` ./install_prerequisites.sh mxnet venv` 

See more [here](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Config_Model_Optimizer.html)

**Comment by alixiu** [comment]
@slyubimt ，
It dosen't work, the same error as above is generated.

**Comment by alixiu** [comment]
Is this problem related to the installation of tensorflow?

**Comment by mryzhov** [comment]
@alixiu do you use a virtual environment? if yes, have you activated it before installing setuptools?

**Comment by alixiu** [comment]
> @alixiu do you use a virtual environment? if yes, have you activated it before installing setuptools?
`cd /opt/intel/openvino/deployment_tools/model_optimizer/install_prerequisites`
`./install_prerequisites.sh tf venv`
`source /opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/install_prerequisites/../venv/bin/activate`
`bash install_prerequisites_tf.sh`
`  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-beqivgqk/termcolor_59e7f15031b2432da19540bc2afbadd4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-beqivgqk/termcolor_59e7f15031b2432da19540bc2afbadd4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b_wgs4bj
         cwd: /tmp/pip-install-beqivgqk/termcolor_59e7f15031b2432da19540bc2afbadd4/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is still needed.
