### ISSUE TITLE
C++ inference result is not equal to python inference result

### ISSUE THREAD

**Issue by oms291** [openvinotoolkit/openvino#3870]
Hi,
I'm still struggling to get the same result in c++ as python in windows 10 with OpenVINO 2020.3 or 2021.2 version.
I checked the same result using openvino python api in python with onnx file and IR files.
I also tried using std::unique_ptr<float[]> as static float array but it didn't work.
i'm using object_detection_sample_ssd. 

Is there any suggestion?

Thanks.

_Originally posted by @oms291 in https://github.com/openvinotoolkit/openvino/issues/311#issuecomment-760473269_

**Comment by avitial** [comment]
@oms291 provide more information about model used by app, is it a pre-trained or custom model? MO command used to convert to IR. Are you using OpenVINO pre-built package or built from source? Please include all details that could help reproduce the observed issue.

~Luis

**Comment by oms291** [comment]
Hi, Lusi.
Thanks for the reply.

I'm using custom mobilenet V1 - only change the classifier but is not a classification model. the custom model is for regression some parameters. 
I used the MO command as below to convert onnx to IR.
python mo_onnx.py --input_model mnet_v1_62.onnx --disable_resnet_optimization --data_type=FP32 --scale_values=[128,128,128] --mean_values=[127.5,127.5,127.5] --finegrain_fusing FINEGRAIN_FUSING

I utilize object_detection_sample_ssd in c++ sample code.

In python, I tried checking onnx model and IR(.xml, .bin). there are not big different results.

Using OpenVINO python API using IR(.xml, .bin)
`[-7.39539042e-02  6.73244372e-02 -9.99904647e-02  2.12700784e-01
 -1.64467961e-01 -8.03914249e-01 -2.68287182e-01 -1.07935846e-01
  2.60992832e-02  7.98627496e-01  1.07895672e-01  2.66254973e-03
 -2.50615850e-02 -7.66936541e-01  5.48313320e-01  7.03350186e-01
  3.01718473e-01  2.20438510e-01 -8.80155116e-02 -2.50414610e-01
  1.17199719e-02  3.11095417e-02  1.99167863e-01 -1.80464804e-01
  4.99712527e-01 -7.14996010e-02 -8.36997777e-02  8.57692212e-02
  1.12674966e-01  2.42589191e-01  3.65396775e-03 -5.73760271e-03
  2.97157615e-01  4.41939086e-02  1.01471141e-01 -3.20782185e-01
  4.90105152e-02  1.19579425e-02 -7.68179595e-02 -3.59913930e-02
  8.17659497e-02  1.76605895e-01  7.36708716e-02  1.74762458e-02
 -8.80673677e-02  2.01793000e-01 -1.07377402e-01  7.72997737e-07
  2.23144516e-02  1.71930999e-01  8.24650675e-02 -2.80437917e-01
  1.41489819e-01  2.14800477e-01 -1.09400675e-01  2.10142985e-01
 -1.34588763e-01 -2.11068451e-01 -3.38465035e-01  4.17760089e-02
 -9.40555707e-02 -2.01399744e-01]
`
PyTorch model
`tensor([[-7.3954e-02,  6.7324e-02, -9.9991e-02,  2.1270e-01, -1.6447e-01,
         -8.0391e-01, -2.6829e-01, -1.0794e-01,  2.6100e-02,  7.9863e-01,
          1.0790e-01,  2.6626e-03, -2.5058e-02, -7.6694e-01,  5.4831e-01,
          7.0335e-01,  3.0172e-01,  2.2044e-01, -8.8015e-02, -2.5041e-01,
          1.1720e-02,  3.1110e-02,  1.9917e-01, -1.8046e-01,  4.9971e-01,
         -7.1500e-02, -8.3699e-02,  8.5769e-02,  1.1268e-01,  2.4259e-01,
          3.6544e-03, -5.7374e-03,  2.9716e-01,  4.4194e-02,  1.0147e-01,
         -3.2078e-01,  4.9011e-02,  1.1957e-02, -7.6818e-02, -3.5991e-02,
          8.1767e-02,  1.7661e-01,  7.3671e-02,  1.7476e-02, -8.8067e-02,
          2.0179e-01, -1.0738e-01,  9.0152e-07,  2.2314e-02,  1.7193e-01,
          8.2465e-02, -2.8044e-01,  1.4149e-01,  2.1480e-01, -1.0940e-01,
          2.1014e-01, -1.3459e-01, -2.1107e-01, -3.3846e-01,  4.1776e-02,
         -9.4056e-02, -2.0140e-01]])`

C++ using OpenVINO C++ API
`[0.442601, -1.27036, 0.416119, -0.912615, 1.29582, -0.406627, -0.489945, -0.124099, 0.209787, 1.10217, 0.661079, 0.00535979, -0.971226, 0.0340915, -1.64148, 1.45665, -0.159814, 0.510636, -0.473237, 0.0347703, 1.64754, 0.882308, 0.731665, -0.811282, -0.403079, -0.818285, -0.855662, 0.821534, -1.12281, 0.344875, -0.537043, 0.273539, 0.374834, -0.158807, -0.129256, -0.203815, -0.725668, 0.702017, 0.0590446, -0.218661, -0.232449, -0.378843, 0.181206, -0.232522, 0.177832, -0.582069, 0.243993, 0.367222, 0.609927, 0.133886, -0.182574, -0.134398, 0.511082, -0.976334, 1.36811, 0.523949, 0.0125486, 0.716905, 0.56385, 0.353774, 0.211539, 0.822448]`

Thanks.

**Comment by ilya-lavrenov** [comment]
Looks like we have the issue with the C++ sample itself. CC @mryzhov

**Comment by avitial** [comment]
@oms291 thanks for the additional info. I've tested the _mobilenet_v1_0.5_160_ (classification type) model available in OMZ with _classification_sample_async_ in C++/Python and it works fine, same results on both samples. Same goes for the _object_detection_sample_ssd_ with _ssd_mobilenet_v1_coco_ model. It might be a coding issue in the C++ sample, I assume you are using the sample as a baseline but modified to your needs, is this correct? Anything else you can provide to replicate issue is welcome.

~Luis
