### ISSUE TITLE
Convert an OpenVINO model to tensorflow?

### ISSUE THREAD

**Issue by benhoff** [openvinotoolkit/openvino#388]
Is it possible to convert an OpenVINO model to tensorflow?

**Comment by jgespino** [comment]
Hi @benhoff 

It is not possible to convert the Intermediate Representation (IR) to TensorFlow. You can use the Model Optimizer to convert the model (TensorFlow, Caffe, ONNX, etc) to IR but no the other way around.

Regards,
Jesus

**Comment by benhoff** [comment]
So this is not a currently supported use case

**Comment by jgespino** [comment]
@benhoff That's correct, is there a particular reason why you need to go from IR to TensorFlow?

**Comment by benhoff** [comment]
Legacy and edge computing.

**Comment by dkurt** [comment]
@benhoff, Which edge hardware is considered? OpenVINO is the fastest DL toolkit for Intel hardware. It also supports ARM based host with NCS accelerators.

**Comment by benhoff** [comment]
I didn't realize that OpenVINO supported ARM at all. That's good to know.

I'm specifically looking at using https://github.com/cortexlabs/cortex.

I don't believe the OpenVINO framework is currently supported.

**Comment by dkurt** [comment]
@benhoff, OpenVINO supports ARM as a host for Movidius NCS. Please read more about configuration and installation steps here: https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_raspbian.html (OpenVINO just downloaded by `wget` as an archive for Raspbian).

**Comment by lazarevevgeny** [comment]
Closing the ticket since it is not really a bug.

**Comment by PINTO0309** [comment]
@benhoff 
I have created my own converter. It's not perfect, but it can convert OpenVINO IR to TensorFlow saved_model, pb, tflite, EdgeTPU, CoreML, TF-TRT(TensorRT), and TensorFlow.js.
**https://github.com/PINTO0309/openvino2tensorflow**
