### ISSUE TITLE
Support for compressed/prunded models

### ISSUE THREAD

**Issue by alrzmshy** [openvinotoolkit/openvino#3882]
Hello,

I can successfully run models trained with PyTorch (converted to ONNX) on NCS2. I have been trying to improve the FPS of models by pruning methods which is successfully done on the PyTorch model but the problem is that when I try to convert with `torch.onnx.export`,   `opset_version=10` it fails to convert to ONNX and with `opset_version=11`, conversion to ONNX is successful but while trying the benchmarkapp, I get :
`[ ERROR ] Failed to compile layer "829": unsupported layer type "ScatterNDUpdate"`. 

Is there any future plans for supporting such layers? Are there any tricks to improve the FPS of the models on NCS2?

Thank you.

**Comment by jgespino** [comment]
Hi @alrzmshy 

Which version of OpenVINO toolkit are you using? Did you build from source (which commit/branch)? There was a pull request for enabling ScatterND that has been merged. See https://github.com/openvinotoolkit/openvino/pull/1987.

I believe this operation is only implemented for CPU, are you able to run on CPU?

Regards,
Jesus

**Comment by alrzmshy** [comment]
Hi @jgespino

I'm using the official 2021.2. In any case, if it only runs on CPU it won't be very useful for us.

**Comment by jgespino** [comment]
@alrzmshy Let me confirm with my peers if this is the case and get back to you.

**Comment by sevhabert** [comment]
@alrzmshy I confirm that we only support this layer on CPU for now.

**Comment by satpalsr** [comment]
Hey @jgespino, I am facing a similar issue while trying to convert XML to blob & I am on CPU.
`Failed to compile layer "ScatterND_735": unsupported layer type "ScatterNDUpdate"`

I am using `2.1.2021.3.0-2787-60059f2c755-releases/2021/3` version

Used commands:
```
!source /opt/intel/openvino_2021/bin/setupvars.sh &&\
python3 /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py --input_model latest.onnx --output_dir . --data_type FP32 --input_shape [1,3,512,512] &&\
/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/myriad_compile -ip U8 -VPU_NUMBER_OF_SHAVES 6 -VPU_NUMBER_OF_CMX_SLICES 6 -m latest.xml -o latest.blob
```

**Comment by ashishpapanai** [comment]
Hi,
I am facing the same issue when I am trying to run inferences on MYRIAD using IR with ScatterNDupdate layers. Is there any workaround for replacing the layer?

**Comment by IkrameBeggar** [comment]
> I had a simmilar issue and solved it as descibed below. I followed the instructions in the OpenVINO docs and converted my PyTorch model to onnx. This resulted in the model having a `ScatterND` layer when I viewed the `.onnx` file in [netron](https://netron.app). But the model mainly consisted of normal 2d convolutions in the first place. Nothing fancy. After some expriments I found out that the ScatterND had been the result of the following formatiation during the output of the last layer:
> 
> ```python
> x[..., 0:2] = (x[..., 0:2].sigmoid() + foo) * bar
> x[..., 2:4] = torch.exp(x[..., 2:4])
> x[..., 4:] = x[..., 4:].sigmoid()
> ```
> 
> When I changed it to
> 
> ```python
> x = torch.cat([
>     (x[..., 0:2].sigmoid() + foo) * bar,
>     torch.exp(x[..., 2:4]),
>     x[..., 4:].sigmoid(),
> ], axis=4)
> ```
> 
> the error was gone and it resulted in a much cleaner graph without `ScatterND` operations. So maybe try to avoid modifieing slices using this indexing pattern. It now works without further issues on my NCS2.
> 
> I also would recommend `onnx-simplifier` for a cleaner graph when debuing these issues.

Hello, @Flova 

I am facing the same issue, and I am a bit confused where I should apply this adjustment on my model. In addition, after modifying the code as you suggested, do I need to retrain the model?

I would really appreciate your help
