### ISSUE TITLE
[Bug]Where is POT?

### ISSUE THREAD

**Issue by qianwangn** [openvinotoolkit/openvino#3891]
##### System information (version)

Icant find POT in your docs.
docs said I cant compile pot in deployment_tools. but where is depleyment_tools?

**Comment by AlexKoff88** [comment]
@qianwangn, POT tool is being developed in a private repository but it is available in the Intel distribution of the [OpenVINO toolkit](https://docs.openvinotoolkit.org/latest/installation_guides.html). Once you install it you can find POT under <openvino_install_dir>/deployment_tools/tools/post_training_optimization_toolkit/.

All the documentation is available [online](https://docs.openvinotoolkit.org/latest/pot_README.html).
