### ISSUE TITLE
[Bug]How to reshape a network containing a GPU Custom Layer?

### ISSUE THREAD

**Issue by cosmos1982** [openvinotoolkit/openvino#3892]
##### System information (version)
- OpenVINO => 2021.2
- Operating System / Platform => Ubuntu18.04
- Problem classification: reshape network when inference 

##### Detailed description
I have implemented a custom layer on both CPU and GPU and successfully run my code, but I found that no interfaces like "validate_and_infer_types()" in OpenCL kernel, so when I try to set batch size of the network, GPU plugin has the error:
 IShapeInferExtension wasn't registered for node relu1_1 with type CustomReLU
Meanwhile, CPU custom layer works fine.

##### Steps to reproduce(just a simple test code for reproduce not real code in use)
1. Prepare GPU extension:
   Download the gpu_ext from:
[gpu_ext.zip](https://github.com/openvinotoolkit/openvino/files/5828072/gpu_ext.zip)

2. Prepare the ir which contains a 'CustomReLU' for test
    Download ssd300 public caffe model from open model zoo, and convert it to ir FP32.
    Then replace the xml with the following:
[VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.zip](https://github.com/openvinotoolkit/openvino/files/5828122/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.zip)

3.  To load GPU extension, insert following code in  samples/hello_reshape_ssd/main.cpp: line 41
 if (device_name.find("GPU") != std::string::npos) {
            const std::string cl_path{argv[5]};
            ie.SetConfig({{PluginConfigParams::KEY_CONFIG_FILE, cl_path}}, "GPU");
            ie.SetConfig({ { PluginConfigParams::KEY_DUMP_KERNELS, PluginConfigParams::YES } }, "GPU");
            std::cout << "GPU extension register done. " << std::endl;
        }

4. Build openvino samples.

5. Run hello_reshape_ssd sample with any test image:
     ./hello_reshape_ssd ~/test/ir_custom/FP32/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml ~/test/Images/1.jpg GPU 2  ~/test/gpu_ext/custom_relu.xml

Then the error occurs:
IShapeInferExtension wasn't registered for node relu1_1 with type CustomReLU

I am not sure whether GPU extension has the inferfaces for "shape validations", if yes, can you get me some implementaion guide?

**Comment by vladimir-paramuzov** [comment]
@cosmos1982 This error doesn't not actually relate to the GPU plugin, and I'd expect that CPU plugin fails with the same error by default. Ngraph just don't know how to infer shapes for this custom operation.

So if you want to enable reshape for an operation, then you need to implement custom ngraph operation and add it as IE extension. Please refer to [this](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Extensibility_DG_Intro.html) docs page. 
Example for CustomReLU is abailable [here](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/samples/hello_reshape_ssd/reshape_ssd_extension.hpp). To use it on GPU you just need to change one condition [in the sample](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/samples/hello_reshape_ssd/main.cpp#L36) and then add corresponding GPU implementation to the plugin (item 3 from your list). 
You might also need to align opset name in the sample's code ("experimental") and in IR ("extension").

**Comment by cosmos1982** [comment]
@vladimir-paramuzov thanks for your quick reply, very useful,  I have added a custom ngraph operation as you mentioned, now the problem has been resolved.  My custom layer implemented on CPU and GPU both work fine.  I think this issue can be closed now.
