### ISSUE TITLE
How to build OpenVINO in Release mode with debug information

### ISSUE THREAD

**Issue by vt911001** [openvinotoolkit/openvino#3908]
Hi,

Is it possible to build OpenVINO in Release mode with debug information?

Thanks,
Vincent

**Comment by jgespino** [comment]
Hi @vt911001

Yes, it should be possible. Try following the [build instructions](https://github.com/openvinotoolkit/openvino/wiki#how-to-build) and setting `-DCMAKE_BUILD_TYPE=RelWithDebInfo`. Please let me know if this works for you.

Regards,
Jesus

**Comment by vt911001** [comment]
Hi Jesus,

Thanks, it worked great.
