### ISSUE TITLE
[Bug] run onnx file out wrong result

### ISSUE THREAD

**Issue by anhtu812** [openvinotoolkit/openvino#3909]
run onnx file out wrong result (very different correct result if run same file with TensorRT of Nvidia)
[https://1drv.ms/u/s!AhFk3ICqlZI2irxlq5eFUSJd3tNJCA?e=akZOUL](onnx_file)
model converted from tensorflow use tf2onnx

##### System information
- OpenVINO => 2021.2
- Operating System / Platform => Ubuntu18.04
- CPU Xeon E5-2620

**Comment by avitial** [comment]
@anhtu812 please provide additional details on how to reproduce, model details (topology, classification or object detection, etc.),  TF version, MO command used to convert to IR, sample/demo app used for model inference (or if custom script used please share), input sample and expected result, and any other relevant info to help identify possible issue.

~Luis

**Comment by anhtu812** [comment]
it is OCR model. Wrong output are all 0 and 69 (correct result must have num different 0 and 69).
Wrong output:
`argmax: 
0 0 0 0 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 0 0`
image to test:
[https://1drv.ms/u/s!AhFk3ICqlZI2irxmX9QsJFljHTgkzw?e=oBwANS](url)
code test:
`#include <inference_engine.hpp>
using namespace InferenceEngine;

#include "opencv2/opencv.hpp"

InferenceEngine::Blob::Ptr wrapMat2Blob(const cv::Mat &mat) {
    size_t channels = mat.channels();
    size_t height = mat.size().height;
    size_t width = mat.size().width;

    size_t strideH = mat.step.buf[0];
    size_t strideW = mat.step.buf[1];

    bool is_dense =
            strideW == channels*4 &&
            strideH == channels * width*4;

    if (!is_dense) THROW_IE_EXCEPTION
                << "Doesn't support conversion from not dense cv::Mat";

    InferenceEngine::TensorDesc tDesc(InferenceEngine::Precision::FP32,
                                      {1, height, width, channels},
                                      InferenceEngine::Layout::NHWC);

    return InferenceEngine::make_shared_blob<float>(tDesc, (float*)(mat.data));
}

int main(int argc, char** argv) {

  std::string setting_file_name = "/media/tu/T4_DATA2/workspace/Tu/git/train_model/OCR/link_to_data/Trains/2020-12-30_09:11_2020-12-30_09:10_59_val_acc:0.8396.h5_converted_trt/2020-12-30_09:10_59_val_acc:0.8396.h5_converted.onnx";
  std::string device_name = "CPU";// [CPU, GPU, MYRIAD, HDDL]


  Core ie;
  std::vector<std::string> devices = ie.GetAvailableDevices();
  for (auto s:devices) std::cout<<s<<"\n";
  CNNNetwork network = ie.ReadNetwork(setting_file_name);
  std::cout<<"1\n";

  std::string input_name, output_name;
  InferRequest infer_request;
  // for(;;)
  {
    auto input_shapes = network.getInputShapes();
    InferenceEngine::SizeVector input_shape;
    std::tie(input_name, input_shape) = *input_shapes.begin(); // let's consider first input only
    input_shape.resize(4);
    input_shape[0] = 1; // set batch size to the first input dimension
    input_shape[1] = 62; // set batch size to the first input dimension
    input_shape[2] = 512; // changes input width to the image one
    input_shape[3] = 1; // changes input width to the image one
    input_shapes[input_name] = input_shape;
    // ---------------------------------------------------------------------------------

    // ------------- 3. Call reshape ---------------------------------------------------
    network.reshape(input_shapes);
    InputInfo::Ptr input_info = network.getInputsInfo().begin()->second;
    input_info->setLayout(Layout::NHWC);
    input_info->setPrecision(Precision::FP32);
    DataPtr output_info = network.getOutputsInfo().begin()->second;
    output_name = network.getOutputsInfo().begin()->first;

    output_info->setPrecision(Precision::FP32);
    ExecutableNetwork executable_network = ie.LoadNetwork(network, device_name);
    // std::cout<<"executable_network\n";
    infer_request = executable_network.CreateInferRequest();
  }
  std::cout<<"infer_request\n";

  cv::Mat image = cv::imread("../0_20151224_0142_7606_1_0000_2_0.png");
  cv::cvtColor(image, image, cv::COLOR_BGR2GRAY);
  int pad = 4;
  // cv::copyMakeBorder(image,image,0,0,pad,pad,cv::BORDER_CONSTANT, cv::Scalar(0));
  cv::Mat image_;
  image.convertTo(image_, CV_32F);

  Blob::Ptr imgBlob = wrapMat2Blob(image_);  // just wrap Mat data by Blob::Ptr without allocating of new memory
  infer_request.SetBlob(input_name, imgBlob);  // infer_request accepts input blob of any size
  std::cout<<"SetBlob done\n";
  /* Running the request synchronously */
  // for (;;)
  {
    infer_request.Infer();
    output_name = "Identity_3:0";
    Blob::Ptr output = infer_request.GetBlob(output_name);
    auto desc = output->getTensorDesc();
    auto dims = desc.getDims();

    std::cout<<dims[0]<<" "<<dims[1]<<" "<<dims[2]<<" "<<dims.size()<<" getDims()\n";
    std::cout<<desc.getPrecision()<<" getPrecision()\n";
    std::cout<<"argmax: \n";
    auto p = output->buffer().as<float*>();
    for (auto i=0; i<dims[1]; ++i){
      float sum = 0;
      int argmax = -1;
      float max = -1;
      for (auto j=0; j<dims[2]; ++j){
        sum += *p;
        if (*p > max){
          max = *p;
          argmax = j;
        }
        ++p;
      }
      // std::cout<<sum<<" ";
      std::cout<<argmax<<" ";
    }
  }
}
`

**Comment by avitial** [comment]
@anhtu812 thanks for the extra info. I am able to see the same incorrect output as reported, share the correct actual output from given image to test. Please also share your TF frozen model prior conversion to ONNX. 

~Luis

**Comment by anhtu812** [comment]
TF2.3.1 saved_model: [https://1drv.ms/u/s!AhFk3ICqlZI2irxncLgVxDsZC5rBvQ?e=RrAIAF](url)
correct output:
```
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 69 69 69 69 69 61 69 69
  69 69 59 69 69 69 69 69 42 69 69  0  0 69 69 22 69  0  0 69 69 69 69 69
  69 61 61 69 69 69 69 69 69 49 69 69 69 69 69 62 69 69 69 69 69 69 69 69
  69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69  0  0  0
   0  0  0  0  0 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69
  69 69 69 69 69 69 69 69]]
```

**Comment by avitial** [comment]
@anhtu812 try changing [1] and [2] below in your code and see if that solves the issue, I am able to see the correct output as per your last comment. Not sure why NHWC doesn't give correct output, might be because default assumption of Inference Engine that the input color format is BGR and color format conversions are disabled, check [Integrate the Inference Engine with Your Application](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Integrate_with_customer_application_new_API.html#integration_steps) for more info. 

[1]
```
InferenceEngine::TensorDesc tDesc(InferenceEngine::Precision::FP32,
                                      {1, height, width, channels},
                                      InferenceEngine::Layout::NCHW);
``` 
[2]
```
input_info->setLayout(Layout::NCHW);
```

~Luis

**Comment by anhtu812** [comment]
@avitial thanks, your solution worked. But i think it is small bug of Openvino.
