### ISSUE TITLE
[Bug] Convert a ONNX to IR to MyriadX VPU Blob from Lobe

### ISSUE THREAD

**Issue by KartoffelToby** [openvinotoolkit/openvino#3916]
##### System information
- OpenVINO => 2021.2.200
- Operating System / Platform => Ubuntu (Docker)
- Problem classification: Error on converting a ONNX Model
- Framework: ONNX from Lobe

##### Detailed description
I'm new to OpenVinou, i have only practice with Tensorflow JS.
Im try to Convert a Lobe exported model (ONNX) into a blob ot run on the MyriadX VPU.

First i run
```python mo_onnx.py --input_model "/path/to/model.onnx"```

Second i would run ```./myriad_compile -m  path/to/model.xml -o /output/path/to/model.blob -ip U8 -VPU_MYRIAD_PLATFORM VPU_MYRIAD_2480 -VPU_NUMBER_OF_SHAVES 4 -VPU_NUMBER_OF_CMX_SLICES 4```

But i got an error with the first command:

```
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/data/Headphones ONNX/model.onnx
	- Path for generated IR: 	/data/.
	- IR output name: 	model
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
ONNX specific parameters:
Model Optimizer version: 	2021.2.0-1877-176bdf51370-releases/2021/2
2021-01-19 13:07:08.640034: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-01-19 13:07:08.640057: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[ ERROR ]  Shape [ -1 224 224   3] is not fully defined for output 0 of "saved_resnet_50_model/tf_op_layer_Mul/Mul". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "saved_resnet_50_model/tf_op_layer_Mul/Mul".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "saved_resnet_50_model/tf_op_layer_Mul/Mul". 
 For more information please refer to Model Optimizer FAQ, question #40. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=40#question-40)
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Elementwise.__init__.<locals>.<lambda> at 0x7fb942099940>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "saved_resnet_50_model/tf_op_layer_Mul/Mul" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)
```
I think the missing GPU Support isn't the failure 
##### Steps to reproduce
- Create a Lobe Model
- Export to ONNX
- Run ```python mo_onnx.py --input_model "/path/to/model.onnx"```

**Comment by avitial** [comment]
@KartoffelToby the issue from first command seems to originate from input node not having a defined shape. Try adding `--batch 1` **OR** `--input_shape [1,224,224,3]` to your Model Optimizer command (first command) and see if that converts successfully. Let me know the outcome.


~Luis

**Comment by KartoffelToby** [comment]
@avitial Sorry, i tried it already with --input_shape [1,224,224,3]. It's a different error forgot to post it

```
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Cannot change data-type for object array.
[ ERROR ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2021.2.200/deployment_tools/model_optimizer/mo/main.py", line 297, in main
    ret_code = driver(argv)
  File "/opt/intel/openvino_2021.2.200/deployment_tools/model_optimizer/mo/main.py", line 264, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/opt/intel/openvino_2021.2.200/deployment_tools/model_optimizer/mo/main.py", line 242, in emit_ir
    prepare_emit_ir(graph=graph,
  File "/opt/intel/openvino_2021.2.200/deployment_tools/model_optimizer/mo/pipeline/common.py", line 221, in prepare_emit_ir
    serialize_constants(graph, bin_file)
  File "/opt/intel/openvino_2021.2.200/deployment_tools/model_optimizer/mo/back/ie_ir_ver_2/emitter.py", line 44, in serialize_constants
    serialize_constants_recursively(graph, bin_file, data_type, bin_hashes)
  File "/opt/intel/openvino_2021.2.200/deployment_tools/model_optimizer/mo/back/ie_ir_ver_2/emitter.py", line 66, in serialize_constants_recursively
    blob_hash = hashlib.sha512(np.ascontiguousarray(blob).view(np.uint8)).hexdigest()
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_internal.py", line 461, in _view_is_safe
    raise TypeError("Cannot change data-type for object array.")
TypeError: Cannot change data-type for object array.

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```

**Comment by avitial** [comment]
@KartoffelToby when going through the OpenVINO install, did you install all the pre-requisites? Share also the TF version installed on your machine as well as the ONNX model.

~Luis

**Comment by KartoffelToby** [comment]
Sure, is installed it via ```cd /opt/intel/openvino_2021/deployment_tools/model_optimizer/install_prerequisites && ./install_prerequisites.sh```

The TF Version is 2.3.2

**Comment by KartoffelToby** [comment]
@avitial here is the model https://1drv.ms/u/s!AqKyxwmGHF8r70J5RrVmaplhIyzc?e=UcJjNj

**Comment by avitial** [comment]
@KartoffelToby, thanks for providing the model. Glancing at the model with Netron I can see model has input `Image:0` and outputs `00fc452e-3d62-4f17-ba5b-28a0046059eb/dense_2/Softmax:0 and 00fc452e-3d62-4f17-ba5b-28a0046059eb/tf_op_layer_3ff186c1-fe28-4442-abe1-44f7ed005781/19c66cd4-e1d6-49f4-80ab-3aa348c5b264/ff9b2ff4-4799-495e-8e91-a6fed91e9315/GatherV2/3ff186c1-fe28-4442-abe1-44f7ed005781/19c66cd4-e1d6-49f4-80ab-3aa348c5b264/ff9b2ff4-4799-495e-8e91-a6fed91e9315/GatherV2` **AND** `00fc452e-3d62-4f17-ba5b-28a0046059eb/dense_2/Softmax:0`. 

The MO issue seems to come from output **GatherV2:0** as it is a type string hence the error, as MO doesn’t support data type string. Perhaps replacing the data type in your original model to type float32 would work. As you can see cutting out this node works with the following MO command: `python3 /opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/mo_onnx.py --input_model model.onnx --input_shape [1,224,224,3] --input="Image:0" --output="00fc452e-3d62-4f17-ba5b-28a0046059eb/dense_2/Softmax"`. Hope this helps.

~Luis

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
