### ISSUE TITLE
[WARN] Could not create an nGraph Constant for an ONNX Constant node

### ISSUE THREAD

**Issue by bianxg** [openvinotoolkit/openvino#3928]
System information (version)
OpenVINO=> 2021.2
Operating System / Platform => Linux - Ubuntu 18.04.5 LTS
ONNX model : https://github.com/PeterL1n/BackgroundMattingV2

When consume ONNX files in IE, There are some warnings. What does it mean? how to fix it? Thanks.

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_555 () -> (f32{})' with friendly_name 'Constant_555':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_565 () -> (f32{})' with friendly_name 'Constant_565':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_593 () -> (f32{})' with friendly_name 'Constant_593':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_603 () -> (f32{})' with friendly_name 'Constant_603':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_631 () -> (f32{})' with friendly_name 'Constant_631':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_641 () -> (f32{})' with friendly_name 'Constant_641':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_669 () -> (f32{})' with friendly_name 'Constant_669':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_679 () -> (f32{})' with friendly_name 'Constant_679':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_707 () -> (f32{})' with friendly_name 'Constant_707':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-01-20T02:56:10z ngraph/frontend/onnx_import/src/op/constant.cpp 45	Could not create an nGraph Constant for an ONNX Constant node. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_717 () -> (f32{})' with friendly_name 'Constant_717':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

This sample is an API example, for any performance measurements please use the dedicated benchmark_app tool

**Comment by jgespino** [comment]
Hi @bianxg 

Thanks for reaching out, are you using the same model from the link you provided? I downloaded `onnx_mobilenetv2_hd.onnx` and run into unsupported **If** ONNX operation. 

`python3 /opt/intel/openvino_2021/deployment_tools/tools/benchmark_tool/benchmark_app.py -m onnx_mobilenetv2_hd.onnx`

Regards,
Jesus

**Comment by bianxg** [comment]
https://github.com/PeterL1n/BackgroundMattingV2/issues/46
The only place squeeze() is used is in refiner.py. You can change ref.squeeze(1) in refiner.py to ref[:, 0, :, :]. Then re-export ONNX. This should get rid of the if node.

**Comment by bianxg** [comment]
https://github.com/PeterL1n/BackgroundMattingV2/issues/57

**Comment by jgespino** [comment]
Hi @bianxg 

I was able to see the warning messages when loading the ONNX model, let me reach out to the development team for input. Loading the intermediate representation (.xml/.bin) of the model did not show any warnings.

Regards,
Jesus

Ref. 48334

**Comment by jgespino** [comment]
Hi @bianxg 

I heard back from the development team, the warnings appear when there is no value for a Constant node in the ONNX model. In this case, the ONNX importer will create a Constant with value '0' instead. This can be fixed in the ONNX model by filling the empty tensors with proper values.

The development team has also created a PR to provide a more meaningful message.
https://github.com/openvinotoolkit/openvino/pull/4355

Please let me know if you have additional questions.

Regards,
Jesus
