### ISSUE TITLE
[Bug]undefined symbol: _ZN3tbb8internal13numa_topology4fillEPi

### ISSUE THREAD

**Issue by alixiu** [openvinotoolkit/openvino#3929]
##### System information (version)

- OpenVINO => 2020.4.287(2021.2.185)
- Operating System / Platform => linux ubuntu 64 Bit
- Compiler =>Linux version 5.4.0-60-generic (buildd@lgw01-amd64-007) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))
- Problem classification: Model Inference

##### Detailed description

I have ssd_mobilenet_v2.xml, and then want to perform inference on ncs. The folllowing operations are conducted.
`cd  /opt/intel/openvino/deployment_tools/inference_engine/samples/cpp`
`bash build_samples.sh`
`cd ~/inference_engine_cpp_samples_build/intel64/Release`
` sudo ./benchmark_app  -m ssd_mobilenet_v2.xml -d MYRIAD -i $OPENVINO_HOME/demo/car.png`
**generating the following error:**
`./benchmark_app: symbol lookup error: /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libinference_engine.so: undefined symbol: _ZN3tbb8internal13numa_topology4fillEPi`
But, when I use cpu device with command `./benchmark_app  -m ssd_mobilenet_v2.xml  -i $OPENVINO_HOME/demo/car.png`, it is ok.

I try to solve the problem:
**Firstly, I checked with`ldd benchmark_app` and everything seems to be ok:**
`	linux-vdso.so.1 (0x00007fff7acde000)
	libinference_engine_legacy.so => /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libinference_engine_legacy.so (0x00007f6c38080000)
	libinference_engine.so => /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libinference_engine.so (0x00007f6c37e20000)
	libformat_reader.so => /home/maxiu/inference_engine_cpp_samples_build/intel64/Release/lib/libformat_reader.so (0x00007f6c37c14000)
	libopencv_core.so.4.4 => /opt/intel/openvino/opencv/lib/libopencv_core.so.4.4 (0x00007f6c36b1c000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6c36918000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6c3658f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6c36377000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6c35f86000)
	libtbb.so.2 => /opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2 (0x00007f6c35d1e000)
	libinference_engine_transformations.so => /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libinference_engine_transformations.so (0x00007f6c35a13000)
	libngraph.so => /opt/intel/openvino/deployment_tools/ngraph/lib/libngraph.so (0x00007f6c350cb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6c34d2d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6c34b0e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6c387a1000)
	libopencv_imgcodecs.so.4.4 => /opt/intel/openvino/opencv/lib/libopencv_imgcodecs.so.4.4 (0x00007f6c3485e000)
	libopencv_imgproc.so.4.4 => /opt/intel/openvino/opencv/lib/libopencv_imgproc.so.4.4 (0x00007f6c324d4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6c322cc000)
`

**Secondly, I checked the tbb.**
`cd /`

`sudo find -name "libtbb.so"`
`./home/xiu/anaconda3/lib/libtbb.so`
`find: ‘./run/user/1000/gvfs’: Permission denied`
`find: ‘./run/user/121/gvfs’: Permission denied`
`./opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/external/tbb/lib/libtbb.so`
`./usr/lib/x86_64-linux-gnu/libtbb.so`

`export LD_LIBRARY_PATH=/opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/external/tbb/lib/:$LD_LIBRARY_PATH`
After configuring,
`sudo ./benchmark_app  -m ssd_mobilenet_v2.xml -d MYRIAD -i $OPENVINO_HOME/demo/car.png`
The above error also occurred.

**Comment by ilya-lavrenov** [comment]
What is the output of `ldd libmyriadPlugin.so`?
Have you run `setupvars.sh` before building and running sample applications?

**Comment by alixiu** [comment]
> What is the output of `ldd libmyriadPlugin.so`?
`	linux-vdso.so.1 (0x00007fff350cc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0125578000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f0125360000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f012515c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0124dd3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0124bbb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f01247ca000)
	libinference_engine.so => /opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/lib/intel64/libinference_engine.so (0x00007f012456a000)
	libtbb.so.2 => /opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2 (0x00007f0124302000)
	libinference_engine_legacy.so => /opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/lib/intel64/libinference_engine_legacy.so (0x00007f0123e51000)
	libinference_engine_transformations.so => /opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/lib/intel64/libinference_engine_transformations.so (0x00007f0123b46000)
	libngraph.so => /opt/intel/openvino_2020.4.287/deployment_tools/ngraph/lib/libngraph.so (0x00007f01231fe000)
	libinference_engine_lp_transformations.so => /opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/lib/intel64/libinference_engine_lp_transformations.so (0x00007f0122f7d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0122bdf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0125ed9000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f01229c1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f01227b9000)
`

> Have you run `setupvars.sh` before building and running sample applications?
Yes, I do. 
Firstly, I perform `source /opt/intel/openvino/bin/setupvars.sh` . 
Then, `cd /opt/intel/openvino/inference_engine/samples/cpp`, ` bash build_samples.sh`.
Next, `cd ~/inference_engine_cpp_samples_build/intel64/Release`, `sudo ./benchmark_app -m ssd_mobilenet_v2.xml -d MYRIAD -i $OPENVINO_HOME/demo/car.png`

**Comment by alalek** [comment]
> sudo

All problems are from here.
Due to security reasons it drops all/some necessary environment variables.
Consider avoiding using of `sudo` in your workflows.

---

Just compare:
```
$ ldd libmyriadPlugin.so
$ sudo ldd libmyriadPlugin.so
```

**Comment by alixiu** [comment]
@alalek 
Thank you very much. I compare the result of the above two commands. The `libtbb.so.2` is different. I try to use
`./benchmark_app -d MYRIAD -i $OPENVINO_HOME/demo/car.png -m ssd_mobilenet_v2.xml`. However, a new problem is generated.

`[Step 7/11] Loading the model to the device
W: [ncAPI] [    626335] [benchmark_app] ncDeviceOpen:939	ncDeviceOpen() XLinkBootRemote returned error X_LINK_SUCCESS for 1.1-ma2480
E: [ncAPI] [    641335] [benchmark_app] ncDeviceOpen:1011	Failed to find booted device after boot
W: [ncAPI] [    641335] [benchmark_app] ncDeviceOpen:1014	Device (1.1-ma2480) doesn't disappear after firmware loading
[ ERROR ] Can not init Myriad device: NC_ERROR
`

I tried to restart the service and **reconnect the USB device(NCS2)** to solve this problem, but it doesn’t work.

**Comment by alalek** [comment]
Ensure that this step is applied:
- https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#additional-NCS-steps
- https://github.com/openvinotoolkit/openvino/blob/2021.2/scripts/install_dependencies/install_NCS_udev_rules.sh

---

In case of continuing using `sudo` you need to prepare launcher:
- `openvino_exec.sh` (don't forget to apply `chmod +x`):
```.bash
#!/bin/bash

source <openvino_path>/bin/setup_vars.sh
exec "$@"
```

- usage: `sudo ./openvino_exec.sh ./benchmark_app ...` (be careful and ensure that it "works" without `sudo` first)

**Comment by alixiu** [comment]
@alalek @ilya-lavrenov 
Thanks very much for your reply.  The problem `ncDeviceOpen:939`  is because of my carelessness, which has been resolved now. The above problem `undefined symbol` is indeed caused by using `sudo`. I perform inference successfully without `sudo`.
