### ISSUE TITLE
Ngraph install env vars setting

### ISSUE THREAD

**Issue by Mingqi2** [openvinotoolkit/openvino#3955]
Hi! I built ngraph for openvino by doc: https://github.com/openvinotoolkit/openvino/blob/master/ngraph/python/BUILDING.md#building-the-python-api-for-ngraph
It's a clear doc but I still found something need to append.

About wheel built:
```
cd "${OPENVINO_BASEDIR}/openvino/ngraph/python"
python3 setup.py bdist_wheel
```
It need two env vars: NGRAPH_CPP_BUILD_PATH & PYBIND_HEADERS_PATH but the doc don't mention them. The setup.py provides a default value for them but it's not right. I found them and set them manually: 
```
export NGRAPH_CPP_BUILD_PATH=~/openvino_dist
export PYBIND_HEADERS_PATH=~/openvino/build-any/ngraph/python/pybind11
```
I think it's a good way to set them in ${OPENVINO_BASEDIR}/openvino_dist/bin/setupvars.sh

**Comment by ilya-lavrenov** [comment]
CC @mryzhov @slyubimt

**Comment by slyubimt** [comment]
@Mingqi2,
  Build instructions for Python bindings for NGraph were refactored recently. You need not to set these environment variables any more. 
Could you please rebase your branches and check?

**Comment by Mingqi2** [comment]
@slyubimt That's good! Thanks for your reply.
I'm on releases/vpux/2021/2 branch. Maybe this branch is behind with master.
