### ISSUE TITLE
Benchmark app python device name formatting

### ISSUE THREAD

**Issue by timlueg** [openvinotoolkit/openvino#398]
Because of:

https://github.com/opencv/dldt/blob/b2140c083a068a63591e8c2e9b5f6b240790519d/inference-engine/tools/benchmark_tool/benchmark_app.py#L33

The python benchmark does not find devices with lowercase names.
`-d MULTI:MYRIAD.3.1-ma2480,MYRIAD.3.2-ma2480` works with c++ based 
`benchmark_app` but but not with `benchmark_app.py`

**Comment by jgespino** [comment]
Hi @timlueg 

Thanks for reporting! A bug was just submitted on Friday for the development team to take a look. I will let you know what we find out. 

Regards,
Jesus

**Comment by ilya-lavrenov** [comment]
@nkogteva could you please comment?

**Comment by nkogteva** [comment]
I close the issue since problem is fixed on master branch.
