### ISSUE TITLE
Converting IR to Caffe

### ISSUE THREAD

**Issue by XiongZhongxia** [openvinotoolkit/openvino#40]
Hi there,
Thanks for your job!
I wonder if there is a way to convert IR files, i.e, .bin and xml files，to the original model, like .caffemodel and .prototxt?
Or could you please tell me where to find person-detection-retail-0013.caffemodel and person-detection-retail-0013.prototxt and other original files before converting to IR files?
Thanks again!

**Comment by lazarevevgeny** [comment]
@XiongZhongxia unfortunately there is no such a capability.

**Comment by EvenPeng** [comment]
@XiongZhongxia  It's a one-way trip since the model optimizer might merge or skip some layers, even change the precisions.

**Comment by lazarevevgeny** [comment]
There is no way to convert IR to Caffe and there are no plans to support this scenario. Closing the issue.
