### ISSUE TITLE
Use Detectron2's .pb model with OpenVINO

### ISSUE THREAD

**Issue by ClaudiaRaffaelli** [openvinotoolkit/openvino#4024]
Hello, 
I'm trying to follow this [demo](https://docs.openvinotoolkit.org/latest/omz_demos_python_demos_instance_segmentation_demo_README.html) for Instance Segmentation. I have seen that it is necessary to use a model converted to the IR format. 
My model has been trained using Detectron2 with Mask R-CNN. Following the [Detectron2 script](https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/export_model.py) for conversion, with export method Caffe2, I exported the model, i.e. from a `.pth` file I obtained the two following `.pb` files: `model_init.pb` and `model.pb`. Basically the first one can be used to obtain a net that stores all the weights, offsets etc., while the model stores the operators that execute the network.

I'm wondering if it is possible to convert this two `.pb` into the format that can be used by OpenVINO. If this is not possibile, are there any alternative ways? Thanks for your support.

**Comment by jgespino** [comment]
Hi @ClaudiaRaffaelli 

Thanks for reaching out, I have not tried using a model that is split into weights and operators. Could you try exporting your model to ONNX format instead? We recently added support of reading ONNX models directly without needing to convert to Intermediate Representation. However, I am not certain this will work as Detectron2 is not currently supported. 

The Instance Segmentation demo only supports the following models: `instance-segmentation-security-????`, `yolact-resnet50-fpn-pytorch`

Regards,
Jesus

**Comment by ClaudiaRaffaelli** [comment]
Hi @jgespino 
Yes, I was also wondering if Detectron2 was supported. Thanks for clarifying.

Regards,
Claudia
