### ISSUE TITLE
file INSTALL cannot find   "/root/packages/dldt/build/share/ie_rh_decoder.cmake".

### ISSUE THREAD

**Issue by code-wangshuyi** [openvinotoolkit/openvino#403]
-- Up-to-date: /usr/local/deployment_tools/inference_engine/share/ie_parallel.cmake
CMake Error at inference-engine/src/inference_engine/cmake_install.cmake:97 (file):
  file INSTALL cannot find
  "/root/packages/dldt/build/share/ie_rh_decoder.cmake".
Call Stack (most recent call first):
  inference-engine/src/cmake_install.cmake:48 (include)
  inference-engine/cmake_install.cmake:75 (include)
  cmake_install.cmake:43 (include)

Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by code-wangshuyi** [comment]
I have tried twice

**Comment by asuhov** [comment]
Hello, make "install" target currently is not supported.

As a workaround, you can try to remove the following line from the "inference-engine\src\inference_engine\CMakeLists.txt" file:

"${OpenVINO_BINARY_DIR}/share/ie_rh_decoder.cmake"

**Comment by code-wangshuyi** [comment]
It worked，then how should I to install what I compiled if I DON'T use make "install".

**Comment by ilya-lavrenov** [comment]
Installation of this file is removed. See https://github.com/openvinotoolkit/openvino/commit/a347375d0188b58056887f382161c6ed6fc3dcb3
