### ISSUE TITLE
slow inference on CRNN

### ISSUE THREAD

**Issue by 07freedom** [openvinotoolkit/openvino#4057]
I have tried classic CRNN OCR model on openvino where I find the result very confusing.
Unlike other models, CRNN with LSTM layer shows worse performance on inference time. 
![image](https://user-images.githubusercontent.com/16747531/106107343-c9d83f80-6181-11eb-885f-60a72893de6d.png)
Does anyone have the same issue?

**Comment by 07freedom** [comment]
System: Ubuntu 18.04(Aliyun)
CPU: Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
CRNN is similar to https://github.com/bgshih/crnn

**Comment by avitial** [comment]
@07freedom thanks for reaching out, we have a [guide](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_CRNN_From_Tensorflow.html) on how to convert TensorFlow CRNN* Models to the Intermediate Representation (IR). Other implementations of CRNN model should work.

If possible share additional details of environment for repro: Python/TensorFlow version, OpenVINO version, Model Optimizer command used to optimize model, plugin used for inference, and any other additional details that can help reproduce. If you have a sample model (pre/post conversion) and app that can help showcase the observed issue please share it as well.

~Luis

**Comment by wdkwyf** [comment]
I also ran CRNN-TF in my PC(i7-8665U). 
Precision: FP32. 
Image size: 1*32*100*3
device: CPU
TF: 30 fps                      profile sess.run() time
OpenVINO: 130 fps      use benchmark_app, profile inference time

**Comment by avitial** [comment]
@wdkwyf seems like you get a performance boost when using OpenVINO. Are you facing the same or similar issue as original reporter?

~Luis

**Comment by avitial** [comment]
Closing this as not enough info was provided. Feel free to reopen and ask additional questions related to this topic if issue persists.
