### ISSUE TITLE
Grouped Convolution on VPU

### ISSUE THREAD

**Issue by dhpalle** [openvinotoolkit/openvino#4073]
Hello All,
I am trying to understand the logic behind the assertion at line 404

in the file
https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/vpu/graph_transformer/src/stages/convolution.cpp

I copied the assertion below for ease of reference:

```C++
    VPU_THROW_UNLESS(output_channels / groups == biases->desc().dim(Dim::C),
                     "number of biases must equal to number of output channels per group, but: "
                     "channels per group=%d, biases=%d",
                     output_channels / groups, biases->desc().dim(Dim::C));
```

Assertion expects that the number of number of biases to be equal to number of output channels per group. 

If the network has layer like the one described below:
```python
from torch import nn
m = nn.Conv3d(in_channels=3,out_channels=3,kernel_size=[3,3,3],stride=[1,2,2],padding=[1,1,1,1,1,1],groups=3)
### We will see that m.weight.shape = torch.Size([3,1,3,3,3])
### m.bias.shape = torch.Size([3])
### m.out_channels = 3
### m.groups = 3
```
So out_channels/groups /= len(bias)

I converted a model with such layer from onnx to openvino format. Model runs on CPU but fails to run on VPU due to the assertion above.

How can we fix this ?

**Comment by jgespino** [comment]
Hi @dhpalle 

Thanks for reaching out, according to the [documentation ](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_Supported_Devices.html#supported_model_formats) Convolution-Grouped 3D layer is only supported on CPU and GPU plugins.

@ilya-lavrenov Could you confirm?

Regards,
Jesus

**Comment by ilya-lavrenov** [comment]
@Maxim-Doronin to comment about MYRIAD layers support.

**Comment by Maxim-Doronin** [comment]
@elatkin, could you please comment on it as Conv3D stage author?

**Comment by dhpalle** [comment]
@elatkin I am not sure how to HETERO plugin works. According to the documentation here (https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_HETERO.html), HETERO plugin should take care of fallback to CPU for case of provider="HETERO:MYRIAD,CPU". If the detection of the no support for groups>1 occurs inside convolution.cpp, will the fallback still occur ?

**Comment by elatkin** [comment]
@dhpalle
Sorry for long delay before responding!

Here is my vision of the situation:
* Grouped 3D convolution is not supported by the Myriad X plugin, unfortunately
* The error message about that is misleading. This is the bug: I am working on fixing the error message, see the pull-request #4199
* We are currently investigating the possibility for supporting grouped 3D convolution on Myriad X processor

Concerning the hetero plugin, I am not sure about performance on ARM processor. I think, by CPU we primarily implied x86, see:
* [Supported Devices - OpenVINO™ Toolkit](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_Supported_Devices.html)

Anyway, please let me find another person who could explain the hetero plugin. I must confess that I do not know much about the hetero

**Comment by alvoron** [comment]
@dhpalle 
Recently [ARM CPU plugin](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin) was released as contrib module. It allows to perform deep neural networks inference on ARM CPUs, using OpenVINO API.
The plugin is built as a wrapper over [ARM Compute library](https://github.com/ARM-software/ComputeLibrary). Unfortunately, ARM Compute library doesn’t support Conv3D, only 2D is supported.

**Comment by avitial** [comment]
Ref. 48529

**Comment by ilya-lavrenov** [comment]
MYRIAD plugin is removed from master branch.
