### ISSUE TITLE
how to get each layer's weights?

### ISSUE THREAD

**Issue by oxygenman** [openvinotoolkit/openvino#4074]
when I convert an onnx model to openvino, the inference result is not correct,so i want to get the weights of each IR model's layer to check out where is wrong, but i can't find an API to do this ? could you tell me how to do this ?

**Comment by ilya-lavrenov** [comment]
Hi @oxygenman

Do you need weights of the layer or maybe its result? In the second case you can add more outputs to the network (`CNNNetwork::addOutput`) and observe output of any graph node

Thanks,
Ilya.

**Comment by oxygenman** [comment]
> Hi @oxygenman
> 
> Do you need weights of the layer or maybe its result? In the second case you can add more outputs to the network (`CNNNetwork::addOutput`) and observe output of any graph node
> 
> Thanks,
> Ilya.

**Comment by oxygenman** [comment]
thank you,this way can't get the weights,but solved my problem.
