### ISSUE TITLE
how to build openvino on a system with no network access

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/openvino#4075]
- OpenVINO => tag 2021.2
- Operating System / Platform => 18.04.5 LTS (GNU/Linux 4.15.0-117-generic x86_64)
- Compiler => gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

##### Detailed description
I have a system with no network access, and I have copied openvino source code, including submodules, into it by u-disk. And I need to build openvino from source code from that machine.

##### Steps to reproduce
```
cmake -DENABLE_VALIDATION_SET=OFF \
        -DCMAKE_INSTALL_PREFIX=~/openvino_work/install \
        -DENABLE_MKL_DNN=ON \
        -DENABLE_GNA=OFF \
        -DENABLE_CLDNN=OFF \
        -DENABLE_MYRIAD=OFF \
        -DENABLE_VPU=OFF \
        -DENABLE_OPENCV=OFF \
        -DCMAKE_BUILD_TYPE=Debug \
         ../openvino
```
as far as I know, cmake will git clone and download some dependencies. Is it possible to download them manually and put them at the right place before cmake? thanks.

**Comment by guoyejun** [comment]
Actually, even when I tried on machines with network, for every refresh build, I always have to wait for a long long time for theses downloads, and sometimes it even takes 2-3 days when the network is not stable. This time, I've spent 4+ hours, retried several times for cmake, and still in cmake period...

**Comment by ilya-lavrenov** [comment]
Hi,

1. `ENABLE_VALIDATION_SET` there is not such option.
2. `ENABLE_VPU` downloads some dependencies. No way to predownload them and put to the right place, but they are not updated very often.
3. `ENABLE_OPENCV` you can build your own version of OpenCV and pass to IE cmake via `-DOpenCV_DIR=<build path>`
4. `THREADING=TBB` which is default, also downloads TBB. You can provide pre-build TBB via `-DTBBROOT` or `-DTBB_DIR`
5. `ENABLE_GNA` no way to pre-download GNA libraries and pass to cmake.
6. `NGRAPH_ONNX_IMPORT_ENABLE` probably, it takes a lot of time and if you don't need ONNX importer, you can set this option to `OFF` and it will not download protobuf, onnx libraries.

**Comment by guoyejun** [comment]
thanks, i'll have a try.

**Comment by guoyejun** [comment]
i tried with
```
cmake -DCMAKE_INSTALL_PREFIX=~/openvino_work/install \
        -DENABLE_MKL_DNN=ON \
        -DENABLE_GNA=OFF \
        -DENABLE_CLDNN=OFF \
        -DENABLE_MYRIAD=OFF \
        -DENABLE_VPU=OFF \
        -DENABLE_OPENCV=OFF \
        -DCMAKE_BUILD_TYPE=Debug \
        -DNGRAPH_ONNX_IMPORT_ENABLE=OFF \
         ../openvino

make
```

And at the end of make, there's still a download
```
[100%] Linking CXX shared library /root/openvino_work/openvino/bin/intel64/Debug/lib/libMKLDNNPlugin.so
[100%] Built target MKLDNNPlugin
error: RPC failed; curl 56 GnuTLS recv error                                                                         (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'ext_gtest'...
-- Had to git clone more than once:
```
