### ISSUE TITLE
LSTM model inference issue

### ISSUE THREAD

**Issue by marcin-sielski** [openvinotoolkit/openvino#408]
I am experiencing inference issue on MYRIAD.

Unsupported layers found: ['input', 'h0', 'fc.bias/Output_0/Data_/copy_const', 'c0', '37/TensorIterator', '63/TensorIterator', '71'] Check whether extensions are available to add to IECore.

The [model](https://software.intel.com/sites/default/files/managed/ea/62/forecast.tar.gz) was converted from ONNX format.

**Comment by maxl16** [comment]
Hi @marcin-sielski 
I've run the model you pointed on MYRIAD (NCS 2) thru OpenVINO toolkit Inference Engine benchmark app (demo_benchmark_app.sh), so it works fine for me.
What application you use for the inference and what is Inference Engine version / OpenVINO toolkit version? And what's the OS?
We recommend you to try the latest available OpenVINO toolkit 2020.1 build from here - https://software.intel.com/en-us/openvino-toolkit/choose-download

Best regards, Max.

**Comment by marcin-sielski** [comment]
Hi @maxl16,

I am using the latest official OpenVino distribution under Ubuntu 18.04/Laptop.
$ ./benchmark_app -d MYRIAD -m ~/forecast/output/forecast.xml
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[ WARNING ] -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance,but it still may be non-optimal for some cases, for more information look at README.

[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine: 
	API version ............ 2.1
	Build .................. 37988
	Description ....... API
[ INFO ] Device info: 
	MYRIAD
	myriadPlugin version ......... 2.1
	Build ........... 37988

[Step 3/11] Setting device configuration
[Step 4/11] Reading the Intermediate Representation network
[ INFO ] Loading network files
[ INFO ] Read network took 1.25 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1, precision: MIXED
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
[ ERROR ] Check (env.config.ignoreUnknownLayers) failed: Failed to compile layer 37/LSTMCell_sequence : AssertionFailed: outputs.size() == 1

It is consistent to what I see on self built inference engine under RPI/Jetson.

Best Regards

Marcin Sielski

**Comment by maxl16** [comment]
Hi @marcin-sielski 
I'm able now to reproduce this error. And while running benchmark_app on CPU plugin with this model, do you see the same output as me?

[Step 7/11] Loading the model to the device
[ ERROR ] Unsupported source format for FC layer. Expected 5, 4 or 2, got: 3 dims.
Traceback (most recent call last):
  File "/opt/intel/openvino_2020.1.023/deployment_tools/tools/benchmark_tool/benchmark_app.py", line 82, in main
    exe_network = benchmark.load_network(ie_network, perf_counts, args.number_infer_requests)
  File "/opt/intel/openvino_2020.1.023/python/python3.6/openvino/tools/benchmark/benchmark.py", line 126, in load_network
    num_requests=number_infer_requests or 0)
  File "ie_api.pyx", line 134, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 141, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: **Unsupported source format for FC layer. Expected 5, 4 or 2, got: 3 dims.**

If so, I believe MYRIAD plugin sees FullyConnected layer with 3 input dims as unknown one. And as pointed above, IE expects it to be 5, 4, or 2 dims. 

I've checked one of the officially tested LSTM models from here - https://docs.openvinotoolkit.org/latest/_inference_engine_samples_speech_sample_README.html
So benchmark_app provides correct results for it.

Where did you get your original ONNX model? Is it available publicly somewhere?

**Comment by marcin-sielski** [comment]
Hi @maxl16 ,

Yes I confirm I have seen this error while executing inference on CPU.
Yes, model is publicly available at https://github.com/hazyair/forecast. ONNX was a product of conversion from PyTorch.

Best Regards

Marcin Sielski

**Comment by maxl16** [comment]
Hi @marcin-sielski 
I've converted your onnx model to FP16 IR model via OpenVINO toolkit 2020 Model Optimizer, and now benchmark app provides inference results for it. I also tried this in IR_V7 format and FP32 precision, and that works anyway.
Please find this attached and let me know if it works for you.
The command we used: >python3 mo_onnx.py --input_model forecast.onnx --data_type FP16

[forecast_IR.zip](https://github.com/opencv/dldt/files/4341138/forecast_IR.zip)

**Comment by marcin-sielski** [comment]
Hi @maxl16,
Thank you. I can confirm that the model is executed fine by benchmark_app without any issues. The problem was that I used model converted with older model optimizer tools and inferred it with new inference engine. I did not realized that there is huge difference between 2020.R3 and 2020.1.   Unfortunately I still see number of unsupported layers with following code:
```
net = IENetwork(model=model_xml, weights=model_bin)
supported_layers = plugin.query_network(network=net, device_name="MYRIAD")
unsupported_layers = [l for l in net.layers.keys() if l not in supported_layers] 
```
Given the fact everything works fine on benchmark_app I will try to investigate it further.

**Comment by marcin-sielski** [comment]
Hi @maxl16,
I am confused now. I have ignored unsupported layers and used load_network. load_network executed fine. Is there a bug in query_network then? I will try to see what about inference.

**Comment by marcin-sielski** [comment]
Hi @maxl16,
It looks like inference is working but I still do not understand the concept of unsupported layers.

**Comment by maxl16** [comment]
Hi @marcin-sielski 
Yes, there is a difference for IR model format between 2019 R3 and 2020.1 builds. However, Inference Engine from OpenVINO toolkit build 2020.1 is backward compatible with previous IR format, so for me it's still unknown why it didn't work for you in the first place.

What warning message do you see with regards to unsupported layers? And how do you do the inference? Is this a sample/demo script or your own program?

For more information on unsupported and custom layers please check this article - https://docs.openvinotoolkit.org/latest/_docs_HOWTO_Custom_Layers_Guide.html
And also "Implement Custom Layers" video series - https://www.youtube.com/playlist?list=PLg-UKERBljNw254jnyMNZiu8yqF8pPq0m

**Comment by lazarevevgeny** [comment]
@marcin-sielski can we close the bug?

**Comment by marcin-sielski** [comment]
Hi @lazarevevgeny,

I eventually was able to solve the issue with model by upgrading the OpenVINO, so yes the issue may be closed. I understand that I can still use model for inference even though "unsupported layers" are reported on NCS-2 as long everything works ok - those layers were just redundant and maybe not necessary/critical. I cannot understand why input and output layers are reported as unsupported though. I pass there appropriate input and I get expected output data so they are eventually supported. Am I missing sth? 

Best Regards

Marcin Sielski

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
