### ISSUE TITLE
C++ inference speed is not accelerated

### ISSUE THREAD

**Issue by bianxg** [openvinotoolkit/openvino#4098]
We have optimize model using openvino(https://github.com/kingpeter2015/libovmatting), but inference speed is not accelerated.
What is the possible reason?

https://github.com/PeterL1n/BackgroundMattingV2/issues/57

**Comment by maxlytkin** [comment]
@bianxg 
What performance results you get for your model converted? Depending on an inference device, for pytorch_mobilenetv2 mobile you should get approximately similar throughput and latency numbers - https://docs.openvinotoolkit.org/latest/openvino_docs_performance_benchmarks.html#mobilenet_v2_pytorch

There is a benchmarking tool available in the OpenVINO toolkit package which performs inference (available in C++ and Python). Performance can be measured for two inference modes: synchronous (latency-oriented) and asynchronous (throughput-oriented). The benchmark app usually produces optimal performance for any device out of the box:
benchmark_app -m <model.xml> -i <input> -d <device>

Benchmark C++ Tool -https://docs.openvinotoolkit.org/latest/openvino_inference_engine_samples_benchmark_app_README.html
Benchmark Python Tool - https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_benchmark_tool_README.html

**Comment by bianxg** [comment]
After retesting, I found that the performance has doubled after using openvino. Is it right?

benchmark_app -m model.xml -i -d
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine: 
	API version ............ 2.1
	Build .................. 2021.2.0-1877-176bdf51370-releases/2021/2
	Description ....... API
[ INFO ] Device info: 
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... 2021.2.0-1877-176bdf51370-releases/2021/2

[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance,but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 218.71 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 292.22 ms
[Step 8/11] Setting optimal runtime parameters
[Step 9/11] Creating infer requests and filling input blobs with images
[ INFO ] Network input 'bgr' precision U8, dimensions (NCHW): 1 3 720 1280 
[ INFO ] Network input 'src' precision U8, dimensions (NCHW): 1 3 720 1280 
[ WARNING ] No input files were given: all inputs will be filled with random values!
[ INFO ] Infer Request 0 filling
[ INFO ] Fill input 'bgr' with random values (image is expected)
[ INFO ] Fill input 'src' with random values (image is expected)
[ INFO ] Infer Request 1 filling
[ INFO ] Fill input 'bgr' with random values (image is expected)
[ INFO ] Fill input 'src' with random values (image is expected)
[ INFO ] Infer Request 2 filling
[ INFO ] Fill input 'bgr' with random values (image is expected)
[ INFO ] Fill input 'src' with random values (image is expected)
[ INFO ] Infer Request 3 filling
[ INFO ] Fill input 'bgr' with random values (image is expected)
[ INFO ] Fill input 'src' with random values (image is expected)
[Step 10/11] Measuring performance (Start inference asynchronously, 4 inference requests using 4 streams for CPU, limits: 60000 ms duration)
[ INFO ] First inference took 1506.59 ms

[Step 11/11] Dumping statistics report
Count:      116 iterations
Duration:   63040.80 ms
Latency:    2146.57 ms
Throughput: 1.84 FPS

**Comment by maxlytkin** [comment]
@bianxg 
Yes, you could also provide your input images for more accurate testing with benchmark app.
benchmark_app -m model.xml -i **"_path_to_images_"** -d CPU

What CPU model you use for inferencing? Performance is quite low, however, this might be also related to your model specifics.
You can check and compare performance results you got for your model with mobilenet-v2-pytorch model from Open Model Zoo repository, which might be downloaded and converted to IR through Model Downloader and then Model Converter, as per https://docs.openvinotoolkit.org/latest/omz_tools_downloader_README.html

**Comment by maxlytkin** [comment]
Closing, please re-open if further assistance is needed.
