### ISSUE TITLE
How to update the mkl-dnn from 0.19 to 1.2.1

### ISSUE THREAD

**Issue by xiaoweiChen** [openvinotoolkit/openvino#412]
I compare the mkl-dnn implement preformance. The 0.19 inner_product layer implement by mkldnn is slower 10x than 1.2.1 implement on my PC.
And I know the mkl-dnn rename to dnnl, changed some api names, and add some new features.

So, If I want to update mkl-dnn in openvino, what I should do?

Thanks!

May same as #166

**Comment by banderlog** [comment]
Also, is it possible to update MKL-DNN to DNNL?

**Comment by xiaoweiChen** [comment]
En, before open this issue I try to do this. Just replace the API is fine. But, In MKLPlugin, there are too many code need to change...
And, DNNL add some new features than MKL-DNN, if want to ues new features, may more work need to do...
