### ISSUE TITLE
[Improvement] Install OpenVINO™ toolkit for Raspbian* OS page Face Detection model text formatting issue

### ISSUE THREAD

**Issue by jomoengineer** [openvinotoolkit/openvino#4128]
##### System information (Raspberry Pi 4 - armv7l)

- OpenVINO=> :2021.2
- Operating System / Platform => Raspbian 10 32 Bit
- Compiler => GCC
- Problem classification => Documentation

##### Detailed description

On the Web page "Install OpenVINO™ toolkit for Raspbian* OS" under the heading "Build and Run Object Detection Sample", the text describing how to run the Face Detection model, step 3,  is not formatted properly.  It looks like a partial git comment.

Link to page:
[https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_raspbian.html](url)

**Comment by jgespino** [comment]
Hi @jomoengineer 

Thank you for reporting, I have passed your feedback to the appropriate team to have the documentation updated.

Regards,
Jesus

Ref. 48061

**Comment by jgespino** [comment]
The documentation has been updated as part of the OpenVINO 2021.3 release.
