### ISSUE TITLE
Inference on VPU AI Core X

### ISSUE THREAD

**Issue by lyuzinmaxim** [openvinotoolkit/openvino#4135]
Hi! 

I have the same problem as [here](https://github.com/openvinotoolkit/openvino/issues/1398), i wrote there, but issue is closed, so I write again.

I have [UPSquared Board](https://up-board.org/upsquared/specifications/) with Ubuntu 18.04.5 LTS and [UP AI Core X](https://up-shop.org/up-ai-core-x-series-myriadtmx.html) with one Myriad X, and I'm using OpenVINO 2021.2 (latest version for today)

According to [up-squared forum](https://forum.up-community.org/discussion/comment/10283#Comment_10283) (here people could run VPU like AI Core X olny with flag `-d MYRIAD`) I tried to install dependencies for Neural Stick ([official guide](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#additional-NCS-steps)). 
But I got error "**can not init myriad device nc_error**" when running `sudo ./demo_squeezenet_download_convert_run.sh -d MYRIAD`

Then I tried to use with HDDL ([official guide](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#install-VPU)), but 
run `sudo -E ./demo_squeezenet_download_convert_run.sh -d HDDL` comes to error too: "**HDDL_NOT_INITIALIZED**", **"HDDL hardware initialization failed, exists now"**. 

I checked my procceses with `ps -ef | grep hddl` and there was no _hddldaemon_. I tried to activate it manually with `./hddldaemon` in _/opt/intel/openvino_2021/deployment_tools/inference_engine/external/hddl/bin_, but got error "**error: Failed to start autoboot**"

When AI Core X is connected, `lsusb` gives a _03e7:2485_ device, that is VPU, and green LED on VPU is shining, so I think that is not hardware error.

Could you help me, if You don't mind it

Best regards,
Maxim Lyuzin

**Comment by maxlytkin** [comment]
@lyuzinmaxim 
We recommend to use HDDL plugin with devices such as UP AI Core X.
Have you successfully installed all the dependencies according to https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux_ivad_vpu.html#configuration_steps ?

**Comment by lyuzinmaxim** [comment]
@maxlytkin, 
Hi, 

Yes, i have installed it without any errors (i mean at installation step), but have received errors while running demos, as i wrote. 

Regards
Maxim

**Comment by maxlytkin** [comment]
@lyuzinmaxim 
Can you please run [Hello Query Device Python* Sample](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_ie_bridges_python_sample_hello_query_device_README.html) in order to check if HDDL device appears in the list of devices identified? Specifically, we need a value for VPU_HDDL_DEVICE_NUM line.

Once the HDDL dependencies were installed successfully from running install_IVAD_VPU_dependencies.sh script, you should have seen outputs:
_Install HDDL dependencies successful
Please reboot_

Was that the case?

Also, check if myd_vsc and myd_ion kernel modules are installed by running the following commands, if you do not see any output you may need to reinstall the modules:

```
lsmod | grep myd_vsc
lsmod | grep myd_ion
```

**Comment by lyuzinmaxim** [comment]
@maxlytkin 
Hi again!

Yes, I had that output early:

> Install HDDL dependencies successful
> Please reboot

After Your answer I configured VPU according to official guide again. Before re-configuring and after that, _Hello Query Device Python* Sample_ gives the same things: CPU, GNA and MYRIAD.

When I run 
`lsmod | grep myd_vsc`
I got 
`myd_vsc                20480  0`
and 
`lsmod | grep myd_ion`
gives 
`myd_ion                53248  0`

Than I ran `./demo_security_barrier_camera.sh -d HDDL` and got this error
**[ ERROR ] _client->query(QUERY_TYPE_DEVICE, &query) failed: HDDL_NOT_INITIALIZED
Error on or near line 198; exiting with status 1**

Later I ran that demo with flag _-d MYRIAD_ - it worked fine the first time! 2x faster inference than on CPU! 

I tried to run optimized yolov3-model on my VPU with flag `-h MYRIAD`, but got error: 
`E: [ncAPI] [    350901] [python3] ncDeviceOpen:745	global mutex initialization failed`

But according to [that answer](https://www.intel.com/content/www/us/en/support/articles/000033390/boards-and-kits.html) I deleted in _/tmp_ file _mcnv.mutex_ and all runs now perfectly! With my yolo-v3 model 3x faster than on CPU. 

I want to say, that all this stuff works only with flag `-d MYRIAD`, but You said that recommended is to use `-d HDDL` flag. Could You please explain, where can be my problem with HDDL and what is the main difference between HDDL and MYRIAD using.  

I have attached terminal outputs for HDDL installation steps, HDDL errors and both _Hello Query Device Python* Sample_ outputs.

[install_drivers_output.txt](https://github.com/openvinotoolkit/openvino/files/5920809/install_drivers_output.txt)
[install_IVAD_VPU_dependencies.txt](https://github.com/openvinotoolkit/openvino/files/5920810/install_IVAD_VPU_dependencies.txt)
[hddl_error_running_demo_security_barrier_camera.txt](https://github.com/openvinotoolkit/openvino/files/5920821/hddl_error_running_demo_security_barrier_camera.txt)
[hello_query_device_before_reinstall_VPU_dep.txt](https://github.com/openvinotoolkit/openvino/files/5920833/hello_query_device_before_reinstall_VPU_dep.txt)
[hello_query_device_after_reinstall_VPU_dep.txt](https://github.com/openvinotoolkit/openvino/files/5920835/hello_query_device_after_reinstall_VPU_dep.txt)

Best regards
Lyuzin Maxim

**Comment by maxlytkin** [comment]
@lyuzinmaxim 
We are glad to hear that it works at least with MYRIAD plugin.
As for the HDDL plugin, when you run Hello Query Device sample, what is a value you see for VPU_HDDL_DEVICE_NUM line? It should show the number of active VPU devices.

**Comment by brmarkus** [comment]
One of your provided log-files shows kernel version "5.4.0-64"; you said you have Ubuntu 18.04.5 LTS?
On my Ubuntu 18.04.5 LTS my kernel version is "4.15.0-135", I also see the kernel modules compiled, installed and loaded successfully - and finally I get it working via the HDDL-plugin (via `autoboot` and the `hddldaemon`).

Can you do the following?
$> pidof hddldaemon autoboot
    are those processes running?
    if yes, then terminate them:
$> kill -9 $(pidof hddldaemon autoboot)

If not already done, then setup the environment via `source /opt/intel/openvino/bin/setupvars.sh`.
And initiate a reset via:
$> ${HDDL_INSTALL_DIR}/bin/bsl_reset

Do you see udev-rules under `ll /etc/udev/rules.d/` for HDDL being installed?

**Comment by lyuzinmaxim** [comment]
> @lyuzinmaxim
> We are glad to hear that it works at least with MYRIAD plugin.
> As for the HDDL plugin, when you run Hello Query Device sample, what is a value you see for VPU_HDDL_DEVICE_NUM line? It should show the number of active VPU devices.

Hi! 

I don't see in output of _hello_query_device.py_ anything about HDDL - I see only CPU, GNA and MYRIAD devices - and they don't have _VPU_HDDL_DEVICE_NUM line_ (since this only applies to HDDL device). (output attached)
I would like to know how to get access to X Core with HDDL plugin.

Best regards,
Lyuzin Maxim

[hello_query_device_output.txt](https://github.com/openvinotoolkit/openvino/files/5939201/hello_query_device_output.txt)

**Comment by lyuzinmaxim** [comment]
> One of your provided log-files shows kernel version "5.4.0-64"; you said you have Ubuntu 18.04.5 LTS?
> On my Ubuntu 18.04.5 LTS my kernel version is "4.15.0-135", I also see the kernel modules compiled, installed and loaded successfully - and finally I get it working via the HDDL-plugin (via `autoboot` and the `hddldaemon`).
> 
> Can you do the following?
> $> pidof hddldaemon autoboot
> are those processes running?
> if yes, then terminate them:
> $> kill -9 $(pidof hddldaemon autoboot)
> 
> If not already done, then setup the environment via `source /opt/intel/openvino/bin/setupvars.sh`.
> And initiate a reset via:
> $> ${HDDL_INSTALL_DIR}/bin/bsl_reset
> 
> Do you see udev-rules under `ll /etc/udev/rules.d/` for HDDL being installed?

Hi!
`pidof hddldaemon autoboot` gives no output - it may mean, that there is such process.
`./bsl_reset` gives following output: 
**[E:] [BSL] No device found
[E:] [BSL] No device found
bsl_reset fail for:	BSL_ERROR_NO_DEVICE_FOUND**

And in directory _rules.d_ there are following rules:

**-rw-r--r-- 1 root root 58549 янв 24 18:44 70-snap.snapd.rules
-rw-r--r-- 1 root root   378 дек  9 16:30 97-myriad-usbboot.rules
-rw-r--r-- 1 root root   150 фев  7 17:37 98-hddlbsl.rules
-rw-r--r-- 1 root root    60 дек  9 16:30 99-hddl-ion.rules
-rw-r--r-- 1 root root   100 дек  9 16:30 99-myriad-vsc.rules**

Best regards,
Lyuzin Maxim

**Comment by maxlytkin** [comment]
@lyuzinmaxim 
It is quite odd. Are you using Docker in your configuration? If not, is there any chance you can try this UP AI Core X on a different machine?

**Comment by lyuzinmaxim** [comment]
@maxlytkin 
No, I don't use Docker. 
Now I don't have such an opportunity - but later may be. 
If it will be run with HDDL - I will inform you, thank you!

**Comment by maxlytkin** [comment]
@lyuzinmaxim 
In order to further isolate this bug we would like to understand if it is related to this specific UP AI Core X device or a host machine. That's the reason for why we propose to perform additional testing either with different HDDL device or on a different system.
Once you have any news, please let us know.
Thanks.

**Comment by maxlytkin** [comment]
Closing, please feel free to re-open or start a new issue if additional assistance is needed.
