### ISSUE TITLE
Semantic segmentation in C++ on video

### ISSUE THREAD

**Issue by zpmmehrdad** [openvinotoolkit/openvino#415]
Hi,

Could you please give me an example of semantic segmentation in C++ on video?

Thanks in advance

**Comment by brmarkus** [comment]
Could you start with "https://docs.openvinotoolkit.org/2019_R1/_inference_engine_samples_segmentation_demo_README.html" using the sample `segmentation_demo` and modify the sample to use a loop to run through the frames of a video-file read-in using "cv::VideoCapture()"?

**Comment by zpmmehrdad** [comment]
> Could you start with "https://docs.openvinotoolkit.org/2019_R1/_inference_engine_samples_segmentation_demo_README.html" using the sample `segmentation_demo` and modify the sample to use a loop to run through the frames of a video-file read-in using "cv::VideoCapture()"?

Thanks for the reply, I've compiled it and I'm using it on images but I wanted to know if there might be an example on video. Is there a method that I can use openCV to display the output? Like python example.

**Comment by brmarkus** [comment]
When you look into the Python sample for instance at the end the array `classes_map` gets written into a file via `cv2.imwrite(out_img, classes_map)`.
Can you add a line to just the array via something like `cv2.imshow("segmentation demo", classes_map)`?

**Comment by zpmmehrdad** [comment]
In C++ demo for displaying the result it used "writeOutputBmp(outArrayClasses, C, outFile)" at the end of main.cpp and I'd like to use openCV to do that.

**Comment by ilyachur** [comment]
@zpmmehrdad You can take a look into [open model zoo demos](https://github.com/opencv/open_model_zoo), some demos contain code which works with video.

**Comment by ilyachur** [comment]
I will close the ticket. Feel free to reopen it if you have any questions.
