### ISSUE TITLE
[Bug] OpenVINO master failed to compile on x64 Windows using Visual Studio 2017 toolchain

### ISSUE THREAD

**Issue by dev0x13** [openvinotoolkit/openvino#4155]
##### System information (version)

- OpenVINO => [d681582](https://github.com/openvinotoolkit/openvino/commit/d681582251f8703d0e1f403258e61e2e2bbd91f7)
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017
- Problem classification: Compilation from sources

##### Detailed description

OpenVINO compilation fails with the following error:
```
C:\repo\openvino-master\openvino\ngraph\core\src\op\util\attr_types.cpp(169): error C2039: 'tolower': is not a member of 'std' [C:\repo\openvi
no-master\openvino\build\ngraph\core\ngraph.vcxproj]
```

##### Steps to reproduce

Follow [building for Windows guide](https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows) on Windows 10 64-bit host with Visual Studio 2017.

**Comment by jgespino** [comment]
Hi @dev0x13 

Thanks for reporting and contributing to OpenVINO by creating the pull request!

Regards,
Jesus
