### ISSUE TITLE
infer_request.Infer() is blocked and not return after fork()

### ISSUE THREAD

**Issue by wujpbb7** [openvinotoolkit/openvino#416]
update ./inference-engine/samples/hello_classification/main.cpp, add fork(), infer_request.Infer() will be blocked and not return, why?

`
#include <unistd.h>
#include <sys/wait.h>

...

    try {
        ...
        
        // --------------------------- 7. Do inference --------------------------------------------------------
        
        /* Running the request synchronously */
        if (0 == fork()) {
          std::cerr << "start infer" << std::endl;
          infer_request.Infer(); //会阻塞在这里.
          std::cerr << "finish infer" << std::endl;
          // -----------------------------------------------------------------------------------------------------

          // --------------------------- 8. Process output ------------------------------------------------------
          Blob::Ptr output = infer_request.GetBlob(output_name);
          // Print classification results
          ClassificationResult_t classificationResult(output, {input_image_path});
          classificationResult.print();
          // -----------------------------------------------------------------------------------------------------
        }
        else {
          int stat_val;
          pid_t cpid = wait(&stat_val);
          if (WIFEXITED(stat_val)) { 
            std::cerr << "ok" << std::endl;
          }
          else if (WIFSIGNALED(stat_val)) {
            std::cerr << "PID " << cpid << " exited due to signal " << WTERMSIG(stat_val) << std::endl;            
          } else {
            std::cerr << "PID " << cpid << " exited with unknown status." << std::endl;            
          }
        }
     
        std::cerr << "finish" << std::endl;
        
    } catch (const std::exception & ex) {
        std::cerr << ex.what() << std::endl;
        return EXIT_FAILURE;
    }
`

**Comment by alalek** [comment]
Avoid using `fork()` in threaded applications (almost all, because huge part of libraries is threaded).

Good reading: https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/

**Comment by wujpbb7** [comment]
> Avoid using `fork()` in threaded applications (almost all, because huge part of libraries is threaded).
> 
> Good reading: https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/

thank you for your reply.  
I test fork() because of frvt test, it needs single-threaded mode and parallelized via the fork().
how to use OpenVino under these constraints?

**Comment by ilya-lavrenov** [comment]
@wujpbb7 you need to create executable network object inside the process Where you want to run inference request. Threads are created during executable network objects and are valid in case of fork

**Comment by yang0817manman** [comment]
Hello, have you solved the problems? I have the same problems, can you tell me how to solve it? @wujpbb7

**Comment by wujpbb7** [comment]
> Hello, have you solved the problems? I have the same problems, can you tell me how to solve it? @wujpbb7

use mkldnn directly.

**Comment by zc850134557** [comment]
> > Hello, have you solved the problems? I have the same problems, can you tell me how to solve it? @wujpbb7
> 
> use mkldnn directly.
We also encountered this problem in the frvt competition. Is there any other way to solve it?

**Comment by yang0817manman** [comment]
Thank you very much for your reply. I still have some details and would like to consult you. Did you replace the openvino framework directly with the mkldnn framework in frvt test?  Have you compared the inference speed of the openvino with the mkldnn, the difference?


Looking forward to your reply.Thanks&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 27, 2021 13:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [openvinotoolkit/openvino] infer_request.Infer() is blocked and not return after fork() (#416)




  
Hello, have you solved the problems? I have the same problems, can you tell me how to solve it? @wujpbb7
  
use mkldnn directly.

**Comment by wujpbb7** [comment]
Openvino should call mkldnn, so speed should be almost same under one thread.
I overwrited some layers with mkldnn in caffe, such as 'convolution'、‘batchnorm’、...，it met FRVT‘s requirements.

**Comment by yang0817manman** [comment]
oh，thanks again！



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 30, 2021 18:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [openvinotoolkit/openvino] infer_request.Infer() is blocked and not return after fork() (#416)




 
Openvino should call mkldnn, so speed should be almost same under one thread.
 I overwrited some layers with mkldnn in caffe, such as 'convolution'、‘batchnorm’、...，it met FRVT‘s requirements.

**Comment by sahira-rizvi** [comment]
Closing. Feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
