### ISSUE TITLE
Where to get yolo v3 tiny yml example about accuracy_check?

### ISSUE THREAD

**Issue by lihaofd** [openvinotoolkit/openvino#417]
Hi,
We are testing standard yolo v3 tiny model from darknet(https://github.com/AlexeyAB/darknet) with VOC 2012 on OpenVINO toolkit 2020.1 release

After converting the model to pb and then OpenVINO IR(https://github.com/opencv/dldt/blob/2020/model-optimizer/extensions/front/tf/yolo_v3_tiny.json), 
python mo_tf.py --input_model .\frozen_darknet_yolov3_model.pb --tensorflow_use_custom_operations_config .\yolo_v3_tiny.json --batch 1

it can detect target object successfully by using object_detection_demo_yolov3_async from openvino

But when running accuracy_check, 
accuracy_check -c /home/work/testmodel/yolo_v3_tiny/yolo.yml -td CPU
It always shows 
500 objects processed in 71.299 seconds
map: 1.30%

Below is my script and yml configuration
convert_annotation voc_detection --imageset_file /home/work/VOC/VOCdevkit/VOC2012/ImageSets/Main/train.txt --images_dir /home/work/VOC/VOCdevkit/VOC2012/JPEGImages --annotations_dir /home/work/VOC/VOCdevkit/VOC2012/Annotations/ -ss 500  -o /home/work/testmodel/yolo_v3_tiny/annotations -a yolo_v3_tiny.pickle -m yolo_v3_tiny.json 

my yolo.yml
models:
  - name: yolo
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   /home/work/testmodel/yolo_v3_tiny/FP32/frozen_darknet_yolov3_model.xml
        weights: /home/work/testmodel/yolo_v3_tiny/FP32/frozen_darknet_yolov3_model.bin
        adapter: yolo_v3

    datasets:
      - name: VOC2012
        data_source: /home/work/VOC/VOCdevkit/VOC2012/JPEGImages/
        annotation_conversion:
          converter: voc_detection
          annotations_dir: /home/work/VOC/VOCdevkit/VOC2012/Annotations
          images_dir: /home/work/VOC/VOCdevkit/VOC2012/JPEGImages/
          imageset_file: /home/work/VOC/VOCdevkit/VOC2012/ImageSets/Segmentation/val.txt
        dataset_meta: /home/work/testmodel/yolo_v3_tiny/annotations/yolo_v3_tiny.json
        annotation: /home/work/testmodel/yolo_v3_tiny/annotations/yolo_v3_tiny.pickle
        preprocessing:
          - type: resize
            size: 416
        postprocessing:
          - type: resize_prediction_boxes
          
        metrics:
          - type: map
            ignore_difficult: True
            presenter: print_scalar

I guess there might have sth wrong with my yml configuration? Can anyone be helpful on it?

Thanks!

**Comment by jgespino** [comment]
Hi @lihaofd 

Could you share a link the the exact model you are using? Looking at that repository, I'm only seeing Yolo V3 models that have been trained with COCO dataset.

Regards,
Jesus

**Comment by lihaofd** [comment]
https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3-tiny.cfg
https://pjreddie.com/media/files/yolov3-tiny.weights

Seems it is based on COCO. I am trying to download COCO dataset but network is very slow now.
Is below setup correct for yolo v3 tiny accuracy_check? Or any example? It is very helpful to run POT calibration etc.  Thanks!

preprocessing:

type: resize
size: 416
postprocessing:
type: resize_prediction_boxes

**Comment by lihaofd** [comment]
@jgespino , any new update? could you help on this issue? Thanks!

**Comment by jgespino** [comment]
Hi @lihaofd 

I tested and also had a fail at 65%. Not sure if the person_keypoints_val2014.json is the correct file as the YoloV3 has 80 classes. I am going to try going though the process with my custom trained Tiny YoloV3 model. I will let you know what I find out. 

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @lihaofd 

Apologies for the long delay. I'm not sure if you are still seeing this issue with the latest OpenVINO 2020.4 release.
If you are, feel free to re-open this issue or start a new discussion.

Regards,
Jesus
