### ISSUE TITLE
[Bug]2021.2 version OpenCL GPU load error

### ISSUE THREAD

**Issue by janicevidal** [openvinotoolkit/openvino#4176]
##### Detailed description

executableNetwork = ie.LoadNetwork(network, "GPU", config);

error:
[ ERROR ] clGetExtensionFunctionAddressForPlatform(clHostMemAllocINTEL) returned NULL.
![image](https://user-images.githubusercontent.com/29887681/106836860-e2da7680-66d4-11eb-86e0-7f51f7f7c998.png)

2020.4 version susscuss, but 2021.2 fail

**Comment by vladimir-paramuzov** [comment]
@janicevidal 
The issue might be related to OpenCL runtime: it reports that unified_shared_memory extension is supported on your device, but `clHostMemAllocINTEL` function is not available. What OCL runtime version do you use? Could you try another version?

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
