### ISSUE TITLE
multistick plugin doesn't working on face_recognition_demo.py 

### ISSUE THREAD

**Issue by glennford49** [openvinotoolkit/openvino#4179]
Good day to all,
I have successfully run face_recognition_demo.py on my notebook using ncs2, I have achieved 11FPS on a single stick and decided to double its FPS to achieve real time detection.However using 2 NCS2, 
with "MULTI:MYRIAD.3.2.3-ma2480,MYRIAD.3.2.4-ma2480" as my default device doesn't do any significant increase of my FPS.
I have only added a single line  on face_recognition_demo.py with
multMyriad ="MULTI:MYRIAD.3.2.3-ma2480,MYRIAD.3.2.4-ma2480"
and changing all the default "CPU" to multMyriad
Did I missed something in here?
O.S = ubuntu 20.14
openvino env = openvino 2021.2.185
demo = face_recognition_demo.py

Same issues on my raspberrypi
O.S = raspian buster (32bit)
openvino env = openvino 2020.4
demo = face_recognition_demo.py
Any idea on this?

**Comment by ilya-lavrenov** [comment]
Hi,

Performance improvements of `MULTI` device usage depend on the application: for latency oriented pipelines MULTI does not improve performance (since 2 devices don't execute the same request), but for throughput oriented - it does (when 2 devices execute 2 different requests and general speed-up 2x) and it should speed-up the app twice in case of 2 MYRIAD sticks usage.

So, you need to understand whether this app is latency or throughput oriented.

**Comment by glennford49** [comment]
I want to use it as what you have said the throughput oriented but I dont know how to implement it, as for the MULTI documentations, I think have followed it.

**Comment by jgespino** [comment]
Hi @glennford49 

Please use the [Benchmark Python Tool](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_benchmark_tool_README.html) to measure performance, you can use synchronous mode for latency-oriented or asynchronous model for throughput-oriented.

Regards,
Jesus

**Comment by glennford49** [comment]
I have this specific question, Does multMyriad ="MULTI:MYRIAD.3.2.3-ma2480,MYRIAD.3.2.4-ma2480 wont work unless I have changed some code like requests? I am only after of throughput oriented as the first comment said it can double the FPS when using 2 ncs2 sticks.

**Comment by brmarkus** [comment]
You might want to experiment with samples&demos supporting the use of asynchronous infer-requests, like `classification_sample_async`, `object_detection_demo_ssd_async` or e.g. `object_detection_demo_yolov3_async` - or have a look into the mentioned "Benchmark Python Tool".
So while you have started an asynchronous infer-request (and the call will return immediately) you could create another request immediately. Those two independent requests in this case will be executed in parallel.

It really depends on the use-case.
With a e.g. realtime camera-feed there might not be a benefit (if doing inference on one frame using one NCS2 device takes (almost) as long as the camera could provide a new frame).
But e.g. when processing a huge number of pictures (or e.g. audio-samples or whatever other data you want to feed into the NeuralNetwork) then the processing could be load-balanced on all the given devices to the multi-device plugin.
