### ISSUE TITLE
Inference Engine Initialization

### ISSUE THREAD

**Issue by catastrophe22** [openvinotoolkit/openvino#418]
Hi! I noticed that the part "Loading the Model to the Device" takes up a lot of time. I need to perform series of inference requests so I am trying to initialize the model once. Is there a way to save the values? (For example: ExecutableNetwork network)

**Comment by ArtemSkrebkov** [comment]
It would be nice to have more details to answer your question. Which device do you use?

**Comment by catastrophe22** [comment]
I am currently using CPU as the device but I was also able to use a MYRIAD plugin to use the Export() function and ImportNetwork(). However, I would prefer to use the CPU. Also, there are still other values that I need to save since these are needed by the Inference part.

**Comment by brmarkus** [comment]
Not sure I understand what you want to achieve...
Do you mean to "serialize" the instance of the InferengeEngine and store it (in a file) - like it is possible with e.g. a Java object instance - and then just load it (deserialize) again, including to load models, restore runtime-config options and something like this?

**Comment by monamacadaeg** [comment]
Yes. I want to save and store these things in a file (or memory if possible) so I will just need to run the initialization part once and not every time that I want to do inference. The problem is that I can't seem to find any implementations on how to store these.

**Comment by catastrophe22** [comment]
Yes. I want to save and store these things in a file (or memory if possible) so I will just need to run the initialization part once and not every time that I want to do inference. Now, I can't seem to find any implementations on how to store these.

**Comment by ilya-lavrenov** [comment]
@catastrophe22 such feature is not implemented yet for CPU plugin. It is not easy to do, but it’s planned

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
