### ISSUE TITLE
[Bug] Select Operation: CPU plugin needs input0 boolean, GPU plugin needs u16/u32

### ISSUE THREAD

**Issue by ts-accessio** [openvinotoolkit/openvino#4203]
##### System information (version)
- OpenVINO=> 2021.2
- Operating System / Platform => Ubuntu 20.04
- Compiler => gcc
- Problem classification => GPU operation problem 

##### Detailed description
The select operation:
In https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/src/op/select.cpp#L49
Argument 0 must have boolean element type

However no GPU kernel can be found. 
The select function of OpenCL does not take boolean and also in the clDNNPlugin it seems to take no boolean: https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/select/select_kernel_ref.cpp#L23

So i guess it's broken? Or is there a trick to get it running?

The layer in our model:
```
<layer id="504" name="pre/select" precision="FP32" type="Select" version="opset1">
      <input>
        <port id="0">
          <dim>1</dim>
          <dim>1</dim>
          <dim>384</dim>
          <dim>384</dim>
        </port>
        <port id="1">
          <dim>1</dim>
          <dim>1</dim>
          <dim>384</dim>
          <dim>384</dim>
        </port>
        <port id="2">
          <dim>1</dim>
          <dim>1</dim>
          <dim>384</dim>
          <dim>384</dim>
        </port>
      </input>
      <output>
        <port id="3" precision="FP32">
          <dim>1</dim>
          <dim>1</dim>
          <dim>384</dim>
          <dim>384</dim>
        </port>
      </output>
    </layer>
```

**Comment by ilya-lavrenov** [comment]
CC @vladimir-paramuzov

**Comment by vladimir-paramuzov** [comment]
@ts-accessio Boolean type in ngraph is [8-bit integer](https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/src/type/element_type.cpp#L70), so the gpu plugin just  [uses](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/cldnn_engine/cldnn_common_utils.h#L73) i8 data type to represent boolean values. There is a [functional test](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/shared_test_classes/src/single_layer/select.cpp#L32) which creates Select operation with boolean input and the [gpu instance](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/select.cpp) works fine. 

So if the gpu plugin can't find suitable kernel for the Select operation, it's unlikely connected with boolean data type. Could you confirm that you see an error for this operation in your model? If yes, could you please attach runnable IR or any guide with steps to reproduce the issue?

**Comment by ts-accessio** [comment]
Datatypes are working fine, however there is a problem if the Select operation is followed by a Convolution with Padding. See [https://github.com/openvinotoolkit/openvino/issues/4356](https://github.com/openvinotoolkit/openvino/issues/4356)
