### ISSUE TITLE
VPU backend overwrites first channel of every input's shape with 1

### ISSUE THREAD

**Issue by litherum** [openvinotoolkit/openvino#421]
`vpu::FrontEnd::detectNetworkBatch()` has:

```C++
   for (const auto& p : inputsInfo) {
        ...
        auto ieShapes = ieData->getTensorDesc().getDims();
        ...
        switch (ieData->getLayout()) {
        case ie::Layout::NCDHW:
        case ie::Layout::NDHWC:
        case ie::Layout::NCHW:
        case ie::Layout::NHWC:
        case ie::Layout::NC:
        case ie::Layout::CN:
            ieShapes[0] = 1;
            break;
        default:
            VPU_THROW_FORMAT("Input %v has unexpected layout %v", ieData->getName(), ieData->getLayout());
        }

        inputShapes[ieData->getName()] = ieShapes;
    }
```

Having a batch size of ≠ 1 seems like a reasonable thing for a model to do, so it's confusing why the vpu backend overwrites it to 1. The other backends don't seem to do this.

**Comment by jgespino** [comment]
Hi @litherum 

The reason why it's overwritten to size 1 is because the VPU plugin only supports batch size 1. Currently dynamic batching is only supported on CPU and GPU Plugins. You can find additional information in the documentation [here](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_DynamicBatching.html).

Regards,
Jesus

**Comment by litherum** [comment]
Perhaps it should cause a compilation failure then, instead of silently only performing part of the requested calculation.

**Comment by ilya-lavrenov** [comment]
@litherum VPU plug-in set batch size to 1, but it still iterates over batch dimension in an external loop, so batch value is not ignored

**Comment by sahira-rizvi** [comment]
Closing. Feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
