### ISSUE TITLE
Multiple issues with install target

### ISSUE THREAD

**Issue by alokpr** [openvinotoolkit/openvino#423]
Building with -DENABLE_SAMPLES=OFF and installing results in this error:
CMake Error at inference-engine/cmake_install.cmake:57 (file):
  file INSTALL cannot find "/sample".
Call Stack (most recent call first):
  cmake_install.cmake:43 (include)

I tried to avoid the error by only installing the "core" component but ran into another error:
$ cmake -DCOMPONENT=core -P cmake_install.cmake
-- Installing: usr/local/deployment_tools/inference_engine/share/ie_parallel.cmake
CMake Error at inference-engine/src/inference_engine/cmake_install.cmake:97 (file):
  file INSTALL cannot find
  "/home/alok/src/dldt/build/share/ie_rh_decoder.cmake".
Call Stack (most recent call first):
  inference-engine/src/cmake_install.cmake:46 (include)
  inference-engine/cmake_install.cmake:63 (include)
  cmake_install.cmake:43 (include)

Oh and BTW, even with ENABLE_SAMPLES=OFF, dldt still builds a portion of samples.

**Comment by alokpr** [comment]
I actually get the "file INSTALL cannot find "/sample"" even after I build the samples. It looks like nobody has actually tried building and installing the opensource version of dldt.

**Comment by asuhov** [comment]
Hello, thank you for reporting these issues. Cmake install target is not supported yet. We will improve it in the future releases.

**Comment by alokpr** [comment]
Thanks for your response. How do people currently install build artifacts?

**Comment by jgespino** [comment]
Hi @alokpr 

After building dldt you can use the build artifacts by exporting some environment variables, see below. By the way, I am using an Intel NUC with Ubuntu 18.04. Could you share additional details about your setup?

**For Python**, assuming you built with `-DPYTHON=ON`:
`export PYTHONPATH=$PYTHONPATH:<dldt_dir>/bin/intel64/Release/lib/python_api/python<version>`
example: `export PYTHONPATH=$PYTHONPATH:/home/jesus/dldt/bin/intel64/Release/lib/python_api/python3.6`
**For C++**:
`export InferenceEngine_DIR=<dldt_dir>/build/`
example: `export InferenceEngine_DIR=/home/jesus/dldt/build/`

Using CMake to build the application, you can use the following to find the packages, include directory and link libraries.
`find_package(InferenceEngine)
include_directories(${InferenceEngine_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} ${InferenceEngine_LIBRARIES} dl)`

Using `-DENABLE_SAMPLES=OFF`, the samples are not built for me. When building with samples on, the samples are placed in <dldt_dir>/bin/intel64/Release directory. There are a couple of binaries that are build but are not part of the samples such as compile_tool, myriad_compile, myriad_perfcheck, unit-test and vpu_profile.

Regards,
Jesus

**Comment by alokpr** [comment]
Hi Jesus,

Thanks for your response. Yes, I have been using the same workaround you suggest here but it is a bit annoying that the canonical way of making and installing dev packages does not work. Ideally the following workflow should work:

1. git clone
2. cmake dldt -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
3. make install
4. find_package(InferenceEngine) just works for any project without having to set any environment variable

Is there a particular reason for the "standard" way of making/installing a library package is not supported for dldt?

**Comment by jgespino** [comment]
Hi @alokpr 

I understand, currently the workflow is as described in my previous response. As @asuhov mentioned the development team is already looking into improving the build process in a future release.

Regards,
Jesus

**Comment by ilya-lavrenov** [comment]
@alokpr 

Installation of `ie_rh_decoder.cmake` is removed now (see https://github.com/openvinotoolkit/openvino/commit/a347375d0188b58056887f382161c6ed6fc3dcb3)

> even with ENABLE_SAMPLES=OFF, dldt still builds a portion of samples

It's done intentionally to build `gflags` since it's also needed for tools.

If you still experience any issues with `make install`, please, file a separate issue. Thanks!
