### ISSUE TITLE
dldt forces ngraph submodule

### ISSUE THREAD

**Issue by alokpr** [openvinotoolkit/openvino#424]
dldt forces ngraph from the submodule:
https://github.com/opencv/dldt/blob/2020/inference-engine/CMakeLists.txt#L26

The idiomatic cmake way of using an external library is to first find_package and fallback to building a local copy only if find_package fails.

**Comment by jgespino** [comment]
Hi @alokpr 

Thank you for bringing this to our attention. I will provide your feedback to the development team to improve the build process.

Regards,
Jesus

**Comment by lazarevevgeny** [comment]
Now OpenVINO comes with ngraph as not a submodule but a copy of the repository. You should not try use your own version of ngraph anymore.

**Comment by ilyachur** [comment]
The original issue was fixed for 2020.2 OpenVINO release.
https://github.com/openvinotoolkit/openvino/blob/2020/inference-engine/CMakeLists.txt#L28
