### ISSUE TITLE
Build artifacts are produced into CMAKE_SOURCE_DIR/bin

### ISSUE THREAD

**Issue by alokpr** [openvinotoolkit/openvino#425]
Even when building out of source directory, build artifacts are produced in the source directory.

**Comment by jgespino** [comment]
Hi @alokpr 

This may be the default behavior as I can see the following in the cmake output:
```
-- [clDNN] Output bin directory:
-- [clDNN]  - "/home/jesus/dldt/bin/intel64/Release"
-- [clDNN] Output lib directory:
-- [clDNN]  - "/home/jesus/dldt/bin/intel64/Release/lib"
```
I will take a look and see if there is a way to change this.

Regards,
Jesus

**Comment by ilyachur** [comment]
Hi @alokpr,

This is a default behaviour of the OpenVINO build infrastructure.
If you want to change the output path for binaries, you can use the cmake variable: `OUTPUT_ROOT`

Can it solve your issue?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
