### ISSUE TITLE
Cannot make install dldt

### ISSUE THREAD

**Issue by vk1z** [openvinotoolkit/openvino#426]
Building in a docker container on Ubuntu 18.04. 
==
FROM ubuntu:18.04
USER root
WORKDIR /
ARG DEPENDENCIES="autoconf \
	automake \
	build-essential \
	cmake \
	cpio \
	curl \
	gnupg2 \
	libdrm2 \
	libglib2.0-0 \
	lsb-release \
	libgtk-3-0 \
	libtool \
	python3-pip \
	udev \
	git   \
	unzip \
        sudo \
        wget"
RUN apt-get update && \
    apt-get install -y --no-install-recommends ${DEPENDENCIES} && \
    rm -rf /var/lib/apt/lists/*
RUN git clone --recursive https://github.com/opencv/dldt.git
WORKDIR /dldt
RUN  git submodule update --init --recursive && mkdir /tmp/neo
WORKDIR /tmp/neo
RUN wget https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-gmmlib_19.3.2_amd64.deb && \
wget https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-igc-core_1.0.2597_amd64.deb && \
wget https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-igc-opencl_1.0.2597_amd64.deb && \
wget https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-opencl_19.41.14441_amd64.deb && \
wget https://github.com/intel/compute-runtime/releases/download/19.41.14441/intel-ocloc_19.41.14441_amd64.deb && \
/usr/bin/dpkg -i *.deb
WORKDIR /dldt
RUN rm -rf /tmp/neo && chmod +x ./install_dependencies.sh && ./install_dependencies.sh && mkdir ./build
WORKDIR /dldt/build
RUN cmake -DCMAKE_BUILD_TYPE=Release ..
RUN make && make install
==
CMake Error at inference-engine/src/inference_engine/cmake_install.cmake:97 (file):
  file INSTALL cannot find "/dldt/build/share/ie_rh_decoder.cmake".
Call Stack (most recent call first):
  inference-engine/src/cmake_install.cmake:48 (include)
  inference-engine/cmake_install.cmake:75 (include)
  cmake_install.cmake:43 (include)

Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1
==
I can proceed by deleting the offending cmake file, but I have no idea what functionality that affects

**Comment by vk1z** [comment]
Please excuse the large caps. Entirely accidental when copy-pasting

**Comment by asuhov** [comment]
Hello, I've committed a fix for this particular error to 2020 branch. But please note that make "install" target is not supported yet and it's recommended to copy built IE binaries and dependencies by a separate shell command.

**Comment by vk1z** [comment]
Hello Alexey,
Thanks for the reply. I am a bit confused about this. Specifically:
1) Which binaries do I copy and if so, why couldn't said command be part of the cmake file.
2) If you don't support the install target, how does the Ubuntu package get built? I've built quite a few before myself and typically they are preceded by a make install on the build machine (after chrooting - legacy or docker, today). Isn't this how build your dpkgs?

Also, are the gmmlib, igc and opencl packages opensourced or are they not? Namely can we build them as part of CI/CD?

**Comment by asuhov** [comment]
Binary dependencies for different IE plugins are described in the table at  https://docs.openvinotoolkit.org/2020.1/_docs_IE_DG_inference_engine_intro.html page, you have to copy these files into your install folder.

Currently we generate the packages using custom shell scripts and we are going to migrate to the "make install" solution later.

**Comment by ilyachur** [comment]
@ilya-lavrenov FYI

**Comment by ilya-lavrenov** [comment]
Installation of this file is removed. See https://github.com/openvinotoolkit/openvino/commit/a347375d0188b58056887f382161c6ed6fc3dcb3
