### ISSUE TITLE
Question: how can I get the name of the input and output nodes?

### ISSUE THREAD

**Issue by zilion22** [openvinotoolkit/openvino#429]
Hi All,
This is not a bug but an issue with my usecase.
I find it very difficult to figure out what it the input and output nodes are converted to from the tensorflow node names, not to mention the original keras node names.
Is there any systematic way of getting it now?
I have written an xml reader but it is very fragile and very dependent of OpenVino version, so I'd rather not advertise it.
Many thanks,
Lev

**Comment by leavim** [comment]
Hi @zilion22 ,
You can use the Inference Engine API to get the input/output information of your IR files, similar to whats explained [here ](https://docs.openvinotoolkit.org/2018_R5/_ie_bridges_python_docs_api_overview.html#inputinfo-class), which I assume your xml reader is already using.

You can also try to get the input/output layer names of the .pb, you could do something similar to what user suggested [here](https://stackoverflow.com/questions/43517959/given-a-tensor-flow-model-graph-how-to-find-the-input-node-and-output-node-name). I'm sure a simple script could be written to expedite the functionality.

Finally you could also use [Netron ](https://github.com/lutzroeder/netron) for visualization of models, very handy tool available. 

Regards,
Luis
