### ISSUE TITLE
Full source code of face beautification algorithm tutorial

### ISSUE THREAD

**Issue by thmatuza** [openvinotoolkit/openvino#4295]
##### Detailed description
Thank you for the document [Implementing a face beautification algorithm with G-API ](https://docs.opencv.org/master/d4/d48/tutorial_gapi_face_beautification.html). It is very helpful to understand how face beautification algorithm works.
I just wonder if there are full source code of the tutorial available.
I would like to try it and see the detail of implementation for each custom functions.

**Comment by avitial** [comment]
@thmatuza not sure if source code of this tutorial is available at the moment and/or if it will be at some point, the Graph API is actively being developed. The API is volatile at the moment and there may be minor but compatibility-breaking changes in the future.


~Luis

**Comment by alalek** [comment]
G-API tutorials code is here: https://github.com/opencv/opencv/tree/master/samples/cpp/tutorial_code/gapi
Other G-API samples: https://github.com/opencv/opencv/tree/master/modules/gapi/samples

/cc @dmatveev

**Comment by thmatuza** [comment]
> G-API tutorials code is here: https://github.com/opencv/opencv/tree/master/samples/cpp/tutorial_code/gapi
> Other G-API samples: https://github.com/opencv/opencv/tree/master/modules/gapi/samples
> 
> /cc @dmatveev

Thank you!

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
