### ISSUE TITLE
need support read model file (.onnx) from buffer

### ISSUE THREAD

**Issue by anhtu812** [openvinotoolkit/openvino#4304]
Because I use my encrypt. If i use "ngraph::onnx_import::import_onnx_model(resnet50_stream);" then code change very much. Please.

**Comment by ilyachur** [comment]
Hi @anhtu812,

At the current moment we support to read ONNX model from buffer.
You need to read model to string and after that use this string as a parameter of `ReadNetwork`.
You can find example here: https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/inference_engine/onnx_reader/onnx_reader.cpp#L114

**Comment by anhtu812** [comment]
Thanks @ilyachur.
