### ISSUE TITLE
How to get feature data with sepcific shape from audio file (.wav) for ASR sample?

### ISSUE THREAD

**Issue by mingmingtasd** [openvinotoolkit/openvino#431]
Hi, for the [ASR sample](https://docs.openvinotoolkit.org/latest/_inference_engine_samples_speech_sample_README.html) , I want to know how to convert the audio data in .wav file to the feature data in .ark file? And for matching the [models ](https://download.01.org/openvinotoolkit/models_contrib/speech/kaldi/)input shape, how to get the feature data with sepcific matrix shape (rows*columns)? Please help me, thanks！

**Comment by brmarkus** [comment]
With respect to the ARK file, please check KALDI resources, like "https://kaldi-asr.org/doc/data_prep.html#data_prep_data_yourself".

**Comment by mingmingtasd** [comment]
OK, I will look into it, thanks!

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
