### ISSUE TITLE
GPU plugin memory usage increase

### ISSUE THREAD

**Issue by 4shome** [openvinotoolkit/openvino#432]
I found that the GPU plugin has been using more and more memory with recent releases:
- 2019_R1.1 256MB (including my application's own usage)
- 2019_R2 329MB
- 2019_R3 352MB
Is this expected?
The CPU plugin is pretty stable though, always around 122MB.

The code is here: https://github.com/YijinLiu/tf-cpu/blob/master/benchmark/obj_detect_dldt.cc

**Comment by leavim** [comment]
Hi @4shome ,

Thanks for reaching out.  It's a significant memory usage increase if you compare your results between 2019_R1.1 and 2019_R3. Do you also see this memory usage increase on newer releases, specifically on 2020.1 and 2020.2?

Regards,
Luis

**Comment by mmx110** [comment]
> Hi @4shome ,
> 
> Thanks for reaching out. It's a significant memory usage increase if you compare your results between 2019_R1.1 and 2019_R3. Do you also see this memory usage increase on newer releases, specifically on 2020.1 and 2020.2?
> 
> Regards,
> Luis

I use 2020.2.120, more 10% memory increase. meanwhile if I create and relese circularly, the memory increased continuely.
`#include <string>
#include <inference_engine.hpp>

using namespace InferenceEngine;
using namespace std;
using namespace cv;
class WrapInferenc
{
public:
	WrapInferenc(string model, string weight, string device):model_(model), weight_(weight),device_(device){};
	~WrapInferenc();
	Core ie;
	CNNNetwork network ;
	InputInfo::Ptr input_info;
	InferRequest infer_request;
	ExecutableNetwork executable_network;

	void ExecInfer(const Mat img);
private:
	Blob::Ptr wrapMat2Blob(const cv::Mat &mat);
	string model_;
	string weight_;
	string device_;
}

void WrapInferenc::ExecInfer(const Mat image)
{
   try{
		network = ie.ReadNetwork(model_, weight_);
		network.setBatchSize(1);

		InputInfo::Ptr input_info = network.getInputsInfo().begin()->second;
		std::string input_name = network.getInputsInfo().begin()->first;
		input_info->getPreProcess().setResizeAlgorithm(RESIZE_BILINEAR);
		input_info->setLayout(Layout::NHWC);
		input_info->setPrecision(Precision::U8);

		DataPtr output_info = network.getOutputsInfo().begin()->second;
		std::string output_name = network.getOutputsInfo().begin()->first;
		output_info->setPrecision(Precision::FP32);

		executable_network = ie.LoadNetwork(network, device_);
		infer_request = executable_network.CreateInferRequest();

		Blob::Ptr imgBlob = wrapMat2Blob(image);
		infer_request.SetBlob(input_name, imgBlob);

		infer_request.Infer();

		Blob::Ptr output = infer_request.GetBlob(output_name);
	} catch (const std::exception & ex) {
		std::cerr << ex.what() << std::endl;
		return EXIT_FAILURE;
	}
}
Blob::Ptr WrapInferenc::wrapMat2Blob(const cv::Mat &mat)
{
	size_t channels = mat.channels();
	size_t height = mat.size().height;
	size_t width = mat.size().width;

	size_t strideH = mat.step.buf[0];
	size_t strideW = mat.step.buf[1];

	bool is_dense =
		strideW == channels &&
		strideH == channels * width;

	if (!is_dense) THROW_IE_EXCEPTION
		<< "Doesn't support conversion from not dense cv::Mat";

	InferenceEngine::TensorDesc tDesc(InferenceEngine::Precision::U8,
	{1, channels, height, width},
	InferenceEngine::Layout::NHWC);

	return InferenceEngine::make_shared_blob<uint8_t>(tDesc, mat.data);
}



int main()
{
	
	Mat img = imread("test.jpg");
	while (true)
	{
		WrapInferenc* infer = new WrapInferenc("model.xml", "model.bin", "GPU");
		infer->ExecInfer(img);
		delete infer;
	}
}`

**Comment by sahira-rizvi** [comment]
Closing. Feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
