### ISSUE TITLE
Please make this easier to install.

### ISSUE THREAD

**Issue by Tylersuard** [openvinotoolkit/openvino#4323]
Current installation process:
download openvino toolkit 
set up environment
install 
optimize models

I can't get this to work and I'm not sure where it is failing.  Please do a "pip install" feature that just takes care of everything and sets up environment variables.

This is really frustrating.

Also, the paths on this documentation need to be updated:
https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_windows.html

**Comment by brmarkus** [comment]
Can you provide more details about what has failed? What's the situation and behavior now? Which version of OpenVINO have you installed, to which machine (type, operating system), what were the steps you did?

**Comment by ilya-lavrenov** [comment]
CC @mryzhov

**Comment by mryzhov** [comment]
both openvino and openvino-dev wheel packages will be available in 2021.3 release,  they should fix these issues

**Comment by andrew-zaytsev** [comment]
@Tylersuard could you please point to the outdated paths in the installation guide so we can quickly fix them? https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_windows.html

**Comment by jgespino** [comment]
Python wheel packages are now available with OpenVINO 2021.3 release.
