### ISSUE TITLE
Change input shape of SSD w/o reloading network

### ISSUE THREAD

**Issue by YijinLiu** [openvinotoolkit/openvino#433]
Currently, if I need to change the input shape of an SSD network, I have to call CNNNetwork::reshape, followed by Core::LoadNetwork to get a new ExecutableNetwork. The second method is pretty slow, especially w/ GPU plugin.
Is it possible that we can avoid the cost by adding a new method like ExecutableNetwork::reshape?

**Comment by jgespino** [comment]
Hi @YijinLiu 

The OpenVINO toolkit 2020.1 release includes a couple of experimental methods that may be what you are looking for. Take a look at the [Using Static Shape Infer Feature](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_ShapeInference.html) documentation.

Regards,
Jesus

**Comment by YijinLiu** [comment]
@jgespino IIUC, isn't it reshape I mentioned initially?
IIUC, it's not new and super slow because calling LoadNetwork is needed after it.

**Comment by sahira-rizvi** [comment]
Closing. Feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
