### ISSUE TITLE
Does openvino currently support yolov1?

### ISSUE THREAD

**Issue by alixiu** [openvinotoolkit/openvino#4352]
I cannot find yolov1 model in openvinotoolkit/open_model_zoo/models/public, 
so I generate a tensorflow model `yolov1_frozen_graph.pb` with `https://github.com/Robinatp/YOLO_Tensorflow/tree/master/YOLO_V1/YOLOv1-Tensorflow-detect-export`. 
Then run `python3 $OPENVINO_HOME/model_optimizer/mo_tf.py 
 --input_shape=[448,448,3] 
 --input=input 
 --transformations_config=$mo_dir/extensions/front/tf/yolo_v1.json 
 --input_model=yolov1_frozen_graph.pb 
 `，
**generating error:**
`Model Optimizer version: 	2021.2.0-1877-176bdf51370-releases/2021/2
[ ERROR ]  Cannot infer shapes or values for node "detected_boxes/YoloRegion".
[ ERROR ]  'mask'
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function RegionYoloOp.regionyolo_infer at 0xa3b5b3ae8>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "detected_boxes/YoloRegion" node. `

**Comment by lazarevevgeny** [comment]
@taka-no-me, @abotsiev, please, take a look.

**Comment by jgespino** [comment]
Per [VPU documentation](https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_VPU.html#doxid-openvino-docs-o-v-u-g-supported-plugins-v-p-u), OpenVINO does not support YOLO v1 on NCS 2.
> TensorFlow*:
> - Yolo family (yolo-v2, yolo-v3, tiny-yolo-v1, tiny-yolo-v2, tiny-yolo-v3)
