### ISSUE TITLE
[Bug] Select operation cannot be followed by Padding on GPU

### ISSUE THREAD

**Issue by ts-accessio** [openvinotoolkit/openvino#4356]
##### System information (version)
- OpenVINO=> 2021.2
- Operating System / Platform => Ubuntu 20.04

##### Detailed description
When having a convolution operation with padding after a Select layer, we get the following error when running on GPU (but not on CPU):
> terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Error has occured for: select:Where_11
Best_kernel.empty()(true) should be false
Cannot find a proper kernel with this arguments
However padding before the Select operation works fine.

Parameter string of select layer:

>SELECT_m0_n0_NONE_INT8_BFYX_d0_v384_p1_0_0_d1_v384_p384_0_0_d2_v1_p147456_0_0_d3_v1_p147456_0_0__F32_BFYX_d0_v384_p1_0_0_d1_v384_p384_0_0_d2_v1_p147456_0_0_d3_v1_p147456_0_0__F32_BFYX_d0_v384_p1_0_0_d1_v384_p384_0_0_d2_v1_p147456_0_0_d3_v1_p147456_0_0__F32_BFYX_d0_v384_p1_1_0_d1_v384_p385_1_0_d2_v1_p148225_0_0_d3_v1_p148225_0_0_

Printing the parameters checked here: https://github.com/openvinotoolkit/openvino/blob/22169a05b9fdf45a9bbebf22de366728f99e78ef/inference-engine/thirdparty/clDNN/kernel_selector/core/kernel_selector_params.cpp#L421 (in form \<fieldname\> \<value from key.restrict\> \<value from k.key.restrict\>)

> different_types 1 1
different_input_weights_types 0 0
offset 0 1
pitches 0 1
batching 1 0
biasPerFeatureMap 0 0
biasPerOutput 0 0
nonBias 0 0
activationAdditionalParamsAsInput 0 0
FP16Emulation 0 0
momentum 0 0
quantization 0 0
sym_quantization 0 0
asym_w_quantization 0 0
asym_d_quantization 0 0

##### Steps to reproduce
[data.tar.gz](https://github.com/openvinotoolkit/openvino/files/5987371/data.tar.gz)
Here are 4 test models (generated from pytorch using the model optimizer), each with the corresponding pytorch model + a conversion example script
Minimal: with padding in convolution after select -> does not work
Minimal2: same model, but no padding -> works
Minimal3: separate padding after select in pytorch -> does not work
Minimal4: padding before select -> works

Testing was done using the benchmark_app sample

**Comment by avitial** [comment]
CC @vladimir-paramuzov @Lyamin-Roman

**Comment by Lyamin-Roman** [comment]
Not reproduced on master
