### ISSUE TITLE
OpenVINO 2020.1 installation artifacts

### ISSUE THREAD

**Issue by h6197627** [openvinotoolkit/openvino#437]
Couple buggy artifacts:

1. OpenVINO 2020.1 (and all previous releases) officially provided distribution for Ubuntu 18.04 installs **.scripts** folder with packages from Intel Media SDK into root directory:

> ls /.scripts
> POSTIN.intel-openvino-mediasdk-2020.1-023.x86_64.rpm  SUMMARY.intel-openvino-mediasdk-2020.1-023.x86_64.rpm

I guess the right place should be /opt/intel/.scripts

2. OpenVINO 2020.1 officially provided distribution (intel-openvino-mediasdk-2020.1-023.x86_64.rpm package) for Ubuntu 18.04 installs **/etc/ld.so.conf.d/intel-mdf.conf** file for making libraries placed in **/opt/intel/common/mdf** globally accessible.
However, starting from 2020.1 /opt/intel/common/mdf is not provided anymore. Either it was mistakenly excluded from distribution, either **/etc/ld.so.conf.d/intel-mdf.conf** file was forgotten to be deleted together with MDF.

**Comment by leavim** [comment]
Hi @h6197627 , 
thanks for reporting this. We have passed this info to the dev team to investigate.

**Comment by ilya-lavrenov** [comment]
@artanokhov @asuhov could you please comment?

**Comment by h6197627** [comment]
Unfortunately the problem still there in 2020.3 LTS

**Comment by h6197627** [comment]
Still there in 2020.4

**Comment by h6197627** [comment]
Unfortunately still there in 2021.1

**Comment by ilya-lavrenov** [comment]
@artanokhov @asuhov could you please comment?

**Comment by h6197627** [comment]
Unfortunately still there in 2021.2

**Comment by h6197627** [comment]
Unfortunately still there in 2021.3

**Comment by h6197627** [comment]
Closing due to:

> Starting with the Intel® Distribution of OpenVINO™ toolkit 2021.3 release, Intel® Media SDK is being deprecated for removal in October 2021.
