### ISSUE TITLE
[Bug] Error while building MKLDNNplugin with Xcode

### ISSUE THREAD

**Issue by Drizshko** [openvinotoolkit/openvino#4374]
##### System information (version)

- OpenVINO=> :master  branch
- Operating System / Platform => Mac (10.15.7)
- Compiler => Xcode (12.3)
- Problem classification => CPU plugin build

##### Detailed description

Generating Xcode project file using cmake (3.19.4) using next command line:

cmake -DENABLE_TESTS=ON -G Xcode -T buildsystem=1 ..

Next opening xcode project file. While building MKLDNNplugin i'm having next error:

no such file or directory: 'openvino/bin/intel64/Release/lib/Debug/libdnnld.a'

Instead of building libdnnld.a to  bin/intel64/Release/lib/Debug/ it builds:

- /openvino/xcode/inference-engine/thirdparty/mkl-dnn/src/cpu/x64/OpenVINO.build/Debug/dnnl_cpu_x64.build/libdnnl_cpu_x64.a
- /openvino/xcode/inference-engine/thirdparty/mkl-dnn/src/common/OpenVINO.build/Debug/dnnl_common.build/libdnnl_common.a
- /openvino/xcode/inference-engine/thirdparty/mkl-dnn/src/cpu/OpenVINO.build/Debug/dnnl_cpu.build/libdnnl_cpu.a

##### Steps to reproduce

clone repo
mkdir xcode
cd xcode
cmake -DENABLE_TESTS=ON -G Xcode -T buildsystem=1 ..
open OpenVINO.xcodeproj
select MKLDNNPlugin for build scheme
build project

**Comment by avitial** [comment]
@Drizshko thanks for reaching out. Does it make any difference if you add `-DCMAKE_BUILD_TYPE=Release` to your cmake command? Does the build fail if you run `make` after running cmake? As per your repro steps, you may be missing `git submodule update --init --recursive` after cloning repo. In addition you can find the build steps for MacOS [here](https://github.com/openvinotoolkit/openvino/wiki/BuildingForMacOS). 

~Luis

**Comment by Drizshko** [comment]
No difference with Release and Debug. As well tried to build with "make" - project built with no issue. With  Xcode i still having issue explained above. I did submodule update before cmake. 
Update: if i do remove libdnnld.a and add 3 libraries (libdnnl_cpu_x64.a, libdnnl_common.a, libdnnl_cpu.a) - i can link MKLDNN Plugin and make it work. 
I believe there is something missing in dnnl cmake files.

**Comment by avitial** [comment]
@Drizshko glad you got it to build. There is a newer release available, if possible try checking it on latest release and see if error is present.

**Comment by latermarch** [comment]
i got the same issue:
Ld bin/intel64/Release/lib/Release/libMKLDNNPlugin.so normal x86_64
    cd /Users/ws/Desktop/openvino
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.9 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -L/Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release -F/Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release -filelist /Users/ws/Desktop/openvino/build/inference-engine/src/mkldnn_plugin/OpenVINO.build/Release/MKLDNNPlugin.build/Objects-normal/x86_64/MKLDNNPlugin.LinkFileList -Xlinker -rpath -Xlinker /Users/ws/Desktop/openvino/inference-engine/temp/tbb/lib -Xlinker -rpath -Xlinker /Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release -Wl,-dead_strip -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/ws/Desktop/openvino/inference-engine/temp/tbb/lib/libtbb.dylib /Users/ws/Desktop/openvino/inference-engine/temp/tbb/lib/libtbbmalloc.dylib /Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release/libdnnl.a /Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release/libinference_engine.dylib /Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release/libinference_engine_lp_transformations.dylib /Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release/libitt.a /Users/ws/Desktop/openvino/inference-engine/temp/tbb/lib/libtbb.dylib /Users/ws/Desktop/openvino/inference-engine/temp/tbb/lib/libtbb.dylib /Users/ws/Desktop/openvino/inference-engine/temp/tbb/lib/libtbbmalloc.dylib /Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release/libinference_engine_transformations.dylib /Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release/libngraph.dylib -Xlinker -dependency_info -Xlinker /Users/ws/Desktop/openvino/build/inference-engine/src/mkldnn_plugin/OpenVINO.build/Release/MKLDNNPlugin.build/Objects-normal/x86_64/MKLDNNPlugin_dependency_info.dat -o /Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release/libMKLDNNPlugin.so

clang: error: no such file or directory: '/Users/ws/Desktop/openvino/bin/intel64/Release/lib/Release/libdnnl.a'

**Comment by latermarch** [comment]
the branch is release.2021.4

**Comment by jgespino** [comment]
@Drizshko Could you provide some insight as to why you need to build OpenVINO using XCode? Have you tried building OpenVINO per the [built instructions](https://github.com/openvinotoolkit/openvino/wiki/BuildingForMacOS)?
