### ISSUE TITLE
When I install openvino-2020.2.120, some package aren't  available

### ISSUE THREAD

**Issue by gtfaiwxm** [openvinotoolkit/openvino#4390]
when I run sudo -E ./install_openvino_dependencies.sh , the error occured No package python36 available.
No package python36-pip available. But I have installed the python3.6.5.

**Comment by jgespino** [comment]
Hi @gtfaiwxm 

What OS are you using? OpenVINO 2020.2 is quite old, could you try installing the latest OpenVINO 2021.2 release?

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, feel free to re-open if additional assistance is needed.
