### ISSUE TITLE
Slice fails to convert from onnx to IR when slicing indices are variables(tensors)

### ISSUE THREAD

**Issue by muaz-urwa** [openvinotoolkit/openvino#440]
I have a slice operation in my pytorch model (shown below):
im = im[:,:,roi[2]:roi[4],roi[2]:roi[3]]]

**roi** and **im** are both tensors. So the indexing/slicing is dynamic and depends on the input roi.

I am able to convert it into onnx and verify the output. 
this node loos like this:
%1679 : Float(1, 5, 28, 64) = onnx::Slice(%1673, %1675, %1676, %1677, %1678) # /app/poolers.py:378:0

But conversion to openvino fails:
#### log ####################
[ 2020-03-29 20:31:50,506 ] [ DEBUG ] [ infer:31 ]  input[0]: shape = [ 1  5 64 64], value = <UNKNOWN>
[ 2020-03-29 20:31:50,506 ] [ DEBUG ] [ infer:31 ]  input[1]: shape = [1], value = <UNKNOWN>
[ 2020-03-29 20:31:50,507 ] [ DEBUG ] [ infer:31 ]  input[2]: shape = [1], value = <UNKNOWN>
[ 2020-03-29 20:31:50,507 ] [ DEBUG ] [ infer:31 ]  input[3]: shape = [1], value = [2]
[ 2020-03-29 20:31:50,507 ] [ DEBUG ] [ infer:31 ]  input[4]: shape = [1], value = [1]
[ WARNING ]  Incorrect slice operation: no starts or ends attr
[ 2020-03-29 20:31:50,507 ] [ DEBUG ] [ infer:144 ]  Outputs:
[ 2020-03-29 20:31:50,507 ] [ DEBUG ] [ infer:31 ]  output[0]: shape = <UNKNOWN>, value = <UNKNOWN>
[ ERROR ]  Shape is not defined for output 0 of "1679".
[ ERROR ]  Cannot infer shapes or values for node "1679".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "1679". 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #40. 
#################################################

As it can be scene that some input values were UNKNOWN because they depend on model input. Hence it was unable to infer the output shape of this node and fails to produce an IR.  

Can you please suggest me a solution or alternative to this problem. I want to export dynamic indexing/slicing from onnx to openvino.

**Comment by lazarevevgeny** [comment]
@muaz-urwa , unfortunately, there is no solution for this issue so far. OpenVINO does not support operations which generate tensors which output shape depends on the input **value** which depends on the model input. Shapes of all tensors must be know at the model loading type and may depend on shapes of model inputs and operation attributes only.

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or start a new issues if additional assistance is needed.

Sincerely,
Sahira
