### ISSUE TITLE
Is it possible to convert yolov3-tiny-xnor to IR model?

### ISSUE THREAD

**Issue by b04505009** [openvinotoolkit/openvino#4414]
I would like to use openvino to get best performance of model inference on Intel CPU, and BNN (like XNOR-NET) seems have lots of advantages working on CPU. 
I think this is possible because you have supported this op in [BinaryConvolution](https://docs.openvinotoolkit.org/latest/openvino_docs_ops_convolution_BinaryConvolution_1.html), but I have no idea how to convert from yolo model ([yolov3-tiny-xnor](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny_xnor.cfg)) or from any other framework to it. 
If this is possible, could you provide some examples or instructions? Thank you.

P.S. This op is also supported by tensorflow (like [Larq](https://github.com/larq/larq))

**Comment by avitial** [comment]
@b04505009 thanks for reaching out. There is a pre-trained model ([resnet18-xnor-binary-onnx-0001](https://docs.openvinotoolkit.org/latest/omz_models_intel_resnet18_xnor_binary_onnx_0001_description_resnet18_xnor_binary_onnx_0001.html)) available in OMZ were most convolutional layers were replaced by binary ones that can be implemented as XNOR+POPCOUNT operations. Only input, final and shortcut layers were kept as FP32, all the rest convolutional layers are replaced by binary convolution layers. That being said, have you tried passing your model through Model Optimizer? If so, do you get any errors from MO? 

Also there is a guide available on [Converting YOLO* Models to the Intermediate Representation (IR)](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html#yolov3-to-ir), thought it might be useful. 


~Luis

**Comment by b04505009** [comment]
Hi @avitial 

Thank you for your response.

I have followed the instructions of [Converting YOLO* Models to the Intermediate Representation (IR)](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html#yolov3-to-ir), but after I convert my xnor model to pb format, I found that the convolution type is still float32.

![SharedScreenshot](https://user-images.githubusercontent.com/14859904/108797083-52050580-75c5-11eb-90d3-8fb8e5d33abf.jpg)

I still convert this pb model to IR model by mo_tf.py, and in xml it shows normal convolution but not BinaryConvolution, which resnet18-xnor-binary-onnx-0001 does.

Is there any other way to convert yolo to pb or directly convert yolo to IR?

b04505009

**Comment by b04505009** [comment]
Is there any plan or update?

**Comment by avitial** [comment]
@b04505009 we are still looking into it, if possible please share your xnor model files with us to test. It looks like the [resnet18-xnor-binary-onnx-0001](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/resnet18-xnor-binary-onnx-0001/description/resnet18-xnor-binary-onnx-0001.md) is coming from a PyTorch implementation, but there is no other info on such.

**Comment by b04505009** [comment]
Hi @avitial 
Here is [our model](https://drive.google.com/file/d/1oQlZWQROWfpmlFSvGO97OOdW13lpGad7/view?usp=sharing)
Thank you for your help!

**Comment by avitial** [comment]
@b04505009 thanks for sharing the model, let me check with dev team for pointers on this and get back to you.


Ref. 52492

**Comment by andrei-kochin** [comment]
Hello @b04505009,

Seems like after saving to pb format you model is no longer xnor but usual float32 and that seems to be pb script issue.

Anyway unfortunately Binary models are not supported by Model Optimizer and can't be converted. The only possible way to have binary convolution is to use internally pre-trained model [resnet18-xnor-binary-onnx-0001] (https://docs.openvinotoolkit.org/latest/omz_models_intel_resnet18_xnor_binary_onnx_0001_description_resnet18_xnor_binary_onnx_0001.html) from OMZ.

Best regards,
Andrei
