### ISSUE TITLE
how to read or load the encryption xml file

### ISSUE THREAD

**Issue by wuqingshan2010** [openvinotoolkit/openvino#4417]
In the version 2020.3, i can do like this:
InferenceEngine::CNNNetReader network_reader;
networkReader.ReadNetwork(xmlFile, xmlFileLength);
networkReader.ReadWeights(binFile);
InferenceEngine::CNNNetwork network = networkReader.getNetwork();

but in the version 2021.2, i can not do like above;
 when i deploy myself algorithm, i must encrypted the xml File, who can help me to solve the problem that how to read or load the encryption xml file.

**Comment by ilyachur** [comment]
Hi @wuqingshan2010,

Could you please read this documentation to understand how you can read encrypted models: https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_protecting_model_guide.html
I hope it should help you.

**Comment by mifan0208** [comment]
@ilyachur ,Hi,I checked this web,but I can't solve this question.When I use this function，A memory leak occurred。ie.ReadNetwork(strModel,make_shared_blob<uint8_t>({Precission::U8,{weights.size()},C},weights.data())).

**Comment by ilyachur** [comment]
@mifan0208 Could you provide a reproducer? What is the weights variable?
How did you detect the memory leak?

**Comment by mifan0208** [comment]
(1) I read the raw XML and bin through ifstream,and write in model and weights.(I only read raw xml and bin in this process)
	std::vector<uint8_t> model;
	std::vector<uint8_t> weights;
        encrypte_tool->decrypte(enc_xml_path, model);
	encrypte_tool->decrypte(enc_bin_path, weights);
(2) I use this code to read my network.
        std::string strModel(model.begin(), model.end());
	//cout << "str Model:" << strModel << endl;
	CNNNetwork network = ie.ReadNetwork(enc_xml_path,
            make_shared_blob<uint8_t>({ Precision::U8, {weights.size()},C },weights.data()));

error:0x00007FFE13403B29 处(位于 openvino_test.exe 中)有未经处理的异常: Microsoft C++ 异常: InferenceEngine::details::InferenceEngineException，位于内存位置 0x000000F0F54FE3F0 处。

**Comment by mifan0208** [comment]
@wuqingshan2010  Have you solved the problem？

**Comment by mifan0208** [comment]
@ilyachur  Hi,ilyachur ,Below,you can check code and IR files. Thanks.
`#include <iostream>
#include <string>
#include <memory>
#include <vector>
#include <algorithm>
#include <map>
#include <chrono>
#include <inference_engine.hpp>
#include <fstream>
#include <sstream>

using namespace InferenceEngine;
using namespace std;


void decrypte(const string& input_filename, std::vector<uint8_t>& inputModel,string & infos) {

	ifstream model_file(input_filename.c_str(),std::ios::binary);
	// xml
	std::stringstream buffer;
	buffer << model_file.rdbuf();
	std::string contents(buffer.str());
	for (int i = 0; i < contents.length(); i++) {
		//model.push_back((uint8_t)contents[i]);
		inputModel.push_back(contents[i]);
		infos.push_back(contents[i]);
	}
}

int main() 
{

const string xml_path = "mobilenet_v1_0.5_160_frozen.xml";
const string bin_path = "mobilenet_v1_0.5_160_frozen.bin";
// read xml_path and bin_path
Core ie;
//CNNNetwork network = ie.ReadNetwork(xml_path, bin_path);
//cout << "Read Network Success" << endl;
//return 0;
//read xml info and weights info
std::vector<uint8_t> model;
std::vector<uint8_t> weights;

string xml_infos;
string bin_infos;

decrypte(xml_path, model, xml_infos);
decrypte(bin_path, weights,bin_infos);

////valid output
std::ofstream fout_xml("result.xml", std::ios::binary);
fout_xml.write(xml_infos.c_str(), xml_infos.size());
////valid output
std::ofstream fout_bin("result.bin", std::ios::binary);
fout_bin.write(bin_infos.c_str(), bin_infos.size());
fout_xml.close();
fout_bin.close();
//return 0;
//cout << "xml" << xml_infos << endl;
// valid the generator xml and bin is correct

//CNNNetwork network = ie.ReadNetwork("result.xml", "result.bin");
//cout << "Read Transfer Network Success" << endl;
//return 0;

std::string strModel(model.begin(), model.end());
//cout << "str Model:" << strModel << endl;
 CNNNetwork network = ie.ReadNetwork(strModel,
	make_shared_blob<uint8_t>({ Precision::U8, {weights.size()},C }, weights.data()));

 cout << "Read Transfer Network Success" << endl;

return 0;
}`

this is my testing code.


[xml_bin.zip](https://github.com/openvinotoolkit/openvino/files/6020493/xml_bin.zip)

The IR files (xml and bin) in xml_bin.zip,Please reproduce this error.
Thank you!

**Comment by mifan0208** [comment]
Hi,ilyachur ,Below,you can check code and IR files in test_xml_bin.zip. Thanks.
[test_xml_bin.zip](https://github.com/openvinotoolkit/openvino/files/6021674/test_xml_bin.zip)

**Comment by ilyachur** [comment]
Hi @mifan0208 ,

I tried to reproduce the problem, but all works as expected.
What OS do you use? And how did you find the memory leak?
Also I would like to notice that the call:
```
make_shared_blob<uint8_t>({ Precision::U8, {weights.size()},C }, weights.data())
```
doesn't copy and hold the original data. It means that you can face some issues if `weights` vector is destroyed.
