### ISSUE TITLE
How to specify SYSTEM 3rd-party libraries?

### ISSUE THREAD

**Issue by jiapei100** [openvinotoolkit/openvino#442]
It looks dldt will **automatically** download and build its own

```
download  gna_01.00.00.1401  opencv_4.2.0_ubuntu18  tbb  vpu
```

How about if I had A**L**L the above 3rd-party libraries installed from repository or manually **ALREADY** on my customized system?

Any suggestions please?

Cheers
Pei

**Comment by ilya-lavrenov** [comment]
@jiapei100 OpenVINO uses specific dependencies which provide better performance. But you can override some of them using environment variables:

1. `OpenCV_DIR` for  OpenCV (see https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/cmake/dependencies.cmake#L197)
2. `TBBROOT` for TBB (see https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/cmake/dependencies.cmake#L128)
