### ISSUE TITLE
dldt-2020 Failed to build from source 

### ISSUE THREAD

**Issue by jiapei100** [openvinotoolkit/openvino#443]
1. Error messages:

```
......
 Found CUDA: /usr/local/cuda (found suitable exact version "10.2")
 CMake Error at inference-engine/CMakeLists.txt:143 (export):
   export given target "ngraph::ngraph" which is not built by this project.

 Configuring incomplete, errors occurred!
 See also "/opt/intel/openvino/dldt/build_18.04/CMakeFiles/CMakeOutput.log".
 See also "/opt/intel/openvino/dldt/build_18.04/CMakeFiles/CMakeError.log".

```

2. What should be the value of **BUILD_DEFINES** ?

3. How can I use the **previously-installed** libraries instead of the thirdparty libraries downloaded with dldt ?

```console
....../dldt/inference-engine/thirdparty
➜  thirdparty git:(2020) ✗ ls
ade  clDNN  CMakeLists.txt  fluid  mkl-dnn  mkldnn.cmake  movidius  ocv  pugixml  stb_lib
```

**Comment by dkurt** [comment]
Hi!

Have you executed
```
git submodule init
git submodule update --recursive
```
before the build?

**Comment by brmarkus** [comment]
On the page "https://github.com/opencv/dldt/blob/2020/get-started-linux.md" the link to the build instructions "https://github.com/opencv/dldt/blob/2020/inference-engine/README.md" under the section "Prerequisites" results in a 404 error.
So we all currently don't know how to build DLDT :-)

**Comment by dkurt** [comment]
I think https://github.com/opencv/dldt/blob/2020/build-instruction.md is more actual

**Comment by ilya-lavrenov** [comment]
@jiapei100 do you still observe the problems?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
