### ISSUE TITLE
a bug of scatternd of MO

### ISSUE THREAD

**Issue by shixinlishixinli** [openvinotoolkit/openvino#4434]
##### Detailed description
paddle OCR is a very powerful model to recognize chinese and other languages. i am try to convert paddleocr to openvino. and there is a bug of scatternd layer when the updates_shape is 1 , input_shape is 3 and  indices_shape is 1 .  
when indices_shape is 1 , indices_shape[:-1] = [], so MO is failed . 

i try to modify the scatternd.py in MO, the MO is successful but there is a new bug in ie_api.pyx.
i think when updates_shape is 1 , input_shape is 3 and  indices_shape is 1, the scatternd layer can work successfully such as

update =[5]
indices = [2]
output = [0,0,5]

looking forward to your reply
best
Lisa Shi

**Comment by slyalin** [comment]
@shixinlishixinli, could you please provide a link to ONNX model that you are trying to convert? Or just capture in Netron that particular place where you thing there is a bug? I suppose you did paddle to onnx conversion as MO doesn't support direct paddle model conversion. Just based on what you write about ranks of ScatterND inputs (`updates_shape is 1 , input_shape is 3 and indices_shape is 1`), I think ONNX model itself has a bug. Please refer to ScatterND-11, that says the updates should be a scalar in this case, not 1D tensor.

**Comment by shixinlishixinli** [comment]
![image](https://user-images.githubusercontent.com/20768380/108591097-cc554000-73a1-11eb-9d4c-fdae800706b7.png)

**Comment by shixinlishixinli** [comment]
i  don't know how to upload the weight file . so i will send a email of weight to you .
i am waiting for your reply

best
Lisa Shi

**Comment by slyalin** [comment]
Exactly my point -- Gather gives 1D 'updates' tensor because `indices` is 1D tensor. For ScatterND `updates` should be a scalar by ONNX requirements (https://github.com/onnx/onnx/blob/master/docs/Changelog.md#scatternd-11) or other inputs of ScatterND should have different ranks. Probably, Gather should provide scalar since it is only a single element.

**Comment by shixinlishixinli** [comment]
i think you are right . but i can get the right result from my onnx model . but onnx model can not be inferenced by IE . and MO of this model is not successful. so what can i do to solve this bug?

**Comment by shixinlishixinli** [comment]
i can modify the MO to get the xml file and bin file. but this bin file can not be inferenced by IE successfully, the new bug is also caused by  scatternd layer

**Comment by captainfffsama** [comment]
I meet a similiar problem,my model work fine on `onnxruntime`...when I convert my ONNX to xml and bin...I get a bug show that Scatternd have a bug that idx beyond the array size range,I find the shape is not right.  
so I change [`output_value[indices_value[indx]] = updates_value[indx]`](https://github.com/openvinotoolkit/openvino/blob/be614035d11d4a3ab7246ebb7393d076c5758ee0/model-optimizer/extensions/ops/scatternd.py#L101) as `output_value[indices_value[indx][0],indices_value[indx][1]] = updates_value[indx]`, it convert success and no error or warning....  
but when I try use openvino infer this model,`exec_net=ie.load_network(network=net,device_name='CPU')` show a error about that:
> RuntimeError: Failed to find reference implementation for `ScatterND_79` Layer with `ScatterNDUpdate` Type on constant propagation

**Comment by captainfffsama** [comment]
Oh,  It seems that ONNX version is not right...when  I convert version to 11,  the scatter of MO can not work,but use onnx 10,It worked!....scatterND should not change,` output_value[indices_value[indx]] = updates_value[indx]` is right ,the principle of scatter can refer:https://www.tensorflow.org/api_docs/python/tf/scatter_nd

**Comment by shixinlishixinli** [comment]
> Oh, It seems that ONNX version is not right...when I convert version to 11, the scatter of MO can not work,but use onnx 10,It worked!....scatterND should not change,` output_value[indices_value[indx]] = updates_value[indx]` is right ,the principle of scatter can refer:https://www.tensorflow.org/api_docs/python/tf/scatter_nd

do you mean you can run the scatternd layer by openvino successfully?

**Comment by captainfffsama** [comment]
> > Oh, It seems that ONNX version is not right...when I convert version to 11, the scatter of MO can not work,but use onnx 10,It worked!....scatterND should not change,` output_value[indices_value[indx]] = updates_value[indx]` is right ,the principle of scatter can refer:https://www.tensorflow.org/api_docs/python/tf/scatter_nd
> 
> do you mean you can run the scatternd layer by openvino successfully?

yes,my model is come from pytorch,when I try convert it to onnx 11,it can be run by onnxruntime but can not convert by openvino/mo.py....but when I convert it to onnx 10,it work fine both.

**Comment by shixinlishixinli** [comment]
i make a new node of  indice in scatternd of onnx , the new node's dim is [1,1] not [1], and new model can be converted by MO successfully, so i close this issue.  thanks for all your help

**Comment by HanGuangXin** [comment]
@shixinlishixinli Hi, there! I am trying to convert paddleocr to openvino, too. I have successfully convert paddleocr to onnx, but failed to convert onnx model to openvino. Can you please tell me how to manage it? Thanks a lot!!!
