### ISSUE TITLE
Need reference for the following use cases.

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [openvinotoolkit/openvino#4454]
Hi 
I am inferencing AI models on Intel PAC with Arria10.
1) is there any support for mixed precision ?
2) How do execute on multiple FPGA's.?

**Comment by avitial** [comment]
@SAIVENKATARAJU thanks for reaching out. To execute on multiple FPGA cards, I believe the way to do this is to implement in your app and use 2x different ExecutableNetwork objects, each with LoadNetwork called with different device ids. You can get the device id of the PAC card with `aocl diagnose -probe`. For more details please refer to [Quick Start Guide](https://www.intel.com/content/dam/www/programmable/us/en/pdfs/literature/ug/ug-opencl-asxf-quickstart.pdf
), Page 12 (Topic: 5 OpenCL Support for Multi-Card Systems). 

As far as your first question, please elaborate more what you mean.


~Luis

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
