### ISSUE TITLE
[Bug] Master Branch Build Fails in VS2017

### ISSUE THREAD

**Issue by kenkoyanagi** [openvinotoolkit/openvino#4457]
##### System information (version)

- OpenVINO=> Master Branch
- Operating System / Platform => Win10
- Compiler => VS 2017 
- Problem classification => Bug

##### Detailed description
Previously able to build Master, pulled latest changes and now run into an OpenMP error. 

C3001 'simd' expected an OpenMP directive name
![image](https://user-images.githubusercontent.com/49453354/108760040-ffaee080-7501-11eb-8404-4eb74504a348.png)

Tried to rebuild from scratch as well. 
Builds successfully with VS2019.

##### Steps to reproduce

Follow steps from documentation:
https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows

**Comment by jgespino** [comment]
Hi @kenkoyanagi 

What CMake and Python version do you have installed on your system? Please provide the full cmake command used to build, for example: `cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release ..`

Please note that the build steps have only been validated on _Microsoft* Windows* 10 (64-bit) with Visual Studio 2019_.

Regards,
Jesus

**Comment by kenkoyanagi** [comment]
Hi @jgespino 

I used that cmake command with `DENABLE_CLDNN=OFF` as the only additional argument. 
`cmake -G "Visual Studio 15 2017 Win64" -DENABLE_CLDNN=OFF -DCMAKE_BUILD_TYPE=Release ..`
Python == 3.6.8
CMake = 3.15.4

I understand validation is only done on W10 VS2019, but the software documentation has VS 2017 as a supported version.

Thanks,
Ken

**Comment by jgespino** [comment]
Hi @kenkoyanagi 

> I understand validation is only done on W10 VS2019, but the software documentation has VS 2017 as a supported version.

My comment regarding the validation only applies to the build process of the open-sourced OpenVINO. I believe you are referring to the Intel Distribution of OpenVINO toolkit documentation, if so, that's correct. You could use Microsoft Visual Studio 2017 or 2019. Is there a particular reason why you need to build OpenVINO from source with Microsoft Visual Studio 2017?

Regards,
Jesus

**Comment by kenkoyanagi** [comment]
Hi @jgespino 

It's from the documentation for building the open-source OpenVINO here: https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows 

Nevertheless, VS2017 v141 libraries are needed to be included in an existing application using v141. Are the errors able to be replicated?

**Comment by jgespino** [comment]
> It's from the documentation for building the open-source OpenVINO here: https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows

Ops did not see that there, sorry! I just installed Microsoft VS 2017, Python 3.6.8 and CMake 3.15.4 to match your environment. I'm about to start the build process, I'll let you know what I find out.

Regards,
Jesus

**Comment by ilya-lavrenov** [comment]
What are the values of `DNNL_CPU_THREADING_RUNTIME`, `THREADING` variables in cmake cache?  They should be `TBB`.

**Comment by jgespino** [comment]
Hi @kenkoyanagi 

Master branch build failed with the same error messages using Microsoft Visual Studio 2017. However, building 2021.2 branch with Microsoft Visual Studio 2017 did not have any issues. 

@ilya-lavrenov  From the CMakeCache.txt, `THREADING:STRING=TBB` is set for both master and 2021.2 branch. `DNNL_CPU_RUNTIME:BOOL=TBB` was set on master but not found on 2021.2 branch. This may be a bug, I will open a bug internally for investigation.

Regards,
Jesus
