### ISSUE TITLE
2020.1 debug mode build fails

### ISSUE THREAD

**Issue by wlfgang** [openvinotoolkit/openvino#446]
Debug-mode build of dldt is failing on CentOS 7 / gcc 4.8.5. Here are my steps to reproduce:

1. git clone
2. git submodule update --init --recursive
3. mkdir build && cd build
4. cmake -DCMAKE_BUILD_TYPE=Debug ..
5. make

```
[  0%] Building CXX object ngraph/src/ngraph/CMakeFiles/ngraph.dir/attribute_adapter.cpp.o
In file included from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:2097,
                 from /usr/include/c++/4.8.2/bits/stl_algobase.h:59,
                 from /usr/include/c++/4.8.2/vector:60,
                 from /home/me/dldt/ngraph/src/ngraph/attribute_adapter.cpp:17:
/usr/include/features.h:330:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
cc1plus: all warnings being treated as errors
make[2]: *** [ngraph/src/ngraph/CMakeFiles/ngraph.dir/attribute_adapter.cpp.o] Error 1
make[1]: *** [ngraph/src/ngraph/CMakeFiles/ngraph.dir/all] Error 2
make: *** [all] Error 2
```

It appears that both ngraph and ade are setting _FORTIFY_SOURCE=2, which is great, but apparently gcc emits warnings unless combined with optimization flags. Both libraries also have hard-coded `-Werror` (treat warnings as errors) in their builds, which would be okay if they did in fact compile without warnings.

**Comment by wlfgang** [comment]
Update: The culprit is actually `cmake/os_flags.cmake`, which adds the `-Werror` flag to dldt and all sub-projects. For windows builds, this respects `TREAT_WARNING_AS_ERROR`, but not so for Linux/Mac. I see there are several other reported issues related to this, and an unmerged pull request going back to Oct 2019 that fixes it.

**Comment by maxl16** [comment]
Hello @wlfgang 
From the documentation available for dldt cmake build on CentOS we have this article - https://github.com/opencv/dldt/blob/2020/build-instruction.md
However, -DCMAKE_BUILD_TYPE=Debug is not listed there as validated option, so this might be not officially supported.
Please check all the available information we have for additional build options here https://github.com/opencv/dldt/blob/2020/build-instruction.md#additional-build-options

Also, we'll let you know if we get any information from developers team about it. 

Thanks.
Best regards, Max.

**Comment by ilya-lavrenov** [comment]
@wlfgang 

1. You can compile DLDT with `cmake -DTREAT_WARNING_AS_ERROR=OFF` and it's not respected for Unix systems as well.
2. Now, ngraph SDL flags are not used in compilation (see https://github.com/openvinotoolkit/openvino/blob/master/CMakeLists.txt#L98) while IE ones are used only for `Release` mode.
