### ISSUE TITLE
[Bug] cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DENABLE_CLDNN=OFF ..

### ISSUE THREAD

**Issue by mifan0208** [openvinotoolkit/openvino#4466]
version infos:VS2019,cmake 3.19.3,Win10
commond:cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DENABLE_CLDNN=OFF ..
error infos:
CMake Error at inference-engine/CMakeLists.txt:25 (export):
  export given target "xbyak" which is not built by this project.
Call Stack (most recent call first):
  inference-engine/CMakeLists.txt:149 (ie_developer_export)

-- Register template_plugin to be built in build-modules/template_plugin
CMake Error at build/inference-engine/build-modules/InferenceEngineDeveloperPackageConfig.cmake:4 (add_library):
  add_library cannot create ALIAS target "IE::xbyak" because target "xbyak"
  does not already exist.
Call Stack (most recent call first):
  docs/template_plugin/CMakeLists.txt:12 (find_package)

CMake Warning at cmake/developer_package/shellcheck/shellcheck.cmake:11 (message):
  shellcheck tool is not found
Call Stack (most recent call first):
  CMakeLists.txt:157 (ie_shellcheck_process)

-- Configuring incomplete, errors occurred!

Thanks.

**Comment by jgespino** [comment]
Hi @mifan0208 

I just tested the build process on the master branch and did not run into this error. Which commit/branch are you building? Could you confirm you completed all the steps as mentioned in the [build instructions](https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows)?

I tested on Windows 10 with Microsoft Visual Studio 2019 (MSBuild and Desktop Development with C++), CMake 3.19.3 (64-bit) and Python 3.6.8 (64-bit).

Commands:
```
git clone https://github.com/openvinotoolkit/openvino
cd openvino
git submodule update --init --recursive
mkdir build && cd build
cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DENABLE_CLDNN=OFF ..
cmake --build . --config Release --verbose -j8
```

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
