### ISSUE TITLE
log should print before the resize()

### ISSUE THREAD

**Issue by junxnone** [openvinotoolkit/openvino#448]
https://github.com/opencv/dldt/blob/a347375d0188b58056887f382161c6ed6fc3dcb3/inference-engine/ie_bridges/python/sample/object_detection_sample_ssd/object_detection_sample_ssd.py#L93-L95

> the image.shape[:-1] should be used before `image=cv2.resize(image, (w, h)`
otherwise, it will print `WARNING:root:Image data/eval/xxx.jpg is resized from (resize_image.h, resize_image.w) to (h, w)`, and is should be `resized from (origin_image.h, origin_image.w) to (h, w)`

**Comment by maxl16** [comment]
Hello @junxnone 
Thank you for reporting this mistake. We'll fill a bug report in order to make this fixed.

**Comment by ilya-lavrenov** [comment]
@junxnone what is the issue? the tool that warns about image resizing. The C++ tool does the same.

**Comment by junxnone** [comment]
https://github.com/openvinotoolkit/openvino/blob/e835a4cf58a69d107f3162dc83d7de192efbf8e4/inference-engine/ie_bridges/python/sample/object_detection_sample_ssd/object_detection_sample_ssd.py#L104-L105

---
The log message is wrong.
the `second {}` shoud be the origin image shape, but now it is the resized image shape

**Comment by yury-gorbachev** [comment]
> https://github.com/openvinotoolkit/openvino/blob/e835a4cf58a69d107f3162dc83d7de192efbf8e4/inference-engine/ie_bridges/python/sample/object_detection_sample_ssd/object_detection_sample_ssd.py#L104-L105
> 
> The log message is wrong.
> the `second {}` shoud be the origin image shape, but now it is the resized image shape

Any chance you could contribute fix?

Possible for y

**Comment by ilya-lavrenov** [comment]
@junxnone thanks for the patch! I'm closing the issue.
