### ISSUE TITLE
Problem about group convolution when NSC2

### ISSUE THREAD

**Issue by Aktcob** [openvinotoolkit/openvino#450]
Openvino version: openvino_2020.1.023

Device: NSC2

Problem:  When I test the infer time of mobilenetv1, I find out that there exists some bugs with group convolution. For example, for a group convolution, the input tensor is 64*H*W, and the group convolution parameters are(in_channels=64, out_channels=128, kernel=(3,3), group=64//2 ), ATTENTION!, When the group is 64//2, not 64, the infer time is so slow and loading network needs more time. And the group is 64//4, it also causes some problem.

**Comment by Aktcob** [comment]
BTW, the input resolution is 320*320, for original mobilenetv1, infer time is about 40ms.
And I changed the group parameter to half, which means 64->32, 512->256, etc. The infer time is 120ms. (SO weird!). Group parameter to 1/4, 81ms; Group parameter to 1/8, 58ms; mobilenetv1_without any group convo, 116ms

**Comment by Aktcob** [comment]
Help

**Comment by brmarkus** [comment]
Can you provide more information to allow reproduction, please?
Where to get the model from, have you converted it, how?
Which sample application have you used, how? Can you share the command lines (with a camera? With images, with a video?), please?

**Comment by Aktcob** [comment]
I get the model from MXnet and converted it. 
I changed the params of group conv in mobilenetv1. For example, group=64 -> 32 (half of original params number). I tested with a random image. The sample application is  
/opt/intel/openvino_2020.1.023/deployment_tools/inference_engine/samples/python/classification_sample
