### ISSUE TITLE
Using MLPerf Inference v0.5 build command results in warnings

### ISSUE THREAD

**Issue by psyhtest** [openvinotoolkit/openvino#451]
Using a CMake command from the [MLPerf Inference v0.5 build instructions](https://github.com/mlperf/inference_results_v0.5/tree/master/closed/Intel/measurements/clx_9282-2s_openvino-linux/ssd-small/Offline#download-and-build-openvino):
```
cmake -DCMAKE_BUILD_TYPE=Release -DTHREADING=OMP -DENABLE_DLIA=OFF -DENABLE_VPU=OFF \
	-DENABPP=OFF -DENABLE_PROFILING_ITT=OFF -DENABLE_VALIDATION_SET=OFF -DENABLE_TESTS=OFF \
	-DENABLE_GNA=OFF -DENABLE_CLDNN=OFF -DENABLE_OPENCV=OFF -DOpenCV_DIR=$( dirname '/path/to/opencv/build/OpenCVConfig.cmake' ) ..
```
results in warnings:
```
  Manually-specified variables were not used by the project:
                                                               
    ENABLE_DLIA                                                                             
    ENABLE_VALIDATION_SET
    ENABPP              
```

What should those variables be please? (Clearly, `ENABPP` is wrong.)

**Comment by maxl16** [comment]
I can say that DLIA stands for Deep Learning Inference Accelerator toolkit, that provides capabilities to develop applications and solutions through the Linux FPGA version of the OpenVINO toolkit.

**Comment by psyhtest** [comment]
Thanks @maxl16! As I don't have an Intel FPGA, clearly that option should be off.

**Comment by ilya-lavrenov** [comment]
the mentioned scripts are not a part of OpenVINO source tree. Closing,
