### ISSUE TITLE
[CLDNN ERROR]. No GPU device was found.

### ISSUE THREAD

**Issue by zccyman** [openvinotoolkit/openvino#452]
I run super_resolution_demo, then get output as follow:
```
./super_resolution_demo -i /home/developer/zhangcc/code/intel/models/lena.png -m /home/developer/zhangcc/code/intel/models/single-image-super-resolution-1033.xml -d gpu
[ INFO ] InferenceEngine: 0x7fd218859030
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     /home/developer/zhangcc/code/intel/models/lena.png
[ INFO ] Loading Inference Engine
[ INFO ] Device info: 
[ ERROR ] Failed to create plugin /home/developer/zhangcc/code/intel/openvino_2020.1.023/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device gpu
Please, check your environment
[CLDNN ERROR]. No GPU device was found.
```

**Comment by brmarkus** [comment]
Does your system have an embedded or discrete Intel GPU?
Have you installed the Intel-GPU specific packages and drivers as described here:
https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html#additional-GPU-steps

If you run "lspci", which "VGA" device do you see, an Intel device, AMD or maybe NVIDIA?

**Comment by zccyman** [comment]
@brmarkus I run code:
```
std::vector<std::string> devices = ie.GetAvailableDevices();
std::cout << "devices: " << devices[0] << " " << devices[1]  << std::endl;
```
then only get devices: CPU GNA.

**Comment by brmarkus** [comment]
Do you have an Intel GPU in your system, either an embedded GPU or a discrete GPU card inserted?

Have you installed the GPU-related components as described above?

Can you call the command "lspci" in a Linux-shell on your system and check for a "VGA" device, please?

Your output from above calling `ie.GetAvailableDevices()` shows that no (compatible) GPU device was found, either it is not compatible or the drivers were not installed.

**Comment by zccyman** [comment]
@brmarkus OK, I will check one by one as you said.

**Comment by zccyman** [comment]
@brmarkus
```
$ lspci | grep -i vga
02:00.0 VGA compatible controller: Huawei Technologies Co., Ltd. Hi1710 [iBMC Intelligent Management system chip w/VGA support] (rev 01)

$ lspci | grep -i nvidia
3b:00.0 3D controller: NVIDIA Corporation TU104GL [Tesla T4] (rev a1)
86:00.0 3D controller: NVIDIA Corporation TU104GL [Tesla T4] (rev a1)
af:00.0 3D controller: NVIDIA Corporation TU104GL [Tesla T4] (rev a1)
```

**Comment by brmarkus** [comment]
That doesn't look like Intel GPU devices...
OpenVINO with the GPU-plugin only supports Intel-GPU devices (embedded or discrete), I think.

**Comment by ilya-lavrenov** [comment]
Right, OpenVINO supports only Intel GPUs

**Comment by vladimir-paramuzov** [comment]
@zccyman Do the comments above resolve your issue?

**Comment by brmarkus** [comment]
A colleague got OpenVINO running on "Intel Haydes Canyon NUC", which has an "AMD Radeon" on board.

**Comment by abrichr** [comment]
I get a similar error on MacOS 10.13.6, with an Intel Iris Graphics 6100 1536 MB:

```
Traceback (most recent call last):
  File "multi_camera_multi_person_tracking.py", line 260, in <module>
    main()
  File "multi_camera_multi_person_tracking.py", line 248, in main
    capture.get_num_sources())
  File "/opt/intel/openvino_2020.2.117/deployment_tools/inference_engine/samples/python/multi_camera_multi_person_tracking/utils/network_wrappers.py", line 40, in __init__
    self.net = load_ie_model(ie, model_path, device, None, ext_path, num_reqs=max_num_frames)
  File "/opt/intel/openvino_2020.2.117/deployment_tools/inference_engine/samples/python/multi_camera_multi_person_tracking/utils/ie_tools.py", line 96, in load_ie_model
    exec_net = ie.load_network(network=net, device_name=device, num_requests=num_reqs)
  File "ie_api.pyx", line 178, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 187, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Device with "GPU" name is not registered in the InferenceEngine
```

Is there a way to enable GPU support on MacOS?

**Comment by asuhov** [comment]
@abrichr GPU plugin supports Windows and Linux only. There is no way to use it on MacOS.

**Comment by abrichr** [comment]
@asuhov thank you for the quick reply.

On Windows 10, following the instructions at https://docs.openvinotoolkit.org/2020.1/_docs_install_guides_installing_openvino_windows.html:

```
classification_sample_async.exe -i "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\car.png" -m "C:\Users<username>\Documents\Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1\FP16\squeezenet1.1.xml" -d GPU

[ INFO ] InferenceEngine:
        API version ............ 2.1
        Build .................. 42025
        Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\demo\car.png
[ INFO ] Creating Inference Engine
[ ERROR ] Failed to create plugin C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\inference_engine\bin\intel64\Release\clDNNPlugin.dll for device GPU
Please, check your environment
[CLDNN ERROR]. No GPU device was found.
```

In the Device Manager, under Display Adapters, I see "Intel(R) HD Graphics 4600". The Driver Version is 20.19.15.4531.

How can I get OpenVINO working with a GPU on Windows?

**Comment by vladimir-paramuzov** [comment]
@abrichr This error means that opencl doesn't work for your device. 
The problem is that GPU driver has NEO compute runtime for opencl which supports only gen8+ GPUs (Broadwell, Skylake, etc), but `Intel(R) HD Graphics 4600` is gen7 (Haswell), so we can't really do anything on the openvino side to fix this issue.

See https://github.com/intel/compute-runtime repo for more details on supported platforms.

**Comment by alfawzaan** [comment]
You may try to update your GPU  driver if you are using windows

**Comment by Gsarg18** [comment]
Is openvino support Nvidia GPU? If yes, then how to configure it

**Comment by brmarkus** [comment]
> Is openvino support Nvidia GPU? If yes, then how to configure it

No, OpenVINO only supports Intel GPUs.
