### ISSUE TITLE
[Bug] Old opencv version in 2021.2 release

### ISSUE THREAD

**Issue by banderlog** [openvinotoolkit/openvino#4527]
##### System information (version)

- OpenVINO=> 2021.2
- Operating System / Platform => any
- Compiler => any
- Problem classification => dependency problem

##### Detailed description

The `openvino-2021.2/inference-engine/cmake/dependencies.cmake` from <https://github.com/openvinotoolkit/openvino/archive/2021.2.tar.gz> contains old OpenCV version:

https://github.com/openvinotoolkit/openvino/blob/4795391b73381660b69b4cd3986c7a0bf902e868/inference-engine/cmake/dependencies.cmake#L183-L187

Bit it supposed to be updated even before OpenCV release.
Dates of releases and commits for convinience:
+  OpenCV to 4.5.1 (#3482) asuhov committed on Dec 6, 2020
+ OpenCV 4.5.1 alalek released this on Dec 22, 2020
+ OpenVINO 2021.2 asuhov released this on Dec 15, 2020

##### Steps to reproduce

See `openvino-2021.2/inference-engine/cmake/dependencies.cmake` from <https://github.com/openvinotoolkit/openvino/archive/2021.2.tar.gz>

**Comment by alalek** [comment]
Some technical information is below:

1. This dependency is configurable.
Use `OpenCV_DIR` through CMake variable to specify your own prebuilt configurations (use custom or system (by OS distribution) builds).
Check Wiki page for details: https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux

2. OpenCV dependency is used in tests and samples only. It is not a part of distribution.

3. Only limited subset of platforms/configurations is used "automatically". Many other configurations are not handled here (and they can't be handled), so you need to use own OpenCV binaries in such cases.

---

You may want change order of "Dates of releases and commits" list by date.

**Comment by banderlog** [comment]
So it is not a bug, but a feature
