### ISSUE TITLE
[Help] How can I print the value on Android?

### ISSUE THREAD

**Issue by zhangkom** [openvinotoolkit/openvino#4534]
On Android platform, I want to print some value in openvino/inference-engine/src/inference_engine/ie_core.cpp, but failed. Please if we have some print method used on Android.

I have #define LOGD(...) ((void)__android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)) in ie_core.cpp, but compile failed, and output the error: "can not find __android_log_print".

**Comment by ilya-lavrenov** [comment]
CC @dkurt

**Comment by dkurt** [comment]
One of the solutions is to write the value into the text file

**Comment by zhangkom** [comment]
Yes, I have include the file as following:
#include <android/log.h>
#define LOGD(...) ((void)__android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, VA_ARGS))

**Comment by zulkifli-halim** [comment]
Hi @zhangkom do you still need help on this issue?

**Comment by zulkifli-halim** [comment]
Case closed due to no further comments received.
