### ISSUE TITLE
[Bug]Device with "CPU" name is not registered in the InferenceEngine

### ISSUE THREAD

**Issue by zhangkom** [openvinotoolkit/openvino#4535]
android platform.
        // Initialize model
        IECore core = new IECore("/storage/emulated/0/models_bin/plugins.xml");
        CNNNetwork net = core.ReadNetwork("/storage/emulated/0/openvino/asl-recognition-0004.xml");
        Map<String, InputInfo> inputsInfo = net.getInputsInfo();
        inputName = new ArrayList<>(inputsInfo.keySet()).get(0);
        InputInfo inputInfo = inputsInfo.get(inputName);

        inputInfo.setLayout(Layout.NDHWC);
        inputInfo.setPrecision(Precision.U8);

        ExecutableNetwork executableNetwork = core.LoadNetwork(net, "CPU");

    InferenceEngineException: 
    	LoadNetwork: GetCPPPluginByName Device with "CPU" name is not registered in the InferenceEngine
        at org.intel.openvino.IECore.LoadNetwork(Native Method)
        at org.intel.openvino.IECore.LoadNetwork(IECore.java:25)
        at com.miguai.openvino_demo.MainActivity.onCreate(MainActivity.java:67)

**Comment by brmarkus** [comment]
When you say "Android platform", do you mean running on an Intel CPU, an Intel SOC? OpenVINO requires an Intel CPU (except for the OpenVINO on ARM, a special installation/distribution for e.g. Rhaspberry, "https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_raspbian.html", which, however, isn't an Android environment).

Can you run the sample-demo "hello_query_device" and check, whether the CPU gets detected as supported device?
On a modern Intel SOC you would get CPU, GNA, GPU (when an embedded/discrete Intel-GPU gets detected). With additional, external accelerators, you could get MYRIAD, HDDL and FPGA in addition.

**Comment by zhangkom** [comment]
@ brmarkus Thanks a lot, I run it on ARM with Android OS. Please help me, how can I resolve the issue.

**Comment by brmarkus** [comment]
Can you run "hello_query_device" as C/C++ or Python application first, to see whether OpenVINO detects the ARM CPU?

I haven't tried the installation/distribution of OpenVINO for ARM and Raspbian, but the description under "https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_raspbian.html" only mentions the InferenceEngine and MyriadX plugin; use of the ARM-CPU for inference is not mentioned...

Maybe it's not supported as it's not an Intel CPU, can someone else confirm, please?

**Comment by vladimir-paramuzov** [comment]
@zhangkom If you want to use ARM CPU as a target inference device, then you need ARM plugin (https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin) 

cc @l-bat for further questions

**Comment by zhangkom** [comment]
@brmarkus @vladimir-paramuzov  Thank you, the "CPU" error is solved. And I use  "vehicle-license-plate-detection-barrier-0106" model to run, but got the error as following, please help me, thank you!
	
SetLayout: Size of dims(4) and format(NDHWC) are inconsistent.
        at org.intel.openvino.InputInfo.SetLayout(Native Method)

**Comment by zhangkom** [comment]
@vladimir-paramuzov  @brmarkus Thank you, I will try and send the result here.

**Comment by zhangkom** [comment]
@vladimir-paramuzov I have another issue as following:
The page show:
2 Download model yolo_v3_tiny using model downloader:
python3 ./downloader.py --name yolo_v3_tiny --precisions FP32

And I do this:
python3 ./downloader.py --name yolo_v3_tiny --precisions FP32
No matching models: "yolo_v3_tiny"

**Comment by l-bat** [comment]
> show:
> 2 Download model yolo_v3_tiny using model downloader:
> python3 ./downloader.py --name yolo_v3_tiny --precisions FP32
> 
> And I do this:

Please, try `python3 ./downloader.py --name yolo-v3-tiny-tf --precisions FP32`. PR with fix: openvinotoolkit/openvino_contrib#56

**Comment by zhangkom** [comment]
@l-bat @vladimir-paramuzov @brmarkus Thank you for your help. I have follow the "https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin" step by step, and I have got the OV_ARM_package.tar.gz. I push the object_detection_demo to Android device which is got from OV_ARM_package.tar.gz. It shows "/system/bin/sh: ./gaze_estimation_demo: No such file or directory"

**Comment by zhangkom** [comment]
and I call the openvino for jave api on armv7 platform with Android OS, and the code is following:

        CNNNetwork net = core.ReadNetwork("vehicle-license-plate-detection-barrier-0106.xml");
        ExecutableNetwork executableNetwork = core.LoadNetwork(net, "ARM");

But I got the error:
"Arm Plugin supports only ngraph cnn network representation"

Is the model is not correct which I use? Which model can been supported on Arm platform? @vladimir-paramuzov @brmarkus @I-bat Please help me, thanks a lot.

**Comment by l-bat** [comment]
@zhangkom Do you use the latest model from https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/vehicle-license-plate-detection-barrier-0106?

**Comment by zhangkom** [comment]
@I-bat Thanks a lot, After I replace the model file, it works.

**Comment by zhangkom** [comment]
@brmarkus @vladimir-paramuzov @l-bat Thanks a lot.
