### ISSUE TITLE
The DeprecationWarning cannot be ignored

### ISSUE THREAD

**Issue by Simonlyym** [openvinotoolkit/openvino#455]
I use yolov3's python sample code for my model, but each time I detect a picture I get the following error:
DeprecationWarning:Please use shape property of DataPtr instead objects returned by in_data or out_data property to access shape of input or output data on corresponding ports
Out_blob = out_blob. Reshape (net. The layers [net. The layers [layer_name]. Parents [0]]. Shape)
How can I ignore this warning
Neither of the following methods works
The import warnings
Warnings. Filterwarnings (' ignore ')
Python -w ignores file. Py

**Comment by leavim** [comment]
Hi @Simonlyym ,

You can modify the object_detection_demo_yolov3_async.py script and change first line to look like `#!/usr/bin/env python -W ignore::DeprecationWarning`. This should ignore the warnings you see at runtime. 

Regards,
Luis
