### ISSUE TITLE
No sample_data folder found in the inference_engine folder

### ISSUE THREAD

**Issue by KunalArora** [openvinotoolkit/openvino#456]
The samples_data folder is missing in the inference_engine/samples directory as mentioned in the get_started_linux.md file

**Comment by ilya-lavrenov** [comment]
@KunalArora  could you please provide a link to the page where it's stated? I failed to find this place.

**Comment by KunalArora** [comment]
In the following page, https://github.com/openvinotoolkit/openvino/blob/2020/get-started-linux.md if you go all the way to "Run the Image Classification Sample Application" for CPU, it is passing the -i with "<DLDT_DIR>/inference-engine/samples/sample_data/car.png" value whereas, the samples folder is not present in the inference-engine folder. 

So, either add the samples folder with sample_data or update the README.md accordingly

**Comment by ilya-lavrenov** [comment]
@asuhov could you please fix?

**Comment by ilya-lavrenov** [comment]
@asuhov could you please fix?

**Comment by asuhov** [comment]
The samples data is now preset in the https://github.com/openvinotoolkit/openvino/tree/master/scripts/demo folder. We will update documentation, thank you.

**Comment by asuhov** [comment]
Documentation has been fixed:
https://github.com/openvinotoolkit/openvino/blob/releases/2020/4/get-started-linux.md
