### ISSUE TITLE
does inference engine support C api?

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/openvino#458]
does inference engine support C api? thanks.

**Comment by ArtemSkrebkov** [comment]
Yes. Please see https://github.com/opencv/dldt/blob/2020/inference-engine/ie_bridges/c/include/c_api/ie_c_api.h for details

**Comment by guoyejun** [comment]
thanks

**Comment by guoyejun** [comment]
and another question, how to get the C library binary, just like https://www.tensorflow.org/install/lang_c, thanks.

**Comment by ArtemSkrebkov** [comment]
I see two ways:
* build on your own using [this tutorial](https://github.com/openvinotoolkit/dldt/blob/2020/build-instruction.md). I will find the `c_api` library next to all other binary once you build the whole project.
* download SDK from [this place](https://software.intel.com/en-us/openvino-toolkit/choose-download). The SDK contains a binary for the `c_api` library.

**Comment by guoyejun** [comment]
thanks, just checked install_dependencies.sh and found that gstreamer/ffmpeg are dependencies, actually, they are not required for dnn inference only engine. 

It would be better that we have a single command to build the inference c library. I'm thinking about add openvino support into ffmepg dnn backend (upstream), the community would be more acceptable if we can easily get the inference c library.

**Comment by guoyejun** [comment]
i tried the build but met the following issue. I've done 'pip install ngraph-core', but still the same issue. could you help on this? thanks.

i'm using the following commit:
commit 95a57795dcb0ed82324af87918339225148202ca
Author: Alexey Suhov <alexey.suhov@intel.com>
Date:   Mon Apr 13 21:17:23 2020 +0300
    Publishing 2020.2 content


$ cmake -DENABLE_VALIDATION_SET=OFF         -DCMAKE_INSTALL_PREFIX=../install         -DLIB_INSTALL_PATH=../install          -DENABLE_MKL_DNN=ON         -DTHREADING=OMP         -DENABLE_GNA=OFF         -DENABLE_CLDNN=OFF         -DENABLE_MYRIAD=OFF         -DENABLE_VPU=OFF         -DENABLE_SAMPLE_CORE=OFF         -DENABLE_OPENCV=OFF ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CMAKE_BUILD_TYPE: Release
-- Detected 64 bit architecture
-- Inference Engine enabled features: 
-- 
--     CI_BUILD_NUMBER: custom_2020_95a57795dcb0ed82324af87918339225148202ca
--     ENABLE_MKL_DNN = ON
--     ENABLE_CLDNN = OFF
--     ENABLE_LTO = OFF
--     OS_FOLDER = OFF
--     TREAT_WARNING_AS_ERROR = ON
--     ENABLE_SANITIZER = OFF
--     ENABLE_THREAD_SANITIZER = OFF
--     COVERAGE = OFF
--     ENABLE_SSE42 = ON
--     ENABLE_AVX2 = ON
--     ENABLE_AVX512F = ON
-- 
-- Found Wget: /usr/bin/wget  
-- PROJECT ............................... OpenVINO
-- CMAKE_BINARY_DIR ...................... /work/ml/openvino_work/dldt/build
-- OpenVINO_MAIN_SOURCE_DIR .............. /work/ml/openvino_work/dldt
-- IE_MAIN_SOURCE_DIR .............. /work/ml/openvino_work/dldt/inference-engine
-- CMAKE_GENERATOR ....................... Unix Makefiles
-- CMAKE_C_COMPILER_ID ................... GNU
-- CMAKE_BUILD_TYPE ...................... Release
CMake Error at CMakeLists.txt:114 (add_subdirectory):
  add_subdirectory given source "ngraph" which is not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:117 (build_ngraph)


-- INTEL_VTUNE_DIR is not defined
-- Could NOT find INTEL_ITT (missing: Located_ITT_INCLUDE_DIRS Located_ITT_LIBS) 
-- Inference Engine enabled features: 
-- 
--     CI_BUILD_NUMBER: custom_2020_95a57795dcb0ed82324af87918339225148202ca
--     ENABLE_MKL_DNN = ON
--     ENABLE_CLDNN = OFF
--     ENABLE_LTO = OFF
--     OS_FOLDER = OFF
--     TREAT_WARNING_AS_ERROR = ON
--     ENABLE_SANITIZER = OFF
--     ENABLE_THREAD_SANITIZER = OFF
--     COVERAGE = OFF
--     ENABLE_SSE42 = ON
--     ENABLE_AVX2 = ON
--     ENABLE_AVX512F = ON
--     ENABLE_GNA = OFF
--     ENABLE_CLDNN_TESTS = OFF
--     ENABLE_PROFILING_ITT = ON
--     GEMM = JIT
--     THREADING = OMP
--     ENABLE_IR_READER = ON
--     ENABLE_VPU = OFF
--     ENABLE_MYRIAD = OFF
--     ENABLE_MYRIAD_NO_BOOT = OFF
--     ENABLE_TESTS = OFF
--     ENABLE_GAPI_TESTS = OFF
--     GAPI_TEST_PERF = OFF
--     ENABLE_MYRIAD_MVNC_TESTS = OFF
--     ENABLE_SAMPLES = ON
--     ENABLE_BEH_TESTS = OFF
--     ENABLE_FUNCTIONAL_TESTS = OFF
--     ENABLE_SAMPLES = ON
--     ENABLE_FUZZING = OFF
--     VERBOSE_BUILD = OFF
--     ENABLE_UNSAFE_LOCATIONS = OFF
--     ENABLE_ALTERNATIVE_TEMP = ON
--     ENABLE_OPENCV = OFF
--     ENABLE_DEBUG_SYMBOLS = OFF
--     ENABLE_PYTHON = OFF
--     ENABLE_CPP_CCT = OFF
--     ENABLE_C = ON
--     ENABLE_CPPLINT = OFF
--     ENABLE_CPPLINT_REPORT = OFF
--     ENABLE_CLANG_FORMAT = OFF
--     ENABLE_TBB_RELEASE_ONLY = OFF
-- 
CMake Error at inference-engine/CMakeLists.txt:32 (find_package):
  By not providing "Findngraph.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ngraph", but
  CMake did not find one.

  Could not find a package configuration file provided by "ngraph" with any
  of the following names:

    ngraphConfig.cmake
    ngraph-config.cmake

  Add the installation prefix of "ngraph" to CMAKE_PREFIX_PATH or set
  "ngraph_DIR" to a directory containing one of the above files.  If "ngraph"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/work/ml/openvino_work/dldt/build/CMakeFiles/CMakeOutput.log".
See also "/work/ml/openvino_work/dldt/build/CMakeFiles/CMakeError.log".

**Comment by guoyejun** [comment]
another question is: is there any .pc file for the c library? So, I can detect if the current system supports openvino c library in makefile. thanks.

**Comment by guoyejun** [comment]
hi, i copied the libinference_engine_c_api.so and some other .so files to /usr/local/lib/, but looks that still the .so files under openvino source tree are used, how to let the application use the so files under /usr/local/lib/, thanks.
```
(gdb) info sharedlibrary
From                To                  Syms Read   Shared Object Library
0x00007ffff5e90a70  0x00007ffff5ed74f4  Yes         /usr/local/lib/libinference_engine_c_api.so
0x00007ffff21a5230  0x00007ffff24a611d  Yes         /work/ml/openvino_work/dldt/bin/intel64/Debug/lib/libinference_engine.so
0x00007ffff168fcf0  0x00007ffff19e03db  Yes         /work/ml/openvino_work/dldt/bin/intel64/Debug/lib/libinference_engine_legacy.so
...
```
```
$ ls /usr/local/lib/libinference_engine*
/usr/local/lib/libinference_engine_c_api.so   /usr/local/lib/libinference_engine.so
/usr/local/lib/libinference_engine_legacy.so  /usr/local/lib/libinference_engine_transformations.so
```

**Comment by brmarkus** [comment]
You probably called "/opt/intel/openvino/bin/setupvars.sh", which sets the LD_LIBRARY_PATH environment variable.
If you add your path to LD_LIBRARY_PATH, will the copied libraries be found then?

**Comment by guoyejun** [comment]
the LD_LIBRARY_PATH points to my path, not the openvino path.
```
$ export | grep LD
declare -x LD_LIBRARY_PATH="/usr/local/lib:/opt/intel/mediasdk/lib/"
declare -x OLDPWD
```

and here is my command to cmake:
```
  cmake -DENABLE_VALIDATION_SET=OFF \
        -DCMAKE_INSTALL_PREFIX=../install \
        -DLIB_INSTALL_PATH=../install  \
        -DENABLE_MKL_DNN=ON \
        -DTHREADING=OMP \
        -DENABLE_GNA=OFF \
        -DENABLE_CLDNN=OFF \
        -DENABLE_MYRIAD=OFF \
        -DENABLE_VPU=OFF \
        -DENABLE_OPENCV=OFF \
        -DCMAKE_BUILD_TYPE=Debug \
         ..

```

**Comment by guoyejun** [comment]
i tried the default build option and make install to /usr/local/deployment_tools/inference_engine, then it works as expected.
