### ISSUE TITLE
FeatureRequest: Convert IR to ONNX

### ISSUE THREAD

**Issue by Laubeee** [openvinotoolkit/openvino#4615]
I was wondering whether this will be supported in the future, as you have started to support onnx more extensively  
Exporting (optimized) models to onnx would make it possible to compare different Frameworks more reliably

**Comment by Iffa-Meah** [comment]
Hi,

Thanks for reaching out.
The conversion of IR back to the model is not supported and it seems that it would not be supported in the future too.

Are you actually trying to find some original ONNX model based on an existing IR as in Open Model Zoo?
If this is the case, we could help you to find one.

**Comment by Laubeee** [comment]
That is one of the use cases, yes. I'm evaluating different pose detectors, so I'd be interested in Human-Pose-Estimation-000*
I didn't find any of those as onnx though.

Another use case is converting from another model like TF, e.g. EfficientPose. Converting it to IR gives reasonable performance results and respective performance boost for both GPU and FP16 inference. However, converting the model to .onnx, e.g. using tf2onnx (which works, but is probably far from optimal), and running it with DirectML performs quite a bit worse, and there seems to be almost zero benefit from using GPU and/or FP16.

Unfortunately I can't run the same .onnx model with OpenVINO (yet?)
When trying to load it I get
```
\jenkins\workspace\OpenCV\OpenVINO\2021.2\build\windows\opencv\modules\dnn\src\layers\convolution_layer.cpp:96: error: (-213:The function/feature is not implemented) Unsupported asymmetric padding in convolution layer in function 'cv::dnn::BaseConvolutionLayerImpl::BaseConvolutionLayerImpl'
```

but even then, depending on the observed performance, I wouldn't know whether the IR version performs better due to model optimization (which might or might not be possible to be fully represented as .onnx as well) or "framework/runtime optimization"

**Comment by Iffa-Meah** [comment]
Generally, you can't use any model in its original form with OpenVINO, you need to convert them to IR.

There are a lot of human pose estimation sample models in Pytorch, so you'll need to convert them to onnx by yourself.
[This](https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch) might helps you.

**Comment by Laubeee** [comment]
Thanks I'll try to convert to ONNX form pytorch for that case.

> Generally, you can't use any model in its original form with OpenVINO, you need to convert them to IR.

The [docs](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_ONNX_Support.html) state its possible though, to load onnx directly in OpenVINO? which is kind of why I was hoping you'd provide conversion from IR to ONNX too at some point, hence the question / feature request :D

**Comment by Iffa-Meah** [comment]
Thanks for mentioning that documentation lol.
Those in the documentations are meant to be used with the OpenVINO inference engine but I can see that you are actually using cv::dnn (OpenCV DNN) to load the native onnx model.

If you intended to use the model as per document, you'll need to use OpenVINO toolkit.

**Comment by Laubeee** [comment]
Sorry for the late reply. I AM using openvino - it comes with its custom OpenCV-build, which can also read IR files through the cv2.dnn module. Are you saying reading ONNX is not available through the Python API?

**Comment by jgespino** [comment]
Hi @Laubeee 

The OpenVINO toolkit does include an OpenCV build along with the inference engine. You should be able to load the ONNX model or IR to the benchmark_app for performance measurements. The benchmark_app is available in Python and C++. Regarding OpenCV DNN question, I recommend asking on the OpenCV forum to get an accurate response as I am not too familiar with it. 

Currently, there is no way to convert IR models back to their native framework. I am not sure this will be supported but I could pass the your feedback on to the development team for consideration.

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, currently there are no plans to enable this feature request.

**Comment by Hezhongwang** [comment]
> 

Hi 
I want to convert person-detection-0301 from openvino to onnx, but I find it not easy. 

Can you help me find the origin ONNX model based on  person-detection-0301 Openvino IR

Thanks

https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/1/person-detection-0301/FP32/person-detection-0301.xml

https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/1/person-detection-0301/FP32/person-detection-0301.bin

**Comment by jgespino** [comment]
@Hezhongwang Converting from OpenVINO IR format to ONNX is not possible. All available information regarding this model can be found here: https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/person-detection-0301

If you have any additional questions, please start a new issue.

**Comment by TouqeerAhmad** [comment]
This could be a very helpful feature for people working on NVIDIA GPUs. 
Here is my scenario that triggered me searching "converting OpenVINO IR to ONNX" and landed here:
 
I used one of the OpenVINO Notebooks that ran a Post Training Static Quantization and converted a PyTorch model to an INT8 quantized mode on CPU with reasonable performance. As I want to run the quantized model on NVIDIA gpu, a conversion from IR to ONNX or to TRT Engine would have been great and saves me time replicating the full PTSQ pipeline on a platform compatible with NVIDIA.
