### ISSUE TITLE
OpenVINO install break OpenCL environment

### ISSUE THREAD

**Issue by JacekDanecki** [openvinotoolkit/openvino#465]
Issue moved from [Neo issue](https://github.com/intel/compute-runtime/issues/301), as the problem is with OpenVINO installer.

**Comment by dkurt** [comment]
@wdkwyf, Hi!

Have you installed OpenVINO by GUI installer or by the script or by `apt-get`?

**Comment by wdkwyf** [comment]
@dkurt ,Hi!
I install OpenVINO by the script `install.sh`

**Comment by dkurt** [comment]
Can reproduce it:

1. Install NEO

2. clinfo
```
$ clinfo 
Number of platforms                               1
  Platform Name                                   Intel(R) OpenCL HD Graphics
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 2.1 
...
  Platform Name                                   Intel(R) OpenCL HD Graphics
Number of devices                                 1
  Device Name                                     Intel(R) Gen9 HD Graphics NEO
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.1 NEO 
  Driver Version                                  20.06.15619
...
```

3. Install OpenVINO
```
~/Downloads/l_openvino_toolkit_p_2020.2.120$ sudo ./install.sh
Enter
q
accept
2 (do no concern)
1 (Skip prerequisites)
q
1 (accept config)
Enter
```

4. clinfo once again
```
$ clinfo
Number of platforms                               0
```

**Comment by dkurt** [comment]
@wdkwyf, Can you please try to deselect Media SDK?
Choose
```
2. Customize installation
```
then
```
3. Change components to install [ All ]
```
choose 7:
```
7. [All] Intel(R) Media SDK
```
```
1. Accept and continue [ default ]
2. [x] Intel(R) Media SDK
  3. [x] Intel(R) Media SDK
```
Type 2 to deselect, then 1 to accept

How it should looks like finally:
```
1. Accept and continue [ default ]
2. [All] Inference Engine
3. [All] Model Optimizer
4. [All] Deep Learning Workbench
5. [All] OpenCV*
6. [All] Open Model Zoo
7. [None] Intel(R) Media SDK
8. [All] DL Streamer
```
Then OpenCL works fine.

**Comment by wdkwyf** [comment]
@dkurt Thanks. It works. I wonder if it's a bug...Why Media SDK install cleaned my NEO environment, it's strange...

**Comment by alalek** [comment]
Media SDK from OpenVINO overrides library search paths with own versions of libraries.
Conflicting libraries block loading of modern NEO OpenCL runtime (perhaps `libgmm` is one of them).

BTW, OpenCL blocking happens on whole user system, regardless of using of OpenVINO's "setupvars.sh".

**Comment by dkurt** [comment]
@wdkwyf, can you please also try to use `LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH ` with Media SDK component installed? It solved issue on my side as well.
