### ISSUE TITLE
Does OpenVino use oneDNN?

### ISSUE THREAD

**Issue by saiyajin-sp** [openvinotoolkit/openvino#466]
I'm using OpenVion version 2020.1.033 in one project.
Also, another project uses MKL-DNN (Intel MKL ver 2018.3.210), but I would like to replace it with oneDNN. In this case, I don't know the difference whether it is better to use oneDNN or replace with openVino.
Does OpenVino use oneDNN internally?

**Comment by dmitry-gorokhov** [comment]
@saiyajin-sp  OpenVINO uses [oneDNN fork](https://github.com/openvinotoolkit/oneDNN) internally. To be more specific fork is based on [v0.21.3](https://github.com/openvinotoolkit/oneDNN/releases/tag/v0.21.3) version of original repo and contains several [features ](https://github.com/openvinotoolkit/oneDNN/commits/v0.21_for_ie_master)applied above.

**Comment by saiyajin-sp** [comment]
@dmitry-gorokhov
Thank you for the information. 
Where can I find the relationship between versions?
If not, please consider adding it in the future.

Thanks.

**Comment by BillyONeal** [comment]
Considering oneDNN is at version 3.2, but the fork in use here is from 0.21, it seems like this makes it hard to include both oneDNN and openvino in a software repository...

**Comment by 2catycm** [comment]
So, which one has a better performance? It seems that OpenVINO and oneDNN are of the exaclty same function.

**Comment by wenjiew** [comment]
New oneDNN versions were integrated into OpenVINO as oneDNN releases are out. This question was from three years ago, and OpenVINO has upgraded the oneDNN version almost in every release. Latest release of OpenVINO 2023.1 will have oneDNN 3.2 release. 

OpenVINO provides deep learning network level acceleration, which is different with oneDNN. That is the reason that oneDNN was included in OpenVINO for underlying kernel implementation as buliding blocks.
https://www.intel.com/content/www/us/en/developer/tools/oneapi/onednn.html
