### ISSUE TITLE
while running demo_squeezenet_download_convert_run.sh Error on or near line 217; exiting with status 1

### ISSUE THREAD

**Issue by samruddhipp** [openvinotoolkit/openvino#4672]
##### System information (version)

- OpenVINO =>  Master Branch
- Operating System / Platform => Ubuntu 18.04.5 LTS
- Problem classification: Run Inference Engine classification sample

- cpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) CPU @ 2.00GHz
Stepping:            3
CPU MHz:             2000.200
BogoMIPS:            4000.40
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            39424K
NUMA node0 CPU(s):   0,1

##### Detailed description
I am Trying to install openvino from master branch  using [link](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux) in google colab

I am getting error while running  ./demo_squeezenet_download_convert_run.sh

####### ERROR  #######

Run Inference Engine classification sample

Run ./classification_sample_async -d CPU -i /opt/intel/openvino/deployment_tools/demo/car.png -m /root/openvino_models/ir/public/squeezenet1.1/FP16/squeezenet1.1.xml

[ INFO ] InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_master_7f8d3aa63899a3e3362c95eb7d1b04a5899660bd
	Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     /opt/intel/openvino/deployment_tools/demo/car.png
[ INFO ] Creating Inference Engine
	CPU
	MKLDNNPlugin version ......... 2.1
	Build ........... custom_master_7f8d3aa63899a3e3362c95eb7d1b04a5899660bd

[ INFO ] Loading network files
[ INFO ] Preparing input blobs
[ WARNING ] Image /opt/intel/openvino/deployment_tools/demo/car.png cannot be read!
[ ERROR ] Valid input images were not found!
Error on or near line 217; exiting with status 1
##### Steps to reproduce
I ran following commands in colab (cpu only)

```
!git clone https://github.com/openvinotoolkit/openvino.git
!cd openvino && git submodule update --init --recursive
!cd openvino && chmod +x install_build_dependencies.sh
!cd openvino && ./install_build_dependencies.sh
!mkdir openvino/build
!cd openvino/build && cmake -DCMAKE_BUILD_TYPE=Release ..
!cd openvino/build  && make --jobs=$(nproc --all)
!cd openvino/build && cmake  --install . --prefix /opt/intel/openvino 


!git clone https://github.com/openvinotoolkit/open_model_zoo.git
!cmake -E copy_directory ./open_model_zoo/ /opt/intel/openvino/deployment_tools/open_model_zoo/

%env LD_LIBRARY_PATH=/content/openvino/inference-engine/temp/opencv_4.5.1_ubuntu18/opencv/lib/
%env OpenCV_DIR=/content/openvino/inference-engine/temp/opencv_4.5.1_ubuntu18/opencv/cmake

!cd /opt/intel/openvino/deployment_tools/demo && ./demo_squeezenet_download_convert_run.sh

```

Detailed error log ./demo_squeezenet_download_convert_run.sh
[error.txt](https://github.com/openvinotoolkit/openvino/files/6096039/error.txt)

**Comment by Iffa-Meah** [comment]
Hi,

Somewhat I had faced the same problem. I solved it by downloading a new car photo. Remove or rename the readily available car.png and name the new car photo with the car.png name.

**Comment by samruddhipp** [comment]
Hi,
Thank you Iffa-Meah for quick response.

it worked with python 3.7
Thanks
