### ISSUE TITLE
TopK error from onnx model misses "k" attribute

### ISSUE THREAD

**Issue by buoyancy99** [openvinotoolkit/openvino#468]
File "/opt/intel/openvino_2019.3.376/deployment_tools/model_optimizer/extensions/front/TopKNormalize.py", line 38, in find_and_replace_pattern
    assert topk_node.has_valid('k'), 'The TopK node "{}" misses "k" attribute'.format(topk_node.name)
AssertionError: The TopK node "TopK_101" misses "k" attribute

 

Some debug gives me:

1. 'k' is not in self.graph.node["TopK_101"].keys()

2. However, 'k' is present in the attribute of self.graph.node["TopK_101"].['pb']

input: "253"
output: "254"
output: "255"
name: "TopK_101"
op_type: "TopK"
attribute {
  name: "axis"
  i: 3
  type: INT
}
attribute {
  name: "k"
  i: 100
  type: INT
}

**Comment by lazarevevgeny** [comment]
This is a known bug which occurs because of the specification change of the ONNX TopK operation. Previously it had 'K' as attribute and starting from opset-10 it is an input. 

@mvafin, please, make the TopK extractor capable support both cases.

**Comment by lazarevevgeny** [comment]
@jane-intel will take care of this issue.
