### ISSUE TITLE
while installing POT toolkit, post_training_optimization_toolkit folder not found 

### ISSUE THREAD

**Issue by rpatil117** [openvinotoolkit/openvino#4680]
##### Detailed description
[setup](https://github.com/openvinotoolkit/openvino/issues/4672)

I have to install openvino from master branch in google colab
I am trying to install POT tool from [docs](https://docs.openvinotoolkit.org/latest/pot_InstallationGuide.html) 

I have successfully installed install_prerequisites.sh  and accuracy_checker
I am NOT able to find  post_training_optimization_toolkit folder at /opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit

folder available at /opt/intel/openvino/deployment_tools/tools :
compile_tool

##### Steps to reproduce 

```
!git clone https://github.com/openvinotoolkit/openvino.git
!cd openvino && git submodule update --init --recursive
!cd openvino && chmod +x install_build_dependencies.sh
!cd openvino && ./install_build_dependencies.sh
!mkdir openvino/build
!cd openvino/build && cmake -DCMAKE_BUILD_TYPE=Release ..
!cd openvino/build  && make --jobs=$(nproc --all)
!cd openvino/build && cmake  --install . --prefix /opt/intel/openvino 


!git clone https://github.com/openvinotoolkit/open_model_zoo.git
!cmake -E copy_directory ./open_model_zoo/ /opt/intel/openvino/deployment_tools/open_model_zoo/

%env LD_LIBRARY_PATH=/content/openvino/inference-engine/temp/opencv_4.5.1_ubuntu18/opencv/lib/
%env OpenCV_DIR=/content/openvino/inference-engine/temp/opencv_4.5.1_ubuntu18/opencv/cmake

!cd /opt/intel/openvino/deployment_tools/demo && ./demo_squeezenet_download_convert_run.sh
```
I have replaced "car.png" image as mentioned in [link](https://github.com/openvinotoolkit/openvino/issues/4672)

Thanks

**Comment by Iffa-Meah** [comment]
It seems the POT is not included with the OpenVINO open source build.
You may try this [quantizer](https://github.com/openvinotoolkit/open_model_zoo/tree/master/tools/downloader) in the open model zoo instead.
They should have the same functionality.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
