### ISSUE TITLE
Error loading TopK 

### ISSUE THREAD

**Issue by buoyancy99** [openvinotoolkit/openvino#470]
I am debugging networks that contains TopK layer converted from onnx, it seems TopK causes errors when loading network.

ExecutableNetwork executable_network = ie.LoadNetwork(network, device);

The error persists after I try a single TopK layer onnx model as follows:

![Screenshot from 2020-04-25 21-47-44](https://user-images.githubusercontent.com/16475227/80298206-aee22600-873e-11ea-99ee-58f4329611d4.png)

This onnx is generated with
```
class TopKTest(nn.Module):
    def forward(self, x):
        _, idx = torch.topk(x, k=5, dim=3)
        return idx

torch.onnx.export(TopKTest(), torch.zeros((1, 2, 5, 10)), "debug.onnx")
```
and then converted with mo.py
```
python3 /opt/intel/openvino/deployment_tools/model_optimizer/mo.py --input_model debug.onnx --model_name debugtopk --data_type FP16 --batch 1
```

**Comment by leavim** [comment]
@buoyancy99 which version of OpenVINO are you using? Gave a quick try at your onnx model and cannot convert to IR using provided MO command, I get an _Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'extensions.front.TopKNormalize.TopKNormalize'>)": The TopK node "TopK_0" misses "k" attribute_. 

Specifying _opset_version>=10_ in export model line seems to convert IR fine. Please try this and check if issue persists. `torch.onnx.export(TopKTest(), torch.zeros((1, 2, 5, 10)), "debug.onnx", opset_version=10)`

Also share environment details, device used for inference and more information of error received when executing `ExecutableNetwork executable_network = ie.LoadNetwork(network, device).`

Regards,
Luis

**Comment by lazarevevgeny** [comment]
@buoyancy99 , what error do you see when you run the model with IE?

**Comment by buoyancy99** [comment]
> @buoyancy99 , what error do you see when you run the model with IE?

I think this is related to not specifying newer version opset when exporting. However, I am currently busy with other projects so haven't had a chance to test things yet
