### ISSUE TITLE
_ZN3tbb8internal13numa_topology11nodes_countEv error when running hello_classification sample

### ISSUE THREAD

**Issue by nvallez** [openvinotoolkit/openvino#473]
Hi,

I have downloaded the 2020.2 version and build it. However, when I tried to run one of the samples, the _hello_classification_, I am getting the following error:

_./hello_classification: symbol lookup error: /................./dldt_2020.2/bin/intel64/Debug/lib/libinference_engine.so: undefined symbol: _ZN3tbb8internal13numa_topology11nodes_countEv_

I have not had any problems before with 2019R3 or 2020.1. Model optimizer and compile tools work.

Regards.

**Comment by dmitry-gorokhov** [comment]
@nvallez  It looks like your libinference_engine.so lib was linked with wrong version of TBB library (maybe system one). OpenVINO has strong requirement to use TBB from distribution package. May I ask you to try to explicitly link with this version (should be on this path: dldt/inference-engine/temp/tbb)?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
