### ISSUE TITLE
Failed to initialize IE backend

### ISSUE THREAD

**Issue by Strimblaster** [openvinotoolkit/openvino#477]
So, I've been trying to compile OpenCV with Inference Engine for quite some time because i need FFmpeg 4 support because I have problems with Gstreamer perfomance on OpenVINO toolkit.

- Operating System: Raspbian Buster

- Raspberry Pi 4

- Intel NCS2 

I followed OpenCV documentation about compiling OpenCV with IE. [guide](https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend#raspbian-buster)

I managed to compile OpenCV 4.2.0 with IE:
` Inference Engine:            YES (2020010000 / 2.1.0)
        * libs:                  /l_openvino_toolkit_runtime_raspbian_p_2020.1.023/deployment_tools/inference_engine/lib/armv7l/libinference_engine_c_api.so
        * includes:              /l_openvino_toolkit_runtime_raspbian_p_2020.1.023/deployment_tools/inference_engine/include
    nGraph:                      YES (0.27.1-rc.0+b0bb801)
        * libs:                  /l_openvino_toolkit_runtime_raspbian_p_2020.1.023/deployment_tools/ngraph/lib/libngraph.so
        * includes:              /l_openvino_toolkit_runtime_raspbian_p_2020.1.023/deployment_tools/ngraph/include
`
After that, I dont know what env variables I should use because if I only set up OpenCV variables, it misses libinference_engine_c_api.so importing cv2 so I used openvino/bin/setupvars.sh and then OpenCV variables to import sucessfully.

The problem comes when i try to run something, I get this error:
cv2.error: OpenCV(4.2.0) /opencv/modules/dnn/src/op_inf_engine.cpp:774: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = MYRIAD): Device with "CPU" name is not registered in the InferenceEngine in function 'initPlugin'

I'm sorry if this isn't supposed to be posted here

Obs:
- I did apply usb rules
- My code sets preferable backend and target (and it works with downloaded OpenVINO toolkit)         
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_MYRIAD)
- lsusb shows Intel Movidius MyriadX

**Comment by alalek** [comment]
> OpenCV(4.2.0)

This community version was released before OpenVINO 2020.1, so important fixes for OpenVINO 2020.1 are just missing.

Please try to use OpenCV sources:
- [4.2.0-openvino](https://github.com/opencv/opencv/releases/tag/4.2.0-openvino) (OpenVINO 2020.1)
- [4.3.0-openvino](https://github.com/opencv/opencv/releases/tag/4.3.0-openvino) (OpenVINO 2020.2)
- or latest code from maintained branches (master, 3.4)

---

OpenCV may require CPU IE plugin even with Myriad devices to process "custom" OpenCV-specific layers.
What is model used?

/cc @dkurt

**Comment by Strimblaster** [comment]
> Please try to use OpenCV sources:
> 
> * [4.2.0-openvino](https://github.com/opencv/opencv/releases/tag/4.2.0-openvino) (OpenVINO 2020.1)

Thank you, it worked! 

> OpenCV may require CPU IE plugin even with Myriad devices to process "custom" OpenCV-specific layers.
> What is model used?
MobileNetSSD

Can I close this?
