### ISSUE TITLE
how to use openvino infer dynamic model

### ISSUE THREAD

**Issue by shixinlishixinli** [openvinotoolkit/openvino#4783]
##### System information (version)

- OpenVINO => 2021.1
- Operating System / Platform => ubuntu1804
- Problem classification: IE and MO
- Framework: onnx (if applicable)
- Model name: paddle OCR(if applicable)

##### Detailed description

i have tried to use a dynamic OCR onnx model converted by paddle OCR. When I set the input_shape of MO, the accuracy of the OCR neural network will drop.  the input_shape of onnx model is [1,3,32,-1], so it can recognize long or short languages. 

do the OpenVINO can infer dynamic model?

best
Lisa Shi

**Comment by shixinlishixinli** [comment]
when i use openvino inference onnx model directly, the bug is 
RuntimeError: Check '(data_shape[i].is_static())' failed at ngraph/frontend/onnx_import/src/utils/pooling_factory.cpp:89:
While validating ONNX node '<Node(GlobalAveragePool): GlobalAveragePool@0>':
All spatial dimensions must be known for global pooling ops

**Comment by shixinlishixinli** [comment]
by the way , i need to use --static_shape in MO to support scatternd layer

**Comment by Iffa-Meah** [comment]
check these out:
[Dynamic Batching](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_DynamicBatching.html)
[Reshape and Batch](https://www.youtube.com/watch?v=Ga8j0lgi-OQ)

**Comment by shixinlishixinli** [comment]
thanks for your reply.  My question is not how to use batch_size.

paddle OCR is a useful ocr model. and i have converted paddle OCR model from paddlepaddle  to openvino .   and i have  used IE inference this model .  Recognition of short sentences is good , but the recognition of long sentences is bad . 

the input_shape of openvino OCR model is fixed  ,so the pictures of long sentences  are severely deformed to adapt the input_shape. i do not want to MO the model for each pictures of sentences.

for example, the picture of  short sentence is [32,80 ,3] the picture of long sentence is [32,10000,3], the input_shape is [32,100,3],. all the pictures need to resize.   Recognition of short sentences is good , but the recognition of long sentences is bad .   i do not want to MO the model for each pictures of sentences. 

in onnx , when the input_shape is [32,-1,3], it means the -1 can be any number , the model can inference all the pictures successfully . Do the openvino have the same functions.

i am looking forward to your reply
best
Lisa Shi

**Comment by Iffa-Meah** [comment]
The Onnx model defines a dynamic shape when  -1 is used & it would automatically infer pictures accordingly.
Generally, in OpenVINO, the model optimizer handles the shapes of inputs without the needs to re-train the model,
by using command - -input_shape[x,y,z,w]. The size for inputs down the pipelines are then adjusted based on that.

According to case [#436](https://github.com/openvinotoolkit/openvino/issues/436), OpenVINO does not allow generating an IR with unknown input shapes, so some fixed shape need to be chosen and then changed using the reshape method. This means that OpenVINO only supports static shape infer.

**Comment by shixinlishixinli** [comment]
in this case, i convert 10 models of different input to solve this question.

**Comment by luvwinnie** [comment]
@shixinlishixinli I have a same OCR which handle dynamic width, how would you operates 10 models with different input?
