### ISSUE TITLE
[VPU] Unexpected CNNNetwork format

### ISSUE THREAD

**Issue by fujunwei** [openvinotoolkit/openvino#479]
For the latest 2020.2 version, A network created with deprecated NN Builder API can work on IE-MKLDNN, IE-CLDNN and IE-GNA plugin, but it will throw below error message when running on VPU.

https://github.com/openvinotoolkit/openvino/blob/2020/inference-engine/src/vpu/graph_transformer/src/frontend/detect_network_batch.cpp#L44

> VPU_THROW_UNLESS(!checkForDeprecatedCnn(), "Unexpected CNNNetwork format: it was converted to deprecated format prior plugin's call");

Does it means the network must be created with `nGraph`? Do we have any other approach to support NN Builder Network on VPU?

**Comment by dkurt** [comment]
Hi!

OpenCV tests both NNBuilder and nGraph APIs for network creation in runtime. They can still work but there are some limitations - you cannot use layers iterator and some of the deprecated methods. If so, the network will be internally converted to old representation.

See https://github.com/opencv/opencv/pull/17134 and https://github.com/opencv/opencv/pull/16687

**Comment by fujunwei** [comment]
Thanks so much.

[SqueezeNet](https://s3.amazonaws.com/onnx-model-zoo/squeezenet/squeezenet1.1/squeezenet1.1.onnx) can work as expected but failing to run [MobileNetV1](https://drive.google.com/drive/folders/1TIdN3MepLthIyvYDNumAhY_hdoxtOW96), i file a new [issue-493](https://github.com/openvinotoolkit/openvino/issues/493). welcome your comments, thanks.
