### ISSUE TITLE
Text Recognition model incompatible with Raspberry Pi 4 & NCS2[Bug]

### ISSUE THREAD

**Issue by lvbenson** [openvinotoolkit/openvino#4795]
- OpenVINO => l_openvino_toolkit_runtime_raspbian_p_2021.2.18..>
- Operating System / Platform => Raspberry Pi 4 Model B
- Problem classification: Open Model Zoo models 
- Model name: Text Recognition 
-
Some of the models in Open Model Zoo seem to be incompatible with the raspberry pi.... in particular, the Text Recognition model produces this error: 

    exec_net_rec = ie.load_network(network=net_rec, device_name=args["device"])
    File "ie_api.pyx", line 311, in openvino.inference_engine.ie_api.IECore.load_network
    File "ie_api.pyx", line 320, in openvino.inference_engine.ie_api.IECore.load_network
    RuntimeError: Check 'shape_size(inputs[0]->get_shape()) == shape_size(output_shape)' failed at 
    ngraph/core/src/op/reshape.cpp:395:
While validating node 'v1::Reshape Reshape_8529 (Constant_8538[0]:f16{1,37}, Constant_8528[0]:i64{1}) -> (f16{37})' with friendly_name 'Reshape_8529':
Requested output shape Shape{4294967295} is incompatible with input shape Shape{1, 37}

I saw that some people had had similar issues with previous versions of the raspberry pi openvino install and Open Model Zoo, but it was supposed to be fixed by 2021.2.... 

This doesn't happen with ALL the pretrained models, only some.
Any help would be greatly appreciated.

**Comment by dkurt** [comment]
Hi! Can you try more recent build? [openvino_debian10_armhf](https://github.com/dkurt/vineyard/suites/1984449765/artifacts/39527493) (Feb, 7)

**Comment by jgespino** [comment]
Closing, please feel free to re-open if additional assistance is needed.
