### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by wanghanyang123** [openvinotoolkit/openvino#48]
When i cmake by "cmake -DCMAKE_BUILD_TYPE=Release ..", there will be:

-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- [clDNN] Selected capabilities: public
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - found
-- Looking for strtoll
-- Looking for strtoll - found
-- Found OpenCV: /home/why/openvino/dldt-2018/inference-engine/temp/opencv_4.0.0_ubuntu (found version "4.0.0") 
-- Validation app build is switched off
-- Configuring incomplete, errors occurred!
See also "/home/why/openvino/dldt-2018/inference-engine/build/CMakeFiles/CMakeOutput.log".
See also "/home/why/openvino/dldt-2018/inference-engine/build/CMakeFiles/CMakeError.log".

How to solve this?

**Comment by SeverineH** [comment]
can you show the full cmake generation text? I can not see any error before the configuring incomplete.

**Comment by wanghanyang123** [comment]
I have solved my issue, thank you. @SeverineH
But I have another question about these demos just run with python3?

**Comment by sgriset** [comment]
> When I cmake, there is a error about:
> 
> Determining if the pthread_create exist failed with the following output:
> Change Dir: /home/why/openvino/dldt/inference-engine/build/CMakeFiles/CMakeTmp
> 
> Run Build Command:"/usr/bin/make" "cmTC_5a4da/fast"
> /usr/bin/make -f CMakeFiles/cmTC_5a4da.dir/build.make CMakeFiles/cmTC_5a4da.dir/build
> make[1]: Entering directory '/home/why/openvino/dldt/inference-engine/build/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_5a4da.dir/CheckSymbolExists.c.o
> /usr/bin/cc -fPIE -fPIC -Wformat -Wformat-security -fstack-protector-strong -fPIE -o CMakeFiles/cmTC_5a4da.dir/CheckSymbolExists.c.o -c /home/why/openvino/dldt/inference-engine/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
> Linking C executable cmTC_5a4da
> /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5a4da.dir/link.txt --verbose=1
> /usr/bin/cc -fPIE -fPIC -Wformat -Wformat-security -fstack-protector-strong -rdynamic CMakeFiles/cmTC_5a4da.dir/CheckSymbolExists.c.o -o cmTC_5a4da
> CMakeFiles/cmTC_5a4da.dir/CheckSymbolExists.c.o：在函数‘main’中：
> CheckSymbolExists.c:(.text+0x1b)：对‘pthread_create’未定义的引用
> collect2: error: ld returned 1 exit status
> CMakeFiles/cmTC_5a4da.dir/build.make:86: recipe for target 'cmTC_5a4da' failed
> make[1]: *** [cmTC_5a4da] Error 1
> make[1]: Leaving directory '/home/why/openvino/dldt/inference-engine/build/CMakeFiles/CMakeTmp'
> Makefile:121: recipe for target 'cmTC_5a4da/fast' failed
> make: *** [cmTC_5a4da/fast] Error 2
> 
> File /home/why/openvino/dldt/inference-engine/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
> /* */
> #include <pthread.h>
> 
> int main(int argc, char** argv)
> {
> (void)argv;
> #ifndef pthread_create
> return ((int*)(&pthread_create))[argc];
> #else
> (void)argc;
> return 0;
> #endif
> }
> 
> And there is not setupvars.sh in the folder of <../inference-engine/bin>, so I could not set the environment variable.
> @SeverineH

How did you solve this

**Comment by Liujingxiu23** [comment]
@wanghanyang123  I confused how you solve the problem?

**Comment by zongwave** [comment]
Hi, can anyone give some information on how to resolve the cmake failed with check "pthread"  error?

I built openvino on Ubuntu 19.10

/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_fa979.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/cmTC_fa979.dir/CheckSymbolExists.c.o  -o cmTC_fa979
/usr/bin/ld: CMakeFiles/cmTC_fa979.dir/CheckSymbolExists.c.o: in function `main':
CheckSymbolExists.c:(.text+0x1f): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status

**Comment by jgespino** [comment]
Closing, feel free to start a new issue if additional assistance is needed.
