### ISSUE TITLE
the debug mode failed when it runs get_opts

### ISSUE THREAD

**Issue by andeyeluguo** [openvinotoolkit/openvino#480]
I am using openvino installed by the official tutorial. But when I run this code in debug mode, it crashed.
```
    Core ie;

    auto cnnNetwork = ie.ReadNetwork("frozen_darknet_yolov3_model.xml");

    std::shared_ptr<const ngraph::Function> ngraphFunction = cnnNetwork.getFunction();

    auto op = ngraphFunction->get_ops();
```
it crashed when it runs get_opts. Works well in release mode, but failed in debug mode.
I try to find why, and just find that
```
    auto param = ngraphFunction->get_parameters();
```
will get empty param in debug mode, while it is not empty in release mode.
I also found the the debug mode is using ngraph.dll , not the ngraphd.dll. the ngraphd.dll is bigger than ngraph.dll, but it seems not to be used, because there is no ngraphd.lib, just a ngraph.lib.
That is really weird. please help me.
Regards.

**Comment by lkepka** [comment]
I have exactly the same problem. Did you managed to fix this?

**Comment by alalek** [comment]
Debug mode doesn't work (some files are missing in OV installation package as mentioned).
Use release mode or build from sources.

see also: #1346

**Comment by lkepka** [comment]
Thanks @alalek
