### ISSUE TITLE
Question about converting Tensorflow Object Detection 2.4 to Model Optimizer

### ISSUE THREAD

**Issue by WonsokYoo** [openvinotoolkit/openvino#4830]
##### System information (version)
ssd_mobilenet_v2_320x320_coco17_tpu-8 (TF2 Model Zoo)

- OpenVINO=> master branch
- Operating System / Platform =>Ubuntu18.04
- Problem classification =>Model Conversion
- Framework: TensorFlow (if applicable)
- Model name:  (if applicable)
-->ssd_mobilenet_v2_320x320_coco17_tpu-8 (TF2 Model Zoo)

##### Detailed description
Hi, I've tried to convert TF2 object detection API model (ssd_mobilenet_v2_320x320_coco17_tpu-8) from 'TF saved_model' to 'IR' but failed. I have read #2682 and @rchuzh99 succeeded converting the same model with mo_tf.py from master branch. So I cloned master branch and tried with the mo_tf.py from there. Below is the command I used: 

python mo_tf.py --saved_model_dir ~/tensorflow/workspace/frozen_models/saved/saved_model/ --transformations_config ~/openvino/model-optimizer/extensions/front/tf/ssd_support_api_v2.0.json --tensorflow_object_detection_api_pipeline_config ~/tensorflow/workspace/frozen_models/saved/pipeline.config --reverse_input_channels --output_dir ~/test2/ --input_shape [1,300,300,3]

However I got the following:

[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Exception occurred during running replacer "ObjectDetectionAPIOutputReplacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIOutputReplacement'>)": 'inputs'
[ ERROR ]  Traceback (most recent call last):
  File "/home/my/openvino/model-optimizer/mo/utils/class_registration.py", line 290, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/home/my/openvino/model-optimizer/mo/middle/pattern_match.py", line 60, in for_graph_and_each_sub_graph_recursively
    for_each_sub_graph_recursively(graph, func)
  File "/home/my/openvino/model-optimizer/mo/middle/pattern_match.py", line 54, in for_each_sub_graph_recursively
    for_each_sub_graph(graph, recursive_helper)
  File "/home/my/openvino/model-optimizer/mo/middle/pattern_match.py", line 39, in for_each_sub_graph
    func(node[sub_graph_name])
  File "/home/my/openvino/model-optimizer/mo/middle/pattern_match.py", line 50, in recursive_helper
    func(sub_graph)
  File "/home/my/openvino/model-optimizer/mo/front/tf/replacement.py", line 48, in find_and_replace_pattern
    self.transform_graph(graph, desc._replacement_desc['custom_attributes'])
  File "/home/my/openvino/model-optimizer/extensions/front/tf/ObjectDetectionAPI.py", line 1238, in transform_graph
    add_output_ops(graph, _outputs, graph.graph['inputs'])
KeyError: 'inputs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/my/openvino/model-optimizer/mo/main.py", line 345, in main
    ret_code = driver(argv)
  File "/home/my/openvino/model-optimizer/mo/main.py", line 309, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/home/my/openvino/model-optimizer/mo/main.py", line 252, in prepare_ir
    graph = unified_pipeline(argv)
  File "/home/my/openvino/model-optimizer/mo/pipeline/unified.py", line 29, in unified_pipeline
    class_registration.ClassType.BACK_REPLACER
  File "/home/my/openvino/model-optimizer/mo/utils/class_registration.py", line 340, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/home/my/openvino/model-optimizer/mo/utils/class_registration.py", line 330, in apply_replacements_list
    num_transforms=len(replacers_order))
  File "/home/my/openvino/model-optimizer/mo/utils/logger.py", line 124, in wrapper
    function(*args, **kwargs)
  File "/home/my/openvino/model-optimizer/mo/utils/class_registration.py", line 318, in apply_transform
    )) from err
Exception: Exception occurred during running replacer "ObjectDetectionAPIOutputReplacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIOutputReplacement'>)": 'inputs'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by WonsokYoo** [comment]
BTW, I succeeded with the frozen model with:

python mo_tf.py --input_model ~/tensorflow/workspace/frozen_models/ssd_mobilenet_v2_320x320_coco17_tpu-8_frozen_graph.pb --transformations_config ~/openvino/model-optimizer/extensions/front/tf/ssd_support_api_v2.0.json --tensorflow_object_detection_api_pipeline_config ~/tensorflow/workspace/frozen_models/saved/pipeline.config --reverse_input_channels --output_dir ~/test2/ --input_shape [1,300,300,3]

**BUT, I still don't know why I have failed with 'saved_mode'. I'm waiting for your reply thanks!**

**Comment by elakkiya-workit** [comment]
Hi, I am also facing the same issue. Could you pls share the version of OpenVino toolkit you are using now ?

**Comment by WonsokYoo** [comment]
@elakkiya-workit The System Info. is described in the above main contents. 
Posting again,

ssd_mobilenet_v2_320x320_coco17_tpu-8 (TF2 Model Zoo)

- OpenVINO=> master branch
- Operating System / Platform =>Ubuntu18.04
- Problem classification =>Model Conversion
- Framework: TensorFlow (if applicable)
- Model name: (if applicable)
- -->ssd_mobilenet_v2_320x320_coco17_tpu-8 (TF2 Model Zoo)

**Comment by WonsokYoo** [comment]
I tested again today and found out phenomenon:

1.  [Succeeded] With the pre-trained model from TF2 Zoo (from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)
  Both ways using frozen_graph/saved_model worked.

2. [Failed] With the exported model (from 'exporter_main_tf2.py' → added self fine-tuned checkpoint dir.)
  Both ways using frozen_graph/saved_model did NOT work. → the same output like the above BUG REPORT.

Hope to be verified this issue ASAP by any developers who are related MO.
Thanks so much!

**Comment by lazarevevgeny** [comment]
@WonsokYoo , there is a PR https://github.com/openvinotoolkit/openvino/pull/4772/ which contains fixes to enabled conversion of TF 2.4 OD API models. This is not ready yet, because the solution does not work for TF 2.4 Faster-RCNN models. But you can checkout MO from the PR and convert the model. Do not forget to change the path to JSON configuration file to have "2.4" in the name.

**Comment by elakkiya-workit** [comment]
@WonsokYoo Thanks for your clarification. I am just keen to know how you created a frozen_graph.pb file in TF2 ? Because, placeholders and frozen graphs are all TF1 features and only '**saved_model**' is supported by TF2.

**Comment by elakkiya-workit** [comment]
@lazarevevgeny , thanks for your reply. I checked the MO from the latest PR and unable to find a JSON configuration file with "2.4" support. 

Currently im working with ssd_mobilenet_v2_320x320_coco17_tpu-8 (TF2 Model Zoo) and i get the same Bug report while using "ssd_support_api_v2.0.json" file.

Could you pls provide more clarity about the "2.4" JSON config file you are referring to?

**Comment by WonsokYoo** [comment]
@elakkiya-workit Hi, regarding how to freeze the model in TF2 I referred to the following post:
https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/

**Comment by WonsokYoo** [comment]
@lazarevevgeny Hi, Thanks for your quick response. Same with @elakkiya-workit  I cannot find the "2.4" JSON config file even in the master branch. Could you share the info. where I can find the "2.4" JSON config file? I think I need to try again with that file.

**Comment by WonsokYoo** [comment]
@lazarevevgeny  @elakkiya-workit  Oh, I find "2.4" config file. This is in the 'lazarevevgeny:tf_2.0_od_api_models_with_loop' branch. I will test with that branch and share the results! Thank you.

**Comment by rchuzh99** [comment]
Hi @WonsokYoo , I was able to convert because I trained the model using TF 2.3. As mentioned by @lazarevevgeny , the v2.4 can be found in PR #4772
https://github.com/openvinotoolkit/openvino/pull/4772

**Comment by WonsokYoo** [comment]
@lazarevevgeny @rchuzh99 I appreciate your helps. I succeeded in converting saved_model to IR with MO by using the #4772 PR branch. FYI, still failed in converting from frozen_model which is extracted by 'exporter_main_v2.py' to IR even with #4772 branch. Below are command and failure output:

(ncs_new) my@my-desktop:~/openvino_2.4/openvino/model-optimizer$ python mo_tf.py --input_model /home/my/tensorflow2/workspace/frozen_models/from_exporter_v2/ssd_mobilenet_v2_320x320_coco17_tpu-8_frozen_graph.pb --transformations_config /home/my/openvino_2.4/openvino/model-optimizer/extensions/front/tf/ssd_support_api_v2.4.json --tensorflow_object_detection_api_pipeline_config /home/my/tensorflow2/workspace/saved_models/from_exporter_v2/ssd_mobilenet_v2_320x320_coco17_tpu-8/pipeline.config --reverse_input_channels --output_dir ~/test3/ --input_shape [1,300,300,3]
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/my/tensorflow2/workspace/frozen_models/from_exporter_v2/ssd_mobilenet_v2_320x320_coco17_tpu-8_frozen_graph.pb
	- Path for generated IR: 	/home/my/test3/
	- IR output name: 	ssd_mobilenet_v2_320x320_coco17_tpu-8_frozen_graph
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	[1,300,300,3]
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	True
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	/home/my/tensorflow2/workspace/saved_models/from_exporter_v2/ssd_mobilenet_v2_320x320_coco17_tpu-8/pipeline.config
	- Use the config file: 	None
Traceback (most recent call last):
  File "/home/my/openvino_2.4/openvino/model-optimizer/mo/utils/check_ie_bindings.py", line 36, in <module>
    from mo.utils.error import classify_error_type
ImportError: cannot import name 'classify_error_type' from 'mo.utils.error' (/opt/intel/openvino_2021/deployment_tools/model_optimizer/mo/utils/error.py)
[ WARNING ] Could not find the Inference Engine Python API. At this moment, the Inference Engine dependency is not required, but will be required in future releases.
[ WARNING ] Consider building the Inference Engine Python API from sources or try to install OpenVINO (TM) Toolkit using "install_prerequisites.sh"
Model Optimizer version: 	custom_tf_2.0_od_api_models_with_loop_1c0e9c5e4ed8cfae03304983370ad027e9e13d76
2021-03-19 11:06:08.919662: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino_2021/data_processing/dl_streamer/lib:/opt/intel/openvino_2021/data_processing/gstreamer/lib:/opt/intel/openvino_2021/opencv/lib:/opt/intel/openvino_2021/deployment_tools/ngraph/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64:/usr/local/cuda/lib64::/usr/local/cuda-11.0/lib64:/usr/local/cuda-10.0/lib64
2021-03-19 11:06:08.919687: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[ ANALYSIS INFO ]  It looks like there are input nodes of boolean type:
	unused_control_flow_input_1
	unused_control_flow_input_5
	unused_control_flow_input_7
	unused_control_flow_input_9
If this input node is as switch between the training and an inference mode, then you need to freeze this input with value True or False.
In order to do this run the Model Optimizer with the command line parameter:
	--input "unused_control_flow_input_1->False" or --input "unused_control_flow_input_1->True"
	--input "unused_control_flow_input_5->False" or --input "unused_control_flow_input_5->True"
	--input "unused_control_flow_input_7->False" or --input "unused_control_flow_input_7->True"
	--input "unused_control_flow_input_9->False" or --input "unused_control_flow_input_9->True"
to switch graph to inference mode.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.user_data_repack.UserDataRepack'>): Original placeholders: 'input_tensor, unused_control_flow_input, unused_control_flow_input_1, unused_control_flow_input_2, unused_control_flow_input_3, unused_control_flow_input_4, unused_control_flow_input_5, unused_control_flow_input_6, unused_control_flow_input_7, unused_control_flow_input_8, unused_control_flow_input_9, unused_control_flow_input_10, unused_control_flow_input_11'. Freezing was requested for ''. --input_shape was provided without --input. Can not deduce which node shape to override

**Comment by lazarevevgeny** [comment]
@WonsokYoo , can you share your models (both frozen and saved_model) with me?

**Comment by lazarevevgeny** [comment]
@WonsokYoo , also, could you try to freeze your model using the following code:

```python
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

model = tf.saved_model.load('./saved_model/')
frozen_func = convert_variables_to_constants_v2(model.signatures['serving_default'], lower_control_flow=False)
graph_def = frozen_func.graph.as_graph_def(add_shapes=True)
tf.io.write_graph(graph_def, './', 'frozen_model.pb', as_text=False)
```

**Comment by WonsokYoo** [comment]
@lazarevevgeny Sorry for my late reply, I cannot use PC during weekend also share any files :-(
I haved converted into frozen model as follows:
```python
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

model = tf.saved_model.load(PATH_TO_SAVED_MODEL)
graph_func = model.signatures['serving_default']

# Get frozen ConcreteFunction 
frozen_func = convert_variables_to_constants_v2(graph_func)
frozen_func.graph.as_graph_def()

# Save frozen graph from frozen ConcreteFunction to hard drive
tf.io.write_graph(graph_or_graph_def=frozen_func.graph, logdir="./frozen_models", name="simple_frozen_graph.pb", as_text=False)
```
Seems like almost the same but the 'lower_control_flow' and 'add_shapes' options.

**Comment by lazarevevgeny** [comment]
@WonsokYoo , could you share your model with me so I can take a look at it?

**Comment by WonsokYoo** [comment]
@lazarevevgeny I wish I could but any of files are not allowed to share in my place. Today, I tested with the code that you suggested and it worked! I think those two different 'lower_control_flow' and 'add_shapes' options caused wrong conversion to 'frozen_model'. (I don't know this point exactly and the above example code I posted generated 'frozen_model' file. This is weired point.. If you want to verify further, plz try to convert 'saved_model' to 'frozen_model' using my suggested example code.) Anyway, all the things are now work. I will close this issue. 
Thanks so much again :-)

**Comment by lazarevevgeny** [comment]
@WonsokYoo , happy to hear that the model works now! Keep using OpenVINO!

**Comment by b04505009** [comment]
Hi @lazarevevgeny ,

I used your code and OpenVINO master branch to convert my TF2 ssd-mobilenet-v2 savedmodel. But when use Netron to check the model's architecture, I found the architecture has missed some parts compared to ssd-mobilenet-v2 from TF1. Is this normal?

TF1 model:
![Screenshot from 2021-05-19 09-04-12](https://user-images.githubusercontent.com/14859904/118741613-3b4b1380-b881-11eb-8d5f-5e1635a5610e.png)
[ssd-mobilenet-v2-license_plate_300x300.zip](https://github.com/openvinotoolkit/openvino/files/6505199/ssd-mobilenet-v2-license_plate_300x300.zip)


TF2 model:
![Screenshot from 2021-05-19 09-07-34](https://user-images.githubusercontent.com/14859904/118741792-b6142e80-b881-11eb-8492-e4227bee0efc.png)
[ssd-mobilenet-v2-license_plate_306x544_tf2.zip](https://github.com/openvinotoolkit/openvino/files/6505201/ssd-mobilenet-v2-license_plate_306x544_tf2.zip)

**Comment by lazarevevgeny** [comment]
@b04505009 , yes this is normal. During the model conversion using the MO some big parts of the model are fused into some high-level operations like Proposal and DetectionOutput. These side edges which you see in the original model are not needed anymore since all the information about original input is delivered to Proposal, DetectionOutput operations from the their corresponding inputs.

The only thing that you should care is that you need to perform image pre-processing in your application before providing an image to the OpenVINO model. Please, take a look at the section "Important Notes About Feeding Input Images to the Samples" of the document https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html

**Comment by b04505009** [comment]
@lazarevevgeny 
Ok I understand. Thank you for your information!

**Comment by wikipedia2008** [comment]
> ##### System information (version)
> ssd_mobilenet_v2_320x320_coco17_tpu-8 (TF2 Model Zoo)
> * OpenVINO=> master branch
> * Operating System / Platform =>Ubuntu18.04
> * Problem classification =>Model Conversion
> * Framework: TensorFlow (if applicable)
> * Model name:  (if applicable)
>   -->ssd_mobilenet_v2_320x320_coco17_tpu-8 (TF2 Model Zoo)
> 
> ##### Detailed description
> Hi, I've tried to convert TF2 object detection API model (ssd_mobilenet_v2_320x320_coco17_tpu-8) from 'TF saved_model' to 'IR' but failed. I have read #2682 and @rchuzh99 succeeded converting the same model with mo_tf.py from master branch. So I cloned master branch and tried with the mo_tf.py from there. Below is the command I used:
> 
> ```shell
> python mo_tf.py --saved_model_dir ~/tensorflow/workspace/frozen_models/saved/saved_model/ --transformations_config ~/openvino/model-optimizer/extensions/front/tf/ssd_support_api_v2.0.json --tensorflow_object_detection_api_pipeline_config ~/tensorflow/workspace/frozen_models/saved/pipeline.config --reverse_input_channels --output_dir ~/test2/ --input_shape [1,300,300,3]
> ```
> 
> However I got the following:
> 
> ```shell
> [ ERROR ]  -------------------------------------------------
> [ ERROR ]  ----------------- INTERNAL ERROR ----------------
> [ ERROR ]  Unexpected exception happened.
> [ ERROR ]  Please contact Model Optimizer developers and forward the following information:
> [ ERROR ]  Exception occurred during running replacer "ObjectDetectionAPIOutputReplacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIOutputReplacement'>)": 'inputs'
> [ ERROR ]  Traceback (most recent call last):
>   File "/home/my/openvino/model-optimizer/mo/utils/class_registration.py", line 290, in apply_transform
>     for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
>   File "/home/my/openvino/model-optimizer/mo/middle/pattern_match.py", line 60, in for_graph_and_each_sub_graph_recursively
>     for_each_sub_graph_recursively(graph, func)
>   File "/home/my/openvino/model-optimizer/mo/middle/pattern_match.py", line 54, in for_each_sub_graph_recursively
>     for_each_sub_graph(graph, recursive_helper)
>   File "/home/my/openvino/model-optimizer/mo/middle/pattern_match.py", line 39, in for_each_sub_graph
>     func(node[sub_graph_name])
>   File "/home/my/openvino/model-optimizer/mo/middle/pattern_match.py", line 50, in recursive_helper
>     func(sub_graph)
>   File "/home/my/openvino/model-optimizer/mo/front/tf/replacement.py", line 48, in find_and_replace_pattern
>     self.transform_graph(graph, desc._replacement_desc['custom_attributes'])
>   File "/home/my/openvino/model-optimizer/extensions/front/tf/ObjectDetectionAPI.py", line 1238, in transform_graph
>     add_output_ops(graph, _outputs, graph.graph['inputs'])
> KeyError: 'inputs'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/my/openvino/model-optimizer/mo/main.py", line 345, in main
>     ret_code = driver(argv)
>   File "/home/my/openvino/model-optimizer/mo/main.py", line 309, in driver
>     ret_res = emit_ir(prepare_ir(argv), argv)
>   File "/home/my/openvino/model-optimizer/mo/main.py", line 252, in prepare_ir
>     graph = unified_pipeline(argv)
>   File "/home/my/openvino/model-optimizer/mo/pipeline/unified.py", line 29, in unified_pipeline
>     class_registration.ClassType.BACK_REPLACER
>   File "/home/my/openvino/model-optimizer/mo/utils/class_registration.py", line 340, in apply_replacements
>     apply_replacements_list(graph, replacers_order)
>   File "/home/my/openvino/model-optimizer/mo/utils/class_registration.py", line 330, in apply_replacements_list
>     num_transforms=len(replacers_order))
>   File "/home/my/openvino/model-optimizer/mo/utils/logger.py", line 124, in wrapper
>     function(*args, **kwargs)
>   File "/home/my/openvino/model-optimizer/mo/utils/class_registration.py", line 318, in apply_transform
>     )) from err
> Exception: Exception occurred during running replacer "ObjectDetectionAPIOutputReplacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIOutputReplacement'>)": 'inputs'
> 
> [ ERROR ]  ---------------- END OF BUG REPORT --------------
> [ ERROR ]  -------------------------------------------------
> ```

hi, 
/opt/intel/openvino/data_processing/audio/speech_recognition/, I can't find the directory. What's the reason? Has the project been deleted

Please tell me where I can find the catalog

Thanks
