### ISSUE TITLE
OpenVINO Docker DLWorkBench error on Ubuntu 18.04

### ISSUE THREAD

**Issue by qiyuangong** [openvinotoolkit/openvino#484]
OS: Ubuntu 18.04
Docker Version:  19.03.8
Command used: 
```
docker run -p 127.0.0.1:5665:5665 \
                --name workbench \
                -it openvino/workbench:latest
```

This command works on my macOS, but failed on Ubuntu.

Error encountered.

```
Celery is not ready at the moment. Retry in 2 seconds
Error:
Unable to load celery application.
Module 'pandas._libs.missing' has no attribute 'natype'

Celery is not ready at the moment. Retry in 2 seconds
Error:
Unable to load celery application.
Module 'pandas._libs.missing' has no attribute 'natype'

```

**Comment by artyomtugaryov** [comment]
Do you use the image from https://hub.docker.com/r/openvino/workbench or build the image locally from the OpenVINO package?

**Comment by qiyuangong** [comment]
Hi @artyomtugaryov.

I used image from docker hub for both mac and Ubuntu. The only difference is that my Ubuntu 18.04 works behind a proxy. :)

**Comment by artyomtugaryov** [comment]
Can you try to build the image from the OpenVINO package? In this case, you need to download and install OpenVINO to your machine with Ubuntu and follow this instruction: https://docs.openvinotoolkit.org/latest/_docs_Workbench_DG_Install_from_Package.html

**Comment by qiyuangong** [comment]
Hi @artyomtugaryov 

Still the same error. But I found DLWorkBench is actually working well in container.

The only problem is this error message may cover the token required for login. 

Thank you for help!
Issue closed.
