### ISSUE TITLE
Conversion onnx-tf-openvino does not work

### ISSUE THREAD

**Issue by mdatres** [openvinotoolkit/openvino#4849]
Dear all,

I have a working .onnx model (opset 11) and I want to convert it into a .pb model. I used the following command for the conversion:

onnx-tf convert -i retinanet1.onnx -o .
This command produces an output, but when I use it for the conversion in OpenVINO (version 2020.1), it produces the following error:

[ FRAMEWORK ERROR ] Cannot load input model: TensorFlow cannot read the model file:
"/Users/massimilianodatres/Documents/catchme_mmdet/ONNX_models/retinanet/saved_model.pb" is incorrect TensorFlow model file.

The file should contain one of the following TensorFlow graphs:

frozen graph in text or binary format
inference graph for freezing with checkpoint (--input_checkpoint) in text or binary format
meta graph
It seems that the frozen graph contained in .pb file is not correct. My environment during conversion is the following:

tensorflow 1.14.0
onnx 1.8.1
onnx-tf 1.7.0

I hope that the problem is well explained. Can you help me?

PS: I know that I can convert directly the .onnx model to openVINO, but unfortunately retinanet is not supported in openVINO version 2020.1, while fizyr/retinanet is supported. I do not use fizyr/retinanet but the mmdetection one (that is in pytorch), and so I have thought to convert it in .onnx and after in .pb.
I can not update OpenVINO version.

Thanks in advance,
mdatres

**Comment by Iffa-Meah** [comment]
Have you verify the TF (.pb) model to check whether was correctly converted using TensorFlow framework, MO error seems like the model is not the correct format

If possible can you also provide some insight why you are constrained to OpenVINO 2020.1 release?

**Comment by mdatres** [comment]
Thanks for the reply. I think that the error is in the .pb model so I close this issue. 

Best regards, 
mdatres
