### ISSUE TITLE
openvino convert PSPNet to IR

### ISSUE THREAD

**Issue by qbTrible** [openvinotoolkit/openvino#485]
Does anyone convert PSPNet to openvino IR model? When I do this, an error occurred.
"There is no registered "infer" function for node "245" with op = "Resize". Please implement this function in the extensions."
But the openvino document shows the "Resize" Opset-10 version is supported.
Does anyone know the reason?

**Comment by ilya-lavrenov** [comment]
@qbTrible could you please provide a link to the models as well as details MO logs?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,
