### ISSUE TITLE
Distorted and gray image while using object_detection_demo

### ISSUE THREAD

**Issue by alexandru-oana** [openvinotoolkit/openvino#4874]
I'm running l_openvino_toolkit_dev_ubuntu18_p_2021.2.185  and have distorted image when trying to run a simple mp4 video against object_detection_demo using a pretrained model ( vehicle-licence-plate-detection-barrier )

If i run the same video with a simple gstreamer pipeline command line, everything is ok, or even if i use detection and classification inside the pipeline.

BTW: i'm using Ubuntu 20.04

The distorted image looks like this: 
![BAD_OUTPUT](https://user-images.githubusercontent.com/77742671/111700510-2c74c000-8842-11eb-914f-39e3890c2c85.jpg)

The below is the gst output from **object_detection_demo**

```

[ INFO ] InferenceEngine:       API version ......... 2.1
        Build ........... 2021.2.0-1877-176bdf51370-releases/2021/2
[ INFO ] Parsing input parameters
[ INFO ] Reading input
0:00:00.012503330   800 0x555985958d30 WARN                 basesrc gstbasesrc.c:3600:gst_base_src_start_complete:<source> pad not activated yet
0:00:00.012706139   800 0x555985958d30 WARN                 basesrc gstbasesrc.c:3600:gst_base_src_start_complete:<source> pad not activated yet
0:00:00.016071206   800 0x555985966300 WARN                 qtdemux qtdemux.c:3237:qtdemux_parse_trex:<qtdemux0> failed to find fragment defaults for stream 1
0:00:00.016110624   800 0x555985966300 WARN                 qtdemux qtdemux.c:3237:qtdemux_parse_trex:<qtdemux0> failed to find fragment defaults for stream 2
[ WARN:0] global ../opencv/modules/videoio/src/cap_gstreamer.cpp (919) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global ../opencv/modules/videoio/src/cap_gstreamer.cpp (956) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
0:00:00.063654939   800 0x555985958d30 WARN                 basesrc gstbasesrc.c:3600:gst_base_src_start_complete:<source> pad not activated yet
0:00:00.063770664   800 0x555985958d30 WARN                 basesrc gstbasesrc.c:3600:gst_base_src_start_complete:<source> pad not activated yet
0:00:00.064285844   800 0x7f52ec0766a0 WARN                 qtdemux qtdemux.c:3237:qtdemux_parse_trex:<qtdemux1> failed to find fragment defaults for stream 1
0:00:00.064321891   800 0x7f52ec0766a0 WARN                 qtdemux qtdemux.c:3237:qtdemux_parse_trex:<qtdemux1> failed to find fragment defaults for stream 2
[ INFO ] Loading Inference Engine
[ INFO ] Device info:
[ INFO ]        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 2021.2.0-1877-176bdf51370-releases/2021/2
Loading network files
[ INFO ] Batch size is forced to 1.
[ INFO ] Checking that the inputs are as the demo expects
[ INFO ] Checking that the outputs are as the demo expects
[ INFO ] Loading model to the device
0:00:22.940090071   800 0x555985966300 WARN                   libav gstavauddec.c:628:gst_ffmpegauddec_drain:<avdec_aac1> send packet failed, could not drain decoder

```

Any hints ?

**Comment by alexandru-oana** [comment]
@Iffa-Meah  also, do you know why o**bject_detection_demo_ssd_async**  is present only in certain releases ? it has been replaced by **object_detection_demo** or what's the reason behind this ?
Thanks,
Alex

**Comment by Iffa-Meah** [comment]
Hi,

I tested the object_detection_demo with the license plate model. It seems to work just fine for me. Probably the distortion occurs due to multiple processing tasks. Sometimes I face it too if I'm using VM with lots of background things running.

Yeah, the object_detection_demo_ssd_async has been deprecated in the latest OpenVINO version. If you noticed, the ssd architecture option is available within the single object_detection_demo instead. (-at ssd)

![car_plate_Obj_det](https://user-images.githubusercontent.com/79643476/111912109-2598b800-8aa3-11eb-90f8-2014a80bcae6.png)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
