### ISSUE TITLE
Convert trained yolov3 Darknet-53 custom model to tensorflow model

### ISSUE THREAD

**Issue by rohit167** [openvinotoolkit/openvino#488]
I have trained a custom yolov3 Darknet-53 model (_yolo3_darknet53_custom.params_) using gluon-cv (mxnet)

I need to convert the _yolo3_darknet53_custom.params_ (mxnet) model to _yolo3_darknet53_custom.pb_ (tensorflow)

Also, here I don't see yolo being supported [https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_MxNet.html](url) Still I tried using mo_mxnet.py but faced errors.

Queries:
1) Does openvino supports yolo models conversion trained using gluon-cv (mxnet) in general?
2) Is there any way or work around by which I can convert yolo models?

Any leads would be great!
Thank you

**Comment by lazarevevgeny** [comment]
@rohit167 
OpenVINO does not provide ability to convert the mxnet models to the tensorflow.

@iimironov, do we support MxNet gluon-cv Yolo model?

**Comment by iimironov** [comment]
@lazarevevgeny yes we support yolov3 from gluoncv

**Comment by ZiyueWangUoB** [comment]
> @lazarevevgeny yes we support yolov3 from gluoncv

Hi I'm trying to implement yolo3 from gluoncv but getting a weird bug, do you have time to take a look at it?

**Comment by lazarevevgeny** [comment]
@ZiyueWangUoB did you follow the documentation https://github.com/openvinotoolkit/openvino/blob/master/docs/MO_DG/prepare_model/convert_model/mxnet_specific/Convert_GluonCV_Models.md ?

@iimironov could you help @ZiyueWangUoB with the issue?

**Comment by ZiyueWangUoB** [comment]
@lazarevevgeny Yes I followed the docs and had an error, which I wrote in the new issue #1765.
