### ISSUE TITLE
Error compiling Cython file:

### ISSUE THREAD

**Issue by tech0x** [openvinotoolkit/openvino#489]
Cython-0.29.17
Python-3.6

Error compiling Cython file:
------------------------------------------------------------
...
    #  Usage example:\n
    #  ```python
    #  ie = IECore()
    #  net = ie.read_network(model=path_to_xml_file, weights=path_to_bin_file)
    #  ```
    cpdef IENetwork read_network(self, model: [str, bytes], weights: [str, bytes] = "", init_from_buffer: bool = False):
         ^
------------------------------------------------------------

/home/oper/openvino/inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx:136:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
cdef class LayersStatsMap(dict):
    cdef C.IENetwork net_impl

cdef class IECore:
    cdef C.IECore impl
    cpdef IENetwork read_network(self, model : [str, bytes], weights : [str, bytes] = ?, bool init_from_buffer = ?)
                               ^
------------------------------------------------------------

/home/oper/openvino/inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pxd:58:32: Previous declaration is here

Error compiling Cython file:
------------------------------------------------------------
...
    #  Usage example:\n
    #  ```python
    #  ie = IECore()
    #  net = ie.read_network(model=path_to_xml_file, weights=path_to_bin_file)
    #  ```
    cpdef IENetwork read_network(self, model: [str, bytes], weights: [str, bytes] = "", init_from_buffer: bool = False):
                                                                                                              ^
------------------------------------------------------------

/home/oper/openvino/inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx:136:111: 'bool' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
...
    #   with open(path_to_xml_file, 'rb') as f:
    #       xml = f.read()
    #   net = IENetwork(model=xml, weights=bin, init_from_buffer=True)
    #   ```

    def __cinit__(self, model: [str, bytes] = "", weights: [str, bytes] = "", init_from_buffer: bool = False):
                                                                                                    ^
------------------------------------------------------------

/home/oper/openvino/inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx:1033:101: 'bool' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
...
            xml_buffer = <char*> malloc(len(model)+1)
            bin_buffer = <uint8_t *> malloc(len(weights))
            memcpy(xml_buffer, <char*> model, len(model))
            memcpy(bin_buffer, <uint8_t *> weights, len(weights))
            xml_buffer[len(model)] = b'\0'
            net.impl = self.impl.readNetwork(xml_buffer, bin_buffer, len(weights))
                                                      ^
------------------------------------------------------------

/home/oper/openvino/inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx:148:55: Cannot assign type 'char *' to 'string'
inference-engine/ie_bridges/python/src/openvino/inference_engine/CMakeFiles/ie_api.dir/build.make:62: recipe for target 'inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.cxx' failed
make[2]: *** [inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.cxx] Error 1
make[2]: *** Deleting file 'inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.cxx'
CMakeFiles/Makefile2:4024: recipe for target 'inference-engine/ie_bridges/python/src/openvino/inference_engine/CMakeFiles/ie_api.dir/all' failed
make[1]: *** [inference-engine/ie_bridges/python/src/openvino/inference_engine/CMakeFiles/ie_api.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by akuporos** [comment]
Hi @tech0x,

Do you use cython and python from conda or something else?

**Comment by tech0x** [comment]
Добрый день, 

Нет, конды или прочего не было использовано.
Систеа ubuntu 18.04 пробовал системный cython3 и пробовал разные версии установленные через pip3, включая самую последнюю. 
Причем проблема одинаковая для amd64 так и для arm64
При этом версия 2019 собирается без проблем и под amd64 так и для arm64

Собираю указывая эти параметры
cmake -DCMAKE_BUILD_TYPE=Release \
           -DENABLE_MKL_DNN=OFF \
           -DENABLE_CLDNN=OFF\
           -DENABLE_GNA=OFF \
           -DENABLE_SSE42=OFF \
           -DTHREADING=SEQ \
           -DENABLE_PYTHON=ON \
           -DPYTHON_EXECUTABLE=/usr/bin/python3 \
           -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 \
           -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so \
           ..

**Comment by akuporos** [comment]
@tech0x 
Обычно такая проблема возникает, когда версия Cython ниже 0.29. У меня на машине тоже стоит 0.29.17 и все работает. Если стоит несколько cython, то может возникать некий "конфликт" версий. 
Пожалуйста, попробуйте построить проект с master ветки. 
И, пожалуйста, подскажите, что будет если в терминале набрать cython -V?

С уважением,
Анастасия

**Comment by tech0x** [comment]
Да все верно, почему то подключался cython из python2.7 и игнорировался тот что установлен для python3.6, после принудительного обновления все собирается без проблем.

Большое спасибо

**Comment by akuporos** [comment]
To summarize the solution to this problem:
You need to check which Cython is picked up in OpenVINO, because there may be conflicts between different versions of Cython. To check which Cython was found, run "cython -V". If you notice that the Cython version is incorrect after executing this command, you can set the path to the correct Cython version using the key "-DCYTHON_EXECUTABLE =" / path / to / cython ""
