### ISSUE TITLE
possible mismatch within tensorDesc for hello_classification c sample

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/openvino#490]
Hi,

i don't quite understand the following code, is there a mismatch? thanks.

https://github.com/openvinotoolkit/openvino/blob/2020/inference-engine/ie_bridges/c/samples/hello_classification/main.c#L140
```
    dimensions_t dimens = {4, {1, (size_t)img.mat_channels, (size_t)img.mat_height, (size_t)img.mat_width}};
    tensor_desc_t tensorDesc = {NHWC, dimens, U8};
```

tensorDesc says that NHWC is used, but dimens contains NCHW (n=1, c=img.mat_channels, h=img.mat_height, w=img.mat_width).

Did I miss anything? thanks.

**Comment by ArtemSkrebkov** [comment]
Hi @guoyejun 
The order of dims in the IE library is fixed and it is always `NCHW` for 4-D data. If you know that your data has `NHWC` layout you need to specify the `layout` field of `TensorDesc` but no need to change the order of the dims. It is, again, `NCHW`.
 
Have tried to find this info in the documentation but couldn't :(
You can rely on [implementation of `getLayoutByDims`](https://github.com/openvinotoolkit/openvino/blob/2020/inference-engine/src/inference_engine/ie_layouts.cpp#L161). It returns an order of channels based on a vector of dimensions passed.

Hope my comment makes things a bit clearer.

**Comment by guoyejun** [comment]
thanks, 

will openvino add an internal convert from NHWC to NCHW if we set NHWC layout? thanks.

**Comment by ArtemSkrebkov** [comment]
Yes. If a network expects to get `NCHW` but a user provides `NHWC`. It is a responsibility of a concrete plugin to do a conversion.

**Comment by guoyejun** [comment]
thanks, and just curious why NHWC needs to be set twice, once here, and another place at https://github.com/openvinotoolkit/openvino/blob/2020/inference-engine/ie_bridges/c/samples/hello_classification/main.c#L109

**Comment by ilya-lavrenov** [comment]
@guoyejun it's not set twice. First in line 109 we set layout which plugin will except (and Core::LoadNetwork will compile for such layout), in line 140 we create a blob with such layout.

**Comment by guoyejun** [comment]
thanks
