### ISSUE TITLE
Convert pre-trained IR models to ONNX.

### ISSUE THREAD

**Issue by sradmard** [openvinotoolkit/openvino#4924]
Hi,
I need to get some pre-trained models, specifically any of [preson-reidentification-retail](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/person-reidentification-retail-0277) models in their original or ONNX format to be able to compare them against some other models in a different platform. I can see that openvino does not support backward conversion from IR models to original models, but is there a way to convert these IR models into ONNX? Or is there a repository where I can access the original or ONNX pre-trained person-reidentification-retail models? (it appears that the original models where available at some point from [here](https://github.com/openvinotoolkit/training_extensions/tree/develop/pytorch_toolkit/person_reidentification#pretrained-models) for example, but not anymore)
I would really appreciate that.

**Comment by Iffa-Meah** [comment]
We don't have the repo for all of the pre-trained model in its native form but lucky for you, the person-reidentification-retail is available in pytorch form [here](https://download.01.org/opencv/openvino_training_extensions/models/person_reidentification/)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
