### ISSUE TITLE
Running Inference Engine with NCS2 on Android

### ISSUE THREAD

**Issue by ShinoharaHare** [openvinotoolkit/openvino#4925]
Hi,

I'm trying to run IE with NCS2 on Android through the Java API.
I built OpenVINO and modules in openvino_contrib, and ran with CPU successfully.

```shell
cmake .. \
  -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
  -DANDROID_ABI=arm64-v8a \
  -DTHREADING=SEQ \
  -DANDROID_PLATFORM=21 \
  -DANDROID_STL=c++_shared \
  -DENABLE_OPENCV=OFF \
  -DENABLE_SAMPLES=OFF \
  -DENABLE_TESTS=OFF \
  -DENABLE_DOCS=OFF \
  -DIE_EXTRA_MODULES=${openvino_contrib}/modules \
```

```java
IECore core = new IECore("/sdcard/data/plugins.xml");
CNNNetwork cnnNetwork = core.ReadNetwork("/sdcard/data/age-gender-recognition-retail-0013.xml");
ExecutableNetwork executableNetwork = core.LoadNetwork(cnnNetwork, "CPU");
```

Now, I want to change the device name from CPU to MYRIAD so I can use NCS2, and it complained that libusb1.0.so cannot be found, so I built the libusb with NDK, putting it into my app, and now it crashed whether NCS2 is connected without showing useful information.

```
03-24 11:00:46.957 32315 32315 I e.openvino_test: type=1400 audit(0.0:6514): avc: denied { read } for name="usb" dev="tmpfs" ino=90942 scontext=u:r:untrusted_app:s0:c243,c256,c512,c768 tcontext=u:object_r:usb_device:s0 tclass=dir permissive=1 app=com.example.openvino_test
03-24 11:00:46.977 32315 32335 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 32335 (RenderThread), pid 32315 (e.openvino_test)
```

I thought it might be caused by the SELinux, so I changed it to Permissive mode, but with no luck.

Could someone give me some help?
Thx!

**Comment by dkurt** [comment]
Hi! Please share what is a host with Android and how NCS2 is connected?

**Comment by ShinoharaHare** [comment]
> Hi! Please share what is a host with Android and how NCS2 is connected?

Sorry, I'm not sure what "host" is (not a native speaker).
Does it mean some hardware and OS information?
If I get it wrong, please tell me what specific information should I provide.

Phone model: HTC 10
CPU Arch: arm64-v8a
ROM: crDroid 6.4
Android Version: 10

I connect NCS2 to Android Device via OTG.

And I just realize that ".mvcmd" files should also be copied to Android(they didn't), but I'm not sure where they should be place, so IE can found them.

**Comment by dkurt** [comment]
@ShinoharaHare, you understood it correct :) Android based phones should be rooted to use any USB device by USB. Have you completed this procedure?

`.mvcmd` are expected to be at the same location as `.so` libraries. BTW, maybe the latest changes with JAR archive may help you here? See https://github.com/openvinotoolkit/openvino_contrib/pull/18

**Comment by ShinoharaHare** [comment]
@dkurt
Yes, it's rooted.
Ok, I will try the java thing later.

Now, I'm trying to test the same code with C++ and run it through adb shell
```cpp
#include <ie_core.hpp>

using namespace InferenceEngine;

int main() {
    Core core("/sdcard/data/plugins.xml");
    CNNNetwork cnnNetwork = core.ReadNetwork("/sdcard/data/age-gender-recognition-retail-0013.xml");
    ExecutableNetwork eNetwork = core.LoadNetwork(cnnNetwork, "MYRIAD");

    return 0;
}
```
and I got "**Failed to find booted device after boot**"
```
E: [ncAPI] [    538518] [] ncDeviceOpen:1013    Failed to find booted device after boot
terminating with uncaught exception of type InferenceEngine::GeneralError:
inference-engine/src/inference_engine/ie_plugin_cpp.hpp:101
inference-engine/src/vpu/myriad_plugin/myriad_executor.cpp:279 Can not init Myriad device: NC_ERROR
Aborted
```
Do you have any clue about this?

**Comment by dkurt** [comment]
@ShinoharaHare, let's check if firmware (.mvcmd) is found. Try to rename these files and see if error will change.

**Comment by ShinoharaHare** [comment]
@dkurt 
```
E: [ncAPI] [    557439] [] getFirmwarePath:639  Firmware not found in: /system/lib64/usb-ma248x.mvcmd
E: [ncAPI] [    557439] [] ncDeviceOpen:917     Can't get firmware, error: NC_ERROR
terminating with uncaught exception of type InferenceEngine::GeneralError: 
inference-engine/src/inference_engine/ie_plugin_cpp.hpp:101
inference-engine/src/vpu/myriad_plugin/myriad_executor.cpp:279 Can not init Myriad device: NC_MVCMD_NOT_FOUND
Aborted
```

looks like it was found.

**Comment by ShinoharaHare** [comment]
when running the test code:
```
pme:/ $ lsusb
Bus 001 Device 010: ID 03e7:f63b
Bus 001 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0003
```
after the test code terminated:
```
pme:/ $ lsusb
Bus 001 Device 011: ID 03e7:2485
Bus 001 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0003
```

The PID changed  correctly though.

**Comment by dkurt** [comment]
@ShinoharaHare, that seems correct. 
Well, maybe adding the following file may help (however, it's for Linux, not sure if actual for Android):

```
$ cat /etc/udev/rules.d/97-myriad-usbboot.rules 
SUBSYSTEM=="usb", ATTRS{idProduct}=="2150", ATTRS{idVendor}=="03e7", GROUP="users", MODE="0660", ENV{ID_MM_DEVICE_IGNORE}="1"
SUBSYSTEM=="usb", ATTRS{idProduct}=="2485", ATTRS{idVendor}=="03e7", GROUP="users", MODE="0660", ENV{ID_MM_DEVICE_IGNORE}="1"
SUBSYSTEM=="usb", ATTRS{idProduct}=="f63b", ATTRS{idVendor}=="03e7", GROUP="users", MODE="0660", ENV{ID_MM_DEVICE_IGNORE}="1"
```
(reboot required)

**Comment by dkurt** [comment]
@ShinoharaHare, BTW, are you in `adb root` model?

**Comment by ShinoharaHare** [comment]
@dkurt, I run ```adb shell``` first then type ```su```
are they different?

**Comment by dkurt** [comment]
@ShinoharaHare, Unfortunately, I don't know :) May I ask to try?

**Comment by ShinoharaHare** [comment]
@dkurt, ok I'm trying it.

**Comment by ShinoharaHare** [comment]
![2021-03-24 230734](https://user-images.githubusercontent.com/47121592/112333673-c41c5780-8cf5-11eb-9724-f2fccc76709b.png)
Same errors

**Comment by ShinoharaHare** [comment]
I'v been testing this all day, and finally found out how to solve "Failed to find booted device after boot".
**libusb1.0.so** I built caused the error. After I replaced it with the prebuilt version in the **temp/vpu/libusb/libs**, it worked.
So basically, NCS2 worked on my android phone now(not yet test the inferring though), but only in shell.

**Comment by ShinoharaHare** [comment]
I still can not run it within an Android App.
Both Java API and JNI crashed as long as I changed the device name from **CPU** to **MYRIAD**, and threw the error
```libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid ...```
I think it would be easier if I know how to debug and get the error message properly.
Does anyone familiar with ndk debugging?

Also, I want to mention that the default firmware search path may not work properly in an android app, because the native libraries will be bundled into APK.
Is it hardcoded or I can change the "customFirmwareDirectory" programmatically?

**Comment by dkurt** [comment]
@ShinoharaHare, probably, you may try to change source code in VPU plugin to change firmware search location.

@likholat l, we already tried it, do you have some notes about required changes?

**Comment by ShinoharaHare** [comment]
The problem is solved.
It was caused by the permission. The global lock file location is set to "/data/local/tmp/mvnc.mutex" which need root permission to RW. After I chmod it to 666 it works now.

And Line 746 in mvnc_api.c ```exit(1);``` somehow prevents me getting useful error message, and makes it so hard to debug.
After I solve this problem, the "useful" error messages shows normally now.

**Comment by ShinoharaHare** [comment]
Since my problem solved, I'm closing this issue.
@dkurt Thanks for the help!

**Comment by dkurt** [comment]
@ShinoharaHare, thank you so much! You're experiment is very useful.

**Comment by jeomincham** [comment]
Hi,
[](url)
I'm trying to run IE with CPU on Android through the Java API.
I built OpenVINO and modules in openvino_contrib

When I run to `core.ReadNetwork(s + "vehicle-attributes-recognition-barrier-0039.xml")`, the following error occurs:


`
SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0))
`

**Comment by dkurt** [comment]
@jeomincham, on which CPU? For x86 you may follow our paper: https://medium.com/@anna.likholat/sign-language-recognition-on-android-with-intel-openvino-1296d76bfa5e

**Comment by jeomincham** [comment]
> @jeomincham, on which CPU? For x86 you may follow our paper: https://medium.com/@anna.likholat/sign-language-recognition-on-android-with-intel-openvino-1296d76bfa5e

@dkurt ,Thank you very much for your reply.  I want to run it on an ARM CPU first and then on NCS2 .  According to the paper, I built OpenVINO and modules in openvino_contrib with following command :
 
`cmake \
  -DANDROID_ABI=arm64-v8a \
  -DTHREADING=SEQ \
  -DANDROID_PLATFORM=21 \
  -DANDROID_STL=c++_shared \
  -DENABLE_VPU=OFF \
  -DENABLE_MKL_DNN=ON \
  -DENABLE_GNA=OFF \
  -DENABLE_CLDNN=OFF \
  -DENABLE_OPENCV=OFF \
  -DENABLE_SAMPLES=OFF \
  -DIE_EXTRA_MODULES=~/Downloads/openvino_contrib/modules \
  -DCMAKE_TOOLCHAIN_FILE=~/downloads/android-ndk/build/cmake/android.toolchain.cmake ..`

After a successful build on Ubuntu , the plugins.xml :
`<ie>
    <plugins>
        <plugin name="AUTO" location="libAutoPlugin.so">
        </plugin>
        <plugin name="HETERO" location="libHeteroPlugin.so">
        </plugin>
        <plugin name="MULTI" location="libMultiDevicePlugin.so">
        </plugin>
        <plugin name="MYRIAD" location="libmyriadPlugin.so">
        </plugin>
    </plugins>
</ie>`
No `CPU` included .  So when I run `ExecutableNetwork executableNetwork = core.LoadNetwork(net, "CPU") `

the error `Device with "CPU" name is not registered in the InferenceEngine on CPU` has occurred , even though I added this parameter  ` -DENABLE_MKL_DNN=ON \`  when I built .  

I sincerely look forward to your reply. Thank you very much !

**Comment by jeomincham** [comment]
> @jeomincham, on which CPU? For x86 you may follow our paper: https://medium.com/@anna.likholat/sign-language-recognition-on-android-with-intel-openvino-1296d76bfa5e

@dkurt ,Thank you very much for your reply.  I want to run it on an ARM CPU first and then on NCS2 .  According to the paper, I built OpenVINO and modules in openvino_contrib with following command :
 
`cmake \
  -DANDROID_ABI=arm64-v8a \
  -DTHREADING=SEQ \
  -DANDROID_PLATFORM=21 \
  -DANDROID_STL=c++_shared \
  -DENABLE_VPU=OFF \
  -DENABLE_MKL_DNN=ON \
  -DENABLE_GNA=OFF \
  -DENABLE_CLDNN=OFF \
  -DENABLE_OPENCV=OFF \
  -DENABLE_SAMPLES=OFF \
  -DIE_EXTRA_MODULES=~/Downloads/openvino_contrib/modules \
  -DCMAKE_TOOLCHAIN_FILE=~/downloads/android-ndk/build/cmake/android.toolchain.cmake ..`

After a successful build on Ubuntu , the plugins.xml :
`<ie>
    <plugins>
        <plugin name="AUTO" location="libAutoPlugin.so">
        </plugin>
        <plugin name="HETERO" location="libHeteroPlugin.so">
        </plugin>
        <plugin name="MULTI" location="libMultiDevicePlugin.so">
        </plugin>
        <plugin name="MYRIAD" location="libmyriadPlugin.so">
        </plugin>
    </plugins>
</ie>`
No `CPU` included .  So when I run `ExecutableNetwork executableNetwork = core.LoadNetwork(net, "CPU") `

the error `Device with "CPU" name is not registered in the InferenceEngine on CPU` has occurred , even though I added this parameter  ` -DENABLE_MKL_DNN=ON \`  when I built .  

I sincerely look forward to your reply. Thank you very much !

**Comment by likholat** [comment]
@jeomincham, I think, you should use the ARM plugin: https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin

**Comment by likholat** [comment]
@alvoron, maybe you can help with this problem: https://github.com/openvinotoolkit/openvino/issues/4925#issuecomment-856661132

**Comment by jeomincham** [comment]
> @jeomincham, I think, you should use the ARM plugin: https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin

but the Arm plugin module supported as  the following
Host | OS
-- | --
Raspberry Pi* 4 Model B | Debian* 9 (32-bit)
Raspberry Pi* 4 Model B | Debian* 10.3 (32-bit)
Raspberry Pi* 4 Model B | Ubuntu* 18.04 (64-bit)

On the Andoid platform , can not  build the module wirh the given three approachs

**Comment by jeomincham** [comment]
> Hi,
> 
> I'm trying to run IE with NCS2 on Android through the Java API.
> I built OpenVINO and modules in openvino_contrib, and ran with CPU successfully.
> 
> ```shell
> cmake .. \
>   -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
>   -DANDROID_ABI=arm64-v8a \
>   -DTHREADING=SEQ \
>   -DANDROID_PLATFORM=21 \
>   -DANDROID_STL=c++_shared \
>   -DENABLE_OPENCV=OFF \
>   -DENABLE_SAMPLES=OFF \
>   -DENABLE_TESTS=OFF \
>   -DENABLE_DOCS=OFF \
>   -DIE_EXTRA_MODULES=${openvino_contrib}/modules \
> ```
> 
> ```java
> IECore core = new IECore("/sdcard/data/plugins.xml");
> CNNNetwork cnnNetwork = core.ReadNetwork("/sdcard/data/age-gender-recognition-retail-0013.xml");
> ExecutableNetwork executableNetwork = core.LoadNetwork(cnnNetwork, "CPU");
> ```


@ShinoharaHare Hi , I built OpenVINO and modules in openvino_contrib  with your Cmake shell script , When I do make,
```
[ 62%] Linking CXX shared library ../../../../bin/aarch64/Release/lib/libinference_engine.so
Remove MultiDevicePlugin from the plugins.xml file
Remove HeteroPlugin from the plugins.xml file
Remove clDNNPlugin from the plugins.xml file
Remove GNAPlugin from the plugins.xml file
Remove MKLDNNPlugin from the plugins.xml file
Remove myriadPlugin from the plugins.xml file
Register myriadPlugin plugin

```
`Remove MKLDNNPlugin from the plugins.xml file`,the `CPU` not included in the `plugins.xml` and there is no `libMKLDNNPlugin.so` in the `openvino/bin/aarch64/Release/lib` directory .

Could you please help me ?
Thx a lot !

**Comment by ShinoharaHare** [comment]
@jeomincham Hi,

According to the docs: 
- ```ENABLE_MKL_DNN``` enables CPU plugin compilation:
    - ```ON``` is default for x86 platforms; OFF, otherwise.

So, if you want to enable it on ARM platforms, you should set ```ENABLE_MKL_DNN``` to ```ON``` explicitly.

And according to my experience, ```CPU``` won't be included in ```plugins.xml```.
If you build with my script, it should looks like:
```xml
<ie>
    <plugins>
        <plugin name="HETERO" location="libHeteroPlugin.so">
        </plugin>
        <plugin name="MULTI" location="libMultiDevicePlugin.so">
        </plugin>
        <plugin name="MYRIAD" location="libmyriadPlugin.so">
        </plugin>
        <plugin name="ARM" location="libarmPlugin.so">
        </plugin>
    </plugins>
</ie>
```

**Comment by jeomincham** [comment]
@ShinoharaHare  Hi, 
  I have run your script many times , the `plugs.xml` results of each successful build are shown below :
```xml
<ie>
    <plugins>
        <plugin name="AUTO" location="libAutoPlugin.so">
        </plugin>
        <plugin name="HETERO" location="libHeteroPlugin.so">
        </plugin>
        <plugin name="MULTI" location="libMultiDevicePlugin.so">
        </plugin>
        <plugin name="MYRIAD" location="libmyriadPlugin.so">
        </plugin>
    </plugins>
</ie>
```
Mine don't have `<plugin name="ARM" location="libarmPlugin.so">  </plugin>`,
But I have this `<plugin name="AUTO" location="libAutoPlugin.so"></plugin>` extra row. I have built on the following machine:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
Build on Android* Systems follow this guide [https://github.com/openvinotoolkit/openvino/wiki/BuildingForAndroid](url) , except run cmake to create makefiles.

Looking forward to your reply .
Thx !

**Comment by ShinoharaHare** [comment]
@jeomincham 

The source code I built is committed around 3 month ago. Maybe there are some changes during the time.

Have you tested the binaries on Android?
Is it not working?

**Comment by alvoron** [comment]
@jeomincham we were able to run ARM plugin on Android device. This fact is not highlighted in the documentation yet, since we're working on the article which explains how to build the plugin and run a demo on Android device.
You can build ARM plugin together with OpenVINO by the following command:
```
cmake -DCMAKE_BUILD_TYPE=Release \ 
      -DTHREADING=SEQ \ 
      -DIE_EXTRA_MODULES=~/android_ov/openvino_contrib/modules \ 
      -DBUILD_java_api=ON \ 
      -DCMAKE_TOOLCHAIN_FILE=~/android_ov/android-ndk-r20/build/cmake/android.toolchain.cmake \ 
      -DANDROID_ABI=arm64-v8a \ 
      -DANDROID_PLATFORM=29 \ 
      -DANDROID_STL=c++_shared \ 
      -DENABLE_SAMPLES=OFF \ 
      -DENABLE_OPENCV=OFF \ 
      -DENABLE_CLDNN=OFF \ 
      -DENABLE_VPU=OFF \ 
      -DENABLE_GNA=OFF \ 
      -DENABLE_MYRIAD=OFF \ 
      -DENABLE_TESTS=OFF \ 
      -DENABLE_GAPI_TESTS=OFF \ 
      -DENABLE_BEH_TESTS=OFF .. && make --jobs=$(nproc --all)

**Comment by ShinoharaHare** [comment]
> @ShinoharaHare Hi,
> I have run your script many times , the `plugs.xml` results of each successful build are shown below :
> 
> ```
> <ie>
>     <plugins>
>         <plugin name="AUTO" location="libAutoPlugin.so">
>         </plugin>
>         <plugin name="HETERO" location="libHeteroPlugin.so">
>         </plugin>
>         <plugin name="MULTI" location="libMultiDevicePlugin.so">
>         </plugin>
>         <plugin name="MYRIAD" location="libmyriadPlugin.so">
>         </plugin>
>     </plugins>
> </ie>
> ```
> 
> Mine don't have `<plugin name="ARM" location="libarmPlugin.so"> </plugin>`,
> But I have this `<plugin name="AUTO" location="libAutoPlugin.so"></plugin>` extra row. I have built on the following machine:
> 
> ```
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.5 LTS
> Release:	18.04
> Codename:	bionic
> ```
> 
> Build on Android* Systems follow this guide [https://github.com/openvinotoolkit/openvino/wiki/BuildingForAndroid](url) , except run cmake to create makefiles.
> 
> Looking forward to your reply .
> Thx !

I test the latest commit both **openvino** and **openvino_contrib**, and the ```plugins.xml``` looks like:
```xml
<ie>
    <plugins>
        <plugin name="AUTO" location="libAutoPlugin.so">
        </plugin>
        <plugin name="HETERO" location="libHeteroPlugin.so">
        </plugin>
        <plugin name="MULTI" location="libMultiDevicePlugin.so">
        </plugin>
        <plugin name="MYRIAD" location="libmyriadPlugin.so">
        </plugin>
        <plugin name="CPU" location="libarmPlugin.so">
        </plugin>
    </plugins>
</ie>
```
so your ```plugins.xml``` do miss the ```CPU```.

As @alvoron mentioned above, did you clone the  **openvino_contrib** repository and set ```IE_EXTRA_MODULES``` to the corresponding path?

**Comment by jeomincham** [comment]
@ShinoharaHare ,@alvoron  I built it on another machine, have successfully generated `libarmPlugin.so` .Thank you both for taking the time to reply and giving me a lot of help !

**Comment by meilovech** [comment]
> @dkurt
> Yes, it's rooted.
> Ok, I will try the java thing later.
> 
> Now, I'm trying to test the same code with C++ and run it through adb shell
> 
> ```c++
> #include <ie_core.hpp>
> 
> using namespace InferenceEngine;
> 
> int main() {
>     Core core("/sdcard/data/plugins.xml");
>     CNNNetwork cnnNetwork = core.ReadNetwork("/sdcard/data/age-gender-recognition-retail-0013.xml");
>     ExecutableNetwork eNetwork = core.LoadNetwork(cnnNetwork, "MYRIAD");
> 
>     return 0;
> }
> ```

@ShinoharaHare Hi,
I have run  with CPU on Android through the Java API  successfully. Now I need running Inference Engine with NCS2 on Android , but a collapse occurs without no error infomation when `core.LoadNetwork(net, "MYRIAD") `is executed.

According to your clues, I'm trying to test the same code with C++ and run it through adb shell

```
arm-linux-gnueabihf-g++-7 -L openvino/inference-engine/include  ncs.cpp 
```
ncs.cpp :
```C++
#include <ie_core.hpp>
using namespace InferenceEngine;
int main() {
    Core core("/data/plugins.xml");
    CNNNetwork cnnNetwork = core.ReadNetwork("/data/age-gender-recognition-retail-0013.xml");
    ExecutableNetwork eNetwork = core.LoadNetwork(cnnNetwork, "MYRIAD");
    return 0;
}

```
the `ie_core.hpp` Cannot be imported when i run the `arm-linux-gnueabihf-g++-7` command even the `ie_core.hpp`file In the  `openvino/inference-engine/include`directory。

How can I test the C++ code and run it through adb shell ?
sincere

**Comment by ShinoharaHare** [comment]
@meilovech , Hi

If I remember correctly,  ```-L``` flag is for archive library search path. You should use the ```-I``` flag to add header file paths.

And according to my experience, crash may be due to:

1. Lack of permission to access USB device.
2. Firmware files were not found.
3. Lack of permission to read and write mutex lock file.

```exit(1);``` in ```mvnc_api.c``` may be the cause of crashing without error information. You would like to look around it, and may find some clues.

**Comment by meylovede** [comment]
@ShinoharaHare, I run this command `arm-linux-gnueabihf-g++-7 -I openvino/inference-engine/include -L openvino/inference-engine/include  ncs.cpp`  

the reuslt is below:

```
/tmp/cciptlEl.o: In function `main':
ncs.cpp:(.text+0x102): undefined reference to `InferenceEngine::Core::Core(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
ncs.cpp:(.text+0x150): undefined reference to `InferenceEngine::Core::ReadNetwork(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
ncs.cpp:(.text+0x1be): undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
/tmp/cciptlEl.o: In function `InferenceEngine::ExecutableNetwork::~ExecutableNetwork()':
ncs.cpp:(.text._ZN15InferenceEngine17ExecutableNetworkD2Ev[_ZN15InferenceEngine17ExecutableNetworkD5Ev]+0x20): undefined reference to `InferenceEngine::details::SharedObjectLoader::~SharedObjectLoader()'
collect2: error: ld returned 1 exit status

```
can not to generate the `a.out` file . What can be done to get the right result ? 
THX!

**Comment by ShinoharaHare** [comment]
No offense, but it looks like you are not familiar with the c++ building stuff. I suggest that you skip this part, because I think it will be easier and more efficient to do it with the Java API.

`mvnc.mutex` will be automatically created if it has the permission which I think it hasn't. So you may need to change the path from `/data/local/tmp` to `/sdcard/ or wherever your application can access.

**Comment by meylovede** [comment]
@ShinoharaHare, Okay, I am really not familiar with C++, I will continue  the test according to your suggestion and clues, thank you very much for your share!

**Comment by meylovede** [comment]
> The problem is solved.
> It was caused by the permission. The global lock file location is set to "/data/local/tmp/mvnc.mutex" which need root permission to RW. After I chmod it to 666, it works now.
> 
> And Line 746 in mvnc_api.c `exit(1);` somehow prevents me getting useful error message, and makes it so hard to debug.
> After I solve this problem, the "useful" error messages shows normally now.

@ShinoharaHare ,Hi
I'm sorry to disturb you again. I find `mvnc_api.c`  under ubuntu `openvino/inference-engine/thirdparty/movidius/mvnc/src/`,But my Android project and Android machine don't have this file. What should I do to make it easier to debug  at Android studio project？

 Line 746 in mvnc_api.c :
```C
 if (!global_lock_fd) {
            mvLog(MVLOG_ERROR, "global mutex initialization failed");
            exit(1);
        }
```

**Comment by ShinoharaHare** [comment]
@meylovede, No worries, feel free to ask me questions.

This file is one of the source code files, so you want to edit it and rebuild the corresponding libraries(.so files). after the new libraries are built, you should copy them to your android project again.

**Comment by meylovede** [comment]
@ShinoharaHare THX , so I need edit `mvnc_api.c` file ,and run 
```
cmake .. \
  -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
  -DANDROID_ABI=arm64-v8a \
  -DTHREADING=SEQ \
  -DANDROID_PLATFORM=21 \
  -DANDROID_STL=c++_shared \
  -DENABLE_OPENCV=OFF \
  -DENABLE_SAMPLES=OFF \
  -DENABLE_TESTS=OFF \
  -DENABLE_DOCS=OFF \
  -DIE_EXTRA_MODULES=${openvino_contrib}/modules \
```

this command again?

**Comment by ShinoharaHare** [comment]
@meylovede
Not 100% sure, but you may not need to do so.
Just run `make` again.

**Comment by meylovede** [comment]
@ShinoharaHare 
I remove the `exit(1);` in the `mvnc_api.c`  and just run make again.
`libmvnc. a` is regenerated  but without `libmvnc.so` or `libmvnc_api.so`

The build process for make `mvnc_api.c`  is as follows:
```c
[ 43%] Built target frontend_manager
/home/pax/Downloads/openvino/inference-engine/thirdparty/movidius/mvnc/src/mvnc_api.c:667:13: warning: 
      'printfOverXLinkOpen' [-Wunused-function]
static void printfOverXLinkOpen(struct _devicePrivate_t *d);
            ^
/home/pax/Downloads/openvino/inference-engine/thirdparty/movidius/mvnc/src/mvnc_api.c:668:13: warning: 
      'printfOverXLinkClose' [-Wunused-function]
static void printfOverXLinkClose(struct _devicePrivate_t *d);
            ^
/home/pax/Downloads/openvino/inference-engine/thirdparty/movidius/mvnc/src/mvnc_api.c:1344:19: warning:
      'deviceSetStdIO2XLink' [-Wunused-function]
static ncStatus_t deviceSetStdIO2XLink(struct _devicePrivate_t *d, uint32_t data)
                  ^
[ 44%] Built target ngraph_backend
3 warnings generated.
[ 44%] Linking CXX static library ../../../../bin/aarch64/Release/lib/libmvnc.a

```

**Comment by ShinoharaHare** [comment]
@meylovede
.a files are static libraries, they will be bundle into other .so files, so libraries that use libmvnc.a as dependency will be regenerated.

**Comment by meylovede** [comment]
@ShinoharaHare ,Hi
I can debug now , but when i run `core.LoadNetwork(net, "MYRIAD")` , the `InferenceEngineException: LoadNetwork: Can not init Myriad device: NC_ERROR` occurred.  According to your experience ，I use the `/temp/vpu/libusb/libs/arm64-v8a/libusb1.0.so` .

And when running the code:
```
roc_plus:/ # lsusb
Bus 001 Device 002: ID 0bda:d723
Bus 007 Device 010: ID 03e7:2485
Bus 001 Device 001: ID 1d6b:0002
```
The PID didn't changed correctly.

One more question, after executing the command  `cmake` and `make`  ,Whether the NCS2 Android driver is automatically configured?  if not, how can i configure the NCS2 Android driver and  use the `97-myriad-usbboot.rules` file?

**Comment by ShinoharaHare** [comment]
@meylovede 

make sure the following things are done:

1. set SELinux to Permissive mode
2. change firmware search path to wherever your app can access and copy the firmware to there
3. change the global lock file path to wherever your app can access 

No, you have to configure it yourself, however `.rules` files didn't work on my device, so i'm not sure whether you need to configure it or not. In my case it's not necessary.

**Comment by meylovede** [comment]
@ShinoharaHare ,Hi 
I hava set  the android machine SELinux to Permissive mode
```
C:\Users\>adb shell
rk3399_roc_pc_plus:/ # getenforce
Permissive
```
But, I put the `usb-ma2x8x.mvcmd` ,`usb-ma2x8x.mvcmd` file   to  the `\app\src\main\jniLibs\arm64-v8a` ,It didn't seem to work, suggest the following information:
` LoadNetwork: Can not init Myriad device: NC_ERROR`

I want to know the default firmware search path  and which source code file  in VPU plugin  modified ,it can change the firmware search location ?

THX !

**Comment by ShinoharaHare** [comment]
Firmware:
https://github.com/openvinotoolkit/openvino/blob/5ba1e8aa1c8addd84ad454d918002f58bbd32761/inference-engine/src/vpu/myriad_plugin/myriad_executor.cpp#L143

Global Lock File:
https://github.com/openvinotoolkit/openvino/blob/e61a594199ab222d8239635b1d651ce3f6bf11a4/inference-engine/thirdparty/movidius/mvnc/src/mvnc_api.c#L753

Also, while I was searching the above things for you, I found that there is `97-myriad-usbboot.rules` under `openvino/inference-engine/thirdparty/movidius/mvnc/src/`

**Comment by meylovede** [comment]
> make sure the following things are done:
> 
> 1. set SELinux to Permissive mode
> 2. change firmware search path to wherever your app can access and copy the firmware to there
> 3. change the global lock file path to wherever your app can access
> 
> No, you have to configure it yourself, however `.rules` files didn't work on my device, so i'm not sure whether you need to configure it or not. In my case it's not necessary.

@ShinoharaHare ,Hi
I have automatically generated the `mvnc.mutex`file  and modified the source code` dirName = "/data/local/tmp"` to change the 
firmware search path,the three things have been done. But when I run `core.LoadNetwork(cnnNetwork, "MYRIAD")`   this info `LoadNetwork: Can not init Myriad device: NC_ERROR` has hanppened too. 

I found that there is 97-myriad-usbboot.rules under `openvino/inference-engine/thirdparty/movidius/mvnc/src/` , but don't know how to use it on Android to configure the NCS2.

please give me some help，THX!

**Comment by ShinoharaHare** [comment]
@meylovede 

Could you show me the path you set (both lock file and firmware), and where you place the firmware files.

**Comment by meylovede** [comment]
@ShinoharaHare 
Both lock file and firmware path is under `/data/local/tmp` ,and I copy the `.mvcmd` files to this directory . the`/data` directory has set `chmod 777`
```
data
│  
└─local
        │  
	└─--tmp
		│---lldb-server
		│---mvnc.mutex
		│---pcie-ma2x8x.mvcmd
		│---start_lldb_server.sh
		└─--usb-ma2x8x.mvcmd
```

**Comment by ShinoharaHare** [comment]
@meylovede 

Not sure, but you may need to `chmod` both parents and children files/folder.

 ```
/data
/data/tmp
/data/tmp/mvnc.mutex
.
.
.
```

Also, you can try the path where you place `plugins.xml` or somewhere that don't need to `chmod`.

**Comment by meylovede** [comment]
@ShinoharaHare
Make sure chmod all the parents and children files/folders，because the command is `chmod 777 -R` ， and hava used `ls -l `to check those files' permission.
the `plugins.xml`  file i put under `/data` too.

In addition, where is the firmware's default search path ?

**Comment by ShinoharaHare** [comment]
@meylovede 

Probably at `/system/lib` or `/system/lib64`

**Comment by ShinoharaHare** [comment]
You may want to build a debug version without stripping, and check the tombstone after crashing.

**Comment by meylovede** [comment]
@ShinoharaHare
Thank you for this idea. I will try it !

**Comment by meylovede** [comment]
@ShinoharaHare ,Hi
when I excute the  `core.LoadNetwork(net, "MYRIAD")` ,some errors occurred.

```
  InferenceEngineException: 
    	LoadNetwork: 
   /openvino/inference-engine/src/inference_engine/ie_common.cpp:73 
   /openvino/inference-engine/src/vpu/common/include/vpu/utils/error.hpp:39 [ GENERAL_ERROR ] 
   /openvino/inference-engine/src/vpu/graph_transformer/src/frontend/remove_const_layers.cpp:24 FrontEnd::removeConstLayers expects CNNNetworkImpl
```
How do I deal with it ? THX!
