### ISSUE TITLE
libinference_engine_transformations.so => not found

### ISSUE THREAD

**Issue by uglymie** [openvinotoolkit/openvino#4926]
I installed openvino with ubuntu 20.04 system, and then used it to develop my own program. The compilation can pass, but the problem of not being able to link the libinference_engine_transformations.so library occurs during runtime.
Later I found that I couldn’t find that library when I ldd libinference_engine.so

Can someone help me answer it? Does openvino still not support Ubuntu 20.04?

**Comment by brmarkus** [comment]
Can you share which OpenVINO version you have installed?
(Yesterday, OpenVINO 2021.3 was published; the ReleaseNotes indicate that Ubuntu 18 is "phasing out" and Ubuntu 20 "phasing in...)

**Comment by brmarkus** [comment]
Have you called "source /opt/intel/openvino/bin/setupvars.sh"? Some do set the ENV variables manually...

On my machine I see:
```
$ cd /opt/intel/openvino/
$ find . -name libinference_engine.*
      ./deployment_tools/inference_engine/lib/intel64/libinference_engine.so
$ ldd ./deployment_tools/inference_engine/lib/intel64/libinference_engine.so
        linux-vdso.so.1 (0x00007ffc72356000)
        libtbb.so.2 => /opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2 (0x00007f1df922c000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1df9028000)
        libinference_engine_transformations.so => /opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/libinference_engine_transformations.so (0x00007f1df8caa000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1df8a8b000)
        libngraph.so => /opt/intel/openvino_2021/deployment_tools/ngraph/lib/libngraph.so (0x00007f1df83c2000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1df8039000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1df7e21000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1df7a30000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1df9767000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1df7828000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1df748a000)
```

**Comment by uglymie** [comment]
> 您是否称“源/opt/intel/openvino/bin/setupvars.sh”？有些确实手动设置ENV变量...
> 
> 在我的机器上，我看到：
> 
> ```
> $ cd /opt/intel/openvino/
> $ find . -name libinference_engine.*
>       ./deployment_tools/inference_engine/lib/intel64/libinference_engine.so
> $ ldd ./deployment_tools/inference_engine/lib/intel64/libinference_engine.so
>         linux-vdso.so.1 (0x00007ffc72356000)
>         libtbb.so.2 => /opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2 (0x00007f1df922c000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1df9028000)
>         libinference_engine_transformations.so => /opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/libinference_engine_transformations.so (0x00007f1df8caa000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1df8a8b000)
>         libngraph.so => /opt/intel/openvino_2021/deployment_tools/ngraph/lib/libngraph.so (0x00007f1df83c2000)
>         libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1df8039000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1df7e21000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1df7a30000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007f1df9767000)
>         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1df7828000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1df748a000)
> ```

**Comment by uglymie** [comment]
> Have you called "source /opt/intel/openvino/bin/setupvars.sh"? Some do set the ENV variables manually...
> 
> On my machine I see:
> 
> ```
> $ cd /opt/intel/openvino/
> $ find . -name libinference_engine.*
>       ./deployment_tools/inference_engine/lib/intel64/libinference_engine.so
> $ ldd ./deployment_tools/inference_engine/lib/intel64/libinference_engine.so
>         linux-vdso.so.1 (0x00007ffc72356000)
>         libtbb.so.2 => /opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2 (0x00007f1df922c000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1df9028000)
>         libinference_engine_transformations.so => /opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/libinference_engine_transformations.so (0x00007f1df8caa000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1df8a8b000)
>         libngraph.so => /opt/intel/openvino_2021/deployment_tools/ngraph/lib/libngraph.so (0x00007f1df83c2000)
>         libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1df8039000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1df7e21000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1df7a30000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007f1df9767000)
>         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1df7828000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1df748a000)
> ```

thank you for your reply。The openvino version I installed is 2021.2.185
I am sure I set the environment variable，It's like this on my machine：

$ ldd ./deployment_tools/inference_engine/lib/intel64/libinference_engine.so
linux-vdso.so.1 (0x00007fff0cd21000)
libtbb.so.2 => /lib/x86_64-linux-gnu/libtbb.so.2 (0x00007fa9d2b87000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa9d2b81000)
libinference_engine_transformations.so => not found
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa9d2b5e000)
libngraph.so => /opt/intel/openvino_2021.2.185/deployment_tools/ngraph/lib/libngraph.so (0x00007fa9d2652000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa9d246f000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa9d2454000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa9d2262000)
/lib64/ld-linux-x86-64.so.2 (0x00007fa9d2d04000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa9d2113000)

you can see “libinference_engine_transformations.so => not found”

**Comment by uglymie** [comment]
I tried to install the latest version: OpenVINO 2021.3, but the result is still the same

**Comment by uglymie** [comment]
I think I found out what went wrong. I set the environment variables of openvino before the environment variables of some other libraries, in .bashrc. The above problem appeared.
When I set the environment variable of openvino to the last line of .bashrc, the problem was solved.
