### ISSUE TITLE
Missing a letter "g" in article <<Permanently Set OpenVINO™ Environment Variables for Windows® 10>> 

### ISSUE THREAD

**Issue by NextBG** [openvinotoolkit/openvino#495]
On tutorial Permanently Set OpenVINO™ Environment Variables for Windows® 10, https://www.intel.com/content/www/us/en/support/articles/000033440/boards-and-kits/neural-compute-sticks.html 
There is a line %INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\bin\intel64\Debu missing a "g".
![捕获](https://user-images.githubusercontent.com/49566324/81965531-c11ef800-964a-11ea-913c-742c6353b02e.PNG)

**Comment by leavim** [comment]
@NextBG this typo has been addressed in document, update should reflect in document shortly. Thanks for reporting this.

**Comment by avitial** [comment]
Document has been updated.
