### ISSUE TITLE
Feature Request - get_perf_counts - Return total number of CPU Time and Number of FLOPs/MACs

### ISSUE THREAD

**Issue by nullbyte91** [openvinotoolkit/openvino#496]
Hi All,

I'm trying to benchmark the CPU performance by using get_perf_counts().
```python
# Running Inference
net.requests[0].infer({input_name:input_img})
#Print the layer wise performance output
pp.pprint(net.requests[0].get_perf_counts())
``` 

The output looks like for Conv Layer,
```bash
'conv2d_1_1/convolution': {   'cpu_time': 26,
                                  'exec_type': 'jit_avx2_FP32',
                                  'execution_index': 3,
                                  'layer_type': 'Convolution',
                                  'real_time': 26,
                                  'status': 'EXECUTED'},
```
I would like to have a total CPU time, and the number of FLOPs performed one single forward pass as part of the same method.

I'm happy to contribute to this.
 
Regards,
Jegathesan S

**Comment by avitial** [comment]
Hi @nullbyte91 we have captured this feature request and forwarded it to development team for consideration. Thanks for using OpenVINO!

**Comment by nullbyte91** [comment]
@avitial Thank you.

**Comment by avitial** [comment]
@nullbyte91 after consideration the development team has decided not to implement this feature request.
