### ISSUE TITLE
Support TF 2.2+ Efficientnets

### ISSUE THREAD

**Issue by TechnikEmpire** [openvinotoolkit/openvino#497]
In order to support conversion of Effnets from TF2.2, you just need to disable eager execution in this function before the calls to tf.placeholder.

Like so:

```
def add_placeholders_to_subgraph(node: Node):
    """
    Adds placeholders to the node's list of protobufs based on input nodes to the subgraph (the value of
    'internal_input_node_name' property).
    The function also updates input tensors for nodes which consume output of nodes that were replaced with
    placeholders.
    :param node: the node to add placeholders to.
    :return: None
    """
Add   -->>>>  tf_v1.compat.v1.disable_eager_execution()
    inputs_replacements = list()
```

https://github.com/openvinotoolkit/openvino/blob/94dd082199444dbe772eb522a87138494391470d/model-optimizer/mo/front/tf/partial_infer/tf.py#L195

**Comment by TechnikEmpire** [comment]
Sorry for no PR I'm stepping out for a few days, just wanted to make a note so I don't forget, maybe someone else can scoop this up.

**Comment by lazarevevgeny** [comment]
@rkazants , this should probably solve the issue 36906.

**Comment by jgespino** [comment]
OpenVINO supports TensorFlow 2.X Object Detection API models including 8 EfficientDet models, see [release notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes.html) for more information.
