### ISSUE TITLE
Cannot infer shapes or values for node xxx

### ISSUE THREAD

**Issue by FFoCC** [openvinotoolkit/openvino#499]
hello!
When I execute this command, this problem comes up.

python mo_tf.py --input_model /root/ymk_work/work/code/EfficientDet/checkpoints/2020-05-18/coco_16.pb --output_dir /root/ymk_work/work/model/efficientDet_model/ --input_shape [1,512,512,3]

[ ERROR ]  Cannot infer shapes or values for node "activation/IdentityN".
[ ERROR ]  Input 1 of node activation/IdentityN was passed double from fpn_cells/cell_0/fnode0/add/truediv_port_0_ie_placeholder:0 incompatible with expected float.
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function tf_native_tf_node_infer at 0x7f15c5690ef0>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Input 1 of node activation/IdentityN was passed double from fpn_cells/cell_0/fnode0/add/truediv_port_0_ie_placeholder:0 incompatible with expected float.
Stopped shape/value propagation at "activation/IdentityN" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 
Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Input 1 of node activation/IdentityN was passed double from fpn_cells/cell_0/fnode0/add/truediv_port_0_ie_placeholder:0 incompatible with expected float.
Stopped shape/value propagation at "activation/IdentityN" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 

My pb model can inference correctly.
What is the reason for this mistake?
Thank you!

**Comment by ilya-lavrenov** [comment]
@FFoCC the patch is merged, please use the latest master

**Comment by FFoCC** [comment]
> @FFoCC the patch is merged, please use the latest master

Thank you. I'll try
