### ISSUE TITLE
An error occurred while using GPU

### ISSUE THREAD

**Issue by RachelRen05** [openvinotoolkit/openvino#5]
environment: ubuntu 16.04
command:
`ros2 run dynamic_vino_sample dynamic_vino_sample -m /home/intel/code/open_model_zoo/model_downloader/Transportation/object_detection/face/pruned_mobilenet_reduced_ssd_shared_weights/dldt/face-detection-adas-0001.xml -m_hp /home/intel/code/open_model_zoo/model_downloader/Transportation/object_attributes/headpose/vanilla_cnn/dldt/head-pose-estimation-adas-0001.xml -m_em /home/intel/code/open_model_zoo/model_downloader/Retail/object_attributes/emotions_recognition/0003/dldt/emotions-recognition-retail-0003.xml -m_ag /home/intel/code/open_model_zoo/model_downloader/Retail/object_attributes/age_gender/dldt/age-gender-recognition-retail-0013.xml -i StandardCamera -d GPU -d_hp CPU -d_em CPU -d_ag CPU`

error:
`[ ERROR ] failed to create engine: clGetPlatformIDs error -1001`

The same situation occurred when using upstream OpenVINO tar ball, but upstream OpenVINO provided an opencl dependency file to solve this problem, but I did not find a solution here.

BTW, I have downloaded [intel-opencl_18.28.11080_amd64.deb](https://github.com/intel/compute-runtime/releases/tag/18.28.11080) and installed it.

**Comment by meshaun9** [comment]
@RachelRen05 You can try the following steps:


1. wget   http://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB5.0_linux64.zip
2.  unzip   SRB5.0_linux64.zip -d SRB5.0_linux64
3. cd   SRB5.0_linux64
4.sudo   apt-get install xz-utils
5. mkdir   intel-opencl
6. tar -C   intel-opencl -Jxf intel-opencl-r5.0-63503.x86_64.tar.xz
7. tar -C   intel-opencl -Jxf intel-opencl-devel-r5.0-63503.x86_64.tar.xz
8. tar -C   intel-opencl -Jxf intel-opencl-cpu-r5.0-63503.x86_64.tar.xz
9. sudo cp -R   intel-opencl/* /
10. sudo   ldconfig

Let me know if this works for you and if not i'll have some follow up questions to understand your hardware configuration.

**Comment by RachelRen05** [comment]
@meshaun9 
Yes, I have tried this solution and it solved my problem.
Thank you!

**Comment by RachelRen05** [comment]
Hi
I solved my problem using the following method:

1. cd ~/Downloads
2.  wget http://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB5.0_linux64.zip
3.  unzip SRB5.0_linux64.zip -d SRB5.0_linux64
4.  cd SRB5.0_linux64
5.  sudo apt-get install xz-utils
6.  mkdir intel-opencl
7.  tar -C intel-opencl -Jxf intel-opencl-r5.0-63503.x86_64.tar.xz
8.  tar -C intel-opencl -Jxf intel-opencl-devel-r5.0-63503.x86_64.tar.xz
9.  tar -C intel-opencl -Jxf intel-opencl-cpu-r5.0-63503.x86_64.tar.xz
10.  sudo cp -R intel-opencl/* /
11.  sudo ldconfig

Others have encountered the same problem, because  opencl dependency problem lead to the GPU not work. So, please consider updating the opencl dependency in the README.
Thank you.

**Comment by zcq183** [comment]
@meshaun9
   I have tried your solution and it solved my problem.
Thank you!

**Comment by AnastasiaKazantaeva** [comment]
Closed this issue as everything's worked
