### ISSUE TITLE
raspbian build instructions

### ISSUE THREAD

**Issue by natxopedreira** [openvinotoolkit/openvino#500]
Is there any place with updated info on how to cross compile for raspbian buster? 

Current documentation is not working
[https://github.com/openvinotoolkit/openvino/blob/2020/build-instruction.md#cross-compilation-using-docker](https://github.com/openvinotoolkit/openvino/blob/2020/build-instruction.md#cross-compilation-using-docker)

**Comment by natxopedreira** [comment]
CMake Error at inference-engine/CMakeLists.txt:32 (find_package):
  By not providing "Findngraph.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ngraph", but
  CMake did not find one.

  Could not find a package configuration file provided by "ngraph" with any
  of the following names:

    ngraphConfig.cmake
    ngraph-config.cmake

  Add the installation prefix of "ngraph" to CMAKE_PREFIX_PATH or set
  "ngraph_DIR" to a directory containing one of the above files.  If "ngraph"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by natxopedreira** [comment]
Posting here for future reference and to let other people know about

This solve hgraph issue, i think it should be  noted on instructions
`cd inference-engine`
`git submodule update --init --recursive`

but now another problem happens as i wan to build with python enabled

CMake Error at /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find Cython (missing: CYTHON_EXECUTABLE)
Call Stack (most recent call first):

**Comment by natxopedreira** [comment]
Ok with those changes and this cmake im able to build...

But the data that build create is not the same that you found on a openvino package when you download it.

What im doing wrong


`cmake -DCMAKE_BUILD_TYPE=Release \`
`    -DCMAKE_TOOLCHAIN_FILE="../cmake/arm.toolchain.cmake" \`
`    -DTHREADS_PTHREAD_ARG="-pthread" \`
`    -DENABLE_SSE42=OFF \`
`    -DTHREADING=SEQ \`
`    -DENABLE_GNA=OFF \`
`    -DENABLE_PYTHON=ON \`
`    -DPYTHON_EXECUTABLE=/usr/bin/python3.7 \`
`    -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so \`
`    -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 ..`

**Comment by dkurt** [comment]
> This solve hgraph issue, i think it should be noted on instructions
cd inference-engine
git submodule update --init --recursive

What do you mean by that? https://github.com/openvinotoolkit/openvino/blob/2020/build-instruction.md#build-steps-3 shows that `git submodule update --init --recursive` is required

**Comment by natxopedreira** [comment]
I see
I was reading under raspbian crosscompile.... maybe is good to put also in that part, imo is more clear

**Comment by natxopedreira** [comment]
@dkurt sorry to bother you but i compiled with the pull request that you mentioned on the ngraph repo but the problem persist. Do you have any clue?

I finally compiled and install, but the issue still persist

i asked on ngraph and thats the reply
`The problem is from the input to PriorBoxClustered; 2x2760708352 doesn't look like the shape you would expect as an input.`

[https://github.com/NervanaSystems/ngraph/issues/4794](https://github.com/NervanaSystems/ngraph/issues/4794)

**Comment by DataScience-RajKapoor** [comment]
@natxopedreira - am in the same boat as you but a tad bit behind - seems that you have gone through the first set of commands on the Docker.

I am using RPi 4 with Buster - is your config the same ?

am not able to get past this error -

`The following packages have unmet dependencies:
 crossbuild-essential-armhf : Depends: gcc-arm-linux-gnueabihf (>= 5.3) but it is not installable
                              Depends: g++-arm-linux-gnueabihf (>= 5.3) but it is not installable
E: Unable to correct problems, you have held broken package`

when i directly trying to install g++ ,it says that the version is the latest.

**Comment by natxopedreira** [comment]
@DataScience-RajKapoor
 
Im on rpi3b and Buster. Im now able to build and install.... maybe i can help you, please explain what you are trying to do

**Comment by DataScience-RajKapoor** [comment]
@natxopedreira  , I am trying to follow through the build instructions to use Neural Compute Stick 2 (Movidus/ MYRIAD).

[https://github.com/openvinotoolkit/openvino/blob/2020/build-instruction.md#cross-compilation-using-docker
](url)
I couldn't install it directly on RPi 4 for different set of issues with the libraries ... so I was hoping that Docker instructions would be easier to replicate.

The build command fails when it reaches `crossbuild-essential-armhf ` 
Again the code seems to be written for Stretch while I am on Buster - did you do any other changes in the Dockerfile to point to Buster specific files ?
Mine is a copy of the Dockerfile that is part of the documentation on the above site

Maybe I should bring in the files from Debian Buster ...

**Comment by natxopedreira** [comment]
Ah ok, you want to compile openvino from source cross-compiling with a docker image.

Sorry but i don't understand where are you having problem....building docker image?

Why aren't you using the download packages?

I will post my notes in a gist

**Comment by DataScience-RajKapoor** [comment]
yes - while building the image - it fails at the cross-compiling step because of couple of libraries 
between these comments, i pointed the Dockerfile to `debian:buster ` and it no longer fails at that step and moved on to the cmake command where lot is going on/ keeping fingers crossed 

can you elaborate on 'using the download packages' - will look forward to your notes

**Comment by natxopedreira** [comment]
@DataScience-RajKapoor 

Just to be clear openvino download packages run without issues, im just trying to build from source as current version on rpi are not compatible with lastest models, you have to use 2019 models. So i built from source in hope to solve this.... but not, error persist.

Here are my notes, ask if you need 

Today they updated the repo so not sure.... if any problem you can use the fork i made yesterday

One important detail is that you should change the Dockerfile they used because they are downloading and compiling from source a version of cmake, and when you later going to do a make install on rpi, i will fail as the version of cmake that install on apt-get is lower than the version they used.

**Docker file**

FROM debian:buster

USER root

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    crossbuild-essential-armhf \
    cmake \
    pkg-config \
    wget \
    xz-utils \
    cmake
    libgtk2.0-dev:armhf \
    libpython-dev:armhf \
    libpython3-dev:armhf \
    python-numpy \
    python3-numpy \
    git \
    libusb-1.0-0-dev:armhf \
    libgtk-3-dev:armhf \
    libavcodec-dev:armhf \
    libavformat-dev:armhf \
    libswscale-dev:armhf \
    libgstreamer1.0-dev:armhf \
    libgstreamer-plugins-base1.0-dev:armhf \
    libpython3-dev:armhf \
    python3-pip


**Later clone the repo enter and add submodules**
`git clone https://github.com/openvinotoolkit/openvino.git`
`cd openvino `
`git submodule update --init --recursive`

**Build the dock image**
`docker image build -t ie_cross_armhf ie_cross_armhf`

**ENter in dock image**
`sudo  docker run -it -v /yourpathtoopenvino/openvino:/home/pi/openvino  ie_cross_armhf /bin/bash`

**Inside docker install Cython**
`pip3 install Cython

**Inside docker access openvino folder**
`cd /home/pi/openvino`

**create build directory and enter**
`mkdir build`
`cd build`

**run cmake and make**

cmake -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_TOOLCHAIN_FILE="../cmake/arm.toolchain.cmake" \
    -DTHREADS_PTHREAD_ARG="-pthread" \
    -DENABLE_SSE42=OFF \
    -DTHREADING=SEQ \
    -DENABLE_GNA=OFF \
    -DENABLE_PYTHON=ON \
    -DPYTHON_EXECUTABLE=/usr/bin/python3.7 \
    -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so \
    -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 .. && make --jobs=$(nproc --all)

**when finish exit docker and move openvino directory to pi**

**set enviroment paths to point your new install**

`export PYTHONPATH="/openvino/bin/armv7l/Release/lib/python_api/python3.7/:$PYTHONPATH"`
`export PYTHONPATH="/openvino/inference-engine/temp/opencv_4.3.0_debian9arm/python/python3:$PYTHONPATH"`
`export LD_LIBRARY_PATH="/openvino/inference-engine/temp/opencv_4.3.0_debian9arm/opencv/lib/:$LD_LIBRARY_PATH"`
`export LD_LIBRARY_PATH="/openvino/bin/armv7l/Release/lib/:$LD_LIBRARY_PATH"`
`export DYLD_LIBRARY_PATH="/openvino/bin/armv7l/Release/myriad_compile:$DYLD_LIBRARY_PATH"`

**Comment by mortyone** [comment]
Following these instructions 

> @DataScience-RajKapoor
> 
> Just to be clear openvino download packages run without issues, im just trying to build from source as current version on rpi are not compatible with lastest models, you have to use 2019 models. So i built from source in hope to solve this.... but not, error persist.
> 
> Here are my notes, ask if you need
> 
> Today they updated the repo so not sure.... if any problem you can use the fork i made yesterday
> 
> One important detail is that you should change the Dockerfile they used because they are downloading and compiling from source a version of cmake, and when you later going to do a make install on rpi, i will fail as the version of cmake that install on apt-get is lower than the version they used.
> 
> **Docker file**
> 
> FROM debian:buster
> 
> USER root
> 
> RUN dpkg --add-architecture armhf &&
> apt-get update &&
> apt-get install -y --no-install-recommends
> build-essential
> crossbuild-essential-armhf
> cmake
> pkg-config
> wget
> xz-utils
> cmake
> libgtk2.0-dev:armhf
> libpython-dev:armhf
> libpython3-dev:armhf
> python-numpy
> python3-numpy
> git
> libusb-1.0-0-dev:armhf
> libgtk-3-dev:armhf
> libavcodec-dev:armhf
> libavformat-dev:armhf
> libswscale-dev:armhf
> libgstreamer1.0-dev:armhf
> libgstreamer-plugins-base1.0-dev:armhf
> libpython3-dev:armhf
> python3-pip
> 
> **Later clone the repo enter and add submodules**
> `git clone https://github.com/openvinotoolkit/openvino.git`
> `cd openvino `
> `git submodule update --init --recursive`
> 
> **Build the dock image**
> `docker image build -t ie_cross_armhf ie_cross_armhf`
> 
> **ENter in dock image**
> `sudo docker run -it -v /yourpathtoopenvino/openvino:/home/pi/openvino ie_cross_armhf /bin/bash`
> 
> **Inside docker install Cython**
> `pip3 install Cython
> 
> **Inside docker access openvino folder**
> `cd /home/pi/openvino`
> 
> **create build directory and enter**
> `mkdir build`
> `cd build`
> 
> **run cmake and make**
> 
> cmake -DCMAKE_BUILD_TYPE=Release
> -DCMAKE_TOOLCHAIN_FILE="../cmake/arm.toolchain.cmake"
> -DTHREADS_PTHREAD_ARG="-pthread"
> -DENABLE_SSE42=OFF
> -DTHREADING=SEQ
> -DENABLE_GNA=OFF
> -DENABLE_PYTHON=ON
> -DPYTHON_EXECUTABLE=/usr/bin/python3.7
> -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so
> -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 .. && make --jobs=$(nproc --all)
> 
> **when finish exit docker and move openvino directory to pi**
> 
> **set enviroment paths to point your new install**
> 
> `export PYTHONPATH="/openvino/bin/armv7l/Release/lib/python_api/python3.7/:$PYTHONPATH"`
> `export PYTHONPATH="/openvino/inference-engine/temp/opencv_4.3.0_debian9arm/python/python3:$PYTHONPATH"`
> `export LD_LIBRARY_PATH="/openvino/inference-engine/temp/opencv_4.3.0_debian9arm/opencv/lib/:$LD_LIBRARY_PATH"`
> `export LD_LIBRARY_PATH="/openvino/bin/armv7l/Release/lib/:$LD_LIBRARY_PATH"`
> `export DYLD_LIBRARY_PATH="/openvino/bin/armv7l/Release/myriad_compile:$DYLD_LIBRARY_PATH"`

Following this with the latest Buster (May 2020), cmake throws this error:

home/pi/openvino/inference-engine/temp/protoc-3.7.1-linux-x86_64/bin/protoc: 1: /home/pi/openvino/inference-engine/temp/protoc-3.7.1-linux-x86_64/bin/protoc: Syntax error: word unexpected (expecting ")")
CMake Error at ngraph/cmake/external_protobuf.cmake:59 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  ngraph/CMakeLists.txt:476 (include)

The key bit being it is somehow referencing "linux-x86_64"? I'm guessing that would should be 32bit for Buster, not 64bit?

**Comment by avitial** [comment]
This issue may not be relevant as there have been new releases since this was reported. To build in Raspbian OS please follow instructions in our Wiki: [BuildingForRaspbianStretchOS](https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS). The steps for cross-compilation work with Stretch OS and should work with Buster OS although not validated. 

Also make sure to export the environment paths, some of these (OpenCV_DIR and PYTHONPATH) may depend on how you built OpenVINO.

```
PYTHONPATH=/home/pi/openvino/bin/armv7l/Release/lib/python_api/python3.5
ngraph_DIR=/home/pi/openvino/ngraph/cmake
InferenceEngine_DIR=/home/pi/openvino/build/share
OpenCV_DIR=/home/pi/openvino/inference-engine/temp/opencv_4.5.1_debian9arm/opencv/cmake
LD_LIBRARY_PATH=/home/pi/openvino/inference-engine/temp/opencv_4.5.1_debian9arm/opencv/lib:/home/pi/openvino/bin/armv7l/Release/lib
```

Closing this as it may not be relevant, please feel free to re-open if you have any questions on this topic.
