### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by karkadad** [openvinotoolkit/openvino#503]
OpenVINO version: openvino_toolkit_p_2020.2.120
TensorFlow version : 1.15.0

Issue:
================================
I'm trying to infer on a simple 1 layer LSTM using OpenVINO, but currently its failing in the model optimizer stage with the following error:
  File "/opt/openvino2020/openvino_2020.2.120/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 134, in partial_infer
    node.infer(node)
  File "/opt/openvino2020/openvino_2020.2.120/deployment_tools/model_optimizer/mo/ops/strided_slice.py", line 109, in infer
    tf_strided_slice_infer(node)
  File "/opt/openvino2020/openvino_2020.2.120/deployment_tools/model_optimizer/mo/front/common/partial_infer/slice.py", line 78, in tf_strided_slice_infer
    def_end = shape[old_idx] if s > 0 else -shape[old_idx]-1
IndexError: index 1 is out of bounds for axis 0 with size 1

mo.utils.error.Error: Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "lstm/while/strided_slice_3" node.

(Logs are attached).

The LSTM model is a keras implementation with TF backend:
lstm_1 = tf.keras.layers.LSTM(num_units, return_sequences=False)(inputs_)
lstm_1 = tf.keras.layers.Dropout(dropout)(lstm_1)

The input shape is : [1,30,1] in the TF graph, which is what is being passed to OpenVino.

I have even tried converting to ONNX format and then tried converting to Openvino, but then end with a different error:
mo.utils.error.Error: There is no registered "infer" function for node "generic_loop_Loop__34" with op = "Loop". Please implement this function in the extensions. 

My questions are:
1. Are LSTM models supported currently? Do I need special extensions for them?
2. If not, how can I fix this error.

Thanks in advance!
[tf_openvino_1.log](https://github.com/openvinotoolkit/openvino/files/4658712/tf_openvino_1.log)

**Comment by lazarevevgeny** [comment]
@karkadad , could you attach the ONNX model?

**Comment by karkadad** [comment]
[ts_lstm_model.zip](https://github.com/openvinotoolkit/openvino/files/4679568/ts_lstm_model.zip)
Please find attached the ONNX model (added a zip file of the ONNX model since .onnx format is not supported on github).

**Comment by jane-intel** [comment]
@karkadad, Model Optimizer doesn't support ONNX `Loop` operator and there are no nearest plans to support it. 

You can find all supported by MO ONNX operators [here in OpenVINO documentation](https://docs.openvinotoolkit.org/2020.2/_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#onnx_supported_operators)

---
For OV developers:
![image](https://user-images.githubusercontent.com/55839243/82954561-b1da6b80-9fb5-11ea-988a-1249e3023178.png)

**Comment by karkadad** [comment]
Please find attached the TF model. This was the command used:
mo_tf.py --input_model ts_lstm_model_frozen.pb  --input 'input_seq' --input_shape [1,30,1] --output 'output/BiasAdd' --log_level=DEBUG
[TF_ts_lstm_model_frozen.zip](https://github.com/openvinotoolkit/openvino/files/4693497/TF_ts_lstm_model_frozen.zip)

**Comment by karkadad** [comment]
Please let me know if there were any updates and if more info is needed..thanks!

**Comment by sahira-rizvi** [comment]
Closing, feel free to re-open or start a new issues if additional assistance is needed.

Sincerely,
Sahira
