### ISSUE TITLE
How to compile 2019_R1.1？

### ISSUE THREAD

**Issue by Liujingxiu23** [openvinotoolkit/openvino#505]
I want to use openvino as an EP of onnxruntime, and it seems that onnxruntime uses openvino 2019_R1.1(https://github.com/microsoft/onnxruntime/issues/1481). 

I downloaded  source code of 2019_R1.1 from  https://github.com/openvinotoolkit/openvino/releases.
But the file directory seems different from the path which I cloned by git command。

I just “cd inference-engine; mkdir build; cd build; cmake *****; make -j20" . Compile done 100%。 But no*.so is generated. it seems someting wrong.

How can I compile the source code of 2019_R1.1 ?

**Comment by SDxKeeper** [comment]
Hi @Liujingxiu23 ,
Two questions:
1. Why you trying to compile one year old release?  Latest and greatest is 2020.2 
2. .so files could be found in subfolder build/intel64/Release/lib. Have you tried to locate them using find?
`cd build && find . -name *.so`

**Comment by SDxKeeper** [comment]
official build instructions could be found here: https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#openvino

**Comment by Liujingxiu23** [comment]
@SDxKeeper  Thank you for your reply, I compiled it successfully.
