### ISSUE TITLE
Error: comparison of integer expressions of different signedness

### ISSUE THREAD

**Issue by cosmin** [openvinotoolkit/openvino#5050]
I'm unable to build the project with `-Werror=sign-compare` due to a few cases of comparing signed vs unsigned integers. For example

https://github.com/openvinotoolkit/openvino/blob/6477e8ec01a73c4c60ef376f6c83e29f5bba494c/ngraph/core/reference/src/runtime/reference/interpolate.cpp#L223

As of 2021.3 the list is 

* ngraph/core/reference/src/runtime/reference/interpolate.cpp:110:27: error: comparison of integer expressions of different signedness: 'int64_t' {aka 'long int'} and 'std::size_t' {aka 'long unsigned int'} [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/interpolate.cpp:235:48: error: comparison of integer expressions of different signedness: '__gnu_cxx::__alloc_traits<std::allocator<long int>, long int>::value_type' {aka 'long int'} and '__gnu_cxx::__alloc_traits<std::allocator<long unsigned int>, long unsigned int>::value_type' {aka 'long unsigned int'} [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/loop.cpp:40:77: error: comparison of integer expressions of different signedness: 'uint64_t' {aka 'long unsigned int'} and 'const long int' [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/loop.cpp:87:65: error: comparison of integer expressions of different signedness: 'uint64_t' {aka 'long unsigned int'} and 'const long int' [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/loop.cpp:145:47: error: comparison of integer expressions of different signedness: 'int' and 'uint64_t' {aka 'long unsigned int'} [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/loop.cpp:179:57: error: comparison of integer expressions of different signedness: 'std::vector<std::shared_ptr<ngraph::runtime::HostTensor> >::size_type' {aka 'long unsigned int'} and 'int64_t' {aka 'long int'} [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/loop.cpp:197:49: error: comparison of integer expressions of different signedness: 'std::vector<std::shared_ptr<ngraph::runtime::HostTensor> >::size_type' {aka 'long unsigned int'} and 'const int64_t' {aka 'const long int'} [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/non_max_suppression.cpp:194:58: error: comparison of integer expressions of different signedness: 'size_t' {aka 'long unsigned int'} and 'int64_t' {aka 'long int'} [-Werror=sign-compare]

* ngraph/core/reference/src/runtime/reference/tensor_iterator.cpp:37:39: error: comparison of integer expressions of different signedness: 'int64_t' {aka 'long int'} and 'std::vector<std::shared_ptr<ngraph::op::util::SubGraphOp::InputDescription> >::size_type' {aka 'long unsigned int'} [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/tensor_iterator.cpp:86:43: error: comparison of integer expressions of different signedness: 'int' and 'uint64_t' {aka 'long unsigned int'} [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/tensor_iterator.cpp:113:53: error: comparison of integer expressions of different signedness: 'int64_t' {aka 'long int'} and 'uint64_t' {aka 'long unsigned int'} [-Werror=sign-compare]
* ngraph/core/reference/src/runtime/reference/tensor_iterator.cpp:118:53: error: comparison of integer expressions of different signedness: 'std::vector<std::shared_ptr<ngraph::runtime::HostTensor> >::size_type' {aka 'long unsigned int'} and 'int64_t' {aka 'long int'} [-Werror=sign-compare]

**Comment by cosmin** [comment]
As a workaround it's of course possible to disable the warning, or at least just the error for this warning with either `-Wno-sign-compare` or `-Wno-error=sign-compare`, but it's much safer to treat these warnings as error as they usually indicate some questionable behavior that should be resolved in the code.

**Comment by zulkifli-halim** [comment]
Yes, when using -Wno-error=sign-compare would actually suppress the errors (if any). We may have to report to the developer team and check with them for a fix.

**Comment by cosmin** [comment]
Yeah, I can of course suppress the error but we build with these warnings as error for a reason, because it tends to hide problems. So a proper fix would be much appreciated.

**Comment by avitial** [comment]
@cosmin thanks for reporting this, we've shared this issue with the dev team. 

Ref. 52492.

**Comment by ilyachur** [comment]
@cosmin `Wall` compilation flag was added for nGraph component. Please verify and close the issue.
