### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by creater-zq** [openvinotoolkit/openvino#5071]
##### Detailed description

After using PyInstaller to package the EXE file, the following error occurs when executing the EXE file：
1. Traceback (most recent cal1 1ast)
File "ie_api.pyx", 1ine 261, in openvino. inference_engine.ie_api.IECore.read_networkFi1e"ie_api.pyx"， 1ine 285, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError:Ulnknown madel format! Carnot find reader for model format: xml and read the mnde1: xxxx\u2netp.xm1. Please check that reader 1ibrary exists in your PATH

2. PyTorch PTH file to onnx file is opset_version=12, onnx to IR file using precision FP32.I then inferred using XML and BIN for FP32.

3. System informations
 - OpenVINO => 2021.2.185
- PyTorch : 1.8.1+cpu
- Python：3.7.10
- onnx：1.8.1
- Operating System / Platform => Windows 64 Bit
- Problem classification: Model Conversion，Model Inference
- Framework: PyTorch
- Model name: U^2-Net

**Comment by zulkifli-halim** [comment]
Hi.

Please double-check the IR model (.xml & .bin) as they may be corrupted or you may pass .bin file instead of .xml file as a path to model_xml. if that is not the case, try converting the ONNX model using the Model Optimizer (MO) once again. If the issue persists, please share the Model Optimizer command.

**Comment by alalek** [comment]
Does the code+model work with native OpenVINO (without PyInstaller)?

---

> PyInstaller to package the EXE

IMHO, Problem comes from here.
Probably used configuration lost some loadable plugins.

---

> try converting the ONNX model using the Model Optimizer (MO) once again

OpenVINO supports reading native ONNX models without "IR" requirement: https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_ONNX_Support.html

> share the Model Optimizer command

so there is no such command.

**Comment by creater-zq** [comment]
> Hi.
> 
> Please double-check the IR model (.xml & .bin) as they may be corrupted or you may pass .bin file instead of .xml file as a path to model_xml. if that is not the case, try converting the ONNX model using the Model Optimizer (MO) once again. If the issue persists, please share the Model Optimizer command.

thanks, I solved the problem in other ways。
The following parameters have been modified in the XXX. Spec file:
        datas=[('C:\\Program Files (x86)\\Intel\\openvino_2021.2.185\\deployment_tools\\inference_engine\\bin\\intel64\\Release\\', '.')],
        hiddenimports=['PyQt5','openvino.inference_engine.constants'],
