### ISSUE TITLE
Cmake source directory must point to <openvino_root> SOLVED

### ISSUE THREAD

**Issue by everfate** [openvinotoolkit/openvino#5072]
System information
- OpenVINO => 2021.3
- Operating System / Platform => ubuntu 20.04
- cmake 3..16.3

Detailed description
I tried to cmake for cunstom compilation, and followed the step in https://www.jianshu.com/p/9b1fa83f23ad?hmsr=toutiao.io.
when I use
cmake -DCMAKE_BUILD_TYPE=Release \
-DENABLE_SSE42=OFF \
-DTHREADING=SEQ  \
-DENABLE_GNA=OFF \
-DENABLE_VPU=ON \
-DENABLE_MYRIAD=ON \
-DENABLE_MKL_DNN=OFF \
-DENABLE_CLDNN=OFF \
-DENABLE_SAMPLES=OFF \
-DENABLE_PYTHON=ON \
-DPYTHON_EXECUTABLE=/usr/bin/python3.8 \
-DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.8.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.8 \
.. && make -j4

**i get the following logs:**

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
**CMake Error at CMakeLists.txt:8 (message):
  Cmake source directory must point to <openvino_root>**

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.16)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/root/openvino/inference-engine/build/CMakeFiles/CMakeOutput.log".

**i have solved the problem
It means I have to cmake under /openvino/build instead of /openvino/inference-engine/build**

issue submission checklist

CMake Error at CMakeLists.txt:8 (message):
  Cmake source directory must point to <openvino_root>

**Comment by jgespino** [comment]
Hi @everfate 

Glad you were able to fix the issue! For future reference, I recommend following the instructions on the OpenVINO Wiki page: https://github.com/openvinotoolkit/openvino/wiki/BuildingCode

Regards,
Jesus
