### ISSUE TITLE
Variable set but not used, `carry_out` in coordinate_transform.cpp

### ISSUE THREAD

**Issue by cosmin** [openvinotoolkit/openvino#5080]
`carry_out` is set but not used in this function in coordinate_transform.cpp, which is causing an error when built in strict mode 

https://github.com/openvinotoolkit/openvino/blob/8d2f58caad933427771c675f11038ed55fbec3a7/ngraph/core/reference/src/coordinate_transform.cpp#L443

```
ngraph/core/reference/src/coordinate_transform.cpp:440:10: error: variable 'carry_out' set but not used [-Werror=unused-but-set-variable]
```

Removing it would be easy enough to do but it's not clear if perhaps it should be used for something instead.

**Comment by jgespino** [comment]
Hi @cosmin 

Could you make the change and submit a pull request? Once submitted the development team will review your suggestion.
Take a look at the [Contribution Guide](https://github.com/openvinotoolkit/openvino/wiki/Contribute) for additional information.

Regards,
Jesus
