### ISSUE TITLE
Wrong validation in clamp.cpp

### ISSUE THREAD

**Issue by d1rtyman** [openvinotoolkit/openvino#5087]
##### System information (version)
- OpenVINO=> 2021.3
- Operating System / Platform => macOS 11.2.3 x86_64
- Compiler => Apple Clang
- Framework: pytorch 1.8.1
- 
##### Detailed description
according to formula: clamp(x) = min(max(x, min_value), max_value)
then min_value == min_value should be ok

see
https://github.com/openvinotoolkit/openvino/blob/bf1b7ef19cf3dae5357154a254ce3f693cf94379/ngraph/core/src/op/clamp.cpp#L136

and
https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/activation/Clamp_1.md

##### Steps to reproduce
import torch
class MyModel(torch.nn.Module):
    def forward(self, x):
        return torch.clamp(x, 1, 1)
model = MyModel()
torch.onnx.export(model, torch.tensor(1), 'a.onnx')

Convert onnx to IR:
`mo.py --input_model a.onnx`

Load network:
`python ~/intel/openvino_2021/deployment_tools/tools/benchmark_tool/benchmark_app.py -m a.xml`

Log:
`
[Step 1/11] Parsing and validating input arguments
[ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README. 
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
         API version............. 2.1.2021.3.0-2787-60059f2c755-releases/2021/3
[ INFO ] Device info
         CPU
         MKLDNNPlugin............ version 2.1
         Build................... 2021.3.0-2787-60059f2c755-releases/2021/3

[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance,but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ ERROR ] Check 'm_min < m_max' failed at core/src/op/clamp.cpp:114:
While validating node 'v0::Clamp Clamp_2 (0[0]:i32{}) -> ()' with friendly_name 'Clamp_2':
The 'min' parameter needs to be less than 'max' for Clamp
Traceback (most recent call last):
  File "/Users/pom/intel/openvino_2021/python/python3.7/openvino/tools/benchmark/main.py", line 199, in run
    ie_network = benchmark.read_network(args.path_to_model)
  File "/Users/pom/intel/openvino_2021/python/python3.7/openvino/tools/benchmark/benchmark.py", line 66, in read_network
    ie_network = self.ie.read_network(model_filename, weights_filename)
  File "ie_api.pyx", line 293, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 315, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Check 'm_min < m_max' failed at core/src/op/clamp.cpp:114:
While validating node 'v0::Clamp Clamp_2 (0[0]:i32{}) -> ()' with friendly_name 'Clamp_2':
The 'min' parameter needs to be less than 'max' for Clamp
`

**Comment by Iffa-Meah** [comment]
Hi, can you help to fill out the issue template and provide additional information, especially steps to reproduce this.

**Comment by ilyachur** [comment]
@d1rtyman The fix was merged to the master branch.
Please verify that it works for your cases.

**Comment by d1rtyman** [comment]
Thanks. close issue.
