### ISSUE TITLE
how to install openvino in a docker image

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/openvino#5130]
I'm writing a docker file based on ubuntu 20.04, and I want to install openvino dev package in the image according to  https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_apt.html

the first problem is how to download the public key with linux command line from https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021?elq_cid=510969_ts1617784105802&erpm_id=1067095_ts1617784105802&elq_cid=510969_ts1617784124333&erpm_id=1067095_ts1617784124333&elq_cid=510969_ts1617784430518&erpm_id=1067095_ts1617784430518&elq_cid=510969_ts1617785148919&erpm_id=1067095_ts1617785148919 

I tried with wget and curl, but could not download during 'docker build'.  Is there an example dockerfile I can refer to? thanks.

**Comment by brmarkus** [comment]
The Dockerfiles for the pre-built and publicly available Docker containers can be found in this repo:
https://github.com/openvinotoolkit/docker_ci

The Dockerfiles here, in a subfolder:
https://github.com/openvinotoolkit/docker_ci/tree/master/dockerfiles

You can find the use of the pub-key here, e.g.:
https://github.com/openvinotoolkit/docker_ci/blob/master/dockerfiles/ubuntu20/openvino_c_base_2021.dockerfile

**Comment by guoyejun** [comment]
thanks, i read the example dockerfile and write a simple one as below.
```
FROM ubuntu:20.04 AS base

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y git

WORKDIR /workspace

RUN apt-get install -y gnupg
RUN apt-get install -y curl ca-certificates

ARG PUBLIC_KEY="https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021"
ARG APT_REPOSITORY="deb https://apt.repos.intel.com/openvino/2021 all main"

RUN curl --noproxy -o GPG-PUB-KEY-INTEL-OPENVINO-2021 ${PUBLIC_KEY} && \
    apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2021 

```

and there's error to do 'docker build':
```
Step 7/10 : RUN apt-get install -y curl ca-certificates
 ---> Using cache
 ---> 91cf2e05c64d
Step 8/10 : ARG PUBLIC_KEY="https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021"
 ---> Using cache
 ---> 1bd77c33d64e
Step 9/10 : ARG APT_REPOSITORY="deb https://apt.repos.intel.com/openvino/2021 all main"
 ---> Using cache
 ---> 56fea35e2581
Step 10/10 : RUN curl --noproxy -o GPG-PUB-KEY-INTEL-OPENVINO-2021 ${PUBLIC_KEY} &&     apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2021 || true
 ---> Running in de3e22231ad4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   269  100   269    0     0   1084      0 --:--:-- --:--:-- --:--:--  1084
<!doctype html>
<html>
<head>
<meta http-equiv="refresh" content="0;url=http://97.64.58.211/ibreports/ibp/bp.html?bu=http://gpg-pub-key-intel-openvino-2021/&bc=Failed%20to%20retrieve%20requested%20URL.&ip=10.239.159.53&er=ERR_DNS_FAIL"/>
</head>
<body>
</body>
</html>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   939  100   939    0     0    201      0  0:00:04  0:00:04 --:--:--   210
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBF2Ru1cBCADET6CERkWEDRAF6GIEceiajgMFT6BepRjF26rtnyEXdAXT4vU+wLqg0DE5Va1t
4ZAXcIHJ3g1OuGw7Vst2b7WySJl1cFvRSOxZg7Em0QUd51c7n0IYX6FL55Ern2pU3sL2NfJnyrKi
HBSTBGqMFELF5cTaY4E1GQyIUj0BrwUXMpLuxxL0ISyz2CNFnJuENbunbax0L5LrHLFwcsTEvT9q
ZVcP5G+xZBmhPOJ3bR3LHZN/9tj1E6IEzFOY/S/jfqXKmwbR4EzZ7pTtBqNzDm6bviWwQHyh6euw
eoDhTa6TAUUsP5vIL+7iWDQd9X10XyByWEsLaQbWNBCPxAwRTAgnABEBAAG1ACZJbnRlbChSKSBT
b2Z0d2FyZSBEZXZlbG9wbWVudCBQcm9kdWN0c4kBPgQTAQgAKAUCXZG7VwIbAwUJB4YfgAYLCQgH
AwIGFQgCCQoLBBYCAwECHgECF4AACgkQrPqfxX5sXb7L5Qf/cxJs9tDCea0ZWqeSX1lAjuff2Bku
H/yXwvu625DcAneUemho6NDck2LJKhpUM/9teyQWGTIIuz8IlIr3zYeK8VmVitm6cgjD07TYeh5j
71eAd7R1o49IUhIx/cXcuBcYHOw9kWCpl05D85xByZxkF7tlShLwVveyNGeVzU8aBJPhqoPGzIP0
/CJ3c2Qe09UMmqyhUw5ETMqBxR1E+vFCqAHfa3VdtOc8gIfmMK50t/wjE33RdnMI0cHoqmRLFj6C
ppBjBabIY+ro1focySyJ8cLkVEsk0T6u0s2B8nj+ctjasYAeZCmk6shNh9Y06zHkRcBS/cy2bHeB
4nKs3YBvpA==
=aXpT
-----END PGP PUBLIC KEY BLOCK-----
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: can't open 'GPG-PUB-KEY-INTEL-OPENVINO-2021': No such file or directory

```

Looks that the key is not downloaded successfully.

**Comment by brmarkus** [comment]
Looks like you get a DNS error when trying to access and download the key:

"<meta http-equiv="refresh" content="0;url=http://97.64.58.211/ibreports/ibp/bp.html?bu=http://gpg-pub-key-intel-openvino-2021/&bc=Failed%20to%20retrieve%20requested%20URL.&ip=10.239.159.53&er=ERR_DNS_FAIL"/>"

Are you in a corporate network, behind a network proxy (like I am)?
Then you probably need to configure DNS for your Docker daemon:

In "/etc/docker/daemon.json" you could configure DNS for your Docker daemon like e.g.:

{
    "dns": ["XX.YY.ZZ.AA", "AA.BB.CC.DD", "EE.FF.GG.HH"],
    "data-root": "/my/path/"
}
