### ISSUE TITLE
FeatureRequest: Increase VPU blob MINOR version on new release

### ISSUE THREAD

**Issue by szabi-luxonis** [openvinotoolkit/openvino#5156]
Currently there is no easy way to differentiate between VPU (myriad X) blob compiled for openvino 2020.4, 2021.1, 2021.2, 2021.3.
Only [BLOB_VERSION_MAJOR](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/vpu/graph_transformer/include/vpu/graph_transformer.hpp#L186) is bumped in-between major releases : 2020.3 -> 2020.4 (5->6).

It would be great if with every small release the [BLOB_VERSION_MINOR](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/vpu/graph_transformer/include/vpu/graph_transformer.hpp#L187) would be increased, and zeroed out on new major release. This requires a trivial change in both OpenVINO and firmware on myriad side (in Fathom lib). 

Another idea is that `BLOB_VERSION_MAJOR` should match `OPENVINO_VERSION_MAJOR` e.g. 2021, while `BLOB_VERSION_MINOR` `OPENVINO_VERSION_MINOR` e.g. 3. This could be automated in CI using the same version numbering for both.

**Comment by Iffa-Meah** [comment]
We appreciate your input and your insight will be shared to the development team.

**Comment by avitial** [comment]
Thank you for submitting this feature request. Unfortunately, due to product development priorities, engineering is unable to implement this feature. Since we cannot commit to support this feature, we recommend closing this thread/case.
