### ISSUE TITLE
Nonnull argument compared to NULL, compilation error with `-Werror=nonnull-compare`

### ISSUE THREAD

**Issue by cosmin** [openvinotoolkit/openvino#5162]
Another compilation error when trying to compile with strict errors.

```
ngraph/core/include/ngraph/check.hpp:127:9: error: 'nonnull' argument 'this' compared to NULL [-Werror=nonnull-compare]
ngraph/core/include/ngraph/check.hpp:127:9: error: 'nonnull' argument 'this' compared to NULL [-Werror=nonnull-compare]
ngraph/core/include/ngraph/check.hpp:127:9: error: 'nonnull' argument 'this' compared to NULL [-Werror=nonnull-compare]
ngraph/core/include/ngraph/check.hpp:127:9: error: 'nonnull' argument 'this' compared to NULL [-Werror=nonnull-compare]
ngraph/core/include/ngraph/check.hpp:127:9: error: 'nonnull' argument 'this' compared to NULL [-Werror=nonnull-compare]
```

**Comment by zulkifli-halim** [comment]
Thank you for reporting this, we've shared this issue with the dev team.

Ref. 52493

**Comment by ilyachur** [comment]
@cosmin I see that you created a set of issues for nGraph component with warnings which appeared after additional of compiler flags.
Why did you use these flags for nGraph build? Do you have such requirements in your product?
I asked it because unfortunately you will have the same issues if you try to build IE or majority of other OpenVINO components.

**Comment by cosmin** [comment]
Our internal build infrastructure appends `-Wall -Werror` for various reasons and this isn't something I can easily bypass. So in order to enable building this project I had to tease through all the errors and disable them one by one. Here is the final list that I had to disable

```
-Wno-error=sign-compare
-Wno-error=unused-but-set-variable
-Wno-error=array-bounds
-Wno-error=cpp
-Wno-error=reorder
-Wno-error=nonnull-compare
-Wno-error=comment
-Wno-error=parentheses
-Wno-error=class-memaccess
-Wno-error=unused-local-typedefs
```

I filed issues for some of these though because it's worth fixing the underlying issues because they may be masking problems. Some of these were in 3rd party dependencies like `xbyak` so I excluded those, and some seemed rather trivial so I gave up after a few issues.

But in order to make it easier to build the project I would recommend going through and systematically eliminating such issues where possible (outside of 3rd party code).

I can try to submit some pull requests once I get the project cleared for open source contributions.

**Comment by ilyachur** [comment]
@cosmin Do you build only the nGraph? Or do you also build the other OpenVINO components with the flag -Wall?

**Comment by cosmin** [comment]
Not just ngraph, the build flags apply to the entire openvino build, but I did turn off a bunch of modules we don’t need at the moment 

-DENABLE_CLDNN=OFF
 -DENABLE_OPENCV=OFF
 -DENABLE_SPEECH_DEMO=OFF
 -DENABLE_PROFILING_ITT=OFF
 -DENABLE_SAMPLES=OFF
 -DENABLE_MYRIAD=OFF
 -DENABLE_TESTS=OFF
 -DNGRAPH_UNIT_TEST_ENABLE=OFF
  -DNGRAPH_TEST_UTIL_ENABLE=OFF
  -DNGRAPH_ONNX_IMPORT_ENABLE=OFF
  -DNGRAPH_USE_SYSTEM_PROTOBUF=ON

so it’s possible there are additional warnings in the parts of the code I disabled.

**Comment by ilyachur** [comment]
The fix for `nonnull-compare` flag was merged to the master branch.

**Comment by ilyachur** [comment]
@cosmin `-Wall` compilation flag was added for nGraph component. Please verify and close the issue.

**Comment by jgespino** [comment]
@cosmin Closing, please re-open if you need additional assistance.
