### ISSUE TITLE
Obtaining label map for inferencing

### ISSUE THREAD

**Issue by dnth** [openvinotoolkit/openvino#5178]
I trained a Tensorflow model on a custom dataset with the SSD MobileNet architecture.
How do I obtain the label map for inferencing?

I have a `vehicles_label_map.pbtxt` as below

```
item {
    name: "Ambulance",
    id: 1,
    display_name: "Ambulance"
}
item {
    name: "Bus",
    id: 2,
    display_name: "Bus"
}
item {
    name: "Car",
    id: 3,
    display_name: "Car"
}
item {
    name: "Motorcycle",
    id: 4,
    display_name: "Motorcycle"
}
item {
    name: "Truck",
    id: 5,
    display_name: "Truck"
}
```
I tried to construct a label map text file with each class name on a separate line as below. However, the label that is displayed during inferencing does not tally. What could be the potential problem?

```
Ambulance
Bus
Car
Motorcycle
Truck
```

**Comment by Iffa-Meah** [comment]
The labels depend on your model and how you train them.
If you refer to [this](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/object_detection_demo/python), you can use the command --labels LABELS to labels mapping file.

[This](https://www.youtube.com/watch?v=jbqOa8DX7Jg) might give you further insight.

**Comment by dnth** [comment]
Hi @Iffa-Meah I have trained my model with Tensorflow Object Detection API. The input consist of tfrecord files and the `vehicles_label_map.pbtxt`

I understand that to use `--label LABELS` I will need a .txt file with the name of each class on a separate line correct?
In this case how should my `.txt ` file look like?

**Comment by Iffa-Meah** [comment]
Yes, that's correct. You need to create the txt file.
It should be something like the file I attached.
[coco_labels.txt](https://github.com/openvinotoolkit/openvino/files/6301030/coco_labels.txt)

**Comment by dnth** [comment]
> Yes, that's correct. You need to create the txt file.
> It should be something like the file I attached.
> [coco_labels.txt](https://github.com/openvinotoolkit/openvino/files/6301030/coco_labels.txt)

Referring to your sample file, if my `label_map.pbtxt` file looks like this

```
item {
    name: "Ambulance",
    id: 1,
    display_name: "Ambulance"
}
item {
    name: "Bus",
    id: 2,
    display_name: "Bus"
}
item {
    name: "Car",
    id: 3,
    display_name: "Car"
}
item {
    name: "Motorcycle",
    id: 4,
    display_name: "Motorcycle"
}
item {
    name: "Truck",
    id: 5,
    display_name: "Truck"
}
```
The corresponding `.txt` file should look like

```
__background__
Ambulance
Bus
Car
Motorcycle
Truck
```
Am I getting this right?

**Comment by Iffa-Meah** [comment]
Yes, try it out.
That works with my coco dataset.

**Comment by dnth** [comment]
Somehow the label map doesnt line up with the pbtxt in my case. Not sure if anyone else could verify this?

**Comment by Iffa-Meah** [comment]
Try to understand this: [Dataset labelling/Annotation](https://medium.com/analytics-vidhya/image-dataset-labeling-annotation-bec3390eda2d)

**Comment by dnth** [comment]
> > Yes, that's correct. You need to create the txt file.
> > It should be something like the file I attached.
> > [coco_labels.txt](https://github.com/openvinotoolkit/openvino/files/6301030/coco_labels.txt)
> 
> Referring to your sample file, if my `label_map.pbtxt` file looks like this
> 
> ```
> item {
>     name: "Ambulance",
>     id: 1,
>     display_name: "Ambulance"
> }
> item {
>     name: "Bus",
>     id: 2,
>     display_name: "Bus"
> }
> item {
>     name: "Car",
>     id: 3,
>     display_name: "Car"
> }
> item {
>     name: "Motorcycle",
>     id: 4,
>     display_name: "Motorcycle"
> }
> item {
>     name: "Truck",
>     id: 5,
>     display_name: "Truck"
> }
> ```
> 
> The corresponding `.txt` file should look like
> 
> ```
> __background__
> Ambulance
> Bus
> Car
> Motorcycle
> Truck
> ```
> 
> Am I getting this right?

To anyone facing this issue, I could get the labels right following this.
