### ISSUE TITLE
[Bug] Build failing with minimal OpenCV library being present at configuration time

### ISSUE THREAD

**Issue by pwuertz** [openvinotoolkit/openvino#5185]
Within `docs/snippets` the CMakeLists.txt searches for any kind of OpenCV package and if found tries to compile an OpenCV dependent target even if the `ENABLE_OPENCV` project option is explicitly disabled. This target may fail to compile if the OpenCV build that was found doesn't provide the `highgui` module for example.

I opened PR #5154 for adding a check for the `ENABLE_OPENCV` project option in order to prevent those OpenCV dependent targets from being built by accident.

**Comment by Iffa-Meah** [comment]
Thank you for creating the pull request, I had linked it to this thread.
