### ISSUE TITLE
does openvino support variable image size as input?

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/openvino#522]
I have a tensorflow model with input dims [1, None, None, 1],  it can mean that the model accepts all kinds of gray image size. But i have to specify a value for 'None' when convert it into openvino model, otherwise, error message below:
[ ERROR ]  Shape [ 1 -1 -1  1] is not fully defined for output 0 of "x". Use --input_shape with positive integers to override model input shapes.

After the convert, a previous general tensorflow model becomes a specific openvino model, it is not convenient when I need to handle different image size in the same project. Any recommendation for such case? thanks.

**Comment by lazarevevgeny** [comment]
Hi, @guoyejun,
You may want to use the "InferenceEngine::CNNNetwork::reshape" method to change the input shape. Refer to the https://docs.openvinotoolkit.org/2020.2/_docs_IE_DG_ShapeInference.html on how use it. 

Also, you should specify "--keep_shape_ops" command line parameter when convert your tensorflow model.

**Comment by guoyejun** [comment]
thanks, but I want the model itself to accept variable image size. The input layer of my tensorflow model is defined as 'input_ph = tf.placeholder(tf.float32, shape=[1, **None**, **None**, 1], name="x")'.

Looks that reshape is used to change to the shape of model input, it is not what i want.

I tried --keep_shape_ops, still the same issue.
```
$ python mo_tf.py --input_model /work/ml/sr/srcnn.pb --data_type=FP32  --keep_shape_ops
...
[ ERROR ]  Shape [ 1 -1 -1  1] is not fully defined for output 0 of "x". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "x".
```

I have to use a fixed value for the input such as `$ python mo_tf.py --input_model /work/ml/sr/srcnn.pb --data_type=FP32 --input_shape [1,**960**,**1440**,1]`, but it makes the openvino model input size fixed with 1440*960. I need to prepare many many models for different image sizes.  It is not convenient.

**Comment by dkurt** [comment]
@guoyejun, after model conversion with fixed shapes, have you tried to use reshape method as mentioned by @lazarevevgeny?

**Comment by guoyejun** [comment]
no, i don't think it is what i want. thanks.

**Comment by dkurt** [comment]
@guoyejun, what do you mean by that?

OpenVINO does support networks which may work on different input resolution. You just need to manage to convert a model once to `.xml` and `.bin` then you can use `.reshape()` method to change input resolution. Please take a look at one of the examples here: https://github.com/dkurt/openvino_superres (tested with 2020.1 release).

**Comment by guoyejun** [comment]
thanks.  i have a better understanding of reshape now.

so, the procedure looks like:
1. I have a tensorflow model with sizable input: 
tf.placeholder(tf.float32, shape=[1, **None**, **None**, 1], name="x")
(we'll see size [1, -1, -1, 1] in .pb model file)

2. Choose arbitrary values for the input when convert to openvino model, for example,
--input_shape [1,123,456,1] --keep_shape_ops

3. at run time, if the gray image size is 654*321, different size with value in step 2, then I must call reshape before inference.
.reshape(1, 321, 654, 1).

If my understanding is right, two questions, thanks.
a. some models have input with fixed size (can't be reshaped), and some models have variable input size (can be reshaped).
How could application know if the model input is reshape-able? 

b. possible to export the .reshape via C API? 

btw, it is straightforward if we choose -1 for the variable input size. The arbitrary values chosen in step 2 looks meaningless.

**Comment by ilya-lavrenov** [comment]
> b. possible to export the .reshape via C API?

Yes, we can plan such activity.

**Comment by ilya-lavrenov** [comment]
@guoyejun it turned out that reshape for C API is already here https://docs.openvinotoolkit.org/latest/ie_c_api/group__Network.html#gac4f690afd0c2221f7db2ff9be4aa0637

See in the code https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/ie_bridges/c/include/c_api/ie_c_api.h#L773-L780

**Comment by guoyejun** [comment]
thanks, that's great.

and any comment for the other two concerns?

a. some models have input with fixed size (can't be reshaped), and some models have variable input size (can be reshaped).
How could application know if the model input is reshape-able?

btw, it is straightforward if we choose -1 for the variable input size. The arbitrary values chosen in step 2 looks meaningless.

**Comment by dkurt** [comment]
> How could application know if the model input is reshape-able?

Moreover some of the models can be rashapable but will fail because of bugs in origin frameworks or Model Optimizer conversion. So you need to test the model by experiment.

**Comment by guoyejun** [comment]
thanks, so it looks that the reshape is not a good method since we'll have to test the model by experiment.  Looks that everything is fine if '-1' is supported. Shall we support '-1' method?

**Comment by dkurt** [comment]
@guoyejun, let's be more specific. Please share a model to reproduce the problem so we can understand if it's possible to make it work with variable input shapes.

**Comment by guoyejun** [comment]
sure,  please see my model at the beginning of https://github.com/openvinotoolkit/openvino/issues/498, thanks.

**Comment by lazarevevgeny** [comment]
'-1' method will not be supported in the nearest future. As of now it is a architectural limitation.

**Comment by guoyejun** [comment]
got it, thanks.
