### ISSUE TITLE
object has no attribute 'layers' [Bug]

### ISSUE THREAD

**Issue by mhamdan91** [openvinotoolkit/openvino#5225]
##### System information (version)
- OpenVINO => 2021.3.394
- Operating System / Platform => Ubuntu 18.04 64bit
- Problem classification: Inference engine
- Model name: mobilenet-ssd

##### Detailed description

I tried installing openvino in docker using this dockerfile:
https://github.com/openvinotoolkit/docker_ci/blob/master/dockerfiles/ubuntu18/openvino_cgvh_dev_2021.3.dockerfile

When I try to run this code: 

      from openvino.inference_engine import IECore
      import openvino.inference_engine as i_e
      
      print(i_e.__version__)
      ie = IECore()
      net = ie.read_network("mobilenet-ssd_FP32.xml","mobilenet-ssd_FP32.bin", init_from_buffer=False)
      net_layers = net.layers.keys()

I get this error:

      2.1.2021.3.0-2787-60059f2c755-releases/2021/3
      /usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
        import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
      Traceback (most recent call last):
        File "code.py", line 7, in <module>
          layer = net.layers.keys()
      AttributeError: 'openvino.inference_engine.ie_api.IENetwork' object has no attribute 'layers'

**Comment by ilyachur** [comment]
@akuporos Could you help?

**Comment by dkurt** [comment]
Please use nGraph to iterate over network:
```python

import ngraph as ng
from openvino.inference_engine import IECore, StatusCode

ie = IECore()
net = ie.read_network('mobilenet-ssd_FP32.xml')
ngraph_func = ng.function_from_cnn(net)
for op in ngraph_func.get_ordered_ops():
    print(op.get_type_name())
```
