### ISSUE TITLE
[Bug] libinference_engine.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by intelav** [openvinotoolkit/openvino#5232]
##### System information (version)

- OpenVINO=> :grey_question:2021.3
- Operating System / Platform => :grey_question:Ubuntu 20.04.1 LTS
- Compiler => :grey_question:
- Problem classification => :grey_question:

##### Detailed description
Installed 2021.3 on ubuntu 20.04 and on installing pre-requsites as below shows me this warning message .. 
sudo ./install_prerequisites_tf.sh

Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow>=2.2->-r /opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/install_prerequisites/../requirements_tf.txt (line 2)) (3.1.0)
**[ WARNING ] Failed to import Inference Engine Python API in: /opt/intel/openvino_2021.3.394/python/python3.8
[ WARNING ] libinference_engine.so: cannot open shared object file: No such file or directory**
	- Inference Engine found in: 	/opt/intel/openvino_2021.3.394/python/python3.8/openvino
Inference Engine version: 	2.1.2021.3.0-2787-60059f2c755-releases/2021/3
Model Optimizer version: 	    2021.3.0-2787-60059f2c755-releases/2021/3
[WARNING] All Model Optimizer dependencies are installed globally.
****

##### Steps to reproduce
source /opt/intel/openvino_2021/bin/setupvars.sh
sudo ./install_prerequisites_tf.sh

**Though I find this library as below 
./openvino_2021.3.394/deployment_tools/inference_engine/lib/intel64/libinference_engine.so**

#

**Comment by jgespino** [comment]
Hi @intelav 

Thank you for reporting, I am also seeing the warnings on Ubuntu 18.04 with OpenVINO 2021.3 release.
Let me open a ticket with the development team so it can be addressed.

Regards,
Jesus

**Comment by jgespino** [comment]
Fix has been merged and will be included in the next release.

**Comment by jinwater88** [comment]
Every time I run ./whisper_speech_recognition ../../whisper-base ../../data/vad_example.wav, I need to activate source /opt/intel/openvino_genai_2025/setupvars.sh. If I don't activate it, ./whisper_speech_recognition: error while loading shared libraries: libtbb.so.12: cannot open shared object file: No such file or directory will appear. I want to run it without /opt/intel/openvino_genai_2025/setupvars.sh. What should I do? How can I modify cmake?
