### ISSUE TITLE
[Bug][2021.3][MO] InferenceEngine Python Libs warning

### ISSUE THREAD

**Issue by cosmos1982** [openvinotoolkit/openvino#5267]
##### System information (version)
- OpenVINO => 2021.3
- Operating System / Platform => Windows 10 64 Bit
- Problem classification: Model Conversion
- Python 3.8.0

##### Detailed description
After openvino installation with python 3.8.0, run: 
`mo.py --input_model test.onnx`
will get these warnings:
```
[ WARNING ] Failed to import Inference Engine Python API in: PYTHONPATH
[ WARNING ] [WinError 2] 系统找不到指定的文件。: 'C:\\Program Files (x86)\\Intel\\openvino_2021\\python\\python3.8\\openvino\\libs'
[ WARNING ] Failed to import Inference Engine Python API in: C:\Program Files (x86)\Intel\openvino_2021.3.394\python\python3.8
[ WARNING ] [WinError 2] 系统找不到指定的文件。: 'C:\\Program Files (x86)\\Intel\\openvino_2021\\python\\python3.8\\openvino\\libs'
[ WARNING ] Failed to import Inference Engine Python API in: C:\Program Files (x86)\Intel\openvino_2021.3.394\python\python3.8
[ WARNING ] [WinError 2] 系统找不到指定的文件。: 'C:\\Program Files (x86)\\Intel\\openvino_2021\\python\\python3.8\\openvino\\libs'
[ WARNING ] Could not find the Inference Engine Python API. At this moment, the Inference Engine dependency is not required, but will be required in future releases.
[ WARNING ] Consider building the Inference Engine Python API from sources or try to install OpenVINO (TM) Toolkit using "install_prerequisites.sh"
```

But with python 3.7.4,  mo works fine without those warnings.

I also tested `pip install openvino-dev` which has the same issue with package installation.

What's more, the warning does not appear in 2021.2.

**Comment by zulkifli-halim** [comment]
Hello @cosmos1982.  Have you sourced your environment variables? 
Please share your model with us, so we can investigate this further.

**Comment by zulkifli-halim** [comment]
Hi @cosmos1982. We do see the same warning. We will report this issue to dev team.

**Comment by cosmos1982** [comment]
@zulkifli-halim , got it.  Thanks for quick reply.

**Comment by jgespino** [comment]
Hi @cosmos1982 This should be fixed in the next software release. Thanks for reporting!

Ref. 56844
