### ISSUE TITLE
[Bug]Failed to find reference implementation for `Add_1079` Layer with `MVN` Type on constant propagation

### ISSUE THREAD

**Issue by uglymie** [openvinotoolkit/openvino#5320]
##### System information (version)

I trained a new model through pytorch, and then converted it into openvino. Bin. XML file, when creating executable objects：

Code execution to：
auto executable_network = ie.LoadNetwork(network, "CPU");    

The following error occurred：

Failed to find reference implementation for `Add_1079` Layer with `MVN` Type on constant propagation

What is the specific reason for this? Is it the wrong model conversion I trained? Or can openvino not parse the model?

**Comment by Iffa-Meah** [comment]
If possible, could you share your model so that we could try it out?
There are specific topologies that are supported in different types of models (Tensorflow,Onnx,etc).

You might want to cross-check yours with the one listed [here](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html).

Those are the ones that are validated to works with OpenVINO.

**Comment by uglymie** [comment]
> 如果可能，您可以分享您的模型以便我们试用吗？
> 另外，如果您还可以提供转换命令及其一些代码片段，那就太好了。
> 
> 在不同类型的模型（Tensorflow，Onnx等）中支持特定的拓扑。
> 
> 您可能要与[此处](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html)列出的内容进行交叉核对。
> 
> 这些都是经过验证可与OpenVINO一起使用的。

**Comment by uglymie** [comment]
> If possible, could you share your model so that we could try it out?
> Plus, it would be great if you could also provide your conversion commands and some of its snippets.
> 
> There are specific topologies that are supported in different types of models (Tensorflow,Onnx,etc).
> 
> You might want to cross-check yours with the one listed [here](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html).
> 
> Those are the ones that are validated to works with OpenVINO.

This is a network built with transformer,The network structure is as follows:

![选区_001](https://user-images.githubusercontent.com/47886076/115643792-0a45f480-a350-11eb-8b9c-491c3357def3.png)
![选区_002](https://user-images.githubusercontent.com/47886076/115643809-12059900-a350-11eb-9374-bd94b03d95e1.png)

Here's a snippet of my conversion code:
pkl  to onnx:
`test_arr = torch.randn(1, 3, 360, 640)
dummy_input = torch.randn(1, 3, 360, 640)
lstr_model = model(kp)
lstr_model.load_state_dict(torch.load( 'LSTR_30w.pkl', map_location=torch.device('cuda')), False)
torch.onnx.export(lstr_model, (test_arr, dummy_input),
                      "LSTR_30w.onnx", opset_version=12, verbose=True)
`
Then I used “mo_onnx.py” to transform
`python /opt/intel/openvino/deployment_tools/model_optimizer/mo_onnx.py --input_model  .onnx  --output_dir `

**Comment by uglymie** [comment]
> If possible, could you share your model so that we could try it out?
> Plus, it would be great if you could also provide your conversion commands and some of its snippets.
> 
> There are specific topologies that are supported in different types of models (Tensorflow,Onnx,etc).
> 
> You might want to cross-check yours with the one listed [here](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html).
> 
> Those are the ones that are validated to works with OpenVINO.

> This is a network built with transformer,The network structure is as follows:

![选区_002](https://user-images.githubusercontent.com/47886076/115645254-a113b080-a352-11eb-880f-51877d3c2d81.png)
![选区_001](https://user-images.githubusercontent.com/47886076/115645267-a40ea100-a352-11eb-9e24-783aa2c1441b.png)

> Here's a snippet of my conversion code:

pkl to onnx:
```
test_arr = torch.randn(1, 3, 360, 640) 
dummy_input = torch.randn(1, 3, 360, 640)
 lstr_model = model(kp) 
lstr_model.load_state_dict(torch.load( 'LSTR_30w.pkl', map_location=torch.device('cuda')), False) 
torch.onnx.export(lstr_model, (test_arr, dummy_input), "LSTR_30w.onnx", opset_version=12, verbose=True)
```

> Then I used “mo_onnx.py” to transform

`python /opt/intel/openvino/deployment_tools/model_optimizer/mo_onnx.py --input_model .onnx --output_dir`

**Comment by Iffa-Meah** [comment]
There are possibilities that your model contains unsupported components since you couldn't infer your IR with CPU.
I recommend that you take [this example](https://github.com/openvinotoolkit/training_extensions/tree/9e3c4bb16935e91049be409f54a920d9bf3db918/misc/pytorch_toolkit/question_answering) as a reference or as a template and work on your custom application based on this.

**Comment by uglymie** [comment]
Thank you very much for your reply, I will try.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by ilyachur** [comment]
This ticket should be fixed by PR https://github.com/openvinotoolkit/openvino/pull/5460

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
