### ISSUE TITLE
Modifying and Building OpenVino Demos

### ISSUE THREAD

**Issue by manetelpian** [openvinotoolkit/openvino#5331]
##### System information (version)

- OpenVINO=> 2021.3
- Operating System / Platform => Ubuntu
- Compiler => gcc
- Problem classification => modifying code

##### Detailed description
Hello, I am wondering how I would be able to modify the face-detection-demo such that a screenshot file would be saved each time a person is detected. Which files would I need to modify in order to successfully build the demo again, so that the changes appear when running my demo. I have had trouble in the past with modifying Demos and not being able to build them again after making changes or adding new files to the directories.

**Comment by Iffa-Meah** [comment]
You'll need to create a code for a screenshot file to be saved each time a person is detected according to the programming language that you are using (eg Python,CPP).

It is best to try that code in the main program, 
eg for Python: face_detection_sample.py,
for cpp: main.cpp (you'll need to re-build/re-compile the code/sample application)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
