### ISSUE TITLE
How to use model optimizer after installing openvino-dev through pip?

### ISSUE THREAD

**Issue by binqi-sun** [openvinotoolkit/openvino#5380]
Hi, I have just successfully installed the openvino-dev 2021.3 version through pip. It is said that the dev version includes both model optimizer and inference engine. But when I try to convert my tensorflow model to IR, I cannot find where is the model optimizer installed. Could you please tell me how to use the model optimizer to convert my model if I install my openvino-dev using pip?

**Comment by zulkifli-halim** [comment]
Hi @binqi-sun. First, you need to source your environment, you can follow this [guide](https://pypi.org/project/openvino-dev/) to install the developer package. 

If you are using Windows 10, here is the path to Model Optimizer:
_C:\Windows\System32\openvino_env\Lib\site-packages_

If you are using Ubuntu, the path to Model Optimizer:
run _pip show openvino-dev_  to locate the installation path.

**Comment by binqi-sun** [comment]
Thank you @zulkifli-halim. Actually, I am using a conda environment on Windows 10, and I can find a folder called _openvino_ in _~\.conda\envs\oak\Lib\site-packages_. But inside the folder _openvino_, there are only three sub folders:
_inference_engine_, _libs_, and _offline_transformations_.
Could you please point me out where I can find the path to the model optimizer in this case? Moreover, if I want to convert a tensorflow model into openvino IR, can I just download a _mo_tf.py_ file from this github repo and run the _mo_tf.py_ file under my conda environment with openvino-dev package installed?

**Comment by zulkifli-halim** [comment]
Hi @binqi-sun. You can experiment with it by yourself, but there is no guarantee it will succeed. My suggestion for you is to follow this [installation guide](https://pypi.org/project/openvino-dev/) for openvino-dev package. The model optimizer can be found in this directory _C:\Windows\System32\openvino_env\Lib\site-packages_.

**Comment by binqi-sun** [comment]
Thank you!
