### ISSUE TITLE
[Bug] Master build fails

### ISSUE THREAD

**Issue by kenkoyanagi** [openvinotoolkit/openvino#5434]
##### System information (version)

- OpenVINO=> Master
- Operating System / Platform => W10
- Compiler => MSVC2019
- Problem classification => Build errors

##### Detailed description
After pulling the latest commits from master (4/24, 4/27), I'm not unable to build the project due to ie_executable_network.

![image](https://user-images.githubusercontent.com/49453354/116297063-c25c0e80-a74f-11eb-9874-66213f2a34a3.png)

Line71 from ie_executable_network.cpp
```
ExecutableNetwork::operator IExecutableNetwork::Ptr() {
    return std::make_shared<ExecutableNetworkBase>(_impl);
}
```

##### Steps to reproduce

* Pull master
* Clone, follow the steps in the wiki documentation
* Build for x64 Windows using VS2019
* Debug or Release
* Compile the project

**Comment by Iffa-Meah** [comment]
Hi,
Are you using an older built application code with the latest release since the issue seems to be related to a deprecated API?

If possible, can you share your sample code and the steps to reproduce this?

You might want to take a look at this API deprecated documentation: https://docs.openvinotoolkit.org/latest/deprecated.html

**Comment by kenkoyanagi** [comment]
Hi @Iffa-Meah I am not using older app code. I'm using the sln that's produced with CMake and trying to compile the project in Visual Studio. This is before making any code changes.

**Comment by ilyachur** [comment]
@ilya-lavrenov Could you have a look?

**Comment by ilya-lavrenov** [comment]
@kenkoyanagi could you please check whether the link PR fixes the issue?

Looks like we have different minor versions of MSVC 2019 and for us it compiles well, while your minor version does the things different. 

Thanks.
