### ISSUE TITLE
openvino demo script run error

### ISSUE THREAD

**Issue by niteshgoyal19** [openvinotoolkit/openvino#545]
![Capture](https://user-images.githubusercontent.com/25811863/82805610-eceb7a80-9ea1-11ea-9358-81006356fc94.PNG)

Dll linking Error coming while running openvino demo_squeezenet_download_convert_run.bat file in windows.
How Can i link all those dll to run demo examples of openvino

**Comment by ilya-lavrenov** [comment]
@niteshgoyal19 have you run `setupvars.bat` before running demo script?

**Comment by niteshgoyal19** [comment]
yes i run it , and all environment variable set successfully

**Comment by ilya-lavrenov** [comment]
are you able to build and run any other OpenVINO sample? Do you see the same issue?

**Comment by niteshgoyal19** [comment]
ye i run other examples also same issue came.
actually it unable to find sone infrence and opencv dll in the build
directory.
Is we have to set any other path or should i have to paste those dll in
directory?

**Comment by ilya-lavrenov** [comment]
@niteshgoyal19 you have to call `setupvars.bat` in the terminal and after you can run the application. Seems `setupvars.bat` does not affect your environment or you use it incorrectly.

**Comment by leavim** [comment]
@niteshgoyal19 when installed OpenVINO, did you customize any items from installation? Did you complete all system pre-requisites given in [guide (v2020.2)](https://docs.openvinotoolkit.org/2020.2/_docs_install_guides_installing_openvino_windows.html)? Please share which version of OpenVINO/Windows OS and plugin (Intel CPU?) used.

After calling the `setupvars.bat` in CMD window, run command `set` and check these variables and if their location/content exists in your machine:
`OpenCV_DIR=C:\Program Files (x86)\IntelSWTools\openvino\opencv\cmake
InferenceEngine_DIR=C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\inference_engine\share`

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one.
