### ISSUE TITLE
[Bug] InferRequestTests may not throw exception

### ISSUE THREAD

**Issue by mashoujiang** [openvinotoolkit/openvino#5461]
[canProcessDeallocatedOutputBlobAfterGetBlobForAsync](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/plugin/shared/include/behavior/infer_request.hpp#L328)
should we always use`{ req.StartAsync(); req.Wait(); }`  instead of single `req.StartAsync();` ?  because req.StartAsync()  may not throw exception before process exit.
Use hell_classification sample could reproduce the above issue, too. 
1. use req.StartAsync() will throw REQUEST_BUSY;
2. use req.StartAsync() and req.Wait() could throw `Blob buffer is nullptr`, which is actually what we want.

**Comment by ilya-lavrenov** [comment]
CC @apankratovantonp

**Comment by apankratovantonp** [comment]
@mashoujiang You are absolutely right!
@ilya-lavrenov we should deprecate the behavior when it is allowed to leave `StartAsync` call without blocking `Wait` as it is exception unsafe. 
And add this Notification into documentations and rewrite tests and may be samples for exception safety purpose.

**Comment by jgespino** [comment]
@apankratovantonp @ilya-lavrenov Any updates on this?

**Comment by mashoujiang** [comment]
Hi @jgespino , this test bug is directly fixed in one PR which is already merged. I reported this bug because I thought maybe some other place has this issue too, I didn't check. I could close this issue if you think OK. Thanks!

**Comment by mashoujiang** [comment]
close this issue since InferRequestTests  already fixed this.
