### ISSUE TITLE
[Bug] Reproducible compilation error while building on raspberry pi

### ISSUE THREAD

**Issue by marmalodak** [openvinotoolkit/openvino#5485]
$ git show
    commit bb022e2d26088c69a39baeac467a18e3e7cdbe51 (HEAD -> master, origin/master, origin/HEAD)
    Author: Vitaly Tuzov <terfendail@mediana.jetos.com>
    Date:   Fri Apr 30 19:17:48 2021 +0300

    $ uname -a
    Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux

    $ cat /etc/os-release 
    PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="10"
    VERSION="10 (buster)"
    VERSION_CODENAME=buster
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Trying to follow along the steps to build openvino. I wrote this script:

    #!/bin/bash

    set -e
    set -u
    set -x

    exec > >(tee "go.out") 2>&1

    cd openvino
    pwd

    git pull --rebase
    git submodule update --init --recursive

    mkdir -p build
    cd build
    pwd

    cmake -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_SSE42=OFF \
          -DTHREADING=SEQ \
          -DENABLE_GNA=OFF \
          -DNGRAPH_ONNX_IMPORT_ENABLE=ON \
          -DNGRAPH_DEBUG_ENABLE=ON \
          -DENABLE_PYTHON=ON \
          -DPYTHON_EXECUTABLE=/usr/bin/python3.7 \
          -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.7m.so \
          -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 ..

    echo
    echo cmake finished here
    echo

    make --jobs=$(nproc --all)

It seems to proceed until this:

    In file included from /usr/include/c++/8/map:61,
                     from /home/pi/openvino/openvino/ngraph/core/include/ngraph/node.hpp:11,
                     from /home/pi/openvino/openvino/ngraph/core/include/ngraph/op/op.hpp:9,
                     from /home/pi/openvino/openvino/ngraph/core/include/ngraph/op/util/unary_elementwise_arithmetic.hpp:7,
                     from /home/pi/openvino/openvino/ngraph/core/include/ngraph/op/abs.hpp:9,
                     from /home/pi/openvino/openvino/ngraph/core/include/ngraph/ops.hpp:9,
                     from /home/pi/openvino/openvino/ngraph/core/src/validation_util.cpp:6:
    /usr/include/c++/8/bits/stl_map.h: In member function ‘void ngraph::Evaluator<V>::ExecuteInst::handle(ngraph::Evaluator<V>&, ngraph::Evaluator<V>::InstStack&, ngraph::Node*) [with V = {anonymous}::MaxValue]’:
    /usr/include/c++/8/bits/stl_map.h:518:8: note: parameter passing for argument of type ‘std::_Rb_tree<ngraph::RawNodeOutput, std::pair<const ngraph::RawNodeOutput, {anonymous}::MaxValue>, std::_Select1st<std::pair<const ngraph::RawNodeOutput, {anonymous}::MaxValue> >, std::less<ngraph::RawNodeOutput>, std::allocator<std::pair<const ngraph::RawNodeOutput, {anonymous}::MaxValue> > >::const_iterator’ {aka ‘std::_Rb_tree_const_iterator<std::pair<const ngraph::RawNodeOutput, {anonymous}::MaxValue> >’} changed in GCC 7.1
        __i = _M_t._M_emplace_hint_unique(__i, std::piecewise_construct,
    [ 66%] Linking CXX shared library ../../../bin/armv7l/Release/lib/libngraph.so
    [ 66%] Built target ngraph
    make: *** [Makefile:163: all] Error 2

What can I do to build openvino on Raspberry Pi?

**Comment by marmalodak** [comment]
Attaching complete log.

[go.txt](https://github.com/openvinotoolkit/openvino/files/6412657/go.txt)

**Comment by Iffa-Meah** [comment]
Hi,
The ngraph issue is a known issue since it had occurred previously.
You may refer to the steps in this article: [Building Open Source OpenVINO™ toolkit for Raspbian* OS and Intel® Neural Compute Stick 2](https://www.intel.com/content/www/us/en/support/articles/000057005/boards-and-kits.html)

**Comment by marmalodak** [comment]
From my reading of this log file, ngraph built successfully. If that's not accurate, can you please help me understand?

What is supposed to happen after ngraph?

**Comment by marmalodak** [comment]
I change my build script slightly:

    #!/bin/bash

    set -e
    set -u
    set -x


    exec > >(tee "go.txt") 2>&1

    cd openvino

    git pull --rebase
    git submodule update --init --recursive

    mkdir -p build
    cd build

    cmake -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_SSE42=OFF \
          -DTHREADING=SEQ \
          -DENABLE_GNA=OFF \
          -DNGRAPH_ONNX_IMPORT_ENABLE=ON \
          -DNGRAPH_DEBUG_ENABLE=ON \
          -DENABLE_PYTHON=ON \
          -DPYTHON_EXECUTABLE=/usr/bin/python3.7 \
          -DPYTHON_LIBRARY=/usr/lib/python3.7/config-3.7m-arm-linux-gnueabihf/libpython3.7m.so \
          -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m ..

    echo
    echo cmake finished here
    echo

    make --jobs=$(nproc --all)

It still stops at ngraph:

    [ 66%] Linking CXX shared library ../../../bin/armv7l/Release/lib/libngraph.so
    [ 66%] Built target ngraph
    make: *** [Makefile:163: all] Error 2

Do I understand correctly that there is an error on line 163 of build/CMakeFiles/Makefile2? That doesn't seem right:

    162 
    163 #=============================================================================
    164 # Target rules for target CMakeFiles/NightlyStart.dir
    165 



Additionally, I see this error message about protobuf:

    [ 61%] Building CXX object _deps/ext_protobuf-build/CMakeFiles/protoc.dir/__/src/google/protobuf/compiler/main.cc.o
    [ 61%] Building CXX object ngraph/core/CMakeFiles/ngraph.dir/src/op/multiply.cpp.o
    [ 61%] Building CXX object ngraph/core/CMakeFiles/ngraph.dir/src/op/mvn.cpp.o
    [ 61%] Building CXX object ngraph/core/CMakeFiles/ngraph.dir/src/op/negative.cpp.o
    [ 61%] Linking CXX executable ../../../bin/armv7l/Release/protoc
    /usr/bin/ld: ../../../bin/armv7l/Release/lib/libprotobuf.so.3.7.1.0: undefined reference to `__atomic_fetch_add_8'
    collect2: error: ld returned 1 exit status
    make[2]: *** [_deps/ext_protobuf-build/CMakeFiles/protoc.dir/build.make:86: ../bin/armv7l/Release/protoc-3.7.1.0] Error 1
    make[1]: *** [CMakeFiles/Makefile2:1784: _deps/ext_protobuf-build/CMakeFiles/protoc.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....

**Comment by Iffa-Meah** [comment]
You should use these commands to compile:

cd ~/openvino

mkdir build && cd build

cmake -DCMAKE_BUILD_TYPE=Release \

-DCMAKE_INSTALL_PREFIX=/home/pi/openvino_dist \

-DENABLE_MKL_DNN=OFF \

-DENABLE_CLDNN=OFF \

-DENABLE_GNA=OFF \

-DENABLE_SSE42=OFF \

-DTHREADING=SEQ \

-DENABLE_OPENCV=OFF \

-DNGRAPH_PYTHON_BUILD_ENABLE=ON \

-DNGRAPH_ONNX_IMPORT_ENABLE=ON \

-DENABLE_PYTHON=ON \

-DPYTHON_EXECUTABLE=$(which python3.7) \

-DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so \

-DPYTHON_INCLUDE_DIR=/usr/include/python3.7 \

-DCMAKE_CXX_FLAGS=-latomic ..

**make -j4**

sudo make install


You may refer to the link I gave previously. That one is **specific for Raspberry Pi** with Open Source OpenVINO.
[Building Open Source OpenVINO™ toolkit for Raspbian* OS and Intel® Neural Compute Stick 2](https://www.intel.com/content/www/us/en/support/articles/000057005/boards-and-kits.html)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
