### ISSUE TITLE
[Bug] Instead of hard-coding the path to python, consider using python3-config

### ISSUE THREAD

**Issue by marmalodak** [openvinotoolkit/openvino#5492]
The build instructions on the wiki set the path to the python binaries and libraries. The tool for getting this formally is called python3-config. [This is the man page for it](https://manpages.debian.org/testing/python3-dev/python3-config.1.en.html)

Additionally, the instructions might need updating to reflect, for example, there are multiple paths to the python includes:

    $ python3-config --includes
    -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9

**Comment by jgespino** [comment]
Hi @marmalodak 

Thank you for your input, I have passed this information to the development team for consideration.

Regards,
Jesus

Ref. 54959

**Comment by slyubimt** [comment]
@marmalodak, 
While this tool can be handy to find out python compile & link information for make/gcc, for OpenVINO Python API build we use cmake options to specify locations :

https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux

```
-DPYTHON_EXECUTABLE=`which python3.7` \
-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.7m.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3 
```
You can also get these values from python (for Linux):

1. `which python3` 
2. `` `which python3` -c "from distutils import sysconfig; print(sysconfig.get_python_inc())" ``
3. `` `which python3` -c "import distutils.sysconfig as sysconfig;  print(sysconfig.get_config_var('LDLIBRARY'))" ``

 Please re-open if additional assistance is still needed.
