### ISSUE TITLE
Plugins libs

### ISSUE THREAD

**Issue by dbrazey** [openvinotoolkit/openvino#56]
Hello everyone, 

I have downloaded and compiled this repo. 
Could you please confirm me that plugins (libMKLDNNPlugin, libclDNNPlugin, ...) are not contained in this repo and that I need to download the toolkit on intel website to get them ? 

Thanks for your help :)

**Comment by elvin-nnov** [comment]
Sources of plugins are here: https://github.com/opencv/dldt/tree/2018/inference-engine/src

**Comment by ilyachur** [comment]
Hi @dbrazey,

At the current moment you can find plugin sources here: https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/src

I will close the ticket. Feel free to reopen it, if you have any questions.
