### ISSUE TITLE
[Bug] Wrong Detection Results for Openvino converted model from Tensorflow 

### ISSUE THREAD

**Issue by naga-master** [openvinotoolkit/openvino#5674]
##### System information (version)

- OpenVINO => 2021.2.185
- Operating System / Platform => Ubuntu 18.04
- Problem classification: Wrong Results
- Framework: TensorFlow v1.15(if applicable)
- Model name: ssdlite_mobilenet_v2_coco (if applicable)

##### Detailed description

I Trained a model in Tensorflow v1.15 with Nvidia GPU got results and inferenced using tensorflow . Then I converted the model using below command.
```
python3 mo_tf.py --input_model /home/alailabs/Downloads/opnvino_models_test/ssdlite_mobilenet/turf_area/frozen_inference_graph.pb --tensorflow_use_custom_operations_config=/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/extensions/front/tf/ssd_support_api_v1.15.json  --tensorflow_object_detection_api_pipeline_config=/home/alailabs/Downloads/opnvino_models_test/ssdlite_mobilenet/turf_area/pipeline.config  --output_dir=/home/alailabs/Downloads/opnvino_models_test/ssdlite_mobilenet/turf_area/openvino_flat/   --reverse_input_channels --input_shape [1,300,300,3]
```
I Used the same Label_map for both training and inferencing .

When I inference the same images(which is used in tensorflow inferencing)  , output is not good , mostly wrong detection by the model. 

How to solve the problem

**Comment by zulkifli-halim** [comment]
Hello @naga-master.  Try to add these two lines and see if it make any changes:

`--input=image_tensor 
--output=detection_scores,detection_boxes,num_detections `

Have you tried to run the inference using the latest OpenVINO 2021.3?

**Comment by naga-master** [comment]
> Hello @naga-master. Try to add this line to your command and see if there is any changes:
> 
> `--input=image_tensor --output=detection_scores,detection_boxes,num_detections `
> 
> Have you tried to run the inference using the latest OpenVINO 2021.3?

No . What the output=detection_scores,detection_boxes,num_detections will do?

**Comment by zulkifli-halim** [comment]
The arguments are suggested in the model_optimizer_args of the [ssdlite_mobilenet_v2 model.yml](https://github.com/openvinotoolkit/open_model_zoo/blob/2021.2/models/public/ssdlite_mobilenet_v2/model.yml) 

Please provide us your native model, converted model, and the pipeline.config for us to reproduce the issue.

**Comment by naga-master** [comment]
> The arguments are suggested in the model_optimizer_args of the [ssdlite_mobilenet_v2 model.yml](https://github.com/openvinotoolkit/open_model_zoo/blob/2021.2/models/public/ssdlite_mobilenet_v2/model.yml)
> 
> Please provide us your native model, converted model, and the pipeline.config for us to reproduce the issue.

What is the detection_scores, detection_box, num_detections? How can we define that.? Is this a threshold value ..like detection_score 0.8 like that?

**Comment by zulkifli-halim** [comment]
closing the issue, feel free to open a new ticket if you need assistance.
