### ISSUE TITLE
[Bug]License in files mvnc_data.c and XLinkStringUtils.c

### ISSUE THREAD

**Issue by 2005songliwei** [openvinotoolkit/openvino#5685]
- OpenVINO => 2021.3
- Operating System / Platform => yocto linux 64 Bit

Hi Maintainer,
Recently I found the license in files mvnc_data.c and XLinkStringUtils.c are  Intel private license, whereas
the top statement of this openvino is  Apache 2.0 license, because the license in that two files which
need Intel's written permission to use or disclose, it's a bit conflict with the top license statement, I check that we use to clear this kind of license in commit a5aaa077211e ("[IE CLDNN] OpenCL headers update (#4345)"), and for these two files, the original license is Apache, then it changed in
95a57795dcb0 ("Publishing 2020.2 content"), my question is: is it possible to change that two files license header to original Apache license? If so I'd like to submit the patch to change it. Thank you very much.

Liwei.

**Comment by ttroilov** [comment]
@2005songliwei , could you please point exact files where you see Intel private license?

**Comment by 2005songliwei** [comment]
Hi,

These two files:
git/inference-engine/thirdparty/movidius/XLink/shared/src/XLinkStringUtils.c 
git/inference-engine/thirdparty/movidius/mvnc/src/mvnc_data.c

Thanks,
Liwei.

**Comment by 2005songliwei** [comment]
Hi Maintainer,

I just found there are also these two files contain Intel's private license which may conflict with the top LICENSE statement
./docs/IE_DG/Legal_Information.md
./docs/Legal_Information.md

Could you help have a check to see if we also can update them to Apache License?
Thank you very much.

Liwei.

**Comment by jgespino** [comment]
@2005songliwei Let me check on the two additional files and get back to you.

Ref. 56885

**Comment by jgespino** [comment]
Hi @2005songliwei 

The following files are part of the Intel® Distribution of OpenVINO™ toolkit which is under propriate license. 

./docs/IE_DG/Legal_Information.md
./docs/Legal_Information.md

Please let me know if you have any questions or if we can proceed to close the issue.

Regards,
Jesus

**Comment by 2005songliwei** [comment]
@jgespino 
Hi Jesus,
Thanks you for your response, in that two files ./docs/IE_DG/Legal_Information.md
./docs/Legal_Information.md, there are statement as below:
(This software and the related documents are Intel copyrighted materials, and your use of them is governed by the express license under which they were provided to you (License). Unless the License provides otherwise, you may not use, modify, copy, publish, distribute, disclose or transmit this software or the related documents without Intel's prior written permission.)
this may still need us got Intel written permission to disclose this toolkit in our release, I don't know if I understand right about
this statement, but is it possible to remove the private statement like that to make it clear that doesn't need got the additional permission from Intel. Thanks again.

Liwei.

**Comment by jgespino** [comment]
@2005songliwei 

Let me check with the team on this and get back to you.

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @2005songliwei 

The legal documents have been updated with the latest release: https://github.com/openvinotoolkit/openvino/blob/releases/2021/4/docs/Legal_Information.md

At this time, there are no plans to update on previous releases.

Regards,
Jesus

**Comment by 2005songliwei** [comment]
Hi @jgespino,

I have saw that change, thank you very much for your help.

Liwei.
