### ISSUE TITLE
why I cannot reshape the second input  when the IR has two input nodes

### ISSUE THREAD

**Issue by jlygit** [openvinotoolkit/openvino#57]
I change two input shapes and it doesn't work for the second input when the IR has two input nodes. why?

it work for the first input.

the code is
![image](https://user-images.githubusercontent.com/10195989/50214269-cd057c80-03ba-11e9-9cb1-99b918079756.png)

and the printf
![image](https://user-images.githubusercontent.com/10195989/50214288-d8f13e80-03ba-11e9-994c-537aab593a49.png)

**Comment by ljaljushkin** [comment]
Hi, jlygit!

Which type does second input (`variables/input_y`) have? 
It would be great if you attached your IR (.xml file) to debug the issue.

Thanks,
Nikolay

**Comment by jlygit** [comment]
@ljaljushkin

**Comment by jlygit** [comment]
@ljaljushkin 
sorry for that, the original IR is here
[tmp.zip](https://github.com/opencv/dldt/files/2699038/tmp.zip)

**Comment by ljaljushkin** [comment]
@jlygit, your model consists of independent graphs. Reshaping of such models (or Shape Inference) is not supported now. There're 2 options to resolve it:

1. Split this IR into 2 .xml. 
2. Wait for the patch or next release with support of independent parts in models.

**Comment by ljaljushkin** [comment]
@jlygit, you could also combine graphs by adding concatenation of outputs using `Concat` layer.

**Comment by jlygit** [comment]
@ljaljushkin 
thanks for you advises.
I has splited my IR into two xml-files as you sayed and it works

**Comment by lazarevevgeny** [comment]
The issue had been fixed already. Closing.
