### ISSUE TITLE
[Bug] why the layer type "input" is the status of "NOT_RUN"?

### ISSUE THREAD

**Issue by alixiu** [openvinotoolkit/openvino#5706]
##### System information (version)
- OpenVINO => 2020.4
- Operating System / Platform => Ubuntu 18.04
- Problem classification: Model Inference

##### Detailed description

Hi, I use tools of benchmark_app with an option of "-report_type  detailed_counters" to obtain layerwise time of DNN models. However, I observed the result of layer type "Input" is as following for all models.
<img width="763" alt="image" src="https://user-images.githubusercontent.com/46623669/118909389-87678800-b955-11eb-9685-9d833eed8979.png">

I have no idea why the input is the status of "NOT_RUN". Where did the time of input transmission go? Can you help me solve my confusion？Thanks.

**Comment by ilya-lavrenov** [comment]
Hi @alixiu 

The input is not run because input is already computed and no needs to process it.

**Comment by zulkifli-halim** [comment]
Hi, do you still need help on this issue?

**Comment by zulkifli-halim** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
