### ISSUE TITLE
[Bug]Error has occured for: select:StatefulPartitionedCall/MultiLevelMatMulCropAndResize/MultiLevelRoIAlign/Select when run python benchmark_app.py -m xxx.xml -d GPU

### ISSUE THREAD

**Issue by dlod-openvino** [openvinotoolkit/openvino#5751]
##### Detailed description
Error has occured for: select:StatefulPartitionedCall/MultiLevelMatMulCropAndResize/MultiLevelRoIAlign/Select Best_kernel.empty()(true) should be false
 
when run python benchmark_app.py -m xxx.xml -d GPU

![ERROR information](https://user-images.githubusercontent.com/59691336/119247985-9c941f00-bbc0-11eb-82c2-a07afb759bbc.png)

##### Steps to reproduce
1. Download Faster R-CNN ResNet50 V1 640x640 from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
2. Convert it into IR model
3. Run python benchmark_app.py -m xxx.xml -d GPU
[**successed**] -d CPU
[**failed**] -d GPU

**Comment by ilya-lavrenov** [comment]
CC @vladimir-paramuzov
