### ISSUE TITLE
Intel® Distribution of OpenVINO™ toolkit On macOS: ngraph static link with protobuf 3.7.1

### ISSUE THREAD

**Issue by junluan** [openvinotoolkit/openvino#577]
Intel® Distribution of OpenVINO™ toolkit On macOS

ngraph lib in m_openvino_toolkit_p_2020.2.117.dmg (2020.2) static link with protobuf 3.7.1, this cause protobuf version conflict when user's project already use another version of protobuf

The output error message like this below:

```
[libprotobuf FATAL google/protobuf/stubs/common.cc:75] This program requires version 3.12.0 of the Protocol Buffer runtime library, but the installed version is 3.7.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "xxx.pb.cc".)
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: This program requires version 3.12.0 of the Protocol Buffer runtime library, but the installed version is 3.7.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "xxx.pb.cc".)
```

I also checked m_openvino_toolkit_p_2020.1.023.dmg. This 2020.1 version's ngraph did not compiled with protobuf.

I think maybe 2020.2 version is compiled with enable onnx, but 2020.1 version disable it.

Is this possible to disable protobuf in ngraph in the future release?

**Comment by ilya-lavrenov** [comment]
@junluan 

1. ONNX importer in 2020.2 is compiled into ngraph shared library, so protobuf is compiler as well.
Currently in master branch, onnx importer is already a separate dynamic library. So, if you don't use this library, you don't have any conflicts.
2. In [this](https://github.com/openvinotoolkit/openvino/pull/532) PR onnx importer is wrapped into plugin when is automatically loaded when a user try to call `Core::ReadNetwork`

@ilyachur  @dkurt do you know how we can use 2 protobufs in a single application?

**Comment by dkurt** [comment]
I think that different namespaces should be used. Otherwise there is a mess with symbols. In example, for OpenCV we use `openc-onnx` instead of origin `onnx`: https://github.com/opencv/opencv/blob/master/modules/dnn/misc/onnx/opencv-onnx.pb.h

**Comment by junluan** [comment]
Thank you @ilya-lavrenov 

In [this](https://github.com/openvinotoolkit/openvino/pull/532) PR you said the plugin is automatically loaded. I see registerReaders() both register onnx (inference_engine_onnx_reader) and xml (inference_engine_ir_readers) readers.

Is it possible to add some flag to control whether enable onnx reader. Because up to now, in most situations we use MO to generate xml model. So Core::ReadNetwork is commonly used by default.

**Comment by ilya-lavrenov** [comment]
@junluan `registerReaders` registers the path to the libraries, but it does not mean that they are loaded at this time. They are lazy loaded only if user passed IR or ONNX and only single reader is loaded depending on model type.

**Comment by ilya-lavrenov** [comment]
@dkurt we also use different namespace for ONNX https://github.com/openvinotoolkit/openvino/blob/master/ngraph/cmake/external_onnx.cmake#L38, but what is about protobuf?

CC @tomdol

**Comment by junluan** [comment]
@dkurt That will be ok. Thank you!

**Comment by dkurt** [comment]
Here some of the related issues:
https://github.com/opencv/opencv/issues/13328 (the most complete)
https://github.com/opencv/opencv/issues/10747
https://github.com/opencv/opencv/issues/12429
https://github.com/opencv/opencv/issues/10949
https://github.com/opencv/opencv/issues/10027

Cannot find a universal solution from it. Maybe @alalek can comment?

**Comment by tomdol** [comment]
Linking statically is recommended and this is why we do it this way in onnx_importer https://github.com/protocolbuffers/protobuf/blob/master/cmake/README.md#dlls-vs-static-linking

As mentioned, it's now a separate library and ngraph doesn't depend on protobuf any more.

**Comment by ilya-lavrenov** [comment]
@tomdol but will we have issues if user uses both ONNX importer and other library with protobuf inside?

**Comment by tomdol** [comment]
This depends a lot on how protobuf is used in this other app. We've had a problem with 2 protobuf versions in ONNXRuntime and UEP and the solution was to use a custom namespace for ONNX ilbrary used by onnx_importer.

There was another problem when ngraph was loaded globally in our python API which was fixed by changing the way it's loaded https://github.com/NervanaSystems/ngraph/pull/4769

In general I think at this point it should be safe to use protobuf in user's app and at the same time onnx_importer using its API that relies on `std::istream` (this is the setup used in UEP). If there are any actual problems - please report them and we'll definitely have a look.

**Comment by junluan** [comment]
@ilya-lavrenov @dkurt @tomdol 

I just find the reason which caused this problem.

**.pb.cc call's macro GOOGLE_PROTOBUF_VERIFY_VERSION which is

```
#define GOOGLE_PROTOBUF_VERIFY_VERSION                                    \
  ::google::protobuf::internal::VerifyVersion(                            \
    GOOGLE_PROTOBUF_VERSION, GOOGLE_PROTOBUF_MIN_LIBRARY_VERSION,         \
    __FILE__)
```

I link ngraph first then protobuf. The linker in macOS use the symble in ngraph instead of protobuf. When I changed the order to link protobuf first, I work's fine. But this problem does not happen in Linux, gcc link the correct symble.

Thank you.

**Comment by tomdol** [comment]
@junluan is it ok to close this issue? Can we consider this resolved?

**Comment by junluan** [comment]
@tomdol It's ok.
