### ISSUE TITLE
[Bug][Doc] Typo in ngraph_function docs

### ISSUE THREAD

**Issue by coneypo** [openvinotoolkit/openvino#5779]
[docs/snippets/example_ngraph_utils.cpp#L157](https://github.com/openvinotoolkit/openvino/blob/master/docs/snippets/example_ngraph_utils.cpp#L157)

`
if (partial_shape.is_dynamic() /* or !partial_shape.is_staic() */) {
`

![image](https://user-images.githubusercontent.com/7233586/119428800-2c140c00-bd40-11eb-8765-caef5ae03587.png)

`partial_shape.is_staic()` there, which should be `partial_shape.is_static()`

**Comment by ilyachur** [comment]
Hi @coneypo,

Thank you for the issue! I created PR https://github.com/openvinotoolkit/openvino/pull/5781 with the fix.

**Comment by coneypo** [comment]
Thanks llya, will close this issue;
