### ISSUE TITLE
Intel® Distribution of OpenVINO™ OS X support?

### ISSUE THREAD

**Issue by njern** [openvinotoolkit/openvino#58]
Are there any plans to add support for OS X as an OS development platform?

**Comment by shubha-ramani** [comment]
It’s in our plans to support it 1H of 2019.  Barring any unforeseen issues it should be on a screen near you within the next two releases.  Thanks for hanging in there with us.  We hear you!

**Comment by lazarevevgeny** [comment]
The support for OS X has been added. Closing the ticket.
