### ISSUE TITLE
Transpose_sinking Optimization

### ISSUE THREAD

**Issue by lisa0314** [openvinotoolkit/openvino#5822]
I find the transpose_sinking optimization code in master branch - https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/transformations/src/transformations/common_optimizations/transpose_sinking.cpp. However, I can't find related work in release branch such as 2021.2 and 2021.3. 
I want to know what's your plan to integrate the transpose_sinking optimization since I need this optimization to run NHWC model ? Will it be integrated in the next release?

**Comment by jgespino** [comment]
Hi @lisa0314 

transpose_sinking optimization was merged to the master branch under https://github.com/openvinotoolkit/openvino/pull/5026, this should be pulled into the next release.

Is there a particular model you plan on using? 

Regards,
Jesus

Ref. 43189
