### ISSUE TITLE
[Question] OneAPI ? Openvino? Can those work together?

### ISSUE THREAD

**Issue by dedoogong** [openvinotoolkit/openvino#5853]
I've optimized several DL models so far using both Openvino and TensorRT.

And recently I'm trying to implement some non-supported, custom ops (like NonZero or GatherND) using OneAPI as it would be better than OpenCL(I think SYCL would be better than this and I want to use Intel CPUs than super expensive Nvidia-GPUs for product deployment).

For that, I'm studying the newly introduced oneAPI with oneTBB and oneMKL. 

NonZero/GatherND has some overload in  memory access or data scanning/thread sync rather than Mul/Div/Add computation like Conv op as those ops needs just data indexing or value comparing.

So, I think recent Data Parallel C++ with TBB can reduce the op's running time. 

Isn't it?

Thank you.

**Comment by jgespino** [comment]
@AlexKoff88 @ilyachur Do you guys have any input on this topic?

**Comment by AlexKoff88** [comment]
+ @vladimir-paramuzov, @myshevts to comment.

@dedoogong, both operations are actually supported:
- https://docs.openvinotoolkit.org/latest/openvino_docs_ops_movement_GatherND_5.html
- https://docs.openvinotoolkit.org/latest/openvino_docs_ops_condition_NonZero_3.html

**Comment by myshevts** [comment]
on the oneAPI: we are not supporting SYCL or DPC+ for custom kernels at the moment.
oneTBB is ~same as the conventional TBB that we are using now
