### ISSUE TITLE
[Bug][Doc] Wrong word in multi-device plugin doc

### ISSUE THREAD

**Issue by coneypo** [openvinotoolkit/openvino#5905]
> Notice that every OpenVINO sample that supports "-d" (which stays for "device") 

https://github.com/openvinotoolkit/openvino/blob/master/docs/IE_DG/supported_plugins/MULTI.md#using-the-multi-device-with-openvino-samples-and-benchmarking-the-performance

It seems that wrong word "stays for" used there, maybe "stands for"?

**Comment by ilya-lavrenov** [comment]
@coneypo could you please create a patch?

**Comment by coneypo** [comment]
@ilya-lavrenov Hi Ilya, MR #5930 created for it.

**Comment by ilya-lavrenov** [comment]
thanks!
