### ISSUE TITLE
Difference output between MXNET model and IR model

### ISSUE THREAD

**Issue by huytuong010101** [openvinotoolkit/openvino#5978]
Thank you for creating Openvino Framework. It's really useful
I try to convert mobilefacenet_arcface from mxnet to IR model but the output of them is very difference
As you known, output of face recognition is feature vector. I used cosine distance to calculate distance from 2 output but it very big
Anyone meet this issue?

**Comment by brmarkus** [comment]
Can you provide more information, please?
Which network, where could we get it from for reproduction and analysis? How have you converted the model to IR, can you share the command-line, please?
How to test and verify the results? Have you used a sample from OpenVINO or OpenModelZoo?
