### ISSUE TITLE
[Bug][CPU] PerfCountersTest actually ignores the configuration for CPU plugin

### ISSUE THREAD

**Issue by mashoujiang** [openvinotoolkit/openvino#5980]
Reproduce:
1. modify https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/plugin/shared/include/behavior/perf_counters.hpp#L25 to `InferenceEngine::PluginConfigParams::NO`
2. ./cpuFuncTests --gtest_filter=*smoke_BehaviorTests/PerfCountersTest.NotEmptyWhenExecuted*

Result:
still could get the `GetPerformanceCounts()` successfully, 
so this config is never active, the config like 
` std::map<std::string, std::string> config = {{ InferenceEngine::PluginConfigParams::KEY_PERF_COUNT,
                                                   InferenceEngine::PluginConfigParams::NO }};` 
should work.
Is it a bug?

**Comment by Iffa-Meah** [comment]
Hi,

If possible could you explain further the steps that you did that results in that error?

Generally, you modified the link that you provide, next you compiled the OpenVINO package and run the binary ./cpuFuncTests.
Are these correct?

**Comment by mashoujiang** [comment]
> n the binary ./cpuFun

Yes, you're correct. What I want to explain is that the config `InferenceEngine::PluginConfigParams::NO` or `InferenceEngine::PluginConfigParams::YES` has no effect to the test result, but we may should expect different results.

**Comment by Iffa-Meah** [comment]
May I know the exact location of your cpuFuncTests binary?

![cpu_perf](https://user-images.githubusercontent.com/79643476/121886383-e5667000-cd47-11eb-82cf-256fd04a1cea.png)

**Comment by mashoujiang** [comment]
the cpuFuncTests binary should be in `openvino/bin/intel64/Debug` or `openvino/bin/intel64/Release`, and you should enable `ENABLE_MKL_DNN` and tests.

**Comment by jgespino** [comment]
Hi @mashoujiang 

I apologize for the delay, I was able to reproduce this behavior. Changing config between YES and NO does not have any effect. I am checking with the development team to understand if there are additional modifications that need to be made or if this is a bug. I will let you know as soon as I hear back.

Regards,
Jesus

Ref. 58889

**Comment by jgespino** [comment]
Closing per https://github.com/openvinotoolkit/openvino/pull/7410

> It is not guaranteed that using InferenceEngine::PluginConfigParams::NO config should provide empty performance counters map. Getting this map does not require a lot of CPU resources and map is not empty as a result
