### ISSUE TITLE
[Bug] Output Blob to std::vector is too slow. why??

### ISSUE THREAD

**Issue by dedoogong** [openvinotoolkit/openvino#6010]
##### System information (version)

- OpenVINO => 2021.3
- Operating System / Platform => Ubuntu 18
- Compiler => GCC
- Problem classification: Inference Engine
- Framework: TORCH->ONNX->OV
- Model name: R2D2

The output tensor size is 1x128x480x640 and blew code takes 100ms!! why so slow and how to speed up?
I limited the number of the CPU core to 4 when running the docker and CPU is the one in V100 server machine.

```
 auto out_blob = blob.second;
 auto output_shape = out_blob->getTensorDesc().getDims();
 LockedMemory<const void> blobMapped = as<MemoryBlob>(out_blob)->rmap();
 float *output_data_pointer = blobMapped.as<float *>();
 size_t output_data_size    = output_shape[0] * output_shape[1] * output_shape[2] * output_shape[3];               
 std::vector<float> output_data(output_data_pointer, output_data_pointer + output_data_size);
```

Thanky you!

**Comment by ilyachur** [comment]
Hi @dedoogong,

As I see from the code that you get the blob and after that copy data to vector.
Can you measure the performance of this line:
```              
 std::vector<float> output_data(output_data_pointer, output_data_pointer + output_data_size);
```

I think the main issue is here. If yes, it is not a OV issue. You copy data from raw array to vector.
Can you work with raw pointer in order to avoid vector creation?

**Comment by dedoogong** [comment]
yes I already did it and worked ok as we expected. 
Thank you~!

**Comment by dedoogong** [comment]
I have a simple question~!

I assumed Openvino folllows NCHW format.

So, if the output blob data is as below;

{1,2,3,4,5,6,7,8,9,10,11,12, 13,14,15,16,17,18,19,20,21,22,23,24}

then it would be like below in tensor format of [1, 2, 3, 4]
channel = 0
1   2   3  4
5   6   7  8
9 10 11 12

channel = 1
13 14 15 16
17 18 19 20
21 22 23 24

is it right??

**Comment by Iffa-Meah** [comment]
OpenVINO does support and follow Tensorflow NCHW format as emphasized in this [github link](https://github.com/openvinotoolkit/openvino/issues/652#issuecomment-635100843)

In NCHW, the C is arranged in the outer layer, and the pixels in each channel are close together, that is the form of 'RRRRRRGGGGGGBBBBBB ( [NCHW format](https://www.programmersought.com/article/32645367260/))

If compared with the TF industry explanations, your assumption is correct.
