### ISSUE TITLE
libinference_engine_legacy.so dependency

### ISSUE THREAD

**Issue by JustasZJ** [openvinotoolkit/openvino#6013]
Hello,

I have tried comping both openvino version 2021.2 and 2021.3 and in both versions it seems that libMKLDNNPlugin.so requires libinference_engine_legacy.so as a dependency. However, in https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Deep_Learning_Inference_Engine_DevGuide.html I don't see it listed as a dependency. Is there a way to avoid this dependency?

**Comment by ilyachur** [comment]
cc @ilya-lavrenov

**Comment by ilya-lavrenov** [comment]
Hi @JustasZJ,

Looks like docs are not updated. CPU plugin depends on legacy library on 2021.3 and older. Only since 2021.4 (current master) this dependency is eliminated.

Thanks,
Ilya.

**Comment by JustasZJ** [comment]
Thank you!
