### ISSUE TITLE
[Bug][code style] lower or upper camel case in code

### ISSUE THREAD

**Issue by coneypo** [openvinotoolkit/openvino#6049]
[inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/config.cpp](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/config.cpp) for example:

all are `const std::vector<std::map<std::string, std::string>>`:

- In #L15, `conf` in lower camel case;
- In #L19, `Configs` in upper camel case;
- In #L29, `MultiConfigs` in upper camel case;

- In #L80, `inconfigs` in lower camel case;
- In #L86, `multiinconfigs` in lower case;
- In #L95, `autoinconfigs` in lower case;
- In #L104, `multiconf ` in lower case;
- In #L108, `autoconf ` in lower case;

**Comment by Iffa-Meah** [comment]
Hi,

Just to clarify, are you asking about why the coding style is inconsistent, where sometimes the code is lower/upper case or else?
May you emphasize in detail?

**Comment by coneypo** [comment]
> Hi,
> 
> Just to clarify, are you asking about why the coding style is inconsistent, where sometimes the code is lower/upper case or else?
> May you emphasize in detail?

Thanks for your reply, this is what I want to check:);

**Comment by Iffa-Meah** [comment]
Sometimes there are multiple variables with similar names meant to be used.
The lower/upper case would distinct them better, such as In #L29, MultiConfigs, and In #L86, multiinconfigs.
They seem the same but actually, they are meant for different functionality.

It would be confusing if the multiinconfigs become MultiinConfigs where at a glance you would mistaken it as the same function call as #L29.

Generally, that's the reason.
