### ISSUE TITLE
[Bug] i can't find setupvars.sh in 2019_R2

### ISSUE THREAD

**Issue by LiaoZihZrong** [openvinotoolkit/openvino#6084]
hi,
i am junior of poenvino
i have already install openvino 2019_R2 
and it can run object_detection_sample_ssd
(in openvino/inference-engine/bin/intel64/Release)
but i can't find the **setupvars.sh**
and i can't run the **source /opt/intel/openvino/bin/setupvars.sh** , too

this is my install step:
```
git clone https://github.com/openvinotoolkit/openvino.git
cd openvino
git checkout 2019_r2
cd inference-engine
git submodule update --init --recursive
chmod +x install_dependencies.sh
./install_dependencies.sh
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make --jobs=$(nproc --all)
```

**Comment by brmarkus** [comment]
Are you looking for "https://github.com/openvinotoolkit/openvino/tree/master/scripts/setupvars/"? It contains "setupvars.sh" and "setupvars.bat".

**Comment by LiaoZihZrong** [comment]
thank you~
i use your guide 
and i success
