### ISSUE TITLE
Supported primitive descriptors list is empty for node when using sample model

### ISSUE THREAD

**Issue by doruime** [openvinotoolkit/openvino#62]
Hello,
I met a problem when I ran code blow using python api:
```
plugin = IEPlugin(device=DEVICE, plugin_dirs=PLUGIN_DIR)
if CPU_EXTENSION and 'CPU' in DEVICE:
    plugin.add_cpu_extension(CPU_EXTENSION)
net = IENetwork.from_ir(model=model_xml, weights=model_bin)
inputs = net.inputs
outputs = net.outputs
exec_net = plugin.load(network=net)
```

The error is:
**Supported primitive descriptors list is empty for node: bottleneck1_1/dim_red/conv**

The model is _person-detection-retail-0013_ which is one sample SSD model from installation package.

The problem comes from the last line _exec_net = plugin.load(network=net)_ , but I have no idea how to solve it.

Thank you for your help.

Best,
dcgao

**Comment by gdmit** [comment]
Hello! 

Could you please provide information about what CPU did you use to run the model?

**Comment by doruime** [comment]
> Hello!
> 
> Could you please provide information about what CPU did you use to run the model?

Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz

**Comment by wiibrew** [comment]
Hi,

I also ran into this error. I was writing a custom layer in c++ and it's solved by adding layer config code:
`std::vector<DataConfigurator> inps;
            for (const auto &in : layer->insData)
                inps.emplace_back(ConfLayout::PLN);
            addConfig(layer, inps, {DataConfigurator(ConfLayout::PLN)});` 
at end of the of the ext_customlayer.cpp (this code is for multiple inputs but should work for single as well).
Not sure if this is exactly the same case but hope help.

**Comment by depthwise** [comment]
@wiibrew saved me hours of debugging. Why this is not in the documentation, I'll never know.
