### ISSUE TITLE
[RFC][Questions]Does openvino support DG1/SG1/ Intel® Iris® Xe gpu?

### ISSUE THREAD

**Issue by fulinjie** [openvinotoolkit/openvino#6211]
Hi, @andrew-zaytsev @mletavin 

Has openvino support DG1/SG1/ Intel® Iris® Xe gpu?

The related information I'm able to find:
https://github.com/openvinotoolkit/openvino/issues/4887#issuecomment-804710301

https://github.com/openvinotoolkit/openvino/pull/1766/files#diff-580b909948fa0a61c2b6b31429fcd13f371f4015f47e0aca693ee7e9b76b95c2R124

https://software.intel.com/content/www/us/en/develop/articles/effective-deployment-ai-workloads-with-xe.html#:~:text=The%20inference%20FPS%20performance%20of,Quadro%20dedicated%20GPU%20with%20DirectML.

https://github.com/openvinotoolkit/openvino/pull/3523

If it's supported, is there any user guide/tutorial available to setup environment on DG1?

**Comment by brmarkus** [comment]
If the installed version of OpenVINO supports the GPU in question, then there is nothing to setup; the installation contains the proper GPU-plugin within the Inference-Engine, ENV-variables are set, the corresponding version of (NEO-)OpenCL can be installed (see GPU-installation-part guide like "https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#additional-GPU-steps").

Then run the sample "hello_query_device" to see whether the GPU-device in question gets listed - under which name.
Usually the device-name is jut "GPU"; in case multiple supported GPU-devices were found, they get listed under different names, like described under "https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_CL_DNN.html#device_naming_convention".

**Comment by vladimir-paramuzov** [comment]
@fulinjie Yes, DG1 is supported by OpenVINO and it's referred in https://github.com/openvinotoolkit/openvino/blob/master/docs/IE_DG/supported_plugins/GPU.md as `Intel® Iris® Xe MAX graphics`
@ttroilov, @andrew-zaytsev we need to add a page with description of setup process for DG1. Current documentation doesn't event have a valid link to the drivers.

**Comment by ttroilov** [comment]
yes, Intel® Iris® Xe Max (DG1) is supported by OpenVINO
to get driver please follow instructions provided here https://dgpu-docs.intel.com/installation-guides/index.html and https://dgpu-docs.intel.com/devices/iris-xe-max-graphics/index.html

**Comment by fulinjie** [comment]
Thanks @vladimir-paramuzov  @ttroilov @brmarkus a lot for the information:D.

**Comment by Baoyinliu** [comment]
when I try to run python demos in OpenModelZoo at SG1 GPU I got this erro:
RuntimeError: Failed to create plugin /opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
[CLDNN ERROR]. clGetPlatformIDs error -1001

I have followed "https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#additional-GPU-steps" to setup GPU

the environment i use is：
centOS: CentOS 7.9
OpenVINO: openvino_2021.2.185
GPU:SG1
./install_NEO_OCL_driver.sh -d 20.35

**Comment by vladimir-paramuzov** [comment]
@Baoyinliu I believe 20.35 driver doesn't support SG1. Please follow the links provided by @ttroilov for driver install guide.

**Comment by ttroilov** [comment]
20.35 doesn't support DG1/SG1
you need to download and install a driver by yourself  
to get driver please follow instructions provided here https://dgpu-docs.intel.com/installation-guides/index.html and https://dgpu-docs.intel.com/devices/iris-xe-max-graphics/index.html

**Comment by coneypo** [comment]
On my windows platform with OpenVINO 2021.4 release:

- CPU：                     Intel® Core i7-1165G7@2.8GHz, Tiger Lake
- iGPU：                    Intel(R) Iris(R) Xe Graphics
- dGPU:                      Intel(R) Iris(R) Xe MAX Graphics

Device manager:
![image](https://user-images.githubusercontent.com/7233586/125256281-e4b4ff80-e32e-11eb-9096-0266f384d14e.png)

Task manager:
![image](https://user-images.githubusercontent.com/7233586/125256412-01513780-e32f-11eb-9dca-29a9f1d7a021.png)

From `hello_query`:

```
GPU.0
        SUPPORTED_METRICS:
                AVAILABLE_DEVICES : [ 0 1 ]
                FULL_DEVICE_NAME : Intel(R) Iris(R) Xe Graphics (iGPU)
                OPTIMIZATION_CAPABILITIES : [ FP32 BIN BATCHED_BLOB FP16 INT8 ]
                RANGE_FOR_ASYNC_INFER_REQUESTS : { 1, 2, 1 }
                RANGE_FOR_STREAMS : { 1, 2 }
                DEVICE_TYPE : integrated
                DEVICE_GOPS : { FP32: 1996.8; FP16: 3993.6; U8: 7987.2; I8: 7987.2;  }
                GPU_DEVICE_TOTAL_MEM_SIZE : 6786088960
                GPU_UARCH_VERSION : unknown
                GPU_EXECUTION_UNITS_COUNT : 96
        SUPPORTED_CONFIG_KEYS (default values):
                CACHE_DIR : ""
                CLDNN_ENABLE_FP16_FOR_QUANTIZED_MODELS : YES
                CLDNN_GRAPH_DUMPS_DIR : ""
                CLDNN_MEM_POOL : YES
                CLDNN_NV12_TWO_INPUTS : NO
                CLDNN_PLUGIN_PRIORITY : 0
                CLDNN_PLUGIN_THROTTLE : 0
                CLDNN_SOURCES_DUMPS_DIR : ""
                CONFIG_FILE : ""
                DEVICE_ID : ""
                DUMP_KERNELS : NO
                DYN_BATCH_ENABLED : NO
                EXCLUSIVE_ASYNC_REQUESTS : NO
                GPU_ENABLE_LOOP_UNROLLING : YES
                GPU_MAX_NUM_THREADS : 8
                GPU_PLUGIN_PRIORITY : 0
                GPU_PLUGIN_THROTTLE : 0
                GPU_THROUGHPUT_STREAMS : 1
                PERF_COUNT : NO
                TUNING_FILE : ""
                TUNING_MODE : TUNING_DISABLED

GPU.1
        SUPPORTED_METRICS:
                AVAILABLE_DEVICES : [ 0 1 ]
                FULL_DEVICE_NAME : Intel(R) Iris(R) Xe MAX Graphics (dGPU)
                OPTIMIZATION_CAPABILITIES : [ FP32 BIN BATCHED_BLOB FP16 INT8 ]
                RANGE_FOR_ASYNC_INFER_REQUESTS : { 1, 2, 1 }
                RANGE_FOR_STREAMS : { 1, 2 }
                DEVICE_TYPE : discrete
                DEVICE_GOPS : { FP32: 2534.4; FP16: 5068.8; U8: 10137.6; I8: 10137.6;  }
                GPU_DEVICE_TOTAL_MEM_SIZE : 3335307264
                GPU_UARCH_VERSION : unknown
                GPU_EXECUTION_UNITS_COUNT : 96
        SUPPORTED_CONFIG_KEYS (default values):
                CACHE_DIR : ""
                CLDNN_ENABLE_FP16_FOR_QUANTIZED_MODELS : YES
                CLDNN_GRAPH_DUMPS_DIR : ""
                CLDNN_MEM_POOL : YES
                CLDNN_NV12_TWO_INPUTS : NO
                CLDNN_PLUGIN_PRIORITY : 0
                CLDNN_PLUGIN_THROTTLE : 0
                CLDNN_SOURCES_DUMPS_DIR : ""
                CONFIG_FILE : ""
                DEVICE_ID : ""
                DUMP_KERNELS : NO
                DYN_BATCH_ENABLED : NO
                EXCLUSIVE_ASYNC_REQUESTS : NO
                GPU_ENABLE_LOOP_UNROLLING : YES
                GPU_MAX_NUM_THREADS : 8
                GPU_PLUGIN_PRIORITY : 0
                GPU_PLUGIN_THROTTLE : 0
                GPU_THROUGHPUT_STREAMS : 1
                PERF_COUNT : NO
                TUNING_FILE : ""
                TUNING_MODE : TUNING_DISABLED

```

**Comment by Iffa-Meah** [comment]
Intel will no longer monitor this thread since this issue has been resolved.  If you need any additional information from Intel, please submit a new question
