### ISSUE TITLE
install inference-engine on ARM（armv6/armv7）such as TK1/TX1/TX2

### ISSUE THREAD

**Issue by Ashsur** [openvinotoolkit/openvino#63]
we can Install the Intel® Distribution of OpenVINO™ Toolkit for Raspbian* OS.[https://software.intel.com/en-us/articles/OpenVINO-Install-RaspberryPI], what i`m confused is how can i install OPENVINO for other ARM platform sunch as TX2(ARM a57)

**Comment by om777** [comment]
It will work on arm64 through foreign architecture armhf.
$ dpkg --add-architecture armhf
$ apt update
$ apt-get install libusb-1.0-0:armhf libstdc++6:armhf

**Comment by hyliu-deepnorth** [comment]
@om777 
Which version can I use on ARM, the RaspberryPI version Or the Linux version ? Thanks

**Comment by skhameneh** [comment]
I'm documenting how to resolve some ARM64 issues with a schroot workaround for those interested:
https://github.com/skhameneh/OpenVINO-ARM64

Feel free to file an issue or make a PR if you'd like anything to be added.

**Comment by avitial** [comment]
There are some instructions available on how to build the toolkit from source on ARM64 SBCs for usage with NCS2, please checkout the following guide: https://software.intel.com/content/www/us/en/develop/articles/arm64-sbc-and-ncs2.html. Hope you find it helpful.

Closing this, feel free to reopen and ask additional questions related to this topic.
