### ISSUE TITLE
[Bug] Will GPU plugin throw exception when SetConfigWithNoExistingKey

### ISSUE THREAD

**Issue by coneypo** [openvinotoolkit/openvino#6341]
Run functional tests for CPU or GPU:

- `./cpuFuncTests --gtest_filter=*smoke_BehaviorTests/IncorrectConfigAPITests.SetConfigWithNoExistingKey*`
- `./gpuFuncTests --gtest_filter=*smoke_BehaviorTests/IncorrectConfigAPITests.SetConfigWithNoExistingKey*`

Test case here: [IncorrectConfigAPITests/SetConfigWithNoExistingKey](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/plugin/shared/include/behavior/config.hpp#L168)

```
TEST_P(IncorrectConfigAPITests, SetConfigWithNoExistingKey) {
	// Skip test according to plugin specific disabledTestPatterns() (if any)
	SKIP_IF_CURRENT_TEST_IS_DISABLED()
	// Create CNNNetwork from ngrpah::Function
	InferenceEngine::CNNNetwork cnnNet(function);
	ASSERT_NO_THROW(ie->GetMetric(targetDevice, METRIC_KEY(SUPPORTED_CONFIG_KEYS)));
	if (targetDevice.find(CommonTestUtils::DEVICE_GNA) != std::string::npos) {
		ASSERT_THROW(ie->SetConfig(configuration, targetDevice), InferenceEngine::NotFound);
	} else {
		try {
			ie->SetConfig(configuration, targetDevice);
		} catch (InferenceEngine::Exception &) {}
	}
}
```

For GNA, ASSERT_THROW `InferenceEngine::NotFound`;
For CPU plugin, can throw with `ASSERT_THROW(ie->SetConfig(configuration, targetDevice), InferenceEngine::Exception);
But for GPU plugin, will throw nothing, so for this test:

```
INSTANTIATE_TEST_SUITE_P(smoke_BehaviorTests, IncorrectConfigAPITests,
						::testing::Combine(
								::testing::ValuesIn(netPrecisions),
								::testing::Values(CommonTestUtils::DEVICE_GPU),
								::testing::ValuesIn(conf)),
						 IncorrectConfigAPITests::getTestCaseName);
```

`conf` is empty for GPU there because GPU plugin will not throw if Setconfig() with No ExistingKey;

https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/config.cpp#L149

So my point is should GPU plugin throw exception when SetConfigWithNoExistingKey and maybe change this test to 

```
if (targetDevice.find(CommonTestUtils::DEVICE_GNA) != std::string::npos) {
	ASSERT_THROW(ie->SetConfig(configuration, targetDevice), InferenceEngine::NotFound);
} else {
	ASSERT_THROW(ie->SetConfig(configuration, targetDevice), InferenceEngine::Exception);
}
```

Or for GPU plugin, this test will be meaningless, not `SetConfigWithNoExistingKey`, just set empty config for it to pass this test;

**Comment by vladimir-paramuzov** [comment]
@coneypo Actually GPU plugin does throw an exception for invalid config keys, but test instances for GPU has **valid** config at the moment. Fixed in #6357

**Comment by coneypo** [comment]
Thanks for your quick comment and PR :)

**Comment by vladimir-paramuzov** [comment]
GPU plugin test cases have been fixed, but enabling code below
```
if (targetDevice.find(CommonTestUtils::DEVICE_GNA) != std::string::npos) {
	ASSERT_THROW(ie->SetConfig(configuration, targetDevice), InferenceEngine::NotFound);
} else {
	ASSERT_THROW(ie->SetConfig(configuration, targetDevice), InferenceEngine::Exception);
}
```
leads to test failures for MULTI plugin. @myshevts could you have a look?

**Comment by myshevts** [comment]
yep, the MULTI SetCOnfig is seemingly corrupted. fixing this and the test (that should now pass): https://github.com/openvinotoolkit/openvino/pull/6373/files
