### ISSUE TITLE
[Feature request]Post-training deep neural network pruning via layer-wise calibration is this method has been merged?

### ISSUE THREAD

**Issue by ColdCodeCool** [openvinotoolkit/openvino#6369]
Post-training deep neural network pruning via layer-wise calibration, I find this article for OpenVINO, it said the pruning method has been released as part of OpenVINO, where does it locate?

**Comment by zulkifli-halim** [comment]
Hello @ColdCodeCool, I found one layerwise folder in this location: `C:\Python\Python37\Lib\site-packages\pot-1.0-py3.7.egg\compression\algorithms\sparsity\layerwise_finetuning`, is it what are you looking for?

**Comment by zulkifli-halim** [comment]
Close Issue due to no response.

**Comment by ColdCodeCool** [comment]
@zulkifli-halim  yes, thank you, that's it
