### ISSUE TITLE
facenet FP16 on MYRIAD is not working as expected.

### ISSUE THREAD

**Issue by terryaic** [openvinotoolkit/openvino#64]
When using facenet FP32 on CPU, everything works fine, but FP16 on MYRIAD is not working as expected, most of the inference output are either 1 or -1.

**Comment by shubha-ramani** [comment]
Hi terryaic. Are you using one of these pre-trained models ? 

[Facenet pre-trained models ](https://github.com/davidsandberg/facenet#pre-trained-models)

Did you follow these instructions to properly convert a Facenet model to IR ?
[Converting a Tensorflow Facenet model ](https://software.intel.com/en-us/articles/OpenVINO-Using-TensorFlow#converting-a-tensorflow-facenet-model)

Please be more specific in your problem description so that we may help you.

Thanks for using OpenVino !

Shubha

**Comment by louisZL** [comment]
I have the same problem. Anyone can help?

Thank you.

**Comment by louisZL** [comment]
like: https://software.intel.com/zh-cn/node/802451

**Comment by masju96** [comment]
Same trouble here. I've been investigating the problem for a while and I wonder if it is a problem involving Inception Resnet v1. According to the MYRIAD plugin documentation, it only supports Inception Resnet v2. The pre-trained models in David Sandberg's repo are Inception Resnet v1 and, although there is a Inception Resnet v2 implementation, I could not find any pre-trained model to test. 

Anyone could confirm this hypothesis or am I horribly wrong?

Thank you

**Comment by avitial** [comment]
There is a pre-trained model available in OMZ for newer OpenVINO releases, check the link to [this document]( https://docs.openvinotoolkit.org/latest/omz_models_public_inception_resnet_v2_tf_inception_resnet_v2_tf.html) where you will find relevant information about _inception-resnet-v2-tf_ model as well as the model files in [this location](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/inception-resnet-v2-tf). Also here is the most current list of supported networks by MYRIAD Plugin [here](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_MYRIAD.html); GoogleNet (Inception) v1, v2, v4 are listed as supported and [googlenet-v1-tf](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/googlenet-v1-tf) among other versions is available in OMZ. 

Closing this as issue may not be actual or present in current release, feel free to reopen and ask additional questions related to this topic if issue persists.
