### ISSUE TITLE
kaldi model inference speed

### ISSUE THREAD

**Issue by ArtemisZGL** [openvinotoolkit/openvino#6402]
After converting model, I found when using nnet3-compute is faster than using speech-sample (8s vs 10s )，and the cpu usage nnet3-compute is much lower(100 % vs 700%), is it normal ?
  
Besides the batch-size flag -bs seems have no influence for the speed when setting cw_r or cw_l, why ?

**Comment by ArtemisZGL** [comment]
@Iffa-Meah hi, can you give some  help, in current openvino version, the calibration_tool is not yet support, how can we quantize model for int8 ? I have tried the FP16, but only half the model size , make no difference on inference speed.

**Comment by ArtemisZGL** [comment]
here is my model config
```
 fixed-affine-layer name=lda input=Append(-1,0,1) affine-transform-file=exp/chain/tdnn7p/configs/lda.mat
  spec-augment-layer name=idct-spec-augment freq-max-proportion=0.3 time-zeroed-proportion=0.2 time-mask-max-frames=20

  # the first splicing is moved before the lda layer, so no splicing here
  relu-batchnorm-dropout-layer name=tdnn1 l2-regularize=0.01 dropout-proportion=0.0 dropout-per-dim=true dropout-per-dim-continuous=true dim=1535
  tdnnf-layer name=tdnnf2 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=1
  tdnnf-layer name=tdnnf3 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=1
  tdnnf-layer name=tdnnf4 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=1
  tdnnf-layer name=tdnnf5 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=0
  tdnnf-layer name=tdnnf6 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=3
  tdnnf-layer name=tdnnf7 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=3
  tdnnf-layer name=tdnnf8 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=3
  tdnnf-layer name=tdnnf9 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=3
  tdnnf-layer name=tdnnf10 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=3
  tdnnf-layer name=tdnnf11 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=3
  tdnnf-layer name=tdnnf12 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=3
  tdnnf-layer name=tdnnf13 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=3
  tdnnf-layer name=tdnnf14 l2-regularize=0.01 dropout-proportion=0.0 bypass-scale=0.75 dim=1535 bottleneck-dim=384 time-stride=3
  linear-component name=prefinal-l dim=384 l2-regularize=0.01 orthonormal-constraint=-1.0

  prefinal-layer name=prefinal-chain input=prefinal-l l2-regularize=0.01 big-dim=2048 small-dim=384
  output-layer name=output include-log-softmax=false dim=7520 l2-regularize=0.002

  prefinal-layer name=prefinal-xent input=prefinal-l l2-regularize=0.01 big-dim=2048 small-dim=384
  output-layer name=output-xent dim=7520 learning-rate-factor=5.0 l2-regularize=0.002
```

**Comment by Iffa-Meah** [comment]
Hi,

can you share your model files instead, and steps to reproduce

**Comment by ArtemisZGL** [comment]
@Iffa-Meah ok，give me some time upload the files， thanks

**Comment by ArtemisZGL** [comment]
@Iffa-Meah  hi, here is the kaldi mdl model, feature ark (contain 5 audio), and the converted files, https://drive.google.com/drive/folders/1y9nBV0oEU6XQvg7TLkIz9fjDyamFw73h?usp=sharing

I first use the mo_kaldi.py to convert the model
```
python3 ./mo_kaldi.py --input_model 0.mdl --output output --remove_output_softmax
```
then i use the compiled speech-sample in inference_engine/samples/cpp to do the inference
```
/root/inference_engine_cpp_samples_build/intel64/Release/speech_sample -i  feats_zhou.ark -m 0.xml -d CPU -o test.ark -cw_l 31 -cw_r 31


result:
Total time in Infer (HW and SW):        9194.93 ms
Frames in utterance:                    1585 frames
Average Infer time per frame:           5.80122 ms
End of Utterance 0
...
```
Besides, I use the nnet3-compute in kaldi to do the inference for comparasion
```
nnet3bin/nnet3-compute 0.mdl ark:feats_zhou.ark ark:output.ark

result:
Time taken 38.5967s: real-time factor assuming 100 frames/sec is 0.506851
```

which mean the rtf is 0.50 vs 0.58

**Comment by ArtemisZGL** [comment]
when converting the model, i found a bug in the code https://github.com/openvinotoolkit/openvino/issues/6337

**Comment by ArtemisZGL** [comment]
I tried above procedure in another machine, which have 80 cpu cores compared with above machine with 8 cores,  but it became much slower, even cpu utils became 3600% from 700%. It's quiet strange to occupy more resource but became slower.

**Comment by ArtemisZGL** [comment]
I want to change the infer mode from async to sync by changing the method StartAsync() to infer() according to docs https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1InferRequest.html, but get the error 
```
error: 'class InferenceEngine::InferRequest' has no member named 'infer'
```
so i wonder can i use sync mode or I missed something?

**Comment by jgespino** [comment]
Hi @ArtemisZGL 

> cpu usage nnet3-compute is much lower(100 % vs 700%), is it normal ?

What CPU model are you using? On my side, converting your model to FP16 I was seeing around 280% CPU utilization.

> Besides the batch-size flag -bs seems have no influence for the speed when setting cw_r or cw_l, why ?

This is expected and is stated in the help menu of the speech_sample: "If you use the cw_l or cw_r flag, then batch size and nthreads  arguments are ingnored."

We highly recommend using the benchmark_tool for any performance measurements. Could you please try that and let me know the results? Also, we just released OpenVINO 2021.4 today. Could you upgrade to the latest and retest?

In order to keep track of all the questions, please ask questions related to the original topic. If you could please start a new issue for the following.

> I want to change the infer mode from async to sync by changing the method StartAsync() to infer() according to docs https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1InferRequest.html, but get the error

Regards,
Jesus

**Comment by ArtemisZGL** [comment]
hi @jgespino , thanks for your help
1.  I run the same code and model in two machine, CPU utilization  was 600% and 3600% respectively, while the latter even slower than the former. Their system both not CentOS7, but a linux version based on it. The former one is a virtual machine, the latter is not.  I run the code in the docker based on https://hub.docker.com/r/openvino/centos7_runtime. Here is their CPU model:
```
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 8
On-line CPU(s) list: 0-7
Thread(s) per core: 1
Core(s) per socket: 8
Socket(s): 1
NUMA node(s): 1
Vendor ID: AuthenticAMD
CPU family: 23
Model: 49
Model name: AMD EPYC 7K62 48-Core Processor
Stepping: 0
CPU MHz: 2595.124
BogoMIPS: 5190.24
Hypervisor vendor: KVM
Virtualization type: full
L1d cache: 32K
L1i cache: 32K
L2 cache: 4096K
L3 cache: 16384K
NUMA node0 CPU(s): 0-7
```
and
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                80
On-line CPU(s) list:   0-79
Thread(s) per core:    2
Core(s) per socket:    20
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz
Stepping:              4
CPU MHz:               2799.982
BogoMIPS:              5001.61
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              28160K
NUMA node0 CPU(s):     0-19,40-59
NUMA node1 CPU(s):     20-39,60-79
```
I have read the speech-sample code roughly. Based on my running command, the number of  thread and inferRequest should be 1. Although using the asyn mode, but it seems the program will block to wait for the previous result.  I also check the return  code for inferRequest.Wait, all of them are "OK". So I am quiet strange about the CPU utilization. 

2.  Thanks, I will try the benchmark_tool  and the new version, and notify you of the result as soon as possible.
3. Sorry about that , I will start a new issue next time.
```
I want to change the infer mode from async to sync by changing the method StartAsync() to infer() according to docs https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1InferRequest.html, but get the error
```

**Comment by ArtemisZGL** [comment]
@jgespino I have tried the new version, but it make no difference on speed or CPU utilization.  Will the gcc or some else version affect ?

**Comment by ArtemisZGL** [comment]
@jgespino hello, can you give some explanation about the CPU utilization?

**Comment by jgespino** [comment]
Hi @ArtemisZGL 

How are you measuring the CPU utilization? I believe you will need to use `htop` for multi-core CPUs.

> Model name: AMD EPYC 7K62 48-Core Processor

This is not a supported platform, please take a look at the [system requirements](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/system-requirements.html) for the OpenVINO toolkit.

Regards,
Jesus

**Comment by ArtemisZGL** [comment]
@jgespino yes, I used the htop and top, it open several process but the speed didn't improve.

**Comment by jgespino** [comment]
Hi @ArtemisZGL 

htop and top will only show you the CPU utilization but will not improve the performance. I ran your model using the default settings on the benchmark app and I observed the following using an Intel(R) Core(TM) i5-9300H processor. 

```
$python3 /opt/intel/openvino_2021/deployment_tools/tools/benchmark_tool/benchmark_app.py -m 0.xml
Count:      29732 iterations
Duration:   60015.53 ms
Latency:    6.36 ms
Throughput: 495.41 FPS
```

The following results were obtained by specifying nstream depending on the processor.
```
$python3 /opt/intel/openvino_2021/deployment_tools/tools/benchmark_tool/benchmark_app.py -m 0.xml -nstreams 8
Count:      46184 iterations
Duration:   60023.34 ms
Latency:    9.46 ms
Throughput: 769.43 FPS
```

Notice that the benchmark_app usually produces optimal performance for any device out of the box. However, you can tweak some options to improve the performance depending on your device and model. Take a look at the [Introduction to the Performance Topics](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Intro_to_Performance.html) document for additional details. 

Please give it a try and let me know your results?

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @ArtemisZGL 

Were you able to try my previous suggestion? Please let me know if you need additional assistance. 

Regards,
Jesus

**Comment by ArtemisZGL** [comment]
@jgespino sorry for late reply, I found it's the support of chunk_size which limit the inference speed of tdnn nnet3 model in Kaldi. Hoping to support this feature as soon as possible. Or can you give me some suggestions how to implement it by myself ?

**Comment by ArtemisZGL** [comment]
@jgespino hi, I have done some work to support chunk inference for converted kaldi model, but after I further added subsample  operation the inference result is wrong. Is there any way to get the intermediate result in the graph for debugging ?

**Comment by jgespino** [comment]
Hi @ArtemisZGL 

Do you want to see the inference results from a different layer? If so, take a look at the [Cutting Off Parts of a Model](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Cutting_Model.html) documentation and see if this is what you were looking for.

Regards,
Jesus

**Comment by ArtemisZGL** [comment]
@jgespino thanks, that is what I want to do.

**Comment by ArtemisZGL** [comment]
@jgespino I found if I use 2021.4 to convert the kaldi model will get this error "[ GENERAL_ERROR ] AssertionFailed: outputNode != nullptr" when loading several model, but if I use 2021.3 to convert the same model, everything is normal. Can you have a look at this?

The error seems come from codes below, when checking if the output of MemoryOutputNode already registered.
```
td::lock_guard<std::mutex> lock{MKLDNNMemoryNodeVirtualEdge::holderMutex};
    // in case of output already registered
    auto& holder = MKLDNNMemoryNodeVirtualEdge::getExisted();
    auto sibling = MKLDNNMemoryNodeVirtualEdge::getByName(holder, node->getId());
    if (sibling != nullptr) {
        auto outputNode = dynamic_cast<MKLDNNMemoryOutputNode*>(sibling);
        IE_ASSERT(outputNode != nullptr);
        outputNode->setInputNode(node);
    } else {
        holder[node->getId()] = node;
    }
    return &holder;
```
