### ISSUE TITLE
Reporting ngraph reporting of operator version.

### ISSUE THREAD

**Issue by jkrigelman** [openvinotoolkit/openvino#6452]
##### System information (version)
OpenVINO=> 2021.4
Operating System / Platform => Ubuntu 18.04.5 LTS
Python Version => 3.9.5
Compiler => GCC 9.3.0
Problem classification => Operator Version Information

##### Detailed description
OpenVINO support multiple versions of operators throughout the opsets, possibly even simultaneously based on the version information in the XML files. Some of these operators can have dramatic changes in either attributes, or worse, input tensors. The problem is that by the time nGraph reports the operator to the user, there is no indication as to what version of the operator was used. So it is hard to predict what the inputs, outputs and attributes are for operators spanning multiple versions. It would be extremely useful if this was reported in possibly the rtinfo or via some other method.

##### Steps to reproduce

```python
        ie = IECore()
        network = ie.read_network(model=ir_file, weights=bin_file)
        ngraph = ng.function_from_cnn(network)
        for node in ngraph.get_ordered_ops():
            node_type = node.get_type_name()
            # node_version = node.get_????()
```

- Contact Intel Internal ArchBench team for environment as needed.

**Comment by jgespino** [comment]
Hi @jkrigelman 

Thank you for your input, I have submitted a feature request with the development team for consideration.

Regards,
Jesus 

Ref. 59443

**Comment by ilya-lavrenov** [comment]
CC @akuporos

**Comment by ilyachur** [comment]
@postrational @jiwaszki Please have a look.

**Comment by jkrigelman** [comment]
Perfect. Thanks @ilyachur
