### ISSUE TITLE
error: ‘class InferenceEngine::InferRequest’ has no member named ‘infer’

### ISSUE THREAD

**Issue by ArtemisZGL** [openvinotoolkit/openvino#6457]
according doc here（https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1InferRequest.html#a3391ce30894abde730523e9ca9371ce8）
I want to use the synchronous mode in speech_sample, but got this error

> error: ‘class InferenceEngine::InferRequest’ has no member named ‘infer’

Am I misunderstand sth?

**Comment by Iffa-Meah** [comment]
It seems like the program wasn't linked properly.
Make sure you had run setupvars beforehand.

I recommend that you refer to this [Speech Library and Speech Recognition Demos](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_samples_speech_libs_and_demos_Speech_libs_and_demos.html#run-demos)

Can you share the command that you had used to run the sample with?

**Comment by ArtemisZGL** [comment]
hi，@Iffa-Meah thanks for your reply. I can run the demo code speech_sample correctly, and just change the line for infer.
```
/root/inference_engine_cpp_samples_build/intel64/Release/speech_sample_own -i feats.ark -m final.xml -d CPU -o test.ark  -r -cw_l 31 -cw_r 31
```
and i build this using inference_engine/samples/cpp/build_samples.sh

**Comment by Iffa-Meah** [comment]
Generally the speech sample already had its own functionalities defined. Try to run the sample with -h only and see the options available especially for sync/async, if that option is there. (eg: the object detection sample has the -at (yolo/ssd/etc option))

**Comment by ArtemisZGL** [comment]
Hi, @Iffa-Meah , unfortunately, it doesn't implement different mode for inference. And without chunk or subsampling options like kaldi. I read the code in speech_sample, and I am confused about how can it process context, because now it seems start inference frame by frame, is there any docs about that?

**Comment by jgespino** [comment]
@ArtemisZGL Try using `Infer()` instead of `infer()`. See the Inference Engine C++ API Reference documentation:
https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1InferRequest.html#a3391ce30894abde730523e9ca9371ce8

Regards,
Jesus

**Comment by ArtemisZGL** [comment]
my fault, Infer is ok.
