### ISSUE TITLE
model optimizer failure with different dilation parameters for width and height

### ISSUE THREAD

**Issue by xonobo** [openvinotoolkit/openvino#65]
I can get an IR model of a caffe model by the model optimizer but when I look at the xml output I see that the repeated dilation paramaters for height and width are not parsed by the model optimizer.

Here is the convolutional layer in caffe prototxt:
```
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  convolution_param {
    num_output: 32
    kernel_w: 5
    kernel_h: 5
    stride: 1
    pad_w: 4
    pad_h: 0
    dilation: 1
    dilation: 2
  }
}
```

and this is the corresponding xml output of the MO:

```
<layer id="1" name="conv1" precision="FP16" type="Convolution">
			<data dilations="1,1" group="1" kernel="5,5" output="32" pads_begin="0,4" pads_end="0,4" strides="1,1"/>
			<input>
				<port id="0">
					<dim>1</dim>
					<dim>1</dim>
					<dim>32</dim>
					<dim>256</dim>
				</port>
			</input>
			<output>
				<port id="3">
					<dim>1</dim>
					<dim>32</dim>
					<dim>28</dim>
					<dim>260</dim>
				</port>
			</output>
			<blobs>
				<weights offset="0" size="1600"/>
				<biases offset="1600" size="64"/>
			</blobs>
		</layer>

```
The dilations in the xml should be "1,2". Is there any work around or solution to this case?

**Comment by lazarevevgeny** [comment]
@xonobo, is this issue still actual?

**Comment by Adrianf1980** [comment]
Can you stop to spam the list

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
