### ISSUE TITLE
[Bug] ie_api.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN15InferenceEngine10IExtension9getOpSetsEv'

### ISSUE THREAD

**Issue by TheGreatGalaxy** [openvinotoolkit/openvino#6540]
##### System information (version)
- OpenVINO => 2020.4
- Operating System / Platform => Ubuntu 18.04

##### Detailed description

When i have installed openvino by 'sudo apt and .tar.gz', when run 'from openvino.inference_engine import IENetwork, IEPlugin' in python 3, it always report 'site-packages/openvino/inference_engine/ie_api.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN15InferenceEngine10IExtension9getOpSetsEv'. See the pictures: 
![2021-07-06_21-27](https://user-images.githubusercontent.com/43978497/124609041-d899ef80-dea1-11eb-813c-971bb0d1b29a.png)

I don't know why. The install progress all is ok.

**Comment by brmarkus** [comment]
With using Ubuntu 18.04 and (the older) OpenVINO in version (v2021.4 was recently published) it looks like your Python version v3.8 is too new:
See https://docs.openvinotoolkit.org/2020.4/openvino_inference_engine_ie_bridges_python_docs_api_overview.html :

```
Supported OSes
Inference Engine Python* API is supported on Ubuntu* 16.04 and 18.04, CentOS* 7.3 OSes, Raspbian* 9, Windows* 10 and macOS* 10.x. Supported Python* versions:

OPERATING SYSTEM	SUPPORTED PYTHON* VERSIONS:
[...]
Ubuntu* 18.04	2.7, 3.5, 3.6, 3.7
[...]
```
Can you try to use an older version of Python, e.g. v3.7?
Or upgrade to Ubuntu 20.04?

**Comment by TheGreatGalaxy** [comment]
ok. Thanks. The python3.7 can run successfully. But the python3.8, which has installed openvino by pip install, still can running openvino without source command. But it will report error shown as the above picture after "source ${OPENVINO_INSTALL_DIR}/bin/setupvars.sh". Do you has a plan when to support python3.8?

**Comment by brmarkus** [comment]
Sorry, I cannot comment on planning or support-roadmap.
I think the Python-version might be aligned with the one from the OS - like Ubuntu 18.04 itself only supports up to Python v3.7?

**Comment by ilya-lavrenov** [comment]
@TheGreatGalaxy the latest version already supports python 3.8, see https://pypi.org/project/openvino/

**Comment by TheGreatGalaxy** [comment]
> Sorry, I cannot comment on planning or support-roadmap.
> I think the Python-version might be aligned with the one from the OS - like Ubuntu 18.04 itself only supports up to Python v3.7?

Ok. Thanks a lot.

**Comment by jgespino** [comment]
Closing, feel free to re-open if you have additional questions regarding this topic.
