### ISSUE TITLE
ModuleNotFoundError: No module named 'openvino.inference_engine.constants'

### ISSUE THREAD

**Issue by adk9** [openvinotoolkit/openvino#655]
I built and installed the Python module by using the `-DENABLE_PYTHON=ON` CMake flag. When I try to load the Python module, I see the following error:
```bash
$ python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from openvino.inference_engine import IECore
  File "/home/adk/openvino_dist/python/python3.6/openvino/inference_engine/__init__.py", line 1, in <module>
    from .ie_api import *
  File "ie_api.pyx", line 23, in init openvino.inference_engine.ie_api
ModuleNotFoundError: No module named 'openvino.inference_engine.constants'
```

I'm using Python 3.6.9 and openvino `master`.

**Comment by yury-gorbachev** [comment]
@akuporos, @nkogteva can you help?

**Comment by akuporos** [comment]
Hello @adk9,
Have you used the last OV master? 
Looks like you built ie_api target, but it's need also build constants. But since last Friday there should be enough to build ie_api target.

Best regards,
Anastasia

**Comment by adk9** [comment]
Hi @akuporos, I'm using the latest OV master. I'm not building any individual targets (if that's what you mean) but simply doing a `make && make install` before trying to use the module. I see that a `constants.so` is built but not installed. Is that the expected behavior?

**Comment by akuporos** [comment]
Hello @adk9,
We haven't try ```make install``` command, so it could cause  this problem.
Usually after ```make``` we just set ```PYTHONPATH``` and run scripts.
So we need sometime to investigate how can we fix it after ```make install```.

Best regards,
Anastasia

**Comment by ilya-lavrenov** [comment]
@adk9 I've provided a fix, could you please review as well and check whether it solves the issue?

**Comment by adk9** [comment]
Thanks @ilya-lavrenov, LGTM and it fixes the issue I was seeing.
