### ISSUE TITLE
Running  with Intel NCS2 on Android

### ISSUE THREAD

**Issue by meylovede** [openvinotoolkit/openvino#6574]
Hi,

I'm trying to run IE with NCS2 on Android through the Java API.
I built OpenVINO and modules in openvino_contrib, and ran with CPU successfully.

```java
IECore core = new IECore("/data/plugins.xml");
CNNNetwork net = core.ReadNetwork("/data/age-gender-recognition-retail-0013.xml");
ExecutableNetwork executableNetwork = core.LoadNetwork(net, "MYRIAD");
```
when I excute the  `core.LoadNetwork(net, "MYRIAD")` ,some errors occurred.

```
  InferenceEngineException: 
    	LoadNetwork: 
   /openvino/inference-engine/src/inference_engine/ie_common.cpp:73 
    /openvino/inference-engine/src/vpu/common/include/vpu/utils/error.hpp:39 [ GENERAL_ERROR ] 
   /openvino/inference-engine/src/vpu/graph_transformer/src/frontend/remove_const_layers.cpp:24 FrontEnd::removeConstLayers expects CNNNetworkImpl
```
Could someone give me some help?
Thx very much!

**Comment by Iffa-Meah** [comment]
Hi,

did you install the [myriad/vpu plugin](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_MYRIAD.html) in your system environment?

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by abdelmalek0** [comment]
> Hi,
> 
> I'm trying to run IE with NCS2 on Android through the Java API. I built OpenVINO and modules in openvino_contrib, and ran with CPU successfully.
> 
> ```java
> IECore core = new IECore("/data/plugins.xml");
> CNNNetwork net = core.ReadNetwork("/data/age-gender-recognition-retail-0013.xml");
> ExecutableNetwork executableNetwork = core.LoadNetwork(net, "MYRIAD");
> ```
> 
> when I excute the `core.LoadNetwork(net, "MYRIAD")` ,some errors occurred.
> 
> ```
>   InferenceEngineException: 
>     	LoadNetwork: 
>    /openvino/inference-engine/src/inference_engine/ie_common.cpp:73 
>     /openvino/inference-engine/src/vpu/common/include/vpu/utils/error.hpp:39 [ GENERAL_ERROR ] 
>    /openvino/inference-engine/src/vpu/graph_transformer/src/frontend/remove_const_layers.cpp:24 FrontEnd::removeConstLayers expects CNNNetworkImpl
> ```
> 
> Could someone give me some help? Thx very much!

Did you find a solution ? I am facing the same problem in Android

**Comment by abdelmalek0** [comment]
> Hi,
> 
> did you install the [myriad/vpu plugin](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_MYRIAD.html) in your system environment?
> 
> Any chance that you tried to run the myriad/NCS2 with OpenVINO samples app to ensure the device itself works? Please help to see these threads:
> 
> 1. [Can we use an android device to run inference using OpenVINO IE API?](https://github.com/openvinotoolkit/openvino/issues/1620)
> 2. [Running Intel Neural Compute Stick 2 (NCS2) on Android systems](https://github.com/openvinotoolkit/openvino/issues/3516)

Not helpful at all
