### ISSUE TITLE
can't find CXXABI_1.3.11 GLIBCXX_3.4.22 etc

### ISSUE THREAD

**Issue by aboy2018** [openvinotoolkit/openvino#6583]
##### System information (version)

I compile openvino static library on my ubuntu18.04 , and I use it on ubuntu16.04 , have errors
Do you have a issue to solve this wrong with not change ubuntu16.04 environment, Thank you!

![2021-07-09 18-32-42 的屏幕截图](https://user-images.githubusercontent.com/50036961/125065381-52212000-e0e4-11eb-9e40-dad002ac068f.png)

**Comment by ilya-lavrenov** [comment]
OpenVINO does not support static compilation

**Comment by aboy2018** [comment]
> OpenVINO does not support static compilation

Thank you for your reply.
I compile my  static library with using openVINO's shared compilation,It should be OK.
I guess openVINO 2021.3 environment don't match my local environment.

**Comment by aboy2018** [comment]
I think the lastest vision don't work on ubuntu 16.04
