### ISSUE TITLE
Question: openvino support for Nvidia Xavier AGX?

### ISSUE THREAD

**Issue by andife** [openvinotoolkit/openvino#6592]
Hello,
I wonder if anyone has managed to run opencv with openvino on the Jetson Xavier AGX.
The platform doesn't seem to be officially supported? And in case it was successful, how does the performance compare to TensorRT? Thanks a lot!

Andreas

**Comment by Iffa-Meah** [comment]
Hi,

Unfortunately, the NVIDIA Xavier AGX is not listed in the [OpenVINO supported devices](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_Supported_Devices.html).
Hence, it is not officially supported.

As for OpenCV, it is recommended for you to post it on the OpenCV forum/threads.
Regarding OpenVINO performance, [these results](https://docs.openvinotoolkit.org/latest/openvino_docs_performance_benchmarks_openvino.html) might intrigue you.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
