### ISSUE TITLE
TestResnetPart is too big and it can't build success under VS2015

### ISSUE THREAD

**Issue by michaelchien1972** [openvinotoolkit/openvino#66]
dldt/inference-engine/tests/unit/engines/mkldnn/graph/structure/graph_structure_test.cpp

in this function

TEST_F(MKLDNNGraphStructureTests, TestResnetPart) 

The model xml is too big, and it will show compilation error under MS Visual Studio 2015. It said "string is too big, you need to truncate spaces"

Any idea?

**Comment by michaelchien1972** [comment]
Well, after some code pieces that can't compile, and it runs.

**Comment by AnastasiaKazantaeva** [comment]
Close the issue, as no active question here and everything's worked
