### ISSUE TITLE
[Bug] input_shape for a value 

### ISSUE THREAD

**Issue by zhoumenghan** [openvinotoolkit/openvino#6622]
hi, thanks for your openvino toolkit! 
when I use 
`python mo_onnx.py --input_model E:\2D_Animation\first-order-model-tf-main\saved_models_float32\process_kp_driving.onnx --input adapt_movement_scale,kp_driving,kp_driving_initial,kp_driving_initial_jacobian,kp_driving_jacobian,kp_source,kp_source_jacobian,use_relative_jacobian --input_shape (),(1,10,2),(1,10,2),(1,10,2,2),(1,10,2,2),(1,10,2),(1,10,2,2),() --output jacobian,value --output_dir E:\2D_Animation\first-order-model-tf-main\saved_models_float32\onnx`
```
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      E:\2D_Animation\first-order-model-tf-main\saved_models_float32\process_kp_driving.onnx
        - Path for generated IR:        E:\2D_Animation\first-order-model-tf-main\saved_models_float32\onnx
        - IR output name:       process_kp_driving
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         adapt_movement_scale,kp_driving,kp_driving_initial,kp_driving_initial_jacobian,kp_driving_jacobian,kp_source,kp_source_jacobian,use_relative_jacobian
        - Output layers:        jacobian,value
        - Input shapes:         (),(1,10,2),(1,10,2),(1,10,2,2),(1,10,2,2),(1,10,2),(1,10,2,2),()
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
ONNX specific parameters:
        - Inference Engine found in:    C:\Program Files (x86)\Intel\openvino_2021\python\python3.6\openvino
Inference Engine version:       2.1.2021.3.0-2787-60059f2c755-releases/2021/3
Model Optimizer version:            2021.3.0-2787-60059f2c755-releases/2021/3
[ ERROR ]  Input shape "(),(1,10,2),(1,10,2),(1,10,2,2),(1,10,2,2),(1,10,2),(1,10,2,2),()" cannot be parsed.
```

to transfer onnx to openvino, I don't know how to describe the shape of adapt_movement_scale and use_relative_jacobian，which are only a value，e.g. adapt_movement_scale=0.0 use_relative_jacobian=1.0

I need your help. Looking forward to your reply~~~

**Comment by Iffa-Meah** [comment]
Hi,

The input shape format should be --input_shape [1,HEIGHT,WIDTH,3].
For your case it's probably --input_shape [1,10,2,2], the order dimensions depends on the framework input layout of the model.

There's another parameter that you can use for scaling, the --scale "SCALE VALUE".
All input coming from original network inputs will be divided by this value.

You may refer to this [General Conversion Parameters](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html)

**Comment by zhoumenghan** [comment]
@Iffa-Meah Hi，I may not describe my problem clearly. adapt_movement_scale and use_relative_jacobian the two input names in the model，“use_relative_jacobian” is only a value like 1.0 or 0.0，which shape is  (). The shape of all inputs is：

adapt_movement_scale   ()
kp_driving (1,10,2)
kp_driving_initial  (1,10,2)
kp_driving_initial_jacobian (1,10,2,2)
kp_driving_jacobian (1,10,2,2)
kp_source  (1,10,2)
kp_source_jacobian (1,10,2,2)
use_relative_jacobian ()

I need your help. Looking forward to your reply~~~

**Comment by Iffa-Meah** [comment]
can you share your files (models &etc) then? it would help us to clarify the problem

**Comment by zhoumenghan** [comment]
@Iffa-Meah Please provide an email address and I will send you the relevant information.

**Comment by Iffa-Meah** [comment]
@zhoumenghan it would be great if you could attach it here, if possible.

**Comment by Iffa-Meah** [comment]
Hi,
I'm closing this case. If you require any further help feel free to re-open.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
