### ISSUE TITLE
[Bug] MULTI plugin benchmark_app failed for MULTI:GPU

### ISSUE THREAD

**Issue by mashoujiang** [openvinotoolkit/openvino#6633]
### Description:
One simple benchmark_app failed for MULTI:GPU usecase, but MULTI:CPU is ok.

OpenVINO branch: master, commit id: 86e5625db69c111ffd370b12a8c2e63d462eac8b
My GPU is iGPU, CPU is i7-8700K

**BTW, I remember serveral weeks ago, this test is OK, seems GPU plugin changes sth.**

================= log below ====================

hddl@hddl-US-E2:~/msj/openvino/bin/intel64/Release$ ./benchmark_app -d MULTI:GPU -i car.png -m squeezenet1.1.xml -pc -niter 100 -api async
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ] car.png
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
IE version ......... 2022.1.0
Build ........... custom_master_86e5625db69c111ffd370b12a8c2e63d462eac8b
[ INFO ] Device info:
GPU
clDNNPlugin version ......... 2022.1.0
Build ........... custom_master_86e5625db69c111ffd370b12a8c2e63d462eac8b
MULTI
MultiDevicePlugin version ......... 2022.1.0
Build ........... custom_master_86e5625db69c111ffd370b12a8c2e63d462eac8b

[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for GPU device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 4.72 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
Network inputs:
data : U8 / NCHW
Network outputs:
prob : FP32 / NCHW
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 3545.19 ms
[Step 8/11] Setting optimal runtime parameters
[Step 9/11] Creating infer requests and filling input blobs with images
[ INFO ] Network input 'data' precision U8, dimensions (NCHW): 1 3 227 227
[ WARNING ] Some image input files will be duplicated: 4 files are required but only 1 are provided
[ INFO ] Infer Request 0 filling
[ INFO ] Prepare image car.png
[ WARNING ] Image is resized from (787, 259) to (227, 227)
[ INFO ] Infer Request 1 filling
[ INFO ] Prepare image car.png
[ WARNING ] Image is resized from (787, 259) to (227, 227)
[ INFO ] Infer Request 2 filling
[ INFO ] Prepare image car.png
[ WARNING ] Image is resized from (787, 259) to (227, 227)
[ INFO ] Infer Request 3 filling
[ INFO ] Prepare image car.png
[ WARNING ] Image is resized from (787, 259) to (227, 227)
[Step 10/11] Measuring performance (Start inference asynchronously, 4 inference requests using 2 streams for GPU, limits: 100 iterations)
[ INFO ] First inference took 4.59 ms
**[ ERROR ] _Map_base::at**

### Tickets:
 - *CVS-59892*

**Comment by coneypo** [comment]
`benchmark_app.exe -m squeezenet1.1.xml -i cat_1.png -d MULTI:GPU -niter 1` works;

`benchmark_app.exe -m squeezenet1.1.xml -i cat_1.png -d MULTI:GPU -niter 1 -pc ` works;

`benchmark_app.exe -m squeezenet1.1.xml -i cat_1.png -d MULTI:GPU -niter 10 -pc`  failed with

```
[Step 10/11] Measuring performance (Start inference asynchronously, 4 inference requests using 2 streams for GPU, limits: 12 iterations)
[ INFO ] First inference took 13.74 ms
[ ERROR ] invalid unordered_map<K, T> key
```

**Comment by mashoujiang** [comment]
BTW, it is strange that no tests cover this benchmark_app test. maybe we should add this kind of tests to CI.

**Comment by myshevts** [comment]
the test exists, but it checks only single request/inference (which passes with the banehcmark_app as well from what I can see form logs).

**Comment by jgespino** [comment]
Closing, per internal ticket issue has been fixed in master branch.
