### ISSUE TITLE
How to use docker inference my network with ncs2

### ISSUE THREAD

**Issue by aboy2018** [openvinotoolkit/openvino#6639]
##### System information (version)

E: [ncAPI] [    638091] [perception] ncDeviceOpen:1003	Failed to find booted device after boot

My local environment has installed ncs2.
Docker image can't find ncs2 device.What should I do?
Thank you.

**Comment by brmarkus** [comment]
Can you describe your environment, please?
Which Docker container have you used?
If you created a Docker container with your own "Dockerfile" then you might need to consider "https://docs.openvinotoolkit.org/2020.2/_docs_install_guides_installing_openvino_docker_linux.html#use_a_docker_image_for_intel_movidius_neural_compute_stick_and_intel_neural_compute_stick_2".

Have you used a pre-built OpenVINO Docker container, like "docker pull openvino/ubuntu20_dev"? And then see the section:

> If you need Myriad* (NCS2) accelerator only, run image with the following command:
> `docker run -it --device-cgroup-rule='c 189:* rmw' -v /dev/bus/usb:/dev/bus/usb --rm openvino/ubuntu20_dev:latest`
