### ISSUE TITLE
ModuleNotFoundError: No module named 'ngraph.frontend'

### ISSUE THREAD

**Issue by qin53027** [openvinotoolkit/openvino#6670]
Hi,

Yesterday I have cloned the OpenVINO github version. Then I have done the inference engine build and config the model optimizer per https://github.com/openvinotoolkit/openvino/wiki/GettingStarted.

Now I try to do: Convert the model to an Intermediate Representation with the Model Optimizer

python3 /home/jiande/program/openvino/model-optimizer/mo.py --input_model /home/jiande/program/open_model_zoo/public_models/public/squeezenet1.1/squeezenet1.1.caffemodel --data_type FP32 --output_dir ir_dir

I got above ModuleNotFoundError.  Actually the ngraph -> frontend pah is there. 

Can you please give me the suggestions since I am new to openvino?

I am running this command in Virtualbox with Ubuntu 20.04. 

Thanks
Jimmy

**Comment by qin53027** [comment]
Also  I try to Run the Image Classification Sample Application:

./classification_sample_async -i /home/jiande/openvino/scripts/demo/car.png -m  ir_dir/squeezenet1.1.xml -d CPU

Where I can find the squeezenet1.1.xml file in order to run this?

**Comment by brmarkus** [comment]
First you need to download the model, e.g. from the Open-Model-Zoo:

```
source /opt/intel/openvino_2021/bin/setupvars.sh
cd /opt/intel/openvino_2021/deployment_tools/tools/model_downloader/
mkdir /tmp/squeeze
./downloader.py --name squeezenet1.1-caffe2 -o /tmp/squeeze/
```
=> this will download the model and you will get:
```
/tmp/squeeze/public/squeezenet1.1-caffe2/
├── init_net.pb
└── predict_net.pb
```
And then, as this is not in in the OpenVINO IR format, convert it:

`./converter.py -d /tmp/squeeze/ -o /tmp/squeeze/ --name squeezenet1.1-caffe2`

=> this will convert to ONNX first and then to IR format; as a specific precision was not specified in the command-line, it will convert to FP16 and FP32 floating-point precision and you will get:

```
/tmp/squeeze/public/squeezenet1.1-caffe2/
├── FP16
│   ├── squeezenet1.1-caffe2.bin
│   ├── squeezenet1.1-caffe2.mapping
│   └── squeezenet1.1-caffe2.xml
├── FP32
│   ├── squeezenet1.1-caffe2.bin
│   ├── squeezenet1.1-caffe2.mapping
│   └── squeezenet1.1-caffe2.xml
├── init_net.pb
├── predict_net.pb
└── squeezenet1.1-caffe2.onnx
```

Then you can call e.g.:

`./classification_sample_async -i /home/jiande/openvino/scripts/demo/car.png -m /tmp/squeeze/public/squeezenet1.1-caffe2/FP32/squeezenet1.1-caffe2.xml -d CPU`

**Comment by qin53027** [comment]
@brmarkus,  thanks for your quick response. I will try to do this shortly. 
By the way, I have run two OpenVINO Jupyter Notebook examples, they all work which tells me that the Inference Engine build is correct.

**Comment by brmarkus** [comment]
Maybe it is something simple like not having called "source /opt/intel/openvino_2021/bin/setupvars.sh" (or what path you have chosen to install OpenVINO to).

**Comment by qin53027** [comment]
@brmarkus, following your example above, now I can run the classification_sample_async without any problem.  Thanks!

But I still got: ModuleNotFoundError: No module named 'ngraph.frontend' after I run:

python3 /home/jiande/program/openvino/model-optimizer/mo.py --input_model /home/jiande/program/open_model_zoo/public_models/public/squeezenet1.1/squeezenet1.1.caffemodel --data_type FP32 --output_dir ir_dir

For my case, I did git clone from the OpenVINO github, so I did source ./scripts/setupvars/setupvars.sh in my /openvino dir.

[setupvars.sh] WARNING: Can not find OpenVINO Python binaries by path /home/jiande/program/openvino/scripts/python
[setupvars.sh] WARNING: OpenVINO Python environment does not set properly
[setupvars.sh] OpenVINO environment initialized

Since my opencv4.5.3 is in my system, I did not install that while I install the OpenVINO.

Any suggestion to solve the ModuleNotFoundError: No module named 'ngraph.frontend'?

Thanks
Jimmy

**Comment by ilyachur** [comment]
@nosovmik Please take a look

**Comment by nosovmik** [comment]
Hi @qin53027 

If I understand correctly, you're not using latest official release packages but trying to convert models from OpenVINO source code. Could you please share your 'cmake' command that you used?

Some recent changes in latest master now require you to build Inference Engine and nGraph python bindings to use mo.py (PR #5721). These recent changes are not released in latest official release 2021.4, so official documentation may miss this information
On latest master you can try the following 'cmake' command:
```
cd <path_to_openvino>
mkdir build
cd build
cmake -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 -DCMAKE_BUILD_TYPE=Release ..
make -j12
``` 

Alternatively, if you want to use latest official release you can build OpenVINO from latest release branch - releases/2021/4

Best regards,
Michael

**Comment by nosovmik** [comment]
Hi @qin53027 Jimmy,
Also it looks like you've installed some official release of OpenVINO (2021.x), but trying to use latest 'model-optimizer' from 'master' branch which is not compatible.

As per my comment above, in this case I'd suggest you to 'git checkout' your repository to corresponding release branch. E.g. if you've installed 2021.4 release of OpenVINO, then do `git checkout origin releases/2021/4` in your repository

Best regards,
Michael

**Comment by qin53027** [comment]
@nosovmik, thanks for your response. Starting from today, I will have times to focus on the OpenVINO for entire week.

In my Ubuntu 20.04, it has the python3.8 rather python3.6. So I used following command rebuild the openvine. 

But after rebuilt,  I still got the oduleNotFoundError: No module named 'ngraph.frontend'

Please keep in mind that: I did git clone from  https://github.com/openvinotoolkit/openvino  which is one of the method suggested by the OpenVINO user guild. but if the problem can not be solved, then I will need to download the OpenVINO tar ball then.

Could you please give your suggestion?
Have a nice day!
Jimmy


testing command
==============
python3.8 /home/jiande/program/openvino/model-optimizer/mo.py --input_model /home/jiande/program/open_model_zoo/public_models/public/squeezenet1.1/squeezenet1.1.caffemodel --data_type FP32 --output_dir ir_dir


build command
=============
cmake -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3.8 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.8 -DCMAKE_BUILD_TYPE=Release -DNGRAPH_ONNX_IMPORT_ENABLE=ON -DNGRAPH_DEBUG_ENABLE=ON  -D BUILD_opencv_python3=YES -DENABLE_MKL_DNN=ON ..
make -j12

**Comment by nosovmik** [comment]
Hi @qin53027 Jimmy

Thanks a lot for your feedback. Could you try to pull latest updates from openvino/master branch (`git pull origin master`)? I'm asking because today I've pushed one change which should produce more user friendly error messages if there are problems with environment setup.

If the issue will still occur on latest 'master', can you attach full console output of 'testing command'?

Best regards,
Michael

**Comment by qin53027** [comment]
@nosovmik,  this is great!
I have done git pull origin master followed by the cmake ......... +  make. Now the Error is gone. Thanks so much for your help!
----  ------------------------------------ --------------------
[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /home/jiande/program/openvino/ir_dir/squeezenet1.1.xml
[ SUCCESS ] BIN file: /home/jiande/program/openvino/ir_dir/squeezenet1.1.bin
[ SUCCESS ] Total execution time: 3.59 seconds. 
[ SUCCESS ] Memory consumed: 117 MB.

**Comment by nosovmik** [comment]
@qin53027 congratulations! Glad to see that model conversion works for you now!

Best regards,
Michael

**Comment by qin53027** [comment]
close this issue
