### ISSUE TITLE
[Bug]ie_core_read_network_from_memory   CAN NOT  WORK!

### ISSUE THREAD

**Issue by skydestroyer** [openvinotoolkit/openvino#6674]
##### System information (version)
<!-- Example
- OpenVINO => 2020.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

**Comment by zulkifli-halim** [comment]
Hello @skydestroyer.  Can you provide the information on your environment? And more detail on what are you trying to accomplish.

**Comment by skydestroyer** [comment]
**OpenVINO => 2021.1.110
Operating System / Platform => win10_64bit  +  VS2015**

**Firstly, I converted the model file to data array, for example :**   
xxd -i model.bin > model_bin.h
xxd -i model.xml > model_xml.h
Then , I got  two data arrays:   unsigned char model_bin[]    ,  unsinged char model_xml[]

**Secondly, I used the data arrays to init the system:**

		std::vector<uint8_t> xml_vec;
		std::vector<uint8_t> bin_vec;
		for (int i = 0; i < model_xml_len; ++i)
		{
			xml_vec.push_back(model_xml[i]);
		}
		for (int i = 0; i < model_bin_len; ++i)
		{
			bin_vec.push_back(model_bin[i]);
		}
		tensor_desc_t weight_desc{ ANY,{ 1,{ bin_vec.size() } }, U8 };
		ie_blob_t *weight_blob = nullptr;
                ie_blob_make_memory_from_preallocated(&weight_desc, bin_vec.data(), bin_vec.size(), &weight_blob));
		ie_core_read_network_from_memory(pHandle->core, xml_vec.data(), xml_vec.size(), weight_blob, &pHandle->network);
		ie_blob_free(&weight_blob);

**Comment by ilya-lavrenov** [comment]
@skydestroyer what does it mean "cannot work"? You remove weights once the network is read, have you tried to keep them and perform inference?

**Comment by skydestroyer** [comment]
It won't help if you comment "ie_blob_free(&weight_blob);".
Actually, the program broke at the "ie_core_read_network_from_memory"  and  return error code -7.
That's why I said "cannot work".

**Comment by jgespino** [comment]
Hi @skydestroyer 

Would you mind sharing your full code to reproduce from my end? You mentioned using OpenVINO 2021.1, do you see the same behavior on the latest release (2021.4)?

Regards,
Jesus
