### ISSUE TITLE
Test async time, inference network on ncs2,cpu use 20% and  async application

### ISSUE THREAD

**Issue by aboy2018** [openvinotoolkit/openvino#6679]
- OpenVINO => 2020.2
- Operating System / Platform => ubuntu 16.04
- model =>preson-detection-retail-0013.xml
I have three questions.
Q1: How to test infernece async time?
             I test "async_infer_request_curr->Wait(IInferRequest::WaitMode::RESULT_READY)" time，first 100 ms，secend 9ms，third 100ms，fourth 9ms......,
            What's reason is it and 100ms is cpu time or ncs2 time ? how to test async time?
Q2:When I use ncs2 inference my network, cpu take up 20%?
           Is it normal,why take up so much cpu resource？What are the main areas of computing？
Q3:What application on async?
          source code show that use "swap" to  convert next frame to current frame. In other words, I always deal with last frame. When I deal with the real-time video, how can I do?
Thank you!

**Comment by aboy2018** [comment]
Q1 :How -> Why?

**Comment by Iffa-Meah** [comment]
Q1: I think this question lies within your purpose of implementation. Why do you need to know the inference time? Probably you want to test the model's inferencing performance and compare it with others. [This](https://docs.openvinotoolkit.org/latest/openvino_docs_performance_benchmarks_openvino.html) might intrigue you.

Plus the best way to test out a model is actually by using the [benchmark app](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_benchmark_tool_README.html).

Q2: May I know which sample application you had used to infer the person-detection-retail model?. Did you ensure to use -d MYRIAD to [infer using NCS2](https://software.intel.com/content/www/us/en/develop/articles/get-started-with-neural-compute-stick.html?elq_cid=7114794_ts1626712031078&erpm_id=10243649_ts1626712031078)?

Q3: The simplest way to test out an async application is by using the [OpenVINO Image Classification Async sample](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_ie_bridges_python_sample_classification_sample_async_README.html) OR the [Object Detection Demo](https://docs.openvinotoolkit.org/latest/omz_demos_object_detection_demo_python.html). Try to see how these are implemented and apply to your custom code (if you are trying to create your own custom code)

**Comment by aboy2018** [comment]
> Q1: I think this question lies within your purpose of implementation. Why do you need to know the inference time? Probably you want to test the model's inferencing performance and compare it with others. [This](https://docs.openvinotoolkit.org/latest/openvino_docs_performance_benchmarks_openvino.html) might intrigue you.
> 
> Plus the best way to test out a model performance is actually by using the [benchmark app](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_benchmark_tool_README.html).
> 
> Q2: May I know which sample application you had used to infer the person-detection-retail model?. Did you ensure to use -d MYRIAD to [infer using NCS2](https://software.intel.com/content/www/us/en/develop/articles/get-started-with-neural-compute-stick.html?elq_cid=7114794_ts1626712031078&erpm_id=10243649_ts1626712031078)?
> 
> Q3: The simplest way to test out an async application is by using the [OpenVINO Image Classification Async sample](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_ie_bridges_python_sample_classification_sample_async_README.html) OR the [Object Detection Demo](https://docs.openvinotoolkit.org/latest/omz_demos_object_detection_demo_python.html). Try to see how these are implemented and apply to your custom code (if you are trying to create your own custom code)

Thank you very much.I have one question, when I plug ncs2 device, There have be "Failed to find booted device after boot", about it, besides reboot,what better way to do it? Thank you.

**Comment by brmarkus** [comment]
For MyriadX (the NCS2 specifically) have you followed the instructions on "https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#additional-NCS-steps", i.e. setting-up a UDEV-rule?
Do you connect the NeuralComputeStick-v2 to a USB3 capable connection (connected directly or using an externally powered USB3 capable USB-hub)?

**Comment by Iffa-Meah** [comment]
Hi, @aboy2018 did you somehow had a chance tried out @brmarkus  suggestions?

This might help you to properly set up too: 
https://software.intel.com/content/www/us/en/develop/articles/get-started-with-neural-compute-stick.html

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
