### ISSUE TITLE
How to change ngraph function param shape in 2021.4?

### ISSUE THREAD

**Issue by JustasZJ** [openvinotoolkit/openvino#6690]
Hello,

I have been having a problem with the following piece of code:

1. `std::shared_ptr<ngraph::Function> ngraph_func = ngraph::clone_function(*saved_ngraph_func);`
2. `ngraph::ParameterVector paramVec = ngraph_func->get_parameters();`
3. `ngraph::PartialShape shape = paramVec[0]->get_partial_shape();`
4. `shape[2] = height, shape[3] = width;`
5. `paramVec[0]->set_partial_shape(shape);`
6. `CNNNetwork network(ngraph_func);`
7. `InferenceEngine::InputsDataMap inputInfos = network.getInputsInfo();`
8. `InferenceEngine::InputsDataMap::iterator inputInfo = inputInfos.begin();`
9. `InferenceEngine::SizeVector inputDims = inputInfo->second->getInputData()->getTensorDesc().getDims();`

The problem is that `inputDims` is equal to the shape of `saved_ngraph_func`, but not the shape of `ngraph_func`, and I would like it to be equal to the new shape, with new `height` and `width`. How should this be done?

**Comment by Iffa-Meah** [comment]
Hi,
[This documentation](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_ie_bridges_python_sample_ngraph_function_creation_sample_README.html) shows how to execute an inference using nGraph function feature to create a network that uses weights from LeNet classification network, which is known to work well on digit classification tasks, a great guide to start with.

[This contains](https://docs.openvinotoolkit.org/latest/openvino_docs_nGraph_DG_PythonAPI.html) information on how to implement dynamic shapes (partially known shapes).

**Comment by JustasZJ** [comment]
Hello,

Thank you for your answer. 

For the first link: I have seen it and it was a good reference for me to learn how to construct ngraph function, but not so much for reshaping the parameter. For the second one: I didn't really understand the part about dynamic shapes, but I did some more search and tried to instead define the parameter shape with height and width as dynamic dimensions, however it seems that this is not supported with CPU plugin (which I am using) and I get an error.

What I want to accomplish is to create an ngraph function once (`saved_ngraph_func`) and then to use it to create different ngraph functions as copies of it, only differing in the height and width dimensions in the parameter. The way which I described seemed to work for me in 2021.2, but in 2021.4 it does not. How should I change the parameter shape correctly for the ngraph function?

**Comment by Iffa-Meah** [comment]
Probably you could use the concept of numpy array where the value in the matrix(every elements in the numpy array) could be manipulated (divide,multiply,add,etc). You will need to figure out the algorithm tho.

**Comment by JustasZJ** [comment]
@Iffa-Meah
Sorry if I am not explaining well what I am trying to achieve. I am using c++ and I am looking for already existing functionality of changing the shape of the `ngraph::op::Parameter` in the `std::shared_ptr<ngraph::Function>`. Something like `ngraph_func->change_param_input_shape(param_index, new_shape);`. Is there no existing functionality like this already? 

For instance, what if in the LeNet tutorial, after the line `std::shared_ptr<ngraph::Function> fnPtr = std::make_shared<ngraph::Function>(result_full, ngraph::ParameterVector {paramNode}, "lenet");` I would like to change the shape of the parameter, which has shape `{64, 1, 28, 28}` and only then to wrap it into `CNNNetwork`?

**Comment by ilya-lavrenov** [comment]
CC @ilyachur for new methods for `ngraph::Function`

**Comment by ilyachur** [comment]
Hi,

You can use `replace_parameter` method to change the shape of parameter. Something like:
```
...
auto newParam = std::make_shared<::ngraph::op::Parameter>(param->get_element_type(), shape);
newParam->set_friendly_name(param->get_friendly_name());
ngraph_function->replace_parameter(i, newParam);
ngraph_function->validate_nodes_and_infer_types();
...
```

Or also you can use the next approach:
```
auto& pshape = param->get_partial_shape();
// Change shape
pshape = {64, 1, 28, 28}
ngraph_function->validate_nodes_and_infer_types();
```

**Comment by JustasZJ** [comment]
Thank you! Looks like the line
`ngraph_function->validate_nodes_and_infer_types();`
was the key here.
