### ISSUE TITLE
[Bug] [VPU] Section relocation at runtime can cause system instability/performance degradation

### ISSUE THREAD

**Issue by szabi-luxonis** [openvinotoolkit/openvino#6691]
Since myriad FW is closed source, I'm not sure how much can I expose so I will provide minimal details. 

It's related to HW errata `MSS_CNN-B31181`.
Section relocation at runtime can cause system instability/performance degradation. It uses DMA to relocate the section, at every HWOP run, which stalls the system (DDR to DDR transfer, a lot).
This issue is more prominent in `2021.4` due to changes in `HwOp::run`.

Steps to reproduce:
 - Allocate custom memory section for mvTensor's bss section at : `0x8f884b80 - 0x8ff4bb00`
 - Use the following blob: https://drive.google.com/file/d/1jPALNV8Am8VZItk2hLSlOfj7g30iuAbg/view?usp=sharing
The following model was used: https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mobilenet-ssd
Converted to IR format with `converter.py` for FP16, compiled to blob with 6 shaves/slices, `-ip U8` CLI option.

Relocation section size is not calculated properly, extends over mvTensor's bss section, crossing 256MB boundary, triggering the aforementioned issue. System crashes in a matter of seconds, in our case the camera driver.

Not sure if I can share more details, I will if I can do so, we already fixed in our FW, runtime relocation can be avoided.

**Comment by Iffa-Meah** [comment]
Hi,

If possible, can you share/attach here the specific model files that you are having issues with?

**Comment by szabi-luxonis** [comment]
> Hi,
> 
> If possible, can you share/attach here the specific model files that you are having issues with?

I shared in the issue description:

> Use the following blob: https://drive.google.com/file/d/1jPALNV8Am8VZItk2hLSlOfj7g30iuAbg/view?usp=sharing
> The following model was used: https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/mobilenet-ssd
> 

Here are the steps for compiling the VPU blob for 2021.4:
From `open_model_zoo` :
```
git checkout 2021.4
tools/downloader/converter.py --name mobilenet-ssd --precision FP16
```
Convert XML to blob:
```
./compile_tool -d ... -m ... -ip U8 -VPU_NUMBER_OF_SHAVES=6 -VPU_NUMBER_OF_CMX_SLICES=6
```

But this issue is not related to the model, but to how the workaround is done for the mentioned HW errata wrt. 256MB boundaries.

**Comment by jgespino** [comment]
Hi @szabi-luxonis 

Could you please start an Intel Premier Support case for this topic? I see you have an active account, please let me know if you have any issues accessing the platform.

http://premiersupport.intel.com/

Regards,
Jesus

**Comment by szabi-luxonis** [comment]
> Hi @szabi-luxonis
> 
> Could you please start an Intel Premier Support case for this topic? I see you have an active account, please let me know if you have any issues accessing the platform.
> 
> http://premiersupport.intel.com/
> 
> Regards,
> Jesus

Case number: 00632338

Case Number | 00632338
-- | --




Case Number | 00632338
-- | --

**Comment by jgespino** [comment]
Thank you @szabi-luxonis, we will continue the conversation through IPS.
