### ISSUE TITLE
nGraph debug UT failed on Windows

### ISSUE THREAD

**Issue by azhogov** [openvinotoolkit/openvino#670]
Please fix the failed nGraph debug UT on Windows in Azure DevOps CI

2020-05-28T09:14:13.4583483Z [----------] 3 tests from opset
2020-05-28T09:14:13.4583730Z [ RUN      ] opset.check_opset1
2020-05-28T09:14:13.9929195Z ##[error]Cmd.exe exited with code '-1073740791'.
2020-05-28T09:14:14.0261563Z ##[section]Finishing: nGraph UT

See details:
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=602&view=logs&j=4c86bc1b-1091-5192-4404-c74dfaad23e7&t=1e0e7149-0c33-565b-af41-050b54dd61be

**Comment by postrational** [comment]
I believe this issue is resolved:
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=1751&view=logs&j=4c86bc1b-1091-5192-4404-c74dfaad23e7&t=ec99a26b-0264-5e86-36fb-9cfd0ca0f9f3&l=5227

**Comment by jgespino** [comment]
@azhogov Is this issue still actual or can we proceed to close?

**Comment by ilyachur** [comment]
nGraph unit tests enabled for Windows, so I am closing the issue.
