### ISSUE TITLE
RuntimeError: dlSym cannot locate method 'CreateExtension'

### ISSUE THREAD

**Issue by DayDayupupupup** [openvinotoolkit/openvino#6717]
##### System information (version)
- OpenVINO: 2021.4.582
- Image: openvino/ubuntu20_dev: 2021.4
- Operating System / Platform: ubuntu 20.04

##### Detailed description
https://docs.openvinotoolkit.org/2021.4/openvino_docs_HOWTO_Custom_Layers_Guide.html
I follow this document step by step, when i run mri_reconstruction_demo.py , get an error:
```python
python3 mri_reconstruction_demo.py -m wnet_20.xml -i inp.npy -p Data/sampling_mask_20perc.npy -l libtemplate_extension.so -d CPU

Traceback (most recent call last):
  File "mri_reconstruction_demo.py", line 34, in <module>
    ie.add_extension(args.cpu_extension, "CPU")
  File "ie_api.pyx", line 500, in openvino.inference_engine.ie_api.IECore.add_extension
RuntimeError: [ NOT_FOUND ] dlSym cannot locate method 'CreateExtension': libtemplate_extension.so: undefined symbol: CreateExtension
```
So how to solve this problem?

**Comment by ilya-lavrenov** [comment]
@ilyachur could you please backport your fix to releases/2021/4?

**Comment by ilyachur** [comment]
@ilya-lavrenov Do you mean my fix for extension creation method? I am not sure that it can help here. But in any way, I created a draft PR: https://github.com/openvinotoolkit/openvino/pull/6725

**Comment by DayDayupupupup** [comment]
I solved this problem by adding extension.hpp and extension.cpp before compiling the libtemplate_extension.so. Thanks.
