### ISSUE TITLE
[Bug]Could not create an nGraph Constant for an ONNX Constant node. Constant with a 0 value was created instead.

### ISSUE THREAD

**Issue by CHENBIN99** [openvinotoolkit/openvino#6762]
##### System information (version)

- OpenVINO=> 2021.4
- Operating System / Platform => Windows 10 21H1
- Pytorch model: https://github.com/ultralytics/yolov5/releases

##### Detailed description

I wanted to convert this yolov5 model to an IR model supported by OpenVINO, during which I first converted to an ONNX model and then to an IR model. After getting the final IR model, I found that although the model could make predictions properly, the predicted coordinate values obtained were negative, which resulted in not being able to locate the object correctly.
I also tried to let OpenVINO read the ONNX model directly, and during the reading of the model, it showed the following information.

> [WARN] 2021-07-22T13:56:27z frontend\onnx_import\src\op\constant.cpp 35	
Could not create an nGraph Constant for an ONNX Constant node. Constant with a 0 value was created instead.
Verify if the ONNX Constant node contains a correct number of elements matching the node's shape. 
Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@2\b\repos\openvino\ngraph\core\include\ngraph/op/constant.hpp:59:
While validating node 'v0::Constant Constant_2690 () -> (f32{})' with friendly_name 'Constant_2690':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

> [WARN] 2021-07-22T13:56:27z frontend\onnx_import\src\op\constant.cpp 35	
Could not create an nGraph Constant for an ONNX Constant node. Constant with a 0 value was created instead.
Verify if the ONNX Constant node contains a correct number of elements matching the node's shape. 
Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@2\b\repos\openvino\ngraph\core\include\ngraph/op/constant.hpp:59:
While validating node 'v0::Constant Constant_2835 () -> (f32{})' with friendly_name 'Constant_2835':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

I load this ONNX model with
 `ie = IECore()`
 `exec_net = ie.load_network(network=r'xxx.onnx', device_name=args.device)`

I don't know how to get OpenVINO to read yolov5 model correctly, I hope you can help me to solve this problem😥

**Comment by Iffa-Meah** [comment]
Hi,

May I know you are running this model with which OpenVINO sample application? 

If possible can you share your files (native&frozen model & IR)? and also the command that you had used to convert the model to IR.

**Comment by ilyachur** [comment]
@tomdol FYI

**Comment by CHENBIN99** [comment]
> Hi,
> 
> May I know you are running this model with which OpenVINO sample application?
> 
> If possible can you share your files (native/frozen model & IR)? and also the command that you had used to convert the model to IR.

Thank you very much for your attention to my problem!
I used the code from `demo_openvino.py` in the folder `conversion` in the repository https://github.com/dsp6414/yolov5_openvino

My Pytorch weights are `yolov5m.pt` which got from https://github.com/ultralytics/yolov5/releases. Then I convert it to ONNX. Finally, I converted ONNX to OpenVINO format use `mo_onnx.py`

**Comment by CHENBIN99** [comment]
> > Hi,
> > May I know you are running this model with which OpenVINO sample application?
> > If possible can you share your files (native/frozen model & IR)? and also the command that you had used to convert the model to IR.
> 
> Thank you very much for your attention to my problem!
> I used the code from `demo_openvino.py` in the folder `conversion` in the repository https://github.com/dsp6414/yolov5_openvino
> 
> My Pytorch weights are `yolov5m.pt` which got from https://github.com/ultralytics/yolov5/releases. Then I convert it to ONNX. Finally, I converted ONNX to OpenVINO format use `mo_onnx.py`

@Iffa-Meah

**Comment by Iffa-Meah** [comment]
Hi,

I had tested the weight file according to the link that you had provided. However, that doesn't really work for me.

Instead, the scripts from here work even with your weight file: https://github.com/violet17/yolov5_demo

I'm using the latest OpenVINO 2021.4 but for the demo script that is shared in the link, it's recommended for you to use version 2021.3. That demo is based on the official OpenVINO demo.

![weight_onnx](https://user-images.githubusercontent.com/79643476/126937691-6949b3c1-4e79-4978-a617-9ecf33dfd48a.png)
![onnx_IR](https://user-images.githubusercontent.com/79643476/126937708-50ce86e2-ba6a-43b2-8aa1-ccae0251d969.png)

**Comment by CHENBIN99** [comment]
> Hi,
> 
> I had tested the weight file according to the link that you had provided. However, that doesn't really work for me.
> 
> Instead, the scripts from here work even with your weight file: https://github.com/violet17/yolov5_demo
> 
> I'm using the latest OpenVINO 2021.4 but for the demo script that is shared in the link, it's recommended for you to use version 2021.3. That demo is based on the official OpenVINO demo.
> 
> ![weight_onnx](https://user-images.githubusercontent.com/79643476/126937691-6949b3c1-4e79-4978-a617-9ecf33dfd48a.png)
> ![onnx_IR](https://user-images.githubusercontent.com/79643476/126937708-50ce86e2-ba6a-43b2-8aa1-ccae0251d969.png)

@Iffa-Meah I have successfully converted the model to OpenVINO model according to your method, however, the prediction result of this converted model still has the same error that I had initially, that is, the prediction result of the model is negative, which is obviously unreasonable, I hope you can help me to troubleshoot the error.

**Comment by Iffa-Meah** [comment]
@CHENBIN99 did you tried the example from https://github.com/violet17/yolov5_demo? did you get the same result from that demo?
Could you share the snippets of the issue and also the command that you had used to run the inference?

**Comment by CHENBIN99** [comment]
After I followed this demo carefully, I found that it works smoothly. I should have had a problem with the openvino version before.
sorry :(
