### ISSUE TITLE
The lastest vision(2021.3) don't work on ubuntu16.04

### ISSUE THREAD

**Issue by aboy2018** [openvinotoolkit/openvino#6774]

**Comment by brmarkus** [comment]
Currently the latest version is already 2021.4.
Can you describe your environment, your HW first, please?
Did you try to install OpenVINO from source or the pre-built version from software.intel.com?

Which problem did you encounter? Did the installation fail or do you see runtime errors?
Can you provide details about what is not working, please?

**Comment by aboy2018** [comment]
> Currently the latest version is already 2021.4.
> Can you describe your environment, your HW first, please?
> Did you try to install OpenVINO from source or the pre-built version from software.intel.com?
> 
> Which problem did you encounter? Did the installation fail or do you see runtime errors?
> Can you provide details about what is not working, please?

Thank's your reply.I install OpenVINO from software.intel.com(tar -xvzf l_openvino_toolkit_p_2021.3.394 and ./install_GUI.sh).
There have a error. "supported operationg systems for this release are:CentOs*7 Ubuntu*18.04,20.04"
when I choose next，that don't have inference 
![image](https://user-images.githubusercontent.com/50036961/126766594-f81fe018-8edb-415b-b9ed-fb4a6fdc4ba3.png)

**Comment by ilya-lavrenov** [comment]
@aboy2018 yes, we don't provide official packages for U16.04, while you still can build on U16.04 from open source version.
