### ISSUE TITLE
Cannot create Const layer with name

### ISSUE THREAD

**Issue by rajan-blackboxes** [openvinotoolkit/openvino#679]
Hi ,
Running [text-detection-0004](https://docs.openvinotoolkit.org/latest/_models_intel_text_detection_0004_description_text_detection_0004.html)  throws an error as

`RuntimeError: Cannot create Const layer with name: model/block_15_expand_BN/FusedBatchNorm/mean/Fused_Mul_1305813060_const. Layer has incorrect weights!`

This error is only showing on this model and Human pose estimation model,However Vehicle attributes recognition works correctly.

Is there any bug?

**Comment by ilyachur** [comment]
Hi @rajan-blackboxes,

You can get this error message when load network with incorrect *.bin file.
For example when the size of *.bin file is less than requirement size (offset and size parameters for some operation from *.xml file).

Can you please check that *.bin file exists and has a correct size?

**Comment by rajan-blackboxes** [comment]
I have checked, *.bin file exists on same folder. I found size of *.bin file to be 4.2 mb and 8.2 mb for all precision in model Human pose estimation and text detection. 
For vehicle  attribute , they are 1.3 mb, 635 kb, for all precision. 
Please tell , how can i solve this. Thank you .

**Comment by ilyachur** [comment]
@rajan-blackboxes Did you run text-detection-0004 or human pose too?

I checked the text-detection-0004 model and the right sizes are:
FP32/text-detection-0004.bin   17.3 Mb
FP16/text-detection-0004.bin   8.7 Mb

I used [model downloader](https://github.com/opencv/open_model_zoo/tree/master/tools/downloader) to download these models.
These model successfully were loaded and inferred on Inference Engine.

Looks like you have corrupted models. Please recheck.

**Comment by rajan-blackboxes** [comment]
Thanks, It was because of corrupted xml and bin files.
Because of some reason downloader.py downloaded corrupted files after downloading again , it worked.
