### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zzcqinag** [openvinotoolkit/openvino#6793]
1. ie.load_network(network=net, device_name="CPU")
[[[ 2.04408485e-02  5.98185547e-02  4.61589471e-02 -5.48391305e-02
   -2.62762122e-02  6.25304580e-02 -3.51790600e-02  9.24296156e-02
                                     ......
    3.33030336e-02  3.50966007e-02  2.22147955e-03 -1.73084922e-02
    4.46277522e-02  3.18557322e-02  7.11902045e-04  1.37730520e-02]]]

2. ie.load_network(network=net, device_name="HDDL")
{'522': array([[ 0.,  0.,  0., -0., -0.,  0., -0.,  0.,  0., -0., -0.,  0.,  0.,
         0.,  0., -0.,  0.,  0.,  0.,  0.,  0., -0., -0., -0., -0.,  0.,
                                     ......
        -0.,  0.,  0.,  0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,  0.,
        -0., -0.,  0., -0., -0.,  0., -0., -0., -0.,  0.,  0.,  0.,  0.]], dtype=float32)}
how can l solve the problem?thank you

**Comment by zzcqinag** [comment]
>     1. ie.load_network(network=net, device_name="CPU")
>        [[[ 2.04408485e-02  5.98185547e-02  4.61589471e-02 -5.48391305e-02
>        -2.62762122e-02  6.25304580e-02 -3.51790600e-02  9.24296156e-02
>        ......
>        3.33030336e-02  3.50966007e-02  2.22147955e-03 -1.73084922e-02
>        4.46277522e-02  3.18557322e-02  7.11902045e-04  1.37730520e-02]]]
> 
>     2. ie.load_network(network=net, device_name="HDDL")
>        {'522': array([[ 0.,  0.,  0., -0., -0.,  0., -0.,  0.,  0., -0., -0.,  0.,  0.,
>        0.,  0., -0.,  0.,  0.,  0.,  0.,  0., -0., -0., -0., -0.,  0.,
>        ......
>        -0.,  0.,  0.,  0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,  0.,
>        -0., -0.,  0., -0., -0.,  0., -0., -0., -0.,  0.,  0.,  0.,  0.]], dtype=float32)}
>        how can l solve the problem?thank you

**Comment by zzcqinag** [comment]
>     1. ie.load_network(network=net, device_name="CPU")
>        [[[ 2.04408485e-02  5.98185547e-02  4.61589471e-02 -5.48391305e-02
>        -2.62762122e-02  6.25304580e-02 -3.51790600e-02  9.24296156e-02
>        ......
>        3.33030336e-02  3.50966007e-02  2.22147955e-03 -1.73084922e-02
>        4.46277522e-02  3.18557322e-02  7.11902045e-04  1.37730520e-02]]]
> 
>     2. ie.load_network(network=net, device_name="HDDL")
>        {'522': array([[ 0.,  0.,  0., -0., -0.,  0., -0.,  0.,  0., -0., -0.,  0.,  0.,
>        0.,  0., -0.,  0.,  0.,  0.,  0.,  0., -0., -0., -0., -0.,  0.,
>        ......
>        -0.,  0.,  0.,  0.,  0.,  0., -0., -0.,  0.,  0., -0., -0.,  0.,
>        -0., -0.,  0., -0., -0.,  0., -0., -0., -0.,  0.,  0.,  0.,  0.]], dtype=float32)}
>        how can l solve the problem?thank you

**Comment by Iffa-Meah** [comment]
Hi,
I don't really understand your issues here. Could you elaborate more?
Perhaps with these details:
1. openvino version 
2. model & topology, if possible source to that model or share/attach here
3. commands that you had use to convert the model to OpenVINO IR
4. what kind of error that you age / snippets of the error that you are getting

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
