### ISSUE TITLE
How to make sure ncs2 device all work

### ISSUE THREAD

**Issue by aboy2018** [openvinotoolkit/openvino#6798]
I load network with using ncs2 device,.When I plug ncs2 device,that some times work bad.
Except reboot, do you have a way to solve that problem？Which parameters need to be set？

**Comment by zulkifli-halim** [comment]
Hi @aboy2018. Plug in the Neural Compute Stick 2 to a USB port on your computer. Run the following commands for your OS in the terminal:

Linux
`cd ~/intel/openvino/deployment_tools/model_optimizer/install_prerequisites/
./install_prerequisites.sh
cd ~/intel/openvino/deployment_tools/demo
./demo_squeezenet_download_convert_run.sh -d MYRIAD`

Windows 10
`C:
cd C:\"Program Files (x86)"\IntelSWTools\openvino\deployment_tools\demo
.\demo_squeezenet_download_convert_run.bat –d MYRIAD`

**Comment by brmarkus** [comment]
Better to use an USB3 capable USB-port. When using an USB-hub, it might be necessary to use an actively powered USB3 hub.

You can find additional installation steps described also here: https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#additional-NCS-steps

**Comment by aboy2018** [comment]
> Better to use an USB3 capable USB-port. When using an USB-hub, it might be necessary to use an actively powered USB3 hub.
> 
> You can find additional installation steps described also here: https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#additional-NCS-steps

Thanks for your reply.
Can it work on USB2.0 hub?When I only have USB2.0 hub,how can I do? 
What do I need to do?There have be that wrong "NC_ERROR", but when I run "lsusb", that appear '03e7:2485'

**Comment by aboy2018** [comment]
@zulkifli-halim Thanks for your reply.
I compile my code with using openvino's '*.so' library.
    ((${PROJECT_SOURCE_DIR}/lib/libngraph.so
    ${PROJECT_SOURCE_DIR}/lib/libtbb.so.2
    ${PROJECT_SOURCE_DIR}/lib/libinference_engine_legacy.so
    ${PROJECT_SOURCE_DIR}/lib/libinference_engine.so
    ${PROJECT_SOURCE_DIR}/lib/libinference_engine_transformations.so)
when I load model on MYRIAD, there have a wrong
E: [ncAPI] [ 148432] [iee] ncDeviceOpen:1008 Failed to find booted device after boot
How can I do?

**Comment by zulkifli-halim** [comment]
There are two options that you can use, connect NCS 2 directly to USB 3.0 port on computer or use a powered USB 3.0 hub. Can we know which OpenVINO version you are using?

**Comment by zulkifli-halim** [comment]
Close due to no further response.
