### ISSUE TITLE
[Bug] How to get the nAP (mean Accuracy Precision) data for OpenVINO model: person-detection-retail-0002 using the COCO 2017 Dataset Images

### ISSUE THREAD

**Issue by qin53027** [openvinotoolkit/openvino#6831]
Hi,

I want to evaluate the nAP using the OpenVINO model: person-detection-retail-0002.

Can Intel provide some scripts to calculate the nAP value?  Or please provide the suggestion how to achieve that goal?

If there is no scripts or suggested way to get the nAP value.  Here is my thinking for my way which may not be a good one:

1. Get a list of COCO 2017 image files (say 100 images).
2. Then run the OpenVINO inference for 100 times while each time it will have the output.jpg file with the bounding box on the picture
3. then write a scripts to calculate the AP using the original image as the ground truth which will comparing with the output.jpg got from inference. 
4. finally add 100 APs together and then divide by 100 => to get nAP.

Thanks so much for the advise.
Jimmy
 
dataset images in COCO 2017
==========================================================
COCO 2017 Test Images - Humans only https://cocodataset.org/#download

**Comment by Iffa-Meah** [comment]
Hi,

1. You may use the cut dataset script for that purpose
https://github.com/aalborov/cut_dataset/blob/master/cut_dataset.py

**Comment by qin53027** [comment]
@Iffa-Meah, thanks so much for this great information. Let me try the cut_dataset.py first to see.

**Comment by qin53027** [comment]
Hi @Iffa-Meah,

I have run following accuracy_check but I got error.

Here: /home/jiande/coco_kitti has the dataset and annotation dir. (label txt files)

annotations  - unzipped dir
val2017 ---unzipped dir. 
annotations_trainval2017.zip
al2017.zip

Could you please advise how to fix the problem?
Thanks
Jimmy

run command
============
accuracy_check -c /home/jiande/program/open_model_zoo/tools/accuracy_checker/configs/person-detection-retail-0002.yml -m /tmp/model -s /home/jiande/coco_kitti


error message
===========
Processing info:
model: person-detection-retail-0002
launcher: dlsdk
device: 
dataset: person_detection
OpenCV version: 4.5.3
20:07:32 accuracy_checker ERROR: path to converted annotation or data for conversion should be specified
Traceback (most recent call last):
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/main.py", line 414, in main
    evaluator = evaluator_class.from_configs(config_entry)
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/evaluators/model_evaluator.py", line 67, in from_configs
    dataset = Dataset(dataset_config) if not delayed_annotation_loading else None
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/dataset.py", line 68, in __init__
    self.create_data_provider()
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/dataset.py", line 199, in create_data_provider
    annotation, meta = self.load_annotation(self.config)
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/dataset.py", line 153, in load_annotation
    raise ConfigError('path to converted annotation or data for conversion should be specified')
accuracy_checker.config.config_validator.ConfigError: path to converted annotation or data for conversion should be specified

**Comment by Iffa-Meah** [comment]
you need to specify path to annotation file... add the -a (your annotation file path)

**Comment by qin53027** [comment]
@Iffa-Meah, thanks.

Now I added -a for annotation dir. where has several .json files. i.e., instances_val2017.json.
But I still got the same error.



run command
============
acy_check -c /home/jiande/program/open_model_zoo/tools/accuracy_checker/configs/person-detection-retail-0002.yml -m /tmp/model -s /home/jiande/coco_kitti/ -a /home/jiande/coco_kitti/annotations

error message
=============

acy_check -c /home/jiande/program/open_model_zoo/tools/accuracy_checker/configs/person-detection-retail-0002.yml -m /tmp/model -s /home/jiande/coco_kitti/ -a /home/jiande/coco_kitti/annotations/
Processing info:
model: person-detection-retail-0002
launcher: dlsdk
device: 
dataset: person_detection
OpenCV version: 4.5.3
22:07:08 accuracy_checker ERROR: path to converted annotation or data for conversion should be specified
Traceback (most recent call last):
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/main.py", line 414, in main
    evaluator = evaluator_class.from_configs(config_entry)
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/evaluators/model_evaluator.py", line 67, in from_configs
    dataset = Dataset(dataset_config) if not delayed_annotation_loading else None
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/dataset.py", line 68, in __init__
    self.create_data_provider()
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/dataset.py", line 199, in create_data_provider
    annotation, meta = self.load_annotation(self.config)
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/dataset.py", line 153, in load_annotation
    raise ConfigError('path to converted annotation or data for conversion should be specified')
accuracy_checker.config.config_validator.ConfigError: path to converted annotation or data for conversion should be specified

**Comment by Iffa-Meah** [comment]
try to specifically add the json file  -a /home/jiande/coco_kitti/annotations/instance_val2017.json

**Comment by qin53027** [comment]
Now I got
raise NotADirectoryError('{}: {}'.format(os.strerror(errno.ENOTDIR), path))
NotADirectoryError: Not a directory: /home/jiande/coco_kitti/annotations/instances_val2017.json

**Comment by qin53027** [comment]
Can you please let me know how to attached a zip file in this issue?

**Comment by qin53027** [comment]
Now I extract the person class and generated lables directory where it has all the .txt lables files. but I still got the same error:

Please advise. Thanks

command
===========
acy_check -c /home/jiande/program/open_model_zoo/tools/accuracy_checker/configs/person-detection-retail-0002.yml -m /tmp/model -s /home/jiande/coco_kitti/ -a /home/jiande/coco_kitti/labels/


error
=============
cy_check -c /home/jiande/program/open_model_zoo/tools/accuracy_checker/configs/person-detection-retail-0002.yml -m /tmp/model -s /home/jiande/coco_kitti/ -a /home/jiande/coco_kitti/labels/
Processing info:
model: person-detection-retail-0002
launcher: dlsdk
device: 
dataset: person_detection
OpenCV version: 4.5.3
23:35:36 accuracy_checker ERROR: path to converted annotation or data for conversion should be specified
Traceback (most recent call last):
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/main.py", line 414, in main
    evaluator = evaluator_class.from_configs(config_entry)
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/evaluators/model_evaluator.py", line 67, in from_configs
    dataset = Dataset(dataset_config) if not delayed_annotation_loading else None
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/dataset.py", line 68, in __init__
    self.create_data_provider()
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/dataset.py", line 199, in create_data_provider
    annotation, meta = self.load_annotation(self.config)
  File "/home/jiande/.local/lib/python3.8/site-packages/accuracy_checker/dataset.py", line 153, in load_annotation
    raise ConfigError('path to converted annotation or data for conversion should be specified')
accuracy_checker.config.config_validator.ConfigError: path to converted annotation or data for conversion should be specified

**Comment by Iffa-Meah** [comment]
Try to use & modify my yml file below.

Run:
accuracy_check -m C:\Users\A221LPEN\Desktop\person_detection\ -c C:\Users\A221LPEN\Desktop\person_detection\person-detection-retail-0002.yml

[person-detection-retail-0002.zip](https://github.com/openvinotoolkit/openvino/files/6905715/person-detection-retail-0002.zip)

**Comment by qin53027** [comment]
Hi @Iffa-Meah,

I really appreciate your good support. After I used your .yml file, I made only datasets section path change:

    datasets:
      - name: person_detection
        data_source: /home/jiande/coco_kitti/val2017
        annotation_conversion:
          converter: mscoco_detection
          annotation_file: /home/jiande/coco_kitti/annotations/instances_val2017.json

Now I have run on my Ubuntun 20.04:
accuracy_check -m /tmp/model/intel/person-detection-retail-0002/FP32 -c /home/jiande/coco_kitti/person-detection-retail-0002.yml   ====> It works!!!!

Since  the result is not great,  could you please check for .yml file?

Also I try to attached my val2017/annotations tar ball file, but I am never successful on that.  Can you let me know how to 
attache the file?    Or if you do not mind, can you give me your e-mail address so that I can set that to you?

Please note that I extract the only Person images from val2017 and used the instances_val2017.json


Thanks
Jimmy


result screen
=====================
IE version: 2021.4.0-3839-cd81789d294-releases/2021/4
Loaded CPU plugin version:
    CPU - MKLDNNPlugin: 2.1.2021.4.0-3839-cd81789d294-releases/2021/4
Found model /tmp/model/intel/person-detection-retail-0002/FP32/person-detection-retail-0002.xml
Found weights /tmp/model/intel/person-detection-retail-0002/FP32/person-detection-retail-0002.bin
Input info:
	Layer name: data
	precision: FP32
	shape [1, 3, 544, 992]

	Layer name: im_info
	precision: FP32
	shape [1, 6]

Output info
	Layer name: detection_out
	precision: FP32
	shape: [1, 1, 200, 7]

5000 objects processed in 753.631 seconds                                      
map: 0.01%

**Comment by qin53027** [comment]
Also I need to evaluate two more OpenVINO models:  person-detection-retail-0013 and person-detection-0106

I used person-detection-retail-0002.yml and changed name only for above models. But after I have run, I got following error:

raise ConfigError('network does not contain input "{}"'.format(name))
accuracy_checker.config.config_validator.ConfigError: network does not contain input "im_info"

I think that person-detection-retail-0013.yml and person-detection-0106.yml needs more spec. items.

If you can provide me the  person-detection-retail-0013.yml and person-detection-0106.yml files,  that will be the great help!

Have a nice day!
JImmy

**Comment by qin53027** [comment]
Hi @Iffa-Meah,

One main reason why the mAP is 0.01% may be related the use of the instances_val2017.json which has all classes of the images.

I do have the label director which has only Person class and images associated with the label text files.

If accuracy_check run can take the .txt files with the -a /lables option, then I think that the AP value will be much high.

This is my two cents
Jimmy

**Comment by qin53027** [comment]
Now  I can find correct .yml files to run all evaluation. I am closing this issue first and will open a new issue for the low AP value. 

Thanks for good help!
