### ISSUE TITLE
exec_net.infer batch of images

### ISSUE THREAD

**Issue by TonyRaven** [openvinotoolkit/openvino#6855]
Hi
Is it possible, 
for example here https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/001-hello-world/001-hello-world.ipynb,
send to exec_net.infer batch of images OR i should convert my net to new format suitable with desired batch size?
Thank you

**Comment by zulkifli-halim** [comment]
Hi @TonyRaven, can you explain in more detail what you wanted to do?

**Comment by TonyRaven** [comment]
@zulkifli-halim Sure
For example, i want get embedding for two pictures
Instead of doing this
```
result1= exec_net.infer(inputs={input_key: input_image1})[output_key]
result2 = exec_net.infer(inputs={input_key: input_image2})[output_key]
```
I want something like this
`result_both = exec_net.infer(inputs={input_key: [input_image1, input_image2]})[output_key]`
And result_both should contain embeddings for both images: input_image1, input_image2

**Comment by zulkifli-halim** [comment]
We suggest you look through [Using Dynamic Batching](https://docs.openvinotoolkit.org/2021.4/openvino_docs_IE_DG_DynamicBatching.html) article in OpenVINO online documentation for more details.
