### ISSUE TITLE
About setupvars.bat

### ISSUE THREAD

**Issue by NeekHua** [openvinotoolkit/openvino#6865]
I have one problem.
whether I must run <INSTALL_DIR>\bin\setupvars.bat init environment?
Can I add the path generated from this  file to the environment variable?
Thanks your watch.
Look forward to your reply

**Comment by jgespino** [comment]
Hi @NeekHua 

Yes, you will need to run setupvars.bat script included in the Intel Distribution of OpenVINO toolkit every time you open a command line. Alternatively, you could set your variables permanently so you don't have to run the script every time. 

Take a look at the [Permanently Set OpenVINO™ Environment Variables for Windows® 10](https://www.intel.com/content/www/us/en/support/articles/000033440/boards-and-kits/neural-compute-sticks.html) for guidance. Just note that the article was recently updated to work with the latest release. I'm adding the instructiosn below as the website has not been updated with the latest revision.

You can manually set OpenVINO™ Environment Variables permanently in Windows® 10. On your Windows® 10 system, go to Control Panel > System and Security > System > Advanced System Settings > Environment Variables. Under System Variables, Add the following as New variables with their corresponding Value as shown below:
<html>
<body>


Variable Name | Variable Value | Notes
-- | -- | --
INTEL_OPENVINO_DIR | C:\Program Files (x86)\Intel\openvino_2021.4.582 | Path to your OpenVINO™ toolkit installation
GNA_DIR | %INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\gna\lib |  
INTEL_CVSDK_DIR | %INTEL_OPENVINO_DIR% |  
ngraph_DIR | %INTEL_OPENVINO_DIR%\deployment_tools\ngraph\cmake |  
OpenCV_DIR | %INTEL_OPENVINO_DIR%\opencv\cmake |  
OPENMP_DIR | %INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\omp\lib |  
OPENVINO_LIB_PATHS | %INTEL_OPENVINO_DIR%\deployment_tools\ngraph\lib%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\tbb\bin%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\bin\intel64\Release%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\bin\intel64\Debug%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\hddl\bin%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\omp\lib%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\gna\lib | Entries to OPENVINO_LIB_PATHS
InferenceEngine_DIR | %INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\share |  
HDDL_INSTALL_DIR | %INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\hddl |  
PYTHONPATH | %INTEL_OPENVINO_DIR%\deployment_tools\tools\post_training_optimization_toolkit%INTEL_OPENVINO_DIR%\deployment_tools\open_model_zoo\tools\accuracy_checker%INTEL_OPENVINO_DIR%\python\python3.8%INTEL_OPENVINO_DIR%\python\python3%INTEL_OPENVINO_DIR%\deployment_tools\model_optimizer | Check your Python* version and Adjust entries
ROOT | %INTEL_OPENVINO_DIR% |  
SCRIPT_NAME | setupvars.bat |  
TBB_DIR | %INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\tbb\cmake |  


</body>
</html>

You will also need to edit the Path variable under System Variables and Add the following entries:
<html>
<body>


%INTEL_OPENVINO_DIR%\deployment_tools\ngraph\lib
--|
%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\tbb\bin
%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\bin\intel64\Release
%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\bin\intel64\Debug
%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\hddl\bin
%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\omp\lib
%INTEL_OPENVINO_DIR%\deployment_tools\inference_engine\external\gna\lib
%INTEL_OPENVINO_DIR%\deployment_tools\model_optimizer
%INTEL_OPENVINO_DIR%\opencv\bin


</body>
</html>

Hope this helps!

Regards,
Jesus

**Comment by NeekHua** [comment]
@jgespino thank you for your help.
My version have openvino_2021.2.185 and openvino_2021.4.582 .But didn't even see deployment_tools\inference_engine\external\omp\lib and deployment_tools\inference_engine\external\gna\lib.
In external fold only have hddl,MovidiusDriver,myriad,tbb.What should I do? don't add GNA_DIR and OPENMP_DIR.
I hope you'll forgive me if this is a naive question.

**Comment by jgespino** [comment]
Hi @NeekHua 

I tested the steps above on my system and I also don't have those paths. Please disregard GNA_DIR and OPENMP_DIR, we will update the instructions. 

Aside from those two, is everything else working for you?

Regards,
Jesus

**Comment by NeekHua** [comment]
@jgespino  I add above variable path and run  
C:\Program Files (x86)\Intel\openvino_2021.2.185\inference_engine\samples\python\classification_sample_async\classification_sample_async.py 
It didn't work.
![image](https://user-images.githubusercontent.com/32665609/127942740-5e9dc541-078d-422b-a05a-ce975f074f19.png)

My version is openvino_2021.2.185.And I will test openvino_2021.4.582 .Look whether work.

**Comment by NeekHua** [comment]
hello @jgespino 
I run cmdline :conda install openvino-ie4py -c intel.
It's work.If I don't install this package.Still need run  <INSTALL_DIR>\bin\setupvars.bat init environment to work,
why is this ?whether because the environment variables are not configured?

**Comment by jgespino** [comment]
Hi @NeekHua 

What installation method are you using? The instructions on the above are assuming you are installing OpenVINO using the web/local package. Additional steps may be required with the other installation methods. 

Regards,
Jesus

**Comment by NeekHua** [comment]
Hi @jgespino  I‘m use web/local package.And auto install C:\Program Files (x86)\Intel\openvino\
