### ISSUE TITLE
[Bug]Use Different Dataset for OpenVINO Models

### ISSUE THREAD

**Issue by qin53027** [openvinotoolkit/openvino#6891]
Hi,

Currently I am using Intel OpenVINO models to do the accuracy analysis:

Person-Detection-Retail-0002
Person-Detection-Retail-0013
Person-Detection-0106

Could you please let me know what dataSet Intel used for train above models?

I will do the accuracy analysis on :  COCO 2017 and CroudHuman dataset.

Thanks
Jimmy

**Comment by zulkifli-halim** [comment]
Hello @qin53027. This is an Intel pre-trained model, such information is not available.

**Comment by qin53027** [comment]
close this issue
