### ISSUE TITLE
Headless installer for Windows

### ISSUE THREAD

**Issue by jbrownkramer** [openvinotoolkit/openvino#6952]
I want an easy command-line installation of OpenVINO on Windows with a copy of opencv built against OpenVINO.  The use case is that we have a production system that accesses OpenVINO through opencv that runs on Windows.  Installing on hundreds of edge machines is just a real pain.  Ideal would be an option to download an installer without requiring a username/password, and a command line tool to do the install, so that this could all be encapsulated in a Dockerfile or at least a powershell script.

**Comment by ilya-lavrenov** [comment]
Hi @jbrownkramer 
You can download official OpenVINO IRC package which have OpenCV built against Inference Engine.
After installing you can pack this into a zip archive and use for deployment. Will it work?

CC @artanokhov

**Comment by alalek** [comment]
Perhaps you are looking for "OpenVINO™ Deployment Manager": https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_deployment_manager_tool.html

**Comment by jbrownkramer** [comment]
What we're doing is using the deployment manager to create a zip of the openvino dependencies we need, and then hosting the zip file on Azure to deploy to machines that need it.  This is workable, it's just very high touch.  When a new version of openvino comes out, I have to log in to intel, download the latest version, manually walk through the install process, manually walk through the deployment manager, manually upload to azure, change configuration file to point to the new Azure link, etc.

In contrast, if I want the latest version of, say, numpy, I just add it to a requirements file.

The python api for the openvino inference engine can be installed with `pip install openvino`.  Why not `pip install opencv-openvino` to get the opencv build as well?

**Comment by jgespino** [comment]
@jbrownkramer Thanks for your feedback, I have submitted a feature request for the development team to consider.

Ref. 65418

**Comment by jgespino** [comment]
@jbrownkramer OpenVINO is now downloadable without registration and can be installed in silent mode. Please take a look and see if it this meets your project needs.

https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html

`start /WAIT w_openvino_toolkit_p_2022.1.0.643_offline.exe -s -a --silent --eula accept`
