### ISSUE TITLE
[Bug]  Outputs get mixed up when using multiple InferRequests with GPU plugin

### ISSUE THREAD

**Issue by ts-accessio** [openvinotoolkit/openvino#6963]
##### System information (version)
- OpenVINO=> 2021.2 and 2021.4
- Operating System / Platform => Ubuntu 20.04 and Docker running on Ubuntu 20.04
- Problem classification => race condition in GPU plugin
- Hardware: NUC8-i3

##### Detailed description
When executing multiple InferRequests simultaneously on a network on the GPU, the outputs get mixed up sometimes. This means the output of the network does not match to the input (e.g. we get the output from another image) and also the outputs do not match together (e.g. output1 is from image 3 and output2 is from image 2).

##### Steps to reproduce
[bug.zip](https://github.com/openvinotoolkit/openvino/files/6946201/bug.zip)
Here you can find the code reproducing the problem (bug.cpp) together with a test model, a cmake file and also an executable file.

What the Code does:
1. Create a network with multiple InferRequests, where each InferRequest has the callback set to the same function
2. Create 13 different inputs
3. Start an inference whenever an InferRequest is available
4. In the callback, compare the results with the result of the first inference for the image. If the results do not match, print to which inputs the results would match.

Output explained:
`wrong i: 4, b:5, c:6, r:5`
means, input is from image 4, output "b" is from image 5, output "c" is from image 6, output "r" is from image 5

This is the problem, we get outputs for another input and even the outputs are mixed up. The problem did not occur with a single InferRequest and also did not occur in CPU mode. It seems to be a race condition as mixed up outputs are rare and occur mostly when InferRequests are executed rapidly.

How to reproduce the test:
Run in docker with:
`docker run -it --device /dev/dri:/dev/dri -u root -v /tmp/bug/:/bug --rm openvino/ubuntu20_data_dev:latest`
Start test application with:
`/bug/build/bug`

**Comment by ts-accessio** [comment]
The problem still exists when we don't use the callback but process the output after the InferRequest finished and before we fill the new input.

**Comment by Iffa-Meah** [comment]
Hi,

First and foremost, may I know which model and topology are you using? and which version of OpenVINO are you using?

Please note that OpenVINO only supports certain types of model topologies.
You may refer here: https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html

Besides, if you are trying to create a custom application and applies it to OpenVINO environment, it is recommended for you to refer to its official sample application and see their requirements and apply it to yours: 
https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Samples_Overview.html

Before we could jump to conclusion that these problems have something to do with OpenVINO GPU plugin, your custom code needs to be validated first. If you are building it from scratch without following the OpenVINO guide/samples there are too many other possibilities that could cause this inconsistency

**Comment by Iffa-Meah** [comment]
Plus, if you are trying to achieve infer request execution in parallel, You will need to consider using the [Multi-Device Plugin](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_MULTI.html).

With this plugin, you don't need to explicitly load the network to every device, create and balance the inference requests and so on. 

Meanwhile, if you want to enable computing for inference on one network on several devices, you will need to use [Heterogeneous Plugin](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_HETERO.html)

The main purposes to implement this are to Utilize the power of accelerators to calculate the heaviest parts of the network and execute unsupported layers on fallback devices like the CPU and Utilize all available hardware more efficiently during one inference

**Comment by ts-accessio** [comment]
The test code can be found in the attached [bug.zip](https://github.com/openvinotoolkit/openvino/files/6946201/bug.zip), it's in bug.cpp. It's very similar to the samples with additional code to compare the data in the input and output blobs.

Multiple models were tested, the problem was found to be more frequent for smaller, faster executing models. The [bug.zip](https://github.com/openvinotoolkit/openvino/files/6946201/bug.zip) contains such a model (bug.xml / bug.bin), which does some Pooling and Convolutions and was converted from pytorch via ONNX.

The sample was executed first on the host system (Ubuntu 20.04) with OpenVino 2021.2 and then within the (I think official) Docker container ([https://hub.docker.com/r/openvino/ubuntu20_data_dev](https://hub.docker.com/r/openvino/ubuntu20_data_dev)) with OpenVino 2021.4. Both showed the same problem.

We are using an Intel NUC8-i3 for our software and use OpenVino to execute the Neural Networks on the internal GPU. We use multiple InferRequests to increase the throughput as it's done in the benchmark_app sample.

**Comment by Iffa-Meah** [comment]
@ts-accessio yes I'm aware that your samples code is in the zip file but where did you refer this code to (its source)?
For instance [Hello Classificaton C++ sample](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_samples_hello_classification_README.html) which is the OpenVINO Official Sample Application.

**Comment by vladimir-paramuzov** [comment]
@ts-accessio Could you check with latest master? I think PR #6922 could fix your issue.

**Comment by ts-accessio** [comment]
Thanks, we could not reproduce the problem with the latest master, so PR #6922 seems to fix the problem.

**Comment by ts-accessio** [comment]
We want to have the fix from the pull request in our live software however it's really difficult to integrate the fix into an old release (e.g. 2021.4), e.g. because of the introduction of IE_THROW. So the question is how stable the master branch is. Is it a good idea to use the latest master branch in a production system or is the stability and testing much worse than for the official releases?
