### ISSUE TITLE
[Bug]Please Advise how to use the Accuracy-Check to Get the Average Precision Data

### ISSUE THREAD

**Issue by qin53027** [openvinotoolkit/openvino#6995]
Hi,

Currently I am using the following OpenVINO models to get the  AP data. 

       Person-Detection-Retail-00002 /  Person-Detection-Retail-00013 / Person-Detection-0106.

Within three models I have used, I have found that 0106 model is the best based on the accuracy calculation scripts I used.

Now I need to use Intel Accuracy-Check to get the AP. But I can never get a good data. Hope you can help me on this!

                            Dataset Name:                  COCO 2017                   CrowdHuman                    My Own Dataset
-----------------------------------------------------------------------------------------------------------------------------------------------------
Person-Detection-Retail-00002                            AP?                                 AP?                                  AP?
Person-Detection-Retail-00013                            AP?                                 AP?                                  AP?
Person-Detection-0106.                                        AP?                                 AP?                                  AP?

Here is the dataset annotation format:

Dataset Name:                  COCO 2017                   CrowdHuman                    My Own Dataset
=========================================================================
                                            KITTI TXT                            .odgt                              KITTI TXT
   

Can you please let me know if Accuracy-Check can handle above annotation format since I have the big problem to get the accuracy check to run?

Thanks a lot
Jimmy

**Comment by Iffa-Meah** [comment]
Hi,

to use this dataset (COCO) with OMZ tools, you need these files:

val2017 - directory containing the COCO 2017 validation images
instances_val2017.json - annotation file which used for object detection and instance segmentation tasks
person_keypoints_val2017.json - annotation file which used for human pose estimation tasks

This means you'll need the [annotation in json format](https://docs.openvinotoolkit.org/latest/omz_data_datasets.html#common_objects_in_context_coco).

**Comment by Iffa-Meah** [comment]
Unfortunately, OpenVINO does not has the capability to convert annotation file from another format to json and most of our validation are based on .json file.

Instead, you could [convert your .odgt file into .json](https://gist.github.com/Mycenae/d29f5402dd5f8be76d45e1909d5aa4e3)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
