### ISSUE TITLE
undefined reference to `InferenceEngine::Core::Core during build

### ISSUE THREAD

**Issue by Litchilitchy** [openvinotoolkit/openvino#7018]
Hi I am trying to use OpenVINO InferenceEngine, I just write a simple line of code 

* OpenVINO version: 2021.4 (tried both pre-built and build from source, same error)
* OS: Ubuntu 20.04
* g++: 9.3.0
```
#include "inference_engine.hpp"
#include <string>
using namespace InferenceEngine;

int main() {
    Core ie;    
    return 0;
}
```
The build command (using pre-built version of OpenVINO) is 
```
/usr/bin/g++  -I/home/litchy/pro/open-source/openvino/inference-engine/include -L/opt/intel/openvino_2021.4.582/inference_engine/lib/intel64 -linference_engine -linference_engine_legacy -g /home/litchy/pro/intel/analytics-zoo-core/openvino/openvino-java-linux/src/main/cpp/OpenVINO_test.cpp -o /home/litchy/pro/intel/analytics-zoo-core/.vscode/OpenVINO_test
```
And I checked the `libinference_engine.so` with `nm` and `string` the `Core` is in it.

**Comment by brmarkus** [comment]
Can you provide more information about your environment, please? Like which OperatingSystem in which version? Which version of the built-tools (make, cmake, gcc) are you using, have you replaced the build tools from your OS-distribution (e.g. using newer or older version)?
Which OpenVINO version do you use, have you built it from source or installed the pre-built version?
Do you use Debug- or Release-libraries?

Can you try adding your code under the inference-engine samples or the open-model-zoo demos of the OpenVINO installation? That would allow you to use the make/cmake files of the samples&demos to find all needed libraries.

In my case - having the pre-built OpenVINO in version 2021.4 installed under Ubuntu 20.04-LTS, using make/cmake/build-essential packages - the inference-engine shared object can be found under `/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/libinference_engine.so`.

**Comment by Litchilitchy** [comment]
Thanks @brmarkus , I add some env info above, and I would try some inference-engine samples.

**Comment by Litchilitchy** [comment]
@brmarkus I could successfully build the samples and has your above output dependencies. Seems it is not a environment issue.

However actually I am trying to develop in VSCode, and I want to build my own application for debug. So the way I build my app should be `cmake`? the default build cmd `g++` would not work?

**Comment by Litchilitchy** [comment]
> The "main" CMakeLists.txt under "/opt/intel/openvino_2021/deployment_tools/inference_engine/samples/cpp/" sets C++11 as well (which you removed in your original description?):

I tried both with `c++11` and without, the outputs are the same.

**Comment by brmarkus** [comment]
> @brmarkus I could successfully build the samples and has your above output dependencies. Seems it is not a environment issue.
> 
> However actually I am trying to develop in VSCode, and I want to build my own application for debug. So the way I build my app should be `cmake`? the default build cmd `g++` would not work?

When building manually you usually need to do:

$> source /opt/intel/openvino_2021/bin/setupvars.sh
=> this will set a lot of ENV variables, like LD_LIBRARY_PATH for the library-search-path, where to find thirdparty, where to find OpenCV, and so on

$> mkdir mybuild && cd mybuild
$> cmake -DCMAKE_BUILD_TYPE=Release /opt/intel/openvino_2021/deployment_tools/inference_engine/samples/cpp/
=> this will check the environment, searching for installed compiler, linker, checking for thirdparties, checking to find source-code-header-files, platform features, etc. and will generate make-files

$> make
=> this will build the code, using the found compiler and linker, library search paths etc

When you want to use your favorite IDE then you would likely need to set the ENV variables manually (or import the ENV variables from your environment), setting search-paths etc ; some IDEs support CMAKE-based projects (i.e. the IDE would parse the cmake/make files to generate a project-file with all settings)...

**Comment by Litchilitchy** [comment]
@brmarkus ok, basically there are many environments to prepare. My previous thought was too simple.. I thought just by providing `.so` and `.h` it would work. I would try some further configs are feedback..
