### ISSUE TITLE
Converting a custom ssd-mobilenet model from pytorch

### ISSUE THREAD

**Issue by WingRS** [openvinotoolkit/openvino#7030]
Hi all, I am trying to use a model  based on ssd-lite with mobilenetv2 as feature extractor. The implementation of the model is here github.com/qfgaohao/pytorch-ssd. After training for 10 classes, I've managed to successfully to convert it to ONNX and then after to IR format. 
After loading it to CPU/GPU (working on Intel NUC) I am struggling to understand with the output format. I've used the person-detection-retail before and made some snippets of code for it, and the output usually is  [1, 1, N, 7] , so the code for configuring the output was like this:

``` 
  InferenceEngine::CNNNetwork network;
  network = ie.ReadNetwork(_model_xml);
 InferenceEngine::DataPtr output_info = network.getOutputsInfo().begin()->second;
  output_name_ = network.getOutputsInfo().begin()->first;
  output_info->setPrecision(InferenceEngine::Precision::FP32);
  auto output_dims = output_info->getTensorDesc().getDims();
  int max_proposal_count = output_dims[2];
  int object_size = output_dims[3];
```
And the object size was exactly 7, in my case I get some really large numbers and each time it's different (97537,23585).
Maybe you could give me an insight on whats going on?
The conversion happened to be successful from the logs:
```
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /test_converter/mb2-ssd-lite/model-ssd-lite.onnx
        - Path for generated IR:        /test_converter/mb2-ssd-lite/.
        - IR output name:       model-ssd-lite
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
ONNX specific parameters:
Model Optimizer version:        2021.2.0-1877-176bdf51370-releases/2021/2
2021-08-11 15:38:08.078806: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/mrs/workspace/devel/lib:/home/mrs/mrs_workspace/devel/lib:/opt/ros/noetic/lib:/opt/intel/openvino_2021/data_processing/dl_streamer/lib:/opt/intel/openvino_2021/data_processing/gstreamer/lib:/opt/intel/openvino_2021/opencv/lib:/opt/intel/openvino_2021/deployment_tools/ngraph/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/home/mrs/mrs_workspace/install/lib/mavlink_sitl_gazebo/plugins:/home/mrs/mrs_workspace/install/lib/mavlink_sitl_gazebo/plugins:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/home/mrs/mrs_workspace/install/lib/mavlink_sitl_gazebo/plugins:/home/mrs/mrs_workspace/install/lib/mavlink_sitl_gazebo/plugins
2021-08-11 15:38:08.078843: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /test_converter/mb2-ssd-lite/./model-ssd-lite.xml
[ SUCCESS ] BIN file: /test_converter/mb2-ssd-lite/./model-ssd-lite.bin
[ SUCCESS ] Total execution time: 21.11 seconds.
[ SUCCESS ] Memory consumed: 359 MB.


```
The resulting XML file is copied [on pastebin](https://pastebin.com/Qg4STici)

**Comment by Iffa-Meah** [comment]
Hi,

Please take note that the output format changes after OpenVINO Model Optimizer conversion. To find a detailed explanation of changes, [go to Model Optimizer development guide](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html).

It is recommended for you to use the OpenVINO Officially supported [ssd_mobilenet_v2](https://docs.openvinotoolkit.org/latest/omz_models_model_ssd_mobilenet_v2_coco.html) 

As you can see in the output section, the detection boxes coordinates format for ssd mobilenetv2 is not bound to be 1,1,N,7 as in [person detection retail model](https://docs.openvinotoolkit.org/latest/omz_models_model_person_detection_retail_0013.html).

Please help to try out the officially supported model instead and see the result.

**Comment by WingRS** [comment]
Thanks for your response, though the model is presented on the documentation website, it seems not to be presented in some of the frameworks that can retrain it. Or I have missed it somewhere? If it is available, I'd try to retrain it and run.

**Comment by Iffa-Meah** [comment]
Generally, you can view the type of models and their topology which validated to work with OpenVINO [here](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model.html).

You may use the [OpenVINO training extension](https://github.com/openvinotoolkit/training_extensions) to train Deep Learning models

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
