### ISSUE TITLE
caffe-intel conversion

### ISSUE THREAD

**Issue by Riko0** [openvinotoolkit/openvino#708]
I have a problem with caffe-intel neural network convertation

First of all it's not readable by model-optimizer, it says 
snapshot_iter_17000.caffemodel does not have a valid structure
[ FRAMEWORK ERROR ]  Tag had invalid wire type.

Secondly if i convert this to bvlc-caffe using these scripts (https://github.com/ftian1/intelcaffe_weight_to_bvlc), i am able to use this network, but when i am converting it to openvino format, it have no detections at all(mobilenetv2 ssd net)

**Comment by ilya-lavrenov** [comment]
@lazarevevgeny could you please advice?

**Comment by lazarevevgeny** [comment]
@Riko0 , have you tried to generate a new parser for Caffe following [instructions](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html)?

**Comment by Riko0** [comment]
@lazarevevgeny, tried just now, converted succesfully, but results are not valid, same detections over all the video and even negative coordinates

**Comment by ilya-lavrenov** [comment]
@Riko0 could you please attach a link to a converted model? what device is used to perform inference?

**Comment by Riko0** [comment]
[1.zip](https://github.com/openvinotoolkit/openvino/files/4725995/1.zip)

using i7 8700 but tried on another cpus

**Comment by jgespino** [comment]
@Riko0 Closing, please re-open if assistance is still needed.
