### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by AlvingCheng** [openvinotoolkit/openvino#7104]
##### System information (version)

Code:
#include <inference_engine.hpp>
using namespace InferenceEngine;

int main() {
	Core ie;  //0x00007FFEFA884ED9 处(位于 xx.exe 中)引发的异常: Microsoft C++ 异常: InferenceEngine::GeneralError，位于内存位置 0x00000070F0B6F270 处。
}
Please tell me how to fix this exception
thx!!!

**Comment by ilyachur** [comment]
Hi,

Looks like you have some issues with reading `plugins.xml` file.
Could you please check that you have `plugins.xml` near with inference_engine library?

**Comment by AlvingCheng** [comment]
In X64 | debug mode,
Include directory contains: 
C:\Program Files %28x86%29\Intel\openvino_2021.4.582\deployment_tools\inference_engine\include;
Library directory contains:
C:\Program Files %28x86%29\Intel\openvino_2021.4.582\deployment_tools\inference_engine\lib\intel64\Debug;
and Additional dependencies contains:
inference_engined.lib
inference_engine_transformationsd.lib
inference_engine_c_apid.lib

Trace the call stack and find that the exception occurred in kernelBase.dll 
![image](https://user-images.githubusercontent.com/28751065/129696732-c791797b-618c-4af4-a723-f850d5a564ea.png)
Could it be that the version of this .dll(10.0.19041.1151) is too new?
