### ISSUE TITLE
How can i start in centos7?

### ISSUE THREAD

**Issue by Hap-Zhang** [openvinotoolkit/openvino#7123]
Hello,everyone

I want to try openvino in my centos7, firstly, i try to pull a image from docker hub(**openvino/centos7_runtime**),and it is so old which i can't find model-optimizer in it, so i gave up... And then, i want to build from source code, but i find some error when i excute **cmake -DCMAKE_BUILD_TYPE=Release ..**,  the error is as follows:
```
-- MODELS_PATH=
-- Downloading from https://download.01.org/opencv/master/openvinotoolkit/thirdparty/unified/VPU/usb-ma2x8x/firmware_usb-ma2x8x_1717.zip to /data1/zqx/openvino/openvino/inference-engine/temp/download/VPU/usb-ma2x8x/firmware_usb-ma2x8x_1717.zip ...
-- /usr/bin/wget --no-cache --no-check-certificate
              --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 --tries=5 https://download.01.org/opencv/master/openvinotoolkit/thirdparty/unified/VPU/usb-ma2x8x/firmware_usb-ma2x8x_1717.zip
--2021-08-18 13:38:42--  https://download.01.org/opencv/master/openvinotoolkit/thirdparty/unified/VPU/usb-ma2x8x/firmware_usb-ma2x8x_1717.zip
Resolving download.01.org (download.01.org)... 104.71.174.98, 2600:140e:6:9a9::4b21, 2600:140e:6:9b0::4b21
Connecting to download.01.org (download.01.org)|104.71.174.98|:443... failed: Connection timed out.
Connecting to download.01.org (download.01.org)|2600:140e:6:9a9::4b21|:443... failed: Network is unreachable.
Connecting to download.01.org (download.01.org)|2600:140e:6:9b0::4b21|:443... failed: Network is unreachable.
```

**it seems the firmware_usb-ma2x8x_1717.zip is not available in the download.01.org?**

**Comment by brmarkus** [comment]
The download path is working for me - by just using the browser and trying to download the mentioned URL "https://download.01.org/opencv/master/openvinotoolkit/thirdparty/unified/VPU/usb-ma2x8x/firmware_usb-ma2x8x_1717.zip" from your log-messages.
Your logs show you ran into a connection-time-out; it would be different if the URL wouldn't exist (like error 404).

Are you sure you have network connectivity?

Maybe you are behind a corporate network and need to set proxy ENVIRONMENT variables like HTTP_PROXY and HTTPS_PROXY?

**Comment by Hap-Zhang** [comment]
Yeah, It's right that i have no access permission for **https://download.01.org/** in my environment, and thank you very much. 
By the way, it seems that openvino support Ubuntu more than CentOS, the latest docker images of centos in docker hub is four month ago, would you have plans to provide a latest docker image of centos?

**Comment by brmarkus** [comment]
Access to download.01.org is not restricted to my knowledge.
Can you try to access the URL "https://download.01.org/opencv/master/openvinotoolkit/thirdparty/unified/VPU/usb-ma2x8x/firmware_usb-ma2x8x_1717.zip" on another machine, in the same network? Everybody should have access, I think.

You ran into a connection-timeout - and not a "access denied" or "does not exist".
I think that might be related to network proxies.

There are some notes and restrictions regarding the support of CentOS under "https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html"...

**Comment by Hap-Zhang** [comment]
Hi, @brmarkus 
I can access the URL "https://download.01.org/opencv/master/openvinotoolkit/thirdparty/unified/VPU/usb-ma2x8x/firmware_usb-ma2x8x_1717.zip" on another machine,  however， I can not access this URL on my work machine, and I have set proxy ENVIRONMENT variables like HTTP_PROXY and HTTPS_PROXY, maybe this URL is only forbidden on my work machine...

**Comment by brmarkus** [comment]
From your original log, it's just "wget" to download the file:
```
/usr/bin/wget --no-cache --no-check-certificate
              --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 --tries=5 https://download.01.org/opencv/master/openvinotoolkit/thirdparty/unified/VPU/usb-ma2x8x/firmware_usb-ma2x8x_1717.zip
```

On your work machine, can you access other URLs through the proxy? If you just to a "wget https://download.01.org/", will you get an "index.html" file? Can you access any other URL with "https" (not http)?

What about DNS in your corporate network? Can you ping "https://download.01.org/" on another machine to retrieve it's IP-address and use the IP-address instead, to download the file?

**Comment by Hap-Zhang** [comment]
I'm sorry that when i try "wget https://download.01.org/", the error still exist and i can not get an "index.html" file

I download the firmware_usb-ma2x8x_1717.zip on another machine and upload to my work machine, but it seems not automatically detect this file and still wget again.

**Comment by brmarkus** [comment]
It looks like you have network issues. Are you sure your network proxy URL(s) and port(s) are correct?
Do you have DNS available in your corporate network?

Can you download the following?
`wget https://github.com/openvinotoolkit/openvino -O index.html`

This should download an "index.html".
