### ISSUE TITLE
[Bug] :Load project from Cmake on CLion IDE error.

### ISSUE THREAD

**Issue by FdyCN** [openvinotoolkit/openvino#7163]
hi, guys. I see Openvino is a toolkit, but i wanna debug in IDE like CLion. When i load project through CMakeList.txt in CLion. it came some errors in CMakeError.log generated by cmake:

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could you help me for this?  thank you

**Comment by FdyCN** [comment]
i think it's my fault.  Now it's ok to build project in CLion by CMake.   but i cannot convert a model by this command:

**python3 ./tools/downloader/converter.py --name googlenet-v1**

And there comes error below:

**ERROR:root:Could not find the Inference Engine or nGraph Python API.
Consider building the Inference Engine and nGraph Python APIs from sources or try to install OpenVINO (TM) Toolkit using "install_prerequisites.sh"**

Then i searched some docs, seems like OpenVINO is not supported on MacOS???(my OS version: MacOS BigSur 11.2.3 & cpu: intel Core i7).

**Comment by coneypo** [comment]
Have you enabled the `-DENABLE_PYTHON=ON` option when building?
Please refer to https://github.com/openvinotoolkit/openvino/wiki/BuildingForMacOS

**Comment by Iffa-Meah** [comment]
There are 2 ways of getting OpenVINO:
1. [Download & install OpenVINO toolkit](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_macos.html)
2. [pull & build OpenVINO from source](https://github.com/openvinotoolkit/openvino/wiki/BuildingForMacOS)

Decide one of the ways and follow the instruction thoroughly.

Note: please help to run the script " install_prerequisites.sh".
This will download the required packages.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
