### ISSUE TITLE
New Feature Request: Deploy IR Model to Intel Myriad X VPU directly

### ISSUE THREAD

**Issue by franva** [openvinotoolkit/openvino#7192]
Hi there,

I have my model exported to OpenVINO IR model which has 1 `.bin` and 1 `.xml`.

How could I deploy this IR model to the Myriad X VPU directly?

**Comment by Iffa-Meah** [comment]
Are you trying to infer the IR with MYRIAD?
You may use the [OpenVINO official Samples](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Samples_Overview.html) for that purpose.
use the -d MYRIAD parameter to run it on Myriad.

Don't forget to install the Plugin.

**Comment by franva** [comment]
thanks @Iffa-Meah 

Yes and I have tried it, it works~!! So happy about it.

Just one important question:
Do we get any **performance boost** by converting the IR model to .blob format?
I noticed that my model size is almost halved~!!!! Went down from 10.1MB to 5.4MB~!!!
And could you please share a piece of code which uses the .blob format in Python?

**Comment by Iffa-Meah** [comment]
Converting IR into blob format does not boost performance.
Instead, it saves time to upload the model to IR and allows application to start inference faster
You can do this by using the [compile tool together with a few lines of code](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_compile_tool_README.html).

**Comment by franva** [comment]
thanks :)
