### ISSUE TITLE
[Bug] ngraph path in InferenceEngine/share/cmake is still old?

### ISSUE THREAD

**Issue by dpatel257** [openvinotoolkit/openvino#7211]
##### System information (version)
- OpenVINO=> 2021.4
- Operating System / Platform => U 18.04

##### Detailed description

Getting error while building dlstreamer_gst (1.5.1):
ngraph path in cmake file under installed setup at /usr/local/openvino/inference-engine/share/InferenceEngineConfig.cmake
probably points to wrong path ?

`set_and_check(_ngraph_dir "${PACKAGE_PREFIX_DIR}/../ngraph/cmake")`

Shouldn't it be ?
`set_and_check(_ngraph_dir "${PACKAGE_PREFIX_DIR}/../deployment_tools/ngraph/cmake")`

##### Steps to reproduce

- Install Dldt 2021.4
- Install gst-video-analytics 1.5.1

**Comment by Iffa-Meah** [comment]
Hi,

I suggest you follow these guides carefully:
1. [Install Guide](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide)  (I did option 3 and I manage to create a pipeline and run classification on a video)
2. [DL Streamer Tutorial](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/DL-Streamer-Tutorial)

You should be good to go if you had set them up correctly and use what had been recommended based on the guides
![pipeline](https://user-images.githubusercontent.com/79643476/130669928-610cfed8-6ac1-4f9b-8a33-6b1cd85a3272.png)
.
Plus, it's good if you could post this issue directly to the [dlstreamer_gst](https://github.com/openvinotoolkit/dlstreamer_gst/issues) thread

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
