### ISSUE TITLE
Converting Tensorflow model to Openvino model

### ISSUE THREAD

**Issue by Hus174** [openvinotoolkit/openvino#7231]
I follow the [Openvino Documentation](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html) for converting a SavedModel format of a Tensorflow model  to an Openvino through model optimizer

I run the following line in the terminal 
sir@sir-00000000000000000000:/opt/intel/openvino_2021/deployment_tools/model_optimizer$ python3 mo_tf.py --saved_model_dir /home/sir/Downloads/Image_processing_project/Oil_spill_detection/project_oill/lib/saved_model/oil_spill_detection_model --input_shape [10,4] --output_dir /home/sir/Downloads/Image_processing_project/Oil_spill_detection/project_oill/lib/saved_model

But I am getting these errors

[ ERROR ]  Cannot infer shapes or values for node "StatefulPartitionedCall/sequential/conv2d/Conv2D".
[ ERROR ]  shape mismatch: value array of shape (2,2) could not be broadcast to indexing result of shape (1,2) 
[ ERROR ]  It can happen due to bug in custom shape infer function <function Convolution.infer at 0x7f9ffe4a65e0>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "StatefulPartitionedCall/sequential/conv2d/Conv2D" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)

I am using Ubuntu 20.04.3 LTS,  Openvino 2021.4 version, tensorflow 2.3.0 version 
Could anyone help me to solve these errors?

**Comment by Iffa-Meah** [comment]
Hi,

Please note that you will need to freeze your Tensorflow model first before using it with the OpenVINO Model Optimizer to convert the model into IR.

Plus please check whether your model's topology is listed. If not, then it is not supported.
You may refer [here](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html).

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
