### ISSUE TITLE
0x00007FFC474D4ED9 in ylov5_openvino.exe: Microsoft C++ exception: InferenceEngine::NotImplemented at memory location 0x000000BC8B1FD450.[Bug]

### ISSUE THREAD

**Issue by besmaGuesmi** [openvinotoolkit/openvino#7248]
Hello Currently I'm working on yolov5 with open vino using c++,and I faced this problem : Exception thrown at 0x00007FFC474D4ED9 in ylov5_openvino.exe: Microsoft C++ exception: InferenceEngine::NotImplemented at memory location 0x000000BC8B1FD450.[Bug]

Any help?

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by latermarch** [comment]
@besmaGuesmi  do you get rid of this bug? I meet the same issue although I have download & install the latest OpenVINO toolkit

**Comment by latermarch** [comment]
in addition, the exe don't crash,just output the exption info while running the code "core_->LoadNetwork(*network_, "CPU");"
