### ISSUE TITLE
[Feature Request] add precision support for `exec_net.export`

### ISSUE THREAD

**Issue by franva** [openvinotoolkit/openvino#7262]
##### System information (version)

- OpenVINO => 2020.4
- Operating System / Platform => Ubuntu 20.04
- Problem classification: Model Exporting in code
- Framework: from IR model to `.blob`

##### Detailed description
When we export our IR models to the compiled `.blob` models , could we support the specified precision?

e.g. 

`exec_net.export('./openvino/model_uint8.blob', 'FP16')`

**Comment by jgespino** [comment]
Hi @franva 

I apologize for the delay in my response. The purpose of generating the blob is to save time when loading a model to the device, currently only MYRIAD plugin is supported and MYRIAD only support FP16 precision.

Regards,
Jesus
