### ISSUE TITLE
[Explanation] VPU_NUMBER_OF_CMX_SLICES 

### ISSUE THREAD

**Issue by franva** [openvinotoolkit/openvino#7263]
##### System information (version)

- OpenVINO => 2021.4
- Operating System / Platform => Ubuntu 20.04

##### Detailed description
Trying to use the `compile_tool` to compile my IR model.
Would like to specify how many shaves the model should use, but found that the `VPU_NUMBER_OF_SHAVES`  needs to be used together with `VPU_NUMBER_OF_CMX_SLICES`.

The problem is that the `VPU_NUMBER_OF_CMX_SLICES` is not given a range, so we do not know what numbers we can put there. After a few rounds of try-and-error, I found it's value range, but I have no idea what's the correlation with `VPU_NUMBER_OF_SHAVES`. E.g. when I set shave=8, I should also set the slice=8, or there is a formula to use to calculate the correct number of `VPU_NUMBER_OF_CMX_SLICES`.

It will be nice if the document can be more detailed with the range and it's related to the number of shave.

**Comment by zulkifli-halim** [comment]
Hi @franva,  We don't have any other documentation for compile tool. The pull request [#2946](https://github.com/openvinotoolkit/openvino/pull/2946) and information from this [code ](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/vpu/graph_transformer/src/graph_transformer.cpp) might help to understand it better.

**Comment by coneypo** [comment]
The Connection Matrix (CMX) enables seamless interaction between the vector processors and other hardware components;

### Example 1.
CMX memory = 2 MB，considered as 16x128 KB ‘slices’, and 12 shaves on this Myriad device;
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Shave | Slice | Start Address | End Address | Size
-- | -- | -- | -- | --
0 | 0 | 0x70000000 | 0x7001FFFF | 128 KB
1 | 1 | 0x70020000 | 0x7003FFFF | 128 KB
2 | 2 | 0x70040000 | 0x7005FFFF | 128 KB
3 | 3 | 0x70060000 | 0x7007FFFF | 128 KB
4 | 4 | 0x70080000 | 0x7009FFFF | 128 KB
5 | 5 | 0x700A0000 | 0x700BFFFF | 128 KB
6 | 6 | 0x700C0000 | 0x700DFFFF | 128 KB
7 | 7 | 0x700E0000 | 0x700FFFFF | 128 KB
8 | 8 | 0x70100000 | 0x7011FFFF | 128 KB
9 | 9 | 0x70120000 | 0x7013FFFF | 128 KB
10 | 10 | 0x70140000 | 0x7015FFFF | 128 KB
11 | 11 | 0x70160000 | 0x7017FFFF | 128 KB
x | 12 | 0x70180000 | 0x7019FFFF | 128 KB
x | 13 | 0x701A0000 | 0x701BFFFF | 128 KB
x | 14 | 0x701C0000 | 0x701DFFFF | 128 KB
x | 15 | 0x701E0000 | 0x701FFFFF | 128 KB



</div>


</body>

</html>


- Shave 0 is assgined the lowest 128 Kbyte of CMX (Slice 0), Shave 1 to Slice 1... Shave 11 to Slice 11;
- Slices 12/13/14/15 are not tied to any Shave, freely used;
- Each SHAVE can access any other slice in CMX at the same cost, but inter-slice routing resources are finite. In addition, a slave accessing data in its own slice is more energy-efficient.

So for this device, shave ranges from 1 to 12, and CMX slices has a upper limt of 16;

### Example 2.
CMX memory = 1 MB, considered as 8x128 KB slices, and one 128 KB CMX slice for one Shave:
So for this device, shave ranges from 1 to 8, and CMX slice also range from 1 to 8;
![image](https://user-images.githubusercontent.com/7233586/131277793-274162b8-e306-40a9-bb37-3bb13a6be52e.png)

So `VPU_NUMBER_OF_SHAVES` and `VPU_NUMBER_OF_CMX_SLICES` both are the capabilities of HW Myriad device;
If 16 shaves on your device, set `VPU_NUMBER_OF_SHAVES` to 16;
If 2 MB CMX memory on it, set `VPU_NUMBER_OF_CMX_SLICES` to 16;

BTW, in this MR https://github.com/openvinotoolkit/openvino/pull/6022, `numShaves` max to 16 and `numSlices` max to 19 in OV now:

```
int DeviceResources::numShaves() {
    return 16;
}

int DeviceResources::numSlices() {
    return 19;
}
```

**Comment by zulkifli-halim** [comment]
Closing issue.

**Comment by franva** [comment]
thank @coneypo  for your detailed and picture-filled answer. 

For both of your examples, you knew the CMX size at the beginning e.g. 2MB for the 1st example and 1MB for the 2nd example.
and you also knew number of "slices" already.

For an user, how can I know how big is my CMX and how many "slices" are there in my Intel's hardware, e.g. Myriad X VPU?

Are shaves the vector processors? 

I will read through the links you provided.

Once again, thank you for providing the information :)
