### ISSUE TITLE
Can not run object_detection_sample_ssd.py on person-detection-retail-0002 model

### ISSUE THREAD

**Issue by qin53027** [openvinotoolkit/openvino#7294]
Hi,

Since I need to extract the bounding box information, I will need to use the object_detection_sample_ssd.py by adding the extract code for xmin/ymin/xmax/ymax. 

While it works for person-detection-retail-0013 model, it gives me the error while I run the person-detection-retail-0002 model:

           [ ERROR ] The sample supports only single input topologies

Can you point me the right python script which can run the person-detection-retail-0002 so that I can extract the BBX information?  Or if this is the correct scripts, then how I can avoid the runtime error?

Thanks so much for help!
Jimmy

run inferece with the python scripts
=============================
python3 object_detection_sample_ssd.py -m /home/jiande/program/intel_models/model1/intel/person-detection-retail-0002/FP32/person-detection-retail-0002.xml -i image_2/$line -d CPU

run inference with the executable file  -- but I do not know how to extract the BBX information
===============================
./bin/intel64/Release/object_detection_sample_ssd -i /home/jiande/coco_kitti/images/000001.jpg -m /home/jiande/program/intel_models/model1/intel/person-detection-retail-0002/FP32/person-detection-retail-0002.xml -d CPU

**Comment by zulkifli-halim** [comment]
Hello @qin53027, person-detection-retail models are not being validated with [ Object Detection SSD Python* Sample](https://docs.openvinotoolkit.org/2021.4/openvino_inference_engine_ie_bridges_python_sample_object_detection_sample_ssd_README.html).  

We suggest you use the [Object Detection SSD C++ Sample ](https://docs.openvinotoolkit.org/2021.4/openvino_inference_engine_samples_object_detection_sample_ssd_README.html) as the [person-detection-retail-0002](https://docs.openvinotoolkit.org/2021.4/omz_models_model_person_detection_retail_0002.html) model can run with this sample.

**Comment by qin53027** [comment]
@zulkifli-halim , thanks.
If so, do you know how to extract the BBX information: xmin/xmax/ymin/ymax?

**Comment by brmarkus** [comment]
Depending on the version of OpenVINO you are using, in the C++ sample the rectangle of the region-of-interest (ROI) (bounding-box) is drawn here, within the method "renderDetectionData()"
https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/object_detection_demo/cpp/main.cpp#L256

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to open a new issue if you have any other questions.
