### ISSUE TITLE
[Bug] Package Created By Deployment Manager On Windows Is Much Larger Than Necessary

### ISSUE THREAD

**Issue by jbrownkramer** [openvinotoolkit/openvino#7312]
##### System information (version)

- OpenVINO=> 2021.4
- Operating System / Platform => Windows 10
- Compiler => Visual Studio
- Problem classification => Deployment Manager

##### Detailed description
The ZIP file you get from the  Deployment Manager, if you include CPU and GPU inference and OpenCV is over 300MB.  If you extract it and then recompress, it gets down to less than 100MB.  This is probably because the archive options in the deployment manager just archive and don't compress.

**Comment by Iffa-Meah** [comment]
Generally, the[ OpenVINO Deployment Manager](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_deployment_manager_tool.html) just assemble your app, IR, model, and associated dependencies into a deployment package. It won't compress those files into a smaller size.

**Comment by jbrownkramer** [comment]
To be clear, I am talking about pushing OpenVINO to production machines.  i.e. pushing the binaries when a new version of OpenVINO becomes available.  Not the model.  The model will be pushed more often, and controlling its size is a separate issue.

**Comment by jgespino** [comment]
Hi @jbrownkramer 

Thank you for your feedback, I have passed this request to the development team for concideration.

Regards,
Jesus

Ref. 65187

**Comment by jgespino** [comment]
@jbrownkramer Pull Request #9367 includes your suggestion. Thanks again!
