### ISSUE TITLE
Unable to call license_plate_recognition_barrier_0001 model through REST api

### ISSUE THREAD

**Issue by m4masood** [openvinotoolkit/openvino#7317]
Hi,
I have got license_plate_recognition_barrier_0001 model deployed in OpenVINO server in container.
I am passing the image and additional field as per https://docs.openvinotoolkit.org/latest/omz_models_model_license_plate_recognition_barrier_0001.html 
but I keep getting error.

First I passed below:
![image](https://user-images.githubusercontent.com/7548298/131616260-61d2178a-4360-4f89-9ad0-b1927d8c7caf.png)

The error I get:
![image](https://user-images.githubusercontent.com/7548298/131616336-41dbf3fd-4092-4813-a1db-cee1a328ccdd.png)

When I pass batch size (as it complained above):
![image](https://user-images.githubusercontent.com/7548298/131616159-6238f599-11d9-4366-9c1e-cf283186e9b0.png)
I get below error:
![image](https://user-images.githubusercontent.com/7548298/131616186-472381e0-884e-4463-b7c7-36981222977b.png)

Can anyone please help me pass the correct dimension?

Thanks,
Muhammad

**Comment by Iffa-Meah** [comment]
Hi,

Probably you could view and analyze[ this code](https://github.com/livezingy/license-plate-recognition/blob/master/testOpenVINO.py) for its functionality and apply it to yours.
This is based on the official OpenVINO demo ([Security Barrier Demo](https://docs.openvinotoolkit.org/latest/omz_demos_security_barrier_camera_demo_cpp.html))

The np.ones() function is used as:
seq_ind = np.ones([88, 1], dtype=np.float32)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
