### ISSUE TITLE
Preserving LSTM states between inference calls

### ISSUE THREAD

**Issue by mbenasher** [openvinotoolkit/openvino#735]
Hello,

I have an LSTM-based network. I have exported it to onnx, converted to IR, and integrated it successfully to the Inference Engine.
I noticed that in order to maintain the states in the LSTM I must pass a complete sequence to the network at once and then call Infer() on the entire sequence.  However, if I pass the elements one by one and call Infer() the network does not remember previous states and starts from the beginning every time.
But because I am doing this in real-time, I don't have the entire sequence apriori and the point of LSTM is to theoretically process infinite sequences.
Is there a way to get and set the hidden states of the network or any other way to maintain the states between inference calls?
I could not find this anywhere in the documentation.

Thanks in advance!

Matan

**Comment by yury-gorbachev** [comment]
@slyalin can you help?

**Comment by slyalin** [comment]
Hello, @mbenasher. This is a task for original model design which is represented in ONNX. You have to define LSTM state input/outputs (initial_h, initial_c, Y_h, Y_c referred in the description here: https://github.com/onnx/onnx/blob/master/docs/Operators.md#LSTM) as explicit inputs and outputs of a model. And then, in your application that uses Inference Engine, pass Y_h and Y_c from previous infer request to the next infer request's initial_h and initial_c correspondingly. I believe there is a method to just allocate the same blob for corresponding input/output to save memory copying. Designing the original model in that way you are free to feed any fragment even a single element of the sequence per one infer request. The size (length) of the sequence should be fixed.
