### ISSUE TITLE
Incorrect Windows link for 2020.3 distribution toolkit

### ISSUE THREAD

**Issue by JulienMaille** [openvinotoolkit/openvino#738]
https://registrationcenter.intel.com/en/products/postregistration/ gives me this link
http://registrationcenter-download.intel.com/akdlm/irc_nas/16667/w_openvino_toolkit_p_2020.3.194.exe
which redirect to an error page:
https://www-ssl.intel.com/content/www/us/en/404.html?aspxerrorpath=/en/irc_nas/16667/w_openvino_toolkit_p_2020.3.194.exe/

**Comment by moslex** [comment]
Hello, @JulienMaille 
Yes, we know about this infrastructure problem and are working to fix it.

**Comment by alalek** [comment]
@JulienMaille Could you please try to download Windows package again?

**Comment by JulienMaille** [comment]
@alalek I can now download the online package, but the full one is still a broken link

**Comment by moslex** [comment]
@JulienMaille, I checked all links and they work. You may also need to purge your browser cache.

**Comment by JulienMaille** [comment]
That was indeed a browser cache issue. Thank you!
