### ISSUE TITLE
how to downlaod all the thirdparty files

### ISSUE THREAD

**Issue by zhaoxuejun1234** [openvinotoolkit/openvino#7401]
When I cloned the project, the thirdparty file couldn't be fully downloaded. There are always empty file clips.How can download it using simple commands instead of downloading them one by one

**Comment by vladimir-paramuzov** [comment]
do you mean empty submodules? If yes, please clone with `--recursive` option or run `git submodule update --init --recursive` inside openvino folder.

**Comment by zhaoxuejun1234** [comment]
Thank you for your reply, it's my Internet connection issue and already be solved with your help!
