### ISSUE TITLE
Converting IR model to specific framework.

### ISSUE THREAD

**Issue by mmrbulbul** [openvinotoolkit/openvino#7443]
Is it possible to use openvino to convert an IR model (given xml and bin file ) to a specific framework model i.e to tensorflow model or caffe model?

**Comment by Iffa-Meah** [comment]
Hi,
It's **not possible** to convert IR (OpenVINO pre-trained model or others) into other frameworks as OpenVINO does not support reverse conversion for the IR to be back to its native form.
