### ISSUE TITLE
how to build openvino with clang

### ISSUE THREAD

**Issue by zhaohb** [openvinotoolkit/openvino#7473]
now , I am compiling OpenVino from source code, and the option should be to support both compilations gcc and clang. I wonder if you have compared the performance of the two compilations, and how can I compile OpenVino using clang？

thank you very much.

**Comment by Iffa-Meah** [comment]
We are investigating this and will get back to you asap.

**Comment by ilya-lavrenov** [comment]
@zhaohb compiling via clang:
```cmake
CC=clang-7 CXX=clang++-7 cmake ../openvino
cmake --build . 
```

**Comment by zhaohb** [comment]
@ilya-lavrenov  thank you very much , but Is there a detailed document for reference?

**Comment by ilya-lavrenov** [comment]
It's a cmake feature, not OpenVINO one. 
You can specify any compiler you want to use

**Comment by zhaohb** [comment]
if I add CC=clang-7 CXX=clang++-7 cmake .. , mkl-dnn will also clang compiler?

**Comment by ilya-lavrenov** [comment]
Yes, this line sets compiler for all submodules

**Comment by zhaohb** [comment]
thank you very much , I will try it

**Comment by zhaohb** [comment]
I've compiled it use clang and test ppenvino's performance but found no difference between GCC and Clang

**Comment by ilya-lavrenov** [comment]
@zhaohb no, we did not. 
CPU plugin has a lot of performance critical kernels which are written in xbyak. So, they the kernels written in xbyak are generated in runtime and it's does not matter which compiler is used to compile CPU plugin.
Of course, we have kernels are written in C++ scalar code and they are auto vectorized by the compiler and performance may vary from compiler to compiler. So, everything depends on your topology and which kernels were selected

**Comment by zhaohb** [comment]
which kernel were select？ how to select different kernel？If kernel selection is automatic, can I choose it myself？l have a deepfm model, however compared with triton tf backend, the performance of openvino model serving is worse, so l want to find the best performance for my model, do you have any suggestions?

**Comment by zhaohb** [comment]
Another question, what does topology refer to? My deepfm model or CPU architecture?

**Comment by ilya-lavrenov** [comment]
> which kernel were select？ how to select different kernel？If kernel selection is automatic, can I choose it myself

Yes, it's automatic.

> what does topology refer to?

Model == topology

@dmitry-gorokhov do you have any suggestion about the performance improvements?

**Comment by zhaohb** [comment]
ok, thank you very much, I need help badly.

**Comment by zhaohb** [comment]
Who can give me some advice？

**Comment by jgespino** [comment]
Hi @zhaohb I believe you are following up on a different issue (https://github.com/openvinotoolkit/openvino/issues/7273) . Let me know if we can close this issue. 

Regards,
Jesus

**Comment by zhaohb** [comment]
Ok, I will close this issue! thank you very much.
