### ISSUE TITLE
I couldn't export the optimized model from DL workbench !

### ISSUE THREAD

**Issue by besmaGuesmi** [openvinotoolkit/openvino#7477]
Hi there!

Could anyone here explain to me why I couldn't export and deployer my optimized project from DL workbench!

![image](https://user-images.githubusercontent.com/36562278/133016063-11b5471b-e551-4b34-8d49-661805478a9b.png)

**Comment by brmarkus** [comment]
Please have a look at the documentation under "https://docs.openvinotoolkit.org/latest/workbench_docs_Workbench_DG_Deployment_Package.html". You need to configure first, what you would like to get packaged.

**Comment by zulkifli-halim** [comment]
Hello @besmaGuesmi,  has your issue been resolved yet?

**Comment by artyomtugaryov** [comment]
Hello @besmaGuesmi,

Thank you for using DL Workbench. 
I believe you need to choose at least one item to download the deployment package: device, model, Python APY, and e.t.c

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to reopen the case or open a new case if you have any further questions.
