### ISSUE TITLE
[Bug] 2021.4.582 install on ubuntu with apt fails

### ISSUE THREAD

**Issue by georgelyuan** [openvinotoolkit/openvino#7495]
Hello, I'm trying to install OpenVINO through apt on an ubuntu 20.04.2 LTS docker using the following commands:

```
wget https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021 &&     apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2021 && rm GPG-PUB-KEY-INTEL-OPENVINO-2021 &&     cd /etc/apt/sources.list.d &&     echo "deb https://apt.repos.intel.com/openvino/2021 all main">intel-openvino-2021.list &&     apt update
apt install -y intel-openvino-dev-ubuntu20-2021.4.582
```

We get the following error:

> Preparing to unpack .../22-intel-openvino-gstreamer-rt-ubuntu-focal-2021.4.582_2021.4-582_amd64.deb ...
> Unpacking intel-openvino-gstreamer-rt-ubuntu-focal-2021.4.582:amd64 (2021.4-582) ...
> dpkg-deb (subprocess): cannot copy archive member from '/tmp/apt-dpkg-install-gx8LJf/22-intel-openvino-gstreamer-rt-ubuntu-focal-2021.4.582_2021.4-582_amd64.deb' to decompressor pipe: unexpected end of file or stream
> dpkg-deb (subprocess): decompressing archive member: lzma error: unexpected end of input
> dpkg-deb: error: <decompress> subprocess returned error exit status 2
> dpkg: error processing archive /tmp/apt-dpkg-install-gx8LJf/22-intel-openvino-gstreamer-rt-ubuntu-focal-2021.4.582_2021.4-582_amd64.deb (--unpack):
>  cannot copy extracted data for './opt/intel/openvino_2021.4.582/data_processing/gstreamer/lib/gstreamer-1.0/libgstgoom.so' to '/opt/intel/openvino_2021.4.582/data_processing/gstreamer/lib/gstreamer-1.0/libgstgoom.so.dpkg-new': unexpected end of file or stream
> Selecting previously unselected package intel-openvino-gva-rt-ubuntu-focal-2021.4.582:amd64.
> Preparing to unpack .../23-intel-openvino-gva-rt-ubuntu-focal-2021.4.582_2021.4-582_amd64.deb ...
> Unpacking intel-openvino-gva-rt-ubuntu-focal-2021.4.582:amd64 (2021.4-582) ...
> Selecting previously unselected package intel-openvino-pot-2021.4.582:amd64.
> Preparing to unpack .../24-intel-openvino-pot-2021.4.582_2021.4-582_amd64.deb ...
> Unpacking intel-openvino-pot-2021.4.582:amd64 (2021.4-582) ...
> Selecting previously unselected package intel-openvino-dev-ubuntu20-2021.4.582:amd64.
> Preparing to unpack .../25-intel-openvino-dev-ubuntu20-2021.4.582_2021.4-582_amd64.deb ...
> Unpacking intel-openvino-dev-ubuntu20-2021.4.582:amd64 (2021.4-582) ...
> Errors were encountered while processing:
>  /tmp/apt-dpkg-install-gx8LJf/22-intel-openvino-gstreamer-rt-ubuntu-focal-2021.4.582_2021.4-582_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> 

This flow was working as of just recently.

**Comment by CoderHam** [comment]
+1 I faced the same issue. These install steps worked a week or so ago. If I replace the version with 2021.2.200, it works as well. I believe the 2021.4 package might be corrupted.

**Comment by superxoder** [comment]
Happened to us too. Repeat same failure with 2021.4 package. Hope they realize and fix the issue.

**Comment by Iffa-Meah** [comment]
Hi,

I just tried this today and it seems I didn't get that error.
Could you try that again? probably as root.


![doc1](https://user-images.githubusercontent.com/79643476/133717998-e92b9c07-8de4-46c7-8acd-b115dad8bd45.png)
![doc2](https://user-images.githubusercontent.com/79643476/133718006-24c4a266-0dd2-4714-bddb-414388b5941d.png)

**Comment by nvpohanh** [comment]
Seems to be working now. @georgelyuan I think we can close this.
