### ISSUE TITLE
[Bug] loading model takes too long time on iGPU

### ISSUE THREAD

**Issue by zhoumenghan** [openvinotoolkit/openvino#7510]
##### Detailed description
I have a FOMM（2D animation）model, and I have run the model with intel GPU. But while CPU plugin takes less than 3 second to load the model, GPU plugin takes more than 2 minutes for that. I have read the [doc ](https://github.com/openvinotoolkit/openvino/blob/master/docs/IE_DG/Model_caching_overview.md)，but some details are still not sure how to achieve. The following is my code implementation, please help point out the problem:
  ```
        // 1.load the model, read network and weights
	InferenceEngine::InferRequest infer_request_kp;
	InferenceEngine::Core ie_kp;
	InferenceEngine::CNNNetwork model_kp = ie_kp.ReadNetwork(xmlPath_kp, binPath_kp);
	// 2.intputs & outputs
	InferenceEngine::InputsDataMap inputsInfo_kp;
	InferenceEngine::OutputsDataMap outputsInfo_kp;
	inputsInfo_kp = model_kp.getInputsInfo();
	outputsInfo_kp = model_kp.getOutputsInfo();
	// 3.load model to device
	ie_kp.SetConfig({ {CONFIG_KEY(CACHE_DIR), "/tmp/kp_gpu/"} }, "GPU");
	InferenceEngine::ExecutableNetwork executableNetwork_kp = ie_kp.LoadNetwork(model_kp, "GPU",
		{ {InferenceEngine::PluginConfigParams::KEY_DUMP_KERNELS, InferenceEngine::PluginConfigParams::YES} });
```

**Comment by zhoumenghan** [comment]
in the [doc](https://github.com/openvinotoolkit/openvino/blob/master/docs/IE_DG/Model_caching_overview.md)
To enable model caching, the application must specify the folder where to store cached blobs. It can be done like this
@snippet snippets/InferenceEngine_Caching0.cpp part0
With this code, if device supports Import/Export network capability, cached blob is automatically creat....

where is the InferenceEngine_Caching0.cpp?

**Comment by brmarkus** [comment]
The code-snippets are displayed correctly here: https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Model_caching_overview.html

The code-snippet looks like this:
```
    InferenceEngine::Core ie;                                 // Step 1: create Inference engine object
    ie.SetConfig({{CONFIG_KEY(CACHE_DIR), "myCacheFolder"}}); // Step 1b: Enable caching
    auto cnnNet = ie.ReadNetwork(modelPath);                  // Step 2: ReadNetwork
    //...                                                     // Step 3: Prepare inputs/outputs
    //...                                                     // Step 4: Set device configuration
    ie.LoadNetwork(cnnNet, device, deviceConfig);             // Step 5: LoadNetwork
```
Please make sure the configured path exists and the application (the user running the application) has write-access to it.

For a quick test - without the need to change your source code - you can also set the ENV variable `cl_cache_dir` before starting your application, like:

`export cl_cache_dir=/tmp/kp_gpu/`

**Comment by zhoumenghan** [comment]
thank you~
