### ISSUE TITLE
Error Preparing Basic Graph with Custom Layers

### ISSUE THREAD

**Issue by mrrosen** [openvinotoolkit/openvino#755]
Running a very simple computation graph (to try out custom layers for GPU and MYRIAD) runs on GPU but fails to run on MYRIAD. Running the attached python script `run.py`, the script runs as follows:

Working on GPU:
```
$ python3 run.py GPU
[E:] [BSL] found 0 ioexpander device
Devices: ['CPU', 'GNA', 'GPU', 'MYRIAD']
Extension added
Inputs: {'Placeholder': <openvino.inference_engine.ie_api.DataPtr object at 0x7fa0e208bd30>, 'Placeholder_1': <openvino.inference_engine.ie_api.DataPtr object at 0x7fa0c61085f0>}
Running 0,0:0
Running 0,1:1
Running 0,2:2
Running 0,3:3
Running 0,4:4
Running 0,5:5
Running 0,6:6
Running 0,7:7
{'mul': array([[[[ 2.,  8., 12., 24.,  2.,  8., 12., 24.]]]], dtype=float32)}
```

Not working on Myriad:
```
$ python3 run.py MYRIAD
[E:] [BSL] found 0 ioexpander device
Devices: ['CPU', 'GNA', 'GPU', 'MYRIAD']
Extension added
Inputs: {'Placeholder': <openvino.inference_engine.ie_api.DataPtr object at 0x7f60ee40cd30>, 'Placeholder_1': <openvino.inference_engine.ie_api.DataPtr object at 0x7f60d24895f0>}
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    runNet = ie.load_network(network=net, device_name=sys.argv[1]);
  File "ie_api.pyx", line 178, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 187, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Unable to bind parameter  for SimpleAdd layer. Name is: add
```

When I examine the output binary from the OpenCL compilation and read through the source for how custom layers are handled for VPU, I find that it looks like the problem is related to the compiler adding a 4th argument with no name (empty string) and type `char` to my kernel. Im not sure if this is an intended part of the implementation but the vpu plugin code doesnt seem to be expecting it.

Here is some of the information on my machine/environment:
Machine: NUC8i7HVK (i7-8809G; Gen9 HD Graphics NEO)
OS: Ubuntu 18.04.1 (kernel 5.3.0-53)
OpenVINO Version: 2020.2.120
clc Version: 1.40.3 (LLVM 7.0.0)

Files:
[openvino-error-files.tar.gz](https://github.com/openvinotoolkit/openvino/files/4725076/openvino-error-files.tar.gz)

**Comment by ilya-lavrenov** [comment]
@geexie could you please help?

**Comment by geexie** [comment]
Thanks, @mrrosen. @maxim-kurin, could you please take a look

**Comment by maxim-kurin** [comment]
@mrrosen I've reproduced your issue. MyriadX OpenCL compiler currently has no support for printfs, unfortunately. Removing it from test.cl solves the problem with 4-th parameter. 
I don't have MyriadX device on hand, so I hope everything else will work fine.

**Comment by geexie** [comment]
@mrrosen, @maxim-kurin, The OpenCL 1.2 specification does not require printf implementation. VPU compiler is based on OpenCL 1.2 with graphic related features (like textures) plus DMA-extension API on top of this spec.

**Comment by mrrosen** [comment]
@maxim-kurin Thanks. I tried again with removing the printf (was hoping it would just be silently ignored if unsupported, oh well). While it seems to be running now, I am not getting the correct result (all zeroes):
```
python3 run.py MYRIAD
[E:] [BSL] found 0 ioexpander device
Devices: ['CPU', 'GNA', 'GPU', 'MYRIAD']
Extension added
Inputs: {'Placeholder': <openvino.inference_engine.ie_api.DataPtr object at 0x7f3fb065ad30>, 'Placeholder_1': <openvino.inference_engine.ie_api.DataPtr object at 0x7f3f946d55f0>}
{'mul': array([[[[0., 0., 0., 0., 0., 0., 0., 0.]]]], dtype=float32)}
```

**Comment by sonebu** [comment]
@mrrosen don't know if you solved this already but I think this line inside test-mv.xml does not "instantiate" any "workers" (sorry about the jargon if its wrong):

`<WorkSizes global="B,X"/>` 

(I don't understand what you wanted to achieve with the comma) + (symbolic B,Y,F,X should work as per [this link](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Extensibility_DG_VPU_Kernel.html#compile_opencl_code_for_vpu_intel_neural_compute_stick_2) but I couldn't make it work), but, this line seems to be the problem. Try hardcoding a number instead of symbolics, e.g., global="4", global="8", that should get the workers going.

Also, not sure why but float/FP32/f32 seems to fail ("fail" as in it produces wrong results for the add/mul), try converting everything to half/FP16/f16, that seems to work (I don't know if FP16 works for your use case of course)
