### ISSUE TITLE
[Bug] FATAL ERROR:                                                   * * This OpenCV build doesn't support current CPU/HW configuration *

### ISSUE THREAD

**Issue by ntackie** [openvinotoolkit/openvino#7555]
Hello,

I receive this error when i try to run inference classification but I get the error below anytime i run

ty@ty:~/inference_engine_samples_build/intel64/Release$ ./classification_sample_async -i /opt/intel/openvino_2021/deployment_tools/demo/car.png -m ~/models/public/squeezenet1.1/ir/squeezenet1.1.xml  CPU

******************************************************************
* FATAL ERROR:                                                   *
* This OpenCV build doesn't support current CPU/HW configuration *
*                                                                *
* Use OPENCV_DUMP_CONFIG=1 environment variable for details      *
******************************************************************

Required baseline features:
    ID=  2 (SSE) - OK
    ID=  3 (SSE2) - OK
    ID=  4 (SSE3) - OK
    ID=  5 (SSSE3) - OK
    ID=  6 (SSE4.1) - OK
    ID=  8 (POPCNT) - NOT AVAILABLE
    ID=  7 (SSE4.2) - OK
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.3-openvino) ../opencv/modules/core/src/system.cpp:645: error: (-215:Assertion failed) Missing support for required CPU baseline features. Check OpenCV build configuration and required CPU/HW setup. in function 'initialize'

Aborted (core dumped)

**Comment by alalek** [comment]
See here: https://github.com/opencv/opencv/issues/18932#issuecomment-734287373

(VirtualBox bug)

**Comment by zulkifli-halim** [comment]
Closing issue.
