### ISSUE TITLE
[Bug] compile_tool: number of biases must equal to number of output channels per group

### ISSUE THREAD

**Issue by Erol444** [openvinotoolkit/openvino#7557]
##### System information (version)
- OpenVINO => 2020.4
- Operating System / Platform => Ubuntu 18 64 Bit
- Problem classification: Model Compiling (compile_tool)

##### Detailed description

When trying to compile a simple sobel filter model (IR format) to .blob using compile_tool, I get the following error:

```
Failed to compile layer "Conv_34": [ GENERAL_ERROR ] 
number of biases must equal to number of output channels per group, but: channels per group=2, biases=1
```
Looking at the Conv_34 layer, it looks ok. Also the bin/xml work fine with the inference engine.
![image](https://user-images.githubusercontent.com/18037362/133910006-5749ed79-b88c-4e74-acaa-4f6717ba5360.png)

The layer type is `Convolution`, looking at OpenVINO docs there's no clear indication whether the `Convolution` is supported by VPU:
![image](https://user-images.githubusercontent.com/18037362/133910128-89e3b052-258a-479c-9196-46c330c34bd3.png)

##### Steps to reproduce

Using `compile_tool -ip U8 [xml path] [bin path]` will return this error with openvino 2021.4. Zip of bin/xml attached:
[sobel_IR.zip](https://github.com/openvinotoolkit/openvino/files/7190727/sobel_IR.zip)

##### Issue submission checklist

There's another issue which has the same error when trying to compile `Convolution-Grouped 3D`, which is not supported by the VPU.

**Comment by Iffa-Meah** [comment]
May I know what model are you using and which topology it is?
If possible, could you share the files?

**Comment by Erol444** [comment]
Hello @Iffa-Meah, `.zip` is actually attached to the post (under `Steps to reproduce`). It's a simple sobel filter. Thanks!

**Comment by Iffa-Meah** [comment]
I've checked your model with the Compile Tool and I get the same error as you are getting.
We are going to further investigate this.
![compile_sobel](https://user-images.githubusercontent.com/79643476/134102326-7c4d7725-174e-4586-afa7-b6933dc83088.png)

**Comment by Erol444** [comment]
Great, thanks for the update @Iffa-Meah!

**Comment by jgespino** [comment]
Hi @Erol444 

It looks like your model is using a Convolution 3D layer which is not supported on VPUs. Could you share your ONNX model and I will double check with the development team?

Regards,
Jesus

**Comment by Erol444** [comment]
Hello @jgespino,
thank you for your reply, I wasn't aware this was `Convolution 3D` layer (in Netron it only shows `Convolution`, without any kind). So that makes sense why it doesn't work as expected. Sobel filter onnx model attached:
[sobel-onnx.zip](https://github.com/openvinotoolkit/openvino/files/7214409/sobel-onnx.zip)
I am using the `sobel_simplified.onnx` model (using onnx simplifier, but I both models have the same unsupported layer.
Thanks again, Erik
.

**Comment by jgespino** [comment]
Thanks! Let me check with the dev team and get back to you.

Regards,
Jesus

Ref. 66215

**Comment by jgespino** [comment]
Hi @Erol444 

I apologize for the delay, I've confirmed with the development team that your model contains 3D Group Convolution layer which is not supported by the VPU plugin.

Regards,
Jesus

**Comment by Erol444** [comment]
Thanks for the update, closing this issue.
