### ISSUE TITLE
[Bug]  Cannot create Gather layer Gather

### ISSUE THREAD

**Issue by zhouxin666251** [openvinotoolkit/openvino#7572]
net = ie.read_network(model=model_xml, weights=model_bin)   File "ie_api.pyx", line 293, in openvino.inference_engine.ie_api.IECore.read_network   File "ie_api.pyx", line 315, in openvino.inference_engine.ie_api.IECore.read_network RuntimeError: Cannot create Gather layer Gather_17430 id:38 from unsupported opset: opset7
IR include Shufflenetv2 network,

**Comment by Iffa-Meah** [comment]
Hi,

May I know what you are trying to achieve with this? (eg: object detection, face recognition).
Plus, which model and topology are you using? (eg: model Tensorflow, topology MobileNet v1 128)

**Comment by zhouxin666251** [comment]
> 
> 
> Hi,
> 
> May I know what you are trying to achieve with this? (eg: object detection, face recognition).
> Plus, which model and topology are you using? (eg: model Tensorflow, topology MobileNet v1 128)

**Comment by zhouxin666251** [comment]
I want to achieve keypoint detection. Using Pytorch, topology Sufflenet v2.

**Comment by Iffa-Meah** [comment]
Is it possible for you to share your files?

**Comment by zhouxin666251** [comment]
Really Sorry, I can not. But I use some simple code to check the output of the optimized network. Generate heatmaps are very poor. I think the fault is in .onnx generated by the code in follow，  torch.onnx.export(net, input, output_name, input_names=input_names, output_names=output_names).   If the caffe an pytorch have different influence for openvino?

**Comment by Iffa-Meah** [comment]
I noticed that You encountered "RuntimeError: Cannot create Gather layer Gather_17430 id:38 from unsupported opset: opset7" which related to the opset version. This might be the issue.

PyTorch* operations couldn't be exported to ONNX* with any desired opset version.

It is recommended to export models to opset 11 or higher when export to default opset 9 is not working. In that case, use opset_version option of the torch.onnx.export. 

These might helps:
1. [Converting your PyTorch model](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_PyTorch.html)
2. [Operators Schemas](https://github.com/onnx/onnx/blob/master/docs/Operators.md)

You may refer [here](https://docs.openvinotoolkit.org/latest/openvino_docs_performance_benchmarks_openvino.html) to see the relation between different model/topology and OpenVINO + different hardware performance and you could judge it yourself based on this.

**Comment by zhouxin666251** [comment]
Thanks for your advices,  have a nice day.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
