### ISSUE TITLE
[Model Support Request] Support UNet for segmentation

### ISSUE THREAD

**Issue by franva** [openvinotoolkit/openvino#7596]
##### System information (version)

- OpenVINO => 2021.4
- Operating System / Platform => Ubuntu 20.04
- Problem classification: Model Conversion
- Framework: PaddleSeg
- Model name: Unet

##### Detailed description

Glad to see that the new OpenVINO supports so many PaddlePaddel models directly, but surprisingly, the very common UNet is not in [the list](https://github.com/openvinotoolkit/openvino/blob/0df7dab345720f3778a039f8b0453a43eb2644f3/docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Paddle.md)

So just wondering is the support of UNet on the table?
If yes, do we have a timeline for it?

Thanks

**Comment by zulkifli-halim** [comment]
Hello @franva, Unet is supported by OpenVINO and listed in [Supported Topologies documentation](https://docs.openvinotoolkit.org/2021.4/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html).  OpenVINO also provide the pre-trained Unet models such as [unet-camvid-onnx-0001](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/unet-camvid-onnx-0001) and [brain-tumor-segmentation](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/brain-tumor-segmentation-0001).

**Comment by franva** [comment]
thanks :)
