### ISSUE TITLE
[Bug] Do OpenVINO supported by Macos Big Sur 11.3.1?

### ISSUE THREAD

**Issue by HappyAIWalker** [openvinotoolkit/openvino#7609]
I run my demo with python on my macbook pro, it can run with right result.
but when i try to run it with cpp mode, it can build but can't run.
![image](https://user-images.githubusercontent.com/85021995/134465864-6882247d-916c-49bc-b821-1e5c00196d85.png)

I also run the same code on win10, it can run with right result.
So I think: maybe the openvino is not supported by MacOS Big Sur.
If so, who can give me a help?

**Comment by brmarkus** [comment]
Can you describe how you installed OpenVINO on your machine - have you built it from source-code?

Can you run any of the inference-engine samples and open-model-zoo-demos (like "hello_query_device", "benchmark_app", "sample_classification" etc) - both part of the installation?

Can you provide more details about your demo code, please? Where exactly is the exception thrown? Can you describe the code, and/or provide a call-stack?

Have you created (converted) the model you are using? Is only this model causing the problem - can you use a pre-trained model from the Open-Model-Zoo successfully?

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
