### ISSUE TITLE
When can dynamic input of the model be supported

### ISSUE THREAD

**Issue by liiitleboy** [openvinotoolkit/openvino#7664]

**Comment by Iffa-Meah** [comment]
Hi,
Currently, the dynamic input is not supported. However, the development team is working on it.
For the time being there is no exact OpenVINO version yet for this support as it's still in development.

**Comment by liiitleboy** [comment]
> 您好，
> 目前不支持动态输入。但是，开发团队正在努力。
> 目前还没有确切的 OpenVINO 版本支持这种支持，因为它仍在开发中。

Thanks for your response.
I heard that this feature is under development, which is very exciting because I really need it very much. 
Do you have a general schedule, such as the middle of next year.

**Comment by liiitleboy** [comment]
> Hi,
> Currently, the dynamic input is not supported. However, the development team is working on it.
> For the time being there is no exact OpenVINO version yet for this support as it's still in development.

Thanks for your response.
I heard that this feature is under development, which is very exciting because I really need it very much. Do you have a general schedule, such as the middle of next year.

**Comment by Iffa-Meah** [comment]
Ref. 56398

**Comment by jgespino** [comment]
@liiitleboy 

We are currently working to support Dynamic Shapes on CPU for the next software release. If you would like to test this, please take a look at the [Dynamic Shapes User Guide](https://docs.openvino.ai/nightly/openvino_docs_OV_UG_DynamicShapes.html) and download the [OpenVINO™ toolkit pre-release](https://github.com/openvinotoolkit/openvino/releases) package.
