### ISSUE TITLE
Intel® Distribution of OpenVINO™ toolkit run-time package on CentOS 8.2 

### ISSUE THREAD

**Issue by cao-nv** [openvinotoolkit/openvino#7677]
Hi, 
I want use OpenVINO to accelerate a model on CPU, but I'm using CentOS 8.2 which is not officially supported. 
My question is that if I can use OpenVINO toolkit run-time package for REHL 8.2 which basically identical to CentOS 8.2. 
If yes, Do I need to install dependencies or just use the provided libraries out of the box? 
Any comments are appreciated. 
Thanks.

**Comment by zulkifli-halim** [comment]
Hello @cao-nv. For deployment scenarios on Red Hat* Enterprise Linux* 8.2 (64 bit), you can use the Intel® Distribution of OpenVINO™ toolkit run-time package that includes the Inference Engine core libraries, nGraph, OpenCV, Python bindings, CPU and GPU plugins. The package is available: 

- [Downloadable archive](https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.3/l_openvino_toolkit_runtime_rhel8_p_2021.3.394.tgz)
- [PyPi package](https://pypi.org/project/openvino/)
- [Docker image](https://catalog.redhat.com/software/containers/intel/openvino-runtime/606ff4d7ecb5241699188fb3)

**Comment by cao-nv** [comment]
> Hello @cao-nv. For deployment scenarios on Red Hat* Enterprise Linux* 8.2 (64 bit), you can use the Intel® Distribution of OpenVINO™ toolkit run-time package that includes the Inference Engine core libraries, nGraph, OpenCV, Python bindings, CPU and GPU plugins. The package is available:
> 
>     * [Downloadable archive](https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.3/l_openvino_toolkit_runtime_rhel8_p_2021.3.394.tgz)
> 
>     * [PyPi package](https://pypi.org/project/openvino/)
> 
>     * [Docker image](https://catalog.redhat.com/software/containers/intel/openvino-runtime/606ff4d7ecb5241699188fb3)

Thank you for replying, 
I know the package for RHEL, and my question waws if the package can be used for CentOS (with a bit of modification).

**Comment by zulkifli-halim** [comment]
Hello @cao-nv, you can try it but there is no guarantee that it will succeed as it is not being tested by our developer.

**Comment by cao-nv** [comment]
> Hello @cao-nv, you can try it but there is no guarantee that it will succeed as it is not being tested by our developer.

Thank you for your timely response! In case of using the package, do I need to install any dependencies?

**Comment by zulkifli-halim** [comment]
There will be OpenVINO dependencies that you need to install.

**Comment by cao-nv** [comment]
> There will be OpenVINO dependencies that you need to install.

Got it, thank you!
