### ISSUE TITLE
[Bug] LessEqual has type S32, but one of [FP16] is expected

### ISSUE THREAD

**Issue by simetin** [openvinotoolkit/openvino#7799]
##### System information (version)

- OpenVINO => 2021.4
- Operating System / Platform => Mac OSX
- Problem classification: Model Conversion
- Framework: PyTorch / Onnx

##### Detailed description
LessEqual operation give me the following error: Stage node LessOrEqual_106 (Less_equal) types check error: output #0 has type S32, but one of [FP16] is expected. 

The error is weird since it's output type is boolean, not fp16/int32

##### Steps to reproduce

```
from torch import nn
import torch
import onnx
from onnxsim import simplify


def rgb2hsv_custom(image, epsilon=1e-6):
    assert(image.shape[1] == 3)
    r, g, b = image[:, 0]/255, image[:, 1]/255, image[:, 2]/255

    max_rgb, argmax_rgb = image.max(1)
    min_rgb, argmin_rgb = image.min(1)
    max_min = max_rgb - min_rgb + epsilon
    h1 = 60.0 * (g - r) / max_min
    h2 = 60.0 * (b - g) / max_min + 180.0
    h3 = 60.0 * (r - b) / max_min + 300.0
    h = torch.stack((h2, h3, h1), dim=0).gather(dim=0, index=argmin_rgb.unsqueeze(0)).squeeze(0)
    s = max_min / (max_rgb + epsilon)
    v = max_rgb
    return torch.stack((h, s, v), dim=1)


class GreenFilter(nn.Module):
    def forward(self, image):
        x_rgb = image.flip(-3)

        hsv_tensor = rgb2hsv_custom(x_rgb)
        hsv_tensor = hsv_tensor[0]
        hsv_tensor = hsv_tensor.permute(1, 2, 0)
        h = torch.empty_like(hsv_tensor[:, :, 0]).copy_(hsv_tensor[:, :, 0])
        h *= 180

        s = torch.empty_like(hsv_tensor[:, :, 1]).copy_(hsv_tensor[:, :, 1])
        s *= 255
        
        v = torch.empty_like(hsv_tensor[:, :, 2]).copy_(hsv_tensor[:, :, 2])

        lower = (36.0, 25.0, 25.0)
        upper = (86.0, 255.0, 255.0)
  
        h[(h >= lower[0]) & (h <= upper[0])] = 1.0
        s[(s >= lower[1]) & (s <= upper[1])] = 1.0
        v[(v >= lower[2]) & (v <= upper[2])] = 1.0

        hsv = torch.stack((h, s, v), dim=1)
        hsv = hsv.permute(1, 2, 0)


        return hsv

X = torch.ones((1, 3, 300, 300), dtype=torch.float32)

torch.onnx.export(
    GreenFilter(),
    (X), # Dummy input for shape
    "model.onnx",
    opset_version=12,
    do_constant_folding=True,
)


onnx_model = onnx.load("model.onnx")
model_simpified, check = simplify(onnx_model, perform_optimization=False)
onnx.save(model_simpified, "model_non-opt.onnx")


import blobconverter

blobconverter.from_onnx(
    model="model_non-opt.onnx",
    output_dir="model.blob",
    data_type="FP16",
    shaves=6,
    use_cache=False,
    optimizer_params=[]
)```

**Comment by simetin** [comment]
[Onnx models.zip](https://github.com/openvinotoolkit/openvino/files/7267820/Onnx.models.zip)

**Comment by simetin** [comment]
![lessequal_error](https://user-images.githubusercontent.com/7005663/135635354-cfd89077-0c2a-4c0e-8f10-4ffdbcc70e6f.png)

**Comment by Iffa-Meah** [comment]
Hi,

Just to clarify, are you using NCS2 or MYRIAD device? If yes, the model must be converted into FP16 format.
The OpenVINO model optimizer should automatically handle this if you included the [--data_type FP16](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html) parameter during conversion.

**Comment by simetin** [comment]
I am using MYRIAD device and I do include the data_type FP16 param.
Model optimizer params: --data_type=FP16 --mean_values=[127.5,127.5,127.5] --scale_values=[255,255,255]
MyriadX compile params: -ip U8
Shaves: 4

**Comment by Iffa-Meah** [comment]
I've checked your model and it seems like the problem lies within your original model (onnx).
Generally, I would test the model with the OpenVINO Benchmark App to see whether they are able to be inferred or not.
The native onnx format is actually supported to be directly run with OpenVINO, so I did check that.
This is how I managed to see the problem I mentioned above.

If the core model has issues, then it is expected to encounter issues with the converted IR too.
According to the native model format inferencing, 91 nodes are not found in the graph cache. Your model might not have the sufficient requirement to be inferred or the topology is not supported.
You may refer [here](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html) to see the supported topologies.

Ori onnx
![ori](https://user-images.githubusercontent.com/79643476/135881375-3a1a9788-bb26-4a4d-a222-553394bb3fb4.png)

myriad FP16 IR

![myriad_FP16](https://user-images.githubusercontent.com/79643476/135881475-e9e62f7b-e426-4e6c-bc63-00414af88785.png)

**Comment by simetin** [comment]
My model is 91 nodes and most of them are supported Onnx operators (Slice, Add, Div, Concat, Mul, etc.). I don't how come 91 nodes be problematic.

**Comment by Iffa-Meah** [comment]
**Not everything in ONNX is supported in OpenVINO**. If your topology is not listed in the documentation I listed above, it means that it is not supported.

**Comment by Erol444** [comment]
Hello @Iffa-Meah, I understand that not every ONNX operation is supported by OpenVINO (or there are some limitations), but from your documentation ([supported onnx layers](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html#onnx_supported_operators)) it's clearly noted that **LessEqual** operation has **no limitations**:
![image](https://user-images.githubusercontent.com/18037362/136025649-909e43e0-06f3-4851-a105-8a6545a5a769.png)
And from the @simetin's post & your screenshot, it looks like there's an issue with **LessEqual** operation. Am I missing something?
Thanks, Erik

**Comment by jgespino** [comment]
Hi @simetin 

Thank you for providing the mode, I just followed up with the development team for an update. I will let you know as soon as I find out more. I apologize for the delay.

Regards,
Jesus

**Comment by jgespino** [comment]
Hi @simetin @Erol444 

I've confirmed with the development team that LessEqual ONNX layer is not currently supported on MYRIAD. I will work with the team to update the [documentation](https://docs.openvino.ai/latest/openvino_docs_IE_DG_supported_plugins_Supported_Devices.html). I apologize for the inconvenience. 

Regards,
Jesus
