### ISSUE TITLE
How to convert the way of load model format opencv to openvino ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [openvinotoolkit/openvino#7808]
Hello,
I got these lines of code to load a model openvino with cv2.dnn.readNet
```
net = cv2.dnn.readNet(face_model_filename_bin,face_model_filename_xml)
blob = cv2.dnn.blobFromImage(img, scalefactor=1.0, size=(img_w_new, img_h_new), mean=(0, 0, 0),
                                     swapRB=True, crop=False)
net.setInput(blob)
```
This model can do inference with this command:
```
heatmap, scale, offset, lms = net.forward(["537", "538", "539", '540'])
```

I try to do the same way without using cv2.dnn.readNet

```
  net_openvino = ie.read_network(model=face_model_filename_xml, weights=face_model_filename_bin)
  net_openvino.batch_size = 1
  exec_net = ie.load_network(network=net_openvino, device_name='CPU')
  input_blob = next(iter(net_openvino.input_info))
```

but i can't not use this command to inference as usual:
```
exec_net.infer(inputs={input_blob: blob})
```
I got this error:
![image](https://user-images.githubusercontent.com/57557628/135700474-ec6dd497-447c-427e-8349-16bcd0cc70e7.png)

I know that it caused by shape of input model is not compatible. But i don't know how to fix it !

Can you give me some advice at this ? Thank you in advance !

Best regard !

**Comment by alalek** [comment]
The following information could help with further investigation:
- link to the used model (or model with random weights)
- used command like for ModelOptimizer (with parameters)
