### ISSUE TITLE
ModuleNotFoundError: No module named 'openvino.tools'

### ISSUE THREAD

**Issue by qin53027** [openvinotoolkit/openvino#7877]
Hi,

I try to run the openvino benchmark using the following command: 

1. run bench mark command

python3 benchmark_app.py -m /home/jiande/program/intel_models/model1/intel/person-detection-retail-0002/FP32/person-detection-retail-0002.xml  -i /home/jiande/Pictures/retail2.jpg -d CPU

2. But I got following error;

Traceback (most recent call last):
  File "benchmark_app.py", line 7, in <module>
    from openvino.tools.benchmark.main import main
ModuleNotFoundError: No module named 'openvino.tools'

3. When I did source, I have got the WARNING message 
source /home/jiande/program/openvino/scripts/setupvars/setupvars.sh

[setupvars.sh] WARNING: Can not find OpenVINO Python binaries by path /home/jiande/program/openvino/scripts/python
[setupvars.sh] WARNING: OpenVINO Python environment does not set properly
[setupvars.sh] OpenVINO environment initialized

4. How I installed the OpenVINO: thrugh the GitHub: https://github.com/openvinotoolkit/openvino

   I do not have problem to run inference on several models.

5.  I did:  export PYTHONPATH=/usr/local/lib/python3.8/dist-packages

It seems t me that, the program run of benchmark is looking for the python3 binding in special way.

Could you please advise?

Thanks
Jimmy

**Comment by qin53027** [comment]
thanks for the good information

**Comment by bigrobinson** [comment]
Sorry to butt in after the fact, but I faced the same problem. The hint is in the command line output from the shell script:

"WARNING: Can not find OpenVINO Python binaries by path /home/jiande/program/openvino/scripts/python"

You have to put the setupvars.sh script in the same directory in which the python binaries were built and installed (your -DCMAKE_INSTALL_PREFIX). If you still have problems with the python version (3.6 through 3.9 are compatible as of this writing), you can make your python version explicit when you source the environment:

`source setupvars.sh -pyver 3.9`
