### ISSUE TITLE
[Bug] GetAvailableDevices function memory leak

### ISSUE THREAD

**Issue by laokingshineUAV** [openvinotoolkit/openvino#7902]
##### System information (version)

- OpenVINO=> openvino_2020.2.120
- Operating System / Platform => ubuntu 16.04
- Compiler => gcc 5.5.0
- Problem classification => model infer

##### Detailed description

GetAvailableDevices function memory leak

**Comment by brmarkus** [comment]
Can you provide more details about how you did the measurement, describing your environment, please? Have you used C/C++ or Python-bindings?
Can you reproduce with the OpenVINO sample "hello_query_device"? Or can you share (snippets of your) code, please?

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to open a new issue, we'll be happy to help you.
