### ISSUE TITLE
integrate openvino with openness network edge

### ISSUE THREAD

**Issue by ishanVshah** [openvinotoolkit/openvino#791]
hello folks,

i have installed openvino consumer and producer application on openness network edge. both consumer and producer application are running on edge nodes as a kubernetes pods.

one another server with GNOME DESKTOP which is seperate server running client-simulator docker container sending the traffic towards openvino pods. (Please take note that selinux and firewalld service is disabled on client-sim server).

Video window is not popping up in GNOME desktop of client-sim machine

once i sending the traffic from client simulator to the edge nodes, below error occurred on terminal.

[root@xxxx clientsim]# ./run-docker.sh
ffplay version 2.8.15 Copyright (c) 2003-2018 the FFmpeg developers
built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
libavutil 54. 31.100 / 54. 31.100
libavcodec 56. 60.100 / 56. 60.100
libavformat 56. 40.101 / 56. 40.101
libavdevice 56. 4.100 / 56. 4.100
libavfilter 5. 40.101 / 5. 40.101
libavresample 2. 1. 0 / 2. 1. 0
libswscale 3. 1.101 / 3. 1.101
libswresample 1. 2.101 / 1. 2.101
libpostproc 53. 3.100 / 53. 3.100
No protocol specified
No protocol specified
Could not initialize SDL - No available video device
(Did you set the DISPLAY variable?)
./tx_video.sh

**Comment by avitial** [comment]
Hi @ishanVshah, I see you posted this in https://github.com/open-ness/specs/issues/28, I'd suggest to continue tracing updates on such issue as the team there would be able to answer your OpenNESS questions better. 

If you have any specific issues or questions in regards to OpenVINO don't hesitate to reach back. Closing this issue.

~Regards,
Luis
