### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by neverstoplearn** [openvinotoolkit/openvino#7927]
(base) zhengxin@zhengxin:~/OpenVINO-YOLOV4$ python object_detection_demo_yolov3_async.py -i cam -m darknet_yolov4.xml  -d CPU
Traceback (most recent call last):
  File "object_detection_demo_yolov3_async.py", line 30, in <module>
    from openvino.inference_engine import IECore
  File "/home/zhengxin/anaconda3/lib/python3.8/site-packages/openvino/inference_engine/__init__.py", line 30, in <module>
    from .ie_api import *
ImportError: /home/zhengxin/anaconda3/lib/python3.8/site-packages/openvino/inference_engine/ie_api.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN15InferenceEngine10IExtension9getOpSetsEv

how can i fix it? thanks.

**Comment by zulkifli-halim** [comment]
@neverstoplearn. Looking at the import error message, it looks like it's pointing to the Intel Distribution of OpenVINO install not built from source. Did you source your environment variables for the Intel Distribution of OpenVINO prior to using the open-source?

Try specifying the environment variables as specified in step 2 of this guide:
[https://www.intel.com/content/www/us/en/support/articles/000057448/software/development-software.html](https://www.intel.com/content/www/us/en/support/articles/000057448/software/development-software.html)

**Comment by neverstoplearn** [comment]
> @neverstoplearn. Looking at the import error message, it looks like it's pointing to the Intel Distribution of OpenVINO install not built from source. Did you source your environment variables for the Intel Distribution of OpenVINO prior to using the open-source?
> 
> Try specifying the environment variables as specified in step 2 of this guide: https://www.intel.com/content/www/us/en/support/articles/000057448/software/development-software.html

I am not build openvino from source, i download the openvino from https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html and  install it , then i use pip install openvino for python . am I wrong?
