### ISSUE TITLE
Op:BatchMatMul is not supported

### ISSUE THREAD

**Issue by xhuan28** [openvinotoolkit/openvino#80]
Hi,
I am working on a project which has an Op of BatchMatMul, but it seems not to be supported by OpenVINO so far. Do you plan to support it in the future release or is there any alternative Op I can use to workaround it currently?

**Comment by xhuan28** [comment]
I managed to replace BatchMatMul with MatMul, but found even MatMul is not supported in R5 release.
[ ERROR ]  List of operations that cannot be converted to IE IR:
[ ERROR ]      MatMul (32)
[ ERROR ]          MatMul
[ ERROR ]          MatMul_1
[ ERROR ]          MatMul_2
[ ERROR ]          MatMul_3
[ ERROR ]          MatMul_4
[ ERROR ]          MatMul_5
[ ERROR ]          MatMul_6
[ ERROR ]          MatMul_7
[ ERROR ]          MatMul_8

**Comment by WilliamZhaoz** [comment]
hi @xhuan28 
have you fix the problem? have you create sumtom layers or ops?
I have the same problem, if you fixed it, please tell me how do you do, thank you.

**Comment by shubha-ramani** [comment]
Dear @WilliamZhaoz 
If it's Tensorflow, MatMul will not be supported til 2019R4 (likely the end of the year-ish timeframe). I'm sorry about this. 

Is it Tensorflow MatMul that you're after ?

Thanks,

Shubha

**Comment by WilliamZhaoz** [comment]
Hi shubha-ramani,
yes, it is an op in Tensorflow.
so before the new version, the only way fix it is I have to write the
custom layer?
That can work, a custom layer, yes?

shubha-ramani <notifications@github.com> 于2019年10月1日周二 上午2:37写道：

**Comment by shubha-ramani** [comment]
@WilliamZhaoz 
Yes of course. You can write a Custom layer for MatMul in the meantime.  Here is some information regarding Custom layers:
[http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_customize_model_optimizer_Extending_Model_Optimizer_with_New_Primitives.html](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_customize_model_optimizer_Extending_Model_Optimizer_with_New_Primitives.html)

[http://docs.openvinotoolkit.org/latest/_docs_IE_DG_Integrate_your_kernels_into_IE.html](http://docs.openvinotoolkit.org/latest/_docs_IE_DG_Integrate_your_kernels_into_IE.html)

**Comment by WilliamZhaoz** [comment]
Okay, thank you shubha-ramani.

shubha-ramani <notifications@github.com> 于2019年10月8日周二 上午1:09写道：

**Comment by lazarevevgeny** [comment]
@xhuan28 the OpenVINO support for BatchMatMul and MatMul has been added. Could you take the latest OpenVINO package or compile OpenVINO from sources and verify?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.
