### ISSUE TITLE
[Bug] Rocket lake Xe GPU needs newer OCL driver

### ISSUE THREAD

**Issue by coneypo** [openvinotoolkit/openvino#8003]
##### System information (version)
- OpenVINO => 2021.4
- Operating System / Platform => Ubutuntu 20.04 / Rocket lake with i9-11900 + Intel UHD 750 (Xe)

##### Detailed description
Rocket lake GPU cannot work with OpenVINO GPU plugin (cannot see GPU from `clinfo` or `hello_query_device`);

Currently in https://github.com/openvinotoolkit/openvino/blob/master/scripts/install_dependencies/install_NEO_OCL_driver.sh#L24

`AVAILABLE_DRIVERS=("19.41.14441" "20.35.17767")`

I have tried on my rocket lake platform, which is not working with `20.35.17767` (also cannot see Rocket lake from following table):
<html>
<body>

Platform | OpenCL | Level Zero
-- | -- | --
Broadwell | 2.1 - Production | -
Skylake | 2.1 - Production | 1.0 - Pre-Release
Kaby Lake | 2.1 - Production | 1.0 - Pre-Release
Coffee Lake | 2.1 - Production | 1.0 - Pre-Release
Ice Lake | 2.1 - Production | 1.0 - Pre-Release
Tiger Lake | 3.0* - Production | 1.0 - Early support
Apollo Lake | 1.2 - Production | -
Gemini Lake | 1.2 - Production | -

</body>
</html>

Newer release works (`21.40.21182` for example):
<html>
<body>

Platform | OpenCL | Level Zero
-- | -- | --
Skylake | 3.0 - Production | 1.2 - Pre-Release
Kaby Lake | 3.0 - Production | 1.2 - Pre-Release
Coffee Lake | 3.0 - Production | 1.2 - Pre-Release
Ice Lake | 3.0 - Production | 1.2 - Pre-Release
Tiger Lake | 3.0 - Production | 1.2 - Pre-Release
Rocket Lake | 3.0 - Production | 1.2 - Pre-Release
Broadwell | 3.0 - Maintenance | -
Apollo Lake | 3.0 - Maintenance | -
Gemini Lake | 3.0 - Maintenance | -
Elkhart Lake | 3.0 - Early support | -

</body>
</html>

After upgrading to latest OCL, I can see Xe graphics from `clinfo`, see GPU from `hello_query_device` and run benchmark with `-d GPU`;

Will we udpate for Rocket lake? Thanks :)

**Comment by Iffa-Meah** [comment]
Hi,

thanks for the info. We'll look further into this.

**Comment by jgespino** [comment]
Hi @coneypo 

Thank you for reporting. Support for this GPU was added in driver version 20.37.17906. I have passed this information to the development team to update the script.

Regards,
Jesus

Ref. 68369

**Comment by coneypo** [comment]
Reopen it and wait the fix

**Comment by awsomecod** [comment]
I have a Rocket Lake CPU with intel UHD 750 GPU. 

The latest release of Intel Compute runtime supports this GPU:

https://github.com/intel/compute-runtime/releases/tag/21.44.21506

However, the following script does not support installation of the above 21.44.21506 release:

https://github.com/openvinotoolkit/openvino/blob/master/scripts/install_dependencies/install_NEO_OCL_driver.sh


Would you please let me know how I can manually make openvino run on UHD 750 GPU? I installed the latest release of Intel Compute runtime note above, but still the result of ``clinfo`` is ``Number of platforms   0``

**Comment by coneypo** [comment]
> I have a Rocket Lake CPU with intel UHD 750 GPU.
> 
> The latest release of Intel Compute runtime supports this GPU:
> 
> https://github.com/intel/compute-runtime/releases/tag/21.44.21506
> 
> However, the following script does not support installation of the above 21.44.21506 release:
> 
> https://github.com/openvinotoolkit/openvino/blob/master/scripts/install_dependencies/install_NEO_OCL_driver.sh
> 
> Would you please let me know how I can manually make openvino run on UHD 750 GPU? I installed the latest release of Intel Compute runtime note above, but still the result of `clinfo` is `Number of platforms 0`

Same HW here, i9-11900 with UHD 750;
Ubuntu 18.04 not working, are you using Ubuntu 20.04?

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



  | Rocket Lake UHD 750 | Rocket Lake UHD 750
-- | -- | --
  | ubuntu 18.04 | ubuntu 20.04
Kernel | 5.4.0-87-generic | 5.11.0-27-generic
ls /dev/dri/ | X | by-path  card0    renderD128
lspci -knn\|grep -A2 VGA | 00:02.0   VGA compatible controller [0300]: Intel Corporation Device [8086:4c8a] (rev   04)           Subsystem: Dell Device [1028:0a58] | 00:02.0   VGA compatible controller [0300]: Intel Corporation Device [8086:4c8a] (rev   04)           DeviceName: OnBoard - Video           Subsystem: Dell Device [1028:0a58]
lshw -c video | *-display UNCLAIMED          description: VGA compatible controller          product: Intel Corporation          vendor: Intel Corporation          physical id: 2          bus info: pci@0000:00:02.0          version: 04          width: 64 bits          clock: 33MHz          capabilities: pciexpress msi pm   vga_controller bus_master cap_list          configuration: latency=0          resources: iomemory:600-5ff   iomemory:400-3ff memory:6000000000-6000ffffff memory:4000000000-400fffffff   ioport:3000(size=64) memory:c0000-dffff | *-display          description: VGA compatible controller          product: Intel Corporation          vendor: Intel Corporation          physical id: 2          bus info: pci@0000:00:02.0          logical name: /dev/fb0          version: 04          width: 64 bits          clock: 33MHz          capabilities: pciexpress msi pm   vga_controller bus_master cap_list rom fb          configuration: depth=32 driver=i915   latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080          resources: iomemory:600-5ff   iomemory:400-3ff irq:126 memory:6000000000-6000ffffff   memory:4000000000-400fffffff ioport:3000(size=64) memory:c0000-dffff
inxi -G | Graphics:  Card: Intel HD Graphics 530              Display Server: Moba/X 1.20.8 drivers: modesetting   (unloaded: fbdev,vesa)              Resolution: 3840x1080@0.00hz              OpenGL: renderer: llvmpipe (LLVM   10.0.0, 256 bits) version: 3.3 Mesa 20.0.8 | Graphics:  Device-1: Intel driver: i915 v: kernel              Display: server: Moba/X 1.20.11 driver: i915   resolution: 3840x1080~N/A              OpenGL: renderer: llvmpipe (LLVM   12.0.0 256 bits) v: 4.5 Mesa 21.0.3
clinfo | Number of   platforms                                 1     Platform Name                                   Clover     Platform Vendor                                 Mesa     Platform Version                                OpenCL 1.1   Mesa 20.0.8     Platform Profile                                FULL_PROFILE     Platform Extensions                             cl_khr_icd     Platform Extensions function suffix             MESA         Platform Name                                   Clover   Number of   devices                                   0       NULL platform   behavior     clGetPlatformInfo(NULL, CL_PLATFORM_NAME,   ...)  Clover     clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL,   ...)   Clover     clCreateContext(NULL, ...) [default]            No devices found in platform     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_DEFAULT)  No devices   found in platform     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_CPU)  No devices found   in platform     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_GPU)  No devices found   in platform     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_ACCELERATOR)  No devices   found in platform     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_CUSTOM)  No devices   found in platform     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_ALL)  No devices found   in platform       ICD loader   properties     ICD loader Name                                 OpenCL ICD   Loader     ICD loader Vendor                               OCL Icd free   software     ICD loader Version                              2.2.11     ICD loader Profile                              OpenCL 2.1 | Number   of platforms                                 2     Platform Name                                   Intel(R)   OpenCL HD Graphics     Platform Vendor                                 Intel(R)   Corporation     Platform Version                                OpenCL 3.0     Platform Profile                                FULL_PROFILE   …           NULL   platform behavior     clGetPlatformInfo(NULL, CL_PLATFORM_NAME,   ...)  Intel(R) OpenCL HD Graphics     clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL,   ...)   Success [INTEL]     clCreateContext(NULL, ...) [default]            Success [INTEL]     clCreateContext(NULL, ...)   [other]               y⚌⚌⚌U     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_DEFAULT)  Success (1)       Platform Name                                 Intel(R)   OpenCL HD Graphics       Device Name                                   Intel(R)   Graphics [0x4c8a]     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_CPU)  No devices found   in platform     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_GPU)  Success (1)       Platform Name                                 Intel(R)   OpenCL HD Graphics       Device Name                                   Intel(R)   Graphics [0x4c8a]     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_ACCELERATOR)  No devices   found in platform     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_CUSTOM)  No devices   found in platform     clCreateContextFromType(NULL,   CL_DEVICE_TYPE_ALL)  Success (1)       Platform Name                                 Intel(R)   OpenCL HD Graphics       Device Name                                   Intel(R)   Graphics [0x4c8a]           …



</div>


</body>

</html>

**Comment by awsomecod** [comment]
Openvino did not complain about not finding the GPU, and the inference actually started. But in the beginning of the inference process, my pc restarted. Below is the details. Should I change the Kernel version? 

| GPU | Rocket Lake UHD 750|
| --- | --- |
|OS| Ubuntu 20.04|
|Kernel | 5.15.2-051502-generic | 
|ls /dev/dri/| by-path  card0  renderD128|
|lspci -knn  \|grep -A2 VGA| 00:02.0 VGA compatible controller [0300]: Intel Corporation RocketLake-S GT1 [UHD Graphics 750] [8086:4c8a] (rev 04)  DeviceName: Onboard - Video Subsystem: Micro-Star International Co., Ltd. [MSI] Device [1462:7d16]|
|lshw -c video| description: VGA compatible controller   product: RocketLake-S GT1 [UHD Graphics 750] vendor: Intel Corporation physical id: 2 bus info: pci@0000:00:02.0 version: 04 width: 64 bits clock: 33MHz capabilities: vga_controller bus_master cap_list configuration: driver=i915 latency=0 resources: irq:141 memory:91000000-91ffffff memory:a0000000-afffffff ioport:4000(size=64) memory:c0000-dffff |
|clinfo|
```Number of platforms  1        
Platform Name  Intel(R) OpenCL HD Graphics 
Platform Vendor   Intel(R) Corporation 
Platform Version    OpenCL 3.0  
Platform Profile        FULL_PROFILE```|

**Comment by awsomecod** [comment]
> Hi @coneypo
> 
> Thank you for reporting. Support for this GPU was added in driver version 20.37.17906. I have passed this information to the development team to update the script.
> 
> Regards, Jesus
> 
> Ref. 68369

Does this mean future release of openvino will support Rocket Lake GPU? Would you please let me know an approximate timeline for this support to become available?

**Comment by awsomecod** [comment]
@coneypo 

I am trying to setup a system with the exact configuration that worked for you. I just installed Ubuntu 20.04 with Kernel 5.11.0-27. However, `clinfo` results in: 

``Number of platforms                               0``

Would you please let me know how you installed OpenCL on Ubuntu 20.04 with 5.11.0-27 kernel?

**Comment by jgespino** [comment]
Hi @awsomecod 

OpenVINO toolkit already supports 11th generation Intel Core processor with Xe architecture. 

You will need to install the driver manually, take a look at the following document.
https://www.intel.com/content/www/us/en/support/articles/000057923/software/development-software.html

Regards,
Jesus

**Comment by awsomecod** [comment]
Hi @jgespino 

I just followed the steps in the link you provided. I no longer receive the following error:

`The inference engine returns error: clGetPlatformIDs error -1001.`

However, when I trigger inference with the `-d GPU` option, the inference stuck and does not proceed. One CPU core is working at 100% utilization as I can see from `top`, but the inference does not complete. The last message printed on terminal is: 

```
/home/awsome/.local/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
```

**Comment by jgespino** [comment]
@awsomecod Could you try running the demo script and provide the full output? Depending on the model, loading to GPU may take longer than CPU as the OpenCL kernels need to be compiled (mentioned [here](https://www.intel.com/content/www/us/en/support/articles/000057525/software/development-software.html)).

```
cd /opt/intel/openvino_2021/deployment_tools/demo
./demo_squeezenet_download_convert_run.sh -d GPU
```

Regards,
Jesus

**Comment by awsomecod** [comment]
> @awsomecod Could you try running the demo script and provide the full output? Depending on the model, loading to GPU may take longer than CPU as the OpenCL kernels need to be compiled (mentioned [here](https://www.intel.com/content/www/us/en/support/articles/000057525/software/development-software.html)).
> 
> ```
> cd /opt/intel/openvino_2021/deployment_tools/demo
> ./demo_squeezenet_download_convert_run.sh -d GPU
> ```
> 
> Regards, Jesus

I run the following demo:

``speech_recognition_deepspeech_demo.py``

Here is the full output I see:

``
/home/awsome/.local/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
``

By the way, `clinfo` produces the following note:

```
	NOTE:	your OpenCL library only supports OpenCL 2.2,
		but some installed platforms support OpenCL 3.0.
		Programs using 3.0 features may crash
		or behave unexpectedly
```

**Comment by coneypo** [comment]
> Hi @jgespino
> 
> I just followed the steps in the link you provided. I no longer receive the following error:
> 
> `The inference engine returns error: clGetPlatformIDs error -1001.`
> 
> However, when I trigger inference with the `-d GPU` option, the inference stuck and does not proceed. One CPU core is working at 100% utilization as I can see from `top`, but the inference does not complete. The last message printed on terminal is:
> 
> ```
> /home/awsome/.local/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>   dtype=np.complex,
> ```

Same issue here with old OCL driver: 20.37.17906 cannot work with Rocket lake iGPU, you will find that it will hang when ``GetAvaiableDevices()`` -> ``GetMetric()`` in IE;

BTW, `hello_query_device` will also hang when querying GPU device, right?

**Comment by coneypo** [comment]
> @coneypo
> 
> I am trying to setup a system with the exact configuration that worked for you. I just installed Ubuntu 20.04 with Kernel 5.11.0-27. However, `clinfo` results in:
> 
> `Number of platforms 0`
> 
> Would you please let me know how you installed OpenCL on Ubuntu 20.04 with 5.11.0-27 kernel?

I installed with https://github.com/intel/compute-runtime/releases/tag/21.42.21270:
```
cd neo
wget https://github.com/intel/compute-runtime/releases/download/21.42.21270/intel-gmmlib_21.2.1_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.8744/intel-igc-core_1.0.8744_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.8744/intel-igc-opencl_1.0.8744_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/21.42.21270/intel-opencl-icd_21.42.021270_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/21.42.21270/intel-level-zero-gpu_1.2.021270_amd64.deb
```

**Comment by coneypo** [comment]
> > @coneypo
> > I am trying to setup a system with the exact configuration that worked for you. I just installed Ubuntu 20.04 with Kernel 5.11.0-27. However, `clinfo` results in:
> > `Number of platforms 0`
> > Would you please let me know how you installed OpenCL on Ubuntu 20.04 with 5.11.0-27 kernel?
> 
> I installed with https://github.com/intel/compute-runtime/releases/tag/21.42.21270:
> 
> ```
> cd neo
> wget https://github.com/intel/compute-runtime/releases/download/21.42.21270/intel-gmmlib_21.2.1_amd64.deb
> wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.8744/intel-igc-core_1.0.8744_amd64.deb
> wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.8744/intel-igc-opencl_1.0.8744_amd64.deb
> wget https://github.com/intel/compute-runtime/releases/download/21.42.21270/intel-opencl-icd_21.42.021270_amd64.deb
> wget https://github.com/intel/compute-runtime/releases/download/21.42.21270/intel-level-zero-gpu_1.2.021270_amd64.deb
> ```

And OCL driver installed on my machine:

```
$ dpkg -l |grep 'igc\|opencl\|gmmlib\|intel-level-ze'
ii  intel-gmmlib                               21.2.1                                amd64        Intel(R) Graphics Memory Management Library Package
ii  intel-igc-core                             1.0.8744                              amd64        Intel(R) Graphics Compiler for OpenCL(TM)
ii  intel-igc-opencl                           1.0.8744                              amd64        Intel(R) Graphics Compiler for OpenCL(TM)
ii  intel-level-zero-gpu                       1.2.021270                            amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.
ii  intel-opencl-icd                           21.42.021270                          amd64        Intel graphics compute runtime for OpenCL
ii  libsigc++-2.0-0v5:amd64                    2.10.2-1build1                        amd64        type-safe Signal Framework for C++ - runtime
ii  ocl-icd-libopencl1:amd64                   2.2.11-1ubuntu1                       amd64        Generic OpenCL ICD Loader
```

**Comment by awsomecod** [comment]
On my pc:

``dpkg -l |grep 'igc\|opencl\|gmmlib\|intel-level-ze'``

```
ii  intel-gmmlib                               20.3.2                                amd64        Intel(R) Graphics Memory Management Library Package

ii  intel-igc-core                             1.0.5353                              amd64        Intel(R) Graphics Compiler for OpenCL(TM)

ii  intel-igc-opencl                           1.0.5353                              amd64        Intel(R) Graphics Compiler for OpenCL(TM)

ii  intel-level-zero-gpu                       1.0.18277                             amd64        Intel(R) Graphics Compute Runtime

ii  intel-opencl                               20.43.18277                           amd64        Intel(R) Graphics Compute Runtime

ii  libsigc++-2.0-0v5:amd64                    2.10.2-1build1                        amd64        type-safe Signal Framework for C++ - runtime

ii  ocl-icd-libopencl1:amd64                   2.2.11-1ubuntu1                       amd64        Generic OpenCL ICD Loader
```

So we both can make openvino see the gpu, but the inference hangs. 

I don't know how to use ``hello_query_device`` to examine the hang. The result of ``python3 hello_query_device.py`` is: 

```
[ INFO ] Creating Inference Engine
[ INFO ] Available devices:
[ INFO ] CPU :
[ INFO ] 	SUPPORTED_METRICS:
[ INFO ] 		AVAILABLE_DEVICES: 
[ INFO ] 		FULL_DEVICE_NAME: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
[ INFO ] 		OPTIMIZATION_CAPABILITIES: WINOGRAD, FP32, FP16, INT8, BIN
[ INFO ] 		RANGE_FOR_ASYNC_INFER_REQUESTS: 1, 1, 1
[ INFO ] 		RANGE_FOR_STREAMS: 1, 16
[ INFO ] 		IMPORT_EXPORT_SUPPORT: True
[ INFO ] 
[ INFO ] 	SUPPORTED_CONFIG_KEYS (default values):
[ INFO ] 		CPU_BIND_THREAD: YES
[ INFO ] 		CPU_THREADS_NUM: 0
[ INFO ] 		CPU_THROUGHPUT_STREAMS: 1
[ INFO ] 		DUMP_EXEC_GRAPH_AS_DOT: 
[ INFO ] 		DYN_BATCH_ENABLED: NO
[ INFO ] 		DYN_BATCH_LIMIT: 0
[ INFO ] 		ENFORCE_BF16: NO
[ INFO ] 		EXCLUSIVE_ASYNC_REQUESTS: NO
[ INFO ] 		PERFORMANCE_HINT: 
[ INFO ] 		PERFORMANCE_HINT_NUM_REQUESTS: 0
[ INFO ] 		PERF_COUNT: NO
[ INFO ] 
[ INFO ] GNA :
[ INFO ] 	SUPPORTED_METRICS:
[ INFO ] 		GNA_LIBRARY_FULL_VERSION: 3.0.0.1377
[ INFO ] 		FULL_DEVICE_NAME: GNA_SW
[ INFO ] 		IMPORT_EXPORT_SUPPORT: True
[ INFO ] 		OPTIMAL_NUMBER_OF_INFER_REQUESTS: 1
[ INFO ] 		AVAILABLE_DEVICES: GNA_SW
[ INFO ] 
[ INFO ] 	SUPPORTED_CONFIG_KEYS (default values):
[ INFO ] 		EXCLUSIVE_ASYNC_REQUESTS: NO
[ INFO ] 		GNA_COMPACT_MODE: NO
[ INFO ] 		GNA_COMPILE_TARGET: 
[ INFO ] 		GNA_DEVICE_MODE: GNA_SW_EXACT
[ INFO ] 		GNA_EXEC_TARGET: 
[ INFO ] 		GNA_FIRMWARE_MODEL_IMAGE: 
[ INFO ] 		GNA_FIRMWARE_MODEL_IMAGE_GENERATION: 
[ INFO ] 		GNA_LIB_N_THREADS: 1
[ INFO ] 		GNA_PRECISION: I16
[ INFO ] 		GNA_PWL_MAX_ERROR_PERCENT: 1.000000
[ INFO ] 		GNA_PWL_UNIFORM_DESIGN: NO
[ INFO ] 		GNA_SCALE_FACTOR: 1.000000
[ INFO ] 		GNA_SCALE_FACTOR_0: 1.000000
[ INFO ] 		PERF_COUNT: NO
[ INFO ] 		SINGLE_THREAD: YES
```

**Comment by coneypo** [comment]
> On my pc:
> 
> `dpkg -l |grep 'igc\|opencl\|gmmlib\|intel-level-ze'`
> 
> ```
> ii  intel-gmmlib                               20.3.2                                amd64        Intel(R) Graphics Memory Management Library Package
> 
> ii  intel-igc-core                             1.0.5353                              amd64        Intel(R) Graphics Compiler for OpenCL(TM)
> 
> ii  intel-igc-opencl                           1.0.5353                              amd64        Intel(R) Graphics Compiler for OpenCL(TM)
> 
> ii  intel-level-zero-gpu                       1.0.18277                             amd64        Intel(R) Graphics Compute Runtime
> 
> ii  intel-opencl                               20.43.18277                           amd64        Intel(R) Graphics Compute Runtime
> 
> ii  libsigc++-2.0-0v5:amd64                    2.10.2-1build1                        amd64        type-safe Signal Framework for C++ - runtime
> 
> ii  ocl-icd-libopencl1:amd64                   2.2.11-1ubuntu1                       amd64        Generic OpenCL ICD Loader
> ```
> 
> So we both can make openvino see the gpu, but the inference hangs.
> 
> I don't know how to use `hello_query_device` to examine the hang. The result of `python3 hello_query_device.py` is:
> 
> ```
> [ INFO ] Creating Inference Engine
> [ INFO ] Available devices:
> [ INFO ] CPU :
> [ INFO ] 	SUPPORTED_METRICS:
> [ INFO ] 		AVAILABLE_DEVICES: 
> [ INFO ] 		FULL_DEVICE_NAME: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
> [ INFO ] 		OPTIMIZATION_CAPABILITIES: WINOGRAD, FP32, FP16, INT8, BIN
> [ INFO ] 		RANGE_FOR_ASYNC_INFER_REQUESTS: 1, 1, 1
> [ INFO ] 		RANGE_FOR_STREAMS: 1, 16
> [ INFO ] 		IMPORT_EXPORT_SUPPORT: True
> [ INFO ] 
> [ INFO ] 	SUPPORTED_CONFIG_KEYS (default values):
> [ INFO ] 		CPU_BIND_THREAD: YES
> [ INFO ] 		CPU_THREADS_NUM: 0
> [ INFO ] 		CPU_THROUGHPUT_STREAMS: 1
> [ INFO ] 		DUMP_EXEC_GRAPH_AS_DOT: 
> [ INFO ] 		DYN_BATCH_ENABLED: NO
> [ INFO ] 		DYN_BATCH_LIMIT: 0
> [ INFO ] 		ENFORCE_BF16: NO
> [ INFO ] 		EXCLUSIVE_ASYNC_REQUESTS: NO
> [ INFO ] 		PERFORMANCE_HINT: 
> [ INFO ] 		PERFORMANCE_HINT_NUM_REQUESTS: 0
> [ INFO ] 		PERF_COUNT: NO
> [ INFO ] 
> [ INFO ] GNA :
> [ INFO ] 	SUPPORTED_METRICS:
> [ INFO ] 		GNA_LIBRARY_FULL_VERSION: 3.0.0.1377
> [ INFO ] 		FULL_DEVICE_NAME: GNA_SW
> [ INFO ] 		IMPORT_EXPORT_SUPPORT: True
> [ INFO ] 		OPTIMAL_NUMBER_OF_INFER_REQUESTS: 1
> [ INFO ] 		AVAILABLE_DEVICES: GNA_SW
> [ INFO ] 
> [ INFO ] 	SUPPORTED_CONFIG_KEYS (default values):
> [ INFO ] 		EXCLUSIVE_ASYNC_REQUESTS: NO
> [ INFO ] 		GNA_COMPACT_MODE: NO
> [ INFO ] 		GNA_COMPILE_TARGET: 
> [ INFO ] 		GNA_DEVICE_MODE: GNA_SW_EXACT
> [ INFO ] 		GNA_EXEC_TARGET: 
> [ INFO ] 		GNA_FIRMWARE_MODEL_IMAGE: 
> [ INFO ] 		GNA_FIRMWARE_MODEL_IMAGE_GENERATION: 
> [ INFO ] 		GNA_LIB_N_THREADS: 1
> [ INFO ] 		GNA_PRECISION: I16
> [ INFO ] 		GNA_PWL_MAX_ERROR_PERCENT: 1.000000
> [ INFO ] 		GNA_PWL_UNIFORM_DESIGN: NO
> [ INFO ] 		GNA_SCALE_FACTOR: 1.000000
> [ INFO ] 		GNA_SCALE_FACTOR_0: 1.000000
> [ INFO ] 		PERF_COUNT: NO
> [ INFO ] 		SINGLE_THREAD: YES
> ```

Old driver like `intel-opencl                               20.43.18277`  on your PC (` intel-opencl-icd                           21.42.021270` on my PC), have you removed old driver and install new one in https://github.com/intel/compute-runtime/releases/tag/21.42.21270?

**Comment by awsomecod** [comment]
I installed [21.42.021270](https://github.com/intel/compute-runtime/releases/tag/21.42.21270)

However, I receive this error now:

```
RuntimeError: Failed to create plugin /home/tidy/Deepvino/openvino/installed/runtime/lib/intel64/libclDNNPlugin.so for device GPU
Please, check your environment
[CLDNN ERROR]. clGetPlatformIDs error -1001
```

These are my current packages:

``
dpkg -l |grep 'igc\|opencl\|gmmlib\|intel-level-ze'
``

```
ii  intel-gmmlib                               21.2.1                                amd64        Intel(R) Graphics Memory Management Library Package

ii  intel-igc-core                             1.0.8744                              amd64        Intel(R) Graphics Compiler for OpenCL(TM)

ii  intel-igc-opencl                           1.0.8744                              amd64        Intel(R) Graphics Compiler for OpenCL(TM)

ii  intel-level-zero-gpu                       1.2.021270                            amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.

rc  intel-opencl                               20.43.18277                           amd64        Intel(R) Graphics Compute Runtime

ii  intel-opencl-icd                           21.42.021270                          amd64        Intel graphics compute runtime for OpenCL

ii  libsigc++-2.0-0v5:amd64                    2.10.2-1build1                        amd64        type-safe Signal Framework for C++ - runtime

ii  ocl-icd-libopencl1:amd64                   2.2.11-1ubuntu1                       amd64        Generic OpenCL ICD Loader
```

**Comment by awsomecod** [comment]
@coneypo 
I finally could run inference on UHD 750 gpu. 

Step 1: I installed [21.42.21270](https://github.com/intel/compute-runtime/releases/tag/21.42.21270). 

Step 2: After installation of [21.42.21270](https://github.com/intel/compute-runtime/releases/tag/21.42.21270), the inference engine was not able to find GPU. I checked and saw `clinfo` results in `Number of platforms 0`. To make `clinfo` see the GPU I ran several commands and I am not sure which one finally resolved the issue. I guess the following commands resolved the issues:

```
sudo usermod -a -G video $LOGNAME
sudo usermod -a -G render $LOGNAME
```
The above commands add the user to video and render groups 

Finally, `clinfo` and the inference engine could see the gpu. Also, the inference could be run on GPU. 

@jgespino 

This [article](https://www.intel.com/content/www/us/en/support/articles/000057923/software/development-software.html) on Intel website needs edit. The article suggests that for running inference on UHD 750, [20.43.18277](https://github.com/intel/compute-runtime/releases/tag/20.43.18277) should be installed. However, [21.42.21270](https://github.com/intel/compute-runtime/releases/tag/21.42.21270) is actually the right release for UHD 750.

**Comment by jgespino** [comment]
The installation script has been updated to install a newer driver and will be available in the next software release.

**Comment by alalek** [comment]
> and will be available in the next software release

BTW, Update is already available on GitHub.

**Comment by jgespino** [comment]
@alalek Thats right, good catch! Here is the pull request: https://github.com/openvinotoolkit/openvino/pull/9801
