### ISSUE TITLE
Speed of inference and CPU core count

### ISSUE THREAD

**Issue by devalexqt** [openvinotoolkit/openvino#8019]
I converted my onnx model to INT8 IR for inference with OpenVino via python. 
Everything woorks good, but then I mesure inference time ( without pre and post processing, just raw time) on Xeon W-2295, I see next picture:
![Time of inference OpenVino](https://user-images.githubusercontent.com/865007/137341047-74fd5539-64ee-4dc4-b695-f0d0b0777fb4.png)

How can I iprove inference time with high core count?
If c++ implementation will be faster that python?

**Comment by devalexqt** [comment]
How to check if avx512_vnii instructions was used?

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
