### ISSUE TITLE
Would InputInfo's getPreProcess() method be implemented in Python?

### ISSUE THREAD

**Issue by chenxiaoyu3** [openvinotoolkit/openvino#81]
https://software.intel.com/en-us/articles/OpenVINO-InferEngine#inpage-nav-9

The C class InputInfo has a `getPreProcess` method used to set the resize algorithm when inferring,
```
 InputInfo::Ptr input_info = network.getInputsInfo().begin()->second;
 std::string input_name = network.getInputsInfo().begin()->first;
 input_info->getPreProcess().setResizeAlgorithm(RESIZE_BILINEAR);
 input_info->setLayout(Layout::NHWC);
 input_info->setPrecision(Precision::U8);

```

but Python interface do not have such a method( precision, layout, shape only).

Resize algorithm is important in our model. Can it be implemented in the python?

Thanks !

**Comment by shubha-ramani** [comment]
Dear chenxiaoyu3, you are correct about this. But good news - we already have plans to include it in the Python interface. We don't have dates as yet but stay tuned ! Thanks for using OpenVino !

Shubha

**Comment by wdkwyf** [comment]
hi, are these api enabled now? I find setLayout is still not supported.

**Comment by ilyachur** [comment]
FYI @akuporos

**Comment by sahira-rizvi** [comment]
Closing. Feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
