### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dimitryn** [openvinotoolkit/openvino#8156]
Hi , we have compilation error when building openvino from sources .
c,make command below stopped working for us on new version,

##### System information (version)
OpenVino Build 2021.4.1
CentOS Linux release 8.3.2011

step to repsoduce :

_git clone https://github.com/openvinotoolkit/openvino.git
git submodule update --init –recursive

mkdir build
cd build

cmake -DENABLE_ALTERNATIVE_TEMP:BOOL="0" -DENABLE_CPPLINT:BOOL="0" -DENABLE_OPENCV:BOOL="0" -DBUILD_SHARED_LIBS:BOOL="0" -DENABLE_CLDNN:BOOL="0" -DENABLE_GNA:BOOL="0" -DENABLE_PROFILING_ITT:BOOL="0" -DBUILD_TESTING:BOOL="0" -DENABLE_SPEECH_DEMO:BOOL="0" -DTREAT_WARNING_AS_ERROR:BOOL="0" -DNGRAPH_ONNX_IMPORT_ENABLE:BOOL="0" -DENABLE_SAMPLES:BOOL="0" -DNGRAPH_TEST_UTIL_ENABLE:BOOL="0" -DENABLE_MYRIAD:BOOL="0" -DENABLE_VPU:BOOL="0" -DTHREADING=SEQ ..

make -j16_

output log :

_**CMake Error at inference-engine/src/legacy_api/CMakeLists.txt:82 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "inference_engine_legacy".

CMake Error at inference-engine/src/low_precision_transformations/CMakeLists.txt:50 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "inference_engine_lp_transformations".

CMake Error at inference-engine/src/snippets/CMakeLists.txt:61 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "inference_engine_snippets".**_

thanks for help

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
