### ISSUE TITLE
any plan to deploy a java-side inference engine?

### ISSUE THREAD

**Issue by ericxsun** [openvinotoolkit/openvino#817]

**Comment by SDxKeeper** [comment]
@ericxsun You can subscribe to #506 pull request which is in progress right now.

**Comment by ericxsun** [comment]
> @ericxsun You can subscribe to #506 pull request which is in progress right now.

Thanks a lot

**Comment by dkurt** [comment]
Java bindings are now in aster branch. Looking forward for any feedback.
