### ISSUE TITLE
[AVX512 in oneDNN slower than AVX2]

### ISSUE THREAD

**Issue by Hap-Zhang** [openvinotoolkit/openvino#8191]
Hi,all

I test the inference time of my ner model with openvino(docker image from docker hub: openvino/ubuntu18_runtime ). OpenVINO uses MKLDNN by default, and use the AVX-512, however when i export MKL_CBWR=AVX2 with non OpenVINO, the inference time is faster than OpenVINO, can i use AVX2 in OpenVINO, and how should i do?

My CPU:Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz

MKL with AVX512: The inference time is 503ms
MKL with AVX2:     The inference time is 320ms
OpenVINO(MKLDNN with AVX512):The inference time is 400ms

**Comment by jgespino** [comment]
Hi @Hap-Zhang 

AVX512 is enabled by default, could you try building OpenVINO from source and disabling AVX512 optimization (`ENABLE_AVX512F=OFF`)? If you could also share your model to reproduce from my end. 

Please take a look at these guides for additional build details/instructions:
https://github.com/openvinotoolkit/openvino/wiki/BuildingCode
https://github.com/openvinotoolkit/openvino/wiki/CMakeOptionsForCustomCompilation

You can verify how the layers are running by using the benchmark app and passing `-pc`.

Regards,
Jesus
