### ISSUE TITLE
when to release one support tensorflow 2.x?

### ISSUE THREAD

**Issue by ericxsun** [openvinotoolkit/openvino#822]

**Comment by dkurt** [comment]
Hi! You can already use SavedModel or convert it to frozen graph if it's a Keras model. Please share a reference to the model so we can reproduce it.

**Comment by ericxsun** [comment]
> Hi! You can already use SavedModel or convert it to frozen graph if it's a Keras model. Please share a reference to the model so we can reproduce it.

Actually, in release 2020-3, the version of tensorflow was restricted to a range `tensorflow>=1.2.0,<2.0.0`, now a new version (2.2.0) has been released [tensorflow-2.2.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0). 

Just wondering when to release a version of openvino to support it?

**Comment by lazarevevgeny** [comment]
@ericxsun , OpenVINO 2020.4 has limited support of TF 2.X. No exact plans for a full support.
