### ISSUE TITLE
plan of resize-11 (opset-11) support

### ISSUE THREAD

**Issue by nai-kon** [openvinotoolkit/openvino#823]
Hi,

I have a pytorch model that has F.interpolate() layer, and wanna convert it to openvino via onnx.

Currently, openvino model optimizer only supports opset-10 (resize-10).
However, onnx's Upsample/Resize result doesn't match Pytorch's Interpolation until opset-11.
The torch.onnx.export() says below warning.
```
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. 
Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
We recommend using opset 11 and above for models using this operator.
```

Is there any plan to support resize-11 soon? (at 2020 R4?)
I really hope it.

**Comment by avitial** [comment]
Hi @nai-kon, as you noted, currently OpenVINO only supports Resize Opset-10 operation. Our team is aware of such and will consider this for future release, thanks for using OpenVINO!

~Luis

**Comment by changhsinlee** [comment]
Thanks @avitial - this is a big problem for PyTorch users trying to run in OpenVINO. I'll be waiting for it too!

**Comment by nai-kon** [comment]
reopen the issue until supported.

**Comment by sasakisasaki** [comment]
Dear Developer,
Thank you for providing us the wonderful framework OpenVINO.
I’m also frequently meet the problem when I convert PyTorch model with opset11 -> ONNX -> OpenVINO IR model.
I’ll be happy if opset11 support gets be available.
Thank you for reading this message and many supports on OpenVINO!

**Comment by lazarevevgeny** [comment]
Hi! The OpenVINO team is working on adding support for Resize-11. There are some PRs related to this already: [operation specification](https://github.com/openvinotoolkit/openvino/pull/1035/) and support for the operation in the [Model Optimizer](https://github.com/openvinotoolkit/openvino/pull/970). Thank you for the feedback and keep using OpenVINO!

**Comment by pluniak** [comment]
@lazarevevgeny Hi! Any updates on this? Will this part of the next OpenVINO toolkit release? When is this expected? We'd ike to move from TFX to OpenVINO model server, so we can better serve PyTorch models and avoid GPU inference. Thanks for any information on this!

**Comment by lazarevevgeny** [comment]
@pluniak, the partial support for Resize-11 (limitations described here https://github.com/openvinotoolkit/openvino/blob/master/docs/MO_DG/prepare_model/Supported_Frameworks_Layers.md) has been added. You can grab the code from the release branch `releases/2021/1` or `master` branch or take the official OpenVINO package which was released just today and try. One of the PRs mentioned by me in the previous comment was abandoned and actual development happened in others :)

Please, provide your feedback!

**Comment by lazarevevgeny** [comment]
No feedback. Assume that everything works. Closing the ticket.
