### ISSUE TITLE
Avoiding dynamic cast to transform precision in gna_plugin/model_quantizer.hpp

### ISSUE THREAD

**Issue by raghuram-sathyamurthy** [openvinotoolkit/openvino#83]
// TODO: probably not the best way of using dynamic cast in order to transform Precision
// one of solution is to create not copyNet overloads, that accepts 2 functors, one for layer copy
// and another one for net copy
auto rawNet = dynamic_cast<InferenceEngine::details::CNNNetworkImpl *>(copiedNet.get());

Can DLDT team work on avoiding dynamic_cast? Or could please provide a workaround for the above line.

**Comment by esmirno** [comment]
Dynamic casts are heavily used across dldt project, fixing this single place probably wont be enough. 
However if you fixed all remained  casts, for that particular one as a workaround I can recommend, to modify CNNNetCopy(model, visitor, precision), and pass precision accordingly to the implementation.
