### ISSUE TITLE
[Support Request] Tensorflow convert .ckpt to .pb then convert via python mo_tf.py

### ISSUE THREAD

**Issue by yc0619** [openvinotoolkit/openvino#8329]
##### Detailed description

`checkpoint_path = ./ckpt/checkpoint.ckpt'

model = ResNetV2((256, 256), image_network=True, print_summary=False)
model.load_weights(checkpoint_path)
model.save('./h5/model.h5')

hfive_model = tf.keras.models.load_model('./h5/model.h5')
tf.saved_model.save(hfive_model, 'model')`

at the terminal i have used the command 
`python mo_tf.py --saved_model_dir <save model dir> --output_dir <output dir> --input_shape (1,3,256,256)`

If i don't give the input shape, the error for no input shape will be raised.

And now these warning are raised:

[ WARNING ] Model Optimizer and Inference Engine versions do no match.
[ WARNING ] Consider building the Inference Engine Python API from sources or reinstall OpenVINO (TM) toolkit using "pip install openvino==2021.4"
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[ WARNING ]  Failed to parse a tensor with Unicode characters. Note that Inference Engine does not support string literals, so the string constant should be eliminated from the graph.
[ WARNING ]  Failed to parse a tensor with Unicode characters. Note that Inference Engine does not support string literals, so the string constant should be eliminated from the graph.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.user_data_repack.UserDataRepack'>): Original placeholders: 'serving_default_input_1, saver_filename'. Freezing was requested for ''. --input_shape was provided without --input. Can not deduce which node shape to override

**Comment by zulkifli-halim** [comment]
Hello @yc0619. Which OpenVINO version did you use? And please share with us your model so that we can take a look at it.

**Comment by yc0619** [comment]
Hi! @zulkifli-halim i have used 2021.4. How could i share the model with you? The checkpoint file is 300mb.

**Comment by zulkifli-halim** [comment]
Hello @yc0619 can you upload the model to google drive and share the link here or you can share the link privately to my email zulkiflix.bin.abdul.halim@intel.com.

**Comment by yc0619** [comment]
Hi @zulkifli-halim ok thanks!

**Comment by zulkifli-halim** [comment]
Hello @yc0619, I'm closing this issue. Feel free to re-open this issue if additional assistance is needed.

**Comment by yc0619** [comment]
OK, thanks. These days i have worked on the training and i have changed the training process. I think i still cant convert it right to ir. I will give a try. When it does not work out, i will write an email to you. Thanks for the help! :)
