### ISSUE TITLE
How to use HDDL without having the hddldaemon.exe terminal

### ISSUE THREAD

**Issue by ibrahimsoliman97** [openvinotoolkit/openvino#8344]
- OpenVINO => 2021.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

Is there a way to hide the hddldaemon.exe terminal when I use the HDDL plugin? Currently, my software has a GUI, and when I am trying to load any OpenVINO model, a hddldaemon terminal will popup and will stay there until i close it by myself. 
I am looking to run this hddldaemon without having a terminal. is it possible? 
I can turn off all the debug messages at the terminal using "info_printer.enable": false at hddl_service.config. But again I want to turn the terminal itself off.

**Comment by zulkifli-halim** [comment]
Hello @ibrahimsoliman97,  currently this is not possible and there is a feature request that has already been opened for this. 

Ref. 35365

**Comment by ibrahimsoliman97** [comment]
Thanks for the info.
How to access this feature request page? i am not sure the Ref number is related to the issue or it is an internal number for the development team.

**Comment by zulkifli-halim** [comment]
Hello @ibrahimsoliman97, you cannot access the page, and the ref no. is for the development team.

**Comment by ibrahimsoliman97** [comment]
Ok, I am closing this issue.
