### ISSUE TITLE
what is the user openvino's password  in docker?

### ISSUE THREAD

**Issue by futureflsl** [openvinotoolkit/openvino#8368]
I pulled https://registry.hub.docker.com/r/openvino/ubuntu18_dev docker.But I find that I don;t konw the user openvino password.So what is the default password

**Comment by coneypo** [comment]
Please run docker with `-itu root` and no password will be needed in docker;

test@test-pc:/home/# sudo docker run -itu root -it --rm openvino/ubuntu18_dev:latest
[setupvars.sh] OpenVINO environment initialized
root@3552126fdf22:/opt/intel/openvino_2021.4.689#

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to open a new issue, we'll be happy to help you.
