### ISSUE TITLE
[Bug]  model init use "GPU", error

### ISSUE THREAD

**Issue by 307509256** [openvinotoolkit/openvino#8422]
- OpenVINO => 2021.4.582
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017
- Problem classification: Model Init
- Framework: pytorch 
- Model name: Matting
```
		_network = ie.LoadNetwork(cnnNetwork, m_deviceName);
		return true;
	}
	catch (exception & e) {
		cout << "exception: " << e.what() << endl;
		return false;
	}
```

result:
```
exception:
C:\j\workspace\private-ci\ie\build-windows-vs2019@2\b\repos\openvino\inference-engine\src\inference_engine\ie_common.cpp:73 program_node: mismatching primitive's type
program_node: mismatching primitive's type
```

search code:
```
typed_program_node<To>& as() {
        if (type() != To::type_id())
            throw std::invalid_argument("program_node: mismatching primitive's type");

        return reinterpret_cast<typed_program_node<To>&>(*this);
    }

    template <class To, class..., class = typename std::enable_if<!std::is_same<To, primitive>::value>::type>
    typed_program_node<To> const& as() const {
        if (type() != To::type_id())
            throw std::invalid_argument("program_node: mismatching primitive's type");

        return reinterpret_cast<typed_program_node<To> const&>(*this);
    }
```

**Comment by brmarkus** [comment]
Have you installed a pre-built version of OpenVINO or have you built it from source code?
What system are you running on, can you provide more details about your CPU and GPU, please?

**Comment by 307509256** [comment]
> Have you installed a pre-built version of OpenVINO or have you built it from source code? What system are you running on, can you provide more details about your CPU and GPU, please?

installed a pre-built version of OpenVINO
PC：  lenovo P1  ， HP
CPU is ok， GPU can not work。

**Comment by brmarkus** [comment]
Does the system has an Intel GPU, or is it another, discrete GPU (like many Laptops have a dedicated, external GPU; a few Laptops have an Intel-CPU with an embedded Intel GPU). OpenVINO supports Intel GPUs only....
Can you provide the output of "hello_query_device", please?
In case you have an Intel-GPU in your system - have you installed the GPU-graphics driver as described under "https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_windows.html#install-gpu"?

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to open a new issue, we'll be happy to help you.
