### ISSUE TITLE
Does OpenVino run threads on isolated cores?

### ISSUE THREAD

**Issue by kiner-shah** [openvinotoolkit/openvino#847]
I was trying to run the `benchmark_app` on Linux machine with 8 cores (4 out of which are isolated). I ran it with 2 inference requests (`-nireq 2`) and 2 streams (`-nstreams 2`) and set CPU binding of threads to YES (`-pin YES`).

I saw using `top` command that only 4 non-isolated cores were used (4 threads on 4 cores), and isolated cores are not touched at all (which is expected). But now, I want it to use the isolated cores as well.

If I were to create a thread manually and if I wanted it to run on an isolated core, I would set its affinity using [pthread_setaffinity_np](https://www.man7.org/linux/man-pages/man3/pthread_setaffinity_np.3.html).

Is there any way to make OpenVINO run threads on isolated cores as well i.e. is there any way I can make OpenVINO set the threads affinity to isolated cores as well?

**Comment by myshevts** [comment]
@kiner-shah , in my above comment I was referring to setting the "entire OS process" (app) affinity via taskset or numactl,  that is respected by the inference threads. 
Do you need smth more fine-grained?

**Comment by kiner-shah** [comment]
@myshevts Yes I understood now. Thanks 😀
