### ISSUE TITLE
Issue installing on nvidia jetson tx2

### ISSUE THREAD

**Issue by antoineTK** [openvinotoolkit/openvino#8472]
Hi team,

I am installing on arm64 nvidia jetson tx2, ubuntu 18.04.

I can build just fine but after installing using `cmake --install . --prefix /opt/intel/openvino` there is no /opt/intel/openvino/deployment_tools/demo and I can not follow the next step of the installation which is to test it with Open Model Zoo.

Thanks for the help

**Comment by zulkifli-halim** [comment]
Hello @antoineTK, Open Model Zoo is a separate folder. It is not created during 'build from source' installation. You can clone the Open Model Zoo repo from this GitHub link: [https://github.com/openvinotoolkit/open_model_zoo.git](https://github.com/openvinotoolkit/open_model_zoo.git).

Then, place the cloned repo in the deployment_tools directory.

**Comment by antoineTK** [comment]
thanks @zulkifli-halim !

i got that and I can do this step fine. By the way I am following this guide (https://github.com/openvinotoolkit/openvino/wiki/BuildingCode#installing).

It's step 3 that doesn't work. As there is no `deployment_tools/demo` directory created during installation so those command lines just fail... 
`cd <INSTALLDIR>\deployment_tools\demo`
`demo_squeezenet_download_convert_run.bat`

**Comment by antoineTK** [comment]
still having issues here, documentation is limited

while invoking cmake I set `ENABLE_MKL_DNN` to `ON` so the inference engine will run on CPU

but the command is not taken into account by cmake as the output shows

```
-- Inference Engine enabled features:
...
--     ENABLE_MKL_DNN = OFF
```
this is the command I am using:

```
cmake -DCMAKE_BUILD_TYPE=Release \
-D ENABLE_OPENCV=OFF \
-D ENABLE_CLDNN=OFF \
-D ENABLE_MYRIAD=OFF \
-D MKLROOT=/home/nvidia/Downloads/mklml/lib \
-D ENABLE_MKL_DNN=ON \
-D ENABLE_PYTHON=ON \
-D PYTHON_EXECUTABLE=`which python3.6` \
-D PYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so \
-D PYTHON_INCLUDE_DIR=/usr/include/python3.6m ..
```

**Comment by zulkifli-halim** [comment]
@antoineTK the MKL_DNN plugin is only for x86 CPUs and will not work with ARM.

**Comment by antoineTK** [comment]
thank you!

so if I am not using a movidius ncs stick there is no way to run openvino on either CPU or GPU on arm? Am I understanding this correctly?

If not, what would my cmake command look like to build openvino for CPU usage?

thanks @zulkifli-halim

**Comment by zulkifli-halim** [comment]
The CPU and GPU plugin support Intel hardware only.
ARM based processor devices such as Jetson is not compatible for the CPU plugin.
The NVIDIA graphics card is also not compatible with OpenVINO and should be used with the CUDA interface instead.
The only compatible devices are MYRIAD devices such as the Neural Compute Stick 2 or Intel® Vision Accelerator.

**Comment by antoineTK** [comment]
thank you @zulkifli-halim, that clears things up

**Comment by zulkifli-halim** [comment]
Closing case. Feel free to open a new issue if you have other inquiries. We'll be happy to help you.
