### ISSUE TITLE
[Improvement Suggestion] add a resize-layer for dynamic input image size

### ISSUE THREAD

**Issue by dnns92** [openvinotoolkit/openvino#8481]
Dear Community,

I think it would be of great help for many developers to add a resize-layer for openvino, that basically resizes an input image of dynamic shape. This could basically wrap or implement the cv::resize(cv::Mat, cv::Mat, cv::INTER_*) function of opencv to resize an input image dynamically for the rest of the network (which can then remain fixed size)

This could be placed well in the model-optimizer with a --dynamic_input flag, that puts a resize layer in front with a variable input. Yes that's slower than loading a designated model, but its also much easier. This way one can maybe even get rid of opencv as a dependency in the code.

Cheers,
Dennis

**Comment by ilya-lavrenov** [comment]
@dnns92 please, see https://github.com/openvinotoolkit/openvino/pull/7583

**Comment by dnns92** [comment]
Thanks, for providing the link. Great Work!
