### ISSUE TITLE
China users cannot access  raw.githubusercontent.com

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/openvino#8492]
.\demo_squeezenet_download_convert_run.bat

.\demo_squeezenet_download_convert_run.bat

----------------------------------
China users cannot access
raw.githubusercontent.com

Can domain names be replaced for China  users

CDN proposal：
raw.openvino.ai

It is difficult to access foreign network environment

Building and buying VPN is an illegal and criminal act in China

**Comment by ilya-lavrenov** [comment]
CC @sammysun0711

**Comment by sammysun0711** [comment]
Hi @monkeycc, ```.\demo_squeezenet_download_convert_run.bat``` demo will download a public SqueezeNet_v1.1 caffe model (deploy.prototxt and squeezenet_v1.1.caffemodel) from original github repo https://github.com/forresti/SqueezeNet/tree/a47b6f13d30985279789d08053d37013d67d131b/SqueezeNet_v1.1, which is unfortunately not hosted by OpenVINO. 

As a quick workaround, you may comment out line 103 for model downloading in ```.\demo_squeezenet_download_convert_run.bat``` as follow:
![image](https://user-images.githubusercontent.com/22404054/141122717-7b558cf3-c978-40e9-8cc7-8ec5ac9679d8.png)
Instead, you can download SqueezeNet_v1.1 from gitee mirror, e.g: https://gitee.com/hedilong/SqueezeNet/tree/master/SqueezeNet_v1.1, then put it into related directory ```models_path```. 

Will it work for you?

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
