### ISSUE TITLE
is it possible to install openvino 2021.4 at conda

### ISSUE THREAD

**Issue by yc0619** [openvinotoolkit/openvino#8508]
i used windows and miniconda. I would like to use pycharm and conda to make predict. I have installed the openvino at conda enviroment with the cmd: pip install openvino
But in pycharm always comes an error: no module named openvino openvino is not a library
Besides, from openvino.inference_engines import IECore is also not possible.

**Comment by yc0619** [comment]
ModuleNotFoundError: No module named 'openvino.inference_engine'; 'openvino' is not a package
And the same error has also raised when i use the virtual enviroment and pip install openvino

**Comment by brmarkus** [comment]
Under MS-Windows using Anaconda I do it like this - from within an Anaconda shell (without admin rights):

If needed, set ENV variables for network-proxies:

```
$> set http_proxy=........add your proxy-URL and port-number
$> set https_proxy=........add your proxy-URL and port-number
```

```
$> conda update conda
$> conda update --all
```

If not already installed:
`$> conda install openvino-ie4py -c intel`
When already installed and want to update/upgrade:
`$> conda update openvino-ie4py -c intel`

Check which version - as of right now (2021-November-9):
```
$>conda list | findstr openvino
openvino-ie               2021.4                intel_689    intel
openvino-ie4py            2021.4                     py37    intel
```

**Comment by yc0619** [comment]
Hi Markus,

i have tried except the first two lines (set http_proxy=...)

i have run the following cmds under my_env
`$> conda update conda
$> conda update --all
$> conda update openvino-ie4py -c intel
`

And i have uninstalled the openvino (which installed from pip install openvino), so that when i write the cmd: `$>conda list | findstr openvino`, i get the same output as you.

But when i test the env in pycharm, the error keeps coming out.
ModuleNotFoundError: No module named 'openvino.inference_engine'; 'openvino' is not a package.

**Comment by brmarkus** [comment]
From within the (Ana-)Conda shell - are you able to just use one of the OpenVINO samples, e.g. "classification_sample.py"?

The sample file uses "from openvino.inference_engine import ... ... ..." - and I see it working.
Maybe this is a "magic conda package search path", used to find and resolve package paths installed under (Ana-)Conda.

I haven't tried to combine "conda env" and "pycharm env".... 
Are you sure your "pycharm env" knows where conda have installed packages?

**Comment by yc0619** [comment]
Hi Markus,

Thanks for the help! I have reinstalled the whole openvino. Before installation, i have make sure, the MSBuild in VSCode, Cmake Version, Python are all correct. Then add conda/envs/myenv/Script to System Variables. Then it all works.

best regards,
Chao

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
