### ISSUE TITLE
symbol lookup error when execute object_detection_sample_ssd

### ISSUE THREAD

**Issue by lynx97** [openvinotoolkit/openvino#852]
When I built Inference Engine with CMake, it had error 
```
CMake Error at docs/template_extension/CMakeLists.txt:13 (add_library):
  Target "template_extension" links to target "IE::inference_engine_c_api"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
```
 I bypassed with commenting line 117 `add_subdirectory(docs)` in CMakeLists.txt
But when I execute `object_detection_sample_ssd` in `bin/intel64/Release` after compiling successfully. It has error that 
`./object_detection_sample_ssd: symbol lookup error: ./object_detection_sample_ssd: undefined symbol: _ZN15InferenceEngine4Core11LoadNetworkERKNS_10CNNNetworkERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapIS9_S9_St4lessIS9_ESaISt4pairISA_S9_EEE`
Thanks

**Comment by lynx97** [comment]
> Could you please try if this helps for the cmake error? #861

Thanks for your helps. But I tried that but it 's still error. 
I compile in docker with Dockerfile followed from official document. I followed from https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#build-on-linux-systems
I used cmake 3.17.3.

**Comment by jgespino** [comment]
Closing, please re-open if assistance is still needed.
