### ISSUE TITLE
Unable to conver centernet_resnet50_v1_fpn_512x512_coco17_tpu from the Tensorflow Object detection API

### ISSUE THREAD

**Issue by dacquaviva** [openvinotoolkit/openvino#8533]
System information (version):

- I am using the https://hub.docker.com/r/openvino/ubuntu20_dev openvino docker image.

I am trying to convert the [centernet_resnet50_v1_fpn_512x512_coco17_tpu](http://download.tensorflow.org/models/object_detection/tf2/20200711/centernet_resnet50_v2_512x512_coco17_tpu-8.tar.gz) from the tensorflow Object detection API. However, reading on the openvino official documentation [Converting TensorFlow* Object Detection API Models ](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html) I don't see the centernet_resnet50_v1_fpn_512x512_coco17_tpu model. Therefore I am not sure whether the model is supported or not by the openvino model optimizer. I wanted to ask, Is there a way to convert it?

Thanks.

**Comment by Iffa-Meah** [comment]
Hi,

unfortunately, as you said, the  centernet_resnet50_v1_fpn_512x512_coco17_tpu model is not listed in the [Tensorflow Supported Topologies](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html#supported-topologies). Hence, this model is expected to be having issues as it is not validated and not supported by OpenVINO.

You may try to consider using the other supported resnet models.

**Comment by dacquaviva** [comment]
I see, Ok thanks for the answer 😄
