### ISSUE TITLE
Error in converting a tensorflow model to OpenVINO IR

### ISSUE THREAD

**Issue by Hap-Zhang** [openvinotoolkit/openvino#8540]
Hi,all

I met a error when converting a pb model to OpenVINO IR in DeepFill. The error lists as follows:

```
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
terminate called after throwing an instance of 'ngraph::NodeValidationFailure'
  what():  Check 'PartialShape::broadcast_merge_into( pshape, node->get_input_partial_shape(i), autob)' failed at core/src/op/util/elementwise_args.cpp:40:
While validating node 'v1::Multiply Multiply_984 (inpaint_net/Reshape_8/Transpose[0]:f32{1,1024,32,32}, inpaint_net/Cast[0]:f32{1,3,1,1}) -> ()' with friendly_name 'Multiply_984':
Argument shapes are inconsistent.
```
The command convert model is :
python3 mo.py --input_model freeze_model_org.pb

The version of OpenVINO is openvino/ubuntu18_dev from docker hub

Has anyone encountered a similar problem？

**Comment by zulkifli-halim** [comment]
Hi @Hap-Zhang, can you share the model, model topology, and any relevant information for us to reproduce the issue.

**Comment by Hap-Zhang** [comment]
Hi, @zulkifli-halim 
Thank you for your attention. The saved model please sees attachment and the topology can shown by netron.
The commad convert model is:
[saved_model.zip](https://github.com/openvinotoolkit/openvino/files/7535332/saved_model.zip)
`python3 mo_tf.py --saved_model_dir ./ --output_dir ./`

**Comment by zulkifli-halim** [comment]
Hi @Hap-Zhang we are trying to convert the model on Docker but it has not succeeded yet. However, the model can be converted to IR successfully if you use our [OpenVINO distribution package](https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_linux.html).

**Comment by Hap-Zhang** [comment]
Hi, @zulkifli-halim 
Is your OpenVINO distribution package built in Linux? I built openvino in Ubuntu 18.04 by OpenVINO distribution package , and it seems that the error still exists...

**Comment by zulkifli-halim** [comment]
I'm using the [Intel® Distribution of OpenVINO™ toolkit](https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_linux.html) and not build from source. 

You can download it from [here](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit-download.html).

**Comment by Hap-Zhang** [comment]
Hi, @zulkifli-halim 
Could you describe it more detailed? For example the os? Ubuntu 18.04 or Centos? And something like as below
![image](https://user-images.githubusercontent.com/32810063/142151373-4227c6ec-3c28-46fa-8ca4-0feb198e306e.png)
I have tried this as you described and the error still exists. Thank you very much.

**Comment by zulkifli-halim** [comment]
My download configuration is similar to the one you have shared above and follows the [steps](https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_linux.html#step-1-install-the-intel-distribution-of-openvino-toolkit-core-components) to install the package. 

Ubuntu 18.04
OpenVINO 2021.4.689
![WhatsApp Image 2021-11-17 at 18 45 00 (1)](https://user-images.githubusercontent.com/79680111/142186750-e02d1daa-625a-4179-8ad2-f7f3c8f50aa5.jpeg)

**Comment by Hap-Zhang** [comment]
Uh... it is really weird. I have no idea...
BTW, @zulkifli-halim  have you noticed all the information in the conversion process, the mo,py generate a xml file and a bin file finally, but there was actually an error before this:
![image](https://user-images.githubusercontent.com/32810063/142204382-43c6ca88-e536-4f6d-9818-b482c62202b0.png)

**Comment by zulkifli-halim** [comment]
@Hap-Zhang does the model works as expected when using TensorFlow? And please share the link to the base model if this was custom trained.

**Comment by Hap-Zhang** [comment]
Hi, @zulkifli-halim  Your support is gratifying. Thank you for your support.
Yes, The model works as expected when using TensorFlow. 
The source code for training this model is in the following file:
https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_model.py
https://github.com/JiahuiYu/generative_inpainting/blob/v2.0.0/inpaint_ops.py

And I found that it seems the dimension after cast op is incorrect during conversion by openvino. The dimension after cast op should [1,1024,1,1], however, it is [1,3,1,1] in openvino model, and caused the above error.
The cast op : https://github.com/JiahuiYu/generative_inpainting/blob/cfc1d41a882dbbe7c2c35446c8e49b81b7ed51ff/inpaint_ops.py#L311

**Comment by jgespino** [comment]
Hi @Hap-Zhang 

The model you are using may not be supported with OpenVINO. However, I am checking with the development team about this custom trained model and why the IR is generated even when the Model Optimizer shows errors.

We do have a pre-trained model and demo for image inpainting available. Could you take a look and see if it meets your project requirements?
https://docs.openvino.ai/latest/omz_demos_image_inpainting_demo_python.html
https://docs.openvino.ai/latest/omz_models_model_gmcnn_places2_tf.html

Regards,
Jesus

Ref. 72871

**Comment by Hap-Zhang** [comment]
@jgespino 
OK, thank you for your kind help and I will have a try.

**Comment by jgespino** [comment]
@jgespino Happy to help, please let me know if the demo/model works for you.

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
