### ISSUE TITLE
object_detection_sample_ssd NonMaxSuppression

### ISSUE THREAD

**Issue by eltonfernando** [openvinotoolkit/openvino#8583]
##### System information (version)

hello i'm trying to use the example object_detection_sample_ssd.py. It seems to me that I still need to apply NonMaxSuppression. how is the SSD block processed here?

 my exit has 3000 box. tentei usar ngraph.non_max_suppression but I can not understand your return. the documentation is very poor about the return of this function, where can i find an example?

**Comment by Iffa-Meah** [comment]
Hi, 

May I know which model are you using with this sample code?
Are there any specific error when you infer the model with this sample?

The object_detection_sample_ssd.py **expects an ssd model** with the output layer as below:

1. Original model: shape - 1, 1, 100, 7 in the format 1, 1, N, 7, where N is the number of detected bounding boxes. For each detection, the description has the format: [image_id, label, conf, x_min, y_min, x_max, y_max], where:

- image_id - ID of the image in the batch
- label - predicted class ID (1..20 - PASCAL VOC defined class ids). Mapping to class names provided by <omz_dir>/data/dataset_classes/voc_20cl_bkgr.txt file.
- conf - confidence for the predicted class
- (x_min, y_min) - coordinates of the top left bounding box corner (coordinates are in normalized format, in range [0, 1])
- (x_max, y_max) - coordinates of the bottom right bounding box corner (coordinates are in normalized format, in range [0, 1])

2. Converted model need to have the shape - 1, 1, 100, 7 in the format 1, 1, N, 7, where N is the number of detected bounding boxes. For each detection, the description has the format: [image_id, label, conf, x_min, y_min, x_max, y_max], where:

- image_id - ID of the image in the batch
- label - predicted class ID (1..20 - PASCAL VOC defined class ids). Mapping to class names provided by <omz_dir>/data/dataset_classes/voc_20cl_bkgr.txt file.
- conf - confidence for the predicted class
- (x_min, y_min) - coordinates of the top left bounding box corner (coordinates are in normalized format, in range [0, 1])
- (x_max, y_max) - coordinates of the bottom right bounding box corner (coordinates are in normalized format, in range [0, 1])

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
