### ISSUE TITLE
[Bug] Master build fails to compile

### ISSUE THREAD

**Issue by mrsabhar-Intel** [openvinotoolkit/openvino#8587]
##### System information (version)
<!-- Example
- OpenVINO => master
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: Compiling OpenVINO failed with below error

"C:\temp\openvino\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\temp\openvino\build\inference-engine\src\cldnn_engine\clDNNPlugin.vcxproj" (default target) (6) ->
       "C:\temp\openvino\build\inference-engine\thirdparty\clDNN\src\clDNN_lib.vcxproj" (default target) (64) ->
       "C:\temp\openvino\build\inference-engine\thirdparty\clDNN\runtime\cldnn_runtime.vcxproj" (default target) (66) ->
       "C:\temp\openvino\build\thirdparty\onednn_gpu_build.vcxproj" (default target) (67) ->
       (CustomBuild target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\temp\openvino\build\CMakeFiles\eac155ff37f0798dfea67ebde2bc8ed2\onednn_gpu_build-build.rule;C:\temp\openvino\build\CMakeFiles\eac155ff37f0798dfea67ebde2bc8ed2\onednn_gpu_build-install.rule;C:\temp\openvino\build\CMakeFiles\3fd9ae4fcac8314c35560563492dfff6\o
       nednn_gpu_build-complete.rule;C:\temp\openvino\build\CMakeFiles\42f04e79ded9207fb595beb79d1a5214\onednn_gpu_build.rule;C:\temp\openvino\thirdparty\CMakeLists.txt' exited with code 1. [C:\temp\openvino\build\thirdparty\onednn_gpu_build.vcxproj

git log

commit 57900a4a18585c33996f5b3b1a10e001b075922b (HEAD -> master, origin/master, origin/HEAD)
Author: Tingqian Li <tingqian.li@intel.com>
Date:   Sat Nov 13 19:05:09 2021 +0800

    Add constructor to allow implict convertion at compile-time but not at run-time (#8525)

    Signed-off-by: Li, Tingqian <tingqian.li@intel.com>

How to reproduce
- Pull latest master
    - Follow cmake pull instructions
- cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release ..
- Fails with onednn_gpu_build.rule

System information
- 11th Gen TGL Platform with iGPU

**Comment by sammysun0711** [comment]
Hi @mrsabhar-Intel, could you please provide more information this issue:  
- On which Operation System you want to build OpenVINO?
- What kind of error you met during building process? 
- Could you please provide example to preproduce the building issue? 

P.S. You may find building instructions for different Operation Systems here: https://github.com/openvinotoolkit/openvino/wiki/BuildingCode

**Comment by mrsabhar-Intel** [comment]
Below system information
- Windows 10 and WIndows 11 (fails on both)
- Error -  Error copying file "C:/temp/openvino/build/thirdparty/onednn_gpu_build//src/onednn_gpu.lib" to "C:/temp/openvino/bin/intel64/onednn_gpu.lib".
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\temp\openvino\build\CMakeFiles\eac155ff37f0798dfea67ebde2bc8ed2\onednn_gpu_build-install.rule;C:\temp\openvino\build\CMakeFiles\3fd9ae4fcac8314c35560563492dfff6\onednn_gpu_build-complete.rule;C:\temp\openvino\build\CMakeFiles\42f04e79ded9207fb595beb79d1a5214\onednn_
gpu_build.rule' exited with code 1. [C:\temp\openvino\build\thirdparty\onednn_gpu_build.vcxproj]

git submodule status
C:\temp\openvino>git submodule status
 63e59ed312ba7a946779596e86124c1633f67607 cmake/developer_package/ncc_naming_style/ncc (v1.0.0-15-g63e59ed)
 5a715df74a92b81235c70802eeed741c936f10a0 inference-engine/thirdparty/mkl-dnn (v0.1-rc-7305-g5a715df74)
 d71ba0cb73616c493d35699a8a9283aa64ef0f6b runtime/bindings/python/thirdparty/pybind11 (v2.7.0-62-gd71ba0cb)
 58b2595a1a95cc807be8bf6222f266a9a1f393a9 thirdparty/ade (v0.1.1f)
 e171aa2d15ed9eb17054558e0b3a6a413bb01067 thirdparty/gflags/gflags (v2.2.2)
 f8bd7cebfb3e6aeefb1d1d93e46a461471e15f57 thirdparty/gtest/gtest (release-1.8.0-2065-gf8bd7ceb)
 5416ee060ad51fd9eac3d6fcd4c7274c1d3370d8 thirdparty/ittapi/ittapi (v3.18.6)
 1d3dc4e7562ac56ee8ab00607af7bd55fb091f22 thirdparty/ocl/cl_headers (v2021.04.29)
 89d843beba559f65e4a77833fcf8604e874a3371 thirdparty/ocl/clhpp_headers (v2.0.14)
 9b5e3849b49a1448996c8b96ba086cd774d987db thirdparty/ocl/icd_loader (v2021.04.29)
 75d978369d0c5be04ec36c3cea2e00a14da1ec83 thirdparty/onednn_gpu (v0.1-rc-7955-g75d978369)
 da889e6b95750350726d149bf447bf0cd1245964 thirdparty/onnx/onnx (v1.10.2-1-gda889e6b)
 52b2447247f535663ac1c292e088b4b27d2910ef thirdparty/protobuf/protobuf (v3.7.0-rc.2-398-g52b244724)
 08b3433180727ea2f78fe02e860a08471db1e03c thirdparty/pugixml (latest)
 8d1e41b650890080fb77548372b6236bbd4079f9 thirdparty/xbyak (v3.71-707-g8d1e41b)
 cacf7f1d4e3d44d871b605da3b647f07d718623f thirdparty/zlib/zlib (v1.2.11)
 b7c83530a470734e3e4bde8fe0d80dcc2d9e9b2c tools/pot/thirdparty/open_model_zoo (2021.1-2985-gb7c83530a)

git log 
commit 57900a4a18585c33996f5b3b1a10e001b075922b (HEAD -> master, origin/master, origin/HEAD)
Author: Tingqian Li <tingqian.li@intel.com>
Date:   Sat Nov 13 19:05:09 2021 +0800

    Add constructor to allow implict convertion at compile-time but not at run-time (#8525)

    Signed-off-by: Li, Tingqian <tingqian.li@intel.com>

I followed the steps in documentation
- git submodule update --init --recursive
- cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release --verbose -j20

**Comment by coneypo** [comment]
Same issue here: I successfully compiled on my windows machine last month with a older commit, but failed to compile now (with https://github.com/openvinotoolkit/openvino/commit/57900a4a18585c33996f5b3b1a10e001b075922b or latest commit), something wrong with onednn in windows:


<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



  | Date | git submodule status | Error log
-- | -- | -- | --
latest | Wed Nov 17   22:46:03 2021       1dbb8910e3bf2aa61df7ed6a3c2e3fc72f345493 | 63e59ed312ba7a946779596e86124c1633f67607   ../cmake/developer_package/ncc_naming_style/ncc (v1.0.0-15-g63e59ed)    5a715df74a92b81235c70802eeed741c936f10a0   ../inference-engine/thirdparty/mkl-dnn (v0.1-rc-7305-g5a715df74)    d71ba0cb73616c493d35699a8a9283aa64ef0f6b   ../runtime/bindings/python/thirdparty/pybind11 (v2.7.0-62-gd71ba0cb)    58b2595a1a95cc807be8bf6222f266a9a1f393a9   ../thirdparty/ade (v0.1.1f)    e171aa2d15ed9eb17054558e0b3a6a413bb01067   ../thirdparty/gflags/gflags (v2.2.2)    f8bd7cebfb3e6aeefb1d1d93e46a461471e15f57   ../thirdparty/gtest/gtest (release-1.8.0-2065-gf8bd7ceb)    5416ee060ad51fd9eac3d6fcd4c7274c1d3370d8   ../thirdparty/ittapi/ittapi (v3.18.6)    1d3dc4e7562ac56ee8ab00607af7bd55fb091f22   ../thirdparty/ocl/cl_headers (v2021.04.29)    89d843beba559f65e4a77833fcf8604e874a3371   ../thirdparty/ocl/clhpp_headers (v2.0.14)    9b5e3849b49a1448996c8b96ba086cd774d987db   ../thirdparty/ocl/icd_loader (v2021.04.29)    75d978369d0c5be04ec36c3cea2e00a14da1ec83   ../thirdparty/onednn_gpu (v0.1-rc-7955-g75d978369)    da889e6b95750350726d149bf447bf0cd1245964   ../thirdparty/onnx/onnx (v1.10.2)    52b2447247f535663ac1c292e088b4b27d2910ef   ../thirdparty/protobuf/protobuf (v3.7.0-rc.2-398-g52b244724)    08b3433180727ea2f78fe02e860a08471db1e03c   ../thirdparty/pugixml (latest)    8d1e41b650890080fb77548372b6236bbd4079f9   ../thirdparty/xbyak (v3.71-707-g8d1e41b)    cacf7f1d4e3d44d871b605da3b647f07d718623f   ../thirdparty/zlib/zlib (v1.2.11)    b7c83530a470734e3e4bde8fe0d80dcc2d9e9b2c   ../tools/pot/thirdparty/open_model_zoo (2021.1-2985-gb7c83530a) | "D:\code\openvino\build\ALL_BUILD.vcxproj" (default target)   (1) ->            "D:\code\openvino\build\inference-engine\src\multi_device\MultiDevicePlugin.vcxproj"   (default target) (8) ->            "D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine.vcxproj"   (default target) (15) ->            "D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj"   (default target) (20          ) ->          (ClCompile target) ->              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(22,49):   error C2039: "SharedObje          ctLoader": ??   "InferenceEngine::details" ???   [D:\code\openvino\build\inference-engine\src\inference_engine\infer          ence_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(22,67):   error C4430: ??????? - ?          ?? int???: C++ ????? int   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxp          roj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(22,67):   error C2143: ????: ??","          (?"&"???)   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(23,5):   error C2511: "ov::runtime          ::RemoteContext::RemoteContext(const   int)":"ov::runtime::RemoteContext"????????????   [D:\code\openvino\build\infe            rence-engine\src\inference_engine\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(23,11):   error C2065: "so": ?????          ??   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(24,13):   error C2065: "impl": ???          ????   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(24,19):   error C2550: "ov::runtim          e::RemoteContext::{ctor}":   ????????????????????????   [D:\code\openvino\build\inference-engine\src\inference_engin          e\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(25,25):   error C2597: ??????"ov::            runtime::RemoteContext::_impl"?????   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engi          ne_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(25,25):   error C3867: "ov::runtim          e::RemoteContext::_impl":   ?????;??? "&" ??????????   [D:\code\openvino\build\inference-engine\src\inference_engine          \inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(33,48):   error C2039: "create_blo          b": ??   "ov::runtime::RemoteContext" ???   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_          engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(35,5):   error C2065: "_impl": ???          ????   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj]                    "D:\code\openvino\build\ALL_BUILD.vcxproj" (default target)   (1) ->            "D:\code\openvino\build\inference-engine\src\cldnn_engine\clDNNPlugin.vcxproj"   (default target) (6) ->            "D:\code\openvino\build\thirdparty\onednn_gpu_build.vcxproj"   (default target) (13) ->          (CustomBuild target) ->            C:\Program Files (x86)\Microsoft   Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.ta          rgets(241,5): error MSB8066: Custom   build for 'D:\code\openvino\build\CMakeFiles\7a42b0916a552ac322bfde5005b3838            2\onednn_gpu_build-mkdir.rule;D:\code\openvino\build\CMakeFiles\7a42b0916a552ac322bfde5005b38382\onednn_gpu_buil            d-download.rule;D:\code\openvino\build\CMakeFiles\7a42b0916a552ac322bfde5005b38382\onednn_gpu_build-update.rule;            D:\code\openvino\build\CMakeFiles\7a42b0916a552ac322bfde5005b38382\onednn_gpu_build-patch.rule;D:\code\openvino\            build\CMakeFiles\7a42b0916a552ac322bfde5005b38382\onednn_gpu_build-configure.rule;D:\code\openvino\build\CMakeFi            les\7a42b0916a552ac322bfde5005b38382\onednn_gpu_build-build.rule;D:\code\openvino\build\CMakeFiles\7a42b0916a552            ac322bfde5005b38382\onednn_gpu_build-install.rule;D:\code\openvino\build\CMakeFiles\5c41d4b653ca0740c3cfe6907526            97cf\onednn_gpu_build-complete.rule;D:\code\openvino\build\CMakeFiles\3cb8c609395dda718f4fab30dc401cb5\onednn_gp          u_build.rule' exited with code 1.   [D:\code\openvino\build\thirdparty\onednn_gpu_build.vcxproj]           1487 Warning(s)       12 Error(s)
11.13 | Sat Nov 13   19:05:09 2021 +0800       57900a4a18585c33996f5b3b1a10e001b075922b | 63e59ed312ba7a946779596e86124c1633f67607   ../cmake/developer_package/ncc_naming_style/ncc (v1.0.0-15-g63e59ed)    5a715df74a92b81235c70802eeed741c936f10a0   ../inference-engine/thirdparty/mkl-dnn (v0.1-rc-7305-g5a715df74)    d71ba0cb73616c493d35699a8a9283aa64ef0f6b   ../runtime/bindings/python/thirdparty/pybind11 (v2.7.0-62-gd71ba0cb)    58b2595a1a95cc807be8bf6222f266a9a1f393a9   ../thirdparty/ade (v0.1.1f)    e171aa2d15ed9eb17054558e0b3a6a413bb01067   ../thirdparty/gflags/gflags (v2.2.2)    f8bd7cebfb3e6aeefb1d1d93e46a461471e15f57   ../thirdparty/gtest/gtest (release-1.8.0-2065-gf8bd7ceb)    5416ee060ad51fd9eac3d6fcd4c7274c1d3370d8   ../thirdparty/ittapi/ittapi (v3.18.6)    1d3dc4e7562ac56ee8ab00607af7bd55fb091f22   ../thirdparty/ocl/cl_headers (v2021.04.29)    89d843beba559f65e4a77833fcf8604e874a3371   ../thirdparty/ocl/clhpp_headers (v2.0.14)    9b5e3849b49a1448996c8b96ba086cd774d987db   ../thirdparty/ocl/icd_loader (v2021.04.29)    75d978369d0c5be04ec36c3cea2e00a14da1ec83   ../thirdparty/onednn_gpu (v0.1-rc-7955-g75d978369)    da889e6b95750350726d149bf447bf0cd1245964   ../thirdparty/onnx/onnx (v1.10.2)    52b2447247f535663ac1c292e088b4b27d2910ef   ../thirdparty/protobuf/protobuf (v3.7.0-rc.2-398-g52b244724)    08b3433180727ea2f78fe02e860a08471db1e03c   ../thirdparty/pugixml (latest)    8d1e41b650890080fb77548372b6236bbd4079f9   ../thirdparty/xbyak (v3.71-707-g8d1e41b)    cacf7f1d4e3d44d871b605da3b647f07d718623f   ../thirdparty/zlib/zlib (v1.2.11)    b7c83530a470734e3e4bde8fe0d80dcc2d9e9b2c   ../tools/pot/thirdparty/open_model_zoo (2021.1-2985-gb7c83530a) | "D:\code\openvino\build\ALL_BUILD.vcxproj" (default target)   (1) ->            "D:\code\openvino\build\inference-engine\src\cldnn_engine\clDNNPlugin.vcxproj"   (default target) (23) ->            "D:\code\openvino\build\inference-engine\thirdparty\clDNN\src\clDNN_lib.vcxproj"   (default target) (25) ->            "D:\code\openvino\build\inference-engine\thirdparty\clDNN\runtime\cldnn_runtime.vcxproj"   (default target) (32) -          >            "D:\code\openvino\build\thirdparty\onednn_gpu_build.vcxproj"   (default target) (73) ->          (CustomBuild target) ->            C:\Program Files (x86)\Microsoft   Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.ta          rgets(241,5): error MSB8066: Custom   build for 'D:\code\openvino\build\CMakeFiles\7a42b0916a552ac322bfde5005b3838            2\onednn_gpu_build-install.rule;D:\code\openvino\build\CMakeFiles\5c41d4b653ca0740c3cfe690752697cf\onednn_gpu_bu            ild-complete.rule;D:\code\openvino\build\CMakeFiles\3cb8c609395dda718f4fab30dc401cb5\onednn_gpu_build.rule'   exit          ed with code 1.   [D:\code\openvino\build\thirdparty\onednn_gpu_build.vcxproj]                    "D:\code\openvino\build\ALL_BUILD.vcxproj" (default target)   (1) ->            "D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj"   (default target) (21          ) ->          (ClCompile target) ->              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(22,49):   error C2039: "SharedObje          ctLoader": ??   "InferenceEngine::details" ???   [D:\code\openvino\build\inference-engine\src\inference_engine\infer          ence_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(22,67):   error C4430: ??????? - ?          ?? int???: C++ ????? int   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxp          roj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(22,67):   error C2143: ????: ??","          (?"&"???)   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(23,5):   error C2511: "ov::runtime          ::RemoteContext::RemoteContext(const   int)":"ov::runtime::RemoteContext"????????????   [D:\code\openvino\build\infe            rence-engine\src\inference_engine\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(23,11):   error C2065: "so": ?????          ??   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(24,13):   error C2065: "impl": ???          ????   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(24,19):   error C2550: "ov::runtim          e::RemoteContext::{ctor}":   ????????????????????????   [D:\code\openvino\build\inference-engine\src\inference_engin          e\inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(25,25):   error C2597: ??????"ov::            runtime::RemoteContext::_impl"?????   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engi          ne_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(25,25):   error C3867: "ov::runtim          e::RemoteContext::_impl":   ?????;??? "&" ??????????   [D:\code\openvino\build\inference-engine\src\inference_engine          \inference_engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(33,48):   error C2039: "create_blo          b": ??   "ov::runtime::RemoteContext" ???   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_          engine_obj.vcxproj]              D:\code\openvino\inference-engine\src\inference_engine\src\remote_context.cpp(35,5):   error C2065: "_impl": ???          ????   [D:\code\openvino\build\inference-engine\src\inference_engine\inference_engine_obj.vcxproj]           1452 Warning(s)       12 Error(s)



</div>


</body>

</html>

**Comment by vladimir-paramuzov** [comment]
@mrsabhar-Intel @coneypo That's a known issue with MSVC generator on windows. We're working on the fix. Meanwhile as a workaround you can use Ninja generator or disable onednn integration for gpu via `-DENABLE_ONENN_FOR_GPU=OFF` cmake option

**Comment by sammysun0711** [comment]
@vladimir-paramuzov, thanks for your Information and help. 
@mrsabhar-Intel, @coneypo I found that this issue was fixed by PR: https://github.com/openvinotoolkit/openvino/pull/8743. 
I have built  commit ```a862331``` with following step on Window 10 SDK 10.0.18362.0 successfully.
```
git submodule update --init --recursive
cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release --verbose -j20
```
Could you please verify if this issue was solved from your side? Thanks!

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to re-open this issue if additional assistance is needed.
