### ISSUE TITLE
[Bug] OpenCV is not available on current platform (Ubuntu 21.04)

### ISSUE THREAD

**Issue by awsomecod** [openvinotoolkit/openvino#8604]
I installed OpenCV on Ubuntu 21.04 using the following command: 

``sudo apt install python3-opencv``

However, running the following command gives me error: 

``
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CLDNN=ON  -DENABLE_PYTHON=ON  -DPYTHON_EXECUTABLE=`which python3.9` \
-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.9.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.9/ ..
``

The error is:

```CMake Warning at inference-engine/cmake/vpu_dependencies.cmake:125 (message):
  VPU_OCL_COMPILER is not found.  Some tests will skipped
Call Stack (most recent call first):
  cmake/dependencies.cmake:55 (include)
  CMakeLists.txt:20 (include)


CMake Error at cmake/dependencies.cmake:235 (message):
  OpenCV is not available on current platform (Ubuntu 21.04)
Call Stack (most recent call first):
  CMakeLists.txt:20 (include)
```

**Comment by zulkifli-halim** [comment]
@awsomecod.  Ubuntu 21.4 version has not been validated, you can refer to this [System Requirements](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_linux.html#system-requirements) for supported Operating Systems.

**Comment by brmarkus** [comment]
(This is because Ubuntu 21.04 is not a LTS version, but e.g. 18.04 or 20.04)

**Comment by alalek** [comment]
It is safe enough:
- to use `-DENABLE_OPENCV=OFF`
- or specify `-DOpenCV_DIR=/usr/lib/x86_64-linux-gnu/cmake/opencv4/`
