### ISSUE TITLE
[Bug]  RuntimeError: Ngraph operation NonZero has dynamic output shape on 0 port

### ISSUE THREAD

**Issue by LYW0288** [openvinotoolkit/openvino#8613]
##### System information (version)
- OpenVINO=> 2020.4
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Framework => TensorFlow

I successfully converted saved_model.pb to IR file by model optimizer, but encountered an error as followed:

    exec_net = ie.load_network(network=self.net, device_name='CPU')
    File "ie_api.pyx", line 372, in openvino.inference_engine.ie_api.IECore.load_network
    File "ie_api.pyx", line 390, in openvino.inference_engine.ie_api.IECore.load_network
    RuntimeError: Ngraph operation NonZero with name StatefulPartitionedCall/model/tf_op_layer_Where/Where/NonZero_ has dynamic output shape on 0 port, but CPU plug-in supports only static shape

The xml file:

```
<layer id="916" name="StatefulPartitionedCall/model/tf_op_layer_Where/Where/NonZero_" type="NonZero" version="opset3">
	<data output_type="i64"/>
	<input>
		<port id="0" precision="BOOL">
			<dim>10647</dim>
		</port>
	</input>
	<output>
		<port id="1" precision="I64">
			<dim>1</dim>
			<dim>10647</dim>
		</port>
	</output>
</layer>

```
##### Steps to reproduce

I trained a yolov3 model on a custom dataset, and converted this Tensorflow model to IR file by followed command: 

    python "C:\Program Files (x86)\Intel\openvino_2021.4.689\deployment_tools\model_optimizer\mo_tf.py" --saved_model_dir=YOLO --output_dir=. --input_shape=[1,416,416,3]

**Comment by zulkifli-halim** [comment]
Hi @LYW0288, Currently NonZero is not supported in the CPU plugin. It will be enabled in the 2022.1 release. There is a pull request regarding this issue: PR [https://github.com/openvinotoolkit/openvino/pull/7957](https://github.com/openvinotoolkit/openvino/pull/7957) and it's already merged.

**Comment by LYW0288** [comment]
Thanks for the info.

**Comment by chuangzhidan** [comment]
i have a similar error occured,"RuntimeError: Ngraph operation **Parameter with name attention_mask** has dynamic output shape on 0 port, but CPU plug-in supports only static shape"
