### ISSUE TITLE
Question: Can I run openvino on integrated and dedicated GPUs?

### ISSUE THREAD

**Issue by awsomecod** [openvinotoolkit/openvino#8670]
If a pc comes with an Intel integrated GPU and an intel Iris Xe dedicated GPU, can I run inference on both of this pc GPUs simultaneously, using the MULTI plugin?

**Comment by brmarkus** [comment]
Yes - requiring proper drivers.
Can you call "hello_query_device" - will both GPUs be detected and listed? Then you can use the listed "classifier" to spell-out each GPU.

**Comment by awsomecod** [comment]
by `hello_query_device` do you mean `hello_query_device.py`?  Would you please write for me the exact code that I should use with `hello_query_device`?

**Comment by awsomecod** [comment]
I just tried the MULTI plugin to use a GPU and a CPU simultaneously.  I received this error:

```
RuntimeError: KEY_MULTI_DEVICE_PRIORITIES key is not set for MULTI device
```

**Comment by brmarkus** [comment]
"hello_query_device" is provided as C/C++ as well as a Python application - choose whatever is better or easier for you (like Python, or you want&need to compile C/C++ code).
Does it show two GPU devices? Does each GPU get a different ID?

Which application have you used and how - where you saw the mentioned runtime error?
Can you try to use one of the OpenVINO/OpenModelZoo samples&demos, first?

Like using "benchmark_app" (or "benchmark_app.py") with e.g. "-d MULTI:my_gpu_id_1:my_gepi_id_2", or "-d MULTI:CPU,GPU", etc.?

**Comment by awsomecod** [comment]
I have an integrated GPU but have not purchased a dedicated one yet. I asked this question to make sure that running inference on multiple GPUs is doable, before I proceed with buying a dedicated GPU. 

Instead of using MULTI plugin, can I run two separate inferences, where each inference use a different GPU?  I mean something like this:

Setting for inference 1: `GPU:my_gpu_id_1` 

Setting for inference 2: `GPU:my_gpu_id_2`

**Comment by brmarkus** [comment]
As long as the GPUs are Intel-GPU (either embedded or discrete) and "new enough" (not very old, see e.g. "https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html" for system-requirements) - then OpenVINO's GPU-plugin will be able to load multiple instances to different physical GPUs - multiple within the same process as well as for multiple different applications.

**Comment by awsomecod** [comment]
Is Intel Xeon Phi Coprocessor a gpu?
As a second gpu, can I use Intel Xeon Phi Coprocessor? 
Does openvino run on Intel Xeon Phi Coprocessor?

**Comment by vladimir-paramuzov** [comment]
@awsomecod you can run inference on multiple GPUs if all of them are visible to OpenVINO. GPU plugin detects and enumerates all supported devices and you can select specific one by GPU.{0,1,2...} names. See https://docs.openvino.ai/2021.4/openvino_docs_IE_DG_supported_plugins_GPU.html#device-naming-convention for more details.

So you can run inference of same network on multi gpus via `MULTI:GPU.1,GPU.0` or load different models to different devices with code like `auto exe_model1 = ie.LoadNetwork(model1, "GPU.0"); auto exe_model2 = ie.LoadNetwork(model2, "GPU.1");`

**Comment by awsomecod** [comment]
So far, Intel Iris Xe DG1 has been the only discrete gpu from intel that came to market. However, this gpu is not available to buy in amazon, ebay, newegg or other websites that I searched. Is there any other gpu that I can use? For instance Radeon?

**Comment by vladimir-paramuzov** [comment]
@awsomecod GPU plugin supports only Intel GPUs. However, you may try CUDA plugin for NVidia GPUs: https://github.com/openvinotoolkit/openvino_cuda_plugin

**Comment by vladimir-paramuzov** [comment]
@awsomecod GPU plugin supports only Intel GPUs.

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
