### ISSUE TITLE
[Bug] Unexpected Error when I use ‘dynamic_axes‘

### ISSUE THREAD

**Issue by RenzeLou** [openvinotoolkit/openvino#8738]
##### Detailed description
Recently, I build a customization model for  **sequence labeling task**. The model structure is similar to [HuggingFace](https://huggingface.co/transformers/model_doc/bert.html?highlight=tokenclassification#transformers.BertForTokenClassification)(i.e., a BERT encoder with a Dense layer). 

To make flexible input batch_size, following the official tutorial and doc. of openvino, I transfer the original `.pt` model to `.onnx` format firstly using [‘dynamic_axes‘](https://pytorch.org/docs/1.8.0/onnx.html?highlight=torch%20onnx%20export#torch.onnx.export)  (some of my codes are as follows):
```python
    model.load_state_dict(torch.load(os.path.join(args.output_dir,"HCT.pt")))
    model.device = torch.device("cpu")
    model.cpu()
    BASE_MODEL_NAME = os.path.join(args.output_dir,"HCT")
    model_path = Path(BASE_MODEL_NAME).with_suffix(".pt")
    onnx_path = model_path.with_suffix(".onnx")
    dummy_input=model.feature2input(train_data[0:16])  ## this line will return a Tuple[Tensor] that can be conveyed to model directly (16 means batch_szie)
 
    input_names = ["input_ids", "attention_mask", "token_type_ids", "label_ids"]
    output_names = ["output", "labels"]

    dynamic_axes = {"input_ids":{0:"batch_size"},
                    "attention_mask":{0:"batch_size"},
                    "token_type_ids":{0:"batch_size"},
                    "label_ids":{0:"batch_size"},
                    "output":{0:"batch_size"},
                    "labels":{0:"batch_size"}}

    '''
    shape of those named params:
    input_ids: [batch_size, max_seq_len]
    attention_mask: [batch_size, max_seq_len]
    token_type_ids: [batch_size, max_seq_len]
    label_ids: [batch_size, max_seq_len]
    output: [batch_size*max_seq_len, label_num]
    labels: [batch_size*max_seq_len]
    '''

    torch.onnx.export(
        model,
        dummy_input,
        onnx_path,
        opset_version=12,
        input_names=input_names,
        output_names=output_names,
        dynamic_axes=dynamic_axes,
        do_constant_folding=False,
    )
    print(f"ONNX model exported to {onnx_path}.")  
```
The operation above had no exception.

Next, when I converted the `.onnx` file into IR formate (i.e., `.bin` and `.xml`) using `mo --input_model "XXX.onnx" --data_type FP16 --output_dir "."`, there is an Error reported:
![image](https://user-images.githubusercontent.com/59914581/142827498-95474c08-20ba-4b38-b116-1cd640a98aad.png)

After consulting several materials, I still have no clue about this problem. I'm sure my `dummy_input` doesn't have any shape and value problems. Why there is a bizarre shape of [-1,1,1,512]?

Best regards！

**Comment by RenzeLou** [comment]
Here, I provide my env:
##### System information (version)

**Comment by RenzeLou** [comment]
Here, I provide my env:
##### System information (version)
- OpenVINO => 2021.4
- Operating System / Platform => Ubuntu 20.04 LTS
- Compiler => Visual Studio 2021
- Problem classification: Customization Requirements
- Framework: Pytorch 1.8.0
- Model name: BERT-base-cased

**Comment by RenzeLou** [comment]
Hi, I have simplified the inference of my model by changing the encoder from BERT to LSTM. Same with aforementioned, however,  there is still an error when I tried to convert `.onnx` into `IR`.

The Warning info of `.onnx`:
![image](https://user-images.githubusercontent.com/59914581/143066591-5216a380-534e-47c6-9a08-4cb785c5b769.png)

The Error info of `IR`:
![image](https://user-images.githubusercontent.com/59914581/143066688-a542fb04-4538-4947-94e7-a5226b5e1c5e.png)

**Comment by jgespino** [comment]
@RenzeLou Could you provide the onnx model?

**Comment by RenzeLou** [comment]
@jgespino 
ok, all my model (including `.pt` `.onnx` `.xml`) are here:
[google driver](https://drive.google.com/drive/folders/1SxKnEmwVqbFCy9Z4OMla3SBKuXMNkgRf?usp=sharing)
Thanks a lot!

**Comment by jgespino** [comment]
Hi @RenzeLou 

Apologies for the delay in my response, dynamic shapes are currently not supported. However, there is [Dynamic Batching](https://docs.openvino.ai/latest/openvino_docs_IE_DG_DynamicBatching.html) that may help if you specify the input shape. Take a look at the documentation as there are some limitations. Please let me know if this would work for your use case.

Regards,
Jesus

**Comment by RenzeLou** [comment]
@jgespino 
No problem at all，I will try this operation later.
Thank you for your kind reply.

**Comment by jgespino** [comment]
@RenzeLou You're welcome, please re-open this issue or start a new issue if you need additional assistance.
