### ISSUE TITLE
How to disable jit dump of dnnl

### ISSUE THREAD

**Issue by laoniangjiu** [openvinotoolkit/openvino#8741]
Hi, 
I run a model on windows pc with cpu, it worked well, but many .bin files were dumped, how can I disable it. By the way, I used c api instead of c++ api.
Thanks. 

![image](https://user-images.githubusercontent.com/79840589/142840976-e1916106-e0c3-4fea-ad4c-b8d46b684297.png)

**Comment by ilya-lavrenov** [comment]
Hi @laoniangjiu
Have you set `MKLDNN_JIT_DUMP` or `DNNL_JIT_DUMP` env variables? If not, jit kernels are not dumped

**Comment by laoniangjiu** [comment]
@ilya-lavrenov Yes, I have set the env variables MKLDNN_JIT_DUMP, but the I can still disable jit dumped by calling the function mkldnn_set_jit_dump(0) when I run the model with mkldnn or dnnl. I there any openvino api can do the same thing?

**Comment by jgespino** [comment]
Hi @laoniangjiu 

I don't believe there is an option to turn this on/off from the OpenVINO API. Instead, setting `DNNL_JIT_DUMP` prior to running your application code should turn on/off the kernel dumps. 

Testing on my system with OpenVINO default configurations kernels are not dump. After setting `DNNL_JIT_DUMP` variable (`set DNNL_JIT_DUMP=1`) and running my c application produced the kernel dumps as you mentioned. Setting `DNNL_JIT_DUMP` to 0 ( `set DNNL_JIT_DUMP=0`) disabled the kernel dumps.

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
