### ISSUE TITLE
[Bug] Raspberry PI 4 - OpenVino does not compile

### ISSUE THREAD

**Issue by woehrl** [openvinotoolkit/openvino#8789]
##### System information (version)
- OpenVINO=> 2021.4.2
- Operating System / Platform => Raspberry PI 4B / Raspberry OS Bullseye distribution (official)
- Compiler => gcc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
- Problem classification => Linking error

##### Detailed description
Even with the latest OpenVINO release a successful built is **not** possible. I read through the following issues in search for a fix: #https://github.com/openvinotoolkit/openvino/issues/2956 #https://github.com/openvinotoolkit/openvino/issues/5485
I edited openvino/ngraph/cmake/external_protobuf.cmake and changed the following code at ~ lines 26-30:
```
if (MSVC)
    set(protobuf_MSVC_STATIC_RUNTIME OFF CACHE BOOL "")
else()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error -latomic")
endif()
```

My configuration is as follows:
```
CFLAGS="-mcpu=cortex-a72 -mfpu=neon-fp-armv8" \
CXXFLAGS="-mcpu=cortex-a72 -mfpu=neon-fp-armv8" \
cmake -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=/opt/intel/openvino \
-DENABLE_MKL_DNN=OFF \
-DENABLE_CLDNN=OFF \
-DENABLE_GNA=OFF \
-DENABLE_SSE42=OFF \
-DTHREADING=SEQ \
-DENABLE_OPENCV=OFF \
-DNGRAPH_PYTHON_BUILD_ENABLE=ON \
-DNGRAPH_ONNX_IMPORT_ENABLE=ON \
-DENABLE_PYTHON=ON \
-DPYTHON_EXECUTABLE=$(which python3.9) \
-DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.9m.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.9 \
-DCMAKE_CXX_FLAGS=-latomic \
-DOPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic ..
```

Still does not compile tho.. Output is still:
```
[ 60%] Linking CXX executable ../../../bin/armv7l/Release/protoc
/usr/bin/ld: ../../../bin/armv7l/Release/lib/libprotobuf.so.3.7.1.0: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [_deps/ext_protobuf-build/CMakeFiles/protoc.dir/build.make:105: ../bin/armv7l/Release/protoc-3.7.1.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:3175: _deps/ext_protobuf-build/CMakeFiles/protoc.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```

**Comment by Iffa-Meah** [comment]
Hi,

Up till this moment, the latest Raspbian 11 (Bullseye) is not validated by OpenVINO. Issues are expected since it is not officially supported by OpenVINO. You may use the Raspbian Buster instead for now.

There's no confirmation of when this Raspbian version will be supported yet.

**Comment by woehrl** [comment]
o/ Iffa-Meah,

thank you for your comment. As Buster is already EOL in next August, and Bullseye is the 1st debian provided from RPi foundation officially also as 64bit variant, and as I currently need to build up a new operating system base for our products, I have some interest on going for Bullseye and try my luck.

What I learned so far:
1) `libprotobuf` - the failing compile from my initial post - is already available in the debian repository and you can disable the protobuf compilation within OpenVINO.
`-DNGRAPH_USE_SYSTEM_PROTOBUF=ON -DProtobuf_INCLUDE_DIR=/usr/include`

2) ONNX_IMPORT is failing on cmake already, so for now I disabled the compile completely as it is not mandatory afai understand (issue postponed for later fix).
`-DNGRAPH_ONNX_IMPORT_ENABLE=OFF`

3) Besides the dependencies mentioned on the [OpenVINO page](https://www.intel.com/content/www/us/en/support/articles/000057005/boards-and-kits.html) the following packages have to be installed as well:
`sudo apt-get install cython3 libprotobuf-dev`

4) `make -j4` would not work as some parts of the compilation process use insane amounts of memory, like this one (1.5G VIRT, 1.3G RES memory):
`[ 62%] Building CXX object ngraph/test/runtime/interpreter/CMakeFiles/interpreter_backend.dir/evaluates_map.cpp.o`
So it's necessary to do (at least parts of the compilation) with `make -j1` (use just 1 cxx process)

5) Next culprit was the following message:
```
[ 96%] Built target compile_tool
make[2]: *** No rule to make target '/usr/lib/arm-linux-gnueabihf/libpython3.9m.so', needed by '../bin/armv7l/Release/lib/python_api/python3.9/openvino/inference_engine/constants.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:5281: inference-engine/ie_bridges/python/src/openvino/inference_engine/CMakeFiles/constants.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```
Seems like OpenVINO is familiar with Python 3.7 and Bullseye brings Python 3.9 without the **shared** library needed (`libpython3.9m.so`). As I could not find this file in any repo package (searching with `dpkg -S libpython3.9m.so`), one way could be to install python 3.9 from sources using pyenv - description [--> here](https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared) but that didn't work out for me neither (no `libpython3.9m.so` built).

So I went for the static library that was already installed (`libpython3.9.so`) and changed my configure accordingly:
`-DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.9.so`

**So in essence, the resulting cmake call looks like this:**
```
LDFLAGS="-L/usr/lib/gcc/arm-linux-gnueabihf/10/ -latomic" \
CFLAGS="-mcpu=cortex-a72 -mfpu=neon-fp-armv8" \
CXXFLAGS="-mcpu=cortex-a72 -mfpu=neon-fp-armv8" \
cmake -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_INSTALL_PREFIX=/opt/intel/openvino \
   -DENABLE_MKL_DNN=OFF \
   -DENABLE_CLDNN=OFF \
   -DENABLE_GNA=OFF \
   -DENABLE_SSE42=OFF \
   -DTHREADING=SEQ \
   -DENABLE_OPENCV=OFF \
   -DNGRAPH_PYTHON_BUILD_ENABLE=ON \
   -DNGRAPH_USE_SYSTEM_PROTOBUF=ON \
   -DProtobuf_INCLUDE_DIR=/usr/include \
   -DNGRAPH_ONNX_IMPORT_ENABLE=OFF \
   -DENABLE_PYTHON=ON \
   -DPYTHON_EXECUTABLE=$(which python3.9) \
   -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.9.so \
   -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 \
   -DCMAKE_CXX_FLAGS=-latomic ..
```

**With those "fixes" I was able to compile OpenVINO on a Raspberry PI 4B with the RPi foundation Bullseye 32Bit distribution.**

**Comment by Iffa-Meah** [comment]
@woehrl , thanks for sharing this information.
We'll make sure these are captured

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by julianx4** [comment]
I tried compiling in the same way on Rasbperry OS 64bit bullseye. Made it to 97%.

`[ 97%] Built target compile_tool
make[2]: *** No rule to make target '/usr/lib/arm-linux-gnueabihf/libpython3.9.so', needed by '../bin/aarch64/Release/lib/python_api/python3.9/openvino/inference_engine/constants.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:5187: inference-engine/ie_bridges/python/src/openvino/inference_engine/CMakeFiles/constants.dir/all] Error 2
make: *** [Makefile:182: all] Error 2`

Any idea?

**Comment by glennford49** [comment]
just build the openvino from source with your bullseye distro, dont use the /opt/intel/openvino_2021, bullseye has  python 3.9 which openvino didnt have the the support yet, I compiled and used it successfully with bullseye 32bit, i think its the same way with 64bit version, but havent tried that yet

**Comment by julianx4** [comment]
Sorry, probably my post was unclear, I said that if I don’t update it further, the issue was solved by pointing to the correct python version. It has compiled without issue after doing that.
