### ISSUE TITLE
what should I do,when I want to convert user-defined yolov3-tiny to openvino model?

### ISSUE THREAD

**Issue by AnnaRose0226** [openvinotoolkit/openvino#88]
If I change the a part of yolov3-tiny,like I drop conv(1024),How can I convert from tensorflow .pb model to openvino .xml model.Thanks a lot.

**Comment by lazarevevgeny** [comment]
@AnnaRose0226 there is an [instruction ](https://docs.openvinotoolkit.org/R5/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html) on how to convert regular YoloV3 (not tiny). You can use this instruction and the custom operations configuration file with the following content to convert the yolo-v3 tiny:

[
  {
    "id": "TFYOLOV3",
    "match_kind": "general",
    "custom_attributes": {
      "classes": 80,
      "anchors": [10, 14, 23, 27, 37, 58, 81, 82, 135, 169, 344, 319],
      "coords": 4,
      "num": 6,
      "mask": [0, 1, 2],
      "entry_points": ["detector/yolo-v3-tiny/Reshape", "detector/yolo-v3-tiny/Reshape_4"]
    }
  }
]

**Comment by AnnaRose0226** [comment]
Thank you for your answer,But I can't rewrite it as you said,Because I changed a lot of the yolov3-tiny,as I test I can't find the yolo-v3-tiny in my computer, and I used 9 anchors,should I changed the anchors and entry_points.How can I do next,Thanks a lot

**Comment by Code-Fight** [comment]
@AnnaRose0226 
Hi,
I do same tried like you.
I changed the conv filters.
First,you should to change this file:[ yolo_tiny.py](https://github.com/mystic123/tensorflow-yolo-v3/blob/136fb66ac4b00e8dfc8391a7ea1c1568a6420206/yolo_v3_tiny.py#L60)
Then,you can convert to" .pb"

But,I tried it,
I generated the IR model but the recognition result is very low.

you can see it:
https://software.intel.com/en-us/forums/computer-vision/topic/828749

**Comment by Code-Fight** [comment]
@AnnaRose0226 I do not konw if you  have any other way.Please tell me. Thanks.

**Comment by lazarevevgeny** [comment]
@AnnaRose0226 The support for Yolo Tiny has been added to the OpenVINO some time ago. Could you check the documentation https://docs.openvinotoolkit.org/2020.2/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html and use the latest OpenVINO version?

**Comment by AnastasiaKazantaeva** [comment]
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.

**Comment by manuiiitv** [comment]
@AnastasiaKazantaeva, @AnnaRose0226, @lazarevevgeny, @Code-Fight  Here is my issue,

Intel openvino version used in deployment setup **openvino_2020.1.023**.
Openvino engines for detection models created on Machine M1.

Deployment Setup 1 :: machine M2
Deployment Setup 2 :: machine M3

CPUs of machine M1, M2 and machine M3 are different.

Everything is same on Deployment setup machines like all the version of the dependencies required and openvino.

Engines generated on machine M1 gives different detections on Machine M2 and Machine M3 with binary generated from same code file written in cpp.

Anyone know what could be the possible reasons for this?

Thanks in advance for your reply.
