### ISSUE TITLE
Failed to convert a onnx model with OpenVINO

### ISSUE THREAD

**Issue by CancelleG** [openvinotoolkit/openvino#8883]
##### System information (version)

- OpenVINO=> 2021.4.2
- Operating System / Platform => centos 7
- Model name: custom model

##### Detailed description
Hi,
I use the docker images of OpenVINO 2021.4.2 named `quay.io/openvino/rhel8_dev` to convert my onnx model. The model contains multiple inputs and multiple outputs. 

when i run the following command: 
`python3 mo_onnx.py --input_model /tmp/models/cvr.onnx --output_dir /tmp/models/openvino/1/ --input dense_input,seq_input,sparse_ids_input,sparse_wgt_input --input_shape [1,438],[1,6,50],[1,79],[1,79]`

output:
```
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      /tmp/models/model.onnx
        - Path for generated IR:        /tmp/models/openvino/1/
        - IR output name:       model
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         dense_input,seq_input,sparse_ids_input,sparse_wgt_input
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,438],[1,6,50],[1,79],[1,79]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
ONNX specific parameters:
        - Inference Engine found in:    /opt/intel/openvino/python/python3.6/openvino
Inference Engine version:       2021.4.2-3974-e2a469a3450-releases/2021/4
Model Optimizer version:        2021.4.2-3974-e2a469a3450-releases/2021/4
terminate called after throwing an instance of 'InferenceEngine::GeneralError'
  what():  Function contains several inputs and outputs with one friendly name!
[ WARNING ]  Using fallback to produce IR.
[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: /tmp/models/openvino/1/model.xml
[ SUCCESS ] BIN file: /tmp/models/openvino/1/model.bin
[ SUCCESS ] Total execution time: 8.16 seconds. 
[ SUCCESS ] Memory consumed: 148 MB.
```

It seems like convert success, while the line `  what():  Function contains several inputs and outputs with one friendly name!` make the later deploy fail with the following error:

`Error: Function contains several inputs and outputs with one friendly name!; occurred during loading CNNNetwork for model: model version: 1`

what's wrong? thanks

**Comment by Iffa-Meah** [comment]
Hi,
if possible, could you share your model?

**Comment by CancelleG** [comment]
> Hi, if possible, could you share your model?, so that we could look further into the issue.

Sorry, the model code is not currently open-source, I need to contact the developer.  I can only share some basic information about the model now. The onnx model is transferred from tensorflow 2.3.1. 

The input names are: dense_input,seq_input,sparse_ids_input,sparse_wgt_input , the input_shape are [1,438],[1,6,50],[1,79],[1,79].

The output names are: ['tf_op_layer_pcvr',
 'tf_op_layer_Sigmoid',
 'tf_op_layer_pctcvr',
 'tf_op_layer_pctr',
 'tf_op_layer_dapan_action',
 'tf_op_layer_delay_time',
 'tf_op_layer_Sigmoid_1',
 'tf_op_layer_pcvr_ctr',
 'tf_op_layer_pctcvr_1']
with the following shape: [(1,), (1,), (1,), (1,), (1,), (1, 2), (1,), (1, 2), (1,)]

**Comment by Iffa-Meah** [comment]
@CancelleG , since that's the case. could you elaborate more regarding your model?
such as the onnx model topology, which OpenVINO sample app did you use to infer it or you did create your own, the purpose of the model (object detection/face detection/etc)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
