### ISSUE TITLE
test failure on certain cache configurations

### ISSUE THREAD

**Issue by notaz** [openvinotoolkit/openvino#89]
The MKLDNNGraphStructureTests.TestNoRedundantReordersRmnet_SSSSD test is failing on certain cache configurations. This was noticed on a kvm vm and should be easily reproducible on any machine with this patch applied: [cache1.patch.txt](https://github.com/opencv/dldt/files/2876169/cache1.patch.txt)

On somewhat related (mkl-dnn?) issue, it also appears get_cache_size() behaves differently in the fallback path compared to the real CPU: when per_core is false, on real CPU L1 and L2 cache sizes are NOT multiplied by core count while in fallback path they are. Note that my vm doesn't use the fallback path, I've only used it in reproducer patch for convenience.

**Comment by shubha-ramani** [comment]
notaz can you kindly attach some sample code ? I need more details regarding the fallback path failure. Much thanks ! Shubha

**Comment by notaz** [comment]
Just run
```
./inference-engine/bin/intel64/Release/InferenceEngineUnitTests --gtest_filter='*TestNoRedundantReordersRmnet*'
```
after applying the patch from description. The patch is needed because the problem only appears if CPU reports specific cache configurations. Alternatively to the patch you can run the test on a Linux kvm virtual machine.

**Comment by shubha-ramani** [comment]
notaz I apologize that it's taken me so long to get back to you. Can you kindly turn on MKL Verbose and attach the output here ?
Here is info on MKL verbose:
[https://software.intel.com/en-us/mkl-windows-developer-guide-using-intel-mkl-verbose-mode](https://software.intel.com/en-us/mkl-windows-developer-guide-using-intel-mkl-verbose-mode)

**Comment by shubha-ramani** [comment]
notaz if you could supply the MKL Verbose that would be great. However, the development team checked and this issue should be fixed in an upcoming OpenVino release.

**Comment by sahira-rizvi** [comment]
Closing. Feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira
