### ISSUE TITLE
error: ‘class dnnl::impl::cpu::x64::jit_generator’ has no member named ‘uni_vpminsd’

### ISSUE THREAD

**Issue by tangjie77wd** [openvinotoolkit/openvino#8949]
##### System information (version)
- OpenVINO => the lastest version
- Operating System / Platform => ubuntu 16.04 LTS
- Compiler => GCC 5.4.0
- Problem classification: compiler error
- Cmake => 3.15.3
- according to: https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux 

##### Detailed description
There is no error when i run cmake like the following shows:
`fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'   git <command> [<revision>...] -- [<file>...]'

    fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

    OpenVINO version is 2022.1.0
    CMAKE_BUILD_TYPE: Release
    Inference Engine enabled features: 

    CI_BUILD_NUMBER: custom_HEAD_HEAD
    ENABLE_LTO = OFF
    OS_FOLDER = OFF
    USE_BUILD_TYPE_SUBFOLDER = ON
    TREAT_WARNING_AS_ERROR = ON
    ENABLE_INTEGRITYCHECK = OFF
    ENABLE_SANITIZER = OFF
    ENABLE_UB_SANITIZER = OFF
    ENABLE_THREAD_SANITIZER = OFF
    ENABLE_COVERAGE = OFF
    ENABLE_SSE42 = ON
    ENABLE_AVX2 = ON
    ENABLE_AVX512F = ON
    BUILD_SHARED_LIBS = ON
    ENABLE_FASTER_BUILD = OFF
    ENABLE_CPPLINT = ON
    ENABLE_CPPLINT_REPORT = OFF
    ENABLE_CLANG_FORMAT = ON
    ENABLE_NCC_STYLE = OFF
    VERBOSE_BUILD = OFF
    ENABLE_UNSAFE_LOCATIONS = OFF
    ENABLE_FUZZING = OFF
    ENABLE_MKL_DNN = ON
    ENABLE_TESTS = OFF
    ENABLE_STRICT_DEPENDENCIES = ON
    ENABLE_CLDNN = OFF
    ENABLE_ONEDNN_FOR_GPU = OFF
    ENABLE_PROFILING_ITT = OFF
    ENABLE_PROFILING_FILTER = ALL
    ENABLE_PROFILING_FIRST_INFERENCE = ON
    SELECTIVE_BUILD = OFF
    ENABLE_ERROR_HIGHLIGHT = OFF
    ENABLE_PYTHON = OFF
    ENABLE_DOCS = OFF
    ENABLE_GNA = OFF
    ENABLE_CLDNN_TESTS = OFF
    THREADING = TBB
    ENABLE_TBBBIND_2_5 = ON
    ENABLE_IR_V7_READER = ON
    ENABLE_GAPI_PREPROCESSING = ON
    ENABLE_MULTI = ON
    ENABLE_HETERO = ON
    ENABLE_TEMPLATE = ON
    ENABLE_VPU = OFF
    ENABLE_MYRIAD = OFF
    ENABLE_MYRIAD_NO_BOOT = OFF
    ENABLE_GAPI_TESTS = OFF
    GAPI_TEST_PERF = OFF
    ENABLE_MYRIAD_MVNC_TESTS = OFF
    ENABLE_DATA = OFF
    ENABLE_BEH_TESTS = OFF
    ENABLE_FUNCTIONAL_TESTS = OFF
    ENABLE_SAMPLES = ON
    ENABLE_OPENCV = ON
    ENABLE_V7_SERIALIZE = OFF
    ENABLE_TBB_RELEASE_ONLY = ON
    ENABLE_SYSTEM_PUGIXML = OFF
    ENABLE_DEBUG_CAPS = OFF
    ENABLE_GPU_DEBUG_CAPS = OFF
    ENABLE_CPU_DEBUG_CAPS = OFF
    NGRAPH_ONNX_FRONTEND_ENABLE = ON
    NGRAPH_PDPD_FRONTEND_ENABLE = ON
    NGRAPH_IR_FRONTEND_ENABLE = ON
    NGRAPH_TF_FRONTEND_ENABLE = ON
    NGRAPH_USE_SYSTEM_PROTOBUF = OFF
    OPENVINO_DEBUG_ENABLE = OFF
    ENABLE_REQUIREMENTS_INSTALL = ON

    MODELS_PATH=
    PROJECT ............................... OpenVINO
    CMAKE_BINARY_DIR ...................... /home/jumper/workspace/openvino/openvino-master/build3rd
    OpenVINO_SOURCE_DIR ................... /home/jumper/workspace/openvino/openvino-master
    CMAKE_GENERATOR ....................... Unix Makefiles
    CMAKE_C_COMPILER_ID ................... GNU
    CMAKE_BUILD_TYPE ...................... Release
    CMAKE_TOOLCHAIN_FILE .................. 
    The name pugixml::static is an ALIAS for pugixml-static. It will be exported to the InferenceEngineDeveloperPackage with the original name.
    The name gflags is an ALIAS for gflags_nothreads_static. It will be exported to the InferenceEngineDeveloperPackage with the original name.

    3.10.0.0
    Found PythonInterp: /usr/local/bin/python3 (found version "3.7.1") 
    Generated: /home/jumper/workspace/openvino/openvino-master/build3rd/thirdparty/onnx/onnx/onnx/onnx_ngraph_onnx-ml.proto
    Generated: /home/jumper/workspace/openvino/openvino-master/build3rd/thirdparty/onnx/onnx/onnx/onnx-operators_ngraph_onnx-ml.proto
    Generated: /home/jumper/workspace/openvino/openvino-master/build3rd/thirdparty/onnx/onnx/onnx/onnx-data_ngraph_onnx.proto

     ******** Summary ********
     CMake version             : 3.15.3
    CMake command             : /usr/local/bin/cmake
    System                    : Linux
    C++ compiler              : /usr/bin/c++
    C++ compiler version      : 5.4.0
    CXX flags                 : -Wsuggest-override   -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong -s -fsigned-char -Werror -ffunction-sections -fdata-sections -fdiagnostics-show-option -Wundef -Wreturn-type -Wunused-variable -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wno-suggest-override -Wnon-virtual-dtor
    Build type                : Release
    Compile definitions       : IE_BUILD_POSTFIX="";ENABLE_MKL_DNN=1;__STDC_FORMAT_MACROS
    CMAKE_PREFIX_PATH         : 
    CMAKE_INSTALL_PREFIX      : /usr/local
    CMAKE_MODULE_PATH         : 

    ONNX version              : 1.10.2
    ONNX NAMESPACE            : ngraph_onnx
    ONNX_USE_LITE_PROTO       : ON
    USE_PROTOBUF_SHARED_LIBS  : OFF
    Protobuf_USE_STATIC_LIBS  : ON
    ONNX_DISABLE_EXCEPTIONS   : OFF
    ONNX_WERROR               : OFF
    ONNX_BUILD_TESTS          : OFF
    ONNX_BUILD_BENCHMARKS     : OFF
    ONNXIFI_DUMMY_BACKEND     : OFF
    ONNXIFI_ENABLE_EXT        : OFF

    Protobuf compiler         : 
    Protobuf includes         : 
    Protobuf libraries        : 
    BUILD_ONNX_PYTHON         : OFF
    The name openvino::pp is an ALIAS for openvino_preprocessor. It will be exported to the InferenceEngineDeveloperPackage with the original name.
    The name openvino::itt is an ALIAS for itt. It will be exported to the InferenceEngineDeveloperPackage with the original name.
    The name openvino::conditional_compilation is an ALIAS for conditional_compilation. It will be exported to the InferenceEngineDeveloperPackage with the original name.
    The name ngraph::builder is an ALIAS for ngraph_builders. It will be exported to the InferenceEngineDeveloperPackage with the original name.
    The name ngraph::reference is an ALIAS for ngraph_reference. It will be exported to the InferenceEngineDeveloperPackage with the original name.
    nGraph unit tests disabled
    DNNL_TARGET_ARCH: X64
    DNNL_LIBRARY_NAME: dnnl
    Found OpenMP_C: -fopenmp  
    Found OpenMP_CXX: -fopenmp  
    Found OpenMP: TRUE   
    TBB: /home/jumper/workspace/openvino/openvino-master/build3rd/temp/tbb
    Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE) 
    Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.7.1", minimum required is "2.7") 
    fatal: 您的当前分支 'master' 尚无任何提交

    Enabled workload: INFERENCE
    Enabled primitives: ALL
    Enabled primitive CPU ISA: ALL
    Primitive cache is disabled
    Static tbbbind_2_5 package is found
    Register template_plugin to be built in build-modules/template_plugin
    CMake Warning at model-optimizer/CMakeLists.txt:5 (message):
    Please enable IE & nGraph Python API (ie_api and offline_transformations_api) targets to enable Model Optimizer target

    Configuring done
    Generating done`

##### Steps to reproduce
However,the following error occurs after i run 'make' in the terminal:
`[ 89%] Built target dnnl_cpu Scanning dependencies of target dnnl

[ 89%] Linking CXX static library ../../../../../bin/intel64/Release/lib/libdnnl.a
[ 89%] Built target dnnl
[ 89%] Generating cross-compiled/proposal_imp_disp.cpp
[ 89%] Generating cross-compiled/AVX2/proposal_imp.cpp
[ 89%] Generating cross-compiled/ANY/proposal_imp.cpp
Scanning dependencies of target MKLDNNPlugin
[ 89%] Building CXX object inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/config.cpp.o
[ 89%] Building CXX object inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/cpu_shape.cpp.o
[ 89%] Building CXX object inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/cpu_types.cpp.o
[ 89%] Building CXX object inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/emitters/jit_eltwise_emitters.cpp.o
/home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/emitters/jit_eltwise_emitters.cpp: In lambda function:
/home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/emitters/jit_eltwise_emitters.cpp:446:38: error: ‘class dnnl::impl::cpu::x64::jit_generator’ has no member named ‘uni_vpminsd’
             case Precision::I32:  h->uni_vpminsd(vmm_dst, vmm_src0, vmm_src1); break;
                                      ^
inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/build.make:117: recipe for target 'inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/emitters/jit_eltwise_emitters.cpp.o' failed
make[2]: *** [inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/emitters/jit_eltwise_emitters.cpp.o] Error 1
CMakeFiles/Makefile2:4458: recipe for target 'inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/all' failed
make[1]: *** [inference-engine/src/mkldnn_plugin/CMakeFiles/MKLDNNPlugin.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2`

#######
I really do not know the reason !!! Does anyone has the same problem ?

**Comment by Iffa-Meah** [comment]
Hi,
I managed to build the latest OpenVINO master branch which would be version 2021.4.2 with Ubuntu 16.04.

This is my cmake version.
![cmakeVersion](https://user-images.githubusercontent.com/79643476/144342615-c89fad25-43fd-4109-aa06-db2d737b4615.png)

the result for "cmake -DCMAKE_BUILD_TYPE=Release .."   ,I disable GPU since I won't be able to use it (I'm using virtual machine). 
Note that you'll need to [Install Intel® Graphics Compute Runtime for OpenCL™ Driver package 19.41.14441](https://github.com/intel/compute-runtime/releases/tag/19.41.14441) before running the build, if you want to use the GPU plugin.
![cmake](https://user-images.githubusercontent.com/79643476/144342906-6e1f61a5-2c99-413f-96c5-08d9edcbb860.png)
![cmake2](https://user-images.githubusercontent.com/79643476/144342917-03e2ebef-898b-410e-b8e0-9a5375a2e379.png)

make --jobs=$(nproc --all)

![make](https://user-images.githubusercontent.com/79643476/144342968-1471f27d-790b-41d4-89bb-e48845952937.png)


Inferencing test
![test](https://user-images.githubusercontent.com/79643476/144343001-b1e64447-37df-40db-b060-25af2f09b7d2.png)



I also need to install the libusb package manually: sudo apt install libusb-1.0-0-dev
Other than this, everything else should works according to the [guide](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux).

**Comment by tangjie77wd** [comment]
> Thanks for your reply ! I noticed that you have not set 'Enabled workload' .Therefore , your 'Enabled workload' is 'TRAINING',right ? However,I set 'Enabled workload:INFERENCE' because i just want to use OpenVINO during 'INFERENCE' .
What's more, i set 'ENABLE_NCC_STYLE=OFF' because the following error occurs if set it 'ON':
`,
    CMake Warning at cmake/developer_package/ncc_naming_style/ncc_naming_style.cmake:56 (message):
  ncc.py is not downloaded via submodule
    Call Stack (most recent call first):
      cmake/developer_package/IEDevScriptsConfig.cmake:311 (include)
      CMakeLists.txt:18 (find_package)
`
And i set 'ENABLE_MKL_DNN=ON'、'ENABLE_GNA=OFF'、'ENABLE_VPU=OFF'、'ENABLE_MYRIAD=OFF' because i just want to get good inference performance on intel core i7-6700.

**Comment by jgespino** [comment]
Hi @tangjie77wd 

OpenVINO toolkit is only for Inference, turning off the other plugins will not improve the CPU plugin performance. It will only reduce the build size which makes sense if you don't need such plugins. 

Could you share your full cmake command?

Regards,
Jesus

**Comment by tangjie77wd** [comment]
> Hi @tangjie77wd
> 
> OpenVINO toolkit is only for Inference, turning off the other plugins will not improve the CPU plugin performance. It will only reduce the build size which makes sense if you don't need such plugins.
> 
> Could you share your full cmake command?
> 
> Regards, Jesus

Here it is:
`
root@jumper-MS-7B47:/home/jumper/workspace/openvino/openvino-master/build# cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CLDNN=OFF ..
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
-- OpenVINO version is 2022.1.0
-- CMAKE_BUILD_TYPE: Release
-- Found libclang: /usr/local/clang_9.0.0/lib/libclang.so.9
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.7.1", minimum required is "3") 
WARNING: Package(s) not found: clang
-- clang package is not installed. Please use "/usr/local/bin/python3 -m pip install clang==9.0".
WARNING: Package(s) not found: pyyaml
-- pyyaml package is not installed. Please use "/usr/local/bin/python3 -m pip install pyyaml".
-- Inference Engine enabled features: 
-- 
--     CI_BUILD_NUMBER: custom_HEAD_HEAD
--     ENABLE_LTO = OFF
--     OS_FOLDER = OFF
--     USE_BUILD_TYPE_SUBFOLDER = ON
--     TREAT_WARNING_AS_ERROR = ON
--     ENABLE_INTEGRITYCHECK = OFF
--     ENABLE_SANITIZER = OFF
--     ENABLE_UB_SANITIZER = OFF
--     ENABLE_THREAD_SANITIZER = OFF
--     ENABLE_COVERAGE = OFF
--     ENABLE_SSE42 = ON
--     ENABLE_AVX2 = ON
--     ENABLE_AVX512F = ON
--     BUILD_SHARED_LIBS = ON
--     ENABLE_FASTER_BUILD = OFF
--     ENABLE_CPPLINT = ON
--     ENABLE_CPPLINT_REPORT = OFF
--     ENABLE_CLANG_FORMAT = ON
--     ENABLE_NCC_STYLE = ON
--     VERBOSE_BUILD = OFF
--     ENABLE_UNSAFE_LOCATIONS = OFF
--     ENABLE_FUZZING = OFF
--     ENABLE_MKL_DNN = ON
--     ENABLE_TESTS = OFF
--     ENABLE_STRICT_DEPENDENCIES = ON
--     ENABLE_CLDNN = OFF
--     ENABLE_ONEDNN_FOR_GPU = OFF
--     ENABLE_PROFILING_ITT = OFF
--     ENABLE_PROFILING_FILTER = ALL
--     ENABLE_PROFILING_FIRST_INFERENCE = ON
--     SELECTIVE_BUILD = OFF
--     ENABLE_ERROR_HIGHLIGHT = OFF
--     ENABLE_PYTHON = OFF
--     ENABLE_DOCS = OFF
--     ENABLE_GNA = OFF
--     ENABLE_CLDNN_TESTS = OFF
--     THREADING = TBB
--     ENABLE_TBBBIND_2_5 = ON
--     ENABLE_IR_V7_READER = ON
--     ENABLE_GAPI_PREPROCESSING = ON
--     ENABLE_MULTI = ON
--     ENABLE_HETERO = ON
--     ENABLE_TEMPLATE = ON
--     ENABLE_VPU = OFF
--     ENABLE_MYRIAD = OFF
--     ENABLE_MYRIAD_NO_BOOT = OFF
--     ENABLE_GAPI_TESTS = OFF
--     GAPI_TEST_PERF = OFF
--     ENABLE_MYRIAD_MVNC_TESTS = OFF
--     ENABLE_DATA = OFF
--     ENABLE_BEH_TESTS = OFF
--     ENABLE_FUNCTIONAL_TESTS = OFF
--     ENABLE_SAMPLES = ON
--     ENABLE_OPENCV = OFF
--     ENABLE_V7_SERIALIZE = OFF
--     ENABLE_TBB_RELEASE_ONLY = ON
--     ENABLE_SYSTEM_PUGIXML = OFF
--     ENABLE_DEBUG_CAPS = OFF
--     ENABLE_GPU_DEBUG_CAPS = OFF
--     ENABLE_CPU_DEBUG_CAPS = OFF
--     NGRAPH_ONNX_FRONTEND_ENABLE = ON
--     NGRAPH_PDPD_FRONTEND_ENABLE = ON
--     NGRAPH_IR_FRONTEND_ENABLE = ON
--     NGRAPH_TF_FRONTEND_ENABLE = ON
--     NGRAPH_USE_SYSTEM_PROTOBUF = OFF
--     OPENVINO_DEBUG_ENABLE = OFF
--     ENABLE_REQUIREMENTS_INSTALL = ON
-- 
-- MODELS_PATH=
-- PROJECT ............................... OpenVINO
-- CMAKE_BINARY_DIR ...................... /home/jumper/workspace/openvino/openvino-master
-- OpenVINO_SOURCE_DIR ................... /home/jumper/workspace/openvino/openvino-master
-- CMAKE_GENERATOR ....................... Unix Makefiles
-- CMAKE_C_COMPILER_ID ................... GNU
-- CMAKE_BUILD_TYPE ...................... Release
-- CMAKE_TOOLCHAIN_FILE .................. 
-- The name pugixml::static is an ALIAS for pugixml-static. It will be exported to the InferenceEngineDeveloperPackage with the original name.
-- The name gflags is an ALIAS for gflags_nothreads_static. It will be exported to the InferenceEngineDeveloperPackage with the original name.
-- 
-- 3.10.0.0
-- Found PythonInterp: /usr/local/bin/python3 (found version "3.7.1") 
Generated: /home/jumper/workspace/openvino/openvino-master/thirdparty/onnx/onnx/onnx/onnx_ngraph_onnx-ml.proto
Generated: /home/jumper/workspace/openvino/openvino-master/thirdparty/onnx/onnx/onnx/onnx-operators_ngraph_onnx-ml.proto
Generated: /home/jumper/workspace/openvino/openvino-master/thirdparty/onnx/onnx/onnx/onnx-data_ngraph_onnx.proto
-- 
-- ******** Summary ********
--   CMake version             : 3.18.4
--   CMake command             : /usr/local/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 5.4.0
--   CXX flags                 : -Wsuggest-override   -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong -s -fsigned-char -Werror -ffunction-sections -fdata-sections -fdiagnostics-show-option -Wundef -Wreturn-type -Wunused-variable -Wuninitialized -Winit-self -Wmaybe-uninitialized -Wno-suggest-override -Wnon-virtual-dtor
--   Build type                : Release
--   Compile definitions       : IE_BUILD_POSTFIX="";ENABLE_MKL_DNN=1;__STDC_FORMAT_MACROS
--   CMAKE_PREFIX_PATH         : 
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         : 
-- 
--   ONNX version              : 1.10.2
--   ONNX NAMESPACE            : ngraph_onnx
--   ONNX_USE_LITE_PROTO       : ON
--   USE_PROTOBUF_SHARED_LIBS  : OFF
--   Protobuf_USE_STATIC_LIBS  : ON
--   ONNX_DISABLE_EXCEPTIONS   : OFF
--   ONNX_WERROR               : OFF
--   ONNX_BUILD_TESTS          : OFF
--   ONNX_BUILD_BENCHMARKS     : OFF
--   ONNXIFI_DUMMY_BACKEND     : OFF
--   ONNXIFI_ENABLE_EXT        : OFF
--
--   Protobuf compiler         : 
--   Protobuf includes         : 
--   Protobuf libraries        : 
--   BUILD_ONNX_PYTHON         : OFF
-- The name openvino::pp is an ALIAS for openvino_preprocessor. It will be exported to the InferenceEngineDeveloperPackage with the original name.
-- The name openvino::itt is an ALIAS for itt. It will be exported to the InferenceEngineDeveloperPackage with the original name.
-- The name openvino::conditional_compilation is an ALIAS for conditional_compilation. It will be exported to the InferenceEngineDeveloperPackage with the original name.
-- The name ngraph::builder is an ALIAS for ngraph_builders. It will be exported to the InferenceEngineDeveloperPackage with the original name.
-- The name ngraph::reference is an ALIAS for ngraph_reference. It will be exported to the InferenceEngineDeveloperPackage with the original name.
-- nGraph unit tests disabled
-- DNNL_TARGET_ARCH: X64
-- DNNL_LIBRARY_NAME: dnnl
-- TBB: /home/jumper/workspace/openvino/openvino-master/temp/tbb
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE) 
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.7.1", minimum required is "2.7") 
fatal: 您的当前分支 'master' 尚无任何提交
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Enabled primitive CPU ISA: ALL
-- Primitive cache is disabled
-- Static tbbbind_2_5 package is found
CMake Warning at samples/cpp/common/format_reader/CMakeLists.txt:21 (message):
  OpenCV is disabled or not found, format_reader will be built without OpenCV
  support

-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
CMake Warning at samples/cpp/benchmark_app/CMakeLists.txt:56 (message):
  OpenCV is disabled or not found, benchmark_app will be built without OpenCV
  support.  Set OpenCV_DIR

CMake Warning at samples/c/common/opencv_c_wrapper/CMakeLists.txt:17 (message):
  OPENCV is disabled or not found, opencv_c_wrapper is built without OPENCV
  support

-- Register template_plugin to be built in build-modules/template_plugin
CMake Warning at model-optimizer/CMakeLists.txt:5 (message):
  Please enable IE & nGraph Python API (ie_api and
  offline_transformations_api) targets to enable Model Optimizer target

-- Configuring done
-- Generating done
-- Build files have been written to: /home/jumper/workspace/openvino/openvino-master
`

And then i run 'make --jobs=$(nproc --all)' . Error occurs as the following shows:
`
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/nodes/mkldnn_tensoriterator_node.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/nodes/mkldnn_tile_node.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/nodes/mkldnn_topk_node.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/nodes/mkldnn_transpose_node.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/nodes/proposal_imp.hpp
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/normalize_preprocess.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/perf_count.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/bfloat16.hpp
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/blob_dump.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/cpu_utils.hpp
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/debug_capabilities.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/general_utils.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/ngraph_utils.hpp
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/node_dumper.h
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/rt_info/memory_formats_attribute.hpp
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/shape_inference/shape_inference.hpp
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/shape_inference/static_dimension.hpp
[ 28%] [cpplint] /home/jumper/workspace/openvino/openvino-master/inference-engine/src/mkldnn_plugin/utils/shape_inference/static_shape.hpp
[ 28%] [cpplint] MKLDNNPlugin_cpplint
[ 28%] Built target MKLDNNPlugin_cpplint
[ 28%] [ncc naming style] ngraph/attribute_adapter.hpp
CMake Error at cmake/developer_package/ncc_naming_style/ncc_run.cmake:38 (message):
  [ncc self check] Self check is not failed for
  /home/jumper/workspace/openvino/openvino-master/cmake/developer_package/ncc_naming_style/self_check/method_name.hpp


CMakeFiles/ncc_all_ncc_check.dir/build.make:98: recipe for target 'ncc_naming_style/method_name.hpp.ncc_style' failed
make[2]: *** [ncc_naming_style/method_name.hpp.ncc_style] Error 1
make[2]: *** Deleting file 'ncc_naming_style/method_name.hpp.ncc_style'
CMakeFiles/Makefile2:2803: recipe for target 'CMakeFiles/ncc_all_ncc_check.dir/all' failed
make[1]: *** [CMakeFiles/ncc_all_ncc_check.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 28%] [ncc naming style] ngraph/attribute_visitor.hpp
[ 28%] [ncc naming style] runtime/common.hpp
[ 28%] [ncc naming style] runtime/core.hpp
[ 28%] [ncc naming style] openvino/util/common_util.hpp
[ 28%] [ncc naming style] ngraph/axis_set.hpp
[ 28%] [ncc naming style] ngraph/axis_vector.hpp
[ 28%] [ncc naming style] ngraph/check.hpp
[ 28%] [ncc naming style] runtime/exception.hpp
[ 28%] [ncc naming style] runtime/executable_network.hpp
[ 28%] [ncc naming style] openvino/util/env_util.hpp
[ 28%] [ncc naming style] ngraph/compatibility.hpp
[ 28%] [ncc naming style] ngraph/coordinate.hpp
[ 28%] [ncc naming style] ngraph/coordinate_diff.hpp
[ 28%] [ncc naming style] runtime/gpu/ocl/dx.hpp
[ 28%] [ncc naming style] runtime/gpu/ocl/ocl.hpp
[ 28%] [ncc naming style] ngraph/deprecated.hpp
[ 28%] [ncc naming style] openvino/util/file_util.hpp
[ 28%] [ncc naming style] ngraph/descriptor/input.hpp
[ 28%] [ncc naming style] ngraph/descriptor/output.hpp
[ 28%] [ncc naming style] runtime/gpu/ocl/ocl_wrapper.hpp
`

**Comment by jgespino** [comment]
Hi @tangjie77wd 

How are you downloading the openvino master branch? Are you cloning or downloading the zip file from GitHub? 

Looking at the cmake output your the HEAD is not pointing to the correct commit. 
`CI_BUILD_NUMBER: custom_HEAD_HEAD`
You should see something like: `CI_BUILD_NUMBER: custom_master_d6094a085adc2367197006b3de7b49450eff368d`

Please try to clone the master branch again and provide the output of `git rev-parse HEAD`.

Regards,
Jesus

**Comment by tangjie77wd** [comment]
> Hi @tangjie77wd
> 
> How are you downloading the openvino master branch? Are you cloning or downloading the zip file from GitHub?
> 
> Looking at the cmake output your the HEAD is not pointing to the correct commit. `CI_BUILD_NUMBER: custom_HEAD_HEAD` You should see something like: `CI_BUILD_NUMBER: custom_master_d6094a085adc2367197006b3de7b49450eff368d`
> 
> Please try to clone the master branch again and provide the output of `git rev-parse HEAD`.
> 
> Regards, Jesus

Thank you ! I downloaded the zip file from Github last week . I will try to download again and check the value of 'CI_BUILD_NUMBER'.

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
