### ISSUE TITLE
Not able to load network for inference engine

### ISSUE THREAD

**Issue by nakul-chakrapani** [openvinotoolkit/openvino#8950]
##### System information (version)

- OpenVINO => 2021.4
- Operating System / Platform => macOS
- Problem classification: Model Loading
- Framework: TensorFlow 
- Model name: Custom InceptionV3 

##### Detailed description
I have a custom Deep learning model based on InceptionV3 which I am trying to run on CPU using OpenVino toolkit. I was able to successfully execute the 'Model Optimizer' step and I got .bin and .xml files. When I am trying to load the model in Inference engine I am facing some problems which I have no idea about. 

I have a simple python script to load the network which looks like below 
`from openvino.inference_engine import IECore, Blob, TensorDesc 

import numpy as np
XML_PATH = "/Users/nchakrapani/ir/amount/saved_model.xml"
BIN_PATH = "/Users/nchakrapani/ir/amount/saved_model.bin"
ie_core_handler = IECore()
network = ie_core_handler.read_network(model=XML_PATH, weights=BIN_PATH)
input_blob = next(iter(network.input_info))
out_blob = next(iter(network.outputs))
executable_network = ie_core_handler.load_network(network, device_name='CPU', num_requests=1)
inference_request = executable_network.requests[0]
print(inference_request)`

I am getting error on this line 
`executable_network = ie_core_handler.load_network(network, device_name='CPU', num_requests=1)`

Error is as follows 
**Traceback (most recent call last):
  File "openvino-infer.py", line 23, in <module>
    executable_network = ie_core_handler.load_network(network, device_name='CPU', num_requests=1)
  File "ie_api.pyx", line 403, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 442, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Unsupported case for conversion**

Unfortunately I can't share my model files to reproduce this issue but if anyone has any idea on how to solve this, I would really appreciate it

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed
