### ISSUE TITLE
Is it possible to leverage openvino tar ball to enable ncs in dldt project?

### ISSUE THREAD

**Issue by RachelRen05** [openvinotoolkit/openvino#90]
Is it possible to leverage openvino tar ball to enable ncs in dldt project? 
And how?
Thank you!

**Comment by shubha-ramani** [comment]
Can you clarify your question RachelRen ? Do you mean does OpenVino support the Movidius stick ? The answer is yes. Kindly look at the examples under https://github.com/opencv/dldt/tree/2018/inference-engine/samples. The way you pass in NCS or MYRIAD is via a -d MYRIAD.

**Comment by RachelRen05** [comment]
@shubha-ramani  
I'm sorry for the ambiguity. I have tried to run the sample with NCS2. 

`./classification_sample -i car.png -m /<path>/alexnet.xml -d MYRIAD
`

But there was an error:

`[ ERROR ] Cannot find plugin to use :`

I have no idea to solve this problem.

**Comment by shubha-ramani** [comment]
hi RachelRen. Can you try putting the -d MYRIAD first  in the command ?

**Comment by RachelRen05** [comment]
@shubha-ramani 
I tried to put the -d MYRIAD first int the command, but still the same error:

`[ ERROR ] Cannot find plugin to use :`

**Comment by shubharamani** [comment]
Did you run the shell script (or bat script if windows) under bin ? You must do this first - it sets environment variables.

**Comment by RachelRen05** [comment]
@shubharamani 

Yes, I have source the environment.

`source /opt/intel/computer_vision_sdk/bin/setupvars.sh`

But, It does not  work.

**Comment by shubharamani** [comment]
Hmmm. That's a red flag. Well if that doesn't work, nothing is going to work.
Can you kindly re-install, following the steps here ? 
[https://software.intel.com/en-us/articles/OpenVINO-Install-Linux](https://software.intel.com/en-us/articles/OpenVINO-Install-Linux)

**Comment by RachelRen05** [comment]
@shubharamani 

I'm sorry, you misunderstood my question, what I want to do is how to make the dldt support NCS.

**Comment by shubharamani** [comment]
So please install R5 of OpenVino. Then carefully follow the above installation steps. RachelRen if your setupvars.sh fails then nothing in OpenVino can work. setupvars.sh succeeding is a first level sanity check. If it fails then something is wrong with your setup/installation.

**Comment by RachelRen05** [comment]
@shubharamani 

setupvars.sh is successful. 

But when I tried to run the sample(https://github.com/opencv/dldt/tree/2018/inference-engine/samples) with NCS2.

`./classification_sample -i car.png -m /<path>/alexnet.xml -d MYRIAD`

there was an error:

`[ ERROR ] Cannot find plugin to use :`

BTW,
When I saw this in dldt readme,

> Inference Engine plugins for Intel® FPGA and Intel® Movidius™ Neural Compute Stick are distributed only in a binary form as a part of Intel® Distribution of OpenVINO™.

I understand that if I want to make dldt support ncs, I just need to install OpenVINO™ binary(https://software.intel.com/en-us/openvino-toolkit),

But, it does not work.

**Comment by shubharamani** [comment]
RachelRen did you configure the USB Driver ? 
[https://software.intel.com/en-us/neural-compute-stick/get-started](https://software.intel.com/en-us/neural-compute-stick/get-started)

**Comment by joeymorrow** [comment]
Notice you have to run 'source' command every time you open a
terminal/session:

source /opt/intel/computer_vision_sdk/bin/setupvars.sh

Before you can run:

./classification_sample -i car.png -m /<path>/alexnet.xml -d MYRIAD

Every time you close the terminal/session, the environment is lost. It's
just a thing developers deal with. You can around this by appending the
'source' command above do your~/.basrch file. This can be cumbersome though
if your OS environment won't be used solely for OpenVINO.

I hope this is the issue.

Good luck!

---

If that doesn't work and you want to try something before reinstalling
OpenVINO, try the running "env" in your terminal and share the output of
all your environment variabes here if you're willing to share more about
your environment.

What we're looking for is to cross-check the environment variables set by
the setupvars.sh script and what's set in your environment. This is just
sanity checking to ensure something didn't go wrong and is set to something
unexpected. It will be useful for this community to find the corner and
unexpected casesof this one.

A pro tip: In case your environment doesn't have the 'source' utility and
you're simply issuing "./source" instead, use '.' in lieu of 'source' as
follows:

. /opt/intel/computer_vision_sdk/bin/setupvars.sh

We appreciate your interest, usage, and inclusion in this community! We'll
standby until it works for you. :)

**Comment by RachelRen05** [comment]
@shubharamani @joeymorrow 
I have configured the USB Driver and I have added the 'source' command to ~/.bashrc file. I open a new terminal to run the command.

`./classification_sample -i car.png -m /<path>/alexnet.xml -d MYRIAD`

but still the same error.

**Comment by ilya-lavrenov** [comment]
please, use `strace` to debug what happens. Make sure that with CPU or GPU plugin the sample works correctly.

**Comment by RachelRen05** [comment]
Yes, with CPU or GPU the sample works fine.
Based on above discussion and experiments, may I say there is no way to support ncs through dldt so far?

**Comment by RachelRen05** [comment]
I have solved the problem, please refer to the following steps to enable ncs under dldt:

- Refer to the [guide](https://github.com/intel/ros2_openvino_toolkit/blob/devel/doc/OPEN_SOURCE_CODE_README.md) to install dldt.

- Refer to the [guide](https://software.intel.com/en-us/neural-compute-stick/get-started)  to install binary and set up the environment.
About how to get OpenVINO R5 binary package: 
`wget -c http://registrationcenter-download.intel.com/akdlm/irc_nas/15078/l_openvino_toolkit_p_2018.5.455.tgz`

- Configure the environment
```export CPU_EXTENSION_LIB=/opt/intel/computer_vision_sdk/deployment_tools/inference_engine/samples/build/intel64/Release/lib/libcpu_extension.so
export GFLAGS_LIB=/opt/intel/computer_vision_sdk/deployment_tools/inference_engine/samples/build/intel64/Release/lib/libgflags_nothreads.a
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/computer_vision_sdk/deployment_tools/inference_engine/samples/build/intel64/Release/lib
source /opt/intel/computer_vision_sdk/bin/setupvars.sh
```

**Comment by ilyachur** [comment]
@RachelRen05 Was the original problem resolved?

**Comment by AnastasiaKazantaeva** [comment]
As problem doesn't exist any more, I am closing this issue. You may reopen it or create a new one
