### ISSUE TITLE
[FEATURE] Please update ubuntu repo to 2021.4.2

### ISSUE THREAD

**Issue by r0l1** [openvinotoolkit/openvino#9005]
The official ubuntu repo does not contain the latest release. After following the official installation instructions `apt-cache search openvino` shows only:

```
intel-openvino-ie-rt-2021.1.110 - Inference Engine RT 2021.1
intel-openvino-ie-rt-2021.2.200 - Inference Engine RT 2021.2
intel-openvino-ie-rt-2021.3.394 - Inference Engine RT 2021.3
intel-openvino-ie-rt-2021.4.582 - Inference Engine RT 2021.4
intel-openvino-ie-rt-2021.4.689 - Inference Engine RT 2021.4.1
intel-openvino-ie-rt-2021.4.752 - Inference Engine RT 2021.4.1
```

**Comment by skaldesh** [comment]
It is maybe just a wrong name string?

**Comment by alalek** [comment]
Unfortunately there is wrong version in the package description.
Please use `intel-openvino-ie-rt-2021.4.752` - it has OpenVINO 2021.4.2 content.

**Comment by r0l1** [comment]
Alright. Thank you.
