### ISSUE TITLE
OpeVINO for multiple users

### ISSUE THREAD

**Issue by Kevin-Rush** [openvinotoolkit/openvino#9008]
Hello OpenVINO Dev Team,

I am working on the Intel digital readiness project and we are working with many schools across the world who wish to use OpenVINO in a lab setting with multiple students. Instead of having each user install OpenVINO, the schools want to install it on the machine for all users. As far as we can tell this feature is not available. 

Can you please tell me if it is possible to install OpenVINO for all users? If not would it be possible for this feature to be added?

Looking forward to hearing from you.
Kevin

**Comment by avitial** [comment]
@Kevin-Rush could you share more about the system configuration(s) or possible configurations (i.e. OS, C++/Python development, hardware for inference, etc.), the user access permissions and components of OpenVINO required (i.e. device plugins, Inference Engine, Model Optimizer, OMZ, etc)? I am not familiar on how software gets installed and deployed in a school setting so I assume there isn't anything special about it, but please elaborate if there is anything to be considered. 

Starting with the assumption that [System Requirements](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_windows.html#system-requirements) are met, with an install on Windows 10, CPU/GPU plugin usage and OpenVINO users with standard non-admin access, I think is possible in two ways:
1. Install OpenVINO with online/offline installer and administrator rights
      - All users must have access to OpenVINO install path (default install path '_C:\Program Files (x86)\Intel\openvino_2021_' or defined by admin)
      - Microsoft Visual Studio 2019 with MSBuild
      - CMake 3.14 or higher, 64-bit (Install for All-Users)
      - Python 3.6 - 3.8, 64-bit (Install for All-Users, as part of this installation make sure you click the option Add Python 3.x to PATH to add Python to your PATH environment variable)
2. Users to install [developer package](https://pypi.org/project/openvino-dev/) from PyPI Repository (Python API only)
   - Python* distribution 3.6, 3.7, 3.8 (Admin Install for All-Users, as part of this installation make sure you click the option Add Python 3.x to PATH to add Python to your PATH environment variable)

Please keep in mind this is not something that has been validated.

Best Regards,
Luis

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
