### ISSUE TITLE
Error converting onnx to IR model 

### ISSUE THREAD

**Issue by pratiksamuel** [openvinotoolkit/openvino#908]
Error converting the onnx model to IR model.
The model used is a detectron 2 object detection model with vovnet v2 backbone.
Produced an onnx model and tried to convert it into an IR model using the following command

python3 mo_onnx.py --input_model /home/ats/workspace/pratik/detectron2/tools/deploy/model.onnx --log_level DEBUG

but got the following error.

[log.txt](https://github.com/openvinotoolkit/openvino/files/4769832/log.txt)

Error: Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "im_info" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 

I have attached the full log in the log.txt 

I also tried to give inputs and input_shapes using the following command

sudo python3 mo_onnx.py --input_model /home/ats/workspace/pratik/detectron2/tools/deploy/model.onnx --log_level DEBUG --input data,im_info.1 --input_shape [1,768,1344,3],[1,3]

but got a similar error
[ 2020-06-12 10:40:13,297 ] [ DEBUG ] [ infer:128 ]  --------------------
[ 2020-06-12 10:40:13,297 ] [ DEBUG ] [ infer:129 ]  Partial infer for onnx_initializer_node__wrapped_model.backbone.bottom_up.stage2.OSA2_1.ese.fc.bias
[ 2020-06-12 10:40:13,297 ] [ DEBUG ] [ infer:130 ]  Op: Const
[ 2020-06-12 10:40:13,297 ] [ DEBUG ] [ infer:131 ]  Inputs:
[ 2020-06-12 10:40:13,298 ] [ DEBUG ] [ infer:144 ]  Outputs:
[ 2020-06-12 10:40:13,306 ] [ DEBUG ] [ infer:31 ]  output[0]: shape = [256], value = [-1.32140309e-01 -4.69729304e-03  1.79335810e-02 -8.93547758e-03
 -1.06612062e-02 -2.26268615e-03...
[ 2020-06-12 10:40:13,307 ] [ DEBUG ] [ infer:128 ]  --------------------
[ 2020-06-12 10:40:13,307 ] [ DEBUG ] [ infer:129 ]  Partial infer for im_info.1
[ 2020-06-12 10:40:13,307 ] [ DEBUG ] [ infer:130 ]  Op: Parameter
[ 2020-06-12 10:40:13,307 ] [ DEBUG ] [ infer:131 ]  Inputs:
[ 2020-06-12 10:40:13,308 ] [ DEBUG ] [ infer:144 ]  Outputs:
[ 2020-06-12 10:40:13,308 ] [ DEBUG ] [ infer:31 ]  output[0]: shape = [1 3], value = <UNKNOWN>
[ ERROR ]  Cannot infer shapes or values for node "im_info".
[ ERROR ]  There is no registered "infer" function for node "im_info" with op = "AliasWithName". Please implement this function in the extensions. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #37. 
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <UNKNOWN>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ 2020-06-12 10:40:13,310 ] [ DEBUG ] [ infer:196 ]  Node "im_info" attributes: {'pb': input: "im_info.1"
output: "im_info"
op_type: "AliasWithName"
attribute {
  name: "name"
  s: "im_info"
  type: STRING
}
attribute {
  name: "is_backward"
  i: 0
  type: INT
}
domain: "org.pytorch._caffe2"
, 'kind': 'op', '_in_ports': {0: {'control_flow': False}}, '_out_ports': {0: {'control_flow': False}}, 'name': 'im_info', 'op': 'AliasWithName', 'is_output_reachable': True, 'is_undead': False, 'is_const_producer': False, 'is_partial_inferred': False}
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "im_info" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 
[ 2020-06-12 10:40:13,315 ] [ DEBUG ] [ main:325 ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 175, in partial_infer
    node.soft_get('op')
mo.utils.error.Error: There is no registered "infer" function for node "im_info" with op = "AliasWithName". Please implement this function in the extensions. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #37. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 288, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/extensions/middle/PartialInfer.py", line 32, in find_and_replace_pattern
    partial_infer(graph)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/middle/passes/infer.py", line 198, in partial_infer
    refer_to_faq_msg(38)) from err
mo.utils.error.Error: Stopped shape/value propagation at "im_info" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/main.py", line 312, in main
    ret_code = driver(argv)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/main.py", line 273, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/main.py", line 238, in prepare_ir
    graph = unified_pipeline(argv)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/pipeline/unified.py", line 29, in unified_pipeline
    class_registration.ClassType.BACK_REPLACER
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 334, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 324, in apply_replacements_list
    num_transforms=len(replacers_order))
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/logger.py", line 124, in wrapper
    function(*args, **kwargs)
  File "/opt/intel/openvino_2020.3.194/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 304, in apply_transform
    )) from err
mo.utils.error.Error: Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "im_info" node. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #38. 
n #38.

I have attached the onnx model for reference.

https://drive.google.com/file/d/1QO5XM3Fqd4lttMJ9A6MlhRFPE02CDYVh/view?usp=sharing

**Comment by maxlytkin** [comment]
Hello @pratiksamuel 
OpenVINO toolkit currently does not officially support Detectron2 model conversion. We are sorry for the inconvenience. 
Meanwhile please have a chance to take a look at possible workaround here https://github.com/facebookresearch/detectron2/issues/1602

Best regards, Max.

**Comment by lazarevevgeny** [comment]
@pratiksamuel , also you may want to try https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/instance_segmentation model which is based on Detectron.

**Comment by pratiksamuel** [comment]
Sure,thanks will try that out.

**Comment by maxlytkin** [comment]
I'm closing this case. Please feel free to re-open if additional assistance is needed.

**Comment by bouachalazhar** [comment]
I would like to export detectron2 model to OpenVINO because I have Intel Iris Xe graphics and NCS 2.
