### ISSUE TITLE
Original placeholders: 'im_shape, image, scale_factor'. Freezing was requested for ''. --input_shape was provided without --input. Can not deduce which node shape to override

### ISSUE THREAD

**Issue by monkeycc** [openvinotoolkit/openvino#9109]
**Problem description**

image_shape:[3,608,608]

Paddle2onnx conversion yolov3_ darknet53_ 270e_ VOC model
[WARNING]   Due to the operator:multiclass_nms3, the converted ONNX model will only supports input[batch_size] == 1.

 paddle2onnx 
--model_dir D:\PaddleDetection\output\yolov3_darknet53_270e_voc_OK\yolov3_darknet53_270e_voc 
--model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 
--save_file D:\PaddleDetection\output\yolov3_darknet53_270e_voc_OK\onnx\yolov3.onnx

D:\anaconda3\envs\PaddleDetection\lib\site-packages\onnx\helper.py:343: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  is_iterable = isinstance(value, collections.Iterable)

2021-12-09 16:44:59 [WARNING]   Due to the operator:multiclass_nms3, the converted ONNX model will only supports input[batch_size] == 1.
2021-12-09 16:45:01 [INFO]      ONNX model generated is valid.
2021-12-09 16:45:03 [INFO]      ONNX model saved in D:\PaddleDetection\output\yolov3_darknet53_270e_voc_OK\onnx\yolov3.onnx

[WARNING]   Due to the operator:multiclass_nms3, the converted ONNX model will only supports input[batch_size] == 1.

---------------------

Convert to openvino
report errors

python mo_onnx.py 
--input_model F:\yolov3_darknet53_270e_voc_OK\onnx\yolov3.onnx 
--output_dir F:\yolov3_darknet53_270e_voc_OK\onnx\yolov3 --input_shape [1,3,608,608]

Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      F:\yolov3_darknet53_270e_voc_OK\onnx\yolov3.onnx
        - Path for generated IR:        F:\yolov3_darknet53_270e_voc_OK\onnx\yolov3
        - IR output name:       yolov3
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,3,608,608]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
ONNX specific parameters:
        - Inference Engine found in:    E:\Intel\openvino_2021.4.689\python\python3.8\openvino
Inference Engine version:       2021.4.1-3926-14e67d86634-releases/2021/4
Model Optimizer version:        2021.4.1-3926-14e67d86634-releases/2021/4

[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 
'extensions.front.user_data_repack.UserDataRepack'>): Original placeholders: 'im_shape, image, scale_factor'. Freezing was requested for ''. --input_shape was provided without --input. Can not deduce which node shape to override

**Comment by meiyang-intel** [comment]
Hi @monkeycc ,

Have tried with paddle model yolov3_darknet53_270e_coco. It should be similar with yolov3_darknet53_270e_voc. The yolov3_darknet53_270e_coco has 3 inputs:'image', 'im_shape' and 'scale_factor'. The Error means that you should specify which input port's shape is [1,3,608,608]. The correct parameter should be '--input_shape=[1,3,608,608],[1,2],[1,2] --input=image,im_shape,scale_factor'.

Besides, Paddle model is supported by OpenVINO now. There is no need to convert paddle to onnx first. Below is the example to convert paddle with MO.

`/usr/bin/python3 <path-to-model_optimizer>/mo.py --model_name yolov3-baidu --output_dir <ir-model-path> --framework=paddle --data_type=FP32 --reverse_input_channels '--input_shape=[1,3,608,608],[1,2],[1,2]' --input=image,im_shape,scale_factor '--mean_values=image[58.395,57.12,57.375]' '--scale_values=image[123.675,116.28,103.53]' --output=save_infer_model/scale_0.tmp_1,save_infer_model/scale_1.tmp_1 --input_model=<path-to-paddle-yolov3-model>/model.pdmodel`

Then you can input the generated IR model to ie core ReadNetwork.
Another way to run paddle model is to directly input paddle model to ie core ReadNetwork. Even the step of MO converting can be omitted.

**Comment by monkeycc** [comment]
PaddleX 2.0
yolov3

Can it be converted to openvino
@meiyang-intel

**Comment by meiyang-intel** [comment]
OK, Let me try with the script

**Comment by monkeycc** [comment]
https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/docs/compile/openvino/openvino_windows.md

我们测试的openvino版本为2021.3，如果你使用其它版本遇到问题，可以尝试切换到该版本
当前检测模型转换为openvino格式是有问题的，暂时只支持分割和分类模型

官方最新教程  目标检测 不支持openvino
很遗憾~

@meiyang-intel

**Comment by meiyang-intel** [comment]
Hi @monkeycc , OpenVINO目前是可以支持paddle yolov3模型的。建议用最新的OpenVINO master版本跑paddle模型，相应的步骤也可以简化，https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/docs/compile/openvino/openvino_windows.md 中步骤1.2和1.3可以用我第一条评论里面的MO命令替代，我们也会提醒baidu去更新相关的文档或代码。

另外，我们有一个用OpenVINO跑paddle模型的demo（https://github.com/raymondlo84/openvino-paddlepaddle-demo ）。其中有跑yolov3的例子，可以作为参考

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
