### ISSUE TITLE
please provide conda/pip install options

### ISSUE THREAD

**Issue by vladium** [openvinotoolkit/openvino#914]
Greetings. I am not having traction with this line of inquiry in Intel forums, so I will repeat my feature request here:

Current instructions for installing openVINO on Linux assume that the end user will be able to execute a lengthy list of native OS packages via `install_openvino_dependencies.sh`, which requires root/sudo privileges (for doing `yum`/`apt-get` installs). The alternative of running openVINO via Docker does not help because using Docker usually requires sudo permissions as well.

This will not be possible in many (most ?) corporate environments. It is, however, common to allow users to create virtualenvs or conda envs and extend these respective env types with public packages. This allows non-privileged installations (under user's HOME dir, for example) and even installing different releases at the same time.

Now that there is an LTS release it would be great to be able to install openvino via conda. (Nore that conda ships with its own c++ compilers/build tools and allows for self-contained installations that are isolated from the OS system paths.)

**Comment by moslex** [comment]
Hello, @vladium 
We added ability to install OpenVINO toolkit using Conda starting from 2020.3 LTS
For macOS and Windows: conda install -c intel openvino-ie4py
For Linux we support Ubuntu 18 only:  conda install -c intel openvino-ie4py-ubuntu18
