### ISSUE TITLE
openvino2020.1  "IE::ie_cpu_extension" not found

### ISSUE THREAD

**Issue by zys1994** [openvinotoolkit/openvino#916]
Target "" links to target "IE::ie_cpu_extension" but the
  target was not found.

which i can make succeed in openvino 2019R3 ,how to fix it?

**Comment by ilya-lavrenov** [comment]
Starting from 2020.1 release we have moved all extensions for CPU plugin directly to CPU plugin code. So, no such target `IE::ie_cpu_extension` and you don't have to link anything else. So, the solution is just to remove this line with `IE::ie_cpu_extension`
