### ISSUE TITLE
How to install Model Optimizer standalone?

### ISSUE THREAD

**Issue by lixiepeng** [openvinotoolkit/openvino#9167]
Is there any official docker image for Model Optimizer?

**Comment by jgespino** [comment]
Hi @lixiepeng 

You can find all available pre-built images on [Docker Hub](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_docker_linux.html). However, there isn’t an image with just the Model Optimizer. The closest images would be `openvino/ubuntu20_dev_no_samples` or  `openvino/ubuntu18_dev_no_samples`. Alternatively, you could use the [DockerHub CI for Intel® Distribution of OpenVINO™ toolkit](https://github.com/openvinotoolkit/docker_ci) to customize an image for your needs.

Regards,
Jesus

**Comment by lixiepeng** [comment]
> 

It works, Thanks `mo --help`
