### ISSUE TITLE
Conversion of mask rcnn (.pb) to openvino format

### ISSUE THREAD

**Issue by himalayanZephyr** [openvinotoolkit/openvino#918]
Hi
I trained a custom Mask RCNN model using this [repo](https://github.com/matterport/Mask_RCNN/).

I converted the model from .h5 to .pb format.
Now, I'm trying to figure out how to convert it to Openvino IR format

`python mo_tf.py --reverse_input_channels --input_shape=[1,1024,1024,3] --tensorflow_use_custom_operations_config=./extensions/front/tf/mask_rcnn_support_api_v1.13.json --input_model ~/Mask_RCNN/Model/mask_rcnn_landing.pb --output_dir=~/Mask_RCNN/Model --log_level=DEBUG`

The error is
`mo.utils.error.Error: Original placeholders: 'input_image, input_image_meta, input_anchors'. Freezing was requested for ''. --input_shape was provided without --input. Can not deduce which node shape to override
Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.user_data_repack.UserDataRepack'>): Original placeholders: 'input_image, input_image_meta, input_anchors'. Freezing was requested for ''. --input_shape was provided without --input. Can not deduce which node shape to override`

How do I specify the --input parameter?

Also, the openvino version I'm using is **openvino_2019.3.334**

I was also wondering if I need to specify this flag _--tensorflow_object_detection_api_pipeline_config_
?

**Comment by avitial** [comment]
Hi @himalayanZephyr if possible could you share your .h5 model and resulting .pb file? Would like to see what the behavior is on newer versions of the toolkit since you are using an old version.

Regards,
~Luis

**Comment by himalayanZephyr** [comment]
Hi @avitial 
Thanks for taking in the time to inspect this.
Here is the [link](https://drive.google.com/drive/folders/1M-Ze0sGXLD4C1cGm1FATojb7USU95V0K) with the .h5 and .pb models

**Comment by avitial** [comment]
@himalayanZephyr tried converting the shared .pb file but was unsuccessful as the model is currently not supported, the team is already aware of this.

**Comment by himalayanZephyr** [comment]
@avitial Ohh so you mean that I won't be able to convert these models into openvino format in any way?
In that case, can you point me to some other way to train a custom segmentation model that could be successfully converted to openvino format.

**Comment by avitial** [comment]
@himalayanZephyr you could take a look at the [openvino_training_extensions ](https://github.com/opencv/openvino_training_extensions) , there are some segmentation models available there for training and can be used with the OpenVINO™ toolkit for inference.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Comment by franva** [comment]
still having this issue when trying to convert [YoloV3 model](https://easyupload.io/b5ydux).

The onnx model will expire in 30 days.

@avitial could you please help?

thanks
