### ISSUE TITLE
Openvino 2020.3.0 mismatch with official release

### ISSUE THREAD

**Issue by marcin-sielski** [openvinotoolkit/openvino#921]
Hi,

There is a mismatch in sources labeled 2020.3.0 and the release available through the official release. It looks like github version (Apache licence) is missing commit or commits related to deprecated API.

Best Regards

Marcin Sielski

**Comment by ilya-lavrenov** [comment]
@asuhov could you please comment?

**Comment by marcin-sielski** [comment]
I think I have found at least one commit that should be part of 2020.3.0
https://github.com/openvinotoolkit/openvino/commit/88e14c9dd6dd553f541726cb9af5b9e6d26e30b7

**Comment by asuhov** [comment]
Hello, sources snapshot for 2020.3 release contains several fixes for deprecated API which didn't get into 2020.3 binary package. The master branch contains the most recent changes.

**Comment by marcin-sielski** [comment]
@asuhov 
I think I have seen opposite situation. The deprecated API fixes were in 2020.3 binary release but were not present in 2020.3.0 source release. All previous releases were in sync.

**Comment by alalek** [comment]
BTW, 2020.3 is LTS release. So we may see ported changes in [this source branch](https://github.com/openvinotoolkit/openvino/tree/releases/2020/3) in the future.
