### ISSUE TITLE
[WARNING] error during parsing cache file, tuning data won't be used

### ISSUE THREAD

**Issue by YijinLiu** [openvinotoolkit/openvino#924]
When I run network on GPU with 2020.3 LTS, I got this warning. It never happened with old versions.
Should I be worried about it?

**Comment by vladimir-paramuzov** [comment]
@YijinLiu This warning means that [cache.json](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/thirdparty/clDNN/kernel_selector/core/cache/cache.json) file was not found or was corrupted. This file has some precollected tuning data for opencl kernels that might improve the performance a little bit in some cases, and it's supposed to be located at the same folder as clDNNPlugin library. So you shouldn't see any big difference from the functional standpoint without tuning cache, but can observe some perf impact.

**Comment by YijinLiu** [comment]
Thanks for the prompt response!
