### ISSUE TITLE
checkpoint(meta) conversion to IR problem

### ISSUE THREAD

**Issue by JinXiaozhao** [openvinotoolkit/openvino#9438]
##### System information (version)
docker images => tensorflow==2.3.1
- OpenVINO-2021.4.2
- Operating System / Platform => linux
- Compiler => GCC 7.5.0
- Problem classification: Model Conversion
- Framework: TensorFlow
- Model name: mnist
-->
I'm trying to convert frozen model or saved model to IR model.
when the openvino==2021.4.582,it can't success.
But the openvino==2021.1.110,it can success.
I want use the openvino==2021.4.582, Is there another way to do it other that writing extension to model optimizer?

##### Detailed description
oot@a110655a8d13:/opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer# python mo_tf.py --input_meta_graph /root/mnist/mnist_ckpt/model.ckpt.meta --output_dir  /root/compiler/mnist/ --input Placeholder --output Softmax -b 1
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      None
        - Path for generated IR:        /root/compiler/mnist/
        - IR output name:       model.ckpt
        - Log level:    ERROR
        - Batch:        1
        - Input layers:         Placeholder
        - Output layers:        Softmax
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
[ WARNING ] Could not find the Inference Engine Python API. At this moment, the Inference Engine dependency is not required, but will be required in future releases.
[ WARNING ] Consider building the Inference Engine Python API from sources or try to install OpenVINO (TM) Toolkit using "install_prerequisites.sh"
Model Optimizer version:        2021.4.0-3839-cd81789d294-releases/2021/4
2021-12-25 02:10:14.099274: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2021-12-25 02:10:14.099333: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-12-25 02:10:16.195110: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-12-25 02:10:16.195529: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2021-12-25 02:10:16.195556: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-12-25 02:10:16.195588: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a110655a8d13): /proc/driver/nvidia/version does not exist
2021-12-25 02:10:16.196065: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-25 02:10:16.197112: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-12-25 02:10:16.256614: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-12-25 02:10:16.260764: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2294605000 Hz
[ WARNING ]  Please set `version` attribute for node dropout/random_uniform/RandomUniform with type=<UNKNOWN>
[ WARNING ]  Changing Const node 'dropout/random_uniform/sub' data type from float32 to <class 'numpy.int32'> for Elementwise operation
[ WARNING ]  Changing Const node 'dropout/random_uniform/min' data type from float32 to <class 'numpy.int32'> for Elementwise operation
[ WARNING ]  Changing Const node 'dropout/rate' data type from float32 to <class 'numpy.int32'> for Elementwise operation
[ ERROR ]  List of operations that cannot be converted to Inference Engine IR:
[ ERROR ]      RandomUniform (1)
[ ERROR ]          dropout/random_uniform/RandomUniform
[ ERROR ]  Part of the nodes was not converted to IR. Stopped. 
 For more information please refer to Model Optimizer FAQ, question #24. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=24#question-24)
root@a110655a8d13:/opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer# pwd
/opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer
root@a110655a8d13:/opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer# cd /
root@a110655a8d13:/# python /opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer/mo_tf.py --input_meta_graph /root/mnist/mnist_ckpt/model.ckpt.meta --output_dir  /root/compiler/mnist/ --input Placeholder --output Softmax -b 1
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      None
        - Path for generated IR:        /root/compiler/mnist/
        - IR output name:       model.ckpt
        - Log level:    ERROR
        - Batch:        1
        - Input layers:         Placeholder
        - Output layers:        Softmax
        - Input shapes:         Not specified, inherited from the model
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
[ WARNING ] Could not find the Inference Engine Python API. At this moment, the Inference Engine dependency is not required, but will be required in future releases.
[ WARNING ] Consider building the Inference Engine Python API from sources or try to install OpenVINO (TM) Toolkit using "install_prerequisites.sh"
Model Optimizer version:        2021.4.0-3839-cd81789d294-releases/2021/4
2021-12-25 02:12:36.932592: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2021-12-25 02:12:36.932654: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-12-25 02:12:38.814266: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-12-25 02:12:38.814550: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 
2021-12-25 02:12:38.814574: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-12-25 02:12:38.814598: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (a110655a8d13): /proc/driver/nvidia/version does not exist
2021-12-25 02:12:38.814949: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-25 02:12:38.815650: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-12-25 02:12:38.898541: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-12-25 02:12:38.903642: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2294605000 Hz
[ WARNING ]  Please set `version` attribute for node dropout/random_uniform/RandomUniform with type=<UNKNOWN>
[ WARNING ]  Changing Const node 'dropout/random_uniform/sub' data type from float32 to <class 'numpy.int32'> for Elementwise operation
[ WARNING ]  Changing Const node 'dropout/random_uniform/min' data type from float32 to <class 'numpy.int32'> for Elementwise operation
[ WARNING ]  Changing Const node 'dropout/rate' data type from float32 to <class 'numpy.int32'> for Elementwise operation
[ ERROR ]  List of operations that cannot be converted to Inference Engine IR:
[ ERROR ]      RandomUniform (1)
[ ERROR ]          dropout/random_uniform/RandomUniform
[ ERROR ]  Part of the nodes was not converted to IR. Stopped. 
 For more information please refer to Model Optimizer FAQ, question #24. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=24#question-24)

**Comment by zulkifli-halim** [comment]
Hi @JinXiaozhao. Please share your frozen or saved model and which Linux version you used to run the command with us so that we can reproduce the issue.

**Comment by JinXiaozhao** [comment]
Thanks for your reply.
 
Operating System / Platform => Ubuntu 18.04.

I got model from the code:

`"""
CNN-MNIST
"""
import tensorflow as tf

_MNIST_SOURCE_URL = 'http://yann.lecun.com/exdb/mnist/'


def load_data(path):
    from tensorflow.examples.tutorials.mnist import input_data
    mnist = input_data.read_data_sets(path, one_hot=True, source_url=_MNIST_SOURCE_URL)
    return mnist


def conv_layer(x_data, shape, init_value, strides, padding):
    weight_conv = tf.Variable(tf.truncated_normal(shape=shape, stddev=init_value[0]))
    bias_conv = tf.Variable(tf.constant(value=init_value[1], shape=[shape[-1]]))
    conv = tf.nn.relu(tf.nn.conv2d(x_data, weight_conv, strides=strides, padding=padding) + bias_conv)

    return conv


def data_flatten(input_fc):
    shape = input_fc.shape
    input_flatten = tf.reshape(input_fc, [-1, shape[1] * shape[2] * shape[3]])
    return input_flatten


def fully_connected(fc_data, units, std, value):
    fc_shape = fc_data.get_shape().as_list()
    weight_fc = tf.Variable(tf.truncated_normal(shape=[fc_shape[1], units], stddev=std))
    bias_fc = tf.Variable(tf.constant(value=value, shape=[units]))
    return tf.matmul(fc_data, weight_fc) + bias_fc


def output_cnn(images, rate):
    images = tf.reshape(images, [-1, 28, 28, 1])
    # conv1 layer
    conv1 = conv_layer(images, shape=[5, 5, 1, 32], init_value=[0.1, 0.1], strides=[1, 1, 1, 1], padding='SAME')

    # pooling layer1
    pool1 = tf.nn.max_pool(conv1, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

    # conv2 layer
    conv2 = conv_layer(pool1, shape=[5, 5, 32, 64], init_value=[0.1, 0.1], strides=[1, 1, 1, 1], padding='SAME')

    # pooling layer2
    pool2 = tf.nn.max_pool(conv2, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

    # fully connected layer
    pool2_flatten = data_flatten(pool2)
    fc1 = tf.nn.relu(fully_connected(pool2_flatten, 1024, 0.1, 0.1))

    # output layer
    fc1_drop = tf.nn.dropout(fc1, rate=rate)

    y_cnn = tf.nn.softmax(fully_connected(fc1_drop, 10, 0.1, 0.1))
    print(y_cnn)

    return y_cnn


def get_loss(y_predict, y_label):
    return -tf.reduce_sum(y_label * tf.log(y_predict))


def get_optimizer(optimizer, learn_rate):
    return optimizer(learn_rate)


def accuracy(y_predict, y_label):
    correct_predict = tf.equal(tf.math.argmax(y_predict, 1), tf.math.argmax(y_label, 1))
    return tf.reduce_mean(tf.cast(correct_predict, 'float'))


def _make_session_function(placeholders, outputs, updates):
    fetches = [outputs, updates]

    def _session_function(session, input_data):
        feed_data = dict(zip(placeholders, input_data))
        return session.run(fetches, feed_dict=feed_data)[0]

    return _session_function


class Mnist:

    def __init__(self):
        with tf.Graph().as_default():
            x_data = tf.placeholder("float", [None, 28 * 28])
            y_label = tf.placeholder("float", [None, 10])
            y_predict = output_cnn(x_data, 0.5)
            loss = get_loss(y_predict, y_label)
            optimizer = get_optimizer(tf.train.AdamOptimizer, learn_rate=1e-4)
            train_op = optimizer.minimize(loss)
            class_accuracy = accuracy(y_predict, y_label)
            saver = tf.train.Saver()
            sess = tf.Session()
            sess.run(tf.global_variables_initializer())

            self.train_function = _make_session_function(placeholders=[x_data, y_label],
                                                         outputs=class_accuracy, updates=train_op)
            self.predict_function = _make_session_function(placeholders=[x_data],
                                                           outputs=y_predict, updates=[])
            self.evaluate_function = _make_session_function(placeholders=[x_data, y_label],
                                                            outputs=class_accuracy, updates=[])
            self.saver = saver
            self.session = sess

    def train(self, images, labels, batch_size, step):
        train_accuracy = None

        for i in range(step):
            start = i * batch_size % images.shape[0]
            end = start + batch_size
            input_data = [images[start:end], labels[start:end]]
            train_accuracy = self.train_function(self.session, input_data=input_data)

        return train_accuracy

    def predict(self, images):
        return self.predict_function(self.session, input_data=images)

    def evaluate(self, images, labels):
        return self.evaluate_function(self.session, input_data=[images, labels])

    def save_checkpoint(self, model_path):
        self.saver.save(self.session, model_path)

    def load_checkpoint(self, model_path):
        self.saver.restore(self.session, model_path)


import os


def _get_data(data_path):
    return load_data(data_path)


_FILE_PATH = os.path.dirname(os.path.abspath(__file__))
_DATA_PATH = os.path.join(_FILE_PATH, 'MNIST_data/')
_CKPT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'model.ckpt')

mnist = _get_data(_DATA_PATH)
train_images = mnist.train.images
train_labels = mnist.train.labels
batch_size = 50
step = 200

model = Mnist()
result = model.train(train_images, train_labels, batch_size, step)
model.save_checkpoint(_CKPT_PATH)
`

**Comment by jgespino** [comment]
@JinXiaozhao 

I was unable to generate the the model using Tensorflow 2.4. However, when switching to Tensorflow 1.14 the model was generated and I can reproduce the same error. 

In OpenVINO 2021.4, TensorFlow 1.x moves to supported with limitations. Take a look at the [release notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-relnotes.html) for additional information. 

Couple of questions:

- Did you generate your model using Tensorflow 1.x as well? 
- Is it possible to upgrade your script to generate the model using Tensorflow 2.x?

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if you need additional assistance.

**Comment by JinXiaozhao** [comment]
@jgespino 
I generate my model using Tensorflow 1.x.
I can't generate the model using Tensorflow 2.x.

**Comment by jgespino** [comment]
Hi @JinXiaozhao 

Please try to convert your model using OpenVINO 2022.1 release. I tested using this version from [pip](https://pypi.org/project/openvino-dev/) and converted your model successfully. I had to downgrade Tensorflow version to 1.14 as I was unable to export the model using Tensorflow 2.x or Tensorflow 1.15. Once the model was converted to IR, I ran the model using the benchmark_app without any issues.

Please note, this may cause unexpected issues as Tensorflow 1.15.5 or newer is required. I highly recommend migrating your project/model to Tensorflow 2.x.

```
mo --input_meta_graph model.ckpt.meta --input Placeholder --output Softmax -b 1
Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      None
        - Path for generated IR:        C:\Users\user\Downloads\9438\.
        - IR output name:       model.ckpt
        - Log level:    ERROR
        - Batch:        1
        - Input layers:         Placeholder
        - Output layers:        Softmax
        - Input shapes:         Not specified, inherited from the model
        - Source layout:        Not specified
        - Target layout:        Not specified
        - Layout:       Not specified
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - User transformations:         Not specified
        - Reverse input channels:       False
        - Enable IR generation for fixed input shape:   False
        - Use the transformations config file:  None
Advanced parameters:
        - Force the usage of legacy Frontend of Model Optimizer for model conversion into IR:   False
        - Force the usage of new Frontend of Model Optimizer for model conversion into IR:      False
TensorFlow specific parameters:
        - Input model in text protobuf format:  False
        - Path to model dump for TensorBoard:   None
        - List of shared libraries with TensorFlow custom layers implementation:        None
        - Update the configuration file with input/output node names:   None
        - Use configuration file used to generate the model with Object Detection API:  None
        - Use the config file:  None
OpenVINO runtime found in:      c:\users\user\openvino_env\lib\site-packages\openvino
OpenVINO runtime version:       2022.1.0-7019-cdb9bec7210-releases/2022/1
Model Optimizer version:        2022.1.0-7019-cdb9bec7210-releases/2022/1
c:\users\user\openvino_env\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
c:\users\user\openvino_env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
[ WARNING ]
Support of the Model Optimizer tool in TensorFlow 1.x environment is deprecated.It is highly recommended to use TensorFlow 2.x.

[ WARNING ]
Detected not satisfied dependencies:
        tensorflow: installed: 1.14.0, required: >= 1.15.5

Please install required versions of components or run pip installation
pip install openvino-dev[tensorflow]
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: C:\Users\user\Downloads\9438\model.ckpt.xml
[ SUCCESS ] BIN file: C:\Users\user\Downloads\9438\model.ckpt.bin
[ SUCCESS ] Total execution time: 9.35 seconds.
```

Regards,
Jesus
