### ISSUE TITLE
[Bug] get_available_devices() memleak issue

### ISSUE THREAD

**Issue by Yanfeng-Mi** [openvinotoolkit/openvino#9501]
-OpenVINO => 2021.4
-Operating System / Platform => Windows 64 Bit
-Compiler => Visual Studio 2019
-Problem classification: memleak

##### Detailed description
Using inference core API to query available devices. the heap have ~27MB left after core is deconstructed. 

##### Steps to reproduce

1. run hello_query_device.exe sample app with vs2019 debugger.
2. Enable heap profiling and take snapshot before get_available_devices() 
3. Take snapshot after get_available_devices() +29MB
4. Take snapshot on return -2MB.

**Comment by Iffa-Meah** [comment]
Hi,

Here is what I observed from my side:

![VSmem](https://user-images.githubusercontent.com/79643476/148333827-a0713957-2a61-4d4f-9011-968f27a46871.png)

We'll further investigate this.

**Comment by alalek** [comment]
Limited "leaks" from initialization of singletons or other global structures / caches are not a real problem actually.

Only critical leaks must be fixed - infinitely growing memory usage during the normal application usage.
Reproducer must have "for" loop on the top-level.

@Iffa-Meah Please collect stats for the second call or add for loop.

**Comment by Yanfeng-Mi** [comment]
for loop 100 times, we can see memory growth:
![image](https://user-images.githubusercontent.com/62379311/148345839-1b4554e5-3a97-4d6a-919b-731929bac622.png)

**Comment by alalek** [comment]
> infinitely growing memory usage

We need to see this.

Memory usage is not measured properly. Measurement should skip the first "warmup" initialization of global structures.

---

I could post adapted code, but modification of screenshots is not a trivial. Consider posting code as text, not through screenshots.

**Comment by jgespino** [comment]
Hi @Yanfeng-Mi 

I ran a test as @alalek mentioned above and this is what I'm seeing. Do you see the same?

![image](https://user-images.githubusercontent.com/18014973/148830503-8f0deb3a-fc67-4bbf-ad1f-1b9f740a59ec.png)

ID1: before calling first `GetAvailableDevices`
ID2: after calling first `GetAvailableDevices`
ID3: after calling `GetAvailableDevices` 100 times
```
int main(int argc, char* argv[]) {
	std::cout << "Loading Inference Engine" << std::endl;
	Core ie;

	std::cout << "Starting in 10 sec " << std::endl;
	std::this_thread::sleep_for(std::chrono::milliseconds(10000));

	std::vector<std::string> availableDevices = ie.GetAvailableDevices();

	std::cout << "After First GetAvailableDevices" << std::endl;
	std::this_thread::sleep_for(std::chrono::milliseconds(10000));

	for(int i = 0; i < 100; i++){
		std::vector<std::string> availableDevices = ie.GetAvailableDevices();
		std::this_thread::sleep_for(std::chrono::milliseconds(200));
		std::cout << i << std::endl;
	}

	std::cout << "After 100 GetAvailableDevices" << std::endl;
	std::this_thread::sleep_for(std::chrono::milliseconds(10000));
       
    return EXIT_SUCCESS;
}
```

Regards,
Jesus

**Comment by Yanfeng-Mi** [comment]
Hi @jgespino, yes, i think it's the same issue.

**Comment by jgespino** [comment]
@Yanfeng-Mi 

I opened an internal ticket with the development team to take a look, I'll let you know what I find out.

Regards,
Jesus

Ref. 75871

**Comment by asomsiko** [comment]
There is a test suite to catch memory growth. @jgespino, @Yanfeng-Mi would you be willing to contribute a test case there?

It should be a few lines of code, similar to this one: https://github.com/openvinotoolkit/openvino/blob/master/tests/stress_tests/memleaks_tests/tests.cpp#L38

**Comment by Yanfeng-Mi** [comment]
@vurusovs even if remove MYRIAD plugin, the leak still exists.

**Comment by Yanfeng-Mi** [comment]
Except myriad plugin, another culprit plugin is gpu which cause little memory growth.
According to my test, there will be 513KB memory increased after 3000 calling
![image](https://user-images.githubusercontent.com/62379311/150306500-0d6b591e-f623-4dca-90aa-067c7545619e.png)

**Comment by vurusovs** [comment]
@Yanfeng-Mi Thanks! 

Such behavior is more allocator/OS-specific than OpenVINO, so there is no way to fix it on OpenVINO side. You may try to use another allocator (e.g. jemalloc) to check the difference against default allocator
