### ISSUE TITLE
Can't convert efficentdet D4 tf2 saved_model.pb to IR

### ISSUE THREAD

**Issue by nevoGoldamn** [openvinotoolkit/openvino#9521]
##### System information (version)

- OpenVINO => 2021.4.752
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: Model Conversion
- Framework: TensorFlow 
- Model name: efficentdet d4

##### Detailed description
I have tried to convert efficentdet saved_model  and got an error.
I have tried to convert my custom model and the original model from tensorflow and still got an error.
Exception: Exception occurred during running replacer "ObjectDetectionAPIPreprocessor2Replacement (<class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIPreprocessor2Replacement'>)":

 assert len(start_nodes) >= 1
AssertionError

when I run my own model it outputs this error:
[ FRAMEWORK ERROR ]  Cannot load input model: SavedModel format load failure: Unknown SavedObject type: None

##### Steps to reproduce

I used this command.

python mo_tf.py --saved_model_dir C:\DATASETS\efficentdet\export\saved_model --transformations_config extensions\front\tf\efficient_det_support_api_v2.4.json --tensorflow_object_detection_api_pipeline_config C:\DATASETS\efficentdet\export\pipeline.config --log_level=DEBUG

**Comment by zulkifli-halim** [comment]
Hi @nevoGoldamn, I'm able to convert the EfficientDet D4 model from [TensorFlow 2 Detection Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md).
![image](https://user-images.githubusercontent.com/79680111/148479583-c604e725-011c-4bd1-b970-842911981c05.png)

The EfficientDet D4 model was trained using TensorFlow 2.2, thus efficient_det_support_api_v2.0.json is required to convert the model to IR.

**Comment by nevoGoldamn** [comment]
Hi @zulkifli-halim, can you shear the command that you used ?

What is that error mean ? [ FRAMEWORK ERROR ] Cannot load input model: SavedModel format load failure: Unknown SavedObject type: None

**Comment by zulkifli-halim** [comment]
Hi @nevoGoldamn here is the full MO command that I used to convert the model to IR:

_python mo_tf.py --saved_model_dir <download_path>\efficientdet_d4_coco17_tpu-32\saved_model --output_dir <output_path>  --transformations_config extensions\front\tf\efficient_det_support_api_v2.0.json --tensorflow_object_detection_api_pipeline_config <download_path>\efficientdet_d4_coco17_tpu-32\pipeline.config_

Can you share with us your custom model and where is the source of your model?

**Comment by dkurt** [comment]
There are two versions of EfficientDet: TensorFlow object detection API and [AutoML](https://github.com/google/automl). They require different approaches:

https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_EfficientDet_Models.html

https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html

**Comment by nevoGoldamn** [comment]
Hi, @zulkifli-halim I have changed the conversion command to yours and got an error:
 Exception occurred during running replacer "REPLACEMENT_ID"
(old shape: [  1 160  20  20], new shape: [  1  20  20 160])

**Comment by zulkifli-halim** [comment]
Hi @nevoGoldamn, Are you able to convert the model from TensorFlow 2 Detection Model Zoo using this MO command:
`python mo_tf.py --saved_model_dir <download_path>\efficientdet_d4_coco17_tpu-32\saved_model --output_dir <output_path> --transformations_config extensions\front\tf\efficient_det_support_api_v2.0.json --tensorflow_object_detection_api_pipeline_config <download_path>\efficientdet_d4_coco17_tpu-32\pipeline.config`

Also please share with us your custom model for replication purposes. If you cannot share it here, you can share the model with me personally via my email.

**Comment by zulkifli-halim** [comment]
Closing issue. Feel free to reopen the issue if further assistance is needed.

**Comment by macimovic** [comment]
Was able to reproduce on OpenVINO 2021.4 with a custom trained efficientdet_d1 using Tensorflow Object Detection API.
