### ISSUE TITLE
[QUESTION] [AVX512] Performance drop with alder lake ? 

### ISSUE THREAD

**Issue by hyperfraise** [openvinotoolkit/openvino#9527]
It seems now clear that there will be no support overall for avx 512 on Alder Lake.
That's a shame. What can we expect in terms of openvino performance ? Why would intel kill its own DNN software's advantage ? 
Do you guys have any hope or reassuring words ?

**Comment by hyperfraise** [comment]
After struggling to find official numbers I've found this link comparing AVX2 TO AVX512 on neural network in openvino, but its results don't correspond to my experience.
https://www.phoronix.com/scan.php?page=article&item=rocket-lake-avx512&num=3

Was the decision of dropping AVX512 in part justified by perceived lack of performance gain in Openvino ?

**Comment by alalek** [comment]
Do you have OpenVINO-related problem?
Could you share your results from benchmark_app (with information about used HW/SW configurations)?

> Intel® Gaussian & Neural Accelerator : 3.0
> Intel® Deep Learning Boost (Intel® DL Boost) : Yes

Ref: https://ark.intel.com/content/www/us/en/ark/products/134594/intel-core-i712700k-processor-25m-cache-up-to-5-00-ghz.html

> In addition to existing AVX and AVX2 instructions, Intel’s Alder Lake and Sapphire Rapids CPUs will support AVX-VNNI (vector neural network instructions) for deep learning that will complement AVX512-VNNI supported by Intel’s higher-end CPUs. 

Ref: https://www.tomshardware.com/news/intels-upcoming-gracemont-microarchitecture-to-support-avx-avx2-and-avx-vnni

**Comment by hyperfraise** [comment]
My Openvino related pronlem is that I fear that Intel 12th gen will bring a performance drop on Openvino due to the dropping of AVX 512 instructions set

**Comment by jgespino** [comment]
@hyperfraise We have published new [performance benchmarks](https://docs.openvino.ai/latest/openvino_docs_performance_benchmarks_openvino.html) that include 12th Gen Intel Core Processors.

**Comment by hyperfraise** [comment]
@jgespino 

Thanks for this. From the looks of it, the performance drop is **catastrophic**, don't you think ?

**Comment by hyperfraise** [comment]
I'm estimating a <3 fold performance drop in FPS / Userbenchmark multi core score.

**Comment by jgespino** [comment]
@hyperfraise 

Thank you for using our official OpenVINO™ Performance Benchmark web page as intended. We want to show how OpenVINO™ performs on different hardware platforms and have chosen to label these by using the installed CPU SKU as a differentiator. We’ve grouped the CPU SKUs according to processor family with Xeons as Server group, Cores as Client group and Atom/Celeron as Entry group. Within each of these groups we will obviously have high performers that are better than some of the lower performers in other groups, the Core i9-10920X is a Cascade Lake generation CPU that is labeled “Core” but performs on-par with lower end Xeon CPUs of the Cascade Lake generation. 

A closer analysis of the CPU specifications exposes these differences: Core i9-10920X sports two AVX-512 FMA units whereas Xeon Silver 4216R has one. However, Xeon 4216R supports running in a 2-socketed motherboard and supports up to 1 TB RAM on 6 memory channels versus the 256 GB RAM limit on 4 memory channels of the Core i9-10920X. Both CPUs support AVX512 (and AVX-VNNI / DL Boost Technology). Benchmarking is complex and has many moving parts that affect performance and this includes the supported instruction set extensions. Other notable performance influencers are physical CPU core count, supported memory speed and number of memory channels (more channels => more throughput) and CPU cache size. The presence of an on-die GPU will also boost performance as OpenVINO™ allows using multiple hardware inference engines in parallel.  The Alder Lake generation (for example Core i9-12900) supports AVX-VNNI (aka DL-Boost technology) which OpenVINO™ does take advantage of. 

Please check back on our official OpenVINO™ performance benchmark web site periodically for updates as we plan to include an Alder Lake CPU with on-die Iris Xe GPU in the next web page update.
