### ISSUE TITLE
[Bug]OpenVINO 2021.4.2LTS do NOT support PPYOLOv2 by GPU

### ISSUE THREAD

**Issue by dlod-openvino** [openvinotoolkit/openvino#9574]
- OpenVINO => 2021.4.2LTS
- Operating System / Platform => Windows 64 Bit
- Problem classification: Inference
- Framework: PaddlePaddle
- Model name: PPYOLOv2 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/ppyolo/README.md#Model_Zoo

Model for reproducing: https://pan.baidu.com/s/1oDpHgb5zm1bNFsWRs5kwQQ  code：s4qb

The PPYOLOv2 can run in CPU mode successfully!
However, run in GPU mode, it fail:
![PPYOLOv2 fail to run in GPU mode](https://user-images.githubusercontent.com/59691336/148943051-d55aeb3c-caed-45dd-88aa-22d1d8e8b257.png)

**Comment by jgespino** [comment]
Hi @dlod-openvino 

I was unable to download your model, received "External links do not support cloud decompression" error. However, I exported the `ppyolov2_r50vd_dcn_365e_coco.pdparams` to pdmodel format and converted to IR format with `mo --framework paddle --input_model model.pdmodel -b 1`.

 I ran the IR with the latest master branch using the benchmark_app on GPU and received the following error:

```
benchmark_app -m model.xml -d GPU
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] OpenVINO: OpenVINO Runtime version ......... 2022.1.0
[ INFO ] Build ........... custom_master_3e9ae4bea743628d21fed4ad0f1e0e760ca752cf
[ INFO ] 
[ INFO ] Device info: 
[ INFO ] GPU
[ INFO ] Intel GPU plugin version ......... 2022.1.0
[ INFO ] Build ........... custom_master_3e9ae4bea743628d21fed4ad0f1e0e760ca752cf
[ INFO ] 
[ INFO ] 
[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for GPU device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 158.92 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ WARNING ] scale_factor: layout is not set explicitly. It is STRONGLY recommended to set layout manually to avoid further issues.
[ WARNING ] image: layout is not set explicitly, so it is defaulted to NCHW. It is STRONGLY recommended to set layout manually to avoid further issues.
[ WARNING ] im_shape: layout is not set explicitly. It is STRONGLY recommended to set layout manually to avoid further issues.
[Step 6/11] Configuring input of the model
[ WARNING ] No batch dimension was found, asssuming batch to be 1. Beware: this might affect FPS calculation.
[ INFO ] Network batch size: 1
Network inputs:
    scale_factor : f32 / [...]
    image : u8 / [N,C,H,W]
    im_shape : f32 / [...]
Network outputs:
    save_infer_model/scale_0.tmp_1/Result : f32 / [...]
    save_infer_model/scale_1.tmp_1/Result : i32 / [...]
[Step 7/11] Loading the model to the device
[ ERROR ] Operation: matrix_nms_0.tmp_1 of type MatrixNms(op::v0) is not supported
```

I believe the model contains operations that are not supported by the GPU Plugin. Please take at the [supported devices](https://docs.openvino.ai/latest/openvino_docs_IE_DG_supported_plugins_Supported_Devices.html#supported-layers) documentation for additional information. 

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is required.
