### ISSUE TITLE
[Bug]Source compile. Can't find the direction ./deployment_tools, bin/setupvars.sh, Model Optimizer

### ISSUE THREAD

**Issue by leejinxi** [openvinotoolkit/openvino#9663]
##### System information (version)

- OpenVINO => release 2021.4.2
- Operating System / Platform => centos7
- Compiler => gcc7.8
- Problem classification: compile

##### Detailed description

I'm trying to compile openvino4.2+onnxruntime1.10 from source code.

1.  After I built openvino4.2 sucessfully, I can't find the file `openvino-4.2/bin/setupvars.sh`, which I found it from another path `/installing_path` , referenced [BuildingCode-Installing](https://github.com/openvinotoolkit/openvino/wiki/BuildingCode#installing).

> cmake --install . --prefix installing_path

2.  Also, I can't find the direction `./deployment_tools` either, which makes me confused, so that I can't configure the Model Optimizer.   if there is a way to download files such like `demo`, `model_optimizer` etc. under `./deployment_tools` ?

Thanks in advance!

**Comment by Iffa-Meah** [comment]
@leejinxi ,

You can clone the OpenVINO Open Model Zoo from this official repo: [open_model_zoo](https://github.com/openvinotoolkit/open_model_zoo)

Building from source won't include the OMZ and you'll need to clone the repo afterward.

This command (from the link you shared:[BuildingCode-Installing](https://github.com/openvinotoolkit/openvino/wiki/BuildingCode#installing)) would copy the open model zoo dir into deployment_tools : cmake -E copy_directory ./open_model_zoo/ <INSTALLDIR>/deployment_tools/open_model_zoo/

The Model Optimizer is not bound to be inside deployment_tools directory as occurs in the installation using Intel Distribution of OpenVINO Toolkit. The setup script for Model Optimizer should locate directly inside the cloned dir, eg: "/home/user/Downloads/openvino/model_optimizer/install_prerequisite".

You may refer to this: [Get Started with OpenVINO Toolkit on Linux](https://github.com/openvinotoolkit/openvino/wiki/GettingStarted)

**Comment by leejinxi** [comment]
@Iffa-Meah 
Thanks for your help, I have solved this problem.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
