### ISSUE TITLE
Confusion in OpenVINO docs

### ISSUE THREAD

**Issue by kiner-shah** [openvinotoolkit/openvino#969]
Hello,

I have two queries:

<h2>Query 1:</h1>

In the article titled [Introduction to Performance topics](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Intro_to_Performance.html) they have mentioned that,

_"Internally, the execution resources are split/pinned into execution 'streams'. "_

Here it is very unclear what these "execution streams" are - like are they some kind of software pipeline, or is it some load balancing mechanism or is it just a thread pool or what is it? 

<h2>Query 2:</h2>

I was reading this article titled [CPU Inference Performance Boost with Throughput mode in Intel distribtion of OpenVINO](https://www.intel.com/content/www/us/en/artificial-intelligence/posts/cpu-inference-performance-boost-openvino.html), there in the section titled **"Try your favorite model with the new throughput mode"** I noticed a line (say line 1):

 _"on an 8-core processor, compare the performance of the '-nireq 1' (which is a latency-oriented scenario with a single request) to the 2, 4 and 8 requests."_

 I remembered seeing a similar line in the document titled [Introduction to Performance topics](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Intro_to_Performance.html) in the **"Throughput mode"** section, but I noticed the line to be a bit different, here it is (say line 2):

 _"on a 8-core CPU, compare the -nstreams 1 (which is a latency-oriented scenario) to the 2, 4 and 8 requests."_

I was able to understand (line 1) very clearly - if on a 8-core machine, compare throughput when there are 1, 2, 4 and 8 inference requests. But, in (line 2) they have mentioned `-nstreams` and I am finding it difficult to correlate `-nstreams` and inference requests. I am trying to figure out how changing number of streams will affect the performance.

Please help me clear these confusions.

**Comment by myshevts** [comment]
Hi, 
the blog post (circa 2018) has not been updated when the benchmark_app was changed to separate #streams and #requests. 
Previously when we had the streams only on the CPU, it was a 1 to 1 mapping, so you have to specify just #requests (and the becnhamrk_app created the streams accordingly).
 Now you can specify different values (primarily for the GPU bow supporting streams as well, which can benefit from the 2 or more requests per stream).

Anyway, **summary is that today you can play #streams ("-nstreams") only, and required #requests will be created/executed automatically by the benchmark_app.**

Now on **what is (execution) stream**.  It is actually explained in the Optimization Guide which is referenced in the top of the [Introduction to Performance topics ](https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Intro_to_Performance.html) page:
![link](https://user-images.githubusercontent.com/7943168/84892833-f5049780-b0a6-11ea-87e0-3ed111d2bf9f.png)
Here are some details on the streams from the Opt Guide: https://docs.openvinotoolkit.org/latest/_docs_optimization_guide_dldt_optimization_guide.html#cpu-checklist
So streams are kind of "internal" instances, that run inference for multiple inputs simultaneously. E.g. this reduces the synchronization pressure within each instance and improves the cores utlilization if the amount of compute per input is small.

**Comment by kiner-shah** [comment]
@myshevts

Okay, I understand that **some no. of inference requests can be run simultaneously on some no. of streams to increase the throughput**.

Now I am trying to understand how is `-nstreams` different from `-nthreads`? 

My understanding for now is that:
- `nstreams` are for inference requests. It's similar to SIMD (Single Instruction Multiple Data) but on a coarser level.
- `nthreads` are for operations. Different model operations (most complex ones perhaps) are run on different threads.

Am I right in my understanding?

**Comment by myshevts** [comment]
Hi, streams are about splitting the machine between inference requests. 
But threads are somewhat more low-level and usually their number is not explicitly touched.
By default #threads (that OpenviNO creates for CPU inference) equals #(phys) cores, but you may want to specify different number.
E.g. on the 16 cores machine, you may want to use only half for inference via "-nthreads 8".

Then you may keep your 8 threads as 1 stream (which is default, latency-oriented scenario), or split  into 2 streams(4 cores each), 4 streams or even 8 (single-threaded) streams. this gives different trade-off between latency and throughput.

**Comment by kiner-shah** [comment]
@myshevts Thanks a lot for the explanation. 😃 It's very clear now! :+1:
