### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by dnns92** [openvinotoolkit/openvino#9766]
I have a couple of questions on the licensing file: https://github.com/openvinotoolkit/openvino/blob/2021.4/licensing/third-party-programs.txt

Let's say I just want to use the 2021.4 open-source openvino runtime: It's said here [openvino-docs](https://docs.openvino.ai/latest/openvino_docs_IE_DG_inference_engine_intro.html)  that we only need:
 - inference_engine.dll
 - inference_engine_transformations.dll
 - tbb.dll
 - tbbmalloc.dll
 - ngraph.dll

Also, for the cpu/gpu/hetero/multi plugins, we need:
- clDNNPlugin.dll
- MKLDNNPlugin.dll
- HeteroPlugin.dll
- MultiDevicePlugin.dll

The licensing file lists way more dependencies than I think are included in those DLLs. Can you tell me which 3rd-Party libraries openvino uses just in those DLLs when using the default build-options? Im sure e.g. gflags or google fonts are not used

**Comment by jgespino** [comment]
Hi @dnns92,

I am reaching out to my peers for input on this topic. I will let you know what I find out.

Regards,
Jesus 

Ref. 76554

**Comment by jgespino** [comment]
Hi @dnns92 

Apologies for the delay, we have updated the licensing files to separate them by runtime, dev tools, documentation and third party programs. Unfortunate, we don't have a separate license file for every binary. Please review the link below and let me know if you have any questions.

https://github.com/openvinotoolkit/openvino/tree/master/licensing

Regards,
Jesus

**Comment by jgespino** [comment]
Closing, please re-open if additional assistance is needed.
