### ISSUE TITLE
[Bug] Softmax is converted incorrectly

### ISSUE THREAD

**Issue by KodeWorker** [openvinotoolkit/openvino#9823]
##### System information (version)
- OpenVINO => 2021.4.752
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2022
- Problem classification: Model Conversion
- Framework: ONNX (from tf2onnx)
- Model name: Deeplab V3+

##### Detailed description

Inconsistant values while converting ONNX model to OpenVINO IR.

The values in the layer, resize_2/ResizeBilinear, is almost the same for both ONNX model and OpenVINO IR.
But the next layer (Softmax:0) in ONNX model is converted into serveral layers in OpenVINO IR.
We got incorrect values in the OpenVINO.

- ONNX model link: [GoogleDrive](https://drive.google.com/file/d/1RHieL8CccqfRZMou4vtSGDF5QBOTwrgD/view?usp=sharing)
- Converted IR model link:  [GoogleDrive](https://drive.google.com/file/d/1r41NV-fsvcWDSBtaoo7BN3EW12Cn0X8K/view?usp=sharing)

In the ONNX model, the Softmax layer will do softmax along the last axis (axis=-1 by default)
[ONNX Softmax Description](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Softmax)
![onnx](https://user-images.githubusercontent.com/24215149/150460787-6fffe4a8-c46b-4819-b932-aef24f0cb2c3.png)

In the OpenVINO IR (xml), the input shape (1x512x512x2) will be flatten (1x524288) and then do the softmax.
This results in very small values in the output layer, and the operation is innconsistent with Softmax in ONNX model.
![ir](https://user-images.githubusercontent.com/24215149/150460765-b1691e8e-df6d-4ee2-93e1-58b4d5467e34.png)

Are there any pointers to fix this problem?

##### Steps to reproduce
1. Download ONNX model from link
2. Convert the model using OpenVINO 2021.4.752
3. Investigate the model structure in Netron

**Comment by jgespino** [comment]
Hi @KodeWorker

I am unable to access your model. Could you check the sharing settings? If you need to keep them private, you can share them to the email listed on my profile. 

Regards,
Jesus

**Comment by KodeWorker** [comment]
Hi @jgespino,

Sorry for your inconvenience.
I have change the accesss setting to anyone who gets the link. Please let me know if model is still unaccessible.

B.R.,
Kelvin

**Comment by jgespino** [comment]
Hi @KodeWorker 

Thanks! I was able to download the files. My first question is how did you convert the model using 2021.4.2? I am getting the following error.

```
python3 /opt/intel/openvino_2021/deployment_tools/model_optimizer/mo.py --input_model Segmentation.onnx 

[ ERROR ]  The ExpandDims node ExpandDims has more than 1 input
[ ERROR ]  The ExpandDims node ExpandDims_1 has more than 1 input
[ ERROR ]  Cannot infer shapes or values for node "ExpandDims".
[ ERROR ]  Wrong number of inputs to the layer ExpandDims
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function ExpandDims.infer at 0x7faede87b0d0>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
```

I then tested on the latest master branch (6f60a7d8f098c7cf3195ba96d964a11bf1babe55) and converted without any issues. The shape size looks correct now, could you try building OpenVINO from source and let me know if it also works for you?

![image](https://user-images.githubusercontent.com/18014973/150845355-1c3cc447-3a58-45f1-89c7-070a3c989fc0.png)

Regards,
Jesus

**Comment by KodeWorker** [comment]
Hi @jgespino,

Sorry, I forgot to mention that ExpandDims error is caused by Unsqueeze layer, and I took ExpandDimsToUnsqueeze.py from this [pull request](https://github.com/openvinotoolkit/openvino/pull/8399) to pass the conversion.

I am still building OpenVINO. I will keep you updated once done the experiment.

B.R.,
Kelvin

**Comment by KodeWorker** [comment]
Hi @jgespino,

I have built OpenVINO ([6f60a7d](https://github.com/openvinotoolkit/openvino/commit/6f60a7d8f098c7cf3195ba96d964a11bf1babe55)) as docker image according to this [repo](https://github.com/openvinotoolkit/docker_ci/tree/master/dockerfiles/ubuntu18/build_custom).
The model can be converted with few lines of warnings.
The output shape of Softmax layer is correct. But I can not load model and get the values using latest release of OpenVINO (2021.4.752) We are still working on the inference code.


There are few other questions:

1. HUGE built image size
The docker images takes 40G HD space. Even if I cut out source code repo, it's still 14G.
Is it possible to further reduce the size of built OpenVINO?

2. How to build on Windows
Is there any instructions about building OpenVINO on Window 10?
I tried to build OpenVINO using following commands:
```
cd openvino
cmake --build . --config Release --target install
```
I did not find any openvino python modules in the installed directory.
Did I do something wrong?

B.R.,
Kelvin

**Comment by mszuyx** [comment]
Having the same issue here. 

I followed the instruction from [https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux](url)

So far I don't have any issue following the instructions and build the openvino's latest branch. But the model optimizer keeps saying that it can't find ngraph or python api. So I did what @KodeWorker suggested, I add the ExpandDimsToUnsqueeze.py from the github repo to the openvino installed by 2021 4.2LTS online distribution. 

The ExpandDimsToUnsqueeze.py  has an dependency "Pack" in line 23:
`from mo.front.Pack import Pack`

Running the mo.py yields the error:
**AssertionError: Attempt to access node <class 'mo.front.Pack.Pack'> that not in graph**

I wonder what is a good instruction on building openvino from source. Or maybe a quick hack on how to avoid 
**The ExpandDims node Unsqueeze_xxx has more than 1 input** error

**Comment by jgespino** [comment]
Hi @KodeWorker 

> The output shape of Softmax layer is correct. But I can not load model and get the values using latest release of OpenVINO (2021.4.752) We are still working on the inference code.

Since you converted the model with the MO from master branch you should also try running with the inference engine from master branch.

> HUGE built image size
The docker images takes 40G HD space. Even if I cut off source code repo, it's still 14G.
Is it possible to further reduce the size of built OpenVINO?

I'll need to look into the Docker built method, I haven't tried it recently. 

> How to build on Windows?
Built instructions for windows can be found [here](https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows).

> I did not find any openvino python modules in the installed directory.
You have to enable Python and point to the python library locations. 

Here are the commands I used when building in Linux, should be similar for Windows. 
```
git clone https://github.com/openvinotoolkit/openvino
cd openvino/
git submodule update --init --recursive
chmod +x install_build_dependencies.sh
./install_build_dependencies.sh
pip3 install cython
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 -DCMAKE_INSTALL_PREFIX=/opt/intel/openvino_master ..
make --jobs=$(nproc --all)
sudo make install
source /opt/intel/openvino_master/setupvars.sh
cd ../tools/mo
sudo -H pip3 install --upgrade pip
python3 -m pip install -r requirements.txt
sudo python3 setup.py install
mo --version
```

Regards,
Jesus

**Comment by jgespino** [comment]
@mszuyx Try using the inference engine from your built, see commands above how I built and installed. 

Additionally, install the benchmark_app and see if you get the same error message with the converted model.

Continuation from above commands:
```
cd ../benchmark_tool/
python3 -m pip install -r requirements.txt
sudo python3 setup.py install
benchmark_app --version
```

Regards,
Jesus

**Comment by mszuyx** [comment]
> @mszuyx Try using the inference engine from your built, see commands above how I built and installed.
> 
> Additionally, install the benchmark_app and see if you get the same error message with the converted model.
> 
> Continuation from above commands:
> 
> ```
> cd ../benchmark_tool/
> python3 -m pip install -r requirements.txt
> sudo python3 setup.py install
> benchmark_app --version
> ```
> 
> Regards, Jesus

Thx! Trying it rn!

Yu

**Comment by mszuyx** [comment]
@ Is python 3.6 a must? I changed the flag option to python 3.8 and got:

```
[ 90%] Built target ov_intel_gpu_graph
make: *** [Makefile:182: all] Error 2
```
when doing make --jobs=$(nproc --all)

**Comment by mszuyx** [comment]
@jgespino I followed the instruction you gave and it is now properly installed.
Running mo.py doesn't give me the The **ExpandDims node Unsqueeze_xxx has more than 1 input** error anymore!

But now I have a new one:
```
OpenVINO runtime version: 	custom_master_069b3839cec79d26eb4bf8ee90a3b7437f96c106
Model Optimizer version: 	custom_master_069b3839cec79d26eb4bf8ee90a3b7437f96c106
[ WARNING ]  The version checker doesn't support environment marker combination and it will be ignored:  python_version < "3.8" and sys_platform == "win32"
2022-01-27 15:34:29.819667: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[ ERROR ]  Error happened while importing openvino-telemetry module. It may happen due to unsatisfied requirements of that module. Please run requirements installation script once more.
Details on module importing failure: invalid syntax (<string>, line 1)
[ WARNING ]  
Detected not satisfied dependencies:
	mxnet: installed: 1.7.0, required: ~= 1.7.0.post2
	openvino-telemetry: package error, required: >= 2022.1.0

Please install required versions of components or use install_prerequisites script
/usr/local/lib/python3.8/dist-packages/openvino/tools/mo/install_prerequisites/install_prerequisites.sh
Note that install_prerequisites scripts may install additional components.
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check 'unknown_operators.empty()' failed at frontends/onnx/frontend/src/core/graph.cpp:136:
nGraph does not support the following ONNX operations: Trilu

[ ERROR ]  Traceback (most recent call last):
  File "/home/ros/openvino/tools/mo/openvino/tools/mo/main.py", line 508, in main
    ret_code = driver(argv)
  File "/home/ros/openvino/tools/mo/openvino/tools/mo/main.py", line 466, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/home/ros/openvino/tools/mo/openvino/tools/mo/main.py", line 371, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
  File "/usr/local/lib/python3.8/dist-packages/openvino/tools/mo/moc_frontend/pipeline.py", line 142, in moc_pipeline
    ngraph_function = moc_front_end.convert(input_model)
RuntimeError: Check 'unknown_operators.empty()' failed at frontends/onnx/frontend/src/core/graph.cpp:136:
nGraph does not support the following ONNX operations: Trilu


[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```
Is this an known issue / not yet implemented feature?

Thx!

**Comment by KodeWorker** [comment]
Hi @jgespino,

I'd checked the output values from both OpenVINO and ONNXRUNTIME

model outputs:
1. SemanticPredictions:0
2. SemanticProbPredictions:0

The values in output#1 from OpenVINO is the same as  those from ONNXRUNTIME.
The differences in output#2 between OpenVINO and ONNXRUNTIME are relatively small ( < 1e-5)

```
np.array_equal(vino_pred, onnx_pred) # -> True
np.allclose(vino_prob, onnx_prob, atol=1e-5, rtol=0) # -> True
np.allclose(vino_prob, onnx_prob, atol=1e-6, rtol=0) # -> False
```

It seems that model (Deeplab V3+ ONNX) conversion is no longer an issue on the latest master branch.
I'll close this issue and open a docker-related issue on [docker_ci](https://github.com/openvinotoolkit/docker_ci)

Thanks for your help.

@mszuyx 
The warning messages I got are somthing like:
```
[WARN] 2022-01-28T02:29:41z frontends/onnx/frontend/src/core/graph.cpp 79
Could not create an nGraph Constant for initializer 'const_empty_float__1533'. Constant with a 0 value was created, make sure connected input is optional.
Otherwise verify if the initializer contains a correct number of elements matching the initializer's shape.
Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at core/include/openvino/op/constant.hpp:50:
While validating node 'v0::Constant Constant_818 () -> (f32{})' with friendly_name 'Constant_818':
Did not get the expected number of literals for a constant of shape {} (got 0, expected 1).
```
I have no idea what the error/warning will do in your case 😥

I am closing this issue.
Feel free to leave comments/updating/reopen this thread.

**Comment by satpalsr** [comment]
Hey @jgespino. It takes forever to execute the commands. Isn't there a short way?
